export const definitions = [
  '"the raiders then spent three months harrying and burning the area"',
  '"the government is being mercilessly harried by a new lobby"',
];
export const synonyms = [
  "attack",
  "assail",
  "assault",
  "maraud",
  "ravage",
  "devastate",
  "plunder",
  "rob",
  "sack",
  "ransack",
  "raid",
  "pillage",
  "lay waste to",
  "despoil",
  "reave",
  "wreak havoc on",
  "depredate",
  "spoliate",
  "harass",
  "hound",
  "pressurize",
  "lean on",
  "keep on at",
  "go on at",
  "chivvy",
  "bedevil",
  "torment",
  "pester",
  "bother",
  "disturb",
  "worry",
  "annoy",
  "badger",
  "nag",
  "plague",
  "persecute",
  "molest",
  "harassed",
  "hard-pressed",
  "beleaguered",
  "agitated",
  "flustered",
  "bothered",
  "troubled",
  "distressed",
  "vexed",
  "beset",
  "hagridden",
  "hounded",
  "plagued",
  "tormented",
  "bring pressure to bear on",
  "put pressure on",
  "untroubled",
  "leave in peace",
];
