export const definitions = [
  '"long-lashed eyes"',
  '"they were all eager to get lashed and start their working week off with a hangover"',
  '"they lashed him repeatedly about the head"',
  '"waves lashed the coast"',
  '"the rain lashed against the car"',
  '"I could feel the wind lashing at me"',
  '"the cat was lashing its tail back and forth"',
  '"the cat\'s tail lashed furiously from side to side"',
  '"the hatch was securely lashed down"',
  '"he lashed the flag to the mast"',
];
export const synonyms = [
  "intoxicated",
  "inebriated",
  "drunken",
  "befuddled",
  "incapable",
  "tipsy",
  "under the influence",
  "maudlin",
  "blind drunk",
  "(as) drunk as a skunk",
  "sottish",
  "tippling",
  "toping",
  "sotted",
  "besotted",
  "foxed",
  "screwed",
  "crapulent",
  "crapulous",
  "inebriate",
  "bibulous",
  "the worse for drink",
  "dead drunk",
  "rolling drunk",
  "roaring drunk",
  "(as) drunk as a lord",
  "gin-soaked",
  "ebrious",
  "ebriose",
  "ebriate",
  "sober",
  "whip",
  "flog",
  "beat",
  "thrash",
  "horsewhip",
  "scourge",
  "birch",
  "switch",
  "flay",
  "belt",
  "strap",
  "cane",
  "leather",
  "strike",
  "hit",
  "clout",
  "batter",
  "welt",
  "hammer",
  "pummel",
  "belabor",
  "smite",
  "stripe",
  "flagellate",
  "pound",
  "batter",
  "buffet",
  "strike",
  "hit",
  "knock",
  "beat against",
  "dash against",
  "crash against",
  "smack against",
  "swish",
  "flick",
  "twitch",
  "switch",
  "whip",
  "wave",
  "wag",
  "fasten",
  "bind",
  "tie",
  "tie up",
  "tether",
  "hitch",
  "attach",
  "knot",
  "rope",
  "strap",
  "leash",
  "truss",
  "fetter",
  "secure",
  "chain",
  "pinion",
  "join",
  "connect",
  "couple",
  "make fast",
];
