export const definitions = [
  '"I was scared stiff"',
  '"the rapid questions were designed to scare her into blurting out the truth"',
  '"I don\'t think I scare easily"',
  '"gosh, that gave me a scare!"',
  '"recent food scares have made the public rightly sensitive to new, apparently untested technologies"',
  '"she has been given the all-clear after a breast cancer scare"',
];
export const synonyms = [
  "frighten",
  "panic",
  "terrify",
  "petrify",
  "make someone's hair stand on end",
  "make some's 's blood run cold",
  "chill some's 's blood",
  "startle",
  "alarm",
  "shock",
  "appall",
  "horrify",
  "intimidate",
  "daunt",
  "unnerve",
  "fright",
  "affright",
  "make afraid",
  "make fearful",
  "make nervous",
  "throw into a panic",
  "scare/frighten to death",
  "scare/frighten someone out of their wits",
  "scare stiff",
  "scare witless",
  "scare/frighten the living daylights out of",
  "scare/frighten the life out of",
  "scare the hell out of",
  "strike terror into",
  "fill with fear",
  "put the fear of God into",
  "make someone jump (out of their skin)",
  "give someone goose pimples",
  "send into a cold sweat",
  "make someone shake in their shoes",
  "give someone a fright",
  "give someone a turn",
  "reassure",
  "fright",
  "shock",
  "start",
  "turn",
  "jump",
];
