export const definitions = [
  '"I wasn\'t scared at all"',
  '"we\'re both scared of spiders"',
  '"I\'m scared stiff of flying"',
  '"I was scared that people were going to take pictures of me"',
  '"he\'s scared to come to you and ask for help"',
  '"I was scared stiff"',
  '"the rapid questions were designed to scare her into blurting out the truth"',
  '"I don\'t think I scare easily"',
];
export const synonyms = [
  "frightened",
  "afraid",
  "fearful",
  "nervous",
  "panicky",
  "agitated",
  "alarmed",
  "worried",
  "intimidated",
  "terrified",
  "petrified",
  "horrified",
  "panic-stricken",
  "terror-stricken",
  "terror-struck",
  "horror-stricken",
  "horror-struck",
  "frantic",
  "hysterical",
  "beside oneself",
  "shaky",
  "frit",
  "afeared",
  "affrighted",
  "scared stiff",
  "frightened/scared out of one's wits",
  "scared witless",
  "frightened/scared to death",
  "with one's heart in one's mouth",
  "shaking in one's shoes",
  "shaking like a leaf",
  "feart",
  "confident",
  "laid-back",
  "calm",
  "frighten",
  "panic",
  "terrify",
  "petrify",
  "make someone's hair stand on end",
  "make some's 's blood run cold",
  "chill some's 's blood",
  "startle",
  "alarm",
  "shock",
  "appall",
  "horrify",
  "intimidate",
  "daunt",
  "unnerve",
  "fright",
  "affright",
  "make afraid",
  "make fearful",
  "make nervous",
  "throw into a panic",
  "scare/frighten to death",
  "scare/frighten someone out of their wits",
  "scare stiff",
  "scare witless",
  "scare/frighten the living daylights out of",
  "scare/frighten the life out of",
  "scare the hell out of",
  "strike terror into",
  "fill with fear",
  "put the fear of God into",
  "make someone jump (out of their skin)",
  "give someone goose pimples",
  "send into a cold sweat",
  "make someone shake in their shoes",
  "give someone a fright",
  "give someone a turn",
  "reassure",
];
