export const definitions = [
  '"the widening schism between Church leaders and politicians"',
  '"the persistence of this group could produce schism within society"',
];
export const synonyms = [
  'division',
  'split',
  'rift',
  'breach',
  'rupture',
  'break',
  'separation',
  'severance',
  'estrangement',
  'alienation',
  'detachment',
  'chasm',
  'gulf',
  'discord',
  'disagreement',
  'dissension',
  'disunion',
  'scission',
  'withdrawal',
  'break',
  'breakaway',
  'separation',
  'severance',
  'apostasy',
  'leaving',
  'quitting',
  'split',
  'splitting',
  'disaffiliation',
  'resignation',
  'desertion',
  'defection',
  'pulling out',
  'dropping out',
  'joining',
  'unification',
];