export const definitions = [
  '"forward scouts reported that the enemy were massing at two points ahead"',
  '"a scout vehicle"',
  '"I returned from a lengthy scout around the area"',
  '"Brock slid the ball in from 14 yards to impress watching scouts"',
  '"a single-seater scout"',
  '"a scout leader"',
  "\"I've got nothing against Harrison—he's a good scout\"",
  '"I was sent to scout around for a place to park the camper"',
  '"we scouted for clues"',
  '"outriders went scouting for small settlements to loot"',
  '"American companies are keen to scout out business opportunities"',
  '"Johnson has been scouting for the Pirates"',
  '"he scouts the claim that the aristocrats cared much for the art treasures their ancestors had bought"',
];
export const synonyms = [
  "lookout",
  "outrider",
  "advance guard",
  "vanguard",
  "spy",
  "lookout man/woman",
  "avant-courier",
  "reconnaissance",
  "reconnoiter",
  "exploration",
  "search",
  "expedition",
  "talent spotter",
  "talent scout",
  "recruiter",
  "search",
  "look",
  "hunt",
  "cast around",
  "ferret (around)",
  "root around",
  "reconnoiter",
  "explore",
  "inspect",
  "investigate",
  "survey",
  "examine",
  "scan",
  "study",
  "observe",
  "take a look at",
  "make a reconnaissance of",
  "spy out",
  "make a survey of",
  "see how the land lies",
  "find out the lie of the land",
];
