export const definitions = [
  '"the treasures of the Orient"',
  '"the orient moon"',
  '"the fires are oriented in direct line with the midsummer sunset"',
  '"there are no street names that would enable her to orient herself"',
  '"magazines oriented to the business community"',
  '"market-oriented economic reforms"',
  '"we were oriented toward the building"',
  '"magazines oriented to the business community"',
  '"market-oriented economic reforms"',
];
export const synonyms = [
  "align",
  "place",
  "position",
  "put",
  "dispose",
  "situate",
  "set",
  "orientate",
  "feel one's way",
  "orientate",
  "get/find one's bearings",
  "get the lie of the land",
  "establish one's location",
  "aim",
  "direct",
  "slant",
  "angle",
  "pitch",
  "steer",
  "design",
  "intend",
  "orientate",
];
