export const definitions = [
  '"the name is Norse in origin"',
  '"the terminology has its origins in America"',
  '"a novel theory about the origin of oil"',
  '"a voice that betrays his Southern origins"',
  '"they will be asked about their ethnic origin"',
];
export const synonyms = [
  "beginning",
  "start",
  "origination",
  "genesis",
  "birth",
  "dawning",
  "dawn",
  "emergence",
  "inception",
  "launch",
  "creation",
  "birthplace",
  "cradle",
  "conception",
  "inauguration",
  "foundation",
  "outset",
  "source",
  "basis",
  "base",
  "cause",
  "root",
  "roots",
  "spring",
  "mainspring",
  "well head",
  "fountainhead",
  "fountain",
  "fount",
  "head",
  "seat",
  "seed",
  "germ",
  "fons et origo",
  "commencement",
  "wellspring",
  "radix",
  "derivation",
  "provenance",
  "etymology",
  "provenience",
  "early stages",
  "end",
  "conclusion",
  "termination",
  "descent",
  "ancestry",
  "parentage",
  "pedigree",
  "lineage",
  "line",
  "heritage",
  "birth",
  "extraction",
  "background",
  "family",
  "stock",
  "blood",
  "bloodline",
  "genealogy",
  "beginnings",
  "filiation",
  "line of descent",
  "stirps",
];
