export const definitions = [];
export const synonyms = [
  "entreaty",
  "plea",
  "appeal",
  "petition",
  "solicitation",
  "exhortation",
  "urge",
  "prayer",
  "invocation",
  "suit",
  "request",
  "application",
  "beseeching",
  "begging",
  "pleading",
  "obsecration",
  "imploration",
];
