export const definitions = [
  '"the eternal verities"',
  '"irrefutable, objective verity"',
];
export const synonyms = [
  'the truth',
  'gospel truth',
  'God\'s truth',
  'fact',
  'reality',
  'actuality',
  'factuality',
  'so',
  'the whole truth',
  'the naked truth',
  'the honest truth',
  'actual fact',
  'what actually/really happened',
  'the case',
  'a certainty',
  'a lie',
  'veracity',
  'truthfulness',
  'sincerity',
  'candor',
  'honesty',
  'genuineness',
  'gospel',
  'gospel truth',
  'accuracy',
  'correctness',
  'rightness',
  'validity',
  'factualness',
  'factuality',
  'authenticity',
  'fact',
  'certainty',
  'certitude',
  'law',
  'principle',
  'dishonesty',
  'falsity',
  'lie',
  'falsehood',
  'old wives\' tale',
];