export const definitions = [
  '"proposals for vetting large takeover bids"',
  '"each applicant will be vetted by police"',
];
export const synonyms = [
  "screen",
  "assess",
  "evaluate",
  "appraise",
  "weigh up",
  "examine",
  "look over",
  "review",
  "consider",
  "scrutinize",
  "study",
  "inspect",
  "investigate",
  "censor",
  "check",
  "redact",
  "check out",
  "check up on",
  "probe",
  "research",
  "look into",
  "delve into",
  "dig into",
  "search into",
];
