export const definitions = [
  '"I was struck by her beauty"',
  '"an area of outstanding natural beauty"',
  '"the artistry and beauty of football"',
  '"beauty treatment"',
  '"beauty products"',
  '"she was considered a great beauty in her youth"',
  '"he arrived with a blonde beauty on his arm"',
  '"the fish was a beauty, around 14 pounds"',
  '"the beauties of the Pennsylvania mountains"',
  '"the beauty of keeping cats is that they don\'t tie you down"',
];
export const synonyms = [
  'landmark',
  'monument',
  'spectacle',
  'scene',
  'view',
  'area',
  'landscape',
  'display',
  'show',
  'exhibition',
  'curiosity',
  'rarity',
  'marvel',
  'wonder',
  'splendor',
  'place of interest',
  'thing worth seeing',
  '(distinctive/prominent) feature',
  'attractiveness',
  'prettiness',
  'pleasingness',
  'comeliness',
  'allure',
  'allurement',
  'loveliness',
  'charm',
  'appeal',
  'heavenliness',
  'voluptuousness',
  'winsomeness',
  'grace',
  'elegance',
  'exquisiteness',
  'splendor',
  'magnificence',
  'grandeur',
  'impressiveness',
  'picturesqueness',
  'artistry',
  'decorativeness',
  'gorgeousness',
  'glamour',
  'irresistibility',
  'bonniness',
  'pulchritude',
  'good looks',
  'beauteousness',
  'ugliness',
  'belle',
  'vision',
  'charmer',
  'enchantress',
  'Venus',
  'goddess',
  'beauty queen',
  'picture',
  'seductress',
  'femme fatale',
  'beautiful woman',
  'English rose',
  'hag',
  'ugly woman',
  'advantage',
  'attraction',
  'strength',
  'benefit',
  'asset',
  'draw',
  'lure',
  'pull',
  'strong point',
  'boon',
  'blessing',
  'virtue',
  'merit',
  'selling point',
  'bonus',
  'plus',
  'good thing/point',
  'added extra',
  'drawback',
];
