export const definitions = [
  '"Miranda beckoned to Adam"',
  '"he beckoned Christopher over"',
  '"he beckoned Duncan to follow"',
  '"the going is tough and soft options beckon"',
];
export const synonyms = [
  'gesture',
  'signal',
  'wave',
  'gesticulate',
  'motion',
  'nod',
  'call',
  'make a gesture',
  'entice',
  'invite',
  'tempt',
  'coax',
  'lure',
  'charm',
  'attract',
  'draw',
  'pull (in)',
  'bring in',
  'call',
  'allure',
  'interest',
  'fascinate',
  'engage',
  'enchant',
  'captivate',
  'persuade',
  'induce',
  'catch the eye of',
];