export const definitions = [
  '"it is becoming clear that we are in a totally new situation"',
  '"they became angry"',
  '"the child will become an adult"',
  '"she wanted to become a doctor"',
  '"what would become of her now?"',
  '"the dress becomes her"',
  '"minor celebrity status did not become him"',
];
export const synonyms = [
  'transmute',
  'turn',
  'go',
  'merge',
  'blend',
  'change gradually',
  'grow',
  'get',
  'turn',
  'wax',
  'come to be',
  'get to be',
  'turn out to be',
  'turn into',
  'be appointed as',
  'be assigned as',
  'be nominated',
  'be elected as',
  'be made',
  'be transformed into',
  'be converted into',
  'change into',
  'transform into',
  'overtake',
  'befall',
  'betide',
  'happen to',
  'be the fate of',
  'be the lot of',
  'be visited on',
  'suit',
  'flatter',
  'set off',
  'enhance',
  'embellish',
  'ornament',
  'grace',
  'look good on',
  'look right on',
  'show to advantage',
  'go well with',
  'befit',
  'behoove',
  'suit',
  'be suitable to',
  'be fitting to',
];
