export const definitions = [
  '"the tourist beetled off"',
  '"his eyebrows beetled with irritation"',
  '"thick beetle brows"',
];
export const synonyms = [
  "coleopteran",
  "winged insect",
  "scurry",
  "scamper",
  "scuttle",
  "bustle",
  "hurry",
  "hasten",
  "rush",
  "race",
  "dash",
  "projecting",
  "protruding",
  "prominent",
  "overhanging",
  "bulging",
  "bulbous",
  "pendent",
  "sticking out",
  "jutting out",
  "standing out",
];
