export const definitions = [
  '"a tragedy befell his daughter"',
  '"she was to blame for anything that befell"',
];
export const synonyms = [
  'overtake',
  'come upon',
  'hit',
  'strike',
  'happen',
  'occur',
  'take place',
  'arise',
  'emerge',
  'come about',
  'transpire',
  'materialize',
  'appear',
  'make an appearance',
  'surface',
  'crop up',
  'ensue',
  'follow',
  'result',
  'supervene',
  'come to pass',
  'betide',
  'hap',
  'eventuate',
  'happen to',
  'fall upon',
  'be visited on',
  'chance to happen',
  'spring up',
  'present itself',
];