export const definitions = [
  '"my playing days had ended six years before"',
  '"it\'s never happened to me before"',
  '"they began trotting through the city with guards running before and behind"',
  '"they lived rough for four days before they were arrested"',
  '"it wasn\'t long before I dozed off"',
  '"they would die before they would cooperate with each other"',
  '"she had to rest before dinner"',
  '"the day before yesterday"',
  '"before the war"',
  '"Matilda stood before her, panting"',
  '"the patterns swam before her eyes"',
  '"he could be taken before a magistrate for punishment"',
  '"a fall in the number of cases brought before the courts"',
  '"a skilled warrior who places duty before all else"',
];
export const synonyms = [
  'previously',
  'earlier',
  'formerly',
  'hitherto',
  'heretofore',
  'before now',
  'before then',
  'until now',
  'until then',
  'up to now',
  'up to then',
  'in the past',
  'in days gone by',
  'prior to',
  'previous to',
  'preparatory to',
  'preliminary to',
  'in advance of',
  'ahead of',
  'earlier than',
  'in preparation for',
  'in anticipation of',
  'in expectation of',
  'leading up to',
  'on the eve of',
  'anterior to',
  'after',
  'in front of',
  'in the presence of',
  'in the sight of',
  'before the very eyes of',
  'under the nose of',
  'in front of',
  'in the presence of',
  'in the sight of',
  'before the very eyes of',
  'under the nose of',
  'above',
  'over',
  'in preference to',
  'rather than',
  'sooner than',
  'instead of',
];
