export const definitions = [
  '"poor little beggars"',
  '"by being soft to the unfortunate, we beggared ourselves"',
];
export const synonyms = [
  "tramp",
  "vagrant",
  "vagabond",
  "down-and-out",
  "derelict",
  "mendicant",
  "pauper",
  "hobo",
  "clochard",
  "beggarman",
  "beggarwoman",
  "homeless person",
  "poor person",
  "fellow",
  "thing",
  "individual",
  "soul",
  "character",
  "creature",
  "wretch",
  "person",
  "man",
  "woman",
  "boy",
  "girl",
  "wight",
  "impoverish",
  "bankrupt",
  "ruin",
  "wipe out",
  "break",
  "cripple",
  "bring someone to their knees",
  "pauperize",
  "make poor",
  "reduce to poverty",
  "reduce to penury",
  "reduce to destitution",
  "make bankrupt",
  "make destitute",
];
