export const definitions = [
  '"she begged me to say nothing to her father"',
  '"I must beg of you not to act impulsively"',
  '"I begged him for mercy"',
  '"he begged their forgiveness"',
  '""Don\'t leave me," she begged"',
  '"I will now beg leave to make some observations"',
  '"we beg to inform you that we are instructed to wait"',
  '"a young woman was begging in the street"',
  '"they had to beg for food"',
  '"a piece of bread that I begged from a farmer"',
];
export const synonyms = [
  "beseech",
  "entreat",
  "implore",
  "adjure",
  "ask",
  "request",
  "call on",
  "petition",
  "importune",
  "exhort",
  "enjoin",
  "press",
  "plead with",
  "appeal to",
  "pray to",
  "apply to",
  "obsecrate",
  "ask for",
  "request",
  "call for",
  "solicit",
  "seek",
  "look for",
  "impetrate",
  "plead for",
  "appeal for",
  "sue for",
  "press for",
  "ask for money",
  "solicit money",
  "seek charity",
  "seek alms",
  "lease",
  "hire",
  "take as a loan",
  "ask for the loan of",
  "receive as a loan",
  "use temporarily",
  "have temporarily",
  "lend",
];
