export const definitions = [
  '"it was beginning to snow"',
  '"she began by rewriting the syllabus"',
  '"theorists have just begun to address these complex questions"',
  '"she began a double life"',
  '"the ground campaign had begun"',
  '"the story begins with the death of her senile father"',
  '"the tour begins at the active Poas Volcano"',
  '"he began as a drummer"',
  '"Watts Lake began as a marine inlet"',
  '"words beginning with a vowel"',
  '"Picasso began on a great canvas"',
  '"\"I\'ve got to go to the hotel,\" she began"',
  '"rooms begin at $139"',
  '"circuitry that Karen could not begin to comprehend"',
];
export const synonyms = [
  'start',
  'set about',
  'go about',
  'launch into',
  'get down to',
  'take up',
  'turn one\'s hand to',
  'undertake',
  'tackle',
  'initiate',
  'institute',
  'inaugurate',
  'commence',
  'embark on',
  'set in motion',
  'get ahead with',
  'cease',
  'appear',
  'arise',
  'make an appearance',
  'crop up',
  'turn up',
  'surface',
  'emerge',
  'originate',
  'start',
  'develop',
  'unfold',
  'set in',
  'happen',
  'occur',
  'commence',
  'come to pass',
  'become apparent',
  'spring up',
  'come into existence',
  'come into being',
  'become established',
  'disappear',
  'open',
  'lead off',
  'get off the ground',
  'start',
  'start off',
  'go ahead',
  'commence',
  'get under way',
  'get going',
  'conclude',
  'finish',
];