export const definitions = [
  '"the botanical gardens were a wonder to behold"',
  '"behold your king!"',
];
export const synonyms = [
  'see',
  'observe',
  'view',
  'watch',
  'survey',
  'scan',
  'witness',
  'regard',
  'contemplate',
  'inspect',
  'eye',
  'catch sight of',
  'glimpse',
  'spot',
  'spy',
  'notice',
  'make out',
  'discern',
  'perceive',
  'mark',
  'remark',
  'consider',
  'espy',
  'descry',
  'look',
  'lo',
  'look at',
  'gaze at',
  'gaze upon',
  'stare at',
  'take note of',
  'pay attention to',
  'pay heed to',
  'ecce',
];