export const definitions = [
  '"they had assembled at his behest"',
  '"the slaughter of the male children at the behest of Herod"',
];
export const synonyms = [
  "instruction",
  "bidding",
  "request",
  "requirement",
  "wish",
  "desire",
  "command",
  "order",
  "decree",
  "edict",
  "rule",
  "ruling",
  "directive",
  "direction",
  "charge",
  "will",
  "dictate",
  "demand",
  "insistence",
  "injunction",
  "mandate",
  "precept",
  "rescript",
];
