export const definitions = [
  '"the railroadbrought many towns into being"',
  '"the single market came into being in 1993"',
  '"many factions remained in being"',
  '"holism promotes a unified way of being"',
  '"sometimes one aspect of our being has been developed at the expense of the others"',
  '"alien beings"',
  '"a rational being"',
];
export const synonyms = [
  'existence',
  'living',
  'life',
  'animation',
  'aliveness',
  'reality',
  'actuality',
  'lifeblood',
  'vital force',
  'entity',
  'esse',
  'animateness',
  'essential nature',
  'nonexistence',
  'actuality',
  'existing',
  'reality',
  'fact',
  'survival',
  'continuance',
  'continuation',
  'subsistence',
  'living',
  'quiddity',
  'esse',
  'nonexistence',
  'soul',
  'spirit',
  'nature',
  'essence',
  'substance',
  'entity',
  'psyche',
  'heart',
  'bosom',
  'breast',
  'core',
  'kernel',
  'marrow',
  'quiddity',
  'pneuma',
  'inner being',
  'inner self',
  'creature',
  'life form',
  'soul',
  'individual',
  'person',
  'personage',
  'human being',
  'human',
  'man',
  'woman',
  'life',
  'existence',
  'earthling',
  'living entity',
  'living thing',
  'living soul',
];
