export const definitions = [
  '"his lively, alert manner belied his years"',
  '"the notebooks belie Darwin\'s later recollection"',
];
export const synonyms = [
  "contradict",
  "give the lie to",
  "disprove",
  "debunk",
  "discredit",
  "explode",
  "controvert",
  "confute",
  "negative",
  "conceal",
  "cover",
  "disguise",
  "misrepresent",
  "falsify",
  "distort",
  "warp",
  "color",
  "be at odds with",
  "call into question",
  "show/prove to be false",
  "knock the bottom out of",
  "drive a coach and horses through",
  "put a spin on",
  "give a false idea of",
  "give a false account of",
  "reveal",
  "testify to",
];
