export const definitions = [
  '"the vehicle did not belong to him"',
  '"most of the credit belongs to Paul"',
  '"the race belonged completely to Ferguson"',
  '"they belong to garden and bridge clubs"',
  '"she is a stranger, and doesn\'t belong here"',
  '"you and me, we belong together"',
  '"young people are generally very anxious to belong"',
  '"learning to place the blame where it belongs"',
  '"bony fish: the vast majority of living fish belong here"',
];
export const synonyms = [
  "be owned by",
  "be the property of",
  "be the possession of",
  "be in the ownership of",
  "be held by",
  "be at the disposal of",
  "be in the hands of",
  "be a member of",
  "be in",
  "be included in",
  "be affiliated to",
  "be allied to",
  "be associated with",
  "be connected to",
  "be linked to",
  "be an adherent of",
  "fit in",
  "be suited to",
  "have a rightful place",
  "have a home",
  "be part of",
  "belonging",
  "associateship",
  "community",
  "integration",
  "clanship",
  "shirt",
  "cap",
  "cloth",
  "seat",
  "whip",
  "lie",
  "stand",
  "have a place",
  "be located",
  "be situated",
  "be found",
  "be included",
  "be classed",
  "be classified",
  "be categorized",
];
