export const definitions = ['"he was bemused by what was happening"'];
export const synonyms = [
  "bewildered",
  "confused",
  "puzzled",
  "perplexed",
  "baffled",
  "stumped",
  "mystified",
  "stupefied",
  "nonplussed",
  "muddled",
  "befuddled",
  "fuddled",
  "dumbfounded",
  "at sea",
  "at a loss",
  "at sixes and sevens",
  "disoriented",
  "disconcerted",
  "discomposed",
  "troubled",
  "discomfited",
  "unnerved",
  "shaken",
  "dazed",
  "stunned",
  "astonished",
  "astounded",
  "wildered",
  "mazed",
  "distracted",
  "thrown (off balance)",
  "taken aback",
  "shaken up",
];
