export const definitions = [
  '"the vessel had left its berth"',
  '"I\'ll sleep in the upper berth"',
  '"a four - berth caravan"',
  '"today\'s victory clinched a berth for the Orioles in the playoffs"',
  '"these modern ships can almost berth themselves"',
  '"the Dutch freighter berthed at the Brooklyn docks"',
];
export const synonyms = [
  "anchorage",
  "mooring",
  "docking site",
  "bunk",
  "bed",
  "bunk bed",
  "cot",
  "couch",
  "hammock",
  "cabin",
  "compartment",
  "billet",
  "sleeping quarters",
  "sleeping accommodation",
  "moor",
  "harbor",
  "tie up",
  "drop anchor",
  "be at anchor",
  "cast anchor",
  "dock",
  "moor",
  "land",
  "tie up",
  "make fast",
  "accommodate",
  "sleep",
  "put up",
  "house",
  "shelter",
  "lodge",
  "provide beds for",
];
