export const definitions = [
  '"the social problems that beset the inner city"',
  '"she was beset with self-doubt"',
  '"poverty is a besetting problem"',
  '"I was beset by clouds of flies"',
  '"the ship was beset by ice"',
  '"blades of grass beset with glistening drops of dew"',
];
export const synonyms = [
  "plague",
  "bedevil",
  "attack",
  "assail",
  "beleaguer",
  "afflict",
  "torment",
  "torture",
  "rack",
  "oppress",
  "trouble",
  "worry",
  "bother",
  "harass",
  "hound",
  "harry",
  "dog",
  "surround",
  "besiege",
  "hem in",
  "shut in",
  "box in",
  "encircle",
  "enclose",
  "fence in",
  "ring around",
];
