export const definitions = [
  '"consumers were warned to beware of faulty packaging"',
  '"Beware! Dangerous submerged rocks ahead"',
  '"we should beware the incompetence of legislators"',
];
export const synonyms = [
  'look out',
  'take care',
  'have a care',
  'fore',
  'ware',
  'be on your guard',
  'watch out',
  'mind out',
  'be wary',
  'be careful',
  'be cautious',
  'be on the lookout',
  'be on the alert',
  'keep your eyes open',
  'keep a sharp lookout',
  'be on the qui vive',
  'take heed',
  'take it slowly',
  'look where you\'re going',
  'tread carefully',
  'proceed with caution',
  'ignore',
];