export const definitions = [
  '"security measures are continually updated and improved"',
  '"the reporter promised to keep the viewers updated"',
  '"an update on recently published crime figures"',
];
export const synonyms = [
  "modernize",
  "renovate",
  "refurbish",
  "recondition",
  "overhaul",
  "re-equip",
  "improve",
  "better",
  "upgrade",
  "streamline",
  "rationalize",
  "reform",
  "revise",
  "correct",
  "amend",
  "bring up to date",
  "bring into the twenty-first century",
  "bring up to code",
  "brief",
  "inform",
  "fill in",
  "advise",
  "notify",
  "apprise",
  "refresh",
  "keep someone posted",
  "bring up to date",
  "report to",
  "give details to",
  "explain the situation to",
  "give information to",
  "give someone the latest information",
  "explain the circumstances to",
  "describe the state of affairs to",
  "keep someone informed",
  "keep someone briefed",
  "keep someone in the picture",
  "keep someone up to date",
];
