export const definitions = [
  '"follow the track uphill"',
  '"the journey is slightly uphill"',
  '"an uphill struggle to gain worldwide recognition"',
  '"he gave mountain biking clinics on handling steep uphills"',
];
export const synonyms = [
  "up",
  "upward",
  "skywards",
  "heavenwards",
  "toward a higher level",
  "to the top",
  "downward",
  "upward",
  "rising",
  "ascending",
  "climbing",
  "mounting",
  "acclivitous",
  "upsloping",
  "downhill",
  "arduous",
  "difficult",
  "hard",
  "tough",
  "taxing",
  "demanding",
  "exacting",
  "stiff",
  "formidable",
  "heavy",
  "exhausting",
  "tiring",
  "wearying",
  "wearisome",
  "fatiguing",
  "laborious",
  "grueling",
  "back-breaking",
  "murderous",
  "punishing",
  "burdensome",
  "onerous",
  "Herculean",
  "toilsome",
  "easy",
];
