export const definitions = [
  '"the uppermost windows"',
  '"her father was uppermost in her mind"',
];
export const synonyms = [
  "highest",
  "loftiest",
  "top",
  "topmost",
  "predominant",
  "to the fore",
  "foremost",
  "dominant",
  "preponderant",
  "principal",
  "leading",
  "greatest",
  "chief",
  "main",
  "paramount",
  "major",
  "furthest up",
  "most elevated",
  "most important",
  "of greatest importance",
];
