export const definitions = [
  '"the elephant\'s trunk is powerful enough to uproot trees"',
  '"a revolution is necessary to uproot the social order"',
  '"my father traveled constantly and uprooted his family several times"',
];
export const synonyms = [
  "pull up",
  "root out",
  "take out",
  "deracinate",
  "rip out/up",
  "tear up by the roots",
  "grub out/up",
  "plant",
  "eradicate",
  "get rid of",
  "eliminate",
  "root out",
  "weed out",
  "remove",
  "destroy",
  "put an end to",
  "do away with",
  "wipe out",
  "stamp out",
  "extirpate",
  "abolish",
  "extinguish",
  "establish",
];
