export const definitions = ['"a Mafia sachem"'];
export const synonyms = [
  "chief",
  "head",
  "principal",
  "director",
  "managing director",
  "MD",
  "CEO",
  "president",
  "chairman",
  "chairwoman",
  "controller",
  "director general",
  "senior official",
  "senior manager",
  "senior administrator",
  "chief executive officer",
  "leader",
  "chief",
  "boss",
  "controller",
  "master",
  "supervisor",
  "governor",
  "superintendent",
  "foreman",
  "forewoman",
  "headman",
  "commander",
  "captain",
  "director",
  "managing director",
  "manager",
  "principal",
  "headmaster",
  "headmistress",
  "president",
  "premier",
  "prime minister",
  "ruler",
  "chair",
  "chairman",
  "chairwoman",
  "chairperson",
  "CEO",
  "commanding officer",
  "chief executive",
  "head teacher",
  "chief executive officer",
  "subordinate",
];
