export const definitions = [
  '"the bed sagged in the middle"',
  '"he closed his eyes and sagged against the wall"',
  '"stockings that sagged at the knees"',
  '"exports are forging ahead while home sales sag"',
];
export const synonyms = [
  'sink',
  'subside',
  'slump',
  'crumple',
  'loll',
  'flop',
  'dip',
  'droop',
  'swag',
  'bulge',
  'bag',
  'curve down',
  'hang down',
  'dip',
  'droop',
  'swag',
  'bulge',
  'bag',
  'curve down',
  'hang down',
  'falter',
  'weaken',
  'languish',
  'flag',
  'fade',
  'wilt',
  'shrivel',
  'wither',
  'fail',
  'fall',
  'decline',
  'go down',
  'drop',
  'turn down',
  'decrease',
  'diminish',
  'reduce',
  'sink',
  'slump',
  'plummet',
  'fall off a cliff',
  'tumble',
  'drop/fall off',
];