export const definitions = [
  '"the next few years saw several appeals for sanity from top scientists"',
  '"I began to doubt my own sanity"',
];
export const synonyms = [
  "sense",
  "common sense",
  "wisdom",
  "prudence",
  "judiciousness",
  "practicality",
  "reasonableness",
  "rationality",
  "soundness",
  "sensibleness",
  "good sense",
  "insanity",
  "mental health",
  "balance",
  "stability",
  "reason",
  "rationality",
  "saneness",
  "lucidity",
  "lucidness",
  "sense",
  "senses",
  "wits",
  "normality",
  "right-mindedness",
  "soundness of mind",
  "mental faculties",
  "balance of mind",
  "insanity",
];
