export const definitions = [
  '"packs of savage dogs roamed the streets"',
  '"a savage attack on the government"',
  '"the decision was a savage blow for the town"',
  '"the mother of one of the victims has described his assailants as savages"',
  '"ewes savaged by marauding dogs"',
  '"Fowler savaged her in his next review"',
];
export const synonyms = [
  "ferocious",
  "fierce",
  "wild",
  "untamed",
  "undomesticated",
  "feral",
  "predatory",
  "ravening",
  "tame",
  "vicious",
  "brutal",
  "cruel",
  "sadistic",
  "ferocious",
  "fierce",
  "violent",
  "bloody",
  "murderous",
  "homicidal",
  "bloodthirsty",
  "bestial",
  "brutish",
  "barbaric",
  "barbarous",
  "merciless",
  "ruthless",
  "pitiless",
  "heartless",
  "inhuman",
  "harsh",
  "callous",
  "cold-blooded",
  "fell",
  "sanguinary",
  "blistering",
  "scathing",
  "searing",
  "stinging",
  "devastating",
  "mordant",
  "trenchant",
  "caustic",
  "cutting",
  "biting",
  "withering",
  "virulent",
  "vitriolic",
  "mild",
  "gentle",
  "severe",
  "crushing",
  "devastating",
  "crippling",
  "terrible",
  "awful",
  "dreadful",
  "dire",
  "catastrophic",
  "calamitous",
  "ruinous",
  "mortal",
  "lethal",
  "fatal",
  "primitive",
  "uncivilized",
  "unenlightened",
  "in a state of nature",
  "heathen",
  "wild",
  "barbarian",
  "barbarous",
  "barbaric",
  "rude",
  "civilized",
  "rugged",
  "rough",
  "wild",
  "inhospitable",
  "uninhabitable",
  "brute",
  "beast",
  "monster",
  "barbarian",
  "ogre",
  "demon",
  "sadist",
  "animal",
  "barbarian",
  "wild man",
  "primitive",
  "heathen",
  "cannibal",
  "wild woman",
  "maul",
  "attack",
  "lacerate",
  "claw",
  "bite",
  "mutilate",
  "mangle",
  "worry",
  "tear to pieces",
  "attack",
  "lambaste",
  "condemn",
  "flay",
  "shoot down",
  "pillory",
  "revile",
  "excoriate",
  "slash",
  "criticize severely",
  "praise",
  "commend",
  "applaud",
];
