export const definitions = [
  '"he hollers when he wants feeding"',
  '""I can\'t get down," she hollered"',
  '"I got his number, so you can holler at him when you get a chance"',
  '"the audience responded with whoops and hollers"',
  '"a lot of folks back in the holler don\'t want the government knowing nothing about them"',
];
export const synonyms = [
  "shout",
  "yell",
  "cry",
  "cry out",
  "call",
  "call out",
  "roar",
  "howl",
  "bellow",
  "bawl",
  "bark",
  "shriek",
  "scream",
  "screech",
  "bay",
  "wail",
  "whoop",
  "boom",
  "thunder",
  "raise one's voice",
  "vociferate",
  "call at the top of one's voice",
  "whisper",
  "shout",
  "cry",
  "yell",
  "roar",
  "howl",
  "bellow",
  "bawl",
  "shriek",
  "scream",
  "screech",
  "bay",
  "wail",
  "whoop",
  "vociferation",
  "whisper",
];
