export const definitions = [
  '"they paid homage to the great poet by reciting his famous poems"',
  '"a masterly work written in homage to Beethoven"',
  '"a man doing homage to his personal lord"',
];
export const synonyms = [
  "respect",
  "recognition",
  "admiration",
  "esteem",
  "adulation",
  "acclaim",
  "acclamation",
  "commendation",
  "honor",
  "reverence",
  "worship",
  "tribute",
  "acknowledgment",
  "eulogy",
  "accolade",
  "panegyric",
  "paean",
  "encomium",
  "salute",
  "laudation",
  "applaud",
  "praise",
  "commend",
  "extol",
  "celebrate",
  "commemorate",
  "glorify",
  "laud",
  "magnify",
  "sing the praises of",
  "take one's hat off to",
  "pay tribute to",
  "give recognition to",
  "speak highly of",
  "criticism",
  "criticize",
];
