export const definitions = [
  '"a modern hotel with a homely atmosphere"',
  '"homely pleasures"',
];
export const synonyms = [
  "unattractive",
  "plain",
  "unprepossessing",
  "unlovely",
  "ill-favored",
  "ugly",
  "plain-featured",
  "plain-looking",
  "plain as a pikestaff",
  "ordinary-looking",
  "attractive",
  "cozy",
  "home-like",
  "homey",
  "comfortable",
  "snug",
  "welcoming",
  "friendly",
  "congenial",
  "hospitable",
  "informal",
  "relaxed",
  "intimate",
  "warm",
  "pleasant",
  "cheerful",
  "down-home",
  "homestyle",
  "uncomfortable",
  "formal",
  "unsophisticated",
  "everyday",
  "ordinary",
  "domestic",
  "plain",
  "simple",
  "modest",
  "natural",
  "down-to-earth",
  "homespun",
  "folksy",
  "unrefined",
  "unpretentious",
  "unaffected",
  "unassuming",
  "sophisticated",
];
