export const definitions = [
  '"a homey atmosphere"',
  '"an idealized vision of traditional peasant life as simple and homey"',
];
export const synonyms = [
  "cozy",
  "home-like",
  "comfortable",
  "snug",
  "welcoming",
  "friendly",
  "congenial",
  "hospitable",
  "informal",
  "relaxed",
  "intimate",
  "warm",
  "pleasant",
  "cheerful",
  "homely",
  "down-home",
  "homestyle",
  "uncomfortable",
  "formal",
  "unsophisticated",
  "homely",
  "unrefined",
  "unpretentious",
  "ordinary",
  "plain",
  "simple",
  "modest",
  "down-to-earth",
  "homespun",
  "sophisticated",
];
