export const definitions = [
  '"the company\'s head honcho in the US"',
  '"the task at hand was to honcho an eighteen-wheeler to St. Louis"',
];
export const synonyms = [
  "chief",
  "head",
  "principal",
  "boss",
  "commander",
  "captain",
  "figurehead",
  "controller",
  "superior",
  "kingpin",
  "headman",
  "mover and shaker",
  "chairman",
  "chairwoman",
  "chairperson",
  "chair",
  "convener",
  "moderator",
  "director",
  "managing director",
  "MD",
  "manager",
  "superintendent",
  "supervisor",
  "overseer",
  "administrator",
  "employer",
  "master",
  "mistress",
  "foreman",
  "president",
  "premier",
  "governor",
  "ruler",
  "monarch",
  "king",
  "queen",
  "sovereign",
  "emperor",
  "tsar",
  "prince",
  "princess",
  "lord",
  "elder",
  "patriarch",
  "guru",
  "mentor",
  "authority",
  "lord and master",
  "follower",
  "supporter",
];
