export const definitions = [
  '"sweet honeyed pastries"',
  '"honeyed duck breast"',
  '"as the wine matures it becomes more honeyed"',
  '"the light gives a honeyed sheen to the barley and wheat"',
  '"he wooed her with honeyed words"',
];
export const synonyms = [
  "sweet",
  "sweet-sounding",
  "saccharine",
  "sugary",
  "pleasant",
  "agreeable",
  "flattering",
  "adulatory",
  "unctuous",
  "dulcet",
  "soothing",
  "soft",
  "mellow",
  "lyrical",
  "mellifluous",
  "harsh",
];
