export const definitions = [
  '"his portrait hangs in the place of honor"',
  '"you are an honor to our profession"',
  '"I must as a matter of honor avoid any taint of dishonesty"',
  '"she died defending her honor"',
  '"the great poet of whom it is my honor to speak tonight"',
  '"the highest military honors"',
  '"she passed with honors"',
  '"an honors degree in mathematics"',
  '"Kyle had the honor at the last hole"',
  '"they honore their parents in all they did"',
  '"talented writers were honored at a special ceremony"',
  '"make sure the franchisees honor the terms of the contract"',
  '"the bank informed him that the check would not be honored"',
];
export const synonyms = [
  "distinction",
  "privilege",
  "glory",
  "tribute",
  "kudos",
  "cachet",
  "prestige",
  "fame",
  "renown",
  "merit",
  "credit",
  "importance",
  "illustriousness",
  "notability",
  "respect",
  "esteem",
  "approbation",
  "disgrace",
  "integrity",
  "honorableness",
  "honesty",
  "uprightness",
  "ethics",
  "morals",
  "morality",
  "principle",
  "righteousness",
  "rectitude",
  "nobility",
  "high-mindedness",
  "right-mindedness",
  "virtue",
  "goodness",
  "decency",
  "probity",
  "scrupulousness",
  "worthiness",
  "worth",
  "fairness",
  "justness",
  "justice",
  "truthfulness",
  "trustworthiness",
  "reliability",
  "dependability",
  "faithfulness",
  "fidelity",
  "(high) principles",
  "noble-mindedness",
  "dishonor",
  "chastity",
  "virginity",
  "virtue",
  "maidenhood",
  "maidenhead",
  "purity",
  "innocence",
  "modesty",
  "immaculateness",
  "privilege",
  "pleasure",
  "pride",
  "satisfaction",
  "joy",
  "compliment",
  "favor",
  "source of pleasure",
  "source of pride",
  "shame",
  "accolade",
  "award",
  "reward",
  "prize",
  "decoration",
  "distinction",
  "order",
  "title",
  "medal",
  "ribbon",
  "star",
  "laurel",
  "bay",
  "palm",
  "laurel wreath",
  "esteem",
  "respect",
  "admire",
  "look up to",
  "appreciate",
  "value",
  "prize",
  "cherish",
  "reverence",
  "revere",
  "venerate",
  "worship",
  "hold in great respect",
  "hold in high esteem",
  "have a high regard for",
  "defer to",
  "think highly of",
  "dishonor",
  "applaud",
  "acclaim",
  "praise",
  "salute",
  "recognize",
  "celebrate",
  "commemorate",
  "commend",
  "glorify",
  "hail",
  "lionize",
  "exalt",
  "fete",
  "eulogize",
  "sing the praises of",
  "magnify",
  "laud",
  "panegyrize",
  "emblazon",
  "give credit to",
  "pay homage to",
  "pay tribute to",
  "show appreciation of",
  "give accolades to",
  "sing paeans to",
  "disgrace",
  "criticize",
  "fulfill",
  "observe",
  "keep",
  "discharge",
  "implement",
  "perform",
  "execute",
  "effect",
  "obey",
  "heed",
  "follow",
  "carry out",
  "carry through",
  "keep to",
  "live up to",
  "effectuate",
  "abide by",
  "adhere to",
  "comply with",
  "conform to",
  "act in accordance with",
  "be true to",
  "be faithful to",
  "disobey",
  "cash",
  "accept",
  "take",
  "clear",
  "pass",
  "encash",
  "convert into cash",
  "convert into money",
  "bounce",
];
