export const definitions = [
  '"This book has won all sorts of prizes. Hooray!"',
  '"hooray for getting up late on Sunday, and doing absolutely nothing"',
  '"Hooray George, promise you\'ll come back."',
  '"they gave us a loud hurrah as we went by"',
  '"we waved our swords and hurrahed"',
];
export const synonyms = [
  "farewell",
  "adieu",
  "au revoir",
  "ciao",
  "adios",
  "sayonara",
  "vale",
  "check you",
  "auf Wiedersehen",
  "hello",
  "whoop",
  "bravo",
  "hoot",
  "shout",
  "shriek",
  "hosanna",
  "alleluia",
  "acclaim",
  "acclamation",
  "shouting",
  "clamor",
  "applause",
  "clapping",
  "ovation",
  "laudation",
  "huzzah",
  "hurray",
  "boo",
  "acclaim",
  "praise",
  "applaud",
  "commend",
  "extol",
  "eulogize",
  "vaunt",
  "hymn",
  "lionize",
  "sing the praises of",
  "make much of",
  "glorify",
  "cheer",
  "salute",
  "exalt",
  "honor",
  "toast",
  "welcome",
  "cry up",
  "emblazon",
  "laud",
  "panegyrize",
  "rave about",
  "express approval of",
  "express admiration for",
  "pay tribute to",
  "speak highly of",
  "hurray",
  "pay homage to",
  "criticize",
  "condemn",
];
