export const definitions = [
  '"his hoarded treasure"',
  '"a year\'s worth of hoarded resentments and grudges"',
  '"thousands of antiques hoarded by a compulsive collector"',
  '"many of the boat people had hoarded rations"',
  '"he hoarded the memory in his heart"',
];
export const synonyms = [
  "store",
  "store up",
  "stockpile",
  "put aside",
  "put by",
  "put away",
  "lay by",
  "lay in",
  "lay up",
  "set aside",
  "stow away",
  "buy up",
  "cache",
  "amass",
  "pile up",
  "stack up",
  "collect",
  "save",
  "gather",
  "garner",
  "accumulate",
  "husband",
  "squirrel away",
  "stock up on",
  "heap up",
  "put to one side",
  "put away for a rainy day",
  "squander",
];
