export const definitions = [
  '"a basic four-chord harmonic sequence"',
  '"the resonant frequencies of the vibrations bear simple harmonic relationships to each other"',
  '"the response of any linear circuit can be found by superposing the responses to each harmonic component of the signal"',
  '"harmonic charts"',
  '"the fifth harmonic"',
];
export const synonyms = [
  'tuneful',
  'melodious',
  'melodic',
  'sweet-sounding',
  'pleasant-sounding',
  'mellifluous',
  'dulcet',
  'lyrical',
  'euphonious',
  'euphonic',
  'harmonizing',
  'polyphonic',
  'consonant',
  'canorous',
  'mellifluent',
  'sweet-toned',
  'symphonious',
  'discordant',
];