export const definitions = [
  '"children screamed in horror"',
  '"photographs showed the horror of the tragedy"',
  '"the horrors of civil war"',
  '"a horror movie"',
  '"to her horror she found that a thief had stolen the machine"',
  '"horrors, two buttons were missing!"',
  '"many have a horror of consulting a dictionary"',
  '"the mere thought of it gives me the horrors"',
  '"that little horror Zach was around"',
];
export const synonyms = [
  "terror",
  "fear",
  "fearfulness",
  "fright",
  "alarm",
  "panic",
  "dread",
  "trepidation",
  "fear and trembling",
  "delight",
  "awfulness",
  "frightfulness",
  "cruelty",
  "savagery",
  "gruesomeness",
  "ghastliness",
  "hideousness",
  "atrocity",
  "outrage",
  "crime",
  "barbarity",
  "dismay",
  "consternation",
  "perturbation",
  "alarm",
  "distress",
  "disgust",
  "outrage",
  "shock",
  "satisfaction",
  "hate",
  "detest",
  "loathe",
  "abhor",
  "abominate",
  "greatly dislike",
  "have a strong aversion to",
  "be unable to bear/stand",
  "love",
  "rascal",
  "devil",
  "imp",
  "monkey",
  "scamp",
  "scapegrace",
  "rapscallion",
];
