export const definitions = [
  '"he has a major weight problem and is not very mobile"',
  '"highly mobile international capital"',
  '"her mobile features working overtime to register shock and disapproval"',
  '"a cup of tea from the mobile canteen"',
  '"mobile army combat units"',
  '"the next generation of mobile networks"',
  '"a mobile device"',
  '"an increasingly mobile and polarized society"',
  '"brightly colored mobiles rotated from the ceiling"',
  '"the biggest growth area in games right now is in mobile"',
  '"snowmobile"',
];
export const synonyms = [
  "moving",
  "walking",
  "ambulant",
  "ambulatory",
  "lively",
  "sprightly",
  "spry",
  "energetic",
  "vigorous",
  "motile",
  "able to move",
  "able to move around",
  "immobile",
  "motionless",
  "inert",
  "expressive",
  "eloquent",
  "suggestive",
  "meaning",
  "speaking",
  "revealing",
  "telltale",
  "animated",
  "changing",
  "ever-changing",
  "expressionless",
  "traveling",
  "transportable",
  "transferable",
  "portable",
  "movable",
  "locomotive",
  "maneuverable",
  "itinerant",
  "peripatetic",
  "nomadic",
  "peregrine",
  "wandering",
  "roving",
  "rangy",
  "airborne",
  "mechanized",
  "motorized",
  "waterborne",
  "seaborne",
  "stationary",
  "adaptable",
  "flexible",
  "versatile",
  "changing",
  "fluid",
  "moving",
  "on the move",
  "adjustable",
  "transplantable",
  "static",
];
