export const definitions = [
  '"the pace of modern life"',
  '"modern U.S. history"',
  '"they do not have modern weapons"',
  '"modern German"',
  '"Matisse\'s contribution to modern art"',
];
export const synonyms = [
  "present-day",
  "contemporary",
  "present-time",
  "present",
  "current",
  "latter-day",
  "recent",
  "latest",
  "twenty-first-century",
  "past",
  "fashionable",
  "in fashion",
  "in",
  "in style",
  "up to date",
  "up to the minute",
  "trendsetting",
  "stylish",
  "voguish",
  "modish",
  "chic",
  "smart",
  "new",
  "newest",
  "newfangled",
  "new-fashioned",
  "fresh",
  "modernistic",
  "advanced",
  "progressive",
  "forward-looking",
  "à la mode",
  "in vogue",
  "all the rage",
  "the latest",
  "out of date",
  "old-fashioned",
];
