export const definitions = [
  '"I counted the money before putting it in my wallet"',
  '"he borrowed money to modernize the store"',
  '"a statement of all moneys paid into and out of the account"',
  '"the college is very short of money"',
  '"the main aim of a commercial organization is to make money"',
  '"she accepted the job at the public school since the money was better"',
  '"her aunt had married money"',
];
export const synonyms = [
  "cash",
  "hard cash",
  "ready money",
  "funds",
  "capital",
  "finances",
  "banknotes",
  "notes",
  "paper money",
  "coins",
  "change",
  "coin",
  "coinage",
  "silver",
  "copper",
  "currency",
  "legal tender",
  "sterling",
  "bills",
  "roll",
  "specie",
  "pelf",
  "the means",
  "the wherewithal",
  "(filthy) lucre",
  "l.s.d.",
  "wealth",
  "riches",
  "fortune",
  "affluence",
  "assets",
  "resources",
  "substance",
  "means",
  "deep pockets",
  "prosperity",
  "liquid assets",
  "pay",
  "salary",
  "wages",
  "remuneration",
  "fee",
  "stipend",
  "emolument",
];
