export const definitions = ['"she was morose and silent when she got home"'];
export const synonyms = [
  "sullen",
  "sulky",
  "gloomy",
  "bad-tempered",
  "ill-tempered",
  "dour",
  "surly",
  "sour",
  "glum",
  "moody",
  "unsmiling",
  "humorless",
  "uncommunicative",
  "taciturn",
  "unresponsive",
  "unsociable",
  "scowling",
  "glowering",
  "ill-humored",
  "somber",
  "sober",
  "saturnine",
  "pessimistic",
  "lugubrious",
  "Eeyorish",
  "mournful",
  "melancholy",
  "melancholic",
  "doleful",
  "miserable",
  "dismal",
  "depressed",
  "dejected",
  "despondent",
  "downcast",
  "unhappy",
  "low-spirited",
  "low",
  "blue",
  "down",
  "fed up",
  "grumpy",
  "irritable",
  "churlish",
  "cantankerous",
  "crotchety",
  "cross",
  "crabbed",
  "crabby",
  "grouchy",
  "testy",
  "snappish",
  "peevish",
  "crusty",
  "waspish",
  "in a bad mood",
  "in low spirits",
  "with a long face",
  "cheerful",
  "happy",
  "communicative",
];
