export const definitions = [
  '"all men are mortal"',
  '"the coffin held the mortal remains of her uncle"',
  '"a mortal disease"',
  '"he has struck a mortal blow to the security of society"',
  '"from the outbuildings came the screams of men in mortal combat"',
  '"a mortal foe"',
  '"parents live in mortal fear of children\'s diseases"',
  '"she had committed a mortal sin"',
  '"punishment out of all mortal proportion to the offense"',
  '"he was in a mortal hurry"',
  '"for three mortal days it rained"',
  '"capacities only possible of God rather than mortals"',
  '"an ambassador had to live in a style that was not expected of lesser mortals"',
];
export const synonyms = [
  "perishable",
  "physical",
  "bodily",
  "corporeal",
  "fleshly",
  "corporal",
  "earthly",
  "human",
  "impermanent",
  "temporal",
  "worldly",
  "transient",
  "ephemeral",
  "passing",
  "sublunary",
  "earth-born",
  "immortal",
  "perishable",
  "physical",
  "bodily",
  "corporeal",
  "fleshly",
  "corporal",
  "earthly",
  "human",
  "impermanent",
  "temporal",
  "worldly",
  "transient",
  "ephemeral",
  "passing",
  "sublunary",
  "earth-born",
  "immortal",
  "deadly",
  "fatal",
  "lethal",
  "death-dealing",
  "killing",
  "murderous",
  "destructive",
  "terminal",
  "incurable",
  "irreconcilable",
  "deadly",
  "to the death",
  "sworn",
  "bitter",
  "out-and-out",
  "implacable",
  "relentless",
  "unrelenting",
  "unappeasable",
  "remorseless",
  "merciless",
  "irreconcilable",
  "deadly",
  "to the death",
  "sworn",
  "bitter",
  "out-and-out",
  "implacable",
  "relentless",
  "unrelenting",
  "unappeasable",
  "remorseless",
  "merciless",
  "unpardonable",
  "unforgivable",
  "irremissible",
  "venial",
  "extreme",
  "great",
  "enormous",
  "terrible",
  "awful",
  "dreadful",
  "intense",
  "severe",
  "grave",
  "dire",
  "inordinate",
  "unbearable",
  "agonizing",
  "very great",
  "unpardonable",
  "unforgivable",
  "irremissible",
  "venial",
  "conceivable",
  "imaginable",
  "perceivable",
  "possible",
  "earthly",
  "human being",
  "human",
  "person",
  "being",
  "creature",
  "individual",
  "earthling",
  "man/woman",
  "immortal",
  "god",
];
