export const definitions = [
  '"the walls and vaults are decorated by marble and mosaic"',
  '"the mosaic shows the baptism of Christ"',
  '"a mosaic floor"',
  '"the bird\'s plumage was a mosaic of slate - gray, blue, and brown"',
  '"an incompetently constructed mosaic of competing interests"',
  '"he mosaicked the walls, ceilings, and floors"',
  '"the digital data were combined, or mosaicked, to delineate counties"',
];
export const synonyms = [
  "mixture",
  "blend",
  "medley",
  "melange",
  "miscellany",
  "mixed bag",
  "pot-pourri",
  "patchwork",
  "mix",
  "compound",
  "composite",
  "collection",
  "assortment",
  "conglomeration",
  "hotchpotch",
  "hodgepodge",
  "jumble",
  "ragbag",
  "mishmash",
  "farrago",
  "hash",
  "gallimaufry",
  "olio",
  "olla podrida",
  "salmagundi",
  "omnium gatherum",
  "macédoine",
  "motley",
  "motley collection",
];
