export const definitions = [
  '"its skin is mottled with brownish spots"',
  '"snow mottled the mountaintops ahead"',
  '"the ship was a mottle of khaki and black"',
  '"the mottles on a trout"',
  '"white marble with mottlings of black and gray"',
];
export const synonyms = [
  "spot",
  "mark",
  "stain",
  "dot",
  "speckle",
  "bespeckle",
  "freckle",
  "stipple",
  "stud",
  "blotch",
  "smudge",
  "streak",
  "splash",
  "spatter",
  "bespatter",
  "scatter",
  "sprinkle",
  "dirty",
  "soil",
  "besmirch",
  "smirch",
  "bestud",
];
