export const definitions = [];
export const synonyms = [
  "bumpkin",
  "country cousin",
  "rustic",
  "countryman",
  "countrywoman",
  "peasant",
  "provincial",
  "oaf",
  "lout",
  "boor",
  "barbarian",
  "paysan",
  "campesino",
  "contadino",
  "contadina",
  "paisano",
  "kulak",
  "fellah",
  "ryot",
  "carl",
  "churl",
  "hind",
  "kern",
  "bucolic",
  "country bumpkin",
  "country dweller",
  "son/daughter of the soil",
];
