export const definitions = [
  '"the offense of inciting racial hatred"',
  '"he incited loyal subjects to rebellion"',
];
export const synonyms = [
  'stir up',
  'whip up',
  'work up',
  'encourage',
  'fuel',
  'kindle',
  'ignite',
  'inflame',
  'stimulate',
  'instigate',
  'provoke',
  'excite',
  'arouse',
  'awaken',
  'waken',
  'inspire',
  'trigger',
  'ferment',
  'foment',
  'cause',
  'generate',
  'bring about',
  'enkindle',
  'urge',
  'goad',
  'push',
  'prod',
  'prompt',
  'induce',
  'impel',
  'motivate',
  'make',
  'influence',
  'rouse',
  'sting',
  'prick',
  'procure',
  'fan the flames of',
  'stoke up',
  'spark off',
  'agitate for/against',
  'egg on',
  'spur on',
  'drive on',
  'suppress',
  'dissuade',
  'deter',
  'persuade',
  'convince',
  'get',
  'make',
  'prompt',
  'move',
  'inspire',
  'instigate',
  'influence',
  'press',
  'urge',
  'encourage',
  'impel',
  'actuate',
  'motivate',
  'talk into',
  'procure',
  'prevail upon',
  'exert influence on',
  'coax into',
  'wheedle into',
  'cajole into',
  'prod into',
  'dissuade',
];