export const definitions = [
  '"type a paragraph of text and indent the first line"',
  '"a coastline indented by many fjords"',
  '"we were indenting for paper clips one by one in those days"',
  '"every indent in the coastline"',
  '"his chin was firm and slightly indented"',
];
export const synonyms = [
  "move to the right",
  "move further from the margin",
  "start in from the margin",
  "notch",
  "nick",
  "scallop",
  "serrate",
  "pink",
  "cut",
  "scratch",
  "gash",
  "slit",
  "snick",
  "gouge",
  "groove",
  "furrow",
  "dent",
  "mark",
  "score",
  "incise",
  "carve",
  "engrave",
  "deboss",
  "make an indentation in",
  "make notches/nicks in",
  "order",
  "requisition",
  "request",
  "ask for",
  "claim",
  "call for",
  "demand",
  "put in an order for",
  "apply for",
  "put in for",
  "put in a request for",
  "put in a claim for",
  "order",
  "requisition",
  "request",
  "call",
  "application",
  "claim",
  "demand",
  "summons",
  "purchase order",
];
