export const definitions = [
  '"it is possible to infer a trend from the figures"',
  '"from these facts we can infer that crime has been increasing"',
];
export const synonyms = [
  "deduce",
  "reason",
  "work out",
  "conclude",
  "conjecture",
  "surmise",
  "theorize",
  "hypothesize",
  "gather",
  "understand",
  "presume",
  "assume",
  "take it",
  "glean",
  "extrapolate",
  "reckon",
  "read between the lines",
  "figure",
  "collect",
  "come to the conclusion",
  "draw the inference",
  "come to understand",
];
