export const definitions = [
  '"the house is infested with cockroaches"',
  '"shark-infested waters"',
];
export const synonyms = [
  "overrun",
  "take over",
  "overspread",
  "invade",
  "penetrate",
  "infiltrate",
  "pervade",
  "permeate",
  "inundate",
  "overwhelm",
  "beset",
  "pester",
  "plague",
  "swarming",
  "teeming",
  "crawling",
  "bristling",
  "alive",
  "ridden",
  "infiltrated",
  "permeated",
  "plagued",
  "spread through",
  "swarm over",
  "crawl over",
  "run riot over",
  "vermined",
];
