export const definitions = [
  '"there is no evidence that the virus can infect humans"',
  '"the water was infected by cholera"',
  '"viruses have infected computer networks"',
  '"the panic in his voice infected her"',
];
export const synonyms = [
  "contaminate",
  "pass infection to",
  "transmit infection to",
  "spread disease to",
  "cause infection in",
  "cause disease in",
  "contaminate",
  "pollute",
  "taint",
  "foul",
  "dirty",
  "blight",
  "spoil",
  "mar",
  "impair",
  "damage",
  "ruin",
  "poison",
  "vitiate",
  "make impure",
  "radioactivate",
  "purify",
  "disinfect",
  "affect",
  "influence",
  "touch",
  "excite",
  "inspire",
  "stimulate",
  "animate",
  "have an effect on",
  "have an impact on",
  "impact on",
  "take hold of",
];
