export const definitions = [
  '"he wrote to her, informing her of the situation"',
  '"they were informed that no risk was involved"',
  '"the role of television is to inform and entertain"',
  '"people called a confidential hotline to inform on friends, neighbors, and family members"',
  '"the relationship of the citizen to the state is informed by the democratic ideal"',
];
export const synonyms = [
  'tell',
  'let someone know',
  'notify',
  'apprise',
  'advise',
  'brief',
  'prime',
  'enlighten',
  'announce to',
  'impart to',
  'communicate to',
  'send word to',
  'keep posted',
  'denounce',
  'give away',
  'betray',
  'incriminate',
  'inculpate',
  'report',
  'double-cross',
  'sell out',
  'delate',
  'tell the authorities/police about',
  'stab in the back',
  'be a Judas to',
  'give someone a Judas kiss',
  'turn Queen\'s / King\'s evidence',
  'suffuse',
  'pervade',
  'permeate',
  'infuse',
  'imbue',
  'saturate',
  'illuminate',
  'animate',
  'characterize',
  'typify',
];