export const definitions = [
  '"they were taken to the hospital after inhaling fumes"',
  '"she inhaled deeply on another cigarette"',
  '"later on I inhaled a box of chocolate cookies while watching cable TV"',
];
export const synonyms = [
  "draw in",
  "suck in",
  "gasp",
  "gulp",
  "inspire",
  "drink in",
  "inbreathe",
  "breathe in",
  "sniff in",
  "exhale",
  "expire",
  "consume",
  "devour",
  "ingest",
  "cram down",
  "finish (off)",
  "swallow",
  "chew",
  "munch",
  "chomp",
  "champ",
  "ingurgitate",
  "partake of",
  "gobble (up/down)",
  "gulp (down)",
  "bolt (down)",
  "wolf (down)",
  "starve",
  "fast",
];
