export const definitions = [
  '"the doctor injected a painkilling drug"',
  '"he injected himself with a drug overdose"',
  '"people who want to stop injecting"',
  '"inject the foam and allow it to expand"',
  '"she tried to inject scorn into her tone"',
  '"he injected his voice with a confidence he didn\'t feel"',
  '"many meteoroids are injected into hyperbolic orbits"',
];
export const synonyms = [
  "administer",
  "introduce",
  "inoculate",
  "vaccinate",
  "administer a drug to",
  "administer",
  "introduce",
  "inoculate",
  "vaccinate",
  "administer a drug to",
  "administer",
  "introduce",
  "inoculate",
  "vaccinate",
  "administer a drug to",
  "insert",
  "introduce",
  "place",
  "push",
  "force",
  "drive",
  "shoot",
  "feed",
  "introduce",
  "instil",
  "bring in",
  "infuse",
  "imbue",
  "inculcate",
  "breathe",
  "introduce",
  "instil",
  "bring in",
  "infuse",
  "imbue",
  "inculcate",
  "breathe",
];
