export const definitions = ['"her innate capacity for organization"'];
export const synonyms = [
  "inborn",
  "natural",
  "inbred",
  "congenital",
  "inherent",
  "intrinsic",
  "instinctive",
  "intuitive",
  "spontaneous",
  "unlearned",
  "untaught",
  "hereditary",
  "inherited",
  "quintessential",
  "organic",
  "essential",
  "basic",
  "fundamental",
  "constitutional",
  "built-in",
  "inbuilt",
  "ingrown",
  "deep-rooted",
  "deep-seated",
  "connate",
  "connatural",
  "in the blood",
  "in the family",
  "acquired",
];
