export const definitions = [
  '"an important way to make inroads in reducing spending"',
  '"serious inroads had now been made into my pitiful cash reserves"',
];
export const synonyms = [
  "occupy",
  "conquer",
  "capture",
  "seize",
  "take (over)",
  "annex",
  "win",
  "gain",
  "secure",
  "overrun",
  "overwhelm",
  "storm",
  "attack",
  "assail",
  "assault",
  "raid",
  "plunder",
  "maraud",
  "march into",
  "descend on",
  "swoop on",
  "swarm over",
  "surge over",
  "make inroads on",
  "withdraw from",
  "charge",
  "sortie",
  "foray",
  "thrust",
  "drive",
  "offensive",
  "attack",
  "raid",
  "assault",
  "descent",
  "blitz",
  "incursion",
  "invasion",
  "onset",
  "onslaught",
  "rush",
  "onrush",
  "blitzkrieg",
  "razzia",
];
