export const definitions = [
  '"she ran a finger around the inside of the bowl"',
  '"he was blocked on the inside at the furlong marker"',
  '"the inside of the bend"',
  '"the inside of the car was like an oven"',
  '"these boats are built of very thin cedar, with ribs on the inside"',
  '"my insides are out of order"',
  '"will you be my spy on the inside?"',
  '"an inside pocket"',
  '"possibly the best inside linebacker in the country"',
  '"an inside pitch to a right-handed hitter"',
  '"a radio was playing inside the apartment"',
  '"Anatoly reached inside his shirt and brought out a map"',
  '"she felt a stirring of life inside her"',
  '"I just roll the phrases around inside my head"',
  '"he went inside Graves and scored near the post"',
  '"the oven will have paid for itself inside 18 months"',
  '"Mr. Jackson is waiting for you inside"',
  '"we walked inside"',
  '"I was screaming inside"',
  '"she was sentenced to three years inside"',
  '"he does an excellent job of getting the ball inside to Randall"',
];
export const synonyms = [
  'interior',
  'center',
  'core',
  'middle',
  'heart',
  'nucleus',
  'inner part',
  'inner side',
  'inner surface',
  'outside',
  'exterior',
  'stomach',
  'gut',
  'bowels',
  'intestines',
  'viscera',
  'entrails',
  'internal organs',
  'inner',
  'interior',
  'internal',
  'inmost',
  'innermost',
  'on the inside',
  'outer',
  'within',
  'in the middle of',
  'within the bounds/confines of',
  'surrounded by',
  'enclosed by',
  'outside',
  'indoors',
  'within',
  'in',
  'into the interior',
  'into the house',
  'into the building',
  'into the room',
  'outside',
  'inwardly',
  'within',
  'secretly',
  'privately',
  'at heart',
  'emotionally',
  'intuitively',
  'instinctively',
  'deep down',
  'in one\'s heart',
  'in \'s \'s mind',
  'outwardly',
  'under lock and key',
  'imprisoned',
  'incarcerated',
  'in prison',
  'in jail',
  'in custody',
  'locked up',
];