export const definitions = [
  '"we\'re planning to install a new shower"',
  '"you may want to install a new version of the program"',
  '"he was installed as music director at the Cathedral of St. Barbara in Cracow"',
  '"Ashley installed herself behind her table"',
];
export const synonyms = [
  'put',
  'position',
  'place',
  'fix',
  'fit',
  'locate',
  'situate',
  'station',
  'site',
  'lodge',
  'establish',
  'insert',
  'put in place',
  'set in place',
  'remove',
  'swear in',
  'induct',
  'instate',
  'inaugurate',
  'invest',
  'institute',
  'introduce',
  'appoint',
  'take on',
  'ordain',
  'consecrate',
  'anoint',
  'enthrone',
  'crown',
  'admit to office',
  'remove',
  'ensconce',
  'establish',
  'position',
  'settle',
  'seat',
  'lodge',
  'plant',
  'plump',
  'sit',
  'sit down',
  'take a seat',
  'perch',
  'take a chair',
];