export const definitions = [
  '"the church was almost in ruins but its tower remained intact"',
];
export const synonyms = [
  "whole",
  "entire",
  "complete",
  "unbroken",
  "undamaged",
  "unharmed",
  "uninjured",
  "unimpaired",
  "unflawed",
  "faultless",
  "flawless",
  "unscathed",
  "untouched",
  "unspoiled",
  "unblemished",
  "unmarked",
  "perfect",
  "pristine",
  "inviolate",
  "unviolated",
  "undefiled",
  "unsullied",
  "in one piece",
  "sound",
  "solid",
  "scatheless",
  "unmutilated",
  "unsevered",
  "unmarred",
  "broken",
  "damaged",
];
