export const definitions = [
  '"the company intends to cut about 4,500 jobs"',
  '"it is intended that coverage shall be worldwide"',
  '"a series of questions intended as a checklist"',
  '"no offense was intended, I assure you"',
  '"this one-roomed cottage was intended to accommodate a family"',
  '"pigs intended for human consumption"',
  '"this benefit is intended for people incapable of work"',
  '"a jigsaw puzzle intended for three-year-olds"',
];
export const synonyms = [
  'plan',
  'mean',
  'aim',
  'propose',
  'aspire',
  'hope',
  'expect',
  'purpose',
  'desire',
  'want',
  'wish',
  'contemplate',
  'think of',
  'envisage',
  'design',
  'earmark',
  'set apart',
  'have the/every intention',
  'have in mind',
  'have in view',
  'have plans',
  'be looking',
  'be going',
  'be resolved',
  'have resolved',
  'be determined',
  'have set out',
  'be plotting',
  'plan',
  'mean',
  'aim',
  'propose',
  'aspire',
  'hope',
  'expect',
  'purpose',
  'desire',
  'want',
  'wish',
  'contemplate',
  'think of',
  'envisage',
  'design',
  'earmark',
  'set apart',
  'have the/every intention',
  'have in mind',
  'have in view',
  'have plans',
  'be looking',
  'be going',
  'be resolved',
  'have resolved',
  'be determined',
  'have set out',
  'be plotting',
  'plan',
  'mean',
  'aim',
  'propose',
  'aspire',
  'hope',
  'expect',
  'purpose',
  'desire',
  'want',
  'wish',
  'contemplate',
  'think of',
  'envisage',
  'design',
  'earmark',
  'set apart',
  'have the/every intention',
  'have in mind',
  'have in view',
  'have plans',
  'be looking',
  'be going',
  'be resolved',
  'have resolved',
  'be determined',
  'have set out',
  'be plotting',
  'plan',
  'mean',
  'aim',
  'propose',
  'aspire',
  'hope',
  'expect',
  'purpose',
  'desire',
  'want',
  'wish',
  'contemplate',
  'think of',
  'envisage',
  'design',
  'earmark',
  'set apart',
  'have the/every intention',
  'have in mind',
  'have in view',
  'have plans',
  'be looking',
  'be going',
  'be resolved',
  'have resolved',
  'be determined',
  'have set out',
  'be plotting',
  'plan',
  'mean',
  'aim',
  'propose',
  'aspire',
  'hope',
  'expect',
  'purpose',
  'desire',
  'want',
  'wish',
  'contemplate',
  'think of',
  'envisage',
  'design',
  'earmark',
  'set apart',
  'have the/every intention',
  'have in mind',
  'have in view',
  'have plans',
  'be looking',
  'be going',
  'be resolved',
  'have resolved',
  'be determined',
  'have set out',
  'be plotting',
];