export const definitions = [
  '"he invented an improved form of the steam engine"',
  '"I did not have to invent any tales about my past"',
];
export const synonyms = [
  'originate',
  'create',
  'innovate',
  'design',
  'devise',
  'contrive',
  'formulate',
  'develop',
  'conceive',
  'think up',
  'come up with',
  'hit on',
  'mastermind',
  'pioneer',
  'discover',
  'find',
  'coin',
  'mint',
  'make up',
  'fabricate',
  'concoct',
  'hatch',
  'dream up',
  'trump up',
  'manufacture',
];