export const definitions = [
  '"we were invited to a dinner at the Embassy"',
  '"she invited Patrick to sit down"',
  '"applications are invited for the post of Director"',
  '"his use of the word did little but invite criticism"',
  '"no one turns down an invite to one of Mickey\'s parties"',
];
export const synonyms = [
  "ask",
  "bid",
  "summon",
  "request someone's company at",
  "request some's 's presence at",
  "request some's 's appearance at",
  "request the pleasure of some's 's company",
  "have someone over",
  "ask for",
  "request",
  "call for",
  "look for",
  "solicit",
  "seek",
  "petition",
  "summon",
  "appeal for",
  "refuse",
  "cause",
  "induce",
  "provoke",
  "create",
  "generate",
  "engender",
  "foster",
  "encourage",
  "call forth",
  "draw",
  "attract",
  "incite",
  "elicit",
  "bring on",
  "arouse",
  "tempt",
  "court",
  "allure",
  "entice",
  "lead to",
  "make happen",
  "bring on oneself",
  "invitation",
  "request",
  "call",
  "bidding",
  "summons",
];
