export const definitions = [
  '"children excitedly unwrapping and playing with their new presents"',
];
export const synonyms = [
  "unfasten",
  "unbutton",
  "unhook",
  "untie",
  "unlace",
  "unbind",
  "unfetter",
  "unshackle",
  "unbridle",
  "unlock",
  "unbolt",
  "uncouple",
  "unhitch",
  "unlink",
  "unclick",
  "loosen",
  "loose",
  "disentangle",
  "extricate",
  "release",
  "detach",
  "free",
  "liberate",
  "open",
  "unseal",
  "let out",
  "disconnect",
  "disjoin",
  "disengage",
  "disunite",
  "separate",
  "unmanacle",
  "disentwine",
  "set free",
  "fasten",
  "do up",
];
