export const definitions = [
  '"she waited for the lion\'s roar"',
  '"he gave a roar of rage"',
  '"her remarks brought a roar of laughter from the old man"',
  '"the roar of the sea"',
  '"we heard a lion roar"',
  '"Manny roared with rage"',
  '"a huge fire roared in the grate"',
  '"the crowd roared its approval"',
  '"\"Get out of my way!\" he roared"',
  '"Shirley roared in amusement"',
  '"a car roared past"',
  '"the Clippers came roaring back to outscore the Nets"',
];
export const synonyms = [
  'shout',
  'bellow',
  'yell',
  'cry',
  'howl',
  'shriek',
  'scream',
  'screech',
  'clamor',
  'clamoring',
  'vociferation',
  'ululation',
  'whisper',
  'guffaw',
  'howl',
  'hoot',
  'shriek',
  'gale',
  'peal',
  'boom',
  'booming',
  'crash',
  'crashing',
  'rumble',
  'rumbling',
  'roll',
  'thundering',
  'peal',
  'crack',
  'clap',
  'thunderclap',
  'loud noise',
  'bellow',
  'yell',
  'shout',
  'bawl',
  'howl',
  'cry',
  'shriek',
  'scream',
  'screech',
  'vociferate',
  'ululate',
  'whisper',
  'boom',
  'rumble',
  'crash',
  'roll',
  'thunder',
  'peal',
  'guffaw',
  'hoot',
  'laugh heartily',
  'roar/howl/shriek with laughter',
  'laugh hysterically',
  'laugh uproariously',
  'be convulsed with laughter',
  'burst out laughing',
  'weep',
  'speed',
  'zoom',
  'whiz',
  'flash',
];