export const definitions = [
  '"the Caplans are a robust, healthy lot"',
  '"a robust metal cabinet"',
  '"California\'s robust property market"',
  '"he took quite a robust view of my case"',
  '"the country\'s decision to bow to UN pressure was preceded by a robust defense of its policies"',
  '"a robust mixture of fish, onions, capers and tomatoes"',
];
export const synonyms = [
  "strong",
  "vigorous",
  "sturdy",
  "tough",
  "powerful",
  "muscular",
  "sinewy",
  "rugged",
  "hardy",
  "strapping",
  "brawny",
  "burly",
  "husky",
  "healthy",
  "fit",
  "hale",
  "hearty",
  "lusty",
  "in trim",
  "able-bodied",
  "stalwart",
  "thewy",
  "stark",
  "powerfully built",
  "solidly built",
  "as strong as a horse/ox",
  "fighting fit",
  "as fit as a fiddle/flea",
  "bursting with health",
  "hale and hearty",
  "in fine fettle",
  "in good health",
  "in good shape",
  "in good trim",
  "aerobicized",
  "in rude health",
  "weak",
  "frail",
  "durable",
  "resilient",
  "tough",
  "hardwearing",
  "long-lasting",
  "well made",
  "sturdy",
  "strong",
  "strongly made",
  "fragile",
  "strong",
  "full-bodied",
  "flavorful",
  "full-flavored",
  "flavorsome",
  "rich",
  "sapid",
  "full of flavor",
  "insipid",
  "tasteless",
];
