export const definitions = [
  '"Anna was awakened by the telephone"',
  '"he sighed but did not awaken"',
  '"different images can awaken new emotions within us"',
  '"the movie helped to awaken the public to the horrors of apartheid"',
];
export const synonyms = [
  "wake (up)",
  "awake",
  "waken",
  "rouse",
  "arouse",
  "send to sleep",
  "wake (up)",
  "awake",
  "waken",
  "stir",
  "come to",
  "come around",
  "bestir oneself",
  "show signs of life",
  "return to the land of the living",
  "go to sleep",
  "arouse",
  "rouse",
  "bring out",
  "engender",
  "generate",
  "evoke",
  "trigger",
  "stir up",
  "inspire",
  "stimulate",
  "excite",
  "kindle",
  "fire",
  "touch off",
  "revive",
  "enkindle",
  "call/bring into being",
  "draw/call forth",
  "spark off",
  "allay",
];
