export const definitions = [
  '"she awoke to find the streets covered in snow"',
  '"my screams awoke my parents"',
  '"I awoke six hours after the operation"',
  '"the authorities finally awoke to the extent of the problem"',
  '"there were echoes and scents that awoke some memory in me"',
];
export const synonyms = [
  "wake (up)",
  "awaken",
  "stir",
  "come to",
  "come around",
  "bestir oneself",
  "show signs of life",
  "return to the land of the living",
  "fall asleep",
  "wake (up)",
  "awaken",
  "waken",
  "rouse",
  "arouse",
  "come around",
  "come to life",
  "come to one's senses",
  "recover",
  "wake up",
  "regain consciousness",
  "recover consciousness",
  "realize",
  "cognize",
  "become aware of",
  "become conscious of",
  "become cognizant of",
  "become mindful of",
];
