export const definitions = [
  '"a tumult of shouting and screaming broke out"',
  '"the whole neighborhood was in a state of fear and tumult"',
  '"his personal tumult ended when he began writing songs"',
];
export const synonyms = [
  'din',
  'racket',
  'uproar',
  'commotion',
  'ruckus',
  'rumpus',
  'hubbub',
  'pandemonium',
  'babel',
  'bedlam',
  'brouhaha',
  'fracas',
  'furor',
  'melee',
  'frenzy',
  'ado',
  'shouting',
  'yelling',
  'clamor',
  'clangor',
  'affray',
  'loud noise',
  'stramash',
  'silence',
  'turmoil',
  'confusion',
  'disorder',
  'disarray',
  'disturbance',
  'unrest',
  'chaos',
  'turbulence',
  'mayhem',
  'havoc',
  'upheaval',
  'upset',
  'ferment',
  'agitation',
  'trouble',
  'storms',
  'tempests',
  'maelstroms',
  'convulsions',
  'peace',
  'tranquility',
];