export const definitions = [
  '"the movie flopped—the second in a trio of turkeys"',
  '"I felt like such a turkey spying on his house"',
];
export const synonyms = [
  "idiot",
  "halfwit",
  "nincompoop",
  "blockhead",
  "buffoon",
  "dunce",
  "dolt",
  "ignoramus",
  "cretin",
  "imbecile",
  "dullard",
  "moron",
  "simpleton",
  "clod",
  "tomfool",
  "noddy",
  "loggerhead",
  "spoony",
  "mooncalf",
  "clodpole",
];
