export const definitions = [
  '"she turned on the TV"',
  '"I turned on the computer and found this in my inbox"',
  '"every time he turns on his famous charm they must be wondering what he is really thinking"',
  "\"if that's what turns you on that's fine by me\"",
  '"he turned on her with cold savagery"',
  '"for most business people, the central questions will turn on taxation"',
  '"there is a subplot turning on a love affair"',
  '"tight jeans can be a real turn-on"',
];
export const synonyms = [
  "switch on",
  "put on",
  "power up",
  "flick on",
  "plug in",
  "start up",
  "boot up",
  "activate",
  "cause to operate",
  "turn off",
  "arouse",
  "excite",
  "stimulate",
  "titillate",
  "please",
  "attract",
  "sexually arouse",
  "make someone feel sexually excited",
  "make someone feel sexy",
  "leave someone cold",
  "attack",
  "set on",
  "fall on",
  "weigh into",
  "round on",
  "launch an attack on",
  "let fly at",
  "lash out at",
  "hit out at",
  "lose one's temper with",
  "hang on",
  "concern",
  "depend on",
  "rest on",
  "hinge on",
  "be contingent on",
  "be decided by",
  "revolve around",
  "relate to",
];
