export const definitions = [
  '"the threat of a turned ankle was something they cared nothing about"',
  '"the smell of turned earth and burning leaves"',
  '"a small table with turned legs made from poplar"',
  '"the carefully turned words of great writers"',
  '"a possible turned letter in cunning/cunuing"',
  '"the big wheel was turning"',
  '"I turned the key in the door and crept in"',
  '"the boy shot up off the ground and turned a somersault in the air"',
  '"Wright turned his ankle in the first minute of the game"',
  '"turn the mould upside down"',
  '"Charlie turned and looked at his friend"',
  '"she turned her head toward me"',
  '"the government has now turned its attention to primary schools"',
  '"we turned around and headed back to the house"',
  '"as the tide turned he finally managed to bring the barge into its berth"',
  '"she turned a page noisily"',
  '"turn to page five for the answer"',
  '"he turned up the collar of his coat"',
  '"there was still the sea, by way of which the Persians hoped to turn all mountain or isthmus defense lines"',
  '"Hooper received the ball and turned his defender before scoring with a crisp left foot shot"',
  '"thou hast also turned the edge of his sword"',
  '"Emmeline turned pale"',
  '"the weather turned really bad"',
  '"cover potatoes with sacking to keep the light from turning them green"',
  '"most of the sugars are turned into alcohol"',
  '"the dogs were turned loose on the crowd"',
  '"I\'ve just turned forty"',
  '"the chestnut leaves were turning"',
  '"the smell was bad enough to turn the strongest stomach"',
  '"the thunder had turned the milk"',
  '"the faceplate is turned rather than cast"',
  '"if I could turn a tune, I even think I should sing"',
  '"there is also a concern that he would remain a security risk, especially as the authorities had already tried to turn him"',
  '"for some reason he thought I was the one who could turn him"',
  '"in 2021 the company turned a profit for the first time"',
];
export const synonyms = [
  "go around",
  "revolve",
  "rotate",
  "spin",
  "roll",
  "circle",
  "wheel",
  "whirl",
  "twirl",
  "gyrate",
  "swivel",
  "spiral",
  "pivot",
  "around",
  "negotiate",
  "take",
  "go round and round",
  "go round in circles",
  "pass around",
  "sweep around",
  "perform",
  "execute",
  "do",
  "carry out",
  "sprain",
  "twist",
  "rick",
  "wrench",
  "hurt",
  "injure",
  "turn around",
  "change direction",
  "change course",
  "make a U-turn",
  "reverse direction",
  "swing around",
  "wheel around",
  "aim at",
  "point at",
  "level at",
  "direct at",
  "train at",
  "focus on",
  "turn around",
  "bend",
  "curve",
  "wind",
  "twist",
  "loop",
  "meander",
  "snake",
  "zigzag",
  "change direction",
  "change course",
  "make a U-turn",
  "reverse direction",
  "swing around",
  "wheel around",
  "flip over",
  "flick over/through",
  "leaf through",
  "double",
  "double up",
  "crease",
  "turn up",
  "turn over",
  "bend",
  "overlap",
  "tuck",
  "gather",
  "pleat",
  "crimp",
  "bunch",
  "double over",
  "turn under",
  "become",
  "go",
  "grow",
  "get",
  "convert",
  "change",
  "transform",
  "make",
  "adapt",
  "modify",
  "rebuild",
  "reconstruct",
  "refashion",
  "remake",
  "make over",
  "restyle",
  "develop into",
  "prove to be",
  "turn out to be",
  "change into",
  "be transformed into",
  "metamorphose into",
  "come to be",
  "become",
  "go",
  "grow",
  "get",
  "convert",
  "change",
  "transform",
  "make",
  "adapt",
  "modify",
  "rebuild",
  "reconstruct",
  "refashion",
  "remake",
  "make over",
  "restyle",
  "develop into",
  "prove to be",
  "turn out to be",
  "change into",
  "be transformed into",
  "metamorphose into",
  "come to be",
  "become",
  "pass",
  "reach (the age of)",
  "get to (the age of)",
  "nauseate",
  "sicken",
  "cause to feel sick",
  "cause to feel nauseous",
  "make sick",
  "make someone's gorge rise",
  "make some's 's stomach rise",
  "go off",
  "sour",
  "curdle",
  "spoil",
  "taint",
  "go/become sour",
  "become rancid",
  "go bad",
  "fashion",
  "make",
  "shape",
  "mold",
  "cast",
  "form",
];
