export const definitions = [
  '"torrential rainstorms wreaked havoc yesterday"',
  '"the environmental damage wreaked by ninety years of phosphate mining"',
  '"they would soon have a chance to wreak their revenge on the enemy"',
  '"grant me some knight to wreak me for my son"',
];
export const synonyms = [
  "inflict",
  "create",
  "cause",
  "effect",
  "engender",
  "bring about",
  "perpetrate",
  "unleash",
  "vent",
  "bestow",
  "serve out",
  "administer",
  "carry out",
  "deliver",
  "apply",
  "lay on",
  "impose",
  "exact",
  "effectuate",
  "result in",
  "deal out",
  "mete out",
];
