export const definitions = [
  '"the area feels firm but has irregular nodules which can be painful to touch"',
  '"laparotomy showed white nodules in the liver"',
  '"flint nodules"',
  '"in the coal pits nodules of iron ore were mined"',
];
export const synonyms = [
  "growth",
  "lump",
  "swelling",
  "protuberance",
  "protrusion",
  "knob",
  "outgrowth",
  "wart",
  "boil",
  "pustule",
  "carbuncle",
  "tumor",
  "lump",
  "bump",
  "protuberance",
  "projection",
  "protrusion",
  "bulge",
  "swelling",
  "knot",
  "node",
  "gnarl",
  "growth",
  "outgrowth",
  "excrescence",
  "carbuncle",
  "tumor",
  "boss",
  "stud",
  "ball",
  "knop",
  "nub",
  "umbo",
  "tumescence",
];
