export const definitions = [
  '"his name became a byword for luxury"',
  '""Small is beautiful" may be the byword for most couturiers"',
];
export const synonyms = [
  "perfect example of",
  "classic case of",
  "model of",
  "exemplar of",
  "embodiment of",
  "incarnation of",
  "personification of",
  "epitome of",
  "typification of",
  "synonymous with",
  "avatar of",
  "slogan",
  "motto",
  "maxim",
  "axiom",
  "dictum",
  "mantra",
  "catchword",
  "watchword",
  "formula",
  "cry",
  "battle cry",
  "nickname",
  "middle name",
  "apothegm",
  "rallying cry",
];
