export const definitions = [
  '"the collar chafed his neck"',
  '"the grommet stops the cable from chafing on the metal"',
  '"I chafed her feet and wrapped the blanket around her"',
  '"the bank chafed at the restrictions imposed upon it"',
  '"it chafed him to be confined like this"',
];
export const synonyms = [
  "abrade",
  "graze",
  "grate",
  "gall",
  "skin",
  "scrape",
  "scratch",
  "rasp",
  "inflame",
  "excoriate",
  "rub against",
  "rub painfully",
  "abrade",
  "graze",
  "grate",
  "gall",
  "skin",
  "scrape",
  "scratch",
  "rasp",
  "inflame",
  "excoriate",
  "rub against",
  "rub painfully",
  "abrade",
  "graze",
  "grate",
  "gall",
  "skin",
  "scrape",
  "scratch",
  "rasp",
  "inflame",
  "excoriate",
  "rub against",
  "rub painfully",
  "rub",
  "warm",
  "warm up",
  "fume",
  "brood",
  "fuss",
  "be impatient",
  "be angry",
  "be annoyed",
  "be irritated",
  "be incensed",
  "be exasperated",
  "be frustrated",
  "upset oneself",
];
