export const definitions = [
  '"there is little chance of his finding a job"',
  '"a chance of victory"',
  '"he played down his chances of becoming chairman"',
  '"I gave her a chance to answer"',
  '"541 straight chances without an error"',
  '"he met his brother by chance"',
  '"what a lucky chance that you are here"',
  '"a chance meeting"',
  '"if they chanced to meet"',
  '"he chanced upon an interesting advertisement"',
  '"she waited a few seconds and chanced another look"',
];
export const synonyms = [
  "possibility",
  "prospect",
  "probability",
  "odds",
  "likelihood",
  "likeliness",
  "expectation",
  "anticipation",
  "conceivability",
  "feasibility",
  "plausibility",
  "risk",
  "threat",
  "menace",
  "hazard",
  "danger",
  "fear",
  "peril",
  "liability",
  "hope",
  "opportunity",
  "promise",
  "unlikelihood",
  "likelihood",
  "probability",
  "chances",
  "balance",
  "opportunity",
  "opening",
  "occasion",
  "turn",
  "time",
  "moment",
  "window (of opportunity)",
  "slot",
  "show",
  "a kick at the can/cat",
  "accident",
  "coincidence",
  "serendipity",
  "fate",
  "destiny",
  "fortuity",
  "fortune",
  "providence",
  "freak",
  "hazard",
  "happenstance",
  "fortuitously",
  "by accident",
  "accidentally",
  "coincidentally",
  "serendipitously",
  "unintentionally",
  "inadvertently",
  "unwittingly",
  "unknowingly",
  "unawares",
  "unconsciously",
  "a twist of fate",
  "a piece of good fortune",
  "(a bit of) luck",
  "(a bit of) good luck",
  "a fluke",
  "a happy chance",
  "intentionally",
  "knowingly",
  "happen",
  "come across",
  "run across",
  "run into",
  "hit on",
  "come upon",
  "run against",
  "happen on",
  "light on",
  "stumble on",
  "blunder on",
  "find by chance",
  "meet (by chance)",
  "risk",
  "hazard",
  "venture",
  "try",
  "essay",
  "try one's luck with",
];
