export const definitions = [
  '"both parties voted against proposals to change the law"',
  '"technology and the internet have dramatically changed the way we communicate"',
  '"fame hasn\'t changed her one bit"',
  "\"I've had time to think and my opinion hasn't changed\"",
  '"the Virginia creeper was just beginning to change from green to gold"',
  '"filters change the ammonia into nitrate"',
  '"electronic cigarettes use liquid nicotine which changes intovapor when heated"',
  '"the ferns began to change shape"',
  '"they stopped at the corner, waiting for the lights to change"',
  '"he is going to be worse for the next two or three days because the moon has changed"',
  '"she decided to change her name"',
  '"I want to change my car for one that\'s reliable and fun to drive"',
  '"most people will change jobs several times in their careers"',
  '"I noticed my rear brake light wasn\'t working and changed the bulb"',
  '"I offered to change seats with him"',
  '"wait for a gap and then change gears"',
  '"with business concluded, the convention changes gear and a gigantic circus takes over the town"',
  '"there\'s an ATM in the reception area which will change your English money"',
  '"he changed for dinner"',
  '"you should change into some dry clothes"',
  '"we popped back to the hotel to get changed before heading out for our last night in Paris"',
  '"Joey went up to his room and changed out of his school clothes"',
  '"give me a moment to change my clothes"',
  '"I changed her on top of the table until she got too big"',
  '"the change from a nomadic to an agricultural society"',
  '"environmental change"',
  '"a change of venue"',
  '"a change came over Eddie\'s face"',
  '"couscous makes an interesting change from rice"',
  '"a change of socks"',
  '"a handful of loose change"',
  '"I\'d go to the bank and get change"',
  '"I watched him pocket the change"',
];
export const synonyms = [
  "convert",
  "transform",
  "make",
  "adapt",
  "modify",
  "rebuild",
  "reconstruct",
  "refashion",
  "remake",
  "make over",
  "restyle",
  "alter",
  "adjust",
  "adapt",
  "turn",
  "amend",
  "improve",
  "modify",
  "convert",
  "revise",
  "recast",
  "reform",
  "reshape",
  "refashion",
  "redesign",
  "restyle",
  "revamp",
  "rework",
  "remake",
  "remodel",
  "remold",
  "redo",
  "reconstruct",
  "reorganize",
  "reorder",
  "refine",
  "reorient",
  "reorientate",
  "vary",
  "transform",
  "transfigure",
  "transmute",
  "metamorphose",
  "evolve",
  "customize",
  "tailor",
  "permute",
  "make different",
  "become different",
  "undergo a change",
  "make alterations to",
  "make adjustments to",
  "undergo a sea change",
  "preserve",
  "stay the same",
  "swap",
  "exchange",
  "interchange",
  "substitution",
  "switch",
  "commutation",
  "conversion",
  "replacement",
  "rotation",
  "alternation",
  "transposition",
  "trade",
  "barter",
  "bartering",
  "truck",
  "alteration",
  "modification",
  "variation",
  "conversion",
  "revision",
  "amendment",
  "adjustment",
  "adaptation",
  "remodeling",
  "reshaping",
  "remolding",
  "redoing",
  "reconstruction",
  "rebuilding",
  "recasting",
  "reorganization",
  "rearrangement",
  "reordering",
  "reshuffling",
  "restyling",
  "rejigging",
  "reworking",
  "renewal",
  "renewing",
  "revamping",
  "renovation",
  "remaking",
  "metamorphosis",
  "transformation",
  "transfiguration",
  "translation",
  "evolution",
  "mutation",
  "sea change",
  "transmogrification",
  "coins",
  "small change",
  "cash",
  "petty cash",
  "coinage",
  "coin",
  "hard cash",
  "silver",
  "copper",
  "coppers",
  "gold",
  "specie",
  "loose change",
  "coin of the realm",
  "chime",
  "carillon",
  "ring",
  "ringing",
  "knell",
  "toll",
  "tolling",
  "sound",
  "sounding",
  "death knell",
  "clang",
  "boom",
  "resounding",
  "reverberation",
  "touch",
  "tocsin",
  "tintinnabulation",
];
