export const definitions = [
  '"a service in the chapel"',
  '"attendance at chapel was compulsory"',
  '"the first chapel on the right of the cathedral is dedicated to St. Ludmila"',
  '"she went to chapel twice on Sunday"',
  '"the funeral was in the chapel at Broadfoot Brothers Funeral Home"',
];
export const synonyms = [
  "holy place",
  "temple",
  "church",
  "tabernacle",
  "altar",
  "sanctuary",
  "sanctum",
  "stupa",
  "tope",
  "marabout",
  "sacrarium",
  "nymphaeum",
  "fane",
  "martyry",
  "ciborium",
  "dargah",
  "tirtha",
  "chorten",
  "feretory",
];
