export const definitions = [
  '"what is required of celibate Catholic clergy is to remain chaste"',
  '"a chaste, consoling embrace"',
  '"the dark, chaste interior was lightened by tilework"',
];
export const synonyms = [
  "virginal",
  "virgin",
  "intact",
  "maidenly",
  "maiden",
  "unmarried",
  "unwed",
  "celibate",
  "abstinent",
  "self-restrained",
  "self-denying",
  "nunlike",
  "innocent",
  "pure",
  "guiltless",
  "sinless",
  "uncorrupted",
  "incorrupt",
  "uncontaminated",
  "undefiled",
  "unsullied",
  "virtuous",
  "good",
  "decent",
  "moral",
  "proper",
  "decorous",
  "demure",
  "modest",
  "wholesome",
  "upright",
  "immaculate",
  "vestal",
  "continent",
  "pure as the driven snow",
  "free of sin",
  "promiscuous",
  "immoral",
  "nonsexual",
  "friendly",
  "platonic",
  "innocent",
  "passionate",
  "plain",
  "simple",
  "bare",
  "unadorned",
  "undecorated",
  "unornamented",
  "unembellished",
  "restrained",
  "unaffected",
  "unpretentious",
  "unfussy",
  "uncluttered",
  "functional",
  "spartan",
  "austere",
  "ascetic",
  "monastic",
  "without frills",
  "ostentatious",
];
