export const definitions = [
  '"the driver was very chatty"',
  '"she wrote a chatty, cheerful letter to her mother"',
];
export const synonyms = [
  'talkative',
  'communicative',
  'expansive',
  'forthcoming',
  'open',
  'unreserved',
  'gossipy',
  'gossiping',
  'garrulous',
  'loquacious',
  'voluble',
  'verbose',
  'effusive',
  'gushing',
  'glib',
  'multiloquent',
  'multiloquous',
  'taciturn',
  'conversational',
  'gossipy',
  'informal',
  'casual',
  'colloquial',
  'familiar',
  'friendly',
  'lively',
  'formal',
];