export const definitions = [
  '"she looked every inch the chic Frenchwoman"',
  '"French chic"',
  '"biker chic"',
];
export const synonyms = [
  "stylish",
  "smart",
  "elegant",
  "sophisticated",
  "dapper",
  "debonair",
  "dashing",
  "trim",
  "tasteful",
  "understated",
  "attractive",
  "flattering",
  "fashionable",
  "high-fashion",
  "modish",
  "voguish",
  "up to date",
  "up to the minute",
  "ultramodern",
  "contemporary",
  "à la mode",
  "trig",
  "in vogue",
  "unfashionable",
  "flair",
  "stylishness",
  "smartness",
  "elegance",
  "grace",
  "gracefulness",
  "poise",
  "polish",
  "suaveness",
  "sophistication",
  "urbanity",
  "finesse",
  "panache",
  "flourish",
  "taste",
  "vigor",
  "energy",
  "pep",
  "dynamism",
  "forcefulness",
  "force",
  "strength",
  "determination",
  "motivation",
  "push",
  "vehemence",
  "fanaticism",
  "go",
  "vitality",
  "vivacity",
  "buoyancy",
  "liveliness",
  "animation",
  "sprightliness",
  "zest",
  "sparkle",
  "effervescence",
  "fizz",
  "verve",
  "spirit",
  "spiritedness",
  "ebullience",
  "life",
  "dash",
  "brio",
  "enthusiasm",
  "eagerness",
  "keenness",
  "passion",
  "zeal",
  "fervor",
  "relish",
  "gusto",
  "feeling",
  "ardor",
  "fire",
  "fieriness",
  "drive",
  "esprit",
  "clumsiness",
];
