export const definitions = [
  '"she\'d been playing tennis since she was a child"',
  '"the film is not suitable for children"',
  '"when children leave home, parents can feel somewhat redundant"',
  '"she\'s such a child!"',
  "'s 's a child in financial matters\"",
  '"the children of Abraham"',
  '"a child of the Sixties"',
  '"OPEC was in a sense a child of the Cold War"',
];
export const synonyms = [
  "youngster",
  "boy",
  "girl",
  "baby",
  "newborn",
  "infant",
  "toddler",
  "schoolboy",
  "schoolgirl",
  "adolescent",
  "teenager",
  "youth",
  "young man",
  "young lady",
  "young adult",
  "juvenile",
  "minor",
  "junior",
  "stripling",
  "fledgling",
  "whippersnapper",
  "son",
  "daughter",
  "scion",
  "descendant",
  "offspring",
  "progeny",
  "issue",
  "neonate",
  "bairn",
  "wean",
  "laddie",
  "lassie",
  "pickney",
  "babe",
  "babe in arms",
  "hobbledehoy",
  "young one",
  "little one",
  "young woman",
  "young person",
  "son and heir",
  "descendant",
  "offshoot",
  "heir",
  "successor",
  "issue",
  "offspring",
  "ancestor",
  "predecessor",
  "novice",
  "greenhorn",
  "ingénue",
  "babe in arms",
  "babe",
  "unworldly person",
  "naive person",
  "descendants",
  "heirs",
  "successors",
  "offspring",
  "children",
  "family",
  "progeny",
  "scions",
  "issue",
  "seed",
];
