export const definitions = [
  '"it had turned chilly"',
  '"a chilly day"',
  '"I felt a bit chilly"',
  '"the out-of-town lawyer got a polite but chilly reception"',
];
export const synonyms = [
  'cold',
  'cool',
  'crisp',
  'fresh',
  'brisk',
  'bleak',
  'wintry',
  'snowy',
  'frosty',
  'icy',
  'ice-cold',
  'icy-cold',
  'glacial',
  'polar',
  'arctic',
  'raw',
  'sharp',
  'bitter',
  'biting',
  'piercing',
  'penetrating',
  'freezing',
  'frigid',
  'chill',
  'gelid',
  'brumal',
  'bitterly cold',
  'warm',
  'cold',
  'frozen',
  'freezing',
  'shivery',
  'numb',
  'numbed',
  'chilled',
  'frozen stiff',
  'frozen to the marrow/core/bone',
  'freezing cold',
  'bitterly cold',
  'unfriendly',
  'unsympathetic',
  'unwelcoming',
  'forbidding',
  'cold',
  'cool',
  'frosty',
  'glacial',
  'frigid',
  'haughty',
  'supercilious',
  'disdainful',
  'aloof',
  'distant',
  'remote',
  'reserved',
  'withdrawn',
  'uncommunicative',
  'unresponsive',
  'unemotional',
  'dispassionate',
  'passionless',
  'wooden',
  'impersonal',
  'formal',
  'stiff',
  'austere',
  'gelid',
  'friendly',
];