export const definitions = [
  '"there used to be a good chippy down the back of Albert Street"',
  '"I thought she was hostile and chippy"',
  '"a chippy game"',
];
export const synonyms = [
  'irritable',
  'irascible',
  'fractious',
  'fretful',
  'cross',
  'petulant',
  'pettish',
  'crabbed',
  'crabby',
  'crotchety',
  'cantankerous',
  'curmudgeonly',
  'disagreeable',
  'miserable',
  'morose',
  'peppery',
  'on edge',
  'edgy',
  'impatient',
  'complaining',
  'querulous',
  'bitter',
  'moody',
  'grumpy',
  'huffy',
  'scratchy',
  'out of sorts',
  'out of temper',
  'ill-tempered',
  'bad-tempered',
  'ill-natured',
  'ill-humored',
  'sullen',
  'surly',
  'sulky',
  'sour',
  'churlish',
  'touchy',
  'testy',
  'tetchy',
  'snappish',
  'waspish',
  'prickly',
  'crusty',
  'bilious',
  'liverish',
  'dyspeptic',
  'splenetic',
  'choleric',
  'in a bad mood',
  'mardy',
  'miffy',
  'affable',
  'easygoing',
];