export const definitions = [
  '"outside, the crickets chirped monotonously"',
  '""Good morning!" chirped Alex"',
  '"the chirps and whirrs of insects"',
];
export const synonyms = [
  "tweet",
  "twitter",
  "chirrup",
  "cheep",
  "peep",
  "chitter",
  "chatter",
  "chirr",
  "sing",
  "warble",
  "trill",
  "pipe",
  "trill",
  "trilling",
  "song",
  "birdsong",
  "cry",
  "warbling",
  "chirping",
  "chirrup",
  "chirruping",
  "chirr",
  "chirring",
  "cheep",
  "cheeping",
  "twitter",
  "twittering",
  "tweet",
  "tweeting",
  "whistle",
  "whistling",
  "chatter",
  "chattering",
  "squeak",
  "squeaking",
  "pipe",
  "piping",
  "peep",
  "peeping",
  "call",
  "calling",
];
