export const definitions = [
  '"she looked positively chirpy"',
  '"a chirpy face"',
];
export const synonyms = [
  "happy",
  "jolly",
  "merry",
  "bright",
  "glad",
  "sunny",
  "joyful",
  "joyous",
  "lighthearted",
  "sparkling",
  "bubbly",
  "exuberant",
  "ebullient",
  "cock-a-hoop",
  "elated",
  "gleeful",
  "breezy",
  "airy",
  "cheery",
  "sprightly",
  "jaunty",
  "animated",
  "radiant",
  "smiling",
  "grinning",
  "laughing",
  "mirthful",
  "frolicsome",
  "jovial",
  "genial",
  "good-humored",
  "happy-go-lucky",
  "carefree",
  "unworried",
  "untroubled",
  "buoyant",
  "optimistic",
  "hopeful",
  "positive",
  "content",
  "contented",
  "gay",
  "jocund",
  "gladsome",
  "blithe",
  "blithesome",
  "of good cheer",
  "in good spirits",
  "in high spirits",
  "without a care in the world",
  "full of the joys of spring",
  "full of hope",
  "sad",
];
