export const definitions = ['"her only ornament was a simple pearl choker"'];
export const synonyms = [
  "neckband",
  "ruff",
  "gorget",
  "bertha",
  "Vandyke",
  "rebato",
  "rope",
  "cord",
  "line",
  "guy",
  "wire",
  "chain",
  "hawser",
  "stay",
  "bridle",
  "topping lift",
  "piece of cordage",
];
