export const definitions = [
  '"Willie choked on a mouthful of soda"',
  '"the toys contained parts that could choke a very young child"',
  '"the bracken will choke the wild gladiolus"',
  '"piracy will choke the creation and distribution of music"',
  '"higher rates of interest choke off investment demand"',
  '"we were the only team not to choke when it came to the crunch"',
  '"the roads were choked with traffic"',
  '"vegetation choked the trails"',
  '"he was choked with fury"',
  '"carbon monoxide results during a cold start, when an engine is choked"',
  '"an automatic choke"',
  '"too much choke does not help"',
  '"he pulled the choke out to its full extent"',
  '"many guns may not have the right choke"',
  '"a full choke gun"',
  '"a little choke of laughter"',
];
export const synonyms = [
  "gag",
  "retch",
  "cough",
  "gasp",
  "struggle for air",
  "fight for breath",
  "suffocate",
  "asphyxiate",
  "smother",
  "stifle",
  "overpower",
  "overcome",
  "strangle",
  "throttle",
  "block",
  "obstruct",
  "stop up",
  "plug",
  "congest",
  "jam",
  "occlude",
  "obturate",
  "clog (up)",
  "bung up",
  "silt up",
  "dam up",
];
