export const definitions = [
  '"he chose a seat facing the door"',
  '"now it\'s my turn to choose"',
  '"he chose to go"',
  '"I\'ll stay as long as I choose"',
];
export const synonyms = [
  "select",
  "pick",
  "pick out",
  "plump for",
  "go for",
  "take",
  "handpick",
  "set",
  "designate",
  "determine",
  "specify",
  "appoint",
  "name",
  "nominate",
  "adopt",
  "espouse",
  "opt for",
  "settle on",
  "decide on",
  "fix on",
  "come down in favor of",
  "vote for",
  "single out",
  "pitch on",
  "reject",
  "decline",
  "wish",
  "want",
  "desire",
  "prefer",
  "please",
  "like",
  "see fit",
  "decide",
  "elect",
  "make up one's mind",
  "feel/be inclined",
];
