export const definitions = [
  '"we can\'t praise Chris enough—he did a brilliant job"',
  '"we praise God for past blessings"',
  '"the audience was full of praise for the whole production"',
  '"give praise to God"',
];
export const synonyms = [
  "commend",
  "applaud",
  "eulogize",
  "compliment",
  "congratulate",
  "celebrate",
  "sing the praises of",
  "make much of",
  "take one's hat off to",
  "lionize",
  "admire",
  "hail",
  "cheer",
  "flatter",
  "laud",
  "panegyrize",
  "express approval of",
  "express admiration for",
  "pay tribute to",
  "speak highly of",
  "praise to the skies",
  "rave about",
  "go into raptures about",
  "heap praise on",
  "wax lyrical about",
  "say nice things about",
  "pat on the back",
  "throw bouquets at",
  "cry someone/something up",
  "criticize",
  "condemn",
  "worship",
  "glorify",
  "honor",
  "exalt",
  "adore",
  "venerate",
  "reverence",
  "hallow",
  "bless",
  "magnify",
  "laud",
  "pay tribute to",
  "pay homage to",
  "give thanks to",
  "approval",
  "acclaim",
  "admiration",
  "approbation",
  "acclamation",
  "plaudits",
  "congratulations",
  "commendation",
  "applause",
  "flattery",
  "adulation",
  "tribute",
  "accolade",
  "cheer",
  "compliment",
  "a pat on the back",
  "eulogy",
  "encomium",
  "panegyric",
  "ovation",
  "bouquet",
  "laurels",
  "puffery",
  "laudation",
  "eulogium",
  "honor",
  "thanks",
  "glory",
  "glorification",
  "worship",
  "devotion",
  "exaltation",
  "adoration",
  "veneration",
  "reverence",
  "tribute",
];
