export const definitions = [
  '"the pony was prancing around the paddock"',
  '"she pranced around the lounge impersonating her favorite pop stars"',
];
export const synonyms = [
  "cavort",
  "dance",
  "jig",
  "trip",
  "caper",
  "jump",
  "leap",
  "spring",
  "bound",
  "skip",
  "hop",
  "parade",
  "strut",
  "swagger",
  "swank",
  "frisk",
  "gambol",
  "romp",
  "frolic",
  "curvet",
  "peacock",
  "rollick",
  "capriole",
  "jump",
  "bound",
  "bounce",
  "leap",
  "spring",
  "skip",
  "gambol",
];
