export const definitions = [
  '"the gap between theory and praxis, text and world"',
  '"patterns of Christian praxis in church and society"',
];
export const synonyms = [
  'custom',
  'practice',
  'habit',
  'tradition',
  'convention',
  'routine',
  'rule',
  'rite',
  'ritual',
  'observance',
  'ordinance',
  'ceremony',
  'ceremonial',
  'way',
  'procedure',
  'method',
  'mode',
  'form',
  'formality',
  'wont',
  'mores',
  'moeurs',
];