export const definitions = [
  '"he preached to a large congregation"',
  '"our pastor will preach the sermon"',
  '"a church that preaches the good news"',
  '"my parents have always preached toleration and moderation"',
  '"viewers want to be entertained, not preached at"',
  '""Please continue to speak up if you see bullying—it could save another\'s life." "Preach!""',
  '""All coaches in this league need to be better\'s \'s embarrassing." "Preach it, Michael""',
];
export const synonyms = [
  "sermonize",
  "evangelize",
  "address",
  "speak",
  "gospelize",
  "give a sermon",
  "deliver a sermon",
  "spread the gospel",
  "proclaim",
  "teach",
  "spread",
  "propagate",
  "expound",
  "explain",
  "make known",
  "advocate",
  "recommend",
  "advise",
  "urge",
  "exhort",
  "teach",
  "counsel",
  "champion",
  "inculcate",
  "instil",
  "moralize",
  "sermonize",
  "pontificate",
  "lecture",
  "harangue",
  "be moralistic",
  "ethicize",
];
