export const definitions = [
  '"I prefer Venice to Rome"',
  '"I would prefer to discuss the matter in private"',
  '"Val would presumably prefer that you didn\'t get arrested"',
  '"his preferred candidate"',
  '"the police will prefer charges"',
  '"he was preferred to the post"',
];
export const synonyms = [
  "favor",
  "choose",
  "select",
  "pick",
  "go for",
  "plump for",
  "elect",
  "wish",
  "desire",
  "want",
  "like better",
  "would rather (have)",
  "would sooner (have)",
  "be more partial to",
  "lean/incline toward",
  "think preferable",
  "opt for",
  "vote for",
  "single out",
  "bring",
  "press",
  "file",
  "lodge",
  "tender",
  "present",
  "place",
  "lay",
  "submit",
  "put forward",
  "proffer",
  "offer",
  "propose",
  "promote",
  "upgrade",
  "advance",
  "raise",
  "elevate",
  "aggrandize",
  "move up",
];
