export const definitions = [
  '"a pretty little girl with an engaging grin"',
  '"it is a pretty state of affairs when a young fellow prefers the company of Italian fiddlers to taking possession of his own first command"',
  '"he looked pretty fit for his age"',
  '"he buys her lots of pretties—bangles and rings and things"',
  '"six pretties in sequined leotards"',
  '"she\'ll be all prettied up and ready to go in an hour"',
];
export const synonyms = [
  "attractive",
  "lovely",
  "good-looking",
  "nice-looking",
  "fetching",
  "prepossessing",
  "appealing",
  "charming",
  "delightful",
  "nice",
  "engaging",
  "pleasing",
  "darling",
  "sweet",
  "dear",
  "adorable",
  "lovable",
  "winning",
  "winsome",
  "cute",
  "as pretty as a picture",
  "dainty",
  "graceful",
  "handsome",
  "well favored",
  "personable",
  "beautiful",
  "glamorous",
  "gorgeous",
  "ravishing",
  "stunning",
  "bewitching",
  "alluring",
  "bonny",
  "beauteous",
  "fair",
  "comely",
  "chocolate-box",
  "plain",
  "ugly",
  "quite",
  "rather",
  "somewhat",
  "fairly",
  "reasonably",
  "moderately",
  "comparatively",
  "relatively",
  "tolerably",
  "passably",
  "adequately",
  "satisfactorily",
  "decently",
  "respectably",
  "beautify",
  "prettify",
  "adorn",
  "ornament",
  "embellish",
  "smarten",
  "glamorize",
  "prink",
  "preen",
  "primp",
  "make attractive",
  "make pretty",
  "pretty up",
  "put makeup on",
];
