export const definitions = [
  '"primal hunting societies"',
  '"he preys on people\'s primal fears"',
  '"rivers were the primal highways of life"',
];
export const synonyms = [
  'original',
  'initial',
  'early',
  'earliest',
  'first',
  'primitive',
  'primeval',
  'primary',
  'subsequent',
  'derivative',
  'basic',
  'fundamental',
  'essential',
  'elemental',
  'primary',
  'vital',
  'central',
  'intrinsic',
  'indispensable',
  'inherent',
  'cardinal',
  'characteristic',
  'peripheral',
];