export const definitions = ['"her prissy mother"', '"prissy little dresses"'];
export const synonyms = [
  "prudish",
  "priggish",
  "prim",
  "niminy-piminy",
  "strait-laced",
  "formal",
  "proper",
  "stuffy",
  "namby-pamby",
  "Victorian",
  "old-maidish",
  "schoolmarmish",
  "po-faced",
  "square-toed",
  "prim and proper",
  "mimsy",
  "schoolmistressy",
  "governessy",
  "Grundyish",
  "broad-minded",
];
