export const definitions = [
  '"he died in prison"',
  '"both men were sent to prison"',
  '"the young man prisoned behind the doors"',
];
export const synonyms = [
  "jail",
  "lockup",
  "guardhouse",
  "detention center",
  "penitentiary",
  "jailhouse",
  "boot camp",
  "stockade",
  "house of correction",
  "pound",
  "roundhouse",
  "borstal",
  "bridewell",
  "tollbooth",
  "bastille",
  "reformatory",
  "penal institution",
  "place of detention",
  "place of confinement",
  "young offender institution",
  "correctional facility",
  "youth custody centre",
  "approved school",
];
