export const definitions = [
  '"she\'s never had a proper job"',
  '"a proper meal"',
  '"some of the dos and don\'ts in espionage proper"',
  '"she looked like a proper harlot"',
  '"an artist needs the proper tools"',
  '"they had not followed the proper procedures"',
  '"her parents\' view of what was proper for a well - bred girl"',
  '"a very prim and proper Swiss lady"',
  '"the two elephant types proper to Africa and to southern Asia"',
  '"to judge with my proper eyes"',
  '"he is a proper youth!"',
  '"my eyes were all blurry and I couldn\'t see proper"',
  '"I had been fooled good and proper"',
  '"we go to the High Mass, with plainsong propers sung by the Ritual Choir"',
];
export const synonyms = [
  'real',
  'genuine',
  'actual',
  'true',
  'bona fide',
  'true',
  'very',
  'rightly so called',
  'complete',
  'absolute',
  'real',
  'perfect',
  'total',
  'thorough',
  'thoroughgoing',
  'utter',
  'out-and-out',
  'positive',
  'unmitigated',
  'consummate',
  'arrant',
  'right',
  'correct',
  'accepted',
  'orthodox',
  'conventional',
  'established',
  'official',
  'formal',
  'regular',
  'acceptable',
  'appropriate',
  'suitable',
  'fitting',
  'apt',
  'due',
  'meet',
  'de règle',
  'inappropriate',
  'wrong',
  'respectable',
  'decorous',
  'seemly',
  'decent',
  'refined',
  'ladylike',
  'gentlemanly',
  'genteel',
  'formal',
  'conventional',
  'correct',
  'orthodox',
  'polite',
  'punctilious',
  'sedate',
  'modest',
  'demure',
  'virtuous',
  'becoming',
  'befitting',
  'fit',
  'done',
  'comme il faut',
  'improper',
  'unconventional',
  'belonging',
  'relating',
  'pertaining',
  'related',
  'relevant',
  'unique',
  'peculiar',
  'associated with',
];