export const definitions = [
  '"a proven ability to work hard"',
  '"a proven risk to health"',
  '"a system based on proven technologies"',
  '"the concept is difficult to prove"',
  '"innocent until proven guilty"',
  '"the plan has proved a great success"',
  '"a new lieutenant, very green and very desperate to prove himself"',
  '"firearms proved for black powder should not be used with smokeless ammunition"',
];
export const synonyms = [
  "demonstrate",
  "show",
  "manifest",
  "evince",
  "determine",
  "substantiate",
  "corroborate",
  "verify",
  "ratify",
  "validate",
  "authenticate",
  "attest",
  "certify",
  "document",
  "bear out",
  "confirm",
  "show beyond doubt",
  "show to be true",
  "produce/submit proof",
  "produce/submit evidence",
  "establish evidence",
  "witness to",
  "give substance to",
  "demonstrate the truth of",
  "disprove",
  "turn out",
  "happen",
  "be found",
  "demonstrate one's abilities / qualities / courage",
  "show one's(true) mettle",
  "show what one is made of",
];
