export const definitions = [
  '"he embarked for India in 1817"',
  '"its passengers were ready to be embarked"',
  '"he embarked on a new career"',
];
export const synonyms = [
  "take ship",
  "take off",
  "board ship",
  "go on board",
  "go aboard",
  "climb aboard",
  "step aboard",
  "disembark",
  "land",
  "begin",
  "start",
  "commence",
  "undertake",
  "set about",
  "enter on",
  "go into",
  "take up",
  "launch into",
  "turn one's hand to",
  "institute",
  "initiate",
  "tackle",
  "venture into",
  "plunge into",
  "engage in",
  "settle down to",
];
