export const definitions = [
  '"a former champion jockey"',
  '"a car jockey"',
  '"both men will be jockeying for the two top jobs"',
  '"Jason jockeyed his machine into a dive"',
];
export const synonyms = [
  "rider",
  "horseman",
  "horsewoman",
  "equestrian",
  "compete",
  "contend",
  "vie",
  "struggle",
  "fight",
  "tussle",
  "scramble",
  "push",
  "jostle",
  "maneuver",
  "ease",
  "edge",
  "manipulate",
  "work",
  "steer",
  "engineer",
  "inveigle",
  "insinuate",
  "ingratiate",
  "wheedle",
  "coax",
  "cajole",
];
