export const definitions = [
  '"people jostled against us"',
  '"passengers arriving and departing, jostling one another"',
  '"a jumble of images jostled for attention"',
  '"the jostle of shoppers"',
];
export const synonyms = [
  'jolt',
  'push',
  'shove',
  'elbow',
  'hustle',
  'mob',
  'thrust',
  'barge',
  'force',
  'squeeze',
  'shoulder',
  'bulldoze',
  'struggle',
  'vie',
  'jockey',
  'scramble',
  'bump into/against',
  'knock into/against',
  'bang into',
  'collide with',
  'cannon into',
  'plow into',
  'crowd one another',
  'push',
  'thrust',
  'barge',
  'ram',
  'bump',
  'bang',
  'jolt',
  'butt',
  'knock',
  'prod',
  'poke',
  'nudge',
  'elbow',
  'shoulder',
];