export const definitions = [
  '"she was in a jovial mood"',
];
export const synonyms = [
  'cheerful',
  'jolly',
  'happy',
  'cheery',
  'good-humored',
  'convivial',
  'genial',
  'good-natured',
  'friendly',
  'amiable',
  'affable',
  'sociable',
  'outgoing',
  'clubbable',
  'smiling',
  'grinning',
  'laughing',
  'mirthful',
  'merry',
  'sunny',
  'bright',
  'joyful',
  'high-spirited',
  'exuberant',
  'ebullient',
  'lively',
  'vivacious',
  'sprightly',
  'jaunty',
  'breezy',
  'happy-go-lucky',
  'carefree',
  'unworried',
  'untroubled',
  'fun-loving',
  'buoyant',
  'optimistic',
  'positive',
  'gay',
  'gladsome',
  'jocund',
  'joyous',
  'jocose',
  'blithe',
  'blithesome',
  'of good cheer',
  'perk',
  'Pickwickian',
  'full of life',
  'without a care in the world',
  'full of the joys of spring',
  'as merry/lively as a grig',
  'miserable',
  'gloomy',
];