export const definitions = [
  '"I felt shame that I had ever joyed in his discomfiture or pain"',
];
export const synonyms = [
  "jump for joy",
  "exult",
  "glory",
  "triumph",
  "celebrate",
  "cheer",
  "revel",
  "make merry",
  "jubilate",
  "be joyful",
  "be happy",
  "be pleased",
  "be glad",
  "be delighted",
  "be elated",
  "be ecstatic",
  "be euphoric",
  "be overjoyed",
  "be as pleased as Punch",
  "be cock-a-hoop",
  "be jubilant",
  "be rapturous",
  "be in raptures",
  "be transported",
  "be beside oneself with joy",
  "be delirious",
  "be thrilled",
  "be on cloud nine",
  "be walking/treading on air",
  "be in seventh heaven",
  "mourn",
  "lament",
];
