export const definitions = [
  '"his mouth curved into an ironic smile"',
  '"maybe his comment is ironic"',
  '"there were a few ironic cheers that soon gave way to roars of disapproval"',
  '"I often find it ironic that despite the wonders of being alive, we refuse to be happy"',
  '"it was ironic that now everybody had plenty of money for food they couldn\'t obtain it because everything was rationed"',
];
export const synonyms = [
  "sarcastic",
  "sardonic",
  "dry",
  "caustic",
  "sharp",
  "stinging",
  "scathing",
  "acerbic",
  "acid",
  "bitter",
  "trenchant",
  "mordant",
  "cynical",
  "mocking",
  "satirical",
  "scoffing",
  "ridiculing",
  "derisory",
  "derisive",
  "scornful",
  "sneering",
  "wry",
  "double-edged",
  "backhanded",
  "tongue-in-cheek",
  "sincere",
  "paradoxical",
  "incongruous",
  "odd",
  "strange",
  "weird",
  "peculiar",
  "unexpected",
  "logical",
  "to be expected",
];
