export const definitions = [
  '"the First Amendment dictum that \"Congress shall make no law … abridging the freedom of speech\""',
  '"the old dictum \"might makes right.\""',
];
export const synonyms = [
  'pronouncement',
  'proclamation',
  'direction',
  'injunction',
  'assertion',
  'statement',
  'dictate',
  'command',
  'commandment',
  'mandate',
  'order',
  'decree',
  'edict',
  'fiat',
  'promulgation',
  'precept',
  'requirement',
  'stipulation',
  'instruction',
  'law',
  'ordinance',
  'rule',
  'regulation',
  'ukase',
  'pronunciamento',
  'rescript',
  'firman',
  'decretal',
  'irade',
  'saying',
  'maxim',
  'axiom',
  'proverb',
  'adage',
  'aphorism',
  'saw',
  'precept',
  'epigram',
  'epigraph',
  'motto',
  'truism',
  'platitude',
  'commonplace',
  'expression',
  'phrase',
  'formula',
  'slogan',
  'quotation',
  'quote',
  'apothegm',
  'gnome',
  'words of wisdom',
  'pearls of wisdom',
];