export const definitions = [
  '"he thought he\'d been diddled out of his change"',
  '"he diddled his income tax returns"',
  '"why diddle around with slow costly tests?"',
  '"he diddled with the graphics on his computer"',
];
export const synonyms = [
  'swindle',
  'defraud',
  'cheat',
  'fleece',
  'exploit',
  'deceive',
  'trick',
  'cozen',
  'sharp',
  'mulct',
  'do someone in the eye',
  'falsify',
  'manipulate',
  'massage',
  'rig',
  'distort',
  'pervert',
  'misrepresent',
  'juggle',
  'doctor',
  'alter',
  'tamper with',
  'interfere with',
];