export const definitions = [
  '"speaking simply and from the heart"',
  '"simply complete the application form"',
  '"it makes Terry simply furious"',
  '"quite simply, some things have to be taught"',
];
export const synonyms = [
  "straightforwardly",
  "directly",
  "clearly",
  "plainly",
  "intelligibly",
  "lucidly",
  "unambiguously",
  "soberly",
  "unfussily",
  "unostentatiously",
  "severely",
  "austerely",
  "starkly",
  "monastically",
  "classically",
  "unpretentiously",
  "modestly",
  "naturally",
  "quietly",
  "without adornment",
  "without decoration",
  "without ornament/ornamentation",
  "without embellishment",
  "unelaborately",
  "without frills",
  "with restraint",
  "without clutter",
  "merely",
  "just",
  "purely",
  "solely",
  "only",
  "for no other reason",
  "utterly",
  "absolutely",
  "completely",
  "positively",
  "really",
  "totally",
  "beyond",
];
