export const definitions = [
  '"cash registers were dinging softly"',
  '"I dinged him one"',
  '"agents who stayed on a call too long got dinged"',
];
export const synonyms = [
  "chime",
  "ring out",
  "toll",
  "peal",
  "knell",
  "sound",
  "clang",
  "bong",
  "clink",
  "jingle",
  "tinkle",
  "ringing",
  "carillon",
  "tolling",
  "sounding",
  "clanging",
  "clinking",
  "dinging",
  "jingling",
  "tinkling",
  "tocsin",
  "tintinnabulation",
  "chime out",
  "hit",
  "strike",
  "buffet",
  "bang",
  "knock",
  "thwack",
  "slug",
  "welt",
  "cuff",
  "punch",
  "smash",
  "concuss",
  "stun",
  "smite",
  "swinge",
  "hit over the head",
  "hit on the head",
];
