export const definitions = ['"Andy\'s dinkum hat from Australia"'];
export const synonyms = [
  "authentic",
  "real",
  "actual",
  "original",
  "bona fide",
  "true",
  "veritable",
  "unfeigned",
  "unadulterated",
  "unalloyed",
  "sterling",
  "attested",
  "undisputed",
  "rightful",
  "legitimate",
  "lawful",
  "legal",
  "valid",
  "sound",
  "echt",
  "simon-pure",
  "sincere",
  "honest",
  "truthful",
  "unhypocritical",
  "straightforward",
  "direct",
  "frank",
  "candid",
  "open",
  "artless",
  "natural",
  "unaffected",
  "guileless",
  "ingenuous",
  "meaning what one says",
  "bogus",
  "fake",
  "insincere",
];
