export const definitions = [
  '"there was no direct flight that day"',
  '"the complications are a direct result of bacteria spreading"',
  '"the government moved towards reintroducing direct rule"',
  '"ferns like a bright position out of direct sunlight"',
  '"a direct descendant of Edward III"',
  '"nonviolence is the direct opposite of compulsion"',
  '"he is very direct and honest"',
  '"there is no direct evidence that officials accepted bribes"',
  '"a direct butt joint between surfaces of steel"',
  '"buy direct and save"',
  '"Austrian Airlines is flying direct to Innsbruck again"',
  '"an economic elite directed the nation\'s affairs"',
  '"the film is directed by Sir Richard Attenborough"',
  '"heating ducts to direct warm air to rear-seat passengers"',
  '"his smile was directed at Laura"',
  '"can you direct me to the railroad station, please?"',
  '"put them all in one packet, and direct them to me"',
  '"we direct our anger and frustration at family"',
  '"I suggest that he direct his remarks to the council"',
  '"he directed his criticism at media coverage of the Catholic Church"',
  '"the book is directed at the younger reader"',
  '"the conscience of the credulous prince was directed by saints and bishops"',
  '"the judge directed him to perform community service"',
  '"he directed that no picture from his collection could be sold"',
];
export const synonyms = [
  "straight",
  "undeviating",
  "unswerving",
  "shortest",
  "quickest",
  "nonstop",
  "unbroken",
  "uninterrupted",
  "through",
  "straight through",
  "indirect",
  "face to face",
  "personal",
  "unmediated",
  "head-on",
  "immediate",
  "firsthand",
  "tête-à-tête",
  "exact",
  "absolute",
  "complete",
  "diametrical",
  "downright",
  "thorough",
  "extreme",
  "frank",
  "straightforward",
  "honest",
  "candid",
  "open",
  "sincere",
  "straight",
  "blunt",
  "plain-spoken",
  "outspoken",
  "forthright",
  "downright",
  "uninhibited",
  "unreserved",
  "point blank",
  "no-nonsense",
  "matter-of-fact",
  "bluff",
  "undiplomatic",
  "tactless",
  "explicit",
  "clear",
  "plain",
  "unequivocal",
  "unambiguous",
  "unqualified",
  "categorical",
  "straight to the point",
  "not afraid to call a spade a spade",
  "not beating around the bush",
  "speaking as one finds",
  "evasive",
  "directly",
  "straight",
  "in person",
  "tête-à-tête",
  "without an intermediary",
  "directly",
  "straight",
  "in person",
  "tête-à-tête",
  "without an intermediary",
  "administer",
  "manage",
  "run",
  "control",
  "govern",
  "conduct",
  "handle",
  "lead",
  "head",
  "command",
  "rule",
  "supervise",
  "superintend",
  "oversee",
  "guide",
  "regulate",
  "orchestrate",
  "coordinate",
  "engineer",
  "mastermind",
  "be in charge of",
  "be in control of",
  "be in command of",
  "be the boss of",
  "preside over",
  "exercise control over",
  "be responsible for",
  "be at the helm of",
  "develop",
  "mold",
  "shape",
  "train",
  "teach",
  "instruct",
  "educate",
  "school",
  "tutor",
  "coach",
  "groom",
  "drill",
  "discipline",
  "prime",
  "prepare",
  "guide",
  "inform",
  "verse",
  "enlighten",
  "inculcate",
  "indoctrinate",
  "edify",
  "cultivate",
  "improve",
  "better",
  "uplift",
  "elevate",
  "aim",
  "point",
  "level",
  "turn on",
  "address to",
  "intend for",
  "mean for",
  "destine for",
  "focus on",
  "train on",
  "fix on",
  "guide",
  "steer",
  "lead",
  "conduct",
  "accompany",
  "usher",
  "escort",
  "navigate",
  "pilot",
  "give directions to",
  "show/point/indicate the way",
  "address",
  "label",
  "superscribe",
  "send",
  "mail",
  "dispatch",
  "post",
  "focus",
  "center",
  "centralize",
  "bring to bear",
  "home in on",
  "zero in on",
  "dissipate",
  "target",
  "market",
  "orient toward",
  "pitch to/toward",
  "design for",
  "tailor to",
  "instruct",
  "tell",
  "command",
  "order",
  "charge",
  "call on",
  "require",
  "dictate",
  "adjure",
  "enjoin",
  "bid",
  "give orders to",
];
