export const definitions = [
  '"drill holes through the tiles for the masonry pins"',
  '"a power tool for drilling wood"',
  '"do not attempt to drill through a joist"',
  '"his eyes drilled into her"',
  '"they are licensed to drill for oil in the area"',
  '"I didn\'t like having my teeth drilled, but extractions were worse"',
  '"Rose drilled a ball deep to right center"',
  '"a sergeant was drilling new recruits"',
  '"the troops were drilling"',
  '"I reacted instinctively because I had been drilled to do just that"',
  '"crops drilled in autumn"',
  '"he drilled 100 acres in eight hours"',
];
export const synonyms = [
  "make a hole in",
  "bore",
  "pierce",
  "puncture",
  "penetrate",
  "perforate",
  "sink",
  "bore a hole in",
  "cut a hole in",
  "drill a hole in",
  "punch",
  "gouge",
  "make a hole in",
  "bore",
  "pierce",
  "puncture",
  "penetrate",
  "perforate",
  "sink",
  "bore a hole in",
  "cut a hole in",
  "drill a hole in",
  "punch",
  "gouge",
  "train",
  "instruct",
  "coach",
  "teach",
  "ground",
  "inculcate",
  "discipline",
  "exercise",
  "rehearse",
  "make fit",
  "put someone through their paces",
];
