export const definitions = [
  '"they managed to distill a small quantity of water"',
  '"whiskey is distilled from a mash of grains"',
  '"distill the leaves of some agrimony"',
  '"coal tar is made by distilling out the volatile products in coal"',
  '"she drew back from the dank breath that distilled out of the earth"',
  '"my travel notes were distilled into a book"',
];
export const synonyms = [
  "purify",
  "refine",
  "filter",
  "treat",
  "process",
  "sublime",
  "sublimate",
  "fractionate",
  "vaporize/evaporate and condense",
  "brew",
  "ferment",
  "make",
  "extract",
  "squeeze out",
  "express",
  "draw out",
  "take out",
  "press out",
  "boil down",
  "reduce",
  "concentrate",
  "thicken",
  "compress",
  "condense",
  "purify",
  "refine",
  "separate",
  "rectify",
  "emanate",
  "exude",
  "drip",
  "leak",
  "trickle",
  "dribble",
  "flow",
];
