export const definitions = [
  '"a scheme to divert water from the river to irrigate agricultural land"',
  '"an aircraft has diverted and will be with you shortly"',
  '"more of their advertising budget was diverted into promotions"',
  '"public relations policies are sometimes intended to divert attention away from criticism"',
  '"although the audience members were diverted by this new symphony, critics disliked it"',
];
export const synonyms = [
  "reroute",
  "redirect",
  "head off",
  "deflect",
  "avert",
  "transfer",
  "channel",
  "change the course of",
  "draw away",
  "turn aside",
  "distract",
  "detract",
  "sidetrack",
  "put off",
  "lead away",
  "draw away",
  "be a distraction",
  "disturb someone's concentration",
  "focus",
  "amuse",
  "entertain",
  "distract",
  "titillate",
  "delight",
  "beguile",
  "enchant",
  "interest",
  "fascinate",
  "occupy",
  "absorb",
  "engross",
  "rivet",
  "grip",
  "recreate",
  "give pleasure to",
  "hold the attention of",
  "bore",
];
