export const definitions = [
  '"I tried in vain to get a shot of a diving falcon"',
  '"she walked to the deep end, then she dived in"',
  '"he dived off the bridge for a bet"',
  '"the fish dive down to about 1,400 feet and then swim southwest"',
  '"he had been diving in the area to test equipment"',
  '"the aircraft dove for the ground to avoid the attack"',
  '"a bullet passed close to his head and he dived for cover"',
  '"profits before tax dived by 61 percent"',
  '"Stein was booked for diving"',
];
export const synonyms = [
  "plunge",
  "plummet",
  "nosedive",
  "descend",
  "jump",
  "fall",
  "drop",
  "swoop",
  "pitch",
  "bellyflop",
  "submerge",
  "sink",
  "snorkel",
  "scuba dive",
  "swim under water",
  "go under water",
  "leap",
  "jump",
  "lunge",
  "bolt",
  "dart",
  "dash",
  "rush",
  "scurry",
  "duck",
  "dodge",
  "launch oneself",
  "throw oneself",
  "go headlong",
];
