export const definitions = [
  '"he had to pacify angry spectators"',
  '"the general pacified northern Italy"',
];
export const synonyms = [
  "placate",
  "appease",
  "calm",
  "conciliate",
  "propitiate",
  "assuage",
  "mollify",
  "soothe",
  "tranquillize",
  "content",
  "still",
  "silence",
  "relax",
  "compose",
  "quieten",
  "quiet",
  "calm down",
  "provoke",
  "enrage",
  "inflame",
];
