export const definitions = [
  '"sow seeds 2 to 3 inches apart or as recommended on the seed packets"',
  '"he smoked a packet of cigarettes a day"',
  '"reusable alternatives will be available to encourage customers to stop using the packets"',
  '"a hectic social life could cost a packet"',
  '"I grew my own sunflowers and packeted the seeds"',
  '"packeted fruit pies"',
];
export const synonyms = [
  'pack',
  'carton',
  'box',
  'container',
  'case',
  'package',
  'parcel',
  'cardboard box',
  'padded bag',
  'Jiffy bag',
  'a fortune',
  'a king\'s ransom',
  'a considerable/vast/large sum of money',
  'ferry boat',
  'packet boat',
  'shuttle',
  'ship',
  'boat',
  'vessel',
  'traghetto',
  'passenger boat',
  'passenger ship',
  'car ferry',
  'train ferry',
  'drive-on ferry',
  'roll-on/roll-off ferry',
  'pont',
  'tie (up)',
  'do up',
  'pack (up)',
  'package',
  'wrap (up)',
  'roll (up)',
  'wind up',
  'furl',
  'bale',
  'tie together',
  'pack together',
  'parcel (up)',
  'fold (up)',
  'bind (up)',
  'fasten together',
  'truss (up)',
  'undo',
];