export const definitions = [
  '"both mother and daughter were wrapped up warm in padded jackets"',
  '"the chair has a padded seat and back"',
  '"a padded envelope"',
  '"the boxing gloves are padded with impact-resistant foam rubber"',
  '"wrap dishes and glassware individually, and pad the box with paper or bubble wrap"',
  '"don\'t pad out your answer to make it seem impressive"',
  '"the short review is padded with irrelevant blather about "Monty Python""',
  '"the indictment alleges that he padded expenses and claimed wages for work he didn\'t do "',
  '"she padded along the corridor"',
  '"he was padding the streets"',
];
export const synonyms = [
  "stuff",
  "fill",
  "pack",
  "line",
  "wad",
  "upholster",
  "cushion",
  "spin out",
  "fill out",
  "augment",
  "amplify",
  "increase",
  "add to",
  "lengthen",
  "overdo",
  "protract",
  "elaborate",
  "stretch out",
  "eke out",
  "flesh out",
  "condense",
  "tighten up",
  "shuffle",
  "soft-shoe",
  "walk quietly",
  "tread softly",
  "walk barefoot",
  "walk in stockinged feet",
  "walk in slippers",
];
