export const definitions = [
  '"we got acquainted but we never really palled around"',
  '"the novelty of the quiet life palled"',
];
export const synonyms = [
  "mix",
  "mingle",
  "socialize",
  "get together",
  "go around",
  "fraternize",
  "consort",
  "rub elbows",
  "keep company",
  "rub shoulders",
  "have dealings",
  "wear off",
  "cloy",
  "bore",
  "tire",
  "fatigue",
  "weary",
  "sicken",
  "nauseate",
  "irritate",
  "irk",
  "become/grow tedious",
  "become/grow boring",
  "become/grow tiresome",
  "lose its/their interest",
  "lose attraction",
];
