export const definitions = [
  '"she would earn a paltry $33 more each month"',
  '"naval glory struck him as paltry"',
];
export const synonyms = [
  "small",
  "meager",
  "trifling",
  "insignificant",
  "negligible",
  "inadequate",
  "insufficient",
  "scant",
  "scanty",
  "derisory",
  "pitiful",
  "pitiable",
  "pathetic",
  "miserable",
  "sorry",
  "wretched",
  "puny",
  "trivial",
  "beggarly",
  "mean",
  "ungenerous",
  "inappreciable",
  "mere",
  "exiguous",
  "considerable",
  "substantial",
  "worthless",
  "petty",
  "trivial",
  "unimportant",
  "insignificant",
  "inconsequential",
  "meaningless",
  "negligible",
  "nugatory",
  "minor",
  "footling",
  "contemptible",
  "of little account/consequence",
  "important",
  "significant",
  "valuable",
];
