export const definitions = [
  '"her ankle was very painful"',
  '"a painful knock"',
  '"a painful experience"',
  '"change is inevitably slow and painful"',
];
export const synonyms = [
  "sore",
  "hurting",
  "hurt",
  "tender",
  "aching",
  "throbbing",
  "smarting",
  "burning",
  "irritating",
  "agonizing",
  "excruciating",
  "distressing",
  "unpleasant",
  "nasty",
  "bitter",
  "awful",
  "disquieting",
  "disturbing",
  "upsetting",
  "traumatic",
  "miserable",
  "wretched",
  "sad",
  "heartbreaking",
  "heart-rending",
  "agonizing",
  "harrowing",
  "mortifying",
  "unendurable",
  "unbearable",
  "torturous",
  "cruel",
  "uncomfortable",
  "disagreeable",
  "distressful",
  "pleasant",
  "agreeable",
];
