export const definitions = [
  '"the festival began with a parade of the competitors"',
  '"a military parade"',
  '"the men massed for parade"',
  '"the parade of Hollywood celebrities who troop onto his show"',
  '"the parade of lunacy and corruption will continue"',
  '"we were walking along South Parade"',
  '"a shopping parade"',
  '"officers will parade through the town center"',
  '"carefree young men were parading the streets"',
  '"guards dragged him from his home and paraded him through the streets"',
  '"he paraded his knowledge"',
  '"these untruths parading as history"',
  '"the recruits were due to parade that day"',
];
export const synonyms = [
  'procession',
  'march',
  'cavalcade',
  'motorcade',
  'carcade',
  'cortège',
  'ceremony',
  'spectacle',
  'display',
  'pageant',
  'concours',
  'file',
  'train',
  'column',
  'array',
  'review',
  'muster',
  'dress parade',
  'tattoo',
  'yatra',
  'mas',
  'march-past',
  'jatha',
  'rath yatra',
  'procession',
  'march',
  'cavalcade',
  'motorcade',
  'carcade',
  'cortège',
  'ceremony',
  'spectacle',
  'display',
  'pageant',
  'concours',
  'file',
  'train',
  'column',
  'array',
  'review',
  'muster',
  'dress parade',
  'tattoo',
  'yatra',
  'mas',
  'march-past',
  'jatha',
  'rath yatra',
  'exhibition',
  'show',
  'display',
  'performance',
  'production',
  'spectacle',
  'demonstration',
  'fuss',
  'bother',
  'to-do',
  'commotion',
  'ado',
  'promenade',
  'walk',
  'walkway',
  'esplanade',
  'mall',
  'boardwalk',
  'alameda',
  '(shopping) mall',
  'galleria',
  'marketplace',
  'mart',
  'flea market',
  'fair',
  'bazaar',
  'piazza',
  'plaza',
  'strip mall',
  'souk',
  'agora',
  'emporium',
  'shopping precinct',
  'shopping complex',
  '(shopping) arcade',
  '(shopping) parade',
  'march',
  'process',
  'file',
  'troop',
  'promenade',
  'go in columns',
  'pass in formation',
  'display',
  'exhibit',
  'flaunt',
  'show',
  'show off',
  'demonstrate',
  'air',
  'make a show of',
  'draw attention to',
];