export const definitions = [
  '"a brown paper parcel"',
  '"a parcel bomb"',
  '"a parcel of shares"',
  '"she decided to divide her property into three parcels and invite sealed bids"',
  '"an inversion forms a barrier to a rising parcel of air"',
  '"he parceled up the goods and sent them back"',
  '"they will start parceling out radio frequencies for digital cordless telephones"',
];
export const synonyms = [
  "package",
  "packet",
  "pack",
  "carton",
  "bundle",
  "box",
  "case",
  "bale",
  "fardel",
  "group",
  "band",
  "pack",
  "gang",
  "crowd",
  "mob",
  "company",
  "collection",
  "horde",
  "party",
  "troop",
  "plot",
  "piece",
  "patch",
  "tract",
  "area",
  "section",
  "allotment",
  "lot",
  "plat",
  "pack",
  "pack up",
  "package",
  "wrap",
  "wrap up",
  "gift-wrap",
  "tie up",
  "do up",
  "box",
  "box up",
  "bundle up",
  "fasten together",
  "distribute",
  "allocate",
  "allot",
  "apportion",
  "hand out",
  "give out",
  "dispense",
  "split up",
  "carve up",
  "divide up",
  "portion out",
  "share out",
  "deal out",
  "dole out",
  "mete out",
];
