export const definitions = [
  '"he parked his car outside her house"',
  '"she couldn\'t find anywhere to park"',
  '"come on in, and park your bag by the door"',
  '"after dinner, we parked ourselves on a pair of couches"',
  '"could I suggest we park that suggestion for the moment?"',
];
export const synonyms = [
  "leave",
  "station",
  "position",
  "stop",
  "pull up",
  "put",
  "put down",
  "place",
  "deposit",
  "set",
  "set down",
  "leave",
  "stick",
  "shove",
  "dump",
  "plump",
  "sit down",
  "flump",
  "perch",
  "seat oneself",
  "settle (oneself)",
  "install oneself",
  "plant oneself",
  "ensconce oneself",
  "plump oneself",
  "plop oneself",
];
