export const definitions = [
  '"when coating walls with fabric, paste the wall, not the fabric"',
  '"ads are pasted on the walls"',
  '"he pasted the guy and tied his ankles together"',
];
export const synonyms = [
  'glue',
  'stick',
  'fasten',
  'gum',
  'fix',
  'affix',
  'beat',
  'conquer',
  'get the better of',
  'best',
  'worst',
  'vanquish',
  'rout',
  'trounce',
  'overcome',
  'overpower',
  'overthrow',
  'overwhelm',
  'crush',
  'quash',
  'bring someone to their knees',
  'quell',
  'subjugate',
  'subdue',
  'repulse',
  'win against',
  'win a victory over',
  'triumph over',
  'prevail over',
  'lose to',
];