export const definitions = [
  '"future issues will demonstrate work with pastels and marker pens"',
  '"a pastel drawing"',
  '"a pastel entitled \"Girl Braiding Her Hair.\""',
  '"the subtlest of pastels and creams"',
  '"pastel blue curtains"',
];
export const synonyms = [
  'pale',
  'soft',
  'delicate',
  'light',
  'light-colored',
  'light-toned',
  'muted',
  'subtle',
  'subdued',
  'faint',
  'soft-hued',
  'low-key',
  'understated',
  'dark',
  'bright',
  'vivid',
];