export const definitions = [
  '"the horse rose on its strong haunches, its forelegs pawing the air"',
  '"young dogs may paw at the floor and whine"',
  '"some overweight, ugly Casanova had tried to paw her"',
];
export const synonyms = [
  "poke",
  "finger",
  "thumb",
  "pull",
  "grab",
  "maul",
  "manhandle",
  "mangle",
  "mess up",
  "handle roughly/carelessly/clumsily",
  "poke",
  "finger",
  "thumb",
  "pull",
  "grab",
  "maul",
  "manhandle",
  "mangle",
  "mess up",
  "fondle",
  "feel",
  "molest",
  "handle roughly/carelessly/clumsily",
];
