export const definitions = [
  '"the supplier of goods or services can become liable for breach of contract in a variety of ways"',
  '"patients were liable to faint if they stood up too suddenly"',
  '"areas liable to flooding"',
];
export const synonyms = [
  "responsible",
  "accountable",
  "answerable",
  "chargeable",
  "blameworthy",
  "at fault",
  "culpable",
  "subject",
  "guilty",
  "faulty",
  "censurable",
  "legally responsible",
  "exempt",
  "unaccountable",
  "likely",
  "inclined",
  "tending",
  "disposed",
  "apt",
  "predisposed",
  "prone",
  "given",
  "unlikely",
  "exposed",
  "open",
  "prone",
  "subject",
  "susceptible",
  "vulnerable",
  "in danger of",
  "at the mercy of",
  "at risk of",
  "immune",
  "above",
];
