export const definitions = [
  '"the light of the sun"',
  '"the street lamps shed a faint light into the room"',
  '"a light came on in his room"',
  '"Christmas lights"',
  '"turn right at the light"',
  '"the plant requires good light"',
  '"in some lights she could look beautiful"',
  '"a shrewd light entered his eyes"',
  '"leaving the police to do the job according to their lights"',
  '"she saw light dawn on the woman\'s face"',
  '"sunshine will brighten the natural lights in your hair"',
  '"he asked me for a light"',
  '"the bedroom has a wide bay with leaded lights"',
  '"volunteers have been the shining lights of the community"',
  '"the room was lighted by a number of small lamps"',
  '"only one of the table lamps was lit"',
  '"Allen gathered sticks and lit a fire"',
  '"the gas wouldn\'t light properly"',
  '"he lit on a possible solution"',
  '"from the horse he lit down"',
  '"a feather just lighted on the ground"',
];
export const synonyms = [
  "illumination",
  "brightness",
  "luminescence",
  "luminosity",
  "shining",
  "gleaming",
  "gleam",
  "brilliance",
  "radiance",
  "luster",
  "glowing",
  "glow",
  "blaze",
  "glare",
  "dazzle",
  "incandescence",
  "phosphorescence",
  "sunlight",
  "moonlight",
  "starlight",
  "lamplight",
  "firelight",
  "gaslight",
  "effulgence",
  "refulgence",
  "lambency",
  "fulguration",
  "daylight",
  "daytime",
  "day",
  "electric light",
  "ray of light",
  "shaft of light",
  "beam of light",
  "light of day",
  "natural light",
  "daylight hours",
  "hours of sunlight",
  "darkness",
  "nighttime",
  "lamp",
  "flashlight",
  "headlight",
  "headlamp",
  "sidelight",
  "street light",
  "floodlight",
  "lantern",
  "candle",
  "taper",
  "beacon",
  "torch",
  "wall light",
  "standard lamp",
  "talent",
  "skill",
  "ability",
  "intelligence",
  "intellect",
  "knowledge",
  "understanding",
  "mental powers",
  "aspect",
  "angle",
  "slant",
  "approach",
  "interpretation",
  "viewpoint",
  "standpoint",
  "context",
  "point of view",
  "vantage point",
  "appearance",
  "guise",
  "hue",
  "complexion",
  "understanding",
  "enlightenment",
  "illumination",
  "comprehension",
  "insight",
  "awareness",
  "knowledge",
  "elucidation",
  "explanation",
  "clarification",
  "edification",
  "ignorance",
  "match",
  "flame",
  "spark",
  "(cigarette) lighter",
  "source of fire",
  "expert",
  "authority",
  "master",
  "leader",
  "guru",
  "leading light",
  "luminary",
  "celebrity",
  "dignitary",
  "worthy",
  "VIP",
  "big name",
  "star",
  "guiding light",
  "public figure",
  "set fire to",
  "ignite",
  "kindle",
  "burn",
  "fire",
  "touch off",
  "start",
  "torch",
  "enkindle",
  "set alight",
  "set light to",
  "set burning",
  "set on fire",
  "put/set a match to",
  "spark (off)",
  "extinguish",
  "put out",
  "come across",
  "hit on",
  "find",
  "discover",
  "uncover",
  "encounter",
  "think of",
  "come up with",
  "chance on",
  "happen on",
  "stumble on/across",
  "blunder on",
  "arrive at",
];
