export const definitions = [
  '"I have to practice to keep myself limber"',
  '"limber graphite fishing rods"',
  '"the acrobats were limbering up for the big show"',
  '"a six-horse limbered gun"',
];
export const synonyms = [
  "lithe",
  "supple",
  "nimble",
  "lissom",
  "flexible",
  "fit",
  "spry",
  "sprightly",
  "agile",
  "acrobatic",
  "quick-moving",
  "deft",
  "willowy",
  "graceful",
  "loose-jointed",
  "loose-limbed",
  "active",
  "lively",
  "in good condition",
  "stiff",
  "unfit",
  "lithe",
  "supple",
  "nimble",
  "lissom",
  "flexible",
  "fit",
  "spry",
  "sprightly",
  "agile",
  "acrobatic",
  "quick-moving",
  "deft",
  "willowy",
  "graceful",
  "loose-jointed",
  "loose-limbed",
  "active",
  "lively",
  "in good condition",
  "stiff",
  "unfit",
  "warm up",
  "loosen up",
  "prepare",
  "practice",
  "train",
  "drill",
  "stretch",
  "exercise",
  "work out",
  "get into condition",
  "get into shape",
  "get ready",
];
