export const definitions = ['"long-limbed"', '"long-limbed"'];
export const synonyms = [
  "arm",
  "leg",
  "wing",
  "extremity",
  "appendage",
  "protuberance",
  "projection",
  "member",
  "branch",
  "bough",
  "arm",
  "leg",
  "wing",
  "extremity",
  "appendage",
  "protuberance",
  "projection",
  "member",
  "branch",
  "bough",
];
