export const definitions = [
  '"a lining of fireproof insulation"',
  '"lining paper"',
  '"leather gloves with fur linings"',
  '"a processional route lined by people waving flags"',
  '"deep wrinkles lined his face"',
  '"a basket lined with polyethylene"',
  '"hundreds of telegrams lined the walls"',
];
export const synonyms = [
  'backing',
  'interlining',
  'facing',
  'inlay',
  'reinforcement',
  'liner',
  'paneling',
  'quilting',
  'cushioning',
  'padding',
  'wadding',
  'stuffing',
  'filling',
  'border',
  'edge',
  'fringe',
  'bound',
  'skirt',
  'hem',
  'rim',
  'furrow',
  'wrinkle',
  'crease',
  'crinkle',
  'pucker',
  'corrugate',
  'mark with lines',
  'cover with lines',
  'covered',
  'backed',
  'interlined',
  'faced',
  'paneled',
  'inlaid',
  'reinforced',
  'encased',
  'papered',
  'decorated',
  'stuffed',
  'filled',
  'packed',
  'padded',
  'ceiled',
  'cover',
  'back',
  'interline',
  'face',
  'panel',
  'inlay',
  'reinforce',
  'encase',
  'paper',
  'decorate',
  'stuff',
  'fill',
  'pack',
  'pad',
  'ceil',
  'put a lining in',
  'put a backing on',
  'cover',
  'back',
  'interline',
  'face',
  'panel',
  'inlay',
  'reinforce',
  'encase',
  'paper',
  'decorate',
  'stuff',
  'fill',
  'pack',
  'pad',
  'ceil',
  'put a lining in',
  'put a backing on',
];