export const definitions = [
  '"yeomen of the guard wearing a royal red and gold livery"',
  '"pageboys in scarlet and green livery"',
  '"the city\'s trams are painted in a red and white livery"',
  '"he was short with livery lips"',
  '"port always makes you livery"',
];
export const synonyms = [
  'uniform',
  'regalia',
  'costume',
  'dress',
  'attire',
  'habit',
  'garb',
  'clothes',
  'clothing',
  'outfit',
  'suit',
  'garments',
  'ensemble',
  'robes',
  'finery',
  'apparel',
  'raiment',
  'array',
  'vestments',
];