export const definitions = [
  '"this lady is going to act as our guide for the rest of the tour"',
  '"his spiritual guide"',
  '"here is a guide to the number of curtain hooks you will need"',
  '"a guide to baby and toddler care"',
  '"the guides for the bolt needed straightening"',
  '"he guided her to the front row and sat beside her"',
  '"the groove in the needle guides the thread"',
  '"he guided the team to a second successive win in the tournament"',
];
export const synonyms = [
  "escort",
  "attendant",
  "conductor",
  "pilot",
  "usher",
  "chaperone",
  "courier",
  "cicerone",
  "convoy",
  "adviser",
  "mentor",
  "counselor",
  "confidant",
  "tutor",
  "teacher",
  "guru",
  "consultant",
  "therapist",
  "guidance counselor",
  "model",
  "pattern",
  "blueprint",
  "template",
  "archetype",
  "prototype",
  "sample",
  "example",
  "exemplar",
  "standard",
  "touchstone",
  "measure",
  "benchmark",
  "yardstick",
  "gauge",
  "norm",
  "paradigm",
  "ideal",
  "precedent",
  "guiding principle",
  "guidebook",
  "Baedeker",
  "travelogue",
  "directory",
  "handbook",
  "manual",
  "ABC",
  "vade mecum",
  "enchiridion",
  "tourist guide",
  "travel guide",
  "A to Z",
  "lead",
  "lead the way",
  "conduct",
  "show",
  "usher",
  "shepherd",
  "direct",
  "steer",
  "pilot",
  "escort",
  "accompany",
  "attend",
  "see",
  "take",
  "help",
  "assist",
  "show someone the way",
  "follow",
  "direct",
  "steer",
  "control",
  "manage",
  "command",
  "lead",
  "conduct",
  "run",
  "govern",
  "rule",
  "superintend",
  "supervise",
  "oversee",
  "handle",
  "regulate",
  "manipulate",
  "maneuver",
  "advise",
  "counsel",
  "inform",
  "illuminate",
  "educate",
  "instruct",
  "teach",
  "be in charge of",
  "take charge of",
  "take control of",
  "have control of",
  "preside over",
  "give advice to",
  "give counsel to",
  "give counseling to",
  "give direction to",
  "make recommendations to",
  "make suggestions to",
  "give someone tips",
  "give someone hints",
  "give someone pointers",
  "give information to",
  "give instruction to",
  "be responsible for the education of",
];
