export const definitions = [
  '"he was found guilty of manslaughter"',
  '"the police will soon discover who the guilty party is"',
  '"he found them guilty on a lesser charge"',
  '"she was guilty of a serious error of judgment"',
  '"John felt guilty at having deceived the family"',
  '"she wrestled with a guilty conscience after her adultery"',
  '"a guilty verdict"',
  '"I have no guilty secret to reveal"',
];
export const synonyms = [
  "culpable",
  "blameworthy",
  "blameable",
  "at fault",
  "in the wrong",
  "responsible",
  "answerable",
  "accountable",
  "liable",
  "censurable",
  "reproachable",
  "condemnable",
  "reprehensible",
  "erring",
  "errant",
  "delinquent",
  "offending",
  "sinful",
  "felonious",
  "iniquitous",
  "criminal",
  "convicted",
  "peccant",
  "to blame",
  "innocent",
  "ashamed",
  "guilt-ridden",
  "conscience-stricken",
  "remorseful",
  "sorry",
  "regretful",
  "contrite",
  "repentant",
  "penitent",
  "rueful",
  "abashed",
  "shamefaced",
  "sheepish",
  "hangdog",
  "mortified",
  "discomfited",
  "distressed",
  "uncomfortable",
  "compunctious",
  "in sackcloth and ashes",
  "unrepentant",
];
