export const definitions = [];
export const synonyms = [
  "association",
  "society",
  "union",
  "league",
  "alliance",
  "coalition",
  "federation",
  "consortium",
  "syndicate",
  "combine",
  "trust",
  "organization",
  "company",
  "cooperative",
  "partnership",
  "fellowship",
  "club",
  "order",
  "lodge",
  "sisterhood",
  "sorority",
  "brotherhood",
  "fraternity",
  "consociation",
  "sodality",
];
