export const definitions = [
  '"he smiled and gulped his milk"',
  '"we emerged to gulp great lungfuls of cold night air"',
  '"she gulped back the tears"',
  '"fumes seeped in until she was forced to gulp for air"',
];
export const synonyms = [
  "swallow",
  "quaff",
  "down",
  "gobble",
  "guzzle",
  "bolt",
  "wolf",
  "cram",
  "stuff",
  "devour",
  "swill down",
  "drain one's glass",
  "gorge (oneself) on",
  "eat greedily",
  "eat hungrily",
  "sip",
  "pick at",
  "draw",
  "pull",
  "breathe",
  "gasp",
  "sniff",
  "inhale",
  "inspire",
  "respire",
  "choke back",
  "fight back",
  "hold back",
  "hold in",
  "keep back",
  "restrain",
  "suppress",
  "stifle",
  "smother",
  "strangle",
  "muffle",
  "quench",
  "curb",
  "check",
  "withhold",
  "contain",
  "bottle up",
  "let out",
];
