export const definitions = ['"Rose eyed him warily"'];
export const synonyms = [
  "see",
  "observe",
  "view",
  "scan",
  "regard",
  "contemplate",
  "survey",
  "inspect",
  "examine",
  "scrutinize",
  "study",
  "consider",
  "watch",
  "keep an eye on",
  "monitor",
  "keep a weather eye on",
  "behold",
  "twig",
  "surveil",
  "ogle",
  "make sheep's eyes at",
  "look at",
  "gaze at",
  "gaze upon",
  "stare at",
  "glance at",
  "take a glance at",
  "keep under observation",
  "keep watch on",
  "keep under scrutiny",
  "keep under surveillance",
  "watch like a hawk",
  "spy on",
  "leer at",
  "make eyes at",
  "ignore",
];
