export const definitions = [
  '"they nattered away for hours"',
  '"I could do with a drink and a natter"',
];
export const synonyms = [
  "chat",
  "chatter",
  "prattle",
  "prate",
  "go on",
  "run on",
  "gossip",
  "tittle-tattle",
  "tattle",
  "ramble",
  "gabble",
  "jabber",
  "babble",
  "blather",
  "blether",
  "blither",
  "twitter",
  "maunder",
  "drivel",
  "patter",
  "yap",
  "jibber-jabber",
  "cackle",
  "talk nineteen to the dozen",
  "slabber",
  "twaddle",
  "clack",
  "talk idly",
  "rattle on/away",
  "twattle",
  "claver",
  "chat",
  "talk",
  "conversation",
  "gossip",
  "chatter",
  "chitter-chatter",
  "heart-to-heart",
  "tête-à-tête",
  "blether",
  "blather",
  "conference",
  "discussion",
  "dialogue",
  "exchange",
  "confabulation",
  "colloquy",
  "adda",
];
