export const definitions = [
  '"the breathtaking beauty of nature"',
  '"it is impossible to change the laws of nature"',
  '"helping them to realize the nature of their problems"',
  '"there are a lot of other documents of that nature"',
  '"it\'s not in her nature to listen to advice"',
  '"I\'m not violent by nature"',
  '"Emerson was so much more luminous a nature"',
];
export const synonyms = [
  "Mother Nature",
  "creation",
  "the world",
  "the environment",
  "Mother Earth",
  "the universe",
  "wildlife",
  "countryside",
  "landscape",
  "scenery",
  "the natural world",
  "the living world",
  "the earth",
  "the cosmos",
  "natural forces",
  "flora and fauna",
  "essence",
  "character",
  "identity",
  "complexion",
  "kind",
  "sort",
  "type",
  "variety",
  "description",
  "category",
  "ilk",
  "class",
  "classification",
  "species",
  "genre",
  "style",
  "cast",
  "order",
  "kidney",
  "mold",
  "stamp",
  "grain",
  "stripe",
  "inherent/basic/essential characteristics",
  "inherent/basic/essential qualities",
  "inherent/basic/essential attributes",
  "inherent/basic/essential features",
  "sum and substance",
  "character",
  "personality",
  "disposition",
  "temperament",
  "temper",
  "humor",
  "makeup",
  "persona",
  "psyche",
  "constitution",
  "fiber",
  "cast/turn of mind",
];
