export const definitions = [
  '"his eyelids were leaden with sleep"',
  '"the snow fell from a leaden sky"',
  '"a leaden coffin"',
];
export const synonyms = [
  "dull",
  "heavy",
  "weighty",
  "listless",
  "lifeless",
  "inactive",
  "inert",
  "sluggish",
  "lumbering",
  "plodding",
  "cumbersome",
  "slow",
  "torpid",
  "labored",
  "light",
  "springy",
  "gray",
  "grayish",
  "black",
  "dark",
  "ashen",
  "cloudy",
  "gloomy",
  "overcast",
  "somber",
  "dim",
  "sunless",
  "starless",
  "louring",
  "oppressive",
  "threatening",
  "dreary",
  "dismal",
  "dingy",
  "bleak",
  "dull",
  "murky",
  "sullen",
  "cheerless",
  "depressing",
  "tenebrous",
  "Cimmerian",
  "caliginous",
  "gray-colored",
  "bright",
  "cheerful",
];
