export const definitions = [
  '"the leader of a protest group"',
  '"a leader in the use of video conferencing"',
];
export const synonyms = [
  "chief",
  "head",
  "principal",
  "boss",
  "commander",
  "captain",
  "figurehead",
  "controller",
  "superior",
  "kingpin",
  "headman",
  "mover and shaker",
  "chairman",
  "chairwoman",
  "chairperson",
  "chair",
  "convener",
  "moderator",
  "director",
  "managing director",
  "MD",
  "manager",
  "superintendent",
  "supervisor",
  "overseer",
  "administrator",
  "employer",
  "master",
  "mistress",
  "foreman",
  "president",
  "premier",
  "governor",
  "ruler",
  "monarch",
  "king",
  "queen",
  "sovereign",
  "emperor",
  "tsar",
  "prince",
  "princess",
  "lord",
  "elder",
  "patriarch",
  "guru",
  "mentor",
  "authority",
  "lord and master",
  "follower",
  "supporter",
  "pioneer",
  "front runner",
  "innovator",
  "trailblazer",
  "pathfinder",
  "groundbreaker",
  "trendsetter",
  "leading light",
  "torchbearer",
  "flagbearer",
  "pacemaker",
  "originator",
  "initiator",
  "developer",
  "discoverer",
  "founder",
  "architect",
  "neoteric",
  "guiding light",
];
