export const definitions = [
  '"they\'d started learning French"',
  '"she is learning to play the piano"',
  '"we learn from experience"',
  '"I\'d learned too many grim poems in school"',
  '"I learned that they had eaten already"',
  '"the military learned of a plot to attack the presidential compound"',
  '"\"That\'ll learn you,\" he chuckled"',
  '"we\'ll have to learn you to milk cows"',
];
export const synonyms = [
  'grasp',
  'master',
  'take in',
  'absorb',
  'assimilate',
  'pick up',
  'digest',
  'comprehend',
  'study',
  'pursue',
  'acquire a knowledge of',
  'gain an understanding of',
  'acquire skill in',
  'become competent in',
  'become proficient in',
  'familiarize oneself with',
  'become expert in',
  'know inside out',
  'know backwards',
  'read up on',
  'work at',
  'apply oneself to',
  'be taught',
  'have lessons in',
  'memorize',
  'know',
  'retain',
  'con',
  'learn by heart',
  'learn by rote',
  'commit to memory',
  'become word-perfect in',
  'learn word for word',
  'learn parrot-fashion',
  'get off/down pat',
  'have off/down pat',
  'forget',
  'discover',
  'find out',
  'hear',
  'gather',
  'understand',
  'ascertain',
  'establish',
  'realize',
  'determine',
  'become aware',
  'be made aware',
  'be informed',
  'have it brought to one\'s attention',
  'be given to understand',
  'get to know',
  'come to know',
  'hear tell',
];