export const definitions = [
  '"my grandmother died and unexpectedly left me a small legacy"',
  '"he left us a rich legacy of buildings that are both innovative architectural creations and genuine works of art"',
  '"her legacy will live on for generations to come"',
  '"the legacy of centuries of neglect"',
  '"being a legacy increased a student\'s chance of being accepted to a highly selective college by up to 45 percent"',
  '"integration with legacy systems has been cited as a problem by over half of respondents"',
];
export const synonyms = [
  "bequest",
  "inheritance",
  "heritage",
  "bequeathal",
  "bestowal",
  "benefaction",
  "endowment",
  "gift",
  "patrimony",
  "heirloom",
  "settlement",
  "birthright",
  "provision",
  "devise",
  "hereditament",
  "consequence",
  "effect",
  "outcome",
  "upshot",
  "spin-off",
  "repercussion",
  "aftermath",
  "footprint",
  "byproduct",
  "product",
  "result",
  "residue",
  "fruits",
];
