export const definitions = [
  '"bare-legged women"',
  '"a three-legged dog"',
  '"a three-legged chair"',
  '"wide-legged trousers"',
  '"I am part of a team legging it around London"',
  '"he legged it after someone shouted at him"',
  '"a little boy was lying on his back, legging the boat along"',
];
export const synonyms = [
  'walk',
  'march',
  'tramp',
  'trek',
  'trudge',
  'plod',
  'wander',
  'ramble',
  'go on foot',
  'run away',
  'run',
  'flee',
  'make off',
  'escape',
  'hurry',
  'decamp',
  'make a break for it',
  'stay',
];