export const definitions = [
  '"he was convicted of a lesser assault charge"',
  '"they nest mostly in Alaska and to a lesser extent in Siberia"',
  '"you\'re looking down your nose at us lesser mortals"',
  '"the lesser aristocracy"',
];
export const synonyms = [
  "minor",
  "secondary",
  "subsidiary",
  "marginal",
  "ancillary",
  "auxiliary",
  "supplementary",
  "supplemental",
  "peripheral",
  "inferior",
  "slighter",
  "insignificant",
  "unimportant",
  "petty",
  "lower",
  "lower-level",
  "second-rate",
  "less important",
  "lower-grade",
  "greater",
  "primary",
  "subordinate",
  "minor",
  "inferior",
  "second-class",
  "subservient",
  "lowly",
  "humble",
  "servile",
  "menial",
  "mean",
  "junior",
  "superior",
];
