export const definitions = [
  '"an advanced lesson in math"',
  '"a driving lesson"',
  '"he had a facility for languages and had learned his lessons well"',
  '"the tragedy is a lesson in disappointment"',
  '"let that be a lesson to you!"',
  '"he went up to read the first lesson"',
  '"Metaneone had beforehand lessoned him what he should say"',
  '"Oedipus has been lessoned to humility before the throne of Zeus"',
];
export const synonyms = [
  "class",
  "session",
  "seminar",
  "tutorial",
  "lecture",
  "period",
  "exercise",
  "assignment",
  "drill",
  "homework",
  "period of instruction",
  "period of teaching",
  "period of coaching",
  "period of tutoring",
  "period of schooling",
  "school task",
  "school work",
  "knowledge",
  "wisdom",
  "enlightenment",
  "experience",
  "truths",
  "warning",
  "deterrent",
  "caution",
  "example",
  "exemplar",
  "message",
  "moral",
  "precept",
  "scripture",
  "text",
  "reading",
  "Bible reading",
  "Bible passage",
];
