export const definitions = [
  '"the years have lessened the gap in age between us"',
  '"the warmth of the afternoon lessened"',
];
export const synonyms = [
  "reduce",
  "minimize",
  "decrease",
  "allay",
  "assuage",
  "alleviate",
  "attenuate",
  "palliate",
  "ease",
  "dull",
  "deaden",
  "blunt",
  "take the edge off",
  "moderate",
  "mitigate",
  "check",
  "dampen",
  "depress",
  "soften",
  "tone down",
  "dilute",
  "relax",
  "mollify",
  "temper",
  "weaken",
  "tame",
  "erode",
  "narrow",
  "lower",
  "discount",
  "curtail",
  "prune",
  "truncate",
  "diminish",
  "decline",
  "subside",
  "abate",
  "fade",
  "let up",
  "ease off",
  "tail off",
  "drop",
  "fall",
  "dwindle",
  "shrink",
  "contract",
  "ebb",
  "wane",
  "flag",
  "slacken",
  "lighten",
  "recede",
  "relent",
  "remit",
  "desist",
  "sink",
  "slump",
  "plummet",
  "fall off a cliff",
  "quieten",
  "quiet",
  "degrade",
  "discredit",
  "devalue",
  "belittle",
  "humble",
  "make less",
  "make smaller",
  "pare down",
  "grow less",
  "get less",
  "grow smaller",
  "die down/off",
  "drop off/away",
  "taper off",
  "peter out",
  "go/come down",
  "waste away",
  "increase",
  "magnify",
  "grow",
  "aggrandize",
  "make more important",
];
