export const definitions = [
  '"a lethal cocktail of alcohol and pills"',
  '"the Krakatoa eruption was the most lethal on record"',
];
export const synonyms = [
  'fatal',
  'deadly',
  'mortal',
  'death-dealing',
  'murderous',
  'homicidal',
  'killing',
  'terminal',
  'final',
  'incurable',
  'poisonous',
  'toxic',
  'virulent',
  'noxious',
  'venomous',
  'dangerous',
  'destructive',
  'harmful',
  'pernicious',
  'malignant',
  'disastrous',
  'calamitous',
  'ruinous',
  'deathly',
  'nocuous',
  'mephitic',
  'baneful',
  'causing death',
  'life-threatening',
  'harmless',
  'safe',
];