export const definitions = [
  '"the clerk had levanted before his employer returned from America"',
];
export const synonyms = [
  "withdraw",
  "retire",
  "draw back",
  "pull back",
  "pull out",
  "fall back",
  "give way",
  "give ground",
  "recoil",
  "flee",
  "take flight",
  "beat a hasty retreat",
  "run away",
  "run off",
  "make a run for it",
  "make off",
  "take off",
  "bolt",
  "clear out",
  "escape",
  "fly",
  "beat a retreat",
  "run for it",
  "take to one's heels",
  "make a break for it",
  "make a quick exit",
  "make one's getaway",
  "head for the hills",
  "advance",
  "dig in",
];
