export const definitions = [
  '"heavy silk fabric"',
  '"waterproof fabrics"',
  '"decay and neglect are slowly eating away at the building\'s fabric"',
  '"we heard creaking and rushing noises in the \'s \'s fabric"',
  '"the fabric of society"',
];
export const synonyms = [
  'cloth',
  'material',
  'textile',
  'stuff',
  'tissue',
  'web',
  'structure',
  'framework',
  'frame',
  'form',
  'makeup',
  'constitution',
  'composition',
  'construction',
  'organization',
  'infrastructure',
  'foundations',
  'mechanisms',
  'anatomy',
  'essence',
];