export const definitions = [
  '"the regiment\'s uniforms had orange facings"',
  '"the bricks were used as a facing on a concrete core"',
  '"two large front-facing windows"',
  '"a book with Italian and English lyrics printed on facing pages"',
  '"he turned to face her"',
  '"the house faces due east"',
  '"they immediately faced about"',
  '"honesty forced her to face facts"',
  '"sooner or later you must face the truth"',
  '"each defendant faced a maximum sentence of 10 years"',
  '"if you were suddenly faced with an emergency, would you know how to cope?"',
  '"the external basement walls were faced with granite slabs"',
];
export const synonyms = [
  'covering',
  'trimming',
  'lining',
  'interfacing',
  'reinforcement',
  'backing',
  'cladding',
  'veneer',
  'skin',
  'surface',
  'facade',
  'front',
  'fronting',
  'coating',
  'covering',
  'dressing',
  'overlay',
  'revetment',
  'paving',
  'lamination',
  'inlay',
  'plating',
  'siding',
  'protective/decorative layer',
  'false front',
  'opposing',
  'overlook',
  'give onto',
  'give over',
  'look out on',
  'front onto',
  'look toward',
  'be facing',
  'have/afford/command a view of',
  'look over/across',
  'open out over',
  'look onto',
  'be opposite (to)',
  'back onto',
  'accept',
  'come to terms with',
  'make the best of',
  'confront',
  'brave',
  'face up to',
  'encounter',
  'meet',
  'dare',
  'defy',
  'oppose',
  'resist',
  'withstand',
  'come to accept',
  'become reconciled to',
  'reconcile oneself to',
  'reach an acceptance (of)',
  'get used to',
  'become accustomed to',
  'adjust to',
  'accommodate oneself to',
  'acclimatize oneself to',
  'learn to live with',
  'cope with',
  'deal with',
  'get to grips with',
  'become resigned to',
  'meet head-on',
  'dodge',
  'succumb to',
  'encounter',
  'experience',
  'run into',
  'come across',
  'meet',
  'come up against',
  'be confronted by',
  'be faced with',
  'come into contact with',
  'be forced to contend with',
  'beset',
  'worry',
  'distress',
  'trouble',
  'bother',
  'confront',
  'burden',
  'harass',
  'oppress',
  'vex',
  'irritate',
  'exasperate',
  'strain',
  'stress',
  'tax',
  'torment',
  'plague',
  'blight',
  'bedevil',
  'rack',
  'smite',
  'curse',
  'harrow',
  'discommode',
  'cause trouble to',
  'cover',
  'clad',
  'veneer',
  'skin',
  'overlay',
  'surface',
  'dress',
  'pave',
  'laminate',
  'inlay',
  'plate',
  'coat',
  'line',
  'put a facing on',
];