export const definitions = [
  '"he could not fairly be accused of wasting police time"',
  '"I was fairly certain she had nothing to do with the affair"',
  '"I get along fairly well with everybody"',
  '"he fairly snarled at her"',
];
export const synonyms = [
  "justly",
  "equitably",
  "impartially",
  "without prejudice",
  "without fear or favor",
  "open-mindedly",
  "even-handedly",
  "objectively",
  "neutrally",
  "disinterestedly",
  "properly",
  "lawfully",
  "legally",
  "legitimately",
  "licitly",
  "by the book",
  "equally",
  "without bias",
  "with an open mind",
  "in accordance with the rules",
  "according to the rules",
  "the same",
  "unfairly",
  "reasonably",
  "passably",
  "tolerably",
  "satisfactorily",
  "sufficiently",
  "adequately",
  "moderately",
  "quite",
  "rather",
  "somewhat",
  "relatively",
  "comparatively",
  "insufficiently",
  "extremely",
  "positively",
  "really",
  "veritably",
  "simply",
  "actually",
  "absolutely",
  "decidedly",
  "practically",
  "almost",
  "nearly",
  "all but",
  "to all intents and purposes",
];
