export const definitions = ['"they had famished the city into surrender"'];
export const synonyms = [
  "undernourished",
  "malnourished",
  "starved",
  "half-starved",
  "unfed",
  "ravenous",
  "famished",
  "empty",
  "hollow",
  "fasting",
  "dying of hunger",
  "dying from lack of food",
  "faint from lack of food",
  "deprived of food",
  "very hungry",
  "be hungry",
  "well fed",
  "full",
];
