export const definitions = [
  '"the country is famous for its natural beauty"',
  '"a famous star"',
];
export const synonyms = [
  "well known",
  "celebrated",
  "prominent",
  "famed",
  "popular",
  "renowned",
  "noted",
  "notable",
  "eminent",
  "preeminent",
  "leading",
  "distinguished",
  "esteemed",
  "respected",
  "venerable",
  "august",
  "illustrious",
  "acclaimed",
  "honored",
  "exalted",
  "great",
  "glorious",
  "remarkable",
  "signal",
  "legendary",
  "lionized",
  "notorious",
  "infamous",
  "having made a name for oneself",
  "of high standing",
  "of distinction",
  "of repute",
  "much publicized",
  "unknown",
  "obscure",
];
