export const definitions = [
  '"the family lived in a large house with a lot of land"',
  '"the family home"',
  '"friends and family can provide support"',
  '"I could not turn him away, for he was family"',
  '"she has the sole responsibility for a large family"',
  '"the house has been owned by the same family for 300 years"',
  '"all manuscripts that share this reading constitute a family"',
  '"the cabbage family"',
  '"the Austronesian language family"',
  '"a family newspaper"',
];
export const synonyms = [
  "household",
  "ménage",
  "nuclear family",
  "relatives",
  "relations",
  "blood relations",
  "kin",
  "next of kin",
  "kinsfolk",
  "kinsmen",
  "kinswomen",
  "kindred",
  "connections",
  "extended family",
  "clan",
  "tribe",
  "people",
  "family members",
  "one's(own) flesh and blood",
  "children",
  "youngsters",
  "offspring",
  "progeny",
  "descendants",
  "scions",
  "heirs",
  "brood",
  "issue",
  "little ones",
  "ancestry",
  "parentage",
  "birth",
  "pedigree",
  "genealogy",
  "background",
  "family tree",
  "descent",
  "lineage",
  "line",
  "bloodline",
  "blood",
  "extraction",
  "derivation",
  "race",
  "strain",
  "stock",
  "breed",
  "dynasty",
  "house",
  "forebears",
  "forefathers",
  "antecedents",
  "progenitors",
  "roots",
  "origins",
  "filiation",
  "line of descent",
  "stirps",
  "variety",
  "stock",
  "strain",
  "line",
  "type",
  "kind",
  "sort",
  "class",
  "group",
  "order",
  "class",
  "subclass",
  "genus",
  "species",
  "stock",
  "strain",
  "line",
  "taxon",
  "phylum",
  "taxonomic group",
];
