export const definitions = [
  '"a car with faulty brakes"',
  '"faulty logic"',
  '"her character was faulty"',
];
export const synonyms = [
  "malfunctioning",
  "broken",
  "damaged",
  "defective",
  "out of order",
  "out of commission",
  "inoperative",
  "unsound",
  "unusable",
  "useless",
  "not working",
  "not functioning",
  "in disrepair",
  "working",
  "functioning",
  "defective",
  "flawed",
  "unsound",
  "distorted",
  "inaccurate",
  "incorrect",
  "erroneous",
  "imprecise",
  "fallacious",
  "wrong",
  "impaired",
  "weak",
  "invalid",
  "sound",
];
