export const definitions = [
  '"the legislation is viewed with favor"',
  '"they accused you of showing favor to one of the players"',
  '"good party favors include stickers, hair barrettes, or crayons"',
  '"I\'ve come to ask you a favor"',
  '"she had granted her favors to him"',
  '"slashing public spending is a policy that few politicians favor"',
  '"critics argued that the policy favored the private sector"',
  '"natural selection has favored bats"',
  '"please favor me with an answer"',
  '"she\'s pretty, and she favors you"',
  '"he favors his sore leg"',
];
export const synonyms = [
  'approval',
  'approbation',
  'commendation',
  'esteem',
  'goodwill',
  'kindness',
  'benevolence',
  'friendliness',
  'disfavor',
  'disapproval',
  'favoritism',
  'bias',
  'partiality',
  'prejudice',
  'partisanship',
  'one-sidedness',
  'unfair preference',
  'present',
  'donation',
  'offering',
  'contribution',
  'handout',
  'presentation',
  'bestowal',
  'largesse',
  'alms',
  'charity',
  'bonus',
  'award',
  'premium',
  'bounty',
  'boon',
  'bequest',
  'legacy',
  'inheritance',
  'settlement',
  'subsidy',
  'grant',
  'endowment',
  'benefaction',
  'tip',
  'gratuity',
  'baksheesh',
  'giving',
  'pourboire',
  'perquisite',
  'conferment',
  'ribbon',
  'rosette',
  'badge',
  'token',
  'keepsake',
  'souvenir',
  'memento',
  'remembrancer',
  'token of affection',
  'token of esteem',
  'service',
  'kindness',
  'courtesy',
  'indulgence',
  'benefit',
  'boon',
  'good turn',
  'kind act',
  'good deed',
  'act of kindness',
  'disservice',
  'preferred',
  'favorite',
  'recommended',
  'chosen',
  'choice',
  'selected',
  'ideal',
  'particular',
  'special',
  'pet',
  'advocate',
  'recommend',
  'advise',
  'support',
  'back',
  'champion',
  'stand up for',
  'urge',
  'promote',
  'espouse',
  'endorse',
  'sanction',
  'most-liked',
  'subscribe to',
  'approve of',
  'look on with favor',
  'be in favor of',
  'campaign for',
  'argue for',
  'press for',
  'lobby for',
  'vouch for',
  'oppose',
  'indulge',
  'pamper',
  'spoil',
  'show favoritism toward',
  'have a bias toward',
  'treat with partiality',
  'have as a favorite',
  'think more highly of',
  'hold in higher regard',
  'benefit',
  'oblige',
  'help',
  'assist',
  'aid',
  'advance',
  'abet',
  'succor',
  'serve',
  'do someone a favor',
  'be to the advantage of',
  'be advantageous to',
  'lend a hand to',
  'be of service to',
  'meet the needs of',
  'hinder',
  'oblige',
  'accommodate',
  'gratify',
  'satisfy',
  'humor',
  'indulge',
  'honor',
  'pander to',
  'put oneself out for',
  'resemble',
  'bear a resemblance to',
  'take after',
  'look like',
  'be like',
  'be similar to',
  'remind one of',
  'put one in mind of',
  'have the look of',
  'bear semblance to',
  'differ from',
];