export const definitions = [
  '"the four ringleaders were sentenced to the gibbet"',
  '"poor Melbourne is gibbeted in The Times"',
];
export const synonyms = [
  "scaffold",
  "derrick",
  "nub",
  "gallow-tree",
  "Gregorian tree",
  "three-legged mare",
  "nubbing cheat",
  "leafless tree",
  "triple tree",
  "Tyburn tree",
  "lynch",
  "execute by hanging",
  "hang by the neck",
  "send to the gallows",
  "send to the gibbet",
  "send to the scaffold",
  "put to death",
  "hanging",
  "gibbeting",
  "execution",
  "capital punishment",
  "death sentence/penalty",
];
