export const definitions = [
  "\"that's salesmanship, you have to gyp people into buying stuff they don't like\"",
];
export const synonyms = [
  "deceive",
  "trick",
  "dupe",
  "outwit",
  "fool",
  "delude",
  "cheat",
  "take in",
  "bluff",
  "hoax",
  "mislead",
  "misguide",
  "lead on",
  "defraud",
  "double-cross",
  "swindle",
  "gull",
  "finagle",
  "get the better of",
  "cozen",
  "sharp",
  "befool",
  "mulct",
];
