export const definitions = [
  '"girly pink paper"',
  '"they liked skipping and picking flowers and doing very girly things"',
  '"don\'t get all girly and cute"',
  '"girlie magazines"',
  '"what\'s your name, girlie ? "',
];
export const synonyms = [
  'womanly',
  'womanlike',
  'ladylike',
  'girlish',
  'female',
  'soft',
  'delicate',
  'gentle',
  'tender',
  'graceful',
  'refined',
  'modest',
  'feminal',
  'young lady',
  'miss',
  'lass',
  'lassie',
  'colleen',
  'mademoiselle',
  'signorina',
  'señorita',
  'Fräulein',
  'maid',
  'maiden',
  'damsel',
  'demoiselle',
  'wench',
  'young woman',
];