export const definitions = [
  '"a giant among sportsmen"',
  '"giant multinational corporations"',
  '"a giant meteorite"',
  '"a giant transport plane"',
];
export const synonyms = [
  'colossus',
  'behemoth',
  'Brobdingnagian',
  'mammoth',
  'leviathan',
  'monster',
  'monstrosity',
  'ogre',
  'man mountain',
  'dwarf',
  'huge',
  'colossal',
  'massive',
  'enormous',
  'gigantic',
  'great',
  'mammoth',
  'vast',
  'immense',
  'tremendous',
  'mighty',
  'stupendous',
  'monumental',
  'epic',
  'prodigious',
  'mountainous',
  'monstrous',
  'titanic',
  'towering',
  'elephantine',
  'king-sized',
  'king-size',
  'gargantuan',
  'Herculean',
  'Brobdingnagian',
  'substantial',
  'extensive',
  'hefty',
  'bulky',
  'weighty',
  'heavy',
  'gross',
  'very big',
  'very large',
  'miniature',
];