export const definitions = [
  '"no amount of struggle availed Charles"',
  '"you can avail discounts on food"',
  '"he begged her to reconsider, but to no avail"',
  '"calls to tech support have been of no avail"',
  '"Latin was of little avail in the practical affairs of life"',
];
export const synonyms = [
  "help",
  "aid",
  "assist",
  "benefit",
  "profit",
  "be of use to",
  "be useful to",
  "be of advantage to",
  "be of service to",
  "in vain",
  "unsuccessfully",
  "vainly",
  "fruitlessly",
  "to no purpose",
  "for nothing",
  "without success",
  "with no result",
  "bootlessly",
  "successfully",
];
