export const definitions = [
  '"he chose John Stuart Mill as the avatar of the liberal view"',
  '"conversation is depicted in a balloon over the avatar\'s head"',
];
export const synonyms = [
  "deity",
  "god",
  "goddess",
  "mother goddess",
  "creator",
  "demiurge",
  "godhead",
  "daemon",
  "numen",
  "power",
  "divine being",
  "celestial being",
  "supreme being",
  "embodiment",
  "personification",
  "exemplification",
  "type",
  "epitome",
  "manifestation",
  "bodily form",
  "representation in the flesh",
];
