export const definitions = [
  '"the trainees were coaxed into doing boring work"',
  '"he was coaxing me to walk a bit further"',
  '""Come on now," I coaxed"',
  '"we coaxed money out of my father"',
  '"coaxing more speed from the car"',
  '"her lovely hair had been coaxed into ringlets"',
];
export const synonyms = [
  "persuade",
  "wheedle",
  "cajole",
  "get around",
  "beguile",
  "flatter",
  "seduce",
  "lure",
  "entice",
  "tempt",
  "inveigle",
  "woo",
  "maneuver",
  "blandish",
  "talk into something",
  "prevail on",
];
