export const definitions = [
  '"she cocked her head slightly to one side"',
  '"she listened, her little finger cocked as she held her coffee cup"',
  '"a greyhound cocked its leg against the tree"',
  '"he took the loaded pistol from his belt and cocked it"',
  '"it does not rake the grass into rows, nor cock it"',
];
export const synonyms = [
  "tilt",
  "tip",
  "angle",
  "lean",
  "slope",
  "bank",
  "slant",
  "incline",
  "pitch",
  "dip",
  "cant",
  "bevel",
  "camber",
  "heel",
  "careen",
  "put at an angle",
  "bend",
  "flex",
  "crook",
  "angle",
  "curve",
  "kink",
  "lift",
  "raise",
  "hold up",
  "lift up",
];
