export const definitions = [
  '"the cocoon of her kimono"',
  '"a warm cocoon of love"',
  '"we began to feel cold even though we were cocooned in our sleeping bags"',
  '"the movers and shakers are now cocooning"',
];
export const synonyms = [
  "wrap",
  "swathe",
  "swaddle",
  "sheathe",
  "muffle",
  "pad",
  "cloak",
  "enfold",
  "envelop",
  "surround",
  "encase",
  "enclose",
  "cover",
  "fold",
  "wind",
  "lap",
  "protect",
  "safeguard",
  "shield",
  "defend",
  "shelter",
  "screen",
  "look after",
  "take care of",
  "cushion",
  "insulate",
  "isolate",
  "cloister",
  "bundle up",
  "keep safe",
  "keep from harm",
  "care for",
  "expose",
];
