export const definitions = [
  '"I was coddled and cosseted"',
  '"you may have your eggs scrambled, poached, coddled, or boiled"',
  '"Dublin coddle is best served with a pint of Guinness on the side, and lots of Irish soda bread to mop up the gravy"',
];
export const synonyms = [
  'pamper',
  'cosset',
  'mollycoddle',
  'wait on someone hand and foot',
  'spoil',
  'indulge',
  'overindulge',
  'humor',
  'spoon-feed',
  'overparent',
  'pet',
  'baby',
  'mother',
  'nanny',
  'feather-bed',
  'cocker',
  'cater to someone\'s every whim',
  'pander to',
  'wrap in cotton wool',
  'neglect',
  'treat harshly',
  'be strict with',
];