export const definitions = [
  '"the statutes have codified certain branches of common law"',
  '"in the United Kingdom there is no codified constitution"',
  '"Verdi helped codify an international operatic culture"',
];
export const synonyms = [
  "systematize",
  "systemize",
  "organize",
  "arrange",
  "order",
  "marshal",
  "set out",
  "chart",
  "structure",
  "tabulate",
  "catalog",
  "list",
  "sort",
  "dispose",
  "index",
  "classify",
  "class",
  "categorize",
  "compile",
  "group",
  "range",
  "file",
  "log",
  "grade",
  "rate",
  "assort",
];
