export const definitions = [
  '"they were coerced into silence"',
  '"their confessions were allegedly coerced by torture"',
];
export const synonyms = [
  'pressure',
  'pressurize',
  'constrain',
  'lean on',
  'press',
  'push',
  'force',
  'compel',
  'oblige',
  'browbeat',
  'brainwash',
  'bludgeon',
  'bully',
  'threaten',
  'work on',
  'act on',
  'influence',
  'intimidate',
  'dragoon',
  'twist someone\'s arm',
  'strong-arm',
  'blackjack',
  'bring pressure to bear on',
  'use pressure on',
  'put pressure on',
  'put under an obligation',
  'prevail on',
  'persuade',
  'wrest',
  'exact',
  'wring',
  'screw',
  'squeeze',
  'milk',
  'force',
  'extort',
  'rack',
  'obtain by force',
  'obtain by threat(s)',
  'blackmail someone for',
  'worm something out of someone',
];