export const definitions = [
  '"a battered leather coffer sealed with a waxen crest"',
  '"the federal government\'s empty coffers"',
];
export const synonyms = [
  "strongbox",
  "cash box",
  "casket",
  "trunk",
  "box",
  "safe",
  "repository",
  "money box",
  "money chest",
  "treasure chest",
  "safety-deposit box",
  "safe-deposit box",
  "fund",
  "funds",
  "reserves",
  "resources",
  "money",
  "finances",
  "wealth",
  "cash",
  "wherewithal",
  "capital",
  "assets",
  "deep pockets",
  "purse",
  "kitty",
  "pool",
  "bank",
  "treasury",
  "exchequer",
  "fisc",
];
