export const definitions = [];
export const synonyms = [
  "sexual intercourse",
  "sex",
  "lovemaking",
  "sex act",
  "sexual relations",
  "intimacy",
  "coupling",
  "mating",
  "coition",
  "copulation",
  "fornication",
  "carnal knowledge",
  "commerce",
  "making love",
  "act of love",
  "intimate relations",
  "going to bed with someone",
  "sleeping with someone",
  "(sexual) congress",
];
