export const definitions = [
  '"neatly combed hair"',
  '"the socks are made of soft combed cotton"',
  '"she combed her hair and put some lipstick on"',
  '"she combed the burrs out of the dog\'s coat"',
  '"the wool had been cleaned and combed"',
  '"police combed the area for the murder weapon"',
  '"his mother combed through the cardboard boxes"',
];
export const synonyms = [
  'groom',
  'untangle',
  'disentangle',
  'straighten',
  'arrange',
  'neaten',
  'tidy',
  'dress',
  'rake',
  'curry',
  'smooth out',
  'separate',
  'dress',
  'card',
  'tease',
  'hackle',
  'heckle',
  'hatchel',
  'search',
  'scour',
  'explore',
  'sweep',
  'probe',
  'look through',
  'dig in',
  'go through',
  'rake',
  'ransack',
  'turn over',
  'look around in',
  'hunt through',
  'scrabble around in',
  'root around in',
  'ferret (around) in',
  'rummage around in',
  'rummage in',
  'rummage through',
  'forage through',
  'fish around in',
  'poke around in',
  'grub around in',
  'delve in',
  'sift through',
  'rifle through',
  'go through with a fine-tooth comb',
  'turn upside down',
  'turn inside out',
  'leave no stone unturned in',
  'roust around in',
];