export const definitions = [
  '"work is due to start in the coming year"',
  '"he was the coming man of French racing"',
  '"the coming of a new age"',
  '"Jessica came into the kitchen"',
  '"I came here on holiday with my parents"',
  '"she came downstairs"',
  '"he came rushing out"',
  '"damp is coming through the ceiling"',
  '"we walked along till we came to a stream"',
  '"it was very late when she came back"',
  '"the letter hasn\'t come yet"',
  '"women wore slim dresses that came all the way to their shoes"',
  '"the path comes straight down"',
  '"someone was coming"',
  '"she heard the train coming"',
  '"the police came"',
  '"come and live with me"',
  '"the electrician came to fix the stove"',
  '"we have certainly come a long way since Aristotle"',
  '"do you want to come fishing tomorrow?"',
  '"\"Come, come, child, no need to thank me.\""',
  '"twilight had not yet come"',
  '"his father waited for a phone call that never came"',
  '"the attacks came without warning"',
  '"the best is yet to come"',
  '"the cuts come amid increasing competition in Hong Kong"',
  '"a voice came from the kitchen"',
  '"it came as a great shock"',
  '"\"No,\" came the reply"',
  '"prisons come far down the list of priorities"',
  '"I make sure my kids come first"',
  '"she came second among sixty contestants"',
  '"I let my stupid pride come between us"',
  '"nothing should come between brothers"',
  '"his shirt had come undone"',
  '"he had come to realize she was no puppet"',
  '"the cars come with a variety of extras"',
  '"they come in three sizes"',
];
export const synonyms = [
  'forthcoming',
  'imminent',
  'impending',
  'approaching',
  'advancing',
  'nearing',
  'near',
  'future',
  'expected',
  'anticipated',
  'close',
  'in store',
  'in the air',
  'in the offing',
  'in the pipeline',
  'on the horizon',
  'on the way',
  '(close) at hand',
  'in the wind',
  'on us',
  'about to happen',
  'approach',
  'advance',
  'advent',
  'arrival',
  'nearing',
  'looming',
  'appearance',
  'emergence',
  'materialization',
  'surfacing',
  'birth',
  'rise',
  'start',
  'onset',
  'approach',
  'advance',
  'near',
  'proceed',
  'forge',
  'move nearer',
  'move closer',
  'draw nigh',
  'draw close/closer',
  'draw near/nearer',
  'make progress',
  'make headway',
  'go away',
  'arrive',
  'appear',
  'make an appearance',
  'come up',
  'approach',
  'enter',
  'turn up',
  'be along',
  'come along',
  'materialize',
  'reach',
  'get here/there',
  'reach one\'s destination',
  'make it',
  'put in an appearance',
  'come on the scene',
  'present oneself',
  'leave',
  'reach',
  'meet',
  'get to',
  'get up to',
  'make',
  'gain',
  'attain',
  'come across',
  'run across',
  'run into',
  'come upon',
  'run against',
  'extend',
  'stretch',
  'continue',
  'carry on',
  'spread',
  'arrive at',
  'get as far as',
  'make it to',
  'set foot on',
  'happen on',
  'chance on',
  'light on',
  'stumble on',
  'blunder on',
  'find by chance',
  'end up at',
  'land up at',
  'fetch up at',
  'come as far as',
  'not stop until',
  'stop short of',
  'imminent',
  'impending',
  'close',
  'near',
  'approaching',
  'coming',
  'forthcoming',
  'at hand',
  'on the way',
  'in the offing',
  'in the pipeline',
  'in the air',
  'in the wings',
  'brewing',
  'looming',
  'threatening',
  'menacing',
  'in prospect',
  'about to happen',
  'upon us',
  'in the wind',
  'just around the corner',
  'happen',
  'occur',
  'take place',
  'come about',
  'transpire',
  'fall',
  'crop up',
  'materialize',
  'arise',
  'arrive',
  'appear',
  'surface',
  'ensue',
  'follow',
  'come to pass',
  'befall',
  'betide',
  'hap',
  'eventuate',
  'present itself',
  'alienate',
  'estrange',
  'separate',
  'divide',
  'split up',
  'break up',
  'disunite',
  'disaffect',
  'set/pit against one another',
  'cause disagreement between',
  'sow dissension between',
  'set at variance/odds',
  'unite',
  'break up',
  'disintegrate',
  'splinter',
  'come unstuck',
  'crumble',
  'separate',
  'split',
  'tear',
  'collapse',
  'dissolve',
  'fall to bits/pieces',
  'come to bits/pieces',
  'be available',
  'be made',
  'be produced',
  'be for sale',
  'be on offer',
  'climax',
  'orgasm',
  'achieve orgasm',
];