export const definitions = [
  '"salt and pepper are the two most common seasonings"',
  '"it\'s common for children to have middle ear infections"',
  '"you might spot less common birds such as the great spotted woodpecker"',
  '"the swordfish is not common in European waters"',
  '"the common blue spruce"',
  '"the dwellings of common people"',
  '"a common soldier"',
  '"common decency"',
  '"the common or vernacular name"',
  '"the two republics\' common border"',
  '"problems common to both communities"',
  '"common land"',
  '"she\'s so common"',
  '"common assault"',
  '"we spent the morning tramping over the common looking for flowers"',
];
export const synonyms = [
  'usual',
  'ordinary',
  'customary',
  'habitual',
  'familiar',
  'regular',
  'frequent',
  'repeated',
  'recurrent',
  'routine',
  'everyday',
  'daily',
  'day-to-day',
  'quotidian',
  'standard',
  'typical',
  'conventional',
  'stock',
  'stereotyped',
  'predictable',
  'commonplace',
  'mundane',
  'run-of-the-mill',
  'wonted',
  'widespread',
  'general',
  'universal',
  'popular',
  'mainstream',
  'prevalent',
  'prevailing',
  'rife',
  'established',
  'well established',
  'traditional',
  'traditionalist',
  'orthodox',
  'accepted',
  'in circulation',
  'in force',
  'in vogue',
  'unusual',
  'rare',
  'ordinary',
  'normal',
  'typical',
  'average',
  'unexceptional',
  'run-of-the-mill',
  'plain',
  'simple',
  'general',
  'collective',
  'nonspecific',
  'inclusive',
  'all-inclusive',
  'all-encompassing',
  'broad',
  'comprehensive',
  'blanket',
  'umbrella',
  'sweeping',
  'universal',
  'cross-disciplinary',
  'interdisciplinary',
  'multidisciplinary',
  'specific',
  'familiar',
  'popular',
  'usual',
  'everyday',
  'customary',
  'conventional',
  'established',
  'widely known',
  'unknown',
  'abstruse',
  'collective',
  'communal',
  'community',
  'public',
  'popular',
  'general',
  'shared',
  'joint',
  'combined',
  'private',
  'individual',
  'collective',
  'communal',
  'community',
  'public',
  'popular',
  'general',
  'shared',
  'joint',
  'combined',
  'private',
  'individual',
  'uncouth',
  'vulgar',
  'coarse',
  'rough',
  'unsavory',
  'boorish',
  'rude',
  'impolite',
  'ill-mannered',
  'unladylike',
  'ungentlemanly',
  'ill-bred',
  'uncivilized',
  'unsophisticated',
  'unrefined',
  'philistine',
  'primitive',
  'savage',
  'brutish',
  'oafish',
  'gross',
  'lowly',
  'low',
  'low-born',
  'low-ranking',
  'low-class',
  'inferior',
  'humble',
  'ignoble',
  'proletarian',
  'plebeian',
  'baseborn',
  'refined',
  'noble',
];