export const definitions = [
  '"a sense of duty compelled Harry to answer her questions"',
  '"they may compel a witness\'s attendance at court by issue of a summons"',
  "\"by hea's 's high will compell'd from shore to shore\"",
];
export const synonyms = [
  "force",
  "pressure",
  "impel",
  "drive",
  "press",
  "push",
  "urge",
  "oblige",
  "require",
  "make",
  "constrain",
  "exact",
  "extort",
  "demand",
  "enforce",
  "necessitate",
  "coerce into",
  "pressurize into",
  "prevail on",
  "dragoon into",
  "browbeat into",
  "bully into",
  "bludgeon into",
  "intimidate into",
  "terrorize into",
  "put under an obligation",
  "leave someone no option but to",
  "insist on",
];
