export const definitions = [
  '"the authors concurred with the majority"',
  '""That\'s right," the chairman concurred"',
  '"they concurred in the creation of the disciplinary procedures"',
  '"we strongly concur with this recommendation"',
  '"in tests, cytogenetic determination has been found to concur with enzymatic determination"',
];
export const synonyms = [
  "agree",
  "accord",
  "go along",
  "fall in",
  "see eye to eye",
  "be in agreement",
  "be in accord",
  "be in accordance",
  "be in harmony",
  "be in sympathy",
  "be of the same mind",
  "be of the same opinion",
  "disagree",
  "permit",
  "allow",
  "accept",
  "respect",
  "stand by",
  "tolerate",
  "brook",
  "bow to",
  "suffer",
  "consent to",
  "agree to",
  "assent to",
  "give one's consent to",
  "concur with",
  "give one's assent to",
  "give 's 's blessing to",
  "say yes to",
  "give the nod to",
  "give one's approval to",
  "comply with",
  "conform to",
  "abide by",
  "cooperate with",
  "give in to",
  "yield to",
  "submit to",
  "forbid",
  "coincide",
  "synchronize",
  "coexist",
  "clash",
  "happen/occur together",
  "happen/occur simultaneously",
  "happen/occur at the same time",
  "be simultaneous",
  "be concurrent",
];
