export const definitions = [
  '"they wandered off to the woods for a private confab"',
  '"this year\'s annual American Booksellers Association confab"',
  '"Peter was confabbing with a curly-haired guy"',
];
export const synonyms = [
  "discussion",
  "talk",
  "chat",
  "gossip",
  "tête-à-tête",
  "heart-to-heart",
  "head-to-head",
  "exchange",
  "dialogue",
  "parley",
  "consultation",
  "conference",
  "confabulation",
  "palaver",
  "colloquy",
  "converse",
  "adda",
  "korero",
  "meeting",
  "negotiation",
  "conference",
  "talk(s)",
  "discussion",
  "conclave",
  "consultation",
  "deliberation",
  "dialogue",
  "parley",
  "colloquy",
  "confabulation",
];
