export const definitions = [
  '"my car conked out"',
  '"he conked out on the rear seat"',
  '"most creatures conk out smartly once they have passed on their genes"',
  '"the clown conked him and sent him to the hospital with a concussion"',
];
export const synonyms = [
  "break down",
  "break",
  "cut out",
  "stop",
  "stall",
  "crash",
  "give out",
  "malfunction",
  "act up",
  "go wrong",
  "stop working",
  "cease to function",
  "develop a fault",
  "be faulty",
  "be defective",
  "work",
  "be in working order",
  "go to sleep",
  "drop off",
  "collapse",
  "drop",
  "faint",
  "pass out",
  "black out",
  "swoon",
  "fall asleep",
  "keel over",
  "lose consciousness",
  "pass away",
  "pass on",
  "lose one's life",
  "depart this life",
  "expire",
  "breathe one's last",
  "lay down 's 's life",
  "perish",
  "go the way of all flesh",
  "go to glory",
  "exit",
  "decease",
  "draw one's last breath",
  "meet 's 's end",
  "meet 's 's death",
  "be no more",
  "be lost",
  "go the way of the flesh",
  "go to one's last resting place",
  "go to meet 's 's maker",
  "cross the great divide",
  "cross the Styx",
  "push up the daisies",
  "be six feet under",
  "live",
  "survive",
  "hit",
  "strike",
  "buffet",
  "bang",
  "knock",
  "thwack",
  "slug",
  "welt",
  "cuff",
  "punch",
  "smash",
  "concuss",
  "stun",
  "smite",
  "swinge",
  "hit over the head",
  "hit on the head",
];
