export const definitions = [
  '"her hull was a conoid, tapering toward the bow"',
];
export const synonyms = [
  'sharp',
  'spearlike',
  'needle-like',
  'V-shaped',
  'tapering',
  'tapered',
  'cone-shaped',
  'conic',
  'conical',
  'acute',
  'edged',
  'jagged',
  'spiky',
  'spiked',
  'barbed',
  'acicular',
  'lanceolate',
  'acuminate',
  'subulate',
  'mucronate',
  'aculeate',
  'cuspidate',
  'cusped',
  'spear-shaped',
  'sharp-cornered',
  'wedge-shaped',
  'sharp-edged',
];