export const definitions = [
  '"pipes were laid to convey water to the house"',
  '"the real virtues and diversity of America had never been conveyed in the movies"',
  '"it\'s impossible to convey how lost I felt"',
  '"Mr. Harvey and his daughter have asked me to convey their very kind regards"',
];
export const synonyms = [
  'transport',
  'carry',
  'bring',
  'take',
  'fetch',
  'bear',
  'move',
  'ferry',
  'shuttle',
  'shift',
  'transfer',
  'send',
  'forward',
  'deliver',
  'dispatch',
  'channel',
  'pipe',
  'conduct',
  'project',
  'exude',
  'emit',
  'emanate',
  'send forth',
  'communicate',
  'pass on',
  'impart',
  'relay',
  'transmit',
  'send',
  'hand on',
  'tell',
  'relate',
  'recount',
  'announce',
  'reveal',
  'disclose',
  'divulge',
  'express',
  'indicate',
  'say',
  'make known',
  'put across/over',
  'get across/over',
  'transfer',
  'grant',
  'cede',
  'devolve',
  'lease',
  'bequeath',
  'leave',
  'will',
  'pass on',
  'deed',
  'demise',
  'devise',
  'give the right/title of',
];