export const definitions = [
  '"the cooler was a dark, claustrophobic room"',
  '"it\'ll be a cool afternoon"',
  '"the wind kept them cool"',
  '"a cool drink in the leafy shade"',
  '"the bathroom was all glass and cool, muted blues"',
  '"wear your cool, comfortable shirts"',
  '"he gave a cool reception to the suggestion for a research center"',
  '"he prided himself on keeping a cool head"',
  '"she seems cool, calm, and collected"',
  '"he made no concessions to fashion, yet somehow he was hip and cool"',
  '"I always wore sunglasses to look cool"',
  '"our office was a sunny room with a computer you didn\'t even have to plug in.Cool!"',
  '"if people want to freak out at our clubs, that\'s cool"',
  '"a cool $15,000 to buy the franchise"',
];
export const synonyms = [
  "jail",
  "prison",
  "cell",
  "detention center",
  "jailhouse",
  "police cell",
  "place of detention",
  "place of confinement",
  "chilly",
  "cold",
  "fresh",
  "crisp",
  "refreshing",
  "invigorating",
  "bracing",
  "brisk",
  "unheated",
  "drafty",
  "chill",
  "warm",
  "hot",
  "chilly",
  "cold",
  "fresh",
  "crisp",
  "refreshing",
  "invigorating",
  "bracing",
  "brisk",
  "unheated",
  "drafty",
  "chill",
  "warm",
  "hot",
  "unenthusiastic",
  "lukewarm",
  "tepid",
  "indifferent",
  "apathetic",
  "halfhearted",
  "negative",
  "unfriendly",
  "distant",
  "remote",
  "aloof",
  "cold",
  "chilly",
  "frosty",
  "unwelcoming",
  "inhospitable",
  "unresponsive",
  "uninterested",
  "unconcerned",
  "offhand",
  "detached",
  "impersonal",
  "dispassionate",
  "undemonstrative",
  "uncommunicative",
  "unfeeling",
  "unemotional",
  "emotionless",
  "Olympian",
  "gelid",
  "enthusiastic",
  "friendly",
  "calm",
  "composed",
  "as cool as a cucumber",
  "collected",
  "coolheaded",
  "levelheaded",
  "self-possessed",
  "controlled",
  "self-controlled",
  "poised",
  "serene",
  "tranquil",
  "relaxed",
  "unruffled",
  "unperturbed",
  "unflustered",
  "undisturbed",
  "unmoved",
  "unbothered",
  "untroubled",
  "equable",
  "even-tempered",
  "imperturbable",
  "placid",
  "quiet",
  "sedate",
  "unexcitable",
  "impassive",
  "dispassionate",
  "unemotional",
  "phlegmatic",
  "stolid",
  "equanimous",
  "cool, calm, and collected",
  "unagitated",
  "panic-stricken",
  "agitated",
  "fashionable",
  "in fashion",
  "voguish",
  "up to the minute",
  "modern",
  "modish",
  "trendsetting",
  "stylish",
  "chic",
  "sophisticated",
  "cosmopolitan",
  "elegant",
  "smart",
  "glamorous",
  "classy",
  "high-class",
  "high-toned",
  "attractive",
  "appealing",
  "impressive",
  "in vogue",
  "(bang) up to date",
  "all the rage",
  "le dernier cri",
  "superb",
  "outstanding",
  "magnificent",
  "exceptional",
  "marvelous",
  "wonderful",
  "sublime",
  "perfect",
  "eminent",
  "preeminent",
  "matchless",
  "peerless",
  "supreme",
  "first-rate",
  "first-class",
  "superior",
  "superlative",
  "splendid",
  "admirable",
  "worthy",
  "sterling",
  "fine",
  "very good",
  "of high quality",
  "of the highest quality",
  "of the highest standard",
  "applaudable",
  "poor",
  "inferior",
];
