export const definitions = [
  '"the problem is telling which is the original document and which the copy"',
  '"the record has sold more than a million copies"',
  '"copy for the next issue must be submitted by the beginning of the month"',
  '"it is an unfortunate truth of today\'s media that bad news makes good copy"',
  '""No more stubble—no more trouble," trumpeted their ad copy"',
  '"examinees will not be allowed to take pens, copies, or water bottles inside the test center"',
  '"you need a stock of exercise copies, A4 refill pads, and maths copies"',
  '"each form had to be copied and sent to a different department"',
  '"the command will copy a file from one disc to another"',
  '"he copied the details into his notebook"',
  '"I began to copy out the addresses"',
  '"I thought I\'d copy to you this letter sent to the PR representative"',
  '"I attached the document and copied him in so he\'d know it had been sent"',
  '"lifestyles that were copied from Miami and Fifth Avenue"',
  '"art students copied from approved old masters"',
  '"she was such fun that everybody wanted to copy her"',
  '"this is Edwards, do you copy, over"',
];
export const synonyms = [
  "duplicate",
  "duplication",
  "reprint",
  "facsimile",
  "photocopy",
  "carbon copy",
  "carbon",
  "mimeograph",
  "mimeo",
  "transcript",
  "Xerox",
  "photostat",
  "replica",
  "reproduction",
  "replication",
  "print",
  "imitation",
  "likeness",
  "lookalike",
  "representation",
  "mock-up",
  "dummy",
  "counterfeit",
  "forgery",
  "fake",
  "sham",
  "bootleg",
  "edition",
  "version",
  "impression",
  "imprint",
  "issue",
  "specimen",
  "sample",
  "example",
  "material",
  "articles",
  "stories",
  "features",
  "duplicate",
  "photocopy",
  "xerox",
  "photostat",
  "mimeograph",
  "run off",
  "transcribe",
  "reproduce",
  "replicate",
  "clone",
  "forge",
  "fake",
  "falsify",
  "counterfeit",
  "bootleg",
  "make a photocopy of",
  "take a photocopy of",
  "imitate",
  "mimic",
  "ape",
  "emulate",
  "follow",
  "echo",
  "mirror",
  "simulate",
  "parrot",
  "reproduce",
  "plagiarize",
  "poach",
  "steal",
  "monkey",
  "infringe the copyright of",
];
