export const definitions = [
  '"a coral reef"',
  '"she was wearing a twisted rope of coral, pearls, and crystal"',
  '"coral beads"',
  '"colors of earth, coral, and chestnut"',
  '"a coral and white dinner service"',
  '"we had scallops with their coral, in their fluted shells"',
];
export const synonyms = [
  'scarlet',
  'vermilion',
  'ruby',
  'cherry',
  'cerise',
  'cardinal',
  'carmine',
  'wine',
  'wine red',
  'claret',
  'blood red',
  'flame',
  'flaming',
  'cochineal',
  'rose',
  'rosy',
  'brick red',
  'maroon',
  'rusty',
  'foxy',
  'rufous',
  'reddish',
  'damask',
  'vermeil',
  'sanguine',
  'gules',
  'rufescent',
  'ruby red',
  'ruby-colored',
  'cherry red',
  'wine-colored',
  'claret red',
  'claret-colored',
];