export const definitions = [
  '"Jan sat at one corner of the table"',
  '"he drove the ball into the corner of the net"',
  '"an apartment on the corner of 199th Street and Amsterdam Avenue"',
  '"the corner house"',
  '"he found himself backed into a corner"',
  '"two outs, with runners on the corners"',
  '"serious racers want a car that is fast going into and out of the corners"',
  '"they descended on the college from all corners of the world"',
  '"his wisdom was disseminated to the four corners of the earth"',
  '"parents are often tempted to resort to snooping and prying into every corner to make sure their children are safe"',
  '"Hodkinson was encouraged by his corner"',
  '"the man was eventually cornered by police dogs"',
  '"I managed to corner Gary for fifteen minutes"',
  '"whether they will corner the market in graphics software remains to be seen"',
  '"you cornered vanadium and made a killing"',
  '"no squeal is evident from the tires when cornering fast"',
  '"Kavanagh lofted a corner kick"',
];
export const synonyms = [
  "bring to bay",
  "cut off",
  "trap",
  "hem in",
  "shut in",
  "close in",
  "enclose",
  "surround",
  "capture",
  "catch",
  "waylay",
  "ambush",
  "ambuscade",
  "drive into a corner",
  "run to earth",
  "run to ground",
  "block off",
  "pen in",
  "take over",
  "control",
  "dominate",
  "monopolize",
  "capture",
  "engross",
  "gain control of",
  "gain dominance of",
];
