export const definitions = [
  '"the parapet wall sweeps down in a bold curve"',
  '"the vehicle rounded a curve"',
  '"her dress twisted tightly around her generous curves"',
  '"the population curve"',
  '"grades were marked on a curve"',
  '"he relies on a couple of curves and a modest fastball"',
  '"her mouth curved in a smile"',
  '"starting with arms outstretched, curve the body sideways"',
];
export const synonyms = [
  "bend",
  "bow",
  "arch",
  "crescent",
  "semicircle",
  "half-moon",
  "curvature",
  "convexity",
  "curling",
  "circular section/line",
  "bend",
  "turn",
  "loop",
  "curl",
  "twist",
  "hook",
  "arch",
  "bow",
  "half-moon",
  "corner",
  "dogleg",
  "oxbow",
  "bulge",
  "swell",
  "curvature",
  "camber",
  "undulation",
  "meander",
  "hairpin bend",
  "hairpin turn",
  "flexure",
  "trajectory",
  "inflection",
  "incurvation",
  "outline",
  "contour(s)",
  "profile",
  "delineation",
  "form",
  "shape",
  "figure",
  "shadow",
  "features",
  "lines",
  "curves",
  "configuration",
  "bend",
  "turn",
  "loop",
  "wind",
  "meander",
  "undulate",
  "snake",
  "spiral",
  "twist",
  "coil",
  "curl",
  "arc",
  "arch",
  "bow",
  "bulge",
  "swell",
  "inflect",
  "incurve",
  "bent",
  "arched",
  "bowed",
  "crescent",
  "curving",
  "recurved",
  "wavy",
  "twisted",
  "twisty",
  "sinuous",
  "serpentine",
  "meandering",
  "undulating",
  "curvilinear",
  "curvy",
  "vaulted",
  "rounded",
  "concave",
  "convex",
  "domed",
  "humped",
  "hooked",
  "aquiline",
  "arcuate",
  "falcate",
  "falciform",
  "circumflex",
  "flexural",
  "embowed",
  "curviform",
  "straight",
];
