export const definitions = [
  '"major problems requiring costly repairs"',
  '"the government\'s biggest and most costly mistake"',
];
export const synonyms = [
  'expensive',
  'dear',
  'high-priced',
  'overpriced',
  'exorbitant',
  'extortionate',
  'immoderate',
  'extravagant',
  'lavish',
  'rich',
  'deluxe',
  'choice',
  'fine',
  'exquisite',
  'valuable',
  'priceless',
  'upmarket',
  'high-cost',
  'highly priced',
  'big-budget',
  'worth its weight in gold',
  'worth a king\'s ransom',
  'over the odds',
  'cheap',
  'inexpensive',
  'catastrophic',
  'ruinous',
  'disastrous',
  'calamitous',
  'cataclysmic',
  'devastating',
  'crippling',
  'crushing',
  'fatal',
  'lethal',
  'damaging',
  'harmful',
  'injurious',
  'deleterious',
  'woeful',
  'grievous',
  'lamentable',
  'dire',
  'awful',
  'terrible',
  'unfortunate',
  'direful',
  'beneficial',
];