export const definitions = [
  '"coffee cans that once contained a full pound of coffee"',
  '"borscht can contain mainly beets or a number of vegetables"',
  '"since F contains the factor Q it disappears from both sides of the equation"',
  '"she was scarcely able to contain herself as she waited to spill the beans"',
  '"a reassuring statement on efforts to contain the disaster"',
];
export const synonyms = [
  'hold',
  'carry',
  'accommodate',
  'seat',
  'have room/space/seating/capacity for',
  'include',
  'comprise',
  'take in',
  'incorporate',
  'involve',
  'encompass',
  'embrace',
  'embody',
  'consist of',
  'be made up',
  'be composed of',
  'restrain',
  'curb',
  'suppress',
  'repress',
  'stifle',
  'subdue',
  'quell',
  'limit',
  'swallow',
  'bottle up',
  'keep back',
  'hold in',
  'control',
  'master',
  'rein in',
  'keep under control',
  'keep in check',
  'gain control over',
  'gain mastery over',
];