export const definitions = [
  '"the road adopts a tortuous course along the coast"',
  '"the new fleet changed course to join the other ships"',
  '"the course of history"',
  '"my decision had seemed to be the wisest course open to me at the time"',
  '"a business studies course"',
  '"a two-year training course"',
  '"she took a course in medicine"',
  '"the doctor prescribed a course of antibiotics"',
  '"guests are offered a choice of main course"',
  '"a four-course meal"',
  '"a golf course"',
  '"tears were coursing down her cheeks"',
  '"exultation coursed through him"',
  '"many of the hares coursed escaped unharmed"',
  '"she would course for hares with her greyhounds"',
];
export const synonyms = [
  "route",
  "way",
  "track",
  "direction",
  "tack",
  "path",
  "line",
  "journey",
  "itinerary",
  "channel",
  "trail",
  "trajectory",
  "flight path",
  "bearing",
  "heading",
  "orbit",
  "circuit",
  "beat",
  "round",
  "run",
  "progression",
  "development",
  "progress",
  "advance",
  "advancement",
  "evolution",
  "unfolding",
  "flow",
  "movement",
  "continuity",
  "sequence",
  "order",
  "succession",
  "rise",
  "march",
  "furtherance",
  "forwarding",
  "proceeding",
  "plan (of action)",
  "course of action",
  "MO",
  "process",
  "procedure",
  "practice",
  "approach",
  "technique",
  "style",
  "manner",
  "way",
  "means",
  "methodology",
  "system",
  "policy",
  "strategy",
  "program",
  "formula",
  "regimen",
  "modus operandi",
  "praxis",
  "method of working",
  "line of action",
  "mode of behavior",
  "mode of conduct",
  "curriculum",
  "syllabus",
  "schedule",
  "classes",
  "lectures",
  "studies",
  "program of study",
  "course of study",
  "educational program",
  "set of lectures",
  "program",
  "series",
  "sequence",
  "system",
  "schedule",
  "regimen",
  "dish",
  "menu item",
  "track",
  "racetrack",
  "racecourse",
  "circuit",
  "ground",
  "stadium",
  "speedway",
  "velodrome",
  "route",
  "trail",
  "circus",
  "cirque",
  "layer",
  "thickness",
  "stratum",
  "seam",
  "vein",
  "band",
  "bed",
  "pursuit",
  "hunt",
  "trail",
  "hunting",
  "coursing",
  "flow",
  "pour",
  "race",
  "stream",
  "run",
  "rush",
  "gush",
  "pump",
  "move",
  "cascade",
  "flood",
  "surge",
  "sweep",
  "roll",
  "hunt",
  "chase",
  "pursue",
  "stalk",
  "run down",
  "run after",
  "follow",
  "track",
  "trail",
  "shadow",
  "hound",
  "dog",
  "give chase to",
];
