export const definitions = [
  '"they are always playing cowboys and Indians"',
  '"cowboy coach firms are alleged to have flouted safety rules"',
  '"Sonora, Mexico, was where he learned to cowboy"',
];
export const synonyms = [
  'cattleman',
  'cowhand',
  'cowman',
  'cowherd',
  'herder',
  'herdsman',
  'drover',
  'stockman',
  'rancher',
  'gaucho',
  'ranchero',
  'vaquero',
  'buckaroo',
  'herd',
  'llanero',
  'cheat',
  'swindler',
  'fraudster',
  'trickster',
  'charlatan',
  'scoundrel',
  'rogue',
  'rascal',
  'incompetent',
  'amateur',
  'bungler',
  'blunderer',
  'bumbler',
  'unscrupulous operator',
  'professional',
];