export const definitions = [
  '"she treated him to a coy smile of invitation"',
  '"he is coy about his age"',
];
export const synonyms = [
  "arch",
  "simpering",
  "coquettish",
  "flirtatious",
  "kittenish",
  "skittish",
  "shy",
  "modest",
  "bashful",
  "reticent",
  "diffident",
  "retiring",
  "backward",
  "self-effacing",
  "shrinking",
  "withdrawn",
  "timid",
  "demure",
  "brazen",
];
