export const definitions = [
  '"he\'s a lying, cheating, snake in the grass"',
  '"the man lay face downward on the grass"',
  '"I had to lie down for two hours because I was groggy"',
  '"Lily lay back on the pillows and watched him"',
  '"a book lay open on the table"',
  '"his body lies in a crypt"',
  '"his epitaph reads "Here lies Garcia, King of Galicia and Portugal""',
  '"the church lies in ruins today"',
  '"putting homeless families into apartments that would otherwise lie empty"',
  '"the solution lies in a return to "traditional family values.""',
  '"the small town of Swampscott lies about ten miles north of Boston"',
  '"stand here, and all of Amsterdam lies before you"',
  '"an action for restitution would lie for money paid in breach of the law"',
  '"why had Wesley lied about his visit to Philadelphia?"',
  '""I am sixty-five," she lied"',
  '"you lied your way on to this voyage by implying you were an experienced sailor"',
  '"the camera cannot lie"',
];
export const synonyms = [
  "untruthful",
  "false",
  "dishonest",
  "mendacious",
  "perfidious",
  "deceitful",
  "deceiving",
  "deceptive",
  "duplicitous",
  "dissimulating",
  "dissembling",
  "double-dealing",
  "two-faced",
  "Janus-faced",
  "guileful",
  "underhand",
  "disingenuous",
  "hollow-hearted",
  "truthful",
  "honest",
  "recline",
  "lean back",
  "sprawl",
  "rest",
  "repose",
  "relax",
  "lounge",
  "loll",
  "bask",
  "lie down",
  "lie back",
  "be recumbent",
  "be prostrate",
  "be supine",
  "be prone",
  "be stretched out",
  "stretch oneself out",
  "stand",
  "rest",
  "repose",
  "be",
  "be placed",
  "be set",
  "be situated",
  "be positioned",
  "rest",
  "be buried",
  "be interred",
  "be laid to rest",
  "be entombed",
  "be inhumed",
  "be sepulchered",
  "consist",
  "inhere",
  "exist",
  "reside",
  "be inherent",
  "be present",
  "be contained",
  "have its existence/being",
  "be",
  "be situated",
  "be located",
  "be placed",
  "be positioned",
  "be found",
  "be sited",
  "be established",
  "fib",
  "fabricate",
  "falsify",
  "dissemble",
  "dissimulate",
  "prevaricate",
  "exaggerate",
  "bluff",
  "pretend",
  "deceive",
  "delude",
  "mislead",
  "trick",
  "hoodwink",
  "hoax",
  "take in",
  "pull the wool over someone's eyes",
  "be economical with the truth",
  "say something untrue",
  "tell an untruth",
  "tell a lie",
  "tell a falsehood",
  "invent a story",
  "make up a story",
  "bear false witness",
  "tell a white lie",
  "stretch the truth",
  "perjure oneself",
  "commit perjury",
  "forswear oneself",
  "be forsworn",
  "depart from the truth",
  "lead astray",
  "throw off the scent",
  "send on a wild goose chase",
  "put on the wrong track",
  "tell a terminological inexactitude",
  "tell the truth",
];
