export const definitions = [
  '"neatly folded shirts"',
  '"she neatly sidestepped the question"',
];
export const synonyms = [
  'tidily',
  'smartly',
  'sprucely',
  'methodically',
  'systematically',
  'cleverly',
  'aptly',
  'nicely',
  'elegantly',
  'well',
  'skillfully',
  'deftly',
  'adroitly',
  'adeptly',
  'expertly',
  'precisely',
  'nimbly',
  'agilely',
  'gracefully',
  'effortlessly',
];