export const definitions = [
  '"a darning needle"',
  '"the meter needle barely moved"',
  '"just left of the needle is a steep wall for those who like bold climbing"',
  '"Cleopatra\'s Needle"',
  '"dust needled his eyes"',
  '"I just said that to Charlie to needle him"',
];
export const synonyms = [
  "indicator",
  "pointer",
  "marker",
  "arrow",
  "hand",
  "stylus",
  "frond",
  "flag",
  "pad",
  "blade",
  "bract",
  "leaflet",
  "cotyledon",
  "foliole",
  "top",
  "peak",
  "mountaintop",
  "crest",
  "crown",
  "apex",
  "vertex",
  "apogee",
  "tip",
  "cap",
  "ridge",
  "brink",
  "brow",
  "crag",
  "tor",
  "mountain top",
  "hilltop",
  "aiguille",
  "serac",
  "bottom",
  "base",
  "goad",
  "provoke",
  "bait",
  "taunt",
  "pester",
  "harass",
  "prick",
  "prod",
  "sting",
  "irritate",
  "annoy",
  "anger",
  "vex",
  "irk",
  "nettle",
  "pique",
  "exasperate",
  "infuriate",
  "get on someone's nerves",
  "ruffle some's 's feathers",
  "exacerbate",
  "hump",
  "rasp",
  "rub up the wrong way",
  "get/put someone's back up",
  "try some's 's patience",
];
