export const definitions = [
  '"I need help now"',
  '"this shirt needs washing"',
  '"they need to win tomorrow"',
  '"I don\'t need your sarcasm"',
  '"need I say more?"',
  '"I need not have worried"',
  '"lest you, even more than needs, embitter our parting"',
];
export const synonyms = [
  "require",
  "have need of",
  "want",
  "demand",
  "call for",
  "necessitate",
  "entail",
  "involve",
  "lack",
  "miss",
  "be in need of",
  "stand in need of",
  "be in want of",
  "be crying out for",
  "be desperate for",
  "have occasion for/to",
  "be without",
  "be short of",
  "have to",
  "be under an obligation to",
  "be obliged to",
  "be compelled to",
  "be under a compulsion to",
  "have need to",
];
