export const definitions = [
  '"waved to them in genial greeting"',
];
export const synonyms = [
  'friendly',
  'affable',
  'cordial',
  'congenial',
  'amiable',
  'warm',
  'easygoing',
  'approachable',
  'sympathetic',
  'well disposed',
  'good-natured',
  'good-humored',
  'cheerful',
  'cheery',
  'neighborly',
  'hospitable',
  'companionable',
  'comradely',
  'bluff',
  'sociable',
  'convivial',
  'outgoing',
  'extrovert',
  'extroverted',
  'gregarious',
  'hail-fellow-well-met',
  'easy to get along with',
  'company-loving',
  'unfriendly',
  'morose',
];