export const definitions = [
  '"books of general interest"',
  '"brush up on your general knowledge"',
  '"it is not general practice to confirm or deny such reports"',
  '"a general introduction to the subject"',
  '"they fired in the general direction of the enemy"',
  '"a general manager"',
];
export const synonyms = [
  "widespread",
  "common",
  "extensive",
  "universal",
  "wide",
  "popular",
  "public",
  "mainstream",
  "prevalent",
  "prevailing",
  "rife",
  "established",
  "well established",
  "conventional",
  "traditional",
  "traditionalist",
  "orthodox",
  "accepted",
  "in circulation",
  "in force",
  "comprehensive",
  "overall",
  "across the board",
  "blanket",
  "umbrella",
  "mass",
  "total",
  "complete",
  "wholesale",
  "sweeping",
  "panoramic",
  "broad",
  "broad-ranging",
  "extended",
  "inclusive",
  "all-inclusive",
  "all-around",
  "generic",
  "outright",
  "encyclopedic",
  "indiscriminate",
  "catholic",
  "global",
  "worldwide",
  "international",
  "nationwide",
  "countrywide",
  "coast-to-coast",
  "in vogue",
  "company-wide",
  "restricted",
  "localized",
  "miscellaneous",
  "mixed",
  "assorted",
  "variegated",
  "diversified",
  "composite",
  "heterogeneous",
  "specialist",
  "usual",
  "customary",
  "habitual",
  "traditional",
  "normal",
  "conventional",
  "typical",
  "standard",
  "regular",
  "familiar",
  "accepted",
  "prevailing",
  "routine",
  "run-of-the-mill",
  "fixed",
  "set",
  "established",
  "confirmed",
  "everyday",
  "ordinary",
  "common",
  "stock",
  "well worn",
  "time-honored",
  "popular",
  "favorite",
  "exceptional",
  "broad",
  "imprecise",
  "inexact",
  "rough",
  "sweeping",
  "overall",
  "loose",
  "basic",
  "approximate",
  "nonspecific",
  "unspecific",
  "vague",
  "hazy",
  "fuzzy",
  "woolly",
  "ill-defined",
  "indefinite",
  "unfocused",
  "undetailed",
  "detailed",
];
