export const definitions = [
  '"double-bladed paddles"',
  '"double-bladed paddles"',
  '"cut cleanly using a sharp blade"',
  '"Lydia is being taught to run on blades"',
  '"the Paralympics brought prosthetics such as running blades into the limelight."',
  '"a blade of grass"',
  '"the director, a young blade in an oversized suit"',
  '"we bladed into the parking lot behind Mensky\'s"',
  '"cut cleanly using a sharp blade"',
  '"Lydia is being taught to run on blades"',
  '"the Paralympics brought prosthetics such as running blades into the limelight."',
  '"a blade of grass"',
  '"the director, a young blade in an oversized suit"',
  '"we bladed into the parking lot behind Mensky\'s"',
  '"we bladed into the parking lot behind Mensky\'s"',
];
export const synonyms = [
  "cutter",
  "carver",
  "cutting tool",
  "steel",
  "brand",
  "oar",
  "scull",
  "sweep",
  "spoon",
  "spade",
  "frond",
  "flag",
  "needle",
  "pad",
  "bract",
  "leaflet",
  "cotyledon",
  "foliole",
  "dandy",
  "fop",
  "gallant",
  "cavalier",
  "man about town",
  "dude",
  "blood",
  "coxcomb",
  "popinjay",
  "cutter",
  "carver",
  "cutting tool",
  "steel",
  "brand",
  "oar",
  "scull",
  "sweep",
  "spoon",
  "spade",
  "frond",
  "flag",
  "needle",
  "pad",
  "bract",
  "leaflet",
  "cotyledon",
  "foliole",
  "dandy",
  "fop",
  "gallant",
  "cavalier",
  "man about town",
  "dude",
  "blood",
  "coxcomb",
  "popinjay",
];
