export const definitions = [
  '"what a blamed old fool I\'ve been"',
  '"I am so blamed ignorant I don\'t know which ones go in pairs"',
  '"the inquiry blamed the engineer for the accident"',
  '"they blame youth crime on unemployment"',
];
export const synonyms = [
  "censure",
  "criticize",
  "condemn",
  "inculpate",
  "hold responsible",
  "hold accountable",
  "hold liable",
  "place/lay the blame on",
  "accuse of",
  "find/consider guilty of",
  "assign fault/liability/guilt to",
  "ascribe to",
  "attribute to",
  "impute to",
  "lay at the door of",
  "put down to",
  "set down to",
  "absolve",
  "forgive",
  "attribute",
  "assign",
  "ascribe",
  "put down",
  "set down",
  "accredit",
  "credit",
  "impute",
  "lay on",
  "pin on",
  "give the credit for",
  "blame on",
  "lay at the door of",
  "connect with",
  "associate with",
];
