export const definitions = [
  '"they saw their company name blazoned all over the media"',
  '"accounts of their ordeal blazoned to the entire nation"',
  '"the book contains tens of thousands of blazons of arms held by English families"',
  '"his knowledge of medieval blazon was unrivaled"',
];
export const synonyms = [
  "display",
  "exhibit",
  "show",
  "present",
  "spread",
  "emblazon",
  "plaster",
  "flaunt",
  "parade",
  "reveal",
  "put on display",
  "draw attention to",
  "publicize",
  "announce",
  "report",
  "communicate",
  "impart",
  "disclose",
  "reveal",
  "divulge",
  "leak",
  "publish",
  "broadcast",
  "transmit",
  "issue",
  "post",
  "put out",
  "distribute",
  "spread",
  "unfold",
  "disseminate",
  "circulate",
  "air",
  "herald",
  "trumpet",
  "advertise",
  "proclaim",
  "promulgate",
  "make known",
  "make public",
  "bring to public notice/attention",
];
