export const definitions = [
  '"twenty fireman fought the blaze"',
  '"the gardens in summer are a blaze ofcolor"',
  '"their relationship broke up in a blaze of publicity"',
  '""Go to blazes!" he shouted"',
  '"what in blue blazes are you all talking about?"',
  '"plumes of smoke rose from fires blazing around the city"',
  '"the fire was brought under control only to blaze up again on Wednesday"',
  '"Elijah felt the anger blaze up again"',
  '"the sun blazed down"',
  '"Barbara\'s eyes were blazing with anger"',
  '"we went in with guns blazing"',
  '"soldiers blazed away withsubmachine guns"',
  '"she blazed to a gold medal in the 200-meter sprint"',
  '"he blazed a drive into the rough"',
  '"small firms would set the pace, blazing a trail for others to follow"',
  '"tourists haven\'t blazed a trail to the top of this hill"',
  '""Pop stars and drugs" blazed the headline"',
];
export const synonyms = [
  "fire",
  "flames",
  "conflagration",
  "inferno",
  "holocaust",
  "firestorm",
  "glare",
  "gleam",
  "flash",
  "burst",
  "flare",
  "dazzle",
  "streak",
  "radiance",
  "brilliance",
  "beam",
  "glitter",
  "outburst",
  "burst",
  "eruption",
  "flare-up",
  "explosion",
  "outbreak",
  "blowup",
  "blast",
  "attack",
  "fit",
  "spasm",
  "paroxysm",
  "access",
  "rush",
  "gale",
  "flood",
  "storm",
  "hurricane",
  "torrent",
  "outpouring",
  "surge",
  "upsurge",
  "spurt",
  "effusion",
  "outflow",
  "outflowing",
  "ebullition",
  "boutade",
  "welling up",
  "outburst",
  "burst",
  "eruption",
  "flare-up",
  "explosion",
  "outbreak",
  "blowup",
  "blast",
  "attack",
  "fit",
  "spasm",
  "paroxysm",
  "access",
  "rush",
  "gale",
  "flood",
  "storm",
  "hurricane",
  "torrent",
  "outpouring",
  "surge",
  "upsurge",
  "spurt",
  "effusion",
  "outflow",
  "outflowing",
  "ebullition",
  "boutade",
  "welling up",
  "burn",
  "flame",
  "flare up",
  "be ablaze",
  "be alight",
  "be on fire",
  "be in flames",
  "be aflame",
  "be afire",
  "be ardent",
  "shine",
  "beam",
  "flash",
  "flare",
  "glare",
  "gleam",
  "glint",
  "dazzle",
  "glitter",
  "glisten",
  "be radiant",
  "burn brightly",
  "fire (away)",
  "let fly",
  "discharge",
  "shoot (away)",
  "blast (away)",
];
