export const definitions = [
  '"short-cropped blond hair"',
  '"her hair was dyed blond"',
  '"a tall blond woman"',
  '"she was blond and blue-eyed"',
  '"a New York office full of blond wood"',
  '"the three blondes posed together"',
  '"her hair was yellow—not any shade of blond, but yellow"',
];
export const synonyms = [
  "fair",
  "light",
  "light-colored",
  "light-toned",
  "yellow",
  "flaxen",
  "tow-colored",
  "strawberry blond",
  "yellowish",
  "golden",
  "silver",
  "silvery",
  "platinum",
  "ash blond",
  "bleached",
  "peroxide",
  "bottle-blond",
  "sun-bleached",
  "dark",
  "fair-haired",
  "tow-headed",
  "light-haired",
  "golden-haired",
  "brunette",
];
