export const definitions = [
  '"red blotches on her face"',
  '"her face was blotched and swollen with crying"',
];
export const synonyms = [
  "patch",
  "smudge",
  "pop",
  "dot",
  "spot",
  "speck",
  "speckle",
  "blot",
  "stain",
  "smear",
  "streak",
  "dab",
  "daub",
  "splash",
  "rash",
  "blemish",
  "freckle",
  "birthmark",
  "strawberry mark",
  "port wine stain",
  "eruption",
  "mark",
  "discoloration",
  "nevus",
  "hemangioma",
  "spot",
  "mark",
  "speck",
  "speckle",
  "smudge",
  "smear",
  "streak",
  "blemish",
  "cover with blotches",
];
