export const definitions = [
  '"the walls are covered with grainy blow-ups"',
  '"the occasional blow-ups he has at Lennie are understandable"',
  '"a blowup neck pillow"',
];
export const synonyms = [
  "magnification",
  "large print",
  "enprint",
  "reduction",
  "fit",
  "outburst",
  "flare-up",
  "pet",
  "paroxysm",
  "frenzy",
  "bad mood",
  "mood",
  "huff",
  "scene",
  "shit fit",
  "fit of temper",
  "fit of rage",
  "fit of pique",
  "mard",
];
