export const definitions = [
  '"this is the first time I have blurbed a whole line of books"',
];
export const synonyms = [
  'notice',
  'announcement',
  'bulletin',
  'commercial',
  'promotion',
  'write-up',
  'display',
  'poster',
  'leaflet',
  'pamphlet',
  'flyer',
  'bill',
  'handbill',
  'handout',
  'circular',
  'brochure',
  'sign',
  'placard',
  'folder',
  'dodger',
  'affiche',
  'publicize',
  'bill',
  'post',
  'announce',
  'broadcast',
  'proclaim',
  'trumpet',
  'call attention to',
  'promulgate',
  'promote',
  'market',
  'merchandise',
  'peddle',
  'display',
  'tout',
  'build up',
  'trail',
  'trailer',
  'make public',
  'make known',
  'give publicity to',
  'shout from the rooftops',
  'give notice of',
  'beat/bang the drum for',
];