export const definitions = [
  '"licenses were issued indiscriminately to any company"',
  '"everyone was issued with a gas mask"',
  '"the minister issued a statement"',
  '"Christmas stamps to be issued in November"',
  '"exotic smells issued from a nearby building"',
  '"the struggles of history issue from the divided heart of humanity"',
];
export const synonyms = [
  "supply",
  "provide",
  "furnish",
  "arm",
  "equip",
  "fit out",
  "rig out",
  "accoutre",
  "outfit",
  "fit up",
  "provision",
  "stock",
  "purvey",
  "accommodate",
  "present",
  "invest",
  "endow",
  "favor",
  "kit out",
  "withdraw",
  "send out",
  "put out",
  "release",
  "deliver",
  "publish",
  "announce",
  "proclaim",
  "broadcast",
  "promulgate",
  "communicate",
  "impart",
  "purvey",
  "circulate",
  "distribute",
  "spread",
  "disseminate",
  "utter",
  "bruit about/abroad",
  "withdraw",
  "emanate",
  "emerge",
  "proceed",
  "exude",
  "discharge",
  "flow (out/forth)",
  "pour (out/forth)",
  "gush (out/forth)",
  "come (out/forth)",
  "seep (out/forth)",
  "ooze (out/forth)",
  "spread out",
  "be uttered",
  "be emitted",
  "be transmitted",
  "result",
  "follow",
  "ensue",
  "develop",
  "stem",
  "spring",
  "arise",
  "start",
  "derive",
  "evolve",
  "proceed",
  "emerge",
  "emanate",
  "flow",
  "attend",
  "accompany",
  "be got",
  "be had",
  "be taken",
  "be caused by",
  "be the result of",
  "be brought on/about by",
  "be produced by",
  "originate in",
  "have its origin in",
  "be consequent on",
  "supervene on",
  "bring about",
];
