export const definitions = [
  '"wait for the glue to harden"',
  '"brick is made of moist clay hardened by heat"',
  '"she hardened her heart"',
  '"suspicion hardened into certainty"',
  '"as oil prices hardened from their recent lows, the US dollar fell"',
];
export const synonyms = [
  "solidify",
  "set",
  "congeal",
  "clot",
  "coagulate",
  "stiffen",
  "thicken",
  "cake",
  "freeze",
  "bake",
  "crystallize",
  "strengthen",
  "reinforce",
  "anneal",
  "vulcanize",
  "ossify",
  "petrify",
  "indurate",
  "inspissate",
  "gelatinize",
  "become hard",
  "become solid",
  "liquefy",
  "toughen",
  "desensitize",
  "inure",
  "case-harden",
  "deaden",
  "numb",
  "benumb",
  "anesthetize",
  "brutalize",
  "indurate",
  "make insensitive",
  "make tough",
  "make unfeeling",
  "harden someone's heart",
  "make callous",
  "soften",
];
