export const definitions = [
  '"he refused to hearken to Tom\'s words of wisdom"',
  '"now hearken and obey"',
];
export const synonyms = [
  'pay attention',
  'listen',
  'lend an ear',
  'take into consideration',
  'heed',
  'respect',
  'follow',
  'observe',
  'notice',
  'mark',
  'regard',
  'pay heed',
  'be attentive',
  'concentrate on',
  'take note of',
  'bear in mind',
  'give thought to',
  'be heedful of',
  'give ear',
  'disregard',
  'ignore',
];