export const definitions = [
  '"he hastened to refute the assertion"',
  '"we hastened back to Paris"',
  '"a move that could hasten peace talks"',
];
export const synonyms = [
  "hurry",
  "make haste",
  "hurtle",
  "dash",
  "dart",
  "race",
  "rush",
  "fly",
  "flash",
  "shoot",
  "streak",
  "bolt",
  "bound",
  "blast",
  "charge",
  "chase",
  "career",
  "hurry up",
  "speed up",
  "scurry",
  "scramble",
  "scamper",
  "scuttle",
  "sprint",
  "run",
  "gallop",
  "scutter",
  "post",
  "hie",
  "fleet",
  "go fast",
  "go quickly",
  "go like lightning",
  "go hell for leather",
  "dawdle",
  "crawl",
  "speed up",
  "accelerate",
  "quicken",
  "precipitate",
  "expedite",
  "advance",
  "step up",
  "facilitate",
  "aid",
  "assist",
  "help",
  "boost",
  "make faster",
  "hurry on",
  "push forward",
  "urge on",
  "spur on",
  "delay",
  "slow down",
];
