export const definitions = [
  '"he hauled his bike out of the shed"',
  '"she hauled on the reins"',
  '"he hauled himself along the cliff face"',
  '"they will be hauled into court next week"',
  '"the train was hauling a cargo of liquid chemicals"',
  '"Bennie hauls trash in North Philadelphia"',
  '"my plan was to haul offshore, well clear of the land"',
];
export const synonyms = [
  "drag",
  "pull",
  "tug",
  "heave",
  "hump",
  "trail",
  "draw",
  "tow",
  "manhandle",
  "hale",
  "push",
  "transport",
  "convey",
  "cart",
  "carry",
  "ship",
  "ferry",
  "move",
  "shift",
  "take",
];
