export const definitions = [
  '"that\'s where people are supposed to hang their wash"',
  '"a chain hanging freely over two pegs"',
  '"we could just hang the pictures on the walls"',
  '"the room in which the pictures will hang"',
  '"the walls of her hall were hung with examples of her work"',
  '"a long time was spent hanging a couple of doors"',
  '"this blend of silk and wool hangs well and resists creases"',
  '"if you\'re using lining paper, hang it horizontally"',
  '"he was hanged for murder"',
  '"she hanged herself in her cell"',
  '"both men were sentenced to hang"',
  '"they could all go hang"',
  '"I\'m hanged if I know"',
  '"a haze of smoke hung below the ceiling"',
  '"a sense of dread hung over him for days"',
  '"the machine has hung"',
  '"it kept hanging my computer"',
  '"I guess I wasn\'t cool enough to hang with them anymore"',
  '"we\'ll be walking along just hanging, chilling"',
  '"this leads to hanging a breaking ball"',
];
export const synonyms = [
  "dangle",
  "swing",
  "sway",
  "depend",
  "be suspended",
  "hang down",
  "be pendent",
  "rise",
  "put up",
  "fix",
  "attach",
  "affix",
  "fasten",
  "post",
  "display",
  "suspend",
  "stick up",
  "pin up",
  "tack up",
  "nail up",
  "put on a hook",
  "take down",
  "decorate",
  "adorn",
  "drape",
  "festoon",
  "trick out",
  "bedeck",
  "array",
  "furnish",
  "garland",
  "swathe",
  "cover",
  "ornament",
  "bedizen",
  "caparison",
  "furbelow",
  "deck out",
  "paste up",
  "stick up",
  "attach",
  "glue on",
  "fasten on",
  "fix on",
  "peel off",
  "gibbet",
  "lynch",
  "execute by hanging",
  "hang by the neck",
  "send to the gallows",
  "send to the gibbet",
  "send to the scaffold",
  "put to death",
  "gibbet",
  "lynch",
  "execute by hanging",
  "hang by the neck",
  "send to the gallows",
  "send to the gibbet",
  "send to the scaffold",
  "put to death",
  "hover",
  "float",
  "drift",
  "linger",
  "remain static",
  "be suspended",
  "be poised",
  "be dispersed",
];
