export const definitions = [
  '"the hazards of smoking"',
  '"a health hazard"',
  '"we can form no calculation concerning the laws of hazard"',
  '"he hazarded a guess"',
  '"the cargo business is too risky to hazard money on"',
];
export const synonyms = [
  'danger',
  'risk',
  'peril',
  'threat',
  'menace',
  'difficulty',
  'problem',
  'pitfall',
  'jeopardy',
  'perilousness',
  'endangerment',
  'imperilment',
  'chance',
  'probability',
  'fortuity',
  'luck',
  'fate',
  'destiny',
  'fortune',
  'providence',
  'serendipity',
  'accident',
  'happenstance',
  'venture',
  'put forward',
  'proffer',
  'advance',
  'volunteer',
  'conjecture',
  'speculate',
  'surmise',
  'opine',
  'risk',
  'jeopardize',
  'chance',
  'gamble',
  'stake',
  'bet',
  'endanger',
  'imperil',
  'put at risk',
  'take a chance with',
  'expose to danger',
  'put in jeopardy',
  'keep safe',
];