export const definitions = [
  '"a heavily loaded freight train"',
  '"a loaded gun"',
  '"your average chocolate bar is loaded with fat"',
  '"she doesn\'t really have to work—they\'re loaded"',
  '"man, did I get loaded after I left his house"',
  '"1989 Ford 250 LXT: low miles, loaded"',
  '"a trick like the one with the loaded dice"',
  '"avoid politically loaded terms like \"nation\""',
  '"\"Anything else?\" It was a loaded question and Kelly knew it"',
  '"they load up their dugout canoes"',
  '"stolen property from a burglary was loaded into a taxi"',
  '"when we came to the quay the ship was still loading"',
  '"I just went down to the store and loaded up on beer"',
  '"Elaine was loaded down with bags full of shopping"',
  '"the King and Queen loaded Columbus with wealth and honors"',
  '"the odds were loaded against them before the match"',
  '"he began to load the gun"',
  '"load your camera before you start"',
  '"load the cassette into the camcorder"',
  '"when the program is loaded into the microcomputer, the CPU carries out each instruction"',
];
export const synonyms = [
  'full',
  'filled',
  'laden',
  'packed',
  'burdened',
  'stuffed',
  'crammed',
  'brimming',
  'freighted',
  'stacked',
  'supplied',
  'stocked',
  'empty',
  'primed',
  'charged',
  'armed',
  'filled',
  'containing ammunition',
  'ready to fire',
  'ready for use',
  'unloaded',
  'rich',
  'wealthy',
  'well off',
  'well-to-do',
  'affluent',
  'prosperous',
  'moneyed',
  'cash rich',
  'with deep pockets',
  'of means',
  'poor',
  'drunk',
  'drunken',
  'inebriated',
  'intoxicated',
  'befuddled',
  'incapable',
  'tipsy',
  'under the influence',
  'maudlin',
  'blind drunk',
  '(as) drunk as a skunk',
  'sottish',
  'tippling',
  'toping',
  'sotted',
  'besotted',
  'foxed',
  'screwed',
  'crapulent',
  'crapulous',
  'inebriate',
  'bibulous',
  'the worse for drink',
  'dead drunk',
  'rolling drunk',
  'roaring drunk',
  '(as) drunk as a lord',
  'gin-soaked',
  'ebrious',
  'ebriose',
  'ebriate',
  'sober',
  'biased',
  'rigged',
  'fixed',
  'weighted',
  'honest',
  'charged',
  'meaningful',
  'pregnant',
  'tendentious',
  'emotive',
  'sensitive',
  'difficult',
  'delicate',
  'ingenuous',
  'straightforward',
  'fill',
  'fill up',
  'pack',
  'stuff',
  'cram',
  'pile',
  'heap',
  'stack',
  'lade',
  'freight',
  'charge',
  'stock',
  'unload',
  'pack',
  'stow',
  'store',
  'stack',
  'bundle',
  'stuff',
  'cram',
  'squeeze',
  'jam',
  'wedge',
  'place',
  'deposit',
  'put away',
  'unload',
  'burden',
  'weigh down',
  'saddle',
  'tax',
  'overtax',
  'stress',
  'strain',
  'overwhelm',
  'overload',
  'overburden',
  'trammel',
  'reward',
  'ply',
  'regale',
  'shower',
  'supply',
  'provide',
  'bias',
  'rig',
  'fix',
  'set up',
  'weight',
  'prime',
  'charge',
  'arm',
  'fill',
  'prepare to fire/use',
  'unload',
  'insert',
  'put',
  'place',
  'fit',
  'slide',
  'slot',
  'remove',
];