export const definitions = [
  '"borrowers can take out a loan for $84,000"',
  '"she offered to buy him dinner in return for the loan of the car"',
  '"the word processor was loaned to us by the theater"',
  '"he knew Rob would not loan him money"',
];
export const synonyms = [
  "credit",
  "advance",
  "mortgage",
  "overdraft",
  "debenture",
  "lending",
  "moneylending",
  "advancing",
  "lend",
  "advance",
  "credit",
  "allow",
  "let out",
  "lease",
  "charter",
  "hire",
  "borrow",
  "give credit",
  "give on loan",
  "give someone the loan of",
  "let someone have the use of",
  "ask for the loan of",
  "receive/take on loan",
  "use temporarily",
  "borrow",
];
