export const definitions = ['"she loathed him on sight"'];
export const synonyms = [
  "hate",
  "detest",
  "abhor",
  "despise",
  "abominate",
  "execrate",
  "hatred",
  "detestation",
  "abhorrence",
  "abomination",
  "execration",
  "odium",
  "antipathy",
  "dislike",
  "hostility",
  "animosity",
  "ill will",
  "ill feeling",
  "malice",
  "animus",
  "enmity",
  "aversion",
  "repugnance",
  "disgust",
  "revulsion",
  "dislike greatly",
  "have a strong aversion to",
  "feel repugnance toward",
  "not be able to bear",
  "not be able to stand",
  "shrink from",
  "recoil from",
  "be repelled by",
  "be unable to stomach",
  "find intolerable",
  "bad feeling",
  "love",
  "like",
];
