export const definitions = [
  '"it is impossible to specify the exact locus in the brain of these neural events"',
  '"the real locus of power is the informal council"',
  '"a parabola is the locus of a point that moves so as to be equidistant from a fixed point and a straight line"',
];
export const synonyms = [
  "emergency",
  "crisis",
  "problem",
  "difficulty",
  "issue",
  "plight",
  "predicament",
  "mess",
  "trouble",
  "bother",
  "emergency situation",
  "urgent situation",
  "potential crisis",
  "problematic situation",
  "awkward situation",
  "difficult situation",
  "tight spot",
  "tight corner",
  "location",
  "place",
  "position",
  "situation",
  "locality",
  "whereabouts",
  "locale",
  "spot",
  "scene",
  "setting",
  "vicinity",
  "area",
  "neighborhood",
  "district",
  "region",
  "environs",
  "zone",
  "locale",
  "territory",
  "community",
  "surrounding area",
  "neighborhood",
  "locality",
  "locale",
  "area",
  "district",
  "region",
  "quarter",
  "sector",
  "territory",
  "domain",
  "place",
  "zone",
  "environs",
  "surroundings",
  "surrounds",
  "precincts",
  "purlieus",
  "vicinage",
  "surrounding district",
  "surrounding area",
  "local area",
];
