export const definitions = [
  '"a hunting lodge"',
  '"Cumberland Lodge"',
  '"the foundation of the Grand Lodge of England"',
  '"he has 28 days in which to lodge an appeal"',
  '"the money is lodged in a bank"',
  '"they had to remove a bullet lodged near his spine"',
  '"the image had lodged in her mind"',
  '"the man who lodged in the room next door"',
  '"she was lodged in the same hall"',
  '"the variety is high yielding, but it has mostly lodged"',
];
export const synonyms = [
  "gatehouse",
  "cottage",
  "toll house",
  "house",
  "cottage",
  "cabin",
  "chalet",
  "shooting box",
  "den",
  "lair",
  "hole",
  "sett",
  "retreat",
  "haunt",
  "shelter",
  "section",
  "branch",
  "chapter",
  "wing",
  "association",
  "society",
  "group",
  "club",
  "union",
  "guild",
  "fraternity",
  "brotherhood",
  "sorority",
  "alliance",
  "coterie",
  "league",
  "sodality",
  "submit",
  "register",
  "enter",
  "put forward",
  "place",
  "advance",
  "lay",
  "present",
  "press",
  "bring",
  "prefer",
  "tender",
  "proffer",
  "record",
  "file",
  "table",
  "put on record",
  "deposit",
  "put",
  "bank",
  "entrust",
  "consign",
  "stash",
  "store",
  "stow",
  "put away",
  "lay in",
  "squirrel away",
  "stick",
  "catch",
  "wedge",
  "come to rest",
  "remain",
  "become fixed",
  "embed itself",
  "become embedded",
  "become implanted",
  "get/become stuck",
  "become caught",
  "become settled",
  "anchor itself",
  "become anchored",
  "reside",
  "board",
  "stay",
  "put up",
  "live",
  "stop",
  "occupy",
  "room",
  "dwell",
  "sojourn",
  "abide",
  "have lodgings",
  "have rooms",
  "take a room",
  "be quartered",
  "be domiciled",
  "accommodate",
  "put up",
  "take in",
  "house",
  "board",
  "billet",
  "quarter",
  "shelter",
  "harbor",
  "cater for",
  "entertain",
  "provide accommodation for",
  "provide shelter for",
];
