export const definitions = [
  '"a long corridor"',
  '"long black hair"',
  '"the line for tickets was long"',
  '"a boat 150 feet long"',
  '"how long is the leash?"',
  '"I went for a long walk"',
  '"he threw a long ball to the catcher"',
  '"a sweater with long sleeves"',
  '"shaped like a torpedo, long and thin"',
  '"a long and distinguished career"',
  '"she took a long time to dress"',
  '"the debates will be 90 minutes long"',
  '"serving long hours on the committee"',
  '"write a long report"',
  '"a long list of candidates"',
  '"the statement was three pages long"',
  '"winning against long odds"',
  '"you\'re taking a long chance"',
  '"an industry that seems long on ideas but short on cash"',
  '"we hadn\'t known them long"',
  '"an experience they will long remember"',
  '"his long - awaited Grand Prix debut"',
  '"how long have you been working?"',
  '"the work was compiled long after his death"',
  '"it was abandoned long ago"',
  '"he could not wait any longer"',
  '"it rained all day long"',
  '"the quarterback dropped back and threw the ball long"',
  '"he threw the ball long"',
];
export const synonyms = [
  "lengthy",
  "extended",
  "prolonged",
  "extensive",
  "long-lasting",
  "lasting",
  "of considerable length",
  "stretched out",
  "spread out",
  "short",
  "lengthways",
  "lengthwise",
  "in length",
  "prolonged",
  "protracted",
  "lengthy",
  "overlong",
  "extended",
  "long-drawn-out",
  "drawn-out",
  "lingering",
  "interminable",
  "tedious",
  "boring",
  "wearisome",
  "spun-out",
  "dragged-out",
  "seemingly endless",
  "short",
  "brief",
];
