export const definitions = [
  '"a loose tooth"',
  '"the truck\'s trailer came loose"',
  '"wear your hair loose"',
  '"pockets bulging with loose change"',
  '"the bull was loose with cattle in the field"',
  '"the tethered horses broke loose"',
  '"many patients report loose bowel movements"',
  '"she slipped into a loose T-shirt and shorts"',
  '"a loose weave"',
  '"a loose federation of political groups"',
  '"she swung back into her easy, loose stride"',
  '"a loose interpretation"',
  '"there is too much loose talk about the situation"',
  '"she ran the risk of being called a loose woman"',
];
export const synonyms = [
  "insecure",
  "unsecured",
  "unattached",
  "detached",
  "unfastened",
  "wobbly",
  "rickety",
  "unsteady",
  "movable",
  "not fixed in place",
  "not secure",
  "secure",
  "tight",
  "untied",
  "unpinned",
  "unbound",
  "down",
  "flowing",
  "floppy",
  "hanging free",
  "free",
  "at large",
  "at liberty",
  "on the loose",
  "escaped",
  "unconfined",
  "untied",
  "unchained",
  "untethered",
  "unsecured",
  "unshackled",
  "unfastened",
  "unrestricted",
  "unbound",
  "freed",
  "liberated",
  "released",
  "let go",
  "set loose",
  "secure",
  "baggy",
  "loose-fitting",
  "slack",
  "roomy",
  "boyfriend",
  "oversized",
  "shapeless",
  "bagging",
  "lax",
  "hanging",
  "sagging",
  "sloppy",
  "slouchy",
  "easy-fitting",
  "generously cut",
  "tight",
  "vague",
  "indefinite",
  "inexact",
  "imprecise",
  "ill-defined",
  "broad",
  "general",
  "rough",
  "nonspecific",
  "inexplicit",
  "liberal",
  "unrigorous",
  "unmeticulous",
  "literal",
  "narrow",
];
