export const definitions = [
  '"they lopped off more branches to save the tree"',
  '"they had lopped some trees without permission"',
  '"it lops an hour off commuting time"',
  '"a stomach that lopped over his belt"',
  '"he lopped toward the plane"',
];
export const synonyms = [
  "cut",
  "chop",
  "hack",
  "saw",
  "hew",
  "slice",
  "pare",
  "prune",
  "sever",
  "clip",
  "trim",
  "snip",
  "dock",
  "crop",
  "remove",
  "detach",
  "excise",
  "remove",
  "cut",
  "slash",
  "axe",
  "take",
  "trim",
  "prune",
  "dock",
  "truncate",
  "eliminate",
];
