export const definitions = [
  '"a matter of the utmost importance"',
  '"a plot that stretches credulity to the utmost"',
];
export const synonyms = [
  'greatest',
  'maximum',
  'highest',
  'most',
  'uttermost',
  'maximal',
  'extreme',
  'supreme',
  'paramount',
  'superlative',
  'enormous',
  'major',
  'greatest possible',
  'most extreme',
  'greatest amount of',
  'least possible',
  'very little',
  'best',
  'uttermost',
  'hardest',
  'maximum',
  'greatest possible extent',
  'least',
];