export const definitions = [
  '"experiments were carried out using sets of identical twins"',
  '"the twins were approaching their third birthday"',
  '"I thought you must have a double or be a twin"',
  '"there was a bruise on his cheek, a twin to the one on mine"',
  '"the hotel has 54 rooms, of which 4 are twins"',
  '"the company twinned its core business of brewing with that of distilling"',
];
export const synonyms = [
  "identical twins",
  "fraternal twins",
  "Siamese twins",
  "nonidentical twins",
  "monozygotic/monozygous twins",
  "dizygotic/dizygous twins",
  "mirror image",
  "double",
  "duplicate",
  "carbon copy",
  "replica",
  "lookalike",
  "clone",
  "counterpart",
  "match",
  "pair",
  "fellow",
  "mate",
  "partner",
  "exact likeness",
  "(living) image",
  "Doppelgänger",
  "combine",
  "join",
  "link",
  "couple",
  "pair",
  "yoke",
  "match",
];
