export const definitions = [
  '"she twined her arms around his neck"',
  '"runner beans twined around canes"',
  '"a spray of jasmine was twined in her hair"',
];
export const synonyms = [
  'string',
  'cord',
  'yarn',
  'strong thread',
  'wind',
  'entwine',
  'wrap',
  'lace',
  'wreathe',
  'coil',
  'loop',
  'twist',
  'spiral',
  'curl',
  'snake',
  'weave',
  'interweave',
  'interlace',
  'intertwine',
  'plait',
  'braid',
  'entwine itself',
];