export const definitions = [
  '"the dog twitched his ears"',
  '"he saw her lips twitch and her eyelids flutter"',
  '"he twitched a cigarette out of a packet"',
  '"his mouth gave a slight twitch"',
  '"he gave a twitch at his mustache"',
  '"he felt a twitch of annoyance"',
];
export const synonyms = [
  'jerk',
  'spasm',
  'convulse',
  'flutter',
  'quiver',
  'tremble',
  'shiver',
  'quaver',
  'shudder',
  'move spasmodically/convulsively',
  'snatch',
  'pluck',
  'pull',
  'tug',
  'tweak',
  'spasm',
  'convulsion',
  'jerk',
  'flutter',
  'quiver',
  'tremor',
  'shiver',
  'shudder',
  'tic',
  'convulsive movement',
  'pull',
  'tug',
  'tweak',
  'twinge',
  'dart',
  'stab',
  'prick',
  'pang',
];