export const definitions = [
  '"they babbled on about their vacation"',
  '"I gasped and stared and babbled, "Look at this!""',
  '"he babbled to another convict while he was in jail"',
  '"the shallow river babbled over smooth rocks"',
  '"the answers were difficult to hear amid the babble of conversation"',
  '"a confused babble of voices"',
  '"her soft voice stopped his babble"',
  '"the babble of a brook"',
  '"psychobabble"',
  '"technobabble"',
];
export const synonyms = [
  "prattle",
  "rattle on",
  "gabble",
  "chatter",
  "jabber",
  "twitter",
  "go on",
  "run on",
  "prate",
  "ramble",
  "burble",
  "blather",
  "blether",
  "blither",
  "maunder",
  "drivel",
  "patter",
  "yap",
  "jibber-jabber",
  "slabber",
  "twaddle",
  "clack",
  "twattle",
  "delirious",
  "raving",
  "babbling",
  "hysterical",
  "irrational",
  "lucid",
  "blab",
  "reveal",
  "divulge",
  "let out",
  "give away",
  "come out with",
  "blurt out",
  "let slip",
  "burble",
  "murmur",
  "gurgle",
  "purl",
  "tinkle",
  "plash",
  "clamor",
  "din",
  "racket",
  "tumult",
  "uproar",
  "hubbub",
  "babbling",
  "shouting",
  "yelling",
  "screaming",
  "commotion",
  "chaos",
  "bedlam",
  "pandemonium",
  "confusion",
  "shivaree",
  "confused noise",
  "stramash",
  "silence",
  "prattle",
  "gabble",
  "chatter",
  "jabber",
  "prating",
  "rambling",
  "blather",
  "blether",
  "gibbering",
  "gibberish",
  "drivel",
  "clack",
  "twattle",
  "burble",
  "purl",
  "lap",
  "plash",
  "roar",
  "thunder",
];
