export const definitions = [
  '"$3.3 million was provided by the project\'s backers"',
];
export const synonyms = [
  "sponsor",
  "investor",
  "subsidizer",
  "underwriter",
  "promoter",
  "financier",
  "patron",
  "benefactor",
  "benefactress",
  "guarantor",
  "supporter",
  "friend",
  "upholder",
  "champion",
  "defender",
  "advocate",
  "proponent",
  "protagonist",
  "seconder",
  "second",
  "booster",
  "Maecenas",
  "speculator",
  "risk-taker",
  "better",
  "bettor",
  "staker",
];
