export const definitions = [
  '"name badges"',
  '"a Girl Scout badge"',
  '"a large gold key hung around his neck as his badge of office"',
  '"my jeans had patches on the knees, like badges of courage marking encounters with barbed wire"',
  '"vendors can badge their products ‘certified’"',
];
export const synonyms = [
  "pin",
  "brooch",
  "button",
  "breastpin",
  "emblem",
  "crest",
  "insignia",
  "device",
  "shield",
  "escutcheon",
  "trademark",
  "logo",
  "sign",
  "symbol",
  "indication",
  "indicator",
  "signal",
  "mark",
  "token",
  "hallmark",
  "trademark",
];
