export const definitions = [
  '"herrings make excellent bait for pike"',
  '"fishing with live baits"',
  '"many potential buyers are reluctant to take the bait"',
  '"she used the prospect of freedom as bait to trap him into talking"',
  '"the other boys reveled in baiting him about his love of literature"',
  '"people who bait badgers"',
  '"she baited a trap with carrots and corn"',
];
export const synonyms = [
  "lure",
  "decoy",
  "fly",
  "troll",
  "jig",
  "plug",
  "teaser",
  "enticement",
  "lure",
  "decoy",
  "snare",
  "trap",
  "siren",
  "carrot",
  "attraction",
  "draw",
  "magnet",
  "incentive",
  "temptation",
  "allurement",
  "incitement",
  "inducement",
  "taunt",
  "goad",
  "provoke",
  "pick on",
  "torment",
  "torture",
  "persecute",
  "badger",
  "plague",
  "harry",
  "harass",
  "hound",
  "tease",
  "annoy",
  "irritate",
  "get someone's back up",
];
