export const definitions = [
  '"he was starting to go bald"',
  '"he had a shiny bald head"',
  '"hedgehogs are born bald"',
  '"the bald trunks with their empty branches"',
  '"my car had two bald tires"',
  '"the bald statement in the preceding paragraph requires amplification"',
];
export const synonyms = [
  "hairless",
  "bald-headed",
  "smooth",
  "shaven",
  "depilated",
  "baldy",
  "glabrous",
  "bald-pated",
  "hairy",
  "leafless",
  "bare",
  "uncovered",
  "stark",
  "lush",
  "plain",
  "simple",
  "unadorned",
  "unvarnished",
  "unembellished",
  "undisguised",
  "unveiled",
  "stark",
  "severe",
  "austere",
  "brutal",
  "harsh",
  "blunt",
  "direct",
  "forthright",
  "plain-spoken",
  "straight",
  "straightforward",
  "candid",
  "honest",
  "truthful",
  "realistic",
  "true to life",
  "frank",
  "outspoken",
  "downright",
  "outright",
  "explicit",
  "unequivocal",
  "unambiguous",
  "unqualified",
  "straight from the shoulder",
  "unexaggerated",
  "exhaustive",
];
