export const definitions = [
  '"any gardener will at first balk at enclosing the garden"',
  '"the utmost of his influence will be invoked to balk the law"',
  '"the lions, fearing to be balked of their prey"',
  '"the rookie balked and permitted Robinson to score"',
];
export const synonyms = [
  "eschew",
  "resist",
  "take exception to",
  "scorn",
  "disdain",
  "refuse to",
  "be unwilling to",
  "draw the line at",
  "be reluctant to",
  "draw back from",
  "flinch from",
  "shrink from",
  "shy from",
  "recoil from",
  "quail at",
  "demur from",
  "hesitate over",
  "scruple to",
  "not like to",
  "hate to",
  "jib at",
  "accept",
  "impede",
  "obstruct",
  "thwart",
  "hinder",
  "prevent",
  "check",
  "stop",
  "curb",
  "halt",
  "bar",
  "block",
  "forestall",
  "frustrate",
  "stall",
  "baffle",
  "foil",
  "defeat",
  "beat",
  "counteract",
  "head off",
  "assist",
];
