export const definitions = [
  '"the bandit produced a weapon and demanded money"',
];
export const synonyms = [
  'robber',
  'raider',
  'mugger',
  'brigand',
  'freebooter',
  'outlaw',
  'desperado',
  'hijacker',
  'plunderer',
  'pillager',
  'looter',
  'marauder',
  'gangster',
  'gunman',
  'criminal',
  'crook',
  'thief',
  'holdupper',
  'rustler',
  'highwayman',
  'footpad',
  'reaver',
  'cateran',
  'mosstrooper',
  'snaphance',
];