export const definitions = [
  '"he began to bang the table with his fist"',
  '"Sarah banged the phone down"',
  '"someone was banging on the door"',
  '"I banged my head on the low beams"',
  '"she banged into some shelves in the darkness"',
  '"in his second start he banged out two hits"',
  '"the shutter was banging in the wind"',
  '"he banged the kitchen door shut behind him"',
  '"the door banged open and a man staggered out"',
  '"she was banging around the kitchen"',
  '"the track bangs and is perfect for any house party"',
  '"the food bangs but isn\'t overpriced"',
];
export const synonyms = [
  'hit',
  'strike',
  'beat',
  'thump',
  'hammer',
  'knock',
  'rap',
  'pound',
  'thud',
  'punch',
  'bump',
  'thwack',
  'smack',
  'crack',
  'slap',
  'slam',
  'welt',
  'cuff',
  'pummel',
  'buffet',
  'explode',
  'crack',
  'detonate',
  'burst',
  'blow up',
  'go off with a bang',
  'crash',
  'smash',
  'thud',
  'go bang',
];