export const definitions = [
  '"students waved a ______ and chanted slogans"',
  '"a ______ in the front window announced \"Grand Reopening\""',
  '"the standard bearers followed, ______s of bright red and yellow depicting dragons and stags"',
  '"the administration is flying the free trade ______"',
  '"a ______ ad"',
  '"to get a new ______ now, click Step 1"',
  '"I predict that 2025 will be a ______ year"',
];
export const synonyms = [
  'placard',
  'sign',
  'poster',
  'notice',
  'flag',
  'standard',
  'ensign',
  'jack',
  'color (s)',
  'pennant',
  'pennon',
  'streamer',
  'banderole',
  'pendant',
  'burgee',
  'vexillum',
  'gonfalon',
  'guidon',
  'labarum',
];
