export const definitions = [
  '"there was much singing and good-natured banter"',
  '"the men bantered with the waitresses"',
];
export const synonyms = [
  "repartee",
  "raillery",
  "ripostes",
  "sallies",
  "swordplay",
  "quips",
  "wisecracks",
  "crosstalk",
  "wordplay",
  "badinage",
  "witticism(s)",
  "joking",
  "jesting",
  "jocularity",
  "drollery",
  "bons mots",
  "persiflage",
  "witty conversation",
  "witty remarks",
  "joke",
  "jest",
  "pun",
  "sally",
  "quip",
];
