export const definitions = [
  '"he had his hair cut at the local barber\'s"',
  '"his hair was neatly barbered"',
];
export const synonyms = [
  "cut",
  "clip",
  "trim",
  "snip",
  "shear",
  "shave",
  "pare",
  "prune",
  "fleece",
  "lop",
  "dock",
  "remove",
  "detach",
  "cut off",
  "hack off",
  "take off",
  "shorten",
  "tonsure",
  "cut short",
  "chop off",
  "make shorter",
  "cut shorter",
  "cut into a bob",
];
