export const definitions = [
  '"thick-barked trees that could resist fire"',
  '"a dog barked at her"',
  '"she barked with laughter"',
  '"he began barking out his orders"',
  '"\"Nobody is allowed up here,\" he barked"',
  '"he was barking at me to make myself presentable"',
  '"doormen bark at passersby, promising hot music and cold beer"',
  '"they had to be barked by hand, you couldn\'t peel them the way you can newly cut wood"',
  '"it\'s pitch black—I barked my shin and took a tumble in a nettle bed"',
];
export const synonyms = [
  'woof',
  'yap',
  'yelp',
  'bay',
  'growl',
  'snarl',
  'howl',
  'whine',
  'snap',
  'snarl',
  'growl',
  'shout',
  'bawl',
  'cry',
  'yell',
  'roar',
  'bellow',
  'thunder',
  'say/speak brusquely',
  'say/speak abruptly',
  'say/speak angrily',
  'scrape',
  'graze',
  'scratch',
  'abrade',
  'scuff',
  'rasp',
  'skin',
  'cut',
  'lacerate',
  'chafe',
  'strip',
  'flay',
  'wound',
  'excoriate',
  'rub something raw',
];