export const definitions = [
  '"the wine is then matured in old ______s"',
  '"a ______ of beer"',
  '"the well was producing 10,000 ______s a day"',
  '"a gun ______"',
  '"a Welsh mountain pony with a ______ like a butt of wine"',
  '"we ______ed across the Everglades"',
  '"they were ______ing along the Ventura freeway"',
  '"when the young spirit is ______ed, it absorbs some of this flavor"',
];
export const synonyms = [
  "cask",
  "keg",
  "butt",
  "vat",
  "tun",
  "tub",
  "drum",
  "tank",
  "firkin",
  "hogshead",
  "kilderkin",
  "pin",
  "pipe",
  "barrique",
  "solera",
  "puncheon",
  "tierce",
  "hurry",
  "race",
  "run",
  "sprint",
  "dash",
  "bolt",
  "dart",
  "rush",
  "hasten",
  "hurtle",
  "career",
  "streak",
  "shoot",
  "whiz",
  "zoom",
  "whirl",
  "whoosh",
  "buzz",
  "swoop",
  "flash",
  "blast",
  "charge",
  "stampede",
  "gallop",
  "sweep",
  "hare",
  "fly",
  "wing",
  "scurry",
  "scud",
  "scutter",
  "scramble",
  "fleet",
  "post",
  "hie",
  "drive",
  "go like lightning",
  "go hell for leather",
  "spank along",
  "bowl along",
  "rattle along",
  "amble",
  "stroll",
];
