export const definitions = [
  '"he sits by a barred window"',
  '"a barred gate"',
  '"he spotted a barred owl"',
  '"she bolts and bars the door"',
  '"she is barred from leaving the country"',
  '"boulders barred her passage"',
  '"the job she loved had been barred to her"',
  '"nothing is barred in the crime novel"',
  '"his face was barred with light"',
];
export const synonyms = [
  "bolt",
  "lock",
  "fasten",
  "padlock",
  "secure",
  "latch",
  "block",
  "barricade",
  "obstruct",
  "deadlock",
  "sneck",
  "snib",
  "unbar",
  "prohibit",
  "debar",
  "preclude",
  "forbid",
  "ban",
  "interdict",
  "inhibit",
  "exclude",
  "keep out",
  "obstruct",
  "hinder",
  "restrain",
  "check",
  "block",
  "impede",
  "stop",
  "enjoin",
  "estop",
  "admit",
  "accept",
];
