export const definitions = [
  '"he often bartered a meal for drawings"',
  '"the company is prepared to barter for Russian oil"',
  '"it will be paid for by a mixture of barter and cash"',
  '"I took a supply of coffee and cigarettes to use as barter"',
];
export const synonyms = [
  "trade",
  "swap",
  "trade off",
  "exchange",
  "change",
  "traffic",
  "sell",
  "give in exchange",
  "trading",
  "trade",
  "exchange",
  "swapping",
  "trafficking",
  "business",
  "commerce",
  "dealing",
  "haggling",
  "negotiation",
  "buying and selling",
];
