export const definitions = [
  '"the electorate\'s baser instincts of greed and selfishness"',
  '"we hope his motives are nothing so base as money"',
  '"the basest coins in the purse were made in the seventh century AD"',
];
export const synonyms = [
  "sordid",
  "improper",
  "low",
  "mean",
  "bad",
  "wrong",
  "evil",
  "wicked",
  "iniquitous",
  "immoral",
  "sinful",
  "unscrupulous",
  "unprincipled",
  "unseemly",
  "unsavory",
  "shoddy",
  "squalid",
  "vile",
  "foul",
  "vulgar",
  "tawdry",
  "cheap",
  "low-minded",
  "debased",
  "degenerate",
  "depraved",
  "corrupt",
  "reprobate",
  "dissolute",
  "dishonest",
  "dishonorable",
  "disreputable",
  "despicable",
  "discreditable",
  "contemptible",
  "petty",
  "ignominious",
  "ignoble",
  "shameful",
  "wretched",
  "scandalous",
  "infamous",
  "abhorrent",
  "abominable",
  "disgusting",
  "good",
  "lofty",
];
