export const definitions = [
  '"the film is based on a novel by Pat Conroy"',
  '"inaccurate conclusions based on incomplete facts"',
  '"a London-based band"',
  '"a research program based at the University of Arizona"',
];
export const synonyms = [
  'found',
  'build',
  'construct',
  'form',
  'establish',
  'ground',
  'root',
  'rest',
  'hinge',
  'use as a basis',
  'emanate from',
  'derive from',
  'spring from',
  'stem from',
  'originate in',
  'have its origin in',
  'can be traced back to',
  'locate',
  'station',
  'situate',
  'post',
  'position',
  'place',
  'install',
  'deploy',
  'site',
  'establish',
  'garrison',
];