export const definitions = [
  '"the latest row over city council junkets"',
  '"during the junket, the actor opened up about his character"',
  '"a plate of junket"',
  '"the mayor junketed off to Christchurch for a cricket match last week"',
];
export const synonyms = [
  'gathering',
  'function',
  'get-together',
  'celebration',
  'reunion',
  'festivity',
  'jamboree',
  'reception',
  'at-home',
  'soirée',
  'social',
  'dance',
  'ball',
  'ceilidh',
  'frolic',
  'carousal',
  'carouse',
  'fete',
  'hoedown',
  'shower',
  'bake',
  'cookout',
  'levee',
  'keg party',
  'corroboree',
  'luau',
  'simcha',
  'squash',
  'squeeze',
  'ding-dong',
  'social gathering',
  'social occasion',
  'social event',
  'social function',
  'bashment',
  'tertulia',
];