export const definitions = [
  '"a concern for justice, peace, and genuine respect for people"',
  '"the justice of his case"',
  '"a tragic miscarriage of justice"',
];
export const synonyms = [
  'fairness',
  'justness',
  'fair play',
  'fair-mindedness',
  'equity',
  'equitableness',
  'even-handedness',
  'egalitarianism',
  'impartiality',
  'objectivity',
  'neutrality',
  'disinterestedness',
  'open-mindedness',
  'nonpartisanship',
  'honor',
  'uprightness',
  'decency',
  'integrity',
  'probity',
  'honesty',
  'righteousness',
  'ethics',
  'morals',
  'morality',
  'virtue',
  'principle',
  'right-mindedness',
  'propriety',
  'scrupulousness',
  'trustworthiness',
  'incorruptibility',
  'impartialness',
  'lack of bias',
  'lack of prejudice',
  'injustice',
  'validity',
  'justification',
  'soundness',
  'legitimacy',
  'reasonableness',
  'well-foundedness',
  'legitimateness',
  'judicial proceedings',
  'administration of the law',
  'judge',
  'magistrate',
  'recorder',
  'sheriff',
  'jurat',
  'jurist',
  'surrogate',
  'alcalde',
  'reeve',
  'bailie',
  'His/Her/Your Honor',
  'Law Lord',
  'Lord Justice',
  'deemster',
  'sheriff-depute',
];