export const definitions = [
  '"a herd of female deer"',
  '"twenty-two of the participants in the study were female"',
  '"a female name"',
  '"females may lay several hundred eggs in two to four weeks"',
  '"both males and females accumulate economic knowledge at a similar rate"',
];
export const synonyms = [
  "feminine",
  "womanly",
  "womanlike",
  "she-",
  "feminal",
  "women's",
  "of women",
  "male",
  "lady",
  "girl",
  "person",
  "lass",
  "lassie",
  "wife",
  "colleen",
  "Frau",
  "Signora",
  "Señora",
  "maid",
  "maiden",
  "damsel",
  "demoiselle",
  "gentlewoman",
  "bitch",
  "adult female",
];
