export const definitions = [
  '"a man with a fetish for surgical masks"',
  '"a foot fetish"',
  '"he had a fetish for writing more opinions each year than any other justice"',
];
export const synonyms = [
  'fixation',
  'obsession',
  'compulsion',
  'mania',
  'weakness',
  'fancy',
  'taste',
  'fascination',
  'craze',
  'fad',
  'idée fixe',
  'sexual fixation',
  'juju',
  'talisman',
  'charm',
  'amulet',
  'totem',
  'icon',
  'idol',
  'image',
  'effigy',
  'doll',
  'statue',
  'figure',
  'figurine',
  'periapt',
];