export const definitions = [
  '"the buildings surround and dwarf All Saints church"',
  '"the insurance industry is still battling with a number of challenges that have dwarfed its growth"',
];
export const synonyms = [
  'gnome',
  'goblin',
  'hobgoblin',
  'troll',
  'imp',
  'elf',
  'brownie',
  'kelpie',
  'leprechaun',
  'fairy',
  'pixie',
  'sprite',
  'giant',
  'dominate',
  'overlook',
  'overshadow',
  'overtop',
  'outshine',
  'surpass',
  'exceed',
  'outclass',
  'outstrip',
  'outdo',
  'top',
  'cap',
  'trump',
  'transcend',
  'shame',
  'diminish',
  'minimize',
  'extinguish',
  'tower above',
  'tower over',
  'loom over',
  'put in the shade',
  'put to shame',
  'outrival',
];