export const definitions = [
  '"he affirmed the country\'s commitment to peace"',
  '"he affirmed that she was, indeed, a good editor"',
  '""Pessimism," she affirmed, "is the most rational view.""',
  '"the referendum affirmed the republic\'s right to secede"',
  '"there are five common ways parents fail to affirm their children"',
  '"good teachers know that students need to be both affirmed and challenged"',
  '"it is a rich and challenging motion picture that both affirms life and emphasizes its fragility"',
];
export const synonyms = [
  "declare",
  "state",
  "assert",
  "aver",
  "proclaim",
  "pronounce",
  "attest",
  "swear",
  "avow",
  "vow",
  "guarantee",
  "promise",
  "certify",
  "pledge",
  "asseverate",
  "give one's word",
  "give an undertaking",
  "deny",
  "uphold",
  "support",
  "defend",
  "maintain",
  "confirm",
  "ratify",
  "endorse",
  "sanction",
  "approve (of)",
  "agree to",
  "consent to",
  "assent to",
  "corroborate",
  "bear out",
  "verify",
  "prove",
  "validate",
  "authenticate",
  "substantiate",
  "justify",
  "vindicate",
  "give credence to",
  "support",
  "uphold",
  "back up",
  "show the truth of",
  "give substance to",
  "vouch for",
  "contradict",
  "repudiate",
  "swear",
  "pledge",
  "promise",
  "avow",
  "undertake",
  "engage",
  "commit",
  "guarantee",
  "depose",
  "plight",
  "asseverate",
  "swear/state under oath",
  "swear on the Bible",
  "take an oath",
  "give an undertaking",
  "commit oneself",
  "make a commitment",
  "give one's word",
  "give 's 's word of honor",
  "give an assurance",
  "make a deposition",
  "bind oneself",
];
