
export const definitions = [
  '"the best that I could ______ was a first-floor room"',
  '"we could never have ______ed to heat the place"',
  '"it was taking up more time than he could ______"',
  '"kings could ______ to be wrathful"',
  '"the rooftop terrace ______s beautiful views"',
  '"they were ______ed the luxury of bed and breakfast"',
];
export const synonyms = [
  'run to',
  'manage',
  'pay for',
  'bear/meet the expense of',
  'spare the price of',
  'have the money for',
  'be rich enough for',
  'have the wherewithal for',
  'stretch to',
  'bear',
  'sustain',
  'stand',
  'carry',
  'allow oneself',
  'provide',
  'supply',
  'present',
  'purvey',
  'offer',
  'give',
  'impart',
  'bestow',
  'furnish',
  'render',
  'grant',
  'yield',
  'produce',
  'bear',
  'make available',
];
