export const definitions = [
  '"I\'m ______ of dogs"',
  '"she tried to think about the future without feeling ______"',
  '"he was ______ that the farmer would send the dog after them"',
  '"she was ______ of antagonizing him"',
  '"I\'m often ______ to go out on the streets"',
  '"William was suddenly ______ for her"',
];
export const synonyms = [
  "frightened",
  "scared",
  "terrified",
  "fearful",
  "petrified",
  "nervous",
  "uneasy",
  "tense",
  "worried",
  "panicky",
  "terror-stricken",
  "terror-struck",
  "horror-stricken",
  "horror-struck",
  "beside oneself",
  "frantic",
  "hysterical",
  "timid",
  "timorous",
  "faint-hearted",
  "cowardly",
  "cowering",
  "cowed",
  "pusillanimous",
  "daunted",
  "nervy",
  "frit",
  "afeared",
  "affrighted",
  "scared stiff",
  "scared to death",
  "apprehensive (about)",
  "intimidated (by)",
  "alarmed (at)",
  "frightened/scared out of one's wits",
  "scared witless",
  "with one's heart in one's mouth",
  "shaking in one's shoes",
  "shaking like a leaf",
  "feart",
];
export const antonyms = [
  "un______",
  "brave",
  "confident",
  "reluctant",
  "unwilling",
  "disinclined",
  "loath",
  "slow",
  "hesitant about",
  "chary of",
  "shy of",
  "averse to",
  "keen",
  "confident",
];
