export const definitions = [
  '"they dabbled their feet in the rock pools"',
  '"teal dabble in the shallows"',
  '"he dabbled in writing as a young man"',
];
export const synonyms = [
  "splash",
  "dip",
  "paddle",
  "wet",
  "moisten",
  "dampen",
  "immerse",
  "trail",
  "play with",
  "toy with",
  "dip into",
  "scratch the surface of",
  "flirt with",
  "tinker with",
  "trifle with",
  "fiddle with",
  "dally with",
  "have a smattering of",
];
