export const definitions = [
  '"saucepans dangled from a rail"',
  '"they were dangling their legs over the water"',
  '"two rich commissions that had been dangling so sweetly in front of me"',
];
export const synonyms = [
  "hanging",
  "drooping",
  "droopy",
  "suspended",
  "pendulous",
  "pendent",
  "swinging",
  "swaying",
  "trailing",
  "flowing",
  "falling",
  "tumbling",
  "pensile",
  "droop",
  "sag",
  "swing",
  "sway",
  "wave",
  "trail",
  "stream",
  "depend",
  "supported from above",
  "hang (down)",
  "offer",
  "hold out",
  "entice someone with",
  "lure someone with",
  "tempt someone with",
  "tantalize someone with",
  "seduce someone with",
];
