export const definitions = [
  '"she daubed her face with night cream"',
  '"a canvas with paint daubed on it"',
  '"they daubed graffiti on the walls"',
];
export const synonyms = [
  "bedaub",
  "smear",
  "plaster",
  "bespatter",
  "splash",
  "stain",
  "spatter",
  "splatter",
  "cake",
  "smother",
  "coat",
  "deface",
  "slap",
  "besmear",
  "befoul",
  "besmirch",
  "begrime",
  "cover thickly",
  "smear",
  "plaster",
  "slather",
  "lather",
  "apply",
  "put",
  "smooth",
  "rub",
  "cover",
  "coat",
  "layer",
  "smother",
  "butter",
  "smear",
  "plaster",
  "spray",
  "spray-paint",
  "airbrush",
];
