export const definitions = [
  '"I couldn\'t dawdle over my coffee any longer"',
  '"Ruth dawdled back through the woods"',
];
export const synonyms = [
  'linger',
  'dally',
  'take one\'s time',
  'drag \'s \'s feet',
  'idle',
  'delay',
  'procrastinate',
  'stall',
  'hang fire',
  'mark time',
  'tarry',
  'be slow',
  'waste time',
  'kill time',
  'fritter time away',
  'putter around',
  'hurry',
  'amble',
  'stroll',
  'putter',
  'hold back',
  'fall behind',
  'go/walk slowly',
  'loiter (along)',
  'move at a snail\'s pace',
  'not keep pace',
  'lag behind',
  'trail behind',
  'speed',
];