export const definitions = ['"she was dazed by his revelations"'];
export const synonyms = [
  "stun",
  "stupefy",
  "knock out",
  "lay out",
  "astound",
  "amaze",
  "astonish",
  "startle",
  "take someone's breath away",
  "dumbfound",
  "overwhelm",
  "overcome",
  "overpower",
  "devastate",
  "dismay",
  "disconcert",
  "stagger",
  "shock",
  "confound",
  "bewilder",
  "nonplus",
  "shake up",
  "knock senseless",
  "knock unconscious",
  "take aback",
];
