export const definitions = [
  '"she was dazzled by the headlights"',
  '"I was dazzled by the beauty and breadth of the exhibition"',
  '"my eyes dazzled and I could not move"',
  '"a dazzle of green and red spotlights"',
];
export const synonyms = [
  'blind temporarily',
  'deprive of sight',
  'overpower',
  'overcome',
  'overwhelm',
  'impress',
  'bedazzle',
  'strike',
  'move',
  'stir',
  'affect',
  'touch',
  'sweep someone off their feet',
  'awe',
  'overawe',
  'take someone\'s breath away',
  'spellbind',
  'hypnotize',
  'fascinate',
  'daze',
  'stagger',
  'floor',
  'amaze',
  'astonish',
  'leave speechless',
  'take aback',
  'glare',
  'flare',
  'blaze',
  'brightness',
  'brilliance',
  'gleam',
  'flash',
  'shimmer',
  'radiance',
  'shine',
];