export const definitions = ['"she gave a rueful grin"'];
export const synonyms = [
  "sorrowful",
  "regretful",
  "apologetic",
  "sorry",
  "remorseful",
  "shamefaced",
  "sheepish",
  "hangdog",
  "contrite",
  "repentant",
  "penitent",
  "conscience-stricken",
  "self-reproachful",
  "woebegone",
  "woeful",
  "sad",
  "melancholy",
  "mournful",
  "compunctious",
  "happy",
  "unrepentant",
];
