export const definitions = [
  '"in an effort to save money, I have committed to only buying items that I truly need"',
  '"he was a keen gardener, winning many prizes for his efforts"',
  '"achieving independence requires some effort and self-discipline"',
  '"the war effort"',
];
export const synonyms = [
  "attempt",
  "try",
  "endeavor",
  "essay",
  "assay",
  "achievement",
  "accomplishment",
  "performance",
  "attainment",
  "result",
  "feat",
  "deed",
  "exploit",
  "undertaking",
  "enterprise",
  "work",
  "handiwork",
  "creation",
  "production",
  "opus",
  "triumph",
  "success",
  "coup",
  "master stroke",
  "stroke of genius",
  "positive result",
  "exertion",
  "force",
  "power",
  "energy",
  "work",
  "muscle",
  "application",
  "labor",
  "striving",
  "endeavor",
  "toil",
  "struggle",
  "slog",
  "strain",
  "stress",
  "trouble",
  "bother",
  "travail",
  "moil",
  "the sweat of one's brow",
];
