export const definitions = [
  '"this was the type of material that they effused about"',
];
export const synonyms = [
  "discharge",
  "release",
  "pour out",
  "send forth",
  "throw out",
  "void",
  "vent",
  "issue",
  "leak",
  "ooze",
  "shed",
  "excrete",
  "disgorge",
  "secrete",
  "eject",
  "spout",
  "belch",
  "emanate",
  "radiate",
  "exhale",
  "ejaculate",
  "exude",
  "eruct",
  "give out/off",
  "give vent to",
  "spew out",
  "absorb",
];
