export const definitions = [
  '"she watched him peel an apple with deliberate care"',
  '"with a small knife, peel the skin from the ginger"',
  '"oranges that peel easily"',
  '"the walls are peeling"',
  '"paint was peeling from the shopfronts"',
  '"the better players are capable of peeling a ball through two or three wickets"',
];
export const synonyms = [
  "pare",
  "skin",
  "strip",
  "shave",
  "trim",
  "flay",
  "hull",
  "shell",
  "husk",
  "shuck",
  "decorticate",
  "take the skin/rind off",
  "peel off",
  "pare",
  "remove",
  "take off",
  "trim (off)",
  "strip (off)",
  "shave (off)",
  "peel off",
  "blister",
  "exfoliate",
  "desquamate",
  "flake (off)",
  "come off in layers/strips",
];
