export const definitions = [
  '"drape individual plants with nets, pegging down the edges"',
  '"most music journalists have us pegged as a comedy band"',
  '"the catcher pegs the ball to the first baseman"',
];
export const synonyms = [
  "fix",
  "pin",
  "attach",
  "fasten",
  "secure",
  "make fast",
  "hold down",
  "keep down",
  "fix",
  "set",
  "hold",
  "control",
  "freeze",
  "limit",
  "throw",
  "toss",
  "fling",
  "pitch",
  "cast",
  "lob",
  "launch",
  "flip",
  "catapult",
  "shy",
  "dash",
  "send",
  "bowl",
  "aim",
  "direct",
  "project",
  "propel",
  "fire",
  "let fly",
  "catch",
  "hold",
];
