export const definitions = [
  '"the words were scribbled in pencil"',
  '"an eyebrow pencil"',
  '"a pencil of light"',
  '"a long pencil beam"',
  '"a previous owner has penciled their name inside the cover"',
];
export const synonyms = [
  "beam",
  "ray",
  "shaft",
  "finger",
  "gleam",
  "write",
  "write down",
  "note",
  "set down",
  "take down",
  "inscribe",
  "scribble",
  "rough out",
  "scrawl",
  "pen",
  "compose",
  "draft",
  "formulate",
  "draw up",
  "dash off",
  "draw",
  "trace",
  "plot",
  "chart",
  "sketch",
  "outline",
  "jot down",
  "write roughly",
  "put in writing",
  "put down on paper",
  "commit to paper",
  "put in black and white",
];
