export const definitions = ['"he died in a state of virtual penury"'];
export const synonyms = [
  "pennilessness",
  "impecuniousness",
  "impoverishment",
  "indigence",
  "need",
  "neediness",
  "want",
  "destitution",
  "privation",
  "deprivation",
  "hardship",
  "beggary",
  "bankruptcy",
  "insolvency",
  "ruin",
  "reduced circumstances",
  "pauperism",
  "pauperdom",
  "mendicity",
  "extreme/dire poverty",
  "straitened circumstances",
  "wealth",
  "affluence",
];
