export const definitions = [
  '"the earthquake killed 30,000 people"',
  '"his economic reforms no longer have the support of the people"',
  '"he is very much a man of the people"',
  '"pretrial statements made by the People\'s witnesses"',
  '"the native peoples of Canada"',
  '"I\'ve had my people watching the house for some time now"',
  '"my people live in West Virginia"',
  '"an arid mountain region peopled by warring clans"',
  '"the street is peopled with ragamuffin hippies"',
  '"it was his intention to people the town with English colonists"',
  '"the porter was the last person to see her"',
  '"she is a person of astonishing energy"',
  '"the entrance fee is $10.00 per person"',
  '"she\'s not a cat person"',
  '"his previous roles in the person of a fallible cop"',
  '"I have publicity photographs on my person at all times"',
];
export const synonyms = [
  "human beings",
  "persons",
  "individuals",
  "humans",
  "mankind",
  "humankind",
  "Homo sapiens",
  "humanity",
  "mortals",
  "personages",
  "the human race",
  "the human species",
  "(living) souls",
  "men, women, and children",
  "citizens",
  "subjects",
  "electors",
  "voters",
  "taxpayers",
  "residents",
  "inhabitants",
  "citizenry",
  "nation",
  "population",
  "populace",
  "community",
  "society",
  "(general) public",
  "the masses",
  "the multitude",
  "the commonality",
  "the third estate",
  "the crowd",
  "the proletariat",
  "the common people",
  "the populace",
  "the rank and file",
  "the commonalty",
  "the plebeians",
  "race",
  "tribe",
  "clan",
  "ethnic group",
  "strain",
  "stock",
  "caste",
  "nation",
  "country",
  "population",
  "populace",
  "breed",
  "folk",
  "seed",
  "family",
  "parents",
  "relatives",
  "relations",
  "folk",
  "kinsmen",
  "kin",
  "next of kin",
  "kinsfolk",
  "kinfolk",
  "kith and kin",
  "one's(own) flesh and blood",
  "blood relatives/relations",
  "nearest and dearest",
  "populate",
  "colonize",
  "inhabit",
  "live in",
  "occupy",
  "be",
  "settle (in)",
  "establish oneself in",
  "reside in",
  "domiciled in",
  "dwell in",
  "human being",
  "individual",
  "human",
  "being",
  "soul",
  "mortal",
  "creature",
  "fellow",
  "figure",
  "personage",
  "wight",
  "man/woman",
  "living soul",
  "individual",
  "creature",
  "fellow",
  "man",
  "woman",
  "wight",
  "ego",
  "I",
  "oneself",
  "persona",
  "identity",
  "character",
  "personality",
  "psyche",
  "soul",
  "spirit",
  "mind",
  "intellect",
  "inner man/woman/person",
  "inner self",
  "one's innermost feelings",
  "'s 's heart of hearts",
  "other",
  "body",
  "self",
  "backside",
];
