export const definitions = [
  '"phlegm and determination carried them through many difficult situations"',
];
export const synonyms = [
  "mucus",
  "catarrh",
  "mucous secretion",
  "self-control",
  "calmness",
  "calm",
  "coolness",
  "composure",
  "sangfroid",
  "level-headedness",
  "equanimity",
  "serenity",
  "tranquility",
  "placidity",
  "placidness",
  "impassivity",
  "self-possession",
  "self-confidence",
  "self-assurance",
  "stolidity",
  "stolidness",
  "imperturbability",
  "impassiveness",
  "dispassionateness",
];
