export const definitions = [
  '""to improve standards" is the key phrase here"',
  '"his favorite phrase is "it\'s a pleasure.""',
  '"the succession of downward phrases in the orchestra is so moving"',
  '"it\'s important to phrase the question correctly"',
  '"they phrased the music with gusto"',
];
export const synonyms = [
  "expression",
  "construction",
  "clause",
  "locution",
  "wording",
  "term",
  "turn of phrase",
  "idiom",
  "set phrase",
  "phrasal verb",
  "remark",
  "comment",
  "saying",
  "utterance",
  "witticism",
  "tag",
  "quotation",
  "quote",
  "citation",
  "line",
  "sentence",
  "group of words",
  "word group",
  "idiomatic expression",
  "phrasal idiom",
  "maxim",
  "saying",
  "proverb",
  "aphorism",
  "adage",
  "saw",
  "axiom",
  "formula",
  "expression",
  "rule",
  "dictum",
  "precept",
  "epigram",
  "gnome",
  "slogan",
  "catchphrase",
  "watchword",
  "byword",
  "cry",
  "battle cry",
  "truism",
  "cliché",
  "platitude",
  "apothegm",
  "express",
  "put",
  "word",
  "style",
  "formulate",
  "couch",
  "frame",
  "set forth",
  "utter",
  "say",
  "tell",
  "articulate",
  "verbalize",
  "communicate",
  "convey",
  "put into words",
  "get/put across",
];
