export const definitions = [
  '"she gave Mark a smack across the face"',
  '"she closed the ledger with a smack"',
  '"I was saluted with two hearty smacks on my cheeks"',
  '"Jessica smacked his face quite hard"',
  '"he smacked a fist into the palm of a black-gloved hand"',
  '"the tea smacked of peppermint"',
  '"the whole thing smacks of a cover-up"',
];
export const synonyms = [
  "slap",
  "blow",
  "spank",
  "cuff",
  "clout",
  "thump",
  "punch",
  "rap",
  "swat",
  "thwack",
  "crack",
  "bang",
  "crash",
  "thud",
  "thump",
  "wham",
  "kiss",
  "peck",
  "slap",
  "hit",
  "strike",
  "spank",
  "cuff",
  "clout",
  "thump",
  "punch",
  "rap",
  "swat",
  "thwack",
  "crack",
  "box someone's ears",
  "smite",
  "put someone over one's knee",
  "make someone feel the back of 's 's hand",
  "bang",
  "slam",
  "crash",
  "thump",
  "sling",
  "fling",
  "taste of",
  "have the flavor of",
  "have the savor of",
  "suggest",
  "resemble",
  "hint at",
  "have overtones of",
  "have a suggestion of",
  "have the air of",
  "give the impression of",
  "have the hallmark of",
  "have the stamp of",
  "seem like",
  "smell of",
  "reek of",
];
