export const definitions = [
  '"smooth flat rocks"',
  '"a smooth skin tans more easily"',
  '"cook gently until the sauce is smooth"',
  '"the smooth summer sea"',
  '"the trucks gave a smooth ride"',
  '"graphics are excellent, with fast, smooth scrolling"',
  '"the group\'s expansion into the U.S.market was not quite so smooth"',
  '"his voice was infuriatingly smooth"',
  '"a lovely, smooth, very fruity wine"',
  '"she smoothed out the newspaper"',
  '"you can use sandpaper to smooth the joint"',
  '"these doctrinal disputes were smoothed over"',
  '"a conference would be held to smooth the way for the establishment of the provisional government"',
  '"values are collected over a long period of time so that fluctuations are smoothed out"',
  '"the course of true love never did run smooth"',
];
export const synonyms = [
  'even',
  'level',
  'flat',
  'as flat as a pancake',
  'plane',
  'flush',
  'unwrinkled',
  'featureless',
  'polished',
  'burnished',
  'glossy',
  'shiny',
  'glassy',
  'sheeny',
  'lustrous',
  'sleek',
  'silky',
  'satiny',
  'clean-shaven',
  'hairless',
  'unrough',
  'smooth-shaven',
  'uneven',
  'rough',
  'dull',
  'hirsute',
  'creamy',
  'whipped',
  'velvety',
  'of an even consistency',
  'lumpy',
  'calm',
  'still',
  'tranquil',
  'placid',
  'serene',
  'undisturbed',
  'unruffled',
  'even',
  'flat',
  'glassy',
  'mirrorlike',
  'waveless',
  'dead calm',
  'like a millpond',
  'rough',
  'choppy',
  'straightforward',
  'easy',
  'effortless',
  'trouble-free',
  'untroubled',
  'well ordered',
  'simple',
  'plain sailing',
  'fraught',
  'suave',
  'urbane',
  'sophisticated',
  'polished',
  'debonair',
  'courteous',
  'gracious',
  'smooth-tongued',
  'glib',
  'media-savvy',
  'persuasive',
  'slick',
  'oily',
  'ingratiating',
  'unctuous',
  'gauche',
  'mellow',
  'mild',
  'agreeable',
  'pleasant',
  'bland',
  'soft',
  'soothing',
  'harsh',
  'bitter',
  'flatten',
  'level',
  'level off',
  'roll',
  'steamroll',
  'iron',
  'plane',
  'regularize',
  'make flat',
  'make level',
  'level out',
  'make even',
  'even off',
  'even out',
  'press (down)',
  'make uniform',
  'make regular',
  'settle',
  'resolve',
  'sort out',
  'iron out',
  'mend',
  'remedy',
  'heal',
  'cure',
  'rectify',
  'patch up',
  'put to rights',
  'ease',
  'facilitate',
  'pave the way for',
  'expedite',
  'assist',
  'aid',
  'help',
  'oil',
  'lubricate',
  'make easy',
  'make easier',
  'clear the way for',
  'smooth the way for',
  'open the door for',
  'help along',
  'oil the wheels of',
];