export const definitions = [
  '"a temple to Athena Nike, goddess of victory"',
  '"he had an affair with a screen goddess"',
];
export const synonyms = [
  "deity",
  "divinity",
  "immortal",
  "creator",
  "demiurge",
  "godhead",
  "daemon",
  "numen",
  "avatar",
  "divine being",
  "celestial being",
  "supreme being",
  "belle",
  "vision",
  "charmer",
  "enchantress",
  "Venus",
  "beauty queen",
  "picture",
  "seductress",
  "femme fatale",
  "beautiful woman",
  "English rose",
  "hag",
  "ugly woman",
];
