export const definitions = [
  '"curls of glossy golden hair"',
  '"bake until golden"',
  '"a golden crown"',
  '"those golden days before World War I"',
  '"a golden opportunity to boost foreign trade"',
  '"a choir of young golden voices"',
  '"the American Ballet Theater\'s golden anniversary extravaganza"',
];
export const synonyms = [
  "blond",
  "yellow",
  "yellowish",
  "fair",
  "flaxen",
  "tow-colored",
  "bright",
  "gleaming",
  "resplendent",
  "brilliant",
  "shining",
  "aureate",
  "gold-colored",
  "brunette",
  "dark",
  "successful",
  "prosperous",
  "flourishing",
  "thriving",
  "favorable",
  "propitious",
  "auspicious",
  "providential",
  "encouraging",
  "lucky",
  "fortunate",
  "happy",
  "joyful",
  "delightful",
  "glorious",
  "precious",
  "treasured",
  "unsuccessful",
  "unhappy",
  "excellent",
  "fine",
  "superb",
  "splendid",
  "tremendous",
  "special",
  "unique",
  "favorable",
  "opportune",
  "exciting",
  "promising",
  "bright",
  "brilliant",
  "rosy",
  "optimistic",
  "hopeful",
  "advantageous",
  "profitable",
  "valuable",
  "fortunate",
  "providential",
  "auspicious",
  "propitious",
  "full of promise",
];
