export const definitions = [
  '"the river comes alive during March when fish gorge on caddisworms"',
  '"we used to go to all the little restaurants there and gorge ourselves"',
];
export const synonyms = [
  "stuff",
  "cram",
  "fill",
  "glut",
  "satiate",
  "sate",
  "surfeit",
  "overindulge",
  "overfill",
  "overeat",
  "guzzle",
  "gobble",
  "bolt",
  "devour",
  "wolf",
  "binge-eat",
  "raven",
  "gluttonize",
  "gourmandize",
  "ingurgitate",
  "eat greedily/hungrily",
  "gulp (down)",
  "swallow hurriedly",
  "nibble",
];
