export const definitions = [
  '"the original settlers were forced to submit to Bulgarian rule"',
  '"the U.S. refused to submit to arbitration"',
  '"samples submitted to low pressure"',
  '"he submitted himself to a body search"',
  '"the panel\'s report was submitted to a parliamentary committee"',
  '"he submitted that such measures were justified"',
];
export const synonyms = [
  'give in',
  'yield',
  'give way',
  'back down',
  'cave in',
  'bow',
  'capitulate',
  'relent',
  'defer',
  'agree',
  'consent',
  'accede',
  'conform',
  'acquiesce',
  'comply',
  'accept',
  'surrender',
  'lay down one\'s arms',
  'knuckle under',
  'bend the knee',
  'kowtow',
  'fall',
  'observe',
  'heed',
  'tolerate',
  'endure',
  'brook',
  'put up with',
  'stomach',
  'suffer',
  'raise/show/wave the white flag',
  'humble oneself',
  'be governed by',
  'abide by',
  'be regulated by',
  'comply with',
  'adhere to',
  'be subject to',
  'agree to',
  'consent to',
  'conform to',
  'defy',
  'resist',
  'put through',
  'treat with',
  'expose to',
  'lay open to',
  'submit to',
  'put forward',
  'present',
  'set forth',
  'offer',
  'proffer',
  'tender',
  'advance',
  'propose',
  'suggest',
  'volunteer',
  'lodge',
  'introduce',
  'come up with',
  'raise',
  'air',
  'moot',
  'put in',
  'send in',
  'hand in',
  'enter',
  'register',
  'table',
  'withdraw',
  'contend',
  'assert',
  'argue',
  'state',
  'claim',
  'aver',
  'propound',
  'posit',
  'postulate',
  'adduce',
  'move',
  'advocate',
  'venture',
  'volunteer',
  'opine',
];