export const definitions = [
  '"his language expresses rich and subtle meanings"',
  '"subtle lighting"',
  '"he tried a more subtle approach"',
  '"a subtle mind"',
];
export const synonyms = [
  "fine",
  "fine-drawn",
  "ultra-fine",
  "nice",
  "overnice",
  "minute",
  "precise",
  "narrow",
  "tenuous",
  "hairsplitting",
  "indistinct",
  "indefinite",
  "elusive",
  "abstruse",
  "crude",
  "understated",
  "low-key",
  "muted",
  "toned down",
  "subdued",
  "delicate",
  "faint",
  "pale",
  "soft",
  "indistinct",
  "indefinite",
  "vague",
  "washed out",
  "lurid",
  "obvious",
  "astute",
  "keen",
  "quick",
  "fine",
  "acute",
  "sharp",
  "razor-sharp",
  "rapierlike",
  "canny",
  "shrewd",
  "aware",
  "perceptive",
  "discerning",
  "sensitive",
  "discriminating",
  "penetrating",
  "sagacious",
  "wise",
  "clever",
  "intelligent",
  "skillful",
  "artful",
  "sapient",
  "percipient",
  "perspicacious",
  "politic",
  "razor-like",
  "slow-witted",
  "ingenious",
  "clever",
  "skillful",
  "adroit",
  "cunning",
  "crafty",
  "wily",
  "artful",
  "devious",
  "crude",
  "artless",
];
