export const definitions = [
  '"if suckers will actually pay to do the work, more fool them"',
  '"what\'s needed is a sucker—sorry, brave volunteer—to test it out"',
  '"I always was a sucker for a good fairy tale"',
  '"he\'s one strong sucker"',
  '"they attach themselves to fish by means of a sucker"',
  '"the suckers run along each tentacle"',
  '"they got suckered into accepting responsibility"',
  '"it spread rapidly after being left undisturbed to sucker"',
];
export const synonyms = [
  "fool",
  "simpleton",
  "innocent",
  "dupe",
  "gull",
  "minion",
  "lackey",
  "flunkey",
  "hireling",
  "subordinate",
  "servant",
  "retainer",
  "vassal",
  "puppet",
  "pawn",
  "tool",
  "instrument",
  "cat's paw",
  "dupe",
  "enthusiast",
  "fanatic",
  "maniac",
  "addict",
  "devotee",
  "fan",
  "lover",
  "follower",
  "aficionado",
  "connoisseur",
  "appreciator",
  "side shoot",
  "shoot",
  "tendril",
  "runner",
  "scion",
  "slip",
  "offset",
  "sprout",
  "sprig",
  "stem",
  "twig",
  "branch",
  "bough",
  "limb",
  "spur",
  "stolon",
  "trunk",
  "deceive",
  "delude",
  "hoodwink",
  "mislead",
  "take in",
  "dupe",
  "fool",
  "double-cross",
  "cheat",
  "defraud",
  "swindle",
  "outwit",
  "outmaneuver",
  "catch out",
  "gull",
  "hoax",
  "bamboozle",
  "beguile",
  "entrap",
  "cozen",
  "chicane",
  "sell",
  "illude",
];
