export const definitions = [
  '"a sudden bright flash"',
  '"sudden there swooped an eagle downward"',
];
export const synonyms = [
  "unexpected",
  "unforeseen",
  "unanticipated",
  "unlooked-for",
  "immediate",
  "instantaneous",
  "instant",
  "precipitous",
  "precipitate",
  "abrupt",
  "rapid",
  "swift",
  "lightning",
  "quick",
  "hurried",
  "sharp",
  "without warning",
  "without notice",
  "not bargained for",
  "without delay",
  "gradual",
  "immediately",
  "instantaneously",
  "instantly",
  "straight away",
  "all of a sudden",
  "at once",
  "all at once",
  "promptly",
  "abruptly",
  "in a trice",
  "swiftly",
  "unexpectedly",
  "on the spur of the moment",
  "in an instant",
  "without warning",
  "without notice",
  "gradually",
];
