export const definitions = [
  '"her supple fingers"',
  '"my mind is becoming more supple"',
  '"this body oil leaves your skin feeling deliciously supple"',
];
export const synonyms = [
  "lithe",
  "limber",
  "nimble",
  "lissom",
  "flexible",
  "loose-limbed",
  "loose-jointed",
  "agile",
  "acrobatic",
  "fit",
  "deft",
  "willowy",
  "graceful",
  "elegant",
  "pliant",
  "pliable",
  "soft",
  "bendable",
  "workable",
  "malleable",
  "stretchy",
  "stretchable",
  "elastic",
  "springy",
  "yielding",
  "rubbery",
  "plastic",
  "resilient",
  "stiff",
  "unfit",
  "rigid",
  "inflexible",
];
