export const definitions = [
  '"she wore a beret over her bobbed blond hair"',
  '"I could see his red head bobbing around"',
  '"the boat bobbed up and down"',
  '"she bobbed her head"',
  '"a lady bobbed up from beneath the counter"',
  '"she bobbed and turned away"',
  '"she\'d had her hair bobbed and highlighted"',
];
export const synonyms = [
  "bounce",
  "float",
  "spring",
  "toss",
  "skip",
  "hop",
  "dance",
  "jump",
  "jounce",
  "quiver",
  "wobble",
  "jiggle",
  "joggle",
  "jolt",
  "jerk",
  "shake",
  "oscillate",
  "nod",
  "incline",
  "bow",
  "dip",
  "duck",
  "wag",
  "waggle",
  "move up and down",
  "curtsy",
  "bow",
  "genuflect",
  "drop a curtsy",
  "prostrate oneself",
];
