export const definitions = [
  '"a woolen ski hat with a bobble on top"',
  '"the glare of the snow made the landscape bobble"',
  '"Andy bobbled the ball, so his throw home was too late"',
  '"a once-a-season bobble by Jordan en route to a breakaway jam"',
];
export const synonyms = [
  "jiggle",
  "wriggle",
  "twitch",
  "flutter",
  "shimmy",
  "joggle",
  "wag",
  "wobble",
  "shake",
  "twist",
  "squirm",
  "writhe",
  "wave",
  "quiver",
  "jerk",
  "make a mess of",
  "bungle",
  "botch",
  "fluff",
  "fumble",
  "butcher",
  "mess up",
  "mismanage",
  "mishandle",
  "misdirect",
  "misgovern",
  "misconduct",
  "mar",
  "spoil",
  "ruin",
  "wreck",
  "manage successfully",
];
