export const definitions = [
  '"it\'s important to keep your body in good condition"',
  '"body temperature"',
  '"the blow almost severed his head from his body"',
  '"they found his body washed up on the beach"',
  '"a duality of body and soul"',
  '"he was just after her body"',
  '"a motherly body"',
  '"the body of the aircraft was filled with smoke"',
  '"information that changes regularly is kept apart from the main body of the text"',
  '"put your name, address, and daytime phone number in the email\'s body"',
  '"a rich body of Canadian folklore"',
  '"large bodies of seawater"',
  '"a regulatory body"',
  '"international bodies of experts"',
  '"the path taken by the falling body"',
  '"best of all, this wine has body and finish"',
  '"designed to add body to limp and straight hair"',
  '"he bodied forth the traditional Prussian remedy for all ills"',
  '"an era when automobiles were bodied over wooden frames"',
];
export const synonyms = [
  "anatomy",
  "figure",
  "frame",
  "form",
  "shape",
  "build",
  "physique",
  "framework",
  "skeleton",
  "bones",
  "corse",
  "soma",
  "flesh and bones",
  "torso",
  "trunk",
  "chest",
  "stomach",
  "middle",
  "corpse",
  "cadaver",
  "carcass",
  "skeleton",
  "remains",
  "relics",
  "dead body",
  "fellow",
  "thing",
  "individual",
  "soul",
  "character",
  "creature",
  "wretch",
  "person",
  "man",
  "woman",
  "boy",
  "girl",
  "wight",
  "bodywork",
  "hull",
  "fuselage",
  "outer casing",
  "principal part",
  "core",
  "heart",
  "hub",
  "nub",
  "kernel",
  "main part",
  "central part",
  "expanse",
  "mass",
  "area",
  "stretch",
  "region",
  "tract",
  "breadth",
  "sweep",
  "extent",
  "aggregate",
  "accumulation",
  "concretion",
  "accretion",
  "quantity",
  "amount",
  "volume",
  "collection",
  "proportion",
  "corpus",
  "association",
  "organization",
  "group",
  "grouping",
  "party",
  "band",
  "company",
  "society",
  "club",
  "circle",
  "fellowship",
  "partnership",
  "fraternity",
  "syndicate",
  "guild",
  "federation",
  "confederation",
  "bloc",
  "corporation",
  "contingent",
  "coterie",
  "clique",
  "object",
  "entity",
  "item",
  "piece of matter",
  "fullness",
  "solidity",
  "density",
  "thickness",
  "firmness",
  "substance",
  "mass",
  "shape",
  "structure",
];
