export const definitions = [
  '"their argument did not bode well for the future"',
  '"the 12 percent interest rate bodes dark days ahead for retailers"',
];
export const synonyms = [
  "augur",
  "presage",
  "portend",
  "foretell",
  "prophesy",
  "predict",
  "forebode",
  "foreshadow",
  "herald",
  "indicate",
  "signify",
  "purport",
  "point to",
  "threaten",
  "promise",
  "spell",
  "mean",
  "betoken",
  "foretoken",
  "adumbrate",
  "be an omen of",
  "warn of",
  "be a sign of",
];
