export const definitions = [
  '"children learn to control their bodily functions"',
  '"the idea of angels taking human bodily form when they come to earth"',
  '"he hauled her bodily from the van"',
  '"he launched himself bodily at the door"',
  '"he built ships on the Atlantic shore, transporting them bodily over the hills and sailing them off into the Pacific"',
];
export const synonyms = [
  'physical',
  'carnal',
  'fleshly',
  'animal',
  'hedonistic',
  'epicurean',
  'sybaritic',
  'voluptuary',
  'Dionysiac',
  'appetitive',
  'physically gratifying',
  'spiritual',
  'mental',
  'physical',
  'corporeal',
  'corporal',
  'mortal',
  'carnal',
  'fleshly',
  'sensual',
  'material',
  'concrete',
  'earthly',
  'real',
  'actual',
  'tangible',
  'substantial',
  'somatic',
  'spiritual',
  'mental',
  'forcefully',
  'powerfully',
  'forcibly',
  'violently',
  'wholly',
  'completely',
  'altogether',
  'entirely',
  'totally',
  'with force',
];