export const definitions = [
  '"a computer boffin"',
  '"he had a reputation as a tax boffin, a learned lawyer"',
];
export const synonyms = [
  "expert",
  "specialist",
  "authority",
  "genius",
  "mastermind",
  "scientist",
  "technician",
  "researcher",
  "inventor",
  "influence",
  "sway",
  "control",
  "leverage",
  "power",
  "command",
  "weight",
  "reputation",
  "standing",
  "kudos",
  "status",
  "stature",
  "prestige",
  "gravitas",
  "image",
  "esteem",
  "supremacy",
  "superiority",
  "eminence",
  "rank",
  "position",
  "station",
  "credibility",
  "plausibility",
  "integrity",
  "acceptance",
  "trust",
  "faith",
  "confidence",
];
