export const definitions = [
  '"a bold attempt to solve the crisis"',
  '"he was the only one bold enough to air his dislike"',
  '"she tossed him a bold look"',
  '"there is a market for bold movies and bold stars"',
  '"a coat with bold polka dots"',
  '"cross references are printed in bold type"',
];
export const synonyms = [
  "daring",
  "intrepid",
  "courageous",
  "brave",
  "valiant",
  "fearless",
  "unafraid",
  "undaunted",
  "dauntless",
  "valorous",
  "audacious",
  "adventurous",
  "dashing",
  "heroic",
  "gallant",
  "swashbuckling",
  "adventuresome",
  "daredevil",
  "venturesome",
  "plucky",
  "unflinching",
  "spirited",
  "confident",
  "positive",
  "decisive",
  "assured",
  "enterprising",
  "rash",
  "reckless",
  "brash",
  "foolhardy",
  "temerarious",
  "timid",
  "unadventurous",
  "brazen",
  "shameless",
  "forward",
  "brash",
  "impudent",
  "audacious",
  "cheeky",
  "saucy",
  "cocky",
  "pert",
  "impertinent",
  "insolent",
  "presumptuous",
  "immodest",
  "unabashed",
  "unreserved",
  "barefaced",
  "unshrinking",
  "defiant",
  "brass-necked",
  "bold as brass",
  "retiring",
  "striking",
  "vivid",
  "bright",
  "strong",
  "eye-catching",
  "conspicuous",
  "distinct",
  "pronounced",
  "prominent",
  "obvious",
  "outstanding",
  "showy",
  "flashy",
  "gaudy",
  "lurid",
  "garish",
  "well marked",
  "pale",
  "heavy",
  "thick",
  "clear",
  "conspicuous",
  "distinct",
  "pronounced",
  "outstanding",
  "light",
  "roman",
];
