export const definitions = [
  '"the strident boogie of the title track"',
  '"the pianist cruises through old-fashioned boogies"',
  '"ready to boogie down to the music of the house band"',
  '"he can boogie the night away"',
  '"I think we\'d better boogie on out of here"',
];
export const synonyms = [
  "dance",
  "dance",
  "jig",
  "leap",
  "jump",
  "skip",
  "bounce",
  "step it",
  "hurtle",
  "speed",
  "career",
  "shoot",
  "streak",
  "sweep",
  "hare",
  "fly",
  "wing",
  "drive",
  "motor",
  "move",
  "travel",
  "go",
  "proceed",
  "post",
  "hie",
];
