export const definitions = [
  '"I have booked a table at the Swan"',
  '"book early to avoid disappointment"',
  '"his secretary had booked him into the Howard Hotel"',
  '"book me a single room at my usual hotel"',
  '"the promoter booked him for another appearance"',
  '"I\'m booked till, like, 2014"',
  '"the cop booked me and took me down to the station"',
  '"they just ate your pizza and drank your soda and booked"',
  '"my sister and I booked to the playground"',
  '"I didn\'t hear the verdict because I had to book it to work"',
];
export const synonyms = [
  "reserve",
  "prearrange",
  "order",
  "charter",
  "hire",
  "engage",
  "bespeak",
  "arrange",
  "program",
  "schedule",
  "timetable",
  "line up",
  "secure",
  "lay on",
  "slate",
  "make a reservation for",
  "arrange in advance",
  "arrange for",
  "fix up",
];
