export const definitions = [
  '"her ample bosom"',
  '"the dress offered a fair display of bosom"',
  '"she had plucked the brooch from her bosom"',
  '"he carried a letter in his bosom"',
  '"Bruno went home each night to the bosom of his family"',
  '"quivering dread was settling in her bosom"',
];
export const synonyms = [
  "bust",
  "chest",
  "breasts",
  "mammary glands",
  "mammae",
  "dugs",
  "paps",
  "embonpoint",
  "protection",
  "heart",
  "core",
  "midst",
  "center",
  "circle",
  "shelter",
  "safety",
  "refuge",
  "heart",
  "breast",
  "soul",
  "being",
  "core",
  "spirit",
  "inner being",
  "seat of one's emotions",
  "seat of 's 's affections",
];
