export const definitions = [
  '"I asked my boss for a promotion"',
  '"does he see you as a partner, or is he already the boss?"',
  '"the boss of the largest crime family in the country"',
  '"he does not like being bossed around"',
  '"a heavy wooden shield with a metal boss"',
  '"the impact-absorbing boss of a steering wheel"',
  '"a climber with clusters of single white blooms around a pink central boss of stamens"',
];
export const synonyms = [
  'head',
  'chief',
  'principal',
  'director',
  'president',
  'executive',
  'chair',
  'chairperson',
  'chairman',
  'chairwoman',
  'manager',
  'manageress',
  'administrator',
  'leader',
  'superintendent',
  'supervisor',
  'foreman',
  'forewoman',
  'overseer',
  'controller',
  'employer',
  'master',
  'owner',
  'proprietor',
  'patron',
  'head man/woman',
  'top man/woman',
  'chief executive',
  'head',
  'chief',
  'principal',
  'director',
  'president',
  'executive',
  'chair',
  'chairperson',
  'chairman',
  'chairwoman',
  'manager',
  'manageress',
  'administrator',
  'leader',
  'superintendent',
  'supervisor',
  'foreman',
  'forewoman',
  'overseer',
  'controller',
  'employer',
  'master',
  'owner',
  'proprietor',
  'patron',
  'head man/woman',
  'top man/woman',
  'chief executive',
  'bully',
  'push around',
  'domineer',
  'dominate',
  'ride roughshod over',
  'pressurize',
  'browbeat',
  'throw one\'s weight around',
  'call the shots',
  'lay down the law',
  'order around',
  'give orders to',
  'dictate to',
  'impose one\'s will on',
  'lord it over',
  'trample on',
  'try to control',
  'use strong-arm tactics on',
];