export const definitions = ['"he does not like being bossed around"'];
export const synonyms = [
  "bully",
  "push around",
  "domineer",
  "dominate",
  "ride roughshod over",
  "pressurize",
  "browbeat",
  "throw one's weight around",
  "call the shots",
  "lay down the law",
  "order around",
  "give orders to",
  "dictate to",
  "impose one's will on",
  "lord it over",
  "trample on",
  "try to control",
  "use strong-arm tactics on",
];
