export const definitions = [
  '"the bottom of the page"',
  '"she paused at the bottom of the stairs"',
  '"the liner plunged to the bottom of the sea"',
  '"place the fruit on the bottom of the dish"',
  '"the shed at the bottom of the garden"',
  '"he started at the bottom and now has his own business"',
  '"pajama bottoms"',
  '"a skimpy bikini bottom"',
  '"river bottoms"',
  '"the double bottoms of the ship"',
  '"he climbs the side of the gorge, scratching his bottom unselfconsciously"',
  '"whatever his faults, he possesses that old-fashioned quality—bottom"',
  '"the bottom of the ninth"',
  '"the books on the bottom shelf"',
  '"households in the bottom income bracket"',
  '"interest rates have bottomed out"',
  ,
];
export const synonyms = [
  'foot',
  'base',
  'extremity',
  'foundation',
  'basis',
  'support',
  'substructure',
  'substratum',
  'groundwork',
  'underpinning',
  'lowest part',
  'lowest point',
  'top',
  'floor',
  'bed',
  'ground',
  'depths',
  'surface',
  'the furthest part',
  'the farthest point',
  'the far end',
  'the extremity',
  'top',
  'lowest level',
  'lowest position',
  'least important part',
  'least successful part',
  'least honorable part',
  'top',
  'base',
  'underside',
  'bottom side',
  'rear',
  'rump',
  'rear end',
  'backside',
  'seat',
  'buttocks',
  'cheeks',
  'hindquarters',
  'haunches',
  'derrière',
  'Sitzfleisch',
  'nates',
  'fundament',
  'posterior',
  'breech',
  'lowest',
  'last',
  'bottommost',
  'undermost',
  'ground',
  'basal',
  'highest',
];
