export const definitions = [
  '"the ball bounced away and he chased it"',
  '"he was bouncing the ball against the wall"',
  '"the ball bounced off the rim"',
  '"short sound waves bounce off even small objects"',
  '"I tried to email him, but the message bounced"',
  '"he was admired for his ability to bounce back from injury"',
  '"bouncing out with the bases loaded"',
  '"bounced a grounder to third"',
  '"bouncing up and down on the mattress"',
  '"the gangplank bounced under his confident step"',
  '"I remember how you used to bounce me on your knee"',
  '"the car bounced down the narrow track"',
  '"Linda bounced in through the open front door"',
  '"my rent check bounced"',
  '"I\'ve never bounced a check"',
  '"those who put in a dismal performance will be bounced from the tour"',
  '"a bad bounce caused the ball to get away from the second baseman"',
  '"a pitch of low bounce"',
  '"every bounce of the truck brought them into fresh contact"',
  '"a bounce on your knee or a cuddle and pat on the back"',
  '"economists agree that there could be a bounce in prices next year"',
  '"the bounce was now back in Jenny\'s step"',
  '"use conditioner to help hair regain its bounce"',
];
export const synonyms = [
  "rebound",
  "bob",
  "recoil",
  "ricochet",
  "jounce",
  "carom",
  "resile",
  "spring back",
  "recover",
  "revive",
  "rally",
  "pick up",
  "cheer up",
  "make a comeback",
  "take a turn for the better",
  "be on the mend",
  "be on the road to recovery",
  "perk up",
  "brighten up",
  "become livelier",
  "take heart",
  "be heartened",
  "liven up",
  "take on a new lease of life",
  "bound",
  "leap",
  "jump",
  "spring",
  "bob",
  "hop",
  "skip",
  "trip",
  "gambol",
  "dance",
  "prance",
  "romp",
  "caper",
  "cavort",
  "frisk",
  "frolic",
  "sport",
  "bound",
  "leap",
  "jump",
  "spring",
  "bob",
  "hop",
  "skip",
  "trip",
  "gambol",
  "dance",
  "prance",
  "romp",
  "caper",
  "cavort",
  "frisk",
  "frolic",
  "sport",
  "expel",
  "throw out",
  "turn out",
  "put out",
  "cast out",
  "remove",
  "oust",
  "evict",
  "dispossess",
  "banish",
  "deport",
  "exile",
  "put out in the street",
  "admit",
  "expulsion",
  "ejection",
  "ousting",
  "banishing",
  "banishment",
  "removal",
  "displacement",
  "clearance",
  "dispossession",
  "expropriation",
  "defenestration",
  "ouster",
  "outing",
  "throwing out",
  "drumming out",
  "driving out",
  "dislodgment",
  "admission",
  "springiness",
  "spring",
  "resilience",
  "elasticity",
  "give",
  "rebound",
  "recoil",
  "springiness",
  "spring",
  "resilience",
  "elasticity",
  "give",
  "rebound",
  "recoil",
  "rebound",
  "reflection",
  "ricochet",
  "vitality",
  "vigor",
  "energy",
  "vivacity",
  "liveliness",
  "life",
  "animation",
  "sparkle",
  "effervescence",
  "exuberance",
  "verve",
  "spiritedness",
  "spirit",
  "enthusiasm",
  "dynamism",
  "fire",
  "ardor",
  "zeal",
  "push",
  "drive",
  "cheerfulness",
  "cheeriness",
  "happiness",
  "joy",
  "buoyancy",
  "optimism",
  "high spirits",
  "light-heartedness",
  "merriment",
  "jollity",
  "ebullience",
];
