export const definitions = [
  '"bouncy floorboards"',
  '"a bouncy ball"',
  '"she was still the girl he remembered, bouncy and full of life"',
  '"the bouncy cheerfulness of polka"',
];
export const synonyms = [
  'springy',
  'flexible',
  'resilient',
  'elastic',
  'stretchy',
  'stretchable',
  'spongy',
  'rubbery',
  'bumpy',
  'jolting',
  'jolty',
  'lurching',
  'jerky',
  'jumpy',
  'jarring',
  'bone-shaking',
  'bone-breaking',
  'turbulent',
  'rough',
  'uncomfortable',
  'tensible',
  'lively',
  'energetic',
  'perky',
  'frisky',
  'jaunty',
  'zestful',
  'dynamic',
  'vital',
  'vigorous',
  'vibrant',
  'animated',
  'spirited',
  'buoyant',
  'bubbly',
  'bubbling',
  'sparkling',
  'effervescent',
  'vivacious',
  'sunny',
  'breezy',
  'enthusiastic',
  'upbeat',
  'bright and breezy',
];