export const definitions = [
  '"trees here and there bowered the cottages"',
  '"we dropped and weighed the massive bower anchor"',
];
export const synonyms = [
  "arbor",
  "alcove",
  "recess",
  "pergola",
  "grotto",
  "sanctuary",
  "summer house",
  "gazebo",
  "conservatory",
  "pavilion",
  "belvedere",
  "kiosk",
  "shady place",
  "leafy shelter",
  "arbor",
  "alcove",
  "recess",
  "pergola",
  "grotto",
  "sanctuary",
  "summer house",
  "gazebo",
  "conservatory",
  "pavilion",
  "belvedere",
  "kiosk",
  "shady place",
  "leafy shelter",
  "boudoir",
  "bedchamber",
  "chamber",
  "bedroom",
  "dressing room",
  "room",
];
