export const definitions = [
  '"the techniques by which the pieces were bowed"',
  '"he turned and bowed to his father"',
  '"she knelt and bowed her head"',
  '"councilors stood with heads bowed"',
  '"he looked at Hector before bowing grave thanks"',
  '"my mother sat bowed over a library book"',
  '"the tree next to the house bowed in the wind"',
  '"the vines were bowed down with flowers"',
  '"the trailer bowed in theaters nationwide on December 23"',
  '"the Pentium III bowed in early 1999"',
];
export const synonyms = [
  "nod",
  "curtsy",
  "bob",
  "salaam",
  "genuflect",
  "bend the knee",
  "kowtow",
  "incline the body",
  "incline the head",
  "make an obeisance",
  "make a bow",
  "drop a curtsy",
];
