export const definitions = [
  '"she snatched her hat off and bowled it ahead of her like a hoop"',
  '"Lillee bowled another bouncer"',
  '"Sobers bowled to Willis"',
  '"Stewart was bowled for 33"',
  '"they bowled along the country roads"',
  '"I usually bowl Tuesday nights"',
  '"she bowled a 162 high game"',
];
export const synonyms = [
  "pitch",
  "throw",
  "propel",
  "hurl",
  "toss",
  "lob",
  "loft",
  "fling",
  "launch",
  "let fly",
  "shy",
  "cast",
  "project",
  "send",
  "deliver",
  "spin",
  "roll",
  "hurtle",
  "speed",
  "career",
  "shoot",
  "streak",
  "sweep",
  "hare",
  "fly",
  "wing",
  "drive",
  "motor",
  "move",
  "travel",
  "go",
  "proceed",
  "post",
  "hie",
];
