export const definitions = [
  '"bald-headed men"',
  '"a seven-headed dragon"',
  '"woolly-headed thinking"',
  '"she was always cool-headed"',
  '"single-headed arrows"',
  '"short flat-headed nails"',
  '"headed cabbages"',
  '"female-headed households"',
  '"headed notepaper"',
  '"the Palm Sunday procession was headed by the crucifer"',
  '"Young heads a team of internationally recognized experts in bone disease and drug development"',
  '"an article headed \"The Protection of Human Life.\""',
  '"he was heading for the exit"',
  '"head towards the town center until the road takes a sharp right"',
  '"we were headed in the wrong direction"',
  '"I turned and headed home"',
  '"the economy is heading for recession"',
  '"traders all over the world are wondering just where stock markets are heading"',
  '"I fear we\'re headed for disaster"',
  '"the nation is headed towards a complete collapse"',
  '"she headed the car toward them"',
  '"a corner kick that he headed into the net"',
  '"the willow is headed every three or four years"',
];
export const synonyms = [
  'lead',
  'lead the way',
  'be at the front of',
  'be the leader of',
  'be at the head of',
  'be first',
  'go first',
  'be at the back of',
  'bring up the rear of',
  'command',
  'control',
  'lead',
  'run',
  'manage',
  'direct',
  'administer',
  'supervise',
  'superintend',
  'oversee',
  'rule',
  'govern',
  'captain',
  'be in charge of',
  'be at the head of',
  'be in command of',
  'be in control of',
  'be the leader of',
  'preside over',
  'be the boss of',
  'be at the helm of',
  'make for',
  'make a beeline for',
  'move toward',
  'go toward',
  'aim for',
  'make one\'s way toward',
  'go in the direction of',
  'direct one\'s steps toward',
  'be bound for',
  'steer for',
  'set out in the direction of',
  'set out for',
  'start out for',
  'move away from',
  'make for',
  'make a beeline for',
  'move toward',
  'go toward',
  'aim for',
  'make one\'s way toward',
  'go in the direction of',
  'direct one\'s steps toward',
  'be bound for',
  'steer for',
  'set out in the direction of',
  'set out for',
  'start out for',
  'move away from',
  'kick',
  'hit',
  'throw',
  'lob',
  'loft',
];