export const definitions = [
  '"high-heeled shoes"',
  '"high-heeled shoes"',
  '"shoes with low heels"',
  '"he rubbed the heel of his hand against the window"',
  '"what kind of a heel do you think I am?"',
  '"he played the perfect wrestling heel, arrogant, overly aggressive, yet the first to run away when the odds are not in his favor"',
  '"they were soling and heeling heavy working boots"',
  '"these dogs are born with the instinctive urge to heel"',
  '"they got into lines and began to heel, toe, and then jump together"',
  '"shoes with low heels"',
  '"he rubbed the heel of his hand against the window"',
  '"what kind of a heel do you think I am?"',
  '"he played the perfect wrestling heel, arrogant, overly aggressive, yet the first to run away when the odds are not in his favor"',
  '"they were soling and heeling heavy working boots"',
  '"these dogs are born with the instinctive urge to heel"',
  '"they got into lines and began to heel, toe, and then jump together"',
  '"they were soling and heeling heavy working boots"',
  '"these dogs are born with the instinctive urge to heel"',
  '"they got into lines and began to heel, toe, and then jump together"',
  '"the boat heeled in the freshening breeze"',
  '"the Mary Rose heeled over and sank in 1545"',
  '"the boat was heeled over so far that water sloshed over the gunwales"',
];
export const synonyms = [
  'wedge',
  'stiletto',
  'stiletto heel',
  'spike heel',
  'Cuban heel',
  'kitten heel',
  'wedge heel',
  'platform heel',
  'Louis heel',
  'stacked heel',
  'tail end',
  'crust',
  'end',
  'remnant',
  'remainder',
  'remains',
  'stump',
  'butt',
  'vestige',
  'wedge',
  'stiletto',
  'stiletto heel',
  'spike heel',
  'Cuban heel',
  'kitten heel',
  'wedge heel',
  'platform heel',
  'Louis heel',
  'stacked heel',
  'tail end',
  'crust',
  'end',
  'remnant',
  'remainder',
  'remains',
  'stump',
  'butt',
  'vestige',
  'list',
  'cant',
  'careen',
  'tilt',
  'tip',
  'incline',
  'slant',
  'slope',
  'lean over',
  'keel over',
  'be at an angle',
];