export const definitions = [
  '"a hired assassin"',
  '"management hired and fired labor in line with demand"',
  "\"don't hire a babysitter who's under 16\"",
  '"she had to hire a dress for the wedding"',
];
export const synonyms = [
  "employ",
  "engage",
  "recruit",
  "appoint",
  "take on",
  "sign on",
  "sign up",
  "enroll",
  "commission",
  "enlist",
  "take into employment",
  "secure the services of",
  "put on the payroll",
  "dismiss",
  "rent",
  "lease",
  "charter",
  "engage",
  "pay for the use of",
  "buy",
];
