export const definitions = [
  '"they considered the first primroses as the herald of spring"',
  '"the speech heralded a change in policy"',
  '"the band has been heralded as the industrial supergroup of the \'90s"',
];
export const synonyms = [
  "harbinger",
  "sign",
  "indicator",
  "indication",
  "signal",
  "prelude",
  "portent",
  "omen",
  "augury",
  "forewarning",
  "presage",
  "announcer",
  "forerunner",
  "precursor",
  "messenger",
  "usher",
  "foretoken",
  "avant-courier",
  "messenger",
  "courier",
  "proclaimer",
  "announcer",
  "crier",
  "town crier",
  "bearer of tidings",
  "signal",
  "indicate",
  "announce",
  "point to",
  "spell",
  "presage",
  "augur",
  "portend",
  "promise",
  "prefigure",
  "foreshadow",
  "foretell",
  "pave the way for",
  "precede",
  "come before",
  "forebode",
  "foretoken",
  "betoken",
  "harbinger",
  "usher in",
  "show in",
  "open the way for",
  "be a harbinger of",
  "be a forerunner",
  "be a precursor of",
];
