export const definitions = [
  '"heroic deeds"',
  '"a few heroic individuals"',
  '"early medieval heroic poetry"',
  '"one passes under pyramids and obelisks, all on a heroic scale"',
  '"the makeshift team performed heroics"',
];
export const synonyms = [
  "brave",
  "courageous",
  "valiant",
  "valorous",
  "intrepid",
  "bold",
  "daring",
  "audacious",
  "superhuman",
  "Herculean",
  "fearless",
  "doughty",
  "undaunted",
  "dauntless",
  "unafraid",
  "plucky",
  "indomitable",
  "stouthearted",
  "lionhearted",
  "mettlesome",
  "venturesome",
  "gallant",
  "stalwart",
  "chivalrous",
  "noble",
  "rock-ribbed",
  "venturous",
  "cowardly",
  "fearful",
  "prodigious",
  "grand",
  "enormous",
  "huge",
  "massive",
  "titanic",
  "colossal",
  "monumental",
  "stupendous",
  "epic",
  "Homeric",
  "modest",
];
