export const definitions = [
  '"steel cables held the convoy together"',
  '"he caught a glimpse of the mast, a cable or two downwind"',
  '"an underground cable"',
  '"transatlantic phone calls went by cable"',
  '"this was an occasion for using the telephone, not cables, teletexes, or letters"',
  '"I watch polo on cable"',
  '"he cabled her to cancel all arrangements"',
  '"the secretariat cabled a reply"',
  '"we cabled to a boat at sea, asking it to stop"',
  '"nearly all urban areas are cabled, so viewers can choose from up to 20 channels"',
];
export const synonyms = [
  "rope",
  "cord",
  "line",
  "guy",
  "wire",
  "chain",
  "hawser",
  "stay",
  "bridle",
  "topping lift",
  "choker",
  "piece of cordage",
  "wire",
  "lead",
  "cord",
  "power line",
  "flex",
  "send",
  "transmit",
  "radio",
  "telegraph",
  "radio-telegraph",
  "send",
  "transmit",
  "radio",
  "telegraph",
  "radio-telegraph",
];
