export const definitions = [
  '"an arms _____"',
  '"a _____ of gold coins"',
  '"there was a good supply of meat in the ______"',
  '"typical _____ sizes range from 64K to 256K"',
  '"he decided that they must _____ their weapons"',
  '"the operating system tries to _____ every disk operation"',
  '"the device comes complete with 4MB of RAM to _____ the hard drive"',
];
export const synonyms = [
  'hoard',
  'store',
  'stockpile',
  'stock',
  'supply',
  'collection',
  'accumulation',
  'reserve',
  'fund',
  'arsenal',
  'treasure',
  'nest egg',
  'hidden treasure',
  'amassment',
  'hiding place',
  'hole',
  'hideout',
  'storage place',
  'secret place',
  'memory bank',
  'store',
  'disk',
  'RAM',
  'ROM',
  'store',
  'stow',
  'pack',
  'load',
  'garner',
  'hide',
  'conceal',
  'secrete',
  'hoard',
  'put aside',
  'set aside',
  'put by',
  'lay by',
  'lay aside',
  'save',
  'stockpile',
  'reserve',
  'deposit',
  'keep',
  'keep in reserve',
  'put by for a rainy day',
];