export const definitions = ['"snow caused chaos in the region"'];
export const synonyms = [
  "disorder",
  "disarray",
  "disorganization",
  "confusion",
  "mayhem",
  "bedlam",
  "pandemonium",
  "madness",
  "havoc",
  "turmoil",
  "tumult",
  "commotion",
  "disruption",
  "upheaval",
  "furor",
  "frenzy",
  "uproar",
  "hue and cry",
  "babel",
  "hurly-burly",
  "anarchy",
  "entropy",
  "lawlessness",
  "a maelstrom",
  "a muddle",
  "a mess",
  "a shambles",
  "a mare's nest",
  "bangarang",
  "order",
  "orderliness",
];
