export const definitions = [
  '"they called their daughter Hannah"',
  '"she is called Eva"',
  '"a 1942 mystery called Time To Kill"',
  '"please call me Lucy"',
  '"some call him a genius"',
  '"he\'s the only person I would call a friend"',
  '"he heard an insistent voice calling his name"',
  '"Meredith was already calling out a greeting"',
  '"she heard Terry calling her"',
  '"I distinctly heard you call"',
  '"overhead, a skylark called"',
  '"her partner called 6♠"',
  '"I call first dibs on the bathroom"',
  '"could I call you back?"',
  '"at the first sign of heart attack symptoms call 911 immediately"',
  '"her husband called an ambulance"',
  '"representatives of all three teams have been called to appear before the stewards"',
  '"I got a letter calling me for an interview"',
  '"four expert witnesses were called"',
  '"she called him on his claim that the media were doing a bad job of covering the economy"',
  '"he was called to the priesthood"',
  '"I think teachers, really good teachers, are called to teach"',
  '"there appeared to be no alternative but to call a general election"',
  '"the Allied forces called a ceasefire"',
  '"she intends to call a meeting of the committee early next week"',
  '"he had promised Celia he would call in at the clinic"',
  '"he called around last night looking for you"',
  '"the linesman called the ball wide"',
  '"in the Northeast, the race remains too close to call"',
  '"few pundits risked calling the election for either Bush or Kerry"',
  '"Burnley called heads and won the toss"',
  '""You call," he said. "Heads or tails?""',
  '"one subroutine may call another subroutine (or itself)"',
];
export const synonyms = [
  "name",
  "christen",
  "baptize",
  "designate",
  "style",
  "term",
  "dub",
  "label",
  "entitle",
  "denominate",
  "answer to the name of",
  "clepe",
  "go by the name of",
  "name",
  "title",
  "entitle",
  "dub",
  "designate",
  "term",
  "address",
  "label",
  "tag",
  "christen",
  "baptize",
  "nickname",
  "denominate",
  "clepe",
  "describe as",
  "regard as",
  "look on as",
  "consider to be",
  "judge to be",
  "think of as",
  "class as",
  "categorize as",
  "cry out",
  "cry",
  "shout",
  "yell",
  "whoop",
  "bellow",
  "roar",
  "halloo",
  "bawl",
  "scream",
  "shriek",
  "screech",
  "exclaim",
  "ejaculate",
  "vociferate",
  "sing out",
  "cry out",
  "cry",
  "shout",
  "yell",
  "whoop",
  "bellow",
  "roar",
  "halloo",
  "bawl",
  "scream",
  "shriek",
  "screech",
  "exclaim",
  "ejaculate",
  "vociferate",
  "sing out",
  "phone",
  "telephone",
  "dial",
  "get",
  "reach",
  "ring up",
  "ring",
  "get on the phone to",
  "get someone on the phone",
  "make/place a call to",
  "give someone a ring",
  "summon",
  "send for",
  "ask for",
  "order",
  "page",
  "convene",
  "summon",
  "order",
  "assemble",
  "arrange",
  "announce",
  "declare",
  "convoke",
  "call together",
  "arrange a time/date for",
];
