export const definitions = [
  '"an intricate design of vees and scallops"',
  '"the tablecloth has a scallop edge"',
  '"the beaded lace overlay scalloped the neckline of the dress"',
  '"the spaces between the frets are scalloped out to form concavities"',
  '"in fall and early winter they went scalloping"',
  '"the season for scalloping is almost over"',
  '"the potatoes were scalloped with green peppers, onions, and herbs"',
];
export const synonyms = [
  "notch",
  "nick",
  "serrate",
  "pink",
  "cut",
  "scratch",
  "gash",
  "slit",
  "snick",
  "gouge",
  "groove",
  "furrow",
  "dent",
  "mark",
  "score",
  "incise",
  "carve",
  "engrave",
  "deboss",
  "make an indentation in",
  "make notches/nicks in",
];
