export const definitions = [
  '"earnest and callow undergraduates"',
];
export const synonyms = [
  'immature',
  'inexperienced',
  'naive',
  'green',
  'raw',
  'unseasoned',
  'untrained',
  'untried',
  'juvenile',
  'adolescent',
  'jejune',
  'innocent',
  'guileless',
  'artless',
  'unworldly',
  'unsophisticated',
  'as green as grass',
  'born yesterday',
  'mature',
  'experienced',
  'sophisticated',
];