export const definitions = [
  '"she had to keep calm at all costs"',
  '"his voice was calm"',
  '"the city was reported to be calm, but army patrols remained"',
  '"the night was clear and calm"',
  '"a dead calm sea"',
];
export const synonyms = [
  'serene',
  'tranquil',
  'relaxed',
  'unruffled',
  'unperturbed',
  'unflustered',
  'undisturbed',
  'unmoved',
  'unbothered',
  'untroubled',
  'equable',
  'even-tempered',
  'imperturbable',
  'quiet',
  'steady',
  'placid',
  'peaceful',
  'sedate',
  'unexcitable',
  'impassive',
  'dispassionate',
  'unemotional',
  'phlegmatic',
  'stolid',
  'composed',
  'cool',
  'collected',
  'as cool as a cucumber',
  'coolheaded',
  'self-possessed',
  'controlled',
  'self-controlled',
  'poised',
  'equanimous',
  'unagitated',
  'cool, calm, and collected',
  'excited',
  'upset',
  'nervous',
  'windless',
  'still',
  'tranquil',
  'quiet',
  'serene',
  'peaceful',
  'pacific',
  'undisturbed',
  'restful',
  'balmy',
  'halcyon',
  'windy',
  'stormy',
  'tranquil',
  'still',
  'smooth',
  'glassy',
  'flat',
  'motionless',
  'waveless',
  'stilly',
  'like a millpond',
  'unagitated',
  'storm-free',
  'rough',
  'stormy',
];