export const definitions = [
  '"he was forced to ______ his visit"',
  '"his visa had been ______ed"',
  '"I intend to ______ your debt to me"',
  '"the shipping costs ______ed out any savings"',
  '"the electric fields may ______ each other out"',
  '"multiplication and division sometimes ______ eachother out"',
  '"fans on social media are torn over whether to support or ______ him"',
  '"a stamp franked and with an adhesive ______"',
  '"a ______ title page"',
];
export const synonyms = [
  "call off",
  "abandon",
  "scrap",
  "drop",
  "postpone",
  "mothball",
  "annul",
  "invalidate",
  "nullify",
  "void",
  "revoke",
  "rescind",
  "retract",
  "countermand",
  "set aside",
  "take back",
  "withdraw",
  "recall",
  "repeal",
  "overrule",
  "override",
  "abrogate",
  "quash",
  "extinguish",
  "remit",
  "retire",
  "vacate",
  "discharge",
  "negate",
  "declare null and void",
  "render null and void",
  "disannul",
  "neutralize",
  "counterbalance",
  "counteract",
  "countervail",
  "negate",
  "nullify",
  "wipe out",
  "offset",
  "make up for",
  "negative",
  "balance (out)",
  "compensate for",
  "counterweigh",
];
