export const definitions = ['"a man of refreshing candor"'];
export const synonyms = [
  "frankness",
  "openness",
  "honesty",
  "candidness",
  "truthfulness",
  "sincerity",
  "forthrightness",
  "directness",
  "straightforwardness",
  "plain-spokenness",
  "plain dealing",
  "plainness",
  "unreservedness",
  "bluffness",
  "bluntness",
  "outspokenness",
  "lack of restraint",
  "calling a spade a spade",
  "guardedness",
  "evasiveness",
  "insincerity",
];
