export const definitions = [
  '"they would cross at the Town ford, under cover of the defending cannon"',
  '"the gunships blasted arms depots with 105 mm cannon fire and rockets"',
];
export const synonyms = [
  "gun",
  "mortar",
  "howitzer",
  "carronade",
  "bombard",
  "culverin",
  "falconet",
  "long tom",
  "serpentine",
  "pom-pom",
  "mounted gun",
  "field gun",
  "piece of artillery",
  "piece of ordnance",
  "gun",
  "mortar",
  "howitzer",
  "carronade",
  "bombard",
  "culverin",
  "falconet",
  "long tom",
  "serpentine",
  "pom-pom",
  "mounted gun",
  "field gun",
  "piece of artillery",
  "piece of ordnance",
];
