export const definitions = [
  '"children were capering about the room"',
  '"she did a little caper"',
  '"I\'m too old for this kind of caper"',
  '"a cop caper about intergalactic drug dealers"',
  '"add capers and olives"',
];
export const synonyms = [
  "skip",
  "dance",
  "romp",
  "jig",
  "frisk",
  "gambol",
  "cavort",
  "prance",
  "frolic",
  "leap",
  "hop",
  "jump",
  "bound",
  "spring",
  "curvet",
  "rollick",
  "capriole",
  "dance",
  "skip",
  "hop",
  "leap",
  "jump",
  "curvet",
  "gambado",
  "gambade",
  "escapade",
  "stunt",
  "prank",
  "trick",
  "practical joke",
  "antics",
  "high jinks",
  "mischief",
  "game",
  "sport",
  "fun",
  "jest",
  "jesting",
  "jape",
];
