export const definitions = [
  '"he capped his pen"',
  '"snow-capped mountains"',
  '"several towers were capped by domes"',
  '"his smile revealed perfectly capped teeth"',
  '"he capped a memorable season by becoming champion"',
  '"they capped each other\'s stories"',
  '"council budgets will be capped"',
];
export const synonyms = [
  "top",
  "crown",
  "cover",
  "coat",
  "blanket",
  "mantle",
  "round off",
  "crown",
  "perfect",
  "complete",
  "be a fitting climax to",
  "put the finishing touch/touches to",
  "beat",
  "better",
  "surpass",
  "outdo",
  "outshine",
  "trump",
  "top",
  "upstage",
  "improve on",
  "go one better than",
  "limit",
  "restrict",
  "curb",
  "control",
  "peg",
  "set a limit on",
  "put a ceiling on",
  "keep within bounds",
];
