export const definitions = [
  '"captain of the 20th precinct"',
  '"a captain of industry"',
  '"all the boats are captained by professional sailors"',
];
export const synonyms = [
  'commander',
  'master',
  'skipper',
  'flyer',
  'aeronaut',
  'commander',
  'copilot',
  'wingman',
  'aircrew',
  'aviator',
  'aviatrix',
  'birdman',
  'airman/airwoman',
  'first/second officer',
  'leader',
  'head',
  'skipper',
  'representative',
  'figurehead',
  'magnate',
  'tycoon',
  'mogul',
  'grandee',
  'baron',
  'nabob',
  'mandarin',
  'industrialist',
  'chief',
  'head',
  'leader',
  'boss',
  'principal',
  'command',
  'skipper',
  'run',
  'control',
  'govern',
  'direct',
  'rule',
  'manage',
  'supervise',
  'superintend',
  'be in charge of',
  'have charge of',
  'have control of',
  'preside over',
];