export const definitions = [
  '"she caressed the girl\'s forehead"',
  '"a gentle breeze caressed his skin"',
  '"she felt the caress of his breath on her cheek"',
];
export const synonyms = [
  "stroke",
  "touch",
  "fondle",
  "brush",
  "skim",
  "pet",
  "pat",
  "nuzzle",
  "kiss",
  "cuddle",
  "embrace",
  "hug",
  "stroke",
  "stroking",
  "touch",
  "touching",
  "fondle",
  "fondling",
  "skim",
  "pat",
  "nuzzle",
  "nuzzling",
  "kiss",
  "cuddle",
  "embrace",
  "hug",
];
