export const definitions = [
  '"a caring and invaluable friend"',
  '"the caring professions"',
  '"they don\'t care about human life"',
  '"I don\'t care what she says"',
  '"you care very deeply for him"',
  '"would you care for some tea?"',
  '"I don\'t care to listen to him"',
  '"he has numerous animals to care for"',
];
export const synonyms = [
  'kind',
  'kindhearted',
  'warmhearted',
  'softhearted',
  'tender',
  'feeling',
  'concerned',
  'attentive',
  'thoughtful',
  'solicitous',
  'responsible',
  'considerate',
  'affectionate',
  'loving',
  'doting',
  'fond',
  'warm',
  'benevolent',
  'benign',
  'humane',
  'good-natured',
  'gentle',
  'mild',
  'indulgent',
  'sympathetic',
  'understanding',
  'receptive',
  'compassionate',
  'charitable',
  'gracious',
  'long-suffering',
  'patient',
  'uncaring',
  'cruel',
  'bother',
  'mind',
  'be concerned',
  'worry (oneself)',
  'trouble oneself',
  'concern oneself with',
  'be interested in',
  'interest oneself in',
  'trouble oneself with',
  'have regard for',
  'burden oneself with',
  'love',
  'cherish',
  'treasure',
  'prize',
  'adore',
  'think the world of',
  'worship',
  'idolize',
  'be fond of',
  'feel affection for',
  'hold dear',
  'dote on',
  'be devoted to',
  'be in love with',
  'hate',
  'like',
  'want',
  'desire',
  'prefer',
  'fancy',
  'take a fancy to',
  'wish for',
  'have a fancy for',
  'feel like',
  'look after',
  'take care of',
  'tend',
  'mind',
  'nurse',
  'foster',
  'protect',
  'watch',
  'guard',
  'keep an eye on',
  'sit with',
  'babysit',
  'attend to',
  'minister to',
  'take charge of',
  'provide for',
  'be responsible for',
  'keep safe',
  'childmind',
  'neglect',
];