export const definitions = [
];
export const synonyms = [
  'voucher',
  'token',
  'ticket',
  'document',
  'certificate',
  'chit',
  'slip',
  'stub',
  'counterfoil',
  'receipt',
  'docket',
  'detachable portion',
  'authorization',
  'license',
  'pass',
  'voucher',
  'ticket',
  'warrant',
  'document',
  'certification',
  'passport',
  'visa',
  'triptyque',
  'laissez-passer',
  'firman',
];