export const definitions = [
  '"the house has wall-to-wall carpets throughout"',
  '"the floor was covered with carpet"',
  '"priceless Persian carpets"',
  '"carpets of snowdrops and crocuses"',
  '"the stairs were carpeted in a lovely shade of red"',
  '"the meadows are carpeted with flowers"',
];
export const synonyms = [
  "rug",
  "mat",
  "matting",
  "runner",
  "drugget",
  "floor covering",
  "covering",
  "blanket",
  "layer",
  "cover",
  "coat",
  "coating",
  "sheet",
  "film",
  "overlay",
  "cloak",
  "mantle",
  "canopy",
  "bed",
  "expanse",
  "crust",
  "cover",
  "coat",
  "overlay",
  "overspread",
  "blanket",
  "overlie",
  "pave",
  "extend over",
  "reprimand",
  "rebuke",
  "admonish",
  "chastise",
  "chide",
  "upbraid",
  "reprove",
  "reproach",
  "scold",
  "berate",
  "pull up",
  "castigate",
  "lambaste",
  "read someone the Riot Act",
  "give someone a piece of one's mind",
  "lecture",
  "criticize",
  "censure",
  "call down",
  "rate",
  "trim",
  "reprehend",
  "objurgate",
  "remonstrate with",
  "take to task",
  "haul over the coals",
  "give someone a rating",
  "praise",
  "commend",
  "compliment",
];
