export const definitions = [
  '"I don\'t want to carp about the way you did it"',
  '"he was constantly carping at me"',
];
export const synonyms = [
  "complaining",
  "cavilling",
  "grumbling",
  "moaning",
  "grousing",
  "grouching",
  "grouchy",
  "whining",
  "bleating",
  "fault-finding",
  "quibbling",
  "niggling",
  "captious",
  "nagging",
  "critical",
  "criticizing",
  "censorious",
  "condemnatory",
  "disparaging",
  "scathing",
  "slighting",
  "reproachful",
  "deprecatory",
  "hypercritical",
  "overcritical",
  "pedantic",
  "complain",
  "cavil",
  "grumble",
  "moan",
  "grouse",
  "grouch",
  "whine",
  "bleat",
  "quibble",
  "niggle",
  "nag",
  "criticize",
  "pick on",
  "censure",
  "denounce",
  "condemn",
  "decry",
  "disparage",
  "twine",
  "hard/difficult/impossible to please",
  "pass-remarkable",
  "find fault with",
  "mither",
  "forgiving",
  "complimentary",
  "praise",
];
