export const definitions = [
  '"a waterproof casing"',
  '"the towers are of steel cased in granite"',
  '"he cased his glasses carefully and walked out"',
  '"I was casing the joint"',
];
export const synonyms = [
  'cover',
  'case',
  'shell',
  'envelope',
  'sheath',
  'sheathing',
  'wrapper',
  'wrapping',
  'sleeve',
  'jacket',
  'housing',
  'capsule',
  'folder',
  'integument',
  'cover',
  'surround',
  'coat',
  'encase',
  'sheathe',
  'wrap',
  'envelop',
  'cover',
  'surround',
  'coat',
  'encase',
  'sheathe',
  'wrap',
  'envelop',
  'reconnoiter',
  'inspect',
  'investigate',
  'examine',
  'scrutinize',
  'survey',
  'scout',
  'explore',
  'make an observation of',
  'take stock of',
];