export const definitions = [
  '"members of the lower castes"',
  '"a man of high caste"',
  '"caste has survived among Goa\'s Christians"',
  '"the caste system"',
  '"those educated in private schools belong to a privileged caste"',
  '"in both ants and termites the workers can include specialist castes such as soldiers"',
];
export const synonyms = [
  "class",
  "social class",
  "order",
  "grade",
  "grading",
  "group",
  "grouping",
  "station",
  "stratum",
  "echelon",
  "rank",
  "level",
  "degree",
  "set",
  "place",
  "standing",
  "position",
  "status",
  "varna",
  "estate",
  "sphere",
  "social order",
  "social division",
];
