export const definitions = [
  '"Carradine catnapped in a hammock between two chairs"',
];
export const synonyms = [
  "go to sleep",
  "get to sleep",
  "drowse",
  "fall asleep",
  "doze (off)",
  "have a nap",
  "wake up",
  "relax",
  "let up",
  "slow down",
  "pause",
  "unbend",
  "repose",
  "laze",
  "idle",
  "loaf",
  "do nothing",
  "unwind",
  "recharge one's batteries",
  "take it easy",
  "sit back",
  "sit down",
  "stand down",
  "lounge",
  "luxuriate",
  "loll",
  "slump",
  "flop",
  "put one's feet up",
  "nap",
  "doze",
  "drowse",
  "sleep",
  "slumber",
  "take a rest",
  "ease up/off",
  "have/take a break",
  "take time off",
  "slack off",
  "be at leisure",
  "lie down",
  "go to bed",
  "have/take a nap",
  "have/take a siesta",
];
