export const definitions = [
  '"they have to tolerate each other\'s little foibles"',
];
export const synonyms = [
  "weakness",
  "failing",
  "shortcoming",
  "flaw",
  "imperfection",
  "blemish",
  "fault",
  "defect",
  "frailty",
  "infirmity",
  "inadequacy",
  "limitation",
  "quirk",
  "kink",
  "idiosyncrasy",
  "eccentricity",
  "peculiarity",
  "abnormality",
  "Achilles heel",
  "weak point",
  "weak spot",
  "chink in one's armor",
  "strength",
];
