export const definitions = [
  '"she went back into the house, and Ben followed her"',
  '"he was following behind in his car"',
  '"the KGB man followed her everywhere"',
  '"I follow fame"',
  '"the road follows a hidden sweetwater brook"',
  '"she followed his gaze, peering into the gloom"',
  '"the six years that followed his restoration"',
  '"the rates are as follows"',
  '"raucous laughter followed the ribald remark"',
  '"retribution soon followed"',
  '"the announcement followed on from the collapse of the bank"',
  '"this argument simply doesn\'t follow"',
  '"it thus follows from this equation that the value must be negative"',
  '"he follows his surprise hit movie with a paranoid thriller"',
  '"turkey was followed by dessert"',
  '"he has difficulty in following written instructions"',
  '"the film faithfully follows Shakespeare\'s plot"',
  '"he follows Aristotle in believing this"',
  '"those who seek to follow Jesus Christ"',
  '"I\'ve been following this discussion closely"',
  '"young Italians follow football"',
  '"the book follows the life and career of Henry Clay"',
  '"if you\'ve been following me on Facebook recently you may have seen a bunch of different posts about surgery and back trouble"',
  '"I don\'t follow many celebrities on Twitter anymore"',
  '"I still don\'t follow you"',
  '"she followed a strict diet"',
];
export const synonyms = [
  'come after',
  'go after',
  'accompany',
  'go along with',
  'go around with',
  'escort',
  'attend',
  'come behind',
  'go behind',
  'walk behind',
  'tread on the heels of',
  'travel with',
  'trail around with',
  'lead',
  'shadow',
  'trail',
  'pursue',
  'chase',
  'stalk',
  'hunt',
  'track',
  'dog',
  'hound',
  'course',
  'give chase to',
  'be hot on someone\'s heels',
  'result',
  'arise',
  'develop',
  'ensue',
  'emanate',
  'issue',
  'proceed',
  'spring',
  'flow',
  'originate',
  'stem',
  'come after',
  'be a consequence of',
  'be caused by',
  'be brought about by',
  'be produced by',
  'be a result of',
  'lead to',
  'stick to',
  'keep to',
  'obey',
  'observe',
  'heed',
  'note',
  'mind',
  'accept',
  'respect',
  'act in accordance with',
  'abide by',
  'adhere to',
  'comply with',
  'conform to',
  'pay attention to',
  'have regard to',
  'bear in mind',
  'take to heart',
  'be guided by',
  'yield to',
  'defer to',
  'flout',
  'stick to',
  'keep to',
  'obey',
  'observe',
  'heed',
  'note',
  'mind',
  'accept',
  'respect',
  'act in accordance with',
  'abide by',
  'adhere to',
  'comply with',
  'conform to',
  'pay attention to',
  'have regard to',
  'bear in mind',
  'take to heart',
  'be guided by',
  'yield to',
  'defer to',
  'flout',
  'imitate',
  'copy',
  'mimic',
  'ape',
  'reproduce',
  'mirror',
  'echo',
  'emulate',
  'take as a pattern',
  'take as an example',
  'take as a model',
  'adopt the style of',
  'style oneself on',
  'model oneself on',
  'support',
  'be a fan of',
  'be a supporter of',
  'be a follower of',
  'be an admirer of',
  'be a devotee of',
  'be devoted to',
  'be interested in',
  'cultivate an interest in',
  'dislike',
  'understand',
  'comprehend',
  'apprehend',
  'take in',
  'grasp',
  'fathom',
  'appreciate',
  'see',
  'cognize',
  'keep up with',
  'misunderstand',
  'conduct',
  'undertake',
  'carry on',
  'continue',
  'prosecute',
  'devote oneself to',
  'go on with',
  'proceed with',
  'go ahead with',
  'keep/carry on with',
  'continue with',
  'take further',
  'persist in',
  'stick with/at',
];