export const definitions = ['"they accused him of fomenting political unrest"'];
export const synonyms = [
  "instigate",
  "incite",
  "provoke",
  "agitate",
  "excite",
  "stir up",
  "whip up",
  "arouse",
  "inspire",
  "encourage",
  "urge",
  "actuate",
  "initiate",
  "generate",
  "cause",
  "prompt",
  "start",
  "bring about",
  "kindle",
  "touch off",
  "enkindle",
  "effectuate",
  "spark off",
  "trigger off",
  "fan the flames of",
];
