export const definitions = [
  '"he fooled nightclub managers into believing he was a successful businessman"',
  '"she had been fooling herself in thinking she could remain indifferent"',
];
export const synonyms = [
  "deceive",
  "trick",
  "play a trick on",
  "hoax",
  "dupe",
  "take in",
  "mislead",
  "delude",
  "hoodwink",
  "bluff",
  "beguile",
  "gull",
  "make a fool of",
  "outwit",
  "swindle",
  "defraud",
  "cheat",
  "double-cross",
  "cozen",
  "sharp",
  "mulct",
];
