export const definitions = [
  '"the brutal regime of forced labor"',
  '"a forced smile"',
  '"they broke into Fred\'s house and forced every cupboard door with axe or crowbar"',
  '"she forced her feet into flat leather sandals"',
  '"the plane might have been forced down by fighters"',
  '"Sabine forced a smile"',
  '"she forced her way up the ladder"',
  '"she knew if she forced it she would rip it"',
  '"she was forced into early retirement"',
  '"the universities were forced to cut staff"',
  '"I was forced at second base as the first half of a double play"',
  '"East could force declarer to ruff another spade"',
];
export const synonyms = [
  "enforced",
  "compulsory",
  "obligatory",
  "mandatory",
  "involuntary",
  "exacted",
  "coerced",
  "imposed",
  "demanded",
  "compelled",
  "required",
  "requisite",
  "stipulated",
  "dictated",
  "ordained",
  "prescribed",
  "necessitated",
  "unavoidable",
  "inescapable",
  "de rigueur",
  "voluntary",
  "strained",
  "labored",
  "unnatural",
  "artificial",
  "false",
  "feigned",
  "simulated",
  "contrived",
  "stilted",
  "wooden",
  "stiff",
  "studied",
  "mannered",
  "self-conscious",
  "overdone",
  "overworked",
  "affected",
  "unconvincing",
  "insincere",
  "hollow",
  "natural",
  "kick in",
  "knock down",
  "blast",
  "crack",
  "break open",
  "force open",
  "burst open",
  "prise open",
  "propel",
  "push",
  "thrust",
  "shove",
  "drive",
  "press",
  "pump",
  "expel",
  "extract",
  "elicit",
  "exact",
  "extort",
  "wrest",
  "wring",
  "wrench",
  "drag",
  "screw",
  "squeeze",
  "milk",
  "compel",
  "coerce",
  "make",
  "constrain",
  "oblige",
  "impel",
  "drive",
  "necessitate",
  "pressurize",
  "pressure",
  "press",
  "push",
  "press-gang",
  "browbeat",
  "steamroller",
  "bully",
  "dragoon",
  "bludgeon",
  "terrorize",
  "menace",
  "exert force on",
  "use force on",
  "urge by force",
  "use duress on",
  "bring pressure to bear on",
];
