export const definitions = [
  '"a pine forest"',
  '"much of Europe was covered with forest"',
  '"a forest of connecting wires"',
  '"the northern parts of the province are heavily forested by coniferous trees"',
  '"this area is forested with indigenous trees"',
];
export const synonyms = [
  "wood(s)",
  "woodland",
  "trees",
  "plantation",
  "jungle",
  "greenwood",
  "holt",
  "tree plantation",
  "plantation",
  "farm",
  "holding",
  "vineyard",
  "ranch",
  "hacienda",
  "pen",
  "shamba",
  "tope",
];
