export const definitions = [
  '"they have illegally entered the UK using forged travel documents"',
  '"he forged a great suit of black armor"',
  '"the two women forged a close bond"',
  '"the country is forging a bright new future"',
  '"the signature on the check was forged"',
  '"he forged through the crowded side streets"',
];
export const synonyms = [
  'hammer out',
  'found',
  'cast',
  'mold',
  'model',
  'fashion',
  'form',
  'shape',
  'make',
  'manufacture',
  'produce',
  'turn out',
  'beat into shape',
  'build',
  'build up',
  'construct',
  'form',
  'create',
  'establish',
  'set up',
  'put together',
  'fake',
  'faked',
  'false',
  'counterfeit',
  'imitation',
  'reproduction',
  'replica',
  'copied',
  'sham',
  'bogus',
  'dummy',
  'ersatz',
  'invalid',
  'falsify',
  'copy',
  'imitate',
  'reproduce',
  'replicate',
  'simulate',
  'copy fraudulently',
  'genuine',
  'push on',
  'move along',
  'proceed',
  'progress',
  'advance steadily',
  'advance gradually',
  'press on',
  'soldier on',
  'march on',
  'push forward',
  'move forward',
  'make progress/headway',
];