export const definitions = [
  '"factories that fouled the atmosphere"',
  '"make sure that your pet never fouls the sidewalk"',
  '"Carter fouled into the glove of Boggs"',
  '"the ships became overcrowded and fouled each other"',
  '"will have to work towards solutions to prevent trucks from fouling railroad tracks"',
  '"seaweed or barnacles could clog or foul the propeller"',
  '"watch out for driftwood that might foul up the engine"',
  '"we feared the anchor would foul in the heavy grasses"',
];
export const synonyms = [
  "dirty",
  "soil",
  "stain",
  "blacken",
  "muddy",
  "begrime",
  "splash",
  "spatter",
  "smear",
  "befoul",
  "besmirch",
  "blight",
  "defile",
  "infect",
  "pollute",
  "contaminate",
  "poison",
  "taint",
  "adulterate",
  "sully",
  "besmear",
  "make filthy",
  "entangle",
  "snarl",
  "catch",
  "entwine",
  "enmesh",
  "twist",
  "tangle",
  "tangle up",
  "entangle",
  "snarl",
  "catch",
  "entwine",
  "enmesh",
  "twist",
  "tangle",
  "tangle up",
];
