export const definitions = [
  '"the foyer of the concert hall"',
];
export const synonyms = [
  'entrance hall',
  'hall',
  'hallway',
  'entrance',
  'entry',
  'porch',
  'portico',
  'atrium',
  'concourse',
  'lobby',
  'vestibule',
  'anteroom',
  'antechamber',
  'waiting room',
  'entryway',
  'reception area',
  'outer room',
  'entrance hall',
  'hallway',
  'entry',
  'entrance',
  'lobby',
  'vestibule',
  'atrium',
  'concourse',
  'passageway',
  'passage',
  'corridor',
  'entryway',
  'reception area',
];