export const definitions = [
  '"a ribald comment"',
  '"he was delighted at the ribald laughter that greeted his witticism"',
];
export const synonyms = [
  "bawdy",
  "indecent",
  "risqué",
  "rude",
  "racy",
  "broad",
  "earthy",
  "Rabelaisian",
  "spicy",
  "suggestive",
  "titillating",
  "improper",
  "naughty",
  "indelicate",
  "indecorous",
  "off color",
  "locker-room",
  "vulgar",
  "dirty",
  "filthy",
  "smutty",
  "crude",
  "offensive",
  "salacious",
  "coarse",
  "obscene",
  "lewd",
  "pornographic",
  "X-rated",
];
