export const definitions = [
  '"riding is an exhilarating experience"',
  '"a riding accident"',
  '"I haven\'t ridden much since the accident"',
  '"Diana went to watch him ride his horse"',
  '"we rode on horseback"',
  '"some of the officers were riding back"',
  '"he rode a Harley Davidson across the U.S"',
  '"she rides the bus across 42nd Street"',
  '"they rode on the train several times during the trip"',
  '"ride the full length of the Ridgeway"',
  '"I rode a good race"',
  '"the van rode as well as some cars of twice the price"',
  '"the taxi driver rode Kate to the airport"',
  '"a stream of young surfers fighting the elements to ride the waves"',
  '"the fund rode the growth boom in the 1980s"',
  '"when two lithospheric plates collide, one tends to ride over the other"',
  '"a large cedar barque rode at anchor"',
  '"the moon was riding high in the sky"',
  '"you must not think him ridden with angst"',
  '"the crime-ridden streets"',
  '"Harrison drew back his jaw as if riding the blow"',
  '"if you don\'t give all the kids a chance to play, the parents ride you"',
];
export const synonyms = [
  "sit on",
  "mount",
  "bestride",
  "manage",
  "handle",
  "control",
  "steer",
  "be mounted on",
  "travel",
  "go",
  "move",
  "progress",
  "proceed",
  "make one's way",
  "drive",
  "cycle",
  "trot",
  "canter",
  "gallop",
  "pester",
  "badger",
  "hound",
  "harry",
  "plague",
  "torment",
  "bedevil",
  "persecute",
  "bother",
  "annoy",
  "exasperate",
  "worry",
  "disturb",
  "trouble",
  "agitate",
  "provoke",
  "vex",
  "stress",
  "nag",
  "keep on at",
  "chivvy",
  "tease",
  "bait",
  "molest",
  "stress out",
  "leave in peace",
];
