export const definitions = [
  '"the role of ritual in religion"',
  '"the ancient rituals of Christian worship"',
  '"she likes the High Church ritual"',
  '"her visits to Joy became a ritual"',
  '"ritual burial"',
  '"the players gathered for the ritual pregame huddle"',
];
export const synonyms = [
  "formalities",
  "proceedings",
  "business",
  "rigmarole",
  "ado",
  "ceremony",
  "rite",
  "celebration",
  "festivity",
  "ceremony",
  "rite",
  "ceremonial",
  "observance",
  "service",
  "sacrament",
  "liturgy",
  "worship",
  "office",
  "celebration",
  "performance",
  "act",
  "practice",
  "order",
  "custom",
  "tradition",
  "convention",
  "institution",
  "formality",
  "procedure",
  "protocol",
  "formal",
  "official",
  "state",
  "public",
  "ritualistic",
  "prescribed",
  "set",
  "stately",
  "courtly",
  "solemn",
  "dignified",
  "celebratory",
  "sacramental",
  "liturgical",
  "informal",
  "unofficial",
  "ceremonial",
  "ritualistic",
  "prescribed",
  "set",
  "formal",
  "stately",
  "solemn",
  "dignified",
  "celebratory",
  "sacramental",
  "liturgical",
  "customary",
  "traditional",
  "conventional",
  "routine",
  "usual",
  "habitual",
];
