export const definitions = [
  '"they were imbibing far too many pitchers of beer"',
  '"having imbibed too freely, he fell over"',
  '"she had imbibed the gospel of modernism from Kandinsky"',
];
export const synonyms = [
  "drink",
  "consume",
  "sup",
  "sip",
  "quaff",
  "swallow",
  "down",
  "guzzle",
  "swill",
  "lap",
  "slurp",
  "indulge",
  "tipple",
  "wassail",
  "tope",
  "gulp (down)",
  "drink alcohol",
  "take strong drink",
  "assimilate",
  "absorb",
  "soak up",
  "take in",
  "digest",
  "ingest",
  "drink in",
  "learn",
  "acquire",
  "grasp",
  "gain",
  "pick up",
  "familiarize oneself with",
];
