export const definitions = [
  '"the sap causes swelling that can impede breathing"',
];
export const synonyms = [
  "hinder",
  "obstruct",
  "hamper",
  "handicap",
  "hold back",
  "hold up",
  "delay",
  "disrupt",
  "retard",
  "slow",
  "slow down",
  "brake",
  "restrain",
  "fetter",
  "shackle",
  "hamstring",
  "cramp",
  "cripple",
  "block",
  "check",
  "bar",
  "curb",
  "stop",
  "thwart",
  "frustrate",
  "balk",
  "foil",
  "derail",
  "stand in the way of",
  "cumber",
  "interfere with",
  "put a brake on",
  "facilitate",
];
