export const definitions = ['"he had an impish look about him"'];
export const synonyms = [
  "mischievous",
  "naughty",
  "wicked",
  "devilish",
  "rascally",
  "roguish",
  "prankish",
  "playful",
  "waggish",
  "mischief-making",
  "troublemaking",
  "sportive",
  "elfin",
  "elfish",
  "elvish",
  "pixieish",
  "puckish",
  "arch",
  "full of mischief",
  "elflike",
  "pixie-like",
];
