export const definitions = [
  '"a car dealer"',
  '"a brash young dealer arrived on the dealing floor"',
  '"he posed as a dealer willing to buy heroin"',
];
export const synonyms = [
  'trader',
  'tradesman',
  'tradesperson',
  'merchant',
  'salesman',
  'saleswoman',
  'salesperson',
  'seller',
  'buyer',
  'marketeer',
  'merchandiser',
  'distributor',
  'supplier',
  'vendor',
  'shopkeeper',
  'retailer',
  'wholesaler',
  'purveyor',
  'marketer',
  'trafficker',
  'pedlar',
  'hawker',
  'stockist',
  'storekeeper',
  'chandler',
  'shopman',
  'chapman',
  'buyer and seller',
  'stockbroker',
  'broker-dealer',
  'broker',
  'agent',
  'negotiator',
  'jobber',
];