export const definitions = [
  '"the love episodes debase the dignity of the drama"',
  '"war debases people"',
  '"the King was forced to debase the coinage"',
];
export const synonyms = [
  "degrade",
  "devalue",
  "demean",
  "cheapen",
  "prostitute",
  "discredit",
  "drag down",
  "tarnish",
  "blacken",
  "blemish",
  "disgrace",
  "dishonor",
  "shame",
  "humble",
  "humiliate",
  "damage",
  "harm",
  "undermine",
  "corrupt",
  "corrupted",
  "bastardized",
  "adulterated",
  "diluted",
  "polluted",
  "tainted",
  "sullied",
  "spoiled",
  "spoilt",
  "vitiated",
  "lower the status of",
  "reduce the status of",
  "drag through the mud",
  "bring shame to",
  "enhance",
  "original",
  "pure",
  "immoral",
  "debauched",
  "dissolute",
  "abandoned",
  "perverted",
  "degenerate",
  "profligate",
  "degraded",
  "wicked",
  "sinful",
  "vile",
  "base",
  "iniquitous",
  "corrupt",
  "corrupted",
  "criminal",
  "vicious",
  "brutal",
  "lewd",
  "licentious",
  "lascivious",
  "lecherous",
  "prurient",
  "obscene",
  "indecent",
  "libertine",
  "honorable",
  "contaminate",
  "adulterate",
  "pollute",
  "taint",
  "defile",
  "spoil",
  "foul",
  "sully",
  "depreciate",
  "corrupt",
  "bastardize",
  "dilute",
  "alloy",
  "vitiate",
  "reduce in value",
  "reduce in quality",
];
