export const definitions = [
  '"now he has decamped to Hollywood"',
  '"the armies of both chiefs had decamped"',
];
export const synonyms = [
  'abscond',
  'make off',
  'run off',
  'run away',
  'flee',
  'bolt',
  'take off',
  'take flight',
  'disappear',
  'vanish',
  'slip away',
  'beat a hasty retreat',
  'escape',
  'make a run for it',
  'leave',
  'depart',
  'make oneself scarce',
  'steal away',
  'sneak away',
  'make one\'s getaway',
  'return',
  'break camp',
  'move on',
  'strike one\'s tents',
  'encamp',
];