export const definitions = [
  '"a two-decked ship"',
  '"a decked parking garage"',
  '"the master bedroom leads on to a decked balcony"',
  '"a decked patio"',
  '"Ingrid was decked out in her Sunday best"',
  '"Lisa threatened to deck her if she didn\'t stop filming"',
];
export const synonyms = [
  "decorate",
  "bedeck",
  "adorn",
  "ornament",
  "trim",
  "trick out",
  "garnish",
  "cover",
  "hang",
  "festoon",
  "garland",
  "swathe",
  "wreathe",
  "embellish",
  "beautify",
  "prettify",
  "enhance",
  "grace",
  "set off",
  "bejewel",
  "bedizen",
  "caparison",
  "furbelow",
  "dress up",
  "dress",
  "clothe",
  "attire",
  "array",
  "garb",
  "robe",
  "drape",
  "accoutre",
  "turn out",
  "fit out",
  "rig out",
  "outfit",
  "costume",
  "apparel",
  "invest",
  "habit",
  "trick up",
  "trap out",
  "strike",
  "slap",
  "smack",
  "cuff",
  "punch",
  "beat",
  "thrash",
  "thump",
  "batter",
  "belabor",
  "drub",
  "hook",
  "pound",
  "smash",
  "slam",
  "welt",
  "pummel",
  "hammer",
  "bang",
  "knock",
  "swat",
  "whip",
  "flog",
  "cane",
  "sucker-punch",
  "box someone's ears",
  "smite",
  "swinge",
  "baste",
  "buffet",
  "birch",
  "rain blows on",
  "give someone a (good) beating/drubbing",
];
