export const definitions = [
  '"he claimed that the article defamed his family"',
];
export const synonyms = [
  'libel',
  'slander',
  'malign',
  'smear',
  'traduce',
  'run down',
  'back-bite',
  'calumniate',
  'vilify',
  'besmirch',
  'tarnish',
  'stigmatize',
  'disparage',
  'denigrate',
  'discredit',
  'decry',
  'insult',
  'slur',
  'asperse',
  'derogate',
  'vilipend',
  'cast aspersions on',
  'blacken the name/character of',
  'give someone a bad name',
  'defame someone\'s character',
  'sully some\'s \'s reputation',
  'speak ill/evil of',
  'run a smear campaign against',
  'lie about',
  'tell lies about',
];