export const definitions = [
  '"a woman who defies convention"',
  '"his actions defy belief"',
  '"he glowered at her, defying her to mock him"',
  '"go now, defy him to the combat"',
];
export const synonyms = [
  "go against",
  "flout",
  "disobey",
  "thumb one's nose at",
  "disregard",
  "ignore",
  "set one's face against",
  "kick against",
  "break",
  "violate",
  "contravene",
  "breach",
  "infringe",
  "set at naught",
  "resist",
  "withstand",
  "stand up to",
  "confront",
  "face",
  "take on",
  "beard",
  "brave",
  "outface",
  "refuse to obey",
  "rebel against",
  "take a stand against",
  "hold out against",
  "meet head-on",
  "square up to",
  "obey",
  "surrender",
  "elude",
  "escape",
  "defeat",
  "foil",
  "frustrate",
  "thwart",
  "baffle",
  "challenge",
  "dare",
  "throw down the gauntlet",
];
