export const definitions = [
  '"the land was defiled by a previous owner"',
  '"the tomb had been defiled and looted"',
  '"he took her behind the building and defiled her"',
  '"the twisting track wormed its way up a defile to level ground"',
  '"we emerged after defiling through the mountainsides"',
];
export const synonyms = [
  "spoil",
  "sully",
  "mar",
  "impair",
  "debase",
  "degrade",
  "pollute",
  "poison",
  "corrupt",
  "taint",
  "tarnish",
  "infect",
  "foul",
  "befoul",
  "dirty",
  "soil",
  "stain",
  "destroy",
  "ruin",
  "purify",
  "desecrate",
  "profane",
  "violate",
  "contaminate",
  "pollute",
  "debase",
  "degrade",
  "dishonor",
  "vitiate",
  "treat sacrilegiously",
  "make impure",
  "sanctify",
];
