export const definitions = [
  '"he was physically deformed by a rare bone disease"',
  '"the suspension deforms slightly on corners"',
];
export const synonyms = [
  "disfigure",
  "misshape",
  "contort",
  "buckle",
  "twist",
  "warp",
  "damage",
  "impair",
  "maim",
  "injure",
  "misshapen",
  "distorted",
  "malformed",
  "contorted",
  "out of shape",
  "twisted",
  "crooked",
  "curved",
  "warped",
  "buckled",
  "gnarled",
  "maimed",
  "injured",
  "damaged",
  "humpbacked",
  "hunchbacked",
  "disfigured",
  "ugly",
  "unsightly",
  "grotesque",
  "monstrous",
  "marred",
  "mutilated",
  "mangled",
  "make misshapen",
  "distort the shape of",
  "bend out of shape",
];
