export const definitions = [
  '"explosives specialists tried to defuse the grenade"',
  '"he had the ability to defuse tense moments with humor"',
];
export const synonyms = [
  "deactivate",
  "disarm",
  "disable",
  "make safe",
  "activate",
  "reduce",
  "lessen",
  "diminish",
  "lighten",
  "relieve",
  "ease",
  "alleviate",
  "allay",
  "moderate",
  "mitigate",
  "take the edge off",
  "clear the air",
  "heighten",
  "intensify",
];
