export const definitions = [
  '"nothing dejects a trader like the interruption of his profits"',
];
export const synonyms = [
  "intimidate",
  "abash",
  "shake",
  "ruffle",
  "throw",
  "demoralize",
  "discourage",
  "deter",
  "put off",
  "dishearten",
  "dispirit",
  "sap",
  "cow",
  "overawe",
  "awe",
  "frighten",
  "scare",
  "alarm",
  "unman",
  "dismay",
  "distress",
  "disconcert",
  "discompose",
  "perturb",
  "upset",
  "discomfit",
  "unsettle",
  "unnerve",
  "disquiet",
  "subdue",
  "put someone off their stroke",
  "confound",
  "panic",
  "stupefy",
  "stun",
  "take aback",
  "throw off balance",
  "cause someone to lose their composure",
  "encourage",
  "hearten",
];
