export const definitions = [
  '"the passage was deleted"',
  '"any program in memory will be deleted before the new one is loaded"',
  '"their EMI release has already been deleted"',
  '"if one important gene is deleted from an animal\'s DNA, other genes can stand in "',
  '"you can use delete to remove a number of lines from your program"',
];
export const synonyms = [
  "remove",
  "cut out",
  "take out",
  "expunge",
  "excise",
  "eradicate",
  "cancel",
  "unpublish",
  "strike out",
  "blue-pencil",
  "obliterate",
  "white out",
  "rub out",
  "erase",
  "efface",
  "wipe out",
  "dele",
  "edit out",
  "cross out",
  "put a line through",
  "ink out",
  "score out",
  "scratch out",
  "blot out",
  "Tippex out",
  "add",
  "insert",
];
