export const definitions = [
  '"the country delinked its trade policy from international policy"',
  '"the possibility of delinking from the international economic system"',
];
export const synonyms = [
  "dissociate",
  "divorce",
  "alienate",
  "separate",
  "segregate",
  "isolate",
  "cut off",
  "break away",
  "disaffiliate",
  "defect",
  "leave",
  "quit",
  "break with",
  "become estranged",
  "withdraw from",
  "secede from",
  "part company with",
  "sever connections with",
  "break off relations with",
  "reach a parting of the ways",
  "associate",
  "join",
];
