export const definitions = ['"a deluxe hotel"'];
export const synonyms = [
  "luxurious",
  "luxury",
  "sumptuous",
  "palatial",
  "opulent",
  "splendid",
  "magnificent",
  "lavish",
  "grand",
  "rich",
  "superior",
  "high-class",
  "quality",
  "exclusive",
  "choice",
  "select",
  "elegant",
  "well appointed",
  "fancy",
  "expensive",
  "costly",
  "upmarket",
  "Lucullan",
  "palatian",
  "basic",
  "cheap",
  "downmarket",
];
