export const definitions = [
  '"they deny any responsibility for the tragedy"',
  '"an anti-environmentalist campaign group that denies climate change"',
  '"the inquiry was denied access to intelligence sources"',
  '"there was no way that I was going to deny myself ice cream"',
  '"the servants are ordered to deny him"',
];
export const synonyms = [
  "contradict",
  "repudiate",
  "gainsay",
  "challenge",
  "contest",
  "oppose",
  "retract",
  "take back",
  "backpedal",
  "disprove",
  "debunk",
  "explode",
  "discredit",
  "refute",
  "rebut",
  "invalidate",
  "negate",
  "nullify",
  "quash",
  "disaffirm",
  "controvert",
  "confute",
  "negative",
  "declare untrue",
  "dissent from",
  "disagree with",
  "confirm",
  "refuse",
  "turn down",
  "reject",
  "rebuff",
  "repulse",
  "decline",
  "veto",
  "dismiss",
  "accept",
];
