export const definitions = [
  '"dense volcanic rock"',
  '"swirling, dense smoke"',
  '"an estuary dense with marine life"',
  '"Am I being dense? I don\'t quite understand"',
  '"a dark, dense novel"',
];
export const synonyms = [
  "thick",
  "heavy",
  "opaque",
  "soupy",
  "murky",
  "smoggy",
  "impenetrable",
  "concentrated",
  "condensed",
  "of high density",
  "thin",
  "light",
  "close-packed",
  "thick",
  "packed",
  "crowded",
  "crammed",
  "compressed",
  "compacted",
  "compact",
  "solid",
  "tight",
  "overgrown",
  "jungle-like",
  "jungly",
  "impenetrable",
  "impassable",
  "thickset",
  "closely packed",
  "tightly packed",
  "closely set",
  "jammed together",
  "sparse",
  "stupid",
  "unintelligent",
  "ignorant",
  "brainless",
  "mindless",
  "foolish",
  "slow",
  "slow-witted",
  "dull-witted",
  "witless",
  "doltish",
  "blockish",
  "simpleminded",
  "empty-headed",
  "vacuous",
  "vapid",
  "halfwitted",
  "idiotic",
  "moronic",
  "imbecilic",
  "obtuse",
  "bovine",
  "lumpish",
  "gullible",
  "naive",
  "dunce-like",
  "clever",
  "impervious",
  "impermeable",
  "solid",
  "thick",
  "hard",
  "unyielding",
  "unbreakable",
  "indestructible",
  "resistant",
  "invulnerable",
  "impregnable",
  "inviolable",
  "unassailable",
  "waterproof",
  "closed",
  "sealed",
  "tight",
  "secure",
  "safe",
  "fortress-like",
  "puncture-proof",
  "unpierceable",
  "unattackable",
  "hermetically sealed",
  "permeable",
  "vulnerable",
];
