export const definitions = [
  '"paintings depicting Old Testament scenes"',
  '"these equations may be depicted on a graph"',
  '"youth is depicted as a time of vitality and good health"',
];
export const synonyms = [
  "portray",
  "represent",
  "picture",
  "illustrate",
  "delineate",
  "outline",
  "reproduce",
  "render",
  "draw",
  "paint",
  "sketch",
  "draft",
  "limn",
  "describe",
  "detail",
  "relate",
  "narrate",
  "recount",
  "unfold",
  "present",
  "set forth",
  "set out",
  "outline",
  "delineate",
  "sketch",
  "paint",
  "represent",
  "portray",
  "characterize",
  "record",
  "chronicle",
];
