export const definitions = [
  '"forces were deployed at strategic locations"',
  '"the air force began to deploy forward"',
  '"they are not always able to deploy this skill"',
];
export const synonyms = [
  "position",
  "station",
  "post",
  "place",
  "install",
  "locate",
  "situate",
  "site",
  "establish",
  "base",
  "garrison",
  "distribute",
  "arrange",
  "range",
  "dispose",
  "redistribute",
  "extend",
  "posit",
  "spread out",
  "put into position",
  "concentrate",
  "use",
  "utilize",
  "employ",
  "make use of",
  "take advantage of",
  "exploit",
  "bring into play",
  "call on",
  "turn to",
  "avail oneself of",
  "turn to account",
  "bring into service",
  "bring into action",
  "have recourse to",
  "resort to",
];
