export const definitions = [
  '"shallow water of no more than 12 feet in depth"',
  '"the depth of the wardrobe"',
  '"loosen the soil to a depth of 8 inches"',
  '"texture in a picture gives it depth"',
  '"my voice had not yet acquired husky depth"',
  '"they have so much depth that they could afford the luxury of breaking in their players slowly"',
  '"they failed to understand the depth of the problems"',
  '"a man of compassion and depth of feeling"',
  '"the book has unexpected depth"',
  '"third-year courses typically go into more depth"',
  '"the wine shows good depth of color"',
  '"he lifted the manhole cover and peered into the depths beneath"',
  '"4 a.m. in the depths of winter"',
  '"the putrid depths to which morality has sunk"',
  '"she was in the depths of despair"',
  '"a remote little village somewhere in the depths of Russia"',
];
export const synonyms = [
  'deepness',
  'drop',
  'profundity',
  'distance downward',
  'distance inwards',
  'distance from the outside',
  'vertical drop',
  'vertical extent',
  'shallowness',
  'profoundness',
  'profundity',
  'deepness',
  'wisdom',
  'understanding',
  'intelligence',
  'sagacity',
  'discernment',
  'perceptiveness',
  'penetration',
  'perspicuity',
  'insight',
  'awareness',
  'intuition',
  'astuteness',
  'acumen',
  'shrewdness',
  'acuity',
  'learning',
  'erudition',
  'knowledgeability',
  'sapience',
  'complexity',
  'intricacy',
  'gravity',
  'seriousness',
  'weight',
  'importance',
  'moment',
  'solemnity',
  'shallowness',
  'triviality',
  'extent',
  'range',
  'scope',
  'breadth',
  'width',
  'extensiveness',
  'comprehensiveness',
  'compass',
  'magnitude',
  'scale',
  'degree',
  'intensity',
  'richness',
  'deepness',
  'darkness',
  'vividness',
  'strength',
  'brilliance',
  'bottom',
  'floor',
  'bed',
  'abyss',
  'back',
  'pit',
  'bowels',
  'deepest part',
  'remotest area',
  'surface',
];