export const definitions = [
  '"a train was derailed after it collided with a herd of cattle"',
  '"the trolley cars had a tendency to derail on sharp corners"',
  '"the plot is seen by some as an attempt to derail the negotiations"',
];
export const synonyms = [
  'destroy',
  'put an end to',
  'end',
  'extinguish',
  'dash',
  'quell',
  'quash',
  'ruin',
  'wreck',
  'shatter',
  'smash',
  'crush',
  'scotch',
  'stop',
  'block',
  'frustrate',
  'thwart',
  'put a stop to',
  'prevent',
  'defeat',
  'bring to an end',
  'be the end of',
  'facilitate',
  'obstruct',
  'impede',
  'hinder',
  'hamper',
  'block',
  'interrupt',
  'hold up',
  'hold back',
  'stand in the way of',
  'frustrate',
  'thwart',
  'balk',
  'inhibit',
  'hamstring',
  'sabotage',
  'encumber',
  'restrain',
  'slow',
  'slow down',
  'retard',
  'delay',
  'stonewall',
  'forestall',
  'arrest',
  'check',
  'stop',
  'halt',
  'stay',
  'restrict',
  'limit',
  'curb',
  'bridle',
  'fetter',
  'shackle',
  'trammel',
  'interfere with',
  'put a brake on',
];