export const definitions = [
  '"they derived great comfort from this assurance"',
  '"Eliot derived his poetics from the French Symbolists"',
  '"the word "punch" derives from the Hindustani "pancha""',
  '"the word "man" is derived from the Sanskrit "manu.""',
  '"words whose spelling derives from Dr. Johnson\'s incorrect etymology"',
  '"strong acids are derived from the combustion of fossil fuels"',
  '"the volume fraction of the soil can then be derived as a function of L"',
];
export const synonyms = [
  "obtain",
  "get",
  "take",
  "gain",
  "acquire",
  "procure",
  "extract",
  "attain",
  "glean",
  "found",
  "build",
  "construct",
  "form",
  "establish",
  "ground",
  "root",
  "rest",
  "hinge",
  "use as a basis",
  "emanate from",
  "derive from",
  "spring from",
  "stem from",
  "originate in",
  "have its origin in",
  "can be traced back to",
  "stem",
  "descend",
  "spring",
  "originate in",
  "have its origins in",
  "have as a source",
  "arise in",
  "be taken",
  "be got",
  "give rise to",
  "stem",
  "proceed",
  "flow",
  "pour",
  "spring",
  "emanate",
  "issue",
  "ensue",
  "descend",
  "come",
  "originate in",
  "have its origin in",
  "be rooted in",
  "be traceable to",
];
