export const definitions = [
  '"each pledged to desist from acts of sabotage"',
];
export const synonyms = [
  'abstain',
  'refrain',
  'forbear',
  'hold back',
  'keep',
  'stop',
  'cease',
  'discontinue',
  'suspend',
  'give up',
  'quit',
  'break off',
  'leave off',
  'conclude',
  'forgo',
  'drop',
  'eschew',
  'wash one\'s hands of',
  'belay',
  'call a halt/stop to',
  'dispense with',
  'have done with',
  'continue',
  'persist in',
];