export const definitions = [
  '"we shall consider every detail of the Bill"',
  '"her meticulous attention to detail"',
  '"he didn\'t want them to get sidetracked on a detail of policy"',
  '"a detail on Charlemagne\'s tomb"',
  '"the classical French detail of the building\'s facade"',
  '"detail of right eye showing marks on the lids"',
  '"the official asked for my father\'s details"',
  '"the candidate\'s security detail"',
  '"I didn\'t often get the toilet detail"',
  '"the report details the environmental and health costs of the car"',
  '"the ships were detailed to keep watch"',
  '"the Buick dealer gave him a job washing and detailing cars"',
];
export const synonyms = [
  "particular",
  "feature",
  "characteristic",
  "respect",
  "ingredient",
  "attribute",
  "item",
  "specific",
  "fact",
  "point",
  "factor",
  "element",
  "circumstance",
  "consideration",
  "aspect",
  "facet",
  "side",
  "part",
  "unit",
  "component",
  "constituent",
  "member",
  "accessory",
  "piece of information",
  "outline",
  "overview",
  "nicety",
  "subtlety",
  "triviality",
  "technicality",
  "trifle",
  "incidental",
  "nonessential",
  "inessential",
  "nothing",
  "trivia",
  "minutiae",
  "unimportant point",
  "insignificant item",
  "trivial fact",
  "minor detail",
  "petty detail",
  "mere detail",
  "matter/thing of no importance",
  "matter/thing of no consequence",
  "fine point",
  "salient point",
  "unit",
  "detachment",
  "squad",
  "troop",
  "contingent",
  "outfit",
  "task force",
  "crew",
  "patrol",
  "section",
  "formation",
  "task",
  "job",
  "duty",
  "chore",
  "charge",
  "labor",
  "assignment",
  "function",
  "commission",
  "mission",
  "engagement",
  "occupation",
  "undertaking",
  "exercise",
  "business",
  "office",
  "responsibility",
  "errand",
  "piece of work",
  "piece of business",
  "secondment",
  "present",
  "describe",
  "set out",
  "set forth",
  "draw up",
  "delineate",
  "frame",
  "explain",
  "expound",
  "relate",
  "recount",
  "narrate",
  "recite",
  "rehearse",
  "catalog",
  "list",
  "spell out",
  "point out",
  "itemize",
  "enumerate",
  "tabulate",
  "particularize",
  "identify",
  "specify",
  "define",
  "state",
  "declare",
  "announce",
  "cite",
  "quote",
  "instance",
  "mention",
  "name",
  "designate",
  "individuate",
  "give an account of",
  "be specific about",
  "outline",
  "assign",
  "allocate",
  "appoint",
  "delegate",
  "commission",
  "ordain",
  "charge",
  "send",
  "post",
  "nominate",
  "vote",
  "elect",
  "adopt",
  "co-opt",
  "select",
  "choose",
];
