export const definitions = [
  '"a measuring device"',
  '"an incendiary device"',
  '"a service that attempts to make all of your files available on all your devices whenever you want them"',
  '"simply connect your device to a power outlet as well as Wi-Fi"',
  '"writing a public letter is a traditional device for signaling dissent"',
  '"a rhetorical device"',
  '"the decorative device on the invitations"',
  '"their shields bear the device of the Blazing Sun"',
  '"works of strange device"',
];
export const synonyms = [
  "implement",
  "gadget",
  "utensil",
  "tool",
  "appliance",
  "apparatus",
  "instrument",
  "machine",
  "mechanism",
  "contrivance",
  "contraption",
  "invention",
  "convenience",
  "amenity",
  "aid",
  "piece of equipment",
  "piece of apparatus",
  "piece of hardware",
  "explosive",
  "incendiary",
  "missile",
  "projectile",
  "blockbuster",
  "bombshell",
  "incendiary device",
  "trajectile",
  "ploy",
  "plan",
  "tactic",
  "move",
  "means",
  "stratagem",
  "scheme",
  "plot",
  "trick",
  "ruse",
  "gambit",
  "maneuver",
  "machination",
  "intrigue",
  "contrivance",
  "expedient",
  "dodge",
  "artifice",
  "subterfuge",
  "game",
  "wile",
  "shift",
  "cunning plan",
  "emblem",
  "symbol",
  "logo",
  "badge",
  "stamp",
  "trademark",
  "crest",
  "insignia",
  "coat of arms",
  "escutcheon",
  "seal",
  "mark",
  "figure",
  "design",
  "rune",
  "logotype",
  "logogram",
  "monogram",
  "hallmark",
  "tag",
  "motto",
  "token",
  "motif",
  "colophon",
  "ideogram",
];
