export const definitions = [
  '"I wanted to devote more time to my family"',
  '"she devoted herself to fundraising"',
  '"the hostile army was devoted with dire execrations to the gods of war"',
];
export const synonyms = [
  'allocate',
  'assign',
  'allot',
  'commit',
  'give',
  'give over',
  'afford',
  'apportion',
  'surrender',
  'consign',
  'sacrifice',
  'pledge',
  'dedicate',
  'consecrate',
  'set aside',
  'earmark',
  'reserve',
  'designate',
  'spare',
];