export const definitions = [
  '"he devoured half of his burger in one bite"',
  '"more and more green space has been devoured by new sprawling estates"',
  '"the hungry flames devoured the old house"',
  '"she spent her evenings devouring the classics"',
  '"she was devoured by envy"',
];
export const synonyms = [
  "eat up",
  "swallow",
  "cram down",
  "consume",
  "ingurgitate",
  "eat hungrily",
  "eat quickly",
  "eat greedily",
  "eat heartily",
  "gobble (up/down)",
  "guzzle (down)",
  "gulp (down)",
  "bolt (down)",
  "gorge oneself on",
  "wolf (down)",
  "feast on",
  "destroy",
  "consume",
  "engulf",
  "envelop",
  "demolish",
  "wipe out",
  "annihilate",
  "devastate",
  "raze",
  "gut",
  "ravage",
  "ruin",
  "wreck",
  "lay waste",
  "peruse",
  "study",
  "scrutinize",
  "look through",
  "wade through",
  "scan",
  "flick through",
  "flip through",
  "con",
  "pore over",
  "be absorbed in",
  "bury oneself in",
  "plow through",
  "run one's eye over",
  "cast an eye over",
  "leaf through",
  "glance through",
  "skim through",
  "thumb through",
  "browse through",
  "dip into",
  "afflict",
  "torture",
  "plague",
  "bedevil",
  "trouble",
  "harrow",
  "rack",
  "consume",
  "engulf",
  "swamp",
  "overcome",
  "overwhelm",
  "swallow up",
];
