export const definitions = [
  '"township jive"',
  '"a single image says more than any amount of blather and jive"',
  '"he told me I was talking jive"',
  '"people were jiving in the aisles"',
  '"Willy kept jiving him until Jimmy left"',
  '"he wasn\'t jiving about that bartender"',
  '"her facial expressions did not jive with what she was saying"',
];
export const synonyms = [
  'dance',
  'dance',
  'jig',
  'leap',
  'jump',
  'skip',
  'bounce',
  'step it',
  'scorn',
  'hold in contempt',
  'disdain',
  'mock',
  'ridicule',
  'deride',
  'taunt',
  'insult',
  'slight',
  'affront',
  'slur',
  'scoff at',
  'be contemptuous of',
  'treat with contempt',
  'jeer at',
  'gibe at',
  'make cutting remarks about',
];