export const definitions = [
  '"he was wearing a sports coat that had obviously been tailored in New York"',
  '"arrangements can be tailored to meet individual requirements"',
];
export const synonyms = [
  "outfitter",
  "dressmaker",
  "couturier",
  "clothier",
  "costumer",
  "seamstress",
  "modiste",
  "garment-maker",
  "fashion designer",
  "customize",
  "adapt",
  "adjust",
  "modify",
  "change",
  "convert",
  "alter",
  "attune",
  "fashion",
  "style",
  "mold",
  "gear",
  "fit",
  "cut",
  "trim",
  "suit",
  "shape",
  "reshape",
  "tune",
];
