export const definitions = [
  '"the taking of life"',
  '"box-office takings were scant"',
  '"he was not a very taking person, she felt"',
  '"he leaned forward to take her hand"',
  '"here, take it—I don\'t need it any more"',
  '"twenty of their ships were sunk or taken"',
  '"the French took Ghent"',
  '"West leads a club enabling his partner to take three tricks in the suit"',
  '"Black takes the rook with his bishop"',
  '"someone must have sneaked in here and taken it"',
  '"can I get taken by buying mutual funds?"',
  '"we found that all the seats were taken"',
  '"they decided to take a small house in the country"',
  '"I\'ll take the one on the end"',
  '"he took possession of a unique Picasso ceramic piece"',
  '"take half the marzipan and roll out"',
  '"let\'s take Napoleon, for instance"',
  '"the nurse takes my blood pressure"',
  '"he was taking notes"',
  '"he stopped to take a snap"',
  '"he was taken with a seizure of some kind"',
  '"he took an envelope from his inside pocket"',
  '"the police took him away"',
  '"take two from ten"',
  '"add the numbers together and take away five"',
  '"he took along a portfolio of his drawings"',
  '"the drive takes you through some wonderful scenery"',
  '"I took him a letter"',
  '"I\'ll take you to your room"',
  '"the attack took the country to the brink of war"',
  '"we took the night train to Scotland"',
  '"take 95 north to Baltimore"',
  '"she was advised to take any job offered"',
  '"they don\'t take children"',
  '"I take your point"',
  '"teaching methods will take various forms"',
  '"he took office in September"',
  '"John Martin took the men\'s title"',
  '"he took his chance to get out while the house was quiet"',
  '"the lad took a savage beating"',
  '"I can\'t take the humidity"',
  '"she took the news well"',
  '"everything you say, he takes it the wrong way"',
  '"he takes the corners with no concern for his own safety"',
  '"he somehow took it as a personal insult"',
  '"I fell over what I took to be a heavy branch"',
  '"they refused to take it any more"',
  '"some people found her hard to take"',
  '"take an aspirin and lie down"',
  '"Lucy took a deep breath"',
  '"he took the oath of office"',
  '"some degrees require a student to take a secondary subject"',
  '"she took a degree in English"',
  '"the jury took an hour and a half to find McPherson guilty"',
  '"it takes me about a quarter of an hour to walk to work"',
  '"it will take an electronics expert to dismantle it"',
  '"an exclusive island hideaway that takes just twenty guests"',
  '"he takes size 5 boots"',
  '"Billie was very taken with him"',
  '"the fuchsia cuttings had taken and were looking good"',
  '"these type of grafts take much better than other xenografts"',
  '"verbs that take both the infinitive and the finite clause as their object"',
];
export const synonyms = [
  "proceeds",
  "returns",
  "receipts",
  "earnings",
  "winnings",
  "pickings",
  "spoils",
  "profit",
  "gain",
  "income",
  "revenue",
  "gate money",
  "gate",
  "purse",
  "money received",
  "payments received",
  "delightful",
  "pleasing",
  "pleasant",
  "agreeable",
  "likable",
  "endearing",
  "lovely",
  "lovable",
  "adorable",
  "cute",
  "sweet",
  "appealing",
  "attractive",
  "good-looking",
  "prepossessing",
  "striking",
  "alluring",
  "delectable",
  "ravishing",
  "winning",
  "winsome",
  "fetching",
  "captivating",
  "engaging",
  "enchanting",
  "entrancing",
  "fascinating",
  "bewitching",
  "beguiling",
  "spellbinding",
  "hypnotizing",
  "mesmerizing",
  "seductive",
  "desirable",
  "tempting",
  "inviting",
  "irresistible",
  "beauteous",
  "fair",
  "comely",
  "repulsive",
  "lay hold of",
  "get hold of",
  "grasp",
  "grip",
  "clasp",
  "clutch",
  "grab",
  "take hold of",
  "get into one's hands",
  "give",
  "capture",
  "seize",
  "catch",
  "arrest",
  "apprehend",
  "carry off",
  "abduct",
  "lay hold of",
  "trap",
  "snare",
  "take captive",
  "take into custody",
  "free",
  "liberate",
  "steal",
  "remove",
  "appropriate",
  "misappropriate",
  "make off with",
  "pilfer",
  "purloin",
  "abstract",
  "peculate",
  "dispossess someone of",
  "give",
  "occupy",
  "use",
  "utilize",
  "fill",
  "hold",
  "reserve",
  "engage",
  "sit down",
  "sit",
  "flump",
  "perch",
  "seat oneself",
  "settle (oneself)",
  "install oneself",
  "plant oneself",
  "ensconce oneself",
  "plump oneself down",
  "plop oneself down",
  "rent",
  "lease",
  "hire",
  "charter",
  "reserve",
  "book",
  "engage",
  "make a reservation for",
  "arrange for",
  "consider",
  "ponder",
  "contemplate",
  "think about",
  "weigh up",
  "examine",
  "study",
  "chew over",
  "give thought to",
  "mull over",
  "deliberate over",
  "cogitate about",
  "meditate over",
  "ruminate over",
  "subscribe to",
  "pay a subscription to",
  "buy regularly",
  "read regularly",
  "read every day/week/month",
  "ascertain",
  "determine",
  "establish",
  "measure",
  "find out",
  "discover",
  "calculate",
  "compute",
  "count",
  "quantify",
  "evaluate",
  "rate",
  "assess",
  "appraise",
  "gauge",
  "write",
  "set down",
  "scribble",
  "scrawl",
  "take down",
  "record",
  "register",
  "document",
  "minute",
  "note (down)",
  "make a note of",
  "jot (down)",
  "put in writing",
  "commit to paper",
  "remove",
  "pull",
  "draw",
  "withdraw",
  "extract",
  "fish",
  "confiscate",
  "take possession of",
  "give",
  "subtract",
  "deduct",
  "remove",
  "discount",
  "take away/off",
  "add",
  "bring",
  "carry",
  "bear",
  "transport",
  "convey",
  "move",
  "transfer",
  "shift",
  "haul",
  "drag",
  "lug",
  "cart",
  "ferry",
  "escort",
  "accompany",
  "help",
  "assist",
  "show",
  "lead",
  "lead the way",
  "conduct",
  "guide",
  "see",
  "usher",
  "steer",
  "pilot",
  "shepherd",
  "convey",
  "show someone the way",
  "use",
  "make use of",
  "utilize",
  "travel on",
  "travel by",
  "journey on",
  "go via",
  "accept",
  "take up",
  "take on",
  "undertake",
  "receive",
  "obtain",
  "gain",
  "get",
  "acquire",
  "collect",
  "secure",
  "procure",
  "come by",
  "win",
  "earn",
  "pick up",
  "carry off",
  "be given",
  "be presented with",
  "be awarded",
  "have conferred on one",
  "walk away/off with",
  "refuse",
  "understand",
  "grasp",
  "get",
  "comprehend",
  "apprehend",
  "see",
  "follow",
  "take in",
  "accept",
  "appreciate",
  "recognize",
  "accept/acknowledge/admit the validity of",
  "sympathize with",
  "agree with",
  "derive",
  "draw",
  "acquire",
  "obtain",
  "get",
  "gain",
  "extract",
  "procure",
  "experience",
  "undergo",
  "feel",
  "encounter",
  "know",
  "face",
  "come into contact with",
  "get",
  "secure",
  "obtain",
  "acquire",
  "reserve",
  "commandeer",
  "grab",
  "appropriate",
  "win",
  "achieve",
  "attain",
  "act on",
  "take advantage of",
  "use",
  "exploit",
  "make the most of",
  "jump on",
  "seize (on)",
  "grasp",
  "grab",
  "snatch",
  "accept",
  "capitalize on",
  "leap at",
  "pounce on",
  "put to advantage",
  "profit from",
  "turn to account",
  "cash in on",
  "miss",
  "ignore",
  "receive",
  "meet",
  "greet",
  "respond to",
  "react to",
  "deal with",
  "cope with",
  "regard as",
  "consider to be",
  "view as",
  "look on as",
  "see as",
  "believe to be",
  "think of as",
  "reckon to be",
  "imagine to be",
  "deem to be",
  "hold to be",
  "judge to be",
  "endure",
  "bear",
  "suffer",
  "tolerate",
  "stand",
  "put up with",
  "stomach",
  "brook",
  "abide",
  "carry",
  "accept",
  "permit",
  "allow",
  "admit",
  "countenance",
  "support",
  "shoulder",
  "thole",
  "submit to",
  "drink",
  "imbibe",
  "consume",
  "swallow",
  "eat",
  "ingest",
  "perform",
  "execute",
  "effect",
  "discharge",
  "carry out",
  "accomplish",
  "fulfill",
  "complete",
  "conduct",
  "implement",
  "do",
  "make",
  "have",
  "effectuate",
  "study",
  "learn",
  "grasp",
  "master",
  "take up",
  "pursue",
  "read",
  "be taught",
  "have lessons in",
  "read up on",
  "work at",
  "apply oneself to",
  "acquire a knowledge of",
  "gain an understanding of",
  "last",
  "require",
  "call for",
  "need",
  "necessitate",
  "entail",
  "involve",
  "continue for",
  "go on for",
  "carry on for",
  "keep on for",
  "run on for",
  "endure for",
  "require",
  "need",
  "necessitate",
  "demand",
  "call for",
  "entail",
  "involve",
  "wear",
  "use",
  "require",
  "need",
  "fit",
  "habitually wear",
  "be fitted by",
  "captivate",
  "enchant",
  "charm",
  "delight",
  "attract",
  "fascinate",
  "bewitch",
  "beguile",
  "enthrall",
  "entrance",
  "lure",
  "infatuate",
  "seduce",
  "dazzle",
  "hypnotize",
  "mesmerize",
  "please",
  "amuse",
  "divert",
  "entertain",
  "gladden",
  "satisfy",
  "gratify",
  "win over",
  "take hold",
  "take root",
  "work",
  "operate",
  "succeed",
  "function",
  "be effective",
  "have/take effect",
  "be efficacious",
  "be productive",
  "be in force",
  "be in operation",
  "be efficient",
  "be effectual",
  "be useful",
];
