export const definitions = [
  '"the fish are so tame you have to push them away from your face mask"',
  '"every businessman needs a tame lawyer at his elbow"',
  '"network TV on Saturday night is a pretty tame affair"',
  '"a big field of tame hay"',
];
export const synonyms = [
  'domesticated',
  'domestic',
  'docile',
  'tamed',
  'disciplined',
  'broken',
  'trained',
  'gentle',
  'mild',
  'pet',
  'house-trained',
  'housebroken',
  'not wild',
  'broken-in',
  'not fierce',
  'used to humans',
  'wild',
  'fierce',
  'docile',
  'submissive',
  'compliant',
  'meek',
  'obedient',
  'tractable',
  'acquiescent',
  'amenable',
  'manageable',
  'unresisting',
  'passive',
  'mild',
  'subdued',
  'suppressed',
  'unassertive',
  'ineffectual',
  'biddable',
  'cooperative',
  'available',
  'willing',
  'under someone\'s control / thumb',
  'independent',
  'uncooperative',
  'unexciting',
  'uninteresting',
  'uninspired',
  'uninspiring',
  'dull',
  'bland',
  'flat',
  'insipid',
  'spiritless',
  'pedestrian',
  'vapid',
  'lifeless',
  'dead',
  'colorless',
  'run-of-the-mill',
  'mediocre',
  'ordinary',
  'prosaic',
  'humdrum',
  'boring',
  'tedious',
  'tiresome',
  'wearisome',
  'harmless',
  'safe',
  'unobjectionable',
  'inoffensive',
  'mainstream',
  'exciting',
  'adventurous',
];