export const definitions = [
  '"viewers said they had been offended by bad language"',
  '"he didn\'t smoke and the smell of ash offended him"',
  '"a small hard core of young criminals who offend again and again"',
  '"those activities which offend against public order and decency"',
];
export const synonyms = [
  'affront',
  'upset',
  'displease',
  'distress',
  'hurt',
  'wound',
  'pain',
  'injure',
  'put out',
  'annoy',
  'anger',
  'exasperate',
  'irritate',
  'vex',
  'pique',
  'gall',
  'irk',
  'provoke',
  'nettle',
  'needle',
  'peeve',
  'ruffle',
  'ruffle someone\'s feathers',
  'make some\'s \'s hackles rise',
  'insult',
  'humiliate',
  'embarrass',
  'mortify',
  'scandalize',
  'shock',
  'outrage',
  'spite',
  'hurt someone\'s feelings',
  'give offense to',
  'be an affront to',
  'get/put someone\'s back up',
  'disgruntle',
  'rankle with',
  'tread on someone\'s toes',
  'rub up the wrong way',
  'displease',
  'upset',
  'put off',
  'disgust',
  'repel',
  'revolt',
  'repulse',
  'sicken',
  'nauseate',
  'be displeasing to',
  'be distasteful to',
  'be disagreeable to',
  'be offensive to',
  'cause offense to',
  'be repugnant to',
  'turn someone\'s stomach',
  'make sick',
  'make someone\'s gorge rise',
  'please',
  'delight',
  'do wrong',
  'sin',
  'go astray',
  'fall from grace',
  'err',
  'transgress',
  'trespass',
  'break the law',
  'commit a crime',
];