export const definitions = [
  '"we are talking about real journalists and not the pseudo kind"',
  '"the artsy chat of a campus pseudo"',
  '"pseudonym"',
  '"pseudoscience"',
  '"pseudohallucination"',
  '"pseudo-French"',
];
export const synonyms = [
  "artificial",
  "synthetic",
  "simulated",
  "man-made",
  "manufactured",
  "ersatz",
  "substitute",
  "reproduction",
  "replica",
  "repro",
  "facsimile",
  "model",
  "mock",
  "sham",
  "fake",
  "counterfeit",
  "bogus",
  "spurious",
  "real",
  "genuine",
  "supposedly",
  "seemingly",
  "apparently",
  "allegedly",
  "reportedly",
  "professedly",
  "ostensibly",
  "on the face of it",
  "to all intents and purposes",
  "outwardly",
  "superficially",
  "purportedly",
  "nominally",
  "on paper",
  "ostensively",
  "supposed",
  "seeming",
  "apparent",
  "alleged",
  "reported",
  "ostensible",
  "purported",
  "nominal",
  "so-called",
  "would-be",
  "bogus",
  "sham",
  "phoney",
  "imitation",
  "artificial",
  "mock",
  "ersatz",
  "fake",
  "forged",
  "feigned",
  "pretended",
  "simulated",
  "false",
  "spurious",
  "counterfeit",
  "fraudulent",
  "deceptive",
  "ostensive",
  "to all appearances",
  "on the surface",
  "by one's / its own account",
  "pretendedly",
];
