export const definitions = [
  '"the question of nuclear weapons had been removed from the ______"',
  '"he vowed to put jobs at the top of his ______"',
  '"the government had its own ______"',
  '"Miller has his own ______ and it has nothing to do with football"',
];
export const synonyms = [
  'schedule',
  'program',
  'timetable',
  'lineup',
  'list',
  'listing',
  'to-do list',
  'plan',
  'scheme',
  'syllabus',
  'bill',
  'card',
  'directory',
  'table',
  'menu',
  'list of items',
  'organizer',
  'personal organizer',
  'calendar',
  'schedule',
  'timetable',
  'program',
  'Filofax',
  'appointment book',
  'engagement book',
];
