export const definitions = [
  '"alcoholism is recognized as a major social problem"',
  '"a traditional Japanese social structure"',
  '"a recent analysis of social class in Britain"',
  '"her mother is a lady of the highest social standing"',
  '"we are social beings as well as individuals"',
  '"Guy led a full social life"',
  '"a church social"',
  '"follow all our socials for the latest updates!"',
  '"I try to be honest on my socials and show the good days and bad days"',
  '"I limit the amount I go on socials"',
];
export const synonyms = [
  "communal",
  "community",
  "collective",
  "group",
  "general",
  "popular",
  "civil",
  "civic",
  "public",
  "societal",
  "endemic",
  "pandemic",
  "community-based",
  "individual",
  "recreational",
  "entertainment",
  "amusement",
  "leisure",
  "gregarious",
  "organized",
  "civilized",
  "interactional",
  "party",
  "gathering",
  "function",
  "get-together",
  "celebration",
  "reunion",
  "festivity",
  "jamboree",
  "reception",
  "at-home",
  "soirée",
  "social gathering",
  "social occasion",
  "social event",
  "social function",
];
