export const definitions = [
  '"a solemn procession"',
  '"Tim looked very solemn"',
  '"he swore a solemn oath to keep faith"',
];
export const synonyms = [
  'dignified',
  'ceremonious',
  'ceremonial',
  'stately',
  'courtly',
  'majestic',
  'imposing',
  'impressive',
  'awe-inspiring',
  'portentous',
  'splendid',
  'magnificent',
  'grand',
  'important',
  'august',
  'formal',
  'frivolous',
  'serious',
  'earnest',
  'grave',
  'sober',
  'somber',
  'unsmiling',
  'poker-faced',
  'stern',
  'grim',
  'dour',
  'humorless',
  'glum',
  'gloomy',
  'moody',
  'stony-faced',
  'thoughtful',
  'preoccupied',
  'pensive',
  'meditative',
  'ruminative',
  'contemplative',
  'introspective',
  'staid',
  'sedate',
  'studious',
  'bookish',
  'owlish',
  'deep in thought',
  'lighthearted',
  'sincere',
  'earnest',
  'honest',
  'genuine',
  'firm',
  'committed',
  'unconditional',
  'heartfelt',
  'wholehearted',
  'sworn',
  'formal',
  'insincere',
];