export const definitions = [
  '"the policy could solve the town\'s housing crisis"',
  '"a murder investigation that has never been solved"',
];
export const synonyms = [
  'answer',
  'resolve',
  'work out',
  'fathom',
  'decipher',
  'decode',
  'break',
  'clear up',
  'interpret',
  'translate',
  'get to the bottom of',
  'make head or tail of',
  'unravel',
  'disentangle',
  'untangle',
  'unfold',
  'explain',
  'expound',
  'elucidate',
  'find an/the answer to',
  'find a/the solution to',
  'puzzle out',
  'find the key to',
  'straighten out',
  'piece together',
  'encode',
  'complicate',
  'obfuscate',
];