export const definitions = [
  '"the staircase gives access to the top floor"',
  '"wheelchair access"',
  '"the bypass will greatly improve road access"',
  '"the building has a side access"',
  '"do you have access to a computer"',
  '"awards to help people gain access to training"',
  '"we were denied access to our grandson"',
  '"this prevents unauthorized access or inadvertent deletion of the file"',
  '"public-access television"',
  '"I was suddenly overcome with an access of rage"',
  '"single rooms have private baths accessed via the balcony"',
  '"information can be accessed from several files and displayed at the same time"',
];
export const synonyms = [
  'entrance',
  'entry',
  'ingress',
  'approach',
  'way in',
  'means of entry',
  'means of approach',
  '(the) use of',
  'the opportunity to use',
  'permission to use',
  'admission',
  'admittance',
  'entry',
  'entrée',
  'ingress',
  'right of entry',
  'permission to enter',
  'the opportunity to enter',
  'fit',
  'attack',
  'bout',
  'outpouring',
  'eruption',
  'explosion',
  'outburst',
  'burst',
  'outbreak',
  'flare-up',
  'blowup',
  'blaze',
  'spasm',
  'paroxysm',
  'seizure',
  'rush',
  'gale',
  'flood',
  'storm',
  'hurricane',
  'torrent',
  'surge',
  'upsurge',
  'spurt',
  'effusion',
  'outflow',
  'outflowing',
  'ebullition',
  'boutade',
  'welling up',
  'retrieve',
  'gain',
  'acquire',
  'obtain',
  'read',
  'examine',
  'gain access to',
];
