export const definitions = [
  '"he ______ed a pen as a present"',
  '"he would ______ their offer and see what happened"',
  '"Tim offered Brian a lift home and he ______ed"',
  '"what if Elizabeth ______ed Darcy the first time?"',
  '"the college ______ed her as a student"',
  '"credit cards are widely ______ed"',
  '"the Harvard literati never ______ed him as one of them"',
  '"vending machines that ______ed 100-yen coins for cans of beer"',
  '"this tentative explanation came to be ______ed by the group"',
  '"it is ______ed that aging is a continuous process"',
  '"Jenkins is willing to ______ his responsibility"',
  '"he ______s that he made a mistake"',
  '"they ______ed the need to cut expenses"',
];
export const synonyms = [
  'receive',
  'welcome',
  'take',
  'get',
  'gain',
  'obtain',
  'acquire',
  'come by',
  'take on',
  'take up',
  'undertake',
  'tackle',
  'shoulder',
  'bear',
  'assume',
  'manage',
  'go about',
  'set about',
  'approach',
  'handle',
  'get down to',
  'launch into',
  'enter on',
  'begin',
  'start',
  'turn one\'s hand to',
  'commence',
  'agree to receive',
  'take receipt of',
  'take on oneself',
  'take responsibility for',
  'be responsible for',
  'engage in',
  'become involved in',
  'take part in',
  'participate in',
  'devote oneself to',
  'concentrate on',
  'address oneself to',
  'deal with',
  'get to grips with',
  'embark on',
  'venture on',
  'refuse',
  'reject',
  'turn down',
  'take on',
  'take up',
  'undertake',
  'tackle',
  'shoulder',
  'bear',
  'assume',
  'manage',
  'go about',
  'set about',
  'approach',
  'handle',
  'get down to',
  'launch into',
  'enter on',
  'begin',
  'start',
  'turn one\'s hand to',
  'commence',
  'go along with',
  'endorse',
  'follow',
  'bow to',
  'respect',
  'recognize',
  'acknowledge',
  'adopt',
  'take on oneself',
  'take responsibility for',
  'be responsible for',
  'engage in',
  'become involved in',
  'take part in',
  'participate in',
  'devote oneself to',
  'concentrate on',
  'address oneself to',
  'deal with',
  'get to grips with',
  'embark on',
  'venture on',
  'say yes to',
  'reply in the affirmative',
  'agree to',
  'comply with',
  'accede to',
  'consent to',
  'acquiesce in',
  'concur with',
  'assent to',
  'abide by',
  'adhere to',
  'conform to',
  'act in accordance with',
  'defer to',
  'yield to',
  'surrender to',
  'give in to',
  'submit to',
  'cooperate with',
  'defy',
  'welcome',
  'greet',
  'receive',
  'embrace',
  'adopt',
  'integrate',
  'let in',
  'receive favorably',
  'offer friendship to',
  'recognized',
  'acknowledged',
  'traditional',
  'orthodox',
  'habitual',
  'confirmed',
  'set',
  'fixed',
  'settled',
  'usual',
  'customary',
  'common',
  'normal',
  'general',
  'prevailing',
  'accustomed',
  'familiar',
  'wonted',
  'popular',
  'expected',
  'routine',
  'regular',
  'typical',
  'conventional',
  'established',
  'mainstream',
  'standard',
  'stock',
  'believe',
  'trust',
  'give credence to',
  'credit',
  'count on',
  'give credit to',
  'put confidence in',
  'be convinced of',
  'have faith in',
  'rely on',
  'depend on',
  'acknowledge',
  'admit',
  'concede',
  'grant',
  'allow',
  'own',
  'say',
  'declare',
  'affirm',
  'recognize',
  'realize',
  'be aware of/that',
  'be conscious of/that',
  'tolerate',
  'endure',
  'put up with',
  'suffer',
  'bear',
  'take',
  'stand',
  'support',
  'stomach',
  'undergo',
  'swallow',
  'make the best of',
  'face up to',
  'thole',
  'submit to',
  'become reconciled to',
  'reconcile oneself to',
  'become resigned to',
  'get used to',
  'become accustomed to',
  'adjust to',
  'accommodate oneself to',
  'acclimatize oneself to',
  'learn to live with',
];