export const definitions = [
  '"the powers accorded to the head of state"',
  '"the national assembly accorded the General more power"',
  '"his views accorded well with those of Merivale"',
  '"opposition groups refused to sign the accord"',
  '"a peace accord"',
  '"the government and the rebels are in accord on one point"',
  '"function and form in harmonious accord"',
];
export const synonyms = [
  "give",
  "grant",
  "tender",
  "present",
  "award",
  "hand",
  "vouchsafe",
  "concede",
  "yield",
  "cede",
  "confer on",
  "bestow on",
  "vest in",
  "put in someone's hands",
  "invest with",
  "endow with",
  "entrust with",
  "favor with",
  "withhold",
  "remove",
  "correspond",
  "agree",
  "tally",
  "match up",
  "concur",
  "coincide",
  "equate",
  "harmonize",
  "dovetail",
  "correlate",
  "suit",
  "fit",
  "match",
  "parallel",
  "be in agreement",
  "be consistent",
  "be in harmony",
  "be compatible",
  "be consonant",
  "be congruous",
  "be in tune",
  "conform to",
  "disagree",
  "contrast",
  "pact",
  "treaty",
  "agreement",
  "settlement",
  "deal",
  "entente",
  "concordat",
  "concord",
  "protocol",
  "compact",
  "contract",
  "convention",
  "agreement",
  "consensus",
  "unanimity",
  "harmony",
  "unison",
  "unity",
  "concord",
  "concert",
  "like-mindedness",
  "rapport",
  "conformity",
  "congruence",
  "settlement",
];
