export const definitions = [
  '"financial benefits will accrue from restructuring"',
  '"all customs duties accrued to the federal government"',
];
export const synonyms = [
  "result",
  "arise",
  "follow",
  "ensue",
  "emanate",
  "stem",
  "spring",
  "flow",
  "attend",
  "accompany",
  "be caused by",
  "be brought about by",
  "be produced by",
  "originate in",
  "be consequent on",
  "accumulate",
  "collect",
  "gather",
  "build up",
  "amass",
  "grow",
  "increase",
  "augment",
  "mount up",
  "be added",
];
