export const definitions = [
  '"he was accused of murdering his wife\'s lover"',
  '"he was accused of favoritism"',
];
export const synonyms = [
  "summons",
  "cite",
  "inculpate",
  "charge with",
  "indict for",
  "arraign for",
  "take to court for",
  "put on trial for",
  "bring to trial for",
  "prosecute for",
  "make accusations about",
  "lay charges against",
  "file charges against",
  "prefer charges against",
  "impeach for",
  "absolve",
  "clear",
  "exonerate",
  "blame for",
  "hold responsible for",
  "lay the blame on someone for",
  "hold accountable for",
  "hold answerable for",
  "condemn for",
  "criticize for",
  "denounce for",
  "impute blame to",
  "assign guilt to",
  "attribute liability to",
  "declare guilty",
  "defend",
  "hold blameless",
];
