export const definitions = [
  '"I ran ______ the street"',
  '"she is traveling ______ the US on a promotional tour"',
  '"they lived ______ the street from one another"',
  '"the bridge ______ the river"',
  '"he had swum ______"',
  '"a crater some 30 feet ______"',
  '"he looked ______ at me"',
  '"halfway ______, Jenny jumped"',
  '"19 ______"',
];
export const synonyms = [
  "over",
  "covering",
  "to the other side of",
  "from one side of … to the other",
  "throughout the width/expanse of",
  "everywhere on",
  "on all parts of",
  "beyond",
  "past",
  "on the other side of",
  "from one side of … to the other",
  "throughout the width/expanse of",
  "everywhere on",
  "on all parts of",
  "over",
  "beyond",
  "past",
  "on the other side of",
];
