export const definitions = [
  '"intellectual acuity"',
  '"visual acuity"',
];
export const synonyms = [
  'insight',
  'discernment',
  'perception',
  'perceptiveness',
  'intelligence',
  'sharp-wittedness',
  'quick-wittedness',
  'cleverness',
  'smartness',
  'incisiveness',
  'keenness',
  'sharpness',
  'trenchancy',
  'astuteness',
  'shrewdness',
  'acuteness',
  'subtlety',
  'clarity',
  'discrimination',
  'sensitivity',
  'thoughtfulness',
  'profundity',
  'percipience',
  'perspicacity',
  'perspicuity',
  'sagacity',
  'dullness',
];