export const definitions = ['"business acumen"'];
export const synonyms = [
  "astuteness",
  "awareness",
  "shrewdness",
  "acuity",
  "sharpness",
  "sharp-wittedness",
  "cleverness",
  "brightness",
  "smartness",
  "judgment",
  "understanding",
  "sense",
  "common sense",
  "canniness",
  "discernment",
  "wisdom",
  "wit",
  "sagacity",
  "perspicacity",
  "ingenuity",
  "insight",
  "intuition",
  "intuitiveness",
  "perception",
  "perspicuity",
  "penetration",
  "capability",
  "enterprise",
  "initiative",
  "resourcefulness",
  "flair",
  "vision",
  "brains",
  "savoir faire",
  "sapience",
  "powers of reasoning",
  "arguteness",
  "witlessness",
];
