export const definitions = [
  '"out of love obedience is to be educed"',
  '"more information can be educed from these statistics"',
];
export const synonyms = [
  "call up",
  "summon",
  "invoke",
  "give rise to",
  "bring forth",
  "elicit",
  "induce",
  "kindle",
  "stimulate",
  "stir up",
  "awaken",
  "arouse",
  "excite",
  "raise",
  "suggest",
  "recall",
  "echo",
  "reproduce",
  "encapsulate",
  "capture",
  "express",
  "bring to mind",
  "call to mind",
  "put one in mind of",
  "conjure up",
  "summon up",
  "deduce",
  "infer",
  "conclude",
  "derive",
  "gather",
  "glean",
];
