export const definitions = [];
export const synonyms = [
  "old man",
  "senior citizen",
  "pensioner",
  "grandfather",
  "grandsire",
  "ancient",
  "senex",
  "elderly man",
  "OAP",
  "bodach",
  "boss",
  "manager",
  "manageress",
  "foreman",
  "forewoman",
  "overseer",
  "controller",
  "supervisor",
  "superintendent",
  "ganger",
];
