export const definitions = [
  '"the horse broke into a furious gallop"',
  '"riding at full gallop"',
  '"Will went for a gallop on the beach"',
  '"she ran after them at a gallop"',
  '"West Ham began at the gallop"',
  '"we galloped along the sand"',
  '"Fred galloped the horse off to the start"',
  '"Leota galloped in from the halfway line"',
  '"don\'t gallop through your speech"',
  '"panic about the deadline galloping toward them"',
];
export const synonyms = [
  'race',
  'canter',
  'run',
  'rush',
  'dash',
  'tear',
  'sprint',
  'bolt',
  'fly',
  'shoot',
  'dart',
  'hurry',
  'hasten',
  'speed',
  'streak',
  'hurtle',
  'career',
  'hare',
  'scamper',
  'scurry',
  'scud',
  'lope',
  'prance',
  'frisk',
  'go like lighting',
  'go like the wind',
  'amble',
];