export const definitions = [];
export const synonyms = [
  "gumboot",
  "wellington",
  "wader",
  "field boot",
  "jackboot",
  "thigh boot",
  "half-boot",
  "ankle boot",
  "Chelsea boot",
  "balmoral",
  "desert boot",
  "moon boot",
  "snow boot",
  "overshoe",
  "buskin",
  "napoleon",
  "top boot",
  "walking boot",
  "riding boot",
  "pixie boot",
  "football boot",
  "Doc Martens",
];
