export const definitions = [
  '"his resignation was a tactical gambit"',
];
export const synonyms = [
  'advantage',
  'edge',
  'lead',
  'trump card',
  'beginning',
  'start',
  'commencement',
  'plan',
  'scheme',
  'strategy',
  'stratagem',
  'measure',
  'technique',
  'proposal',
  'step',
  'action',
  'act',
  'maneuver',
  'approach',
  'tack',
  'tactic',
  'démarche',
  'upper hand',
  'whip hand',
  'first step',
  'first move',
  'first blow',
  'opening move',
  'opening gambit',
  'stratagem',
  'machination',
  'scheme',
  'plan',
  'tactic',
  'maneuver',
  'move',
  'course of action',
  'device',
  'operation',
  'ruse',
  'trick',
  'ploy',
  'artifice',
  'line of action',
];