export const definitions = [
  '"the Olympic Games"',
  '"he will attempt to raise his game to another level"',
  '"a baseball game"',
  '"this was a game of shuttle diplomacy at which I had become adept"',
  '"I was on to his little game, but I didn\'t want him to know"',
  '"it was very easy for a few big companies to game the system"',
  '"politicians blamed electricity generators for gaming the market"',
  '"the majority of the audience are teens who game and watch anime"',
  '"other Russians gamed at the tables in Monte Carlo"',
];
export const synonyms = [
  "match",
  "contest",
  "tournament",
  "meeting",
  "meet",
  "event",
  "fixture",
  "tie",
  "test match",
  "final",
  "cup final",
  "playoff",
  "clash",
  "split",
  "tourney",
  "sports meeting",
  "athletic event",
  "cup tie",
  "playdown",
  "business",
  "profession",
  "occupation",
  "trade",
  "industry",
  "field",
  "province",
  "area",
  "line (of work)",
  "line of business",
  "scheme",
  "plot",
  "ploy",
  "stratagem",
  "strategy",
  "gambit",
  "master plan",
  "tactics",
  "trick",
  "artifice",
  "device",
  "maneuver",
  "wile",
  "dodge",
  "ruse",
  "machination",
  "contrivance",
  "subterfuge",
  "shift",
  "cunning plan",
  "grand design",
  "crafty designs",
  "big game",
  "quarry",
  "prey",
  "wild animals",
  "wild fowl",
  "gamble",
  "bet",
  "wager",
  "place bets",
  "lay bets",
  "stake money",
];
