export const definitions = [
  '"the connection was awful and kept garbling his voice"',
  '"most readers assumed the word was a typographical garble"',
  '"upon winning a race a driver spews out a litany of commercial garble"',
];
export const synonyms = [
  'mix up',
  'muddle',
  'jumble',
  'confuse',
  'blur',
  'slur',
  'obscure',
  'distort',
  'twist',
  'warp',
  'misstate',
  'misquote',
  'misreport',
  'misrepresent',
  'mistranslate',
  'misinterpret',
  'misconstrue',
  'change',
  'alter',
  'doctor',
  'falsify',
  'pervert',
  'corrupt',
  'adulterate',
  'twist around',
  'tamper with',
  'tinker with',
  'misarticulate',
  'misrender',
];