export const definitions = [
  '"the police struggled to garner sufficient evidence"',
  '"the crop was ready to be reaped and garnered"',
];
export const synonyms = [
  "gather",
  "collect",
  "accumulate",
  "amass",
  "assemble",
  "store",
  "lay up",
  "lay by",
  "put away",
  "stow away",
  "hoard",
  "stockpile",
  "reserve",
  "save",
  "preserve",
  "store",
  "stow",
  "pack",
  "load",
  "cache",
  "hide",
  "conceal",
  "secrete",
  "hoard",
  "put aside",
  "set aside",
  "put by",
  "lay by",
  "lay aside",
  "save",
  "stockpile",
  "reserve",
  "deposit",
  "keep",
  "keep in reserve",
  "put by for a rainy day",
  "storehouse",
  "silo",
  "store",
  "storeroom",
  "depository",
  "warehouse",
  "vault",
  "storage place",
  "treasure house",
];
