export const definitions = ['"a shy and gauche teenager"'];
export const synonyms = [
  "awkward",
  "gawky",
  "inelegant",
  "graceless",
  "ungraceful",
  "ungainly",
  "bumbling",
  "maladroit",
  "inept",
  "unpolished",
  "unsophisticated",
  "uncultured",
  "uncultivated",
  "unrefined",
  "raw",
  "inexperienced",
  "uneducated",
  "unworldly",
  "socially awkward",
  "socially inept",
  "lacking in social grace(s)",
  "elegant",
  "sophisticated",
];
