export const definitions = [
  '"a fuel gauge"',
  '"mark out the details of the angled surfaces with a knife and gauge"',
  '"emigration is perhaps the best gauge of public unease"',
  '"a fine 0.018-inch gauge wire"',
  '"a 12-gauge shotgun"',
  '"500-gauge polyethylene"',
  '"the line was laid to a gauge of 2 ft. 9 in"',
  '"astronomers can gauge the star\'s intrinsic brightness"',
  '"she was unable to gauge his mood"',
  '"it is difficult to gauge how effective the ban was"',
  '"when dry, the assemblies can be gauged exactly and planed to width"',
];
export const synonyms = [
  "meter",
  "measure",
  "indicator",
  "dial",
  "scale",
  "index",
  "display",
  "measuring instrument",
  "measuring device",
  "measure",
  "indicator",
  "barometer",
  "basis",
  "standard",
  "guide",
  "guideline",
  "touchstone",
  "yardstick",
  "benchmark",
  "criterion",
  "example",
  "model",
  "pattern",
  "formula",
  "exemplar",
  "sample",
  "test",
  "litmus test",
  "point of reference",
  "size",
  "measure",
  "extent",
  "degree",
  "scope",
  "capacity",
  "magnitude",
  "width",
  "breadth",
  "area",
  "thickness",
  "span",
  "depth",
  "height",
  "bore",
  "caliber",
  "diameter",
  "bore",
  "diameter",
  "size",
  "measure",
  "compute",
  "calculate",
  "work out",
  "estimate",
  "determine",
  "reckon",
  "put a figure on",
  "forecast",
  "predict",
  "count up",
  "give a figure to",
  "assess",
  "evaluate",
  "appraise",
  "analyze",
  "weigh up",
  "judge",
  "adjudge",
  "rate",
  "reckon",
  "determine",
  "estimate",
  "guess",
  "get the measure of",
  "form an opinion of",
  "form an impression of",
  "make up one's mind about",
  "measure",
  "calculate",
  "compute",
  "work out",
  "determine",
  "ascertain",
  "count",
  "weigh",
  "quantify",
  "put a figure on",
];
