export const definitions = [
  '"the sudden gaiety of children\'s laughter"',
  '"he seemed to be a part of the gaiety, having a wonderful time"',
  '"people long for the enchantments and gaieties of the European cities"',
];
export const synonyms = [
  'cheerfulness',
  'cheer',
  'light-heartedness',
  'merriment',
  'glee',
  'gladness',
  'happiness',
  'joy',
  'joyfulness',
  'joyousness',
  'delight',
  'pleasure',
  'high spirits',
  'good humor',
  'jollity',
  'jolliness',
  'hilarity',
  'mirth',
  'joviality',
  'exuberance',
  'elation',
  'exultation',
  'euphoria',
  'jubilation',
  'liveliness',
  'vivacity',
  'animation',
  'effervescence',
  'levity',
  'buoyancy',
  'sprightliness',
  'zest',
  'zestfulness',
  'joie de vivre',
  'blitheness',
  'gayness',
  'good spirits',
  'gladsomeness',
  'blithesomeness',
  'misery',
  'merrymaking',
  'festivity',
  'fun',
  'fun and games',
  'frolics',
  'revels',
  'revelry',
  'jollification',
  'celebration',
  'rejoicing',
  'pleasure',
  'sport',
];