export const definitions = [
  '"he could only gaze at her in astonishment"',
  '"he turned, following her gaze"',
  '"offices screened from the public gaze"',
  '"the male gaze"',
];
export const synonyms = [
  "stare",
  "look",
  "gape",
  "goggle",
  "peer",
  "leer",
  "ogle",
  "eye",
  "contemplate",
  "survey",
  "scan",
  "study",
  "behold",
  "look fixedly",
  "look vacantly",
  "take a good look",
  "stare",
  "gape",
  "eye",
  "regard",
  "watch",
  "observance",
  "inspection",
  "scrutiny",
  "fixed look",
  "intent look",
];
