export const definitions = [
  '"the trio are fuming after they were gazumped by a property speculator"',
  '"gazumping has returned, as there is a shortage of good properties"',
  '"I gazumped a friend of mine with complete success last night"',
];
export const synonyms = [
  "defraud",
  "cheat",
  "trick",
  "fleece",
  "dupe",
  "deceive",
  "exploit",
  "squeeze",
  "milk",
  "bleed",
  "fool",
  "take advantage of",
  "mislead",
  "delude",
  "hoax",
  "hoodwink",
  "bamboozle",
  "string along",
  "embezzle",
  "cozen",
  "sharp",
  "mulct",
];
