export const definitions = [
  '"they earn $35 per hour"',
  '"he earns his living as a truck driver"',
  '"this latest win earned them $50,000 in prize money"',
  '"the dollars can be placed on deposit and earn interest"',
  '"through the years she has earned affection and esteem"',
];
export const synonyms = [
  "gross",
  "receive",
  "get",
  "make",
  "obtain",
  "draw",
  "clear",
  "collect",
  "bring in",
  "be paid",
  "receive a salary of",
  "take home",
  "take home earnings of",
  "pay out",
  "net",
  "pocket",
  "gain",
  "make",
  "get",
  "acquire",
  "secure",
  "reap",
  "bring in",
  "pull in",
  "make a profit of",
  "realize a profit of",
  "take home",
  "be paid",
  "spend",
  "deserve",
  "merit",
  "warrant",
  "justify",
  "gain",
  "win",
  "attain",
  "achieve",
  "secure",
  "establish",
  "obtain",
  "procure",
  "get",
  "acquire",
  "find",
  "be entitled to",
  "be worthy of",
  "be deserving of",
  "have a right to",
  "come to have",
  "lose",
];
