export const definitions = [
  '"an easy way of retrieving information"',
  '"promises of an easy life in the New World"',
  '"his easy and agreeable manner"',
  '"they didn\'t feel easy about what they were doing"',
  '"he was vulnerable and an easy target"',
  '"her reputation at school for being easy"',
  '"we all scared real easy in those days"',
];
export const synonyms = [
  "uncomplicated",
  "undemanding",
  "unchallenging",
  "effortless",
  "painless",
  "trouble-free",
  "facile",
  "simple",
  "straightforward",
  "elementary",
  "idiot-proof",
  "plain sailing",
  "easy-breezy",
  "not difficult",
  "unexacting",
  "a snip",
  "difficult",
  "calm",
  "tranquil",
  "serene",
  "quiet",
  "peaceful",
  "trouble-free",
  "untroubled",
  "undisturbed",
  "unworried",
  "contented",
  "relaxed",
  "comfortable",
  "secure",
  "safe",
  "uneasy",
  "natural",
  "casual",
  "informal",
  "unceremonious",
  "unreserved",
  "uninhibited",
  "unconstrained",
  "unforced",
  "unaffected",
  "free and easy",
  "easygoing",
  "familiar",
  "amiable",
  "affable",
  "genial",
  "congenial",
  "agreeable",
  "good-humored",
  "carefree",
  "nonchalant",
  "unconcerned",
  "composed",
  "insouciant",
  "urbane",
  "suave",
  "formal",
  "vulnerable",
  "susceptible",
  "exploitable",
  "defenseless",
  "naive",
  "gullible",
  "trusting",
  "credulous",
  "impressionable",
  "ripe for the picking",
  "streetwise",
];
