export const definitions = ['"a freaky coincidence"'];
export const synonyms = [
  "strange",
  "peculiar",
  "odd",
  "bizarre",
  "queer",
  "curious",
  "funny",
  "eccentric",
  "outlandish",
  "offbeat",
  "off-center",
  "unusual",
  "abnormal",
  "atypical",
  "untypical",
  "anomalous",
  "out of the ordinary",
  "out of the way",
  "extraordinary",
  "irregular",
  "deviant",
  "aberrant",
  "freakish",
  "surreal",
  "eerie",
  "unnatural",
  "perverse",
  "unexpected",
  "surprising",
  "outré",
  "unco",
];
