export const definitions = [
  '"I have no ambitions other than to have a happy life and be free"',
  '"a free choice"',
  '"you are free to leave"',
  '"a free press"',
  '"the poor among the free men joined the slaves against the rich"',
  '"the Free Dutch, Free Polish, and Free Norwegian fleets"',
  '"the researchers set the birds free"',
  '"police were forced to let him walk free"',
  '"she smiled, leaned back, and waved a free arm in the air"',
  '"she lifted the cat free"',
  '"the atmosphere of that time contained virtually no free oxygen"',
  '"she spent her free time shopping"',
  '"the bathroom was free"',
  '"membership is free of charge"',
  '"free healthcare"',
  '"she was always free with her money"',
  '"he was free in his talk of revolution"',
];
export const synonyms = [
  "allowed",
  "permitted",
  "unrestricted",
  "able to",
  "in a position to",
  "capable of",
  "unable",
  "independent",
  "self-governing",
  "self-governed",
  "self-ruling",
  "self-determining",
  "nonaligned",
  "sovereign",
  "autonomous",
  "autarkic",
  "democratic",
  "emancipated",
  "enfranchised",
  "self-sufficient",
  "manumitted",
  "self-legislating",
  "self-directing",
  "dependent",
  "on the loose",
  "at liberty",
  "at large",
  "loose",
  "unconfined",
  "unbound",
  "untied",
  "unchained",
  "untethered",
  "unshackled",
  "unfettered",
  "unrestrained",
  "unsecured",
  "captive",
  "unobstructed",
  "unimpeded",
  "unrestricted",
  "unhampered",
  "unlimited",
  "clear",
  "open",
  "unblocked",
  "unattached",
  "unfastened",
  "unsecured",
  "unhitched",
  "untied",
  "uncoupled",
  "detached",
  "loose",
  "not fixed",
  "obstructed",
  "attached",
  "unoccupied",
  "off duty",
  "off",
  "idle",
  "at leisure",
  "available",
  "contactable",
  "not at work",
  "not working",
  "not busy",
  "not tied up",
  "between appointments",
  "off work",
  "on leave",
  "on annual leave",
  "with time on one's hands",
  "with time to spare",
  "on holiday",
  "occupied",
  "unavailable",
  "vacant",
  "empty",
  "available",
  "spare",
  "unoccupied",
  "untaken",
  "unfilled",
  "unused",
  "uninhabited",
  "tenantless",
  "not in use",
  "occupied",
  "engaged",
  "taken",
  "without",
  "unencumbered by",
  "unaffected by",
  "clear of",
  "devoid of",
  "lacking in",
  "exempt from",
  "not liable to",
  "safe from",
  "immune to",
  "relieved of",
  "released from",
  "excused of",
  "exempted from",
  "rid of",
  "encumbered by",
  "free of charge",
  "for nothing",
  "complimentary",
  "gratis",
  "gratuitous",
  "without charge",
  "at no cost",
  "expensive",
  "paid for",
  "generous",
  "lavish",
  "liberal",
  "openhanded",
  "unstinting",
  "giving",
  "munificent",
  "bountiful",
  "bounteous",
  "charitable",
  "extravagant",
  "prodigal",
  "easygoing",
  "free and easy",
  "tolerant",
  "liberal",
  "permissive",
  "indulgent",
  "relaxed",
  "casual",
  "informal",
  "unceremonious",
  "unforced",
  "natural",
  "open",
  "frank",
  "spontaneous",
  "uninhibited",
  "artless",
  "ingenuous",
  "good-humored",
  "affable",
  "friendly",
  "strained",
  "formal",
  "impudent",
  "impertinent",
  "disrespectful",
  "familiar",
  "overfamiliar",
  "presumptuous",
  "forward",
  "bold",
  "assertive",
  "over-free",
  "polite",
  "flexible",
  "broad",
  "loose",
  "rough",
  "nonrestrictive",
  "general",
  "nonliteral",
  "nonspecific",
  "inexact",
  "imprecise",
  "vague",
  "indefinite",
  "ill-defined",
  "not literal",
  "not strict",
  "not close",
  "unrigorous",
  "unmeticulous",
  "strict",
  "to the letter",
];
