export const definitions = [
  '"in the winter the milk froze"',
  '"the pipes had frozen"',
  '"the ground was frozen hard"',
  '"you\'ll freeze to death standing there"',
  '"at night it froze again"',
  '"she would freeze him with a look when he tried to talk to her"',
  '"the cake can be frozen"',
  '"this soup freezes well"',
  '"Mathewson froze on the spot, unable to take the next step"',
  '"she came out with a revolver and told the boys to freeze"',
  '"new spending on defense was to be frozen"',
  '"the charity\'s bank account has been frozen"',
  '"the camera will set fast shutter speeds to freeze the action"',
  '"workers faced a pay freeze"',
  '"the big freeze surprised the weathermen"',
];
export const synonyms = [
  'ice over',
  'solidify',
  'harden',
  'turn into ice',
  'ice up',
  'glaciate',
  'thaw',
  'melt',
  'shiver',
  'feel very cold',
  'go numb with cold',
  'turn blue with cold',
  'shiver with cold',
  'get chilled',
  'get chilled to the bone/marrow',
  'overheat',
  'deep-freeze',
  'quick-freeze',
  'freeze-dry',
  'ice',
  'chill',
  'cool',
  'refrigerate',
  'preserve',
  'put in the freezer',
  'pack in ice',
  'put on ice',
  'store at a low temperature',
  'thaw',
  'warm up',
  'stop dead',
  'stop',
  'stop in one\'s tracks',
  'stand (stock) still',
  'go rigid',
  'become motionless',
  'become paralyzed',
  'run away',
  'stop dead',
  'stop',
  'stop in one\'s tracks',
  'stand (stock) still',
  'go rigid',
  'become motionless',
  'become paralyzed',
  'run away',
  'fix',
  'suspend',
  'hold',
  'peg',
  'set',
  'limit',
  'restrict',
  'curb',
  'check',
  'cap',
  'confine',
  'control',
  'regulate',
  'hold/keep down',
  'change',
  'fix',
  'suspension',
  'hold',
  'cold snap',
  'freeze-up',
  'frost',
  'spell of cold weather',
  'heatwave',
];