export const definitions = [
  '"Doreen worked herself into a frenzy of rage"',
];
export const synonyms = [
  'hysteria',
  'madness',
  'mania',
  'insanity',
  'derangement',
  'dementedness',
  'delirium',
  'feverishness',
  'fever',
  'wildness',
  'distraction',
  'agitation',
  'turmoil',
  'tumult',
  'euphoria',
  'elation',
  'ecstasy',
  'fit',
  'seizure',
  'paroxysm',
  'spasm',
  'bout',
  'outburst',
  'ferment',
  'storm',
  'wild excitement',
  'deliration',
];