export const definitions = [
  '"she\'s a friend of mine"',
  '"we were close friends"',
  '"my friends, let me introduce myself"',
  '"join the Friends of Guilford Free Library"',
  '"she was unsure whether he was friend or foe"',
  '"he settled for that old friend the compensation grant"',
  '"all of a sudden you\'ve got 50 friends online who need to stay connected"',
  '"I am friended by 29 people who I have not friended back"',
];
export const synonyms = [
  "companion",
  "boon companion",
  "best friend",
  "intimate",
  "confidante",
  "confidant",
  "familiar",
  "soul mate",
  "alter ego",
  "shadow",
  "playmate",
  "playfellow",
  "classmate",
  "schoolmate",
  "workmate",
  "ally",
  "comrade",
  "associate",
  "sister",
  "brother",
  "compeer",
  "fidus Achates",
  "bosom friend",
  "close friend",
  "second self",
  "enemy",
  "patron",
  "backer",
  "supporter",
  "benefactor",
  "benefactress",
  "sponsor",
  "well-wisher",
  "defender",
  "champion",
  "benefactrice",
  "benefactrix",
  "Maecenas",
  "opponent",
];
