export const definitions = [];
export const synonyms = [
  "monk",
  "brother",
  "religious",
  "contemplative",
  "prior",
  "abbot",
  "Dominican",
  "Black Friar",
  "Carmelite",
  "White Friar",
  "Franciscan",
  "Friar Minor",
  "Gray Friar",
  "Minorite",
  "Augustinian",
  "Augustine",
  "Austin Friar",
  "Capuchin",
  "Servite",
  "mendicant",
  "cenobite",
  "male member of a religious order",
  "Crutched Friar",
  "cloisterer",
  "religioner",
  "religieux",
];
