export const definitions = [
  '"the air was frigid, and spectators shivered against the cold"',
  '"frigid water"',
  '"Henrietta looked back with a frigid calm"',
  '"my ex told everyone I was frigid"',
];
export const synonyms = [
  "bitter",
  "freezing",
  "frozen",
  "frosty",
  "icy",
  "icy-cold",
  "ice-cold",
  "chilly",
  "wintry",
  "bleak",
  "subzero",
  "arctic",
  "Siberian",
  "polar",
  "glacial",
  "chill",
  "Hyperborean",
  "hibernal",
  "boreal",
  "gelid",
  "brumal",
  "rimy",
  "very cold",
  "bitterly cold",
  "hiemal",
  "algid",
  "hot",
  "tropical",
  "stiff",
  "formal",
  "stony",
  "steely",
  "flinty",
  "wooden",
  "impersonal",
  "indifferent",
  "unresponsive",
  "unemotional",
  "unfeeling",
  "unsmiling",
  "unenthusiastic",
  "austere",
  "distant",
  "aloof",
  "remote",
  "reserved",
  "unapproachable",
  "frosty",
  "cold",
  "icy",
  "cool",
  "lukewarm",
  "forbidding",
  "unfriendly",
  "unwelcoming",
  "hostile",
  "friendly",
  "unresponsive",
  "undemonstrative",
  "cold",
  "cold-blooded",
  "cold-hearted",
  "passionless",
  "unfeeling",
  "unemotional",
  "unloving",
  "uncaring",
  "sexually unresponsive",
  "unaffectionate",
  "passionate",
];
