export const definitions = [
  '"I jumped up in fright"',
  '"she\'s had a nasty fright"',
  '"I got the fright of my life seeing her in the hotel"',
  '"come, be comforted, he shan\'t fright you"',
];
export const synonyms = [
  "fear",
  "fearfulness",
  "terror",
  "horror",
  "alarm",
  "panic",
  "dread",
  "trepidation",
  "uneasiness",
  "nervousness",
  "apprehension",
  "apprehensiveness",
  "consternation",
  "dismay",
  "perturbation",
  "disquiet",
  "discomposure",
  "scare",
  "shock",
  "surprise",
  "turn",
  "jolt",
  "start",
  "the shivers",
  "the shakes",
  "frighten",
  "panic",
  "terrify",
  "petrify",
  "make someone's hair stand on end",
  "make some's 's blood run cold",
  "chill some's 's blood",
  "startle",
  "alarm",
  "shock",
  "appall",
  "horrify",
  "intimidate",
  "daunt",
  "unnerve",
  "affright",
  "make afraid",
  "make fearful",
  "make nervous",
  "throw into a panic",
  "scare/frighten to death",
  "scare/frighten someone out of their wits",
  "scare stiff",
  "scare witless",
  "scare/frighten the living daylights out of",
  "scare/frighten the life out of",
  "scare the hell out of",
  "strike terror into",
  "fill with fear",
  "put the fear of God into",
  "make someone jump (out of their skin)",
  "give someone goose pimples",
  "send into a cold sweat",
  "make someone shake in their shoes",
  "give someone a fright",
  "give someone a turn",
  "reassure",
];
