export const definitions = [
  '"a page at the front of the book had been torn out"',
  '"he sealed the envelope and wrote on the front"',
  '"she quickly turned her head to face the front"',
  '"she rolled over onto her front"',
  '"oatmeal slopped from the tray onto his shirt front"',
  '"get your eyes off my front, meathead"',
  '"the west front of the Cathedral"',
  '"his regiment was immediately sent to the front"',
  '"the Spartans preserving an even and unbroken front"',
  '"there was some good news on the jobs front"',
  '"the Palestinian Liberation Front"',
  '"she put on a brave front"',
  '"the CIA identified the company as a front for a terrorist group"',
  '"he\'s got a bit of talent and a lot of front"',
  '"the houses that front Beacon Street"',
  '"we sold the uphill land that fronted on the road"',
  '"they reached the hedge fronting the garden"',
  '"a metal box fronted by an alloy panel"',
  '"a glass-fronted bookcase"',
  '"the group is fronted by two girl singers"',
  '"she is set to front a new BBC show"',
  '"he fronted for them in illegal property deals"',
  '"I can\'t front, I never really listened to much of his music"',
  '"parents get a bit worried if you don\'t front up now and then"',
  '"Tom fronted him with unwavering eyes"',
  '"all speakers use raised and fronted variants more in spontaneous speech"',
];
export const synonyms = [
  'forepart',
  'fore',
  'anterior',
  'forefront',
  'nose',
  'head',
  'bow',
  'prow',
  'foreground',
  'foremost part',
  'nearest part',
  'closest part',
  'fore-end',
  'rear',
  'back',
  'forepart',
  'fore',
  'anterior',
  'forefront',
  'nose',
  'head',
  'bow',
  'prow',
  'foreground',
  'foremost part',
  'nearest part',
  'closest part',
  'fore-end',
  'rear',
  'back',
  'frontage',
  'face',
  'facing',
  'facade',
  'window',
  'front line',
  'vanguard',
  'van',
  'first line',
  'firing line',
  'battlefield',
  'battleground',
  'trenches',
  'lists',
  'field of battle',
  'combat zone',
  'party',
  'faction',
  'organization',
  'grouping',
  'wing',
  'lobby',
  'camp',
  'coalition',
  'political group',
  'appearance',
  'look',
  'expression',
  'face',
  'manner',
  'air',
  'countenance',
  'demeanor',
  'bearing',
  'posture',
  'pose',
  'mien',
  'aspect',
  'exterior',
  'veneer',
  'act',
  'pretense',
  'affectation',
  '(outward) show',
  'false display',
  'cover',
  'cover-up',
  'pretext',
  'blind',
  'disguise',
  'facade',
  'mask',
  'cloak',
  'screen',
  'smokescreen',
  'camouflage',
  'false front',
  'self-confidence',
  'boldness',
  'forwardness',
  'audacity',
  'audaciousness',
  'temerity',
  'brazenness',
  'presumption',
  'presumptuousness',
  'rashness',
  'daring',
  'assumption',
  'shyness',
  'overlook',
  'look onto',
  'look out on',
  'look out over',
  'look toward',
  'face (toward)',
  'lie opposite (to)',
  'have a view of',
  'command a view of',
  'back onto',
  'lead',
  'head',
  'be the driving force behind',
  'be in the forefront of',
  'be in the front line of',
  'lead the way in/for',
  'be in the van of',
  'be in the vanguard of',
  'present',
  'introduce',
  'anchor',
  'announce',
  'compère',
  'be the presenter of',
];