export const definitions = [
  '"steaming mugs of frothy coffee"',
  '"lots of frothy interviews"',
];
export const synonyms = [
  "foaming",
  "foamy",
  "bubbling",
  "bubbly",
  "fizzy",
  "sparkling",
  "effervescent",
  "gassy",
  "carbonated",
  "aerated",
  "creamy",
  "yeasty",
  "sudsy",
  "spumy",
  "spumous",
  "flat",
  "still",
  "insubstantial",
  "light",
  "lightweight",
  "superficial",
  "shallow",
  "slight",
  "empty",
  "trivial",
  "trifling",
  "frivolous",
  "petty",
  "paltry",
  "insignificant",
  "worthless",
  "lacking substance",
  "of no account",
  "of no merit",
  "of no value",
  "deep",
];
