export const definitions = [
  '"he frowned as he reread the letter"',
  '"the old Russian rural system frowned on private enterprise"',
  '"she leans back uneasily, her mouth forming a pensive frown"',
  '"a frown of disapproval"',
];
export const synonyms = [
  "scowl",
  "glower",
  "glare",
  "lour",
  "make a face",
  "look sullen",
  "look daggers",
  "give someone black looks",
  "knit/furrow one's brows",
  "smile",
  "dislike",
  "discourage",
  "not take kindly to",
  "take a dim view of",
  "take exception to",
  "discountenance",
  "disapprove of",
  "view with dislike/disfavor",
  "show/indicate disapproval of",
  "look askance at",
  "not think much of",
  "find unacceptable",
  "be against",
  "object to",
  "think wrong",
  "have a low opinion of",
  "smile on",
  "approve of",
  "scowl",
  "glower",
  "glare",
  "dirty look",
  "black look",
  "knitted brows",
  "furrowed brows",
  "smile",
];
