export const definitions = [
  '"seedy-looking doormen in frowzy uniforms"',
  '"a frowzy nightclub"',
];
export const synonyms = [
  "scruffy",
  "unkempt",
  "untidy",
  "sloppy",
  "messy",
  "disheveled",
  "slovenly",
  "slatternly",
  "bedraggled",
  "down at heel",
  "dowdy",
  "ill-dressed",
  "badly dressed",
  "tidy",
  "dingy",
  "gloomy",
  "dull",
  "drab",
  "dark",
  "dim",
  "stuffy",
  "close",
  "musty",
  "stale",
  "stagnant",
  "stifling",
  "suffocating",
  "shabby",
  "seedy",
  "run down",
  "tacky",
  "frowsty",
  "fuggy",
  "badly/poorly lit",
  "unfresh",
];
