export const definitions = [
  '"tropical fruits such as mangoes and papaya"',
  '"eat plenty of fresh fruit and vegetables"',
  '"we give thanks for the fruits of the earth"',
  '"the pupils began to appreciate the fruits of their labors"',
  '"the journal was the first fruit of the creative partnership"',
  '"she couldn\'t bear not to see the fruit of her womb"',
  '"the trees fruit very early"',
];
export const synonyms = [
  "reward",
  "benefit",
  "advantages",
  "product",
  "produce",
  "profit",
  "return",
  "yield",
  "legacy",
  "issue",
  "deserts",
  "outcome",
  "upshot",
  "result",
  "results",
  "consequences",
  "effect",
  "effects",
  "children",
  "progeny",
  "family",
  "youngsters",
  "babies",
  "brood",
  "descendants",
  "heirs",
  "successors",
  "scions",
  "young",
  "litter",
  "fry",
  "issue",
  "seed",
  "sons and daughters",
  "fruit of one's loins",
  "bear fruit",
  "produce fruit",
];
