export const definitions = [
  '"furniture can give off lethal fumes when it ignites"',
  '"sparks flew out and ignited the dry scrub"',
  '"the words ignited new fury in him"',
];
export const synonyms = [
  "catch fire",
  "catch",
  "burst into flames",
  "erupt",
  "explode",
  "burn up",
  "burn",
  "kindle",
  "light",
  "set fire to",
  "fire",
  "inflame",
  "touch off",
  "be set off",
  "flame up",
  "set on fire",
  "set alight",
  "set burning",
  "go out",
  "extinguish",
  "arouse",
  "kindle",
  "trigger",
  "spark",
  "instigate",
  "excite",
  "provoke",
  "foment",
  "agitate",
  "stimulate",
  "stir up",
  "work up",
  "whip up",
  "incite",
  "fuel",
  "animate",
  "dampen",
];
