export const definitions = [
  '"snarky remarks"',
  '"Bobby\'s always a bit snarky before his nap"',
];
export const synonyms = [
  "acerbic",
  "sarcastic",
  "sharp",
  "sardonic",
  "satirical",
  "scathing",
  "cutting",
  "razor-edged",
  "incisive",
  "penetrating",
  "piercing",
  "biting",
  "stinging",
  "searing",
  "keen",
  "caustic",
  "trenchant",
  "mordant",
  "bitter",
  "acrimonious",
  "astringent",
  "harsh",
  "severe",
  "abrasive",
  "wounding",
  "hurtful",
  "unkind",
  "cruel",
  "vitriolic",
  "virulent",
  "venomous",
  "poisonous",
  "waspish",
  "spiteful",
  "vicious",
  "malicious",
  "acerb",
  "mordacious",
  "acidulous",
  "kind",
  "pleasant",
  "complimentary",
];
