export const definitions = [
  '"she snatched a cookie from the plate"',
  '"a victory snatched from the jaws of defeat"',
  '"a mission to snatch Winston Churchill"',
  '"she snatched at the handle"',
  '"we snatched a few hours\' sleep"',
  '"I snatched at the chance"',
  '"a quick snatch of breath"',
  '"brief snatches of sleep"',
  '"picking up snatches of conversation"',
  '"a bag snatch"',
];
export const synonyms = [
  "grab",
  "seize",
  "lay hold of",
  "lay (one's) hands on",
  "get one's hands on",
  "take",
  "pluck",
  "grip",
  "grasp",
  "clutch",
  "seize hold of",
  "grab hold of",
  "take hold of",
  "take a grip of",
  "steal",
  "thieve",
  "rob",
  "take",
  "pilfer",
  "purloin",
  "loot",
  "rifle",
  "carry off",
  "embezzle",
  "misappropriate",
  "crib",
  "hook",
  "abscond with",
  "achieve",
  "secure",
  "obtain",
  "seize",
  "pluck",
  "wrest",
  "scrape",
  "jump at",
  "take advantage of",
  "snap up",
  "seize (on)",
  "grasp",
  "accept eagerly",
  "grab (at)",
  "grasp with both hands",
  "pounce on",
  "swoop down on",
  "buy eagerly/quickly",
  "period",
  "spell",
  "time",
  "fit",
  "bout",
  "interval",
  "duration",
  "season",
  "term",
  "stretch",
  "span",
  "phase",
  "run",
  "fragment",
  "snippet",
  "smattering",
  "bit",
  "scrap",
  "piece",
  "part",
  "extract",
  "excerpt",
  "portion",
  "section",
  "selection",
  "theft",
  "robbery",
  "stealing",
  "thieving",
  "larceny",
  "thievery",
  "robbing",
  "pilfering",
  "pilferage",
  "purloining",
  "shoplifting",
  "burglary",
  "raid",
  "holdup",
  "appropriation",
  "expropriation",
  "misappropriation",
  "embezzlement",
  "dacoity",
  "peculation",
  "defalcation",
];
