export const definitions = [
  '"the storm suddenly abated"',
  '"nothing abated his crusading zeal"',
  '"this action would not have been sufficient to abate the odor nuisance"',
];
export const synonyms = [
  "subside",
  "lessen",
  "ease (off)",
  "let up",
  "decrease",
  "diminish",
  "moderate",
  "decline",
  "fade",
  "dwindle",
  "slacken",
  "recede",
  "tail off",
  "wane",
  "ebb",
  "relent",
  "desist",
  "weaken",
  "come to an end",
  "remit",
  "die down/away/out",
  "drop off/away",
  "cool off",
  "peter out",
  "taper off",
  "become weaker",
  "intensify",
  "lessen",
  "decrease",
  "diminish",
  "subside",
  "moderate",
  "decline",
  "relent",
  "slacken",
  "ease (off)",
  "tail off",
  "ebb",
  "wane",
  "dwindle",
  "fade",
  "weaken",
  "stop",
  "cease",
  "finish",
  "come to an end",
  "terminate",
  "quieten",
  "quiet",
  "die down/off",
  "taper off",
  "drop off/away",
  "peter out",
  "calm (down)",
  "come to a stop",
  "quieten down",
  "quiet down",
  "continue",
  "decrease",
  "lessen",
  "diminish",
  "reduce",
  "lower",
  "moderate",
  "ease",
  "soothe",
  "relieve",
  "dampen",
  "calm",
  "tone down",
  "alleviate",
  "mitigate",
  "mollify",
  "allay",
  "assuage",
  "palliate",
  "temper",
  "appease",
  "attenuate",
  "increase",
];
