export const definitions = [
  '"professional tax preparers abhor a flat tax because it would dry up their business"',
];
export const synonyms = [
  "hate",
  "loathe",
  "despise",
  "abominate",
  "execrate",
  "dislike",
  "disdain",
  "disrelish",
  "regard with disgust",
  "feel disgust for",
  "feel repugnance toward",
  "feel distaste for",
  "shrink from",
  "recoil from",
  "shudder at",
  "be unable to bear",
  "be unable to abide",
  "feel hostility to",
  "feel aversion to",
  "feel animosity to",
  "find intolerable",
  "have an aversion to",
  "love",
  "admire",
];
