export const definitions = [
  '"I said I would abide by their decision"',
  '"if there is one thing I cannot abide it is a lack of discipline"',
  '"he enjoyed socializing and could not abide being alone"',
  '"at least one memory will abide"',
  '"many unskillful Men do abide in our City of London"',
];
export const synonyms = [
  "obey",
  "observe",
  "follow",
  "keep to",
  "hold to",
  "stick to",
  "stand by",
  "uphold",
  "heed",
  "accept",
  "go along with",
  "acknowledge",
  "respect",
  "comply with",
  "conform to",
  "adhere to",
  "act in accordance with",
  "pay attention to",
  "agree to/with",
  "consent to",
  "accede to",
  "acquiesce in",
  "defer to",
  "flout",
  "reject",
  "tolerate",
  "bear",
  "stand",
  "put up with",
  "endure",
  "suffer",
  "accept",
  "live with",
  "brook",
  "support",
  "take",
  "countenance",
  "face",
  "handle",
  "cope with",
  "continue",
  "remain",
  "survive",
  "last",
  "persist",
  "stay",
  "hold on",
  "live on",
  "fade",
  "disappear",
  "reside",
  "live",
  "lodge",
  "stay",
  "sojourn",
  "bide",
  "have one's home",
  "have 's 's residence",
  "be settled",
  "be housed",
  "be domiciled",
];
