export const definitions = [
  '"we usually go ______ for a week in May"',
  '"competition from companies at home and ______"',
  '"millions of seeds are annually scattered ______"',
  '"there is a new buccaneering spirit ______"',
  '"con artists ______ on the streets of the town"',
  '"few people ventured ______ from their warm houses"',
  '"servicemen returning from ______"',
];
export const synonyms = [
  "overseas",
  "out of the country",
  "to/in foreign parts",
  "to/in a foreign country/land",
  "over the sea",
  "beyond the seas",
  "widely",
  "far and wide",
  "everywhere",
  "about",
  "around",
  "forth",
  "publicly",
  "extensively",
  "here, there, and everywhere",
  "in all directions",
  "at large",
  "current",
  "in circulation",
  "circulating",
  "in the air",
  "about",
  "afoot",
  "around",
  "astir",
  "around",
  "here and there",
  "to and fro",
  "back and forth",
  "hither and thither",
  "from place to place",
  "in every direction",
  "in all directions",
];
