export const definitions = [
  '"buildings can be designed to absorb and retain heat"',
  '"steroids are absorbed into the bloodstream"',
  '"she absorbed the information in silence"',
  '"the family firm was absorbed into a larger group"',
  '"arms spending absorbs roughly two percent of the national income"',
  '"deep-pile carpets absorbed all sound of the outside world"',
  '"she sat in an armchair, absorbed in a book"',
  '"the work absorbed him and continued to make him happy"',
];
export const synonyms = [
  'soak up',
  'suck up',
  'mop up',
  'draw up/in',
  'take up/in',
  'blot up',
  'sponge up',
  'sop up',
  'exude',
  'give out',
  'assimilate',
  'digest',
  'ingest',
  'take in',
  'imbibe',
  'drink in',
  'comprehend',
  'grasp',
  'learn',
  'understand',
  'master',
  'familiarize oneself with',
  'incorporate',
  'assimilate',
  'integrate',
  'appropriate',
  'take in',
  'subsume',
  'include',
  'co-opt',
  'swallow up',
  'use (up)',
  'consume',
  'take up',
  'occupy',
  'waste',
  'squander',
  'go through',
  'deplete',
  'drain',
  'exhaust',
  'swallow up',
  'deaden',
  'soften',
  'cushion',
  'reduce',
  'decrease',
  'lessen',
  'soak up',
  'reflect',
  'increase',
  'preoccupy',
  'engross',
  'captivate',
  'occupy',
  'engage',
  'rivet',
  'grip',
  'hold',
  'interest',
  'intrigue',
  'immerse',
  'involve',
  'enthrall',
  'spellbind',
  'fascinate',
  'arrest',
  'monopolize',
  'distract',
  'divert',
  'entertain',
  'amuse',
];