export const definitions = [
  '"admission is by ticket only"',
  '"the winning ticket was bought in Anaheim, California"',
  "\"if you have opened a ticket and it's not yet been resolved, there's no need to open a new one\"",
  '"they closed the ticket without doing anything"',
  '"drugs are seen as the only ticket out of poverty"',
  '"companies that appeared to have a one-way ticket to profitability"',
  '"the officer issued Rhodes a speeding ticket"',
  '"his presence on the Republican ticket"',
  '"they ran on strong anti-corruption tickets"',
  '"a wet spring would be just the ticket for the garden"',
  '"park illegally and you are likely to be ticketed"',
  '"passengers can now get electronically ticketed"',
  '"they were sure that Downing was ticketed for greatness"',
  '"the sports jacket had been ticketed at two hundred dollars"',
];
export const synonyms = [
  "pass",
  "warrant",
  "authorization",
  "license",
  "permit",
  "token",
  "coupon",
  "voucher",
  "carnet",
  "season ticket",
  "rover",
  "chit",
  "slip",
  "card",
  "stub",
  "counterfoil",
  "rain check",
  "laissez-passer",
  "firman",
  "complimentary ticket",
  "notice",
  "notification",
  "warning",
  "certificate",
  "label",
  "tag",
  "sticker",
  "slip",
  "tally",
  "tab",
  "marker",
  "docket",
];
