export const definitions = [
  '"one of the secrets of golf is good timing"',
  '"the introduction of new signal timings"',
  '"the first track race is timed for 11:15"',
  '"the bomb had been timed to go off an hour later"',
  '"Williams timed his pass perfectly from about thirty yards"',
  '"we were timed and given certificates according to our speed"',
  '"he was timed at a Canadian record 7.41 seconds"',
  '"I timed how long it took to empty that tanker"',
];
export const synonyms = [
  "schedule",
  "set",
  "set up",
  "arrange",
  "organize",
  "fix",
  "book",
  "line up",
  "prearrange",
  "timetable",
  "bill",
  "program",
  "plan",
  "slate",
  "fix up",
  "fix a time for",
  "slot in",
  "regulate",
  "adjust",
  "calculate",
  "set",
  "synchronize",
  "measure",
  "meter",
  "count",
  "put a stopwatch on",
];
