export const definitions = [
  '"the clatter of cutlery and tinging of glasses"',
  '"a mass of white blossom tinged with pink"',
  '"toward the sun the sky was tinged crimson"',
  '"this visit will be tinged with sadness"',
];
export const synonyms = [
  "tint",
  "color",
  "dye",
  "stain",
  "shade",
  "suffuse",
  "flush",
  "imbue",
  "wash",
  "overlay",
  "bathe",
  "saturate",
  "steep",
  "impregnate",
  "permeate",
  "penetrate",
  "pervade",
  "run through",
  "influence",
  "affect",
  "touch",
  "flavor",
  "color",
  "suffuse",
  "imbue",
  "modify",
  "magnify",
  "distort",
  "poison",
  "sour",
  "enliven",
  "spice up",
];
