export const definitions = [
  '"cool water tinkled in the stone fountains"',
  '"the maid tinkled a bell"',
  '"tinkling laughter"',
  '"I needed to tinkle"',
  '"the distant tinkle of a cowbell"',
  '"I\'ll give them a tinkle"',
  '"you have to pay to go in for a tinkle"',
];
export const synonyms = [
  "ring",
  "jingle",
  "jangle",
  "chime",
  "peal",
  "ding",
  "ping",
  "clink",
  "chink",
  "splash",
  "purl",
  "babble",
  "burble",
  "plash",
  "tintinnabulate",
  "ring",
  "chime",
  "peal",
  "ding",
  "ping",
  "clink",
  "chink",
  "jingle",
  "jangle",
  "tintinnabulation",
  "splash",
  "purl",
  "babble",
  "burble",
  "plash",
  "telephone call",
  "phone call",
  "call",
];
