export const definitions = [
  '"tinned fruit"',
  '"a pair of tinned copper conductors"',
  '"the copper pans are tinned inside"',
];
export const synonyms = [
  "conserve",
  "bottle",
  "can",
  "pot",
  "chill",
  "freeze",
  "freeze-dry",
  "quick-freeze",
  "dry",
  "desiccate",
  "dehydrate",
  "cure",
  "smoke",
  "kipper",
  "salt",
  "pickle",
  "marinate",
  "souse",
  "corn",
  "jelly",
  "candy",
  "embalm",
  "mummify",
  "consume",
  "use",
];
