export const definitions = ['"a tirade of abuse"'];
export const synonyms = [
  "diatribe",
  "invective",
  "polemic",
  "denunciation",
  "rant",
  "broadside",
  "attack",
  "harangue",
  "reviling",
  "railing",
  "decrying",
  "condemnation",
  "brickbats",
  "flak",
  "criticism",
  "censure",
  "lecture",
  "berating",
  "admonishment",
  "admonition",
  "reprimand",
  "rebuke",
  "reproof",
  "upbraiding",
  "abuse",
  "battering",
  "stricture",
  "tongue-lashing",
  "vilification",
  "castigation",
  "denouncement",
  "vituperation",
  "obloquy",
  "fulmination",
  "philippic",
  "verbal onslaught",
  "reproval",
  "stream of abuse",
];
