export const definitions = [
  '"the boom and slump periods of a trade cycle"',
  '"the cells are shed over a cycle of twenty-eight days"',
  '"the familiar four cycles of intake, combustion, ignition, and exhaust"',
  '"the storks\' breeding cycle"',
  '"AC reverses its direction of flow sixty times a second at 60 cycles"',
  '"the painting is one of a cycle of seven"',
  '"Wagner\'s Ring Cycle"',
  '"for the energetic, cycles may be hired"',
  '"cycle shorts"',
  '"a 112-mile cycle"',
  '"she cycled to work every day"',
  '"economies cycle regularly between boom and slump"',
];
export const synonyms = [
  "round",
  "rotation",
  "revolution",
  "circle",
  "pattern",
  "rhythm",
  "series",
  "sequence",
  "succession",
  "run",
  "set",
  "bicycle",
  "two-wheeler",
  "pedal cycle",
  "travel",
  "go",
  "move",
  "progress",
  "proceed",
  "make one's way",
  "drive",
  "trot",
  "canter",
  "gallop",
];
