export const definitions = [
  '"he wrote cryptic notes in a cipher"',
  '"the information may be given in cipher"',
  '"he came across ciphers written on parchment and concealed in a hollow altar pillar"',
  '"journalists are not mere interchangeable ciphers in the propaganda battle"',
  '"a pair of rock crystal goblets engraved with the cipher of Peter the Great"',
  '"he left two, as yet uncracked, ciphered messages for posthumous decoding"',
];
export const synonyms = [
  'code',
  'cryptograph',
  'cryptogram',
  'secret writing',
  'coded message',
  'code',
  'cryptograph',
  'cryptogram',
  'secret writing',
  'coded message',
  'zero',
  'nought',
  'nil',
  'naught',
  '0',
  'nobody',
  'nonentity',
  'nothing',
  'non-person',
  'unimportant person',
  'person of no account',
  'celebrity',
  'numeral',
  'number',
  'integer',
  'figure',
  'digit',
  'character',
  'symbol',
  'sign',
];