export const definitions = [
  '"a surreal, madcap novel"',
  '"some madcap money-making scheme"',
];
export const synonyms = [
  'zany',
  'eccentric',
  'ridiculous',
  'unconventional',
  'weird',
  'reckless',
  'rash',
  'hotheaded',
  'daredevil',
  'impulsive',
  'wild',
  'daring',
  'adventurous',
  'heedless',
  'thoughtless',
  'incautious',
  'imprudent',
  'indiscreet',
  'ill-advised',
  'hasty',
  'foolhardy',
  'foolish',
  'senseless',
  'impractical',
  'harebrained',
  'eccentric',
  'crank',
  'maniac',
  'lunatic',
  'psychotic',
  'oddity',
  'odd fellow',
  'character',
  'individual',
  'hothead',
  'daredevil',
  'madman/madwoman',
];