export const definitions = [
  '"the maggots attack the roots of the developing cabbages"',
  '"these sections produced a few good roach to maggot"',
];
export const synonyms = [
  'grub',
  'larva',
  'caterpillar',
  'impulse',
  'urge',
  'notion',
  'fancy',
  'whimsy',
  'foible',
  'idea',
  'caprice',
  'conceit',
  'vagary',
  'kink',
  'megrim',
  'crotchet',
  'craze',
  'fad',
  'passion',
  'inclination',
  'bent',
  'freak',
  'humor',
  'whim-wham',
];