export const definitions = [
  '"two knights fought to win the hand of a fair maiden"',
  '"a maiden aunt"',
  '"the top-priced maiden heifer"',
  '"the ship\'s maiden voyage"',
];
export const synonyms = [
  "girl",
  "young lady",
  "miss",
  "lass",
  "lassie",
  "colleen",
  "mademoiselle",
  "signorina",
  "señorita",
  "Fräulein",
  "damsel",
  "demoiselle",
  "nymph",
  "wench",
  "young woman",
  "maid",
  "vestal virgin",
  "celibate",
  "virgo intacta",
  "vestal",
  "unmarried girl",
  "chaste woman",
  "unmarried",
  "unwed",
  "unwedded",
  "single",
  "husbandless",
  "celibate",
  "spinster",
  "spouseless",
  "first",
  "initial",
  "inaugural",
  "introductory",
  "initiatory",
  "proving",
];
