export const definitions = [
  '"taking notes in an unobtrusive manner"',
  '"a dramatic poem in the manner of Goethe"',
  '"an adverb of manner"',
  '"what manner of man is he?"',
  '"his arrogance and pompous manner"',
  '"a shy and diffident manner"',
  '"didn\'t your mother teach you any manners ? "',
  '"Tim apologized for his son\'s bad manners"',
  '"I have no complaints about the performance or road manners"',
];
export const synonyms = [
  "way",
  "fashion",
  "mode",
  "means",
  "method",
  "system",
  "style",
  "approach",
  "technique",
  "procedure",
  "process",
  "methodology",
  "modus operandi",
  "form",
  "routine",
  "practice",
  "kind",
  "sort",
  "variety",
  "class",
  "category",
  "classification",
  "group",
  "set",
  "bracket",
  "genre",
  "genus",
  "species",
  "family",
  "order",
  "breed",
  "race",
  "strain",
  "style",
  "description",
  "designation",
  "condition",
  "quality",
  "nature",
  "design",
  "shape",
  "form",
  "pattern",
  "rank",
  "brand",
  "make",
  "model",
  "line",
  "mark",
  "generation",
  "vintage",
  "stamp",
  "ilk",
  "kidney",
  "cast",
  "grain",
  "mold",
  "stripe",
  "demeanor",
  "air",
  "aspect",
  "attitude",
  "appearance",
  "look",
  "bearing",
  "cast",
  "deportment",
  "behavior",
  "conduct",
  "comportment",
  "mien",
  "etiquette",
  "good form",
  "protocol",
  "politeness",
  "decorum",
  "propriety",
  "gentility",
  "civility",
  "formalities",
  "niceties",
  "breeding",
  "politesse",
  "convenances",
  "rudeness",
  "discourtesy",
  "discourteousness",
  "impoliteness",
  "incivility",
  "unmannerliness",
  "boorishness",
  "uncouthness",
  "vulgarity",
  "customs",
  "habits",
  "ways",
  "practices",
  "conventions",
  "usages",
  "correct behavior",
  "social graces",
  "Ps and Qs",
  "ungentlemanly behavior",
  "unladylike behavior",
  "lack of social grace",
  "lack of refinement",
  "rudeness",
  "bad behavior",
  "behavior",
  "conduct",
  "form",
  "social behavior",
  "way of behaving",
  "social habit",
];
