export const definitions = [
  '"the eastern margin of the Indian Ocean"',
  '"they were forced to live on the margins of society"',
  '"the notations in the margin"',
  '"they won by a convincing 17-point margin"',
  '"there was no margin for error"',
  '"the lighting is considerably brighter than before but is still at the margins of acceptability"',
  '"launching these new products helped increase margins and market share"',
  '"its leaves are margined with yellow"',
  '"these he deals forth as the notable Matters, margined for better Notice"',
  '"new contracts are margined with the winnings of previously held contracts"',
];
export const synonyms = [
  "edge",
  "side",
  "bank",
  "verge",
  "border",
  "perimeter",
  "brink",
  "brim",
  "rim",
  "fringe",
  "boundary",
  "limits",
  "periphery",
  "bound",
  "extremity",
  "marge",
  "bourn",
  "skirt",
  "leeway",
  "latitude",
  "scope",
  "room",
  "space",
  "allowance",
  "extra",
  "surplus",
  "room for maneuver",
  "room to spare",
  "gap",
  "majority",
  "amount",
  "difference",
  "measure/degree of difference",
  "leeway",
  "latitude",
  "scope",
  "room",
  "space",
  "allowance",
  "extra",
  "surplus",
  "room for maneuver",
  "room to spare",
  "gloss",
  "explain",
  "interpret",
  "elucidate",
  "explicate",
  "footnote",
  "marginalize",
  "comment on",
  "add notes/footnotes to",
];
