export const definitions = [
  '"he acceded to his master\'s wishes"',
  '"he was master of the situation"',
  '"the master of the house"',
  '"in many ways dogs reflect the styles of their masters"',
  '"a master cylinder"',
  '"the games master"',
  '"I\'m a master of disguise"',
  '"the work of the great masters is spread around the art galleries of the world"',
  '"a chess master"',
  '"a master\'s degree"',
  '"a Master of Arts"',
  '"I had a master\'s in computer engineering"',
  '"Master James Williams"',
  '"the master tape"',
  '"a heart-warming story from a master storyteller"',
  '"a master bricklayer"',
  '"the apartment\'s master bathroom has a free - standing oval bathtub"',
  '"I never mastered Latin"',
  '"I managed to master my fears"',
  '"all records are now being mastered and manufactured for us in the Netherlands"',
  '"a three-master"',
];
export const synonyms = [
  "lord",
  "overlord",
  "ruler",
  "sovereign",
  "monarch",
  "liege",
  "liege lord",
  "suzerain",
  "overseer",
  "superintendent",
  "director",
  "manager",
  "controller",
  "leader",
  "governor",
  "commander",
  "padrone",
  "captain",
  "head",
  "headman",
  "boss",
  "principal",
  "employer",
  "foreman",
  "lord and master",
  "servant",
  "underling",
  "lord",
  "overlord",
  "ruler",
  "sovereign",
  "monarch",
  "liege",
  "liege lord",
  "suzerain",
  "overseer",
  "superintendent",
  "director",
  "manager",
  "controller",
  "leader",
  "governor",
  "commander",
  "padrone",
  "captain",
  "head",
  "headman",
  "boss",
  "principal",
  "employer",
  "foreman",
  "lord and master",
  "servant",
  "underling",
  "owner",
  "keeper",
  "lord",
  "overlord",
  "ruler",
  "sovereign",
  "monarch",
  "liege",
  "liege lord",
  "suzerain",
  "overseer",
  "superintendent",
  "director",
  "manager",
  "controller",
  "leader",
  "governor",
  "commander",
  "padrone",
  "captain",
  "head",
  "headman",
  "boss",
  "principal",
  "employer",
  "foreman",
  "lord and master",
  "servant",
  "underling",
  "teacher",
  "schoolteacher",
  "schoolmaster",
  "tutor",
  "instructor",
  "pedagogue",
  "preceptor",
  "pupil",
  "captain",
  "skipper",
  "commander",
  "expert",
  "adept",
  "genius",
  "past master",
  "maestro",
  "virtuoso",
  "professional",
  "doyen",
  "authority",
  "pundit",
  "prodigy",
  "grandmaster",
  "champion",
  "star",
  "master hand",
  "amateur",
  "novice",
  "original",
  "archetype",
  "prototype",
  "copy",
  "expert",
  "adept",
  "proficient",
  "skilled",
  "skillful",
  "deft",
  "dexterous",
  "adroit",
  "practiced",
  "experienced",
  "masterly",
  "accomplished",
  "demon",
  "brilliant",
  "compleat",
  "principal",
  "main",
  "chief",
  "leading",
  "prime",
  "predominant",
  "foremost",
  "great",
  "grand",
  "biggest",
  "most important",
  "learn",
  "acquire",
  "pick up",
  "grasp",
  "understand",
  "learn thoroughly",
  "become proficient in",
  "know inside out",
  "know backwards",
  "become expert in",
  "overcome",
  "conquer",
  "beat",
  "quell",
  "quash",
  "suppress",
  "control",
  "repress",
  "restrain",
  "overpower",
  "subdue",
  "vanquish",
  "subjugate",
  "hegemonize",
  "govern",
  "curb",
  "check",
  "bridle",
  "tame",
  "defeat",
  "get the better of",
  "get a grip on",
  "get over",
  "triumph over",
  "prevail over",
  "gain mastery over",
  "give way to",
];
