export const definitions = [
  '"the school takes a maximum of 32 students"',
  '"production levels are near their maximum"',
  '"an offense that carries a maximum of 14 years"',
];
export const synonyms = [
  "limit",
  "utmost",
  "uttermost",
  "greatest",
  "most",
  "extreme",
  "extremity",
  "peak",
  "height",
  "ceiling",
  "top",
  "summit",
  "pinnacle",
  "crest",
  "apex",
  "vertex",
  "apogee",
  "acme",
  "zenith",
  "upper limit",
];
