export const definitions = [
  '"complete mayhem broke out"',
  '"thousands of supporters tried to force their way into the stadium, causing mayhem"',
];
export const synonyms = [
  "chaos",
  "disorder",
  "confusion",
  "havoc",
  "bedlam",
  "pandemonium",
  "tumult",
  "uproar",
  "turmoil",
  "madness",
  "madhouse",
  "hullabaloo",
  "disorganization",
  "maelstrom",
  "trouble",
  "disturbance",
  "commotion",
  "riot",
  "anarchy",
  "destruction",
  "violence",
  "all hell broken loose",
  "wild disarray",
];
