export const definitions = [
  '"a simple solution"',
  '"camcorders are now so simple to operate"',
  '"the simple truth"',
  '"a simple white blouse"',
  '"the house is furnished in a simple country style"',
  '"a quiet, unassuming man with simple tastes"',
  '"the gatherers of simples"',
  '"I don\'t overanalyze.I listen, I like, I buy.Simple!"',
];
export const synonyms = [
  "straightforward",
  "easy",
  "uncomplicated",
  "uninvolved",
  "effortless",
  "painless",
  "manageable",
  "undemanding",
  "elementary",
  "child's play",
  "plain sailing",
  "nothing",
  "clear",
  "plain",
  "intelligible",
  "comprehensible",
  "understandable",
  "lucid",
  "coherent",
  "unambiguous",
  "direct",
  "accessible",
  "unexacting",
  "a five-finger exercise",
  "clearly expressed",
  "(words) of one syllable",
  "difficult",
  "hard",
  "demanding",
  "complicated",
  "complex",
  "basic",
  "fundamental",
  "mere",
  "sheer",
  "pure",
  "pure and simple",
  "candid",
  "frank",
  "honest",
  "direct",
  "sincere",
  "plain",
  "absolute",
  "unqualified",
  "bald",
  "stark",
  "naked",
  "blunt",
  "unadorned",
  "unvarnished",
  "unembellished",
  "plain",
  "unadorned",
  "undecorated",
  "unembellished",
  "unornamented",
  "unpretentious",
  "unostentatious",
  "unfussy",
  "no-nonsense",
  "basic",
  "modest",
  "unsophisticated",
  "honest",
  "homely",
  "homespun",
  "everyday",
  "workaday",
  "stark",
  "severe",
  "spartan",
  "austere",
  "chaste",
  "spare",
  "bare",
  "muted",
  "unpatterned",
  "patternless",
  "classic",
  "understated",
  "uncluttered",
  "clean",
  "restrained",
  "homestyle",
  "without ornament/ornamentation",
  "unelaborate",
  "penny plain",
  "without frills",
  "fancy",
  "elaborate",
  "unpretentious",
  "unsophisticated",
  "ordinary",
  "unaffected",
  "unassuming",
  "natural",
  "honest-to-goodness",
  "modest",
  "homely",
  "wholesome",
  "humble",
  "quiet",
  "lowly",
  "rustic",
  "innocent",
  "artless",
  "guileless",
  "childlike",
  "naive",
  "ingenuous",
  "gullible",
  "inexperienced",
  "cracker-barrel",
  "pretentious",
  "affected",
  "noncomplex",
  "uncombined",
  "unmixed",
  "unalloyed",
  "pure",
  "basic",
  "single",
  "elementary",
  "fundamental",
  "noncompound",
  "uncompounded",
  "unblended",
  "compound",
];
