export const definitions = [
  '"a short, sinewy, sunburnt man"',
  '"the language is spare and sinewy"',
];
export const synonyms = [
  "muscular",
  "muscly",
  "brawny",
  "well built",
  "burly",
  "strapping",
  "sturdy",
  "rugged",
  "strong",
  "powerful",
  "broad-shouldered",
  "athletic",
  "well knit",
  "muscle-bound",
  "Herculean",
  "manly",
  "stalwart",
  "thewy",
  "mesomorphic",
  "well muscled",
  "powerfully built",
  "puny",
  "weedy",
];
