export const definitions = [
  '"a single red rose"',
  '"the kingdom was ruled over by a single family"',
  '"she wrote down every single word"',
  '"it\'s our single most popular beach"',
  '"they didn\'t receive a single reply"',
  '"a single bed"',
  '"a single mother"',
  '"the studio was a single large room"',
  '"a first-class single ticket"',
  '"the individual blooms can be single, semidouble, or fully double"',
  '"a single whiskey"',
  '"a pure and single heart"',
  '"a singles bar"',
  '"one newspaper was singled out for criticism"',
  '"Aaron singled to center"',
  '"they each singled in a run"',
];
export const synonyms = [
  "one",
  "sole",
  "lone",
  "solitary",
  "isolated",
  "unique",
  "exclusive",
  "unaccompanied",
  "by oneself",
  "alone",
  "solo",
  "odd",
  "one only",
  "by itself",
  "double",
  "multiple",
  "individual",
  "separate",
  "distinct",
  "particular",
  "unmarried",
  "unattached",
  "free",
  "available",
  "eligible",
  "unwed",
  "unwedded",
  "wifeless",
  "husbandless",
  "partnerless",
  "on the shelf",
  "sole",
  "young, free, and single",
  "footloose and fancy free",
  "spouseless",
  "a bachelor",
  "a spinster",
  "married",
  "select",
  "pick out",
  "choose",
  "target",
  "earmark",
  "mark out",
  "distinguish",
  "differentiate",
  "put aside",
  "cull",
  "fix on",
  "decide on",
  "separate out",
  "set apart/aside",
];
