export const definitions = [
  '"tributes exacted from the Slavic peoples"',
  '"William\'s advisers exacted an oath of obedience from the clergy"',
  '"he exacts a cruel revenge against the winning candidate"',
];
export const synonyms = [
  "demand",
  "require",
  "command",
  "call for",
  "impose",
  "request",
  "ask for",
  "expect",
  "look for",
  "extract",
  "compel",
  "force",
  "wring",
  "wrest",
  "squeeze",
  "obtain",
  "constrain",
  "insist on",
  "inflict",
  "impose",
  "deliver",
  "administer",
  "issue",
  "apply",
];
