export const definitions = [
  '"production costs have exceeded $60,000"',
  '"the Tribunal\'s decision clearly exceeds its powers under the statute"',
  '"catalog sales have exceeded expectations"',
];
export const synonyms = [
  "run over",
  "go over",
  "overshoot",
  "overreach",
  "pass",
  "top",
  "be more than",
  "be greater than",
  "be over",
  "go beyond",
  "fall short of",
  "surpass",
  "outdo",
  "outstrip",
  "outshine",
  "outclass",
  "transcend",
  "top",
  "cap",
  "beat",
  "better",
  "pass",
  "eclipse",
  "overshadow",
  "extinguish",
  "be greater than",
  "be superior to",
  "be better than",
  "go one better than",
  "put in the shade",
  "put to shame",
  "outrival",
  "outvie",
];
