export const definitions = [
  '"excise taxes on cigarettes"',
  '"the precision with which surgeons can excise brain tumors"',
  '"the clauses were excised from the treaty"',
];
export const synonyms = [
  "duty",
  "tax",
  "levy",
  "tariff",
  "toll",
  "tithe",
  "customs",
  "customs duties",
  "mulct",
  "cut out",
  "cut off",
  "cut away",
  "take out",
  "extract",
  "remove",
  "eradicate",
  "extirpate",
  "resect",
  "snip out",
  "replace",
  "insert",
  "delete",
  "strike out",
  "cancel",
  "blue-pencil",
  "erase",
  "efface",
  "take out",
  "remove",
  "cut out",
  "cut",
  "expunge",
  "eliminate",
  "expurgate",
  "bowdlerize",
  "dele",
  "cross out",
  "cross through",
  "score out",
  "scratch out",
  "put a line through",
  "ink out",
  "edit out",
  "blank out",
  "add",
];
