export const definitions = [
  '""Come on, you guys," exhorted Linda"',
  '"the media have been exhorting people to turn out for the demonstration"',
];
export const synonyms = [
  "urge",
  "encourage",
  "call on",
  "enjoin",
  "adjure",
  "charge",
  "press",
  "pressure",
  "pressurize",
  "lean on",
  "push",
  "spur",
  "incite",
  "goad",
  "bid",
  "entreat",
  "implore",
  "beseech",
  "advise",
  "counsel",
  "admonish",
  "warn",
  "try to persuade",
  "put pressure on",
  "use pressure on",
  "egg on",
  "appeal to",
  "discourage",
];
