export const definitions = [
  '"supporters of the exiled king"',
  '"a corrupt dictator who had been exiled from his country"',
  '"he was exiled to Tasmania in 1849"',
];
export const synonyms = [
  "expel",
  "banish",
  "expatriate",
  "deport",
  "ban",
  "bar",
  "drive out",
  "throw out",
  "cast out",
  "eject",
  "oust",
  "outlaw",
  "uproot",
  "separate",
  "extradite",
  "excommunicate",
  "transport",
  "displace",
  "ostracize",
];
