export const definitions = [
  '"there existed no organization to cope with espionage"',
  '"remains of these baths still exist on the south side of the Pantheon"',
  '"two conflicting stereotypes of housework exist in popular thinking today"',
  '"only a minority of people exist on unemployment benefits alone"',
  '"how am I going to exist without you?"',
];
export const synonyms = [
  "live",
  "breathe",
  "draw breath",
  "be",
  "be alive",
  "be living",
  "have life",
  "have being",
  "have existence",
  "be extant",
  "prevail",
  "occur",
  "remain",
  "obtain",
  "continue",
  "last",
  "endure",
  "be the case",
  "be found",
  "be met with",
  "be in existence",
  "survive",
  "subsist",
  "live",
  "manage",
  "make do",
  "keep going",
  "keep one's head above water",
  "make ends meet",
  "stay alive",
  "support oneself",
  "eke out a living",
  "eke out an existence",
  "struggle along",
  "scrape by",
];
