export const definitions = [
  '"the old contract had expired"',
  '"the three-year period has expired"',
  '"the lady had expired bearing her lord a son"',
  '"the volume of expired air"',
];
export const synonyms = [
  "run out",
  "lapse",
  "cease",
  "end",
  "finish",
  "stop",
  "come to an end",
  "conclude",
  "terminate",
  "become invalid",
  "become void",
  "be no longer valid",
  "become obsolete",
  "be over",
  "be at an end",
  "begin",
  "die",
  "decease",
  "perish",
  "depart this life",
  "breathe one's last",
  "meet one's Maker",
  "give up the ghost",
  "shuffle off this mortal coil",
  "pass away/on",
  "be no more",
  "draw one's last breath",
  "meet one's end",
  "meet one's death",
  "go to the great beyond",
  "cross the great divide",
  "go the way of the/all flesh",
  "go to one's last resting place",
  "exhale",
  "blow out",
  "expel",
  "emit",
  "breathe out",
  "puff out",
  "inhale",
  "inspire",
];
