export const definitions = [
  '"a hubbub of laughter and shouting"',
  '"she fought through the hubbub"',
];
export const synonyms = [
  'noise',
  'din',
  'racket',
  'commotion',
  'clamor',
  'ruckus',
  'cacophony',
  'babel',
  'vociferation',
  'loud noise',
  'confusion',
  'chaos',
  'pandemonium',
  'bedlam',
  'mayhem',
  'uproar',
  'disorder',
  'turmoil',
  'tumult',
  'fracas',
  'hurly-burly',
  'havoc',
  'brouhaha',
  'stramash',
  'bangarang',
  'calm',
];