export const definitions = [
  '"they huddled together for warmth"',
  '"the watchman remained, huddled under his canvas shelter"',
  '"selection committee members huddled with attorneys"',
  '"a man with his clothes all huddled on anyhow"',
  '"a huddle of barns and outbuildings"',
  '"they stood together in a huddle, whispering to each other"',
  '"he controls the huddle and the team better than anybody else"',
  '"the service was performed with more harmony and less huddle than I have known it"',
];
export const synonyms = [
  "crowd",
  "gather",
  "throng",
  "flock",
  "herd",
  "pile",
  "bunch",
  "cluster",
  "collect",
  "group",
  "congregate",
  "press",
  "pack",
  "squeeze",
  "cram",
  "jam",
  "foregather",
  "disperse",
  "snuggle",
  "cuddle",
  "nestle",
  "curl up",
  "hunch up",
  "snug down",
  "stretch out",
  "crowd",
  "gathering",
  "throng",
  "flock",
  "herd",
  "swarm",
  "press",
  "pack",
  "cluster",
  "bunch",
  "knot",
  "band",
  "collection",
  "circle",
  "assemblage",
  "group",
  "number",
  "mass",
  "selection",
  "array",
  "jumble",
  "confusion",
  "muddle",
  "heap",
  "tangle",
  "mess",
  "small group",
  "consultation",
  "discussion",
  "debate",
  "talk",
  "parley",
  "meeting",
  "conference",
  "confabulation",
];
