export const definitions = ['"a hugely expensive house"'];
export const synonyms = [
  "very",
  "most",
  "really",
  "thoroughly",
  "extremely",
  "exceedingly",
  "particularly",
  "tremendously",
  "highly",
  "greatly",
  "decidedly",
  "distinctly",
  "exceptionally",
  "immensely",
  "eminently",
  "supremely",
  "inordinately",
  "singularly",
  "extraordinarily",
  "vastly",
  "overly",
  "to a great extent",
  "unco",
  "très",
  "right",
  "exceeding",
  "sore",
  "very much",
  "slightly",
];
