export const definitions = [
  '"a breed of humped cattle"',
  '"a humped bridge"',
  '"he continued to hump cases up and down the hotel corridor"',
  '"it was late morning by the time I finally humped into camp"',
  '"the cat humped himself into a different shape and purred"',
];
export const synonyms = [
  "arched",
  "bent",
  "bowed",
  "curved",
  "recurved",
  "rounded",
  "hunched",
  "humpbacked",
  "hunchbacked",
  "kyphotic",
  "embowed",
  "crookbacked",
  "curviform",
  "straight",
  "carry",
  "lug",
  "heave",
  "lift",
  "shoulder",
  "hoist",
  "heft",
  "tote",
  "upheave",
  "arch",
  "curve",
  "hunch",
  "bend",
  "bow",
  "curl",
  "crook",
  "straighten",
];
