export const definitions = [
  '"she was faint with hunger"',
  '"they died from cold and hunger"',
  '"her hunger for knowledge"',
  '"all actors hunger for such a role"',
  '"when he had fasted forty days and forty nights, he afterwards hungered"',
];
export const synonyms = [
  "hungriness",
  "ravenousness",
  "emptiness",
  "starvation",
  "famine",
  "malnutrition",
  "malnourishment",
  "undernourishment",
  "inanition",
  "lack of food",
  "need for food",
  "famishment",
  "desire",
  "craving",
  "longing",
  "yearning",
  "pining",
  "hankering",
  "thirst",
  "appetite",
  "lust",
  "ache",
  "want",
  "need",
  "appetence",
  "appetency",
  "aversion",
  "desire",
  "crave",
  "want",
  "need",
  "have a craving for",
  "long for",
  "yearn for",
  "have a yearning for",
  "pine for",
  "ache for",
  "thirst for",
  "have an appetite for",
  "hanker after",
  "lust after",
  "be athirst for",
  "be desirous of",
  "have an aversion to",
];
