export const definitions = [
  '"she chose to wear a blue jacket with white stripes"',
  '"he put his hand in his jacket pocket"',
  '"potatoes cooked in their jackets"',
];
export const synonyms = [
  'wrapping',
  'wrapper',
  'wrap',
  'sleeve',
  'sheath',
  'sheathing',
  'envelope',
  'cover',
  'covering',
  'casing',
  'case',
  'shell',
  'housing',
  'encasement',
  'capsule',
  'integument',
  'file',
  'binder',
  'ring binder',
  'portfolio',
  'document case',
  'envelope',
  'sleeve',
  'wrapper',
  'wallet',
];