export const definitions = [
  '"four of us were jammed in one compartment"',
  '"people jammed their belongings into cars"',
  '"75,000 refugees jammed into a stadium today to denounce the accord"',
  '"he jammed his hat on"',
  '"the roads were jammed with traffic"',
  '"listeners jammed WBOQ\'s switchboard with calls"',
  '"the photocopier jammed"',
  '"the doors were jammed open"',
  '"GPS signals are weak and easily jammed"',
  '"the opportunity to jam with Atlanta blues musicians"',
];
export const synonyms = [
  "stuff",
  "shove",
  "force",
  "ram",
  "thrust",
  "wedge",
  "press",
  "push",
  "stick",
  "squeeze",
  "compress",
  "confine",
  "cram",
  "pack",
  "sandwich",
  "insert",
  "crowd",
  "pile",
  "throng",
  "occupy",
  "fill",
  "overfill",
  "overcrowd",
  "obstruct",
  "block",
  "clog",
  "congest",
  "mob",
  "stuff",
  "shove",
  "force",
  "ram",
  "thrust",
  "wedge",
  "press",
  "push",
  "stick",
  "squeeze",
  "compress",
  "confine",
  "cram",
  "pack",
  "sandwich",
  "insert",
  "stick",
  "catch",
  "seize (up)",
  "immobilize",
  "paralyze",
  "disable",
  "cripple",
  "deactivate",
  "stop",
  "halt",
  "become stuck",
  "become immobilized",
  "become unable to move",
  "become fixed",
  "become wedged",
  "become lodged",
  "become trapped",
  "put out of action",
  "make inoperative",
  "bring to a halt",
  "bring to a standstill",
  "free",
];
