export const definitions = [
  '"her little jaunt in France was over"',
  '"they went jaunting through Ireland"',
];
export const synonyms = [
  'trip',
  'outing',
  'excursion',
  'expedition',
  'day trip',
  'tour',
  'drive',
  'ride',
  'run',
  'turn',
  'cruise',
  'sally',
  'pleasure trip',
  'day out',
  'short break',
  'mystery tour',
  'minibreak',
  'mini holiday',
  'wander',
  'roam',
  'rove',
  'range',
  'travel',
  'journey',
  'voyage',
  'globetrot',
  'drift',
  'coast',
  'meander',
  'gallivant',
  'ramble',
  'stroll',
  'saunter',
  'maunder',
  'amble',
  'traipse',
  'dawdle',
  'putter',
  'traverse',
  'peregrinate',
  'perambulate',
  'vagabond',
  'travel idly',
  'gad around',
  'take a trip',
  'go on a trip',
  'travel round',
  'roam around',
  'range over',
];