export const definitions = [
  '"spectators ducked for cover"',
  '"he ducked his head and entered"',
  '"she ducked into the doorway to get out of the line of fire"',
  '"I thought I saw you duck out"',
  '"he ducked a punch from an angry first baseman"',
  '"a responsibility that a less courageous man might well have ducked"',
  '"I was engaged twice and ducked out both times"',
  '"I had to keep ducking down to get my head cool"',
  '"declarer ducked the opening spade lead"',
];
export const synonyms = [
  'sit on one\'s haunches',
  'cower',
  'cringe',
  'shrink',
  'huddle',
  'bob down',
  'bend (down)',
  'bow down',
  'stoop (down)',
  'crouch (down)',
  'squat (down)',
  'hunch down',
  'hunker down',
  'stand',
  'straighten up',
  'shirk',
  'dodge',
  'evade',
  'avoid',
  'steer clear of',
  'elude',
  'escape',
  'shun',
  'eschew',
  'miss',
  'sidestep',
  'bypass',
  'circumvent',
  'turn one\'s back on',
  'decline',
  'bilk',
  'run away from',
  'find a way out of',
  'back out of',
  'pull out of',
  'skirt around',
  'give a wide berth to',
  'find a way around',
  'face up to',
  'take part in',
  'dip',
  'dunk',
  'plunge',
  'immerse',
  'submerge',
  'lower',
  'sink',
];