export const definitions = [
  '"the newspaper was duped into publishing an untrue story"',
  '"knowing accomplices or unknowing dupes"',
];
export const synonyms = [
  'deceive',
  'trick',
  'hoodwink',
  'hoax',
  'swindle',
  'defraud',
  'cheat',
  'double-cross',
  'gull',
  'mislead',
  'take in',
  'fool',
  'delude',
  'misguide',
  'lead on',
  'inveigle',
  'seduce',
  'ensnare',
  'entrap',
  'beguile',
  'cozen',
  'sharp',
  'mulct',
  'victim',
  'gull',
  'pawn',
  'puppet',
  'instrument',
  'fool',
  'simpleton',
  'innocent',
  'swindler',
  'con man',
];