export const definitions = ['"you and Larry had a dust-up over Val?"'];
export const synonyms = [
  "quarrel",
  "argument",
  "row",
  "fight",
  "disagreement",
  "dissension",
  "falling-out",
  "dispute",
  "disputation",
  "contention",
  "squabble",
  "contretemps",
  "clash",
  "altercation",
  "exchange",
  "brawl",
  "tussle",
  "conflict",
  "affray",
  "war of words",
  "shouting match",
  "fracas",
  "wrangle",
  "tangle",
  "misunderstanding",
  "battle royal",
  "donnybrook",
  "broil",
  "miff",
  "difference of opinion",
  "passage of/at arms",
  "threap",
  "collieshangie",
  "tracasserie(s)",
];
