export const definitions = [
  '"I broke the vase I had been dusting"',
  '"pick yourself up and dust yourself off"',
  '"she washed and dusted and tidied"',
  '"a number of aircraft will be dusted off and returned to flight"',
  '"roll out on a surface dusted with flour"',
  '"orange powder was dusted over the upper body"',
  '"the officers dusted him up a little bit"',
];
export const synonyms = [
  "wipe",
  "clean",
  "buff",
  "brush",
  "sweep",
  "mop",
  "sprinkle",
  "scatter",
  "powder",
  "dredge",
  "sift",
  "spray",
  "cover",
  "spread",
  "strew",
  "dot",
  "fleck",
  "freckle",
  "dab",
  "bestrew",
  "besprinkle",
  "befleck",
];
