export const definitions = [
  '"it\'s my duty to uphold the law"',
  '"she was determined to do her duty as a citizen"',
  '"a strong sense of duty"',
  '"a fifteen-minute duty visit"',
  '"the queen\'s official duties"',
  '"your duties will include sweeping the switchboard"',
  '"Juliet reported for duty"',
  '"combat duty in the army"',
  '"a duty nurse"',
  '"he was willing to take Sunday duties"',
  '"a 6 percent duty on imports"',
  '"goods subject to excise duty"',
];
export const synonyms = [
  "responsibility",
  "obligation",
  "commitment",
  "obedience",
  "allegiance",
  "loyalty",
  "faithfulness",
  "fidelity",
  "respect",
  "deference",
  "reverence",
  "homage",
  "fealty",
  "job",
  "task",
  "chore",
  "assignment",
  "commission",
  "mission",
  "function",
  "charge",
  "part",
  "place",
  "role",
  "concern",
  "requirement",
  "responsibility",
  "obligation",
  "work",
  "burden",
  "onus",
  "office",
  "tax",
  "levy",
  "tariff",
  "toll",
  "tithe",
  "customs",
  "customs duties",
  "mulct",
];
