export const definitions = [
  '"though they were speaking in undertones, Philip could hear them"',
  '"you will be informed of its progress, slow though that may be"',
  '"her first name was Rose, though no one called her that"',
  '"I was hunting for work. Jobs were scarce though"',
];
export const synonyms = [
  'although',
  'even though',
  'in spite of the fact that',
  'despite the fact that',
  'for all that',
  'although',
  'while',
  'whilst',
  'albeit',
  'however',
  'yet',
  'but',
  'even though/if',
  'in spite of the fact that',
  'despite the fact that',
  'notwithstanding the fact that',
  'notwithstanding that',
  'for all that',
  'granted that',
  'even supposing',
  'despite the possibility that',
  'nevertheless',
  'nonetheless',
  'even so',
  'however',
  'be that as it may',
  'just the same',
  'all the same',
  'at the same time',
  'in any event',
  'come what may',
  'at any rate',
  'notwithstanding',
  'regardless',
  'anyway',
  'anyhow',
  'howbeit',
  'withal',
  'natheless',
  'for all that',
  'in spite of that/everything',
  'despite that/everything',
  'after everything',
  'having said that',
];