export const definitions = [
  '"she thrashed him across the head and shoulders"',
  '"the wind screeched and the mast thrashed the deck"',
  '"he lay on the ground thrashing around in pain"',
  '"she thrashed her arms, attempting to swim"',
  '"two months of thrashing around on my own have produced nothing"',
  '"I wrench the steering wheel back and thrash on up the hill"',
  '"I thrashed Pete at cards"',
  '"the Braves were thrashed 8–1 by the Mets"',
  '"the thrash of the waves"',
  '"after all those twelve-bar thrashes, my fingers were blistered"',
  '"a grungy thrash band"',
  '"Henry\'s charity ball had been one hell of a thrash"',
];
export const synonyms = [
  "hit",
  "beat",
  "flog",
  "whip",
  "horsewhip",
  "scourge",
  "lash",
  "flagellate",
  "flail",
  "strap",
  "birch",
  "cane",
  "belt",
  "leather",
  "bullwhip",
  "switch",
  "stripe",
  "thong",
  "quirt",
  "flail",
  "thresh",
  "flounder",
  "jerk",
  "toss",
  "squirm",
  "writhe",
  "twist",
  "wriggle",
  "wiggle",
  "twitch",
  "toss and turn",
  "struggle",
  "thresh",
  "flail",
  "pitch",
  "splash",
  "stagger",
  "stumble",
  "falter",
  "lurch",
  "blunder",
  "fumble",
  "grope",
  "squirm",
  "writhe",
  "toss and turn",
  "twist and turn",
  "make good progress",
  "trounce",
  "rout",
  "annihilate",
  "crush",
  "overwhelm",
  "best",
  "get the better of",
  "worst",
  "bring someone to their knees",
  "beat hollow",
  "defeat utterly",
  "triumph over",
  "win a resounding victory over",
  "be victorious over",
];
