export const definitions = [
  '"the new baby thrived"',
  '"education groups thrive on organization"',
  '"a thriving economy"',
];
export const synonyms = [
  'flourish',
  'prosper',
  'burgeon',
  'bloom',
  'blossom',
  'advance',
  'succeed',
  'shoot up',
  'boom',
  'profit',
  'expand',
  'flourishing',
  'prosperous',
  'prospering',
  'growing',
  'developing',
  'burgeoning',
  'blooming',
  'healthy',
  'successful',
  'advancing',
  'progressing',
  'luxuriant',
  'lush',
  'prolific',
  'booming',
  'profitable',
  'expanding',
  'fast-growing',
  'grow vigorously',
  'develop well',
  'do well',
  'make strides',
  'go well',
  'grow rich',
  'decline',
  'wither',
  'fail',
  'stagnate',
  'die',
  'moribund',
  'dying',
  'unhealthy',
];