export const definitions = [
  '"he pushed his way through the throng"',
  '"a throng of birds"',
  '"a crowd thronged the station"',
  '"the streets are thronged with people"',
  '"tourists thronged to the picturesque village"',
];
export const synonyms = [
  "crowd",
  "mass",
  "multitude",
  "horde",
  "host",
  "mob",
  "assemblage",
  "gathering",
  "congregation",
  "crush",
  "press",
  "body",
  "band",
  "army",
  "troop",
  "legion",
  "gang",
  "stream",
  "swarm",
  "flock",
  "bevy",
  "herd",
  "pack",
  "drove",
  "array",
  "sea",
  "myriad",
  "pile",
  "knot",
  "cluster",
  "group",
  "jam",
  "fill",
  "mob",
  "hem in",
  "jostle",
  "pack (into)",
  "cram (into)",
  "press into",
  "squeeze into",
  "crowd around",
  "press around",
  "mill around",
  "congregate around",
  "converge around",
  "rush",
  "stream",
  "flock",
  "troop",
  "crowd",
  "swarm",
  "surge",
  "flood",
  "flow",
  "spill",
  "teem",
];
