export const definitions = [
  '"the dress just needs to be altered a teensy bit"',
];
export const synonyms = [
  "minute",
  "small-scale",
  "scaled-down",
  "mini",
  "baby",
  "toy",
  "pocket",
  "fun-size",
  "petite",
  "dwarfish",
  "knee-high",
  "miniature",
  "minuscule",
  "microscopic",
  "nanoscopic",
  "infinitesimal",
  "micro",
  "microscale",
  "diminutive",
  "pocket-sized",
  "reduced",
  "Lilliputian",
  "trivial",
  "trifling",
  "negligible",
  "insignificant",
  "unimportant",
  "minor",
  "inconsequential",
  "minimal",
  "inappreciable",
  "imperceptible",
  "nugatory",
  "petty",
  "token",
  "nominal",
  "paltry",
  "inadequate",
  "insufficient",
  "meager",
  "derisory",
  "pitiful",
  "pathetic",
  "miserable",
  "wee",
  "vest-pocket",
  "of no account",
  "of no consequence",
  "of no importance",
  "not worth bothering about",
  "not worth mentioning",
  "huge",
  "significant",
];
