export const definitions = [
  '"people fled in terror"',
  '"a terror of darkness"',
  '"weapons of terror"',
  '"his unyielding scowl became the terror of the Chicago mob"',
  '"placid and obedient in their parents\' presence, but holy terrors when left alone"',
];
export const synonyms = [
  "dread",
  "horror",
  "fright",
  "trepidation",
  "alarm",
  "panic",
  "shock",
  "extreme fear",
  "fear and trembling",
  "demon",
  "fiend",
  "devil",
  "monster",
  "horror",
  "nightmare",
  "rascal",
  "devil",
  "imp",
  "monkey",
  "wretch",
  "scamp",
  "mischief-maker",
  "troublemaker",
  "scapegrace",
  "rapscallion",
];
