export const definitions = [
  '"she had always been tetchy and impatient with him"',
  '"a tetchy statement"',
];
export const synonyms = [
  "irritable",
  "irascible",
  "peevish",
  "crotchety",
  "cantankerous",
  "cross",
  "fractious",
  "disagreeable",
  "pettish",
  "crabbed",
  "crabby",
  "waspish",
  "prickly",
  "testy",
  "peppery",
  "impatient",
  "grumpy",
  "bad-tempered",
  "ill-tempered",
  "ill-natured",
  "ill-humored",
  "touchy",
  "scratchy",
  "volatile",
  "crusty",
  "dyspeptic",
  "splenetic",
  "liverish",
  "short-tempered",
  "hot-tempered",
  "quick-tempered",
  "choleric",
  "good-humored",
];
