export const definitions = [
  '"locate the area where you can go rabbiting"',
  '"stop rabbiting on, will you, and go to bed!"',
  '"he rabbited as soon as he saw us coming"',
];
export const synonyms = [
  "coney",
  "bunny (rabbit)",
  "talk",
  "gossip",
  "chatter",
  "chitter-chatter",
  "speak",
  "converse",
  "tittle-tattle",
  "prattle",
  "jabber",
  "jibber-jabber",
  "babble",
  "prate",
  "go on",
  "run on",
  "communicate",
  "talk nineteen to the dozen",
  "slabber",
  "confabulate",
  "twaddle",
  "clack",
  "have a conversation",
  "engage in conversation",
  "twattle",
  "claver",
];
