export const definitions = [
  '"officers raided thirty homes yesterday"',
  '"she crept down the stairs to raid the pantry"',
];
export const synonyms = [
  "attack",
  "assault",
  "harass",
  "harry",
  "blitz",
  "assail",
  "storm",
  "rush",
  "charge",
  "plunder",
  "pillage",
  "loot",
  "rifle",
  "maraud",
  "strip",
  "ransack",
  "sack",
  "despoil",
  "reave",
  "spoil",
  "forage",
  "rob",
  "hold up",
  "break into",
  "search",
  "make a raid on",
  "set upon",
  "descend on",
  "swoop on",
  "make inroads on",
  "steal from",
  "depredate",
  "spoliate",
  "make a search of",
];
