export const definitions = [
  '"I was the one who raked the leaves and cut the grass"',
  '"they started raking up hay"',
  '"in the early morning squads of workers rake the beach"',
  '"the infield dirt is meticulously raked"',
  '"her fingers raked Bill\'s face"',
  '"she raked a comb through her hair"',
  '"Greg let his high beams rake the shrubbery"',
  '"his steady gaze raked over the two men"',
  '"Nina decided to rake through the drawers"',
  '"the floor is steeply raked"',
  '"her long clipper bow and raked mast"',
];
export const synonyms = [
  "collect",
  "gather",
  "scrape up/together",
  "smooth",
  "level",
  "flatten",
  "comb",
  "smooth out",
  "even out",
  "scratch",
  "lacerate",
  "scrape",
  "rasp",
  "graze",
  "abrade",
  "grate",
  "bark",
  "excoriate",
  "drag",
  "pull",
  "scrape",
  "draw",
  "tug",
  "sweep",
  "enfilade",
  "pepper",
  "strafe",
  "cannonade",
  "fusillade",
  "search",
  "scan",
  "survey",
  "study",
  "inspect",
  "scour",
  "scrutinize",
  "examine",
  "explore",
  "look around/over",
  "rummage",
  "search",
  "hunt",
  "sift",
  "rifle",
  "ransack",
  "comb",
  "scour",
  "turn upside down",
  "go through with a fine-tooth comb",
];
