export const definitions = [
  '"I spent most of my spare time rambling and climbing"',
  '"he rambled on about his acting career"',
  '"roses climbed, rambled, hung over walls"',
];
export const synonyms = [
  "walk",
  "hike",
  "tramp",
  "backpack",
  "trek",
  "wander",
  "stroll",
  "saunter",
  "amble",
  "drift",
  "roam",
  "range",
  "rove",
  "traipse",
  "jaunt",
  "vagabond",
  "perambulate",
  "peregrinate",
  "take a walk",
  "go for a walk",
  "stravaig",
  "chatter",
  "babble",
  "prattle",
  "prate",
  "blather",
  "blether",
  "gabble",
  "jabber",
  "twitter",
  "go on",
  "run on",
  "blither",
  "maunder",
  "drivel",
  "twaddle",
  "clack",
  "rattle on/away",
  "twattle",
  "walk",
  "hike",
  "trek",
  "wander",
  "stroll",
  "saunter",
  "amble",
  "roam",
  "traipse",
  "jaunt",
  "promenade",
  "trip",
  "excursion",
  "tour",
  "perambulation",
  "peregrination",
];
