export const definitions = [
  '"he spoke without rancor"',
];
export const synonyms = [
  'bitterness',
  'spite',
  'hate',
  'hatred',
  'resentment',
  'malice',
  'ill will',
  'malevolence',
  'malignancy',
  'animosity',
  'antipathy',
  'enmity',
  'hostility',
  'acrimony',
  'venom',
  'poison',
  'vindictiveness',
  'balefulness',
  'vengefulness',
  'vitriol',
  'virulence',
  'perniciousness',
  'meanness',
  'nastiness',
  'maleficence',
  'amicability',
];