export const definitions = [
  '"the kidnappers demanded a ransom"',
  '"the capture and ransom of the king"',
  '"the lord was captured in war and had to be ransomed"',
  '"mercenaries burned the village and ransomed the inhabitants"',
  '"they were all ransomed and returned unharmed"',
];
export const synonyms = [
  "payoff",
  "payment",
  "price",
  "release",
  "freedom",
  "deliverance",
  "liberation",
  "rescue",
  "redemption",
  "restoration",
  "setting free",
  "release",
  "free",
  "deliver",
  "liberate",
  "rescue",
  "redeem",
  "obtain the release of",
  "exchange for a ransom",
  "buy the freedom of",
  "restore to freedom",
];
