export const definitions = [
  '"both countries were due to ratify the treaty by the end of the year"',
];
export const synonyms = [
  'confirm',
  'approve',
  'sanction',
  'endorse',
  'accept',
  'affirm',
  'uphold',
  'corroborate',
  'authorize',
  'formalize',
  'certify',
  'validate',
  'recognize',
  'sign',
  'countersign',
  'agree to',
  'consent to',
  'assent to',
  'put one\'s name to',
  'reject',
  'revoke',
];