export const definitions = [
  '"the ravings of a madwoman"',
  '"she\'d never been a raving beauty"',
  '"have you gone raving mad ? "',
  '"Nancy\'s having hysterics and raving about a ghost"',
  '""Never mind how he feels!" Melissa raved"',
  '"New York\'s theater critics raved about the acting"',
  '"they used to rave together—then they started working together"',
];
export const synonyms = [
  "gibberish",
  "rambling",
  "babbling",
  "wild talk",
  "incoherent talk",
  "considerable",
  "remarkable",
  "extraordinary",
  "singular",
  "striking",
  "outstanding",
  "stunning",
  "very great",
  "babble",
  "jabber",
  "ramble",
  "maunder",
  "talk wildly",
  "talk incoherently",
  "be delirious",
  "rant",
  "rant and rave",
  "rage",
  "lose one's temper",
  "storm",
  "fulminate",
  "shout",
  "roar",
  "thunder",
  "bellow",
  "fume",
  "explode in anger",
  "be beside oneself",
  "deliver a tirade/harangue",
  "go into a frenzy",
  "lose control",
  "be very angry",
  "be furious",
  "be enraged",
  "be incensed",
  "sing the praises of",
  "acclaim",
  "eulogize",
  "extol",
  "laud",
  "panegyrize",
  "praise enthusiastically",
  "go into raptures about/over",
  "wax lyrical about",
  "praise to the skies",
  "heap praise on",
  "rhapsodize over",
  "enthuse about/over",
  "gush about/over",
  "throw bouquets at",
  "express delight over",
  "cry someone/something up",
  "criticize",
  "condemn",
];
