export const definitions = [
  '"there is no assurance that her infant child will not be ravished from her breast"',
  '"an angry father who suspects that his daughter has been ravished"',
  '"ravished by a sunny afternoon, she had agreed without even thinking"',
];
export const synonyms = [
  'kidnap',
  'carry off',
  'seize',
  'capture',
  'make off with',
  'hijack',
  'rape',
  'run away/off with',
  'spirit away',
  'hold hostage',
  'hold to ransom',
  'rape',
  'violate',
  'molest',
  'dishonor',
  'defile',
  'sexually assault/abuse',
  'force oneself on',
  'enrapture',
  'enchant',
  'delight',
  'charm',
  'entrance',
  'enthrall',
  'captivate',
  'bewitch',
  'spellbind',
  'fascinate',
  'transport',
  'rapture',
  'send into raptures',
  'fill with delight',
  'overjoy',
];