export const definitions = [
  '"the hostilities had ceased and normal life was resumed"',
  '"on his retirement the job will cease to exist"',
  '"they were asked to cease all military activity"',
];
export const synonyms = [
  "come to an end",
  "end",
  "halt",
  "stop",
  "conclude",
  "terminate",
  "finish",
  "wind up",
  "pause",
  "break off",
  "abate",
  "fade away",
  "discontinue",
  "leave off",
  "quit",
  "shut down",
  "suspend",
  "come to a halt",
  "come to a stop",
  "draw to a close",
  "be over",
  "come to a standstill",
  "peter out",
  "fizzle out",
  "die away",
  "bring to an end",
  "bring to a halt",
  "bring to a stop",
  "desist from",
  "refrain from",
  "cut short",
  "start",
  "continue",
];
