export const definitions = [
  '"20th century popular culture"',
  '"men of culture"',
  '"Caribbean culture"',
  '"people from many different cultures"',
  '"the emerging drug culture"',
  '"the cells proliferate readily in culture"',
  '"the bacterium was isolated in two blood cultures"',
  '"this variety of lettuce is popular for its ease of culture"',
  '"several investigators have attempted to culture biliary cells"',
];
export const synonyms = [
  "the arts",
  "literature",
  "music",
  "painting",
  "philosophy",
  "the humanities",
  "intellectual achievement(s)",
  "intellectual activity",
  "education",
  "cultivation",
  "enlightenment",
  "discernment",
  "discrimination",
  "taste",
  "refinement",
  "polish",
  "sophistication",
  "urbanity",
  "urbaneness",
  "erudition",
  "learning",
  "letters",
  "belles-lettres",
  "intellectual/artistic awareness",
  "good taste",
  "civilization",
  "society",
  "way of life",
  "lifestyle",
  "customs",
  "traditions",
  "heritage",
  "habits",
  "ways",
  "mores",
  "values",
  "cultivation",
  "growing",
  "farming",
  "agriculture",
  "husbandry",
  "agronomy",
];
