export const definitions = [
  '"rubber cement"',
  '"traditional entertainment was a form of community cement"',
  '"dental cement"',
  '"wooden posts were cemented into the ground"',
  '"the two firms are expected to cement an agreement soon"',
  '"the original quartz grains were cemented by authigenic quartz"',
];
export const synonyms = [
  "adhesive",
  "glue",
  "fixative",
  "gum",
  "paste",
  "bonding",
  "binder",
  "sealer",
  "sealant",
  "superglue",
  "epoxy resin",
  "mucilage",
  "stick",
  "bond",
  "join",
  "connect",
  "fasten",
  "fix",
  "affix",
  "attach",
  "secure",
  "bind",
  "glue",
  "gum",
  "paste",
  "fuse",
  "weld",
  "solder",
];
