export const definitions = [
  '"the station has a central courtyard"',
  '"coaches met at a central location"',
  '"his preoccupation with American history is central to his work"',
  '"the rising crime rate remained the central campaign issue"',
  '"central government"',
  '"the central office"',
  '"you\'re in workaholic central here"',
];
export const synonyms = [
  "middle",
  "center",
  "halfway",
  "midway",
  "mid",
  "median",
  "medial",
  "mean",
  "middling",
  "intermediate",
  "mesial",
  "inner",
  "innermost",
  "interior",
  "nuclear",
  "intermedial",
  "side",
  "extreme",
  "outer",
  "main",
  "chief",
  "principal",
  "primary",
  "leading",
  "foremost",
  "first",
  "predominant",
  "dominant",
  "key",
  "crucial",
  "vital",
  "essential",
  "basic",
  "fundamental",
  "core",
  "staple",
  "critical",
  "pivotal",
  "salient",
  "prime",
  "focal",
  "premier",
  "paramount",
  "major",
  "ruling",
  "master",
  "supreme",
  "overriding",
  "cardinal",
  "capital",
  "preeminent",
  "ultimate",
  "uppermost",
  "highest",
  "utmost",
  "top",
  "topmost",
  "arch-",
  "most important",
  "(most) prominent",
  "subordinate",
  "minor",
];
