export const definitions = ['"tax dodgers"'];
export const synonyms = [
  "notice",
  "announcement",
  "bulletin",
  "commercial",
  "promotion",
  "blurb",
  "write-up",
  "display",
  "poster",
  "leaflet",
  "pamphlet",
  "flyer",
  "bill",
  "handbill",
  "handout",
  "circular",
  "brochure",
  "sign",
  "placard",
  "folder",
  "affiche",
];
