export const definitions = [
  '"success required dogged determination"',
  '"photographers seemed to dog her every step"',
  '"their finance committee has been dogged by controversy"',
  '"Eric had a reputation for dogging it a little"',
  '"she has dogged the door shut"',
];
export const synonyms = [
  "tenacious",
  "determined",
  "resolute",
  "resolved",
  "purposeful",
  "persistent",
  "persevering",
  "pertinacious",
  "relentless",
  "intent",
  "dead set",
  "single-minded",
  "focused",
  "dedicated",
  "committed",
  "undeviating",
  "unshakeable",
  "unflagging",
  "indefatigable",
  "untiring",
  "tireless",
  "unfailing",
  "unfaltering",
  "unwavering",
  "unyielding",
  "unbending",
  "immovable",
  "obdurate",
  "strong-willed",
  "firm",
  "steadfast",
  "steady",
  "staunch",
  "stouthearted",
  "laborious",
  "indurate",
  "never-tiring",
  "perseverant",
  "hesitant",
  "halfhearted",
  "pursue",
  "follow",
  "stalk",
  "track",
  "trail",
  "shadow",
  "hound",
  "plague",
  "beset",
  "bedevil",
  "assail",
  "beleaguer",
  "blight",
  "trouble",
  "torment",
  "haunt",
  "trouble",
  "disturb",
  "worry",
  "plague",
  "beset",
  "torture",
  "torment",
  "rack",
  "bedevil",
  "nag",
  "vex",
  "harass",
  "pester",
  "be prey to",
  "be the victim of",
];
