export const definitions = [
];
export const synonyms = [
  'pauper',
  'indigent',
  'bankrupt',
  'insolvent',
  'beggar',
  'mendicant',
  'vagrant',
  'tramp',
  'drifter',
  'derelict',
  'vagabond',
  'knight of the road',
  'bird of passage',
  'rolling stone',
  'job-seeker',
  'hobo',
  'bagman',
  'knockabout',
  'overlander',
  'sundowner',
  'whaler',
  'streety',
  'the homeless',
  'poor person',
  'homeless person',
  'person of no fixed address/abode',
  'unemployed person',
  'the poor',
  'the destitute',
  'the needy',
  'the unemployed',
];