export const definitions = [
  '"she was spoiled outrageously by her doting father"',
  '"she doted on her two young children"',
  '"having an older brother who dotes you a lot is the best thing ever"',
  '"the parson is now old and dotes"',
];
export const synonyms = [
  "adore",
  "idolize",
  "treasure",
  "cherish",
  "worship",
  "admire",
  "prize",
  "indulge",
  "spoil",
  "pamper",
  "adoring",
  "loving",
  "amorous",
  "besotted",
  "infatuated",
  "lovesick",
  "passionate",
  "affectionate",
  "fond",
  "devoted",
  "solicitous",
  "caring",
  "tender",
  "warm",
  "warmhearted",
  "overindulgent",
  "indulgent",
  "love dearly",
  "be devoted to",
  "lavish affection on",
  "think very highly of",
  "appreciate greatly",
  "hold dear",
  "hate",
  "neglect",
  "stony",
];
