export const definitions = [
  '"the double doors"',
  '"she sipped a double brandy"',
  '"a double bed"',
  '"the double life of a freelance secret agent"',
  '""otter" is spelled with a double t"',
  '"large double blooms"',
  '"the jail now houses almost double the number of prisoners it was designed for"',
  '"I\'ll pay double what I paid last time"',
  '"you have to be careful, and this counts double for older people"',
  '"she thought she was seeing double"',
  '"join the two sleeping bags together to make a double"',
  '""Two whiskies, and make it doubles please""',
  '"you must finish the game on a double"',
  '"you could pass yourself off as his double"',
  '"she had seen her husband\'s double"',
  '"the semifinals of the doubles"',
  '"he paid double and had a room all to himself"',
  '"profits doubled in one year"',
  '"Clare doubled her income overnight"',
  '"thy fifty yet doth double five and twenty"',
  '"I doubled across the deck to join the others"',
  '"Strawberry doubled with two outs"',
  '"it may be right for East to double"',
  '"the muslin is doubled and then laid in a sieve over the bowl"',
  '"he had one arm around her and the other fist doubled"',
  '"we struck out seaward to double the headland of the cape"',
  '"a laser printer doubles as a photocopier"',
];
export const synonyms = [
  "dual",
  "duplex",
  "twin",
  "binary",
  "duplicate",
  "matched",
  "matching",
  "paired",
  "complementary",
  "coupled",
  "twofold",
  "binate",
  "in pairs",
  "single",
  "doubled",
  "twofold",
  "twice the usual size",
  "ambiguous",
  "equivocal",
  "dual",
  "two-edged",
  "ambivalent",
  "arguable",
  "debatable",
  "Delphic",
  "cryptic",
  "enigmatic",
  "gnomic",
  "paradoxical",
  "misleading",
  "double-edged",
  "deceitful",
  "double-dealing",
  "two-faced",
  "Janus-faced",
  "hypocritical",
  "backstabbing",
  "false",
  "duplicitous",
  "insincere",
  "deceiving",
  "dissembling",
  "dishonest",
  "disloyal",
  "treacherous",
  "perfidious",
  "faithless",
  "lying",
  "untruthful",
  "mendacious",
  "open to debate",
  "open to argument",
  "unambiguous",
  "simple",
  "honest",
  "twice",
  "doubly",
  "twice over",
  "twice the amount",
  "lookalike",
  "twin",
  "clone",
  "duplicate",
  "replica",
  "copy",
  "facsimile",
  "imitation",
  "picture",
  "image",
  "mirror image",
  "counterpart",
  "match",
  "mate",
  "fellow",
  "perfect likeness",
  "exact likeness",
  "living image",
  "Doppelgänger",
  "stand-in",
  "body double",
  "understudy",
  "substitute",
  "lookalike",
  "twin",
  "clone",
  "duplicate",
  "replica",
  "copy",
  "facsimile",
  "imitation",
  "picture",
  "image",
  "mirror image",
  "counterpart",
  "match",
  "mate",
  "fellow",
  "perfect likeness",
  "exact likeness",
  "living image",
  "Doppelgänger",
  "enlarge",
  "magnify",
  "repeat",
  "multiply by two",
  "increase twofold",
  "sprint",
  "race",
  "dart",
  "rush",
  "dash",
  "hasten",
  "hurry",
  "scurry",
  "scuttle",
  "scamper",
  "hare",
  "bolt",
  "bound",
  "fly",
  "gallop",
  "career",
  "charge",
  "pound",
  "shoot",
  "hurtle",
  "speed",
  "streak",
  "whiz",
  "zoom",
  "sweep",
  "flash",
  "jog",
  "lope",
  "trot",
  "jogtrot",
  "dogtrot",
  "post",
  "hie",
  "go like lightning",
  "go hell for leather",
  "go like the wind",
  "dawdle",
  "crease",
  "fold (back/up/down/over/under)",
  "turn back/up/down/over/under",
  "tuck back/up/down/under",
  "bend back/over",
  "function",
  "do",
  "(also) serve",
  "have/serve a dual purpose",
  "have a dual role",
];
