export const definitions = [
  '"he doused the car with gasoline and set it on fire"',
  '"stewards appeared and the fire was doused"',
  '"nothing could douse her sudden euphoria"',
];
export const synonyms = [
  "drench",
  "soak",
  "souse",
  "saturate",
  "drown",
  "flood",
  "inundate",
  "deluge",
  "wet",
  "splash",
  "slosh",
  "hose down",
  "extinguish",
  "put out",
  "quench",
  "stamp out",
  "smother",
  "beat out",
  "blow out",
  "dampen down",
  "snuff out",
  "dout",
];
