export const definitions = [
  '"175 enemy aircraft had been downed"',
  '"he struck Slater on the face, downing him"',
  '"Jones downed the ball in the end zone"',
  '"he downed a six-pack"',
  '"he downed a 20-foot putt for victory"',
];
export const synonyms = [
  "knock down",
  "knock over",
  "bring down",
  "fell",
  "topple",
  "prostrate",
  "tackle",
  "knock to the ground",
  "throw to the ground",
  "bring to the ground",
  "rugby-tackle",
  "trip up",
  "guzzle",
  "quaff",
  "drain",
  "imbibe",
  "sup",
  "slurp",
  "suck",
  "sip",
  "swallow",
  "finish off",
  "polish off",
  "ingurgitate",
  "drink (up/down)",
  "gulp (down)",
];
