export const definitions = ['"the old adage "out of sight out of mind.""'];
export const synonyms = [
  "saying",
  "maxim",
  "axiom",
  "proverb",
  "aphorism",
  "saw",
  "dictum",
  "precept",
  "epigram",
  "epigraph",
  "motto",
  "truism",
  "platitude",
  "cliché",
  "commonplace",
  "expression",
  "phrase",
  "formula",
  "slogan",
  "quotation",
  "apothegm",
  "gnome",
  "words of wisdom",
  "pearls of wisdom",
];
