export const definitions = [
  '"a former heroin addict"',
  '"a self-confessed chocolate addict"',
  '"a must-buy book for the crossword-puzzle addict"',
];
export const synonyms = [
  "abuser",
  "user",
  "viper",
  "narcotist",
  "morphinist",
  "morphiomaniac",
  "etheromaniac",
  "enthusiast",
  "fan",
  "fanatic",
  "lover",
  "devotee",
  "aficionado",
  "master",
  "wizard",
  "adherent",
  "follower",
  "admirer",
];
