export const definitions = [
  '"this might just be my addled brain playing tricks"',
  '"a drug-addled hell-raiser"',
  '"being in love must have addled your brain"',
  '"the extremely hot and dry weather had caused the eggs to addle"',
];
export const synonyms = [
  'rotten',
  'off',
  'decayed',
  'decomposed',
  'decomposing',
  'putrid',
  'putrefied',
  'putrescent',
  'moldy',
  'moldering',
  'sour',
  'rancid',
  'rank',
  'maggoty',
  'worm-eaten',
  'wormy',
  'flyblown',
  'putrefactive',
  'unfit for human consumption',
  'putrefacient',
  'fresh',
];