export const definitions = ['"they are adepts at kung fu and karate"'];
export const synonyms = [
  "expert",
  "past master",
  "master",
  "genius",
  "virtuoso",
  "maestro",
  "doyen",
  "artist",
  "professional",
  "veteran",
  "old hand",
  "grandmaster",
  "champion",
  "star",
  "winner",
  "wunderkind",
  "master hand",
  "amateur",
];
