export const definitions = [
  '"he adored his mother"',
  '"she adores Mexican cuisine"',
  '"he adored the Sacred Host"',
];
export const synonyms = [
  'love',
  'cherish',
  'treasure',
  'prize',
  'think the world of',
  'admire',
  'look up to',
  'revere',
  'reverence',
  'idolize',
  'lionize',
  'worship',
  'deify',
  'love dearly',
  'be devoted to',
  'dote on',
  'care for',
  'hold dear',
  'set great store by',
  'hold in admiration',
  'hold in high regard',
  'regard highly',
  'have a high opinion of',
  'stand in awe of',
  'hate',
  'loathe',
  'detest',
  'like',
  'love',
  'enjoy',
  'take pleasure in',
  'relish',
  'savor',
  'have a liking for',
  'be fond of',
  'be keen on',
  'be partial to',
  'have a taste for',
  'have a weakness for',
  'delight in',
  'revel in',
  'rate highly',
  'regard highly',
  'hate',
  'loathe',
  'detest',
  'worship',
  'glorify',
  'praise',
  'revere',
  'reverence',
  'exalt',
  'laud',
  'extol',
  'esteem',
  'venerate',
  'magnify',
  'pay homage to',
  'pay tribute to',
];