export const definitions = [
  '"a cargo ship went adrift"',
  '"she found herself cast adrift in a land full of strangers"',
  '"one of my fillings has come adrift"',
  '"the seamen are adrift in lifeboats"',
  '"the film industry was adrift in a sea of debt"',
  '"the film\'s focus is a young woman adrift in a city where individuals struggle to make meaningful connections"',
  '"they were only a point adrift at the break"',
  '"the team are three points adrift of the leaders"',
];
export const synonyms = [
  "drifting",
  "unmoored",
  "unanchored",
  "lost",
  "off course",
  "off track",
  "disorientated",
  "disoriented",
  "confused",
  "bewildered",
  "unsettled",
  "drifting",
  "rootless",
  "directionless",
  "aimless",
  "purposeless",
  "off the right track",
  "having lost one's bearings",
  "(all) at sea",
  "without purpose",
  "without goal",
  "at a loose end",
  "loose",
  "free",
  "astray",
  "detached",
  "unsecured",
  "unhitched",
  "unfastened",
  "untied",
  "untethered",
  "unknotted",
  "undone",
  "drifting",
  "unmoored",
  "unanchored",
  "lost",
  "off course",
  "off track",
  "disorientated",
  "disoriented",
  "confused",
  "bewildered",
  "unsettled",
  "drifting",
  "rootless",
  "directionless",
  "aimless",
  "purposeless",
  "off the right track",
  "having lost one's bearings",
  "(all) at sea",
  "without purpose",
  "without goal",
  "at a loose end",
];
