export const definitions = [
  '"she visited the island on her doctor\'s ______"',
  '"he took my ______ and put his house up for sale"',
  '"remittance ______s"',
  '"the want of fresh ______s from Europe"',
];
export const synonyms = [
  "guidance",
  "advising",
  "counseling",
  "counsel",
  "help",
  "direction",
  "instruction",
  "information",
  "enlightenment",
  "recommendations",
  "guidelines",
  "suggestions",
  "hints",
  "tips",
  "pointers",
  "ideas",
  "opinions",
  "views",
  "facts",
  "data",
  "news",
  "information",
  "word",
  "intelligence",
  "intimation",
  "tidings",
];
