export const definitions = [
  '"they would take the mickey out of me with sickening enthusiasm"',
  '"I bet some guy slipped me a mickey"',
];
export const synonyms = [
  "mockery",
  "derision",
  "laughter",
  "scorn",
  "scoffing",
  "contempt",
  "jeering",
  "sneering",
  "sneers",
  "jibes",
  "jibing",
  "joking",
  "teasing",
  "taunts",
  "taunting",
  "ragging",
  "chaffing",
  "twitting",
  "raillery",
  "sarcasm",
  "satire",
  "lampoon",
  "burlesque",
  "caricature",
  "parody",
  "sport",
  "praise",
  "respect",
];
