export const definitions = [
  '"two hours later he was up again to milk the cows"',
  '"I had to start the milking"',
  '"the breed does seem to milk better in harder conditions"',
  '"scientists have found a new way of producing an anti-clotting agent—by milking a leech"',
  '"he had milked his grandmother dry of all her money"',
  '"the newspapers were milking the story for every possible drop of drama"',
  '"he milked the crowd for every last drop of applause"',
];
export const synonyms = [
  'siphon',
  'bleed',
  'tap',
  'drain',
  'extract',
  'withdraw',
  'draw off',
  'pump off',
  'exploit',
  'take advantage of',
  'bleed',
  'fleece',
  'squeeze',
  'wring',
  'blackmail',
  'cash in on',
  'impose on',
  'suck dry',
  'extract',
  'elicit',
  'force',
  'coerce',
  'exact',
  'extort',
  'wrest',
  'wrench',
  'screw',
  'squeeze',
];