export const definitions = [
  '"the sound of voices mingled with a scraping of chairs"',
  '"an expression that mingled compassion and bewilderment"',
  '"over aperitifs, there was a chance to mingle with friends old and new"',
];
export const synonyms = [
  "mix",
  "blend",
  "intermingle",
  "commingle",
  "intermix",
  "interweave",
  "interlace",
  "combine",
  "merge",
  "fuse",
  "unite",
  "join",
  "amalgamate",
  "meld",
  "marry",
  "mesh",
  "compound",
  "coalesce",
  "admix",
  "commix",
  "interflow",
  "interblend",
  "separate",
  "be separated",
  "socialize",
  "circulate",
  "fraternize",
  "get together",
  "associate with others",
  "rub shoulders",
  "consort with others",
  "separate",
  "part",
];
