export const definitions = [
  '"I imagine those kids think I\'m minted"',
  '"grilled lamb chops with minted potatoes"',
  '"only coins of a relatively high denomination were minted"',
  '"an example of newly minted technology"',
];
export const synonyms = [
  'wealthy',
  'affluent',
  'moneyed',
  'cash rich',
  'well off',
  'well-to-do',
  'prosperous',
  'opulent',
  'substantial',
  'propertied',
  'silk-stocking',
  'multi-crore',
  'with deep pockets',
  'poor',
  'coin',
  'stamp',
  'stamp out',
  'strike',
  'cast',
  'punch',
  'die',
  'forge',
  'make',
  'manufacture',
  'produce',
  'create',
  'invent',
  'make up',
  'think up',
  'dream up',
  'hatch',
  'devise',
  'frame',
  'originate',
  'come up with',
  'fabricate',
  'fashion',
  'produce',
];