export const definitions = [
  '"although there were a few minor mishaps, none of the pancakes stuck to the ceiling"',
  '"the event passed without mishap"',
];
export const synonyms = [
  "accident",
  "trouble",
  "problem",
  "difficulty",
  "issue",
  "setback",
  "reverse",
  "adversity",
  "misadventure",
  "misfortune",
  "mischance",
  "blow",
  "failure",
  "disaster",
  "tragedy",
  "affliction",
  "woe",
  "trial",
  "tribulation",
  "catastrophe",
  "contretemps",
  "upset",
  "calamity",
  "reverse of fortune",
  "stroke of bad luck",
];
