export const definitions = [
  '"he was found guilty of misusing public funds"',
  '"we felt that we had been deceived and misused"',
  '"drugs of such potency that their misuse can have dire consequences"',
  '"a misuse of power"',
];
export const synonyms = [
  "misapply",
  "misemploy",
  "embezzle",
  "abuse",
  "exploit",
  "squander",
  "waste",
  "dissipate",
  "put to wrong use",
  "use fraudulently",
  "ill-treat",
  "maltreat",
  "mistreat",
  "abuse",
  "ill-use",
  "hit",
  "beat",
  "strike",
  "mishandle",
  "manhandle",
  "maul",
  "molest",
  "injure",
  "harm",
  "hurt",
  "bully",
  "persecute",
  "treat badly",
  "handle/treat roughly",
  "knock about/around",
  "look after",
  "treat well",
  "misemployment",
  "embezzlement",
  "fraud",
  "exploitation",
  "squandering",
  "waste",
  "dissipation",
  "abuse",
  "misapplication",
  "wrong use",
  "illegal use",
];
