export const definitions = [
  '"this horse has a placid nature"',
  '"the placid waters of a small lake"',
];
export const synonyms = [
  "even-tempered",
  "calm",
  "equable",
  "tranquil",
  "imperturbable",
  "unexcitable",
  "peaceable",
  "peaceful",
  "serene",
  "mild",
  "gentle",
  "quiet",
  "cool",
  "coolheaded",
  "collected",
  "composed",
  "self-possessed",
  "poised",
  "easygoing",
  "temperate",
  "levelheaded",
  "steady",
  "unruffled",
  "unmoved",
  "undisturbed",
  "unperturbed",
  "unemotional",
  "phlegmatic",
  "stolid",
  "bovine",
  "equanimous",
  "cool, calm, and collected",
  "excitable",
  "temperamental",
  "quiet",
  "calm",
  "tranquil",
  "still",
  "peaceful",
  "motionless",
  "smooth",
  "waveless",
  "pacific",
  "unruffled",
  "undisturbed",
  "restful",
  "sleepy",
  "like a millpond",
  "stormy",
  "rough",
];
