export const definitions = [
  '"up to 40 percent of employed people are in part-time jobs"',
  '"the firm employs 150 people"',
  '"temps can be employed to do much of the work"',
  '"most of the newcomers are employed in developing the technology into a product"',
  '"the methods they have employed to collect the data"',
];
export const synonyms = [
  "working",
  "professional",
  "career",
  "earning",
  "waged",
  "breadwinning",
  "in work",
  "in employment",
  "with a job",
  "holding down a job",
  "with a career",
  "in gainful employment",
  "earning one's living",
  "unemployed",
  "hire",
  "engage",
  "recruit",
  "take on",
  "sign up",
  "sign",
  "enroll",
  "appoint",
  "commission",
  "enlist",
  "retain",
  "indenture",
  "apprentice",
  "take into employment",
  "secure the services of",
  "put on the payroll",
  "have in employment",
  "have on the payroll",
  "dismiss",
  "occupy",
  "engage",
  "involve",
  "tie up",
  "absorb",
  "engross",
  "immerse",
  "keep busy",
  "use",
  "utilize",
  "make use of",
  "implement",
  "apply",
  "exercise",
  "practice",
  "exert",
  "bring into play",
  "draw on",
  "turn to",
  "take advantage of",
  "avail oneself of",
  "put into service",
  "put into practice",
  "bring into action",
  "bring to bear",
  "resort to",
  "have recourse to",
];
