export const definitions = [
  '"deep-buttoned plush upholstery"',
  '"the plush chrome and leather office"',
];
export const synonyms = [
  'fibers',
  'threads',
  'loops',
  'nap',
  'velvet',
  'shag',
  'fur',
  'hair',
  'surface',
  'soft surface',
  'lavish',
  'luxurious',
  'deluxe',
  'opulent',
  'magnificent',
  'resplendent',
  'gorgeous',
  'splendid',
  'grand',
  'extravagant',
  'lush',
  'palatial',
  'princely',
  'rich',
  'costly',
  'expensive',
  'impressive',
  'imposing',
  'lavishly appointed',
  'humble',
  'plain',
  'cheap',
];