export const definitions = ['"the poles are spaced 3 feet apart"'];
export const synonyms = [
  "separate",
  "place",
  "position",
  "arrange",
  "line up",
  "range",
  "order",
  "array",
  "dispose",
  "lay out",
  "deploy",
  "locate",
  "settle",
  "situate",
  "set",
  "stand",
  "station",
  "place at intervals",
];
