export const definitions = [
  '"her sparky personality"',
];
export const synonyms = [
  'cheerful',
  'happy',
  'jolly',
  'merry',
  'bright',
  'sunny',
  'joyous',
  'lighthearted',
  'sparkling',
  'bubbly',
  'effervescent',
  'exuberant',
  'ebullient',
  'cock-a-hoop',
  'breezy',
  'airy',
  'cheery',
  'sprightly',
  'jaunty',
  'smiling',
  'grinning',
  'beaming',
  'laughing',
  'mirthful',
  'radiant',
  'jubilant',
  'overjoyed',
  'thrilled',
  'ecstatic',
  'euphoric',
  'blissful',
  'elated',
  'delighted',
  'glad',
  'gleeful',
  'gratified',
  'jovial',
  'genial',
  'good-humored',
  'happy-go-lucky',
  'carefree',
  'unworried',
  'untroubled',
  'buoyant',
  'optimistic',
  'hopeful',
  'positive',
  'content',
  'contented',
  'gay',
  'jocund',
  'gladsome',
  'blithe',
  'blithesome',
  'of good cheer',
  'in good spirits',
  'in high spirits',
  'beside oneself with joy',
  'on cloud nine/seven',
  'without a care in the world',
  'full of the joys of spring',
  'full of hope',
  'sad',
  'miserable',
];