export const definitions = [
  '"the Bank of England in 1795 had held around £8 million in specie"',
];
export const synonyms = [
  "cash",
  "hard cash",
  "ready money",
  "funds",
  "capital",
  "finances",
  "banknotes",
  "notes",
  "paper money",
  "coins",
  "change",
  "coin",
  "coinage",
  "silver",
  "copper",
  "currency",
  "legal tender",
  "sterling",
  "bills",
  "roll",
  "pelf",
  "the means",
  "the wherewithal",
  "(filthy) lucre",
  "l.s.d.",
];
