export const definitions = [
  '"we hit the water with a mighty splash"',
  '"the girls joined them for a final splash in the pool"',
  '"a splash of gravy"',
  '"a splash of lemonade"',
  '"add a red scarf to give a splash of color"',
  '"a front-page splash"',
  '"there\'s going to be a big splash when Mike returns to the ring"',
  '"she splashed cold water onto her face"',
  '"they splashed each other with water"',
  '"a tear fell and splashed onto the pillow"',
  '"some stones splashed into the water"',
  '"wheels splashed through a puddle"',
  '"a field splashed with purple clover"',
  '"the story was splashed across the front pages"',
  '"the newspaper splashed the news on Sunday\'s cover"',
];
export const synonyms = [
  "splashing",
  "swashing",
  "dashing",
  "beating",
  "battering",
  "plash",
  "plashing",
  "swash",
  "swim",
  "bathe",
  "dive",
  "plunge",
  "paddle",
  "spot",
  "blob",
  "dab",
  "daub",
  "smudge",
  "smear",
  "speck",
  "speckle",
  "fleck",
  "patch",
  "pop",
  "mark",
  "stain",
  "drop",
  "dash",
  "bit",
  "spot",
  "soupçon",
  "dribble",
  "driblet",
  "little",
  "small amount",
  "patch",
  "burst",
  "streak",
  "feature",
  "story",
  "article",
  "piece",
  "display",
  "spatter",
  "bespatter",
  "splatter",
  "speck",
  "speckle",
  "blotch",
  "smear",
  "stain",
  "mark",
  "bedabble",
  "sprinkle",
  "spray",
  "spritz",
  "shower",
  "splatter",
  "slosh",
  "slop",
  "squirt",
  "daub",
  "wet",
  "swash",
  "wash",
  "break",
  "lap",
  "dash",
  "beat",
  "lash",
  "batter",
  "crash",
  "buffet",
  "surge",
  "plash",
  "paddle",
  "wade",
  "slosh",
  "wallow",
  "be flecked with",
  "be dotted with",
  "be stippled with",
  "be studded with",
  "be scattered with",
  "blazon",
  "display",
  "spread",
  "plaster",
  "trumpet",
  "publicize",
  "broadcast",
  "headline",
];
