export const definitions = [
  '"I wouldn\'t want to spoil your fun"',
  '"a series of political blunders spoiled their chances of being re - elected"',
  '"she was afraid of spoiling Christmas for the rest of the family"',
  '"the group called on its supporters to spoil their papers"',
  "\"I've got some ham that'll spoil if we don't eat it tonight\"",
  '"the last thing I want to do is spoil Thomas"',
  '"breakfast in bed—you\'re spoiling me!"',
  '"Cooper was spoiling for a fight"',
  '"the enemy entered into Hereford, spoiled and fired the city, and razed the walls to the ground"',
  '"he acts like a spoiled brat"',
  '"the smell of spoiled milk"',
  '"the number of spoiled ballots was quite worrying"',
];
export const synonyms = [
  "mar",
  "damage",
  "impair",
  "blemish",
  "disfigure",
  "blight",
  "flaw",
  "deface",
  "scar",
  "injure",
  "harm",
  "ruin",
  "destroy",
  "wreck",
  "be a blot on the landscape",
  "disfeature",
  "improve",
  "enhance",
  "ruin",
  "wreck",
  "destroy",
  "upset",
  "undo",
  "mess up",
  "make a mess of",
  "dash",
  "sabotage",
  "scupper",
  "scotch",
  "torpedo",
  "blast",
  "vitiate",
  "cast a shadow over",
  "cloud",
  "darken",
  "take the shine off",
  "put a damper on",
  "take the edge off",
  "cook someone's goose",
  "bring to naught",
  "cast a pall over",
  "take the enjoyment/pleasure out of",
  "upset someone's apple cart",
  "further",
  "help",
  "enhance",
  "go off",
  "turn",
  "sour",
  "molder",
  "curdle",
  "rot",
  "perish",
  "decompose",
  "decay",
  "putrefy",
  "go bad",
  "go rancid",
  "go sour",
  "go moldy",
  "become addled",
  "become rotten",
  "keep",
  "overindulge",
  "pamper",
  "indulge",
  "mollycoddle",
  "cosset",
  "coddle",
  "baby",
  "spoon-feed",
  "overparent",
  "nanny",
  "nursemaid",
  "feather-bed",
  "cocker",
  "wait on hand and foot",
  "cater to someone's every whim",
  "kill with kindness",
  "dote on",
  "wrap in cotton wool",
  "neglect",
  "treat harshly",
  "be strict with",
  "after",
  "set on",
  "eager for",
  "itching for",
  "looking for",
  "keen to have",
  "raring for",
  "bent on",
  "on the lookout for",
  "longing for",
  "ransack",
  "plunder",
  "rob",
  "raid",
  "loot",
  "rifle",
  "sack",
  "dispossess",
  "strip",
  "deprive",
  "denude",
  "devastate",
  "ravage",
  "harry",
  "maraud",
  "despoil",
  "reave",
  "rape",
  "forage",
  "steal from",
  "lay waste",
  "depredate",
  "spoliate",
];
