export const definitions = ['"a sporty outfit"', '"a sporty red coupe"'];
export const synonyms = [
  "stylish",
  "smart",
  "jaunty",
  "casual",
  "informal",
  "formal",
  "dressy",
  "fast",
  "speedy",
  "slow",
  "athletic",
  "fit",
  "active",
  "energetic",
  "outdoor",
  "hearty",
  "unfit",
  "lazy",
];
