export const definitions = [
  '"the door shot open, sending him sprawling across the pavement"',
  '"she lay sprawled on the bed"',
  '"the town sprawled along several miles of cliff top"',
  '"she fell into a sort of luxurious sprawl"',
  '"a sprawl of buildings"',
  '"the growth of urban sprawl"',
];
export const synonyms = [
  "lounge",
  "loll",
  "lie",
  "recline",
  "slump",
  "flop",
  "slouch",
  "stretch out",
  "lie down",
  "lie back",
  "drape oneself",
  "be recumbent",
  "be prostrate",
  "be supine",
  "spread",
  "stretch",
  "straggle",
  "ramble",
  "trail",
  "spill",
];
