export const definitions = [
  '"I saw Charlie sprinting through the traffic toward me"',
  '"Greg broke into a sprint"',
  '"MacFarlane won the 1,500m with a fine sprint finish"',
  '"the 100 meters sprint"',
  '"team members discuss issues with each other at the end of every sprint"',
  '"a sprint planning session"',
];
export const synonyms = [
  "run",
  "race",
  "dart",
  "rush",
  "dash",
  "hasten",
  "hurry",
  "scurry",
  "scuttle",
  "scamper",
  "hare",
  "bolt",
  "bound",
  "fly",
  "gallop",
  "career",
  "charge",
  "pound",
  "shoot",
  "hurtle",
  "speed",
  "streak",
  "whiz",
  "zoom",
  "flash",
  "post",
  "hie",
  "go like lightning",
  "go hell for leather",
  "go like the wind",
  "walk",
  "turn of speed",
  "rush",
  "burst of speed",
  "increase of speed",
  "burst of energy",
  "race",
  "dash",
  "gallop",
  "rush",
  "spurt",
  "jog",
  "trot",
];
