export const definitions = [
  '"the plan includes a hydroelectric plant to fuel a paper factory"',
  '"a big novel that is fueled by anger and revenge"',
  '"arrive straight from work and fuel up on the complimentary buffet"',
  '"gasoline may have been used to fuel the fire"',
  '"don\'t open a door or you could fuel the flames"',
  '"his private pain fuels his passion as an actor"',
];
export const synonyms = [
  'power',
  'charge',
  'fire',
  'stoke up',
  'supply with fuel',
  'stimulate',
  'boost',
  'encourage',
  'intensify',
  'fortify',
  'support',
  'nurture',
  'incite',
  'inflame',
  'exacerbate',
  'animate',
  'vitalize',
  'fan',
  'feed',
  'whip up',
  'provoke',
  'goad',
  'dampen',
];