export const definitions = [
  '"he wouldn\'t be able to fulfill his ambition to visit Naples"',
  '"arts grants go to young people who say they wish to fulfill themselves"',
  '"friends whose ill-timed speed fulfilled my soon-repented deed"',
  '"some officials were dismissed because they could not fulfill their duties"',
  '"goods must fulfill three basic conditions"',
  '"customers expect online orders to be fulfilled reliably, quickly, and cheaply"',
];
export const synonyms = [
  "attain",
  "realize",
  "consummate",
  "satisfy",
  "manage",
  "bring off",
  "bring about",
  "carry off",
  "carry out",
  "carry through",
  "deliver",
  "succeed in",
  "bring to fruition",
  "fail in",
  "carry out",
  "accomplish",
  "achieve",
  "execute",
  "perform",
  "discharge",
  "implement",
  "effect",
  "effectuate",
  "conduct",
  "complete",
  "finish",
  "conclude",
  "perfect",
  "honor",
  "make good",
  "observe",
  "bring to completion",
  "be true to",
  "keep faith with",
  "neglect",
  "satisfy",
  "fill",
  "answer",
  "meet",
  "obey",
  "comply with",
  "conform to",
  "adhere to",
  "respond to",
  "fail",
];
