export const definitions = [
  '"a fusion of an idea from anthropology and an idea from psychology"',
  '"malformation or fusion of the three bones in the middle ear"',
  '"the center of the Sun where fusion occurs"',
  '"a fusion reactor"',
  '"the fusion of resin and glass fiber in the molding process"',
  '"jazz fusion"',
  '"their fusion fare includes a sushi-like roll of gingery rice and eel wrapped in marinated Greek grape leaves"',
];
export const synonyms = [
  "blend",
  "blending",
  "combination",
  "amalgamation",
  "joining",
  "bonding",
  "binding",
  "merging",
  "melding",
  "mingling",
  "integration",
  "intermixture",
  "intermingling",
  "synthesis",
  "coalescence",
  "compounding",
  "agglutination",
  "uniting",
  "marrying",
  "alliance",
  "unification",
  "commingling",
  "commixture",
  "interflow",
  "separation",
  "melting",
  "smelting",
  "dissolving",
  "dissolution",
  "liquefaction",
];
