export const definitions = [
  '"melt three ounces of butter in a large frying pan"',
  '"Robin summoned up every ounce of strength"',
];
export const synonyms = [
  "particle",
  "scrap",
  "bit",
  "speck",
  "iota",
  "whit",
  "jot",
  "trace",
  "atom",
  "shred",
  "crumb",
  "fragment",
  "grain",
  "drop",
  "spot",
  "mite",
  "tittle",
  "modicum",
  "scantling",
  "scruple",
  "jot or tittle",
  "stim",
];
