export const definitions = [
  '"an outcry of spontaneous passion"',
  '"the public outcry over the bombing"',
];
export const synonyms = [
  "shout",
  "exclamation",
  "cry",
  "yell",
  "howl",
  "whoop",
  "roar",
  "scream",
  "shriek",
  "screech",
  "protest(s)",
  "protestation(s)",
  "complaints",
  "objections",
  "indignation",
  "furor",
  "clamor",
  "clamoring",
  "fuss",
  "commotion",
  "uproar",
  "hue and cry",
  "row",
  "outbursts",
  "tumult",
  "opposition",
  "dissent",
  "vociferation",
  "howls of protest",
  "indifference",
];
