export const definitions = [
  '"the project was flawed from the outset"',
  '"a field of which he had known nothing at the outset and learned on the job"',
];
export const synonyms = [
  "start",
  "beginning",
  "arrival",
  "dawn",
  "birth",
  "origin",
  "inception",
  "conception",
  "opening",
  "launch",
  "inauguration",
  "institution",
  "initiation",
  "debut",
  "creation",
  "commencement",
  "starting point",
  "(first) appearance",
  "day one",
  "the first",
  "end",
  "conclusion",
];
