export const definitions = [
  '"a riding outfit"',
  '"Tom was the brains of the outfit"',
  '"a repair outfit"',
  '"an auction of dolls outfitted by world-famous designers"',
  '"he outfitted himself in the best gray suit he could afford"',
  '"planes outfitted with sophisticated electronic gear"',
];
export const synonyms = [
  "costume",
  "suit",
  "uniform",
  "ensemble",
  "habit",
  "attire",
  "clothes",
  "clothing",
  "dress",
  "garb",
  "regalia",
  "regimentals",
  "rig",
  "livery",
  "accoutrements",
  "trappings",
  "disguise",
  "kit",
  "strip",
  "apparel",
  "array",
  "raiment",
  "organization",
  "setup",
  "enterprise",
  "company",
  "firm",
  "partnership",
  "house",
  "business",
  "group",
  "band",
  "body",
  "crew",
  "team",
  "coterie",
  "clique",
  "unit",
  "formation",
  "corps",
  "commando",
  "cadre",
  "squad",
  "squadron",
  "patrol",
  "troop",
  "platoon",
  "detachment",
  "kit",
  "equipment",
  "tools",
  "utensils",
  "implements",
  "tackle",
  "apparatus",
  "paraphernalia",
  "things",
  "stuff",
  "accoutrement",
  "turnout",
  "equip",
  "rig out",
  "supply",
  "issue",
  "provide",
  "provision",
  "stock",
  "arm",
  "dress",
  "attire",
  "clothe",
  "robe",
  "costume",
  "garb",
  "drape",
  "array",
  "accoutre",
  "get up",
  "turn out",
  "bedizen",
  "caparison",
  "apparel",
  "invest",
  "habit",
  "fit out/up",
  "furnish with",
  "deck out",
  "trick out/up",
  "kit out",
  "trap out",
];
