export const definitions = [
  '"he had stood in front of it, observing the intricacy of the ironwork with the wonder of a child"',
  '"Athens was a place of wonder and beauty"',
  '"the electric trolley car was looked upon as the wonder of the age"',
  '"a wonder drug"',
  '"it is a wonder that losses are not much greater"',
  '"how many times have I written that, I wonder?"',
  '"I can\'t help wondering how Stasia and Katie are feeling"',
  '"I wonder whether you have thought more about it?"',
  '"I wonder about such a marriage"',
  '"people stood by and wondered at such bravery"',
  '"if I feel compassion for her, it is not to be wondered at"',
];
export const synonyms = [
  "awe",
  "admiration",
  "wonderment",
  "fascination",
  "surprise",
  "astonishment",
  "amazement",
  "marvel",
  "miracle",
  "phenomenon",
  "sensation",
  "sight",
  "spectacle",
  "beauty",
  "curiosity",
  "rarity",
  "nonpareil",
  "wonderful thing",
  "ponder",
  "think about",
  "conjecture",
  "ask oneself",
  "meditate on",
  "reflect on",
  "deliberate about",
  "muse on",
  "speculate about",
  "puzzle about",
  "be curious about",
  "be inquisitive about",
  "marvel",
  "be lost for words",
  "gape",
  "goggle",
  "gawk",
  "be amazed",
  "be filled with amazement",
  "be filled with admiration",
  "be astonished",
  "be surprised",
  "be awed",
  "stand in awe",
  "be full of wonder",
  "not believe one's eyes / ears",
  "not know what to say",
  "be dumbfounded",
  "be surprised",
  "express surprise",
  "find it surprising",
  "be astonished/amazed",
];
