export const definitions = [
  '"victims of domestic violence"',
  '"earthquake victims"',
  '"the victim of a hoax"',
  '"sacrificial victims for the ritual festivals"',
];
export const synonyms = [
  'sufferer',
  'casualty',
  'fatality',
  'loss',
  'loser',
  'injured party',
  'injured person',
  'wounded person',
  'dead person',
  'attacker',
  'assailant',
  'dupe',
  'fair game',
  'sitting target',
  'stooge',
  'gull',
  'fool',
  'Aunt Sally',
  'target',
  'prey',
  'quarry',
  'object',
  'subject',
  'recipient',
  'focus',
  'easy target',
  'easy prey',
  'everybody\'s fool',
  'sacrifice',
  'offering',
  'burnt offering',
  'scapegoat',
];