export const definitions = [
  '"she\'s still a virgin"',
  '"the parable of the wise and foolish virgins"',
  '"a political virgin"',
  '"his virgin bride"',
  '"acres of virgin forests"',
  '"virgin snow"',
  '"virgin aluminum"',
];
export const synonyms = [
  "maiden",
  "maid",
  "vestal virgin",
  "celibate",
  "virgo intacta",
  "vestal",
  "unmarried girl",
  "chaste woman",
  "chaste",
  "virginal",
  "celibate",
  "abstinent",
  "self-restrained",
  "self-denying",
  "unmarried",
  "unwed",
  "maiden",
  "maidenly",
  "pure",
  "virtuous",
  "uncorrupted",
  "incorrupt",
  "undefiled",
  "unblemished",
  "unsullied",
  "innocent",
  "sinless",
  "moral",
  "decent",
  "demure",
  "vestal",
  "pure as the driven snow",
  "untouched",
  "unspoiled",
  "untainted",
  "untarnished",
  "unadulterated",
  "pure",
  "immaculate",
  "pristine",
  "flawless",
  "unmarked",
  "unblemished",
  "spotless",
  "stainless",
  "unsullied",
  "unpolluted",
  "undefiled",
  "unaffected",
  "unchanged",
  "intact",
  "inviolate",
  "preserved",
  "unused",
  "in mint condition",
  "perfect",
  "unexplored",
  "uncharted",
  "unmapped",
  "in perfect condition",
];
