export const definitions = ['"outings vivify learning for children"'];
export const synonyms = [
  "enliven",
  "vitalize",
  "breathe (new) life into",
  "energize",
  "invigorate",
  "revive",
  "light up",
  "cheer up",
  "gladden",
  "encourage",
  "hearten",
  "inspire",
  "exhilarate",
  "thrill",
  "excite",
  "fire",
  "arouse",
  "rouse",
  "stir",
  "stimulate",
  "galvanize",
  "electrify",
  "inspirit",
  "give (new) life to",
  "liven up",
  "depress",
  "inhibit",
];
