export const definitions = [
  '"women were aided in childbirth by midwives"',
  '"the heel was slanted to aid in climbing hilly terrain"',
  '"diet and exercise aid healthy skin"',
];
export const synonyms = [
  'help',
  'assist',
  'abet',
  'avail',
  'succor',
  'sustain',
  'support',
  'back',
  'back up',
  'second',
  'stand by',
  'uphold',
  'come to the aid of',
  'give assistance to',
  'lend a hand to',
  'be of service to',
  'hinder',
  'facilitate',
  'promote',
  'encourage',
  'help',
  'speed up',
  'hasten',
  'accelerate',
  'expedite',
  'further',
  'boost',
  'give a boost/lift/push to',
  'spur on',
  'smooth/clear the way for',
  'discourage',
  'hinder',
];