export const definitions = [
  '"somebody had given the place a thorough ______"',
  '"taking the baby out for an ______"',
  '"these are ideas I feel might be worth an ______"',
  '"I hope the BBC gives the play another ______ very soon"',
  '"______ long-standing grievances at couples therapy"',
  '"______ out the laundry"',
  '"______ a snowy hand and signet ring"',
];
export const synonyms = [
  "ventilating",
  "ventilation",
  "aerating",
  "aeration",
  "freshening",
  "refreshing",
  "cooling",
  "air conditioning",
  "stroll",
  "walk",
  "saunter",
  "turn",
  "jaunt",
  "amble",
  "outing",
  "excursion",
  "trip",
  "expedition",
  "promenade",
  "constitutional",
  "expression",
  "voicing",
  "venting",
  "ventilation",
  "articulation",
  "statement",
  "declaration",
  "publicizing",
  "publication",
  "dissemination",
  "circulation",
  "communication",
  "spreading",
  "promulgation",
  "broadcast",
  "broadcasting",
  "revelation",
  "announcement",
  "proclamation",
  "divulgence",
  "submission",
  "raising",
  "mooting",
  "proposal",
  "discussion",
  "debate",
  "broadcast",
  "transmission",
  "televising",
  "showing",
  "relaying",
  "telecast",
  "dissemination",
  "express",
  "voice",
  "vent",
  "ventilate",
  "articulate",
  "state",
  "declare",
  "give voice to",
  "publicize",
  "publish",
  "disseminate",
  "circulate",
  "communicate",
  "spread",
  "promulgate",
  "broadcast",
  "reveal",
  "announce",
  "proclaim",
  "divulge",
  "submit",
  "raise",
  "moot",
  "propose",
  "discuss",
  "debate",
  "make public",
  "give expression to",
  "make known",
  "have one's say",
  "broadcast",
  "transmit",
  "beam",
  "televise",
  "show",
  "telecast",
  "relay",
  "disseminate",
  "send/put out",
  "put on the air/airwaves",
  "display",
  "exhibit",
  "flaunt",
  "show",
  "show off",
  "demonstrate",
  "make a show of",
  "draw attention to",
  "ventilate",
  "aerate",
  "freshen",
  "refresh",
  "cool",
  "air-condition",
];
