export const definitions = [
  '"aspirin is useful for headaches"',
];
export const synonyms = [
  'functional',
  'practical',
  'handy',
  'neat',
  'convenient',
  'utilitarian',
  'utility',
  'helpful',
  'applicable',
  'serviceable',
  'beneficial',
  'advantageous',
  'worthwhile',
  'profitable',
  'gainful',
  'rewarding',
  'productive',
  'constructive',
  'effective',
  'efficacious',
  'valuable',
  'fruitful',
  'of use',
  'of service',
  'of help',
  'of assistance',
  'useless',
  'disadvantageous',
];