export const definitions = [
  '"a waiter ushered me to a table"',
  '"the railroads ushered in an era of cheap mass travel"',
];
export const synonyms = [
  "attendant",
  "escort",
  "guide",
  "doorkeeper",
  "commissionaire",
  "aide",
  "lackey",
  "flunkey",
  "escort",
  "accompany",
  "help",
  "assist",
  "take",
  "show",
  "see",
  "lead",
  "lead the way",
  "conduct",
  "guide",
  "steer",
  "pilot",
  "shepherd",
  "convoy",
  "show someone the way",
  "herald",
  "signal",
  "announce",
  "ring in",
  "pave the way for",
  "portend",
  "foreshadow",
  "start",
  "begin",
  "initiate",
  "introduce",
  "inaugurate",
  "get off the ground",
  "kick off",
  "launch",
  "cause",
  "precede",
  "mark the start of",
  "give notice of",
  "show in",
  "set the scene for",
  "clear the way for",
  "open the way for",
  "smooth the path of",
  "put in place",
  "open the door to",
  "allow to happen",
  "get going",
  "set in motion",
  "get under way",
  "antecede",
];
