export const definitions = [
  '"he leaned back so that only two legs of his chair touched the floor"',
  '"the dog had one paw outstretched, not quite touching the ground"',
  '"he touched a strand of her hair"',
  '"she lowered her head to touch his fingers with her lips"',
  '"for a moment their fingers touched"',
  '"we touched wheels and nearly came off the road"',
  '"I didn\'t play her records or touch any of her stuff"',
  "\"I've got friends who'll pull strings—nobody will dare touch me\"",
  '"the beer by his right hand was hardly touched"',
  '"in three years I haven\'t touched a cent of the money"',
  '"he was good only for the jobs that nobody else would touch"',
  '"a tenth of state companies have been touched by privatization"',
  '"the voice was touched by hysteria"',
  '"a wry smile touched his lips"',
  '"she was touched by her friend\'s loyalty"',
  '"sales touched twenty grand last year"',
  '"there\'s no one who can touch him at lightweight judo"',
  '"her touch on his shoulder was hesitant"',
  '"you can manipulate images on the screen at the touch of a key"',
  '"expressions of love through words and touch"',
  '"reading by touch"',
  '"Viennese instruments with their too delicate touch"',
  '"add a touch of vinegar"',
  '"he retired to bed with a touch of flu"',
  '"the film\'s most inventive touch"',
  '"later he showed a surer political touch"',
  '"getting caught looks so incompetent, as though we\'re losing our touch"',
  '"I only tolerated him because he was good for a touch now and then"',
  '"you must put your fate to the touch"',
];
export const synonyms = [
  "meet",
  "join",
  "connect",
  "adjoin",
  "abut",
  "neighbor",
  "be in contact (with)",
  "come into contact (with)",
  "come together (with)",
  "converge (with)",
  "be contiguous (with)",
  "border (on)",
  "be (up) against",
  "link up (with)",
  "tap",
  "pat",
  "nudge",
  "prod",
  "poke",
  "feel",
  "stroke",
  "rub",
  "brush",
  "graze",
  "fondle",
  "caress",
  "pet",
  "tickle",
  "finger",
  "thumb",
  "handle",
  "press lightly",
  "rub (up) against",
  "brush (up) against",
  "toy with",
  "play about with",
  "fiddle with",
  "put one's hand on",
  "lay a hand on",
  "lay a finger on",
  "handle",
  "hold",
  "pick up",
  "move",
  "disturb",
  "harm",
  "use",
  "employ",
  "make use of",
  "access",
  "get (at)",
  "take advantage of",
  "meddle with",
  "play (about/around) with",
  "toy with",
  "fiddle with",
  "interfere with",
  "tamper with",
  "lay a hand on",
  "lay a finger on",
  "put to use",
  "have access to",
  "avail oneself of",
  "taste",
  "consume",
  "eat",
  "drink",
  "take",
  "partake of",
  "refrain from",
  "handle",
  "be associated with",
  "concern oneself with",
  "involve oneself in/with",
  "get involved with/in",
  "have something to do with",
  "have dealings with",
  "deal with",
  "be a party to",
  "affect",
  "concern",
  "involve",
  "have an effect on",
  "have a bearing on",
  "be relevant to",
  "be pertinent to",
  "affected",
  "softened",
  "moved",
  "stirred",
  "swayed",
  "aroused",
  "impressed",
  "influenced",
  "warmed",
  "impassioned",
  "upset",
  "disturbed",
  "distressed",
  "affect",
  "move",
  "stir",
  "arouse",
  "impress",
  "influence",
  "impassion",
  "disturb",
  "melt",
  "soften",
  "make/leave an impression on",
  "have an impact on",
  "have an effect on",
  "make sad",
  "arouse sympathy",
  "unmoved",
  "unimpressed",
  "reach",
  "attain",
  "come to",
  "make",
  "get up to",
  "get down to",
  "arrive at",
  "rise to",
  "soar to",
  "sink to",
  "plummet to",
  "dive to",
  "equal",
  "match",
  "parallel",
  "rival",
  "approach",
  "better",
  "beat",
  "compare with",
  "be on a par with",
  "be a match for",
  "be in the same class as",
  "be in the same league as",
  "be on an equal footing with",
  "come near",
  "get near",
  "come up to",
  "come/get close to",
  "measure up to/against",
  "press",
  "tap",
  "pat",
  "nudge",
  "prod",
  "poke",
  "push",
  "glance",
  "flick",
  "stroke",
  "brush",
  "graze",
  "pressure",
  "feeling",
  "feel",
  "contact",
  "tactility",
  "texture",
  "sense of touch",
  "tactile sense",
  "press",
  "tap",
  "pat",
  "nudge",
  "prod",
  "poke",
  "push",
  "glance",
  "flick",
  "stroke",
  "brush",
  "graze",
  "pressure",
  "trace",
  "bit",
  "suggestion",
  "suspicion",
  "hint",
  "scintilla",
  "tinge",
  "tincture",
  "whiff",
  "whisper",
  "overtone",
  "undertone",
  "nuance",
  "murmur",
  "coloring",
  "breath",
  "vein",
  "dash",
  "taste",
  "spot",
  "drop",
  "dab",
  "pinch",
  "speck",
  "smack",
  "smattering",
  "sprinkling",
  "splash",
  "soupçon",
  "small amount",
  "detail",
  "feature",
  "nicety",
  "addition",
  "accessory",
  "minutiae",
  "fine point",
  "skill",
  "skillfulness",
  "expertise",
  "dexterity",
  "deftness",
  "virtuosity",
  "adroitness",
  "adeptness",
  "ability",
  "talent",
  "flair",
  "facility",
  "proficiency",
  "knack",
  "technique",
  "approach",
  "style",
  "manner",
  "execution",
  "method",
  "feel",
  "craftsmanship",
  "workmanship",
  "artistry",
  "performance",
  "influence",
  "effect",
  "hand",
  "handling",
  "direction",
  "management",
  "talent",
  "flair",
  "aptitude",
  "facility",
  "knack",
  "technique",
  "bent",
  "ability",
  "expertise",
  "capacity",
  "capability",
  "power",
  "faculty",
  "endowment",
  "strength",
  "strong point",
  "forte",
  "genius",
  "brilliance",
  "dexterity",
  "adroitness",
  "skill",
  "cleverness",
  "virtuosity",
  "artistry",
];
