export const definitions = [
  '"an accidental toot from the saxophonist"',
  '"the blue van\'s familiar toots"',
  '"he still likes a toot"',
  '"you won\'t have me to supply you with free toot"',
  '"a sales manager on a toot"',
  '"behind us an impatient driver tooted a horn"',
  '"a car tooted at us"',
  '"the drawbacks of tooting cocaine"',
];
export const synonyms = [
  "blast",
  "blare",
  "sound",
  "beep",
  "meep",
  "honk",
  "debauch",
  "bacchanal",
  "bacchanalia",
  "wassail",
  "fuddle",
  "potation",
  "drinking bout",
  "operate",
  "set off",
  "play",
  "blow",
  "blast",
  "blare",
  "ring",
  "chime",
  "peal",
  "toll",
  "ding",
  "clang",
  "wind",
];
