export const definitions = [
  '"she toppled over when I touched her"',
  '"disagreement had threatened to topple the government"',
  '"the push almost toppled him to the ground"',
];
export const synonyms = [
  "fall",
  "tumble",
  "overturn",
  "overbalance",
  "tip",
  "keel",
  "drop",
  "pitch",
  "plunge",
  "capsize",
  "collapse",
  "founder",
  "plummet",
  "dive",
  "knock over",
  "knock down",
  "upset",
  "push over",
  "upend",
  "fell",
  "tear down",
  "flatten",
  "level",
  "lose one's balance",
  "go head over heels",
  "tip over",
  "overthrow",
  "oust",
  "depose",
  "unseat",
  "overturn",
  "bring down",
  "overcome",
  "defeat",
  "get rid of",
  "dislodge",
  "eject",
  "supplant",
  "dethrone",
  "bring low",
];
