export const definitions = [
  '"the torrid heat of the afternoon"',
  '"a torrid love affair"',
  '"Wall Street is in for a torrid time in the next few weeks"',
];
export const synonyms = [
  "hot",
  "sweltering",
  "sultry",
  "scorching",
  "boiling",
  "parching",
  "sizzling",
  "roasting",
  "blazing",
  "burning",
  "blistering",
  "tropical",
  "stifling",
  "suffocating",
  "oppressive",
  "dry",
  "arid",
  "barren",
  "parched",
  "waterless",
  "desert",
  "cold",
  "cool",
  "wet",
  "passionate",
  "impassioned",
  "ardent",
  "intense",
  "inflamed",
  "fervent",
  "fervid",
  "lustful",
  "amorous",
  "erotic",
  "sexy",
  "passionless",
  "unemotional",
];
