export const definitions = [
  '"I walked toward the front door"',
  '"an irresistible move toward freedom"',
  '"toward the end of April"',
  '"he was warm and tender toward her"',
  '"our attitude toward death"',
  '"the council provided a grant toward the cost of new buses"',
  '"is something new toward?"',
];
export const synonyms = [
  'to',
  'in the direction of',
  'so as to approach',
  'so as to near',
  'on the way to',
  'on the road to',
  'en route for',
  'in the vicinity of',
  'away from',
  'for',
  'with the aim of',
  'in order to obtain',
  'in order to achieve',
  'so as to achieve',
  'away from',
  'near',
  'nearing',
  'around',
  'approaching',
  'close to',
  'not quite',
  'just before',
  'shortly before',
  'coming to',
  'getting on for',
  'with regard to',
  'as regards',
  'regarding',
  'respecting',
  'in relation to',
  'concerning',
  'about',
  'in connection with',
  'apropos',
  'in/with regard to',
  'in/with respect to',
  'for',
  'supporting',
  'promoting',
  'assisting',
  'as a contribution to',
  'as a help to',
  'to help',
  'to assist',
];