export const definitions = [
  '"she toweled her hair dry"',
  '"we\'d towel off and dress for dinner"',
];
export const synonyms = [
  'rag',
  'dishcloth',
  'floorcloth',
  'wipe',
  'sponge',
  'duster',
  'facecloth',
  'paper towel',
  'tablecloth',
  'flannel',
  'tea towel',
  'washcloth',
  'washrag',
  'washer',
  'tea cloth',
  'J-cloth',
  'towel-dry',
  'rub',
  'mop up',
  'soak up',
  'absorb',
  'clean up',
  'drain',
  'dry off',
  'blot up',
  'sop up',
];