export const definitions = [
  '"he was cured of the disease"',
  '"centuries of science have not cured us of our superstitions"',
  '"this technology could be used to cure diabetes"',
  '"stopping foreign investment is no way to cure the fundamental problem"',
  '"home-cured ham"',
  '"some farmers cured their own bacon"',
  '"the early synthetic rubbers were much more difficult to cure than natural rubber"',
  '"the mastic takes days to cure"',
];
export const synonyms = [
  'heal',
  'restore',
  'rehabilitate',
  'cleanse',
  'restore to health',
  'make well',
  'make better',
  'treat successfully',
  'rectify',
  'remedy',
  'right',
  'fix',
  'mend',
  'repair',
  'heal',
  'ameliorate',
  'alleviate',
  'ease',
  'solve',
  'sort out',
  'eliminate',
  'do away with',
  'end',
  'put an end to',
  'remove',
  'counteract',
  'correct',
  'put right',
  'set right',
  'set to rights',
  'make better',
  'be the answer/solution to',
  'exacerbate',
  'aggravate',
  'preserve',
  'smoke',
  'salt',
  'dry',
  'kipper',
  'pickle',
];