export const definitions = [
  '"she\'d put a curse on him"',
  '"impatience is the curse of our day and age"',
  '"his mouth was spitting vile oaths and curses"',
  '"it often seemed as if the family had been cursed"',
  '"many owners have been cursed with a series of bankruptcies"',
  '"he cursed loudly as he burned his hand"',
  '"drivers were cursing and sounding their horns"',
  '"I cursed myself for my carelessness"',
  '"I toss in sweaty discomfort and curse the lack of air conditioning"',
];
export const synonyms = [
  "malediction",
  "the evil eye",
  "imprecation",
  "execration",
  "voodoo",
  "hoodoo",
  "anathema",
  "excommunication",
  "hex",
  "cess",
  "malison",
  "ban",
  "evil",
  "blight",
  "scourge",
  "plague",
  "cancer",
  "canker",
  "poison",
  "affliction",
  "burden",
  "bane",
  "misfortune",
  "misery",
  "ordeal",
  "trial",
  "tribulation",
  "torment",
  "trouble",
  "problem",
  "cross to bear",
  "bitter pill",
  "blessing",
  "advantage",
  "swear word",
  "expletive",
  "oath",
  "profanity",
  "four-letter word",
  "dirty word",
  "obscenity",
  "imprecation",
  "blasphemy",
  "vulgarism",
  "vulgarity",
  "swearing",
  "strong language",
  "bad/foul language",
  "execrate",
  "imprecate",
  "hoodoo",
  "anathematize",
  "excommunicate",
  "damn",
  "hex",
  "accurse",
  "put a curse on",
  "put the evil eye on",
  "be afflicted with",
  "be troubled by",
  "be plagued with",
  "suffer from",
  "be burdened with",
  "be blighted with",
  "be bedeviled by",
  "be blessed with",
  "swear",
  "blaspheme",
  "swear like a trooper",
  "damn",
  "execrate",
  "utter profanities",
  "utter oaths",
  "use bad/foul language",
  "be foul-mouthed",
  "be blasphemous",
  "take the Lord's name in vain",
  "revile",
  "attack",
  "upbraid",
  "berate",
  "harangue",
  "lambaste",
  "reprimand",
  "castigate",
  "chastise",
  "rebuke",
  "scold",
  "chide",
  "censure",
  "condemn",
  "damn",
  "denounce",
  "run down",
  "vilify",
  "denigrate",
  "calumniate",
  "insult",
  "abuse",
  "slander",
  "smear",
  "contemn",
  "asperse",
  "excoriate",
  "vilipend",
  "rail against",
  "inveigh against",
  "fulminate against",
  "find fault with",
  "take to task",
  "praise",
];
