export const definitions = ['"his reply was curt"'];
export const synonyms = [
  "terse",
  "brusque",
  "abrupt",
  "clipped",
  "blunt",
  "short",
  "monosyllabic",
  "summary",
  "snappy",
  "snappish",
  "sharp",
  "crisp",
  "tart",
  "gruff",
  "offhand",
  "unceremonious",
  "ungracious",
  "rude",
  "impolite",
  "discourteous",
  "uncivil",
  "laconic",
  "brief",
  "succinct",
  "compact",
  "pithy",
  "to the point",
  "economical",
  "dusty",
  "polite",
  "expansive",
];
