export const definitions = [
  '"a horse and cart"',
  '"from the product page select the size and quantity you\'d like and click ‘Buy’ to add it to your cart"',
  '"the produce was packed in crates and carted to Kansas City"',
  '"they carted the piano down three flights of stairs"',
  '"they were carted off to the nearest police station"',
  '"some fans were carted away by security"',
  '"my mother carted us around from one activity to another"',
];
export const synonyms = [
  "wagon",
  "carriage",
  "wain",
  "handcart",
  "pushcart",
  "barrow",
  "wheelbarrow",
  "trolley",
  "transport",
  "convey",
  "haul",
  "transfer",
  "move",
  "conduct",
  "transmit",
  "shift",
  "fetch",
  "take",
  "ferry",
  "carry",
  "lug",
  "tote",
  "heave",
  "heft",
  "drag",
  "lift",
  "raise",
  "heave",
  "hoist",
  "haul",
  "manhandle",
  "carry",
  "lug",
  "tote",
  "upheave",
  "lift up",
  "raise up",
  "put down",
  "take away",
  "carry away",
  "move",
  "shift",
  "convey",
  "transport",
  "confiscate",
  "take possession of",
  "replace",
  "put back",
];
