export const definitions = [
  '"birds with long curved bills"',
  '"her mouth curved in a smile"',
  '"starting with arms outstretched, curve the body sideways"',
];
export const synonyms = [
  "bend",
  "turn",
  "loop",
  "wind",
  "meander",
  "undulate",
  "snake",
  "spiral",
  "twist",
  "coil",
  "curl",
  "arc",
  "arch",
  "bow",
  "bulge",
  "swell",
  "inflect",
  "incurve",
  "bent",
  "arched",
  "bowed",
  "crescent",
  "curving",
  "recurved",
  "wavy",
  "twisted",
  "twisty",
  "sinuous",
  "serpentine",
  "meandering",
  "undulating",
  "curvilinear",
  "curvy",
  "vaulted",
  "rounded",
  "concave",
  "convex",
  "domed",
  "humped",
  "hooked",
  "aquiline",
  "arcuate",
  "falcate",
  "falciform",
  "circumflex",
  "flexural",
  "embowed",
  "curviform",
  "straight",
];
