export const definitions = [
  '"those on the cusp of adulthood"',
  '"he was Aries on the cusp with Taurus"',
];
export const synonyms = [
  "corner",
  "intersection",
  "point",
  "apex",
  "nook",
  "niche",
  "recess",
  "crook",
  "projection",
  "bend",
  "curve",
  "arc",
  "kink",
  "dogleg",
  "crook",
  "deviation",
  "turn",
  "turning",
  "junction",
  "fork",
  "intersection",
  "angle",
  "projection",
  "apex",
  "hairpin",
  "hairpin bend",
];
