export const definitions = [
  '"the cutoff date to register is July 2"',
  '"a cutoff valve"',
  '"a cutoff T-shirt"',
  '"aid to the cutoff troops in the north"',
  '"1 p.m. is the cutoff for being out of the woods"',
  '"a cutoff of aid would be a disaster"',
  '"a cutoff frequency of 8 Hz"',
];
export const synonyms = [
  'isolated',
  'remote',
  'out of the way',
  'outlying',
  'lonely',
  'off the map',
  'godforsaken',
  'obscure',
  'inaccessible',
  'unreachable',
  'faraway',
  'far-flung',
  'secluded',
  'hidden',
  'concealed',
  'private',
  'unfrequented',
  'unvisited',
  'undisturbed',
  'sequestered',
  'desolate',
  'lonesome',
  'lone',
  'unapproachable',
  'off the beaten track',
  'in the depths of …',
  'hard to find',
  'in the back of beyond',
  'in the hinterlands',
  'in the middle of nowhere',
  'tucked away',
  'in the backwoods',
  'in the backveld',
  'in the platteland',
  'in the backblocks',
  'in the booay',
  'accessible',
  'busy',
  'interruption',
  'interval',
  'gap',
  'hiatus',
  'lacuna',
  'discontinuation',
  'discontinuance',
  'discontinuity',
  'suspension',
  'disruption',
  'stop',
  'stoppage',
  'cessation',
  'caesura',
  'surcease',
  'lapse of time',
];