export const definitions = [
  '"an ______ battle"',
  '"an intrepid ______ adventurer"',
  '"______ bombardment of civilian targets"',
  '"______ photography"',
  '"knobby sections of ______ roots"',
  '"the more ______ and terrestrial birds are less dependent on a strictly aquatic habitat"',
  '"jiggle the ______ on the radio"',
];
export const synonyms = [
  "raised",
  "upraised",
  "uplifted",
  "high up",
  "aloft",
  "overhead",
  "hoisted",
  "lifted up",
  "flagpole",
  "flagstaff",
  "pole",
  "post",
  "rod",
  "support",
  "upright",
  "transmitter",
  "pylon",
];
