export const definitions = [
  '"quaint country cottages"',
  '"a quaint old custom"',
];
export const synonyms = [
  "picturesque",
  "charming",
  "sweet",
  "attractive",
  "old-fashioned",
  "old-world",
  "cunning",
  "olde",
  "unusual",
  "different",
  "out of the ordinary",
  "out of the way",
  "unfamiliar",
  "curious",
  "eccentric",
  "quirky",
  "bizarre",
  "zany",
  "whimsical",
  "fanciful",
  "idiosyncratic",
  "unconventional",
  "outlandish",
  "offbeat",
  "off-center",
  "outré",
  "pleasantly old-fashioned",
  "toytown",
  "olde worlde",
  "modern",
  "ugly",
  "normal",
  "ordinary",
];
