export const definitions = ['"she quailed at his heartless words"'];
export const synonyms = [
  "cower",
  "cringe",
  "waver",
  "falter",
  "flinch",
  "shrink",
  "recoil",
  "start",
  "pull back",
  "back away",
  "draw back",
  "shudder",
  "shiver",
  "tremble",
  "shake",
  "quake",
  "blench",
  "blanch",
  "get cold feet",
  "shy (away)",
];
