export const definitions = [
  '"the court must determine the quantum of compensation due"',
  '"each man has only a quantum of compassion"',
];
export const synonyms = [
  "amount",
  "proportion",
  "quantity",
  "bulk",
  "total",
  "quota",
  "portion",
  "part",
  "division",
  "bit",
  "quota",
  "allowance",
  "ration",
  "allocation",
  "allotment",
  "lot",
  "measure",
  "due",
  "percentage",
  "commission",
  "dividend",
  "stake",
  "interest",
  "equity",
  "helping",
  "serving",
  "apportionment",
  "moiety",
];
