export const definitions = [
  '"his voice quavered with rage"',
  '"\"I\'m not safe here, am I ?\" she said in a quavering voice"',
  '"it was impossible to hide the slight quaver in her voice"',
];
export const synonyms = [
  'tremble',
  'quiver',
  'shake',
  'flutter',
  'vibrate',
  'pulsate',
  'oscillate',
  'fluctuate',
  'waver',
  'ripple',
  'falter',
  'trill',
  'twitter',
  'warble',
  'trembling',
  'shaking',
  'shakiness',
  'tremble',
  'shake',
  'quivering',
  'quiver',
  'twitching',
  'twitch',
  'convulsion',
  'vibration',
  'juddering',
  'judder',
  'quavering',
  'tic',
  'steadiness',
];