export const definitions = [
  '"in the war they had queued for food"',
  '"companies are queuing up to move to the bay"',
  '"input or output requests to a file are queued by the operating system"',
];
export const synonyms = [
  'line',
  'row',
  'column',
  'file',
  'chain',
  'string',
  'stream',
  'procession',
  'train',
  'succession',
  'progression',
  'cavalcade',
  'sequence',
  'series',
  'waiting list',
  'breadline',
  'wait list',
  'backup',
  'traffic jam',
  'jam',
  'tailback',
  'gridlock',
  'reserve list',
  'waiting line',
  'line up',
  'fall in',
  'file',
  'form lines',
  'get into rows/columns',
  'walk/move in line',
  'stand in a queue',
  'form a queue',
  'queue up',
  'wait in line',
  'form a line',
];