export const definitions = [
  '"the tree\'s branches stopped quivering"',
  '"the bird runs along in a zigzag path, quivering its wings"',
  '"Meredith felt a quiver of fear"',
  '"he had created a whole new quiver of boards specifically for Hawaii"',
];
export const synonyms = [
  "tremble",
  "shake",
  "shiver",
  "quaver",
  "quake",
  "shudder",
  "convulse",
  "flutter",
  "agitate",
  "vibrate",
  "flap",
  "beat",
  "tremor",
  "tremble",
  "shake",
  "shaking",
  "shakiness",
  "shiver",
  "frisson",
  "chill",
  "vibration",
  "quaver",
  "quake",
  "shudder",
  "flutter",
  "oscillation",
  "fluctuation",
  "waver",
  "ripple",
  "falter",
];
