export const definitions = [
  '"one of Italy\'s most beautiful cities"',
  '"the city council"',
  '"panic city"',
  '"a City analyst"',
];
export const synonyms = [
  "town",
  "municipality",
  "metropolis",
  "megalopolis",
  "conurbation",
  "burgh",
  "wen",
  "urban area",
  "metropolitan area",
  "town",
  "municipality",
  "metropolis",
  "megalopolis",
  "conurbation",
  "burgh",
  "wen",
  "urban area",
  "metropolitan area",
];
