export const definitions = [
  '"authors who are highly regarded by their peers tend to be cited"',
  '"he does not cite any source for this assertion"',
  '"medics have been cited as a key example of a modern breed of technical expert"',
  '"he has been cited many times for his contributions in the intelligence area"',
  '"the summons cited four of the defendants"',
];
export const synonyms = [
  "quote",
  "reproduce",
  "mention",
  "adduce",
  "instance",
  "point to",
  "specify",
  "name",
  "bring up",
  "advance",
  "invoke",
  "refer to",
  "make reference to",
  "allude to",
  "give as an example",
  "draw attention to",
  "mention",
  "adduce",
  "instance",
  "point to",
  "specify",
  "name",
  "bring up",
  "advance",
  "invoke",
  "refer to",
  "make reference to",
  "allude to",
  "give as an example",
  "draw attention to",
  "commend",
  "praise",
  "recognize",
  "pay tribute to",
  "give recognition to",
  "summon",
  "summons",
  "subpoena",
  "call",
  "serve with a summons",
  "serve with a writ",
];
