export const definitions = [
  '"there is no need to be unduly alarmed"',
];
export const synonyms = [
  'excessively',
  'immoderately',
  'intemperately',
  'disproportionately',
  'inordinately',
  'superfluously',
  'too',
  'overly',
  'overmuch',
  'unnecessarily',
  'needlessly',
  'unwarrantedly',
  'unjustifiably',
  'unreasonably',
  'inappropriately',
  'unsuitably',
  'improperly',
  'ill-advisedly',
  'out of all proportion',
  'duly',
  'appropriately',
];