export const definitions = [
  '"this discovery was unique in history"',
  '"original and unique designs"',
  '"a style of architecture that is unique to Portugal"',
  '"a unique opportunity to see the spectacular Bolshoi Ballet"',
  '"some of Lamb\'s writings were so memorably beautiful as to be uniques in their class"',
];
export const synonyms = [
  "distinctive",
  "individual",
  "special",
  "especial",
  "idiosyncratic",
  "quirky",
  "eccentric",
  "isolated",
  "single",
  "sole",
  "lone",
  "unrepeated",
  "unrepeatable",
  "solitary",
  "exclusive",
  "only",
  "one and only",
  "rare",
  "uncommon",
  "unusual",
  "peculiar",
  "novel",
  "strange",
  "odd",
  "sui generis",
  "in a class by itself",
  "common",
  "ordinary",
  "peculiar",
  "specific",
  "particular",
  "found only in",
  "characteristic of",
  "typical of",
  "remarkable",
  "special",
  "singular",
  "noteworthy",
  "notable",
  "signal",
  "outstanding",
  "extraordinary",
  "unequaled",
  "unparalleled",
  "unmatched",
  "matchless",
  "peerless",
  "nonpareil",
  "unsurpassed",
  "unexcelled",
  "incomparable",
  "beyond compare",
  "superior",
  "inimitable",
  "second to none",
  "unexampled",
  "without equal",
  "unremarkable",
];
