export const definitions = [
  '"women acting together in a united way"',
  '"Oxford United"',
  '"he called on the party to unite"',
  '"they are united by their love of cars"',
  '"the two Germanys officially united"',
  '"his work unites theory and practice"',
  '"he aimed to unite Italy and Sicily under his imperial crown"',
  '"Lady Midlothian united herself to a man of bad character"',
];
export const synonyms = [
  'unified',
  'integrated',
  'consolidated',
  'amalgamated',
  'joined',
  'merged',
  'federal',
  'federated',
  'confederate',
  'common',
  'shared',
  'joint',
  'combined',
  'corporate',
  'mutual',
  'communal',
  'allied',
  'cooperative',
  'collective',
  'collaborative',
  'aggregate',
  'undivided',
  'solid',
  'consistent',
  'concerted',
  'pooled',
  'cross-party',
  'agreed',
  'of like mind',
  'like-minded',
  'at one',
  'unanimous',
  'in sympathy',
  'shoulder to shoulder',
  'banded together',
  'in agreement',
  'in unison',
  'of the same opinion',
  'of the same mind',
  'as one',
  'in accord',
  'in concord',
  'in rapport',
  'in harmony',
  'in unity',
  'divided',
  'separated',
  'different',
  'disagreeing',
  'differing',
  'unify',
  'join',
  'link',
  'connect',
  'combine',
  'amalgamate',
  'fuse',
  'integrate',
  'weld',
  'bond',
  'stick together',
  'glue',
  'cement',
  'coalesce',
  'join forces',
  'associate',
  'ally',
  'cooperate',
  'collaborate',
  'pull together',
  'get together',
  'bring together',
  'knit together',
  'join together',
  'band together',
  'club together',
  'work together',
  'act together',
  'team up',
  'go into partnership',
  'work side by side',
  'pool resources',
  'divide',
  'separate',
  'split',
  'unify',
  'join',
  'link',
  'connect',
  'combine',
  'amalgamate',
  'fuse',
  'integrate',
  'weld',
  'bond',
  'stick together',
  'glue',
  'cement',
  'coalesce',
  'join forces',
  'associate',
  'ally',
  'cooperate',
  'collaborate',
  'pull together',
  'get together',
  'bring together',
  'knit together',
  'join together',
  'band together',
  'club together',
  'work together',
  'act together',
  'team up',
  'go into partnership',
  'work side by side',
  'pool resources',
  'divide',
  'separate',
  'split',
];