export const definitions = ['"they were unwashed and unkempt"'];
export const synonyms = [
  "untidy",
  "messy",
  "scruffy",
  "disordered",
  "disheveled",
  "disarranged",
  "rumpled",
  "windblown",
  "bedraggled",
  "shabby",
  "slovenly",
  "shaggy",
  "tousled",
  "uncombed",
  "knotted",
  "matted",
  "ungroomed",
  "in a mess",
  "messed up",
  "tidy",
  "neat",
];
