export const definitions = [
  '"a large house not unlike Mr. Shaw\'s"',
  '"they were unlike anything ever seen before"',
  '"unlike Helen, he was not superstitious"',
  '"he sounded irritable, which was unlike him"',
  '"they seemed utterly unlike, despite being twins"',
  '"he was very unlike to any other man"',
  '"the article suggests that his character was unliked by many"',
  '"I cut about 300 of my 400 friends and unliked about 20–30 pages"',
];
export const synonyms = [
  'unalike',
  'far from',
  'as opposed to',
  'different from',
  'dissimilar to',
  'not like',
  'not similar to',
  'not resembling',
  'far apart from',
  'distant from',
  'in contrast to/with',
  'differently from',
  'in contradistinction to',
  'not typical of',
  'uncharacteristic of',
  'like',
  'similar to',
  'similarly to',
  'dissimilar',
  'unalike',
  'disparate',
  'contrastive',
  'contrasting',
  'contrasted',
  'contrary',
  'antithetical',
  'different',
  'distinct',
  'diverse',
  'heterogeneous',
  'divergent',
  'distinguishable',
  'incompatible',
  'inconsistent',
  'opposed',
  'varying',
  'variant',
  'at odds',
  'clashing',
  'conflicting',
  'discrepant',
  'ill-matched',
  'incongruous',
  'nonidentical',
  'at variance',
  'like',
  'identical',
];