export const definitions = [
  '"thieves caused untold damage"',
  '"no event, however boring, is left untold"',
];
export const synonyms = [
  "boundless",
  "measureless",
  "limitless",
  "without limit",
  "unlimited",
  "unbounded",
  "immense",
  "vast",
  "great",
  "endless",
  "unending",
  "never-ending",
  "without end",
  "inexhaustible",
  "infinite",
  "interminable",
  "unceasing",
  "everlasting",
  "immeasurable",
  "incalculable",
  "countless",
  "innumerable",
  "numberless",
  "without number",
  "uncountable",
  "uncounted",
  "numerous",
  "many",
  "multiple",
  "manifold",
  "legion",
  "multitudinous",
  "myriad",
  "unnumbered",
  "an infinite number of",
  "an incalculable number of",
  "more than one can count",
  "too many to be counted",
  "unnumberable",
  "innumerous",
  "unsummed",
  "limited",
  "unreported",
  "unrelated",
  "unrevealed",
  "undisclosed",
  "unpublished",
  "secret",
  "suppressed",
  "unmentioned",
  "unstated",
  "unspoken",
  "unrecounted",
  "undivulged",
  "unnarrated",
];
