export const definitions = [
  '"the mayor unveiled a plaque"',
  '"the manufacturer unveiled plans for expanding into aviation"',
];
export const synonyms = [
  "reveal",
  "present",
  "disclose",
  "divulge",
  "air",
  "communicate",
  "publish",
  "broadcast",
  "display",
  "show",
  "exhibit",
  "demonstrate",
  "parade",
  "flaunt",
  "release",
  "bring out",
  "launch",
  "introduce",
  "make known",
  "make public",
  "put on show",
  "put on display",
  "put on view",
  "expose to view",
];
