export const definitions = [
  '"Ella unwound the long woolen scarf from her neck"',
  '"the net unwinds from the reel"',
  '"the Grand Hotel is a superb place to unwind"',
  '"the hedge funds were forced to unwind their short positions"',
];
export const synonyms = [
  'unroll',
  'uncoil',
  'unreel',
  'undo',
  'unravel',
  'untwine',
  'untwist',
  'disentangle',
  'unfurl',
  'lay out',
  'unkink',
  'spread out',
  'open (out)',
  'straighten (out)',
  'relax',
  'loosen up',
  'let up',
  'slow down',
  'de-stress',
  'unbend',
  'rest',
  'repose',
  'laze',
  'idle',
  'loaf',
  'do nothing',
  'sit back',
  'stand down',
  'lounge',
  'loll',
  'slump',
  'flop',
  'put one\'s feet up',
  'take it easy',
  'luxuriate',
  'play',
  'ease up/off',
  'take time off',
  'slack off',
  'be at leisure',
  'take one\'s leisure',
  'take \'s \'s ease',
  'enjoy oneself',
  'amuse oneself',
  'entertain oneself',
];