export const definitions = [
  '"he will waive all rights to the money"',
  '"her tuition fees would be waived"',
];
export const synonyms = [
  "relinquish",
  "renounce",
  "give up",
  "abandon",
  "reject",
  "surrender",
  "yield",
  "cede",
  "do without",
  "abdicate",
  "abjure",
  "sacrifice",
  "refuse",
  "turn down",
  "spurn",
  "sign away",
  "dispense with",
  "set/put aside",
  "claim",
  "pursue",
  "disregard",
  "ignore",
  "overlook",
  "set aside",
  "forgo",
  "drop",
  "omit",
  "cast aside",
  "brush aside",
  "uphold",
  "follow",
];
