export const definitions = [
  '"sheer wanton vandalism"',
  '"her cheeks burned as she recalled how forward she had been, how wanton"',
  '"where wanton ivy twines"',
  '"a wanton fawn"',
  '"she\'d behaved like a wanton"',
  '"they sat gazing at the white-flecked pure blue sea and the various gulls that wantoned in the wake"',
  '"women who have wantoned with suitors"',
];
export const synonyms = [
  "deliberate",
  "willful",
  "malicious",
  "malevolent",
  "spiteful",
  "vicious",
  "wicked",
  "evil",
  "cruel",
  "unprovoked",
  "unmotivated",
  "motiveless",
  "arbitrary",
  "groundless",
  "unjustifiable",
  "unjustified",
  "needless",
  "unnecessary",
  "gratuitous",
  "senseless",
  "pointless",
  "purposeless",
  "aimless",
  "useless",
  "meaningless",
  "empty",
  "vacuous",
  "uncalled for",
  "justifiable",
  "licentious",
  "promiscuous",
  "immoral",
  "immodest",
  "indecent",
  "shameless",
  "unblushing",
  "unchaste",
  "unvirtuous",
  "impure",
  "abandoned",
  "lustful",
  "lecherous",
  "lascivious",
  "salacious",
  "lubricious",
  "libidinous",
  "libertine",
  "profligate",
  "dissolute",
  "dissipated",
  "debauched",
  "degenerate",
  "reprobate",
  "corrupt",
  "sinful",
  "loose",
  "fast",
  "of easy virtue",
  "chaste",
  "moral",
  "capricious",
  "playful",
  "frisky",
  "jolly",
  "fun-loving",
  "lively",
  "high-spirited",
  "spirited",
  "careless",
  "heedless",
  "impulsive",
  "impetuous",
  "rash",
  "reckless",
  "abandoned",
  "audacious",
  "cavalier",
  "devil-may-care",
  "happy-go-lucky",
  "frolicsome",
  "sportive",
  "full of life",
  "serious",
];
