export const definitions = [
  '"he waved to me from the train"',
  '"he waved a sheaf of papers in the air"',
  '"we waved our farewells"',
  '"she waved him goodbye"',
  '"he waved her back"',
  '"the flag waved in the wind"',
  '"her hair had been carefully waved for the evening"',
  '"she marveled at the blueness of his eyes, how straight his nose was, the way his hair waved"',
  '"he was swept out to sea by a freak wave"',
  '"gulls and cormorants bobbed on the waves"',
  '"a wave of treetops stretched to the horizon"',
  '"its remarkable how one small gesture can create a wave of kindness"',
  '"horror came over me in waves"',
  '"he gave a little wave and walked off"',
  '"his hair was drying in unruly waves"',
  '"her hair has a slight natural wave"',
];
export const synonyms = [
  "gesture",
  "gesticulate",
  "signal",
  "sign",
  "beckon",
  "indicate",
  "motion",
  "nod",
  "bid",
  "wag",
  "waggle",
  "swing",
  "shake",
  "swish",
  "sweep",
  "swipe",
  "brandish",
  "flourish",
  "flaunt",
  "wield",
  "flick",
  "flutter",
  "move to and fro",
  "move up and down",
  "ripple",
  "flutter",
  "undulate",
  "stir",
  "flap",
  "sway",
  "swing",
  "waft",
  "shake",
  "quiver",
  "oscillate",
  "move",
  "blow",
  "curl",
  "kink",
  "coil",
  "undulate",
  "crimp",
  "frizz",
  "frizzle",
  "breaker",
  "billow",
  "roller",
  "comber",
  "ripple",
  "swell",
  "surf",
  "froth",
  "bombora",
  "white horse",
  "white cap",
  "wavelet",
  "undulation",
  "ripplet",
  "ridge",
  "crease",
  "wrinkle",
  "ruffle",
  "pucker",
  "flow",
  "rush",
  "surge",
  "flood",
  "stream",
  "swell",
  "tide",
  "deluge",
  "torrent",
  "spate",
  "billow",
  "ripple",
  "spasm",
  "thrill",
  "frisson",
  "shiver",
  "tingle",
  "stab",
  "dart",
  "upsurge",
  "outbreak",
  "rash",
  "feeling",
  "welling up",
  "gesture",
  "gesticulation",
  "signal",
  "sign",
  "motion",
  "indication",
  "hand movement",
  "curl",
  "kink",
  "corkscrew",
  "crimp",
  "twist",
  "twirl",
  "ringlet",
  "frizz",
  "coil",
  "loop",
  "undulation",
  "curl",
  "kink",
  "corkscrew",
  "crimp",
  "twist",
  "twirl",
  "ringlet",
  "frizz",
  "coil",
  "loop",
  "undulation",
  "ripple",
  "vibration",
  "oscillation",
  "undulation",
];
