export const definitions = [
  '"acres of arable land"',
  '"open arable fields"',
  '"arable crops"',
  '"arable farming"',
  '"vast areas of arable and pasture"',
];
export const synonyms = [
  "fertile",
  "productive",
  "fecund",
  "fruitful",
  "lush",
  "barren",
  "farmable",
  "cultivable",
  "cultivatable",
  "plowable",
  "tillable",
  "fertile",
  "productive",
  "fruitful",
  "fecund",
  "lush",
  "infertile",
];
