export const definitions = [
  '"archers shoot 30 arrows each at the target"',
  '"arch observations about even the most mundane matters"',
];
export const synonyms = [
  "bowman",
  "knowing",
  "playful",
  "mischievous",
  "puckish",
  "roguish",
  "impish",
  "elfin",
  "devilish",
  "naughty",
  "wicked",
  "cheeky",
  "teasing",
  "saucy",
  "flippant",
  "tongue-in-cheek",
  "artful",
  "sly",
  "cunning",
  "affected",
  "frolicsome",
];
