export const definitions = [
  '"an ardent baseball fan"',
  '"an ardent suitor"',
  '"the ardent flames"',
];
export const synonyms = [
  "passionate",
  "avid",
  "impassioned",
  "fervent",
  "fervid",
  "zealous",
  "wholehearted",
  "eager",
  "vehement",
  "intense",
  "fierce",
  "fiery",
  "flaming",
  "emotional",
  "hot-blooded",
  "earnest",
  "sincere",
  "enthusiastic",
  "keen",
  "committed",
  "dedicated",
  "assiduous",
  "halfhearted",
  "white-hot",
  "red-hot",
  "burning",
  "fiery",
  "on fire",
  "blazing",
  "ablaze",
  "aflame",
  "glowing",
  "aglow",
  "radiant",
  "bright",
  "brilliant",
  "dazzling",
  "shining",
  "luminous",
  "gleaming",
  "fervid",
  "rutilant",
  "lucent",
  "candescent",
  "fervent",
  "intensely hot",
];
