export const definitions = [
  '"they felt the stirrings of revolutionary ardor"',
];
export const synonyms = [
  'passion',
  'avidity',
  'fervor',
  'zeal',
  'wholeheartedness',
  'eagerness',
  'vehemence',
  'intensity',
  'fierceness',
  'zest',
  'gusto',
  'energy',
  'animation',
  'fire',
  'fieriness',
  'emotion',
  'emotionalism',
  'feeling',
  'hot-bloodedness',
  'earnestness',
  'sincerity',
  'enthusiasm',
  'keenness',
  'dedication',
  'devotion',
  'assiduity',
  'readiness',
  'empressement',
];