export const definitions = [
  '"her artful wiles"',
  '"an artful photograph of a striking woman"',
];
export const synonyms = [
  "sly",
  "crafty",
  "cunning",
  "wily",
  "scheming",
  "devious",
  "Machiavellian",
  "sneaky",
  "guileful",
  "tricky",
  "conniving",
  "designing",
  "calculating",
  "shrewd",
  "astute",
  "sharp-witted",
  "sharp",
  "acute",
  "intelligent",
  "clever",
  "alert",
  "canny",
  "deceitful",
  "deceptive",
  "duplicitous",
  "cheating",
  "dishonest",
  "disingenuous",
  "underhand",
  "untrustworthy",
  "unscrupulous",
  "double-dealing",
  "vulpine",
  "carny",
  "subtle",
  "ingenuous",
  "honest",
  "dull",
];
