export const definitions = [
  '"a surgeon who is an artist with the scalpel"',
  '"a con ______"',
  '"rip-off ______"',
];

export const synonyms = [
  'creator',
  'originator',
  'designer',
  'producer',
  'old master',
  'begetter',
  'entertainer',
  'performer',
  'trouper',
  'showman',
  'player',
  'musician',
  'singer',
  'dancer',
  'actor',
  'actress',
  'thespian',
  'comic',
  'comedian',
  'comedienne',
  'clown',
  'impressionist',
  'conjuror',
  'magician',
  'acrobat',
  'star',
  'superstar',
  'executant',
  'expert',
  'master',
  'maestro',
  'past master',
  'adept',
  'virtuoso',
  'genius',
  'old hand',
  'proficient',
  'skilled person',
  'novice',
  'amateur',
];
