export const definitions = [
  '"Ginny glanced at her watch"',
  '"I glanced through your personnel file last night"',
  '"the stone glanced off a crag and hit Tom on the head"',
  '"sunlight glanced off the curved body of a dolphin"',
  '"he glanced the ball into the corner of the net"',
  '"I stole a glance at John"',
  '"fish … sporting with quick glance, Show to the Sun their wav\'d coats"',
  '"lead glance"',
];
export const synonyms = [
  'peek',
  'peep',
  'glimpse',
  'keek',
  'glance one\'s eye',
  'take a quick look',
  'look quickly',
  'look briefly',
  'catch a glimpse of',
  'gaze',
  'scrutinize',
  'scan',
  'skim',
  'leaf',
  'flick',
  'flip',
  'thumb',
  'browse',
  'read quickly',
  'have a quick look',
  'run one\'s eye over',
  'dip into',
  'study',
  'pore over',
  'ricochet',
  'rebound',
  'fly',
  'bounce',
  'graze',
  'clip',
  'cannon',
  'carom',
  'resile',
  'be deflected',
  'make contact with',
  'reflect',
  'flash',
  'gleam',
  'glint',
  'glitter',
  'glisten',
  'glimmer',
  'shimmer',
  'flicker',
  'sparkle',
  'twinkle',
  'coruscate',
  'peek',
  'peep',
  'glimpse',
  'keek',
  'coup d\'œil',
  'brief look',
  'quick look',
  'flash',
  'gleam',
  'glitter',
  'glint',
  'glimmer',
  'shimmer',
  'flicker',
  'sparkle',
  'twinkle',
];