export const definitions = [
  '"bookcases with glazed doors"',
  '"glazed shallots"',
  '"a large glazed urn"',
  '"she had a glazed look in her eyes"',
  '"windows can be glazed using laminated glass"',
  '"the verandas were glazed in"',
  '"new potatoes that had been glazed in mint-flavored butter"',
  '"the prospect makes my eyes glaze over with boredom"',
];
export const synonyms = [
  'varnish',
  'enamel',
  'lacquer',
  'japan',
  'shellac',
  'paint',
  'coat',
  'gloss',
  'cover',
  'ice',
  'frost',
  'make shiny',
  'become glassy',
  'grow expressionless',
  'go blank',
  'be motionless',
  'mist over',
  'film over',
];