export const definitions = [
  '"she was careful not to let the answer sound too glib"',
];
export const synonyms = [
  "slick",
  "pat",
  "neat",
  "plausible",
  "silky",
  "smooth-talking",
  "fast-talking",
  "smooth",
  "urbane",
  "smooth-tongued",
  "silver-tongued",
  "fluent",
  "voluble",
  "loquacious",
  "disingenuous",
  "insincere",
  "facile",
  "shallow",
  "superficial",
  "simplistic",
  "oversimplified",
  "easy",
  "ready",
  "flippant",
  "smooth-spoken",
  "having kissed the Blarney Stone",
  "sincere",
  "thoughtful",
  "inarticulate",
];
