export const definitions = [
  '"her glasses were glinting in the firelight"',
  '"his eyes glinted angrily"',
  '"the glint of gold in his teeth"',
  '"she saw the glint of excitement in his eyes"',
];
export const synonyms = [
  "shine",
  "gleam",
  "catch the light",
  "glitter",
  "sparkle",
  "twinkle",
  "blink",
  "wink",
  "glimmer",
  "shimmer",
  "glow",
  "flicker",
  "glisten",
  "flash",
  "glister",
  "coruscate",
  "scintillate",
  "fulgurate",
  "luminesce",
  "incandesce",
  "phosphoresce",
  "reflect light",
  "effulge",
  "glitter",
  "gleam",
  "sparkle",
  "twinkle",
  "blink",
  "wink",
  "glimmer",
  "flash",
  "glimmer",
  "flicker",
  "spark",
  "trace",
  "hint",
  "indication",
  "suggestion",
  "sign",
  "scintilla",
  "whisper",
];
