export const definitions = [
  '"a draft version was lost in a computer glitch"',
  '"this has been the first real glitch they\'ve encountered in a three months\' tour"',
  '"her job involves troubleshooting when systems glitch"',
];
export const synonyms = [
  'crash',
  'breakdown',
  'fault',
  'failure',
  'defect',
  'flaw',
  'collapse',
  'impairment',
  'problem',
  'difficulty',
  'issue',
  'hitch',
  'complication',
  'upset',
  'disappointment',
  'misfortune',
  'mishap',
  'reversal',
  'reverse',
  'blow',
  'body blow',
  'knock',
  'stumbling block',
  'hindrance',
  'impediment',
  'obstruction',
  'delay',
  'holdup',
  'check',
  'foil',
  'piece of bad luck',
  'unfortunate development',
  'reverse of fortune',
  'breakthrough',
  'step forward',
];