export const definitions = [
  '"the downturn in the global economy"',
  '"some students may prefer to be given a global picture of what is involved in the task"',
  '"global searches"',
];
export const synonyms = [
  'worldwide',
  'international',
  'world',
  'intercontinental',
  'universal',
  'national',
  'local',
  'comprehensive',
  'overall',
  'general',
  'all-inclusive',
  'all-encompassing',
  'encyclopedic',
  'universal',
  'exhaustive',
  'blanket',
  'broad',
  'wide-ranging',
  'far-reaching',
  'extensive',
  'sweeping',
  'cross-disciplinary',
  'interdisciplinary',
  'multidisciplinary',
  'partial',
  'restricted',
];