export const definitions = [
  '"rooms must be vacated by noon on the last day of your vacation"',
  '"he will vacate a job in government sales"',
  '"the Justices vacated a ruling by the federal appeals court"',
];
export const synonyms = [
  'leave',
  'get out of',
  'evacuate',
  'quit',
  'abandon',
  'desert',
  'relinquish',
  'forsake',
  'move out of',
  'go away from',
  'depart from',
  'exit from',
  'withdraw from',
  'pull out of',
  'occupy',
  'inhabit',
  'leave',
  'give up',
  'relinquish',
  'abdicate',
  'resign from',
  'stand down from',
  'bow out of',
  'depart from',
  'walk out on',
  'retire from',
  'take up',
  'annul',
  'invalidate',
  'nullify',
  'void',
  'revoke',
  'rescind',
  'retract',
  'countermand',
  'set aside',
  'take back',
  'withdraw',
  'recall',
  'repeal',
  'overrule',
  'override',
  'abrogate',
  'quash',
  'extinguish',
  'remit',
  'retire',
  'discharge',
  'negate',
  'declare null and void',
  'render null and void',
  'disannul',
];