export const definitions = [
  '"a valued friend"',
  '"his estate was valued at $45,000"',
  '"she had come to value her privacy and independence"',
];
export const synonyms = [
  "evaluate",
  "assess",
  "estimate",
  "appraise",
  "assay",
  "rate",
  "price",
  "put/set a price on",
  "cost (out)",
  "cherished",
  "treasured",
  "dear",
  "prized",
  "favorite",
  "precious",
  "special",
  "appreciated",
  "esteemed",
  "respected",
  "well thought of",
  "appreciate",
  "esteem",
  "respect",
  "admire",
  "prize",
  "cherish",
  "treasure",
  "worth its/one's weight in gold",
  "highly regarded",
  "rate (highly)",
  "hold in high esteem",
  "hold in high regard",
  "hold dear",
  "have a high opinion of",
  "think highly of",
  "think much of",
  "set (great) store by",
  "attach importance to",
];
