export const definitions = [
  '"it flattered his vanity to think I was in love with him"',
  '"the personal vanities and ambitions of politicians"',
  '"a vanity press"',
  '"the vanity of human wishes"',
];
export const synonyms = [
  "conceit",
  "conceitedness",
  "self-conceit",
  "narcissism",
  "self-love",
  "self-admiration",
  "self-regard",
  "self-absorption",
  "self-obsession",
  "self-centeredness",
  "egotism",
  "egoism",
  "egocentrism",
  "egomania",
  "pride",
  "haughtiness",
  "arrogance",
  "boastfulness",
  "swagger",
  "imperiousness",
  "cockiness",
  "pretension",
  "affectation",
  "airs",
  "show",
  "ostentation",
  "vainglory",
  "braggadocio",
  "modesty",
  "futility",
  "uselessness",
  "pointlessness",
  "worthlessness",
  "purposelessness",
  "idleness",
  "fruitlessness",
  "profitlessness",
];
