export const definitions = [
  '"a long and varied career"',
  '"a little effort to make life pleasant and varied"',
  '"the properties vary in price"',
  '"your skin\'s moisture content varies according to climatic conditions"',
  '"he tried to vary his diet"',
];
export const synonyms = [
  'diverse',
  'assorted',
  'diversified',
  'differing',
  'miscellaneous',
  'mixed',
  'motley',
  'sundry',
  'jumbled',
  'haphazard',
  'heterogeneous',
  'manifold',
  'wide-ranging',
  'disparate',
  'variegated',
  'multifarious',
  'uniform',
];