export const definitions = [
];
export const synonyms = [
  'attendant',
  'retainer',
  'domestic help',
  'domestic worker',
  'domestic',
  'help',
  'cleaner',
  'helper',
  'lackey',
  'flunkey',
  'minion',
  'maid',
  'housemaid',
  'maidservant',
  'lady\'s maid',
  'handmaid',
  'scullery maid',
  'girl',
  'footman',
  'page',
  'page boy',
  'valet',
  'butler',
  'man',
  'gentleman\'s gentleman',
  'batman',
  'manservant',
  'houseman',
  'houseboy',
  'boy',
  'housekeeper',
  'steward',
  'major domo',
  'coachman',
  'postilion',
  'equerry',
  'menial',
  'drudge',
  'hireling',
  'slave',
  'galley slave',
  'mozo',
  'bearer',
  'amah',
  'charwoman',
  'charlady',
  'char',
  'boots',
  'scout',
  'bedder',
  'gyp',
  'seneschal',
  'servitor',
  'scullion',
  'tweeny',
  'serving man',
  'serving woman',
  'turnspit',
  'vassal',
  'serf',
  'famulus',
  'cleaning woman/lady',
  'parlor maid',
  'serving maid',
  'maid-of-all-work',
  'hired help',
  'chokra',
  'bai',
  'jong',
  'abigail',
  'serving wench',
  'master',
  'mistress',
  'rogue',
  'rascal',
  'scoundrel',
  'good-for-nothing',
  'villain',
  'wretch',
  'rake',
  'profligate',
  'degenerate',
  'debauchee',
  'libertine',
  'troublemaker',
  'mischief-maker',
  'wrongdoer',
  'evil-doer',
  'transgressor',
  'sinner',
  'roué',
  'cad',
  'ne\'er -do -well',
  'miscreant',
  'blackguard',
  'knave',
  'rapscallion',
  'wastrel',
  'scapegrace',
  'unprincipled person',
  'vaurien',
  'rakehell',
];