export const definitions = [
  '"a much stronger nation can also turn a weaker one into a vassal state"',
];
export const synonyms = [
  "villein",
  "liege",
  "liegeman",
  "man",
  "bondsman",
  "vavasour",
  "serf",
  "helot",
  "slave",
  "thrall",
  "subject",
  "freeman",
  "lord",
  "subordinate",
  "inferior",
  "deputy",
  "junior",
  "assistant",
  "adjutant",
  "aide",
  "minion",
  "lackey",
  "flunkey",
  "menial",
  "retainer",
  "subject",
  "serf",
  "hireling",
  "servant",
  "henchman",
  "myrmidon",
  "factotum",
  "stooge",
  "follower",
  "camp follower",
  "hanger-on",
  "disciple",
  "scullion",
  "servitor",
  "right-hand man/woman",
  "girl/man Friday",
  "boss",
  "leader",
];
