export const definitions = [
  '"I was amazed that he could remember me"',
  '"he was amazed at how modern everything was"',
  '"Chandler looked absolutely amazed"',
  '"she shook her head in amazed disbelief"',
  '"she amazed doctors by fighting back when her deteriorating condition caused her to suffer heart failure"',
  '"he has been amazed by the quality of the employees at the bank"',
];
export const synonyms = [
  "astonished",
  "astounded",
  "staggered",
  "surprised",
  "startled",
  "stunned",
  "thunderstruck",
  "aghast",
  "confounded",
  "dumbfounded",
  "stupefied",
  "dazed",
  "nonplussed",
  "dumbstruck",
  "open-mouthed",
  "agape",
  "speechless",
  "wide-eyed",
  "awed",
  "awestruck",
  "wonderstruck",
  "shaken",
  "unnerved",
  "disconcerted",
  "discomposed",
  "bewildered",
  "bemused",
  "taken aback",
  "lost for words",
  "at a loss for words",
  "filled with astonishment",
  "filled with amazement",
  "filled with awe",
  "filled with wonder",
  "shaken up",
  "astonish",
  "astound",
  "surprise",
  "bewilder",
  "stun",
  "stagger",
  "flabbergast",
  "nonplus",
  "shock",
  "startle",
  "shake",
  "stupefy",
  "take someone's breath away",
  "dumbfound",
  "daze",
  "benumb",
  "perplex",
  "confound",
  "dismay",
  "disconcert",
  "shatter",
  "jolt",
  "shake up",
  "stop someone in their tracks",
  "leave open-mouthed",
  "leave aghast",
  "take aback",
];
