export const definitions = [
  '"try to make ______ for the rude way you spoke to Lucy"',
  '"the plaintiff cannot succeed if the defendant proves that an offer of ______ was made in good time"',
  '"the rule was _____ed to apply only to nonmembers"',
  '"did she _____ her original will later on?"',
  '"pressuring Panama to _____ its banking laws"',
  '"if you can _____ or alter people\'s mindset"',
  '"a few things had gone wrong, but these had been _____ed"',
];
export const synonyms = [
  'compensation',
  'recompense',
  'reparation',
  'restitution',
  'restoration',
  'redress',
  'indemnity',
  'indemnification',
  'atonement',
  'expiation',
  'requital',
  'make up for',
  'make good',
  'expiate',
  'redress the balance',
  'compensate',
  'indemnify',
  'repay',
  'reimburse',
  'pay back',
  'atone for',
  'do penance for',
  'pay the price for',
  'redeem oneself',
  'make it up to',
  'revise',
  'alter',
  'change',
  'modify',
  'qualify',
  'adapt',
  'adjust',
  'edit',
  'copyedit',
  'rewrite',
  'rescript',
  'redraft',
  'recast',
  'rephrase',
  'reword',
  'rework',
  'reform',
  'update',
  'revamp',
  'correct',
  'remedy',
  'fix',
  'repair',
  'emend',
  'improve',
  'ameliorate',
  'better',
  'enhance',
  'clarify',
  'set right',
  'put right',
  'rectify',
  'remedy',
  'restore',
  'solve',
  'sort out',
  'resolve',
  'correct',
  'repair',
  'mend',
  'fix',
  'redress',
  'make good',
  'improve',
  'ameliorate',
  'better',
  'put right',
  'set right',
  'set to rights',
  'put to rights',
  'straighten out',
  'deal with',
  'make better',
];
