export const definitions = [
  '"she ascended the stairs"',
  '"new magmas were created and ascended to the surface"',
  '"the first traveler to ascend the mountain"',
  '"salmon ascend rivers from the sea to spawn"',
  '"we had ascended 3,000 ft"',
  '"the road ascends to the lake"',
  '"some executives ascend to top-level positions"',
  '"he took exams to ascend through the ranks"',
  '"the Prophet ascended to heaven"',
  '"Carolyn\'s voice had ascended into high - pitched giggles"',
];
export const synonyms = [
  "arise",
  "mount",
  "scale",
  "conquer",
  "levitate",
  "take off",
  "soar",
  "loom",
  "tower",
  "climb (up)",
  "come/go/move up",
  "make one's / its way up",
  "come/go/move upwards",
  "rise (up)",
  "clamber up",
  "scramble up",
  "shin up",
  "fly up",
  "take to the air",
  "slope upwards",
  "descend",
];
