export const definitions = [
  '"the first ascent of the Matterhorn"',
  '"the routes of ascent can be retraced"',
  '"the ascent grew steeper"',
  '"the first balloon ascent was in 1783"',
  '"his ascent to power"',
];
export const synonyms = [
  "climb",
  "scaling",
  "conquest",
  "scramble",
  "clamber",
  "trek",
  "descent",
  "incline",
  "ramp",
  "rise",
  "bank",
  "tilt",
  "slant",
  "inclination",
  "acclivity",
  "(upward) slope",
  "upward gradient",
  "descent",
  "drop",
  "rise",
  "takeoff",
  "liftoff",
  "launch",
  "blastoff",
  "climb",
  "levitation",
  "soaring",
  "jump",
  "leap",
  "Ascension",
  "upward movement",
  "descent",
  "drop",
];
