export const definitions = [
  '"the financial ______ can be overstressed"',
  '"from every ______ theirs was a changing world"',
  '"the air of desertion lent the place a sinister ______"',
  '"a man of decidedly foreign ______"',
  '"a greenhouse with a southern ______"',
  '"the front ______ of the hotel was unremarkable"',
  '"the sun in Aries formed an adverse ______ with Uranus in Capricorn"',
  '"the semantics of tense and ______"',
  '"four verbal ______s"',
  '"the sun is superbly ______ed by your ruler Mars on the 19th"',
];

export const synonyms = [
  "feature",
  "facet",
  "side",
  "characteristic",
  "particular",
  "detail",
  "point",
  "ingredient",
  "strand",
  "angle",
  "slant",
  "sense",
  "respect",
  "regard",
  "detail",
  "item",
  "particular",
  "fact",
  "thing",
  "idea",
  "argument",
  "consideration",
  "factor",
  "element",
  "regard",
  "respect",
  "subject",
  "issue",
  "topic",
  "question",
  "matter",
  "piece of information",
  "appearance",
  "look",
  "air",
  "bearing",
  "cast",
  "manner",
  "mien",
  "demeanor",
  "deportment",
  "expression",
  "countenance",
  "features",
  "semblance",
  "guise",
  "impression",
  "effect",
  "atmosphere",
  "mood",
  "quality",
  "ambience",
  "feeling",
  "flavor",
  "outlook",
  "view",
  "exposure",
  "direction",
  "situation",
  "position",
  "location",
  "face",
  "elevation",
  "facade",
  "side",
];
