export const definitions = [
  '"a loud murmur of assent"',
  '"he nodded assent"',
  '"the governor has power to withhold his assent from a bill"',
  '""Guest house, then," Frank assented cheerfully"',
  '"Roosevelt assented to the agreement"',
];
export const synonyms = [
  "approval",
  "acceptance",
  "endorsement",
  "encouragement",
  "recognition",
  "appreciation",
  "support",
  "respect",
  "admiration",
  "commendation",
  "congratulations",
  "praise",
  "acclamation",
  "adulation",
  "regard",
  "esteem",
  "veneration",
  "kudos",
  "applause",
  "ovation",
  "accolades",
  "salutes",
  "plaudits",
  "laudation",
  "criticism",
  "agreement",
  "acceptance",
  "approval",
  "approbation",
  "consent",
  "acquiescence",
  "compliance",
  "concurrence",
  "blessing",
  "imprimatur",
  "rubber stamp",
  "sanction",
  "endorsement",
  "ratification",
  "authorization",
  "mandate",
  "license",
  "validation",
  "confirmation",
  "support",
  "backing",
  "permission",
  "leave",
  "seal/stamp of approval",
  "dissent",
  "refusal",
  "accept",
  "approve",
  "bless",
  "rubber-stamp",
  "ratify",
  "sanction",
  "endorse",
  "authorize",
  "mandate",
  "license",
  "warrant",
  "validate",
  "pass",
  "confirm",
  "support",
  "back",
  "agree to",
  "consent to",
  "acquiesce in",
  "concur in",
  "accede to",
  "give one's blessing to",
  "give 's 's seal / stamp of approval to",
  "say yes to",
  "give one's permission / leave",
  "refuse",
  "dissent from",
];
