export const definitions = [
  '"a senior academic would ______ him in his work"',
  '"their presence would ______ in keeping the peace"',
  '"he ______ed her to find employment"',
  '"they were ______ing police with their inquiries"',
  '"funds to ______ with capital investment"',
  '"two midwives ______ed at the water birth"',
  '"he led the league with 14 outfield ______s"',
  '"the budget must have an ______ from tax policies"',
];

export const synonyms = [
  "help",
  "aid",
  "abet",
  "oblige",
  "accommodate",
  "serve",
  "do someone a favor",
  "do someone a good turn",
  "succor",
  "encourage",
  "support",
  "back",
  "back up",
  "second",
  "lend a (helping) hand to",
  "be of use to",
  "be of service to",
  "do someone a service",
  "bail someone out",
  "come to someone's rescue",
  "cooperate with",
  "collaborate with",
  "work with",
  "be a tower of strength to",
  "hinder",
  "facilitate",
  "aid",
  "ease",
  "expedite",
  "spur",
  "promote",
  "boost",
  "benefit",
  "foster",
  "encourage",
  "stimulate",
  "precipitate",
  "accelerate",
  "advance",
  "further",
  "forward",
  "make easier",
  "give a boost to",
  "help along",
  "contribute to",
  "be a factor in",
  "smooth the way for",
  "clear a path for",
  "open the door for",
  "oil the wheels of",
  "impede",
];
