export const definitions = [
  '"a puppet show"',
  '"he was little more than a puppet of his aides"',
];
export const synonyms = [
  'marionette',
  'hand puppet',
  'glove puppet',
  'finger puppet',
  'rod puppet',
  'shadow puppet',
  'pawn',
  'tool',
  'instrument',
  'cat\'s paw',
  'poodle',
  'creature',
  'hostage',
  'counter',
  'cog',
  'dupe',
  'mouthpiece',
  'minion',
  'figurehead',
];