export const definitions = [
  '"the filtration plant is able to purify 70 tons of water a day"',
  '"a group of 19th-century German painters who set out to purify art"',
  '"genomic DNA was purified from whole blood"',
  '"a ritual bath to purify the soul"',
];
export const synonyms = [
  "clean",
  "refine",
  "cleanse",
  "decontaminate",
  "filter",
  "sieve",
  "strain",
  "sift",
  "clarify",
  "clear",
  "freshen",
  "deodorize",
  "boil",
  "distill",
  "sanitize",
  "disinfect",
  "sterilize",
  "pasteurize",
  "fumigate",
  "autoclave",
  "liquate",
  "rectify",
  "filtrate",
  "make pure",
  "depollute",
  "pollute",
  "contaminate",
  "purge",
  "cleanse",
  "clear",
  "free",
  "unburden",
  "deliver",
  "relieve",
  "redeem",
  "shrive",
  "exorcise",
  "sanctify",
  "lustrate",
  "corrupt",
  "defile",
];
