export const definitions = [
  '"after the concert, I felt elated"',
  '"dozens of elated fans welcomed the champions home"',
  '"while the wealth of wildlife elated me, it unnerved me as well"',
];
export const synonyms = [
  "thrilled",
  "exhilarated",
  "happy",
  "delighted",
  "overjoyed",
  "joyous",
  "gleeful",
  "excited",
  "animated",
  "jubilant",
  "exultant",
  "ecstatic",
  "euphoric",
  "rapturous",
  "enraptured",
  "rapt",
  "in seventh heaven",
  "transported",
  "hysterical",
  "frenzied",
  "corybantic",
  "beside oneself with happiness",
  "in raptures",
  "walking on air",
  "on cloud nine/seven",
  "jumping for joy",
  "in transports of delight",
  "carried away",
  "in a frenzy of delight",
  "delirious (with happiness)",
  "wild with excitement",
  "miserable",
];
