export const definitions = [
  '"an elixir guaranteed to induce love"',
  '"a cough elixir"',
];
export const synonyms = [
  "potion",
  "concoction",
  "brew",
  "philter",
  "decoction",
  "medicine",
  "tincture",
  "tonic",
  "draft",
  "potation",
  "mixture",
  "solution",
  "potion",
  "tincture",
  "extract",
  "essence",
  "concentrate",
  "distillate",
  "distillation",
];
