export const definitions = [
  '"the guest house was erected in the eighteenth century"',
  '"the police had erected roadblocks"',
  '"the party that erected the welfare state"',
];
export const synonyms = [
  "build",
  "construct",
  "put up",
  "assemble",
  "put together",
  "fabricate",
  "form",
  "manufacture",
  "set up",
  "pitch",
  "position",
  "place",
  "locate",
  "set upright",
  "fit together",
  "piece together",
  "fix in position",
  "demolish",
  "dismantle",
  "establish",
  "form",
  "set up",
  "found",
  "institute",
  "initiate",
  "formulate",
  "devise",
  "create",
  "organize",
  "frame",
  "put in place",
  "break up",
];
