export const definitions = ['"her book of erotic fantasies"'];
export const synonyms = [
  "titillating",
  "salacious",
  "prurient",
  "lubricious",
  "suggestive",
  "pornographic",
  "lewd",
  "smutty",
  "hardcore",
  "soft-core",
  "dirty",
  "off color",
  "indecent",
  "improper",
  "filthy",
  "vulgar",
  "crude",
  "libidinous",
  "lustful",
  "lascivious",
  "lecherous",
  "licentious",
  "sexual",
  "sexy",
  "sensual",
  "carnal",
  "venereal",
  "amatory",
  "seductive",
  "alluring",
  "tantalizing",
  "desirable",
  "aphrodisiac",
  "racy",
  "risqué",
  "ribald",
  "naughty",
  "bawdy",
  "earthy",
  "spicy",
  "Rabelaisian",
  "erogenous",
  "erotogenic",
  "concupiscent",
  "anacreontic",
  "sexually arousing",
  "sexually exciting",
  "sexually stimulating",
  "sexually explicit",
  "venereous",
];
