export const definitions = [
  '"he could never forgive his daughter\'s errant ways"',
  '"that same lady errant"',
];
export const synonyms = [
  'offending',
  'guilty',
  'culpable',
  'misbehaving',
  'delinquent',
  'lawless',
  'lawbreaking',
  'criminal',
  'transgressing',
  'aberrant',
  'deviant',
  'erring',
  'sinning',
  'mischievous',
  'troublesome',
  'difficult',
  'unmanageable',
  'unruly',
  'disobedient',
  'uncontrollable',
  'out of control',
  'badly behaved',
  'innocent',
  'well behaved',
  'traveling',
  'wandering',
  'itinerant',
  'journeying',
  'rambling',
  'roaming',
  'roving',
  'drifting',
  'floating',
  'wayfaring',
  'voyaging',
  'touring',
  'peripatetic',
  'unsettled',
  'rootless',
  'restless',
  'on the move',
  'on the go',
  'on the wing',
  'nomadic',
  'vagabond',
  'vagrant',
  'migrant',
  'migratory',
  'migrating',
  'transient',
  'displaced',
  'globetrotting',
  'jet-setting',
  'sedentary',
];