export const definitions = [];
export const synonyms = [
  "error",
  "mistake",
  "miscalculation",
  "fallacy",
  "slip",
  "oversight",
  "fault",
  "blunder",
  "gaffe",
  "defect",
  "flaw",
  "slip of the pen",
  "literal",
  "corrigendum",
  "slip of the tongue",
  "lapsus calami",
  "lapsus linguae",
  "typographical error",
  "printer's error",
];
