export const definitions = [
  '"she asked Tim to run an errand for her"',
  '"she knew that if she stated her errand she would not be able to see him"',
];
export const synonyms = [
  'task',
  'job',
  'chore',
  'assignment',
  'collection',
  'delivery',
  'shopping',
  'trip',
  'run',
  'journey',
  'mission',
  'expedition',
  'operation',
  'undertaking',
  'commission',
  'business',
  'message',
  'responsibility',
  'duty',
  'concern',
  'province',
  'aim',
  'activity',
  'assignment',
  'obligation',
  'charge',
  'task',
  'chore',
  'job',
  'role',
  'mission',
  'detail',
  'undertaking',
  'commission',
  'capacity',
  'post',
  'situation',
  'office',
  'occupation',
  'employment',
  'business',
  'operation',
  'raison d\'être',
  'line of country',
];