export const definitions = [
  '"he was working for his father slating a new roof"',
  '"a slated roof"',
  '"his work was slated by the critics"',
  '"renovations are slated for late June"',
  '"construction is slated to begin late next year"',
  '"I understand that I am being slated for promotion"',
  '"the assistant cameraman is about to slate the scene"',
];
export const synonyms = [
  "attack",
  "pillory",
  "lambaste",
  "condemn",
  "flay",
  "savage",
  "shoot down",
  "revile",
  "vilify",
  "slash",
  "excoriate",
  "criticize harshly",
  "praise",
  "commend",
  "applaud",
  "schedule",
  "set",
  "set up",
  "arrange",
  "organize",
  "sort out",
  "fix",
  "time",
  "book",
  "line up",
  "prearrange",
  "bill",
  "program",
  "plan",
  "fix up",
  "fix a time for",
  "slot in",
];
