export const definitions = [
  '"a dog sledge"',
  '"a sledge journey"',
  '"the task of sledging lifeboats across tundra"',
  '"they sledged down the slopes in the frozen snow"',
  '"children built snowmen and went sledging"',
  '"Zol smashed Zaheer for a couple of fours immediately after being sledged by the veteran seamer"',
  '"in Australia he stared down batsmen, sledged, swore, and kept coming at them"',
  '"people on that side of the chamber sledged the Prime Minister and accused the coalition of immorality"',
  '"he was upset after a very personal sledge by the Australian captain"',
  '"as political sledges go, it was a killer"',
];
export const synonyms = [
  "toboggan",
  "bobsled",
  "luge",
  "bobsleigh",
  "sleigh",
  "coaster",
  "cutter",
  "sled",
  "carriole",
  "troika",
  "komatik",
  "travois",
  "kibitka",
  "toboggan",
  "bobsled",
  "luge",
  "bobsleigh",
  "sleigh",
  "coaster",
  "cutter",
  "sled",
  "carriole",
  "troika",
  "komatik",
  "travois",
  "kibitka",
  "poke fun at",
  "make fun of",
  "get at",
  "insult",
  "tease",
  "chaff",
  "torment",
  "provoke",
  "goad",
  "ridicule",
  "deride",
  "mock",
  "heckle",
  "ride",
  "make sport of",
  "jeer at",
  "gibe at",
  "sneer at",
  "scoff at",
  "censure",
  "denounce",
  "condemn",
  "arraign",
  "attack",
  "lambaste",
  "pillory",
  "pour scorn on",
  "disparage",
  "denigrate",
  "deprecate",
  "malign",
  "vilify",
  "besmirch",
  "run down",
  "slur",
  "excoriate",
  "rate",
  "slash",
  "reprobate",
  "objurgate",
  "asperse",
  "derogate",
  "reprehend",
  "offend",
  "affront",
  "abuse",
  "call someone names",
  "slight",
  "discredit",
  "libel",
  "slander",
  "defame",
  "impugn",
  "revile",
  "calumniate",
  "hurt",
  "mortify",
  "humiliate",
  "wound",
  "snub",
  "rebuff",
  "spurn",
  "shun",
  "ignore",
  "turn one's back on",
  "miscall",
  "find fault with",
  "disapprove of",
  "carp at",
  "cavil at",
  "rail against",
  "inveigh against",
  "cast aspersions on",
  "give a bad press to",
  "vituperate against",
  "animadvert on",
  "give/cause offense to",
  "be rude to",
  "hurt someone's feelings",
  "treat disrespectfully",
  "cut dead",
  "give someone the cold-shoulder",
  "praise",
  "compliment",
  "flatter",
  "approve of",
  "jeer",
  "gibe",
  "sneer",
  "insult",
  "barb",
  "catcall",
  "brickbat",
  "scoff",
  "teasing",
  "taunting",
  "provocation",
  "goading",
  "ridiculing",
  "derision",
  "mockery",
  "sarcasm",
  "slap in the face",
  "censure",
  "condemnation",
  "denunciation",
  "disapproval",
  "disparagement",
  "opprobrium",
  "captiousness",
  "fault-finding",
  "carping",
  "cavilling",
  "chastisement",
  "castigation",
  "upbraiding",
  "berating",
  "abuse",
  "vituperation",
  "scolding",
  "chiding",
  "reproofs",
  "remonstrances",
  "broadsides",
  "strictures",
  "admonishments",
  "recriminations",
  "aspersions",
  "slurs",
  "smears",
  "contumely",
  "animadversion",
  "objurgation",
  "excoriation",
  "reprobation",
  "arraignment",
  "jibe",
  "affront",
  "slight",
  "snub",
  "barb",
  "slur",
  "injury",
  "libel",
  "slander",
  "defamation",
  "depreciation",
  "impugnment",
  "revilement",
  "humiliation",
  "indignity",
  "insolence",
  "rudeness",
  "reproval",
  "abusive remark",
  "backhanded compliment",
  "compliment",
];
