export const definitions = [
  '"the water gushed through the sluices"',
  '"lake levels are now regulated by sluices"',
  '"a sluice with cold water"',
  '"she sluiced her face in cold water"',
  '"crews sluiced down the decks of their ship"',
  '"the waves sluiced over them"',
];
export const synonyms = [
  "drain",
  "sluiceway",
  "culvert",
  "spillway",
  "flume",
  "sewer",
  "channel",
  "conduit",
  "pipe",
  "duct",
  "chute",
  "trough",
  "trench",
  "ditch",
  "furrow",
  "cut",
  "wash",
  "wash down",
  "rinse",
  "clean",
  "cleanse",
  "flush",
  "swill down",
  "pour",
  "flow",
  "run",
  "gush",
  "cascade",
  "stream",
  "course",
  "spout",
  "jet",
  "spurt",
  "flood",
  "surge",
  "spill",
  "rush",
  "well",
  "spew",
  "discharge",
  "disembogue",
];
