export const definitions = [
  '"his letters evince the excitement he felt at undertaking this journey"',
  '"man\'s inhumanity to man as evinced in the use of torture"',
];
export const synonyms = [
  "reveal",
  "show",
  "manifest",
  "indicate",
  "display",
  "exhibit",
  "demonstrate",
  "evidence",
  "bear witness to",
  "convey",
  "communicate",
  "proclaim",
  "impart",
  "bespeak",
  "disclose",
  "divulge",
  "betray",
  "give away",
  "expose",
  "make clear",
  "make plain",
  "make obvious",
  "make manifest",
  "be evidence of",
  "attest to",
  "testify to",
  "lay bare",
  "conceal",
];
