export const definitions = [
  '"he was at the podium facing an expectant conference crowd"',
  '"I took the score out of my briefcase and put it on the podium"',
  '"it was more than I could imagine to be up on the podium and singing the national anthem"',
  '"a six columned portico raised on a podium"',
  "\"I've had great results in the sprint and I've podiumed in the individual\"",
];
export const synonyms = [
  "platform",
  "stage",
  "dais",
  "rostrum",
  "stand",
  "soapbox",
  "mandapam",
  "plinth",
  "base",
  "support",
  "bottom",
  "bed",
  "foot",
  "substructure",
  "mounting",
  "platform",
  "stand",
  "foundation",
  "pillar",
  "column",
  "pier",
  "socle",
];
