export const definitions = [
  '"I pondered the question of what clothes to wear for the occasion"',
  '"she sat pondering over her problem"',
];
export const synonyms = [
  "think about",
  "consider",
  "review",
  "contemplate",
  "study",
  "dwell on",
  "chew over",
  "weigh up",
  "cerebrate",
  "give thought to",
  "reflect on",
  "mull over",
  "meditate on",
  "muse on",
  "deliberate about",
  "cogitate on",
  "brood on/over",
  "ruminate about/on",
  "puzzle over",
  "speculate about",
  "turn over in one's mind",
  "be in a brown study",
  "pore on",
];
