export const definitions = [
  '"the sheer number of visitors is posing a threat to the area"',
  '"a statement that posed more questions than it answered"',
  '"she posed for a swarm of TV cameramen"',
  '"he posed her on the sofa"',
  '"a literary novel posing as a spy thriller"',
  '"a detective posing as a customer"',
  '"some people like to drive these cars, but most just like to pose in them"',
  '"we have thus posed the mathematician and the historian"',
];
export const synonyms = [
  "constitute",
  "present",
  "create",
  "cause",
  "produce",
  "give rise to",
  "lead to",
  "result in",
  "put forward",
  "raise",
  "ask",
  "put",
  "set",
  "submit",
  "advance",
  "propose",
  "propound",
  "posit",
  "broach",
  "suggest",
  "postulate",
  "moot",
  "model",
  "sit",
  "strike a pose",
  "be a model",
  "take up a position",
  "assume an attitude",
  "position",
  "place",
  "put",
  "arrange",
  "lay out",
  "set out",
  "dispose",
  "locate",
  "situate",
  "posture",
  "impersonate",
  "pass for",
  "personate",
  "pretend to be",
  "pass oneself off as",
  "be disguised as",
  "masquerade as",
  "profess to be",
  "purport to be",
  "set oneself up as",
  "assume/feign the identity of",
  "represent oneself as",
  "strike a pose",
  "posture",
  "attitudinize",
  "behave affectedly",
  "strike an attitude",
  "put on airs",
  "put on an act",
];
