export const definitions = ['"don\'t make such a pother!"'];
export const synonyms = [
  "commotion",
  "uproar",
  "outcry",
  "disturbance",
  "hubbub",
  "hurly-burly",
  "fuss",
  "upset",
  "tumult",
  "brouhaha",
  "palaver",
  "to-do",
  "turmoil",
  "tempest",
  "agitation",
  "pandemonium",
  "confusion",
  "stir",
  "excitement",
  "scandal",
  "sensation",
];
