export const definitions = [
  '"the season starts in September"',
  '"we ate before the show started"',
  '"below Roaring Springs the real desert starts"',
  '"I started to chat to him"',
  '"we plan to start building in the fall"',
  '"the teacher can start by capitalizing on children\'s curiosity"',
  '"I shall start with the case you mention first"',
  '"we started out into the snow"',
  '"he started for the door"',
  '"she will start school today"',
  '"he started work at a travel agency"',
  '"he started as a typesetter"',
  '"fees start at around $300"',
  '"it\'s quite expensive, starting from $800 for the most basic model"',
  "\"the fire started in the build's 's upper floor\"",
  "\"Towns's 's troubles started before the incident\"",
  '"two men started the blaze that caused the explosion"',
  '"those women started all the trouble"',
  '"I\'m starting a campaign to get the law changed"',
  '"what should I do if the engine won\'t start again ? "',
  '"there was a moment of silence before the organ started"',
  '"we had trouble starting the car"',
  '"his father started him in business"',
  '"what he said started me thinking"',
  '""Oh my!" she said, starting"',
  '"she had seen Meg start suddenly from a thicket"',
  '"his eyes started out of his head like a hare\'s"',
  '"the mortar in the joints had started"',
  '"he takes over as chief executive at the start of next year"',
  '"the event was a shambles from start to finish"',
  '"his bicycle was found close to the start of a forest trail"',
  '"make sure you are not over the line at the start"',
  '"I can make a start on cleaning up"',
  '"an early start enabled us to avoid the traffic"',
  '"if he would tell her who had put him up to it, it would be a start"',
  '"she\'s anxious to give her baby the best start in life"',
  '"he would have a ninety-minute start on them"',
  '"she awoke with a start"',
  '"the woman gave a nervous start"',
];
export const synonyms = [
  "begin",
  "go ahead",
  "commence",
  "appear",
  "arrive",
  "emerge",
  "erupt",
  "arise",
  "originate",
  "break",
  "unfold",
  "develop",
  "crop up",
  "get under way",
  "get going",
  "come into being",
  "be born",
  "come into existence",
  "come forth",
  "burst out",
  "first see the light of day",
  "finish",
  "end",
  "clear up",
  "begin",
  "go ahead",
  "take something forward",
  "turn to",
  "put one's shoulder to the wheel",
  "put 's 's hand to the plow",
  "commence",
  "make a start",
  "make a beginning",
  "take the first step",
  "lay the first stone",
  "make the first move",
  "get going",
  "set things moving",
  "buckle to/down",
  "start/get/set the ball rolling",
  "stop",
  "give up",
  "hang about",
  "set off",
  "set out",
  "start out",
  "set forth",
  "depart",
  "leave",
  "embark",
  "sail",
  "begin one's journey",
  "get on the road",
  "get under way",
  "make a start",
  "sally forth",
  "set forward",
  "arrive",
  "stay",
  "begin",
  "appear",
  "arrive",
  "emerge",
  "erupt",
  "arise",
  "originate",
  "break",
  "unfold",
  "develop",
  "crop up",
  "commence",
  "come into being",
  "be born",
  "come into existence",
  "come forth",
  "burst out",
  "first see the light of day",
  "end",
  "clear up",
  "establish",
  "set up",
  "found",
  "sow the seeds of",
  "create",
  "institute",
  "initiate",
  "inaugurate",
  "introduce",
  "open",
  "begin",
  "launch",
  "float",
  "kick-start",
  "activate",
  "originate",
  "pioneer",
  "organize",
  "mastermind",
  "tackle",
  "set about",
  "lay the foundations of",
  "lay the cornerstone of",
  "lay the first stone of",
  "bring into being",
  "put in place",
  "get something off the ground",
  "get something going",
  "get something moving",
  "get something working",
  "get something functioning",
  "embark on",
  "make a start on",
  "end",
  "wind up",
  "begin working",
  "start functioning",
  "get going",
  "start operating",
  "stop",
  "activate",
  "switch on",
  "turn on",
  "energize",
  "actuate",
  "set off",
  "start off",
  "kick-start",
  "set in motion",
  "fire up",
  "get/set something going/moving",
  "start something functioning",
  "start something operating",
  "stop",
  "close down",
  "flinch",
  "jerk",
  "jump",
  "twitch",
  "recoil",
  "shrink",
  "blench",
  "wince",
  "shy",
  "jump",
  "leap",
  "spring",
  "bound",
  "dash",
  "charge",
  "pounce",
  "dive",
  "rush",
  "dart",
  "beginning",
  "inception",
  "onset",
  "emergence",
  "arrival",
  "eruption",
  "dawn",
  "birth",
  "establishment",
  "foundation",
  "institution",
  "origination",
  "inauguration",
  "induction",
  "creation",
  "opening",
  "launch",
  "float",
  "floating",
  "commencement",
  "origin",
  "source",
  "root",
  "germ",
  "seeds",
  "genesis",
  "cause",
  "reason",
  "motivation",
  "motive",
  "fons et origo",
  "fountainhead",
  "wellspring",
  "fount",
  "(first) appearance",
  "starting point",
  "flying start",
  "opening",
  "opportunity",
  "chance",
  "encouragement",
  "lift",
  "assistance",
  "support",
  "boost",
  "kick-start",
  "advantageous beginning",
  "helping hand",
  "lead",
  "advantage",
  "head start",
  "advantageous position",
  "jerk",
  "twitch",
  "flinch",
  "wince",
  "spasm",
  "convulsion",
  "jump",
];
