export const definitions = [
  '"the stigma of having gone to prison will always be with me"',
  '"debt has lost its stigma and is now a part of everyday life"',
  '"knee deformities or other stigmata of childhood rickets"',
];
export const synonyms = [
  "shame",
  "disgrace",
  "dishonor",
  "stain",
  "taint",
  "blot",
  "blemish",
  "brand",
  "mark",
  "slur",
  "smirch",
  "blot on one's escutcheon",
  "honor",
  "credit",
  "cicatrix",
  "mark",
  "blemish",
  "disfigurement",
  "discoloration",
  "defacement",
  "pockmark",
  "pock",
  "pit",
  "wound",
  "lesion",
  "burn",
  "birthmark",
  "nevus",
  "stigmata",
];
