export const definitions = [
  '"they stripped the bed"',
  '"the man had been stripped naked"',
  '"she stripped down to her underwear"',
  '"they stripped and showered"',
  '"she stripped off her shirt"',
  '"strip away the hype and you\'ll find original thought"',
  '"the floorboards can be stripped, sanded, and polished"',
  '"strip off the existing paint"',
  '"thieves stripped the room of luggage"',
  '"the tank was stripped down piece by piece"',
  '"the lieutenant was stripped of his rank"',
  '"she got drunk and did a strip on top of the piano"',
  '"a campaigner against strip joints"',
  '"a strip of linen"',
  '"the offensive gained a strip of territory a mile wide"',
  '"a strip cartoon"',
];
export const synonyms = [
  'undress',
  'unclothe',
  'disrobe',
  'strip off',
  'take one\'s clothes off',
  'remove \'s \'s clothes',
  'shed \'s \'s clothes',
  'strip naked',
  'denude oneself',
  'expose oneself',
  'reveal oneself',
  'uncover oneself',
  'divest oneself of one\'s clothes',
  'dress',
  'peel',
  'remove',
  'take off',
  'flake',
  'scrape',
  'scratch',
  'shave',
  'abrade',
  'rub',
  'clear',
  'clean',
  'pare',
  'skin',
  'flay',
  'excoriate',
  'decorticate',
  'empty',
  'clear',
  'clean out',
  'plunder',
  'rob',
  'burgle',
  'loot',
  'rifle',
  'pillage',
  'ransack',
  'gut',
  'devastate',
  'sack',
  'ravage',
  'raid',
  'despoil',
  'spoil',
  'reave',
  'lay bare',
  'dismantle',
  'disassemble',
  'take apart',
  'break up',
  'demolish',
  'take to pieces',
  'take to bits',
  'construct',
  'assemble',
  'take away from',
  'dispossess',
  'deprive',
  'confiscate',
  'divest',
  'relieve',
  'deny',
  'rob',
  'piece',
  'bit',
  'band',
  'belt',
  'ribbon',
  'sash',
  'stripe',
  'bar',
  'swathe',
  'slip',
  'fillet',
  'shred',
  'narrow piece',
];