export const definitions = [
  '"my father was very strict"',
  '"a strict upbringing"',
  '"civil servants are bound by strict rules on secrecy"',
  '"a strict vegetarian"',
  '"a strict interpretation of the law"',
];
export const synonyms = [
  "stern",
  "severe",
  "harsh",
  "uncompromising",
  "authoritarian",
  "firm",
  "austere",
  "illiberal",
  "inflexible",
  "unyielding",
  "unbending",
  "no-nonsense",
  "lenient",
  "stringent",
  "rigorous",
  "severe",
  "harsh",
  "hard",
  "rigid",
  "tough",
  "extreme",
  "absolute",
  "utter",
  "complete",
  "total",
  "perfect",
  "liberal",
  "precise",
  "exact",
  "literal",
  "close",
  "faithful",
  "true",
  "accurate",
  "unerring",
  "scrupulous",
  "careful",
  "meticulous",
  "rigorous",
  "stringent",
  "conscientious",
  "punctilious",
  "painstaking",
  "thorough",
  "orthodox",
  "fundamentalist",
  "conservative",
  "traditional",
  "devout",
  "religious",
  "imprecise",
  "loose",
  "moderate",
  "liberal",
];
