export const definitions = [
  '"strife within the community"',
  '"ethnic and civil strife"',
];
export const synonyms = [
  "conflict",
  "friction",
  "discord",
  "disagreement",
  "dissension",
  "variance",
  "dispute",
  "argument",
  "quarreling",
  "wrangling",
  "bickering",
  "controversy",
  "contention",
  "disharmony",
  "ill feeling",
  "bad blood",
  "hostility",
  "animosity",
  "bad feeling",
  "harmony",
  "peace",
  "cooperation",
];
