export const definitions = [
  '"national movements were striving for independence"',
  '"we must strive to secure steady growth"',
  '"scholars must strive against bias"',
];
export const synonyms = [
  'try',
  'attempt',
  'endeavor',
  'aim',
  'aspire',
  'venture',
  'undertake',
  'seek',
  'make an effort',
  'make every effort',
  'spare no effort',
  'do one\'s best',
  'do \'s \'s utmost',
  'labor',
  'work',
  'toil',
  'strain',
  'struggle',
  'have a go at',
  'essay',
  'fight',
  'battle',
  'combat',
  'contend',
  'grapple',
  'campaign',
  'war',
  'crusade',
  'try hard',
  'exert oneself',
  'do all one can',
  'give one\'s all',
  'apply oneself',
];