export const definitions = [
  '"her neat, tidy script"',
  '"Russian script"',
  '"it was perfectly scripted and beautifully acted"',
];
export const synonyms = [
  "handwriting",
  "writing",
  "hand",
  "autograph",
  "pen",
  "letters",
  "longhand",
  "penmanship",
  "calligraphy",
  "chirography",
  "scribble",
  "scrawl",
  "text",
  "book",
  "screenplay",
  "libretto",
  "lyrics",
  "score",
  "lines",
  "parts",
  "dialogue",
  "words",
  "manuscript",
];
