export const definitions = [
  '"she cut through the water with her strong arms"',
  '"he was not a strong swimmer"',
  '"a strong current"',
  '"the competition was too strong"',
  '"there is a strong argument for decentralization"',
  '"his imagery made a strong impression on the critics"',
  '"the government was urged to take strong measures against the perpetrators of violence"',
  '"cotton is strong, hard-wearing, and easy to handle"',
  '"despite his strong constitution, constant worry and exposure to the elements had worn him down"',
  '"driving on these highways requires strong nerves"',
  '"only a strong will enabled him to survive"',
  '"a strong and trusting relationship"',
  '"a strong smell"',
  '"she should wear strong colors"',
  '"strong cheese"',
  '"a cup of strong coffee"',
  '"a hostile crowd several thousand strong"',
];
export const synonyms = [
  "powerful",
  "muscular",
  "brawny",
  "well built",
  "strapping",
  "sturdy",
  "hefty",
  "burly",
  "meaty",
  "robust",
  "fit",
  "athletic",
  "vigorous",
  "tough",
  "rugged",
  "stalwart",
  "staunch",
  "mighty",
  "hardy",
  "lusty",
  "Herculean",
  "powerfully built",
  "strong as an ox/horse/lion",
  "weak",
  "puny",
  "capable",
  "able",
  "proficient",
  "adept",
  "adroit",
  "accomplished",
  "impressive",
  "powerful",
  "mighty",
  "terrific",
  "tremendous",
  "great",
  "redoubtable",
  "indomitable",
  "invincible",
  "seasoned",
  "skillful",
  "skilled",
  "gifted",
  "talented",
  "masterly",
  "virtuoso",
  "expert",
  "knowledgeable",
  "qualified",
  "trained",
  "efficient",
  "good",
  "excellent",
  "brilliant",
  "outstanding",
  "first-class",
  "first-rate",
  "compleat",
  "habile",
  "weak",
  "forceful",
  "powerful",
  "vigorous",
  "fierce",
  "intense",
  "extreme",
  "gentle",
  "compelling",
  "cogent",
  "forceful",
  "powerful",
  "potent",
  "weighty",
  "convincing",
  "plausible",
  "effective",
  "efficacious",
  "sound",
  "valid",
  "well founded",
  "telling",
  "impressive",
  "persuasive",
  "influential",
  "authoritative",
  "weak",
  "unconvincing",
  "intense",
  "forceful",
  "vehement",
  "passionate",
  "ardent",
  "fervent",
  "fervid",
  "profound",
  "deep-seated",
  "consuming",
  "extreme",
  "acute",
  "fierce",
  "perfervid",
  "passional",
  "firm",
  "forceful",
  "severe",
  "strict",
  "drastic",
  "extreme",
  "draconian",
  "secure",
  "well built",
  "indestructible",
  "impregnable",
  "impenetrable",
  "inviolable",
  "unassailable",
  "fortress-like",
  "solid",
  "durable",
  "hardwearing",
  "heavy-duty",
  "tough",
  "sturdy",
  "well made",
  "substantial",
  "rugged",
  "resistant",
  "resilient",
  "imperishable",
  "long-lasting",
  "enduring",
  "well fortified",
  "well defended",
  "well protected",
  "weak",
  "well",
  "healthy",
  "fit",
  "robust",
  "vigorous",
  "blooming",
  "thriving",
  "hale",
  "hearty",
  "sound",
  "in good health",
  "fighting fit",
  "bursting with health",
  "in rude health",
  "hale and hearty",
  "in good shape",
  "in excellent shape",
  "in good condition",
  "in good trim",
  "in fine fettle",
  "sound in body and limb",
  "frail",
  "forceful",
  "determined",
  "spirited",
  "dynamic",
  "self-assertive",
  "tough",
  "tenacious",
  "high-powered",
  "formidable",
  "aggressive",
  "redoubtable",
  "zealous",
  "firm",
  "resolute",
  "strong-minded",
  "weak",
  "forceful",
  "determined",
  "spirited",
  "dynamic",
  "self-assertive",
  "tough",
  "tenacious",
  "high-powered",
  "formidable",
  "aggressive",
  "redoubtable",
  "zealous",
  "firm",
  "resolute",
  "strong-minded",
  "weak",
  "keen",
  "eager",
  "deep",
  "acute",
  "dedicated",
  "passionate",
  "fervent",
  "zealous",
  "enthusiastic",
  "earnest",
  "staunch",
  "loyal",
  "steadfast",
  "fierce",
  "intense",
  "deep",
  "rich",
  "warm",
  "bright",
  "brilliant",
  "vivid",
  "striking",
  "colorful",
  "graphic",
  "radiant",
  "gleaming",
  "dazzling",
  "glaring",
  "pale",
  "loud",
  "powerful",
  "forceful",
  "lusty",
  "stentorian",
  "resonant",
  "sonorous",
  "orotund",
  "full",
  "rich",
  "deep",
  "booming",
  "penetrating",
  "carrying",
  "clear",
  "strident",
  "canorous",
  "quiet",
  "weak",
  "flavorful",
  "flavorsome",
  "savory",
  "pungent",
  "aromatic",
  "piquant",
  "tangy",
  "sharp",
  "biting",
  "zesty",
  "spicy",
  "hot",
  "flavorous",
  "sapid",
  "highly flavored",
  "strongly flavored",
  "mild",
  "concentrated",
  "undiluted",
  "alcoholic",
  "intoxicating",
  "inebriating",
  "hard",
  "heady",
  "potent",
  "stiff",
  "spirituous",
  "vinous",
  "intoxicant",
  "highly flavored",
  "weak",
  "mild",
  "nonalcoholic",
  "soft",
];
