export const definitions = [
  '"I strolled around the city"',
  '"we took a stroll in the garden"',
];
export const synonyms = [
  "saunter",
  "amble",
  "wander",
  "meander",
  "ramble",
  "dawdle",
  "promenade",
  "walk",
  "putter",
  "roam",
  "traipse",
  "stretch one's legs",
  "take the air",
  "perambulate",
  "peregrinate",
  "go for a walk",
  "take a walk",
  "get some exercise",
  "get some air",
  "stravaig",
  "saunter",
  "amble",
  "wander",
  "walk",
  "turn",
  "promenade",
  "airing",
  "breather",
  "outing",
  "excursion",
  "jaunt",
  "constitutional",
  "perambulation",
];
