export const definitions = [
  '"the yacht is well proportioned and conservatively styled"',
  '"he styled her hair by twisting it up to give it body"',
  '"the official is styled principal and vice chancellor of the university"',
];
export const synonyms = [
  "design",
  "fashion",
  "tailor",
  "make",
  "produce",
  "groom",
  "arrange",
  "comb",
  "brush",
  "do",
  "straighten",
  "adjust",
  "preen",
  "primp",
  "put in order",
  "call",
  "name",
  "title",
  "entitle",
  "dub",
  "designate",
  "term",
  "address",
  "label",
  "tag",
  "christen",
  "baptize",
  "nickname",
  "denominate",
  "clepe",
];
