export const definitions = [
  '"the changes must not be allowed to stymie new medical treatments"',
];
export const synonyms = [
  'impede',
  'hamper',
  'hinder',
  'obstruct',
  'inhibit',
  'frustrate',
  'thwart',
  'foil',
  'spoil',
  'stall',
  'shackle',
  'fetter',
  'stop',
  'check',
  'block',
  'cripple',
  'handicap',
  'scotch',
  'interfere with',
  'assist',
  'help',
];