export const definitions = [
  '"the use of opiate drugs"',
  '"the opiates are known to have natural counterparts called endorphins"',
  '"the capacity to use books as an opiate"',
  '"he grew old and soft, opiating himself into a dreaming bliss"',
  '"they opiate the people with the promises of social change that they fail to keep"',
];
export const synonyms = [
  "drug",
  "narcotic",
  "sedative",
  "tranquilizer",
  "depressant",
  "sleeping pill",
  "soporific",
  "anesthetic",
  "painkiller",
  "analgesic",
  "anodyne",
  "barbiturate",
  "bromide",
  "morphine",
  "opium",
  "laudanum",
  "calmative",
  "palliative",
  "stupefacient",
  "nepenthes",
  "mind-altering drug",
  "sleeping draft",
];
