export const definitions = [
  '""The man is a genius," he opined"',
  '"the critic opined that the most exciting musical moment occurred when the orchestra struck up the national anthem"',
];
export const synonyms = [
  "suggest",
  "submit",
  "advance",
  "propose",
  "venture",
  "volunteer",
  "put forward",
  "moot",
  "propound",
  "posit",
  "air",
  "hazard",
  "say",
  "declare",
  "observe",
  "comment",
  "remark",
  "think",
  "believe",
  "consider",
  "maintain",
  "imagine",
  "reckon",
  "guess",
  "estimate",
  "conjecture",
  "fancy",
  "suspect",
  "feel",
  "assume",
  "presume",
  "take it",
  "suppose",
  "expect",
  "gather",
  "contend",
  "reason",
  "deduce",
  "conclude",
  "theorize",
  "hypothesize",
  "ween",
  "be of the view",
  "be of the opinion",
  "have a/the feeling",
  "be convinced",
  "be of the conviction",
  "take as a hypothesis",
];
