export const definitions = [
  '"the plant grows within a range of 68 and 78°F, the optimum being 74°"',
  '"the optimum must lie between these two values"',
];
export const synonyms = [
  'peak',
  'pinnacle',
  'zenith',
  'high point',
  'crown',
  'crest',
  'summit',
  'top',
  'tip',
  'apex',
  'apogee',
  'climax',
  'culmination',
  'height',
  'maximum',
  'extremity',
  'limit',
  'prime',
  'flower',
  'flowering',
  'bloom',
  'blooming',
  'highlight',
  'highest point',
  'upper limit',
  'crowning point',
  'nadir',
  'bottom',
  'lowest point',
];