export const definitions = [
  '"trashy novels and formulaic movies"',
];
export const synonyms = [
  'substandard',
  'bad',
  'deficient',
  'defective',
  'faulty',
  'imperfect',
  'inferior',
  'mediocre',
  'abject',
  'poor',
  'appalling',
  'abysmal',
  'atrocious',
  'awful',
  'terrible',
  'dismal',
  'dreadful',
  'unsatisfactory',
  'low-grade',
  'third-rate',
  'jerry-built',
  'shoddy',
  'crude',
  'tinny',
  'miserable',
  'wretched',
  'lamentable',
  'deplorable',
  'pitiful',
  'inadequate',
  'insufficient',
  'unacceptable',
  'execrable',
  'frightful',
  'direful',
  'egregious',
  'below standard',
  'below par',
  'first-rate',
  'excellent',
];