export const definitions = [
  '"the administration had to tread carefully so as not to offend the judiciary"',
  '"he trod lightly, trying to make as little contact with the mud as possible"',
  '"the youth stumbled and trod on Harry\'s shoe"',
  '"shoppers will soon be treading the floors of the new shopping mall"',
  '"food and cigarette butts had been trodden into the carpet"',
  '"the snow had been trodden down by the horses"',
  '"she stood on the floor of trodden earth"',
  '"I heard the heavy tread of Dad\'s boots"',
];
export const synonyms = [
  "walk",
  "step",
  "stride",
  "pace",
  "go",
  "march",
  "tramp",
  "plod",
  "stomp",
  "trudge",
  "crush",
  "flatten",
  "squash",
  "press down",
  "trample on",
  "tramp on",
  "step on",
  "stamp on",
  "stomp on",
  "step",
  "footstep",
  "footfall",
  "tramp",
];
