export const definitions = [
  '"the newspaper accounts of the trial"',
  '"the editor was summoned to stand trial for libel"',
  '"clinical trials must establish whether the new hip replacements are working"',
  '"he cracked his ankle the week before the final trial"',
  '"horse trials"',
  '"this winter has been a trial for me, physically and emotionally"',
  '"all seeds are carefully trialed in a variety of growing conditions"',
  '"the pup trialed on Saturday"',
];
export const synonyms = [
  "court case",
  "case",
  "lawsuit",
  "suit",
  "hearing",
  "inquiry",
  "tribunal",
  "litigation",
  "legal proceedings",
  "proceedings",
  "legal action",
  "court martial",
  "appeal",
  "retrial",
  "judicial proceedings",
  "test",
  "tryout",
  "experiment",
  "examination",
  "check",
  "assessment",
  "evaluation",
  "appraisal",
  "probation",
  "testing",
  "audition",
  "screen test",
  "assay",
  "pilot study",
  "trial/test period",
  "trial/test run",
  "dummy run",
  "contest",
  "tournament",
  "match",
  "game",
  "round",
  "heat",
  "fixture",
  "event",
  "meet",
  "encounter",
  "race",
  "bout",
  "fight",
  "prize fight",
  "quiz",
  "trials",
  "stakes",
  "clash",
  "nuisance",
  "pest",
  "bother",
  "irritant",
  "worry",
  "problem",
  "inconvenience",
  "vexation",
  "plague",
  "bore",
  "trouble",
  "anxiety",
  "burden",
  "affliction",
  "ordeal",
  "tribulation",
  "adversity",
  "hardship",
  "tragedy",
  "trauma",
  "reverse",
  "setback",
  "difficulty",
  "misfortune",
  "bad luck",
  "mishap",
  "misadventure",
  "suffering",
  "distress",
  "misery",
  "wretchedness",
  "unhappiness",
  "sadness",
  "woe",
  "grief",
  "pain",
  "travails",
  "source of irritation/annoyance",
  "source of aggravation",
  "thorn in one's flesh",
  "the bane of 's 's life",
  "'s 's cross to bear",
  "stroke of bad luck",
  "ill fortune",
  "test",
  "try out",
  "pilot",
  "assay",
  "carry out trials on",
  "put to the test",
  "put through its paces",
  "experiment with",
];
