export const definitions = [
  '"a triple murder"',
  '"triple somersaults"',
  '"a triple dark rum"',
  '"the copper energy cells had triple the efficiency of silicon cells"',
  '"two whiskies—triples, please"',
  '"grain prices were expected to triple"',
  '"the party more than tripled its share of the vote"',
  '"he tripled into right field"',
];
export const synonyms = [
  "three-way",
  "tripartite",
  "threefold",
  "treble",
  "three times",
  "three times as much as",
  "trio",
  "threesome",
  "triumvirate",
  "triad",
  "troika",
  "three",
  "treble",
  "increase by three",
];
