export const definitions = [
  '"a water trough"',
  '"a vast glacial trough"',
  '"learning a language is a series of peaks and troughs"',
];
export const synonyms = [
  'manger',
  'feed box',
  'feeder',
  'crib',
  'feeding container',
  'fodder rack',
  'channel',
  'conduit',
  'trench',
  'ditch',
  'gully',
  'drain',
  'culvert',
  'cut',
  'flume',
  'gutter',
  'furrow',
  'groove',
  'depression',
  'hollow',
  'indentation',
  'dent',
  'dint',
  'cavity',
  'concavity',
  'dip',
  'pit',
  'hole',
  'pothole',
  'sink',
  'sinkhole',
  'excavation',
  'crater',
  'valley',
  'basin',
  'bowl',
  'fossa',
  'lacuna',
  'protuberance',
];