export const definitions = [
  '"a true story"',
  '"of course it\'s true"',
  '"that is not true of the people I am talking about"',
  '"people are still willing to pay for true craftsmanship"',
  '"we believe in true love"',
  '"he has guessed my true intentions"',
  '"true, it faced north, but you got used to that"',
  '"it was a true depiction"',
  '"steer 085 degrees true"',
  '"he was a true friend"',
  '"this entirely new production remains true to the essence of Lorca\'s play"',
  '"we appeal to all good men and true to rally to us"',
];
export const synonyms = [
  'accurate',
  'correct',
  'verifiable',
  'faithful',
  'literal',
  'veracious',
  'so',
  'unelaborated',
  'unvarnished',
  'in accordance with reality',
  'what actually/really happened',
  'the case',
  'untrue',
  'false',
  'fallacious',
  'genuine',
  'authentic',
  'real',
  'actual',
  'proper',
  'veritable',
  'bona fide',
  'rightful',
  'legitimate',
  'legal',
  'lawful',
  'authorized',
  'recognized',
  'valid',
  'de jure',
  'sincere',
  'unfeigned',
  'unaffected',
  'heartfelt',
  'from the heart',
  'unpretended',
  'bogus',
  'phoney',
  'de facto',
  'insincere',
  'feigned',
  'genuine',
  'authentic',
  'real',
  'actual',
  'proper',
  'veritable',
  'bona fide',
  'bogus',
  'phoney',
  'accurate',
  'true to life',
  'faithful',
  'fact-based',
  'realistic',
  'close',
  'lifelike',
  'convincing',
  'correct',
  'unerring',
  'exact',
  'precise',
  'perfect',
  'on target',
  'on the mark',
  'vérité',
  'verisimilar',
  'veristic',
  'telling it like it is',
  'as it really happened',
  'inaccurate',
  'aligned',
  'level',
  'balanced',
  'straight',
  'plumb',
  'abreast',
  'side by side',
  'in alignment',
  'at the same height',
  'loyal',
  'faithful',
  'truehearted',
  'devoted',
  'dedicated',
  'staunch',
  'true-blue',
  'constant',
  'unswerving',
  'unwavering',
  'trustworthy',
  'trusty',
  'reliable',
  'dependable',
  'firm',
  'steady',
  'dutiful',
  'supportive',
  'disloyal',
  'faithless',
  'in keeping with',
  'in accord with',
  'in accordance with',
  'in line with',
  'befitting',
  'consistent with',
  'in harmony with',
  'in agreement with',
  'in character with',
  'compatible with',
  'congruent with',
  'commensurate with',
  'appropriate to',
  'as befits',
  'suitable for',
  'suited to',
];