export const definitions = [
  '"it had been a very trying day"',
  '"he tried to regain his breath"',
  '"I started to try and untangle the mystery"',
  '"I decided to try writing fiction"',
  '"three times he tried the maneuver and three times he failed"',
  '"none of them tried very hard"',
  '"everyone wanted to know if I\'d tried jellied eel"',
  '"these methods are tried and tested"',
  '"they decided to try for another baby"',
  '"she\'s not here, but you could try her room"',
  '"I tried the library but it was out on loan"',
  '"he tried all her friends but no one knew where she was"',
  '"I tried the doors, but they were locked"',
  '"he was arrested and tried for the murder"',
  '"such cases must be tried by a jury"',
  '"Mary tried everyone\'s patience to the limit"',
];
export const synonyms = [
  "stressful",
  "difficult",
  "taxing",
  "demanding",
  "tough",
  "hard",
  "heavy",
  "pressured",
  "testing",
  "frustrating",
  "fraught",
  "traumatic",
  "arduous",
  "grueling",
  "tiring",
  "fatiguing",
  "exhausting",
  "wearing",
  "annoying",
  "irritating",
  "exasperating",
  "maddening",
  "infuriating",
  "tiresome",
  "irksome",
  "troublesome",
  "bothersome",
  "vexatious",
  "easy",
  "painless",
  "accommodating",
  "attempt",
  "endeavor",
  "make an effort",
  "seek",
  "strive",
  "struggle",
  "do one's best",
  "do 's 's utmost",
  "undertake",
  "aim",
  "set out",
  "try one's hand at",
  "essay",
  "assay",
  "exert oneself",
  "do all one can",
  "take it on oneself",
  "test",
  "try out",
  "check out",
  "sample",
  "taste",
  "inspect",
  "investigate",
  "examine",
  "appraise",
  "evaluate",
  "assess",
  "trial",
  "pilot",
  "put to the test",
  "experiment with",
  "have a taste of",
  "put through its paces",
  "put into practice",
  "adjudicate",
  "consider",
  "hear",
  "adjudge",
  "examine",
  "pass judgment on",
  "tax",
  "strain",
  "test",
  "stretch",
  "sap",
  "drain",
  "exhaust",
  "wear out",
  "weary",
  "make severe demands on",
  "put a strain on",
  "tire out",
];
