export const definitions = [
  '"the idiocy of decimating rainforests"',
  '"every aspect of public administration throws up its own idiocies"',
];
export const synonyms = [
  "stupidity",
  "folly",
  "foolishness",
  "foolhardiness",
  "madness",
  "insanity",
  "lunacy",
  "silliness",
  "brainlessness",
  "thoughtlessness",
  "senselessness",
  "indiscretion",
  "irresponsibility",
  "injudiciousness",
  "imprudence",
  "rashness",
  "recklessness",
  "ineptitude",
  "inaneness",
  "inanity",
  "irrationality",
  "illogicality",
  "absurdity",
  "nonsense",
  "ludicrousness",
  "ridiculousness",
  "fatuousness",
  "fatuity",
  "asininity",
  "pointlessness",
  "meaninglessness",
  "futility",
  "fruitlessness",
  "lack of sense",
  "sense",
];
