export const definitions = [
  '"I feel like an idiot who swallowed every lie I was told"',
  '"the drivers around here are complete idiots"',
  '"he entered their employ and learnt their secrets by pretending to be an idiot"',
];
export const synonyms = [
  "fool",
  "halfwit",
  "nincompoop",
  "dunce",
  "dolt",
  "ignoramus",
  "cretin",
  "imbecile",
  "dullard",
  "moron",
  "simpleton",
  "clod",
  "tomfool",
  "noddy",
  "loggerhead",
  "spoony",
  "mooncalf",
  "clodpole",
  "genius",
];
