export const definitions = [
  '"one big kahuna runs the whole show"',
];
export const synonyms = [
  'VIP',
  'personality',
  'name',
  'big name',
  'household name',
  'star',
  'superstar',
  'celebutante',
  'leading light',
  'giant',
  'great',
  'master',
  'guru',
  'dignitary',
  'luminary',
  'worthy',
  'grandee',
  'lion',
  'notable',
  'notability',
  'personage',
  'panjandrum',
  'famous person',
  'very important person',
  'famous name',
  'public figure',
  'pillar of society',
  'nonentity',
  'wave',
  'breaker',
  'roller',
  'comber',
  'billow',
  'bombora',
  'swell',
  'white horses',
  'white caps',
];