export const definitions = [
  '"black-billed and yellow-billed cuckoos"',
  '"they were billed to appear but didn\'t show up"',
  '"he was billed as "the new Sean Connery.""',
  '"we shall be billing them for the damage caused"',
  '"he had been billed $3,000 for his license"',
  '"we billed her $400,000"',
];
export const synonyms = [
  "advertise",
  "promote",
  "announce",
  "post",
  "schedule",
  "program",
  "timetable",
  "slate",
  "give advance notice of",
  "put up in lights",
  "advertise",
  "promote",
  "announce",
  "post",
  "schedule",
  "program",
  "timetable",
  "slate",
  "call",
  "style",
  "label",
  "dub",
  "designate",
  "pronounce",
  "give advance notice of",
  "put up in lights",
  "describe as",
  "promote as",
  "publicize as",
  "talk up as",
  "invoice",
  "charge",
  "debit",
  "send an invoice to",
  "send a statement to",
  "invoice",
  "charge",
  "debit",
  "send an invoice to",
  "send a statement to",
];
