export const definitions = [
  '"with a deft motion of her nimble fingers"',
  '"she is well-read and intellectually nimble"',
];
export const synonyms = [
  "agile",
  "lithe",
  "sprightly",
  "acrobatic",
  "light-footed",
  "light",
  "fleet-footed",
  "spry",
  "lively",
  "active",
  "quick",
  "quick-moving",
  "graceful",
  "supple",
  "limber",
  "lissom",
  "flexible",
  "skillful",
  "deft",
  "dexterous",
  "adroit",
  "fleet",
  "lightsome",
  "nimble-footed",
  "light on one's feet",
  "stiff",
  "clumsy",
  "lumbering",
  "quick-thinking",
  "quick-witted",
  "quick",
  "alert",
  "alive",
  "lively",
  "wide awake",
  "ready",
  "observant",
  "astute",
  "perceptive",
  "perspicacious",
  "penetrating",
  "discerning",
  "shrewd",
  "sharp",
  "sharp-witted",
  "intelligent",
  "bright",
  "clever",
  "gifted",
  "able",
  "brainy",
  "brilliant",
  "nimble-witted",
  "quick off the mark",
  "dull",
];
