export const definitions = ['"the monkey leapt nimbly from rock to rock"'];
export const synonyms = [
  "agilely",
  "lithely",
  "acrobatically",
  "lightly",
  "easily",
  "spryly",
  "actively",
  "quickly",
  "smartly",
  "briskly",
  "gracefully",
  "supply",
  "lissomly",
  "flexibly",
  "skillfully",
  "deftly",
  "dexterously",
  "adroitly",
  "fleetly",
  "lightsomely",
  "clumsily",
];
