export const definitions = [
  '"Sheikh Zayed Bin Sultan al-Nahyan"',
];
export const synonyms = [
  'ruler',
  'sovereign',
  'lord',
  'overlord',
  'dynast',
  'leader',
  'monarch',
  'crowned head',
  'royal duke',
  'king',
  'emperor',
  'tsar',
  'grand duke',
  'elector',
  'potentate',
  'suzerain',
  'crown prince',
  'princeling',
  'prince regent',
  'mogul',
  'baron',
  'liege (lord)',
  'emir',
  'sultan',
  'maharaja',
  'raja',
  'atheling',
];