export const definitions = [
  '"the fatty sheath around nerve fibers"',
  '"a tight sheath of black and gold lurex"',
];
export const synonyms = [
  'scabbard',
  'case',
  'covering',
  'cover',
  'case',
  'casing',
  'envelope',
  'sleeve',
  'wrapper',
  'tunica',
  'capsule',
  'fascia',
  'neurilemma',
  'epimysium',
  'perimysium',
  'perineurium',
  'sarcolemma',
  'coleoptile',
  'coleorhiza',
  'ocrea',
  'condom',
  'contraceptive',
  'prophylactic',
  'protective',
  'Durex',
];