export const definitions = [
  '"a day of sunny spells and scattered showers"',
  '"a shower of dust sprinkled his face"',
  '"he was pleased by the shower of awards"',
  '"she turned off the shower and reached for a towel"',
  '"she had a nice refreshing shower"',
  '"she loved going to baby showers"',
  '"bits of broken glass showered over me"',
  '"his hooves showered sparks across the concrete floor"',
  '"hooligans showered him with rotten eggs"',
  '"he showered her with kisses"',
  '"senior officers showered praise on their young cadet"',
  '"she showered and went down to breakfast"',
];
export const synonyms = [
  "fall",
  "drizzle",
  "flurry",
  "sprinkling",
  "mizzle",
  "downpour",
  "deluge",
  "light fall",
  "volley",
  "cascade",
  "hail",
  "rain",
  "storm",
  "salvo",
  "bombardment",
  "barrage",
  "fusillade",
  "broadside",
  "cannonade",
  "avalanche",
  "deluge",
  "rush",
  "flood",
  "spate",
  "torrent",
  "cluster",
  "flurry",
  "wave",
  "outbreak",
  "outpouring",
  "profusion",
  "abundance",
  "plethora",
  "superabundance",
  "glut",
  "mass",
  "large number",
  "large quantity",
  "trickle",
  "dearth",
  "rain",
  "fall",
  "drizzle",
  "spray",
  "mizzle",
  "hail",
  "deluge",
  "flood",
  "inundate",
  "swamp",
  "submerge",
  "engulf",
  "bury",
  "overwhelm",
  "saturate",
  "glut",
  "overload",
  "beset",
  "overburden",
  "snow under",
  "lavish",
  "pour",
  "load",
  "heap",
  "waste",
  "squander",
  "bestow freely",
  "give freely",
  "give generously",
];
