export const definitions = [
  '"she was shrewd enough to guess the motive behind his gesture"',
  '"a shrewd career move"',
  '"a shrewd east wind"',
  '"a bayonet\'s shrewd thrust"',
];
export const synonyms = [
  'astute',
  'sharp-witted',
  'sharp',
  'acute',
  'intelligent',
  'clever',
  'alert',
  'canny',
  'media-savvy',
  'perceptive',
  'perspicacious',
  'observant',
  'discriminating',
  'sagacious',
  'sage',
  'wise',
  'far-seeing',
  'far-sighted',
  'cunning',
  'artful',
  'crafty',
  'wily',
  'calculating',
  'disingenuous',
  'long-headed',
  'sapient',
  'argute',
  'have all one\'s wits about one',
  'stupid',
  'unwise',
  'ingenuous',
];