export const definitions = [
  '"their horses shied at the unfamiliar sight"',
  '"don\'t shy away from saying what you think"',
  '"he tore the glasses off and shied them at her"',
];
export const synonyms = [
  "wince",
  "start",
  "recoil",
  "shrink",
  "pull back",
  "back away",
  "draw back",
  "withdraw",
  "blench",
  "cringe",
  "squirm",
  "quiver",
  "shudder",
  "shiver",
  "tremble",
  "quake",
  "shake",
  "quail",
  "cower",
  "waver",
  "falter",
  "hesitate",
  "blanch",
  "shy (away)",
  "shy away",
  "get cold feet",
  "stand firm",
  "flinch",
  "demur",
  "recoil",
  "hang back",
  "fight shy of",
  "disrelish",
  "have scruples about",
  "scruple about",
  "have misgivings about",
  "have qualms about",
  "be averse to",
  "be chary of",
  "not be in favor of",
  "be against",
  "be opposed to",
  "be diffident about",
  "be bashful about",
  "be shy about",
  "be coy about",
  "be loath to",
  "scruple to",
  "be reluctant to",
  "be unwilling to",
  "be disinclined to",
  "not be in the mood to",
  "be indisposed to",
  "be sorry to",
  "be slow to",
  "be hesitant to",
  "be ashamed to",
  "be afraid to",
  "hesitate to",
  "hate to",
  "not like to",
  "not have the heart to",
  "drag one's feet / heels over",
  "waver about",
  "vacillate about",
  "think twice about",
  "balk at",
  "quail at",
  "mind doing something",
  "throw",
  "toss",
  "fling",
  "hurl",
  "cast",
  "lob",
  "launch",
  "flip",
  "pitch",
  "dash",
  "aim",
  "direct",
  "propel",
  "bowl",
];
