export const definitions = [
  '"he used his wealth to bribe officials"',
  '"some people buy boats and cars to display their wealth"',
  '"the country\'s mineral wealth"',
  '"the tables and maps contain a wealth of information"',
];
export const synonyms = [
  "affluence",
  "prosperity",
  "opulence",
  "riches",
  "means",
  "substance",
  "luxury",
  "well-being",
  "plenty",
  "deep pockets",
  "Mammon",
  "money",
  "cash",
  "lucre",
  "capital",
  "principal",
  "treasure",
  "fortune",
  "finance",
  "assets",
  "possessions",
  "resources",
  "effects",
  "goods",
  "funds",
  "valuables",
  "property",
  "stock",
  "reserves",
  "securities",
  "holdings",
  "belongings",
  "chattels",
  "pelf",
  "ill-gotten gains",
  "poverty",
  "privation",
  "prosperity",
  "prosperousness",
  "successfulness",
  "affluence",
  "riches",
  "fortune",
  "opulence",
  "luxury",
  "comfort",
  "milk and honey",
  "life of ease",
  "the good life",
  "failure",
  "poverty",
  "abundance",
  "profusion",
  "plethora",
  "mine",
  "store",
  "treasury",
  "copiousness",
  "plenitude",
  "amplitude",
  "bounty",
  "cornucopia",
  "dearth",
  "lack",
];
