export const definitions = [
  '"I am in a pickle"',
  '"chunks of green tomatoes pickled in brine"',
];
export const synonyms = [
  'relish',
  'chutney',
  'chow chow',
  'piccalilli',
  'sauerkraut',
  'tsukemono',
  'achar',
  'marinade',
  'brine',
  'vinegar',
  'plight',
  'predicament',
  'mess',
  'difficulty',
  'trouble',
  'crisis',
  'problem',
  'quandary',
  'dilemma',
  'dire/desperate straits',
  'ticklish/tricky situation',
  'preserve',
  'souse',
  'marinate',
  'conserve',
  'bottle',
  'tin',
  'can',
  'pot',
];