export const definitions = [
  '"a splinter had pierced the skin"',
  '"I had to pierce another hole in my belt"',
  '"I pierced my nose and ears"',
  '"the dividing wall is pierced by arches and piers"',
  '"they were seeking to pierce the antiballistic-missile defenses"',
  '"a shrill voice pierced the air"',
];
export const synonyms = [
  'make a hole in',
  'penetrate',
  'puncture',
  'punch',
  'perforate',
  'riddle',
  'stab',
  'prick',
  'probe',
  'gore',
  'spike',
  'stick',
  'impale',
  'transfix',
  'lance',
  'tap',
  'bore (through)',
  'drill (through)',
  'make a hole in',
  'penetrate',
  'puncture',
  'punch',
  'perforate',
  'riddle',
  'stab',
  'prick',
  'probe',
  'gore',
  'spike',
  'stick',
  'impale',
  'transfix',
  'lance',
  'tap',
  'bore (through)',
  'drill (through)',
  'make a hole in',
  'perforate',
  'puncture',
  'prick',
  'hole',
  'riddle',
  'spike',
  'skewer',
  'spit',
  'stick',
  'pin',
  'needle',
  'pink',
  'transpierce',
  'put/punch holes in',
  'drill',
  'perforate',
  'puncture',
  'punch',
  'cut',
  'tunnel',
  'burrow',
  'mine',
  'dig (out)',
  'sink',
  'make',
  'create',
  'put',
  'drive',
  'gouge (out)',
  'penetrate',
  'percolate',
  'pervade',
  'permeate',
  'light up',
  'pass through',
  'burst through',
  'filter through',
];