export const definitions = [
  '"a strike by local airline pilots"',
  '"the crash had been due to pilot error"',
  '"he piloted the helicopter from Paris to Deauville"',
  '"the task of piloting the economy out of recession"',
  '"other schools were piloting such courses"',
];
export const synonyms = [
  'flyer',
  'aeronaut',
  'captain',
  'commander',
  'copilot',
  'wingman',
  'aircrew',
  'aviator',
  'aviatrix',
  'birdman',
  'airman/airwoman',
  'first/second officer',
  'navigator',
  'helmsman',
  'guide',
  'steersman',
  'coxswain',
  'leader',
  'director',
  'usher',
  'escort',
  'attendant',
  'sample',
  'experiment',
  'trial episode',
  'pilot episode',
  'pilot program',
  'fly',
  'control',
  'handle',
  'maneuver',
  'drive',
  'operate',
  'steer',
  'regulate',
  'monitor',
  'direct',
  'captain',
  'aviate',
  'be at the controls of',
  'navigate',
  'guide',
  'steer',
  'direct',
  'sail',
  'usher',
  'shepherd',
  'lead',
  'conduct',
  'escort',
  'convoy',
  'show the way to',
  'test',
  'trial',
  'try out',
  'assess',
  'investigate',
  'examine',
  'appraise',
  'evaluate',
  'check out',
  'put to the test',
  'carry out trials on',
  'experiment with',
];