export const definitions = [];
export const synonyms = [
  "flagpole",
  "flagstaff",
  "pole",
  "post",
  "rod",
  "support",
  "upright",
  "aerial",
  "transmitter",
  "barrier",
  "wicket",
  "wicket gate",
  "lychgate",
  "turnstile",
  "port",
  "moon gate",
  "five-barred gate",
  "kissing gate",
];
