export const definitions = [
  '"in the three weeks leading up to the attack, sixteen container ships had been boarded by pirates"',
  '"a pirate ship"',
  '"software pirates"',
  '"pirate recordings"',
  '"a pirate radio station"',
  '"his latest album has been pirated and downloaded so many times since its release that he\'s lost $10 million in sales"',
  '"the company is seeking compensation from people who pirated the movie"',
  '"nine ships were pirated off the coast of the country between 2006 and May of last year"',
];
export const synonyms = [
  "freebooter",
  "marauder",
  "raider",
  "buccaneer",
  "privateer",
  "corsair",
  "rover",
  "picaroon",
  "filibuster",
  "sea wolf",
  "water rat",
  "sea rover",
  "sea thief",
  "sea robber",
  "water thief",
  "sea rat",
  "marooner",
  "plagiarist",
  "plagiarizer",
  "copyright infringer",
  "plagiarize",
  "poach",
  "steal",
  "appropriate",
  "bootleg",
  "reproduce illegally",
  "infringe the copyright of",
  "copy illegally",
  "pillage",
  "loot",
  "rob",
  "raid",
  "ransack",
  "strip",
  "fleece",
  "ravage",
  "devastate",
  "maraud",
  "sack",
  "rape",
  "despoil",
  "spoil",
  "reave",
  "forage",
  "lay waste",
  "depredate",
  "spoliate",
];
