export const definitions = [
  '"a hairline crack down the middle of the glass"',
  '"he climbed into a crack between two rocks"',
  '"the door opened a tiny crack"',
  '"the company spotted a crack in their rival\'s defenses"',
  '"your butt crack should not be visible when you squat"',
  "\"I've got sand in my crack.I don't know how that's even possible\"",
  '"a loud crack of thunder"',
  '"she gave the thief a crack over the head with her rolling pin"',
  '"the boy\'s voice had an uncertain crack in it"',
  '"he knew about the gossip and would make the odd crack"',
  '"he loved the crack, the laughing"',
  '"they are having a great crack about shooting"',
  '"I thought I had a crack at winning"',
  '"he wanted to have a crack at the enemy"',
  '"he uses crack and cocaine"',
  '"a crack dealer"',
  '"the ice all over the lake had cracked"',
  '"a stone cracked the headlight glass on his car"',
  '"his face cracked into a smile"',
  '"she cracked an egg into the frying pan"',
  '"you can see how the landmasses have cracked up and moved around"',
  '"gingerly, he cracks open his door"',
  '"the witnesses cracked and the truth came out"',
  '"no one can crack them—they believe their story"',
  '"a shot cracked across the ridge"',
  '"he cracked his whip and galloped away"',
  '"she winced as her knees cracked against metal"',
  '"she cracked him across the forehead"',
  '""I want to get away," she said, her voice cracking"',
  '"a hacker cracked the codes used in internet software"',
  '"he cracked jokes which she didn\'t find very funny"',
  '"catalytic cracking"',
];
export const synonyms = [
  "split",
  "fissure",
  "crevice",
  "break",
  "fracture",
  "rupture",
  "breach",
  "rift",
  "cleft",
  "slit",
  "chink",
  "gap",
  "cranny",
  "interstice",
  "crazing",
  "split",
  "fissure",
  "crevice",
  "break",
  "fracture",
  "rupture",
  "breach",
  "rift",
  "cleft",
  "slit",
  "chink",
  "gap",
  "cranny",
  "interstice",
  "crazing",
  "bang",
  "report",
  "explosion",
  "detonation",
  "clap",
  "pop",
  "snap",
  "crackle",
  "knock",
  "tap",
  "clash",
  "crash",
  "smash",
  "smack",
  "blow",
  "bang",
  "hit",
  "punch",
  "knock",
  "thump",
  "rap",
  "bump",
  "thwack",
  "smack",
  "slap",
  "welt",
  "cuff",
  "box",
  "buffet",
  "joke",
  "witticism",
  "jest",
  "quip",
  "pun",
  "sally",
  "pleasantry",
  "epigram",
  "aphorism",
  "repartee",
  "banter",
  "bon mot",
  "jibe",
  "barb",
  "jeer",
  "sneer",
  "taunt",
  "insult",
  "slight",
  "affront",
  "slur",
  "insinuation",
  "funny remark",
  "witty remark",
  "cutting remark",
  "gathering",
  "function",
  "get-together",
  "celebration",
  "reunion",
  "festivity",
  "jamboree",
  "reception",
  "at-home",
  "soirée",
  "social",
  "dance",
  "ball",
  "ceilidh",
  "frolic",
  "carousal",
  "carouse",
  "fete",
  "hoedown",
  "shower",
  "bake",
  "cookout",
  "levee",
  "keg party",
  "corroboree",
  "luau",
  "simcha",
  "squash",
  "squeeze",
  "ding-dong",
  "social gathering",
  "social occasion",
  "social event",
  "social function",
  "bashment",
  "tertulia",
  "discussion",
  "talk",
  "chat",
  "gossip",
  "tête-à-tête",
  "heart-to-heart",
  "head-to-head",
  "exchange",
  "dialogue",
  "parley",
  "consultation",
  "conference",
  "confabulation",
  "palaver",
  "colloquy",
  "converse",
  "adda",
  "korero",
  "attempt",
  "try",
  "effort",
  "endeavor",
  "venture",
  "essay",
  "assay",
  "opportunity",
  "chance",
  "say",
  "stint",
  "spell",
  "time",
  "try",
  "attempt",
  "split",
  "fracture",
  "fissure",
  "rupture",
  "break",
  "snap",
  "cleave",
  "craze",
  "break down",
  "give way",
  "cave in",
  "crumble",
  "collapse",
  "go to pieces",
  "yield",
  "succumb",
  "founder",
  "lose control",
  "bang",
  "pop",
  "snap",
  "crackle",
  "crash",
  "thud",
  "thump",
  "boom",
  "ring out",
  "clap",
  "explode",
  "detonate",
  "go bang",
  "bump",
  "bang",
  "hit",
  "strike",
  "injure",
  "hurt",
  "damage",
  "bruise",
  "hit",
  "strike",
  "beat",
  "thump",
  "hammer",
  "knock",
  "rap",
  "pound",
  "thud",
  "punch",
  "bump",
  "thwack",
  "smack",
  "slap",
  "slam",
  "welt",
  "cuff",
  "pummel",
  "buffet",
  "box someone's ears",
  "solve",
  "resolve",
  "work out",
  "fathom",
  "decipher",
  "decode",
  "break",
  "clear up",
  "interpret",
  "translate",
  "get to the bottom of",
  "make head or tail of",
  "unravel",
  "disentangle",
  "untangle",
  "unfold",
  "elucidate",
  "find an/the answer to",
  "find a/the solution to",
  "puzzle out",
  "find the key to",
  "straighten out",
  "piece together",
  "break into",
  "force open",
  "break open",
  "prise open",
  "open without a key",
];
