export const definitions = [
  '"the baby slept peacefully in its cradle"',
  '"a society that would secure the welfare of its citizens from cradle to grave"',
  '"he saw Greek art as the cradle of European civilization"',
  '"she cradled his head in her arms"',
  '"the northeastern states cradled an American industrial revolution"',
  '"she cradled the receiver gently"',
];
export const synonyms = [
  "crib",
  "bassinet",
  "cot",
  "Moses basket",
  "carrycot",
  "beginnings",
  "seeds",
  "roots",
  "start",
  "launch",
  "debut",
  "rise",
  "emergence",
  "outset",
  "onset",
  "dawn",
  "dawning",
  "birth",
  "inception",
  "conception",
  "genesis",
  "commencement",
  "very beginnings",
  "early days",
  "early stages",
  "end",
  "birthplace",
  "fount",
  "fountainhead",
  "source",
  "spring",
  "fountain",
  "origin",
  "nursery",
  "root",
  "roots",
  "seat",
  "seed",
  "germ",
  "beginning",
  "start",
  "origination",
  "genesis",
  "birth",
  "dawning",
  "dawn",
  "emergence",
  "inception",
  "launch",
  "creation",
  "conception",
  "inauguration",
  "foundation",
  "outset",
  "fons et origo",
  "commencement",
  "wellspring",
  "radix",
  "place of origin",
  "breeding place",
  "early stages",
  "framework",
  "rack",
  "holder",
  "stand",
  "base",
  "support",
  "mounting",
  "mount",
  "platform",
  "prop",
  "horse",
  "rest",
  "chock",
  "plinth",
  "bottom",
  "trivet",
  "bracket",
  "frame",
  "subframe",
  "structure",
  "substructure",
  "chassis",
  "hold",
  "support",
  "prop up",
  "rest",
  "pillow",
  "bolster",
  "cushion",
  "shelter",
  "protect",
];
