export const definitions = [
  '"she paused to crunch a ginger snap"',
  '"footsteps began to crunch across the frozen rock"',
  '"the snow crunched as we walked"',
  '"two cab drivers who had just crunched fenders"',
  '"computers crunch data from real-world observations"',
  "\"Marco's fist struck Brian's nose with a crunch\"",
  '"when it comes to the crunch you chicken out"',
  '"the Fed would do what it could to ease America\'s credit crunch"',
];
export const synonyms = [
  "munch",
  "chomp",
  "champ",
  "bite",
  "gnaw",
  "masticate",
  "eat",
  "devour",
  "consume",
  "chew noisily",
  "chumble",
  "moment of truth",
  "critical point",
  "crux",
  "crisis",
  "zero hour",
  "showdown",
  "decision time",
  "point of no return",
];
