export const definitions = [
  '"he was bored and cranky after eight hours of working"',
  '"a cranky scheme to pipe ground-level ozone into the stratosphere"',
  '"the cranky elevator breaks down periodically"',
];
export const synonyms = [
  "bad-tempered",
  "irritable",
  "irascible",
  "tetchy",
  "testy",
  "grumpy",
  "grouchy",
  "crotchety",
  "ill-tempered",
  "ill-natured",
  "ill-humored",
  "peevish",
  "cross",
  "fractious",
  "disagreeable",
  "cantankerous",
  "curmudgeonly",
  "pettish",
  "crabbed",
  "crabby",
  "waspish",
  "prickly",
  "peppery",
  "touchy",
  "scratchy",
  "crusty",
  "splenetic",
  "shrewish",
  "short-tempered",
  "hot-tempered",
  "quick-tempered",
  "dyspeptic",
  "choleric",
  "bilious",
  "liverish",
  "cross-grained",
  "in a (bad) mood",
  "having gotten up on the wrong side of the bed",
  "as cross as two sticks",
  "eccentric",
  "bizarre",
  "weird",
  "peculiar",
  "odd",
  "quirky",
  "avant-garde",
  "unconventional",
  "off-center",
  "strange",
  "outlandish",
  "ridiculous",
  "ludicrous",
  "mad",
  "insane",
  "crazy",
  "absurd",
];
