export const definitions = [
  '"the stolen car she was riding in crashed into a tree"',
  '"a jet crashed 200 yards from the school"',
  '"the test pilot crashed a Hurricane fighter plane"',
  '"huge waves crashed down on us"',
  '"she crashed down the telephone receiver"',
  '"the thunder crashed"',
  '"silver prices crashed in early 1980"',
  '"the project was postponed because the computer crashed"',
  '"I\'ll crash in the back of the van for a couple of hours"',
  '"a car crash"',
  '"a pilot who survived the crash of his plane"',
  '"he slammed the phone down with a crash"',
  '"the crash of 1987"',
  '"a stock market crash"',
  '"the crash of the company meant that 150 jobs would go"',
  '"system crashes are an everyday hazard"',
];
export const synonyms = [
  "hit",
  "strike",
  "ram",
  "run into",
  "bump into",
  "impact",
  "smash into",
  "collide with",
  "be in collision with",
  "come into collision with",
  "smack into",
  "slam into",
  "bang into",
  "cannon into",
  "plow into",
  "meet head-on",
  "drive into",
  "knock into",
  "crack into/against",
  "dash against",
  "smash",
  "wreck",
  "bump",
  "write off",
  "dash",
  "batter",
  "pound",
  "pummel",
  "lash",
  "slam",
  "bang",
  "ram",
  "smack",
  "be hurled",
  "slam into",
  "boom",
  "crack",
  "roll",
  "clap",
  "explode",
  "bang",
  "blast",
  "resound",
  "reverberate",
  "rumble",
  "thunder",
  "ring out",
  "blare",
  "echo",
  "clash",
  "clang",
  "clank",
  "clatter",
  "smash",
  "sound loudly",
  "fill the air",
  "fail",
  "collapse",
  "go under",
  "founder",
  "cave in",
  "fold (up)",
  "be ruined",
  "go bankrupt",
  "become insolvent",
  "cease trading",
  "go into receivership",
  "go into liquidation",
  "be liquidated",
  "be wound up",
  "be closed (down)",
  "be shut (down)",
  "fail",
  "collapse",
  "go under",
  "founder",
  "cave in",
  "fold (up)",
  "be ruined",
  "go bankrupt",
  "become insolvent",
  "cease trading",
  "go into receivership",
  "go into liquidation",
  "be liquidated",
  "be wound up",
  "be closed (down)",
  "be shut (down)",
  "gatecrash",
  "invade",
  "come uninvited to",
  "sneak into",
  "slip into",
  "butt in on",
  "intrude on/into",
  "accident",
  "collision",
  "bump",
  "car crash",
  "derailment",
  "smash",
  "RTA",
  "wreck",
  "car accident",
  "road accident",
  "traffic accident",
  "multiple crash",
  "multiple collision",
  "rail accident",
  "air accident",
  "air crash",
  "road traffic accident",
  "bang",
  "smash",
  "smack",
  "crack",
  "boom",
  "bump",
  "thud",
  "thump",
  "slam",
  "clunk",
  "clonk",
  "clash",
  "clang",
  "report",
  "explosion",
  "detonation",
  "shot",
  "clangor",
  "racket",
  "din",
  "failure",
  "collapse",
  "foundering",
  "ruin",
  "ruination",
  "bankruptcy",
  "insolvency",
  "receivership",
  "liquidation",
  "closure",
  "shutting",
  "cessation of trading",
  "winding up",
];
