export const definitions = [
  '"I climbed the creaky stairs"',
  '""We don\'t know, do we," he said, creaky with self - restraint"',
  '"the country\'s creaky legal system"',
];
export const synonyms = [
  "aching",
  "achy",
  "painful",
  "arthritic",
  "rheumatic",
  "taut",
  "tight",
  "stark",
  "supple",
  "limber",
  "harsh",
  "grating",
  "jarring",
  "raspy",
  "discordant",
  "dissonant",
  "scratchy",
  "hoarse",
  "rough",
  "gravelly",
  "croaky",
  "croaking",
  "gruff",
  "husky",
  "throaty",
  "guttural",
  "stridulant",
  "old-fashioned",
  "outmoded",
  "out of fashion",
  "out of date",
  "unfashionable",
  "frumpish",
  "frumpy",
  "outdated",
  "dated",
  "out",
  "outworn",
  "old",
  "former",
  "dead",
  "musty",
  "old-time",
  "old-world",
  "behindhand",
  "past",
  "bygone",
  "archaic",
  "obsolescent",
  "obsolete",
  "ancient",
  "antiquated",
  "superannuated",
  "defunct",
  "medieval",
  "prehistoric",
  "antediluvian",
  "oldfangled",
  "conservative",
  "quaint",
  "anachronistic",
  "crusted",
  "feudal",
  "fusty",
  "moth-eaten",
  "démodé",
  "passé",
  "square-toed",
  "out of style",
  "old-fogeyish",
  "backward-looking",
  "olde worlde",
  "vieux jeu",
  "up to date",
  "ahead of one's time",
];
