export const definitions = [
  '"people of many creeds and cultures"',
  '"the godparents will then swear that they believe in the Creed and the Commandments"',
  '"not everyone follows a creed of acceptance and understanding"',
];
export const synonyms = [
  "faith",
  "religion",
  "church",
  "persuasion",
  "affiliation",
  "denomination",
  "sect",
  "body",
  "following",
  "communion",
  "order",
  "school",
  "fraternity",
  "brotherhood",
  "sisterhood",
  "religious belief(s)",
  "religious persuasion",
  "religious conviction",
  "religious group",
  "faith community",
  "doctrine",
  "teaching",
  "ideology",
  "ethic",
  "dogma",
  "tenet",
  "catechism",
  "credo",
  "beliefs",
  "principles",
  "canons",
  "maxims",
  "rules",
  "laws",
  "system of belief",
  "set of principles",
  "statement of beliefs",
  "profession of faith",
  "articles of faith",
  "morals",
  "morality",
  "principles",
  "ideals",
  "credo",
  "ethos",
  "virtues",
  "moral code",
  "moral stand",
  "moral principles",
  "moral values",
  "rights and wrongs",
  "rules of conduct",
  "standards (of behavior)",
  "dictates of conscience",
];
