export const definitions = [
  '"he cringed away from the blow"',
  '"I cringed at his stupidity"',
  '"learning about sex and sexuality can be seriously cringe"',
  '"this whole situation is so cringe"',
];
export const synonyms = [
  'cower',
  'shrink',
  'draw back',
  'pull back',
  'recoil',
  'start',
  'wince',
  'flinch',
  'blench',
  'blanch',
  'dodge',
  'duck',
  'crouch',
  'shudder',
  'shake',
  'tremble',
  'quiver',
  'quail',
  'quake',
  'kowtow',
  'bow and scrape',
  'grovel',
  'creep',
  'crawl',
  'toady',
  'fawn',
  'truckle',
  'dance attendance on',
  'flatter',
  'woo',
  'pay court to',
  'get around',
  'blandish',
  'shy (away)',
  'get cold feet',
  'be servile toward',
  'be sycophantic toward',
  'ingratiate oneself with',
  'curry favor with',
  'wince',
  'squirm',
  'blush',
  'flush',
  'go red',
  'feel embarrassed',
  'feel ashamed',
  'feel sheepish',
  'feel mortified',
  'wince with embarrassment',
];