export const definitions = [
  '"critics say many schools are not prepared to handle the influx of foreign students"',
  '"a film critic"',
];
export const synonyms = [
  "detractor",
  "censurer",
  "attacker",
  "fault-finder",
  "carper",
  "backbiter",
  "caviller",
  "reviler",
  "vilifier",
  "traducer",
  "disparager",
  "denigrator",
  "deprecator",
  "belittler",
  "asperser",
  "commentator",
  "observer",
  "monitor",
  "pundit",
  "expert",
  "authority",
  "arbiter",
  "interpreter",
  "exponent",
  "expounder",
  "writer",
  "author",
  "speaker",
  "reviewer",
  "appraiser",
  "evaluator",
  "analyst",
  "judge",
  "scholiast",
  "exegete",
];
