export const definitions = [
  '"zany humor"',
];
export const synonyms = [
  'eccentric',
  'bizarre',
  'weird',
  'peculiar',
  'odd',
  'quirky',
  'avant-garde',
  'unconventional',
  'off-center',
  'strange',
  'outlandish',
  'ridiculous',
  'ludicrous',
  'mad',
  'insane',
  'crazy',
  'absurd',
  'comic',
  'comical',
  'clownish',
  'farcical',
  'madcap',
  'silly',
  'lighthearted',
  'funny',
  'amusing',
  'diverting',
  'waggish',
  'hilarious',
  'chucklesome',
  'conventional',
  'sensible',
  'serious',
  'jester',
  'clown',
  'buffoon',
  'comic',
  'joker',
  'jokester',
  'merry andrew',
  'harlequin',
  'Pierrot',
  'Punchinello',
  'Pantaloon',
  'court jester',
  'wearer of the motley',
];