export const definitions = [
  '"a charcoal sketch"',
  '"a biographical sketch of Ernest Hemingway"',
  '"you can see how the first movement evolved from the composer\'s sketches"',
  '"a hilarious sketch for their latest BBC series"',
  '"as they talked, Modigliani began to sketch her"',
  '"Jeanne sketched and painted whenever she had the time"',
  '"they sketched out the prosecution case"',
  '"he sketched a graceful bow in her direction"',
];
export const synonyms = [
  "drawing",
  "outline",
  "diagram",
  "representation",
  "delineation",
  "design",
  "plan",
  "artist's impression",
  "tracing",
  "underdrawing",
  "cartoon",
  "maquette",
  "preliminary drawing",
  "ébauche",
  "esquisse",
  "croquis",
  "outline",
  "rundown",
  "run-through",
  "bones",
  "bare bones",
  "skeleton",
  "summary",
  "synopsis",
  "recapitulation",
  "summarization",
  "abstract",
  "precis",
  "résumé",
  "tour d'horizon",
  "wrap-up",
  "description",
  "portrait",
  "vignette",
  "cameo",
  "profile",
  "portrayal",
  "depiction",
  "brief idea",
  "main points",
  "thumbnail sketch",
  "brief description",
  "potted biography",
  "skit",
  "scene",
  "piece",
  "performance",
  "act",
  "item",
  "turn",
  "routine",
  "number",
  "playlet",
  "joker",
  "jester",
  "wit",
  "wag",
  "comic",
  "wisecracker",
  "punner",
  "jokester",
  "prankster",
  "clown",
  "fool",
  "buffoon",
  "draw",
  "depict",
  "portray",
  "represent",
  "delineate",
  "pencil",
  "rough out",
  "outline",
  "make a drawing of",
  "draw a picture of",
  "describe",
  "outline",
  "rough out",
  "block out",
  "chalk out",
  "map out",
  "delineate",
  "indicate",
  "summarize",
  "precis",
  "recapitulate",
  "give a brief idea of",
  "give a rundown of",
  "give a thumbnail sketch of",
  "trace out",
  "give a summary of",
  "give an abstract/precis/résumé of",
];
