export const definitions = [
  '"his skinny arms"',
  '"a skinny black dress"',
  '"in the winter I live in skinny jeans and boots"',
  '"I love jeans—either bootcut or skinny"',
  '"a pair of skinny cords"',
  '"one skinny latte to go, please"',
  '"if you\'re tired of squeezing into your skinnies, bell - bottoms and flares are back in fashion"',
  '"the inside skinny is that he didn\'t know the deal was in the works"',
];
export const synonyms = [
  'thin',
  'scrawny',
  'scraggly',
  'bony',
  'angular',
  'rawboned',
  'gaunt',
  'as thin as a rake',
  'sticklike',
  'size-zero',
  'emaciated',
  'skeletal',
  'pinched',
  'undernourished',
  'underfed',
  'slim',
  'lean',
  'slender',
  'rangy',
  'lanky',
  'spindly',
  'gangly',
  'gangling',
  'gawky',
  'starveling',
  'macilent',
  'hollow-cheeked',
  'skin-and-bones',
  'spindle-shanked',
  'fat',
  'plump',
  'obese',
];