export const definitions = [
  '"in the old days, business was carried on at a rather more sedate pace"',
  '"sedate suburban domesticity"',
  '"she was heavily sedated"',
];
export const synonyms = [
  "calm",
  "tranquil",
  "placid",
  "composed",
  "serene",
  "steady",
  "unruffled",
  "imperturbable",
  "unflappable",
  "dignified",
  "serious",
  "serious-minded",
  "formal",
  "decorous",
  "proper",
  "prim",
  "demure",
  "sober",
  "earnest",
  "staid",
  "stiff",
  "stuffy",
  "boring",
  "slow",
  "unhurried",
  "relaxed",
  "leisurely",
  "slow-moving",
  "easy",
  "easygoing",
  "gentle",
  "comfortable",
  "restful",
  "undemanding",
  "lazy",
  "languid",
  "languorous",
  "plodding",
  "dawdling",
  "leisured",
  "measured",
  "unrushed",
  "slow-going",
  "slow and steady",
  "exciting",
  "wild",
  "fast",
  "tranquillize",
  "pacify",
  "soothe",
  "relax",
  "dope",
  "drug",
  "knock out",
  "anesthetize",
  "stupefy",
  "quieten",
  "quiet",
  "give a sedative to",
  "put under sedation",
  "calm down",
  "administer drugs/narcotics/opiates to",
  "invigorate",
  "energize",
];
