export const definitions = [
  '"a serial publication"',
  '"the use of serial verbs"',
  '"a suspected serial rapist"',
  '"he was a serial adulterer"',
  '"serial monogamy"',
  '"the harmonic flow of serial music"',
  '"Schoenberg\'s serial revolution"',
  '"a new three-part drama serial"',
];
export const synonyms = [
  "consecutive",
  "in a row",
  "straight",
  "solid",
  "sequential",
  "succeeding",
  "in succession",
  "following",
  "running",
  "continuous",
  "unbroken",
  "uninterrupted",
  "seriate",
  "sequential",
  "consecutive",
  "in sequence",
  "in order",
  "ordered",
  "progressive",
  "historical",
  "in order of time",
  "random",
  "program",
  "production",
  "situation comedy",
  "soap opera",
  "set of programs",
  "journal",
  "publication",
  "magazine",
  "newspaper",
  "paper",
  "review",
  "digest",
  "gazette",
  "newsletter",
  "organ",
  "annual",
  "quarterly",
  "monthly",
  "bimonthly",
  "fortnightly",
  "weekly",
  "biweekly",
];
