export const definitions = [];
export const synonyms = [
  "homily",
  "address",
  "speech",
  "talk",
  "discourse",
  "oration",
  "lesson",
  "preaching",
  "teaching",
  "peroration",
  "lecture",
  "tirade",
  "harangue",
  "diatribe",
  "speech",
  "disquisition",
  "monologue",
  "declamation",
  "exhortation",
  "reprimand",
  "reproach",
  "reproof",
  "scolding",
  "admonishment",
  "admonition",
  "remonstration",
  "upbraiding",
  "castigation",
  "lambasting",
  "criticism",
  "censure",
  "rating",
  "reproval",
  "commendation",
  "pat on the back",
];
