export const definitions = [
  '"the Jazz Club presents a new sextet"',
  '"the sextet from \"The Marriage of Figaro\""',
  '"a sextet of new releases"',
];
export const synonyms = [
  'group',
  'band',
  'orchestra',
  'combo',
  'company',
  'troupe',
  'cast',
  'chorus',
  'corps',
  'circle',
  'association',
  'duo',
  'trio',
  'quartet',
  'quintet',
  'septet',
  'octet',
  'nonet',
];