export const definitions = [
    '"his clothes were ablaze"',
    '"farm buildings were set ablaze"',
    '"New England is ablaze withcolor in autumn"',
    '"his eyes were ablaze with excitement"',
]
export const synonyms = [
    'alight',
    'aflame',
    'on fire',
    'in flames',
    'flaming',
    'burning',
    'blazing',
    'raging',
    'fiery',
    'lit',
    'lighted',
    'ignited',
    'afire',
    'extinguished',
    'alight',
    'gleaming',
    'glowing',
    'aglow',
    'illuminated',
    'brilliant',
    'bright',
    'shining',
    'radiant',
    'shimmering',
    'sparkling',
    'flashing',
    'dazzling',
    'luminous',
    'lustrous',
    'incandescent',
    'lit up',
    'dark',
    'passionate',
    'impassioned',
    'aroused',
    'excited',
    'stimulated',
    'eager',
    'animated',
    'incensed',
    'intense',
    'heated',
    'ardent',
    'fervent',
    'frenzied',
    'feverish',
]