export const definitions = [
    '"rumors of a further scandal abound"',
    '"this land abounds with wildlife"',
]
export const synonyms = [
    'proliferate',
    'superabound',
    'thrive',
    'flourish',
    'be thick on the ground',
    'be plentiful',
    'be abundant',
    'be numerous',
    'be scarce',
    'swarm with',
    'be full of',
    'overflow with',
    'teem with',
    'be packed with',
    'be crowded with',
    'be thronged with',
    'be jammed with',
    'be alive with',
    'be overrun with',
    'bristle with',
    'be bristling with',
    'be infested with',
    'be thick with',
    'pullulate with',
]