export const definitions = [
  '"the allegations are patently absurd"',
  '"so you think I\'m a spy ? How absurd!"',
  '"she was being absurd—and imagining things"',
  '"he had a keen eye for the incongruous and the absurd"',
  '"it may look absurd, but having a treadmill desk could improve your attention span"',
];
export const synonyms = [
  'preposterous',
  'ridiculous',
  'ludicrous',
  'farcical',
  'laughable',
  'risible',
  'idiotic',
  'stupid',
  'foolish',
  'silly',
  'inane',
  'imbecilic',
  'insane',
  'harebrained',
  'unreasonable',
  'irrational',
  'illogical',
  'nonsensical',
  'pointless',
  'senseless',
  'outrageous',
  'shocking',
  'astonishing',
  'monstrous',
  'fantastic',
  'incongruous',
  'grotesque',
  'unbelievable',
  'incredible',
  'unthinkable',
  'implausible',
  'reasonable',
  'sensible',
  'laughable',
  'ridiculous',
  'comical',
  'comic',
  'amusing',
  'funny',
  'hilarious',
  'humorous',
  'droll',
  'entertaining',
  'diverting',
  'farcical',
  'slapstick',
  'silly',
  'facetious',
  'ludicrous',
  'hysterical',
  'uproarious',
  'riotous',
  'sidesplitting',
  'zany',
  'grotesque',
  'killing',
  'derisible',
  'chucklesome',
  'serious',
];