export const definitions = [
    '"______ children"',
    '"an ______ rescue dog"',
    '"\"next generation\" is an ______ term"',
    '"food can be an ______ substance"',
    '"the judge ______ his power by imposing the fines"',
    '"at various times in her life she ______ both alcohol and drugs"',
    '"riders who abuse their horses should be prosecuted"',
    '"he was a depraved man who had ______ his two young daughters"',
    '"he had been abusing his body for years"',
    '"the referee was ______ by players from both teams"'
];
export const synonyms = [
    'misuse',
    'misapply',
    'misemploy',
    'mishandle',
    'exploit',
    'pervert',
    'take advantage of',
    'mistreat',
    'maltreat',
    'ill-treat',
    'ill-use',
    'misuse',
    'knock around',
    'manhandle',
    'mishandle',
    'maul',
    'molest',
    'grope',
    'assault',
    'hit',
    'strike',
    'beat',
    'injure',
    'hurt',
    'harm',
    'damage',
    'wrong',
    'bully',
    'persecute',
    'oppress',
    'torture',
    'treat badly',
    'handle/treat roughly',
    'interfere with',
    'indecently assault',
    'sexually abuse',
    'sexually assault',
    'look after',
    'practice onanism',
    'mistreat',
    'maltreat',
    'ill-treat',
    'ill-use',
    'misuse',
    'knock around',
    'manhandle',
    'mishandle',
    'maul',
    'molest',
    'grope',
    'assault',
    'hit',
    'strike',
    'beat',
    'injure',
    'hurt',
    'harm',
    'damage',
    'wrong',
    'bully',
    'persecute',
    'oppress',
    'torture',
    'treat badly',
    'handle/treat roughly',
    'interfere with',
    'indecently assault',
    'sexually abuse',
    'sexually assault',
    'look after',
    'insult',
    'curse',
    'call someone names',
    'taunt',
    'scold',
    'rebuke',
    'upbraid',
    'reprove',
    'castigate',
    'impugn',
    'slur',
    'revile',
    'smear',
    'vilify',
    'slander',
    'libel',
    'offend',
    'slight',
    'disparage',
    'denigrate',
    'defame',
    'miscall',
    'be rude to',
    'swear at',
    'shout at',
    'inveigh against',
    'vituperate against',
    'cast aspersions on',
    'compliment',
    'flatter'
]