export const definitions = [
    '"the cool air was a relief to my aching head"',
    '"an aching feeling of nostalgia"',
    '"my legs ached from the previous day\'s exercise"',
    '"I\'m aching all over"',
    '"she sat still and silent, her heart aching"',
    '"she looked so tired that my heart ached for her"',
    '"she ached for his touch"',
    '"he was aching to get his hands on the ball"',
]
export const synonyms = [
    'painful',
    'achy',
    'sore',
    'stiff',
    'hurt',
    'tender',
    'uncomfortable',
    'troublesome',
    'hurting',
    'throbbing',
    'pounding',
    'twingeing',
    'smarting',
    'gnawing',
    'burning',
    'tingling',
    'stinging',
    'agonizing',
    'searing',
    'in pain',
    'feeling tender',
    'feeling uncomfortable',
    'giving someone trouble',
    'sorrowful',
    'sad',
    'mournful',
    'miserable',
    'upset',
    'distressed',
    'anguished',
    'grief-stricken',
    'wretched',
    'heavy',
    'grieving',
    'sorrowing',
    'mourning',
    'lamenting',
    'suffering',
    'bleeding',
    'heavy with grief',
    'in distress',
    'in anguish',
    'cheerful',
    'light',
    'painful',
    'achy',
    'sore',
    'stiff',
    'hurt',
    'tender',
    'uncomfortable',
    'troublesome',
    'hurting',
    'throbbing',
    'pounding',
    'twingeing',
    'smarting',
    'gnawing',
    'burning',
    'tingling',
    'stinging',
    'agonizing',
    'searing',
    'throb',
    'pound',
    'twinge',
    'smart',
    'gnaw',
    'burn',
    'tingle',
    'sting',
    'in pain',
    'feeling tender',
    'feeling uncomfortable',
    'giving someone trouble',
    'be sore',
    'be painful',
    'be in pain',
    'be uncomfortable',
    'be tender',
    'give someone trouble',
    'sorrowful',
    'sad',
    'mournful',
    'miserable',
    'upset',
    'distressed',
    'anguished',
    'grief-stricken',
    'wretched',
    'heavy',
    'grieving',
    'sorrowing',
    'mourning',
    'lamenting',
    'suffering',
    'bleeding',
    'grieve',
    'sorrow',
    'mourn',
    'lament',
    'agonize',
    'anguish',
    'suffer',
    'bleed',
    'eat one\'s heart out',
    'heavy with grief',
    'in distress',
    'in anguish',
    'be sorrowful',
    'be sad',
    'be distressed',
    'be in distress',
    'be miserable',
    'be mournful',
    'be in anguish',
    'weep and wail',
    'cheerful',
    'light',
    'rejoice',
    'crave',
    'desire',
    'covet',
    'long for',
    'yearn for',
    'hunger for',
    'thirst for',
    'hanker for',
    'hanker after',
    'pine for',
    'pine after',
    'itch for',
    'be desperate for',
    'be unable to wait for',
    'be athirst for',
    'suspire for',
]