export const definitions = [
  '"she studied ______ in New York"',
  '"______ director"',
  '"______ in self-defense"',
  '"we should be ______ to reduce pollution"',
  '"they followed the man who was seen ______ suspiciously"',
  '"______ as if one owned the place"',
  '"blood samples are analyzed to find out how the drug is ______ in the body"',
  '"______ in her first professional role"',
  '"______ dumb at first"',
];
export const synonyms = [
  'drama',
  'the theater',
  'the stage',
  'dramatics',
  'dramaturgy',
  'stagecraft',
  'theatricals',
  'theatrics',
  'show business',
  'performing',
  'performance',
  'portraying',
  'portrayal',
  'thespianism',
  'histrionics',
  'the performing arts',
  'dramatic art',
  'the thespian art',
  'playing a role',
  'appearing on stage',
  'substitute',
  'deputy',
  'reserve',
  'fill-in',
  'stand-in',
  'caretaker',
  'temporary',
  'short-term',
  'provisional',
  'interim',
  'intervening',
  'pro tem',
  'improvised',
  'surrogate',
  'stopgap',
  'transitional',
  'changeover',
  'pro tempore',
  'ad interim',
  'permanent',
  'take the initiative',
  'move',
  'make a move',
  'react',
  'proceed',
  'go ahead',
  'take action',
  'take steps',
  'take measures',
  'do something',
  'make progress',
  'make headway',
  'be active',
  'be employed',
  'be busy',
  'do nothing',
  'behave',
  'function',
  'perform',
  'conduct oneself',
  'acquit oneself',
  'bear oneself',
  'comport oneself',
  'deport oneself',
  'affect',
  'influence',
  'work on',
  'alter',
  'change',
  'modify',
  'transform',
  'condition',
  'control',
  'have an effect on',
  'exert influence on',
  'have an impact on',
  'impact on',
  'have no effect on',
  'perform',
  'play',
  'play a part',
  'take part',
  'appear',
  'theatrics',
  'be one of the cast',
  'pretend',
  'playact',
  'sham',
  'fake',
  'feign',
  'bluff',
  'pose',
  'posture',
  'masquerade',
  'dissemble',
  'dissimulate',
  'put it on',
];