export const definitions = [
    '"the estimate was much less than the ______ cost"',
    '"those were his ______ words"',
    '"the book could be condensed into half the space, but what of the ______ content?"',
    '"using ______ income to measure expected income"'
];
export const synonyms = [
    'real',
    'true',
    'genuine',
    'authentic',
    'verified',
    'attested',
    'confirmed',
    'definite',
    'hard',
    'plain',
    'clear',
    'clear-cut',
    'undeniable',
    'veritable',
    'existing',
    'existent',
    'manifest',
    'substantial',
    'nonfictional',
    'factual',
    'unquestionable',
    'indisputable',
    'effective',
    'realistic',
    'de facto',
    'bona fide',
    'unimaginary',
    'notional',
    'nonexistent',
    'exact',
    'particular',
    'very',
    'specific',
    'distinct',
    'current',
    'present',
    'existing',
    'existent',
    'extant',
    'urgent',
    'pressing',
    'instant',
    'past',
    'future'
]