export const definitions = [
    '"the music is played adagio with very slight dynamic change"',
    '"the beautiful adagio ending of the piece was just too loud"',
]
export const synonyms = [
    'unhurriedly',
    'leisurely',
    'steadily',
    'ploddingly',
    'heavily',
    'lento',
    'largo',
    'larghetto',
    'without hurrying',
    'at a leisurely pace',
    'at a slow pace',
    'taking one\'s time',
    'in \'s \'s own good time',
    'at a sn\'s \'s pace',
    'with heavy steps',
    'with leaden steps',
    'adagietto',
    'fast',
    'quickly',
    'rapidly',
    'unhurriedly',
    'leisurely',
    'steadily',
    'ploddingly',
    'heavily',
    'lento',
    'largo',
    'larghetto',
    'without hurrying',
    'at a leisurely pace',
    'at a slow pace',
    'taking one\'s time',
    'in \'s \'s own good time',
    'at a sn\'s \'s pace',
    'with heavy steps',
    'with leaden steps',
    'adagietto',
    'fast',
    'quickly',
    'rapidly',
]