export const definitions = [
    '"hospitals have had to be adapted for modern medical practice"',
    '"the policies can be adapted to suit individual needs and requirements"',
    '"mink are well adapted to hunting prey"',
    '"a large organization can be slow to adapt to change"',
    '"the miniseries was adapted from Wouk\'s novel"',
]
export const synonyms = [
    'modify',
    'alter',
    'change',
    'adjust',
    'convert',
    'transform',
    'redesign',
    'restyle',
    'refashion',
    'remodel',
    'reshape',
    'revamp',
    'rework',
    'redo',
    'reconstruct',
    'reorganize',
    'customize',
    'tailor',
    'improve',
    'amend',
    'refine',
    'make alterations to',
    'make adjustments to',
    'make improvements to',
    'preserve',
    'adjust',
    'acclimatize',
    'accommodate',
    'attune',
    'habituate',
    'acculturate',
    'conform',
    'come to terms with',
    'find one\'s feet',
    'fit in',
    'acclimate',
    'familiarize oneself with',
    'habituate oneself to',
    'become habituated to',
    'get used to',
    'orient oneself in',
    'condition oneself to',
    'reconcile oneself to',
    'resign oneself to',
    'become resigned to',
    'find one\'s way around',
    'become naturalized',
    'become seasoned',
    'get one\'s bearings',
    'blend in',
    'amend',
    'emend',
    'correct',
    'alter',
    'change',
    'edit',
    'copyedit',
    'rewrite',
    'redraft',
    'rescript',
    'recast',
    'rephrase',
    'rework',
    'update',
    'revamp',
    'preserve',
]