export const definitions = [
    '"paint won\'t adhere well to a greasy surface"',
    '"the people adhere to the Muslim religion"',
    '"the account adhered firmly to fact"',
]
export const synonyms = [
    'stick',
    'cling',
    'hold fast',
    'cohere',
    'bond',
    'attach',
    'stick fast',
    'be stuck',
    'be fixed',
    'be pasted',
    'be glued',
    'stick to',
    'hold to',
    'stand by',
    'go along with',
    'follow',
    'obey',
    'heed',
    'observe',
    'respect',
    'uphold',
    'fulfill',
    'support',
    'abide by',
    'comply with',
    'be faithful to',
    'act in accordance with',
    'pay attention to',
    'pay regard to',
    'cooperate with',
    'conform to',
    'submit to',
    'take to heart',
    'bear in mind',
    'be guided by',
    'be attached to',
    'be connected with',
    'be affiliated to',
    'be a member of',
    'give support to',
    'cleave to',
    'be loyal to',
    'remain true to',
    'flout',
    'ignore',
]