export const definitions = [
  '"the dining room adjoins a small library"',
];
export const synonyms = [
  'neighbor',
  'abut',
  'join',
  'conjoin',
  'touch',
  'meet',
  'be next to',
  'be adjacent to',
  'border (on)',
  'verge on',
  'butt up against',
  'butt up to',
  'bound on',
  'be contiguous with',
  'be connected to',
  'communicate with',
  'link up with',
  'extend as far as',
  'extend to',
  'connect with/to',
];