export const definitions = [
    '"he smoothed his hair and ______ed his tie"',
    '"the interest rate should be ______ed for inflation"',
    '"a harness that ______s to the correct fit"',
    '"she must be allowed to grieve and to ______ in her own way"',
    '"his eyes had ______ed tosemidarkness"',
    '"the insurance agent may have the responsibility of ______ing small losses"',
];
export const synonyms = [
    'modify',
    'alter',
    'regulate',
    'tune',
    'fine-tune',
    'calibrate',
    'balance',
    'adapt',
    'rearrange',
    'change',
    'rejig',
    'rework',
    'revamp',
    'remodel',
    'reshape',
    'convert',
    'transform',
    'tailor',
    'improve',
    'enhance',
    'customize',
    'repair',
    'fix',
    'correct',
    'rectify',
    'make good',
    'overhaul',
    'standardize',
    'normalize',
    'put in working order',
    'put right',
    'set right',
    'set to rights',
    'adapt',
    'accommodate',
    'acclimatize',
    'attune',
    'assimilate',
    'conform',
    'come to terms with',
    'acclimate',
    'become accustomed',
    'get used',
    'orient oneself',
    'reconcile oneself',
    'habituate oneself',
    'familiarize oneself with',
    'acquaint oneself with',
    'blend in with',
    'fit in with',
    'find one\'s feet in '
]
