export const definitions = [
    '"I admire your courage"',
    '"we were just admiring your garden"',
]
export const synonyms = [
    'applaud',
    'praise',
    'commend',
    'favor',
    'appreciate',
    'respect',
    'look up to',
    'acclaim',
    'compliment',
    'worship',
    'adore',
    'love',
    'cherish',
    'idolize',
    'lionize',
    'express admiration for',
    'approve of',
    'express approval for',
    'look on with favor',
    'think highly of',
    'rate highly',
    'hold in high regard',
    'hold in high esteem',
    'speak highly of',
    'put on a pedestal',
    'dote on',
    'be enamored of',
    'be infatuated with',
    'be taken with',
    'be attracted to',
    'find attractive',
    'loathe',
    'disapprove of',
]