export const definitions = [
    '"there are many people eager to _____ a baby"',
    '"this approach has been _____ed by many big banks"',
    '"we wouldn\'t be surprised to see more small businesses _____ this technology"',
    '"he _____ed a patronizing tone"',
    '"she was recently _____ed as Labour candidate for the constituency"',
    '"the committee voted 5-1 to _____ the proposal"'
];
export const synonyms = [
    'embrace',
    'take on',
    'acquire',
    'affect',
    'espouse',
    'assume',
    'appropriate',
    'arrogate',
    'approve',
    'endorse',
    'accept',
    'ratify',
    'validate',
    'rubber-stamp',
    'sanction',
    'support',
    'back',
    'agree to',
    'consent to',
    'accede to',
    'vote for',
    'abandon',
    'choose',
    'select',
    'pick',
    'pick out',
    'elect',
    'plump for',
    'name',
    'nominate',
    'designate',
    'appoint',
    'vote for',
    'settle on',
    'decide on',
    'single out',
    'opt for',
    'reject',
    'embrace',
    'take on',
    'acquire',
    'affect',
    'espouse',
    'assume',
    'appropriate',
    'arrogate',
    'approve',
    'endorse',
    'accept',
    'ratify',
    'validate',
    'rubber-stamp',
    'sanction',
    'support',
    'back',
    'agree to',
    'consent to',
    'accede to',
    'vote for',
    'abandon'
]
