export const definitions = [
    '"the advert currently runs during televised matches"',
    '"he got the chance to join NASA after seeing their job advert on their campus bulletin board"',
    '"he had failed to advert to the consequences that his conduct was having"',
]
export const synonyms = [
    'notice',
    'announcement',
    'bulletin',
    'commercial',
    'promotion',
    'blurb',
    'write-up',
    'display',
    'poster',
    'leaflet',
    'pamphlet',
    'flyer',
    'bill',
    'handbill',
    'handout',
    'circular',
    'brochure',
    'sign',
    'placard',
    'folder',
    'dodger',
    'affiche',
    'mention',
    'touch on',
    'cite',
    'name',
    'go into',
    'note',
    'point out',
    'call attention to',
    'bring up',
    'raise',
    'broach',
    'introduce',
    'moot',
    'make mention of',
    'make reference to',
    'allude to',
    'speak of/about',
    'talk of/about',
    'write about',
    'comment on',
    'deal with',
    'treat (of)',
    'advert to',
]