export const definitions = [
  '"I ______d him to go home"',
  '"he ______d caution"',
  '"we ______ against sending cash by mail"',
  '"\"Go to Paris,\" he ______d"',
  '"sleeping pills are not ______d"',
  '"you will be ______d of the requirements"',
  '"the lawyer ______d the court that his client wished to give evidence"',
];
export const synonyms = [
  'counsel',
  'guide',
  'direct',
  'instruct',
  'illuminate',
  'educate',
  'give counsel',
  'give counseling',
  'give guidance',
  'make recommendations',
  'offer suggestions',
  'offer opinions',
  'give hints',
  'give tips',
  'give pointers',
  'give direction(s)',
  'give instruction',
  'advocate',
  'suggest',
  'recommend',
  'commend',
  'urge',
  'admonish',
  'bid',
  'encourage',
  'enjoin',
  'push for',
  'endorse',
  'champion',
  'back',
  'support',
  'speak for',
  'call for',
  'promote',
  'prompt',
  'press for',
  'subscribe to',
  'campaign for',
  'argue for',
  'inform',
  'notify',
  'apprise',
  'brief',
  'send word',
  'warn',
  'forewarn',
  'give notice',
  'give intelligence',
  'keep posted',
  'acquaint with',
  'make familiar with',
  'make known to',
  'let know',
  'enlighten as to',
  'give information about',
  'keep up to date with',
  'update about',
];