export const definitions = [
  '"the board admitted responsibility for the affair"',
  '"I wanted the funeral to be a family affair"',
  '"what you do in your spare time is your affair"',
  '"commissions were created to advise on foreign affairs"',
  '"his time was spent in winding up his affairs"',
  '"his wife is having an affair"',
  '"her dress was a black low-cut affair"',
];
export const synonyms = [
  'event',
  'incident',
  'happening',
  'occurrence',
  'phenomenon',
  'eventuality',
  'episode',
  'interlude',
  'circumstance',
  'adventure',
  'experience',
  'case',
  'matter',
  'business',
  'thing',
  'proceedings',
  'set of circumstances',
  'business',
  'concern',
  'matter',
  'responsibility',
  'province',
  'preserve',
  'interest',
  'problem',
  'worry',
  'lookout',
  'transactions',
  'concerns',
  'matters',
  'activities',
  'dealings',
  'undertakings',
  'ventures',
  'proceedings',
  'business',
  'field',
  'sphere',
  'relationship',
  'love affair',
  'romance',
  'fling',
  'flirtation',
  'dalliance',
  'liaison',
  'entanglement',
  'involvement',
  'attachment',
  'intrigue',
  'relations',
  'affaire',
  'amour',
  'romantic entanglement',
  'affair of the heart',
  'affaire de/du cœur',
];