export const definitions = [
    '"an advertising ______"',
    '"the Environmental Protection ______"',
    '"canals carved by the ______ of running water"',
    '"a belief in various forms of supernatural ______"',
    '"the movies could be an ______ molding the values of the public"',
    '"a contract of ______"'
];
export const synonyms = [
    'business',
    'organization',
    'company',
    'firm',
    'office',
    'bureau',
    'concern',
    'service',
    'branch',
    'representative',
    'division',
    'section',
    'sector',
    'subsection',
    'subdivision',
    'unit',
    'branch',
    'arm',
    'wing',
    'segment',
    'compartment',
    'office',
    'bureau',
    'ministry',
    'action',
    'activity',
    'effect',
    'influence',
    'force',
    'power',
    'work',
    'means',
    'vehicle',
    'medium',
    'instrument',
    'mechanism',
    'route',
    'channel',
    'mode',
    'technique',
    'expedient',
    'intervention',
    'intercession',
    'involvement',
    'mediation',
    'arbitration',
    'interposing',
    'instrumentality',
    'auspices',
    'aegis',
    'good offices'
]