export const definitions = [
    '"the ______ time"',
    '"the ______ upon percentage"',
    '"all the republics are ______ on the necessity of a common defense policy"',
    '"we are ______ that what is needed is a catchy title"',
    '"I completely ______ with a recent editorial"',
    '"we both ______ on issues such as tougher penalties for criminals"',
    '"\"Yes, it\'s dreadful, isn\'t it,\" she ______"',
    '"she had ______ to go and see a movie with him"',
    '"the government has ______ a plan on the country\'s territorial waters"',
    '"the commission ______ on a proposal to limit imports"',
];
export const synonyms = [
    'settled',
    'established',
    'resolved',
    'determined',
    'concluded',
    'clinched',
    'designated',
    'allotted',
    'chosen',
    'ordained',
    'prescribed',
    'decreed',
    'set',
    'fixed',
    'concrete',
    'worked out',
    'set in stone',
    'undecided',
    'concur',
    'see eye to eye',
    'sympathize',
    'accord',
    'acknowledge',
    'admit',
    'concede',
    'grant',
    'own',
    'confess',
    'be of the same mind/opinion',
    'be in sympathy',
    'be united',
    'be as one man',
    'hold with',
    'endorse',
    'support',
    'back',
    'uphold',
    'recommend',
    'advocate',
    'second',
    'favor',
    'like',
    'tolerate',
    'appreciate',
    'countenance',
    'admire',
    'commend',
    'embrace',
    'applaud',
    'acclaim',
    'praise',
    'agree with',
    'subscribe to',
    'express one\'s approval of',
    'be in favor of',
    'think well of',
    'look on with favor',
    'give one\'s blessing to',
    'take kindly to',
    'be pleased with',
    'hold in regard/esteem',
    'condemn',
    'disapprove',
    'consent',
    'assent',
    'accede',
    'accept',
    'allow',
    'admit',
    'grant',
    'undertake',
    'go along with',
    'recognize',
    'acknowledge',
    'acquiesce in',
    'approve (of)',
    'comply with',
    'say yes to',
    'give one\'s approval to',
    'give something the nod',
    'reject',
    'settle',
    'decide',
    'shake hands',
    'arrange',
    'negotiate',
    'work out',
    'thrash out',
    'hammer out',
    'strike a bargain',
    'arrive at',
    'reach an agreement on',
    'come to terms about',
    'reach terms on',
    'make a deal',
    'match',
    'match up',
    'accord',
    'correspond',
    'conform',
    'coincide',
    'fit',
    'tally',
    'harmonize',
    'equate',
    'dovetail',
    'chime',
    'correlate',
    'be in harmony',
    'be in agreement',
    'be consistent',
    'be compatible',
    'be consonant',
    'be congruous',
    'be in tune',
    'be equivalent',
    'be parallel',
    'suit',
    'be agreeable to',
    'be good for',
    'be healthy for',
    'be acceptable to'
]

export const antonyms = [
    'disagree',
    'differ',
    'contradict',
]
