export const definitions = [
    '"I went to see my ailing mother"',
    '"the ailing economy"',
    '"exercise is good for whatever ails you"',
]
export const synonyms = [
    'ill',
    'unwell',
    'sick',
    'sickly',
    'poorly',
    'weak',
    'indisposed',
    'infirm',
    'debilitated',
    'delicate',
    'off color',
    'languishing',
    'valetudinarian',
    'dying',
    'at death\'s door',
    'failing',
    'poor',
    'inadequate',
    'deficient',
    'imperfect',
    'substandard',
    'flawed',
    'not well',
    'in poor/bad health',
    'in poor condition',
    'healthy',
    'strong',
    'successful',
    'trouble',
    'bother',
    'burden',
    'distress',
    'beset',
    'harass',
    'worry',
    'oppress',
    'annoy',
    'vex',
    'irritate',
    'exasperate',
    'strain',
    'stress',
    'tax',
    'torment',
    'plague',
    'blight',
    'bedevil',
    'pursue',
    'rack',
    'smite',
    'curse',
    'harrow',
    'grip',
    'visit',
    'take',
    'discommode',
    'cause trouble to',
    'cause suffering to',
    'comfort',
]