export const definitions = [
  '"the wedding pictures had pride of place in family ______"',
  '"unlike past ______, this latest is very influenced by jazz"',
];
export const synonyms = [
  'vinyl',
  'tape',
  'cassette',
  'disk',
  'compact disk',
  'CD',
  'recording',
  'release',
  'gramophone record',
  'LP',
  'long-player',
  'single',
  'forty-five',
  'twelve-inch (single)',
  'seventy-eight',
  '78',
  'phonograph record',
  'EP (extended-play)',
  'black disc',
];