export const definitions = [
    '"he was the only passenger to alight from the train"',
    '"visitors should alight at the Fort Road stop"',
    '"the conductor alights to push the cable car completely around"',
    '"a lovely blue swallow alighted on a branch"',
    '"the house was alight when the firemen arrived"',
    '"flammable liquid was set alight"',
    '"a single lamp was alight"',
    '"the boy\'s face was alight with excitement"',
]
export const synonyms = [
    'get off',
    'get down',
    'dismount',
    'disembark',
    'descend',
    'exit',
    'detrain',
    'deplane',
    'step off',
    'get on',
    'board',
    'land',
    'come down',
    'come to rest',
    'touch down',
    'light',
    'arrive',
    'descend',
    'settle',
    'perch',
    'roost',
    'sit',
    'rest',
    'fly off',
    'on fire',
    'ablaze',
    'aflame',
    'in flames',
    'flaming',
    'burning',
    'blazing',
    'raging',
    'fiery',
    'lit',
    'lighted',
    'ignited',
    'afire',
    'extinguished',
    'gleaming',
    'glowing',
    'aglow',
    'ablaze',
    'illuminated',
    'brilliant',
    'bright',
    'shining',
    'radiant',
    'shimmering',
    'sparkling',
    'flashing',
    'dazzling',
    'luminous',
    'incandescent',
    'lit up',
    'dark',
]