export const definitions = [
    '"gently brush the surface to _____ the fibers"',
    '"the domestic price ______ with prices in world markets"',
    '"the pattern of the border at the seam should _____ perfectly"',
    '"newspapers usually _____ themselves with certain political parties"',
    '"all of them must now _____ against the foe"',
    '"Trump ______ with Russia"',
    '"_____ oneself with"',
];
export const synonyms = [
    'line up',
    'range',
    'marshal',
    'orient',
    'place',
    'position',
    'dispose',
    'situate',
    'set',
    'arrange in line',
    'put in order',
    'put in rows/columns',
    'straighten (up)',
    'place',
    'position',
    'put',
    'dispose',
    'situate',
    'set',
    'orientate',
    'join forces with',
    'join up with',
    'form an alliance with',
    'ally with',
    'link up with',
    'go into league with',
    'combine with',
    'join fortunes with',
    'make common cause with',
    'ally',
    'affiliate',
    'associate',
    'join',
    'side',
    'sympathize',
    'unite',
    'combine',
    'join forces',
    'cooperate',
    'collaborate',
    'make common cause',
    'be in league',
    'join (up)',
    'form an alliance',
    'team up',
    'band together',
    'throw in one\'s lot'
]


