export const definitions = [
    '"he alleged that he had been assaulted"',
    '"he is alleged to have assaulted five men"',
    '"the offenses are alleged to have been committed outside the woman\'s home"',
    '"the first artifact ever alleged to be from Earh\'s \'s aircraft"',
]
export const synonyms = [
    'claim',
    'assert',
    'declare',
    'state',
    'proclaim',
    'maintain',
    'advance',
    'contend',
    'argue',
    'affirm',
    'aver',
    'avow',
    'attest',
    'testify',
    'swear',
    'certify',
    'give evidence',
    'charge',
    'accuse',
    'suggest',
    'imply',
    'hint',
    'insinuate',
    'indicate',
    'intimate',
    'impute',
    'plead',
    'pretend',
    'profess',
    'depose',
    'represent',
    'asseverate',
    'bear witness',
]