export const definitions = [
    '"he took a short cut along an alley"',
    '"there were a few muggings in the backstreets and alleys"',
    '"alleys of standing stones"',
]
export const synonyms = [
    'passage',
    'passageway',
    'alleyway',
    'back alley',
    'backstreet',
    'lane',
    'path',
    'pathway',
    'walk',
    'corridor',
    'aisle',
    'arcade',
    'gully',
    'allée',
    'ginnel',
    'snicket',
    'twitten',
    'twitchel',
    'vennel',
    'wynd',
]