export const definitions = [
    '"she had a way of alluding to Jean but never saying her name"',
    '"we will allude briefly to the main points"',
    '"the photographs allude to Italian Baroque painting"',
]
export const synonyms = [
    'suggest',
    'imply',
    'mention',
    'touch on',
    'cite',
    'refer to',
    'hint at',
    'mention in passing',
    'mention en passant',
    'speak briefly of',
    'make an allusion to',
    'advert to',
    'mention',
    'touch on',
    'cite',
    'name',
    'go into',
    'note',
    'point out',
    'call attention to',
    'bring up',
    'raise',
    'broach',
    'introduce',
    'moot',
    'make mention of',
    'make reference to',
    'allude to',
    'speak of/about',
    'talk of/about',
    'write about',
    'comment on',
    'deal with',
    'treat (of)',
    'advert to',
    'call up',
    'evoke',
    'echo',
    'bring to mind',
    'call to mind',
    'put one in mind of',
    'summon up',
    'conjure up',
    'allude to',
]