export const definitions = [
    '"they ambled along the riverbank"',
    '"he ambled into the foyer"',
    '"a peaceful riverside amble"',
]
export const synonyms = [
    'stroll',
    'saunter',
    'wander',
    'meander',
    'ramble',
    'dawdle',
    'promenade',
    'walk',
    'putter',
    'roam',
    'traipse',
    'stretch one\'s legs',
    'take the air',
    'perambulate',
    'peregrinate',
    'go for a walk',
    'take a walk',
    'get some exercise',
    'get some air',
    'stravaig',
    'stride',
    'walk',
    'hike',
    'trek',
    'wander',
    'stroll',
    'saunter',
    'roam',
    'traipse',
    'jaunt',
    'promenade',
    'trip',
    'excursion',
    'tour',
    'perambulation',
    'peregrination',
]