export const definitions = [
    '"seven members of a patrol were killed in an ambush"',
    '"kidnappers waiting in ambush"',
    '"they were ambushed and taken prisoner by the enemy"',
    '"representatives were ambushed by camera crews"',
]
export const synonyms = [
    'trap',
    'snare',
    'pitfall',
    'lure',
    'ambuscade',
    'surprise attack',
    'trap',
    'surprise',
    'waylay',
    'entrap',
    'ensnare',
    'bushwhack',
    'ambuscade',
    'attack by surprise',
    'pounce on',
    'lay a trap for',
    'set an ambush for',
    'lie in wait for',
]