export const definitions = [
    '"the sport gives an enormous ______ of pleasure to many people"',
    '"the substance is harmless if taken in small ______s"',
    '"they have spent a colossal ______ rebuilding the stadium"',
    '"losses ______ed to over 10 million dollars"',
    '"their actions ______ed to a conspiracy"',
    '"what this guy was doing clearly did ______ to persecution"',
    '"you\'ll never ______ to anything"'
];
export const synonyms = [
    'quantity',
    'number',
    'total',
    'aggregate',
    'sum',
    'quota',
    'group',
    'size',
    'mass',
    'weight',
    'volume',
    'bulk',
    'load',
    'consignment',
    'proportion',
    'portion',
    'part',
    'dose',
    'dosage',
    'quantum',
    'fee',
    'price',
    'tariff',
    'sum',
    'figure',
    'fare',
    'rate',
    'payment',
    'toll',
    'levy',
    'cost',
    'expense',
    'expenditure',
    'outlay',
    'dues',
    'add up to',
    'come to',
    'run to',
    'number',
    'be',
    'make',
    'total',
    'equal',
    'represent',
    'be equal to',
    'be equivalent to',
    'count as',
    'tot up to',
    'constitute',
    'comprise',
    'add up to',
    'come down to',
    'boil down to',
    'signify',
    'signal',
    'mean',
    'indicate',
    'suggest',
    'denote',
    'point to',
    'betoken',
    'be equivalent to',
    'be tantamount to',
    'approximate to',
    'be evidence of',
    'be symptomatic of',
    'become',
    'grow into',
    'develop into',
    'mature into',
    'prove to be',
    'turn out to be',
    'progress to',
    'advance to'
]
