export const definitions = [
  '"there is ample time for discussion"',
  '"an ample supply of consumer goods"',
  '"he leaned back in his ample chair"',
  '"she stood with her hands on her ample hips"',
];
export const synonyms = [
  'enough',
  'sufficient',
  'adequate',
  'abundant',
  'suitable',
  'satisfactory',
  'passable',
  'allowable',
  'tolerable',
  'plentiful',
  'copious',
  'profuse',
  'rich',
  'lavish',
  'liberal',
  'generous',
  'bountiful',
  'large',
  'huge',
  'great',
  'bumper',
  'flush',
  'overflowing',
  'superabundant',
  'infinite',
  'inexhaustible',
  'opulent',
  'prolific',
  'teeming',
  'bounteous',
  'plenteous',
  'plenty of',
  'more than enough',
  'enough and to spare',
  'insufficient',
  'meager',
  'spacious',
  'commodious',
  'capacious',
  'roomy',
  'sizeable',
  'substantial',
  'generous',
  'big',
  'large',
  'broad',
  'wide',
  'extensive',
  'voluminous',
  'loose-fitting',
  'baggy',
  'slack',
  'slouchy',
  'sloppy',
  'full',
  'spacey',
  'cramped',
  'tight-fitting',
];