export const definitions = [
  '"people looked on with amused curiosity"',
  '"he made faces to amuse her"',
  '"they amused themselves digging through an old encyclopedia"',
  '"the hotel has planned many activities to amuse its guests"',
];
export const synonyms = [
  'entertain',
  'delight',
  'divert',
  'gladden',
  'cheer (up)',
  'please',
  'charm',
  'tickle',
  'convulse',
  'beguile',
  'enliven',
  'regale',
  'occupy',
  'engage',
  'busy',
  'employ',
  'distract',
  'absorb',
  'engross',
  'preoccupy',
  'hold',
  'immerse',
  'interest',
  'involve',
  'make laugh',
  'hold someone\'s attention',
  'bore',
  'depress',
];