export const definitions = [
    '"the boat, no longer held fast by its ______, swung wildly"',
    '"an ______ chain"',
    '"the European Community is the economic ______ of the New Europe"',
    '"he signed off after nineteen years as CBS news ______"',
    '"the ship was ______ed in the lee of the island"',
    '"we ______ed in the harbor"',
    '"the tail is used as a hook with which the fish ______s itself to coral"',
    '"with cords and pitons they ______ed him to the rock"',
    '"the first baseman is ______ed to the bag"',
    '"it is important that policy be ______ed to some acceptable theoretical basis"',
    '"she ______ed a television documentary series in the early 1980s"'
];
export const synonyms = [
    'mainstay',
    'cornerstone',
    'bulwark',
    'foundation',
    'prop',
    'linchpin',
    'chief support',
    'main source of stability/security',
    'center',
    'focal point',
    'center of attention',
    'hub',
    'pivot',
    'nucleus',
    'heart',
    'cornerstone',
    'linchpin',
    'kingpin',
    'bedrock',
    'basis',
    'backbone',
    'cynosure',
    'central point',
    'announcer',
    // 'anchorman',
    // 'anchorwoman',
    // 'drop anchor',
    // 'be at anchor',
    // 'cast anchor',
    'newscaster',
    'broadcaster',
    'reporter',
    'presenter',
    'newsreader',
    'moor',
    'berth',
    'harbor',
    'tie up',
    'secure',
    'fasten',
    'attach',
    'connect',
    'bind',
    'affix',
    'fix',
    'make fast',
    'stick',
    'lodge',
    'implant',
    'embed',
    'host',
    'introduce',
    'announce',
    'compère',
    'be the presenter of'
]