export const definitions = [
    '"she could barely restrain her anger at this comment"',
    '"I was seething with anger and frustration"',
    '"venting his anger had calmed him a little"',
    '"she was angered by his terse answer"',
    '"he was angered that he had not been told"',
    '"I was angered to receive a further letter from them"',
]
export const synonyms = [
    'annoyance',
    'vexation',
    'exasperation',
    'crossness',
    'irritation',
    'irritability',
    'indignation',
    'pique',
    'displeasure',
    'resentment',
    'rage',
    'fury',
    'wrath',
    'outrage',
    'temper',
    'road rage',
    'air rage',
    'irascibility',
    'ill temper',
    'dyspepsia',
    'spleen',
    'ill humor',
    'tetchiness',
    'testiness',
    'waspishness',
    'ire',
    'choler',
    'bile',
    'pleasure',
    'good humor',
    'annoy',
    'irritate',
    'exasperate',
    'irk',
    'vex',
    'put out',
    'provoke',
    'pique',
    'gall',
    'displease',
    'enrage',
    'incense',
    'infuriate',
    'madden',
    'inflame',
    'antagonize',
    'make someone\'s blood boil',
    'make some\'s \'s hackles rise',
    'ruffle some\'s \'s feathers',
    'ruffle',
    'peeve',
    'aggravate',
    'needle',
    'bug',
    'nettle',
    'rile',
    'miff',
    'hack off',
    'empurple',
    'rub up the wrong way',
    'get someone',
    'pacify',
    'placate',
]