export const definitions = [
    '"the Angles and Saxons from modern-day Denmark and Germany began landing in eastern England"',
    '"in any triangle, the longest side is opposite the largest _____"',
    '"spring-loaded hinges open the doors to any _____ up to 90°"',
    '"a skylight in the _____ of the roof"',
    '"sloping at an _____ of 33° to the horizontal"',
    '"he trudged back, the _____ of his shoulders spelling dejection"',
    '"from this _____ Maggie could not see Naomi\'s face"',
    '"camera ______"',
    '"discussing the problems from every conceivable _____"',
    '"he always had a fresh _____ on life"',
    '"a prosecutor who downplayed the racial _____"',
    '"his chosen _____ was the language of the Old Testament"',
    '"Zimmer saw the world from an _____ that few could understand"',
    '"the supporting frame is usually of aluminum _____ bolted together"',
    '"he _____d his chair so that he could watch her"',
    '"Anna _____d her camera toward the tree"',
    '"the cab ______ across two lanes and skids to a stop"',
    '"the sun ______ into the dining room"',
    '"_____ your answer so that it is relevant to the job for which you are applying"',
    '"there are no big fish left to _____ for"',
    '"Ralph had begun to _____ for an invitation"',
    '"her husband was angling to get into the Cabinet"',
    '"you will be pleased too, if you find a Trout at one of our Angles"'
];
export const synonyms = [
    'corner',
    'intersection',
    'point',
    'apex',
    'cusp',
    'nook',
    'niche',
    'recess',
    'crook',
    'projection',
    'gradient',
    'slant',
    'inclination',
    'geometrical relation',
    'perspective',
    'point of view',
    'viewpoint',
    'standpoint',
    'position',
    'side',
    'aspect',
    'slant',
    'direction',
    'approach',
    'outlook',
    'light',
    'way of looking at something',
    'tilt',
    'slant',
    'point',
    'direct',
    'aim',
    'turn',
    'present',
    'slant',
    'orient',
    'skew',
    'distort',
    'twist',
    'bias',
    'give a particular slant to',
    'solicit',
    'look for',
    'try to get',
    'seek to obtain',
    'make a bid for',
    'aim for',
    'cast around for',
    'hope for'
]
