______
export const definitions = [
    '"he sent an ______ shot into the net"',
    '"a sharply ______ flight of stairs"',
    '"a right-______ bend"',
    '"an obtuse-______ triangle"',
    '"______ views on dancing"',
    '"he ______ his chair so that he could watch her"',
    '"Anna ______ her camera toward the tree"',
    '"the cab ______ across two lanes and skidded to a stop"',
    '"the sun ______ into the dining room"',
    '"_____ your answer so that it is relevant to the job for which you are applying"',
    '"there are no big fish left to _____ for"',
    '"Ralph had begun to _____ for an invitation"',
    '"her husband had ______ to get a Cabinet position"'
];
export const synonyms = [
    'crossways',
    'crosswise',
    'slanting',
    'slanted',
    'aslant',
    'slant',
    'slantwise',
    'sloping',
    'oblique',
    'inclined',
    'inclining',
    'tilted',
    'tilting',
    'cornerwise',
    'squint',
    'cater-cornered',
    'catty-cornered',
    'kitty-corner',
    'from corner to corner',
    'cater-corner',
    'tilt',
    'slant',
    'point',
    'direct',
    'aim',
    'turn',
    'present',
    'slant',
    'orient',
    'skew',
    'distort',
    'twist',
    'bias',
    'give a particular slant to',
    'solicit',
    'look for',
    'try to get',
    'seek to obtain',
    'make a bid for',
    'aim for',
    'cast around for',
    'hope for'
]
