export const definitions = [
    '"eighth-century Northumberland annals"',
    '"the deed will live forever in the annals of infamy"',
    '"the annals of the famous European discoverers"',
    '"Annals of Internal Medicine"',
]
export const synonyms = [
    'records',
    'archives',
    'chronicles',
    'accounts',
    'registers',
    'journals',
    'history',
    'muniments',
    'diary',
    'log',
    'logbook',
    'weblog',
    'blog',
    'vlog',
    'moblog',
    'yearbook',
    'chronicle',
    'register',
    'notebook',
    'commonplace book',
    'history',
    'daybook',
    'day-by-day account',
    'daily record',
]