export const definitions = [
    '"your damned cheerfulness has always annoyed me"',
    '"rock music loud enough to annoy"',
    '"a gallant Saxon, who annoyed this Coast"',
]
export const synonyms = [
    'irritate',
    'vex',
    'anger',
    'exasperate',
    'irk',
    'gall',
    'pique',
    'put out',
    'displease',
    'antagonize',
    'get on someone\'s nerves',
    'ruffle',
    'ruffle someone\'s feathers',
    'make some\'s \'s hackles rise',
    'enrage',
    'infuriate',
    'madden',
    'make someone\'s blood boil',
    'goad',
    'provoke',
    'exacerbate',
    'hump',
    'rasp',
    'irritated',
    'cross',
    'angry',
    'vexed',
    'exasperated',
    'irked',
    'piqued',
    'displeased',
    'fed up',
    'disgruntled',
    'testy',
    'huffy',
    'resentful',
    'aggrieved',
    'furious',
    'irate',
    'infuriated',
    'incensed',
    'enraged',
    'wrathful',
    'choleric',
    'ireful',
    'snuffy',
    'wrath',
    'make angry',
    'make cross',
    'get/put someone\'s back up',
    'rub up the wrong way',
    'raise someone\'s hackles',
    'drive to distraction',
    'in a bad mood',
    'in a temper',
    'in high dudgeon',
    'in a huff',
    'please',
    'gratify',
]