export const definitions = [
  '"I told you, it\'s all right, and ______, it was my fault"',
  '"it\'s too late now ______"',
  '"What are you doing here, ______?"',
  '"______, Dot, I must go"',
  '"How she lives with him is beyond me. ______, I really like her"',
  '"Poor John always enjoyed a drink. ______, he died last year."',
  '"nobody invited Miss Honey to sit down so she sat down ______"',
];
export const synonyms = [
  'in any case',
  'in any event',
  'at any rate',
  'regardless',
  'however',
  'be that as it may',
  'at all events',
  'no matter what',
  'nonetheless',
  'even so',
  'however',
  'but',
  'still',
  'yet',
  'though',
  'be that as it may',
  'that said',
  'just the same',
  'all the same',
  'at the same time',
  'in any event',
  'come what may',
  'at any rate',
  'notwithstanding',
  'regardless',
  'anyhow',
  'howbeit',
  'withal',
  'natheless',
  'in spite of that/everything',
  'for all that',
  'despite that/everything',
  'after everything',
  'having said that',
];
