export const definitions = [
    '"smoke ______ed on the horizon"',
    '"the major life forms ______ed on earth"',
    '"the paperback edition didn\'t ______ for another two years"',
    '"he ______ed on six charges of theft"',
    '"he ______ed on Broadway"',
    '"the symbol ______s in many paintings of the period"',
    '"by ten o\'clock Bill still hadn\'t ______ed"',
    '"she ______ed not to know what was happening"',
    '"it ______s unlikely that interest rates will fall"',
    '"he ______ed unaware of the rebuke"'
]

export const synonyms = [
    'materialize',
    'take shape',
    'emerge',
    'surface',
    'come to light',
    'arise',
    'crop up',
    'occur',
    'develop',
    'become visible',
    'come into view',
    'come into sight',
    'be revealed',
    'be seen',
    'manifest itself',
    'become apparent',
    'become evident',
    'enter into the picture',
    'dis______',
    'vanish',
    'come out',
    'become available',
    'come on the market',
    'go on sale',
    'be published',
    'be produced',
    'come into existence',
    'perform',
    'play',
    'act',
    'take the part of',
    'take the role of',
    'feature',
    'participate',
    'play a part',
    'star',
    'be featured/mentioned',
    'be referred to',
    'play a role',
    'be conspicuous',
    'have prominence',
    'have a place',
    'arrive',
    'turn up',
    'make an ______ance',
    'come',
    'put in an ______ance',
    'get here/there',
    'present oneself',
    'seem',
    'look',
    'give the impression of being',
    'have the ______ance/air of being',
    'come across as being',
    'look as though one is',
    'look to be',
    'strike someone as'
]

