export const definitions = [
    '"a triumphal arch"',
    '"the delicate arch of his eyebrows"',
    '"the muscles in the arch of my right foot suddenly seized up"',
    '"a beautiful bridge that arched over a canal"',
    '"her eyebrows arched in surprise"',
    '"she arched her back"',
]
export const synonyms = [
    'archway',
    'vault',
    'span',
    'dome',
    'bridge',
    'curve',
    'bow',
    'bend',
    'arc',
    'semicircle',
    'sweep',
    'curvature',
    'convexity',
    'curving',
    'curling',
    'bending',
    'flex',
    'hunch',
    'crook',
    'curve',
    'bow',
    'bend',
    'arc',
    'curl',
]