export const definitions = [
    '"arch observations about even the most mundane matters"',
]
export const synonyms = [
    'knowing',
    'playful',
    'mischievous',
    'puckish',
    'roguish',
    'impish',
    'elfin',
    'devilish',
    'naughty',
    'wicked',
    'cheeky',
    'teasing',
    'saucy',
    'flippant',
    'tongue-in-cheek',
    'artful',
    'sly',
    'cunning',
    'affected',
    'frolicsome',
]