export const definitions = [
  '"an Arctic explorer"',
  '"Arctic plants"',
  '"February brought arctic conditions"',
  '"the arctic weather of 1981"',
];
export const synonyms = [
  'polar',
  'northern',
  'northerly',
  'boreal',
  'hyperborean',
  'far northern',
  'Antarctic',
  'frosty',
  'wintry',
  'freezing',
  'frigid',
  'frozen',
  'icy',
  'ice-cold',
  'glacial',
  'subzero',
  'polar',
  'Siberian',
  'bitter',
  'biting',
  'piercing',
  'cutting',
  'raw',
  'extreme',
  'gelid',
  'brumal',
  'rimy',
  '(bitterly) cold',
  'intensely cold',
  'algid',
  'tropical',
  'the far north',
  'the North Pole',
  'the Arctic circle',
  'the Antarctic',
];