export const definitions = [
  '"\"It stands to reason,\" she argued"',
  '"defense attorneys argue that the police lacked \"probable cause\" to arrest the driver"',
  '"I tried to argue him out of it"',
  '"I wasn\'t going to argue with a gun"',
  '"she was too tired to argue the point"',
  '"don\'t argue with me"',
];
export const synonyms = [
  'contend',
  'assert',
  'declare',
  'maintain',
  'state',
  'proclaim',
  'advance',
  'insist',
  'hold',
  'claim',
  'aver',
  'avow',
  'reason',
  'attest',
  'expostulate',
  'testify',
  'swear',
  'certify',
  'propound',
  'submit',
  'posit',
  'postulate',
  'adduce',
  'move',
  'advocate',
  'opine',
  'allege',
  'defend',
  'explain',
  'vindicate',
  'justify',
  'depose',
  'represent',
  'asseverate',
  'make a case for',
  'give reasons for',
  'talk out of',
  'persuade to',
  'convince to',
  'prevail on to',
  'coax into',
  'talk someone around',
  'dissuade from',
  'persuade against',
  'quarrel',
  'disagree',
  'row',
  'squabble',
  'bicker',
  'fight',
  'wrangle',
  'dispute',
  'feud',
  'cross swords',
  'lock horns',
  'be at each other\'s throats',
  'dissent',
  'clash',
  'differ',
  'altercate',
  'have a row',
  'bandy words',
  'have words',
  'be at odds',
];