export const definitions = [
    '"new difficulties had arisen"',
    '"the practice arose in the nineteenth century"',
    '"most conflicts arise from ignorance or uncertainty"',
    '"he arose at 9:30 and went out for a walk"',
]
export const synonyms = [
    'come to light',
    'make an appearance',
    'appear',
    'emerge',
    'come about',
    'surface',
    'occur',
    'ensue',
    'set in',
    'transpire',
    'begin',
    'commence',
    'befall',
    'come to pass',
    'become apparent',
    'crop/turn up',
    'spring up',
    'enter into the picture',
    'come into being/existence',
    'result',
    'proceed',
    'follow',
    'ensue',
    'derive',
    'stem',
    'accrue',
    'originate',
    'emanate',
    'spring',
    'flow',
    'be caused by',
    'be brought about by',
    'be produced by',
    'stand up',
    'rise',
    'get up',
    'jump up',
    'get to one\'s feet',
    'leap up',
    'spring up',
    'become erect',
    'straighten up',
    'sit down',
    'lie down',
]