export const definitions = [
    '"knights in armor"',
    '"a suit of armor"',
    '"the contingent includes infantry, armor, and logistic units"',
    '"his armor of self-confidence"',
    '"the knowledge armored him against her"',
]
export const synonyms = [
    'armor plate',
    'covering',
    'protection',
    'sheathing',
    'shield',
    'chain mail',
    'coat of mail',
    'panoply',
    'protective covering',
    'chain armor',
    'armor plate',
    'covering',
    'protection',
    'sheathing',
    'shield',
    'chain mail',
    'coat of mail',
    'panoply',
    'protective covering',
    'chain armor',
    'carapace',
    'outside',
    'exterior',
]