export const definitions = [
    '"the mountains towering all ______"',
    '"a building visible for miles ______"',
    '"everyone crowded ______"',
    '"a pool with banks all the way ______"',
    '"sometimes you wonder how many friends will rally ______ you when your life hits rock-bottom"',
    '"the boats were spun ______ by waterspouts"',
    '"she paused to glance ______ admiringly at the decor"',
    '"he passed a newspaper clipping ______"',
    '"Jack seized her by the shoulders and turned her ______"',
    '"having him in my corner has turned my career ______"',
    '"it was the last house before the road curved ______"',
    '"the picture shows the pieces the wrong way ______"',
    '"it was he who was attacking her, not the other way ______"',
    '"word got ______ that he was on the verge of retirement"',
    '"his only ambition is to drive ______ in a sports car"',
    '"he made his way ______ to the back of the building"',
    '"they went the long way ______ by the main road"',
    '"I like pupils to find their own way ______"',
    '"why don\'t you come ______ to my office?"',
    '"one of them was glancing nervously ______"',
    '"John tried to focus on her but she kept moving ______"',
    '"there was no one ______"',
    '"barley has been ______ for a long time"',
    '"by being ______ I threaten her happiness"',
    '"he would want to have her ______ as much as possible"',
    '"software costs would be ______ $1,500"',
    '"I returned to my hotel ______ 3 a.m."',
    '"the palazzo is built ______ a courtyard"',
    '"the hills ______ the city"',
    '"our entire culture is built ______ those loyalties"',
    '"you can organize your essay ______ an existing critical controversy"',
    '"cycling ______ the village"',
    '"a number of large depots ______ the country"',
    '"he walked ______ the airfield"',
    '"it can drill ______ corners"',
    '"he put his arm ______ her"',
    '"warming her hands ______ a cup of coffee"',
    '"the polar vortex ______ Antarctica"',
    '"just ______ the corner'
]

export const synonyms = [
    'throughout',
    'all over',
    'all over the place',
    'everywhere',
    'about',
    'here and there',
    'on every side',
    'on all sides',
    'in all directions',
    'backwards',
    'in the opposite direction',
    'in the reverse direction',
    'to face the other way',
    'to the rear',
    'about',
    'to and fro',
    'hither and thither',
    'back and forth',
    'from pillar to post',
    'from place to place',
    'in all directions',
    'nearby',
    'near',
    'about',
    'close by',
    'close',
    'at hand',
    'hard by',
    'accessible',
    'handy',
    'convenient',
    'close at hand',
    'in the vicinity',
    'in the neighborhood',
    'on the doorstep',
    'within (easy) reach',
    'at close range',
    'approximately',
    'about',
    'round about',
    'roughly',
    'in the region of',
    'in the neighborhood of',
    'of the order of',
    'or so',
    'there or thereabouts',
    'more or less',
    'nearly',
    'close to',
    'approaching',
    'plus-minus',
    'circa',
    'something like',
    'in the area of',
    'or thereabouts',
    'give or take a few',
    'plus or minus a few',
    'as near as dammit',
    'not far off',
    'getting on for',
    'about',
    'circling',
    'encircling',
    'surrounding',
    'encompassing',
    'framing',
    'on every side of',
    'on all sides of',
    'all over',
    'about',
    'here and there in',
    'everywhere in',
    'in/to all parts of',
    'about',
    'circling',
    'encircling',
    'surrounding',
    'encompassing',
    'framing',
    'on every side of',
    'on all sides of'
]
