export const definitions = [
  '"the police ______ed him for possession of marijuana"',
  '"two youths aged 16 were ______ed"',
  '"the spread of the disease can be ______ed"',
  '"______ed development may occur"',
  '"they were trying to resuscitate a patient who had ______ed"',
  '"his attention was ______ed by a strange sound"',
  '"I have a warrant for your ______"',
  '"they placed her under ______"',
  '"at least 69 ______s were made"',
  '"a respiratory ______"',
];

export const synonyms = [
  'apprehend',
  'seize',
  'take in',
  'detain',
  'take into custody',
  'take prisoner',
  'put in jail',
  'throw in jail',
  'release',
  'stop',
  'halt',
  'end',
  'check',
  'block',
  'hinder',
  'hamper',
  'delay',
  'hold up',
  'hold back',
  'restrict',
  'limit',
  'interrupt',
  'prevent',
  'obstruct',
  'inhibit',
  'impede',
  'thwart',
  'balk',
  'curb',
  'slow',
  'slow down',
  'retard',
  'stay',
  'bring to a standstill',
  'interfere with',
  'put a brake on',
  'nip in the bud',
  'start',
  'attract',
  'capture',
  'catch',
  'hold',
  'grip',
  'engage',
  'absorb',
  'occupy',
  'rivet',
  'engross',
  'fascinate',
  'mesmerize',
  'hypnotize',
  'spellbind',
  'bewitch',
  'captivate',
  'entrance',
  'enthrall',
  'enrapture',
  'catch hold of',
  'detention',
  'apprehension',
  'seizure',
  'capture',
  'taking into custody',
  'stoppage',
  'halt',
  'interruption',
];
