
export const definitions = [
    '"people are always ______ questions"',
    '"“How much further?” I kept ______"',
    '"an old man ______ about her job"',
    '"he\'s ______ if she wanted coffee"',
    '"______ whether his electric wheelchair would fit through their doors"',
    '"Mary is ______ her father for money"',
    '"I will not be ______ him to call the manager"',
    '"______ for advice"',
    '"______ her if she will consider moving in"',
    '"he was ______ $250 for the guitar"',
    '"it\'s ______ a lot, but could you look through Billy\'s things?"',
    '"______ for a playdate"'
]

export const synonyms = [
    'query',
    'question',
    'interrogate',
    'quiz',
    'cross-question',
    'cross-examine',
    'catechize',
    'put',
    'put forward',
    'pose',
    'raise',
    'submit',
    'propose',
    'inquire (of)',
    'want to know',
    'put a question to',
    'seek/get the answer to',
    'answer',
    'request',
    'demand',
    'petition',
    'call on',
    'entreat',
    'beg',
    'implore',
    'exhort',
    'urge',
    'enjoin',
    'importune',
    'pray',
    'solicit',
    'beseech',
    'sue',
    'supplicate',
    'seek',
    'call for',
    'crave',
    'appeal to',
    'apply to',
    'plead with',
    'put in for',
    'invite',
    'bid',
    'summon',
    'have someone over',
    'request the pleasure of someone\'s company'
]
