export const definitions = [
    '"the Scots army assailed Edward\'s army from the rear"',
    '"she was assailed by doubts and regrets"',
    '"he assailed a group of editors for their alleged excesses"',
]
export const synonyms = [
    'attack',
    'assault',
    'weigh into',
    'fly at',
    'turn on',
    'round on',
    'beset',
    'belabor',
    'fall on',
    'accost',
    'mug',
    'charge',
    'rush',
    'storm',
    'besiege',
    'make an assault on',
    'launch an attack on',
    'pounce on',
    'set upon',
    'launch oneself at',
    'let fly at',
    'lash out at',
    'hit out at',
    'trouble',
    'disturb',
    'worry',
    'plague',
    'beset',
    'torture',
    'torment',
    'rack',
    'bedevil',
    'nag',
    'vex',
    'harass',
    'pester',
    'dog',
    'be prey to',
    'be the victim of',
    'criticize',
    'censure',
    'attack',
    'condemn',
    'castigate',
    'chastise',
    'berate',
    'lambaste',
    'lash',
    'pillory',
    'abuse',
    'revile',
    'rate',
    'slash',
    'excoriate',
    'objurgate',
    'reprehend',
    'find fault with',
    'give someone a bad press',
]