export const definitions = [
  '"the committee must ______ the relative importance of the issues"',
  '"it is difficult to ______ whether this is a new trend"',
  '"the damage was ______ed at $5 billion"',
  '"all empty properties will be ______ed at 50 percent"',
];

export const synonyms = [
  'evaluate',
  'judge',
  'gauge',
  'rate',
  'estimate',
  'appraise',
  'check out',
  'determine',
  'weigh up',
  'analyze',
  'form an opinion of',
  'form an impression of',
  'make up one\'s mind about',
  'get the measure of',
  'value',
  'calculate',
  'compute',
  'work out',
  'determine',
  'fix',
  'cost',
  'price',
  'estimate',
  'put a value on',
  'charge',
  'tithe',
  'mulct',
  'levy a tax on',
  'impose a toll on',
  'charge duty on',
  'exact a tax on',
  'demand a tax on',
];
