export const definitions = [
    '"quick reflexes were his chief asset"',
    '"the school is an asset to the community"',
    '"growth in net assets"',
    '"debiting the asset account"',
]
export const synonyms = [
    'benefit',
    'advantage',
    'blessing',
    'strong point',
    'strength',
    'forte',
    'talent',
    'gift',
    'strong suit',
    'long suit',
    'virtue',
    'recommendation',
    'attraction',
    'selling point',
    'resource',
    'beauty',
    'boon',
    'value',
    'merit',
    'bonus',
    'aid',
    'help',
    'saving grace',
    'good point',
    'attractive feature',
    'redeeming feature',
    'compensating feature',
    'liability',
    'handicap',
    'property',
    'resources',
    'estate',
    'holdings',
    'possessions',
    'effects',
    'goods',
    'valuables',
    'belongings',
    'chattels',
    'worldly goods',
    'capital',
    'funds',
    'wealth',
    'principal',
    'money',
    'riches',
    'means',
    'deep pockets',
    'fortune',
    'finance',
    'reserves',
    'savings',
    'securities',
    'worldly possessions',
    'liability',
]