export const definitions = [
    '"the company ______s that the cuts will not affect development"',
    '"he ______ed his innocence"',
    '"the good librarian is able to ______ authority when required"',
    '"it was time to ______ himself"'
]

export const synonyms = [
    'declare',
    'maintain',
    'contend',
    'argue',
    'state',
    'claim',
    'propound',
    'submit',
    'posit',
    'postulate',
    'adduce',
    'move',
    'advocate',
    'venture',
    'volunteer',
    'aver',
    'proclaim',
    'announce',
    'pronounce',
    'attest',
    'affirm',
    'protest',
    'profess',
    'swear',
    'insist',
    'avow',
    'opine',
    'asseverate',
    'stand up for',
    'uphold',
    'defend',
    'contend',
    'establish',
    'stress',
    'insist on',
    'press/push for',
    'behave confidently',
    'speak confidently',
    'put oneself forward',
    'make one\'s presence felt',
    'exert one\'s influence',
    'make people sit up and take notice',
    'make people sit up and listen'
]