export const definitions = [
    '"Congress ______ed the task to the agency"',
    '"his leader ______ed him this mission"',
    '"she has been ______ed to a new job"',
    '"he was ______ed to prosecute the case"',
    '"managers happily ______ large sums of money to travel budgets"',
    '"it is difficult to decide whether to ______ the victory to Goodwin"',
    '"not all people who were ______ed male at birth identify as men"',
    '"Susan\'s baby was ______ed female"',
    '"they will ask you to ______ your rights against the airline"',
    '"this agreement shall be binding upon the parties and their successors and ______s"',
]

export const synonyms = [
    'allocate',
    'allot',
    'give',
    'set',
    'charge with',
    'entrust with',
    'appoint',
    'promote',
    'delegate',
    'commission',
    'post',
    'nominate',
    'vote',
    'elect',
    'adopt',
    'co-opt',
    'make',
    'create',
    'name',
    'designate',
    'dub',
    'decide on for',
    'select for',
    'choose for',
    'install in',
    'induct in',
    'institute in',
    'invest in',
    'ordain in',
    'detail for',
    'earmark',
    'appropriate',
    'designate',
    'set aside',
    'set apart',
    'keep',
    'reserve',
    'allot',
    'allocate',
    'apportion',
    'fix',
    'appoint',
    'determine',
    'specify',
    'stipulate',
    'hypothecate',
    'decide on',
    'ascribe',
    'attribute',
    'put down',
    'set down',
    'accredit',
    'credit',
    'chalk up',
    'impute',
    'lay on',
    'pin on',
    'give the credit for',
    'blame on',
    'lay at the door of',
    'connect with',
    'associate with',
    'transfer',
    'make over',
    'give',
    'pass',
    'hand over',
    'hand down',
    'convey',
    'consign',
    'alienate',
    'demise',
    'devise',
    'attorn'
]
