export const definitions = [
    '"it is reasonable to ______ that such changes have significant social effects" · "they were ______d to be foreign"',
    '"you\'re afraid of what people are going to ______ about me"',
    '"he ______d full responsibility for all organizational work"',
    '"the rebels ______d control of the capital"',
    '"militant activity had ______d epidemic proportions"',
    '"Oliver ______d an expression of penitence"',
    '"she puts on a disguise, ______s a different persona, and cruises the squalid bars on the bad side of town"'
]

export const synonyms = [
    'presume',
    'suppose',
    'take it',
    'take for granted',
    'presuppose',
    'conjecture',
    'surmise',
    'conclude',
    'deduce',
    'infer',
    'reckon',
    'reason',
    'guess',
    'imagine',
    'think',
    'fancy',
    'suspect',
    'expect',
    'accept',
    'believe',
    'understand',
    'gather',
    'glean',
    'figure',
    'opine',
    'ween',
    'take as read',
    'take it as given',
    'come to the conclusion',
    'draw the inference',
    'be of the opinion',
    'be given to understand',
    'accept',
    'shoulder',
    'bear',
    'undertake',
    'take on',
    'take up',
    'manage',
    'handle',
    'turn one\'s hand to',
    'take on oneself',
    'deal with',
    'get to grips with',
    'seize',
    'take',
    'take over',
    'take away',
    'appropriate',
    'commandeer',
    'expropriate',
    'confiscate',
    'requisition',
    'hijack',
    'wrest',
    'usurp',
    'preempt',
    'claim',
    'take possession of',
    'arrogate to oneself',
    'help oneself to',
    'lay claim to',
    'acquire',
    'take on',
    'adopt',
    'come to have',
    'feign',
    'fake',
    'put on',
    'simulate',
    'counterfeit',
    'sham',
    'affect',
    'adopt',
    'impersonate'
]
