export const definitions = [
    '"clarify your objectives and ways of attaining them"',
    '"he attained the rank of admiral"',
    '"human beings can attain happiness"',
    '"dolphins can attain remarkable speeds in water"',
]
export const synonyms = [
    'achieve',
    'accomplish',
    'reach',
    'come by',
    'obtain',
    'gain',
    'procure',
    'secure',
    'get',
    'grasp',
    'hook',
    'net',
    'win',
    'earn',
    'acquire',
    'establish',
    'make',
    'realize',
    'fulfill',
    'bring off',
    'bring about',
    'carry off',
    'carry through',
    'effect',
    'effectuate',
    'reify',
    'arrive at',
    'succeed in',
    'bring to fruition',
    'reach',
    'come to',
    'make',
    'get up to',
    'get down to',
    'arrive at',
    'rise to',
    'soar to',
    'sink to',
    'plummet to',
    'dive to',
]