export const definitions = [
    '"in December, the Japanese ______ed Pearl Harbor"',
    '"Italian forces ______ed in October"',
    '"a doctor was ______ed by two youths"',
    '"the disease is thought to ______ certain cells in the brain"',
    '"he ______ed the government\'s defense policy"',
    '"a plan of action to ______ unemployment"',
    '"the home team ______ed from the kick off"',
    '"the nucleophile ______s the epoxide from the opposite side of the ring to the oxygen"',
    '"he was killed in an ______ on a checkpoint"',
    '"three classrooms were gutted in the arson ______"',
    '"the tissue is open to ______ by fungus"',
    '"an ______ of nausea" · "an asthma ______"',
    '"he launched a stinging ______ on the White House"',
    '"an ______ on inflation"',
    '"the sheer ______ of Hendrix\'s playing"',
]

export const synonyms = [
    'charge',
    'pounce',
    'strike',
    'ambush',
    'bombard',
    'shell',
    'blitz',
    'strafe',
    'rush',
    'storm',
    'begin an assault',
    'begin hostilities',
    'fire on/at',
    'defend',
    'assault',
    'beat',
    'beat up',
    'batter',
    'thrash',
    'pound',
    'pummel',
    'assail',
    'tear into',
    'aggress',
    'ambush',
    'mug',
    'set upon',
    'fall upon',
    'strike at',
    'let fly at',
    'lash out at',
    'pounce on',
    'affect',
    'strike',
    'infect',
    'damage',
    'injure',
    'have an effect on',
    'strike at',
    'take hold of',
    'protect',
    'criticize',
    'censure',
    'condemn',
    'castigate',
    'chastise',
    'lambaste',
    'pillory',
    'savage',
    'abuse',
    'berate',
    'reprove',
    'rebuke',
    'reprimand',
    'admonish',
    'reproach',
    'impugn',
    'harangue',
    'blame',
    'revile',
    'vilify',
    'rate',
    'slash',
    'excoriate',
    'objurgate',
    'reprehend',
    'find fault with',
    'fulminate against',
    'remonstrate with',
    'take to task',
    'haul over the coals',
    'give someone a bad press',
    'praise',
    'address',
    'see to',
    'confront',
    'set about',
    'undertake',
    'attend to',
    'deal with',
    'grapple with',
    'direct one\'s attention to',
    'focus on',
    'concentrate on',
    'apply oneself to',
    'buckle down to',
    'get to work on',
    'go to work on',
    'set to work on',
    'get started on',
    'embark on',
    'assault',
    'onslaught',
    'offensive',
    'strike',
    'blitz',
    'raid',
    'sortie',
    'sally',
    'storming',
    'charge',
    'rush',
    'drive',
    'push',
    'thrust',
    'invasion',
    'incursion',
    'inroad',
    'razzia',
    'onset',
    'act of aggression',
    'fit',
    'seizure',
    'spasm',
    'convulsion',
    'paroxysm',
    'outburst',
    'flare-up',
    'bout',
    'spell',
    'dose',
    'access',
    'criticism',
    'censure',
    'rebuke',
    'admonition',
    'admonishment',
    'reprimand',
    'condemnation',
    'denunciation',
    'revilement',
    'invective',
    'vilification',
    'tirade',
    'diatribe',
    'rant',
    'polemic',
    'broadside',
    'harangue',
    'stricture',
    'rating',
    'philippic',
    'reproval',
    'verbal onslaught',
    'commendation',
    'defense'
]
