export const definitions = [
    '"holiday attire"',
    '"the usually sober attire of security service personnel"',
    '"Donna was attired in an elaborate evening gown"',
    '"an outrageously attired rock star"',
]
export const synonyms = [
    'clothing',
    'clothes',
    'garments',
    'dress',
    'wear',
    'outfit',
    'turnout',
    'garb',
    'ensemble',
    'costume',
    'array',
    'finery',
    'regalia',
    'wardrobe',
    'accoutrements',
    'trappings',
    'kit',
    'strip',
    'apparel',
    'raiment',
    'habiliments',
    'habit',
    'vestments',
    'dressed',
    'clothed',
    'garbed',
    'arrayed',
    'costumed',
    'appareled',
    'invested',
    'habited',
    'dress',
    'clothe',
    'dress up',
    'fit out',
    'garb',
    'robe',
    'array',
    'deck',
    'turn out',
    'trick out',
    'costume',
    'accoutre',
    'drape',
    'swathe',
    'adorn',
    'apparel',
    'bedizen',
    'caparison',
    'furbelow',
    'invest',
    'habit',
    'dressed up',
    'fitted out',
    'decked out',
    'turned out',
    'tricked up',
    'trapped out',
    'deck out',
    'trick up',
    'trap out',
]