export const definitions = [
    "______ can\'t be expected to detect every fraud",
    "a complete _____ of flora and fauna at the site",
    "companies must have their accounts _____ed",
    "_____ing obstetrical and neonatal care",
    "he made use of the knowledge gleaned from economics classes he _____ed"
];
export const synonyms = [
    'inspection',
    'examination',
    'survey',
    'scrutiny',
    'probe',
    'vetting',
    'investigation',
    'check',
    'assessment',
    'appraisal',
    'evaluation',
    'review',
    'analysis',
    'study',
    'perusal',
    'dissection',
    'inspect',
    'examine',
    'survey',
    'look over',
    'go over',
    'go through',
    'scrutinize',
    'probe',
    'vet',
    'investigate',
    'look into',
    'check',
    'check into',
    'assess',
    'appraise',
    'evaluate',
    'review',
    'analyze',
    'study',
    'peruse',
    'sift',
    'dissect',
    'check out',
    'inquire into',
    'pore over',
    'go over with a fine-tooth comb',
    'delve into',
    'dig into',
    'survey',
    'study',
    'research',
    'consider',
    'analyze',
    'examine',
    'scrutinize',
    'explore',
    'look into',
    'probe',
    'investigate',
    'inspect',
    'assess',
    'appraise',
    'sum up',
    'anatomize',
    'take stock of',
    'inquire into',
    'make inquiries into',
    'conduct investigations into',
    'size up',
    'attend',
    'observe',
    'watch',
    'be present at',
    'be an observer at'
]
