export const definitions = [
    '"the end of the cold war seemed to augur well"',
    '"the return to the gold standard augured badly for industry"',
    '"a new coalition would not augur a new period of social reforms"',
]
export const synonyms = [
    'bode',
    'portend',
    'herald',
    'foreshadow',
    'presage',
    'indicate',
    'signify',
    'signal',
    'point to',
    'promise',
    'threaten',
    'spell',
    'denote',
    'foretell',
    'forecast',
    'predict',
    'prophesy',
    'prognosticate',
    'divine',
    'foresee',
    'betoken',
    'foretoken',
    'forebode',
    'harbinger',
    'foreshow',
    'previse',
    'vaticinate',
    'be a sign of',
    'be an indication of',
    'be a warning of',
    'warn of',
    'forewarn of',
    'be an omen of',
    'be a harbinger of',
    'spae',
    'auspicate',
    'seer',
    'soothsayer',
    'fortune teller',
    'crystal gazer',
    'clairvoyant',
    'psychic',
    'visionary',
    'prognosticator',
    'diviner',
    'prophesier',
    'prophet',
    'prophetess',
    'oracle',
    'sibyl',
    'sage',
    'wise man',
    'wise woman',
    'vaticinator',
    'haruspex',
    'spaewife',
    'spaeman',
    'oracler',
]