export const definitions = [
  'he is the ______ of several books on the subject',
  'my favorite ______s are Kurt Vonnegut and Aldous Huxley',
  'I had to read ______s I disliked',
  'the ______s of the peace plan',
  'she has ______ed several articles on wildlife',
  'the concept has been ______ed largely by insurance companies',
];
export const synonyms = [
  'writer',
  'wordsmith',
  'novelist',
  'dramatist',
  'playwright',
  'screenwriter',
  'scriptwriter',
  'poet',
  'essayist',
  'biographer',
  'journalist',
  'columnist',
  'reporter',
  'correspondent',
  'librettist',
  'lyricist',
  'songwriter',
  'littérateur',
  'man/woman of letters',
  'originator',
  'creator',
  'initiator',
  'instigator',
  'founder',
  'father',
  'prime mover',
  'architect',
  'engineer',
  'designer',
  'deviser',
  'planner',
  'inventor',
  'maker',
  'producer',
  'cause',
  'agent',
  'begetter',
  'write',
  'create',
  'devise',
  'make up',
  'think up',
  'frame',
  'formulate',
  'fashion',
  'produce',
  'originate',
  'invent',
  'contrive',
  'concoct',
  'pen',
  'draft',
  'rhyme',
  'sing',
  'verse',
  'indite',
];
