export const definitions = [
    '"tree-lined avenues surround the hotel"',
    '"Euclid Avenue"',
    '"7th Avenue"',
    '"an avenue of limes"',
    '"three possible avenues of research suggested themselves"',
]
export const synonyms = [
    'driveway',
    'approach',
    'access road',
    'road',
    'roadway',
    'road',
    'street',
    'thoroughfare',
    'boulevard',
    'way',
    'broadway',
    'highway',
    'line',
    'path',
    'direction',
    'route',
    'method',
    'approach',
    'course of action',
]