export const definitions = [
    '"an avowed atheist"',
    '"they came to power with the avowed aim of promoting religious toleration"',
    '"he avowed that he was no longer in perfect health"',
    '"he avowed his change of faith"',
]
export const synonyms = [
    'assert',
    'declare',
    'state',
    'maintain',
    'aver',
    'attest',
    'swear',
    'vow',
    'insist',
    'confess',
    'admit',
    'asseverate',
    'declared',
    'sworn',
    'self-confessed',
    'confessed',
    'self-proclaimed',
    'acknowledged',
    'admitted',
    'open',
    'overt',
    'known',
]