export const definitions = [
    "he was _____ed the Purple Heart",
    "the 3.5 percent pay raise was _____ed to the staff",
    "the company was _____ed a contract to refurbish the timber mill",
    "the company\'s annual _____ for high-quality service",
    "an _____ ceremony",
    "a generous _____ given to promising young dancers",
    "the _____ of an honorary doctorate",
    "an _____ of damages"
];
export const synonyms = [
    'give',
    'grant',
    'accord',
    'assign',
    'apportion',
    'allot',
    'allocate',
    'allow',
    'confer on',
    'present to',
    'bestow on',
    'gift with',
    'furnish with',
    'endow with',
    'decorate with',
    'prize',
    'trophy',
    'medal',
    'reward',
    'honors',
    'decoration',
    'payment',
    'settlement',
    'compensation',
    'damages',
    'grant',
    'scholarship',
    'subsidy',
    'subvention',
    'endowment',
    'bursary',
    'bursarship',
    'giving',
    'granting',
    'conferment',
    'conferral',
    'presentation',
    'bestowal'
]