export const definitions = [
    '"no police ______ could be expected"',
    '"I\'ve got a security force as ______"',
    '"a ______ generator"',
    '"the filter is an excellent ______ to other systems"',
    '"make a ______ of any important files"',
    '"a ______ copy"',
    '"automatic online ______"',
    '"a ______ system"',
    '"there is a long ______ temporarily on this route"',
];
export const synonyms = [
    'help',
    'support',
    'assistance',
    'aid',
    'reinforcements',
    'reserves',
    'additional resources',
    'acting',
    'replacement',
    'deputy',
    'relief',
    'reserve',
    'surrogate',
    'fill-in',
    'stand-in',
    'temporary',
    'caretaker',
    'alternative',
    'locum',
    'standby',
    'stopgap',
    'interim',
    'provisional',
    'pro tem',
    'proxy',
    'ancillary',
    'pro tempore',
    'permanent',
]
