export const definitions = [
  '"one of them is a real badass, the other\'s pretty friendly"',
  '"she is so wonderful, so sweet, so rad, so amazing; \'s \'s a badass"',
  '"a badass demeanor"',
  '"this was one badass camera"',
];
export const synonyms = [
  'persecutor',
  'oppressor',
  'tyrant',
  'tormentor',
  'browbeater',
  'intimidator',
  'coercer',
  'subjugator',
  'crybully',
  'scourge',
  'tough',
  'heavy',
  'bully boy',
  'ruffian',
  'thug',
  'attack dog',
  'strict',
  'stern',
  'severe',
  'hard',
  'harsh',
  'firm',
  'hard-hitting',
  'adamant',
  'inflexible',
  'unyielding',
  'unbending',
  'uncompromising',
  'unsentimental',
  'unsympathetic',
  'merciless',
  'ruthless',
  'callous',
  'hard-hearted',
  'uncaring',
  'cold',
  'cool',
  'stony',
  'stony-hearted',
  'flinty',
  'soft',
  'light',
  'admirable',
  'accomplished',
  'expert',
  'skilled',
  'skillful',
  'masterly',
  'consummate',
  'excellent',
  'formidable',
  'outstanding',
  'first-class',
  'first-rate',
  'fine',
  'unimpressive',
  'mediocre',
];