export const definitions = [
  '"he expressed how it feels to be on stage playing the baddie"',
  '"the baddie will stop at nothing to get the cash back"',
];
export const synonyms = [
  'criminal',
  'lawbreaker',
  'outlaw',
  'offender',
  'felon',
  'convict',
  'jailbird',
  'malefactor',
  'wrongdoer',
  'black hat',
  'supervillain',
  'transgressor',
  'sinner',
  'gangster',
  'gunman',
  'bandit',
  'brigand',
  'desperado',
  'thief',
  'robber',
  'mugger',
  'swindler',
  'fraudster',
  'racketeer',
  'terrorist',
  'pirate',
  'rogue',
  'scoundrel',
  'wretch',
  'heel',
  'reprobate',
  'charlatan',
  'evil-doer',
  'ruffian',
  'hoodlum',
  'hooligan',
  'thug',
  'delinquent',
  'ne\'er -do -well',
  'good-for-nothing',
  'malfeasant',
  'infractor',
  'cad',
  'knave',
  'rake',
  'miscreant',
  'blackguard',
  'misfeasor',
];