export const definitions = [
    '"brown paper bags"',
    '"a shopping bag"',
    '"a bag of apples"',
    '"a velvet evening bag"',
    '"she began to unpack her bags"',
    '"an estimated bag of 3,000 ducks"',
    '"the bags under his eyes gave him a sad appearance"',
    '"I had bags of energy"',
    '"if religion and politics are your bag, you\'ll find something to interest you here"',
    '"customers bagged their own groceries"',
    '"we bagged up the apples"',
    '"once you\'ve raked the leaves, bag them up right away so that they don\'t get wet"',
    '"in 1979, handgun hunters bagged 677 deer"',
    '"we\'ve bagged three awards for excellence"',
    '"get there early to bag a seat in the front row"',
    '"these trousers never bag at the knee"',
    '"it was a drag to be in the ninth grade at 17, so he bagged it"',
]
export const synonyms = [
    'receptacle',
    'container',
    'sack',
    'carrier',
    'poke',
    'keister',
    'shopping bag',
    'string bag',
    'carrier bag',
    'handbag',
    'shoulder bag',
    'pocketbook',
    'purse',
    'reticule',
    'scrip',
    'clutch bag',
    'evening bag',
    'pochette',
    'suitcase',
    'case',
    'valise',
    'portmanteau',
    'grip',
    'overnight bag',
    'overnighter',
    'flight bag',
    'Gladstone bag',
    'carpet bag',
    'backpack',
    'rucksack',
    'knapsack',
    'haversack',
    'kitbag',
    'duffel bag',
    'satchel',
    'luggage',
    'baggage',
    'holdall',
    'carryall',
    'traveling bag',
    'hobby',
    'pastime',
    'recreation',
    'entertainment',
    'diversion',
    'amusement',
    'relaxation',
    'passion',
    'enthusiasm',
    'leisure activity',
    'leisure pursuit',
    'catch',
    'capture',
    'trap',
    'snare',
    'ensnare',
    'land',
    'kill',
    'shoot',
    'pick off',
    'get',
    'secure',
    'obtain',
    'acquire',
    'reserve',
    'commandeer',
    'grab',
    'appropriate',
    'take',
    'win',
    'achieve',
    'attain',
    'sag',
    'bulge',
    'swell',
    'balloon',
    'hang loosely',
]