export const definitions = [
]
export const synonyms = [
    'youngster',
    'boy',
    'girl',
    'baby',
    'newborn',
    'infant',
    'toddler',
    'schoolboy',
    'schoolgirl',
    'adolescent',
    'teenager',
    'youth',
    'young man',
    'young lady',
    'young adult',
    'juvenile',
    'minor',
    'junior',
    'stripling',
    'fledgling',
    'whippersnapper',
    'son',
    'daughter',
    'scion',
    'descendant',
    'offspring',
    'progeny',
    'issue',
    'neonate',
    'wean',
    'laddie',
    'lassie',
    'pickney',
    'babe',
    'babe in arms',
    'hobbledehoy',
    'young one',
    'little one',
    'young woman',
    'young person',
    'son and heir',
]