export const definitions = [
  '"he picked up what was to become a consuming interest in baking"',
  '"the residents like the smell and taste of fresh baking"',
  '"donations of raffle prizes and home baking would be much appreciated by the committee members"',
  '"deep winters and baking summers"',
  '"we could have more baking sunshine"',
  '"already the sun was baking hot"',
  '"they bake their own bread and cakes"',
  '"I baked him a cake for his birthday"',
  '"the bread was baking on hot stones"',
  '"the sun has baked the earth a dusty brown"',
  '"the city was baking in a heatwave"',
];
export const synonyms = [
  'scorching',
  'roasting',
  'blistering',
  'blazing',
  'sweltering',
  'parching',
  'searing',
  'broiling',
  'sultry',
  'torrid',
  'sweaty',
  'ovenlike',
  'very hot',
  'cold',
  'cool',
  'cook',
  'oven-bake',
  'dry-roast',
  'roast',
  'spit-roast',
  'pot-roast',
  'oven',
  'brown',
  'grill',
  'barbecue',
  'singe',
  'sear',
  'broil',
  'charbroil',
  'crisp (up)',
  'scorch',
  'burn',
  'sear',
  'parch',
  'dry (up)',
  'desiccate',
  'wither',
  'shrivel',
  'fire',
  'broil',
  'hot',
  'stifling',
  'suffocating',
  'humid',
  'steamy',
  'sultry',
  'sticky',
  'muggy',
  'close',
  'stuffy',
  'airless',
  'oppressive',
  'tropical',
  'torrid',
  'burning',
  'searing',
  'parching',
  'jungle-like',
  'like an oven',
  'like a Turkish bath',
  'claggy',
  'cold',
  'chilly',
  'cool',
];