export const definitions = [
    '"the commissioners were elected by ______"',
    '"next year\'s primary ______"',
    '"he won 54 percent of the ______"',
    '"the union is preparing to ______ its members on the same issue"',
    '"ambulance crews ______ed unanimously to reject the deal"',
    '"if the offer is oversubscribed acceptances will be ______ed"',
];
export const synonyms = [
    'plebiscite',
    'popular vote',
    'poll',
    'public vote',
    'vote',
    'poll',
    'election',
    'referendum',
    'plebiscite',
    'general election',
    'popular vote',
    'straw poll',
    'show of hands',
    'voting',
    'polling',
    'local election',
    'vote',
    'poll',
    'election',
    'referendum',
    'plebiscite',
    'general election',
    'popular vote',
    'straw poll',
    'show of hands',
    'voting',
    'polling',
    'local election',
    'canvass',
    'survey',
    'ask',
    'question',
    'interview',
    'sample',
]
