export const definitions = [
    '"they were banished to Siberia for political crimes"',
    '"all thoughts of romance were banished from her head"',
    '"it\'s perfectly feasible to banish the smoke without banning smoking"',
]
export const synonyms = [
    'exile',
    'expel',
    'deport',
    'eject',
    'expatriate',
    'extradite',
    'repatriate',
    'transport',
    'cast out',
    'oust',
    'drive away',
    'evict',
    'throw out',
    'exclude',
    'shut out',
    'ban',
    'excommunicate',
    'ostracize',
    'admit',
    'readmit',
    'dispel',
    'dismiss',
    'disperse',
    'scatter',
    'dissipate',
    'drive away',
    'rout',
    'oust',
    'cast out',
    'shut out',
    'get rid of',
    'quell',
    'allay',
    'eliminate',
    'dislodge',
    'drive off',
    'chase away',
    'engender',
]