export const definitions = [
  '"the rain banked the soil up behind the gate"',
  '"snow was banked in humps at the roadside"',
  '"purple clouds banked up over the hills"',
  '"she could have made a fire and banked it with dirt"',
  '"steps banked with pots of chrysanthemums"',
  '"the plane banked as if to return to the airport"',
  '"I banked the aircraft steeply and turned"',
  '"the track was banked to allow a train to take curves faster while maintaining passenger comfort"',
  '"a banked racetrack"',
  '"he has built a four-cylinder locomotive for banking trains up the Lickey incline"',
  '"I banked the eight ball off two cushions"',
  '"I banked the check"',
  '"he did not bank with the old family banks"',
  '"I’ve banked at the same bank for nearly 50 years"',
  '"he banked $100,000 for a hole-in-one"',
  '"the sperm is banked or held in storage for the following spring"',
];
export const synonyms = [
  'pile (up)',
  'stack (up)',
  'accumulate',
  'amass',
  'assemble',
  'put together',
  'heap (up)',
  'make a pile of',
  'make a heap of',
  'make a stack of',
  'smother',
  'stifle',
  'damp (down)',
  'tilt',
  'lean',
  'tip',
  'slant',
  'incline',
  'angle',
  'slope',
  'list',
  'camber',
  'pitch',
  'dip',
  'cant',
  'put/be at an angle',
  'deposit',
  'pay in',
  'clear',
  'save',
  'keep',
  'lay by',
  'put aside',
  'set aside',
  'put by',
  'hoard',
  'cache',
  'garner',
  'use',
  'save up',
  'keep in reserve',
  'put by for a rainy day',
  'have an account at',
  'deposit one\'s money with',
  'be a customer of',
  'deal with',
  'do business with',
];