export const definitions = [
    '"he was banned from driving for a year"',
    '"a proposal to ban all trade in ivory"',
    '"he once was banned from a casino in Reno"',
]
export const synonyms = [
    'prohibit',
    'forbid',
    'veto',
    'proscribe',
    'disallow',
    'outlaw',
    'embargo',
    'bar',
    'debar',
    'block',
    'stop',
    'put a stop to',
    'put an end to',
    'suppress',
    'interdict',
    'enjoin',
    'restrain',
    'make illegal',
    'place an embargo on',
    'permit',
    'exclude',
    'banish',
    'expel',
    'eject',
    'evict',
    'drive out',
    'force out',
    'oust',
    'remove',
    'get rid of',
    'drum out',
    'turn out',
    'thrust out',
    'push out',
    'prohibit from entering',
    'admit',
]