export const definitions = [
  '"barbed arrows"',
  '"a fair degree of barbed wit"',
  '"he has barbed the hair of any celebrity you can think of"',
  '"my grandson got his hair barbed today"',
  '"I will never barb my hair in this guy\'s shop again"',
];
export const synonyms = [
  'jagged',
  'hooked',
  'spiky',
  'spiked',
  'spined',
  'spiny',
  'prickly',
  'thorny',
  'scratchy',
  'bristly',
  'bristled',
  'briary',
  'brambly',
  'sharp',
  'pointed',
  'spinose',
  'spinous',
  'hurtful',
  'wounding',
  'cutting',
  'biting',
  'stinging',
  'mean',
  'spiteful',
  'nasty',
  'rude',
  'cruel',
  'vicious',
  'unkind',
  'unfriendly',
  'snide',
  'pointed',
  'hateful',
  'ill-natured',
  'bitter',
  'venomous',
  'poisonous',
  'mordant',
  'acid',
  'acerbic',
  'acrimonious',
  'astringent',
  'caustic',
  'sharp',
  'scathing',
  'hostile',
  'rancorous',
  'malicious',
  'malevolent',
  'baleful',
  'vindictive',
  'vengeful',
  'vitriolic',
  'splenetic',
  'malign',
  'malignant',
  'pernicious',
  'bilious',
  'malefic',
  'maleficent',
  'evil-intentioned',
  'kindly',
  'generous',
];