export const definitions = [
  '"he was bare from the waist up"',
  '"she padded in bare feet towards the door"',
  '"bare floorboards"',
  '"a clump of bare aspen trees"',
  '"a bare cell with just a mattress"',
  '"the interior was bare of plaster"',
  '"an ordeal that would lay bare a troubled family background"',
  '"he outlined the bare essentials of the story"',
  '"a strange, bare production of Twelfth Night"',
  '"a bare majority"',
  '"all you need to get started with this program is a bare 10K bytes of memory"',
];
export const synonyms = [
  'naked',
  'unclothed',
  'undressed',
  'uncovered',
  'stripped',
  'in a state of nature',
  'disrobed',
  'unclad',
  'undraped',
  'exposed',
  'nude',
  'in the nude',
  'stark naked',
  'au naturel',
  'with nothing on',
  'clothed',
  'uncovered',
  'unpainted',
  'unvarnished',
  'stripped',
  'polished',
  'sealed',
  'barren',
  'bleak',
  'exposed',
  'desolate',
  'stark',
  'arid',
  'desert',
  'denuded',
  'lunar',
  'treeless',
  'defoliated',
  'unsheltered',
  'unprotected',
  'unshielded',
  'unwooded',
  'uncarpeted',
  'forestless',
  'without vegetation',
  'lush',
  'empty',
  'emptied',
  'unfurnished',
  'vacant',
  'clear',
  'cleared',
  'free',
  'stark',
  'austere',
  'spartan',
  'unadorned',
  'unembellished',
  'unornamented',
  'unfussy',
  'plain',
  'furnished',
  'embellished',
  'without',
  'lacking',
  'wanting',
  'free from',
  'empty of',
  'emptied of',
  'devoid of',
  'bereft of',
  'deprived of',
  'destitute of',
  'containing',
  'straightforward',
  'plain',
  'simple',
  'basic',
  'pure',
  'essential',
  'bare-bones',
  'fundamental',
  'stripped down',
  'cut down',
  'stark',
  'bald',
  'cold',
  'hard',
  'truthful',
  'realistic',
  'true to life',
  'brutal',
  'harsh',
  'explicit',
  'unequivocal',
  'unambiguous',
  'unadorned',
  'unembellished',
  'undisguised',
  'unveiled',
  'unvarnished',
  'unqualified',
  'unexaggerated',
  'trifling',
  'meager',
  'trivial',
  'paltry',
  'basic',
  'scant',
  'scanty',
  'skimpy',
  'minimal',
  'slender',
  'just',
  'only',
  'no more than',
  'mere',
  'no better than',
  'simple',
  'sheer',
  'very',
  'basic',
  'slim',
  'slight',
  'slender',
  'paltry',
  'skimpy',
  'minimum',
  'trifling',
  'no more than',
  'just a',
  'only a',
  'comfortable',
];