export const definitions = [
  '"we can\'t just barge into a private garden"',
  '"displays of dissent, such as deliberately barging into the umpire"',
];
export const synonyms = [
  'lighter',
  'canal boat',
  'flatboat',
  'narrowboat',
  'wherry',
  'scow',
  'push',
  'shove',
  'force',
  'elbow',
  'shoulder',
  'jostle',
  'bludgeon',
  'bulldoze',
  'muscle',
  'hit',
  'strike',
  'ram',
  'impact',
  'collide with',
  'be in collision with',
  'crash into',
  'smash into',
  'knock into',
  'plow into',
  'barge into',
  'meet head-on',
  'miss',
];