export const definitions = [
    '"the plains of Kyrenia were barren"',
    '"the barren, burnt-up countryside"',
    '"the barren fig tree"',
    '"much of philosophy has been barren"',
    '"the sports hall turned out to be a rather barren concrete building"',
    '"those young heads were stuffed with barren facts"',
    '"the room was barren of furniture"',
    '"crossing the barrens was no easy feat"',
]
export const synonyms = [
    'unproductive',
    'infertile',
    'unfruitful',
    'sterile',
    'arid',
    'desert',
    'waste',
    'desolate',
    'impoverished',
    'uncultivatable',
    'fertile',
    'productive',
    'unproductive',
    'unfruitful',
    'unprofitable',
    'unremunerative',
    'arid',
    'hard',
    'bad',
    'difficult',
    'tough',
    'impoverished',
    'poverty-stricken',
    'moneyless',
    'productive',
    'prosperous',
    'infertile',
    'sterile',
    'childless',
    'infecund',
    'fertile',
    'bleak',
    'stark',
    'bare',
    'drab',
    'desolate',
    'dreary',
    'dismal',
    'gloomy',
    'somber',
    'forlorn',
    'grim',
    'stern',
    'harsh',
    'forbidding',
    'uninviting',
    'unwelcoming',
    'cheerless',
    'cheerful',
    'pointless',
    'futile',
    'worthless',
    'profitless',
    'valueless',
    'unrewarding',
    'purposeless',
    'useless',
    'vain',
    'aimless',
    'uninteresting',
    'boring',
    'dull',
    'drab',
    'dry',
    'arid',
    'flat',
    'lifeless',
    'uninspiring',
    'unstimulating',
    'stale',
    'prosaic',
    'hollow',
    'empty',
    'vacuous',
    'vapid',
    'stimulating',
    'fruitful',
    'lacking',
    'without',
    'wanting',
    'in need of',
    'free from/of',
    'empty of',
    'vacant of',
    'void of',
    'bare of',
    'barren of',
    'bereft of',
    'drained of',
    'denuded of',
    'deprived of',
    'depleted of',
    'destitute of',
    'bankrupt of',
]