export const definitions = [
  '"they bashed him over the head with a blunt object"',
  '"the car\'s rear window had been bashed in "',
  '"a remark bashing the Belgian brewing industry"',
];
export const synonyms = [
  'strike',
  'hit',
  'beat',
  'thump',
  'slap',
  'smack',
  'batter',
  'pound',
  'pummel',
  'thrash',
  'rap',
  'buffet',
  'hammer',
  'bang',
  'knock',
  'vilify',
  'disparage',
  'denigrate',
  'defame',
  'run down',
  'impugn',
  'revile',
  'berate',
  'belittle',
  'abuse',
  'insult',
  'slight',
  'attack',
  'speak ill of',
  'speak evil of',
  'pour scorn on',
  'criticize',
  'censure',
  'condemn',
  'decry',
  'denounce',
  'pillory',
  'lambaste',
  'malign',
  'slander',
  'libel',
  'discredit',
  'stigmatize',
  'traduce',
  'calumniate',
  'slur',
  'contemn',
  'derogate',
  'vituperate',
  'asperse',
  'vilipend',
  'speak badly of',
  'fulminate against',
  'rail against',
  'inveigh against',
  'conduct a smear campaign against',
  'spread lies about',
  'blacken the name/reputation of',
  'sully the reputation of',
  'give someone a bad name',
  'bring into disrepute',
];