export const definitions = [
    '"learning the basics of the business"',
    '"storytelling has re-emerged as people have turned back to basics"',
    '"people are facing a shortage of basics like flour"',
]
export const synonyms = [
    'fundamentals',
    'essentials',
    'rudiments',
    'principles',
    'first principles',
    'foundations',
    'preliminaries',
    'groundwork',
    'essence',
    'basis',
    'core',
    'kernel',
    'nub',
    'marrow',
    'meat',
    'crux',
    'bedrock',
    'facts',
    'practicalities',
    'realities',
    'sine qua non',
    'hard facts',
]