export const definitions = [
  '"sprawled figures basking in the afternoon sun"',
  '"he went on basking in the glory of his first book"',
];
export const synonyms = [
  'laze',
  'lie',
  'lounge',
  'relax',
  'sprawl',
  'loll',
  'sunbathe',
  'sun oneself',
  'warm oneself',
  'revel',
  'luxuriate',
  'wallow',
  'delight',
  'rejoice',
  'glory',
  'enjoy',
  'relish',
  'savor',
  'take pleasure',
  'indulge oneself',
  'lap up',
];