export const definitions = [
  '"slip herbs under the skin and baste the chicken constantly"',
  '"keep any remaining sauce ready for basting"',
  '"baste the zip under the edges so that it is concealed"',
  '"stitch in place over the basting"',
  '"go baste him one!"',
];
export const synonyms = [
  'sew',
  'tack',
  'seam',
  'hem',
  'sew up',
  'repair',
  'mend',
  'darn',
  'strike',
  'slap',
  'smack',
  'cuff',
  'punch',
  'beat',
  'thrash',
  'thump',
  'batter',
  'belabor',
  'drub',
  'hook',
  'pound',
  'smash',
  'slam',
  'welt',
  'pummel',
  'hammer',
  'bang',
  'knock',
  'swat',
  'whip',
  'flog',
  'cane',
  'sucker-punch',
  'box someone\'s ears',
  'smite',
  'swinge',
  'buffet',
  'birch',
  'rain blows on',
  'give someone a (good) beating/drubbing',
];