export const definitions = [
    '"she took a long, hot bath"',
    '"he lay thinking in the bath"',
    '"how to bath a baby"',
]
export const synonyms = [
    'wash',
    'soak',
    'dip',
    'shower',
    'douche',
    'soaping',
    'sponging',
    'toilet',
    'ablution',
    'bathtub',
    'tub',
    'hot tub',
    'sitz bath',
    'whirlpool bath',
    'sauna',
    'steam bath',
    'Turkish bath',
    'pool',
    'Jacuzzi',
    'hip bath',
    'slipper bath',
    'thermae',
    'wash',
    'clean',
    'soak',
    'douche',
    'soap',
    'bathe',
    'lave',
    'give ... a bath',
]