export const definitions = [
  '"how to bath a baby"',
  '"she was advised to bathe or shower daily"',
  '"she bathed and bandaged my knee"',
  '"they bathed the baby"',
  '"the park lay bathed in sunshine"',
  '"mussels bathed in garlic butter"',
];
export const synonyms = [
  'wash',
  'clean',
  'soak',
  'douche',
  'soap',
  'bathe',
  'lave',
  'give ... a bath',
  'wash',
  'clean',
  'soak',
  'shower',
  'douche',
  'bath',
  'lave',
  'have/take a bath',
  'perform one\'s ablutions',
  'cleanse',
  'clean',
  'wash',
  'rinse',
  'wet',
  'moisten',
  'soak',
  'immerse',
  'disinfect',
  'wash',
  'clean',
  'soak',
  'douche',
  'soap',
  'bath',
  'lave',
  'give ... a bath',
  'swim',
  'dip',
  'go swimming',
  'take a dip',
  'splash around',
  'suffuse',
  'envelop',
  'permeate',
  'cover',
  'pervade',
  'wash',
  'saturate',
  'imbue',
  'fill',
  'load',
  'impregnate',
  'inform',
  'steep',
  'color',
  'mantle',
];