export const definitions = [
  '"he was battered and falsely imprisoned by the officers"',
  '"the loss of his baby turned him into a domineering bully who battered his partner"',
  '"men have also been battered by their spouses or partners"',
  '"he was battered at times by critics"',
  '"pancake batter"',
  '"a batter thin enough to be poured"',
  '"the replay goes into a slow-motion view and zooms in on the batter as he hits a ball out"',
  '"the batter is an inch in for every foot of height"',
];
export const synonyms = [
  'pummel',
  'pound',
  'buffet',
  'belabor',
  'thrash',
  'beat up',
  'abuse',
  'hit',
  'strike',
  'beat',
  'smack',
  'assault',
  'attack',
  'thump',
  'lash',
  'damage',
  'injure',
  'hurt',
  'harm',
  'impair',
  'mar',
  'spoil',
  'destroy',
  'demolish',
  'crush',
  'shatter',
  'smash',
  'ruin',
  'rain blows on',
  'aim blows at',
];