export const definitions = [
  '"Stephen was battening down the shutters"',
  '"multinational monopolies batten on the working classes"',
];
export const synonyms = [
  'bar',
  'bolt',
  'clamp',
  'rail',
  'shaft',
  'board',
  'strip',
  'fasten',
  'fix',
  'secure',
  'clamp',
  'clasp',
  'bolt',
  'rivet',
  'lash',
  'nail down',
  'seal',
  'tether',
  'make fast',
  'flourish at the expense of',
  'thrive at the expense of',
  'fatten at the expense of',
  'prosper at the expense of',
  'gain at the expense of',
  'be a parasite on',
];