export const definitions = [
    '"the ______ of Shiloh"',
    '"he died in ______"',
    '"the ______ against aging"',
    '"the ______ over the future shape of Europe"',
    '"he needs to ______ against the illness"',
    '"representatives from eight countries will ______ for the title"',
    '"firefighters ______d a 9,800-acre brush fire"',
];
export const synonyms = [
    'fight',
    'conflict',
    'clash',
    'struggle',
    'skirmish',
    'engagement',
    'dogfight',
    'affray',
    'fray',
    'encounter',
    'confrontation',
    'contest',
    'meeting',
    'collision',
    'duel',
    'tussle',
    'scuffle',
    'melee',
    'fracas',
    'war',
    'campaign',
    'crusade',
    'fighting',
    'warfare',
    'combat',
    'action',
    'hostilities',
    'armed conflict',
    'truce',
    'peace',
    'conflict',
    'clash',
    'contest',
    'competition',
    'struggle',
    'disagreement',
    'argument',
    'dispute',
    'controversy',
    'debate',
    'dissension',
    'altercation',
    'strife',
    'fight',
    'combat',
    'resist',
    'withstand',
    'stand up to',
    'confront',
    'war',
    'feud',
    'struggle',
    'strive',
    'campaign',
    'work',
    'toil',
    'contend with',
    'put up a fight against',
    'give up',
    'give in',
    'scramble',
    'struggle',
    'labor',
    'fight',
    'elbow',
    'push',
]