export const definitions = [
  '"clutch bags embellished with glittering baubles"',
  '"people in quest of honors are wasting time and effort to secure baubles"',
];
export const synonyms = [
  'trinket',
  'knickknack',
  'ornament',
  'toy',
  'novelty',
  'curiosity',
  'gimmick',
  'plaything',
  'trifle',
  'frippery',
  'gewgaw',
  'gimcrack',
  'bagatelle',
  'bibelot',
  'furbelow',
  'folderol',
  'whim-wham',
  'kickshaw',
  'bijou',
  'gaud',
];