export const definitions = [
  '"the dogs bayed"',
  '"a jackal baying at the moon"',
  '"as a mob bayed below, the king was dead"',
  '"a pack of wolves baying at the moon"',
];
export const synonyms = [
  'howl',
  'bark',
  'yelp',
  'yap',
  'cry',
  'growl',
  'bellow',
  'roar',
  'clamor',
  'snarl',
  'ululate',
  'clamor',
  'shout',
  'call',
  'press',
  'yell',
  'scream',
  'shriek',
  'roar',
  'demand',
  'urge',
  'claim',
  'insist on',
  'make a claim for',
];