export const definitions = [
  '"beaming a distress signal into space"',
  '"the TV station begins beaming into homes in the new year"',
  '"Scotty, beam me up!"',
  '"the sun\'s rays beamed down"',
  '"she beamed with pleasure"',
  '"a beaming smile"',
  '"the teacher beamed her approval"',
  '"\"Isn\'t that wonderful, Beatrice ?\" beamed the nun"',
  '"vaulted beamed ceilings in the family room"',
];
export const synonyms = [
  'broadcast',
  'transmit',
  'relay',
  'disseminate',
  'direct',
  'aim',
  'televise',
  'show',
  'telecast',
  'send/put out',
  'put on the air/airwaves',
  'shine',
  'radiate',
  'glare',
  'glitter',
  'gleam',
  'shimmer',
  'glimmer',
  'twinkle',
  'flash',
  'flare',
  'streak',
  'grinning',
  'smiling',
  'laughing',
  'cheerful',
  'happy',
  'radiant',
  'glowing',
  'sunny',
  'joyful',
  'elated',
  'thrilled',
  'delighted',
  'overjoyed',
  'rapturous',
  'blissful',
  'bright',
  'cheery',
  'sparkling',
  'flashing',
  'brilliant',
  'dazzling',
  'intense',
  'gleaming',
  'grin',
  'smile',
  'dimple',
  'twinkle',
  'smirk',
  'laugh',
  'grin like a Cheshire Cat',
  'frowning',
  'frown',
  'grinning',
  'smiling',
  'laughing',
  'cheerful',
  'happy',
  'radiant',
  'glowing',
  'sunny',
  'joyful',
  'elated',
  'thrilled',
  'delighted',
  'overjoyed',
  'rapturous',
  'blissful',
  'frowning',
];