export const definitions = [
    '"a flag-bearer"',
    '"I\'m sorry to be the bearer of bad tidings"',
    '"promissory notes payable to the bearer"',
    '"bearer bonds"',
]
export const synonyms = [
    'messenger',
    'agent',
    'conveyor',
    'emissary',
    'carrier',
    'provider',
    'runner',
    'courier',
    'carrier',
    'porter',
    'conveyor',
    'transporter',
    'holder',
    'possessor',
    'owner',
    'payee',
    'consignee',
    'beneficiary',
]