export const definitions = [
    '"wild ______"',
    '"the gift of reason differentiates humanity from the ______"',
    '"filthy drunken ______"',
    '"scheming, manipulative little ______"',
    '"the ______ roar their ugly head"',
    '"altered ______"',
];
export const synonyms = [
    'animal',
    'creature',
    'brute',
    'monster',
    'brute',
    'savage',
    'barbarian',
    'animal',
    'swine',
    'pig',
    'ogre',
    'fiend',
    'sadist',
    'demon',
    'devil',
    'wretch',
    'blackguard',
    'dastard',
    'knave',
    'varlet',
    'whoreson',
]
