export const definitions = [
    '"a wild beast"',
    '"the gift of reason differentiates humanity from the beasts"',
    '"he is a filthy drunken beast"',
    '"a scheming, manipulative little beast"',
    '"the beast in you is rearing its ugly head"',
    '"that much-maligned beast, the rave record"',
];
export const synonyms = [
    'animal',
    'creature',
    'brute',
    'monster',
    'brute',
    'savage',
    'barbarian',
    'animal',
    'swine',
    'pig',
    'ogre',
    'fiend',
    'sadist',
    'demon',
    'devil',
    'wretch',
    'blackguard',
    'dastard',
    'knave',
    'varlet',
    'whoreson',
]
