export const definitions = [
    '"I knew when I was beaten"',
    '"he sat feeling old and beaten"',
    '"he trudged home like a beaten dog"',
    '"beaten eggs"',
    '"beaten copper coffee tables"',
    '"if we were caught we were beaten"',
    '"the victims were beaten to death with baseball bats"',
    '"they beat me with a stick and punched me"',
    '"he beat the table with his hand"',
    '"drums were beating in the distance"',
    '"upright cleaners have a motorized head which beats the carpet to loosen the dirt"',
    '"pure gold can be beaten out to form very thin sheets"',
    '"she beat her fists against the wood"',
    '"Sid beat on the door with the flat of his hand"',
    '"Emmie began to beat at the flames"',
    '"outside the rain beat against the windows"',
    '"she beat him easily at chess"',
    '"the Senators beat out the Yankees for the 1933 pennant"',
    '"he beat heroin addiction in 1992"',
    '"they are investing their savings in hopes of beating inflation"',
    '"he beat his own world record"',
    '"you can\'t beat the taste of fresh raspberries"',
    '"it beats me how you manage to work in this heat"',
    '"the goalie beat him to the ball"',
    '"I could beat him on my bicycle"',
    '"they set off early to beat the traffic"',
    '"her heart beat faster with panic"',
    '"doves wheel around the rooftops, beating their wings"',
    '"an owl beat low over the salt marsh"',
    '"beat the butter until light and fluffy"',
    '"beat the cream into the mixture"',
    '"we beat southward all that first day"',
];
export const synonyms = [
    'unprofitable',
    'unprosperous',
    'loss-making',
    'failed',
    'losing',
    'unlucky',
    'luckless',
    'unfortunate',
    'ill-starred',
    'fated',
    'ill-fated',
    'ill-omened',
    'out of luck',
    'profitable',
    'winning',
    'defeated',
    'losing',
    'unsuccessful',
    'conquered',
    'bettered',
    'vanquished',
    'trounced',
    'routed',
    'overcome',
    'overwhelmed',
    'overpowered',
    'overthrown',
    'bested',
    'subdued',
    'quashed',
    'crushed',
    'broken',
    'foiled',
    'hapless',
    'luckless',
    'victorious',
    'winning',
    'abused',
    'battered',
    'maltreated',
    'ill-treated',
    'mistreated',
    'misused',
    'downtrodden',
    'assaulted',
    'thumped',
    'hit',
    'thrashed',
    'pummeled',
    'smacked',
    'drubbed',
    'whisked',
    'whipped',
    'stirred',
    'mixed',
    'blended',
    'frothy',
    'foamy',
    'hammered',
    'forged',
    'formed',
    'shaped',
    'molded',
    'worked',
    'stamped',
    'fashioned',
    'modeled',
    'fabricated',
    'cast',
    'sculpted',
    'dimpled',
    'pockmarked',
    'spotted',
    'trodden',
    'trampled',
    'well trodden',
    'well used',
    'worn',
    'well worn',
    'much trodden',
    'much traveled',
    'hit',
    'strike',
    'batter',
    'thump',
    'hammer',
    'punch',
    'knock',
    'thrash',
    'pound',
    'pummel',
    'slap',
    'smack',
    'crack',
    'thwack',
    'cuff',
    'buffet',
    'maul',
    'pelt',
    'drub',
    'assault',
    'attack',
    'abuse',
    'flay',
    'whip',
    'lash',
    'cudgel',
    'club',
    'birch',
    'chastise',
    'rain blows on',
    'bang',
    'hit',
    'strike',
    'rap',
    'tap',
    'pound',
    'thump',
    'hammer',
    'play',
    'sound',
    'perform on',
    'make music on',
    'hammer',
    'forge',
    'form',
    'shape',
    'mold',
    'work',
    'stamp',
    'fashion',
    'model',
    'fabricate',
    'make',
    'cast',
    'frame',
    'sculpt',
    'sculpture',
    'pound',
    'batter',
    'buffet',
    'strike',
    'hit',
    'knock',
    'beat against',
    'dash against',
    'crash against',
    'smack against',
    'bang',
    'tap',
    'rap',
    'thump',
    'pound',
    'hammer',
    'strike',
    'hit',
    'batter',
    'buffet',
    'pummel',
    'defeat',
    'conquer',
    'get the better of',
    'vanquish',
    'trounce',
    'rout',
    'overpower',
    'overcome',
    'overwhelm',
    'overthrow',
    'subdue',
    'quash',
    'crush',
    'win against',
    'handle',
    'manage',
    'address',
    'face',
    'face up to',
    'confront',
    'tackle',
    'sort out',
    'take care of',
    'put up with',
    'get through',
    'weather',
    'endure',
    'withstand',
    'stand up to',
    'bear',
    'brave',
    'accept',
    'come to terms with',
    'master',
    'overcome',
    'surmount',
    'get over',
    'get the better of',
    'deal with',
    'take in hand',
    'get to grips with',
    'contend with',
    'grapple with',
    'wrestle with',
    'struggle with',
    'tussle with',
    'surpass',
    'outdo',
    'exceed',
    'eclipse',
    'transcend',
    'top',
    'trump',
    'cap',
    'better',
    'outperform',
    'outstrip',
    'outshine',
    'outclass',
    'overshadow',
    'put in the shade',
    'be better than',
    'improve on',
    'go one better than',
    'baffle',
    'bewilder',
    'mystify',
    'bemuse',
    'perplex',
    'puzzle',
    'confuse',
    'confound',
    'nonplus',
    'disconcert',
    'throw',
    'disorientate',
    'wilder',
    'gravel',
    'maze',
    'distract',
    'pose',
    'obfuscate',
    'throw off balance',
    'take aback',
    'set thinking',
    'cause to be at a stand',
    'avoid',
    'evade',
    'escape',
    'dodge',
    'sidestep',
    'elude',
    'get around',
    'circumvent',
    'steer clear of',
    'bypass',
    'skirt',
    'cheat',
    'duck',
    'give a wide berth to',
    'find a way around',
    'get caught up in',
    'pulsate',
    'pulse',
    'palpitate',
    'vibrate',
    'throb',
    'reverberate',
    'pump',
    'pound',
    'thump',
    'thud',
    'hammer',
    'drum',
    'pitter-patter',
    'go pit-a-pat',
    'quop',
    'flap',
    'flutter',
    'thresh',
    'thrash',
    'wave',
    'shake',
    'swing',
    'agitate',
    'quiver',
    'tremble',
    'vibrate',
    'oscillate',
    'move up and down',
    'flutter',
    'agitate',
    'wave',
    'wag',
    'waggle',
    'shake',
    'swing',
    'twitch',
    'thresh',
    'thrash',
    'flail',
    'vibrate',
    'quiver',
    'tremble',
    'oscillate',
    'move up and down',
    'whisk',
    'mix',
    'blend',
    'whip',
    'stir',
    'fold',
    'swerve',
    'zigzag',
    'go about',
    'come about',
    'change course',
    'change direction',
    'change heading',
    'veer off/away',
    'sail into the wind',
]
