export const definitions = [
    '"there was bedlam in the courtroom"',
]
export const synonyms = [
    'uproar',
    'pandemonium',
    'commotion',
    'mayhem',
    'confusion',
    'unrest',
    'furor',
    'upheaval',
    'hubbub',
    'hurly-burly',
    'turmoil',
    'riot',
    'ruckus',
    'tumult',
    'disarray',
    'turbulence',
    'disorder',
    'chaos',
    'anarchy',
    'lawlessness',
    'calm',
    'psychiatric hospital',
    'hospital',
    'home',
    'institution',
    'mental institution',
    'mental hospital',
    'madhouse',
    'psychiatric unit',
]