export const definitions = [
    '"they hoped that the King might beget an heir by his new queen"',
    '"success begets further success"',
]
export const synonyms = [
    'father',
    'sire',
    'engender',
    'generate',
    'spawn',
    'create',
    'have',
    'procreate',
    'reproduce',
    'breed',
    'give life to',
    'bring into being',
    'bring into the world',
    'cause',
    'give rise to',
    'bring about',
    'create',
    'produce',
    'generate',
    'engender',
    'spawn',
    'occasion',
    'effect',
    'bring on',
    'precipitate',
    'prompt',
    'provoke',
    'kindle',
    'trigger',
    'touch off',
    'stir up',
    'whip up',
    'induce',
    'inspire',
    'promote',
    'foster',
    'enkindle',
    'effectuate',
    'lead to',
    'result in',
    'bring to pass',
    'spark off',
]