export const definitions = [
  '"he always behaved like a gentleman"',
  '"you should behave affectionately toward the patient"',
  '"each car behaves differently"',
  '"they were expected to behave themselves"',
  '"you can go as long as you behave"',
];
export const synonyms = [
  'act',
  'conduct oneself',
  'acquit oneself',
  'bear oneself',
  'carry oneself',
  'comport oneself',
  'deport oneself',
  'function',
  'go',
  'run',
  'operate',
  'perform',
  'be in working order',
  'act correctly',
  'act properly',
  'conduct oneself well',
  'act in a polite way',
  'show good manners',
  'mind one\'s manners',
  'mind \'s \'s Ps and Qs',
  'be good',
  'be polite',
  'be well behaved',
  'misbehave',
];