export const definitions = [
  '"votes cast by labor unions on behalf of their members"',
  '"he had to attend the funeral on Mama\'s behalf"',
  '"this wasn\'t simply a philanthropic gesture on his behalf"',
];
export const synonyms = [
  'in the interests of',
  'in support of',
  'for',
  'for the benefit of',
  'on account of',
  'for the good of',
  'for the sake of',
  'to the advantage of',
  'to the profit of',
  'for',
  'in the name of',
  'in place of',
  'representing',
  'in the interests of',
  'as a representative of',
  'as a spokesperson for',
  'with power of attorney for',
  'on the authority of',
  'at the behest of',
  'appearing for',
  'for',
  'in the name of',
  'in place of',
  'representing',
  'in the interests of',
  'as a representative of',
  'as a spokesperson for',
  'with power of attorney for',
  'on the authority of',
  'at the behest of',
  'appearing for',
];
