export const definitions = [
  '"his belief in the value of hard work"',
  '"a belief that solitude nourishes creativity"',
  '"we\'re prepared to fight for our beliefs"',
  '"contrary to popular belief, Aramaic is a living language"',
  '"Christian beliefs"',
  '"I\'m afraid to say belief has gone"',
  '"local beliefs and customs"',
  '"a belief in democratic politics"',
  '"I\'ve still got belief in myself"',
];
export const synonyms = [
  'guess',
  'speculation',
  'surmise',
  'fancy',
  'notion',
  'suspicion',
  'presumption',
  'assumption',
  'theory',
  'hypothesis',
  'postulation',
  'supposition',
  'inference',
  'extrapolation',
  'projection',
  'approximation',
  'estimate',
  'guesswork',
  'guessing',
  'surmising',
  'imagining',
  'theorizing',
  'rough calculation',
  'rough idea',
  'fact',
  'opinion',
  'view',
  'viewpoint',
  'point of view',
  'attitude',
  'stance',
  'stand',
  'standpoint',
  'position',
  'perspective',
  'contention',
  'conviction',
  'judgment',
  'thinking',
  'thought',
  'idea',
  'theory',
  'hypothesis',
  'thesis',
  'interpretation',
  'assumption',
  'presumption',
  'supposition',
  'surmise',
  'postulation',
  'conclusion',
  'deduction',
  'inference',
  'notion',
  'impression',
  'sense',
  'feeling',
  'fancy',
  'hunch',
  'way of thinking',
  'ideology',
  'principle',
  'ideal',
  'ethic',
  'conviction',
  'doctrine',
  'teaching',
  'dogma',
  'tenet',
  'canon',
  'credence',
  'creed',
  'credo',
  'article of faith',
  'code of belief',
  'faith',
  'trust',
  'reliance',
  'confidence',
  'credence',
  'optimism',
  'hopefulness',
  'hope',
  'freedom from doubt',
  'disbelief',
  'doubt',
];
