export const definitions = [
  '"he bellowed in agony"',
  '"the bellowing of a bull"',
  '"he bellowed out the order"',
  '"the watchers were bellowing encouragement"',
  '"\"God send the right!\" he bellowed"',
  '"his desperate parents were bellowing at her to stop"',
  '"he got thrown out of bars for bellowing Portuguese folk songs"',
  '"a bellow of rage"',
  '"he delivers his lines in a bellow"',
];
export const synonyms = [
  'blare',
  'boom',
  'roar',
  'thunder',
  'pump',
  'shriek',
  'screech',
  'roar',
  'shout',
  'bawl',
  'thunder',
  'trumpet',
  'boom',
  'bark',
  'bay',
  'yawp',
  'yell',
  'yelp',
  'shriek',
  'howl',
  'scream',
  'screech',
  'call',
  'cry',
  'cry out',
  'whoop',
  'wail',
  'caterwaul',
  'raise one\'s voice',
  'vociferate',
  'ululate',
  'sing out',
  'whisper',
  'roar',
  'shout',
  'bawl',
  'bark',
  'bay',
  'yawp',
  'yell',
  'yelp',
  'shriek',
  'howl',
  'scream',
  'screech',
  'call',
  'cry',
  'whoop',
  'wail',
  'caterwaul',
  'vociferation',
  'ululation',
  'whisper',
];