export const definitions = [
  '"a belted black and gold dress"',
  '"a belted kingfisher"',
  '"a belted earl"',
  '"she belted her raincoat firmly"',
  '"she paused only to belt a robe about her waist"',
  '"the jacket belts at the waist"',
  '"he was securely belted into the passenger seat"',
  '"she belted him over the head with her racquet"',
  '"he belted the ball to the left-field fence"',
  '"they belted along the empty road"',
  '"cocktails should be sipped and savored, not belted down"',
  '"he belted it back and poured another"',
];
export const synonyms = [
  'fasten',
  'tie',
  'bind',
  'encircle',
  'gird',
  'encompass',
  'circle',
  'speed',
  'hurry',
  'race',
  'run',
  'sprint',
  'dash',
  'bolt',
  'dart',
  'rush',
  'hasten',
  'hurtle',
  'career',
  'streak',
  'shoot',
  'whiz',
  'zoom',
  'whirl',
  'whoosh',
  'buzz',
  'swoop',
  'flash',
  'blast',
  'charge',
  'stampede',
  'gallop',
  'sweep',
  'hare',
  'fly',
  'wing',
  'scurry',
  'scud',
  'scutter',
  'scramble',
  'fleet',
  'post',
  'hie',
  'drive',
  'go like lightning',
  'go hell for leather',
  'spank along',
  'bowl along',
  'rattle along',
  'amble',
  'stroll',
];
