export const definitions = [
    '"his benign but firm manner"',
    '"her face was calm and benign"',
    '"the climate becomes more benign as we move nearer to the Black Sea"',
    '"an ozone-benign refrigerant"',
    '"a benign condition"',
    '"benign growths"',
]
export const synonyms = [
    'kindly',
    'kind',
    'warmhearted',
    'good-natured',
    'friendly',
    'warm',
    'affectionate',
    'agreeable',
    'amiable',
    'good-humored',
    'genial',
    'congenial',
    'cordial',
    'approachable',
    'tender',
    'tenderhearted',
    'softhearted',
    'gentle',
    'sympathetic',
    'compassionate',
    'caring',
    'considerate',
    'thoughtful',
    'helpful',
    'well disposed',
    'obliging',
    'accommodating',
    'generous',
    'big-hearted',
    'unselfish',
    'benevolent',
    'gracious',
    'liberal',
    'indulgent',
    'benignant',
    'unfriendly',
    'hostile',
    'temperate',
    'mild',
    'gentle',
    'clement',
    'calm',
    'balmy',
    'pleasant',
    'agreeable',
    'soft',
    'soothing',
    'refreshing',
    'healthy',
    'health-giving',
    'wholesome',
    'salubrious',
    'favorable',
    'advantageous',
    'beneficial',
    'helpful',
    'propitious',
    'auspicious',
    'lucky',
    'opportune',
    'fortunate',
    'providential',
    'encouraging',
    'benevolent',
    'conducive',
    'right',
    'good',
    'harsh',
    'unhealthy',
    'unfavorable',
    'harmless',
    'noncancerous',
    'innocent',
    'curable',
    'remediable',
    'treatable',
    'removable',
    'benignant',
    'nonmalignant',
    'nondangerous',
    'malignant',
]