export const definitions = [
    '"his mother came out and berated me for raising my voice"',
]
export const synonyms = [
    'rebuke',
    'reprimand',
    'reproach',
    'reprove',
    'admonish',
    'chastise',
    'chide',
    'upbraid',
    'pull up',
    'castigate',
    'lambaste',
    'read someone the Riot Act',
    'give someone a piece of one\'s mind',
    'go on at',
    'criticize',
    'censure',
    'call down',
    'rate',
    'trim',
    'reprehend',
    'objurgate',
    'remonstrate with',
    'take to task',
    'haul over the coals',
    'give someone a rating',
    'praise',
]