export const definitions = [
    '"he sat beside me in the front seat"',
    '"on the table beside the bed"',
    '"beside Beth\'s idealism, my priorities looked shabby"',
    '"he commissioned work from other artists beside Rivera"',
]
export const synonyms = [
    'alongside',
    'by the side of',
    'next to',
    'at someone\'s elbow',
    'with',
    'by',
    'next door to',
    'hard by',
    'bordering',
    'abutting',
    'neighboring',
    'close to',
    'near',
    'overlooking',
    'at the side of',
    'parallel to',
    'abreast of',
    'adjacent to',
    'cheek by jowl with',
    'aside of',
    'next to',
    'against',
    'compared with',
    'in comparison with',
    'contrasted with',
    'in contrast to/with',
]