export const definitions = [
  '"the office was bestowed on him by the chief of state"',
  '"thank you for this honor that you have bestowed upon me"',
  '"she bestowed her nicest smile on Jim"',
];
export const synonyms = [
  'give',
  'grant',
  'vouchsafe',
  'confer on',
  'present to',
  'award to',
  'accord to',
  'afford to',
  'vest in',
  'invest in',
  'bequeath to',
  'donate to',
  'allot to',
  'assign to',
  'consign to',
  'apportion to',
  'distribute to',
  'impart to',
  'entrust to',
  'commit to',
  'lavish on',
  'heap on',
];