export const definitions = [
    '"I waited with beating heart, as yet not knowing what would betide"',
    '"she was trembling with fear lest worse might betide her"',
]
export const synonyms = [
    'happen',
    'occur',
    'take place',
    'come about',
    'transpire',
    'arise',
    'chance',
    'result',
    'ensue',
    'follow',
    'develop',
    'supervene',
    'come to pass',
    'befall',
    'bechance',
    'hap',
    'arrive',
    'eventuate',
    'overtake',
    'befall',
    'happen to',
    'be the fate of',
    'be the lot of',
    'be visited on',
]