export const definitions = [
    '"there was evidence of bias against foreign applicants"',
    '"the bias toward younger people in recruitment"',
    '"a systematic bias in favor of the powerful"',
    '"he worked on a variety of Greek topics, with a discernible bias toward philosophy"',
    '"I\'m a fan of Blackpink and my bias is Jennie"',
    '"a turquoise silk dress cut on the bias"',
    '"the search results are biased by the specific queries used"',
    '"common sense biases me against these theories"',
]
export const synonyms = [
    'prejudice',
    'partiality',
    'partisanship',
    'favoritism',
    'unfairness',
    'one-sidedness',
    'bigotry',
    'intolerance',
    'racism',
    'racialism',
    'sexism',
    'heterosexism',
    'homophobia',
    'chauvinism',
    'anti-Semitism',
    'discrimination',
    'predisposition',
    'leaning',
    'tendency',
    'inclination',
    'propensity',
    'proclivity',
    'proneness',
    'predilection',
    'parti pris',
    'a jaundiced eye',
    'objectivity',
    'fairness',
    'impartiality',
    'diagonal',
    'cross',
    'slant',
    'oblique',
    'angle',
    'prejudice',
    'influence',
    'color',
    'sway',
    'weight',
    'predispose',
    'distort',
    'skew',
    'bend',
    'twist',
    'warp',
    'angle',
    'load',
    'slant',
]