export const definitions = [
    '"whenever the phone rings, they bicker over who must answer it"',
    '"the constant bickering between Edgar and his mother"',
    '"against the glass the rain did beat and bicker"',
    '"the restless wheels whose flashing spokes bicker and burn"',
]
export const synonyms = [
    'squabble',
    'argue',
    'quarrel',
    'wrangle',
    'fight',
    'fall out',
    'disagree',
    'dispute',
    'spar',
    'be at each other\'s throats',
    'lock horns',
    'altercate',
    'chop logic',
    'have a disagreement',
    'bandy words',
    'have words',
    'agree',
    'pitter-patter',
    'tap',
    'drum',
    'clatter',
    'beat',
    'pound',
    'rattle',
    'throb',
    'pulsate',
    'rat-a-tat',
    'pit-a-pat',
    'clack',
    'click-clack',
    'thrum',
    'go pit-a-pat',
    'clacket',
]