export const definitions = [
    '"he biffed me on the nose"',
]
export const synonyms = [
    'strike',
    'slap',
    'smack',
    'cuff',
    'punch',
    'beat',
    'thrash',
    'thump',
    'batter',
    'belabor',
    'drub',
    'hook',
    'pound',
    'smash',
    'slam',
    'welt',
    'pummel',
    'hammer',
    'bang',
    'knock',
    'swat',
    'whip',
    'flog',
    'cane',
    'sucker-punch',
    'box someone\'s ears',
    'smite',
    'swinge',
    'baste',
    'buffet',
    'birch',
    'rain blows on',
    'give someone a (good) beating/drubbing',
]