export const definitions = [
    '"big hazel eyes"',
    '"big buildings"',
    '"big cuts in staff"',
    '"my big toe"',
    '"I\'m a big girl now"',
    '"my big sister"',
    '"a small company with big plans"',
    '"a big eater"',
    '"a big gambler"',
    '"a big tennis fan"',
    '"he tells me the Inuits of the Arctic are very big on Jim Reeves"',
    '"my wife was big with child"',
    '"a word big with fate"',
    '"it\'s a big decision"',
    '"M\'s \'s biggest problem is money"',
    '"he made a big mistake"',
    '"Latino bands that are big in Los Angeles"',
    '"as a senior in college, he was a big man on campus"',
    '"\"I\'m inclined to take pity on you.\" \"That\'s big of you!\""',
]
export const synonyms = [
    'large',
    'sizeable',
    'substantial',
    'considerable',
    'great',
    'huge',
    'immense',
    'enormous',
    'extensive',
    'colossal',
    'massive',
    'mammoth',
    'vast',
    'prodigious',
    'tremendous',
    'gigantic',
    'giant',
    'monumental',
    'mighty',
    'stupendous',
    'gargantuan',
    'elephantine',
    'titanic',
    'epic',
    'mountainous',
    'megalithic',
    'monstrous',
    'Brobdingnagian',
    'towering',
    'tall',
    'high',
    'lofty',
    'outsize',
    'oversized',
    'overgrown',
    'cumbersome',
    'unwieldy',
    'inordinate',
    'unlimited',
    'goodly',
    'capacious',
    'voluminous',
    'commodious',
    'spacious',
    'massy',
    'well built',
    'heavily built',
    'sturdy',
    'brawny',
    'burly',
    'broad-shouldered',
    'muscular',
    'muscly',
    'robust',
    'rugged',
    'lusty',
    'Herculean',
    'bulky',
    'strapping',
    'thickset',
    'stocky',
    'solid',
    'hefty',
    'meaty',
    'fat',
    'stout',
    'portly',
    'plump',
    'heavy',
    'overweight',
    'fleshy',
    'paunchy',
    'corpulent',
    'obese',
    'stalwart',
    'thewy',
    'stark',
    'of considerable size',
    'good-size(d)',
    'fair-size(d)',
    'king-size(d)',
    'man-size',
    'family-size(d)',
    'economy-size(d)',
    'sturdily built',
    'well muscled',
    'oversize',
    'small',
    'little',
    'slight',
    'short',
    'grown-up',
    'adult',
    'mature',
    'grown',
    'full grown',
    'elder',
    'older',
    'older',
    'senior',
    'first',
    'firstborn',
    'more grown up',
    'younger',
    'little',
    'ambitious',
    'far-reaching',
    'grandiose',
    'unrealistic',
    'overambitious',
    'on a grand scale',
    'modest',
    'important',
    'significant',
    'major',
    'momentous',
    'weighty',
    'consequential',
    'far-reaching',
    'key',
    'vital',
    'critical',
    'crucial',
    'life-and-death',
    'high-priority',
    'serious',
    'grave',
    'solemn',
    'no laughing matter',
    'of great import',
    'of significance',
    'of moment',
    'of consequence',
    'no joke',
    'minor',
    'unimportant',
    'trivial',
    'popular',
    'successful',
    'in demand',
    'sought-after',
    'commercially successful',
    'all the rage',
    'powerful',
    'important',
    'prominent',
    'influential',
    'high-powered',
    'leading',
    'preeminent',
    'outstanding',
    'well known',
    'eminent',
    'distinguished',
    'principal',
    'foremost',
    'noteworthy',
    'notable',
    'noted',
    'major-league',
    'of high standing',
    'unimportant',
    'obscure',
    'generous',
    'kind',
    'kindly',
    'kindhearted',
    'caring',
    'compassionate',
    'loving',
    'benevolent',
    'magnanimous',
    'unselfish',
    'altruistic',
    'selfless',
    'philanthropic',
]