export const definitions = [
    '"her dress billowed out around her"',
    '"smoke was billowing from the chimney"',
]
export const synonyms = [
    'cloud',
    'mass',
    'wave',
    'roller',
    'breaker',
    'swell',
    'fill out',
    'puff up/out',
    'balloon (out)',
    'bulge out',
    'belly out',
    'pour',
    'flow',
    'swirl',
    'spiral',
    'roll',
    'undulate',
    'eddy',
    'rise and fall',
]