export const definitions = [
    '"he was blind from birth"',
    '"despite a difficult birth he\'s fit and healthy"',
    '"the birth of democracy"',
    '"the mother is American by birth"',
    '"he is not of noble birth"',
    '"she had carried him and birthed him"',
    '"in spring the cows birthed"',
];
export const synonyms = [
    'childbirth',
    'delivery',
    'nativity',
    'birthing',
    'parturition',
    'confinement',
    'accouchement',
    'childbed',
    'death',
    'beginning(s)',
    'emergence',
    'genesis',
    'dawn',
    'dawning',
    'rise',
    'start',
    'arrival',
    'advent',
    'origin',
    'source',
    'fountainhead',
    'end',
    'demise',
    'ancestry',
    'descent',
    'origin(s)',
    'parentage',
    'lineage',
    'line',
    'heritage',
    'family',
    'stock',
    'blood',
    'bloodline',
    'genealogy',
    'breeding',
    'pedigree',
    'house',
    'extraction',
    'derivation',
    'background',
    'filiation',
    'line of descent',
    'stirps',
    'have',
    'bear',
    'produce',
    'mother',
    'bring forth',
    'be delivered of',
    'bring into the world',
    'be brought to bed of',
]
