export const definitions = [
    '"the raw berries have an intensely bitter flavor"',
    '"I don\'t feel jealous or bitter"',
    '"a bitter five-year legal battle"',
    '"today\'s decision has come as a bitter blow"',
    '"a bitter wind blowing from the east"',
    '"a pint of bitter"',
    '"the company brews a range of bitters"',
    '"a dash of bitters"',
];
export const synonyms = [
    'sharp',
    'acid',
    'acidic',
    'pungent',
    'acrid',
    'tart',
    'sour',
    'biting',
    'harsh',
    'unsweetened',
    'vinegary',
    'acetous',
    'acerb',
    'acerbic',
    'sweet',
    'resentful',
    'embittered',
    'aggrieved',
    'dissatisfied',
    'disgruntled',
    'discontented',
    'grudging',
    'begrudging',
    'indignant',
    'rancorous',
    'splenetic',
    'spiteful',
    'jaundiced',
    'ill-disposed',
    'sullen',
    'sour',
    'churlish',
    'morose',
    'petulant',
    'peevish',
    'grudge-bearing',
    'with a chip on one\'s shoulder',
    'magnanimous',
    'content',
    'acrimonious',
    'virulent',
    'angry',
    'rancorous',
    'spiteful',
    'vindictive',
    'vicious',
    'vitriolic',
    'savage',
    'hostile',
    'ferocious',
    'scathing',
    'antagonistic',
    'hate-filled',
    'venomous',
    'poisonous',
    'acrid',
    'bilious',
    'nasty',
    'ill-natured',
    'malign',
    'choleric',
    'amicable',
    'painful',
    'unpleasant',
    'disagreeable',
    'nasty',
    'cruel',
    'awful',
    'distressing',
    'disquieting',
    'disturbing',
    'upsetting',
    'harrowing',
    'heartbreaking',
    'heart-rending',
    'agonizing',
    'unhappy',
    'miserable',
    'wretched',
    'sad',
    'poignant',
    'grievous',
    'traumatic',
    'tragic',
    'chilling',
    'mortifying',
    'galling',
    'vexatious',
    'distressful',
    'welcome',
    'freezing',
    'icy',
    'icy-cold',
    'arctic',
    'glacial',
    'frosty',
    'frigid',
    'chilly',
    'piercing',
    'penetrating',
    'biting',
    'nipping',
    'stinging',
    'sharp',
    'keen',
    'raw',
    'harsh',
    'wintry',
    'chill',
    'intensely cold',
    'bitterly cold',
    'warm',
    'balmy',
]
