export const definitions = [
    '"a tray decorated in black and green"',
    '"a series of paintings done only in grays and blacks"',
    '"dressed in the black of widowhood"',
    '"the only thing visible in the black was the light of the lantern"',
    '"Black\'s king\'s defenses are somewhat weakened"',
    '"a rum and black"',
    '"I managed to break even in the first six months—quite a short time for a small business to get into the black"',
    '"the company just managed to stay in the black"',
    '"the house was pocked with bullet holes and blacked by smoke"',
    '"the union blacked the film because overtime was not being paid"',
]
export const synonyms = [
    'widow\'s weeds',
    'weeds',
    'sackcloth and ashes',
    'sables',
    'black clothes',
    'in funds',
    'debt-free',
    'solvent',
    'creditworthy',
    'solid',
    'secure',
    'profit-making',
    'profitable',
    'in credit',
    'out of debt',
    'financially sound',
    'able to pay one\'s debts',
    'of good financial standing',
    'unindebted',
    'in debt',
    'blacken',
    'darken',
    'dirty',
    'stain',
    'grime',
    'begrime',
    'befoul',
    'soil',
    'make dirty',
    'make sooty',
    'make smoky',
    'boycott',
    'embargo',
    'blacklist',
    'ban',
    'bar',
    'proscribe',
    'put/place an embargo on',
]