export const definitions = [
    '"the cold light blanched her face"',
    '"blanch endive by covering plants with large flowerpots"',
    '"many people blanch at the suggestion"',
    '"their faces blanched with fear"',
    '"blanch the almonds and grind them to a paste, adding a little water"',
    '"I blanched the carrots for a couple of minutes before roasting them"',
]
export const synonyms = [
    'whiten',
    'lighten',
    'gray',
    'wash out',
    'fade',
    'blench',
    'decolorize',
    'bleach',
    'peroxide',
    'pale',
    'make/turn pale',
    'make/turn pallid',
    'etiolate',
    'go/grow/turn/become pale',
    'go/grow/turn/become white',
    'go/grow/turn/become pallid',
    'lose its color',
    'color',
    'darken',
    'redden',
    'blush',
    'wince',
    'start',
    'recoil',
    'shrink',
    'pull back',
    'back away',
    'draw back',
    'withdraw',
    'blench',
    'cringe',
    'squirm',
    'quiver',
    'shudder',
    'shiver',
    'tremble',
    'quake',
    'shake',
    'quail',
    'cower',
    'waver',
    'falter',
    'hesitate',
    'shy (away)',
    'shy away',
    'get cold feet',
    'stand firm',
]