export const definitions = [
  '"leave blanks to type in the appropriate names"',
  '"this measure required subjects to fill in the blanks in a story"',
  '"my mind was a total blank"',
  '"electronic countermeasures blanked out the radar signals"',
  '"the picture blanked out"',
  '"the complete core disk can be blanked out in one piece"',
  '"Baltimore blanked Toronto in a 7–0 victory"',
];
export const synonyms = [
  'space',
  'gap',
  'blank space',
  'empty space',
  'void',
  'vacuum',
  'emptiness',
  'vacancy',
  'envelop',
  'surround',
  'swathe',
  'enfold',
  'cover',
  'cover up',
  'conceal',
  'hide',
  'secrete',
  'camouflage',
  'disguise',
  'mask',
  'screen',
  'shield',
  'cloak',
  'blanket',
  'shroud',
  'enwrap',
  'canopy',
  'overlay',
  'obscure',
  'shade',
  'shadow',
  'eclipse',
  'cloud',
  'block out',
  'obliterate',
  'overshadow',
  'enshroud',
  'mantle',
  'bedim',
  'becloud',
  'befog',
  'obnubilate',
  'blot out',
  'blank out',
  'benight',
  'unveil',
  'expose',
  'uncover',
];
