export const definitions = [
  '"the lamb was bleating weakly"',
  '"handing the mike to some woman who starts bleating out rap rhymes"',
  '"he bleated incoherently about the report"',
  '"the distant bleat of sheep in the field"',
  '"his despairing bleat touched her heart"',
  '"they\'re hoping that I\'ll bow to their idiotic arrangements without a bleat"',
];
export const synonyms = [
  'baa',
  'cry',
  'call',
  'maa',
  'complain',
  'moan',
  'mutter',
  'grumble',
  'grouse',
  'groan',
  'grouch',
  'growl',
  'carp',
  'snivel',
  'make a fuss',
  'twine',
  'gurn',
  'crib',
  'natter',
  'mither',
  'whine',
  'cry',
  'sniffle',
  'snivel',
  'sob',
  'moan',
  'mewl',
  'wail',
  'groan',
];