export const definitions = [
    '"the injury temporarily blinded him"',
    '"eyes blinded with tears"',
    '"somehow Clare and I were blinded to the truth"',
    '"a clever tactician blinded by passion"',
    '"they try to blind you with science"',
    '"guide dogs for the blind"',
    '"she pulled down the blinds"',
    '"he phoned again from his own home: that was just a blind for his wife"',
    '"you can sometimes use your car as a blind"',
    '"a duck blind"',
    '"he\'s off on a blind again"',
]
export const synonyms = [
    'put someone\'s eyes out',
    'dazzle',
    'make blind',
    'deprive of sight',
    'deprive of vision',
    'render unsighted',
    'render sightless',
    'gouge someone\'s eyes out',
    'stop someone seeing',
    'obscure someone\'s vision',
    'block some\'s \'s vision',
    'get in some\'s \'s line of vision',
    'deprive of understanding',
    'deprive of perception',
    'deprive of judgment',
    'deprive of reason',
    'deprive of sense',
    'overawe',
    'awe',
    'intimidate',
    'daunt',
    'deter',
    'cow',
    'abash',
    'disquiet',
    'perturb',
    'discomfit',
    'disconcert',
    'confuse',
    'nonplus',
    'bewilder',
    'confound',
    'perplex',
    'overwhelm',
    'unsettle',
    'discompose',
    'unnerve',
    'discourage',
    'subdue',
    'dismay',
    'frighten',
    'alarm',
    'scare',
    'terrify',
    'terrorize',
    'browbeat',
    'bully',
    'trouble',
    'bother',
    'agitate',
    'fluster',
    'ruffle',
    'jolt',
    'shake (up)',
    'throw',
    'put off',
    'unbalance',
    'destabilize',
    'pull the rug (out) from under',
    'make anxious',
    'make uneasy',
    'take aback',
    'throw off balance',
    'put off one\'s stroke',
    'screen',
    'shade',
    'louver',
    'awning',
    'canopy',
    'sunshade',
    'curtain',
    'shutter',
    'cover',
    'covering',
    'protection',
    'Venetian blind',
    'jalousie',
    'Austrian blind',
    'roller blind',
    'persienne',
    'deception',
    'camouflage',
    'screen',
    'smokescreen',
    'front',
    'facade',
    'cover',
    'disguise',
    'cloak',
    'pretext',
    'masquerade',
    'mask',
    'feint',
    'trick',
    'stratagem',
    'ploy',
    'ruse',
    'scheme',
    'device',
    'move',
    'maneuver',
    'contrivance',
    'machination',
    'expedient',
    'artifice',
    'wile',
    'dodge',
    'debauch',
    'bacchanal',
    'bacchanalia',
    'wassail',
    'fuddle',
    'potation',
    'drinking bout',
]