export const definitions = [
  '"a blithe disregard for the rules of the road"',
  '"a blithe seaside comedy"',
];
export const synonyms = [
  'heedless',
  'uncaring',
  'careless',
  'casual',
  'indifferent',
  'thoughtless',
  'unconcerned',
  'unworried',
  'untroubled',
  'nonchalant',
  'cool',
  'blasé',
  'devil-may-care',
  'irresponsible',
  'thoughtful',
  'happy',
  'cheerful',
  'cheery',
  'lighthearted',
  'jolly',
  'merry',
  'sunny',
  'joyous',
  'joyful',
  'blissful',
  'ecstatic',
  'euphoric',
  'elated',
  'beatific',
  'gladsome',
  'mirthful',
  'carefree',
  'easygoing',
  'buoyant',
  'airy',
  'breezy',
  'jaunty',
  'animated',
  'sprightly',
  'vivacious',
  'spirited',
  'frisky',
  'blithesome',
  'jocund',
  'gay',
  'in high spirits',
  'without a care in the world',
  'sad',
];