export const definitions = [
  '"a bloody body"',
  '"a bloody discharge"',
  '"a bloody coup"',
  '"the bloody tyrannies of Europe"',
  '"he ended the fight with his face bloodied and battered"',
  '"she has been bloodied in her three years on the commission"',
  '"took your bloody time"',
  '"it\'s bloody cold outside"',
  '"don\'t be too bloody to poor Jack"',
];
export const synonyms = [
  'bleeding',
  'raw',
  'gaping',
  'bloodstained',
  'gory',
  'sanguinary',
  'shedding blood',
  'emitting blood',
  'blood-soaked',
  'blood-spattered',
  'gory',
  'bloodthirsty',
  'vicious',
  'cruel',
  'ferocious',
  'savage',
  'fierce',
  'brutal',
  'murderous',
  'sanguinary',
  'involving bloodshed',
  'blasted',
  'damn',
  'damned',
  'flaming',
  'precious',
  'confounded',
  'pestilential',
  'rotten',
  'wretched',
  'cursed',
  'accursed',
  'damnable',
];