export const definitions = [
  '"the offer was denounced as a bluff"',
  '"his game of bluff"',
  '"he\'s been bluffing all along"',
  '"the object is to bluff your opponent into submission"',
  '"he bluffed his way onto an Antarctic supply vessel"',
];
export const synonyms = [
  'deception',
  'subterfuge',
  'pretense',
  'sham',
  'fake',
  'show',
  'deceit',
  'feint',
  'delusion',
  'hoax',
  'fraud',
  'masquerade',
  'charade',
  'trick',
  'stratagem',
  'ruse',
  'maneuver',
  'scheme',
  'artifice',
  'machination',
  'humbug',
  'bluster',
  'bombast',
  'bragging',
  'false show',
  'idle boast',
  'pretend',
  'sham',
  'fake',
  'feign',
  'lie',
  'hoax',
  'pose',
  'posture',
  'masquerade',
  'dissemble',
  'dissimulate',
  'deceive',
  'delude',
  'mislead',
  'trick',
  'fool',
  'hoodwink',
  'dupe',
  'take in',
  'beguile',
  'humbug',
  'bamboozle',
  'gull',
  'cheat',
  'cozen',
  'put on an act',
  'put it on',
  'cliff',
  'ridge',
  'promontory',
  'headland',
  'crag',
  'bank',
  'slope',
  'height',
  'peak',
  'escarpment',
  'scarp',
  'precipice',
  'rock face',
  'overhang',
  'eminence',
];