export const definitions = [
  '"wood can blunt your axe"',
  '"the edge may blunt very rapidly"',
  '"their determination had been blunted"',
];
export const synonyms = [
  'make less sharp',
  'make blunt',
  'make dull',
  'sharpen',
  'hone',
  'dull',
  'deaden',
  'dampen',
  'soften',
  'numb',
  'weaken',
  'take the edge off',
  'calm',
  'cool',
  'temper',
  'muffle',
  'impair',
  'allay',
  'abate',
  'tone down',
  'dilute',
  'sap',
  'thin',
  'reduce',
  'moderate',
  'assuage',
  'alleviate',
  'mollify',
  'ease',
  'relieve',
  'slake',
  'sate',
  'appease',
  'diminish',
  'decrease',
  'lessen',
  'deplete',
  'water down',
  'intensify',
  'sharpen',
  'cannabis cigarette',
  'marijuana cigarette',
  'zol',
];