export const definitions = [
  '"\"It wasn\'t my idea,\" Gordon blurted"',
  '"she wouldn\'t blurt out words she did not mean"',
];
export const synonyms = [
  'exclaim',
  'ejaculate',
  'tell',
  'babble',
  'jabber',
  'call out',
  'cry out',
  'come out with',
  'divulge',
  'disclose',
  'reveal',
  'betray',
  'leak',
  'let out',
  'give away',
  'give the game away',
  'bring to light',
  'utter suddenly',
  'burst out with',
  'let slip',
  'keep quiet',
];