export const definitions = [
    '"loose ______ creaked as I walked on them"',
    '"sections of _____"',
    '"teachers talk and write on the _____"',
    '"Pete set the pieces out on the _____"',
    '"a graphics _____"',
    '"you kick-turn with both feet on the _____"',
    '"the absence of center David Robinson to dominate on the ______"',
    '"he sits on the _____ of directors"',
    '"a _____ meeting"',
    '"your room and _____ will be free"',
    '"he looked at the banquet which was spread upon his _____"',
    '"we were tacking up to the anchor, shortening cable at each _____"',
    '"we _____ed the plane for Oslo"',
    '"they would not be able to _____ without a ticket"',
    '"flight 172 to Istanbul is now _____ing at gate 37"',
    '"the cousins _____ed for a while with Ruby"',
    '"parents had to cope with their child _____ing at a special school"',
    '"dogs may have to be _____ed at kennels"',
    '"the shop was still _____ed up"',
    '"when we\'re not _____ing, we\'re skiing"',
];
export const synonyms = [
    'plank',
    'beam',
    'panel',
    'slat',
    'batten',
    'timber',
    'lath',
    'length of timber',
    'piece of wood',
    'notice',
    'signpost',
    'warning sign',
    'road sign',
    'traffic sign',
    'placard',
    'plate',
    'pointer',
    'arrow',
    'marker',
    'indicator',
    'poster',
    'bill',
    'sticker',
    'advertisement',
    'waymark',
    'plank',
    'beam',
    'panel',
    'slat',
    'batten',
    'timber',
    'lath',
    'length of timber',
    'piece of wood',
    'binding',
    'case',
    'jacket',
    'dust jacket',
    'dust cover',
    'wrapper',
    'committee',
    'council',
    'panel',
    'directorate',
    'commission',
    'group',
    'delegation',
    'delegates',
    'trustees',
    'convocation',
    'quango',
    'panel of trustees',
    'food',
    'meals',
    'provisions',
    'sustenance',
    'nourishment',
    'fare',
    'diet',
    'menu',
    'table',
    'bread',
    'daily bread',
    'foodstuffs',
    'refreshments',
    'edibles',
    'keep',
    'maintenance',
    'upkeep',
    'vivas',
    'comestibles',
    'provender',
    'vittles',
    'commons',
    'victuals',
    'viands',
    'aliment',
    'daily meals',
    'get on',
    'enter',
    'mount',
    'ascend',
    'embark',
    'catch',
    'emplane',
    'entrain',
    'climb on',
    'embus',
    'alight',
    'get off',
    'lodge',
    'live',
    'reside',
    'room',
    'accommodate',
    'take in',
    'put up',
    'house',
    'billet',
    'quarter',
    'harbor',
    'shelter',
    'receive',
    'keep',
    'feed',
    'cater for',
    'have rooms',
    'be quartered',
    'be housed',
    'be settled',
    'have one\'s home',
    'provide shelter for',
    'give a bed to',
    'give someone a roof over their head',
    'make room for',
    'give accommodation to',
    'cook for',
    'close up',
    'shut up',
    'seal',
    'cover up/over',
]
