export const definitions = [
    '"the mind boggles at the spectacle"',
    '"the inflated salary of a CEO boggles the mind"',
    '"the total was a boggling 1.5 trillion miles"',
    '"you never boggle at plain speaking"',
]
export const synonyms = [
    'marvel',
    'wonder',
    'gape',
    'goggle',
    'gawk',
    'be astonished',
    'be astounded',
    'be amazed',
    'be filled with amazement',
    'be overwhelmed',
    'be shocked',
    'be staggered',
    'be bowled over',
    'be startled',
    'astonish',
    'astound',
    'amaze',
    'overwhelm',
    'shock',
    'startle',
    'fill with amazement',
    'fill with wonder',
    'demur',
    'jib',
    'waver',
    'falter',
    'dither',
    'balk',
    'shrink from',
    'flinch from',
    'recoil from',
    'hang back from',
    'vacillate about',
    'think twice about',
    'be reluctant about',
    'have scruples about',
    'scruple about',
    'have misgivings about',
    'have qualms about',
    'be chary of',
    'hesitate to',
    'be shy about',
    'be coy about',
    'shy away from',
]