export const definitions = [
    '"northern boreal forest"',
]
export const synonyms = [
    'chilly',
    'cool',
    'freezing',
    'icy',
    'snowy',
    'icy-cold',
    'glacial',
    'wintry',
    'crisp',
    'frosty',
    'frigid',
    'bitter',
    'biting',
    'piercing',
    'numbing',
    'sharp',
    'raw',
    'polar',
    'arctic',
    'Siberian',
    'chill',
    'hyperborean',
    'hibernal',
    'gelid',
    'brumal',
    'bitterly cold',
    'hiemal',
    'hot',
]