export const definitions = [
  '"he had borrowed a car from one of his colleagues"',
  '"she was wearing a borrowed jacket"',
  '"I borrowed the money for a return plane ticket"',
  '"lower interest rates will make it cheaper for individuals to borrow"',
  '"the term is borrowed from Greek"',
  '"designers consistently borrow from the styles of preceding generations"',
];
export const synonyms = [
  'take',
  'carry off',
  'appropriate',
  'commandeer',
  'abstract',
  'steal',
  'purloin',
  'shoplift',
  'crib',
  'hook',
  'take for oneself',
  'help oneself to',
  'use as one\'s own',
  'abscond with',
  'lease',
  'hire',
  'take as a loan',
  'ask for the loan of',
  'receive as a loan',
  'use temporarily',
  'have temporarily',
  'lend',
  'adopt',
  'take on',
  'take in',
  'take over',
  'acquire',
  'embrace',
  'lease',
  'hire',
  'take as a loan',
  'ask for the loan of',
  'receive as a loan',
  'use temporarily',
  'have temporarily',
  'lend',
];