export const definitions = [
    '"scientists rarely bother with such niceties"',
    '"the driver didn\'t bother to ask why"',
    '"nobody bothered locking the doors"',
    '"is there an issue that bothers you so much you\'d campaign against it ? "',
    '"it bothered me that I hadn\'t done anything"',
    '"don\'t bother about me—I\'ll find my own way home"',
    '"he wasn\'t to bother himself with day - to - day things"',
    '"she didn\'t feel she could bother Mike with the problem"',
    '"he saved me the bother of having to come up with a speech"',
    '"it may seem like too much bother to cook just for yourself"',
    '"I hope she hasn\'t been a bother"',
];
export const synonyms = [
    'mind',
    'care',
    'worry',
    'trouble',
    'concern',
    'perturb',
    'disturb',
    'disquiet',
    'disconcert',
    'unnerve',
    'fret',
    'upset',
    'distress',
    'alarm',
    'work up',
    'agitate',
    'weigh down',
    'concern oneself',
    'trouble oneself',
    'worry oneself',
    'burden oneself',
    'occupy oneself',
    'busy oneself',
    'take the time',
    'make the effort',
    'go to trouble',
    'inconvenience oneself',
    'make anxious',
    'cause someone anxiety',
    'gnaw at',
    'lie heavy on',
    'comfort',
    'disturb',
    'trouble',
    'worry',
    'inconvenience',
    'put out',
    'pester',
    'badger',
    'harass',
    'molest',
    'plague',
    'beset',
    'torment',
    'nag',
    'hound',
    'dog',
    'chivvy',
    'harry',
    'annoy',
    'upset',
    'irritate',
    'vex',
    'provoke',
    'nettle',
    'discommode',
    'impose on',
    'try someone\'s patience',
    'make one\'s hackles rise',
    'trouble',
    'effort',
    'exertion',
    'strain',
    'inconvenience',
    'fuss',
    'bustle',
    'disruption',
    'pains',
    'hustle and bustle',
    'nuisance',
    'pest',
    'palaver',
    'rigmarole',
    'job',
    'trial',
    'tribulation',
    'bind',
    'bore',
    'drag',
    'inconvenience',
    'difficulty',
    'trouble',
    'problem',
    'irritation',
    'annoyance',
    'vexation',
]
