export const definitions = [
    '"he ______ me a new dress"',
    '"we had to find some money to buy a house"',
    '"here was a man who could not be ______"',
    '"money can\'t buy happiness"',
    '"greatness is dearly ______"',
    '"I am not prepared to buy the claim that the ends justify the means"',
];
export const synonyms = [
    'purchase',
    'acquire',
    'obtain',
    'get',
    'pick up',
    'snap up',
    'take',
    'secure',
    'procure',
    'come by',
    'make a/the purchase of',
    'pay for',
    'shop for',
    'invest in',
    'put money into',
    'sell',
    'bribe',
    'buy off',
    'pay off',
    'suborn',
    'corrupt',
    'give an inducement to',
    'accept',
    'bless',
    'rubber-stamp',
    'ratify',
    'sanction',
    'endorse',
    'authorize',
    'mandate',
    'license',
    'warrant',
    'validate',
    'pass',
    'confirm',
    'support',
    'back',
    'agree to',
    'consent to',
    'assent to',
    'acquiesce in',
    'concur in',
    'accede to',
    'give one\'s blessing to',
    'give one\'s seal/stamp of approval to',
    'say yes to',
    'give one\'s permission/leave',
    'refuse',
]
