export const definitions = [
  '"Louis came bounding down the stairs"',
  '"the dog bounded up to him"',
  '"bullets bounded off the veranda"',
  '"I went up the steps in two effortless bounds"',
  '"the ancient bounds of the forest"',
  '"it is not beyond the bounds of possibility that the issue could arise again"',
  '"enthusiasm to join the union knew no bounds"',
  '"an upper bound on each modulus"',
  '"the ground was bounded by a main road on one side and a meadow on the other"',
  '"freedom of action is bounded by law"',
];
export const synonyms = [
  'leap',
  'jump',
  'spring',
  'bounce',
  'hop',
  'vault',
  'hurdle',
  'skip',
  'bob',
  'dance',
  'prance',
  'romp',
  'caper',
  'cavort',
  'sport',
  'frisk',
  'frolic',
  'gambol',
  'gallop',
  'hurtle',
  'curvet',
  'rollick',
  'capriole',
  'leap',
  'jump',
  'spring',
  'bounce',
  'hop',
  'vault',
  'hurdle',
  'curvet',
  'capriole',
  'borders',
  'boundaries',
  'confines',
  'limits',
  'extremities',
  'margins',
  'edges',
  'fringes',
  'marches',
  'periphery',
  'perimeter',
  'circumference',
  'compass',
  'precinct',
  'pale',
  'outer limits',
  'limits',
  'confines',
  'restrictions',
  'limitations',
  'demarcations',
  'proportions',
  'enclose',
  'surround',
  'encircle',
  'circle',
  'ring',
  'circumscribe',
  'border',
  'close in',
  'hem in',
  'lock in',
  'cut off',
  'hedge in',
  'wall in',
  'fence in',
  'limit',
  'restrict',
  'confine',
  'cramp',
  'straiten',
  'restrain',
  'circumscribe',
  'demarcate',
  'delimit',
  'define',
];