export const definitions = [
    '"I grew up watching boxing with my dad and grandfather"',
    '"she is confident that she could beat him in a boxing match"',
    '"each piece is boxed with a certificate of authenticity"',
    '"Muriel boxed up all Christopher\'s clothes"',
    '"procedures relating to topics within the chapter are boxed in and numbered so that the reader can quickly recognize them"',
    '"he boxed for England"',
    '"he had to box Bennett for the title"',
]
export const synonyms = [
    'pugilism',
    'fighting',
    'sparring',
    'fisticuffs',
    'kick-boxing',
    'Thai boxing',
    'prizefighting',
    'the ring',
    'the prize ring',
    'bare-knuckle boxing/fighting',
    'the noble art/science (of self defense)',
    'package',
    'pack',
    'parcel',
    'wrap',
    'bundle',
    'bale',
    'crate',
    'stow',
    'store',
    'put away',
    'fight',
    'spar',
    'battle',
    'grapple',
    'brawl',
    'exchange blows',
    'engage in fisticuffs',
]