export const definitions = [
    '"the posts were braced by lengths of timber"',
    '"she braced her feet against a projecting shelf"',
    '"he stood with legs braced"',
    '"both stations are bracing themselves for job losses"',
    '"police are braced for a traffic nightmare today"',
]
export const synonyms = [
    'support',
    'prop up',
    'hold up',
    'buttress',
    'carry',
    'bear',
    'underpin',
    'strengthen',
    'reinforce',
    'fortify',
    'underprop',
    'shore up',
    'steady',
    'secure',
    'stabilize',
    'fix',
    'prop',
    'poise',
    'tense',
    'tighten',
    'stiffen',
    'strain',
    'make fast',
    'prepare',
    'make ready',
    'gear up',
    'nerve',
    'steel',
    'galvanize',
    'gird',
    'strengthen',
    'fortify',
    'bolster',
    'buttress',
    'get ready',
]