export const definitions = [
  '"Sophie was in the branches of a tree eating an apple"',
  '"a branch of the Susquehanna River"',
  '"he went to work at our Boston branch"',
  '"a branch of mathematics called graph theory"',
  '"follow this track south until it branches into two"',
  '"the road branched off at the market town"',
  '"this rose has a tendency to branch and spread at the top"',
  '"the branching heads of large yellow daisies"',
];
export const synonyms = [
  'bough',
  'limb',
  'arm',
  'offshoot',
  'tributary',
  'feeder',
  'side stream',
  'division',
  'subdivision',
  'section',
  'subsection',
  'department',
  'sector',
  'part',
  'side',
  'wing',
  'area',
  'sphere',
  'discipline',
  'field',
  'office',
  'bureau',
  'agency',
  'affiliate',
  'subsidiary',
  'offshoot',
  'satellite',
  'chapter',
  'lodge',
  'fork',
  'bifurcate',
  'divide',
  'subdivide',
  'split',
  'separate',
  'furcate',
  'divaricate',
  'ramify',
  'go in different directions',
  'diverge from',
  'deviate from',
  'depart from',
  'turn aside from',
  'shoot off from',
  'split off from',
  'go off at a tangent from',
  'fan out from',
  'ray out from',
  'radiate from',
  'swerve',
  'career',
  'skew',
  'swing',
  'sheer',
  'weave',
  'wheel',
  'deviate',
  'diverge',
  'curve',
  'twist',
  'bend',
  'curl',
  'incline',
  'swivel',
  'zigzag',
  'tack',
  'divagate',
  'change direction',
  'change course',
  'go off course',
  'be deflected',
  'turn (aside)',
  'branch off',
];
