export const definitions = [
    '"a great brawny brute"',
    '"Gordon had brawny tattooed arms"',
]
export const synonyms = [
    'strong',
    'as strong as an ox',
    'muscular',
    'muscly',
    'muscle-bound',
    'well built',
    'powerful',
    'mighty',
    'Herculean',
    'strapping',
    'burly',
    'robust',
    'sturdy',
    'husky',
    'lusty',
    'sinewy',
    'well knit',
    'rugged',
    'bulky',
    'hefty',
    'meaty',
    'solid',
    'stalwart',
    'thewy',
    'stark',
    'well muscled',
    'powerfully built',
    'solidly built',
    'scrawny',
    'puny',
    'weak',
]