export const definitions = [
  '"a loaf of bread"',
  '"a bread roll"',
  '"Italian breads"',
  '"altar bread"',
  '"his day job puts bread on the table"',
  '"I hate doing this, but I need the bread"',
  '"bread the chicken and fry it in oil"',
];
export const synonyms = [
  'cash',
  'hard cash',
  'ready money',
  'funds',
  'capital',
  'finances',
  'banknotes',
  'notes',
  'paper money',
  'coins',
  'change',
  'coin',
  'coinage',
  'silver',
  'copper',
  'currency',
  'legal tender',
  'sterling',
  'bills',
  'roll',
  'specie',
  'pelf',
  'the means',
  'the wherewithal',
  '(filthy) lucre',
  'l.s.d.',
];