export const definitions = [
  '"a breach of confidence"',
  '"they alleged breach of copyright"',
  '"a sudden breach between father and son"',
  '"a breach in the mountain wall"',
  '"the river breached its bank"',
  '"these outside bodies are bootlegging albums and breaching copyright"',
  '"we saw whales breaching in the distance"',
];
export const synonyms = [
  'contravention',
  'violation',
  'breaking',
  'nonobservance',
  'infringement',
  'transgression',
  'neglect',
  'dereliction',
  'infraction',
  'delict',
  'failure to observe',
  'noncompliance with',
  'rift',
  'gulf',
  'chasm',
  'division',
  'difference',
  'schism',
  'disunion',
  'estrangement',
  'alienation',
  'discord',
  'dissension',
  'disaffection',
  'separation',
  'split',
  'break',
  'breakup',
  'parting',
  'parting of the ways',
  'severance',
  'rupture',
  'quarrel',
  'falling-out',
  'scission',
  'break',
  'rupture',
  'split',
  'crack',
  'fracture',
  'rent',
  'rift',
  'opening',
  'gap',
  'hole',
  'fissure',
  'cleft',
  'aperture',
  'break (through)',
  'rupture',
  'split',
  'burst (through)',
  'force itself through',
  'break',
  'contravene',
  'violate',
  'infringe',
  'defy',
  'disobey',
  'flout',
  'fly in the face of',
  'infract',
  'fail to comply with',
  'transgress against',
];