export const definitions = [
    '"the Minoans made large numbers of statuettes in ivory and bronze"',
    '"a bronze statue"',
    '"on the black bookcase were three exquisite bronzes"',
    '"rich, gleaming shades of bronze"',
    '"Alison was bronzed by outdoor life"',
    '"the doors were bronzed with sculpted reliefs"',
]
export const synonyms = [
    'bronze medal',
    'third prize',
    'copper',
    'chestnut',
    'rust-colored',
    'rust',
    'henna',
    'tan',
    'tanned',
    'suntanned',
    'sunburned',
    'bronzed',
    'browned',
    'bronze-colored',
    'copper-colored',
    'reddish brown',
    'metallic brown',
    'tanned',
    'suntanned',
    'sunburned',
    'browned',
    'brown',
    'tan',
    'pale',
]