export const definitions = [
    '"he stopped to browse around a sporting goods store"',
    '"she browsed through the newspaper"',
    '"I decided to spend the night browsing the internet"',
    '"they reach upward to browse on bushes"',
    '"the animals browse the high foliage of trees"',
    '"the brochure is well worth a browse"',
    '"a moose needs to eat forty to fifty pounds of browse a day"',
];
export const synonyms = [
    'look around',
    'window-shop',
    'peruse',
    'have a look',
    'scan',
    'skim',
    'glance',
    'look',
    'peruse',
    'thumb',
    'leaf',
    'flip',
    'flick',
    'run',
    'riffle',
    'speed-read',
    'run one\'s eye over',
    'have a look at',
    'give something a/the once-over',
    'dip into',
    'graze',
    'feed',
    'eat',
    'nibble',
    'crop',
    'pasture',
    'ruminate',
    'scan',
    'read',
    'skim',
    'leaf',
    'flick through',
    'glance',
    'look',
]
