export const definitions = [
    '"blowing bubbles is a favourite pastime of many children"',
    '"I\'m going to soak myself in the bath filled with bubbles"',
    '"the white foamy part of a broken wave is largely made up of air bubbles"',
    '"we both lived in a bubble, the kind provided by occupying a privileged pied-à-terre in Greenwich Village"',
    '"the US economy squandered trillions as a result of the 1990s stock market bubble"',
    '"many companies enjoyed rapid expansion before the bubble burst"',
    '"piglets born into a sterile bubble"',
    '"they are not on tour packages seeing foreign ports from a bubble"',
    '"you cannot stay overnight in another person\'s home, unless you\'ve formed a bubble with them"',
    '"people in your support bubble"',
    '"social bubbles can interact indoors"',
    '"a speech bubble"',
    '"a pot of soup bubbled away on the stove"',
    '"close by, a stream bubbled along through reeds and rushes"',
    '"Ellen was bubbling with enthusiasm"',
    '"the fury bubbling up inside her"',
    ,
];
export const synonyms = [
    'globe',
    'ball',
    'orb',
    'spheroid',
    'globule',
    'round',
    'spherule',
    'globule',
    'bead',
    'blister',
    'drop',
    'air pocket',
    'sparkle',
    'fizz',
    'effervescence',
    'mousse',
    'froth',
    'head',
    'lather',
    'suds',
    'barm',
    'air cavity',
    'illusion',
    'delusion',
    'fantasy',
    'dream',
    'pipe dream',
    'daydream',
    'chimera',
    'vanity',
    'castle in the air',
    'transient phenomenon',
    'short-lived phenomenon',
    'sparkle',
    'fizz',
    'effervesce',
    'gurgle',
    'foam',
    'froth',
    'spume',
    'boil',
    'simmer',
    'seethe',
    'be flat',
    'be still',
    'gurgle',
    'murmur',
    'purr',
    'purl',
    'tinkle',
    'whir',
    'drone',
    'rumble',
    'buzz',
    'hum',
    'plash',
    'overflow',
    'run over',
    'gush',
    'brim over',
    'be filled',
]
