export const definitions = [
    '"family and friends can provide a ______ against stress"',
    '"print speed is boosted by pages being formatted in a ______ while another is printing"',
    '"the massage helped to ______ the strain"',
    '"add organic matter to ______ the resulting alkalinity"',
    '"best to ______ the video stream before pressing play"',
    '"a distinguished old ______"',
]
export const synonyms = [
    'cushion',
    'bulwark',
    'shield',
    'screen',
    'barrier',
    'guard',
    'safeguard',
    'hedge',
    'shock absorber',
    'armor',
    'intermediary',
    'middleman',
    'go-between',
    'cushion',
    'absorb',
    'soften',
    'lessen',
    'diminish',
    'moderate',
    'mitigate',
    'allay',
    'deaden',
    'muffle',
    'stifle',
    'shield',
    'intensify',
    'healthy',
    'well',
    'in shape',
    'in trim',
    'as fit as a flea',
    'as strong as an ox',
    'strong',
    'robust',
    'sturdy',
    'hardy',
    'stalwart',
    'lusty',
    'vigorous',
    'sound',
    'athletic',
    'muscular',
    'strapping',
    'tough',
    'powerful',
    'rugged',
    'in good health',
    'in good shape',
    'in good trim',
    'in good condition',
    'in tip-top condition',
    'in fine fettle',
    'fighting fit',
    'as fit as a fiddle',
    'hale and hearty',
    'unfit',
    'unwell',
]