export const definitions = [
    '"all right, let the little buggers come in"',
    '"I\'m all for living life to the full and bugger the consequences"',
]
export const synonyms = [
    'scoundrel',
    'villain',
    'rogue',
    'rascal',
    'brute',
    'animal',
    'weasel',
    'snake',
    'monster',
    'ogre',
    'wretch',
    'devil',
    'good-for-nothing',
    'reprobate',
    'wrongdoer',
    'evil-doer',
    'picaro',
    'blackguard',
    'miscreant',
    'varlet',
    'vagabond',
    'rapscallion',
    'whoreson',
    'human being',
    'individual',
    'human',
    'being',
    'soul',
    'mortal',
    'creature',
    'fellow',
    'figure',
    'personage',
    'wight',
    'man/woman',
    'living soul',
]