export const definitions = [
    '"he bungled his first attempt to manage a group of professional players"',
    '"a few individuals had bungled in handling the situation"',
    '"a series of bureaucratic bungles over his visa status"',
]
export const synonyms = [
    'mishandle',
    'mismanage',
    'mess up',
    'make a mess of',
    'botch',
    'spoil',
    'mar',
    'ruin',
    'succeed in',
    'manage successfully',
    'muddle',
    'mess',
    'tangle',
    'jumble',
    'entanglement',
    'imbroglio',
    'misunderstanding',
    'misinterpretation',
    'misconstruction',
    'misapprehension',
    'misconception',
    'confusion',
    'mistake',
    'error',
    'mix-up',
    'the wrong idea',
    'false impression',
    'comess',
]