export const definitions = [
  '"I let the water buoy up my weight"',
  '"the party was buoyed by an election victory"',
  '"the price is buoyed up by investors"',
  '"the wreck is often buoyed during summer months"',
];
export const synonyms = [
  'cheer',
  'cheer up',
  'hearten',
  'rally',
  'animate',
  'invigorate',
  'comfort',
  'uplift',
  'lift',
  'encourage',
  'stimulate',
  'support',
  'sustain',
  'inspirit',
  'brighten up',
  'ginger up',
  'raise someone\'s spirits',
  'give a lift to',
  'give strength to',
  'be a source of strength to',
  'be a tower of strength to',
  'keep someone going',
  'see someone through',
  'depress',
];