export const definitions = [
    '"the burden of long-term illness"',
    '"the burden of establishing that the cost was unreasonable"',
    '"the schooner Wyoming, of about 6,000 tons burden"',
    '"the burden of his views"',
    '"she walked forward burdened with a wooden box"',
    '"they were not yet burdened with adult responsibility"'
];
export const synonyms = [
    'load',
    'cargo',
    'freight',
    'weight',
    'charge',
    'pack',
    'bundle',
    'parcel',
    'responsibility',
    'onus',
    'charge',
    'duty',
    'obligation',
    'liability',
    'trouble',
    'care',
    'problem',
    'worry',
    'anxiety',
    'tribulation',
    'affliction',
    'trial',
    'difficulty',
    'misfortune',
    'strain',
    'stress',
    'encumbrance',
    'millstone',
    'albatross',
    'cumber',
    'cross to bear',
    'job',
    'duty',
    'chore',
    'charge',
    'labor',
    'assignment',
    'function',
    'commission',
    'mission',
    'engagement',
    'occupation',
    'undertaking',
    'exercise',
    'business',
    'responsibility',
    'errand',
    'detail',
    'endeavor',
    'enterprise',
    'venture',
    'quest',
    'problem',
    'piece of work',
    'piece of business',
    'gist',
    'substance',
    'drift',
    'implication',
    'intention',
    'thrust',
    'meaning',
    'significance',
    'signification',
    'sense',
    'essence',
    'thesis',
    'import',
    'purport',
    'tenor',
    'message',
    'spirit',
    'refrain',
    'strain',
    'load',
    'weight',
    'charge',
    'weigh down',
    'encumber',
    'hamper',
    'overload',
    'overburden',
    'trammel',
    'oppress',
    'trouble',
    'worry',
    'beset',
    'bother',
    'harass',
    'disturb',
    'upset',
    'depress',
    'distress',
    'grieve',
    'haunt',
    'nag',
    'torment',
    'harrow',
    'afflict',
    'strain',
    'stress',
    'tax',
    'overwhelm',
    'perturb',
    'plague',
    'bedevil',
    'cause trouble to',
    'cause suffering to',
    'get someone down',
]
