export const definitions = [
    '"a news bureau"',
    '"the London bureau of the Washington Post"',
    '"the intelligence bureau"',
    ,
];
export const synonyms = [
    'cabinet',
    'cupboard',
    'chiffonier',
    'sideboard',
    'desk',
    'writing desk',
    'roll-top desk',
    'davenport',
    'secretaire',
    'escritoire',
    'writing table',
    'agency',
    'service',
    'office',
    'business',
    'company',
    'firm',
    'organization',
    'operation',
    'concern',
    'department',
    'division',
    'branch',
    'section',
]
