export const definitions = [
    '"his remains were shipped home for burial"',
    '"burial rites"',
    '"burial mounds"',
]
export const synonyms = [
    'burying',
    'committal',
    'entombment',
    'inhumation',
    'obsequies',
    'sepulture',
    'exequies',
    'a funeral',
    'funeral rites',
    'exhumation',
    'burying',
    'interment',
    'committal',
    'inhumation',
    'entombment',
    'funeral',
    'obsequies',
    'sepulture',
    'exequies',
    'funerary rites',
    'exhumation',
]