export const definitions = [
    '"moles burrowing away underground"',
    '"the fish can burrow a hiding place"',
    '"worms that burrow through dead wood"',
    '"the child burrowed deeper into the bed"',
    '"they need to burrow into the heart of what\'s going on"',
]
export const synonyms = [
    'warren',
    'tunnel',
    'hole',
    'lair',
    'set',
    'den',
    'earth',
    'retreat',
    'excavation',
    'cave',
    'dugout',
    'hollow',
    'scrape',
    'tunnel',
    'dig (out)',
    'excavate',
    'grub',
    'mine',
    'bore',
    'drill',
    'channel',
    'cut out',
    'delve',
    'hollow out',
    'gouge out',
    'scoop out',
    'dig',
    'dig out',
    'gouge',
    'cut out',
    'bore',
    'tunnel',
    'sink',
    'quarry',
    'mine',
    'hollow out',
    'scoop out',
]