export const definitions = [
  '"they bust the tunnel wide open"',
  '"the film busts every box-office record"',
  '"he was laughing fit to bust"',
  '"he promised to bust the mafia"',
  '"now they\'ve bust up, she won\'t inherit the house"',
  '"men hired to bust up union rallies"',
  '"they wanted to bust me on the mouth"',
  '"she busted out of prison"',
  '"their house got busted"',
  '"he was busted for drugs"',
  '"I sneaked up on them and told them they were busted"',
  '"he was busted to private"',
];
export const synonyms = [
  'break',
  'crack',
  'snap',
  'fracture',
  'shatter',
  'smash',
  'fragment',
  'splinter',
  'disintegrate',
  'fall to pieces',
  'split',
  'burst',
  'rupture',
  'tear',
  'rend',
  'sever',
  'separate',
  'divide',
  'shiver',
  'smash to smithereens',
  'fall to bits',
  'raid',
  'search',
  'make a search of',
  'swoop on',
  'make a raid on',
  'arrest',
  'apprehend',
  'seize',
  'take in',
  'detain',
  'take into custody',
  'take prisoner',
  'put in jail',
  'throw in jail',
  'release',
];