export const definitions = [
  '"relics of a bygone society"',
  '"the museum consists of a fascinating collection of rural bygones"',
];
export const synonyms = [
  'past',
  'former',
  'earlier',
  'one-time',
  'long-ago',
  'previous',
  'forgotten',
  'lost',
  'finished',
  'completed',
  'of old',
  'ancient',
  'antiquated',
  'obsolete',
  'departed',
  'dead',
  'extinct',
  'defunct',
  'out of date',
  'outmoded',
  'passé',
  'of yore',
  'olden',
  'foregone',
  'gone by',
  'forepassed',
  'present',
  'recent',
];