export const definitions = [
    '"I had a bypass last year so have been building up my strength"',
    '"he\'s just had a triple bypass operation"',
    '"my granddad is well into his eighties and had a bypass"',
    '"he\'s just had a triple bypass operation"',
    '"bypass the farm and continue to the road"',
    '"the town has been bypassed"',
    '"a manager might bypass formal channels of communication"',
]
export const synonyms = [
    'detour',
    'diversion',
    'ring road',
    'relief road',
    'circuitous route',
    'roundabout way',
    'alternative route',
    'go around',
    'avoid',
    'go past',
    'make a detour around',
    'pass around',
    'keep out of',
    'don\'t go near',
    'avoid',
    'evade',
    'dodge',
    'escape',
    'elude',
    'circumvent',
    'get around',
    'sidestep',
    'steer clear of',
    'get out of',
    'shirk',
    'skirt (around)',
    'find a way around',
    'give a wide berth to',
]