export const definitions = [
    '"he decided that they must _____ their weapons"',
    '"the operating system tries to _____ every disk operation"',
    '"the device comes complete with 4MB of RAM to _____ the hard drive"',
    '"a ______ host adapter"',
]
export const synonyms = [
    'store',
    'stow',
    'pack',
    'load',
    'garner',
    'hide',
    'conceal',
    'secrete',
    'hoard',
    'put aside',
    'set aside',
    'put by',
    'lay by',
    'lay aside',
    'save',
    'stockpile',
    'reserve',
    'deposit',
    'keep',
    'keep in reserve',
    'put by for a rainy day',
]