export const definitions = [
    '"the deck beams are curved for the camber of the deck"',
    '"suspension changes include a wider front and rear track with increased negative camber for better cornering grip"',
]
export const synonyms = [
    'bend',
    'turn',
    'loop',
    'curl',
    'twist',
    'hook',
    'arch',
    'bow',
    'half-moon',
    'corner',
    'dogleg',
    'oxbow',
    'bulge',
    'swell',
    'curvature',
    'undulation',
    'meander',
    'hairpin bend',
    'hairpin turn',
    'flexure',
    'trajectory',
    'inflection',
    'incurvation',
]