export const definitions = [
    '"the site offers washing facilities for campers"',
    '"the movie seems more camp than shocking or gruesome"',
    '"a heavily made-up and highly camp actor"',
]
export const synonyms = [
    'exaggerated',
    'theatrical',
    'actorly',
    'affected',
    'mannered',
    'flamboyant',
    'extravagant',
    'overripe',
    'camped up',
    'effeminate',
    'effete',
    'foppish',
    'affected',
    'niminy-piminy',
    'mincing',
    'posturing',
    'campy',
    'queeny',
    'limp-wristed',
    'pansyish',
    'macho',
    'virile',
]