export const definitions = [
  '"his responses were remarkably candid"',
  '"a candid discussion"',
  '"it is better to let the photographer mingle among the guests and take candid shots"',
];
export const synonyms = [
  'frank',
  'outspoken',
  'forthright',
  'blunt',
  'open',
  'honest',
  'truthful',
  'sincere',
  'direct',
  'straightforward',
  'plain-spoken',
  'bluff',
  'unreserved',
  'downright',
  'unvarnished',
  'bald',
  'heart-to-heart',
  'intimate',
  'personal',
  'man-to-man',
  'woman-to-woman',
  'round',
  'free-spoken',
  'not afraid to call a spade a spade',
  'straight from the shoulder',
  'secretive',
  'guarded',
  'insincere',
  'unposed',
  'informal',
  'uncontrived',
  'unstudied',
  'impromptu',
  'spontaneous',
  'extemporary',
  'natural',
];