export const definitions = [
    '"Hold a ______ to someone"',
    '"Burning the ______ at both ends"',
    '"A numeric ______ may use more wax"',
    '"She lit a ______ and placed it on the windowsill"',
    '"shining ______ in the dark world of politics."',
    '"The ______ flickered"',
    '"like a ______ in the wind"',
    '"He snuffed out the ______ with his fingers."',
    '"The ______ preceded the lighbulb."',
    'paschal ______',
    'tallow ______',
    'wax ______',
    'Christmas ______',
    'votary ______',
    'rush ______',
]
export const synonyms = [
    'taper',
    'sconce',
    'wax light',
    'glim',
    'rushlight',
    'bougie',
    'cierge',
]