export const definitions = [
    '"a canvas bag"',
    '"they found a canvas and he seated his model"',
    '"he is used to painting large canvases"',
    '"Turner\'s late canvases"',
    '"she sent her needle stabbing in and out of the canvas"',
    '"a thunderous uppercut sent him crashing to the canvas"',
    '"the door had been canvased over"',
]
export const synonyms = [
    'painting',
    'picture',
    'drawing',
    'sketch',
    'likeness',
    'image',
    'study',
    'representation',
    'portrayal',
    'depiction',
    'miniature',
    'self-portrait',
    'portraiture',
    'kit-cat portrait',
    'solicit',
    'seek',
    'drum up',
    'ask',
    'petition',
    'appeal',
    'beg',
]