export const definitions = [
    '"an electric golf cart careened around the corner"',
    '"a heavy flood tide caused my vessel to careen dizzily"',
]
export const synonyms = [
    'rush',
    'hurtle',
    'career',
    'streak',
    'shoot',
    'race',
    'bolt',
    'dash',
    'speed',
    'run',
    'whiz',
    'zoom',
    'flash',
    'blast',
    'charge',
    'fly',
    'belt',
    'scoot',
    'tear',
    'zip',
    'whip',
    'zap',
    'bomb',
    'hightail',
    'clip',
    'go like the wind',
    'go like a bat out of hell',
    'lean',
    'tip',
    'list',
    'slope',
    'camber',
    'bank',
    'slant',
    'incline',
    'pitch',
    'dip',
    'cant',
    'bevel',
    'angle',
    'cock',
    'heel',
    'bend',
    'be at an angle',
    'level',
    'right',
    'be/come level',
    'be/come upright',
]