export const definitions = [
    '"I begged him to be more careful"',
    '"be careful not to lose her address"',
    '"Careful! That stuff\'s worth a fortune!"',
    '"he was very careful of his reputation"',
    '"he had always been careful with money"',
    '"a careful consideration of the facts"',
]
export const synonyms = [
    'cautious',
    'heedful',
    'alert',
    'aware',
    'attentive',
    'watchful',
    'vigilant',
    'hypervigilant',
    'wary',
    'on guard',
    'chary',
    'circumspect',
    'prudent',
    'mindful',
    'guarded',
    'unhurried',
    'measured',
    'deliberate',
    'careless',
    'mindful',
    'heedful',
    'protective',
    'watchful',
    'careless',
    'prudent',
    'thrifty',
    'economical',
    'economic',
    'economizing',
    'sparing',
    'frugal',
    'scrimping',
    'abstemious',
    'canny',
    'sensible',
    'cautious',
    'miserly',
    'penny-pinching',
    'parsimonious',
    'mean',
    'extravagant',
    'attentive',
    'conscientious',
    'painstaking',
    'meticulous',
    'diligent',
    'assiduous',
    'sedulous',
    'scrupulous',
    'punctilious',
    'fastidious',
    'methodical',
    'orderly',
    'deliberate',
    'judicious',
    'perfectionist',
    'thorough',
    'exhaustive',
    'rigorous',
    'accurate',
    'precise',
    'correct',
    'particular',
    'fussy',
    'finicky',
    'nice',
    'laborious',
    'inattentive',
]