export const definitions = [
    '"carnal desire"',
]
export const synonyms = [
    'sexual',
    'sensual',
    'erotic',
    'lustful',
    'lascivious',
    'libidinous',
    'lecherous',
    'licentious',
    'lewd',
    'prurient',
    'salacious',
    'coarse',
    'gross',
    'lubricious',
    'venereal',
    'physical',
    'bodily',
    'corporeal',
    'fleshly',
    'animal',
    'spiritual',
]