export const definitions = [
]
export const synonyms = [
    'cubicle',
    'kiosk',
    'box',
    'compartment',
    'enclosure',
    'cupboard',
    'cubbyhole',
    'cabin',
    'hut',
    'alcove',
    'bay',
    'recess',
    'booth',
    'cubicle',
    'kiosk',
    'cabin',
    'hut',
    'enclosure',
    'compartment',
    'cupboard',
    'cubbyhole',
    'alcove',
    'bay',
    'recess',
]