export const definitions = [
  '"storm the castle gates"',
  '"the crumbling stonework of a ruined castle"',
  '"preference is to castle on the queenside"',
];
export const synonyms = [
  'fortress',
  'fort',
  'stronghold',
  'fortification',
  'keep',
  'citadel',
  'fastness',
  'tower',
  'peel',
  'palace',
  'chateau',
  'donjon',
  'alcazar',
  'mansion',
  'stately home',
  'hall',
  'manor',
  'big house',
  'country house',
  'palace',
  'edifice',
  'residence',
  'abode',
  'seat',
  'château',
  'palazzo',
  'manor house',
  'impressive building/structure',
  'manoir',
];