definitions: [
    '"she threw the bottle into the air and caught it again"',
    '"he fell forwards and Linda caught him"',
    '"he caught hold of her arm as she tried to push past him"',
    '"his hands caught at her arms as she tried to turn away"',
    '"we hadn\'t caught a single rabbit"',
    '"my sister was caught in a thunderstorm"',
    '"he was caught with bomb-making equipment in his home"',
    '"unexpected snow caught us by surprise"',
    '"the charm bracelet always caught on her clothing"',
    '"she caught her foot in the bedspread"',
    '"companies face increased risks of being caught in a downward spiral"',
    '"her hair was caught back in a scrunchie"',
    '"they caught the 12:15 from Chicago"',
    '"she was hurrying downstairs to catch the news"',
    '"it was the business scheme that had caught his imagination"',
    '"she caught a glimpse of herself in the mirror"',
    '"he bellowed something Jess couldn\'t catch"',
    '"the program caught something of the flavor of Minoan culture"',
    '"Ben caught him on the chin with an uppercut"',
    '"she fell and caught her head on the corner of the hearth"',
    '"he served in Macedonia, where he caught malaria"',
    '"the rafters have caught"',
    '"the generator caught immediately"',
]
synonyms: [
    'seize',
    'grab',
    'snatch',
    'lay (one\'s) hands on',
    'get one\'s hands on',
    'grasp',
    'grip',
    'clutch',
    'clench',
    'pluck',
    'hold',
    'receive',
    'acquire',
    'get',
    'intercept',
    'seize/grab/take hold of',
    'fasten on',
    'hang onto',
    'come into possession of',
    'drop',
    'seize',
    'grab',
    'snatch',
    'lay (one\'s) hands on',
    'grasp',
    'grip',
    'clutch',
    'clench',
    'pluck',
    'hold',
    'receive',
    'acquire',
    'get',
    'intercept',
    'seize/grab/take hold of',
    'fasten on',
    'hang onto',
    'come into possession of',
    'drop',
    'seize',
    'grab',
    'snatch',
    'grasp',
    'grip',
    'clutch',
    'clench',
    'pluck',
    'hold',
    'receive',
    'acquire',
    'get',
    'intercept',
    'seize/grab/take hold of',
    'fasten on',
    'hang onto',
    'come into possession of',
    'drop',
    'grasp',
    'clutch',
    'hold',
    'clasp',
    'latch onto',
    'grab',
    'seize',
    'clench',
    'get one\'s hands on',
    'pluck',
    'squeeze',
    'press',
    'gripe',
    'grasp/take/lay hold of',
    'cling to',
    'catch at',
    'release',
    'hold lightly',
    'capture',
    'seize',
    'apprehend',
    'take',
    'arrest',
    'lay hold of',
    'trap',
    'snare',
    'ensnare',
    'net',
    'hook',
    'land',
    'beach',
    'bag',
    'take prisoner',
    'take captive',
    'take into custody',
    'haul in',
    'reel in',
    'release',
    'discover',
    'detect',
    'find',
    'bring to light',
    'turn up',
    'expose',
    'find out',
    'unmask',
    'surprise',
    'catch out',
    'come upon/across',
    'stumble on',
    'chance on',
    'light on',
    'take by surprise',
    'catch unawares',
    'catch off guard',
    'catch red-handed',
    'catch in the act',
    'burst in on',
    'entangle',
    'snarl',
    'entwine',
    'intertwine',
    'intertwist',
    'twist',
    'ravel',
    'knot',
    'enmesh',
    'coil',
    'mat',
    'jumble',
    'muddle',
    'untangle',
    'disentangle',
    'unravel',
    'stick',
    'snag',
    'become trapped',
    'become stuck',
    'become wedged',
    'become entangled',
    'become snarled up',
    'become snagged',
    'fasten',
    'do up',
    'hook',
    'strap',
    'tie',
    'secure',
    'clasp',
    'clip',
    'unfasten',
    'make',
    'get to',
    'board',
    'get on',
    'enter',
    'mount',
    'ascend',
    'embark',
    'entrain',
    'emplane',
    'be in time for',
    'reach in time',
    'go on board',
    'go aboard',
    'step aboard',
    'embus',
    'miss',
    'alight',
    'engage',
    'capture',
    'attract',
    'draw',
    'gain',
    'grab',
    'arrest',
    'seize',
    'hold',
    'win',
    'absorb',
    'engross',
    'rivet',
    'grip',
    'captivate',
    'bewitch',
    'perceive',
    'notice',
    'observe',
    'discern',
    'detect',
    'note',
    'make out',
    'spot',
    'see',
    'become aware of',
    'miss',
    'hear',
    'perceive',
    'recognize',
    'discern',
    'make out',
    'understand',
    'comprehend',
    'grasp',
    'take in',
    'fathom',
    'apprehend',
    'get to the bottom of',
    'unravel',
    'decipher',
    'follow',
    'puzzle out',
    'keep up with',
    'evoke',
    'suggest',
    'recall',
    'express',
    'reproduce',
    'represent',
    'show',
    'encapsulate',
    'capture',
    'record',
    'film',
    'photograph',
    'draw',
    'paint',
    'conjure up',
    'summon up',
    'call to mind',
    'hit',
    'strike',
    'slap',
    'smack',
    'crack',
    'bang',
    'contact',
    'connect with',
    'miss',
    'contract',
    'get',
    'take',
    'develop',
    'fall victim to',
    'go down with',
    'become infected with',
    'become ill/sick with',
    'fall ill/sick with',
    'be taken ill with',
    'show symptoms of',
    'succumb to',
    'go/come down with',
    'sicken for',
    'be struck down with',
    'be stricken with',
    'shake off',
    'escape',
    'ignite',
    'burn',
    'flame',
    'burst into flames',
    'kindle',
    'become ignited',
    'start burning',
    'catch/take fire',
    'flame up',
    'go out',
    'start',
    'fire',
    'go',
    'function',
    'operate',
    'start running',
    'begin working',
    'stop',
]