export const definitions = [
    '"he ceded control of the company to his brother"',
]
export const synonyms = [
    'surrender',
    'concede',
    'relinquish',
    'yield',
    'give up',
    'hand over',
    'turn over',
    'give over',
    'make over',
    'transfer',
    'bequeath',
    'grant',
    'remit',
    'renounce',
    'resign',
    'abandon',
    'forgo',
    'sacrifice',
    'waive',
    'forsake',
    'part with',
    'deliver up',
    'keep',
    'gain',
]