export const definitions = [
    '"a single-celled organism"',
    '"a single-celled organism"',
    '"the authorities locked all remaining inmates in their cells"',
    '"the weapons may be used to arm terrorist cells"',
    '"a button cell for a quartz watch"',
    '"I\'ll just call him on his cell"',
    '"the authorities locked all remaining inmates in their cells"',
    '"the weapons may be used to arm terrorist cells"',
    '"a button cell for a quartz watch"',
    '"I\'ll just call him on his cell"',
]
export const synonyms = [
    'dungeon',
    'oubliette',
    'lockup',
    'prison',
    'room',
    'cubicle',
    'compartment',
    'chamber',
    'stall',
    'enclosure',
    'compartment',
    'cavity',
    'hole',
    'hollow',
    'bay',
    'chamber',
    'slot',
    'niche',
    'section',
    'compartment',
    'cavity',
    'hole',
    'hollow',
    'bay',
    'chamber',
    'slot',
    'niche',
    'section',
    'caucus',
    'unit',
    'faction',
    'arm',
    'section',
    'nucleus',
    'clique',
    'coterie',
    'group',
    'party',
    'clan',
    'wing',
    'accumulator',
    'power unit',
    'dungeon',
    'oubliette',
    'lockup',
    'prison',
    'room',
    'cubicle',
    'compartment',
    'chamber',
    'stall',
    'enclosure',
    'compartment',
    'cavity',
    'hole',
    'hollow',
    'bay',
    'chamber',
    'slot',
    'niche',
    'section',
    'compartment',
    'cavity',
    'hole',
    'hollow',
    'bay',
    'chamber',
    'slot',
    'niche',
    'section',
    'caucus',
    'unit',
    'faction',
    'arm',
    'section',
    'nucleus',
    'clique',
    'coterie',
    'group',
    'party',
    'clan',
    'wing',
    'accumulator',
    'power unit',
]