export const definitions = [
    '"the report had been censored \"in the national interest\""',
    '"my mail was being censored"',
    '"the editors censored an article I wrote this week"',
    '"the report was approved by the military censors"',
    '"the movie has been given an adults-only rating by film censors"',
    '"at least the censor did not cut the column completely"',
]
export const synonyms = [
    'cut',
    'delete',
    'redact',
    'blue-pencil',
    'unpublish',
    'examine',
    'inspect',
    'edit',
    'expurgate',
    'bowdlerize',
    'sanitize',
    'delete parts of',
    'make cuts in',
    'make changes to',
    'make acceptable',
    'expurgator',
    'examiner',
    'inspector',
    'editor',
]