definitions: [
    '"the center of the ceiling"',
    '"the center of a vast territory"',
    '"a new center party"',
    '"many coaches instruct their center to charge viciously on all plays"',
    '"only 10 centers averaged more than 10 points per game last year"',
    '"truffles with liqueur centers"',
    '"the galactic rotation of the solar system around the galactic center"',
    '"he flied out to center"',
    '"the city was a center of discontent"',
    '"two issues at the center of the healthcare debate"',
    '"Geneva was then the center of the international world"',
    '"a center for medical research"',
    '"a shopping center"',
    '"the mercantile association was centered in northern Germany"',
    '"the case centers around the couple\'s adopted children"',
    '"the plot centers on two young men"',
    '"he is centering his discussion on an analysis of patterns of mortality"',
    '"to center the needle, turn the knob"',
    '"he centered from a difficult position on the left"',
    '"West Virginia\'s offense lined up to center the ball"',
    'No translation found.',
]
synonyms: [
    'middle',
    'nucleus',
    'heart',
    'core',
    'hub',
    'pivot',
    'kernel',
    'eye',
    'bosom',
    'midpoint',
    'mean',
    'median',
    'interior',
    'depths',
    'thick',
    'bullseye',
    'focus',
    'focal point',
    'cynosure',
    'middle point',
    'halfway point',
    'edge',
    'pivot',
    'axis',
    'fulcrum',
    'center point',
    'foundation',
    'basis',
    'keystone',
    'mainspring',
    'mainstay',
    'linchpin',
    'bedrock',
    'fundament',
    'base',
    'key',
    'centerpiece',
    'core',
    'heart',
    'focus',
    'crux',
    'prop',
    'backbone',
    'anchor',
    'fundamental principle',
    'main ingredient',
    'central component',
    'establishment',
    'installation',
    'place',
    'depot',
    'station',
    'location',
    'premises',
    'site',
    'post',
    'base',
    'camp',
    'focus',
    'concentrate',
    'pivot',
    'hinge',
    'be based',
    'revolve around',
    'have as its starting point',
]