export const definitions = [
  '"I began to be curious about the whereabouts of the bride and groom"',
  '"she was curious to know what had happened"',
  '"a curious stare"',
  '"a curious sensation overwhelmed her"',
];
export const synonyms = [
  'eager',
  'excited',
  'impatient',
  'on tenterhooks',
  'on the edge of one\'s seat',
  'on pins and needles',
  'keen',
  'anxious',
  'longing',
  'expectant',
  'enthralled',
  'enthusiastic',
  'avid',
  'breathless',
  'open-mouthed',
  'in suspense',
  'waiting with bated breath',
  'uninterested',
  'incurious',
  'inquisitive',
  'intrigued',
  'interested',
  'agog',
  'quizzical',
  'inquiring',
  'searching',
  'probing',
  'querying',
  'questioning',
  'interrogative',
  'perplexed',
  'puzzled',
  'baffled',
  'mystified',
  'eager to know',
  'dying to know',
  'burning with curiosity',
  'nebby',
  'uninterested',
  'strange',
  'odd',
  'peculiar',
  'funny',
  'unusual',
  'bizarre',
  'weird',
  'eccentric',
  'queer',
  'unexpected',
  'unfamiliar',
  'abnormal',
  'out of the ordinary',
  'atypical',
  'anomalous',
  'untypical',
  'different',
  'out of the way',
  'surprising',
  'incongruous',
  'extraordinary',
  'remarkable',
  'puzzling',
  'mystifying',
  'mysterious',
  'perplexing',
  'baffling',
  'unaccountable',
  'inexplicable',
  'irregular',
  'singular',
  'offbeat',
  'unconventional',
  'unorthodox',
  'outlandish',
  'off-center',
  'aberrant',
  'freak',
  'freakish',
  'deviant',
  'uncanny',
  'eerie',
  'unnatural',
  'outré',
  'unco',
  'out of the common',
  'ordinary',
];