export const definitions = [
    '"a group of young people set up a chant of \"Why are we waiting?\""',
    '"he was whispering something, repeating it like a chant or a mantra"',
    '"Gregorian chant"',
    '"protesters were chanting slogans"',
    '"the crowd chanted, \"No violence!\""',
    '"priests and choir chant the story of the resurrection"',
]
export const synonyms = [
    'shout',
    'cry',
    'slogan',
    'war cry',
    'chorus',
    'chanting',
    'rallying call',
    'incantation',
    'intonation',
    'recitation',
    'singing',
    'song',
    'recitative',
    'mantra',
    'cantillation',
    'shout',
    'sing',
    'chorus',
    'carol',
    'repeat',
    'sing',
    'intone',
    'incant',
    'recite',
    'cantillate',
    'intonate',
]