export const definitions = [
  '"a chart showing how much do-it-yourself costs compared with retail"',
  '"she topped the charts for eight weeks"',
  '"a chart of the English coast"',
  '"scribbled on a patient\'s chart"',
  '"Cook charted the coasts and waters of New Zealand"',
  '"the pilot found his craft taking a route he had not charted"',
  '"the poems chart his descent into madness"',
  '"a major series charting the history of country music"',
  '"the record will probably chart at about No. 74"',
];
export const synonyms = [
  'graph',
  'table',
  'tabulation',
  'grid',
  'histogram',
  'diagram',
  'guide',
  'scheme',
  'figure',
  'illustration',
  'bar chart',
  'pie chart',
  'flow chart',
  'map',
  'plan',
  'blueprint',
  'graphic',
  'hit parade',
  'top twenty',
  'list',
  'listing',
  'league',
  'catalog',
  'index',
  'blueprint',
  'drawing',
  'diagram',
  'sketch',
  'map',
  'layout',
  'artist\'s impression',
  'illustration',
  'representation',
  'delineation',
  'plat',
  'scale drawing',
  'plot',
  'delineate',
  'draw',
  'depict',
  'portray',
  'survey',
  'follow',
  'trace',
  'outline',
  'describe',
  'detail',
  'note',
  'report',
  'record',
  'register',
  'document',
  'chronicle',
  'log',
  'catalog',
  'follow',
  'trace',
  'outline',
  'describe',
  'detail',
  'note',
  'report',
  'record',
  'register',
  'document',
  'chronicle',
  'log',
  'catalog',
];