export const definitions = [
    '"a cheeky grin"',
    '"a cheeky pint"',
    '"we ventured south for a cheeky weekend away"',
    '"he was attacked by a cheeky dog"',
]
export const synonyms = [
    'impudent',
    'impertinent',
    'insolent',
    'presumptuous',
    'forward',
    'pert',
    'bold',
    'brazen',
    'brazen-faced',
    'shameless',
    'audacious',
    'overfamiliar',
    'irreverent',
    'discourteous',
    'disrespectful',
    'insubordinate',
    'impolite',
    'bad-mannered',
    'ill-mannered',
    'unmannerly',
    'mannerless',
    'rude',
    'insulting',
    'malapert',
    'contumelious',
    'presumptive',
    'assumptive',
    'bold as brass',
    'respectful',
    'polite',
]