definitions: [
    '"a chesty cough"',
]
synonyms: [
    'large-breasted',
    'big-breasted',
    'bosomy',
    'large-bosomed',
    'big-bosomed',
    'shapely',
    'ample',
    'plump',
    'rounded',
    'well rounded',
    'full-figured',
    'womanly',
    'voluptuous',
    'curvaceous',
    'Junoesque',
    'Rubenesque',
    'full-breasted',
    'heavy-breasted',
    'full-bosomed',
    'well covered',
    'well padded',
    'of ample proportions',
    'skinny',
    'petite',
    'vain',
    'narcissistic',
    'self-loving',
    'self-admiring',
    'self-regarding',
    'self-centered',
    'egotistic',
    'egotistical',
    'egoistic',
    'egocentric',
    'egomaniac',
    'proud',
    'arrogant',
    'boastful',
    'cocky',
    'cocksure',
    'full of oneself',
    'above oneself',
    'self-important',
    'immodest',
    'swaggering',
    'strutting',
    'self-satisfied',
    'self-congratulatory',
    'smug',
    'complacent',
    'supercilious',
    'haughty',
    'snobbish',
    'vainglorious',
    'boast',
    'brag',
    'blow one\'s own trumpet',
    'pleased with oneself',
    'in love with oneself',
    'peacockish',
    'have an excessively high opinion of oneself',
    'think too highly of oneself',
    'think a lot of oneself',
    'modest',
    'self-effacing',
]