export const definitions = [
    '"she chided him for not replying to her letters"',
    '"\"You mustn\'t speak like that,\" she chided gently"',
]
export const synonyms = [
    'scold',
    'chastise',
    'upbraid',
    'berate',
    'castigate',
    'lambaste',
    'rebuke',
    'reprimand',
    'reproach',
    'reprove',
    'admonish',
    'lecture',
    'criticize',
    'censure',
    'pull up',
    'go on at',
    'read someone the Riot Act',
    'give someone a piece of one\'s mind',
    'call down',
    'rate',
    'trim',
    'reprehend',
    'objurgate',
    'remonstrate with',
    'call to account',
    'take to task',
    'haul someone over the coals',
    'give someone a rating',
    'praise',
]