export const definitions = [
    '"she chained her bicycle to the railing"',
    '"he had been chained up"',
    '"as an actuary you will not be chained to a desk"',
]
export const synonyms = [
    'tie',
    'secure',
    'fasten',
    'tether',
    'hitch',
    'bind',
    'rope',
    'moor',
    'restrain',
    'shackle',
    'fetter',
    'manacle',
    'handcuff',
    'hobble',
    'confine',
    'imprison',
    'trammel',
    'gyve',
]