export const definitions = [
  '"strong guitar-driven songs with big, big choruses"',
  '"a selection of choruses from the \"Messiah\""',
  '"a typical service includes several hymns and choruses sung by all"',
  '"the orchestra lacked polish and the chorus were inclined to rush ahead regardless"',
  '"a growing chorus of complaint"',
  '"\"Good morning,\" we replied in chorus"',
  '"Sophocles no longer gave the chorus the major role"',
  '"a chorus pedal"',
  '"\"Morning, Father,\" the children chorused"',
  '"they chorused a noisy amen"',
];
export const synonyms = [
  'refrain',
  'burden',
  'strain',
  'choir',
  'ensemble',
  'choristers',
  'vocalists',
  'choral group',
  '(group of) singers',
  'chorus line',
  'dancing girls',
  'dance troupe',
  'together',
  'simultaneously',
  'at the same time',
  'in concert',
  'in unison',
  'as one',
  'in harmony',
  'chant',
  'intone',
  'croon',
  'carol',
  'warble',
  'trill',
  'pipe',
  'quaver',
  'yodel',
  'render',
  'perform',
  'troll',
];