export const definitions = [
    '"the human body"',
    '"they are only human and therefore mistakes do occur"',
    '"the risk of human error"',
    '"the human side of politics is getting stronger"',
]
export const synonyms = [
    'anthropoid',
    'animal',
    'mortal',
    'flesh and blood',
    'fallible',
    'weak',
    'frail',
    'imperfect',
    'vulnerable',
    'susceptible',
    'erring',
    'error-prone',
    'physical',
    'bodily',
    'fleshly',
    'carnal',
    'corporal',
    'infallible',
    'compassionate',
    'humane',
    'kind',
    'kindly',
    'kindhearted',
    'considerate',
    'understanding',
    'sympathetic',
    'tolerant',
    'approachable',
    'accessible',
    'inhuman',
    'person',
    'human being',
    'personage',
    'mortal',
    'man',
    'woman',
    'child',
    'individual',
    'soul',
    'being',
    'earthling',
    'Homo sapiens',
    'wight',
    'member of the human race',
    'living soul',
    'animal',
    'alien',
]