export const definitions = [
    '"they came to church with me"',
    '"the Church of England"',
    '"Isobel would enter the Church as a deacon"',
    '"the separation of church and state"',
]
export const synonyms = [
    'house of God',
    'kirk',
    'the Lord\'s house',
    'house of prayer',
    'denomination',
    'sect',
    'creed',
    'faith',
    'sect',
    'Church',
    'cult',
    'movement',
    'body',
    'persuasion',
    'communion',
    'order',
    'fraternity',
    'brotherhood',
    'sisterhood',
    'school',
    'faith',
    'creed',
    'belief',
    'religion',
    'sodality',
    'religious group',
    'faith community',
    'religious persuasion',
    'religious belief',
]