definitions: [
    '"draw a circle with a compass"',
    '"the lamp spread a circle of light"',
    '"they all sat around in a circle"',
    '"she was pale and rather beautiful, with dark circles around deep, exhausted eyes"',
    '"she sat in the front row of the circle"',
    '"she did not normally move in such exalted circles"',
    '"we circled around the island"',
    '"the two dogs circle each other with hackles raised"',
    '"he paced away from her, then circled back"',
    '"the monastery was circled by a huge wall"',
    '"circle the correct answers"',
]
synonyms: [
    'ring',
    'round',
    'band',
    'hoop',
    'circlet',
    'halo',
    'disk',
    'wreath',
    'annulus',
    'balcony',
    'upper circle',
    'group',
    'set',
    'ring',
    'company',
    'body',
    'coterie',
    'clique',
    'camp',
    'league',
    'faction',
    'crowd',
    'band',
    'crew',
    'sphere',
    'world',
    'milieu',
    'arena',
    'domain',
    'society',
    'wheel',
    'revolve',
    'rotate',
    'whirl',
    'spiral',
    'gyrate',
    'go around',
    'circumnavigate',
    'orbit',
    'circumambulate',
    'move around',
    'move around in circles',
    'walk around',
    'travel around',
    'revolve around',
    'surround',
    'encircle',
    'ring',
    'enclose',
    'encompass',
    'bound',
    'hem in',
    'gird',
    'girdle',
    'ring around',
    'hedge in',
    'fence in',
]