export const definitions = [
    '"the questions rose to a clamor"',
    '"the growing public clamor for more police officers on the beat"',
    '"the surging crowds clamored for attention"',
    '"scientists are clamoring for a ban on all chlorine substances"',
]
export const synonyms = [
    'din',
    'racket',
    'uproar',
    'tumult',
    'babel',
    'shouting',
    'yelling',
    'screaming',
    'baying',
    'roaring',
    'blaring',
    'clangor',
    'commotion',
    'brouhaha',
    'hue and cry',
    'hubbub',
    'bedlam',
    'pandemonium',
    'vociferation',
    'ululation',
    'shivaree',
    'loud noise',
    'stramash',
    'silence',
    'demand(s)',
    'call(s)',
    'urging',
    'insistence',
    'protests',
    'complaints',
    'outcry',
    'storms of protest',
    'yell',
    'bay',
    'scream',
    'shriek',
    'roar',
    'shout loudly',
    'demand',
    'call',
    'bay',
    'press',
    'push',
    'lobby',
]