export const definitions = [
    '"a clawed hand grabbed for me"',
    '"scaly creatures with beaks and clawed feet"',
    '"two Asian short-clawed otters"',
    '"clawed lobsters are found in Nova Scotia"',
    '"the kitten was clawing at Lowell\'s trouser leg"',
    '"her hands clawed his shoulders"',
    '"bitter jealousy clawed at her"',
    '"his fingers clawed at the air"',
    '"he clawed his way over a pile of bricks"',
]
export const synonyms = [
    'scratch',
    'lacerate',
    'tear',
    'rake',
    'rip',
    'slash',
    'scrape',
    'graze',
    'maul',
    'savage',
    'mutilate',
    'dig into',
    'scrabble at',
    'grab',
    'seize',
    'lay (one\'s) hands on',
    'get one\'s hands on',
    'reach for',
    'snatch at',
    'make a grab for',
    'catch at',
    'claw at',
    'grab/seize/take hold of',
]