export const definitions = [
    '"clean your teeth properly after meals"',
    '"chair covers should be easy to clean"',
    '"there are a variety of ways to cook the herring, but it must first be gutted and cleaned"',
]
export const synonyms = [
    'wash',
    'cleanse',
    'wipe',
    'sponge',
    'scrub',
    'mop',
    'rinse',
    'scour',
    'swab',
    'flush',
    'polish',
    'disinfect',
    'shampoo',
    'floss',
    'lave',
    'launder',
    'dry-clean',
    'hose down',
    'sluice (down)',
    'dirty',
    'soil',
    'gut',
    'eviscerate',
    'draw',
    'dress',
    'remove the innards of',
]