export const definitions = [
    '"she clenched her fists, struggling for control"',
    '"John\'s right hand clenched into a fist"',
    '"he clenched his teeth, fighting waves of nausea"',
    '"her teeth clenched in anger"',
    '"he clenched the steering wheel so hard that the car wobbled"',
    '"my stomach was clenched in a knot"',
    '"her heart clenched in fear"',
    '"she saw the anger rise, saw the clench of his fists"',
]
export const synonyms = [
    'firm',
    'fast',
    'secure',
    'fixed',
    'clenched',
    'clinched',
    'relaxed',
    'insecure',
    'grit',
    'squeeze together',
    'press together',
    'clamp together',
    'close tightly',
    'shut tightly',
    'make into a fist',
    'make into a ball',
    'grip',
    'grasp',
    'grab',
    'clutch',
    'clamp',
    'clasp',
    'seize',
    'press',
    'squeeze',
    'lay (one\'s) hands on',
    'hold tightly',
    'fasten one\'s hand on',
    'hang onto',
    'contraction',
    'tightening',
    'tensing',
    'tension',
    'constricting',
    'cramp',
]