export const definitions = [
    '"a clever and studious young woman"',
    '"how clever of him to think of this!"',
    '"he was clever at getting what he wanted"',
    '"she is clever with her hands"',
    '"a simple but clever idea for helping people learn computing"',
    '"it wasn\'t too clever, leaving Dolly alone"',
]
export const synonyms = [
    'intelligent',
    'bright',
    'smart',
    'brilliant',
    'talented',
    'gifted',
    'precocious',
    'capable',
    'able',
    'competent',
    'apt',
    'proficient',
    'educated',
    'learned',
    'erudite',
    'academic',
    'bookish',
    'knowledgeable',
    'wise',
    'sagacious',
    'stupid',
    'skillful',
    'dexterous',
    'adroit',
    'deft',
    'nimble',
    'nimble-fingered',
    'handy',
    'adept',
    'skilled',
    'talented',
    'shrewd',
    'astute',
    'sharp',
    'acute',
    'quick',
    'sharp-witted',
    'quick-witted',
    'ingenious',
    'resourceful',
    'canny',
    'cunning',
    'crafty',
    'artful',
    'wily',
    'slick',
    'neat',
    'ill-advised',
    'foolish',
    'wise',
    'sensible',
    'prudent',
    'politic',
    'shrewd',
    'astute',
    'canny',
    'sagacious',
    'common-sense',
    'commonsensical',
    'sound',
    'well advised',
    'well thought out',
    'considered',
    'thoughtful',
    'perceptive',
    'discerning',
    'clear-sighted',
    'insightful',
    'far-sighted',
    'percipient',
    'discriminating',
    'informed',
    'intelligent',
    'enlightened',
    'logical',
    'rational',
    'discreet',
    'careful',
    'cautious',
    'circumspect',
    'diplomatic',
    'strategic',
    'expedient',
    'practical',
    'advisable',
    'long-headed',
    'sapient',
    'well judged',
    'in one\'s(best) interests',
    'argute',
    'injudicious',
    'foolish',
    'ill-advised',
]