export const definitions = [
    '"insurance tailor-made to a client\'s specific requirements"',
    '"a client referred for counseling"',
    '"workstation clients are going to be easy to install"',
    '"friendly client programs like this enable you to perform complicated actions in just a mouse press or two"',
]
export const synonyms = [
    'customer',
    'buyer',
    'purchaser',
    'shopper',
    'consumer',
    'user',
    'patient',
    'patron',
    'regular',
    'habitué',
    'frequenter',
    'clientele',
    'patronage',
    'public',
    'market',
    'trade',
    'business',
    'vendee',
    'emptor',
    'child',
    'minor',
    'ward',
    'charge',
    'protégé',
    'relative',
    'hanger-on',
    'parasite',
    'offspring',
    'progeny',
    'fosterling',
    'leech',
    'passenger',
    'drone',
    'family member',
]