export const definitions = [
    '"the old-school clique"',
]
export const synonyms = [
    'coterie',
    'circle',
    'inner circle',
    'crowd',
    'in-crowd',
    'set',
    'group',
    'pack',
    'band',
    'ring',
    'mob',
    'crew',
    'club',
    'society',
    'fraternity',
    'sorority',
    'fellowship',
    'camp',
    'cartel',
    'cabal',
    'junta',
    'caucus',
    'cell',
    'lobby',
    'push',
    'camarilla',
]