export const definitions = [
    '"she jumped into the train just as the doors were closing"',
    '"they had to close the window because of the insects"',
    '"Stephen closed his ears to the sound"',
    '"glass doors close off the living room from the hall"',
    '"Loretta closed her mouth"',
    '"Ron closed the book"',
    '"my fist closed around the weapon"',
    '"this will cause a relay to operate and close the circuit"',
    '"the members were thanked for attending and the meeting was closed"',
    '"the concert closed with \"Silent Night\""',
    '"we close with a point about truth"',
    '"he closed a deal with a metal dealer"',
    '"the factory is to close with the loss of 150 jobs"',
    '"the country has been closed to outsiders for almost 50 years"',
    '"I went to the bank to close an account held by my daughter"',
    '"a statement is used to close a data file"',
    '"they plotted a large group of aircraft about 130 miles away and closing fast"',
]
export const synonyms = [
    'shut',
    'slam',
    'fasten',
    'secure',
    'lock',
    'bolt',
    'bar',
    'latch',
    'padlock',
    'draw to',
    'pull to',
    'push to',
    'put up the shutter',
    'open',
    'unlock',
    'stop up',
    'plug',
    'cork',
    'stopper',
    'fill (up)',
    'pack',
    'stuff',
    'choke',
    'obstruct',
    'occlude',
    'stopple',
    'block (up/off)',
    'seal (up/off)',
    'shut up/off',
    'bung (up)',
    'make airtight',
    'make watertight',
    'clog (up)',
    'open',
    'unblock',
    'join',
    'connect',
    'unite',
    'come together',
    'come into contact',
    'form a circle',
    'end',
    'conclude',
    'finish',
    'terminate',
    'wind up',
    'break off',
    'halt',
    'discontinue',
    'dissolve',
    'adjourn',
    'suspend',
    'prorogue',
    'recess',
    'bring/come to an end',
    'call a halt to',
    'open',
    'begin',
    'end',
    'conclude',
    'finish',
    'terminate',
    'wind up',
    'break off',
    'halt',
    'discontinue',
    'dissolve',
    'adjourn',
    'suspend',
    'prorogue',
    'recess',
    'bring/come to an end',
    'call a halt to',
    'open',
    'begin',
    'clinch',
    'settle',
    'secure',
    'seal',
    'set the seal on',
    'confirm',
    'guarantee',
    'establish',
    'transact',
    'pull off',
    'complete',
    'conclude',
    'fix',
    'agree',
    'finalize',
    'bring off/about',
    'shake hands on',
    'shut down',
    'close down',
    'fail',
    'collapse',
    'crash',
    'go under',
    'cease activity',
    'cease production',
    'cease operating',
    'come to a halt',
    'cease trading',
    'go out of business',
    'go bankrupt',
    'become insolvent',
    'go into receivership',
    'go into liquidation',
    'be liquidated',
    'be wound up',
    'be closed (down)',
    'be shut (down)',
    'open',
    'catch up',
    'creep up',
    'near',
    'approach',
    'narrow',
    'lessen',
    'dwindle',
    'diminish',
    'reduce',
    'shrink',
    'contract',
    'constrict',
    'straiten',
    'gain on someone',
    'draw nearer/near',
    'get nearer/near',
    'come nearer/near',
    'draw closer/close',
    'get closer/close',
    'come closer/close',
    'grow/become/make smaller',
    'get/become/make narrower',
    'widen',
]