export const definitions = [
  '"of the hundreds of new plants ______ the best ones are selected"',
  '"we have ______ DNA sequences added to the ends of the linear plasmid"',
];
export const synonyms = [
  'copy',
  'reproduce',
  'duplicate',
  'recreate',
  'repeat',
  'make a copy of',
  'make a replica of',
  'perform again',
  'copy',
  'duplicate',
  'replicate',
  'photocopy',
  'xerox',
  'photostat',
  'mimeograph',
  'mimeo',
  'print',
  'transcribe',
  'forge',
  'counterfeit',
  'produce a copy of',
  'make a facsimile of',
  'make a Xerox of',
];