export const definitions = [
  '"successful women don\'t want to be male ______"',
  '"attack of the ______"',
  '"______ can create more problems than they solve"',
  '"harddrive backups are a form of ______"',
];
export const synonyms = [
  'doubles',
  'replicas',
  'lookalikes',
  'copies',
  'reproductions',
  'twins',
  'duplicates',
  'facsimile',
  'counterparts',
  'mirror images',
  'similitude',
  'living images',
  'exact likeness',
  'Doppelgänger',
  'reproduce',
  'recreations',
  'repeats',
  'make a copy of',
  'make a replica of',
  'perform again',
  'copy',
  'duplicate',
  'replicates',
  'replications',
  'photocopies',
  'xeroxes',
  'photostats',
  'mimeographs',
  'mimeos',
  'prints',
  'transcriptions',
  'forges',
  'counterfeits',
  'produce a copy of',
  'make a facsimile of',
  'make a Xerox of',
];