export const definitions = [
  '"the perfect ______ to the album"',
  '"the last episode was still a great ______"',
  '"this role will best suit a ______ whose hungry for commissions"',
  '"he could develop into a big-league ______"',
  '"baseball\'s highest - paid ______"',
  '"this hotel is even ______ to the sea"',
  '"her birthday and wedding anniversary are ______ together than she would have liked"',
  '"cloth with a ______ weave"',
  '"holding eachother ______ than ever before"',
];
export const synonyms = [
  'near',
  'adjacent',
  'in the neighborhood of',
  'neighboring',
  'hard by',
  'adjoining',
  'abutting',
  'alongside',
  'close by',
  'nearby',
  'at hand',
  'contiguous',
  'proximate',
  'accessible',
  'handy',
  'convenient',
  'walkable',
  'nigh',
  'in close proximity',
  'close/near at hand',
  'not far from',
  'in the vicinity of',
  'within reach of',
  'within close range of',
  'on the doorstep',
  'within sight',
  'within earshot',
  'a stone\'s throw away',
  'at close quarters',
  'far',
  'distant',
  'remote',
  'dense',
  'compact',
  'tight',
  'close-packed',
  'packed',
  'solid',
  'condensed',
  'compressed',
  'concentrated',
  'crowded',
  'cramped',
  'crammed',
  'congested',
  'crushed',
  'squeezed',
  'jammed',
  'tightly packed',
  'sparse',
  'near',
  'within an ace of',
  'on the verge of',
  'on the brink of',
  'on the point of',
  'even',
  'well matched',
  'neck and neck',
  'side by side',
  'hard-fought',
  'nip and tuck',
  'evenly matched',
  'nose to nose',
  'with nothing to choose between them',
  'sharply contested',
  'one-sided',
  'immediate',
  'direct',
  'near',
  'distant',
  'intimate',
  'dear',
  'bosom',
  'close-knit',
  'inseparable',
  'attached',
  'loving',
  'devoted',
  'faithful',
  'constant',
  'special',
  'good',
  'best',
  'fast',
  'firm',
  'valued',
  'treasured',
  'cherished',
  'casual',
  'strong',
  'marked',
  'distinct',
  'pronounced',
  'slight',
  'careful',
  'detailed',
  'thorough',
  'minute',
  'painstaking',
  'meticulous',
  'assiduous',
  'diligent',
  'rigorous',
  'scrupulous',
  'conscientious',
  'attentive',
  'focused',
  'intent',
  'concentrated',
  'searching',
  'methodical',
  'vigilant',
  'watchful',
  'keen',
  'alert',
  'casual',
  'strict',
  'tight',
  'carefully guarded',
  'closely guarded',
  'reticent',
  'quiet',
  'uncommunicative',
  'unforthcoming',
  'private',
  'secretive',
  'tight-lipped',
  'close-mouthed',
  'close-lipped',
  'guarded',
  'evasive',
  'humid',
  'muggy',
  'stuffy',
  'airless',
  'fuggy',
  'heavy',
  'sticky',
  'steamy',
  'clammy',
  'sultry',
  'oppressive',
  'stifling',
  'suffocating',
  'unventilated',
  'like a Turkish bath',
  'like a sauna',
  'claggy',
  'fresh',
];