export const definitions = [
  '"Francesca was told to ______ in white"',
  '"luxuriant tropical forests will continue to ______ the islands"',
  '"eight children to feed and ______"',
];
export const synonyms = [
  'dress',
  'attire',
  'outfit',
  'array',
  'rig (out)',
  'turn out',
  'fit out',
  'costume',
  'robe',
  'garb',
  'drape',
  'accoutre',
  'bedizen',
  'caparison',
  'apparel',
  'habit',
  'invest',
  'cover',
  'overlay',
  'overspread',
  'cloak',
  'blanket',
  'carpet',
  'envelop',
  'swathe',
  'swaddle',
  'shroud',
  'wrap',
  'surround',
  'enshroud',
  'trick out/up',
  'deck out',
  'trap out',
  'undress',
  'uncover',
  'provide',
  'furnish',
  'endow',
  'serve',
  'confer',
  'equip',
  'rig out',
  'outfit',
  'fit',
  'arm',
  'endue',
  'kit out',
];