export const definitions = [
  '"the large axe his father used to cleave wood for the fire"',
  '"the egg cleaves to form a mulberry-shaped cluster of cells"',
  '"they watched a coot cleave the smooth water"',
  '"an unstoppable warrior clove through their ranks"',
  '"Stan was off, cleaving a path through the traffic"',
];
export const synonyms = [
  'split',
  'divided',
  'bisected',
  'cleft',
  'split',
  'divide',
  'sever',
  'splinter',
  'cut (up)',
  'hew',
  'hack',
  'halve',
  'bisect',
  'quarter',
  'rend',
  'sunder',
  'rive',
  'split open',
  'crack open',
  'lay open',
  'chop up',
  'slice up',
  'plow',
  'drive',
  'bulldoze',
  'cut',
  'carve',
  'make',
];