export const definitions = [
    '"clumps of earth"',
    '"they sat on the wall in clumps of two and three"',
    '"a clump of ferns"',
    '"the particles tend to clump together"',
]
export const synonyms = [
    'lump',
    'clod',
    'mass',
    'wad',
    'concentration',
    'agglutination',
    'agglomeration',
    'accumulation',
    'buildup',
    'gobbet',
    'cluster',
    'thicket',
    'group',
    'bunch',
    'collection',
    'assembly',
    'assemblage',
    'tuft',
    'tuffet',
    'tussock',
    'mat',
    'tangle',
    'stamp',
    'stomp',
    'stump',
    'clomp',
    'tramp',
    'plod',
    'trudge',
    'lumber',
    'stumble',
    'thump',
    'thud',
    'bang',
    'walk heavily',
    'sprauchle',
    'stamp',
    'stomp',
    'stump',
    'clomp',
    'tramp',
    'plod',
    'trudge',
    'lumber',
    'stumble',
    'thump',
    'thud',
    'bang',
    'walk heavily',
    'sprauchle',
]