export const definitions = [
    '"the cold made his fingers clumsy"',
    '"a terribly clumsy fellow"',
    '"a clumsy attempt to park"',
    '"a clumsy remake of an old movie"',
    '"the legal procedure is far too clumsy"',
    '"chairs with clumsy wooden armrests"',
    '"his choice of words was clumsy"',
]
export const synonyms = [
    'awkward',
    'uncoordinated',
    'ungainly',
    'graceless',
    'ungraceful',
    'inelegant',
    'gawky',
    'gauche',
    'gangling',
    'cloddish',
    'blundering',
    'lumbering',
    'bungling',
    'bumbling',
    'fumbling',
    'inept',
    'maladroit',
    'unskillful',
    'inexpert',
    'unhandy',
    'accident-prone',
    'like a bull in a china shop',
    'all fingers and thumbs',
    'graceful',
    'awkward',
    'uncoordinated',
    'ungainly',
    'graceless',
    'ungraceful',
    'inelegant',
    'gawky',
    'gauche',
    'gangling',
    'cloddish',
    'blundering',
    'lumbering',
    'bungling',
    'bumbling',
    'fumbling',
    'inept',
    'maladroit',
    'unskillful',
    'inexpert',
    'unhandy',
    'accident-prone',
    'like a bull in a china shop',
    'all fingers and thumbs',
    'graceful',
    'unwieldy',
    'unmanageable',
    'cumbersome',
    'bulky',
    'hulking',
    'heavy',
    'solid',
    'awkward',
    'unmaneuverable',
    'elegant',
    'gauche',
    'awkward',
    'graceless',
    'unpolished',
    'unsubtle',
    'crude',
    'uncouth',
    'boorish',
    'crass',
    'tactless',
    'insensitive',
    'thoughtless',
    'inconsiderate',
    'undiplomatic',
    'indelicate',
    'impolitic',
    'injudicious',
    'ill-judged',
    'tactful',
]