export const definitions = [
  '"a coarse woolen cloth"',
  '"dry, coarse sand"',
  '"under the microscope they are seen to contain coarse grains"',
  '"his coarse, ugly features contorted with rage"',
  '"the wine is harsh, tannic, and coarse"',
  '"a man of coarse speech"',
  '"indecent language and coarse jests"',
];
export const synonyms = [
  'rough',
  'bristly',
  'scratchy',
  'prickly',
  'hairy',
  'shaggy',
  'wiry',
  'soft',
  'heavy',
  'broad',
  'large',
  'rough',
  'rough-hewn',
  'unrefined',
  'inelegant',
  'rugged',
  'craggy',
  'delicate',
  'oafish',
  'loutish',
  'boorish',
  'churlish',
  'uncouth',
  'rude',
  'discourteous',
  'impolite',
  'ungentlemanly',
  'unladylike',
  'ill-mannered',
  'uncivil',
  'ill-bred',
  'vulgar',
  'common',
  'rough',
  'uncultured',
  'uncivilized',
  'crass',
  'foul-mouthed',
  'crude',
  'off color',
  'offensive',
  'dirty',
  'filthy',
  'smutty',
  'obscene',
  'indelicate',
  'improper',
  'indecent',
  'indecorous',
  'unseemly',
  'tasteless',
  'lewd',
  'prurient',
  'bawdy',
  'earthy',
  'broad',
  'ribald',
  'salty',
  'sophisticated',
  'refined',
  'inoffensive',
];