export const definitions = [
];
export const synonyms = [
  'pamper',
  'spoil',
  'overindulge',
  'coddle',
  'mollycoddle',
  'cosset',
  'nanny',
  'nursemaid',
  'mother',
  'baby',
  'pet',
  'spoon-feed',
  'overparent',
  'humor',
  'wait on someone hand and foot',
  'kill someone with kindness',
  'feather-bed',
  'cocker',
  'pander to',
  'cater to someone\'s every whim',
  'wrap in cotton wool',
];