export const definitions = [
    '"a cup of coffee"',
    '"a coffee pot"',
    '"she\'ll buy you a coffee"',
    '"a jar of instant coffee"',
    '"a maxi dress in cream with a coffee silk trim"',
    '"going to coffees and answering questions"',
]
export const synonyms = [
    'joe',
    'java',
    'fawn',
    'buff',
    'sand',
    'sandy',
    'oatmeal',
    'wheaten',
    'biscuit',
    'coffee-colored',
    'café au lait',
    'camel',
    'kasha',
    'ecru',
    'taupe',
    'stone',
    'mushroom',
    'putty',
    'greige',
    'neutral',
    'natural',
    'brownish yellow',
    'pale brown',
    'stone-colored',
    'naturelle',
]