export const definitions = [
    '"they put forward cogent arguments for British membership"',
    '"the newspaper\'s lawyers must prepare a cogent appeal"',
]
export const synonyms = [
    'convincing',
    'compelling',
    'strong',
    'forceful',
    'powerful',
    'potent',
    'weighty',
    'valid',
    'sound',
    'well founded',
    'plausible',
    'effective',
    'efficacious',
    'telling',
    'impressive',
    'persuasive',
    'irresistible',
    'eloquent',
    'credible',
    'influential',
    'conclusive',
    'unanswerable',
    'authoritative',
    'logical',
    'reasoned',
    'rational',
    'reasonable',
    'lucid',
    'coherent',
    'systematic',
    'orderly',
    'methodical',
    'clear',
    'articulate',
    'consistent',
    'relevant',
    'well reasoned',
    'well organized',
    'vague',
    'unconvincing',
    'muddled',
]