export const definitions = [
  '"a cohort of civil servants patiently drafting legislation"',
  '"the 1940–44 birth cohort of women"',
  '"young Jack arrived with three of his cohorts"',
  '"a long-time cohort of the band"',
  '"in the plan elementary students will be cohorted, or placed, in an assigned class"',
  '"those who test positive are being cohorted on two designated floors to prevent the spread of the virus"',
];
export const synonyms = [
  'group',
  'grouping',
  'category',
  'categorization',
  'grade',
  'grading',
  'classification',
  'class',
  'set',
  'section',
  'division',
  'order',
  'batch',
  'list',
  'age group',
  'generation',
  'supporter',
  'follower',
  'adherent',
  'devotee',
  'champion',
  'backer',
  'upholder',
  'promoter',
  'fanatic',
  'fan',
  'enthusiast',
  'stalwart',
  'zealot',
  'disciple',
  'votary',
  'booster',
  'janissary',
  'sectary',
  'unit',
  'outfit',
  'force',
  'army',
  'group',
  'corps',
  'division',
  'brigade',
  'battalion',
  'regiment',
  'squadron',
  'company',
  'commando',
  'battery',
  'troop',
  'section',
  'patrol',
  'cadre',
  'crew',
  'detachment',
  'contingent',
  'column',
  'squad',
  'detail',
  'band',
  'legion',
];