export const definitions = [
    '"guineas and half-guineas were coined"',
    '"he coined the term \"desktop publishing.\""',
]
export const synonyms = [
    'mint',
    'stamp',
    'stamp out',
    'strike',
    'cast',
    'punch',
    'die',
    'mold',
    'forge',
    'make',
    'manufacture',
    'produce',
    'invent',
    'create',
    'make up',
    'devise',
    'conceive',
    'originate',
    'think up',
    'dream up',
    'formulate',
    'fabricate',
]