definitions: [
    '"he committed an uncharacteristic error"',
    '"they were reluctant to commit themselves to an opinion"',
    '"the treaty commits each party to defend the other"',
    '"try it out before you commit to a purchase"',
    '"we must be committed to peace"',
    '"manufacturers will have to commit substantial funds to developing new engines"',
    '"she loved a man who was committed to another woman"',
    '"he composed a letter but didn\'t commit it to paper"',
    '"she committed each tiny feature to memory"',
    '"committed to the flames"',
    '"he was committed to prison for contempt of court"',
    '"the magistrate decided to commit him for trial"',
    '"he had been committed for treatment"',
]
synonyms: [
    'carry out',
    'do',
    'perform',
    'perpetrate',
    'enact',
    'execute',
    'effect',
    'accomplish',
    'effectuate',
    'engage in',
    'be responsible for',
    'be to blame for',
    'be guilty of',
    'pledge',
    'devote',
    'apply',
    'give',
    'dedicate',
    'bind',
    'obligate',
    'devout',
    'devoted',
    'loyal',
    'dedicated',
    'faithful',
    'staunch',
    'firm',
    'steadfast',
    'resolute',
    'unwavering',
    'sincere',
    'wholehearted',
    'keen',
    'earnest',
    'enthusiastic',
    'zealous',
    'passionate',
    'ardent',
    'fervent',
    'motivated',
    'driven',
    'active',
    'sworn',
    'pledged',
    'dutiful',
    'hard-working',
    'diligent',
    'studious',
    'assiduous',
    'engagé',
    'apathetic',
    'allocate',
    'assign',
    'allot',
    'give',
    'give over',
    'afford',
    'apportion',
    'surrender',
    'consign',
    'sacrifice',
    'pledge',
    'dedicate',
    'consecrate',
    'set aside',
    'earmark',
    'reserve',
    'designate',
    'spare',
    'consign',
    'assign',
    'send',
    'deliver',
    'confine',
    'hospitalize',
    'confine',
    'institutionalize',
    'put away',
    'lock away',
    'lock up',
    'certify',
    'release',
]