export const definitions = [
  '"moves were made to confer an honorary degree on her"',
  '"the officials were conferring with allies"',
];
export const synonyms = [
  'bestow on',
  'present with/to',
  'grant to',
  'award to',
  'decorate with',
  'honor with',
  'give to',
  'give out to',
  'gift with',
  'endow with',
  'vest in',
  'hand out to',
  'extend to',
  'vouchsafe to',
  'accord to',
  'withhold',
  'remove',
  'consult',
  'talk',
  'speak',
  'converse',
  'communicate',
  'negotiate',
  'parley',
  'palaver',
  'confabulate',
  'have discussions',
  'discuss things',
  'exchange views',
  'have a talk',
  'have a chat',
  'have a tête-à-tête',
  'have negotiations',
  'have talks',
];