export const definitions = [
    '"I conned him into giving me your home number"',
    '"she was jailed for conning her aunt out of $500,000"',
    '"the children conned their pages with a great show of industry"',
    '"he hadn\'t conned anything bigger than a Boston whaler"',
]
export const synonyms = [
    'swindle',
    'defraud',
    'cheat',
    'trick',
    'fleece',
    'dupe',
    'deceive',
    'rook',
    'exploit',
    'squeeze',
    'milk',
    'bleed',
    'fool',
    'take advantage of',
    'mislead',
    'delude',
    'hoax',
    'hoodwink',
    'bamboozle',
    'string along',
    'embezzle',
    'gazump',
    'cozen',
    'sharp',
    'mulct',
]