export const definitions = [
    '"contraflow"',
    '"contradict"',
    '"contralateral"',
    '"contrabass"',
    '"contralto"',
]
export const synonyms = [
    'contra',
    'versus',
    'counter',
    'dead set against',
    'opposed to',
    'in opposition to',
    'hostile to',
    'averse to',
    'antagonistic toward',
    'inimical to',
    'unsympathetic to',
    'resistant to',
    'at odds with',
    'in disagreement with',
    'in defiance of',
    'at cross purposes with',
    'in favor of',
    'pro',
]