export const definitions = [
    '"a cooked breakfast"',
    '"cooked chicken can last longer than two days when stored properly"',
    '"as the result of cooked books, stock prices soared"',
    '"shall I cook dinner tonight?"',
    '"I told you I could cook"',
    '"while the rice is cooking, add the saffron to the stock"',
    '"a narcotics team who cooked the evidence"',
    '"if I can\'t talk to him I\'m cooked"',
    '"what\'s cooking on the alternative fuels front ? "',
    '"the band used to get up on the bandstand and really cook"',
]
export const synonyms = [
    'prepare',
    'make',
    'get',
    'put together',
    'bake',
    'sizzle',
    'crackle',
    'fizz',
    'hiss',
    'spit',
    'sputter',
    'crack',
    'snap',
    'fry',
    'decrepitate',
    'crepitate',
    'falsify',
    'alter',
    'doctor',
    'massage',
    'manipulate',
    'rig',
    'misrepresent',
    'forge',
    'tamper with',
    'interfere with',
    'happen',
    'go on',
    'occur',
    'take place',
]