export const definitions = [
  '"we hold the cooled branding irons"',
  '"an air-cooled engine"',
  '"we dived into the river to cool off"',
  '"cool the pastry for five minutes"',
  '"his feelings for her took a long time to cool"',
  '"after I\'d cooled off, I realized I was being irrational"',
  '"George was trying to cool him down"',
];
export const synonyms = [
  'chill',
  'refrigerate',
  'make cold/colder',
  'get cold/colder',
  'cool down',
  'lose heat',
  'heat',
  'pull oneself together',
  'calm down',
  'recover/regain one\'s self - control',
  'recover/regain one\'s composure',
  'compose oneself',
  'control oneself',
  'simmer down',
  'lose one\'s temper',
];