export const definitions = [
  '"being cooped up indoors all day makes him fidgety"',
];
export const synonyms = [
  'confine',
  'shut in',
  'close in',
  'shut up',
  'keep',
  'detain',
  'trap',
  'lock up',
  'imprison',
  'incarcerate',
  'immure',
  'intern',
  'impound',
  'cage',
  'hem in',
  'enclose',
  'mew up',
  'hold captive',
  'hold prisoner',
  'put under lock and key',
  'cage in',
  'pen in',
  'fence in',
  'rail in',
  'wall in',
  'set free',
];