export const definitions = [
    '"the 5th Army Corps"',
    '"the U.S. Army Medical Corps"',
    '"the press corps"',
]
export const synonyms = [
    'brigade',
    'regiment',
    'battalion',
    'company',
    'troop',
    'division',
    'squadron',
    'squad',
    'platoon',
    'contingent',
    'unit',
    'force',
    'garrison',
    'section',
    'group',
    'detachment',
    'commando',
    'battery',
    'band',
    'outfit',
    'cohort',
    'unit',
    'division',
    'detachment',
    'section',
    'company',
    'troop',
    'contingent',
    'squad',
    'squadron',
    'regiment',
    'garrison',
    'battalion',
    'brigade',
    'platoon',
    'force',
    'group',
    'body',
    'band',
    'team',
    'party',
    'troupe',
    'gang',
    'pack',
    'cohort',
]