export const definitions = [
    '"each form had to be copied and sent to a different department"',
    '"the command will copy a file from one disc to another"',
    '"he copied the details into his notebook"',
    '"I began to copy out the addresses"',
    '"I thought I\'d copy to you this letter sent to the PR representative"',
    '"I attached the document and copied him in so he\'d know it had been sent"',
    '"lifestyles that were copied from Miami and Fifth Avenue"',
    '"art students copied from approved old masters"',
    '"she was such fun that everybody wanted to copy her"',
    '"this is Edwards, do you copy, over"',
]
export const synonyms = [
    'duplicate',
    'photocopy',
    'xerox',
    'photostat',
    'mimeograph',
    'run off',
    'transcribe',
    'reproduce',
    'replicate',
    'clone',
    'forge',
    'fake',
    'falsify',
    'counterfeit',
    'bootleg',
    'make a photocopy of',
    'take a photocopy of',
    'imitate',
    'mimic',
    'ape',
    'emulate',
    'follow',
    'echo',
    'mirror',
    'simulate',
    'parrot',
    'reproduce',
    'plagiarize',
    'poach',
    'steal',
    'monkey',
    'infringe the copyright of',
]