export const definitions = [
    '"his ability to cope with stress"',
    '"it all got too much for me and I couldn\'t cope"',
    '"the roads are barely adequate to cope with the present traffic"',
    '"a high wall coped with tiles"',
]
export const synonyms = [
    'manage',
    'survive',
    'subsist',
    'shift for oneself',
    'stand on one\'s own two feet',
    'carry on',
    'get through',
    'get on',
    'get along',
    'get by',
    'muddle through',
    'bear up',
    'make the grade',
    'come through',
    'hold one\'s own',
    'keep \'s \'s end up',
    'keep \'s \'s head above water',
    'keep the wolf from the door',
    'handle',
    'address',
    'face',
    'face up to',
    'confront',
    'tackle',
    'sort out',
    'take care of',
    'put up with',
    'weather',
    'endure',
    'withstand',
    'stand up to',
    'bear',
    'brave',
    'accept',
    'come to terms with',
    'master',
    'overcome',
    'surmount',
    'get over',
    'get the better of',
    'beat',
    'look after oneself',
    'fend for oneself',
    'muddle along',
    'scrape by',
    'weather the storm',
    'deal with',
    'take in hand',
    'get to grips with',
    'contend with',
    'grapple with',
    'wrestle with',
    'struggle with',
    'tussle with',
]