export const definitions = [
  '"troops threw a cordon around the headquarters"',
  '"the city center was cordoned off after fires were discovered in two stores"',
];
export const synonyms = [
  'barrier',
  'line',
  'column',
  'row',
  'file',
  'ranks',
  'chain',
  'ring',
  'circle',
  'picket line',
  'seal off',
  'shut off',
  'isolate',
  'segregate',
  'quarantine',
  'seal',
  'close',
  'shut',
  'blockade',
  'enclose',
  'encircle',
  'surround',
  'close off',
  'tape off',
  'fence off',
  'rope off',
  'screen off',
  'curtain off',
  'partition off',
  'separate off',
];