export const definitions = [
  '"always open and taste your wine before the meal, if only to check that it is not corked"',
  '"the bottles were tightly corked and wired"',
  '"he had corked a mustache on his upper lip"',
  '"the balls are doctored and the bats are corked"',
];
export const synonyms = [
  'stop up',
  'plug',
  'stopper',
  'fill (up)',
  'pack',
  'stuff',
  'choke',
  'obstruct',
  'occlude',
  'stopple',
  'block (up/off)',
  'seal (up/off)',
  'shut up/off',
  'bung (up)',
  'make airtight',
  'make watertight',
  'clog (up)',
  'open',
  'unblock',
];