export const definitions = [
  '"the organizers were corralling the crowd into marching formation"',
  '"sheep and goats grazed the plains during the day but they were corralled at night"',
  '"the wagons, in forming the encampment, were corralled"',
  '"he was galloping a pony very fast around a tiny corral"',
];
export const synonyms = [
  'enclose',
  'confine',
  'lock up',
  'shut up',
  'shut in',
  'kettle',
  'fence in',
  'pen (in)',
  'rail in',
  'wall in',
  'cage (in)',
  'coop up',
  'mew in',
  'enclosure',
  'pen',
  'fold',
  'compound',
  'pound',
  'stockade',
  'paddock',
  'kraal',
  'potrero',
  'parrock',
];