export const definitions = [
  '"the table had been covered with a checked tablecloth"',
  '"cover the dish and put it in the microwave"',
  '"he was covered in mud"',
  '"she was covered in confusion"',
  '"the barn floor was covered in straw"',
  '"masonry paint will cover hairline cracks"',
  '"the grounds covered eight acres"',
  '"it took them four days to cover 150 miles"',
  '"a sequence of novels that will cover the period from 1968 to the present"',
  '"NBC is covering the Olympics"',
  '"development officers whose work would cover a large area"',
  '"the offense covers a wide spectrum of culpability"',
  '"there are grants to cover the cost of materials for loft insulation"',
  '"you\'re covered for up to $500 of incidentals per person"',
  '"your contents are now covered against accidental loss or damage in transit"',
  '"one reason doctors take temperatures is to cover themselves against negligence claims"',
  '"Louise laughed to cover her embarrassment"',
  '"she raised her gun to cover Klift"',
  '"I moved in front of Hawk to cover him as he reloaded"',
  '"he moved to cover second base"',
  '"other artists who have covered the song include U2"',
  '"a working stallion who has covered forty mares this season"',
  '"the ploy will fail if the ten is covered"',
  '"East covered with his queen"',
  '"a seat cover"',
  '"a manhole cover"',
  '"her life was captured between hard covers in her 1986 autobiography"',
  '"she burrowed down beneath the covers"',
  '"the sirens wailed and people ran for cover"',
  '"store seats under cover before the bad weather sets in"',
  '"the standing crops of game cover"',
  '"a landscape bare of woodland except for neat little fox covers"',
  '"they agreed to provide additional naval cover"',
  '"a restaurant is run as a cover for a money-laundering operation"',
  '"he was worried that their cover was blown"',
  '"the band played covers of Beatles songs"',
  '"the busiest time is in summer, with up to a thousand covers for three meals a day"',
];
export const synonyms = [
  'protect',
  'shield',
  'shelter',
  'envelop',
  'enfold',
  'engulf',
  'enclose',
  'tuck',
  'cup',
  'surround',
  'house',
  'sink',
  'embed',
  'bury',
  'submerge',
  'immerse',
  'put something on top of',
  'place something over',
  'place under cover',
  'reveal',
  'cake',
  'coat',
  'encrust',
  'plaster',
  'smother',
  'daub',
  'smear',
  'bedaub',
  'overspread',
  'besmear',
  'blanket',
  'overlay',
  'carpet',
  'overlie',
  'layer',
  'film',
  'submerge',
  'mantle',
  'pave',
  'spread thickly',
  'extend over',
  'scatter',
  'pepper',
  'sprinkle',
  'strew',
  'litter',
  'punctuate',
  'stud',
  'spread',
  'disperse',
  'intersperse',
  'distribute',
  'decorate',
  'bedeck',
  'adorn',
  'ornament',
  'trim',
  'trick out',
  'garnish',
  'hang',
  'festoon',
  'garland',
  'swathe',
  'wreathe',
  'embellish',
  'beautify',
  'prettify',
  'enhance',
  'grace',
  'set off',
  'bejewel',
  'bedizen',
  'caparison',
  'furbelow',
  'extend',
  'spread',
  'continue',
  'range',
  'unfold',
  'unroll',
  'span',
  'be unbroken',
  'travel',
  'journey',
  'go',
  'do',
  'pass over',
  'traverse',
  'cross',
  'put behind one',
  'get under one\'s belt',
  'travel over',
  'journey over/across',
  'go across',
  'make one\'s way across',
  'range/tramp over',
  'report',
  'write up',
  'describe',
  'tell of',
  'investigate',
  'look into',
  'write about',
  'commentate on',
  'write/give an account of',
  'publish/broadcast details of',
  'inquire into',
  'include',
  'involve',
  'take in',
  'contain',
  'comprise',
  'embrace',
  'embody',
  'incorporate',
  'subsume',
  'consider',
  'deal with',
  'provide for',
  'refer to',
  'bear on',
  'appertain',
  'pertain',
  'relate',
  'concern',
  'have to do with',
  'affect',
  'involve',
  'touch',
  'be relevant',
  'have relevance to',
  'have a bearing on',
  'be concerned with',
  'be pertinent',
  'be significant',
  'be apt',
  'be apposite',
  'be appropriate',
  'be fitting',
  'be germane',
  'deal with',
  'offset',
  'counterbalance',
  'balance',
  'make up for',
  'pay back',
  'pay',
  'fund',
  'finance',
  'make up',
  'cancel out',
  'pay for',
  'be enough for',
  'have enough money for',
  'provide for',
  'insure',
  'protect',
  'secure',
  'underwrite',
  'indemnify',
  'assure',
  'provide insurance for',
  'mask',
  'disguise',
  'obscure',
  'hide',
  'muffle',
  'stifle',
  'smother',
  'camouflage',
  'cloak',
  'veil',
  'shroud',
  'swathe',
  'secrete',
  'envelop',
  'enshroud',
  'stop something being overheard',
  'blot out',
  'sleeve',
  'wrapping',
  'wrapper',
  'covering',
  'envelope',
  'sheath',
  'sheathing',
  'housing',
  'jacket',
  'casing',
  'cowling',
  'awning',
  'tarpaulin',
  'lid',
  'top',
  'cap',
  'coating',
  'coat',
  'layer',
  'carpet',
  'blanket',
  'overlay',
  'topping',
  'dusting',
  'cloak',
  'mantle',
  'canopy',
  'film',
  'sheet',
  'veneer',
  'crust',
  'surface',
  'skim',
  'skin',
  'thickness',
  'deposit',
  'veil',
  'pall',
  'shroud',
  'binding',
  'case',
  'boards',
  'jacket',
  'dust jacket',
  'dust cover',
  'wrapper',
  'bedclothes',
  'bedding',
  'sheets',
  'blankets',
  'linen',
  'duvet',
  'quilt',
  'eiderdown',
  'bedspread',
  'counterpane',
  'shelter',
  'protection',
  'refuge',
  'hiding',
  'concealment',
  'housing',
  'sanctuary',
  'shield',
  'defense',
  'haven',
  'hiding place',
  'undergrowth',
  'vegetation',
  'shrubbery',
  'greenery',
  'ground cover',
  'underwood',
  'brushwood',
  'brush',
  'scrub',
  'woodland',
  'forest',
  'jungle',
  'bushes',
  'plants',
  'covert',
  'thicket',
  'copse',
  'coppice',
  'underbrush',
  'frith',
  'herbage',
  'verdure',
  'copsewood',
  'underscrub',
  'underbush',
  'shin-tangle',
  'rone',
  'front',
  'facade',
  'smokescreen',
  'screen',
  'blind',
  'deception',
  'camouflage',
  'disguise',
  'mask',
  'cloak',
  'pretext',
  'masquerade',
  'feint',
  'show',
  'semblance',
  'affectation',
  'appearance',
  'impression',
  'image',
  'front',
  'guise',
  'color',
  'facade',
  'display',
  'posture',
  'pose',
  'masquerade',
  'mask',
  'cloak',
  'veil',
  'veneer',
  'smokescreen',
  'camouflage',
  'travesty',
  'parody',
  'charade',
  'snivel',
  'false show',
  'false appearance',
  'outward appearance',
  'false front',
];