export const definitions = [
    '"she called on all her courage to face the ordeal"',
    '"he fought his illness with great courage"',
]
export const synonyms = [
    'bravery',
    'braveness',
    'courageousness',
    'pluck',
    'pluckiness',
    'valor',
    'fearlessness',
    'intrepidity',
    'intrepidness',
    'nerve',
    'daring',
    'audacity',
    'boldness',
    'dauntlessness',
    'doughtiness',
    'stout-heartedness',
    'hardihood',
    'manfulness',
    'heroism',
    'gallantry',
    'backbone',
    'spine',
    'spirit',
    'spiritedness',
    'mettle',
    'determination',
    'fortitude',
    'resolve',
    'resolution',
    'cowardice',
    'timidity',
]