export const definitions = [
  '"a cozy cabin tucked away in the trees"',
  '"a very cozy little chat"',
  '"a rather cozy assumption among automakers that they would never actually go bust"',
  '"a cozy deal"',
  '"the cozy crime story is about a group of elderly friends solving mysteries from their retirement village"',
  '"for those who can\'t stomach the reality of true crime, cozy fiction is having a moment"',
];
export const synonyms = [
  'snug',
  'comfortable',
  'warm',
  'restful',
  'home-like',
  'homey',
  'cheerful',
  'welcoming',
  'pleasant',
  'agreeable',
  'safe',
  'sheltered',
  'secure',
  'at ease',
  'mellow',
  'homely',
  'down-home',
  'homestyle',
  'uncomfortable',
  'intimate',
  'relaxed',
  'informal',
  'friendly',
];