export const definitions = [
    '"a cozy cabin tucked away in the trees"',
    '"a very cozy little chat"',
    '"a rather cozy assumption among automakers that they would never actually go bust"',
    '"a cozy deal"',
    '"the cozy crime story is about a group of elderly friends solving mysteries from their retirement village"',
    '"for those who can\'t stomach the reality of true crime, cozy fiction is having a moment"',
    '"a photograph of Smith pouring tea from a pot with a knitted cozy"',
    '"mug cozies are simple to make"',
    '"a handmade phone cozy"',
    '"crocheted tissue box cozies"',
    '"guests received beer cozies"',
    '"she cozied him, pretending to find him irresistibly attractive"',
    '"almost everyone loves to cozy up to a roaring fire"',
    '"I shall have a certain lovely lady to cozy up with"',
    '"he decided to resign rather than cozy up to hard-liners in the party"',
]
export const synonyms = [
    'snug',
    'comfortable',
    'warm',
    'restful',
    'home-like',
    'homey',
    'cheerful',
    'welcoming',
    'pleasant',
    'agreeable',
    'safe',
    'sheltered',
    'secure',
    'at ease',
    'mellow',
    'homely',
    'down-home',
    'homestyle',
    'uncomfortable',
    'intimate',
    'relaxed',
    'informal',
    'friendly',
]