export const definitions = [
    '"a crafty crook faked an injury to escape from prison"',
    '"he sneaked off to a toilet for a crafty fag"',
    '"a market full of crafty pots and interesting earrings"',
    '"they are looking for crafty people to join the group to make ornaments"',
]
export const synonyms = [
    'cunning',
    'guileful',
    'wily',
    'artful',
    'devious',
    'sly',
    'tricky',
    'duplicitous',
    'dishonest',
    'underhand',
    'cheating',
    'deceitful',
    'Janus-faced',
    'sharp',
    'scheming',
    'calculating',
    'designing',
    'evasive',
    'shrewd',
    'astute',
    'canny',
    'subtle',
    'honest',
    'naive',
]