export const definitions = [
    '"crappy wine"',
]
export const synonyms = [
    'substandard',
    'bad',
    'deficient',
    'defective',
    'faulty',
    'imperfect',
    'inferior',
    'mediocre',
    'abject',
    'appalling',
    'abysmal',
    'atrocious',
    'awful',
    'terrible',
    'dismal',
    'dreadful',
    'unsatisfactory',
    'low-grade',
    'second-rate',
    'third-rate',
    'jerry-built',
    'shoddy',
    'crude',
    'tinny',
    'trashy',
    'miserable',
    'wretched',
    'disappointing',
    'lamentable',
    'deplorable',
    'pitiful',
    'inadequate',
    'insufficient',
    'unacceptable',
    'execrable',
    'frightful',
    'direful',
    'egregious',
    'below standard',
    'below par',
    'superior',
    'unwell',
    'sick',
    'ailing',
    'poorly',
    'sickly',
    'peaky',
    'afflicted',
    'indisposed',
    'infirm',
    'liverish',
    'out of sorts',
    'bad',
    'in a bad way',
    'bedridden',
    'invalided',
    'valetudinarian',
    'queasy',
    'nauseous',
    'nauseated',
    'weak',
    'feeble',
    'frail',
    'diseased',
    'infected',
    'off colour',
    'queer',
    'seedy',
    'not (very) well',
    'not oneself',
    'not in good shape',
    'not up to par',
    'under/below par',
    'on the sick list',
    'well',
    'healthy',
]