export const definitions = [
    '"a program to give the infants the human touch they crave"',
    '"I must crave your indulgence"',
]
export const synonyms = [
    'set one\'s heart on',
    'seek',
    'desire',
    'want',
    'covet',
    'desiderate',
    'long for',
    'yearn for',
    'hunger for',
    'thirst for',
    'dream of',
    'aspire to',
    'have as one\'s aim',
    'have as \'s \'s goal',
    'be bent on',
    'hope for',
    'hanker after',
    'wish for',
    'sigh for',
    'pant for',
    'pine for',
    'lust after',
    'be athirst for',
    'be desirous of',
    'suspire for',
    'ask for',
    'request',
    'seek',
    'beg',
    'canvass',
    'call for',
    'drum up',
    'impetrate',
    'apply for',
    'put in for',
    'plead for',
    'sue for',
    'press for',
]