export const definitions = [
    '"the stairs creaked as she went up them"',
    '"the garden gate creaked open"',
    '"stock prices creaked to a mixed finish today"',
    '"the creak of a floorboard broke the silence"',
]
export const synonyms = [
    'squeak',
    'groan',
    'grate',
    'screech',
    'squeal',
    'grind',
    'jar',
    'rasp',
    'rub',
    'scrape',
    'complain',
    'grate',
    'grating',
    'creaking',
    'grind',
    'grinding',
    'jar',
    'jarring',
    'rasp',
    'rasping',
    'scratch',
    'scratching',
    'rub',
    'rubbing',
    'squeak',
    'squeaking',
    'screech',
    'screeching',
]