export const definitions = [
  '"he created a thirty-acre lake"',
  '"over 170 jobs were created"',
  '"divorce only created problems for children"',
  '"he was created a baronet"',
];
export const synonyms = [
  'generate',
  'produce',
  'design',
  'make',
  'fabricate',
  'fashion',
  'manufacture',
  'build',
  'construct',
  'erect',
  'do',
  'turn out',
  'originate',
  'invent',
  'initiate',
  'engender',
  'devise',
  'frame',
  'develop',
  'shape',
  'form',
  'mold',
  'forge',
  'concoct',
  'hatch',
  'establish',
  'found',
  'institute',
  'constitute',
  'inaugurate',
  'launch',
  'set up',
  'start',
  'organize',
  'build up',
  'bring into being',
  'put in place',
  'lay the foundations of',
  'get something going',
  'get something moving',
  'get something working',
  'dismantle',
  'bring about',
  'cause',
  'give rise to',
  'breed',
  'generate',
  'engender',
  'produce',
  'make',
  'make for',
  'prompt',
  'promote',
  'foster',
  'sow the seeds of',
  'stir up',
  'whip up',
  'inspire',
  'enkindle',
  'result in',
  'be the cause of',
  'lead to',
  'contribute to',
  'destroy',
  'appoint',
  'make',
  'invest',
  'name',
  'nominate',
  'designate',
  'install as',
];