export const definitions = [
    '"khaki trousers with knife-edge creases"',
    '"stubble lines the creases of his face"',
    '"he was caught in the crease without the puck"',
    '"he sank into the chair, careful not to crease his dinner jacket"',
    '"a small frown creased her forehead"',
    '"a bullet creased his thigh"',
]
export const synonyms = [
    'fold',
    'groove',
    'ridge',
    'furrow',
    'line',
    'ruck',
    'pleat',
    'tuck',
    'corrugation',
    'ruckle',
    'wrinkle',
    'line',
    'crinkle',
    'pucker',
    'laughter line',
    'crumple',
    'wrinkle',
    'crinkle',
    'rumple',
    'line',
    'pucker',
    'crimp',
    'gather',
    'furrow',
    'ruckle',
    'press',
    'iron',
    'fold',
    'corrugate',
    'pleat',
    'tuck',
    'scrunch up',
    'ruck up',
    'put a crease in',
    'press',
    'crumple',
]