export const definitions = [
    '"the creepy feelings one often gets in a strange house"',
]
export const synonyms = [
    'frightening',
    'scaring',
    'terrifying',
    'hair-raising',
    'spine-chilling',
    'blood-curdling',
    'chilling',
    'petrifying',
    'alarming',
    'shocking',
    'harrowing',
    'horrifying',
    'horrific',
    'horrible',
    'awful',
    'nightmarish',
    'macabre',
    'ghostly',
    'disturbing',
    'eerie',
    'sinister',
    'weird',
    'menacing',
    'ominous',
    'threatening',
    'eldritch',
    'relaxing',
    'pleasant',
]