export const definitions = [
  '"a large game bird with a conspicuous erect red crest"',
  '"she reached the crest of the hill"',
  '"biopsy specimens of the iliac crest were obtained under local anesthesia"',
  '"take hold of the mane halfway up the horse\'s crest"',
  '"a high wave formed by the meeting of two crests"',
  '"she crested a hill and saw the valley spread out before her"',
  '"the river was expected to crest at eight feet above flood stage"',
  '"the swell begins to curl and crest"',
  '"his helmet was crested with a fan of spikes"',
];
export const synonyms = [
  'comb',
  'plume',
  'tuft',
  'topknot',
  'mane',
  'aigrette',
  'panache',
  'tassel',
  'caruncle',
  'feather',
  'quill',
  'plumule',
  'pinion',
  'summit',
  'peak',
  'top',
  'mountaintop',
  'tip',
  'pinnacle',
  'brow',
  'crown',
  'head',
  'cap',
  'brink',
  'apex',
  'vertex',
  'apogee',
  'zenith',
  'ridge',
  'tor',
  'aiguille',
  'serac',
  'highest point',
  'bottom',
  'insignia',
  'regalia',
  'badge',
  'emblem',
  'ensign',
  'device',
  'coat of arms',
  'arms',
  'escutcheon',
  'shield',
  'bearing',
  'charge',
  'heraldic device',
  'armorial bearing',
  'climb',
  'scale',
  'ascend',
  'mount',
  'conquer',
  'reach the top of',
];