export const definitions = [
    '"I turned my head so quickly that I cricked my neck"',
]
export const synonyms = [
    'cramp',
    'spasm',
    'rick',
    'kink',
    'twinge',
    'pang',
    'pain',
    'ache',
    'stiffness',
    'discomfort',
    'tenderness',
    'soreness',
    'muscle spasm',
    'muscular contraction',
    'shooting pain',
    'strain',
    'sprain',
    'pull',
    'wrench',
    'tear',
    'twist',
    'rick',
    'injure',
    'hurt',
    'damage',
    'impair',
]