export const definitions = [
    '"shoplifting was a serious crime"',
    '"the victims of crime"',
    '"they condemned apartheid as a crime against humanity"',
    '"it\'s a crime to keep a creature like Willy in a tank"',
]
export const synonyms = [
    'offense',
    'misdemeanor',
    'misdeed',
    'wrong',
    'felony',
    'violation',
    'transgression',
    'fault',
    'injury',
    'malfeasance',
    'malefaction',
    'tort',
    'trespass',
    'unlawful act',
    'illegal act',
    'breach/violation/infraction of the law',
    'lawbreaking',
    'delinquency',
    'wrongdoing',
    'transgression',
    'misconduct',
    'criminality',
    'illegality',
    'villainy',
    'felony',
    'corruption',
    'malfeasance',
    'malefaction',
    'knavery',
    'malversation',
    'sin',
    'evil',
    'wrong',
    'wrongdoing',
    'atrocity',
    'abomination',
    'enormity',
    'disgrace',
    'outrage',
    'monstrosity',
    'violation',
    'abuse',
    'injustice',
    'affront',
    'immoral act',
    'evil action',
]