export const definitions = [
    '"use a good soap compound to remove accumulated crud"',
    '"there\'s no way I can ski crud"',
    '"the usual crud that passes itself off as a smart twenty-something comedy"',
    '"I\'m tired of this crud"',
]
export const synonyms = [
    'mud',
    'muck',
    'mire',
    'ooze',
    'silt',
    'alluvium',
    'dirt',
    'slime',
    'slush',
    'slurry',
    'sediment',
    'lees',
    'dregs',
    'deposit',
    'grounds',
    'precipitate',
    'residue',
    'slob',
    'grouts',
    'settlings',
    'clag',
    'clart',
    'rabble',
    'riffraff',
    'refuse',
    'garbage',
    'trash',
    'vermin',
    'good-for-nothing(s)',
    'undesirable(s)',
    'the lowest of the low',
    'dastard(s)',
    'despicable person/people',
    'the dregs of society',
    'trog(s)',
]