export const definitions = [
    '"she brushed some cake crumbs off her dress"',
    '"a crispy crumb topping"',
    '"a morsel of crumb will often tempt a chub"',
    '"apple crumb pie"',
    '"the Budget provided few crumbs of comfort"',
    '"a multi-billion dollar franchise and the family of the creator doesn\'t even get crumbs from the table"',
    '"endless scrabbling for crumbs from the public spending table is undermining morale"',
    '"he\'s an absolute crumb"',
    '"while the sweet potato is cooking, crumb the fish"',
]
export const synonyms = [
    'bit',
    'section',
    'slice',
    'chunk',
    'segment',
    'lump',
    'hunk',
    'wedge',
    'slab',
    'knob',
    'block',
    'cake',
    'bar',
    'tablet',
    'brick',
    'cube',
    'stick',
    'length',
    'sample',
    'particle',
    'fragment',
    'flake',
    'sliver',
    'splinter',
    'wafer',
    'chip',
    'grain',
    'speck',
    'scrap',
    'remnant',
    'shred',
    'shard',
    'snippet',
    'mite',
    'mouthful',
    'morsel',
    'offcut',
    'fragment',
    'bit',
    'morsel',
    'particle',
    'speck',
    'scrap',
    'shred',
    'sliver',
    'atom',
    'grain',
    'granule',
    'trace',
    'tinge',
    'mite',
    'iota',
    'jot',
    'whit',
    'ounce',
    'scintilla',
    'vestige',
    'soupçon',
    'scantling',
    'scruple',
    'tiny piece',
    'stim',
]