export const definitions = [
    '"people think you\'re cuckoo"',
]
export const synonyms = [
    'lunatic',
    'maniac',
    'psychotic',
    'psychopath',
    'schizophrenic',
    'insane',
    'mad',
    'certifiable',
    'deranged',
    'demented',
    'out of one\'s mind',
    'not in \'s \'s right mind',
    'crazed',
    'maniac',
    'maniacal',
    'lunatic',
    'unbalanced',
    'unhinged',
    'unstable',
    'disturbed',
    'distracted',
    'manic',
    'frenzied',
    'raving',
    'distraught',
    'frantic',
    'hysterical',
    'delirious',
    'non compos mentis',
    'sectionable',
    'psychotic',
    'sociopathic',
    'psychopathological',
    'severely mentally ill',
    'mentally ill',
    'of unsound mind',
    'not together',
    'stark mad',
    'mad as a hatter',
    'mad as a March hare',
]