export const definitions = [
    '"they would lie in wait and cudgel her to death"',
]
export const synonyms = [
    'club',
    'bludgeon',
    'stick',
    'truncheon',
    'baton',
    'blackthorn',
    'mace',
    'bat',
    'blackjack',
    'billy',
    'billy club',
    'nightstick',
    'shillelagh',
    'lathi',
    'knobkerrie',
    'danda',
    'kierie',
    'bludgeon',
    'club',
    'beat',
    'batter',
    'bash',
    'attack',
    'assault',
]