export const definitions = [
  '"the dollar was a strong currency"',
  '"travelers checks in foreign currency"',
  '"he was rich in the currency of love"',
  '"the term gained currency during the second half of the 20th century"',
  '"no claim had been made during the currency of the policy"',
];
export const synonyms = [
  'money',
  'legal tender',
  'cash',
  'banknotes',
  'notes',
  'paper money',
  'coins',
  'coinage',
  'bills',
  'specie',
  'medium of exchange',
  'prevalence',
  'circulation',
  'dissemination',
  'publicity',
  'exposure',
  'acceptance',
  'popularity',
  'traction',
  'fashionableness',
  'voguishness',
];