export const definitions = [
    '"she promised she would curb her temper"',
    '"both men were instinctively curbing their horses"',
]
export const synonyms = [
    'restrain',
    'hold back',
    'keep back',
    'hold in',
    'repress',
    'suppress',
    'fight back',
    'bite back',
    'check',
    'control',
    'keep a tight rein on',
    'contain',
    'discipline',
    'govern',
    'bridle',
    'tame',
    'subdue',
    'stifle',
    'smother',
    'swallow',
    'choke back',
    'muzzle',
    'silence',
    'muffle',
    'strangle',
    'gag',
    'limit',
    'slow down',
    'retard',
    'restrict',
    'constrain',
    'deter',
    'impede',
    'inhibit',
    'freeze',
    'peg',
    'trammel',
    'keep in check',
    'keep under control',
    'rein in',
    'put a limit on',
    'keep within bounds',
    'put the brakes on',
    'release',
]