export const definitions = [
  '"civil liberties were further curtailed"',
  '"I that am curtailed of this fair proportion"',
];
export const synonyms = [
  'reduce',
  'cut',
  'cut down',
  'cut back',
  'decrease',
  'lessen',
  'diminish',
  'retrench',
  'trim',
  'dock',
  'lop',
  'shrink',
  'shorten',
  'break off',
  'truncate',
  'restrict',
  'limit',
  'curb',
  'slim down',
  'tighten up',
  'pare down',
  'cut short',
  'put a restriction on',
  'put a limit on',
  'put the brakes on',
  'rein in',
  'rein back',
  'increase',
  'lengthen',
];