definitions: [
    '"the old English custom of dancing around the maypole"',
    '"custom demanded that a person should have gifts for the child"',
    '"it was my custom to nap for an hour every day"',
    '"if you keep me waiting, I will take my custom elsewhere"',
    '"a custom guitar"',
]
synonyms: [
    'tradition',
    'practice',
    'usage',
    'observance',
    'way',
    'convention',
    'procedure',
    'ceremony',
    'ritual',
    'ordinance',
    'form',
    'formality',
    'fashion',
    'mode',
    'manner',
    'shibboleth',
    'sacred cow',
    'mores',
    'consuetude',
    'praxis',
    'unwritten rule',
    'way of doing things',
    'habit',
    'practice',
    'routine',
    'way',
    'wont',
    'policy',
    'rule',
    'habitude',
    'business',
    'patronage',
    'trade',
    'support',
]
