export const definitions = [
    '"a cute kitten"',
    '"the baby was so cute"',
    '"Ryan\'s cute but he\'s kinda young"',
    '"a cute guy"',
    '"I don\'t want to be cute with you"',
]
export const synonyms = [
    'endearing',
    'adorable',
    'lovable',
    'sweet',
    'lovely',
    'appealing',
    'engaging',
    'delightful',
    'dear',
    'darling',
    'winning',
    'winsome',
    'charming',
    'enchanting',
    'attractive',
    'pretty',
    'as pretty as a picture',
    'bonny',
    'chocolate-box',
    'unattractive',
    'unappealing',
    'shrewd',
    'astute',
    'sharp',
    'acute',
    'quick',
    'sharp-witted',
    'quick-witted',
    'ingenious',
    'resourceful',
    'canny',
    'cunning',
    'crafty',
    'artful',
    'wily',
    'slick',
    'neat',
    'ill-advised',
    'foolish',
]