export const definitions = [
    '"don\'t ask such daft questions"',
    '"I find some of the ideas a bit daft"',
    '"we can\'t stop laughing at their daft antics"',
    '"we were all daft about him"',
]
export const synonyms = [
    'absurd',
    'preposterous',
    'ridiculous',
    'ludicrous',
    'farcical',
    'laughable',
    'risible',
    'idiotic',
    'stupid',
    'foolish',
    'foolhardy',
    'unwise',
    'imprudent',
    'ill-conceived',
    'silly',
    'inane',
    'puerile',
    'infantile',
    'fatuous',
    'imbecilic',
    'harebrained',
    'half-baked',
    'unreasonable',
    'irrational',
    'illogical',
    'nonsensical',
    'pointless',
    'senseless',
    'impracticable',
    'unworkable',
    'unrealistic',
    'peculiar',
    'odd',
    'strange',
    'queer',
    'weird',
    'eccentric',
    'bizarre',
    'fantastic',
    'incongruous',
    'grotesque',
    'simpleminded',
    'simple',
    'moronic',
    'dull-witted',
    'dull',
    'dimwitted',
    'slow-witted',
    'slow',
    'witless',
    'halfwitted',
    'feebleminded',
    'cretinous',
    'empty-headed',
    'vacuous',
    'vapid',
    'deranged',
    'unhinged',
    'insane',
    'mad',
    'dunce-like',
    'sensible',
    'infatuated with',
    'enamored of',
    'obsessed by',
    'smitten with',
    'besotted by',
    'doting on',
    'very fond of',
]