definitions: [
    '"bombing caused extensive damage to the town"',
    '"the damage to his reputation was considerable"',
    '"she was awarded $284,000 in damages"',
    '"the car was badly damaged in the accident"',
    '"damaged ligaments"',
    '"the scandal could seriously damage his career"',
]
synonyms: [
    'harm',
    'injury',
    'destruction',
    'vandalism',
    'impairment',
    'defilement',
    'desecration',
    'defacement',
    'disfigurement',
    'scarring',
    'mutilation',
    'vitiation',
    'detriment',
    'ruin',
    'havoc',
    'devastation',
    'battering',
    'friction',
    'erosion',
    'attrition',
    'corrosion',
    'abrasion',
    'deterioration',
    'degeneration',
    'detrition',
    'vandalization',
    'wear and tear',
    'compensation',
    'recompense',
    'restitution',
    'redress',
    'reparation(s)',
    'repayment',
    'reimbursement',
    'remuneration',
    'requital',
    'indemnification',
    'indemnity',
    'satisfaction',
    'guerdon',
    'meed',
    'solatium',
    'harm',
    'injure',
    'mar',
    'deface',
    'mutilate',
    'mangle',
    'impair',
    'blemish',
    'disfigure',
    'vandalize',
    'blight',
    'spoil',
    'defile',
    'desecrate',
    'sabotage',
    'disrupt',
    'play havoc with',
    'vitiate',
    'ruin',
    'devastate',
    'destroy',
    'wreck',
    'cripple',
    'do damage to',
    'tamper with',
    'drive a nail into the coffin of',
    'disfeature',
    'repair',
    'improve',
]