definitions: [
    '"their cheeks were pressed together as they danced"',
    '"all the men wanted her to dance with them"',
    '"they danced a tango"',
    '"I danced her out of the room"',
    '"Sheila danced in gaily"',
    '"midges danced over the stream"',
    '"she could see flames dancing in the fireplace"',
    '"he grinned, his gray eyes dancing"',
]
synonyms: [
    'trip',
    'sway',
    'spin',
    'whirl',
    'twirl',
    'pirouette',
    'gyrate',
    'foot it',
    'tread a measure',
    'trip',
    'sway',
    'spin',
    'whirl',
    'twirl',
    'pirouette',
    'gyrate',
    'foot it',
    'tread a measure',
    'caper',
    'cavort',
    'frisk',
    'frolic',
    'skip',
    'prance',
    'romp',
    'gambol',
    'jig',
    'bound',
    'leap',
    'jump',
    'spring',
    'bob',
    'hop',
    'trip',
    'bounce',
    'rollick',
    'flicker',
    'sparkle',
    'twinkle',
    'shimmer',
    'leap',
    'ripple',
    'dart',
    'play',
    'flick',
    'flit',
    'quiver',
    'jiggle',
    'joggle',
    'oscillate',
]