export const definitions = [
  '"his life was in ______"',
  '"infertile soils where drought is a ______"',
  '"there was no ______ of the champagne running out"',
  '"one of the trains involved passed a signal at ______"',
];
export const synonyms = [
  'peril',
  'hazard',
  'risk',
  'jeopardy',
  'endangerment',
  'imperilment',
  'insecurity',
  'perilousness',
  'riskiness',
  'precariousness',
  'uncertainty',
  'instability',
  'safety',
  'menace',
  'hazard',
  'threat',
  'risk',
  'peril',
  'source of apprehension',
  'source of dread',
  'source of fright',
  'source of fear',
  'source of terror',
  'possibility',
  'chance',
  'risk',
  'probability',
  'likelihood',
  'fear',
  'prospect',
];