export const definitions = [
    '"the sky was darkening rapidly"',
    '"darken the eyebrows with black powder"',
    '"his mood darkened"',
    '"the abuse darkened the rest of their lives"',
    '"his face darkened and he lunged away"',
    '"misery darkened her gaze"',
]
export const synonyms = [
    'blacken',
    'dim',
    'lour',
    'shade',
    'eclipse',
    'fog',
    'obscure',
    'grow dark/darker',
    'grow black/blacker',
    'grow dim',
    'cloud over',
    'make dark/darker',
    'make black/blacker',
    'make dim',
    'lighten',
    'cast down',
    'deject',
    'weigh down',
    'oppress',
    'blacken',
    'sadden',
    'spoil',
    'mar',
    'make/become gloomy',
    'make/become angry',
    'make/become unhappy',
    'make/become annoyed',
    'make/become depressed',
    'become cast down',
    'become dejected',
    'dampen the spirits of',
    'make/become dispirited',
    'make/become troubled',
    'cast a pall over',
    'look black',
    'detract from',
]