export const definitions = [
  '"she darted across the street"',
  '"she darted a glance across the table"',
  '"he darted the leopard with a long-acting anesthetic"',
  '"he darted his fierce iron"',
];
export const synonyms = [
  'scurry',
  'scuttle',
  'run',
  'rush',
  'dash',
  'race',
  'sprint',
  'hurry',
  'hasten',
  'make haste',
  'romp',
  'frolic',
  'gambol',
  'scutter',
  'direct',
  'cast',
  'throw',
  'shoot',
  'send',
  'fling',
  'toss',
  'flash',
  'bestow',
  'give',
];