export const definitions = [
  '"I ______ into the garden"',
  '"the ship was ______ upon the rocks"',
  '"a gust of rain ______ against the bricks"',
  '"the budget ______ hopes of an increase in funding"',
];
export const synonyms = [
  'damned',
  'damn',
  'damnable',
  'wretched',
  'accursed',
  'rotten',
  'horrible',
  'annoying',
  'irritating',
  'infuriating',
  'exasperating',
  'rush',
  'race',
  'run',
  'sprint',
  'bolt',
  'dart',
  'gallop',
  'career',
  'charge',
  'shoot',
  'hurtle',
  'hare',
  'bound',
  'fly',
  'speed',
  'streak',
  'zoom',
  'plunge',
  'dive',
  'whisk',
  'scurry',
  'scuttle',
  'scamper',
  'scramble',
  'fleet',
  'post',
  'hie',
  'haste',
  'dawdle',
  'hurl',
  'smash',
  'crash',
  'slam',
  'throw',
  'toss',
  'fling',
  'pitch',
  'cast',
  'lob',
  'launch',
  'flip',
  'catapult',
  'shy',
  'aim',
  'direct',
  'project',
  'propel',
  'send',
  'bowl',
  'crash',
  'smash',
  'batter',
  'strike',
  'beat',
  'pound',
  'pummel',
  'lash',
  'be hurled',
  'slam into',
  'shatter',
  'destroy',
  'wreck',
  'ruin',
  'crush',
  'devastate',
  'demolish',
  'blast',
  'blight',
  'wipe out',
  'overturn',
  'torpedo',
  'scotch',
  'spoil',
  'frustrate',
  'thwart',
  'balk',
  'check',
  'burst someone\'s bubble',
  'bring to naught',
  'wreak havoc with',
  'raise',
  'depress',
  'dispirit',
  'dishearten',
  'grieve',
  'desolate',
  'discourage',
  'upset',
  'get down',
  'bring down',
  'cast down',
  'break someone\'s heart',
  'deject',
  'dampen someone\'s spirits',
  'cast a gloom on',
  'bring tears to someone\'s eyes',
  'make someone\'s heart bleed',
  'cheer up',
];
