export const definitions = [
    '"I dashed into the garden"',
    '"I must dash, I\'m late"',
    '"the ship was dashed upon the rocks"',
    '"a gust of rain dashed against the bricks"',
    '"the budget dashed hopes of an increase in funding"',
    '"I won\'t tell Stuart—I think he\'d be dashed"',
    '"she made a dash for the door"',
    '"a 20-mile dash to the airport"',
    '"the 100-yard dash"',
    '"whiskey with a dash of soda"',
    '"a casual atmosphere with a dash of sophistication"',
    '"he has youthful energy, dash, and charisma"',
    '"an indicator on the dash tells you what gear you are in"',
]
export const synonyms = [
    'rush',
    'race',
    'run',
    'sprint',
    'bolt',
    'dart',
    'gallop',
    'career',
    'charge',
    'shoot',
    'hurtle',
    'hare',
    'bound',
    'fly',
    'speed',
    'streak',
    'zoom',
    'plunge',
    'dive',
    'whisk',
    'scurry',
    'scuttle',
    'scamper',
    'scramble',
    'fleet',
    'post',
    'hie',
    'haste',
    'dawdle',
    'hurl',
    'smash',
    'crash',
    'slam',
    'throw',
    'toss',
    'fling',
    'pitch',
    'cast',
    'lob',
    'launch',
    'flip',
    'catapult',
    'shy',
    'aim',
    'direct',
    'project',
    'propel',
    'send',
    'bowl',
    'crash',
    'smash',
    'batter',
    'strike',
    'beat',
    'pound',
    'pummel',
    'lash',
    'be hurled',
    'slam into',
    'shatter',
    'destroy',
    'wreck',
    'ruin',
    'crush',
    'devastate',
    'demolish',
    'blast',
    'blight',
    'wipe out',
    'overturn',
    'torpedo',
    'scotch',
    'spoil',
    'frustrate',
    'thwart',
    'balk',
    'check',
    'burst someone\'s bubble',
    'bring to naught',
    'wreak havoc with',
    'raise',
    'depress',
    'dispirit',
    'dishearten',
    'grieve',
    'desolate',
    'discourage',
    'upset',
    'get down',
    'bring down',
    'cast down',
    'break someone\'s heart',
    'deject',
    'dampen someone\'s spirits',
    'cast a gloom on',
    'bring tears to someone\'s eyes',
    'make someone\'s heart bleed',
    'cheer up',
    'rush',
    'race',
    'run',
    'sprint',
    'bolt',
    'dart',
    'leap',
    'charge',
    'plunge',
    'dive',
    'bound',
    'break',
    'scamper',
    'scramble',
    'stampede',
    'drop',
    'splash',
    'dribble',
    'trickle',
    'spot',
    'hint',
    'touch',
    'bit',
    'few drops',
    'touch',
    'sprinkle',
    'pinch',
    'taste',
    'lick',
    'spot',
    'drop',
    'dab',
    'speck',
    'smack',
    'smattering',
    'sprinkling',
    'splash',
    'dribble',
    'trickle',
    'grain',
    'soupçon',
    'trace',
    'bit',
    'modicum',
    'little',
    'suggestion',
    'suspicion',
    'hint',
    'scintilla',
    'tinge',
    'tincture',
    'whiff',
    'whisper',
    'overtone',
    'undertone',
    'nuance',
    'coloring',
    'small amount',
    'lashings',
    'verve',
    'style',
    'stylishness',
    'flamboyance',
    'gusto',
    'zest',
    'confidence',
    'self-assurance',
    'elan',
    'flair',
    'flourish',
    'vigor',
    'vivacity',
    'vivaciousness',
    'sparkle',
    'brio',
    'panache',
    'éclat',
    'exuberance',
    'ebullience',
    'enthusiasm',
    'eagerness',
    'vitality',
    'dynamism',
    'animation',
    'liveliness',
    'spirit',
    'energy',
    'ineptitude',
    'apathy',
]