export const definitions = [
    '"they date the paintings to 1460–70"',
    '"sign and date the document"',
    '"the controversy dates back to 1986"',
    '"disco—that word alone dates me"',
    '"a movie that will date quickly"',
    '"a few years ago, I dated the ex of a friend"',
    '"they have been dating for more than a year"',
]
export const synonyms = [
    'carbon-date',
    'assign a date to',
    'establish/determine/ascertain the date of',
    'put a date on/to',
    'establish/determine/ascertain the age of',
    'become old-fashioned',
    'become outmoded',
    'become obsolete',
    'become dated',
    'show its age',
    'was made in',
    'was built in',
    'was created in',
    'came into being in',
    'bears the date of',
    'originates in',
    'comes from',
    'belongs to',
    'goes back to',
    'has existed since',
    'old-fashioned',
    'out of fashion',
    'out of date',
    'outdated',
    'outmoded',
    'behind the times',
    'superseded',
    'archaic',
    'obsolete',
    'antiquated',
    'unfashionable',
    'unpopular',
    'unstylish',
    'bygone',
    'oldfangled',
    'crusty',
    'prehistoric',
    'antediluvian',
    'passé',
    'démodé',
    'out of style',
    'last year\'s',
    'olde worlde',
    'become old-fashioned',
    'become outmoded',
    'become obsolete',
    'become dated',
    'show its age',
    'modern',
    'up to date',
    'take out',
    'go around with',
    'go with',
    'see',
    'court',
    'woo',
    'go out with',
    'be involved with',
    'be romantically linked with',
]