export const definitions = [
  '"Thursday dawned bright and sunny"',
  '"a new era of land-use policy was dawning"',
  '"the awful truth was beginning to dawn on him"',
];
export const synonyms = [
  'begin',
  'open',
  'break',
  'arrive',
  'emerge',
  'lighten',
  'brighten',
  'grow light',
  'end',
  'begin',
  'start',
  'appear',
  'arrive',
  'emerge',
  'erupt',
  'arise',
  'rise',
  'originate',
  'break',
  'unfold',
  'develop',
  'crop up',
  'commence',
  'come into being',
  'be born',
  'come into existence',
  'come forth',
  'burst out',
  'first see the light of day',
  'end',
  'come to',
  'come to mind',
  'strike',
  'hit',
  'occur to',
  'spring to mind',
  'enter someone\'s mind / head',
  'come into some\'s \'s head / mind',
  'register with',
  'enter someone\'s consciousness',
  'flash across some\'s \'s mind',
  'pass through some\'s \'s mind',
  'cross some\'s \'s mind',
  'suggest itself',
];