export const definitions = [
  '"a dead body"',
  '"he has been dead for many years"',
  '"he was shot dead by a sniper"',
  '"there was no time to bury the dead with decency"',
  '"I severed nerves in my leg so part of my foot is dead"',
  '"a cold, dead voice"',
  '"a dead planet"',
  '"Brussels isn\'t dead after dark, if you know where to look"',
  '"the phone had gone dead"',
  '"the batteries are dead"',
  '"the fire had been dead for some days"',
  '"the ball had gone dead"',
  '"they got all the dead glasses and put them on the table"',
  '"pollution had become a dead issue"',
  '"far from being dead money, it is available to be spent or invested"',
  '"the note sounds dead compared to all others on the keyboard"',
  '"higher up, the marble becomes of a dull, dead color"',
  '"we sat in dead silence"',
];
export const synonyms = [
  'deceased',
  'expired',
  'departed',
  'gone',
  'no more',
  'late',
  'lost',
  'lamented',
  'perished',
  'fallen',
  'slain',
  'slaughtered',
  'killed',
  'murdered',
  'lifeless',
  'defunct',
  'extinct',
  'inanimate',
  'insentient',
  'insensate',
  'inert',
  'demised',
  'exanimate',
  'passed on',
  'passed away',
  'not breathing',
  'having breathed one\'s last',
  'alive',
  'living',
  'numb',
  'benumbed',
  'deadened',
  'desensitized',
  'insensible',
  'insensate',
  'unfeeling',
  'paralyzed',
  'incapacitated',
  'immobilized',
  'frozen',
  'useless',
  'emotionless',
  'unemotional',
  'unfeeling',
  'impassive',
  'unresponsive',
  'insensitive',
  'indifferent',
  'dispassionate',
  'inexpressive',
  'wooden',
  'stony',
  'cold',
  'frigid',
  'inert',
  'deadpan',
  'flat',
  'toneless',
  'hollow',
  'blank',
  'vacant',
  'glazed',
  'glassy',
  'passionate',
  'barren',
  'lifeless',
  'bare',
  'empty',
  'desolate',
  'sterile',
  'without life',
  'without living things',
  'fertile',
  'lush',
  'uneventful',
  'uninteresting',
  'unexciting',
  'uninspiring',
  'dull',
  'boring',
  'flat',
  'quiet',
  'sleepy',
  'slow',
  'stale',
  'humdrum',
  'tame',
  'pedestrian',
  'lackluster',
  'lifeless',
  'tedious',
  'tiresome',
  'wearisome',
  'backward',
  'backwoods',
  'behind the times',
  'lively',
  'out of order',
  'out of commission',
  'inoperative',
  'inactive',
  'ineffective',
  'broken',
  'broken-down',
  'malfunctioning',
  'defective',
  'not working',
  'in (a state of) disrepair',
  'in working order',
  'barren',
  'lifeless',
  'bare',
  'empty',
  'desolate',
  'sterile',
  'without life',
  'without living things',
  'fertile',
  'lush',
  'complete',
  'absolute',
  'total',
  'entire',
  'outright',
  'utter',
  'downright',
  'out-and-out',
  'thorough',
  'unqualified',
  'unmitigated',
  'partial',
];