export const definitions = [
  '"ether was used to deaden the pain"',
  '"diabetes can deaden the nerve endings"',
  '"the syllabus has deadened the teaching process"',
  '"laughter might deaden us to the moral issue"',
];
export const synonyms = [
  'numb',
  'stifle',
  'dull',
  'blunt',
  'suppress',
  'alleviate',
  'mitigate',
  'moderate',
  'weaken',
  'diminish',
  'reduce',
  'decrease',
  'lessen',
  'palliate',
  'abate',
  'ease',
  'soothe',
  'relieve',
  'assuage',
  'subdue',
  'take the edge off',
  'get rid of',
  'put an end to',
  'muffle',
  'mute',
  'smother',
  'damp',
  'tone down',
  'hush',
  'silence',
  'quieten',
  'soften',
  'cushion',
  'blanket',
  'buffer',
  'absorb',
  'quiet',
  'damp down',
  'intensify',
  'amplify',
  'desensitize',
  'numb',
  'benumb',
  'anesthetize',
  'harden',
  'toughen',
  'render insensitive',
  'make insensitive',
  'harden someone\'s heart',
  'sensitize',
];