export const definitions = [
    '"there is a dearth of evidence"',
]
export const synonyms = [
    'lack',
    'scarcity',
    'scarceness',
    'shortage',
    'shortfall',
    'want',
    'deficiency',
    'insufficiency',
    'inadequacy',
    'paucity',
    'sparseness',
    'meagerness',
    'scantiness',
    'rareness',
    'infrequency',
    'uncommonness',
    'destitution',
    'privation',
    'famine',
    'drought',
    'poverty',
    'absence',
    'nonexistence',
    'exiguity',
    'exiguousness',
    'abundance',
    'surfeit',
]