export const definitions = [
    '"a dear friend"',
    '"he is very dear to me"',
    '"Martin, my dear fellow"',
    '"Dear Sir or Madam"',
    '"a dear little puppy"',
]
export const synonyms = [
    'beloved',
    'loved',
    'darling',
    'adored',
    'cherished',
    'precious',
    'esteemed',
    'respected',
    'worshipped',
    'close',
    'intimate',
    'confidential',
    'bosom',
    'boon',
    'favorite',
    'best',
    'treasured',
    'valued',
    'prized',
    'special',
    'favored',
    'much loved',
    'hated',
    'beloved',
    'loved',
    'darling',
    'adored',
    'cherished',
    'precious',
    'esteemed',
    'respected',
    'worshipped',
    'close',
    'intimate',
    'confidential',
    'bosom',
    'boon',
    'favorite',
    'best',
    'much loved',
    'hated',
    'endearing',
    'adorable',
    'lovable',
    'appealing',
    'engaging',
    'charming',
    'enchanting',
    'captivating',
    'winsome',
    'winning',
    'attractive',
    'lovely',
    'nice',
    'pleasant',
    'delightful',
    'angelic',
    'sweet',
    'darling',
    'cunning',
    'simpatico',
    'taking',
    'sympathique',
    'sympatisch',
    'disagreeable',
    'expensive',
    'costly',
    'high-priced',
    'overpriced',
    'exorbitant',
    'extortionate',
    'immoderate',
    'extravagant',
    'lavish',
    'valuable',
    'upmarket',
    'high-cost',
    'highly priced',
    'big-budget',
    'over the odds',
    'inexpensive',
]