export const definitions = [
    '"an increase in deaths from skin cancer"',
    '"I don\'t believe in life after death"',
    '"a death sentence"',
    '"even in death, she was beautiful"',
    '"the death of her hopes"',
    '"to be driven to a dance by one\'s father would be social death"',
]
export const synonyms = [
    'demise',
    'dying',
    'end',
    'passing',
    'expiry',
    'expiration',
    'murder',
    'killing',
    'assassination',
    'execution',
    'dispatch',
    'slaying',
    'slaughter',
    'massacre',
    'decease',
    'quietus',
    'passing away',
    'passing on',
    'loss of life',
    'departure from life',
    'final exit',
    'eternal rest',
    'life',
    'the Grim Reaper',
    'the Dark Angel',
    'the Angel of Death',
    'end',
    'finish',
    'cessation',
    'termination',
    'extinction',
    'extinguishing',
    'collapse',
    'ruin',
    'ruination',
    'destruction',
    'extermination',
    'eradication',
    'annihilation',
    'obliteration',
    'extirpation',
    'birth',
]
