export const definitions = [
  '"last night\'s debate on the Education Bill"',
  '"the national debate on education"',
  '"there has been much debate about prices"',
  '"the board debated his proposal"',
  '"the date when people first entered America is hotly debated"',
  '"he debated whether he should leave the matter alone or speak to her"',
];
export const synonyms = [
  'discussion',
  'discourse',
  'parley',
  'argument',
  'dispute',
  'wrangle',
  'altercation',
  'war of words',
  'arguing',
  'argumentation',
  'wrangling',
  'sparring',
  'disputation',
  'dissension',
  'disagreement',
  'controversy',
  'contention',
  'conflict',
  'disharmony',
  'negotiations',
  'talks',
  'dialogue',
  'comment',
  'interest',
  'contestation',
  'exchange of views',
  'velitation',
  'argument',
  'quarrel',
  'wrangle',
  'squabble',
  'altercation',
  'dispute',
  'disputation',
  'war of words',
  'contretemps',
  'misunderstanding',
  'discord',
  'strife',
  'conflict',
  'bickering',
  'sparring',
  'contention',
  'dissension',
  'disharmony',
  'discuss',
  'talk over',
  'talk through',
  'talk about',
  'thrash out',
  'argue',
  'dispute',
  'contest',
  'controvert',
  'moot',
  'altercate',
  'confer about',
  'exchange views on',
  'exchange views about',
  'argue about',
  'argue the pros and cons of',
  'wrangle over',
  'bandy words concerning',
  'contend over',
  'consider',
  'think over',
  'think about',
  'chew over',
  'weigh up',
  'ponder',
  'deliberate',
  'reflect',
  'contemplate',
  'muse',
  'meditate',
  'cogitate',
  'cerebrate',
  'give some thought to',
  'mull over',
  'turn over in one\'s mind',
  'pore on',
];