definitions: [
    '"the bomb hits it, showering debris from all sides"',
    '"clean away any collected dust or debris"',
    '"a stable arrangement of planets, comets, and debris orbiting the sun"',
]
synonyms: [
    'detritus',
    'refuse',
    'waste',
    'litter',
    'scrap',
    'dross',
    'chaff',
    'flotsam and jetsam',
    'lumber',
    'rubble',
    'wreckage',
    'spoilage',
    'remains',
    'remnants',
    'fragments',
    'scraps',
    'dregs',
    'offscourings',
    'odds and ends',
    'slag',
    'rubbish',
    'trash',
    'garbage',
    'draff',
    'raffle',
    'cultch',
    'orts',
    'waste matter',
    'discarded matter',
    'mullock',
    'debitage',
    'raff',
]