export const definitions = [
  '"the good name of such a decent and innocent person"',
  '"they would meet again after a decent interval"',
  '"a decent high-necked dress"',
  '"make yourself decent"',
  '"people need decent homes"',
  '"find me a decent cup of coffee"',
  '"the deer are small: a 14-inch spread is a pretty decent buck"',
  '"that was pretty awfully decent of him"',
];
export const synonyms = [
  'respectable',
  'upright',
  'upstanding',
  'honorable',
  'honest',
  'on the level',
  'right-minded',
  'law-abiding',
  'conventional',
  'conservative',
  'traditional',
  'conformist',
  'old-fashioned',
  'strait-laced',
  'unadventurous',
  'proper',
  'correct',
  'appropriate',
  'apt',
  'apposite',
  'fitting',
  'fit',
  'befitting',
  'right',
  'suitable',
  'respectable',
  'dignified',
  'becoming',
  'decorous',
  'seemly',
  'modest',
  'nice',
  'tasteful',
  'refined',
  'genteel',
  'conventional',
  'accepted',
  'approved',
  'standard',
  'traditional',
  'orthodox',
  'comme il faut',
  'in good taste',
  'indecent',
  'satisfactory',
  'reasonable',
  'fair',
  'acceptable',
  'adequate',
  'sufficient',
  'ample',
  'up to scratch',
  'up to the mark',
  'up to par',
  'competent',
  'not bad',
  'all right',
  'average',
  'tolerable',
  'passable',
  'suitable',
  'sufficiently good',
  'good enough',
  'up to standard',
  'unsatisfactory',
  'honorable',
  'honest',
  'trustworthy',
  'dependable',
  'worthy',
  'respectable',
  'upright',
  'incorrupt',
  'virtuous',
  'good',
  'ethical',
  'moral',
  'obliging',
  'helpful',
  'accommodating',
  'indulgent',
  'unselfish',
  'altruistic',
  'generous',
  'kind',
  'kindly',
  'thoughtful',
  'considerate',
  'courteous',
  'civil',
  'polite',
  'well mannered',
  'neighborly',
  'hospitable',
  'pleasant',
  'agreeable',
  'amiable',
  'mannerly',
  'regardful',
  'clean-living',
  'disobliging',
  'dishonest',
];