export const definitions = [
  '"a web of deceit"',
  '"a series of lies and deceits"',
];
export const synonyms = [
  'deception',
  'deceitfulness',
  'duplicity',
  'double-dealing',
  'fraud',
  'fraudulence',
  'cheating',
  'trickery',
  'duping',
  'hoodwinking',
  'chicanery',
  'underhandedness',
  'deviousness',
  'slyness',
  'cunning',
  'craftiness',
  'craft',
  'wiliness',
  'artfulness',
  'guile',
  'dissimulation',
  'dissembling',
  'bluff',
  'bluffing',
  'lying',
  'pretense',
  'artifice',
  'treachery',
  'management',
  'knavery',
  'sham',
  'imposture',
  'hoax',
  'fake',
  'misrepresentation',
  'blind',
  'wile',
  'Trojan horse',
  'trick',
  'stratagem',
  'device',
  'ruse',
  'scheme',
  'dodge',
  'maneuver',
  'contrivance',
  'machination',
  'subterfuge',
  'cheat',
  'swindle',
  'confidence trick',
  'shift',
  'fetch',
  'rig',
  'honesty',
];