export const definitions = [
  '"a decoy duck"',
  '"we need a decoy to distract their attention"',
  '"they would try to decoy the enemy toward the hidden group"',
];
export const synonyms = [
  'lure',
  'bait',
  'red herring',
  'enticement',
  'inducement',
  'temptation',
  'attraction',
  'allurement',
  'draw',
  'carrot',
  'ensnarement',
  'entrapment',
  'snare',
  'trap',
  'pitfall',
  'ambush',
  'lure',
  'entice',
  'induce',
  'inveigle',
  'ensnare',
  'tempt',
  'seduce',
  'entrap',
  'snare',
  'trap',
];