export const definitions = [
  '"the decree guaranteed freedom of assembly"',
  '"presidential decrees"',
  '"the king ruled by decree"',
  '"the president decreed that the military was to be streamlined"',
  '"they decreed a ban on smoking in public places"',
];
export const synonyms = [
  'order',
  'edict',
  'command',
  'commandment',
  'mandate',
  'proclamation',
  'dictum',
  'fiat',
  'promulgation',
  'precept',
  'law',
  'statute',
  'act',
  'bill',
  'ordinance',
  'regulation',
  'rule',
  'injunction',
  'enactment',
  'manifesto',
  'ukase',
  'pronunciamento',
  'firman',
  'decretal',
  'rescript',
  'irade',
  'judgment',
  'verdict',
  'adjudication',
  'ruling',
  'rule',
  'resolution',
  'arbitration',
  'decision',
  'conclusion',
  'findings',
  'order',
  'command',
  'rule',
  'dictate',
  'lay down',
  'prescribe',
  'pronounce',
  'proclaim',
  'ordain',
  'enact',
  'adjudge',
  'enjoin',
  'direct',
  'decide',
  'determine',
];