export const definitions = [
    '"the event was deemed a great success"',
    '"the strike was deemed to be illegal"',
]
export const synonyms = [
    'consider',
    'judge',
    'adjudge',
    'count',
    'rate',
    'find',
    'esteem',
    'gauge',
    'suppose',
    'reckon',
    'account',
    'think',
    'regard as',
    'hold to be',
    'look on as',
    'view as',
    'see as',
    'take to be',
    'take for',
    'class as',
    'estimate as',
    'calculate to be',
    'interpret as',
    'believe to be',
    'feel to be',
    'imagine to be',
    'conceive to be',
]