export const definitions = [
    '"the crisis deepened"',
]
export const synonyms = [
    'grow',
    'increase',
    'intensify',
    'strengthen',
    'escalate',
    'mushroom',
    'snowball',
    'add to',
    'heighten',
    'reinforce',
    'enhance',
    'boost',
    'magnify',
    'amplify',
    'augment',
    'enrich',
    'promote',
    'encourage',
    'exacerbate',
    'aggravate',
    'inflame',
    'worsen',
    'dig out',
    'excavate',
    'make/become worse',
    'make deeper',
    'dig deeper',
    'scoop out',
    'scrape out',
    'hollow out',
]