definitions: [
    '"Arab armies defeated the Byzantine garrison"',
    '"she was defeated by the last steep hill"',
    '"don\'t cheat by allowing your body to droop—this defeats the object of the exercise"',
    '"the amendment was defeated"',
    '"this line of reasoning defeats me, I must confess"',
    '"she had still not quite admitted defeat"',
    '"the defeat of the Armada in 1588"',
]
synonyms: [
    'beat',
    'conquer',
    'get the better of',
    'best',
    'worst',
    'vanquish',
    'rout',
    'trounce',
    'overcome',
    'overpower',
    'overthrow',
    'overwhelm',
    'crush',
    'quash',
    'bring someone to their knees',
    'quell',
    'subjugate',
    'subdue',
    'repulse',
    'win against',
    'win a victory over',
    'triumph over',
    'prevail over',
    'lose to',
    'thwart',
    'block',
    'frustrate',
    'prevent',
    'foil',
    'balk',
    'ruin',
    'put a stop to',
    'scotch',
    'obviate',
    'forestall',
    'debar',
    'snooker',
    'derail',
    'obstruct',
    'impede',
    'hinder',
    'hamper',
    'deter',
    'discomfit',
    'advance',
    'assist',
    'reject',
    'overthrow',
    'throw out',
    'dismiss',
    'outvote',
    'spurn',
    'rebuff',
    'turn down',
    'pass',
    'baffle',
    'puzzle',
    'perplex',
    'bewilder',
    'mystify',
    'bemuse',
    'confuse',
    'confound',
    'frustrate',
    'nonplus',
    'throw',
    'loss',
    'beating',
    'conquest',
    'conquering',
    'besting',
    'worsting',
    'vanquishing',
    'vanquishment',
    'rout',
    'trouncing',
    'overpowering',
    'subjugation',
    'subduing',
    'reverse',
    'debacle',
    'downfall',
    'failure',
    'breakdown',
    'collapse',
    'ruin',
    'discomfiture',
    'rejection',
    'frustration',
    'foundering',
    'misfiring',
    'overthrow',
    'abortion',
    'miscarriage',
    'undoing',
    'disappointment',
    'setback',
    'game, set, and match',
    'lack of success',
    'victory',
    'success',
]