definitions: [
    '"we shall defend our country, whatever the cost"',
    '"he defended his policy of imposing high taxes"',
    '"the lawyer had defended the dissidents"',
    '"he successfully defended his congressional seat in new elections"',
]
synonyms: [
    'protect',
    'guard',
    'safeguard',
    'preserve',
    'secure',
    'shield',
    'shelter',
    'screen',
    'fortify',
    'garrison',
    'barricade',
    'uphold',
    'support',
    'keep from harm',
    'fight for',
    'be on the side of',
    'take up cudgels for',
    'watch over',
    'be the defender of',
    'attack',
    'justify',
    'vindicate',
    'support',
    'excuse',
    'exonerate',
    'palliate',
    'explain',
    'back',
    'stand by',
    'stick up for',
    'stand up for',
    'champion',
    'endorse',
    'uphold',
    'sustain',
    'bolster',
    'argue/speak for',
    'speak on behalf of',
    'speak in support of',
    'give an apologia for',
    'make a case for',
    'plead for',
    'make excuses for',
    'give reasons for',
    'give the rationale behind',
    'argue for',
    'come to the defense of',
    'attack',
    'criticize',
]
