export const definitions = [
  '"genetic defects"',
  '"the property is free from defect"',
  '"he defected to the Soviet Union after the war"',
];
export const synonyms = [
  'fault',
  'flaw',
  'imperfection',
  'deficiency',
  'weakness',
  'inadequacy',
  'shortcoming',
  'limitation',
  'failing',
  'obstruction',
  'snag',
  'kink',
  'deformity',
  'blemish',
  'taint',
  'crack',
  'break',
  'tear',
  'split',
  'scratch',
  'chip',
  'fracture',
  'spot',
  'mistake',
  'error',
  'bug',
  'virus',
  'weak spot/point',
  'desert',
  'turn traitor',
  'rebel',
  'renege',
  'abscond',
  'quit',
  'escape',
  'break faith',
  'apostatize',
  'abandon',
  'renounce',
  'repudiate',
  'forsake',
  'tergiversate',
  'go over to the enemy',
  'change sides/loyalties/allegiances',
  'go AWOL',
  'shift ground',
  'be apostate',
  'secede from',
  'revolt against',
];