export const definitions = [
    '"the contract will seek to define the client\'s obligations"',
    '"the dictionary defines it as \"a type of pasture\""',
    '"for some, the football team defines their identity"',
    '"the river defines the park\'s boundary"',
    '"she defined her eyes by applying eyeshadow"',
]
export const synonyms = [
    'explain',
    'expound',
    'interpret',
    'elucidate',
    'explicate',
    'describe',
    'clarify',
    'spell out',
    'give the meaning of',
    'state precisely',
    'put into words',
    'express in words',
    'determine',
    'establish',
    'fix',
    'specify',
    'designate',
    'decide',
    'stipulate',
    'settle',
    'set out',
    'mark out',
    'mark off',
    'demarcate',
    'bound',
    'delimit',
    'delineate',
    'circumscribe',
    'set the boundaries/limits of',
    'outline',
    'delineate',
    'silhouette',
    'trace',
    'pencil',
]