export const definitions = [
  '"a degree of caution is probably wise"',
  '"a question of degree"',
  '"set at an angle of 45 degrees"',
  '"water boils at 100 degrees Celsius"',
  '"second-degree murder"',
  '"criminal conduct in the first degree"',
  '"second-degree relatives"',
  '"the lowered third degree of the scale"',
  '"an equation of the second degree"',
  '"a degree in zoology"',
  '"persons of unequal degree"',
];
export const synonyms = [
  'level',
  'stage',
  'point',
  'rung',
  'standard',
  'grade',
  'gradation',
  'mark',
  'amount',
  'extent',
  'measure',
  'magnitude',
  'intensity',
  'strength',
  'proportion',
  'ratio',
  'social class',
  'social status',
  'rank',
  'station',
  'estate',
  'condition',
  'standing/position in society',
];