export const definitions = [
  '"this may be the worst deluge in living memory"',
  '"the world appeared to be emerging still from the waters of the Deluge"',
  '"a deluge of rain hit the plains"',
  '"a deluge of complaints"',
  '"he has been deluged with offers of work"',
  '"the country was deluged with rain"',
];
export const synonyms = [
  'flood',
  'flash flood',
  'torrent',
  'spate',
  'downpour',
  'thunderstorm',
  'rainstorm',
  'cloudburst',
  'torrential rain',
  'torrent of rain',
  'drizzle',
  'barrage',
  'volley',
  'flood',
  'torrent',
  'avalanche',
  'stream',
  'storm',
  'shower',
  'cascade',
  'spate',
  'wave',
  'rush',
  'outpouring',
  'trickle',
  'inundate',
  'overwhelm',
  'overload',
  'overrun',
  'flood',
  'swamp',
  'snow under',
  'engulf',
  'shower',
  'bombard',
  'flood',
  'inundate',
  'engulf',
  'submerge',
  'swamp',
  'drown',
];