export const definitions = [
    '"she delved in her pocket"',
    '"the society is determined to delve deeper into the matter"',
    '"when Adam delved and Eve span, who was then the gentleman?"',
    '"the approach from the surface above had awed her, so hugely delved were the tunnels"',
]
export const synonyms = [
    'dig in',
    'go through',
    'scour',
    'ransack',
    'rummage (around) in',
    'search (through)',
    'hunt through',
    'scrabble around in',
    'root around in',
    'ferret (around) in',
    'fish around in',
    'poke around in',
    'grub around in',
    'burrow in',
    'rifle through',
    'turn upside down',
    'turn inside out',
    'roust around in',
    'investigate',
    'probe',
    'examine',
    'explore',
    'research',
    'study',
    'look into',
    'go into',
    'conduct investigations into',
    'make inquiries into',
    'inquire into',
    'try to get to the bottom of',
    'dig',
    'excavate',
    'burrow',
    'tunnel',
    'poke around',
    'explore',
    'probe',
    'scratch around',
    'rake through',
    'sift through',
]