export const definitions = [
];
export const synonyms = [
  'old-fashioned',
  'outmoded',
  'out of fashion',
  'out of date',
  'unfashionable',
  'frumpish',
  'frumpy',
  'outdated',
  'dated',
  'out',
  'outworn',
  'old',
  'former',
  'dead',
  'musty',
  'old-time',
  'old-world',
  'behindhand',
  'past',
  'bygone',
  'archaic',
  'obsolescent',
  'obsolete',
  'ancient',
  'antiquated',
  'superannuated',
  'defunct',
  'medieval',
  'prehistoric',
  'antediluvian',
  'oldfangled',
  'conservative',
  'quaint',
  'anachronistic',
  'crusted',
  'feudal',
  'fusty',
  'moth-eaten',
  'passé',
  'square-toed',
  'out of style',
  'old-fogeyish',
  'backward-looking',
  'olde worlde',
  'vieux jeu',
  'up to date',
  'ahead of one\'s time',
];