export const definitions = [
  '"a demure young lady"',
  '"Antonia was pensive and demure"',
  '"a demure knee-length skirt"',
];
export const synonyms = [
  'modest',
  'unassuming',
  'meek',
  'mild',
  'reserved',
  'retiring',
  'quiet',
  'shy',
  'bashful',
  'diffident',
  'reticent',
  'timid',
  'timorous',
  'shrinking',
  'coy',
  'decorous',
  'decent',
  'seemly',
  'ladylike',
  'respectable',
  'proper',
  'virtuous',
  'pure',
  'innocent',
  'maidenly',
  'virginal',
  'chaste',
  'sober',
  'sedate',
  'staid',
  'prim',
  'priggish',
  'prissy',
  'prudish',
  'goody-goody',
  'strait-laced',
  'puritanical',
  'old-maidish',
  'retired',
  'prim and proper',
  'brazen',
  'shameless',
];