export const definitions = [
    '"she shook her head in ______"',
    '"brazen ______, given the mounting evidence"',
    '"his ______ that he was having an affair"',
    '"the ______ of insurance to people with certain medical conditions"',
    '"you\'re living in ______"',
]
export const synonyms = [
    'contradiction',
    'refutation',
    'rebuttal',
    'repudiation',
    'disclaimer',
    'retraction',
    'abjuration',
    'negation',
    'dissent',
    'disaffirmation',
    'confutation',
    'counterstatement',
    'retractation',
    'confirmation',
    'contradiction',
    'refutation',
    'rebuttal',
    'repudiation',
    'disclaimer',
    'retraction',
    'abjuration',
    'negation',
    'dissent',
    'disaffirmation',
    'confutation',
    'counterstatement',
    'retractation',
    'confirmation',
    'refusal',
    'withholding',
    'withdrawal',
    'rejection',
    'dismissal',
    'rebuff',
    'repulse',
    'declination',
    'veto',
    'turndown',
    'acceptance',
]