export const definitions = [
  '"this mark will ______ purity and quality going forward"',
  '"The color red can ______ anger or passion."',
  '"The symbol * can ______ multiplication or a footnote."',
  '"The term GDP can ______ gross domestic product or government debt percentage."',
  'The phrase \"to be or not to be\" can ______ a famous quote from Shakespeare or a philosophical dilemma.',
  '"The letter A can ______ the first letter of the alphabet or a grade in school."',
];
export const synonyms = [
  'designate',
  'indicate',
  'signify',
  'signal',
  'symbolize',
  'represent',
  'stand for',
  'mean',
  'typify',
  'characterize',
  'distinguish',
  'mark',
  'identify',
  'bespeak',
  'betoken',
  'suggest',
  'point to',
  'show',
  'reveal',
  'demonstrate',
  'intimate',
  'imply',
  'connote',
  'convey',
  'give away',
  'betray',
  'be a sign of',
  'be a mark of',
  'be evidence of',
  'smack of',
  'conjure up',
  'bring to mind',
  'represent',
  'stand for',
  'exemplify',
  'signify',
  'mean',
  'communicate',
  'indicate',
  'convey',
  'express',
  'imply',
  'suggest',
  'embody',
  'epitomize',
  'encapsulate',
  'personify',
  'typify',
  'betoken',
  'symbol',
  'be a symbol of',
  'be a sign of',
  'allude to',
];