export const definitions = [
  '"they departed for Germany"',
  '"a contingent was departing from Cairo"',
  '"he departed from the precedent set by many"',
];
export const synonyms = [
  'leave',
  'go',
  'go off',
  'take one\'s leave',
  'withdraw',
  'quit',
  'exit',
  'break camp',
  'decamp',
  'retreat',
  'retire',
  'make off',
  'clear out',
  'make oneself scarce',
  'run off',
  'run away',
  'flee',
  'fly',
  'bolt',
  'set off',
  'set out',
  'start out',
  'be on one\'s way',
  'repair',
  'remove',
  'go away',
  'take oneself off',
  'absent oneself',
  'say one\'s goodbyes',
  'make an exit',
  'beat a retreat',
  'get going',
  'get under way',
  'betake oneself',
  'abstract oneself',
  'arrive',
  'stay',
  'deviate',
  'diverge',
  'digress',
  'drift',
  'stray',
  'slew',
  'veer',
  'swerve',
  'turn away',
  'differ',
  'vary',
  'contravene',
  'contradict',
  'divagate',
  'turn aside',
  'branch off',
  'be different',
  'be at variance with',
  'run counter to',
  'contrast with',
];