export const definitions = [
    '"differences in earnings ______ed on a wide variety of factors"',
    '"the kind of person you could ______ on"',
    '"a town that had ______ed heavily upon the wool industry"',
    '"his tongue ______ed from open jaws"',
]
export const synonyms = [
    'turn on',
    'hang on',
    'be contingent on',
    'be conditional on',
    'pivot on',
    'hinge on',
    'rest on',
    'be based on',
    'rely on',
    'be subject to',
    'be controlled by',
    'be determined by',
    'be influenced by',
    'be decided by',
    'be resultant from',
    'relate to',
    'believe in',
    'bank on',
    'count on',
    'swear by',
    'have faith in',
    'put/place one\'s trust in ',
    'have (every) confidence in',
    'pin one\'s hopes / faith on',
    'rely on',
    'be sure of',
    'be convinced by',
    'confide in',
    'distrust',
    'mistrust',
    'doubt',
    'lean on',
    'count on',
    'bank on',
    'trust',
    'believe in',
    'swear by',
    'rely on',
    'place reliance on',
    'cling to',
    'be supported by',
    'be sustained by',
    'be unable to manage without',
    'trust in',
    'put one\'s trust in ',
    'put one\'s faith in ',
    'have faith in',
    'have (every) confidence in',
    'be sure of',
    'pin one\'s hope on',
    'droop',
    'sag',
    'swing',
    'sway',
    'wave',
    'trail',
    'stream',
    'hang (down)',
]