export const definitions = [
  '"he had been deposed by a military coup"',
  '"every affidavit shall state which of the facts deposed to are within the deponent\'s knowledge"',
];
export const synonyms = [
  'overthrow',
  'overturn',
  'topple',
  'bring down',
  'remove',
  'unseat',
  'dethrone',
  'supplant',
  'displace',
  'dismiss',
  'discharge',
  'oust',
  'drum out',
  'throw out',
  'force out',
  'drive out',
  'expel',
  'eject',
  'demote',
  'cashier',
  'remove from office',
  'strip of rank',
  'swear',
  'testify',
  'attest',
  'undertake',
  'assert',
  'declare',
  'profess',
  'aver',
  'submit',
  'claim',
  'asseverate',
  'represent',
  'swear on the Bible',
  'swear under oath',
  'state on oath',
  'make a deposition',
  'give an undertaking',
  'solemnly promise',
];