export const definitions = [
    '"he was deported for violation of immigration laws"',
    '"he was deported to Turkey for his public condemnation of the Shah"',
    '"he has deported himself with great dignity"',
]
export const synonyms = [
    'expel',
    'banish',
    'exile',
    'transport',
    'expatriate',
    'extradite',
    'repatriate',
    'evict',
    'oust',
    'cast out',
    'throw out',
    'turn out',
    'drive out',
    'drum out',
    'out',
    'ostracize',
    'admit',
    'behave',
    'act',
    'perform',
    'conduct oneself',
    'acquit oneself',
    'bear oneself',
    'carry oneself',
    'hold oneself',
    'comport oneself',
]