export const definitions = [
    '"she had been deputed to look after him while Clarissa was away"',
]
export const synonyms = [
    'appoint',
    'designate',
    'nominate',
    'assign',
    'commission',
    'charge',
    'choose',
    'select',
    'elect',
    'co-opt',
    'empower',
    'authorize',
    'mandate',
    'detail',
    'delegate',
    'transfer',
    'turn over',
    'hand over',
    'hand on',
    'pass on',
    'consign',
    'assign',
    'entrust',
    'give',
    'devolve',
]