export const definitions = [
  '"his deputy has been largely running the business for the past year"',
  '"the deputy prime minister"',
  '"the deputies are chosen by the people for three years"',
];
export const synonyms = [
  'second in command',
  'second',
  'number two',
  'subordinate',
  'junior',
  'auxiliary',
  'adjutant',
  'lieutenant',
  'subaltern',
  'assistant',
  'personal assistant',
  'PA',
  'aide',
  'helper',
  'right-hand man',
  'henchman',
  'underling',
  'substitute',
  'stand-in',
  'fill-in',
  'relief',
  'understudy',
  'supply',
  'representative',
  'surrogate',
  'proxy',
  'delegate',
  'agent',
  'spokesperson',
  'ambassador',
  'legate',
  'depute',
  'locum tenens',
  'acting',
  'reserve',
  'caretaker',
  'temporary',
  'short-term',
  'provisional',
  'stopgap',
  'pro tempore',
  'ad interim',
  'expediential',
];