export const definitions = [
  '"critics derided the proposals as clumsy attempts to find a solution"',
];
export const synonyms = [
  'ridicule',
  'mock',
  'make fun of',
  'poke fun at',
  'pillory',
  'disdain',
  'disparage',
  'denigrate',
  'pooh-pooh',
  'dismiss',
  'slight',
  'scorn',
  'taunt',
  'insult',
  'torment',
  'vilify',
  'lampoon',
  'satirize',
  'contemn',
  'jeer at',
  'scoff at',
  'jibe at',
  'laugh at',
  'hold up to ridicule',
  'detract from',
  'sneer at',
  'pour/heap scorn on',
  'treat with contempt',
  'flout at',
  'respect',
  'praise',
];