export const definitions = [
  '"we feel our public representatives have deserted us"',
  '"good weather came after the summer hordes had deserted the beaches"',
  '"her luck deserted her"',
  '"his life in the regiment had been such a hell that he decided to desert"',
  '"a cultural desert"',
  '"overgrazing has created desert conditions"',
  '"desert wastes"',
];
export const synonyms = [
  'abandoned',
  'forsaken',
  'betrayed',
  'jilted',
  'shunned',
  'neglected',
  'stranded',
  'marooned',
  'relinquished',
  'renounced',
  'forlorn',
  'bereft',
  'abandon',
  'leave',
  'give up',
  'cast off',
  'turn one\'s back on',
  'throw over',
  'betray',
  'jilt',
  'neglect',
  'shun',
  'leave behind',
  'strand',
  'maroon',
  'relinquish',
  'renounce',
  'forsake',
  'repudiate',
  'forswear',
  'wash one\'s hands of',
  'abjure',
  'disavow',
  'apostatize',
  'recant',
  'cast off/aside',
  'thrown over',
  'break (up) with',
  'leave high and dry',
  'leave in the lurch',
  'leave stranded',
  'renege on',
  'have no more truck with',
  'have done with',
  'disprofess',
  'stand by',
  'empty',
  'uninhabited',
  'unoccupied',
  'unpeopled',
  'abandoned',
  'evacuated',
  'vacant',
  'vacated',
  'untenanted',
  'tenantless',
  'unfrequented',
  'neglected',
  'secluded',
  'isolated',
  'desolate',
  'lonely',
  'solitary',
  'godforsaken',
  'forlorn',
  'crowded',
  'populous',
  'abscond',
  'defect',
  'run away',
  'make off',
  'decamp',
  'flee',
  'fly',
  'bolt',
  'turn tail',
  'depart',
  'quit',
  'escape',
  'go absent without leave',
  'take French leave',
  'stay',
  'wasteland',
  'waste',
  'wilderness',
  'wilds',
  'dust bowl',
  'barren land',
  'wasteland',
  'uninteresting place/period',
  'unproductive place/period',
  'arid',
  'dry',
  'moistureless',
  'parched',
  'scorched',
  'burnt',
  'hot',
  'burning',
  'torrid',
  'barren',
  'bare',
  'stark',
  'infertile',
  'nonfertile',
  'unproductive',
  'unfruitful',
  'dehydrated',
  'sterile',
  'dried up',
  'uncultivatable',
  'fertile',
  'uninhabited',
  'empty',
  'solitary',
  'lonely',
  'desolate',
  'bleak',
  'dismal',
  'waste',
  'wild',
  'uncultivated',
  'untended',
  'untilled',
];
