export const definitions = [
    '"a desire to work in the dirt with your bare hands"',
    '"they were clinging together in fierce mutual desire"',
    '"he never achieved the status he so desired"',
    '"there had been a time, years ago, when he had desired her"',
    '"John spake unto him, and desired him in like manner and contestation as before"',
]
export const synonyms = [
    'wish',
    'want',
    'fancy',
    'inclination',
    'aspiration',
    'impulse',
    'preference',
    'yearning',
    'longing',
    'craving',
    'hankering',
    'pining',
    'ache',
    'hunger',
    'thirst',
    'itch',
    'burning',
    'need',
    'eagerness',
    'enthusiasm',
    'determination',
    'predilection',
    'proclivity',
    'predisposition',
    'lust',
    'lustfulness',
    'passion',
    'libido',
    'sensuality',
    'sexuality',
    'lasciviousness',
    'lechery',
    'lecherousness',
    'salaciousness',
    'libidinousness',
    'lewdness',
    'licentiousness',
    'prurience',
    'wantonness',
    'carnality',
    'concupiscence',
    'sexual appetite',
    'sexual attraction',
    'carnal passion',
    'want',
    'crave',
    'set one\'s heart on',
    'covet',
    'fancy',
    'required',
    'necessary',
    'proper',
    'right',
    'correct',
    'appropriate',
    'fitting',
    'suitable',
    'preferred',
    'chosen',
    'selected',
    'expected',
    'wanted',
    'sought-after',
    'craved',
    'needed',
    'coveted',
    'wish for',
    'long for',
    'yearn for',
    'hanker after/for',
    'pine for/after',
    'thirst for',
    'itch for',
    'be desperate for',
    'be bent on',
    'have a need for',
    'aspire to',
    'have a fancy for',
    'feel like',
    'feel in need of',
    'called for',
    'wished for',
    'longed for',
    'yearned for',
    'pined for',
    'unwanted',
    'be attracted to',
    'lust after',
    'burn for',
    'be captivated by',
    'be infatuated by',
]