export const definitions = [
    '"he has just unveiled his design for the new museum"',
    '"good design can help the reader understand complicated information"',
    '"the cloister is of late-twelfth-century design"',
    '"pottery with a lovely blue and white design"',
    '"the appearance of design in the universe"',
    '"a number of architectural students were designing a factory"',
    '"the tax changes were designed to stimulate economic growth"',
]
export const synonyms = [
    'plan',
    'blueprint',
    'drawing',
    'sketch',
    'outline',
    'map',
    'plot',
    'diagram',
    'delineation',
    'draft',
    'depiction',
    'representation',
    'artist\'s impression',
    'scheme',
    'model',
    'prototype',
    'proposal',
    'scale drawing',
    'pattern',
    'motif',
    'device',
    'style',
    'arrangement',
    'composition',
    'makeup',
    'layout',
    'constitution',
    'configuration',
    'organization',
    'construction',
    'shape',
    'form',
    'formation',
    'figure',
    'intention',
    'aim',
    'purpose',
    'plan',
    'intent',
    'objective',
    'object',
    'goal',
    'end',
    'target',
    'point',
    'hope',
    'desire',
    'wish',
    'dream',
    'aspiration',
    'ambition',
    'idea',
    'plan',
    'draw',
    'sketch',
    'outline',
    'map out',
    'plot',
    'block out',
    'delineate',
    'draft',
    'depict',
    'invent',
    'originate',
    'create',
    'think up',
    'come up with',
    'devise',
    'form',
    'formulate',
    'conceive',
    'make',
    'produce',
    'develop',
    'fashion',
    'fabricate',
    'forge',
    'hatch',
    'coin',
    'draw plans of',
    'intend',
    'aim',
    'devise',
    'contrive',
    'purpose',
    'plan',
    'tailor',
    'fashion',
    'adjust',
    'adapt',
    'fit',
    'gear',
    'equip',
    'mean',
    'destine',
    'orient',
    'make fitting',
]