export const definitions = [
    '"cancer may soon be detected in its earliest stages"',
    '"Paul detected a faint note of weariness in his father\'s voice"',
    '"the public can help the police to detect crime"',
]
export const synonyms = [
    'notice',
    'perceive',
    'note',
    'discern',
    'make out',
    'observe',
    'spot',
    'recognize',
    'distinguish',
    'mark',
    'remark',
    'identify',
    'diagnose',
    'catch',
    'decry',
    'sense',
    'see',
    'catch sight of',
    'smell',
    'scent',
    'taste',
    'behold',
    'descry',
    'espy',
    'become aware of',
    'become conscious of',
    'discover',
    'uncover',
    'find',
    'find out',
    'turn up',
    'unearth',
    'dig up',
    'root out',
    'expose',
    'reveal',
    'bring to light',
    'come across',
    'hit on',
    'encounter',
    'solve',
    'clear up',
    'get to the bottom of',
    'catch',
    'unmask',
    'smoke out',
    'track down',
    'apprehend',
    'arrest',
    'dredge up',
    'hunt out',
    'nose out',
    'ferret out',
    'bring into the open',
    'stumble on',
    'chance on',
    'find the perpetrator of',
    'find the person behind',
    'hunt down',
]
