export const definitions = [
    '"of all birds the carrion crow is the most detested by gamekeepers"',
]
export const synonyms = [
    'abhor',
    'hate',
    'loathe',
    'despise',
    'abominate',
    'execrate',
    'dislike',
    'disdain',
    'disrelish',
    'regard with disgust',
    'feel disgust for',
    'feel repugnance toward',
    'feel distaste for',
    'shrink from',
    'recoil from',
    'shudder at',
    'be unable to bear',
    'be unable to abide',
    'feel hostility to',
    'feel aversion to',
    'feel animosity to',
    'find intolerable',
    'have an aversion to',
    'love',
    'admire',
]