export const definitions = [
  '"only a health problem would deter him from seeking re-election"',
  '"strategists think not only about how to deter war, but about how war might occur"',
];
export const synonyms = [
  'put off',
  'discourage',
  'dissuade',
  'scare off',
  'warn',
  'caution',
  'dishearten',
  'demoralize',
  'daunt',
  'frighten',
  'unnerve',
  'intimidate',
  'make worried/nervous/anxious',
  'encourage',
  'prevent',
  'stop',
  'put a stop to',
  'avert',
  'fend off',
  'stave off',
  'ward off',
  'head off',
  'shut out',
  'block',
  'intercept',
  'halt',
  'arrest',
  'check',
  'stay',
  'keep',
  'hinder',
  'impede',
  'hamper',
  'obstruct',
  'balk',
  'foil',
  'thwart',
  'obviate',
  'frustrate',
  'forestall',
  'counteract',
  'inhibit',
  'hold back',
  'curb',
  'restrain',
  'preclude',
  'preempt',
  'save',
  'help',
  'let',
  'nip in the bud',
  'turn aside',
  'encourage',
];