export const definitions = [
    '"a training program should be devised"',
    '"a complicated game of his own devising"',
]
export const synonyms = [
    'conceive',
    'think up',
    'come up with',
    'dream up',
    'draw up',
    'work out',
    'form',
    'formulate',
    'concoct',
    'design',
    'frame',
    'invent',
    'coin',
    'originate',
    'compose',
    'construct',
    'fabricate',
    'create',
    'produce',
    'put together',
    'make up',
    'develop',
    'evolve',
    'discover',
    'hit on',
    'hatch',
    'cook up',
    'contrive',
    'leave',
    'will',
    'make over',
    'pass on',
    'hand on',
    'hand down',
    'cede',
    'consign',
    'commit',
    'entrust',
    'grant',
    'transfer',
    'convey',
    'donate',
    'give',
    'give over',
    'turn over',
    'vouchsafe',
    'demise',
    'leave in one\'s will',
    'bestow on',
    'confer on',
]