export const definitions = [
    '"heroes with divine powers"',
    '"paintings of shipwrecks being prevented by divine intervention"',
    '"divine liturgy"',
    '"he had the most divine smile"',
    '"that succulent clementine tasted divine"',
    '"his brother usually divined his ulterior motives"',
    '"they had divined that he was a fake"',
    '"frauds who claimed to divine the future in chickens\' entrails"',
]
export const synonyms = [
    'godly',
    'godlike',
    'angelic',
    'seraphic',
    'saintly',
    'beatific',
    'spiritual',
    'heavenly',
    'celestial',
    'holy',
    'empyrean',
    'deiform',
    'deific',
    'mortal',
    'religious',
    'holy',
    'sacred',
    'sanctified',
    'consecrated',
    'blessed',
    'devotional',
    'devoted to God',
    'dedicated to God',
    'lovely',
    'handsome',
    'beautiful',
    'good-looking',
    'prepossessing',
    'charming',
    'delightful',
    'appealing',
    'engaging',
    'winsome',
    'ravishing',
    'gorgeous',
    'bewitching',
    'beguiling',
    'wonderful',
    'glorious',
    'marvelous',
    'excellent',
    'superlative',
    'perfect',
    'delicious',
    'mouthwatering',
    'delectable',
    'bonny',
    'beauteous',
    'taking',
    'comely',
    'fair',
    'sightly',
    'mundane',
    'dreadful',
    'theologian',
    'clergyman',
    'churchman',
    'churchwoman',
    'cleric',
    'ecclesiastic',
    'man of the cloth',
    'man of God',
    'preacher',
    'priest',
    'member of the clergy',
    'holy man',
    'holy woman',
    'kirkman',
    'guess',
    'surmise',
    'conjecture',
    'suspect',
    'suppose',
    'assume',
    'presume',
    'deduce',
    'infer',
    'work out',
    'theorize',
    'hypothesize',
    'discern',
    'intuit',
    'perceive',
    'recognize',
    'see',
    'realize',
    'appreciate',
    'understand',
    'grasp',
    'apprehend',
    'comprehend',
    'figure',
    'cognize',
    'foretell',
    'predict',
    'prophesy',
    'forecast',
    'foresee',
    'prognosticate',
    'forewarn',
    'forebode',
    'previse',
    'presage',
    'foreshow',
    'croak',
    'vaticinate',
    'spae',
    'auspicate',
    'dowse',
    'find by dowsing',
]