export const definitions = [
  '"she was a devout Catholic"',
  '"a rabbi\'s devout prayers"',
  '"the most devout environmentalist"',
];
export const synonyms = [
  'pious',
  'religious',
  'devoted',
  'dedicated',
  'reverent',
  'God-fearing',
  'believing',
  'spiritual',
  'prayerful',
  'holy',
  'godly',
  'saintly',
  'faithful',
  'dutiful',
  'righteous',
  'churchgoing',
  'orthodox',
  'insincere',
  'lapsed',
  'dedicated',
  'devoted',
  'committed',
  'loyal',
  'faithful',
  'staunch',
  'genuine',
  'firm',
  'steadfast',
  'resolute',
  'unwavering',
  'sincere',
  'wholehearted',
  'keen',
  'earnest',
  'enthusiastic',
  'zealous',
  'passionate',
  'ardent',
  'fervent',
  'intense',
  'vehement',
  'active',
  'sworn',
  'pledged',
  'engagé',
  'apathetic',
];