export const definitions = [
  '"your skin will begin to feel revitalized and dewy"',
  '"the girls have yet to lose their dewy charm"',
];
export const synonyms = [
  'moist',
  'moistened',
  'wettish',
  'dampened',
  'dampish',
  'humid',
  'steamy',
  'muggy',
  'clammy',
  'sweaty',
  'sticky',
  'dank',
  'moisture-laden',
  'wet',
  'wetted',
  'rainy',
  'drizzly',
  'showery',
  'misty',
  'foggy',
  'vaporous',
  'claggy',
  'dry',
];