export const definitions = [
    '"the book consisted of a series of dialogues"',
    '"passages of dialogue"',
    '"the U.S. would enter into a direct dialogue with Vietnam"',
    '"interfaith dialogue"',
    '"he stated that he wasn\'t going to dialogue with the guerrillas"',
]
export const synonyms = [
    'conversation',
    'talk',
    'communication',
    'interchange',
    'discourse',
    'argument',
    'chat',
    'chatter',
    'chitchat',
    'chitter-chatter',
    'gossip',
    'confabulation',
    'converse',
    'interlocution',
    'duologue',
    'colloquy',
    'script',
    'text',
    'screenplay',
    'speech',
    'lines',
    'words',
    'parts',
    'spoken parts',
    'discussion',
    'exchange',
    'debate',
    'discourse',
    'head-to-head',
    'tête-à-tête',
    'consultation',
    'conference',
    'parley',
    'interview',
    'talks',
    'negotiations',
    'confabulation',
    'exchange of views',
    'question and answer session',
]