definitions: [
    '"the second set of data differed from the first"',
    '"tastes differ, especially in cars"',
    '"he differed from his contemporaries in ethical matters"',
]
synonyms: [
    'vary',
    'diverge',
    'contradict',
    'go against',
    'be different',
    'be unlike',
    'be dissimilar',
    'be distinguishable',
    'deviate from',
    'depart from',
    'run counter to',
    'contrast with',
    'conflict with',
    'be incompatible with',
    'be at odds with',
    'be in opposition to',
    'coincide',
    'resemble',
    'disagree',
    'dissent',
    'conflict',
    'clash',
    'cross swords',
    'lock horns',
    'be at each other\'s throats',
    'quarrel',
    'argue',
    'wrangle',
    'quibble',
    'squabble',
    'altercate',
    'fail to agree',
    'be at variance',
    'be in dispute',
    'be in opposition',
    'take issue',
    'agree',
]