export const definitions = [
    '"the computer digested your labors into a form understandable by a program"',
    '"a digest of their findings"',
    '"a digest of cloned DNA"',
]
export const synonyms = [
    'break down',
    'dissolve',
    'assimilate',
    'absorb',
    'take in',
    'take up',
    'assimilate',
    'absorb',
    'take in',
    'understand',
    'comprehend',
    'grasp',
    'master',
    'learn',
    'consider',
    'think about',
    'contemplate',
    'chew over',
    'weigh up',
    'ponder',
    'study',
    'familiarize oneself with',
    'mull over',
    'reflect on',
    'meditate on',
    'classify',
    'catalog',
    'tabulate',
    'codify',
    'arrange',
    'order',
    'dispose',
    'systematize',
    'methodize',
    'condense',
    'compress',
    'compact',
    'telescope',
    'summarize',
    'precis',
    'abstract',
    'epitomize',
    'list',
    'chart',
    'diagram',
    'figure',
    'graph',
    'plan',
    'catalog',
    'inventory',
    'enumeration',
    'tabulation',
    'index',
    'directory',
    'register',
    'itemization',
    'record',
    'graphic',
    'journal',
    'publication',
    'magazine',
    'newspaper',
    'paper',
    'review',
    'gazette',
    'newsletter',
    'organ',
    'serial',
    'annual',
    'quarterly',
    'monthly',
    'bimonthly',
    'fortnightly',
    'weekly',
    'biweekly',
    'summary',
    'synopsis',
    'abstract',
    'precis',
    'résumé',
    'outline',
    'sketch',
    'roundup',
    'abridgment',
    'summation',
    'review',
    'compendium',
    'wrap-up',
    'argument',
    'epitome',
    'summa',
    'conspectus',
    '(quick) rundown',
]