export const definitions = [
  '"a diktat from the Bundestag"',
  '"he can disband the legislature and rule by diktat"',
];
export const synonyms = [
  'law',
  'regulation',
  'enactment',
  'act',
  'bill',
  'decree',
  'edict',
  'rule',
  'ruling',
  'resolution',
  'promulgation',
  'measure',
  'motion',
  'dictum',
  'command',
  'order',
  'stipulation',
  'commandment',
  'directive',
  'pronouncement',
  'ratification',
  'proclamation',
  'dictate',
  'fiat',
  'covenant',
  'demand',
  'bylaw',
  'ordinance',
  'ukase',
  'pronunciamento',
];