export const definitions = [
  '"bleach can be diluted with cold water"',
  '"the reforms have been diluted"',
  '"a dilute solution of potassium permanganate"',
  '"a short measure of dilute sun"',
];
export const synonyms = [
  'weaken',
  'thin',
  'mix',
  'doctor',
  'lace',
  'adulterate',
  'make weaker',
  'thin out',
  'make thinner',
  'water down',
  'add water to',
  'concentrate',
  'diminish',
  'reduce',
  'decrease',
  'lessen',
  'attenuate',
  'weaken',
  'mitigate',
  'temper',
  'quell',
  'allay',
  'assuage',
  'alleviate',
  'palliate',
  'moderate',
  'modify',
  'tone down',
  'quieten',
  'quiet',
  'make weaker',
  'lenify',
  'intensify',
  'weak',
  'diluted',
  'thin',
  'watered down',
  'watery',
  'adulterated',
  'thinned out',
];