export const definitions = [
  '"a smoky inferno that dimmed the sun"',
  '"the lights dimmed and the curtains parted"',
  '"the car moved slowly, its headlights dimmed"',
  '"the difficulty in sleeping couldn\'t dim her happiness"',
  '"the company\'s prospects have dimmed"',
  '"his eyes dimmed"',
  '"your sight is dimmed"',
];
export const synonyms = [
  'fade',
  'dull',
  'darken',
  'blacken',
  'lour',
  'grow faint',
  'grow feeble',
  'grow dim',
  'grow dark',
  'cloud over',
  'become overcast',
  'grow leaden',
  'become gloomy',
  'brighten',
  'turn down',
  'lower',
  'dip',
  'soften',
  'subdue',
  'mute',
  'bedim',
  'make dim',
  'make faint',
  'make less bright',
  'make less intense',
  'turn up',
  'fade',
  'blur',
  'dull',
  'numb',
  'fail',
  'disappear',
  'become vague',
  'become indistinct',
  'grow dim',
  'become blurred',
  'become shadowy',
  'become confused',
  'sharpen',
];