export const definitions = [
  '"what\'s for dinner ? "',
  '"Brown heard the phone ring during dinner"',
  '"a candlelit dinner for two"',
  '"Eric sits next to Beth at the dinner table"',
  '"the annual graduation dinner"',
  '"a dinner in honor of his homecoming"',
];
export const synonyms = [
  'supper',
  'repast',
  'lunch',
  'feast',
  'banquet',
  'dinner party',
  'tea',
  'refection',
  'collation',
  'evening meal',
  'main meal',
  'supper',
  'repast',
  'lunch',
  'feast',
  'banquet',
  'dinner party',
  'tea',
  'refection',
  'collation',
  'evening meal',
  'main meal',
];