export const definitions = [
    '"guerrillas had completely disarmed and demobilized their forces"',
    '"the other militias had disarmed by the agreed deadline"',
    '"police yesterday disarmed a parcel bomb"',
    '"his tact and political skills will disarm critics"',
    '"camp humor acts to provoke rather than disarm moral indignation"',
]
export const synonyms = [
    'demilitarize',
    'demobilize',
    'deprive of arms',
    'take weapons from',
    'render defenseless',
    'make powerless',
    'arm',
    'militarize',
    'demilitarize',
    'lay down arms/weapons',
    'turn over weapons',
    'decommission arms/weapons',
    'become unarmed',
    'sheathe the sword',
    'turn swords into plowshares',
    'arm',
    'defuse',
    'disable',
    'deactivate',
    'remove the fuse from',
    'put out of action',
    'make safe',
    'make harmless',
    'arm',
    'set',
    'charm',
    'sweeten',
    'persuade',
    'convert',
    'mollify',
    'appease',
    'placate',
    'pacify',
    'conciliate',
    'humor',
    'propitiate',
    'win over',
    'undermine someone\'s resistance',
    'antagonize',
]