export const definitions = [
  '"an ovenproof dish"',
  '"a dish of oysters"',
  '"fresh fish dishes"',
  '"pasta was served as a main dish"',
  '"it was our turn to wash the dishes"',
  '"a water dish"',
  '"other channels are available with a larger dish"',
  '"I gather he\'s quite a dish"',
  '"as a public relations man this was my dish and the campaign was right up my street"',
  '"if he has the real dish I wish he\'d tell us"',
  '"groups gather to brag about babies and dish about romances"',
  '"I don\'t think I dished the wheel correctly—there\'s a rubbing sound"',
  '"this tool accurately checks for proper dishing of a wheel"',
];
export const synonyms = [
  'bowl',
  'plate',
  'soup plate',
  'platter',
  'salver',
  'container',
  'receptacle',
  'vessel',
  'repository',
  'trencher',
  'charger',
  'porringer',
  'paten',
  'serving dish',
  'oven dish',
  'ashet',
  'recipe',
  'course',
  'special',
  'food',
  'fare',
  'plat du jour',
  'item of food',
  'dish of the day',
  'menu item',
  'dishes',
  'plates',
  'crockery',
  'dinner service',
  'tea service',
  'tableware',
  'ware',
  'dinnerware',
  'cups and saucers',
  'delph',
  'bowl',
  'plate',
  'soup plate',
  'platter',
  'salver',
  'container',
  'receptacle',
  'vessel',
  'repository',
  'trencher',
  'charger',
  'porringer',
  'paten',
  'serving dish',
  'oven dish',
  'ashet',
  'belle',
  'vision',
  'charmer',
  'enchantress',
  'Venus',
  'goddess',
  'beauty queen',
  'picture',
  'seductress',
  'femme fatale',
  'beautiful woman',
  'English rose',
  'hag',
  'ugly woman',
  'destroy',
  'put an end to',
  'end',
  'extinguish',
  'dash',
  'quell',
  'quash',
  'ruin',
  'wreck',
  'shatter',
  'smash',
  'crush',
  'scotch',
  'stop',
  'block',
  'frustrate',
  'thwart',
  'put a stop to',
  'prevent',
  'defeat',
  'derail',
  'bring to an end',
  'be the end of',
  'facilitate',
];