export const definitions = [
    '"overloaded timber floors are likely to sag, producing a dished or sloping floor surface"',
    '"groups gather to brag about babies and dish about romances"',
    '"I don\'t think I dished the wheel correctly—there\'s a rubbing sound"',
    '"this tool accurately checks for proper dishing of a wheel"',
]
export const synonyms = [
    'destroy',
    'put an end to',
    'end',
    'extinguish',
    'dash',
    'quell',
    'quash',
    'ruin',
    'wreck',
    'shatter',
    'smash',
    'crush',
    'scotch',
    'stop',
    'block',
    'frustrate',
    'thwart',
    'put a stop to',
    'prevent',
    'defeat',
    'derail',
    'bring to an end',
    'be the end of',
    'facilitate',
]