export const definitions = [
    '"to his dismay, she left him"',
    '"they were dismayed by the U-turn in policy"',
]
export const synonyms = [
    'alarm',
    'shock',
    'surprise',
    'consternation',
    'concern',
    'perturbation',
    'disquiet',
    'disquietude',
    'discomposure',
    'distress',
    'upset',
    'anxiety',
    'trepidation',
    'fear',
    'pleasure',
    'relief',
    'appall',
    'horrify',
    'shock',
    'shake',
    'shake up',
    'disconcert',
    'confound',
    'surprise',
    'startle',
    'alarm',
    'frighten',
    'scare',
    'daunt',
    'discomfit',
    'unnerve',
    'unman',
    'unsettle',
    'discompose',
    'discountenance',
    'trouble',
    'bother',
    'concern',
    'perturb',
    'disturb',
    'upset',
    'distress',
    'sadden',
    'dishearten',
    'dispirit',
    'pother',
    'take aback',
    'throw off balance',
    'encourage',
    'please',
]