export const definitions = [
    '"he was dithering about the election date"',
    '"the easiest way to remove hot pixels is to dither the images"',
    '"after months of dither they had still not agreed"',
    '"buses are jammed and dirty and everyone is in a dither over taxis"',
]
export const synonyms = [
    'hesitate',
    'falter',
    'waver',
    'teeter',
    'vacillate',
    'oscillate',
    'fluctuate',
    'change one\'s mind',
    'procrastinate',
    'hang back',
    'delay',
    'stall',
    'temporize',
    'drag one\'s feet',
    'dawdle',
    'dally',
    'haver',
    'be in two minds',
    'be ambivalent',
    'be indecisive',
    'be unsure',
    'be undecided',
    'hum and haw',
    'swither',
]