export const definitions = [
  '"men are unlikely to be divested of power without a struggle"',
  '"he has divested the original play of its charm"',
  '"the government\'s policy of divesting itself of state holdings"',
  '"it appears easier to carry on in the business than to divest"',
  '"she divested him of his coat"',
];
export const synonyms = [
  'deprive',
  'strip',
  'dispossess',
  'relieve',
  'rob',
  'trick out of',
  'do out of',
  'despoil',
  'reave',
  'cheat out of',
  'strip',
  'relieve',
  'denude',
  'remove',
  'take off',
  'pull off',
  'peel off',
  'shed',
  'unclothe',
  'undress',
  'disrobe',
  'doff',
];