export const definitions = [
    '"none of the jobs were fun, but they were doable"',
]
export const synonyms = [
    'workable',
    'feasible',
    'practicable',
    'practical',
    'applicable',
    'usable',
    'manageable',
    'operable',
    'operational',
    'possible',
    'within reach',
    'likely',
    'achievable',
    'attainable',
    'realizable',
    'reasonable',
    'sensible',
    'realistic',
    'logical',
    'useful',
    'serviceable',
    'suitable',
    'expedient',
    'effective',
    'valid',
    'tenable',
    'sound',
    'well advised',
    'well thought out',
    'well grounded',
    'judicious',
    'levelheaded',
    'wise',
    'within the bounds/realms of possibility',
    'within reason',
    'accomplishable',
    'of use',
    'impracticable',
]