export const definitions = [
    '"the case will go to the Supreme Court, and may be docketed for the fall term"',
    '"he docketed the letter on the back in his distinctive writing"',
]
export const synonyms = [
    'document',
    'chit',
    'coupon',
    'voucher',
    'certificate',
    'counterfoil',
    'bill',
    'receipt',
    'proof of purchase',
    'label',
    'tag',
    'ticket',
    'tab',
    'documentation',
    'paperwork',
    'acquittance',
    'sales slip',
    'document',
    'record',
    'register',
    'log',
    'label',
    'tag',
    'tab',
    'mark',
    'ticket',
]