export const definitions = [
    '"the rejection of political dogma"',
    '"the Christian dogma of the Trinity"',
]
export const synonyms = [
    'teaching',
    'belief',
    'conviction',
    'tenet',
    'principle',
    'ethic',
    'precept',
    'maxim',
    'canon',
    'law',
    'rule',
    'creed',
    'credo',
    'doctrine',
    'ideology',
    'orthodoxy',
    'certainty',
    'article of faith',
    'code of belief',
    'set of beliefs',
    'set of principles',
    'blind faith',
    'unquestioning belief',
    'invincible conviction',
    'unchallengeable conviction',
    'arrogant conviction',
    'doubt',
    'open-mindedness',
]