export const definitions = [
    '"a soiled T-shirt"',
    '"a chance to repair their soiled reputations"',
    '"he might soil his expensive suit"',
    '"what good is there in soiling your daughter\'s reputation ? "',
]
export const synonyms = [
    'dirty',
    'blacken',
    'grime',
    'begrime',
    'stain',
    'muddy',
    'splash',
    'spot',
    'spatter',
    'splatter',
    'smear',
    'smudge',
    'sully',
    'spoil',
    'defile',
    'pollute',
    'contaminate',
    'foul',
    'befoul',
    'get/make dirty',
    'get/make filthy',
    'clean',
    'keep clean',
    'damage',
    'sully',
    'injure',
    'stain',
    'blacken',
    'tarnish',
    'taint',
    'besmirch',
    'blemish',
    'defile',
    'blot',
    'smear',
    'dishonor',
    'bring discredit to',
    'drag through the mud',
]