export const definitions = [
    '"the latest doings of television stars"',
    '"someone had given her a doing"',
    '"it would take some doing to calm him down"',
]
export const synonyms = [
    'performance',
    'performing',
    'effecting',
    'execution',
    'implementation',
    'implementing',
    'discharge',
    'discharging',
    'achievement',
    'accomplishment',
    'realization',
    'completion',
    'completing',
    'acquittal',
    'effectuation',
    'exploit',
    'activity',
    'act',
    'action',
    'undertaking',
    'deed',
    'feat',
    'endeavor',
    'work',
    'venture',
    'enterprise',
    'behavior',
    'conduct',
    'handiwork',
    'carrying out',
    'bringing off',
    'effort',
    'exertion',
    'work',
    'hard work',
    'application',
    'labor',
    'toil',
    'struggle',
    'strain',
    'pains',
    'travail',
]