export const definitions = [
  '"they squatted, hunched in their habitual dolor"',
];
export const synonyms = [
  'sadness',
  'sorrow',
  'unhappiness',
  'dejection',
  'regret',
  'depression',
  'misery',
  'cheerlessness',
  'downheartedness',
  'despondency',
  'despair',
  'desolation',
  'wretchedness',
  'glumness',
  'gloom',
  'gloominess',
  'dolefulness',
  'melancholy',
  'low spirits',
  'mournfulness',
  'woe',
  'broken-heartedness',
  'heartache',
  'grief',
  'disconsolateness',
  'disconsolation',
  'dismalness',
  'heaviness of heart',
  'joy',
];