export const definitions = [
  '"the southwestern French domains of the Plantagenets"',
  '"the expanding domain of psychology"',
  '"visual communication is the domain of the graphic designer"',
];
export const synonyms = [
  'realm',
  'kingdom',
  'empire',
  'dominion',
  'province',
  'estate',
  'territory',
  'land',
  'lands',
  'dominions',
  'state',
  'country',
  'preserve',
  'zone',
  'sphere',
  'area',
  'place',
  'field',
  'area',
  'arena',
  'sphere',
  'discipline',
  'sector',
  'section',
  'region',
  'province',
  'world',
];