export const definitions = [
    '"a portion of the proceeds will be donated to charity"',
    '"all donated blood is tested for antibodies"',
]
export const synonyms = [
    'give',
    'contribute',
    'present',
    'gift',
    'subscribe',
    'hand out',
    'grant',
    'bestow',
    'pledge',
    'put up',
    'come up with',
    'accord',
    'provide',
    'supply',
    'furnish',
    'give/make a donation of',
    'make a gift of',
    'make a contribution of',
    'put oneself down for',
    'endow someone with',
    'confer on someone',
    'keep',
    'receive',
]