export const definitions = [
    '"the moving story of their doomed love affair"',
    '"fuel was spilling out of the damaged wing and the aircraft was doomed"',
    '"her plan was doomed to failure"',
]
export const synonyms = [
    'ill-fated',
    'ill-starred',
    'ill-omened',
    'star-crossed',
    'cursed',
    'jinxed',
    'foredoomed',
    'hapless',
    'damned',
    'bedeviled',
    'luckless',
    'unlucky',
    'fey',
    'destine',
    'fate',
    'predestine',
    'ordain',
    'preordain',
    'foredoom',
    'mean',
    'foreordain',
    'consign',
    'condemn',
    'sentence',
    'certain',
    'sure',
    'bound',
    'guaranteed',
    'assured',
    'under a curse',
    'very likely',
    'happy',
    'lucky',
    'promising',
]