export const definitions = [
    '"she was under sedation and a bit dopey"',
    '"did you ever hear such dopey names?"',
]
export const synonyms = [
    'dazed',
    'confused',
    'muddled',
    'befuddled',
    'bewildered',
    'disoriented',
    'disorientated',
    'stupefied',
    'groggy',
    'dizzy',
    'alert',
    'stupid',
    'foolish',
    'senseless',
    'brainless',
    'mindless',
    'idiotic',
    'imbecilic',
    'imbecile',
    'insane',
    'lunatic',
    'asinine',
    'ridiculous',
    'ludicrous',
    'absurd',
    'preposterous',
    'silly',
    'inane',
    'witless',
    'half-baked',
    'empty-headed',
    'unintelligent',
    'halfwitted',
    'slow-witted',
    'weak-minded',
    'intelligent',
]