export const definitions = [
    '"a ______ of 450 milligrams a day"',
    '"there are recommendations about ______ for elderly patients"',
]
export const synonyms = [
    'amount',
    'number',
    'total',
    'aggregate',
    'sum',
    'quota',
    'group',
    'size',
    'mass',
    'weight',
    'volume',
    'bulk',
    'load',
    'consignment',
    'expanse',
    'extent',
    'length',
    'area',
    'quantum',
    'proportion',
    'portion',
    'part',
    'dose',
]