export const definitions = [
  '"a daily douche"',
  '"the mixture may be used as an antiseptic douche or as a gargle"',
  '"that guy is such a douche"',
  '"the patient was advised to douche the nose with saline"',
];
export const synonyms = [
  'wash',
  'soak',
  'dip',
  'shower',
  'soaping',
  'sponging',
  'toilet',
  'ablution',
  'sprinkle',
  'shower',
  'spritz',
  'spatter',
  'scatter',
  'disperse',
  'diffuse',
  'mist',
  'besprinkle',
  'spread in droplets',
];