export const definitions = [
    '"a hard, dour, humorless fanatic"',
]
export const synonyms = [
    'stern',
    'unsmiling',
    'unfriendly',
    'frowning',
    'poker-faced',
    'severe',
    'forbidding',
    'morose',
    'sour',
    'gruff',
    'surly',
    'uncommunicative',
    'grim',
    'gloomy',
    'dismal',
    'sullen',
    'somber',
    'grave',
    'sober',
    'serious',
    'solemn',
    'austere',
    'stony',
    'unsympathetic',
    'disapproving',
    'mean-looking',
    'cheerful',
    'friendly',
]