export const definitions = [
  '"we are the sons and daughters of Adam"',
  '"the tennis champ was one of California\'s most famous daughters"',
  '"a daughter of the dry savannas of Africa"',
  '"Italian, the eldest daughter of ancient Latin"',
  '"as radon gas decays it produces daughters that attach themselves to dust particles"',
  '"daughter cells"',
];
export const synonyms = [
  'girl',
  'descendant',
  'offspring',
  'female child',
  'child',
  'baby',
  'infant',
  'son',
  'youngster',
  'tot',
  'descendant',
  'heir',
  'successor',
  'bairn',
  'wean',
  'pickney',
  'babe',
  'little one',
  'tiny tot',
];