export const definitions = [
    '"a dozen bottles of sherry"',
    '"she has dozens of admirers"',
]
export const synonyms = [
    'quantities',
    'plenty',
    'masses',
    'many',
    'numerous',
    'scores',
    'hundreds',
    'thousands',
    'millions',
    'billions',
    'a large amount',
    'a fair amount',
    'a good/great deal',
    'a deal',
    'a great quantity',
    'an abundance',
    'a wealth',
    'a profusion',
    'a great many',
    'a large number',
    'a considerable number',
    'a little',
    'not much',
    'a few',
    'not many',
]