export const definitions = [
    '"a long, draggy, boring Friday afternoon"',
]
export const synonyms = [
    'boring',
    'monotonous',
    'dull',
    'uninteresting',
    'unexciting',
    'unvaried',
    'unvarying',
    'mind-numbing',
    'mindless',
    'soulless',
    'humdrum',
    'dreary',
    'ho-hum',
    'mundane',
    'wearisome',
    'wearying',
    'tiresome',
    'soporific',
    'dry',
    'as dry as dust',
    'arid',
    'lifeless',
    'colorless',
    'monochrome',
    'uninspired',
    'uninspiring',
    'flat',
    'plodding',
    'slow',
    'banal',
    'vapid',
    'insipid',
    'bland',
    'lackluster',
    'prosaic',
    'run-of-the-mill',
    'pedestrian',
    'jejune',
    'leaden',
    'heavy',
    'long-drawn-out',
    'overlong',
    'long-winded',
    'prolix',
    'laborious',
    'ponderous',
    'endless',
    'interminable',
    'mechanical',
    'routine',
    'deadly dull',
    'lacking variety',
    'soul-destroying',
    'dreich',
    'exciting',
    'interesting',
]