export const definitions = [
    '"the lower stretch of the river had been dredged"',
    '"the dredging and deepening of the canal"',
    '"mud was dredged out of the harbor"',
    '"they start to dredge for oysters in November"',
    '"I don\'t understand why you had to dredge up this story"',
    '"dredge the bananas with sugar and cinnamon"',
]
export const synonyms = [
    'detect',
    'discover',
    'come across',
    'hit on',
    'encounter',
    'find',
    'find out',
    'turn up',
    'unearth',
    'dig up',
    'root out',
    'disinter',
    'extricate',
    'expose',
    'bring to light',
    'unmask',
    'unveil',
    'reveal',
    'divulge',
    'disclose',
    'betray',
    'give away',
    'smoke out',
    'uncloak',
    'stumble on/across',
    'chance on',
    'dredge up',
    'hunt out',
    'nose out',
    'ferret out',
    'grub out',
    'bring into the open',
    'lay bare',
    'make known',
    'make public',
    'conceal',
    'hide',
    'cover up',
    'sprinkle',
    'scatter',
    'powder',
    'sift',
    'spray',
    'cover',
    'spread',
    'strew',
    'dot',
    'fleck',
    'freckle',
    'dab',
    'bestrew',
    'besprinkle',
    'befleck',
]