export const definitions = [
  '"I fell in the stream and got drenched"',
  '"a severe drenching would kill his uncle"',
  '"cool patios drenched in flowers"',
  '"three-times-a-year drenching for calves"',
  '"a worming drench"',
];
export const synonyms = [
  'soak',
  'saturate',
  'wet through',
  'permeate',
  'drown',
  'swamp',
  'submerge',
  'inundate',
  'flood',
  'douse',
  'souse',
  'slosh',
  'steep',
  'bathe',
  'rinse',
  'wash',
  'wet thoroughly',
  'swill down',
  'sluice down',
  'dry',
  'flood',
  'deluge',
  'overflow',
  'overrun',
  'swamp',
  'submerge',
  'engulf',
  'drown',
  'immerse',
  'cover',
  'saturate',
  'soak',
  'amount',
  'quantity',
  'measure',
  'portion',
  'dosage',
  'draft',
  'overdose',
  'lethal dose',
];