export const definitions = [
    '"the cabin cruiser started to drift downstream"',
    '"excited voices drifted down the hall"',
    '"people began to drift away"',
    '"I\'ve just drifted into things because they were offered to me and they seemed like fun"',
    '"he was drifting in and out of consciousness"',
    '"I noticed my audience\'s attention drifting"',
    '"fallen leaves were starting to drift in the gutters"',
    '"there was a drift to the towns"',
    '"the pilot had not noticed any appreciable drift"',
    '"the drift toward a more market-oriented system of higher education"',
    '"after so much drift, any expression of enthusiasm is welcome"',
    '"maybe I\'m too close to the forest to see the trees, if you catch my drift"',
    '"he didn\'t understand much Greek, but he got her drift"',
    '"four sheep were dug out of the drift"',
    '"a drift of daffodils"',
    '"the drift led to another smaller ore chamber"',
]
export const synonyms = [
    'float',
    'bob',
    'coast',
    'meander',
    'be carried',
    'be carried (away/along)',
    'be borne',
    'be wafted',
    'move slowly',
    'go with the current',
    'stray',
    'digress',
    'depart',
    'diverge',
    'veer',
    'swerve',
    'deviate',
    'divagate',
    'get sidetracked',
    'pile up',
    'accumulate',
    'gather',
    'amass',
    'bank up',
    'heap up',
    'form heaps/drifts',
    'movement',
    'shift',
    'flow',
    'transfer',
    'transferral',
    'relocation',
    'gravitation',
    'deviation',
    'digression',
    'veering',
    'straying',
    'gist',
    'essence',
    'core',
    'meaning',
    'sense',
    'thesis',
    'substance',
    'significance',
    'signification',
    'thrust',
    'import',
    'purport',
    'tenor',
    'vein',
    'spirit',
    'implication',
    'intention',
    'direction',
    'course',
    'tendency',
    'trend',
    'pile',
    'heap',
    'bank',
    'mound',
    'mass',
    'accumulation',
    'dune',
    'ridge',
]