export const definitions = [
    '"a drippy love song"',
    '"drippy food"',
]
export const synonyms = [
    'banal',
    'trite',
    'hackneyed',
    'commonplace',
    'clichéd',
    'predictable',
    'stereotyped',
    'platitudinous',
    'inane',
    'fatuous',
    'vapid',
    'jejune',
    'weak',
    'feeble',
    'tired',
    'stale',
    'overworked',
    'overused',
    'well worn',
    'mawkish',
    'sentimental',
    'sickly',
    'sickly-sweet',
    'cloying',
    'syrupy',
    'sugary',
    'saccharine',
    'honeyed',
    'sickening',
    'nauseating',
    'choking',
    'twee',
    'mushy',
    'slushy',
    'sloppy',
    'schmaltzy',
    'cutesy',
    'cute',
    'gooey',
    'treacly',
    'icky',
    'sick-making',
    'truistic',
    'bromidic',
    'oversweet',
    'toe-curling',
    'original',
]