export const definitions = [
    '"two fishermen were drowned when their motorboat capsized"',
    '"she drowned in the pond"',
    '"they committed suicide by jumping into the sea and drowning themselves"',
    '"when the ice melted the valleys were drowned"',
    '"his voice was drowned out by the approaching engine noise"',
    '"both business and household sectors are drowning in debt"',
    '"art dealers are still drowning in a sea of paperwork"',
    '"good pizza is not eight inches thick and drowned in tomato sauce"',
]
export const synonyms = [
    'go under',
    'suffocate in water',
    'inhale water',
    'go to a watery grave',
    'flood',
    'submerge',
    'immerse',
    'inundate',
    'deluge',
    'swamp',
    'engulf',
    'drench',
    'soak',
    'cover',
    'saturate',
    'drain',
    'overpower',
    'overwhelm',
    'overcome',
    'override',
    'engulf',
    'devour',
    'bury',
    'muffle',
    'deaden',
    'stifle',
    'wipe out',
    'extinguish',
    'silence',
    'make inaudible',
    'drown out',
    'be louder than',
    'swallow up',
    'augment',
]