export const definitions = [
  '"the German gun crews kept in their dugouts"',
];
export const synonyms = [
  'pit',
  'ditch',
  'trench',
  'cavity',
  'crater',
  'depression',
  'hollow',
  'well',
  'borehole',
  'excavation',
  'shaft',
  'mineshaft',
  'cave',
  'cavern',
  'pothole',
  'chamber',
  'gorge',
  'chasm',
  'canyon',
  'ravine',
];