export const definitions = [
  '"record the dulcet tones of your family and friends"',
];
export const synonyms = [
  'sweet',
  'sweet-sounding',
  'mellifluous',
  'euphonious',
  'soothing',
  'mellow',
  'honeyed',
  'pleasant',
  'agreeable',
  'melodious',
  'melodic',
  'tuneful',
  'musical',
  'lilting',
  'lyrical',
  'harmonious',
  'silvery',
  'bell-like',
  'golden',
  'mellifluent',
  'silver-toned',
  'harsh',
];