export const definitions = [
  '"confessions extracted under duress"',
];
export const synonyms = [
  'coercion',
  'compulsion',
  'force',
  'pressure',
  'pressurization',
  'intimidation',
  'threats',
  'constraint',
  'enforcement',
  'exaction',
  'free will',
  'coercion',
  'force',
  'compulsion',
  'constraint',
  'oppression',
  'enforcement',
  'insistence',
  'demand',
  'entreaty',
  'goading',
  'pestering',
  'provocation',
  'harassment',
  'nagging',
  'harrying',
  'badgering',
  'intimidation',
  'arm-twisting',
  'pressurization',
  'persuasion',
  'influence',
  'imprisonment',
  'internment',
  'confinement',
  'detention',
  'custody',
  'captivity',
  'restraint',
  'penal servitude',
  'hard labor',
  'durance',
  'freedom',
];