export const definitions = [
    '"the tide began to ebb"',
    '"my enthusiasm was ebbing away"'
]
export const synonyms = [
    'recede',
    'go out',
    'retreat',
    'draw back',
    'fall back',
    'fall away',
    'abate',
    'subside',
    'retrocede',
    'flow back',
    'come in',
    'diminish',
    'dwindle',
    'wane',
    'fade away',
    'decline',
    'flag',
    'let up',
    'lessen',
    'decrease',
    'weaken',
    'dissolve',
    'disappear',
    'come to an end',
    'deteriorate',
    'decay',
    'degenerate',
    'remit',
    'abatement',
    'subsiding',
    'easing',
    'waning',
    'dwindling',
    'de-escalation',
    'diminution',
    'diminishing',
    'lessening',
    'melt away',
    'peter out',
    'die away',
    'die down',
    'die out',
    'petering out',
    'dying away',
    'dying down',
    'dying out',
    'fading away',
    'increase',
    'intensify',
    'intensification',
]