export const definitions = [
    '"he became edgy and defensive"',
    '"tremendously edgy brass playing"',
    '"their songs combine good music and smart, edgy ideas"'
]
export const synonyms = [
    'tense',
    'nervous',
    'on edge',
    'highly strung',
    'anxious',
    'apprehensive',
    'uneasy',
    'ill at ease',
    'unsettled',
    'unstable',
    'excitable',
    'twitchy',
    'jumpy',
    'keyed up',
    'fidgety',
    'restive',
    'skittish',
    'neurotic',
    'brittle',
    'hysterical',
    'sensitive',
    'insecure',
    'irritable',
    'touchy',
    'tetchy',
    'testy',
    'crotchety',
    'irascible',
    'peevish',
    'querulous',
    'bad-tempered',
    'short-tempered',
    'hot-tempered',
    'quick-tempered',
    'temperamental',
    'snappy',
    'captious',
    'crabbed',
    'prickly',
    'nervy',
    'calm',
]