export const definitions = [
  '"the article is an edited version of a lecture paper"',
  '"edited highlights of the game"',
  '"Volume I was edited by J. Johnson"',
  '"you could edit together a succession of short clips"',
  '"the story was ruthlessly edited down to its allotted span"',
  '"the footage wasn\'t good enough to be edited into broadcast form"',
  '"the film\'s sexually explicit scenes have been edited out"',
  '"he began to edit the magazine in 1923"',
  '"in recent years, scientists have sought more precise ways to edit the genome"',
];
export const synonyms = [
  'correct',
  'check',
  'copyedit',
  'improve',
  'revise',
  'emend',
  'polish',
  'modify',
  'adapt',
  'rewrite',
  'reword',
  'rework',
  'rescript',
  'redraft',
  'rephrase',
  'assemble',
  'shorten',
  'condense',
  'cut',
  'abridge',
  'approve',
  'censor',
  'redact',
  'select',
  'choose',
  'organize',
  'put together',
  'arrange',
  'rearrange',
  'prepare for publication',
  'select',
  'choose',
  'assemble',
  'organize',
  'put together',
  'arrange',
  'rearrange',
  'amend',
  'emend',
  'correct',
  'alter',
  'change',
  'adapt',
  'copyedit',
  'rewrite',
  'redraft',
  'rescript',
  'recast',
  'rephrase',
  'rework',
  'update',
  'revamp',
  'preserve',
  'delete',
  'strike out',
  'cancel',
  'blue-pencil',
  'erase',
  'efface',
  'take out',
  'remove',
  'cut out',
  'cut',
  'expunge',
  'eliminate',
  'expurgate',
  'bowdlerize',
  'dele',
  'cross out',
  'cross through',
  'score out',
  'scratch out',
  'put a line through',
  'ink out',
  'edit out',
  'blank out',
  'add',
  'control',
  'direct',
  'run',
  'manage',
  'head',
  'lead',
  'supervise',
  'superintend',
  'oversee',
  'be the editor of',
  'control the content of',
  'be in charge of',
  'be responsible for',
  'be at the helm of',
  'be chief of',
  'preside over',
  'be the boss of',
];