export const definitions = [
  '"an eerie green glow in the sky"',
];
export const synonyms = [
  'uncanny',
  'sinister',
  'ghostly',
  'spectral',
  'unnatural',
  'unearthly',
  'preternatural',
  'supernatural',
  'otherworldly',
  'unreal',
  'mysterious',
  'strange',
  'abnormal',
  'odd',
  'curious',
  'queer',
  'weird',
  'bizarre',
  'freakish',
  'frightening',
  'spine-chilling',
  'hair-raising',
  'blood-curdling',
  'scaring',
  'terrifying',
  'petrifying',
  'chilling',
  'eldritch',
  'normal',
  'reassuring',
];