export const definitions = [
    '"the lethal effects of hard drugs"',
    '"politicians really do have some effect on the lives of ordinary people"',
    '"wind power can be used to great effect"',
    '"the Doppler effect"',
    '"gentle music can have a soothing effect"',
    '"the production relied too much on spectacular effects"',
    '"the insurance covers personal effects"',
    '"nature always effected a cure"',
    '"budget cuts that were quietly effected over four years"'
]
export const synonyms = [
    'affect',
    'influence',
    'act on',
    'work on',
    'condition',
    'touch',
    'attack',
    'infect',
    'strike',
    'hit',
    'change',
    'alter',
    'modify',
    'transform',
    'form',
    'shape',
    'control',
    'govern',
    'determine',
    'decide',
    'guide',
    'sway',
    'bias',
    'result',
    'consequence',
    'upshot',
    'outcome',
    'outturn',
    'sequel',
    'reaction',
    'repercussions',
    'reverberations',
    'ramifications',
    'end result',
    'conclusion',
    'termination',
    'culmination',
    'denouement',
    'corollary',
    'concomitant',
    'aftermath',
    'footprint',
    'fruit(s)',
    'product',
    'byproduct',
    'sequelae',
    'issue',
    'success',
    'exert influence on',
    'interact with',
    'have an impact on',
    'impact on',
    'take hold of',
    'strike at',
    'cause',
    'force',
    'operation',
    'enforcement',
    'implementation',
    'execution',
    'action',
    'effectiveness',
    'validity',
    'lawfulness',
    'legality',
    'legitimacy',
    'authenticity',
    'implement',
    'apply',
    'put into action',
    'execute',
    'enact',
    'carry out',
    'carry through',
    'perform',
    'administer',
    'fulfill',
    'discharge',
    'accomplish',
    'bring about',
    'achieve',
    'realize',
    'contrive',
    'enforce',
    'impose',
    'effectuate',
    'come into operation',
    'begin',
    'work',
    'act',
    'legal acceptability',
    'put into practice',
    'come into force',
    'come into being',
    'become operative',
    'become valid',
    'become law',
    'be applied',
    'be effective',
    'produce results',
    'have the desired effect',
    'be efficacious',
    'lapse',
    'wear off',
    'impact',
    'action',
    'effectiveness',
    'efficacy',
    'efficaciousness',
    'influence',
    'power',
    'potency',
    'strength',
    'usefulness',
    'success',
    'belongings',
    'possessions',
    'goods',
    'worldly goods',
    'chattels',
    'goods and chattels',
    'accoutrements',
    'appurtenances',
    'property',
    'paraphernalia',
    'luggage',
    'baggage',
    'rubbish',
    'personal possessions',
    'personal effects',
    'achieve',
    'accomplish',
    'carry out',
    'realize',
    'attain',
    'manage',
    'bring off',
    'carry off',
    'carry through',
    'execute',
    'conduct',
    'fix',
    'engineer',
    'perform',
    'do',
    'perpetrate',
    'discharge',
    'fulfill',
    'complete',
    'finish',
    'consummate',
    'conclude',
    'cause',
    'bring about',
    'initiate',
    'create',
    'produce',
    'make',
    'give rise to',
    'provoke',
    'call forth',
    'occasion',
    'generate',
    'originate',
    'engender',
    'precipitate',
    'actuate',
    'wreak',
    'kindle',
    'effectuate',
    'succeed in',
    'cause to happen/occur',
    'put in place',
    'bring to pass',
]