export const definitions = [
    '"effete trendies from art college"',
    '"he chatted away, exercising his rather effete charm"',
    '"the authority of an effete aristocracy began to dwindle"'
]
export const synonyms = [
    'affected',
    'over-refined',
    'ineffectual',
    'artificial',
    'studied',
    'pretentious',
    'precious',
    'chi-chi',
    'flowery',
    'mannered',
    'alembicated',
    'unpretentious',
    'effeminate',
    'unmasculine',
    'unmanly',
    'womanish',
    'girlish',
    'feminine',
    'weak',
    'soft',
    'timid',
    'timorous',
    'fearful',
    'cowardly',
    'lily-livered',
    'spineless',
    'craven',
    'pusillanimous',
    'chicken-hearted',
    'weak-kneed',
    'limp-wristed',
    'pansyish',
    'manly',
    'weakened',
    'enfeebled',
    'enervated',
    'worn out',
    'exhausted',
    'finished',
    'burnt out',
    'drained',
    'spent',
    'powerless',
    'played out',
    'powerful',
]