export const definitions = [
    '"he liked to boast and she would egg him on shamelessly"'
]
export const synonyms = [
    'urge',
    'goad',
    'incite',
    'provoke',
    'prick',
    'sting',
    'propel',
    'push',
    'drive',
    'prod',
    'prompt',
    'induce',
    'impel',
    'cheer on',
    'encourage',
    'exhort',
    'stimulate',
    'motivate',
    'galvanize',
    'inspire',
    'stir',
    'incentivize',
    'spur on',
    'act as a stimulus to',
    'act as an incentive to',
]