export const definitions = [
  '"they invariably elicit exclamations of approval from guests"',
  '"a corrupt heart elicits in an hour all that is bad in us"',
];
export const synonyms = [
  'obtain',
  'bring out',
  'draw out',
  'extract',
  'evoke',
  'bring about',
  'bring forth',
  'induce',
  'excite',
  'give rise to',
  'call forth',
  'prompt',
  'generate',
  'engender',
  'trigger',
  'kindle',
  'extort',
  'exact',
  'wrest',
  'derive',
  'provoke',
  'wring',
  'screw',
  'squeeze',
  'spark off',
  'cause',
  'induce',
  'provoke',
  'create',
  'generate',
  'engender',
  'foster',
  'encourage',
  'call forth',
  'draw',
  'attract',
  'incite',
  'bring on',
  'arouse',
  'tempt',
  'court',
  'allure',
  'entice',
  'lead to',
  'make happen',
  'bring on oneself',
];