export const definitions = [
  '"he had an operation to remove a nail embedded in his chest"',
  '"the Victorian values embedded in Tennyson\'s poetry"',
  '"phrases or clauses that are embedded in a sentence for effect"',
  '"you can embed the videos into a blog post."',
  '"to embed the controller, he has to get creative"',
  '"the CNN correspondent is now embedded with the US Navy aboard the USS Constellation"',
  '"most of the embeds found themselves covering construction and civil works projects"',
];
export const synonyms = [
  'implant',
  'plant',
  'set',
  'fix',
  'lodge',
  'root',
  'insert',
  'place',
  'sink',
  'submerge',
  'immerse',
  'drive in',
  'hammer in',
  'ram in',
];