export const definitions = [
    '"black ravens emerged from the fog"',
    '"Philadelphia has emerged as the clear favorite"',
    '"a world of emerging economic giants"',
    '"reports of a deadlock emerged during preliminary discussions"',
    '"during the trial it emerged that she had been suffering from a rare personality disorder"',
    '"the economy has started to emerge from recession"'
]
export const synonyms = [
    'come out',
    'appear',
    'make an appearance',
    'turn up',
    'come up',
    'surface',
    'crop up',
    'pop up',
    'materialize',
    'arise',
    'proceed',
    'issue',
    'emanate',
    'come into view',
    'become visible',
    'spring up',
    'manifest oneself',
    'come forth',
    'disappear',
    'come to light',
    'come out',
    'transpire',
    'unfold',
    'turn out',
    'get around',
    'become known',
    'become apparent',
    'become evident',
    'be revealed',
    'come to the fore',
    'enter the picture',
    'prove to be the case',
    'become common knowledge',
]