export const definitions = [
    '"Soviet émigrés and defectors"',
    '"émigré life"'
]
export const synonyms = [
    'stranger',
    'visitor',
    'nonmember',
    'foreigner',
    'alien',
    'outlander',
    'immigrant',
    'emigrant',
    'newcomer',
    'parvenu',
    'arriviste',
    'interloper',
    'intruder',
    'gatecrasher',
    'outcast',
    'misfit',
    'individualist',
    'nonconformist',
    'free spirit',
    'original',
    'bohemian',
    'eccentric',
    'maverick',
    'rebel',
    'dissenter',
    'dissident',
    'odd man out',
    'incomer',
    'unorthodox person',
]