export const definitions = [
    '"the Roman Empire"',
    '"he encouraged the Greeks in their dream of empire in Asia Minor"',
    '"her business empire grew"',
    '"each ministry, each department had its own empire, its own agenda and worked to protect its turf"'
]
export const synonyms = [
    'kingdom',
    'realm',
    'domain',
    'territory',
    'province',
    'commonwealth',
    'federation',
    'confederation',
    'power',
    'world power',
    'superpower',
    'jurisdiction',
    'res publica',
    'organization',
    'corporation',
    'multinational',
    'conglomerate',
    'consortium',
    'company',
    'business',
    'firm',
    'operation',
    'institution',
    'establishment',
    'body',
]