export const definitions = [
  '"the firm employs 150 people"',
  '"temps can be employed to do much of the work"',
  '"most of the newcomers are employed in developing the technology into a product"',
  '"the methods they have employed to collect the data"',
  '"I started work in the employ of a grocer and wine merchant"',
  '"her place of employ"',
];
export const synonyms = [
  'hire',
  'engage',
  'recruit',
  'take on',
  'sign up',
  'sign',
  'enroll',
  'appoint',
  'commission',
  'enlist',
  'retain',
  'indenture',
  'apprentice',
  'take into employment',
  'secure the services of',
  'put on the payroll',
  'have in employment',
  'have on the payroll',
  'dismiss',
  'occupy',
  'engage',
  'involve',
  'tie up',
  'absorb',
  'engross',
  'immerse',
  'keep busy',
  'use',
  'utilize',
  'make use of',
  'implement',
  'apply',
  'exercise',
  'practice',
  'exert',
  'bring into play',
  'draw on',
  'turn to',
  'take advantage of',
  'avail oneself of',
  'put into service',
  'put into practice',
  'bring into action',
  'bring to bear',
  'resort to',
  'have recourse to',
  'job',
  'post',
  'position',
  'situation',
  'day job',
  'occupation',
  'profession',
  'trade',
  'livelihood',
  'career',
  'business',
  'line',
  'calling',
  'vocation',
  'craft',
  'pursuit',
  'work',
  'labor',
  'service',
  'métier',
  'line of work',
];