export const definitions = [
    '"the evidence would enable us to arrive at firm conclusions"',
    '"a number of courses are available to enable an understanding of a broad range of issues"',
    '"you can enable compression or even virus scanning prior to backup"'
]
export const synonyms = [
    'authorize',
    'sanction',
    'warrant',
    'license',
    'qualify',
    'allow',
    'permit',
    'entitle',
    'empower',
    'accredit',
    'legalize',
    'validate',
    'commission',
    'delegate',
    'let',
    'equip',
    'prepare',
    'facilitate',
    'capacitate',
    'fit',
    'give the means to',
    'give the resources to',
    'forbid',
    'prevent',
    'allow',
    'permit',
    'authorize',
    'sanction',
    'grant',
    'warrant',
    'license',
    'empower',
    'entitle',
    'tolerate',
    'countenance',
    'suffer',
    'brook',
    'cause',
    'make',
    'give permission to',
    'give leave to',
    'grant the right to',
    'assent to',
    'consefnt to',
    'agree to',
    'acquiesce in',
    'accede to',
    'approve of',
    'admit of',
    'give one\'s blessing to',
    'give assent to',
    'prevent',
    'prohibit',
]