export const definitions = [
  '"each was encased in a plastic shrink-wrap"',
];
export const synonyms = [
  'surround',
  'cover',
  'enfold',
  'enwrap',
  'blanket',
  'swathe',
  'swaddle',
  'wrap (up)',
  'engulf',
  'encircle',
  'encompass',
  'cocoon',
  'sheathe',
  'enclose',
  'cloak',
  'conceal',
  'hide',
  'obscure',
  'cover (up)',
  'screen',
  'shield',
  'mask',
  'veil',
  'shroud',
  'mantle',
  'enshroud',
  'obnubilate',
];