export const definitions = [
  '"it seemed impossible that anyone could endure such pain"',
  '"these cities have endured through time"',
];
export const synonyms = [
  'undergo',
  'go through',
  'live through',
  'experience',
  'meet',
  'encounter',
  'face',
  'face up to',
  'handle',
  'suffer',
  'tolerate',
  'put up with',
  'brave',
  'bear',
  'withstand',
  'sustain',
  'weather',
  'make the best of',
  'thole',
  'go along with',
  'countenance',
  'accept',
  'brook',
  'support',
  'take',
  'cope with',
  'deal with',
  'become reconciled to',
  'reconcile oneself to',
  'become resigned to',
  'get used to',
  'become accustomed to',
  'learn to live with',
  'submit to',
  'give one\'s blessing to',
  'last',
  'live',
  'live on',
  'go on',
  'hold on',
  'abide',
  'continue',
  'persist',
  'remain',
  'stay',
  'survive',
  'bide',
  'tarry',
  'lasting',
  'long-lasting',
  'durable',
  'continuing',
  'remaining',
  'persisting',
  'prevailing',
  'abiding',
  'eternal',
  'perennial',
  'permanent',
  'unending',
  'everlasting',
  'constant',
  'stable',
  'steady',
  'steadfast',
  'fixed',
  'firm',
  'unwavering',
  'unfaltering',
  'unchanging',
  'changeless',
  'long-standing',
  'long-established',
  'long-running',
  'long-term',
  'perdurable',
  'sempiternal',
  'fade',
  'short-lived',
];