export const definitions = [
    '"he shut off the engine and silence enfolded them"',
    '"he enfolded her in his arms and stroked her hair"'
]
export const synonyms = [
    'envelop',
    'engulf',
    'sheathe',
    'swathe',
    'swaddle',
    'cocoon',
    'shroud',
    'veil',
    'cloak',
    'drape',
    'cover',
    'conceal',
    'mask',
    'surround',
    'encircle',
    'circle',
    'enclose',
    'encase',
    'enshroud',
    'mantle',
    'pall',
    'pave',
    'lap',
    'obnubilate',
    'clasp',
    'hold',
    'fold',
    'wrap',
    'squeeze',
    'clutch',
    'take',
    'gather',
    'embrace',
    'hug',
    'cuddle',
    'cradle',
    'embosom',
    'strain',
]