export const definitions = [
    '"railroads engirdled this tract of country"'
]
export const synonyms = [
    'surround',
    'circle',
    'ring',
    'encompass',
    'encircle',
    'circumscribe',
    'border',
    'bound',
    'edge',
    'skirt',
    'fringe',
    'hem',
    'line',
    'flank',
    'confine',
    'close in',
    'shut in',
    'hem in',
    'lock in',
    'lock up',
    'cut off',
    'gird',
    'girdle',
    'engird',
    'fence in',
    'wall in',
    'hedge in',
]