export const definitions = [
  '"Joe enjoys reading Icelandic family sagas"',
  '"I could never enjoy myself, knowing you were in your room alone"',
  '"Bake until the filling starts to bubble and the crust turns golden brown. Enjoy!"',
  '"the security forces enjoy legal immunity from prosecution"',
];
export const synonyms = [
  'like',
  'love',
  'appreciate',
  'relish',
  'adore',
  'savor',
  'be fond of',
  'be entertained by',
  'be amused by',
  'be pleased by',
  'find/take pleasure in',
  'be keen on',
  'delight in',
  'rejoice in',
  'revel in',
  'lap up',
  'luxuriate in',
  'bask in',
  'wallow in',
  'glory in',
  'dislike',
  'hate',
  'live',
  'party',
  'make merry',
  'celebrate',
  'revel',
  'roister',
  'have fun',
  'have a good time',
  'enjoy life',
  'be happy',
  'live life to the full',
  'have the time of one\'s life',
  'be miserable',
  'have',
  'possess',
  'own',
  'boast',
  'benefit from',
  'have the benefit of',
  'reap the benefits of',
  'have the advantage',
  'have the use of',
  'have available',
  'avail oneself of',
  'be blessed with',
  'be favored with',
  'be endowed with',
  'be born with',
  'be possessed of',
  'participate of',
  'lack',
];