export const definitions = [
  '"decades of enmity between the two countries"',
  '"family feuds and enmities"',
];
export const synonyms = [
  'hostility',
  'animosity',
  'antagonism',
  'friction',
  'antipathy',
  'animus',
  'opposition',
  'dissension',
  'rivalry',
  'feud',
  'conflict',
  'discord',
  'contention',
  'acrimony',
  'bitterness',
  'rancor',
  'resentment',
  'aversion',
  'dislike',
  'ill feeling',
  'ill will',
  'bad blood',
  'hatred',
  'hate',
  'loathing',
  'detestation',
  'abhorrence',
  'odium',
  'malice',
  'spite',
  'spitefulness',
  'venom',
  'malevolence',
  'malignity',
  'grudges',
  'grievances',
  'bad feeling',
  'friendship',
  'goodwill',
];