export const definitions = [
  '"the students were enraged at these new rules"',
];
export const synonyms = [
  'anger',
  'incense',
  'infuriate',
  'madden',
  'inflame',
  'incite',
  'antagonize',
  'provoke',
  'ruffle someone\'s feathers',
  'exasperate',
  'empurple',
  'irate',
  'furious',
  'infuriated',
  'angered',
  'incensed',
  'raging',
  'incandescent',
  'fuming',
  'ranting',
  'raving',
  'seething',
  'frenzied',
  'beside oneself',
  'outraged',
  'hostile',
  'antagonistic',
  'black',
  'dark',
  'wrathful',
  'ireful',
  'wroth',
  'rub up the wrong way',
  'very angry',
  'in a temper',
  'in a frenzy',
  'in high dudgeon',
  'placate',
  'please',
  'calm',
  'good-humored',
];