export const definitions = [
    '"my plans are to travel the entire world"',
    '"an ideological system with which he is in entire agreement"'
]
export const synonyms = [
    'whole',
    'complete',
    'total',
    'full',
    'continuous',
    'unbroken',
    'uninterrupted',
    'undivided',
    'partial',
    'intact',
    'unbroken',
    'undamaged',
    'unharmed',
    'unimpaired',
    'unflawed',
    'unscathed',
    'unspoiled',
    'unblemished',
    'unmarked',
    'perfect',
    'inviolate',
    'in one piece',
    'sound',
    'solid',
    'unmutilated',
    'broken',
    'partial',
    'absolute',
    'total',
    'utter',
    'out-and-out',
    'thorough',
    'thoroughgoing',
    'wholehearted',
    'unqualified',
    'unreserved',
    'unmitigated',
    'unmixed',
    'unalloyed',
    'unrestricted',
    'perfect',
    'outright',
    'pure',
    'sheer',
    'unmodified',
    'partial',
    'qualified',
]