export const definitions = [
    '"meat and fish entrées are served with your choice of pasta, house salad, or vegetable of the day"',
    '"I was getting fries with my entrée"',
    '"they have to make an appetizer, entree, and dessert"',
    '"I didn\'t have any alcohol, no entree, just a steak"',
    '"an actress with an entrée into the intellectual society of Berlin"',
    '"her beauty and charm rapidly gained her entrée to high society"',
    '"their connections and relative wealth gave them entree to all of the most select entertainments"'
]
export const synonyms = [
    'main course',
    'main dish',
    'main meal',
    'starter',
    'dessert',
    'entrance',
    'entry',
    'ingress',
    'route',
    'path',
    'avenue',
    'way',
    'key',
    'passport',
    'access',
    'admission',
    'admittance',
    'acceptance',
    'means of entry',
    'opportunity to enter',
    'right of entry',
]