export const definitions = [
    '"the UN special envoy to Yugoslavia"',
    '"a peace envoy"'
]
export const synonyms = [
    'representative',
    'delegate',
    'deputy',
    'agent',
    'intermediary',
    'mediator',
    'negotiator',
    'proxy',
    'surrogate',
    'liaison',
    'broker',
    'courier',
    'spokesperson',
    'spokesman',
    'spokeswoman',
    'mouthpiece',
    'stand-in',
    'factor',
    'accredited messenger',
    'ambassador',
    'emissary',
    'diplomat',
    'legate',
    'consul',
    'attaché',
    'chargé \'affaires',
    'plenipotentiary',
    'nuncio',
]