export const definitions = [
    '"the book jacket enwraps a plain blue paper binding"',
    '"they were enwrapped in conversation"'
]
export const synonyms = [
    'envelop',
    'surround',
    'swathe',
    'enfold',
    'cover',
    'cover up',
    'conceal',
    'hide',
    'secrete',
    'camouflage',
    'disguise',
    'mask',
    'screen',
    'shield',
    'cloak',
    'blanket',
    'shroud',
    'canopy',
    'overlay',
    'obscure',
    'shade',
    'shadow',
    'eclipse',
    'cloud',
    'block out',
    'obliterate',
    'overshadow',
    'enshroud',
    'mantle',
    'bedim',
    'becloud',
    'befog',
    'obnubilate',
    'blot out',
    'blank out',
    'benight',
    'unveil',
    'expose',
    'uncover',
]