export const definitions = [
    '"the Victorian epoch"',
    '"welfare reform was an epoch in the history of U.S. social policy"',
    '"the Pliocene epoch"'
]
export const synonyms = [
    'era',
    'age',
    'period',
    'time',
    'eon',
    'span',
    'stage',
    'date',
    'point in history',
    'era',
    'age',
    'period',
    'time',
    'eon',
    'span',
    'stage',
    'date',
    'point in history',
    'era',
    'age',
    'period',
    'time',
    'eon',
    'span',
    'stage',
    'date',
    'point in history',
]