export const definitions = [
    '"the strictest possible action should be taken against the erring officials"',
    '"the judge had erred in ruling that the evidence was inadmissible"',
    '"he has erred and strayed as many of us have"'
]
export const synonyms = [
    'offending',
    'guilty',
    'culpable',
    'misbehaving',
    'delinquent',
    'lawless',
    'lawbreaking',
    'criminal',
    'transgressing',
    'aberrant',
    'deviant',
    'errant',
    'sinning',
    'innocent',
    'well behaved',
    'mistake',
    'blunder',
    'misjudge',
    'miscalculate',
    'get the wrong end of the stick',
    'make a mistake',
    'be wrong',
    'be in error',
    'be mistaken',
    'make a blunder',
    'be incorrect',
    'be inaccurate',
    'get things/something/it wrong',
    'bark up the wrong tree',
    'be wide of the mark',
    'be right',
    'misbehave',
    'do wrong',
    'go wrong',
    'act up',
    'sin',
    'go astray',
    'transgress',
    'trespass',
    'fall from grace',
    'lapse',
    'degenerate',
    'fool around',
    'behave badly',
    'misconduct oneself',
    'be bad',
    'be naughty',
    'get up to mischief',
    'get up to no good',
    'act badly',
    'give someone trouble',
    'cause someone trouble',
    'clown around',
    'act the clown',
    'act the fool',
    'act the goat',
    'act foolishly',
    'forget oneself',
]