export const definitions = [
    '"he appealed to the crowd to eschew violence"'
]
export const synonyms = [
    'give up',
    'forgo',
    'forswear',
    'shun',
    'renounce',
    'swear off',
    'abjure',
    'steer clear of',
    'fight shy of',
    'relinquish',
    'reject',
    'disavow',
    'abandon',
    'deny',
    'gainsay',
    'disclaim',
    'repudiate',
    'spurn',
    'abnegate',
    'abdicate',
    'wash one\'s hands of',
    'drop',
    'disaffirm',
    'forsake',
    'abstain from',
    'refrain from',
    'have nothing to do with',
    'give a wide berth to',
    'dispense with',
    'renege on',
    'indulge in',
]