export const definitions = [
  '"a misjudged essay"',
  '"essay a smile"',
];
export const synonyms = [
  'article',
  'composition',
  'study',
  'paper',
  'dissertation',
  'assignment',
  'thesis',
  'discourse',
  'treatise',
  'text',
  'tract',
  'disquisition',
  'monograph',
  'leader',
  'commentary',
  'critique',
  'criticism',
  'exposition',
  'appraisal',
  'assessment',
  'discussion',
  'theme',
  'piece of writing',
  'attempt',
  'effort',
  'endeavor',
  'try',
  'venture',
  'trial',
  'experiment',
  'undertaking',
  'attempt',
  'try',
  'strive',
  'aim',
  'venture',
  'endeavor',
  'seek',
  'set out',
  'do one\'s best',
  'do one\'s utmost',
  'make an effort',
  'make every effort',
  'spare no effort',
  'have a go at',
  'undertake',
  'try one\'s hand at',
  'try out',
  'take on',
  'make an attempt at',
  'do all one can',
  'give one\'s all',
  'take it on oneself',
  'embark on',
];