export const definitions = [
  '"he was held in high esteem by colleagues"',
  '"many of these qualities are esteemed by managers"',
  '"I should esteem it a favor if you could speak to them"',
];
export const synonyms = [
  'respect',
  'admiration',
  'estimation',
  'acclaim',
  'approbation',
  'approval',
  'appreciation',
  'favor',
  'popularity',
  'recognition',
  'veneration',
  'awe',
  'reverence',
  'deference',
  'honor',
  'praise',
  'adulation',
  'extolment',
  'homage',
  'laudation',
  '(high) regard',
  '(high/good) opinion',
  'disrespect',
  'respect',
  'admire',
  'value',
  'regard',
  'acclaim',
  'appreciate',
  'like',
  'prize',
  'treasure',
  'favor',
  'recognize',
  'venerate',
  'look up to',
  'revere',
  'reverence',
  'honor',
  'praise',
  'adulate',
  'extol',
  'hold in (high) regard',
  'think (highly) of',
  'approve of',
  'hold in awe',
  'pay homage to',
  'disparage',
  'consider',
  'deem',
  'think',
  'reckon',
  'count',
  'account',
  'believe',
  'judge',
  'adjudge',
  'rate',
  'gauge',
  'regard as',
  'hold to be',
  'think of as',
  'class as',
  'look on as',
  'view as',
  'see as',
  'interpret as',
];