export const definitions = [
  '"aquatint is a process of achieving tone by etching a metal plate"',
  '"the gallery has 12,000 prints engraved and etched by celebrated masters"',
  '"the image is etched into the metal plate"',
  '"tiny droplets in the glaze emulsion were etched away by acid"',
  '"ballistic electron emission microscopy is used to etch templates for even smaller circuits"',
  '"her initials were etched on the table"',
  '"his name is etched in baseball history"',
  '"a Pictish stone etched with mysterious designs"',
  '"her face was etched with tiredness"',
  '"Jo watched the outline of the town etched against the sky"',
  '"the events remain etched in the minds of all who witnessed them"',
  '"semiconductor production processes such as plasma etch"',
  '"acetic acid gives a more selective etch"',
];
export const synonyms = [
  'engrave',
  'carve',
  'inscribe',
  'cut (in)',
  'incise',
  'chisel',
  'chase',
  'score',
  'notch',
  'imprint',
  'impress',
  'deboss',
  'stamp',
  'print',
  'mark',
  'corrode',
  'burn into',
  'bite into',
  'eat into/away',
  'carve',
  'engrave',
  'incise',
  'score',
  'chisel',
  'whittle',
  'carve',
  'inscribe',
  'cut (in)',
  'incise',
  'chisel',
  'chase',
  'score',
  'imprint',
  'impress',
  'print',
  'mark',
  'outline',
  'delineate',
  'define',
  'demarcate',
  'delimit',
  'mark off',
  'trace',
  'stand out',
];