export const definitions = [
  '"the merchant can be euchred out of his caftan by hard bargaining"',
];
export const synonyms = [
  'wreck',
  'ruin',
  'spoil',
  'disrupt',
  'undo',
  'upset',
  'play havoc with',
  'make a mess of',
  'put an end to',
  'end',
  'put a stop to',
  'terminate',
  'prevent',
  'frustrate',
  'blight',
  'crush',
  'quell',
  'quash',
  'dash',
  'scotch',
  'shatter',
  'vitiate',
  'blast',
  'devastate',
  'demolish',
  'sabotage',
  'torpedo',
  'cook someone\'s goose',
  'bring to naught',
  'bring to an end',
  'upset someone\'s apple cart',
  'raise',
  'deceive',
  'trick',
  'play a trick on',
  'hoax',
  'dupe',
  'take in',
  'mislead',
  'delude',
  'hoodwink',
  'bluff',
  'beguile',
  'gull',
  'make a fool of',
  'outwit',
  'swindle',
  'defraud',
  'cheat',
  'double-cross',
  'cozen',
  'sharp',
  'mulct',
];