export const definitions = [
  '"his good friend delivered a brief eulogy"',
];
export const synonyms = [
  'accolade',
  'panegyric',
  'paean',
  'encomium',
  'tribute',
  'testimonial',
  'compliment',
  'commendation',
  'praise',
  'acclaim',
  'acclamation',
  'raving',
  'homage',
  'plaudits',
  'bouquets',
  'extolment',
  'laudation',
  'eulogium',
  'speech of praise',
  'attack',
];