export const definitions = [
    '"the company has evolved into a major chemical manufacturer"',
    '"the Gothic style evolved steadily and naturally from the Romanesque"',
    '"each school must evolve its own way of working"',
    '"the populations are cut off from each other and evolve independently"',
    '"the energy evolved during this chemical change is transferred to water"'
]
export const synonyms = [
    'develop',
    'progress',
    'advance',
    'mature',
    'grow',
    'unfold',
    'unroll',
    'expand',
    'enlarge',
    'spread',
    'extend',
    'alter',
    'change',
    'transform',
    'adapt',
    'metamorphose',
    'differentiate',
    'transmogrify',
    'make progress',
    'move forward',
    'make headway',
    'open out',
    'emit',
    'yield',
    'discharge',
    'release',
    'produce',
    'give off',
]