export const definitions = [
    '"they work every day except Sunday"',
    '"I was naked except for my socks"',
    '"I didn\'t tell him anything, except that I needed the money"',
    '"our berets were the same except mine had a leather band inside"',
    '"she never offered advice, except it were asked of her"',
    '"he excepted from his criticism a handful of distinguished writers"'
]
export const synonyms = [
    'excluding',
    'excepting',
    'omitting',
    'but',
    'besides',
    'barring',
    'bar',
    'other than',
    'saving',
    'save',
    'apart from',
    'aside from',
    'with the exception of',
    'forbye',
    'not including',
    'leaving out',
    'not counting',
    'exclusive of',
    'with the omission of',
    'with the exclusion of',
    'including',
    '(do) other than',
    'otherwise than',
    'exclude',
    'omit',
    'leave out',
    'rule out',
    'count out',
    'disregard',
    'pass over',
    'bar',
    'include',
]