export const definitions = [
    '"are you suffering from an excess of stress in your life?"',
    '"the excess of imports over exports rose $1.4 billion"',
    '"there is no issue as to excess of jurisdiction"',
    '"bouts of alcoholic excess"',
    '"the worst excesses of the French Revolution"',
    '"trim any excess fat off the meat"'
]
export const synonyms = [
    'surplus',
    'surfeit',
    'overabundance',
    'superabundance',
    'superfluity',
    'profusion',
    'plethora',
    'glut',
    'too much',
    'remainder',
    'rest',
    'residue',
    'overflow',
    'overspill',
    'leftovers',
    'remnants',
    'leavings',
    'extra',
    'difference',
    'residuum',
    'oversufficiency',
    'more than enough',
    'enough and to spare',
    'nimiety',
    'remaining quantity',
    'dearth',
    'lack',
    'remainder',
    'rest',
    'residue',
    'overflow',
    'overspill',
    'leftovers',
    'remnants',
    'leavings',
    'surplus',
    'extra',
    'difference',
    'residuum',
    'remaining quantity',
    'profligacy',
    'unthriftiness',
    'thriftlessness',
    'improvidence',
    'wastefulness',
    'waste',
    'overspending',
    'prodigality',
    'squandering',
    'lavishness',
    'immoderation',
    'recklessness',
    'irresponsibility',
    'lack of thrift',
    'lack of restraint',
    'spendthrift behavior',
    'free-spending ways',
    'thrift',
    'overindulgence',
    'overconsumption',
    'intemperance',
    'intemperateness',
    'immoderation',
    'profligacy',
    'prodigality',
    'lavishness',
    'excessiveness',
    'extravagance',
    'decadence',
    'self-indulgence',
    'self-gratification',
    'debauchery',
    'dissipation',
    'dissolution',
    'dissoluteness',
    'lack of restraint',
    'moderation',
    'restraint',
    'surplus',
    'superfluous',
    'spare',
    'redundant',
    'unwanted',
    'unneeded',
    'unused',
    'excessive',
    'leftover',
    'extra',
    'additional',
    'reserve',
]