export const definitions = [
  '"flying still excites me"',
  '"Gould was excited by these discoveries"',
  '"his kiss thrilled and excited her"',
  '"the ability to excite interest in others"',
  '"the energy of an electron is sufficient to excite the atom"',
];
export const synonyms = [
  'thrill',
  'exhilarate',
  'animate',
  'enliven',
  'rouse',
  'stir',
  'move',
  'stimulate',
  'galvanize',
  'electrify',
  'delight',
  'enrapture',
  'intoxicate',
  'inspirit',
  'fire the imagination of',
  'fire the enthusiasm of',
  'bore',
  'depress',
  'arouse',
  'stimulate',
  'titillate',
  'inflame',
  'please',
  'attract',
  'entice',
  'arouse sexually',
  'make someone feel sexually excited',
  'turn off',
  'provoke',
  'stir up',
  'elicit',
  'rouse',
  'arouse',
  'stimulate',
  'kindle',
  'touch off',
  'awaken',
  'incite',
  'instigate',
  'foment',
  'bring out',
  'cause',
  'bring about',
  'enkindle',
  'trigger (off)',
  'spark off',
];