export const definitions = [
    '"these patients are exempt from all charges"',
    '"they are not exempt from criticism"',
    '"they were exempted from paying the tax"'
]
export const synonyms = [
    'free from',
    'exempted',
    'spared',
    'excepted',
    'excused',
    'absolved',
    'released',
    'discharged',
    'immune',
    'not liable to',
    'not subject to',
    'liable to',
    'subject to',
    'free from',
    'exempted',
    'spared',
    'excepted',
    'excused',
    'absolved',
    'released',
    'discharged',
    'immune',
    'excuse',
    'free',
    'release',
    'exclude',
    'spare',
    'let off',
    'liberate',
    'absolve',
    'discharge',
    'dispense',
    'not liable to',
    'not subject to',
    'give/grant immunity',
    'relieve of',
    'make an exception of/for',
    'liable to',
    'subject to',
]