export const definitions = [
  '"he knew now that he would die in exile"',
  '"the return of political exiles"',
  '"a corrupt dictator who had been exiled from his country"',
  '"he was exiled to Tasmania in 1849"',
];
export const synonyms = [
  'banishment',
  'expulsion',
  'expatriation',
  'deportation',
  'eviction',
  'uprooting',
  'separation',
  'extradition',
  'transportation',
  'ostracism',
  'return',
  'émigré',
  'expatriate',
  'displaced person',
  'refugee',
  'asylum seeker',
  'deportee',
  'outcast',
  'pariah',
  'expel',
  'banish',
  'expatriate',
  'deport',
  'ban',
  'bar',
  'drive out',
  'throw out',
  'cast out',
  'eject',
  'oust',
  'outlaw',
  'uproot',
  'separate',
  'extradite',
  'excommunicate',
  'transport',
  'displace',
  'ostracize',
];