export const definitions = [
    '"their business expanded into other hotels and properties"',
    '"baby birds cannot expand and contract their lungs"',
    '"Anne expanded on the theory"'
]
export const synonyms = [
    'enlarge',
    'swell',
    'dilate',
    'inflate',
    'balloon',
    'lengthen',
    'stretch',
    'thicken',
    'fatten',
    'fill out',
    'intumesce',
    'tumefy',
    'grow',
    'extend',
    'augment',
    'broaden',
    'widen',
    'develop',
    'diversify',
    'multiply',
    'add to',
    'build up',
    'scale up',
    'branch out',
    'broaden one\'s horizons',
    'spread',
    'proliferate',
    'mushroom',
    'increase in size',
    'become larger',
    'become distended',
    'puff out/up',
    'become/make larger',
    'become/make bigger',
    'increase in size/scope',
    'extend one\'s operations',
    'shrink',
    'contract',
    'condense',
    'scale down',
    'enlarge on',
    'develop',
    'supplement',
    'amplify',
    'embellish',
    'embroider',
    'fill out',
    'elaborate on',
    'add detail to',
    'go into detail about',
    'flesh out',
    'put flesh on the bones of',
    'expatiate on',
    'pad out',
    'touch on',
]