export const definitions = [
  '"a financial expert"',
  '"experts in child development"',
  '"he had received expert academic advice"',
  '"he is expert at handling the media"',
];
export const synonyms = [
  'specialist',
  'authority',
  'pundit',
  'oracle',
  'resource person',
  'adept',
  'maestro',
  'virtuoso',
  'master',
  'past master',
  'professional',
  'genius',
  'wizard',
  'connoisseur',
  'aficionado',
  'cognoscente',
  'doyen',
  'savant',
  'proficient',
  'one of the cognoscenti',
  'inexpert',
  'amateur',
  'skillful',
  'skilled',
  'adept',
  'accomplished',
  'talented',
  'fine',
  'master',
  'masterly',
  'brilliant',
  'virtuoso',
  'bravura',
  'magnificent',
  'marvelous',
  'wonderful',
  'outstanding',
  'great',
  'exceptional',
  'superlative',
  'formidable',
  'excellent',
  'dazzling',
  'first-class',
  'first-rate',
  'elite',
  'superb',
  'proficient',
  'good',
  'able',
  'apt',
  'capable',
  'competent',
  'clever',
  'experienced',
  'practiced',
  'qualified',
  'knowledgeable',
  'specialist',
  'professional',
  'deft',
  'dexterous',
  'adroit',
  'au fait',
  'well versed',
  'inexpert',
  'incompetent',
];