export const definitions = [
    '"the moon exerts a force on the Earth"',
    '"exerting influence over the next generation"',
    '"he needs to exert himself to try to find an answer"'
]
export const synonyms = [
    'apply',
    'bring into play',
    'exercise',
    'employ',
    'use',
    'make use of',
    'utilize',
    'deploy',
    'wield',
    'expend',
    'spend',
    'bring to bear',
    'make an effort',
    'strive',
    'endeavor',
    'do one\'s best',
    'do one\'s utmost',
    'make every effort',
    'spare no effort',
    'struggle',
    'labor',
    'toil',
    'strain',
    'work like a Trojan',
    'try hard',
    'apply oneself',
    'do all one can',
    'give one\'s all',
    'be at pains',
    'put oneself out',
    'push oneself',
    'drive oneself',
    'work hard',
    'rack/cudgel one\'s brains',
]