export const definitions = [
  '"an enclosure ten acres in extent"',
  '"an in-depth survey will be carried out to establish the extent of the damage"',
  '"everyone will have to compromise to some extent"',
  '"they altered the document to such an extent that it contained little in the way of new policy"',
];
export const synonyms = [
  'area',
  'size',
  'expanse',
  'length',
  'stretch',
  'range',
  'scope',
  'compass',
  'proportions',
  'dimensions',
  'size',
  'dimensions',
  'magnitude',
  'measurements',
  'mass',
  'volume',
  'bulk',
  'expanse',
  'width',
  'breadth',
  'scale',
  'scope',
  'range',
  'degree',
  'scale',
  'level',
  'magnitude',
  'scope',
  'extensiveness',
  'amount',
  'size',
  'coverage',
  'breadth',
  'width',
  'reach',
  'range',
  'compass',
  'comprehensiveness',
  'thoroughness',
  'completeness',
  'all-inclusiveness',
];