export const definitions = [
  '"the beetle exudes a caustic liquid"',
  '"slime exudes from the fungus"',
  '"Mr. Thomas exuded friendship and goodwill"',
  '"the building exudes an air of tranquility"',
];
export const synonyms = [
  'discharge',
  'release',
  'send out',
  'send forth',
  'emit',
  'issue',
  'emanate',
  'ooze',
  'weep',
  'leak',
  'leach',
  'secrete',
  'excrete',
  'extravasate',
  'seep',
  'trickle',
  'filter',
  'percolate',
  'escape',
  'flow',
  'well',
  'drip',
  'dribble',
  'drain',
  'bleed',
  'sweat',
  'filtrate',
  'transude',
  'exudate',
  'give off/out',
  'absorb',
  'take up',
  'discharge',
  'release',
  'send out',
  'send forth',
  'emit',
  'issue',
  'emanate',
  'ooze',
  'weep',
  'leak',
  'leach',
  'secrete',
  'excrete',
  'extravasate',
  'seep',
  'trickle',
  'filter',
  'percolate',
  'escape',
  'flow',
  'well',
  'drip',
  'dribble',
  'drain',
  'bleed',
  'sweat',
  'filtrate',
  'transude',
  'exudate',
  'give off/out',
  'absorb',
  'take up',
  'emanate',
  'radiate',
  'ooze',
  'give out',
  'send out',
  'issue',
  'emit',
  'display',
  'show',
  'exhibit',
  'manifest',
  'demonstrate',
  'transmit',
  'breathe',
  'embody',
  'give forth',
  'be a/the picture of',
];