export const definitions = [
  '"participation by the laity in all facets of church life"',
];
export const synonyms = [
  'surface',
  'face',
  'side',
  'plane',
  'angle',
  'slant',
  'aspect',
  'feature',
  'side',
  'dimension',
  'particular',
  'characteristic',
  'detail',
  'point',
  'ingredient',
  'strand',
  'factor',
  'component',
  'constituent',
  'element',
  'part',
  'section',
  'portion',
  'piece',
  'bit',
  'angle',
  'slant',
  'sense',
  'respect',
  'regard',
  'way',
  'viewpoint',
  'standpoint',
];