export const definitions = [
  '"facile generalizations"',
  '"a man of facile and shallow intellect"',
  '"a facile victory"',
  '"he was revealed to be a facile liar"',
];
export const synonyms = [
  'simplistic',
  'superficial',
  'oversimple',
  'oversimplified',
  'schematic',
  'black and white',
  'shallow',
  'pat',
  'glib',
  'slick',
  'jejune',
  'naive',
  'thorough',
  'profound',
  'effortless',
  'easy',
  'undemanding',
  'painless',
  'trouble-free',
  'unchallenged',
  'leisurely',
  'simple',
  'uncomplicated',
  'straightforward',
  'elementary',
  'unexacting',
  'hard-won',
];