export const definitions = [
    '"she worked fast, conscious of the time factor"',
    '"his legal problems were not a factor in his decision"',
    '"the Rhesus factor"',
    '"an amount that exceeds it by a factor of 1000 or more"',
    '"his father was chief factor for the Hudson\'s Bay Company"',
    '"last year researchers factored a number 155 digits long"',
    '"this situation occurs when code is factored to remove application- and domain-specific dependencies"',
    '"they collected rents while he factored these forfeited estates"',
]
export const synonyms = [
    'element',
    'part',
    'component',
    'ingredient',
    'strand',
    'constituent',
    'point',
    'detail',
    'item',
    'feature',
    'facet',
    'aspect',
    'characteristic',
    'consideration',
    'influence',
    'circumstance',
    'thing',
    'determinant',
    'agent',
    'representative',
    'deputy',
    'middleman',
    'intermediary',
    'go-between',
    'reeve',
    'estate manager',
    'land agent',
    'land steward',
]