export const definitions = [
    '"incentives for farmers to let the land lie fallow in order to reduce grain surpluses"',
    '"long fallow periods when nothing seems to happen"',
    '"a great estate was usually divided between fallows, grazed stubble, and wheat"',
    '"strips of summer fallow"',
    '"fallow the ground for a week or so after digging"',
    '"possible feather colors include fallows, pieds, and yellows"',
]
export const synonyms = [
    'uncultivated',
    'unplowed',
    'untilled',
    'unplanted',
    'unsown',
    'unseeded',
    'unused',
    'undeveloped',
    'dormant',
    'resting',
    'empty',
    'bare',
    'virgin',
    'neglected',
    'untended',
    'unmanaged',
    'unmaintained',
    'cultivated',
    'inactive',
    'dormant',
    'quiet',
    'slack',
    'slow',
    'slow-moving',
    'flat',
    'idle',
    'inert',
    'static',
    'stagnant',
    'depressed',
    'barren',
    'unproductive',
    'unfruitful',
    'busy',
]