export const definitions = [
    '"her smile faltered and then faded"',
    '"\"I c-c-can\'t, \" he faltered"',
    '"he faltered and finally stopped in midstride"',
]
export const synonyms = [
    'hesitate',
    'delay',
    'drag one\'s feet',
    'stall',
    'think twice',
    'change one\'s mind',
    'waver',
    'oscillate',
    'fluctuate',
    'vacillate',
    'see-saw',
    'yo-yo',
    'haver',
    'tergiversate',
    'get cold feet',
    'be undecided',
    'be indecisive',
    'be irresolute',
    'hum and haw',
    'stammer',
    'stutter',
    'stumble',
    'hesitate',
    'pause',
    'halt',
    'splutter',
    'flounder',
    'blunder',
    'fumble',
    'speak haltingly',
]