export const definitions = [
    '"drought could result in famine throughout the region"',
    '"the famine of 1921–22"',
    '"the cotton famine of the 1860s"',
]
export const synonyms = [
    'deprivation',
    'want',
    'scarcity of food',
    'food shortages',
    'plenty',
    'shortage',
    'scarcity',
    'lack',
    'dearth',
    'want',
    'deficiency',
    'insufficiency',
    'shortfall',
    'undersupply',
    'scantiness',
    'rareness',
    'paucity',
    'poverty',
    'drought',
    'unavailability',
    'exiguity',
    'exiguousness',
    'hungriness',
    'ravenousness',
    'emptiness',
    'starvation',
    'malnutrition',
    'malnourishment',
    'undernourishment',
    'inanition',
    'lack of food',
    'need for food',
    'famishment',
]