export const definitions = [
    '"the forest was closed for hunting when the does were fawning"',
    '"they try to ingratiate themselves by fawning over the boss"',
    '"the dogs started fawning on me"',
]
export const synonyms = [
    'obsequious',
    'servile',
    'sycophantic',
    'flattering',
    'ingratiating',
    'unctuous',
    'oleaginous',
    'oily',
    'toadyish',
    'slavish',
    'groveling',
    'abject',
    'crawling',
    'creeping',
    'cringing',
    'prostrate',
    'saponaceous',
    'pay court to',
    'play up to',
    'dance attendance on',
    'flatter',
    'praise',
    'sing the praises of',
    'eulogize',
    'bowing and scraping',
    'Uriah Heepish',
    'be obsequious to',
    'be sycophantic to',
    'be servile to',
    'curry favor with',
    'crawl to',
    'creep to',
    'ingratiate oneself with',
    'fall over oneself for',
    'kowtow to',
    'toady to',
    'truckle to',
    'bow and scrape before',
    'grovel before',
    'cringe before',
    'abase oneself before',
    'praise to the skies',
    'praise to excess',
]