export const definitions = [
    '"safety features like dual air bags"',
    '"a dark-haired man with strong, regular features"',
    '"a feature on Detroit\'s downtown fishery"',
    '"the hotel features a large lounge, a sauna, and a coin-operated solarium"',
    '"the film featured Glenn Miller and his Orchestra"',
    '"his later paintings feature prominently in the exhibition"',
]
export const synonyms = [
    'characteristic',
    'attribute',
    'quality',
    'property',
    'trait',
    'mark',
    'hallmark',
    'trademark',
    'aspect',
    'facet',
    'side',
    'point',
    'detail',
    'factor',
    'ingredient',
    'component',
    'constituent',
    'element',
    'theme',
    'peculiarity',
    'idiosyncrasy',
    'quirk',
    'oddity',
    'face',
    'countenance',
    'physiognomy',
    'profile',
    'visage',
    'lineaments',
    'front',
    'boat race',
    'article',
    'piece',
    'item',
    'report',
    'story',
    'column',
    'review',
    'commentary',
    'criticism',
    'analysis',
    'write-up',
    'exposé',
    'theme',
    'present',
    'promote',
    'call attention to',
    'spotlight',
    'highlight',
    'accent',
    'make a feature of',
    'give prominence to',
    'focus attention on',
    'star',
    'appear',
    'participate',
    'play a part',
    'have a place',
    'have prominence',
]