export const definitions = [
    '"a fiend thirsty for blood and revenge"',
    '"the restaurant\'s owner is a wine fiend"',
]
export const synonyms = [
    'demon',
    'devil',
    'imp',
    'bogie',
    'incubus',
    'succubus',
    'hellhound',
    'cacodemon',
    'evil spirit',
    'brute',
    'beast',
    'villain',
    'barbarian',
    'monster',
    'ogre',
    'sadist',
    'evil-doer',
    'blackguard',
    'enthusiast',
    'fanatic',
    'maniac',
    'addict',
    'devotee',
    'fan',
    'lover',
    'follower',
    'aficionado',
    'connoisseur',
    'appreciator',
]