export const definitions = [
    '"a feisty heroine who\'s more than a pretty face"',
    '"a feisty upstart"',
    '"he got a bit feisty and tried to hit me"',
]
export const synonyms = [
    'energetic',
    'spirited',
    'active',
    'lively',
    'zestful',
    'vital',
    'vigorous',
    'strong',
    'forceful',
    'powerful',
    'potent',
    'positive',
    'effective',
    'effectual',
    'high-powered',
    'aggressive',
    'driving',
    'pushing',
    'bold',
    'enterprising',
    'electric',
    'magnetic',
    'flamboyant',
    'passionate',
    'fiery',
    'halfhearted',
    'lethargic',
]