export const definitions = [
  '"he pleaded guilty to six felonies"',
  '"an accusation of felony"',
];
export const synonyms = [
  'crime',
  'lawbreaking',
  'lawlessness',
  'criminality',
  'misconduct',
  'malpractice',
  'corruption',
  'immorality',
  'sin',
  'sinfulness',
  'wickedness',
  'badness',
  'evil',
  'vice',
  'iniquity',
  'villainy',
  'delinquency',
  'misbehavior',
  'mischief',
  'naughtiness',
  'offense',
  'wrong',
  'misdeed',
  'misdemeanor',
  'fault',
  'error',
  'lapse',
  'peccadillo',
  'transgression',
  'malfeasance',
  'tort',
  'trespass',
  'maleficence',
  'malefaction',
  'malversation',
  'unethical behavior',
  'criminal act',
  'immoral act',
  'evil act',
];