export const definitions = [
  '"a letter of fervid thanks"',
];
export const synonyms = [
  'impassioned',
  'passionate',
  'intense',
  'vehement',
  'ardent',
  'sincere',
  'feeling',
  'profound',
  'deep-seated',
  'heartfelt',
  'emotional',
  'animated',
  'spirited',
  'enthusiastic',
  'zealous',
  'fanatical',
  'wholehearted',
  'avid',
  'eager',
  'earnest',
  'keen',
  'committed',
  'dedicated',
  'devout',
  'perfervid',
  'passional',
  'deeply felt',
  'apathetic',
  'white-hot',
  'red-hot',
  'burning',
  'fiery',
  'on fire',
  'blazing',
  'ablaze',
  'aflame',
  'glowing',
  'aglow',
  'radiant',
  'bright',
  'brilliant',
  'dazzling',
  'shining',
  'luminous',
  'gleaming',
  'ardent',
  'rutilant',
  'lucent',
  'candescent',
  'fervent',
  'intensely hot',
];