export const definitions = [
  '"he appeared in festal array"',
];
export const synonyms = [
  'jolly',
  'merry',
  'joyous',
  'joyful',
  'happy',
  'jovial',
  'lighthearted',
  'cheerful',
  'cheery',
  'jubilant',
  'convivial',
  'good-time',
  'high-spirited',
  'gleeful',
  'mirthful',
  'uproarious',
  'rollicking',
  'backslapping',
  'hilarious',
  'celebratory',
  'holiday',
  'carnival',
  'Christmassy',
  'gay',
  'frolicsome',
  'sportive',
  'miserable',
];