export const definitions = [
    '"he lay bound with fetters of iron"',
    '"the fetters of discipline and caution"',
    '"there were no chains immediately available to fetter the prisoners"',
    '"he was not fettered by tradition"',
]
export const synonyms = [
    'shackles',
    'manacles',
    'handcuffs',
    'irons',
    'leg irons',
    'chains',
    'bonds',
    'tethers',
    'ropes',
    'restraints',
    'trammels',
    'gyves',
    'bilboes',
    'darbies',
    'restraint',
    'constraint',
    'curb',
    'check',
    'impediment',
    'obstacle',
    'barrier',
    'handicap',
    'bar',
    'block',
    'hindrance',
    'encumbrance',
    'disadvantage',
    'drawback',
    'snag',
    'stumbling block',
    'shackles',
    'fetters',
    'bonds',
    'help',
    'assistance',
    'shackle',
    'manacle',
    'handcuff',
    'bind',
    'tie (up)',
    'tether',
    'rope',
    'hobble',
    'secure',
    'restrain',
    'enfetter',
    'gyve',
    'clap in irons',
    'put in chains',
    'chain (up)',
    'restrict',
    'restrain',
    'constrain',
    'confine',
    'limit',
    'hinder',
    'hamper',
    'impede',
    'obstruct',
    'handicap',
    'hamstring',
    'encumber',
    'inhibit',
    'check',
    'curb',
    'tie down',
    'cramp someone\'s style',
    'trammel',
    'tie someone\'s hands',
]