export const definitions = [
  '"feudal barons"',
  '"his view of patriotism was more than old-fashioned—it was positively feudal"',
];
export const synonyms = [
  'old-fashioned',
  'out of date',
  'outmoded',
  'out of fashion',
  'unfashionable',
  'dated',
  'out',
  'outworn',
  'old',
  'former',
  'musty',
  'old-time',
  'old-world',
  'behind the times',
  'behindhand',
  'past',
  'bygone',
  'archaic',
  'obsolescent',
  'obsolete',
  'ancient',
  'antiquated',
  'superannuated',
  'defunct',
  'medieval',
  'prehistoric',
  'antediluvian',
  'oldfangled',
  'quaint',
  'anachronistic',
  'crusted',
  'fusty',
  'moth-eaten',
  'passé',
  'démodé',
  'square-toed',
  'out of style',
  'old-fogeyish',
  'backward-looking',
  'olde worlde',
  'vieux jeu',
  'current',
  'modern',
  'fashionable',
];