export const definitions = [
  '"may I ask a few questions?"',
  '"he had few friends"',
  '"sewing was one of her few pleasures"',
  '"comforts here are few"',
  '"a population of fewer than two million"',
  '"ask which products have the fewest complaints"',
];
export const synonyms = [
  'hardly any',
  'one or two',
  'little',
  'not many',
  'scarcely any',
  'a small number of',
  'a small amount of',
  'a small quantity of',
  'a handful of',
  'a sprinkling of',
  'many',
  'hardly any',
  'one or two',
  'little',
  'scarce',
  'scant',
  'scanty',
  'meager',
  'insufficient',
  'negligible',
  'in short supply',
  'scattered',
  'few and far between',
  'infrequent',
  'uncommon',
  'rare',
  'sporadic',
  'not many',
  'scarcely any',
  'a small number of',
  'a small amount of',
  'a small quantity of',
  'a handful of',
  'a sprinkling of',
  'thin on the ground',
  'seldom met with',
  'many',
  'plentiful',
];