export const definitions = [
    '"parents told little white fibs about out-of-wedlock births"',
]
export const synonyms = [
    'lie',
    'untruth',
    'falsehood',
    'invention',
    'fake news',
    'fabrication',
    'deception',
    'fiction',
    'falsification',
    'cock and bull story',
    'half-truth',
    'exaggeration',
    'porky',
    'made-up story',
    'trumped-up story',
    'piece of fiction',
    'fairy story/tale',
    '(little) white lie',
    'departure from the truth',
    'alternative fact',
    'pork pie',
    'porky pie',
    'terminological inexactitude',
    'truth',
    'fact',
    'lie',
    'dissemble',
    'dissimulate',
    'pretend',
    'exaggerate',
    'pull the wool over someone\'s eyes',
    'pull some\'s \'s leg',
    'be economical with the truth',
    'tell a fib',
    'tell a lie',
    'invent a story',
    'make up a story',
    'depart from the truth',
    'stretch the truth',
    'tell a terminological inexactitude',
    'tell the truth',
]