export const definitions = [
  '"she raked her hair back with her fingers"',
  '"he poured three fingers of vodka into a juice glass"',
  '"a shortbread finger"',
  '"the thin man fingered his mustache"',
  '"a woman fingered a lute"',
  '"you fingered me for those burglaries"',
  '"a research biologist with impeccable credentials was fingered for team leader"',
];
export const synonyms = [
  'digit',
  'thumb',
  'index finger',
  'forefinger',
  'first finger',
  'middle finger',
  'ring finger',
  'little finger',
  'pinkie',
  'dram',
  'drink',
  'nip',
  'slug',
  'drop',
  'draft',
  'swallow',
  'swig',
  'libation',
  'small measure',
  'strip',
  'rectangle',
  'sliver',
  'streak',
  'pencil',
  'touch',
  'feel',
  'handle',
  'manipulate',
  'stroke',
  'rub',
  'caress',
  'fondle',
  'maul',
  'manhandle',
  'pull',
  'grab',
  'toy with',
  'play (around) with',
  'fiddle with',
  'twiddle with',
  'meddle with',
  'put one\'s hands on',
  'lay a finger on',
  'report',
  'give away',
  'sell out',
  'inform (on/against)',
  'act as an informer',
  'tell tales (on)',
  'sneak (on)',
  'be disloyal (to)',
  'stab in the back',
  'identify',
  'recognize',
  'pick out',
  'spot',
  'choose',
  'select',
  'point out',
  'denounce',
  'single out',
  'inform on',
];