export const definitions = [
    '"the sea is thick with fish"',
    '"hot crab appetizers stuffed with fish"',
    '"he is generally thought to be a bit of a cold fish"',
    '"he was fishing for bluefish"',
    '"I\'ve told the girls we\'ve gone fishing"',
    '"they did fish the mountain streams when game grew scarce"',
    '"he fished for his registration certificate and held it up to the policeman\'s flashlight"',
    '"I was not fishing for compliments"',
    '"the body of a woman had been fished out of the river"',
]
export const synonyms = [
    'angle',
    'cast',
    'trawl',
    'go fishing',
    'search',
    'delve',
    'look',
    'hunt',
    'grope',
    'scrabble',
    'fumble',
    'seek',
    'cast around',
    'ferret (around)',
    'root around',
    'rummage (around)',
    'look high and low',
    'solicit',
    'angle',
    'aim',
    'hope',
    'look',
    'try to get',
    'seek to obtain',
    'make a bid',
    'cast around',
    'pull out',
    'haul out',
    'take out',
    'bring out',
    'remove',
    'extricate',
    'extract',
    'retrieve',
    'rescue from',
    'save from',
]