export const definitions = [
  '"the fixing of the date of the hearing"',
  '"the fixing of a fair and reasonable price"',
  '"picnic fixings"',
  '"have all the fixings ready before starting"',
  '"the fixing of additional strengthening steelwork"',
  '"the roof needs fixing"',
  '"problems in need of fixing"',
  '"police investigating the alleged fixing of horse races"',
  '"several laws restricted the fixing of retail prices"',
  '"fix the clamp on a rail"',
  '"the upper jaw of an amphibian is firmly fixed to the skull"',
  '"he turned back to fix the scene in his mind"',
  '"I fixed my attention on the tower"',
  '"her gaze fixed on Jess"',
  '"she fixed her nephew with an unwavering stare"',
  '"no date has yet been fixed for a hearing"',
  '"the rent will be fixed at $600 a month"',
  '"their thinking then seemed fixed on conventional projects"',
  '"having made landfall, he fixed his position"',
  '"there are no facts that fix the defendant with liability"',
  '"you should fix that shelf"',
  '"we want to fix up the house before we sell it"',
  '"Laura was fixing her hair"',
  '"I\'ve fixed it for you to see him on Thursday"',
  '"he\'s sent her on ahead to fix things up"',
  '"I\'ll fix you up with a room"',
  '"Ruth fixed herself a cold drink"',
  '"they were fixing him breakfast"',
  '"you\'re fixing to get into trouble"',
  '"he perfected a process of fixing a photographic likeness on a silver plate"',
  '"specimens were fixed in buffered formalin"',
  '"lupins fix gaseous nitrogen in their root nodules"',
  '"the foundation denies fixing races"',
  '"don\'t you tell nobody, or I\'ll fix you good!"',
];
export const synonyms = [
  'fasten',
  'attach',
  'affix',
  'secure',
  'join',
  'connect',
  'couple',
  'link',
  'install',
  'implant',
  'plant',
  'embed',
  'anchor',
  'stick',
  'glue',
  'bond',
  'cement',
  'pin',
  'nail',
  'screw',
  'bolt',
  'clamp',
  'clip',
  'bind',
  'tie',
  'lash',
  'establish',
  'position',
  'station',
  'situate',
  'lodge',
  'make fast',
  'remove',
  'aim',
  'point',
  'level',
  'turn on',
  'address to',
  'intend for',
  'mean for',
  'destine for',
  'focus on',
  'train on',
  'fix on',
  'attract',
  'draw',
  'hold',
  'grip',
  'engage',
  'captivate',
  'absorb',
  'rivet',
  'lose',
  'select',
  'choose',
  'determine',
  'settle',
  'set',
  'finalize',
  'arrange',
  'prearrange',
  'establish',
  'allot',
  'prescribe',
  'designate',
  'define',
  'name',
  'ordain',
  'appoint',
  'specify',
  'stipulate',
  'decide on',
  'resolve on',
  'arrive at',
  'repair',
  'mend',
  'see to',
  'restore',
  'remedy',
  'rectify',
  'overhaul',
  'service',
  'renovate',
  'recondition',
  'rehabilitate',
  'rebuild',
  'reconstruct',
  'refit',
  'adjust',
  'fettle',
  'patch up',
  'put right',
  'put to rights',
  'set right',
  'get working',
  'make as good as new',
  'restore to working order',
  'put back together',
  'break',
  'damage',
  'neaten',
  'arrange',
  'adjust',
  'style',
  'groom',
  'comb',
  'brush',
  'preen',
  'primp',
  'dress',
  'put in order',
  'arrange',
  'organize',
  'contrive',
  'sort out',
  'see to',
  'see about',
  'manage',
  'engineer',
  'orchestrate',
  'find a way',
  'plan',
  'put together',
  'mastermind',
  'choreograph',
  'make arrangements for',
  'provide',
  'supply',
  'furnish',
  'accommodate',
  'equip',
  'endow',
  'prepare',
  'cook',
  'make',
  'make ready',
  'put together',
  'get',
  'set',
  'make permanent',
  'make fast',
  'rig',
  'manipulate',
  'maneuver',
  'twist',
  'influence',
  'arrange fraudulently',
  'prearrange/predetermine the result of',
  'tamper with',
  'get back at',
  'settle accounts with',
  'punish',
  'revenge oneself on',
  'get one\'s revenge on',
  'be revenged on',
  'avenge oneself on',
  'wreak vengeance on',
  'take retribution on',
  'get even with',
  'give someone their just deserts',
  'hit back at',
  'settle the/a score with',
  'take reprisals against',
  'deal with',
  'inject drugs',
  'take drugs',
  'castrate',
  'neuter',
  'geld',
  'cut',
  'emasculate',
  'spay',
  'desex',
  'sterilize',
  'alter',
  'caponize',
  'evirate',
  'eunuchize',
];