export const definitions = [
    '"he always had a flashy car"',
]
export const synonyms = [
    'ostentatious',
    'showy',
    'bold',
    'flamboyant',
    'conspicuous',
    'obtrusive',
    'extravagant',
    'expensive',
    'pretentious',
    'vulgar',
    'tasteless',
    'tawdry',
    'brash',
    'lurid',
    'garish',
    'loud',
    'gaudy',
    'crude',
    'trashy',
    'in bad/poor taste',
    'understated',
    'tasteful',
]