export const definitions = [
  '"as the sheep came on board, we grabbed their long shaggy fleeces"',
  '"he clutched the ram by two handfuls of thick fleece"',
  '"the shed can be used for storing fleeces"',
  '"a reversible fleece jacket"',
  '"money that authorities say he fleeced from well-to-do acquaintances"',
  '"the sky was half blue, half fleeced with white clouds"',
];
export const synonyms = [
  'hide',
  'pelt',
  'crop',
  'kip',
  'fell',
  'greenhide',
  'wool',
  'coat',
  'hair',
  'fur',
  'pelt',
  'swindle',
  'cheat',
  'defraud',
  'deceive',
  'trick',
  'dupe',
  'hoodwink',
  'double-cross',
  'gull',
  'shortchange',
  'exploit',
  'take advantage of',
  'victimize',
  'cozen',
  'chicane',
  'sell',
  'illude',
  'mulct',
];