export const definitions = [
    '"her torso was full, fleshy, and heavy"',
    '"fleshy, greeny-gray leaves"',
    '"normally, the tissue is fleshy pink"',
]
export const synonyms = [
    'plump',
    'chubby',
    'portly',
    'fat',
    'fattish',
    'obese',
    'overweight',
    'stout',
    'corpulent',
    'paunchy',
    'beer-bellied',
    'thickset',
    'hefty',
    'heavy',
    'heavyset',
    'burly',
    'bulky',
    'chunky',
    'well upholstered',
    'meaty',
    'rotund',
    'round',
    'well rounded',
    'big',
    'large',
    'nuggety',
    'pyknic',
    'pursy',
    'abdominous',
    'well padded',
    'well covered',
    'of ample proportions',
    'squabby',
    'thin',
]