export const definitions = [
  '"land softly with slightly flexed knee and hip joints"',
  '"if you want a further challenge, try eating and drinking with flexed abs"',
  '"a flexed burial"',
  '"she saw him flex his ankle and wince"',
  '"it\'s important to prevent the damaged wrist from flexing"',
  '"a group of bodybuilders flexed their muscles"',
  '"a muscle flexed in his jaw"',
  '"set windows in rubber so they flex during an earthquake"',
  '"the talks were seen as a way for Merkel to flex her well-known diplomatic prowess"',
  '"she flexes her power and success with a flick of her diamond-braceleted wrist"',
];
export const synonyms = [
  'bend',
  'curve',
  'crook',
  'hook',
  'cock',
  'angle',
  'kink',
  'buckle',
  'double up',
  'straighten',
  'tighten',
  'tauten',
  'tension',
  'contract',
  'stiffen',
  'brace',
  'knot',
  'make taut',
  'tense (up)',
  'relax',
];