export const definitions = [
    '"voyagers who crossed the sea in flimsy boats"',
    '"I wore flimsy clothes and needed warming"',
    '"a pretty flimsy excuse"',
    '"credit-card flimsies"',
    '"sheets of yellow flimsy"',
]
export const synonyms = [
    'insubstantial',
    'slight',
    'light',
    'fragile',
    'breakable',
    'frail',
    'shaky',
    'unstable',
    'wobbly',
    'tottery',
    'rickety',
    'ramshackle',
    'makeshift',
    'jerry-built',
    'cheap',
    'shoddy',
    'gimcrack',
    'badly built',
    'thrown together',
    'sturdy',
    'thin',
    'light',
    'lightweight',
    'fine',
    'ultra-fine',
    'diaphanous',
    'sheer',
    'delicate',
    'insubstantial',
    'floaty',
    'filmy',
    'silken',
    'gossamer',
    'gossamer-thin',
    'gossamery',
    'gauzy',
    'gauze-like',
    'cobwebby',
    'feathery',
    'translucent',
    'transparent',
    'see-through',
    'transpicuous',
    'chiffony',
    'gossamer-like',
    'translucid',
    'thick',
    'weak',
    'feeble',
    'poor',
    'inadequate',
    'insufficient',
    'thin',
    'unsubstantial',
    'unconvincing',
    'implausible',
    'unsatisfactory',
    'paltry',
    'trifling',
    'trivial',
    'shallow',
    'sound',
]