export const definitions = [
    '"she relaxed, floating gently in the water"',
    '"trees were felled and floated downstream"',
    '"fragments of chipped cartilage floated in the joint"',
    '"clouds floated across a brilliant blue sky"',
    '"through the open window floated the sound of traffic"',
    '"the notion was floating around Capitol Hill"',
    '"he floated the kick into the net"',
    '"the advice his father had given him floated into his mind"',
    '"a policy of letting the pound float"',
    '"a carnival float"',
    '"root-beer floats"',
]
export const synonyms = [
    'stay afloat',
    'stay on the surface',
    'be buoyant',
    'be buoyed up',
    'sink',
    'hover',
    'levitate',
    'hang',
    'drift',
    'glide',
    'sail',
    'slip',
    'slide',
    'waft',
    'flow',
    'stream',
    'move',
    'travel',
    'be suspended',
    'defy gravity',
    'be carried',
    'rush',
    'suggest',
    'put forward',
    'come up with',
    'submit',
    'raise',
    'moot',
    'propose',
    'advance',
    'offer',
    'proffer',
    'posit',
    'present',
    'table',
    'test the popularity of',
    'withdraw',
    'launch',
    'get off the ground',
    'offer',
    'sell',
    'introduce',
    'establish',
    'set up',
    'institute',
    'promote',
    'get going',
    'wind up',
    'buy back',
]