export const definitions = [
    '"a fluent speaker and writer on technical subjects"',
    '"she became fluent in French and German"',
    '"he spoke fluent Spanish"',
    '"his style of play was fast and fluent"',
    '"a fluent discharge from the nose"',
]
export const synonyms = [
    'articulate',
    'eloquent',
    'expressive',
    'communicative',
    'coherent',
    'cogent',
    'illuminating',
    'vivid',
    'silver-tongued',
    'persuasive',
    'glib',
    'voluble',
    'inarticulate',
    'articulate',
    'able to speak or write … easily and accurately',
    'have a (good) command of',
    'free-flowing',
    'smooth',
    'effortless',
    'easy',
    'natural',
    'fluid',
    'unbroken',
    'uninterrupted',
    'continuous',
    'graceful',
    'elegant',
    'regular',
    'rhythmic',
    'jerky',
]