export const definitions = [
    '"secretaries fob off most unwanted callers by saying their boss is in a meeting"',
    '"he fobbed off the chairmanship on Clifford"',
]
export const synonyms = [
    'put off',
    'stall',
    'deceive',
    'placate',
    'appease',
    'deter',
    'discourage',
    'daunt',
    'scare off',
    'intimidate',
    'unnerve',
    'give someone the runaround',
    'impose',
    'palm off',
    'unload',
    'dump',
    'get rid of',
    'foist',
    'offload',
    'inflict',
    'thrust',
    'saddle someone with something',
    'land someone with something',
    'lumber someone with something',
    'burden someone with something',
]