export const definitions = [
  '"the fetid water of the marsh"',
];
export const synonyms = [
  'stinking',
  'smelly',
  'foul-smelling',
  'evil-smelling',
  'malodorous',
  'reeking',
  'pungent',
  'acrid',
  'high',
  'rank',
  'foul',
  'unpleasant',
  'nasty',
  'noxious',
  'fresh',
  'noisome',
  'mephitic',
  'miasmic',
  'miasmal',
  'olid',
  'stinking to high heaven',
  'fragrant',
];