export const definitions = [
    '"hot steam drifted about her, fogging up the window"',
    '"the windshield was starting to fog up"',
    '"she stared at him, confusion fogging her brain"',
    '"the government has been fogging the issue"',
    '"Winnipeg stopped fogging for mosquitoes three years ago"',
]
export const synonyms = [
    'obscure',
    'shade',
    'veil',
    'befog',
    'becloud',
    'steam up',
    'mist over',
    'cloud over',
    'film over',
    'become misty',
    'become blurred',
    'become covered in condensation',
    'make hazy',
    'make cloudy',
    'clear',
    'muddle',
    'daze',
    'stupefy',
    'fuddle',
    'befuddle',
    'bewilder',
    'confuse',
    'perplex',
    'baffle',
    'obscure',
    'bedim',
    'becloud',
    'obfuscate',
]