export const definitions = [
    '"an extensive program of reforms"',
    '"the nuclear power program"',
    '"a weekly program of films"',
    '"the program includes Dvořák\'s New World symphony"',
    '"a nature program"',
    '"a theater program"',
    '"it is a simple matter to program the computer to recognize such symbols"',
    '"I\'ve programmed for 25 years and have used many languages"',
    '"he has been programming since he was a teenager in the mid - 1970s"',
    '"simply program in your desired volume level"',
    '"all members of a particular species are programmed to build nests in the same way"',
    '"we learn how to program our own lives consciously"',
    '"the next stage of the treaty is programmed for 1996"',
    '"the station does not program enough contemporary works"',
]
export const synonyms = [
    'scheme',
    'plan',
    'plan of action',
    'initiative',
    'project',
    'strategy',
    'solution',
    'series of measures',
    'schedule',
    'agenda',
    'calendar',
    'timetable',
    'lineup',
    'list',
    'listing',
    'bill',
    'menu',
    'bill of fare',
    'order of events',
    'list of events',
    'order of the day',
    'software',
    'routine',
    'use',
    'broadcast',
    'production',
    'show',
    'presentation',
    'transmission',
    'performance',
    'telecast',
    'simulcast',
    'videocast',
    'podcast',
    'documentary',
    'play',
    'comedy',
    'film',
    'docudrama',
    'newscast',
    'magazine (program)',
    'phone-in',
    'episode',
    'installment',
    'chat show',
    'guide',
    'playbill',
    'list of performers/players/artistes',
    'set',
    'fix',
    'arrange',
    'arrange',
    'organize',
    'schedule',
    'plan',
    'map out',
    'lay out',
    'timetable',
    'line up',
    'prearrange',
    'slate',
]