export const definitions = [
    '"it will be a forum for consumers to exchange their views on medical research"',
]
export const synonyms = [
    'meeting',
    'assembly',
    'gathering',
    'conference',
    'seminar',
    'convention',
    'colloquy',
    'convocation',
    'congress',
    'rally',
    'council',
    'symposium',
    'conclave',
    'congregation',
    'synod',
    'diet',
    'caucus',
    'colloquium',
    'setting',
    'place',
    'scene',
    'context',
    'stage',
    'framework',
    'backdrop',
    'medium',
    'means',
    'agency',
    'channel',
    'avenue',
    'vehicle',
    'mechanism',
    'apparatus',
    'auspices',
    'court of law',
    'law court',
    'bench',
    'bar',
    'judicature',
    'tribunal',
    'chancery',
    'assizes',
    'courtroom',
    'palais de justice',
    'court of justice',
    'marketplace',
    'agora',
    'public meeting place',
    'public square',
]