export const definitions = [
  '"a brave policewoman foiled the armed robbery"',
  '"Errol Flynn was a dashing Mountie foiling Nazi agents in Canada"',
];
export const synonyms = [
  'thwart',
  'frustrate',
  'counter',
  'oppose',
  'balk',
  'disappoint',
  'impede',
  'obstruct',
  'hamper',
  'hinder',
  'snooker',
  'cripple',
  'scotch',
  'derail',
  'smash',
  'dash',
  'stop',
  'check',
  'block',
  'prevent',
  'defeat',
  'traverse',
  'nip in the bud',
  'assist',
  'thwart',
  'frustrate',
  'counter',
  'oppose',
  'balk',
  'disappoint',
  'impede',
  'obstruct',
  'hamper',
  'hinder',
  'snooker',
  'cripple',
  'scotch',
  'derail',
  'smash',
  'dash',
  'stop',
  'check',
  'block',
  'prevent',
  'defeat',
  'traverse',
  'nip in the bud',
  'assist',
];