export const definitions = [
    '"the garrison made a foray against Richard\'s camp"',
    '"he made another foray to the bar"',
    '"my first foray into journalism"',
    '"the place into which they were forbidden to foray"',
]
export const synonyms = [
    'raid',
    'attack',
    'assault',
    'incursion',
    'swoop',
    'strike',
    'charge',
    'sortie',
    'sally',
    'rush',
    'onrush',
    'push',
    'thrust',
    'onslaught',
    'offensive',
    'bombardment',
    'blitz',
    'campaign',
    'onset',
    'act of aggression',
    'act of war',
]