export const definitions = [
  '"environmental laws forbid alteration of the coast"',
  '"I was forbidden from leaving Russia"',
  '"my doctor has forbidden me to eat sugar"',
  '"all cars are forbidden"',
  '"the cliffs forbid any easy turning movement"',
];
export const synonyms = [
  'prohibit',
  'ban',
  'outlaw',
  'veto',
  'proscribe',
  'disallow',
  'preclude',
  'exclude',
  'rule out',
  'bar',
  'debar',
  'block',
  'stop',
  'put a stop to',
  'put an end to',
  'interdict',
  'enjoin',
  'restrain',
  'make illegal',
  'declare taboo',
  'permit',
  'prohibit',
  'ban',
  'outlaw',
  'veto',
  'proscribe',
  'disallow',
  'preclude',
  'exclude',
  'rule out',
  'bar',
  'debar',
  'block',
  'stop',
  'put a stop to',
  'put an end to',
  'interdict',
  'enjoin',
  'restrain',
  'make illegal',
  'declare taboo',
  'permit',
];