export const definitions = [
  '"he was thrown backward by the force of the explosion"',
  '"a force-nine gale"',
  '"they ruled by law and not by force"',
  '"the force of popular opinion"',
  '"he might still be a force for peace and unity"',
  '"the force of her writing is undiminished"',
  '"a soldier in a UN peacekeeping force"',
  '"concealment from enemy forces"',
  '"a battle between the forces of good and evil"',
  '"a sales force"',
  '"Luke used the Force to draw his lightsaber to his hand"',
  '"he clearly used the Force to sense where the football was"',
  '"they broke into Fred\'s house and forced every cupboard door with axe or crowbar"',
  '"she forced her feet into flat leather sandals"',
  '"the plane might have been forced down by fighters"',
  '"Sabine forced a smile"',
  '"she forced her way up the ladder"',
  '"she knew if she forced it she would rip it"',
  '"she was forced into early retirement"',
  '"the universities were forced to cut staff"',
  '"I was forced at second base as the first half of a double play"',
  '"East could force declarer to ruff another spade"',
  '"at the village of West Burton, two miles distant, is a fine force"',
];
export const synonyms = [
  'strength',
  'power',
  'energy',
  'might',
  'potency',
  'vigor',
  'muscle',
  'stamina',
  'effort',
  'exertion',
  'impact',
  'pressure',
  'weight',
  'impetus',
  'weakness',
  'coercion',
  'compulsion',
  'constraint',
  'duress',
  'oppression',
  'enforcement',
  'harassment',
  'intimidation',
  'threats',
  'pressure',
  'pressurization',
  'influence',
  'violence',
  'force majeure',
  'intensity',
  'feeling',
  'passion',
  'vigor',
  'vigorousness',
  'vehemence',
  'drive',
  'fierceness',
  'vividness',
  'impact',
  'shallowness',
  'agency',
  'power',
  'influence',
  'instrument',
  'vehicle',
  'means',
  'cause',
  'effect',
  'cogency',
  'weight',
  'effectiveness',
  'efficacy',
  'efficaciousness',
  'soundness',
  'validity',
  'strength',
  'might',
  'power',
  'significance',
  'influence',
  'authority',
  'impressiveness',
  'eloquence',
  'persuasiveness',
  'credibility',
  'conclusiveness',
  'logic',
  'logicality',
  'foundation',
  'reasonableness',
  'coherence',
  'weakness',
  'body',
  'group',
  'outfit',
  'party',
  'team',
  'corps',
  'detachment',
  'unit',
  'squad',
  'squadron',
  'company',
  'battalion',
  'division',
  'patrol',
  'regiment',
  'army',
  'cohort',
  'body of people',
  'kick in',
  'knock down',
  'blast',
  'crack',
  'break open',
  'force open',
  'burst open',
  'prise open',
  'propel',
  'push',
  'thrust',
  'shove',
  'drive',
  'press',
  'pump',
  'expel',
  'extract',
  'elicit',
  'exact',
  'extort',
  'wrest',
  'wring',
  'wrench',
  'drag',
  'screw',
  'squeeze',
  'milk',
  'compel',
  'coerce',
  'make',
  'constrain',
  'oblige',
  'impel',
  'drive',
  'necessitate',
  'pressurize',
  'pressure',
  'press',
  'push',
  'press-gang',
  'browbeat',
  'steamroller',
  'bully',
  'dragoon',
  'bludgeon',
  'terrorize',
  'menace',
  'exert force on',
  'use force on',
  'urge by force',
  'use duress on',
  'bring pressure to bear on',
];