export const definitions = [
    '"her former boyfriend"',
    '"in former times"',
    '"the powers of the former are more comprehensive than those of the latter"',
    '"those who take the former view"',
    '"an opinion-former"',
    '"fifth-formers"',
]
export const synonyms = [
    'one-time',
    'erstwhile',
    'sometime',
    'late',
    'as was',
    'previous',
    'foregoing',
    'preceding',
    'old',
    'earlier',
    'prior',
    'precursory',
    'antecedent',
    'ex-',
    'past',
    'last',
    'ci-devant',
    'quondam',
    'whilom',
    'anterior',
    'precedent',
    'future',
    'next',
    'earlier',
    'old',
    'past',
    'bygone',
    'long-ago',
    'forgotten',
    'immemorial',
    'remote',
    'ancient',
    'primeval',
    'primordial',
    'prehistoric',
    'antediluvian',
    'long ago',
    'of old',
    'of yore',
    'olden',
    'foregone',
    'pristine',
    'gone by',
    'long departed',
    'long gone',
    'long past',
    'primigenial',
    'present',
    'future',
    'first',
    'first-mentioned',
    'latter',
]