export const definitions = [
  '"the format of the funeral service"',
  '"the format is A4 on newsprint"',
  '"(as modifier, in combination) large-format paperbacks"',
  '"the album is available as a CD as well as on LP and cassette formats"',
  '"a data file in binary format"',
  '"how to format a document"',
  '"you will be able to format a disk"',
];
export const synonyms = [
  'configuration',
  'arrangement',
  'pattern',
  'array',
  'alignment',
  'positioning',
  'disposition',
  'order',
  'ordering',
  'organization',
  'design',
  'marshaling',
  'grouping',
  'layout',
  'design',
  'style',
  'presentation',
  'appearance',
  'look',
  'form',
  'shape',
  'size',
  'arrangement',
  'plan',
  'scheme',
  'composition',
  'makeup',
  'configuration',
  'structure',
  'setup',
];