export const definitions = [
    '"the teacher\'s task is to foster learning"',
    '"appropriate praise helps a child foster a sense of self-worth"',
    '"a person who would foster Holly was found"',
    '"foster parent"',
    '"foster child"',
    '"foster care"',
    '"foster home"',
]
export const synonyms = [
    'encourage',
    'promote',
    'further',
    'stimulate',
    'advance',
    'forward',
    'cultivate',
    'nurture',
    'strengthen',
    'enrich',
    'help',
    'aid',
    'abet',
    'assist',
    'support',
    'endorse',
    'champion',
    'speak for',
    'proselytize',
    'sponsor',
    'espouse',
    'uphold',
    'back',
    'boost',
    'facilitate',
    'contribute to',
    'give backing to',
    'neglect',
    'suppress',
    'destroy',
    'bring up',
    'rear',
    'raise',
    'take care of',
    'look after',
    'nurture',
    'mother',
    'parent',
    'care for',
    'provide for',
]