export const definitions = [
    '"the fracas was broken up by stewards"',
]
export const synonyms = [
    'disturbance',
    'quarrel',
    'scuffle',
    'brawl',
    'affray',
    'tussle',
    'melee',
    'free-for-all',
    'fight',
    'clash',
    'skirmish',
    'brouhaha',
    'riot',
    'uproar',
    'commotion',
    'argument',
    'altercation',
    'war of words',
    'shouting match',
    'tiff',
    'dispute',
    'disagreement',
    'row',
    'wrangle',
    'squabble',
    'rumpus',
    'donnybrook',
    'broil',
    'miff',
    'angry exchange',
    'stooshie',
    'bangarang',
]