export const definitions = [
]
export const synonyms = [
    'argue',
    'quarrel',
    'squabble',
    'bicker',
    'fight',
    'fall out',
    'disagree',
    'differ',
    'dispute',
    'spar',
    'wrangle',
    'bandy words',
    'cross swords',
    'lock horns',
    'be at each other\'s throats',
    'altercate',
    'chop logic',
    'have a row/fight',
    'fail to agree',
    'be at odds',
    'have a misunderstanding',
    'be at variance',
    'have words',
    'be at loggerheads',
]