export const definitions = [
    '"I roamed freely"',
    '"air can freely circulate"',
    '"she drank freely to keep up her courage"',
    '"you may speak freely"',
    '"I freely confess to this failing"',
]
export const synonyms = [
    'copiously',
    'plentifully',
    'amply',
    'profusely',
    'exuberantly',
    'prolifically',
    'luxuriantly',
    'aplenty',
    'extensively',
    'everywhere',
    'all over the place',
    'bounteously',
    'plenteously',
    'in profusion',
    'in abundance',
    'in great quantity',
    'in large quantities',
    'in plenty',
    'in huge numbers',
    'sparsely',
    'openly',
    'candidly',
    'frankly',
    'plainly',
    'matter-of-factly',
    'straightforwardly',
    'directly',
    'explicitly',
    'bluntly',
    'outspokenly',
    'unreservedly',
    'truthfully',
    'honestly',
    'without constraint',
    'without inhibition',
    'without beating around the bush',
    'without mincing one\'s words',
    'without prevarication',
    'evasively',
    'voluntarily',
    'willingly',
    'readily',
    'of one\'s own volition',
    'of \'s \'s own accord',
    'of \'s \'s own free will',
    'without being asked',
    'without being forced',
    'without reluctance',
    'under duress',
]