export const definitions = [
    '"the southern fringes of the city"',
    '"people on the fringe of the crowd had trouble hearing him"',
    '"the lunatic fringe of American political life"',
    '"rap music is no longer something on the fringe"',
    '"the beaded fringe of her dress"',
    '"she smiled as she pushed her fringe back out of her eyes"',
    '"a long fringe of hair on the tail"',
    '"we offer the highest salary and fringes in the country"',
    '"fringe theater"',
    '"a fringe political party"',
    '"a rich robe of gold, fringed with black velvet"',
    '"the sea is fringed by palm trees"',
    '"each of the legs on its first six body segments were fringed with fine hairlike structures"',
]
export const synonyms = [
    'edging',
    'edge',
    'border',
    'hem',
    'trimming',
    'frill',
    'flounce',
    'ruffle',
    'tassels',
    'purfle',
    'unconventional',
    'unorthodox',
    'offbeat',
    'alternative',
    'avant-garde',
    'experimental',
    'innovative',
    'innovatory',
    'radical',
    'extreme',
    'peripheral',
    'unofficial',
    'left-field',
    'off Broadway',
    'mainstream',
    'trim',
    'hem',
    'edge',
    'border',
    'rim',
    'bind',
    'braid',
    'tassel',
    'decorate',
    'adorn',
    'ornament',
    'embellish',
    'finish',
    'purfle',
    'befringe',
    'befrill',
    'border',
    'edge',
    'bound',
    'skirt',
    'line',
    'hem',
    'flank',
    'verge',
    'surround',
    'enclose',
    'encircle',
    'circle',
    'encompass',
    'ring',
    'circumscribe',
    'gird',
    'girdle',
    'engird',
    'compass',
    'environ',
]