export const definitions = [
    '"Edward frolicked on the sand"',
    '"he denied allegations that he frolicked with a secretary"',
    '"his injuries were inflicted by the frolics of a young filly"',
    '"the days of fun and frolic were gone for good"',
    '"her poolside frolics"',
    '"a thousand forms of frolic life"',
]
export const synonyms = [
    'frisk',
    'gambol',
    'cavort',
    'caper',
    'sport',
    'scamper',
    'skip',
    'dance',
    'romp',
    'trip',
    'prance',
    'leap',
    'spring',
    'hop',
    'jump',
    'bounce',
    'bob',
    'curvet',
    'rollick',
    'capriole',
    'cut capers',
    'antic',
    'caper',
    'game',
    'romp',
    'stunt',
    'escapade',
    'exploit',
    'revel',
    'spree',
    'sport',
    'fling',
    'prank',
    'jape',
    'giggle',
    'laugh',
    'fun (and games)',
    'merrymaking',
    'amusement',
    'playful',
    'frisky',
    'fun-loving',
    'jolly',
    'merry',
    'gleeful',
    'lighthearted',
    'exuberant',
    'high-spirited',
    'spirited',
    'lively',
    'perky',
    'skittish',
    'coltish',
    'kittenish',
    'mischievous',
    'impish',
    'roguish',
    'prankish',
    'waggish',
    'jokey',
    'gamesome',
    'sportive',
    'wanton',
]