export const definitions = [
    '"Smith was left fuming following the security breach"',
    '"she was absolutely fuming, and who can blame her?"',
    '"she wrote a fuming letter"',
    '"fuming is a highly toxic process"',
    '""We simply cannot have this," she fumed"',
    '"the minister reportedly fumed at officials of the department"',
    '"fragments of lava hit the ground, fuming and sizzling"',
    '"you can fume the wood with industrial-strength ammonia."',
    '"the fumed oak sideboard"',
]
export const synonyms = [
    'seethe',
    'smolder',
    'simmer',
    'boil',
    'bristle',
    'spit',
    'chafe',
    'rage',
    'rant and rave',
    'lose one\'s temper',
    'explode',
    'flare up',
    'bluster',
    'be furious',
    'be enraged',
    'be angry',
    'be livid',
    'be incensed',
    'be beside oneself',
    'lose control',
    'go berserk',
    'smoke',
    'reek',
    'emit smoke',
    'emit gas',
]