export const definitions = [
    '"a funnel of light fell from a circular ceiling"',
    '"they were close to the middle of the cloud funnel"',
    '"some $12.8 billion was funneled through the Marshall Plan"',
    '"the wind funneled down through the valley"',
    '"the crevice funneled out"',
]
export const synonyms = [
    'tube',
    'pipe',
    'channel',
    'conduit',
    'chimney',
    'flue',
    'vent',
    'shaft',
    'lum',
    'channel',
    'guide',
    'feed',
    'direct',
    'convey',
    'move',
    'pass',
    'pour',
    'filter',
    'siphon',
    'scatter',
    'splurge',
]