export const definitions = [
    '"truck wheels had dug furrows in the sand"',
    '"there were deep furrows in his brow"',
    '"gorges furrowing the deep-sea floor"',
    '"a look of concern furrowed his brow"',
    '"her brow furrowed"',
    '"his brows furrowed in concentration"',
    '"she furrowed her brows, thinking hard"',
    '"the tractors continuously furrowed the fields for several days"',
]
export const synonyms = [
    'groove',
    'trench',
    'rut',
    'trough',
    'ditch',
    'channel',
    'seam',
    'gutter',
    'gouge',
    'hollow',
    'fissure',
    'gash',
    'track',
    'wrinkle',
    'line',
    'crease',
    'crinkle',
    'crow\'s foot',
    'cleft',
    'indentation',
    'corrugation',
    'scar',
    'sulcus',
    'wrinkle',
    'crease',
    'line',
    'crinkle',
    'pucker',
    'crumple',
    'screw up',
    'corrugate',
    'scrunch up',
    'smooth',
    'cultivate',
    'till',
    'work',
    'harrow',
    'ridge',
    'break up',
    'turn up',
]