export const definitions = [
  '"a futile attempt to keep fans from mounting the stage"',
];
export const synonyms = [
  'fruitless',
  'vain',
  'pointless',
  'useless',
  'worthless',
  'ineffectual',
  'ineffective',
  'inefficacious',
  'in vain',
  'unavailing',
  'unsuccessful',
  'failed',
  'thwarted',
  'unproductive',
  'barren',
  'unprofitable',
  'abortive',
  'impotent',
  'hollow',
  'empty',
  'forlorn',
  'idle',
  'sterile',
  'nugatory',
  'valueless',
  'hopeless',
  'doomed',
  'lost',
  'bootless',
  'to no effect',
  'of no use',
  'to no avail',
  'useful',
  'fruitful',
];