export const definitions = [
  '"we plan on getting married in the near future"',
  '"work on the building will be halted for the foreseeable future"',
  '"nobody can predict the future"',
  '"a blueprint for the future of American fast food"',
  '"he\'d decided that there was no future in the gang"',
  '"I began to believe I might have a future as an artist"',
  '"the needs of future generations"',
  '"his future wife"',
  '"expectation of a future life"',
];
export const synonyms = [
  'hereafter',
  'time to come',
  'time ahead',
  'what lay/lies ahead',
  'coming times',
  'the fullness of time',
  'past',
  'destiny',
  'fate',
  'fortune',
  'doom',
  'prospects',
  'expectations',
  'chances',
  'likely success/advancement/improvement',
  'later',
  'following',
  'ensuing',
  'succeeding',
  'subsequent',
  'upcoming',
  'to come',
  'coming',
  'past',
  'destined',
  'intended',
  'planned',
  'to be',
  'prospective',
  'expected',
  'anticipated',
];