export const definitions = [
  '"he knew he was losing, and it galled him"',
  '"the straps galled their shoulders"',
];
export const synonyms = [
  'irritate',
  'annoy',
  'vex',
  'anger',
  'exasperate',
  'irk',
  'pique',
  'put out',
  'displease',
  'antagonize',
  'get on someone\'s nerves',
  'ruffle',
  'ruffle someone\'s feathers',
  'make some\'s \'s hackles rise',
  'infuriate',
  'madden',
  'goad',
  'provoke',
  'exacerbate',
  'hump',
  'rasp',
  'make angry',
  'make cross',
  'get/put someone\'s back up',
  'rub up the wrong way',
  'raise someone\'s hackles',
  'drive to distraction',
  'chafe',
  'abrade',
  'scrape',
  'graze',
  'skin',
  'scratch',
  'rasp',
  'bark',
  'fret',
  'excoriate',
  'rub (against)',
  'rub painfully',
  'rub raw',
];