export const definitions = [
    '"she was fond of gambling on cards and horses"',
    '"he was gambling every penny he had on the spin of a wheel"',
    '"the British could only gamble that something would turn up"',
]
export const synonyms = [
    'bet',
    'wager',
    'game',
    'place a bet',
    'lay a bet',
    'stake money on something',
    'back the horses',
    'try one\'s luck on the horses',
    'take a chance',
    'speculate',
    'venture',
    'take a flyer',
    'bank on',
    'take a risk',
    'take a leap in the dark',
    'leave things to chance',
    'buy a pig in a poke',
    'act in the hope of',
    'trust in',
    'take a chance on',
    'bet',
    'wager',
    'speculation',
    'game of chance',
]