export const definitions = [
    '"a crowd gathered in the square"',
    '"we have gathered the information"',
    '"they gathered up the dirty plates and cups"',
    '"the harvest of wheat and barley had been gathered in"',
    '"the Bushmen live by hunting and gathering"',
    '"she gathered the child in her arms"',
    '"the green movement is gathering pace"',
    '"her clients were, I gathered, a prosperous group"',
    '"he lay gathering his thoughts together"',
    '"he gathered himself for a tremendous leap"',
    '"the front is gathered at the waist"',
]
export const synonyms = [
    'congregate',
    'convene',
    'assemble',
    'meet',
    'collect',
    'muster',
    'rally',
    'converge',
    'crowd',
    'mass',
    'foregather',
    'come/get together',
    'cluster together',
    'flock together',
    'scatter',
    'collect',
    'get together',
    'put together',
    'accumulate',
    'amass',
    'assemble',
    'garner',
    'store',
    'stockpile',
    'pile up',
    'stack up',
    'hoard',
    'put by',
    'put away',
    'lay by',
    'lay in',
    'set aside',
    'heap up',
    'collect',
    'get together',
    'put together',
    'accumulate',
    'amass',
    'assemble',
    'garner',
    'store',
    'stockpile',
    'pile up',
    'stack up',
    'hoard',
    'put by',
    'put away',
    'lay by',
    'lay in',
    'set aside',
    'heap up',
    'harvest',
    'collect',
    'reap',
    'pick',
    'pluck',
    'garner',
    'crop',
    'glean',
    'clasp',
    'clutch',
    'take',
    'pull',
    'embrace',
    'enfold',
    'hold',
    'hug',
    'cuddle',
    'squeeze',
    'embosom',
    'strain',
    'understand',
    'believe',
    'think',
    'conclude',
    'deduce',
    'infer',
    'assume',
    'surmise',
    'fancy',
    'take it',
    'hear',
    'notice',
    'see',
    'learn',
    'discover',
    'be given to understand',
    'be led to believe',
    'come to the conclusion',
    'draw the inference',
    'hear tell',
    'be informed',
    'summon',
    'assemble',
    'convene',
    'rally',
    'round up',
    'collect',
    'muster',
    'marshal',
    'organize',
    'convoke',
    'summon up',
    'call together',
    'bring together',
    'disperse',
    'pleat',
    'shirr',
    'pucker',
    'tuck',
    'fold',
    'corrugate',
    'ruffle',
    'crimp',
    'crease',
    'scrunch up',
]