export const definitions = [
  '"astronomers can gauge the star\'s intrinsic brightness"',
  '"she was unable to gauge his mood"',
  '"it is difficult to gauge how effective the ban was"',
  '"when dry, the assemblies can be gauged exactly and planed to width"',
];
export const synonyms = [
  'compute',
  'calculate',
  'work out',
  'estimate',
  'determine',
  'reckon',
  'put a figure on',
  'forecast',
  'predict',
  'count up',
  'give a figure to',
  'assess',
  'evaluate',
  'appraise',
  'analyze',
  'weigh up',
  'judge',
  'adjudge',
  'rate',
  'reckon',
  'determine',
  'estimate',
  'guess',
  'get the measure of',
  'form an opinion of',
  'form an impression of',
  'make up one\'s mind about',
  'measure',
  'calculate',
  'compute',
  'work out',
  'determine',
  'ascertain',
  'count',
  'weigh',
  'quantify',
  'put a figure on',
];