export const definitions = [
    '"Mandy shouted a greeting"',
    '"she raised her hand in greeting"',
    '"warm greetings to you all"',
    '"some of the customers greeted the barman in Gaelic"',
    '"everyone present greeted this idea warmly"',
    '"flowers and cheers greeted the shipyard workers"',
    '"he sat down on the armchair and started to greet"',
]
export const synonyms = [
    'hello',
    'salute',
    'salutation',
    'address',
    'welcome',
    'hailing',
    'nod',
    'wave',
    'acknowledgment',
    'farewell',
    'welcome',
    'welcoming',
    'entertaining',
    'best wishes',
    'regards',
    'congratulations',
    'compliments',
    'respects',
    'felicitations',
    'remembrances',
    'good wishes',
    'kind/kindest regards',
    'one\'s devoirs',
    'address',
    'salute',
    'hail',
    'halloo',
    'welcome',
    'meet',
    'receive',
    'admit',
    'accept',
    'say hello to',
    'nod to',
    'wave to',
    'raise one\'s hat to',
    'tip \'s \'s hat to',
    'acknowledge the presence of',
    'show in',
    'usher in',
    'let in',
    'ignore',
    'receive',
    'acknowledge',
    'take',
    'hear',
    'respond to',
    'react to',
    'listen to',
]