export const definitions = [
    '"he was a gentle, sensitive man"',
    '"her gentle voice"',
    '"a gentle breeze"',
    '"a little gentle persuasion"',
    '"a gentle embankment"',
    '"Cobb\'s tone gentled a little"',
    '"a bird that has been gentled enough to sit on the hand"',
    '"he put the gentle on the hook"',
]
export const synonyms = [
    'kind',
    'kindly',
    'tender',
    'benign',
    'humane',
    'lenient',
    'merciful',
    'forgiving',
    'forbearing',
    'sympathetic',
    'considerate',
    'understanding',
    'clement',
    'compassionate',
    'benevolent',
    'kindhearted',
    'tenderhearted',
    'good-natured',
    'sweet-tempered',
    'loving',
    'mild',
    'soft',
    'quiet',
    'shy',
    'demure',
    'modest',
    'humble',
    'retiring',
    'unassuming',
    'still',
    'tranquil',
    'peaceful',
    'peaceable',
    'pacific',
    'placid',
    'serene',
    'reposeful',
    'reverent',
    'meek',
    'docile',
    'lamblike',
    'dove-like',
    'unkind',
    'brutal',
    'light',
    'soft',
    'moderate',
    'pleasant',
    'zephyr-like',
    'strong',
    'gradual',
    'slight',
    'easy',
    'imperceptible',
    'steep',
    'aristocratic',
    'noble',
    'titled',
    'upper-class',
    'blue-blooded',
    'high-born',
    'well born',
    'patrician',
    'elite',
    'born with a silver spoon in one\'s mouth',
    'silver-spoon',
    'low',
]