export const definitions = [
    '"the building is haunted by the ghost of a monk"',
    '"a ghost ship"',
    '"the ghosts of past deeds"',
    '"she gave the ghost of a smile"',
    '"his memoirs were smoothly ghosted by a journalist"',
    '"they ghosted up the river"',
    '"I didn\'t want to ghost her, so we ended up having ‘the talk’ and it was horrible"',
    '"being ghosted is one of the toughest ways to be dumped"',
    '"people who ghost are primarily focused on avoiding their own emotional discomfort"',
]
export const synonyms = [
    'specter',
    'phantom',
    'wraith',
    'spirit',
    'soul',
    'shadow',
    'presence',
    'vision',
    'apparition',
    'hallucination',
    'duppy',
    'phantasm',
    'shade',
    'revenant',
    'visitant',
    'wight',
    'eidolon',
    'manes',
    'lemures',
    'bodach',
    'Doppelgänger',
    'trace',
    'hint',
    'suggestion',
    'impression',
    'touch',
    'suspicion',
    'tinge',
    'modicum',
    'dash',
    'soupçon',
    'glimmer',
    'semblance',
    'shadow',
    'breath',
    'whiff',
    'undertone',
    'whisper',
    'faint appearance',
]