export const definitions = [
  '"they shrieked and gibbered as flames surrounded them"',
];
export const synonyms = [
  'prattle',
  'rattle on',
  'chatter',
  'babble',
  'ramble',
  'drivel',
  'jabber',
  'patter',
  'gabble',
  'bumble',
  'burble',
  'twitter',
  'go on',
  'run on',
  'mutter',
  'mumble',
  'maunder',
  'prate',
  'bleat',
  'cackle',
  'slabber',
  'clack',
  'twaddle',
  'twattle',
];