export const definitions = [
    '"they giggled at some private joke"',
    '"I got a fit of the giggles"',
]
export const synonyms = [
    'titter',
    'snigger',
    'snicker',
    'tee-hee',
    'chuckle',
    'chortle',
    'smirk',
    'sneer',
    'simper',
    'give a half-suppressed laugh',
    'titter',
    'snigger',
    'snicker',
    'tee-hee',
    'chuckle',
    'chortle',
    'smirk',
    'sneer',
    'simper',
    'half-suppressed laugh',
]