export const definitions = [
  '"a few gondolas glided past"',
  '"slide your hands firmly across the shoulders then glide them down"',
  '"students learning to glide"',
  '"gulls are gliding birds"',
];
export const synonyms = [
  'slide',
  'slip',
  'sail',
  'float',
  'drift',
  'flow',
  'coast',
  'freewheel',
  'roll',
  'skim',
  'skate',
  'glissade',
  'move smoothly',
  'hurtle',
  'slide',
  'slip',
  'sail',
  'float',
  'drift',
  'flow',
  'coast',
  'freewheel',
  'roll',
  'skim',
  'skate',
  'glissade',
  'move smoothly',
  'hurtle',
  'soar',
  'wheel',
  'plane',
  'fly',
];