export const definitions = [
    '"a gloomy corridor"',
    '"I am by no means gloomy about the prospects for domestic industry"',
    '"a gloomy atmosphere"',
]
export const synonyms = [
    'dark',
    'ill-lit',
    'shadowy',
    'sunless',
    'dim',
    'somber',
    'dingy',
    'frowzy',
    'drab',
    'dismal',
    'dreary',
    'murky',
    'depressing',
    'unwelcoming',
    'uninviting',
    'cheerless',
    'joyless',
    'comfortless',
    'funereal',
    'gray',
    'leaden',
    'overcast',
    'cloudy',
    'crepuscular',
    'tenebrous',
    'Stygian',
    'Tartarean',
    'caliginous',
    'subfusc',
    'poorly lit',
    'bright',
    'sunny',
    'well lit',
    'despondent',
    'downcast',
    'downhearted',
    'dejected',
    'disconsolate',
    'dispirited',
    'crestfallen',
    'cast down',
    'depressed',
    'disappointed',
    'disheartened',
    'discouraged',
    'demoralized',
    'desolate',
    'heavy-hearted',
    'low-spirited',
    'sad',
    'unhappy',
    'glum',
    'doleful',
    'melancholy',
    'miserable',
    'woebegone',
    'mournful',
    'sorrowful',
    'forlorn',
    'long-faced',
    'fed up',
    'subdued',
    'wretched',
    'lugubrious',
    'Eeyorish',
    'morose',
    'sepulchral',
    'saturnine',
    'dour',
    'mirthless',
    'woeful',
    'dolorous',
    'chapfallen',
    'pessimistic',
    'depressing',
    'downbeat',
    'disheartening',
    'disappointing',
    'dispiriting',
    'unpromising',
    'unfavorable',
    'bleak',
    'bad',
    'dark',
    'black',
    'somber',
    'saddening',
    'distressing',
    'grim',
    'cheerless',
    'comfortless',
    'hopeless',
    'in low spirits',
    'full of gloom',
    'in the doldrums',
    'adust',
    'looking on the black side',
    'happy',
    'cheerful',
    'optimistic',
    'upbeat',
]