export const definitions = [
    '"the snow was sun-softened glop"',
    '"a glop of creamy dressing"',
    '"commercialized glop, not worth thinking about"',
    '"glop 2 gallons of premixed compound into a bucket"',
]
export const synonyms = [
    'mud',
    'muck',
    'mire',
    'ooze',
    'silt',
    'alluvium',
    'dirt',
    'slime',
    'slush',
    'slurry',
    'sediment',
    'lees',
    'dregs',
    'deposit',
    'grounds',
    'precipitate',
    'residue',
    'slob',
    'grouts',
    'settlings',
    'clag',
    'clart',
]