export const definitions = [
    '"thick, glossy, manageable hair"',
    '"a 16-page glossy brochure"',
    '"glossy TV miniseries and soaps"',
    '"I cared much too much about getting my picture in the glossies"',
]
export const synonyms = [
    'shiny',
    'shining',
    'gleaming',
    'lustrous',
    'bright',
    'brilliant',
    'sparkling',
    'shimmering',
    'glistening',
    'sleek',
    'silky',
    'silken',
    'satiny',
    'sheeny',
    'smooth',
    'glassy',
    'polished',
    'burnished',
    'glazed',
    'waxed',
    'japanned',
    'shellacked',
    'lacquered',
    'patinated',
    'nitid',
    'dull',
    'lusterless',
    'matt',
    'expensive',
    'stylish',
    'fashionable',
    'glamorous',
    'sophisticated',
    'attractive',
    'artistic',
    'upmarket',
    'coffee-table',
    'high-quality',
    'well produced',
    'cheap',
    'downmarket',
]