export const definitions = [
    '"it is the Church\'s mission to preach the gospel"',
    '"they say\'s \'s sold out, but don\'t take that as gospel"',
    '"the new economics unit has produced what it reckons to be the approved gospel"',
    '"a vocalist who combined gospel with rhythm and blues and soul"',
    '"gospel singers"',
]
export const synonyms = [
    'Christian teaching',
    'Christ\'s teaching',
    'the life of Christ',
    'the word of God',
    'the good news',
    'Christian doctrine',
    'the New Testament',
    'the writings of the evangelists',
    'the truth',
    'gospel truth',
    'God\'s truth',
    'fact',
    'reality',
    'actuality',
    'factuality',
    'so',
    'verity',
    'the whole truth',
    'the naked truth',
    'the honest truth',
    'actual fact',
    'what actually/really happened',
    'the case',
    'a certainty',
    'a lie',
    'doctrine',
    'dogma',
    'teaching',
    'principle',
    'ethic',
    'creed',
    'credo',
    'theory',
    'thesis',
    'ideology',
    'idea',
    'ideal',
    'position',
    'belief',
    'tenet',
    'canon',
    'conviction',
    'persuasion',
    'opinion',
]