export const definitions = [
    '"he became the subject of much local gossip"',
    '"they would start gossiping about her as soon as she left"',
]
export const synonyms = [
    'chat',
    'talk',
    'conversation',
    'chatter',
    'heart-to-heart',
    'tête-à-tête',
    'blether',
    'blather',
    'conference',
    'discussion',
    'dialogue',
    'exchange',
    'confabulation',
    'colloquy',
    'adda',
    'scandalmonger',
    'gossipmonger',
    'tattler',
    'busybody',
    'muckraker',
    'quidnunc',
    'calumniator',
    'tittle-tattler',
    'tittle-tattle',
    'tattle',
    'talk',
    'whisper',
    'tell tales',
    'muckrake',
    'chat',
    'converse',
    'confabulate',
    'spread rumors',
    'spread gossip',
    'circulate rumors',
    'spread stories',
    'bruit something abroad/about',
    'speak to each other',
    'discuss things',
    'have a talk',
    'have a chat',
    'have a tête-à-tête',
    'have a conversation',
    'engage in conversation',
]