export const definitions = [
    '"he was incapable of governing the country"',
    '"the future of Jamaica will be governed by geography not history"',
    '"men would give in to passion and become unable to govern themselves"',
    '"the Latin preposition \"cum\" governs nouns in the ablative"',
]
export const synonyms = [
    'rule',
    'control',
    'command',
    'hegemonize',
    'lead',
    'dominate',
    'run',
    'head',
    'direct',
    'administer',
    'order',
    'manage',
    'regulate',
    'guide',
    'conduct',
    'oversee',
    'supervise',
    'superintend',
    'steer',
    'pilot',
    'sway',
    'preside over',
    'be in power over',
    'reign over',
    'exercise control over',
    'have control of',
    'be in control of',
    'be in charge of',
    'hold sway over',
    'be the leader of',
    'be at the helm of',
    'determine',
    'decide',
    'control',
    'regulate',
    'direct',
    'rule',
    'dictate',
    'condition',
    'form',
    'shape',
    'affect',
    'influence',
    'sway',
    'act on',
    'work on',
    'mold',
    'modify',
    'alter',
    'touch',
    'have an effect on',
    'exert influence on',
    'be a factor in',
    'have an impact on',
    'impact on',
    'control',
    'restrain',
    'check',
    'curb',
    'hold back',
    'keep back',
    'bridle',
    'keep a tight rein on',
    'subdue',
    'constrain',
    'contain',
    'keep in check',
    'rein in',
]