export const definitions = [
  '"they are graded according to thickness"',
  '"carefully graded exercises"',
  '"the sky graded from blue to white on the horizon"',
];
export const synonyms = [
  'classify',
  'class',
  'categorize',
  'bracket',
  'sort',
  'group',
  'order',
  'arrange',
  'type',
  'pigeonhole',
  'brand',
  'size',
  'rank',
  'evaluate',
  'rate',
  'value',
  'range',
  'graduate',
  'calibrate',
  'assess',
  'mark',
  'score',
  'judge',
  'evaluate',
  'appraise',
  'pass',
  'shade',
  'change',
  'merge',
  'blend',
  'transmute',
  'turn',
];