export const definitions = [
    '"it was common to graft different varieties onto a single tree trunk"',
    '"they can graft a new hand onto the arm"',
    '"information technology cannot just be grafted onto existing plans"',
    '"I need people prepared to go out and graft"',
]
export const synonyms = [
    'scion',
    'cutting',
    'shoot',
    'offshoot',
    'bud',
    'slip',
    'sprout',
    'sprig',
    'new growth',
    'transplant',
    'implant',
    'implantation',
    'transplant',
    'implant',
    'implantation',
    'affix',
    'slip',
    'join',
    'insert',
    'splice',
    'engraft',
    'transplant',
    'implant',
    'transfer',
    'fasten',
    'attach',
    'add',
    'fix',
    'join',
    'insert',
    'toil',
    'labor',
    'hammer away',
    'grind away',
    'sweat',
    'work like a Trojan',
    'keep one\'s nose to the grindstone',
    'persevere',
    'persist',
    'drudge',
    'travail',
    'moil',
    'work hard',
    'exert oneself',
    'plod away',
    'slave away',
    'work like a dog',
    'keep at it',
    'stick with it',
]