export const definitions = [
    '"the retroverted gravid uterus"',
    '"the scene is gravid with unease"',
]
export const synonyms = [
    'expectant',
    'enceinte',
    'with child',
    'in a delicate condition',
    'on the way',
    'parturient',
    'impregnate',
    'expect',
    'carry',
    'bear',
    'expecting a baby',
    'having a baby',
    'with a baby on the way',
    'having a child',
    'carrying a child',
    'heavy/big with child',
    'in an interesting condition',
    'childing',
    'infanticipating',
    'storked',
]