export const definitions = [
  '"a matter of grave concern"',
  '"his face was grave"',
];
export const synonyms = [
  'serious',
  'important',
  'all-important',
  'profound',
  'significant',
  'momentous',
  'weighty',
  'vital',
  'crucial',
  'critical',
  'acute',
  'urgent',
  'pressing',
  'exigent',
  'pivotal',
  'precarious',
  'touch-and-go',
  'life-and-death',
  'in the balance',
  'dire',
  'terrible',
  'awful',
  'dreadful',
  'alarming',
  'drastic',
  'sore',
  'perilous',
  'hazardous',
  'dangerous',
  'threatening',
  'menacing',
  'risky',
  'egregious',
  'of great consequence',
  'trivial',
  'solemn',
  'earnest',
  'serious',
  'somber',
  'sober',
  'severe',
  'unsmiling',
  'long-faced',
  'stone-faced',
  'stony-faced',
  'grim',
  'gloomy',
  'preoccupied',
  'thoughtful',
  'dignified',
  'staid',
  'dour',
  'aloof',
  'forbidding',
  'grim-faced',
  'carefree',
  'cheerful',
];