export const definitions = [
  '"he wiped his greasy fingers"',
  '"their moisturizers don\'t feel greasy"',
  '"greasy skin"',
  '"greasy food"',
  '"the floor was greasy"',
  '"the greasy little man from the newspaper"',
];
export const synonyms = [
  'oily',
  'shiny',
  'glossy',
  'dry',
  'oily',
  'shiny',
  'glossy',
  'dry',
  'fatty',
  'oily',
  'fat',
  'buttery',
  'oleaginous',
  'adipose',
  'sebaceous',
  'pinguid',
  'unctuous',
  'swimming in oil/fat',
  'lean',
  'crisp',
  'slippery',
  'slick',
  'slimy',
  'slithery',
  'oily',
  'glassy',
  'smooth',
  'dry',
  'ingratiating',
  'fawning',
  'groveling',
  'sycophantic',
  'toadying',
  'obsequious',
  'cringing',
  'flattering',
  'effusive',
  'gushing',
  'gushy',
  'abject',
  'truckling',
  'self-effacing',
  'unctuous',
  'oily',
  'smooth-tongued',
  'smooth',
  'glib',
  'suave',
  'slick',
  'reptilian',
  'Uriah Heepish',
];