export const definitions = [
  '"the Beatles, Bob Dylan, all the greats"',
  '"the lives of the great, including Churchill and Newton"',
];
export const synonyms = [
  'celebrity',
  'personality',
  'name',
  'big name',
  'household name',
  'star',
  'superstar',
  'celebutante',
  'leading light',
  'mogul',
  'giant',
  'master',
  'king',
  'guru',
  'dignitary',
  'luminary',
  'worthy',
  'grandee',
  'lion',
  'notable',
  'notability',
  'personage',
  'panjandrum',
  'famous person',
  'very important person',
  'famous name',
  'public figure',
  'pillar of society',
  'nobody',
  'nonentity',
];