export const definitions = [
    '"\"Holidays don\'t make any difference to Simon,\" Pat griped"',
    '"they gripe about the busywork"',
    '"Hilyard griped his dagger"',
    '"his biggest gripe is that he has lost his sense of privacy"',
    '"if your baby has gripe or is teething, we have the medication to help them"',
    '"he seized me by the arms with a rude gripe"',
]
export const synonyms = [
    'protest',
    'grumble',
    'moan',
    'whine',
    'bleat',
    'carp',
    'cavil',
    'make a fuss',
    'oppose',
    'lament',
    'bewail',
    'criticize',
    'run down',
    'twine',
    'crib',
    'natter',
    'lodge a complaint',
    'make a complaint',
    'object to',
    'speak out against',
    'rail at',
    'find fault with',
    'inveigh against',
    'mither',
    'plain over',
    'grasp',
    'clutch',
    'hold',
    'clasp',
    'latch onto',
    'grab',
    'seize',
    'clench',
    'catch',
    'get one\'s hands on',
    'pluck',
    'squeeze',
    'press',
    'grasp/take/lay hold of',
    'cling to',
    'catch at',
    'release',
    'hold lightly',
    'complaint',
    'grumble',
    'moan',
    'groan',
    'grievance',
    'objection',
    'protest',
    'whine',
    'cavil',
    'quibble',
    'niggle',
    'grasp',
    'hold',
    'clutch',
    'clasp',
    'clench',
]