export const definitions = [
  '"his knuckles were white as he gripped the steering wheel"',
  '"a sole that really grips well on wet rock"',
  '"she was gripped by a feeling of excitement"',
  '"she gripped us from the first sentence"',
  '"he lost his grip on Johnson\'s arm"',
  '"the icy grip of winter"',
  '"I\'ve changed my grip and my backswing"',
  '"these shoes have got no grip"',
  '"our firm grip on inflation"',
  '"you\'ve got a pretty good grip on what\'s going on"',
  '"handlebar grips"',
  '"a grip crammed with new clothes"',
];
export const synonyms = [
  'grasp',
  'clutch',
  'hold',
  'clasp',
  'latch onto',
  'grab',
  'seize',
  'clench',
  'catch',
  'get one\'s hands on',
  'pluck',
  'squeeze',
  'press',
  'gripe',
  'grasp/take/lay hold of',
  'cling to',
  'catch at',
  'release',
  'hold lightly',
  'afflict',
  'affect',
  'take over',
  'beset',
  'rack',
  'torment',
  'convulse',
  'engrossing',
  'enthralling',
  'entrancing',
  'absorbing',
  'riveting',
  'captivating',
  'spellbinding',
  'bewitching',
  'fascinating',
  'compulsive',
  'addictive',
  'compelling',
  'mesmerizing',
  'arresting',
  'thrilling',
  'exciting',
  'dramatic',
  'stimulating',
  'interesting',
  'engaging',
  'distracting',
  'diverting',
  'entertaining',
  'amusing',
  'engross',
  'enthrall',
  'entrance',
  'absorb',
  'rivet',
  'spellbind',
  'bewitch',
  'fascinate',
  'hold',
  'catch',
  'compel',
  'mesmerize',
  'arrest',
  'ensnare',
  'enrapture',
  'interest',
  'intrigue',
  'engage',
  'distract',
  'divert',
  'entertain',
  'amuse',
  'action-packed',
  'hold spellbound',
  'boring',
  'repel',
  'bore',
  'grasp',
  'hold',
  'clutch',
  'clasp',
  'clench',
  'gripe',
  'handshake',
  'hand grip',
  'hand clasp',
  'handshake',
  'hand grip',
  'hand clasp',
  'traction',
  'purchase',
  'friction',
  'adhesion',
  'resistance',
  'control',
  'power',
  'mastery',
  'hold',
  'stranglehold',
  'clutches',
  'domination',
  'dominion',
  'command',
  'influence',
  'possession',
  'rule',
  'tyranny',
  'evil embrace',
  'understanding of',
  'comprehension of',
  'perception of',
  'awareness of',
  'grasp of',
  'apprehension of',
  'conception of',
  'realization of',
  'knowledge of',
  'cognizance of',
  'ken of',
  'mastery of',
  'command of',
  'insight into',
  'familiarity with',
  'bag',
  'overnight bag',
  'overnighter',
  'flight bag',
  'kitbag',
  'Gladstone bag',
  'valise',
  'portmanteau',
  'holdall',
  'traveling bag',
  'stagehand',
  'theatrical assistant',
];