export const definitions = [
    '"the sleeping pills had left her feeling groggy"',
]
export const synonyms = [
    'dazed',
    'muzzy',
    'stupefied',
    'befuddled',
    'fuddled',
    'muddled',
    'confused',
    'bewildered',
    'disoriented',
    'disorientated',
    'vague',
    'benumbed',
    'numb',
    'stunned',
    'dizzy',
    'punch-drunk',
    'shaky',
    'staggering',
    'reeling',
    'unsteady',
    'wobbly',
    'weak',
    'faint',
    'in a stupor',
]