export const definitions = [
    '"the upward growth of plants"',
    '"the growth of the city affects the local climate"',
    '"keeping a journal can be a vital step in our personal growth"',
    '"the rates of population growth are lowest in the north"',
    '"some additives slow down the growth of microorganisms"',
    '"the government aims to get growth back into the economy"',
    '"a day\'s growth of unshaven stubble on his chin"',
    '"the method enables doctors to distinguish between malignant and benign growths"',
    '"all growths within the legally delimited Champagne zone are classified"',
]
export const synonyms = [
    'growing',
    'extension',
    'widening',
    'thickening',
    'broadening',
    'heightening',
    'swelling',
    'magnification',
    'ballooning',
    'development',
    'maturation',
    'germination',
    'sprouting',
    'blooming',
    'flourishing',
    'thriving',
    'vegetation',
    'burgeoning',
    'pullulation',
    'shooting up',
    'springing up',
    'shrinking',
    'withering',
    'expansion',
    'development',
    'progress',
    'advance',
    'advancement',
    'headway',
    'improvement',
    'furtherance',
    'extension',
    'spread',
    'buildout',
    'escalation',
    'rise',
    'success',
    'thriving',
    'flourishing',
    'blooming',
    'boom',
    'upturn',
    'upswing',
    'decline',
    'failure',
    'increase',
    'expansion',
    'augmentation',
    'proliferation',
    'multiplication',
    'enlargement',
    'amplification',
    'mushrooming',
    'snowballing',
    'rise',
    'escalation',
    'buildup',
    'development',
    'evolution',
    'decrease',
    'tumor',
    'malignancy',
    'cancer',
    'lump',
    'outgrowth',
    'swelling',
    'protuberance',
    'protrusion',
    'knob',
    'nodule',
    'cyst',
    'polyp',
    'process',
    'bulla',
    'excrescence',
    'intumescence',
    'tumescence',
    'tumefaction',
    'cancerous growth',
    'malignant growth',
]