export const definitions = [
    '"the ______ face of a young boy"',
    '"______ little moneylenders"',
]
export const synonyms = [
    'dirty',
    'grimy',
    'filthy',
    'unwashed',
    'stained',
    'soiled',
    'smeared',
    'spotted',
    'muddy',
    'dusty',
    'sooty',
    'messy',
    'scruffy',
    'shabby',
    'untidy',
    'unkempt',
    'slovenly',
    'slatternly',
    'sordid',
    'squalid',
    'unhygienic',
    'unsanitary',
    'insanitary',
    'befouled',
    'besmirched',
    'besmeared',
    'begrimed',
    'feculent',
    'clean',
]