export const definitions = [
    '"a grouping of Protestant churches"',
    '"an alternative form of ability grouping"',
    '"three wooden chairs were grouped around a dining table"',
    '"we group them into species merely as a convenience"',
    '"many growers began to group together to form cooperatives"',
]
export const synonyms = [
    'faction',
    'group',
    'side',
    'alliance',
    'affiliation',
    'association',
    'coalition',
    'movement',
    'cabal',
    'junta',
    'bloc',
    'camp',
    'set',
    'caucus',
    'sect',
    'political party',
    'assemble',
    'collect',
    'mass',
    'amass',
    'cluster',
    'clump',
    'bunch',
    'arrange',
    'organize',
    'marshal',
    'range',
    'line up',
    'dispose',
    'gather together',
    'categorize',
    'classify',
    'class',
    'sort',
    'bracket',
    'pigeonhole',
    'grade',
    'rate',
    'rank',
    'designate',
    'label',
    'tag',
    'brand',
    'file',
    'catalog',
    'list',
    'tabulate',
    'index',
    'assign',
    'unite',
    'join forces',
    'get together',
    'gather',
    'collaborate',
    'pull together',
    'cooperate',
    'link',
    'ally',
    'associate',
    'fraternize',
    'affiliate',
    'federate',
    'amalgamate',
    'combine',
    'merge',
    'integrate',
    'consolidate',
    'join up',
    'join together',
    'team up',
    'pool resources',
    'club together',
    'come together',
    'work together',
    'form an alliance',
    'split up',
]