export const definitions = [
    '"his performance as the grumpy gateman"',
    '"he\'s grumpy because he hasn\'t heard from you"',
]
export const synonyms = [
    'bad-tempered',
    'ill-tempered',
    'short-tempered',
    'crotchety',
    'crabby',
    'crabbed',
    'tetchy',
    'testy',
    'waspish',
    'prickly',
    'peppery',
    'touchy',
    'irritable',
    'irascible',
    'crusty',
    'cantankerous',
    'curmudgeonly',
    'bearish',
    'surly',
    'churlish',
    'ill-natured',
    'ill-humored',
    'peevish',
    'cross',
    'fractious',
    'disagreeable',
    'pettish',
    'having gotten up on the wrong side of the bed',
    'as cross as two sticks',
    'good-humored',
]