export const definitions = [
    '"a guided tour of the castle"',
    '"a guided missile"',
    '"he guided her to the front row and sat beside her"',
    '"the groove in the needle guides the thread"',
    '"he guided the team to a second successive win in the tournament"',
]
export const synonyms = [
    'lead',
    'lead the way',
    'conduct',
    'show',
    'usher',
    'shepherd',
    'direct',
    'steer',
    'pilot',
    'escort',
    'accompany',
    'attend',
    'see',
    'take',
    'help',
    'assist',
    'show someone the way',
    'follow',
    'direct',
    'steer',
    'control',
    'manage',
    'command',
    'lead',
    'conduct',
    'run',
    'govern',
    'rule',
    'superintend',
    'supervise',
    'oversee',
    'handle',
    'regulate',
    'manipulate',
    'maneuver',
    'advise',
    'counsel',
    'inform',
    'illuminate',
    'educate',
    'instruct',
    'teach',
    'be in charge of',
    'take charge of',
    'take control of',
    'have control of',
    'preside over',
    'give advice to',
    'give counsel to',
    'give counseling to',
    'give direction to',
    'make recommendations to',
    'make suggestions to',
    'give someone tips',
    'give someone hints',
    'give someone pointers',
    'give information to',
    'give instruction to',
    'be responsible for the education of',
]