export const definitions = [
  '"workers had been gulled into inflicting poverty and deprivation upon themselves"',
];
export const synonyms = [
  'swindle',
  'defraud',
  'cheat',
  'trick',
  'hoodwink',
  'hoax',
  'dupe',
  'take in',
  'mislead',
  'delude',
  'fool',
  'outwit',
  'misguide',
  'lead on',
  'inveigle',
  'seduce',
  'ensnare',
  'entrap',
  'beguile',
  'double-cross',
  'cozen',
  'sharp',
  'mulct',
];