export const definitions = [
  '"I hallooed in the hope that they might hear my shouts"',
  '"he hallooed a number of men in sweatshirts"',
];
export const synonyms = [
  'greeting',
  'hello',
  'call',
  'cry',
  'shout',
  'salutation',
  'acknowledgment',
  'welcome',
  'salute',
  'hallo',
  'farewell',
  'call out',
  'shout',
  'cry out',
  'yell',
  'bawl',
  'bellow',
  'scream',
  'shriek',
  'screech',
  'roar',
  'whoop',
  'hail',
  'greet',
  'call hello to',
];