export const definitions = [
    '"two and a half years"',
    '"the northern half of the island"',
    '"divide the cake in half"',
    '"spending was reduced by half"',
    '"she holed from six feet for a half at the seventeenth"',
    '"peel and halve the pears"',
    '"his pledge to halve the deficit over the next four years"',
    '"profits are expected to halve after a tail-off in new customers"',
    '"she insisted on halving the bill"',
    '"they halved the extra hole in bogey-5s"',
    '"the sills are usually halved and pinned together at the corners"',
]
export const synonyms = [
    'fifty percent of',
    'bisection of',
    'all',
    'bisect',
    'cut in half',
    'divide into two equal parts',
    'divide in two',
    'split in two',
    'sever in two',
    'divide equally',
    'share equally',
    'reduce by fifty percent',
    'decrease by fifty percent',
    'lessen by fifty percent',
]