export const definitions = [
  '"a laundry hamper"',
  '"a picnic hamper"',
  '"their work is hampered by lack of funds"',
];
export const synonyms = [
  'basket',
  'pannier',
  'box',
  'container',
  'holder',
  'wickerwork basket',
  'hinder',
  'obstruct',
  'impede',
  'inhibit',
  'retard',
  'balk',
  'thwart',
  'foil',
  'curb',
  'delay',
  'set back',
  'slow down',
  'hold back',
  'hold up',
  'restrict',
  'restrain',
  'constrain',
  'block',
  'check',
  'curtail',
  'frustrate',
  'cramp',
  'bridle',
  'handicap',
  'cripple',
  'hamstring',
  'shackle',
  'fetter',
  'encumber',
  'cumber',
  'trammel',
  'interfere with',
  'help',
];