export const definitions = [
    '"two hours had passed and still nothing had happened"',
    '"the accident happened at 7.40 a.m"',
    '"the afternoon when the disturbance happened"',
    '"this is what happens when the mechanism goes wrong"',
    '"we just happened to meet Paul"',
    '"there happens to be a clash of personalities"',
    '"it just so happened that she turned up that afternoon"',
    '"do you happen to know who her doctor is?"',
    '"Mike played football as a boy and happened on cycling by accident"',
    '"the same thing happened to me"',
    '"I don\'t care what happens to the money"',
]
export const synonyms = [
    'occur',
    'take place',
    'come about',
    'come off',
    'ensue',
    'result',
    'transpire',
    'materialize',
    'arise',
    'be',
    'crop up',
    'come up',
    'fall out',
    'pan out',
    'turn out',
    'follow',
    'develop',
    'emerge',
    'surface',
    'supervene',
    'come to pass',
    'betide',
    'chance',
    'eventuate',
    'hap',
    'come into being',
    'present itself',
    'chance',
    'have the good/bad/ill fortune',
    'have the good/bad/ill luck',
    'be someone\'s fortune / misfortune',
    'hit on',
    'come on',
    'come across',
    'run across',
    'unearth',
    'uncover',
    'locate',
    'bring to light',
    'run into',
    'encounter',
    'run against',
    'discover unexpectedly',
    'find unexpectedly',
    'find by chance',
    'chance on',
    'stumble on',
    'light on',
    'blunder on',
    'meet by chance',
    'overtake',
    'befall',
    'betide',
    'become of',
    'be the fate of',
    'be the lot of',
    'be visited on',
    'overtake',
    'befall',
    'betide',
    'become of',
    'be the fate of',
    'be the lot of',
    'be visited on',
]