export const definitions = [
  '"being harassed at work can leave you feeling confused and helpless"',
  '"the squadron\'s task was to harass the retreating enemy forces"',
];
export const synonyms = [
  'pester',
  'badger',
  'hound',
  'harry',
  'plague',
  'torment',
  'bedevil',
  'persecute',
  'bother',
  'annoy',
  'exasperate',
  'worry',
  'disturb',
  'trouble',
  'agitate',
  'provoke',
  'vex',
  'stress',
  'nag',
  'keep on at',
  'chivvy',
  'tease',
  'bait',
  'molest',
  'stress out',
  'leave in peace',
  'harry',
  'raid',
  'beleaguer',
  'assail',
  'maraud',
  'ravage',
  'oppress',
  'attack repeatedly',
  'press hard',
  'set upon',
];