export const definitions = [
  '"they enjoyed fishing in the harbor"',
  '"the westerly wind kept us in harbor until the following afternoon"',
  '"the offered harbor of his arms"',
  '"she started to harbor doubts about the wisdom of their journey"',
  '"he was suspected of harboring an escaped prisoner"',
  '"the water can become stagnant, harboring bacteria and other microorganisms"',
  '"some of these planets may harbor life"',
  '"woodlands that once harbored a colony of red deer"',
  '"patients who may have been harboring tuberculosis"',
  '"he might have harbored in San Francisco"',
];
export const synonyms = [
  'port',
  'dock',
  'haven',
  'marina',
  'dockyard',
  'boatyard',
  'mooring',
  'anchorage',
  'roads',
  'waterfront',
  'jetty',
  'quay',
  'pier',
  'slipway',
  'wharf',
  'landing stage',
  'moorage',
  'roadstead',
  'harborage',
  'hithe',
  'refuge',
  'haven',
  'safe haven',
  'shelter',
  'sanctuary',
  'retreat',
  'asylum',
  'oasis',
  'sanctum',
  'place of safety',
  'place of security',
  'port in a storm',
  'bear',
  'nurse',
  'nurture',
  'cherish',
  'entertain',
  'foster',
  'possess',
  'maintain',
  'retain',
  'feel secretly',
  'hold onto',
  'cling to',
  'shelter',
  'conceal',
  'hide',
  'shield',
  'protect',
  'accommodate',
  'lodge',
  'put up',
  'take in',
  'billet',
  'house',
  'give asylum to',
  'give sanctuary to',
  'give shelter to',
  'provide a refuge for',
  'hand over',
  'moor',
  'berth',
  'tie up',
  'drop anchor',
  'be at anchor',
  'cast anchor',
];