export const definitions = [
  '"they ploughed and harrowed the heavy clay"',
  '"Todd could take it, whereas I\'m harrowed by it"',
];
export const synonyms = [
  'distress',
  'trouble',
  'afflict',
  'grieve',
  'torment',
  'torture',
  'crucify',
  'rack',
  'sear',
  'pain',
  'wound',
  'mortify',
  'distressing',
  'traumatic',
  'upsetting',
  'heartbreaking',
  'heart-rending',
  'shocking',
  'disturbing',
  'painful',
  'affecting',
  'haunting',
  'appalling',
  'tragic',
  'horrifying',
  'distressful',
  'cause agony to',
  'cause suffering to',
  'calm',
  'comfort',
  'heartening',
];