export const definitions = [
    '"the boys hate each other"',
    '"two separate polls confirmed he is hated by the public"',
    '"he hates flying"',
    '"I\'d hate to live there"',
    '"I hate to bother you"',
    '"I can\'t hate on them for trying something new "',
]
export const synonyms = [
    'loathe',
    'detest',
    'abhor',
    'abominate',
    'despise',
    'execrate',
    'disrelish',
    'dislike greatly',
    'feel aversion toward',
    'feel revulsion toward',
    'feel hostile toward',
    'be repelled by',
    'be revolted by',
    'regard with disgust',
    'not be able to bear/stand',
    'be unable to stomach',
    'find intolerable',
    'shudder at',
    'recoil from',
    'shrink from',
    'love',
    'like',
    'regret',
    'dislike',
    'hesitate',
    'be sorry',
    'be reluctant',
    'be loath',
    'be unwilling',
    'be disinclined',
    'not like',
]