export const definitions = [
    '"racial hatred"',
    '"his murderous hatred of his brother"',
]
export const synonyms = [
    'loathing',
    'hate',
    'detestation',
    'dislike',
    'distaste',
    'abhorrence',
    'abomination',
    'execration',
    'resentment',
    'aversion',
    'hostility',
    'ill will',
    'ill feeling',
    'enmity',
    'animosity',
    'antagonism',
    'antipathy',
    'bitterness',
    'animus',
    'revulsion',
    'disgust',
    'contempt',
    'repugnance',
    'odium',
    'rancor',
    'disrelish',
    'bad feeling',
    'love',
    'liking',
]