export const definitions = [
    '"a gray lady who haunts the chapel"',
    '"he haunts used book stores"',
    '"the sight haunted me for years"',
    '"cities haunted by the shadow of cholera"',
    '"I revisited my old haunts"',
    '"Greenwich Village has been home to a number of literary haunts"',
]
export const synonyms = [
    'visit',
    'appear in',
    'materialize in',
    'frequent',
    'patronize',
    'spend time in',
    'visit regularly',
    'be a regular visitor to',
    'be a regular client of',
    'loiter in',
    'linger in',
    'torment',
    'obsess',
    'oppress',
    'disturb',
    'trouble',
    'worry',
    'plague',
    'burden',
    'beset',
    'beleaguer',
    'bedevil',
    'besiege',
    'torture',
    'weigh on',
    'prey on',
    'gnaw at',
    'nag at',
    'weigh heavily on',
    'lie heavy on',
    'prey on one\'s mind',
    'weigh heavily on \'s \'s mind',
    'be a weight on \'s \'s mind',
    'oppress',
    'torment',
    'torture',
    'rack',
    'plague',
    'afflict',
    'harrow',
    'beset',
    'beleaguer',
    'trouble',
    'bedevil',
    'cause suffering to',
    'prey on',
    'weigh heavily on',
    'lie heavy on',
    'gnaw at',
    'nag at',
    'hangout',
    'stomping ground',
    'territory',
    'domain',
    'purlieu',
    'resort',
    'den',
    'retreat',
    'meeting place',
    'favorite spot',
]