export const definitions = [
  '"a haven for wildlife"',
  '"a haven in times of trouble"',
];
export const synonyms = [
  'refuge',
  'retreat',
  'shelter',
  'sanctuary',
  'asylum',
  'harbor',
  'oasis',
  'sanctum',
  'place of safety',
  'place of security',
  'port in a storm',
  'anchorage',
  'harbor',
  'port',
  'mooring',
  'roads',
  'cove',
  'inlet',
  'bay',
  'fjord',
  'moorage',
  'roadstead',
  'harborage',
  'hithe',
];