export const definitions = [
    '"he had a new car and a boat"',
    '"have you got a job yet?"',
    '"I don\'t have that much money on me"',
    '"he\'s got the equipment with him"',
    '"the ham had a sweet, smoky flavor"',
    '"she\'s got blue eyes"',
    '"the house has gas heat"',
    '"he had himself two highballs"',
    '"in 1989 the party had 10,000 members"',
    '"he\'s got three children"',
    '"do you have a client named Pedersen ? "',
    '"how much time have I got for the presentation?"',
    '"he\'s got a BA in English"',
    '"he knew Latin and Greek; I had only a little French"',
    '"I went to a few parties and had a good time"',
    '"I was having difficulty in keeping awake"',
    '"I\'ve got a headache"',
    '"he had the strong impression that someone was watching him"',
    '"we\'ve got a few ideas we\'re kicking around"',
    '"I\'ve no doubt he\'s a\'s usy as I am"',
    '"she had her bag stolen"',
    '"I want to have everything ready in good time"',
    '"I had the TV on with the sound turned down"',
    '"it is advisable to have your carpet laid by a professional"',
    '"always having the builders in to do something"',
    '"she had her long hair cut"',
    '"you\'ve got me there; I\'ve never given the matter much thought"',
    '"I realized I\'d been had"',
    '"you don\'t have to accept this situation"',
    '"we\'ve got to plan for the future"',
    '"he\'s got a lot to do "',
    '"if you think that place is great, you have to try our summer house"',
    '"there has to be a catch"',
    '"he had a look around"',
    '"the color green has a restful effect"',
    '"are you going to have a party?"',
    '"I\'ll have the vegetable plate"',
    '"she\'s going to have a baby"',
    '"he had little patience with technological gadgetry"',
    '"if you\'ve got the drive to finish your degree"',
    '"God have mercy on me!"',
    '"I can\'t have you insulting Tom like that"',
    '"Mary had her back to me"',
    '"I soon had the trout in a net"',
    '"he had me by the throat"',
    '"she had a letter from Mark"',
    '"we\'re having the children for the weekend"',
]
export const synonyms = [
    'possess',
    'own',
    'have to one\'s name',
    'boast',
    'enjoy',
    'keep',
    'maintain',
    'retain',
    'hold',
    'use',
    'utilize',
    'occupy',
    'be in possession of',
    'be the owner of',
    'be the (proud) possessor of',
    'have in one\'s possession',
    'count among \'s \'s possessions',
    'be blessed with',
    'be bereft of',
    'comprise',
    'contain',
    'include',
    'incorporate',
    'embrace',
    'embody',
    'encompass',
    'take in',
    'comprehend',
    'consist of',
    'be composed of',
    'be made up of',
    'be formed of',
    'experience',
    'encounter',
    'undergo',
    'face',
    'meet',
    'find',
    'go through',
    'run into',
    'come across',
    'enjoy',
    'taste',
    'be subjected to',
    'have experience of',
    'be faced with',
    'be suffering from',
    'be afflicted by',
    'be affected by',
    'be troubled with',
    'be a sufferer from',
    'harbor',
    'feel',
    'entertain',
    'foster',
    'nurse',
    'cherish',
    'nurture',
    'bear',
    'sustain',
    'maintain',
    'keep in one\'s mind',
    'make',
    'get to',
    'cause to',
    'ask to',
    'request to',
    'tell to',
    'require to',
    'persuade to',
    'induce to',
    'prevail upon someone to',
    'order to',
    'command to',
    'direct to',
    'enjoin to',
    'oblige to',
    'force to',
    'compel to',
    'coerce to',
    'trick',
    'fool',
    'deceive',
    'cheat',
    'dupe',
    'take in',
    'outwit',
    'double-cross',
    'hoodwink',
    'swindle',
    'make love',
    'mate',
    'seduce',
    'copulate',
    'fornicate',
    'possess',
    'couple',
    'swive',
    'know',
    'have sexual intercourse',
    'sleep with/together',
    'go to bed with/together',
    'lie with/together',
    'must',
    'have got to',
    'be obliged to',
    'be required to',
    'be compelled to',
    'be forced to',
    'be bound to',
    'be duty-bound to',
    'be under an obligation to',
    'perform',
    'execute',
    'effect',
    'discharge',
    'carry out',
    'accomplish',
    'fulfill',
    'complete',
    'conduct',
    'implement',
    'do',
    'make',
    'effectuate',
    'organize',
    'arrange',
    'hold',
    'give',
    'host',
    'throw',
    'provide',
    'put on',
    'lay on',
    'set up',
    'pencil in',
    'fix up',
    'make arrangements for',
    'make preparations for',
    'prepare for',
    'plan for',
    'cancel',
    'eat',
    'consume',
    'devour',
    'drink',
    'empty',
    'drain',
    'quaff',
    'imbibe',
    'sink',
    'knock back',
    'ingurgitate',
    'bib',
    'partake of',
    'bear',
    'produce',
    'bring forth',
    'beget',
    'give birth to',
    'be delivered of',
    'bring into the world',
    'be brought to bed of',
    'manifest',
    'show',
    'display',
    'exhibit',
    'demonstrate',
    'express',
    'evince',
    'tolerate',
    'endure',
    'bear',
    'support',
    'accept',
    'put up with',
    'go along with',
    'take',
    'countenance',
    'brook',
    'permit to',
    'allow to',
    'receive',
    'get',
    'obtain',
    'acquire',
    'procure',
    'come by',
    'be given',
    'be sent',
    'take receipt of',
    'send',
    'give',
    'entertain',
    'cater for',
    'receive',
    'accommodate',
    'put up',
    'take in',
    'be host to',
    'invite over',
    'ask over',
    'show hospitality to',
    'invite to a meal',
    'invite to a party',
    'wine and dine',
    'give a bed to',
    'visit',
]