export const definitions = [
    '"the sky was hazy from irrigation evaporation"',
    '"hazy memories"',
    '"the picture we have of him as a man is extremely hazy"',
]
export const synonyms = [
    'misty',
    'foggy',
    'cloudy',
    'clouded',
    'smoggy',
    'murky',
    'overcast',
    'claggy',
    'bright',
    'sunny',
    'vague',
    'indistinct',
    'unclear',
    'faint',
    'dim',
    'indefinite',
    'ill-defined',
    'nebulous',
    'shadowy',
    'blurred',
    'fuzzy',
    'muzzy',
    'woolly',
    'confused',
    'muddled',
    'clear',
]