export const definitions = [
  '"he was restored to health"',
  '"a health risk"',
  '"bad health forced him to retire"',
  '"a standard for measuring the financial health of a company"',
];
export const synonyms = [
  'healthiness',
  'fitness',
  'well-being',
  'haleness',
  'robustness',
  'strength',
  'vigor',
  'soundness',
  'salubrity',
  'good physical condition',
  'physical fitness',
  'good trim',
  'good shape',
  'fine fettle',
  'good kilter',
  'illness',
  'condition',
  'constitution',
  'form',
  'state of health',
  'physical state',
  'physical health',
  'physical shape',
  'your health',
  'good luck',
  'prosit',
  'salut',
  'here\'s to you',
  'good health',
  'here\'s health',
  'skol',
  'slainte',
  'prost',
  'salud',
];