export const definitions = [
  '"they bought some cheap fruit"',
  '"local buses were reliable and cheap"',
  '"a cheap restaurant"',
  '"cheap, shoddy goods"',
  '"she\'s too cheap to send me a postcard"',
  '"her moment of cheap triumph"',
  '"a cheap trick"',
];
export const synonyms = [
  'inexpensive',
  'low-priced',
  'low-price',
  'low-cost',
  'economical',
  'economic',
  'competitive',
  'affordable',
  'reasonable',
  'budget',
  'economy',
  'cheap and cheerful',
  'bargain',
  'cut-rate',
  'cut-price',
  'half-price',
  'sale',
  'reduced',
  'discounted',
  'discount',
  'rock-bottom',
  'giveaway',
  'reasonably priced',
  'moderately priced',
  'keenly priced',
  'sale-price',
  'on special offer',
  'marked down',
  'expensive',
  'poor-quality',
  'second-rate',
  'third-rate',
  'substandard',
  'low-grade',
  'inferior',
  'common',
  'vulgar',
  'shoddy',
  'trashy',
  'tawdry',
  'tinny',
  'brassy',
  'worthless',
  'meretricious',
  'cheap and nasty',
  'cheapjack',
  'gimcrack',
  'Brummagem',
  'pinchbeck',
  'trumpery',
  'high-class',
  'despicable',
  'contemptible',
  'low',
  'base',
  'immoral',
  'unscrupulous',
  'unprincipled',
  'unsavory',
  'distasteful',
  'unpleasant',
  'mean',
  'shabby',
  'sordid',
  'vulgar',
  'tawdry',
  'low-minded',
  'dishonorable',
  'discreditable',
  'ignoble',
  'sorry',
  'shameful',
  'scurvy',
  'admirable',
  'despicable',
  'contemptible',
  'low',
  'base',
  'immoral',
  'unscrupulous',
  'unprincipled',
  'unsavory',
  'distasteful',
  'unpleasant',
  'mean',
  'shabby',
  'sordid',
  'vulgar',
  'tawdry',
  'low-minded',
  'dishonorable',
  'discreditable',
  'ignoble',
  'sorry',
  'shameful',
  'scurvy',
  'admirable',
];