export const definitions = [
    '"those who practiced good deeds would receive the reward of a place in heaven"',
    '"Juno, Queen of Heaven and wife of Jupiter"',
    '"Constantine was persuaded that disunity in the Church was displeasing to heaven"',
    '"the everlasting happiness with God that we call heaven"',
    '"heaven knows!"',
    '"good heavens!"',
    '"Galileo used a telescope to observe the heavens"',
    '"lying by the pool with a good book is my idea of heaven"',
]
export const synonyms = [
    'paradise',
    'nirvana',
    'the promised land',
    'Zion',
    'the next world',
    'happy hunting ground',
    'Elysium',
    'the Elysian Fields',
    'Valhalla',
    'Avalon',
    'the kingdom of heaven',
    'the heavenly kingdom',
    'the City of God',
    'the celestial city',
    'the abode of God',
    'the abode of the saints',
    'the abode of the angels',
    'Abraham\'s bosom',
    'the empyrean',
    'the beyond',
    'the hereafter',
    'the next life',
    'the afterworld',
    'the afterlife',
    'the New Jerusalem',
    'Swarga',
    'the Islands of the Blessed',
    'hell',
    'purgatory',
    'the blue',
    'the ether',
    'the sky',
    'the skies',
    'the upper atmosphere',
    'the stratosphere',
    'the firmament',
    'the vault of heaven',
    'the (wide) blue yonder',
    'the welkin',
    'the empyrean',
    'the azure',
    'the upper regions',
    'the sphere',
    'the celestial sphere',
    'ecstasy',
    'bliss',
    'rapture',
    'contentment',
    'happiness',
    'delight',
    'joy',
    'felicity',
    'paradise',
    'utopia',
    'idyll',
    'nirvana',
    'Eden',
    'Shangri-La',
    'Arcadia',
    'Arcady',
    'supreme happiness',
    'supreme joy',
    'perfect contentment',
    'seventh heaven',
    'cloud nine',
    'misery',
    'hell on earth',
]