export const definitions = [
    '"Huss was burned for heresy"',
    '"the doctrine was denounced as a heresy by the Pope"',
    '"cutting capital gains taxes is heresy"',
    '"the politician\'s heresies became the conventional wisdom of the day"',
]
export const synonyms = [
    'dissension',
    'dissent',
    'dissidence',
    'blasphemy',
    'nonconformity',
    'unorthodoxy',
    'heterodoxy',
    'apostasy',
    'freethinking',
    'schism',
    'faction',
    'skepticism',
    'agnosticism',
    'atheism',
    'nontheism',
    'nonbelief',
    'unbelief',
    'idolatry',
    'paganism',
    'separatism',
    'sectarianism',
    'revisionism',
    'tergiversation',
    'recreancy',
    'recusancy',
    'orthodoxy',
]