export const definitions = [
]
export const synonyms = [
    'recluse',
    'solitary',
    'loner',
    'ascetic',
    'anchorite',
    'anchoress',
    'eremite',
    'stylite',
    'solitudinarian',
    'hikikomori',
    'pillarist',
    'pillar hermit',
    'pillar saint',
    'recluse',
    'solitary',
    'loner',
    'ascetic',
    'anchorite',
    'anchoress',
    'eremite',
    'stylite',
    'solitudinarian',
    'hikikomori',
    'pillarist',
    'pillar hermit',
    'pillar saint',
]