export const definitions = [
    '"she enjoys hiking and climbing in her spare time"',
    '"we planned to hike another mile up a steep trail"',
    '"he hiked up his sweatpants and marched to the door"',
    '"some of the local merchants hiked the price of goods"',
]
export const synonyms = [
    'walk',
    'trek',
    'tramp',
    'trudge',
    'traipse',
    'slog',
    'footslog',
    'plod',
    'march',
    'ramble',
    'wander',
    'stroll',
    'peregrinate',
    'perambulate',
    'go on foot',
    'drive',
    'pull up',
    'lift',
    'raise',
    'hoist',
    'hitch up',
    'jerk up',
    'pull down',
    'increase',
    'raise',
    'up',
    'put up',
    'mark up',
    'push up',
    'inflate',
    'advance',
    'make higher',
    'lower',
]