export const definitions = [
    '"the escaping gas was now hissing"',
    '"the audience hissed loudly at the mention of his name"',
    '"he was hissed off the stage"',
    '"\"Get back!\" he hissed"',
    '"he hissed at them to be quiet"',
]
export const synonyms = [
    'fizz',
    'fizzle',
    'whistle',
    'wheeze',
    'buzz',
    'shrill',
    'sibilate',
    'jeer',
    'catcall',
    'whistle',
    'scoff',
    'taunt',
    'hoot',
    'jibe',
    'deride',
    'utter catcalls',
    'shout disapproval',
    'cheer',
]