export const definitions = [
    '"he was hobbling around on crutches"',
    '"Johnson was still hobbled slightly by an ankle injury"',
    '"cotton farmers hobbled by low prices"',
    '"he finished the game almost reduced to a hobble"',
]
export const synonyms = [
    'limp',
    'shuffle',
    'shamble',
    'falter',
    'totter',
    'dodder',
    'stagger',
    'stumble',
    'reel',
    'lurch',
    'walk with a limp',
    'walk with difficulty',
    'move unsteadily',
    'walk unevenly',
    'walk lamely',
    'walk haltingly',
    'hirple',
    'stride',
    'lameness',
    'shuffle',
    'claudication',
    'uneven gait',
]