export const definitions = [
    '"the cord retracts easily into its holder"',
    '"holders of two American hostages"',
    '"US passport holders"',
    '"the record holder in the 100-meter dash"',
]
export const synonyms = [
    'container',
    'receptacle',
    'case',
    'casing',
    'cover',
    'covering',
    'housing',
    'sheath',
    'stand',
    'rest',
    'support',
    'base',
    'rack',
    'bearer',
    'owner',
    'possessor',
    'keeper',
    'proprietor',
    'incumbent',
    'occupant',
    'custodian',
]