export const definitions = [
    '"the Holy Bible"',
    '"the holy month of Ramadan"',
    '"saints and holy men"',
    '"I do not lead a holy life"',
    '"holy macaroni!"',
]
export const synonyms = [
    'sacred',
    'consecrated',
    'hallowed',
    'sanctified',
    'venerated',
    'revered',
    'reverenced',
    'divine',
    'religious',
    'blessed',
    'blest',
    'dedicated',
    'cursed',
    'unsanctified',
    'saintly',
    'godly',
    'saintlike',
    'pious',
    'pietistic',
    'religious',
    'devout',
    'God-fearing',
    'spiritual',
    'canonized',
    'beatified',
    'ordained',
    'deified',
    'righteous',
    'good',
    'virtuous',
    'moral',
    'sinless',
    'pure',
    'perfect',
    'sinful',
    'irreligious',
]