export const definitions = [
    '"each fiber has a hollow core"',
    '"hollow cheeks"',
    '"a hollow cough"',
    '"the result was a hollow victory"',
    '"a hollow promise"',
    '"a hollow at the base of a large tree"',
    '"the house fell behind as they climbed out of the hollow"',
    '"a tunnel was hollowed out in a mountain range"',
    '"gushing water has hollowed a succession of natural spa baths"',
    '"Flora\'s laugh hollowed her cheeks"',
    '"its finances were ravaged and its neighborhoods hollowed out by a long, slow decline in population and auto manufacturing"',
    '"democratic institutions built up and enjoyed for decades are still being hollowed out"',
]
export const synonyms = [
    'empty',
    'void',
    'unfilled',
    'vacant',
    'hollowed out',
    'not solid',
    'solid',
    'sunken',
    'deep-set',
    'concave',
    'depressed',
    'dented',
    'indented',
    'incurvate',
    'caved in',
    'dull',
    'low',
    'flat',
    'toneless',
    'expressionless',
    'muffled',
    'muted',
    'deep',
    'rumbling',
    'echoing',
    'sepulchral',
    'meaningless',
    'empty',
    'valueless',
    'worthless',
    'useless',
    'pyrrhic',
    'futile',
    'fruitless',
    'profitless',
    'pointless',
    'unavailing',
    'bootless',
    'of no use',
    'of no value',
    'of no avail',
    'worthwhile',
    'insincere',
    'hypocritical',
    'feigned',
    'pretended',
    'artificial',
    'false',
    'dissembling',
    'dissimulating',
    'deceitful',
    'sham',
    'cynical',
    'counterfeit',
    'spurious',
    'untrue',
    'unsound',
    'flimsy',
    'two-faced',
    'double-dealing',
    'sincere',
    'hole',
    'pit',
    'cavity',
    'crater',
    'trough',
    'cave',
    'cavern',
    'depression',
    'indentation',
    'concavity',
    'dent',
    'dint',
    'dip',
    'dimple',
    'dish',
    'basin',
    'niche',
    'nook',
    'cranny',
    'recess',
    'valley',
    'vale',
    'dale',
    'dene',
    'combe',
    'glen',
    'strath',
    'dell',
    'dingle',
    'slade',
    'clough',
    'dig out',
    'cut out',
    'excavate',
    'channel',
    'gouge out',
    'scoop out',
]