export const definitions = [
    '"I haven\'t been totally honest with you"',
    '"I did the only right and honest thing"',
    '"he\'s struggling to make an honest living"',
    '"he\'d made an honest mistake"',
    '"good honest food with no gimmicks"',
    '"you\'ll like it when you get there, honest"',
]
export const synonyms = [
    'truthful',
    'sincere',
    'candid',
    'frank',
    'direct',
    'open',
    'forthright',
    'straight',
    'straightforward',
    'genuine',
    'blunt',
    'plain-spoken',
    'plain-speaking',
    'matter-of-fact',
    'outspoken',
    'as straight as a die',
    'free-spoken',
    'objective',
    'impartial',
    'unbiased',
    'balanced',
    'unprejudiced',
    'disinterested',
    'even-handed',
    'fair',
    'just',
    'equitable',
    'straight from the shoulder',
    'insincere',
    'biased',
    'upright',
    'honorable',
    'moral',
    'ethical',
    'principled',
    'righteous',
    'right-minded',
    'respectable',
    'virtuous',
    'good',
    'worthy',
    'decent',
    'law-abiding',
    'high-minded',
    'upstanding',
    'just',
    'fair',
    'incorruptible',
    'anticorruption',
    'truthful',
    'true',
    'veracious',
    'trustworthy',
    'trusty',
    'reliable',
    'conscientious',
    'scrupulous',
    'reputable',
    'dependable',
    'loyal',
    'faithful',
    'morally correct',
    'dishonest',
    'genuine',
    'real',
    'authentic',
    'actual',
    'true',
    'legitimate',
    'above board',
    'fair and square',
    'bona fide',
    'intentional',
    'plain',
    'unadorned',
    'undecorated',
    'unembellished',
    'unornamented',
    'unpretentious',
    'unostentatious',
    'unfussy',
    'no-nonsense',
    'basic',
    'modest',
    'unsophisticated',
    'homely',
    'homespun',
    'everyday',
    'workaday',
    'stark',
    'severe',
    'spartan',
    'austere',
    'chaste',
    'spare',
    'bare',
    'muted',
    'unpatterned',
    'patternless',
    'classic',
    'understated',
    'uncluttered',
    'clean',
    'restrained',
    'homestyle',
    'without ornament/ornamentation',
    'unelaborate',
    'penny plain',
    'without frills',
    'fancy',
    'elaborate',
]