export const definitions = [
  '"the hoopla and ceremony of international competition"',
];
export const synonyms = [
  'disturbance',
  'racket',
  'uproar',
  'tumult',
  'ruckus',
  'clamor',
  'brouhaha',
  'furor',
  'hue and cry',
  'palaver',
  'fuss',
  'stir',
  'to-do',
  'storm',
  'maelstrom',
  'melee',
  'turmoil',
  'disorder',
  'confusion',
  'chaos',
  'mayhem',
  'havoc',
  'pandemonium',
  'upheaval',
  'unrest',
  'fracas',
  'riot',
  'breach of the peace',
  'disruption',
  'agitation',
  'excitement',
  'hurly-burly',
  'hubbub',
  'disquiet',
  'ferment',
  'bother',
  'folderol',
  'bustle',
  'donnybrook',
  'tamasha',
  'affray',
  'broil',
  'hustle and bustle',
  'bangarang',
];