export const definitions = [
    '"owls hooted, the new moon rose"',
    '"a car horn hooted, frightening her"',
    '"Sam hooted his horn"',
    '"she began to hoot with laughter"',
    '"his questions were hooted down or answered obscenely"',
]
export const synonyms = [
    'cry',
    'call',
    'screech',
    'tu-whit tu-whoo',
    'utter a hoot',
    'sound',
    'blare',
    'blast',
    'beep',
    'honk',
    'toot',
    'make a loud sound',
    'shout',
    'yell',
    'cry',
    'howl',
    'scream',
    'shriek',
    'whoop',
    'whistle',
    'boo',
    'hiss',
    'jeer',
    'mock',
    'taunt',
    'catcall',
    'cheer',
]