export const definitions = [
    '"he hotted up the flask in Daisy\'s hand"',
    '"the championship contest hotted up"',
]
export const synonyms = [
    'warm',
    'warm up',
    'take the chill off',
    'reheat',
    'cook',
    'boil',
    'bake',
    'roast',
    'toast',
    'stew',
    'fry',
    'grill',
    'heat up',
    'make hot',
    'make warm',
    'raise something\'s temperature',
    'become hot',
    'become warm',
    'grow hot',
    'grow warm',
    'become hotter',
    'become warmer',
    'get hotter',
    'get warmer',
    'increase in temperature',
    'rise in temperature',
    'cool',
    'cool down',
    'cheer up',
    'enliven',
    'animate',
    'hearten',
    'gladden',
    'invigorate',
    'rejuvenate',
    'vitalize',
    'restore',
    'revive',
    'refresh',
    'vivify',
    'galvanize',
    'stimulate',
    'stir up',
    'brighten up',
    'put some life into',
    'put some spark into',
    'raise someone\'s spirits',
    'perk up',
    'spice up',
    'ginger up',
    'make lively',
    'waken/wake up',
    'give a boost to',
    'put some zest into',
    'get going',
    'calm someone down',
]