export const definitions = [
    '"I will confess, I am a hugger"',
    '"I can remember a few close friends who were particularly good huggers"',
    '"call me a tree hugger, but the devastation we humans exact on the earth is atrocious"',
    '"the gun huggers keep passing more and more extreme gun carry bills"',
    '"he hugged her close to him"',
    '"people kissed and hugged each other"',
    '"we hugged and kissed"',
    '"he hugged his knees to his chest"',
    '"a pair of jeans that hugged the contours of his body"',
    '"I headed north, hugging the coastline all the way"',
    '"she hugged herself with secret joy"',
    '"a boy hugging a secret"',
    '"there were hugs and tears as they were reunited"',
]
export const synonyms = [
    'embrace',
    'cuddle',
    'squeeze',
    'clasp',
    'clutch',
    'embosom',
    'cling to',
    'hold someone close',
    'hold someone tight',
    'take someone in one\'s arms',
    'enfold someone in \'s \'s arms',
    'clasp/press someone to \'s \'s bosom',
    'embrace',
    'clasp',
    'cradle',
    'fold',
    'enfold',
    'envelop',
    'squeeze',
    'embosom',
    'hold tight',
    'hold in one\'s arms',
    'keep close to',
    'stay near to',
    'follow closely',
    'follow the course of',
    'keep away from',
    'cherish',
    'harbor',
    'nurture',
    'nurse',
    'foster',
    'retain',
    'maintain',
    'cling to',
    'hold onto',
    'keep in one\'s mind',
    'abandon',
    'embrace',
    'cuddle',
    'squeeze',
    'bear hug',
    'hold',
    'clasp',
    'clutch',
    'clinch',
    'caress',
]