export const definitions = [
  '"regulations ensuring the humane treatment of animals"',
  '"humane methods of killing"',
  '"the center emphasizes economics as a humane discipline"',
];
export const synonyms = [
  'compassionate',
  'kind',
  'kindly',
  'kindhearted',
  'considerate',
  'understanding',
  'sympathetic',
  'tolerant',
  'civilized',
  'good',
  'good-natured',
  'gentle',
  'lenient',
  'forbearing',
  'forgiving',
  'merciful',
  'mild',
  'tender',
  'clement',
  'benign',
  'humanitarian',
  'benevolent',
  'charitable',
  'generous',
  'magnanimous',
  'approachable',
  'accessible',
  'benignant',
  'cruel',
  'inhumane',
];