export const definitions = [
    '"he was humble about his stature as one of rock history\'s most influential guitarists"',
    '"my humble apologies"',
    '"she came from a humble, unprivileged background"',
    '"he built the business empire from humble beginnings"',
    '"I knew he had humbled himself to ask for my help"',
    '"he was humbled by his political opponents"',
]
export const synonyms = [
    'meek',
    'deferential',
    'respectful',
    'submissive',
    'self-effacing',
    'unassertive',
    'unpresuming',
    'modest',
    'unassuming',
    'self-deprecating',
    'obsequious',
    'sycophantic',
    'servile',
    'mim',
    'resistless',
    'free from vanity',
    'hiding one\'s light under a bushel',
    'proud',
    'overbearing',
    'low-ranking',
    'low',
    'lowly',
    'lower-class',
    'plebeian',
    'proletarian',
    'working-class',
    'undistinguished',
    'poor',
    'mean',
    'ignoble',
    'low-born',
    'common',
    'commonplace',
    'ordinary',
    'simple',
    'inferior',
    'unimportant',
    'unremarkable',
    'insignificant',
    'inconsequential',
    'baseborn',
    'of low birth',
    'of low rank',
    'noble',
    'unpretentious',
    'modest',
    'unostentatious',
    'plain',
    'simple',
    'ordinary',
    'grand',
    'humiliate',
    'abase',
    'demean',
    'belittle',
    'lower',
    'degrade',
    'debase',
    'bring down',
    'mortify',
    'shame',
    'abash',
    'subdue',
    'chasten',
    'bring low',
    'put to shame',
    'make someone eat humble pie',
    'take down a peg or two',
    'defeat',
    'beat',
    'crush',
    'trounce',
    'conquer',
    'vanquish',
    'rout',
    'smash',
    'overwhelm',
    'get the better of',
    'bring someone to their knees',
    'beat hollow',
    'give a drubbing to',
    'be victorious over',
]