export const definitions = [
    '"rioters hurled a brick through the windshield of a car"',
    '"I seized Nathan and hurled him into the lobby"',
    '"he hurled himself into the job with enthusiasm"',
    '"they were hurling insults over a back fence"',
    '"it made me want to hurl"',
]
export const synonyms = [
    'throw',
    'toss',
    'fling',
    'pitch',
    'cast',
    'lob',
    'launch',
    'flip',
    'catapult',
    'shy',
    'dash',
    'send',
    'bowl',
    'aim',
    'direct',
    'project',
    'propel',
    'fire',
    'let fly',
    'catch',
    'hold',
    'throw',
    'toss',
    'fling',
    'pitch',
    'cast',
    'lob',
    'launch',
    'flip',
    'catapult',
    'shy',
    'dash',
    'send',
    'bowl',
    'aim',
    'direct',
    'project',
    'propel',
    'fire',
    'let fly',
    'catch',
    'hold',
    'be sick',
    'spew',
    'fetch up',
    'heave',
    'retch',
    'reach',
    'gag',
    'get sick',
    'regorge',
    'purge',
    'brake',
    'cascade',
    'spew up',
    'egurgitate',
]