export const definitions = [
    '"someone yelled \"Huzzah!\""',
    '"he huzzahed at the top of his voice"',
]
export const synonyms = [
    'hurrah',
    'whoop',
    'bravo',
    'hoot',
    'shout',
    'shriek',
    'hosanna',
    'alleluia',
    'acclaim',
    'acclamation',
    'shouting',
    'clamor',
    'applause',
    'clapping',
    'ovation',
    'laudation',
    'hurray',
    'boo',
    'shout',
    'cry',
    'call',
    'yell',
    'roar',
    'scream',
    'shriek',
    'screech',
    'hoot',
    'hoop',
    'cheer',
    'hurrah',
]