export const definitions = [
  '"the bird was a hybrid of a goose and a swan"',
  '"a hybrid of wheat and rye"',
  '"the final text is a hybrid of the stage play and the film"',
  '"a hybrid variety"',
  '"hybrid offspring"',
  '"Mexico\'s hybrid post - conquest culture"',
  '"these hybrid cars can be driven over short distances in electric-only mode"',
  '"there are concerns that shifting to hybrid working may only benefit those with office jobs"',
  '"hybrid learning is the key to education in the near future"',
];
export const synonyms = [
  'cross',
  'crossbreed',
  'mixture',
  'blend',
  'meld',
  'amalgam',
  'amalgamation',
  'combination',
  'composite',
  'compound',
  'conglomerate',
  'fusion',
  'synthesis',
  'mixed-breed',
  'mixture',
  'blend',
  'mingling',
  'combination',
  'compound',
  'fusion',
  'composition',
  'concoction',
  'brew',
  'alloy',
  'merger',
  'union',
  'amalgamation',
  'amalgam',
  'coalition',
  'cross',
  'medley',
  'melange',
  'diversity',
  'collection',
  'selection',
  'assortment',
  'variety',
  'mixed bag',
  'miscellany',
  'assemblage',
  'pot-pourri',
  'conglomeration',
  'jumble',
  'mess',
  'confusion',
  'mishmash',
  'hotchpotch',
  'hodgepodge',
  'ragbag',
  'pastiche',
  'patchwork',
  'farrago',
  'hash',
  'gallimaufry',
  'omnium gatherum',
  'olio',
  'salmagundi',
  'macédoine',
  'motley collection',
  'composite',
  'cross-bred',
  'interbred',
  'mixed',
  'compound',
  'combined',
  'blended',
  'mongrel',
  'impure',
  'pure-bred',
];