export const definitions = [
  '"Johnson\'s reply hymns education"',
  '"they were hymning to their god"',
];
export const synonyms = [
  'praise',
  'applaud',
  'cheer',
  'commend',
  'approve',
  'welcome',
  'eulogize',
  'compliment',
  'congratulate',
  'celebrate',
  'sing the praises of',
  'make much of',
  'take one\'s hat off to',
  'salute',
  'lionize',
  'exalt',
  'admire',
  'hail',
  'toast',
  'flatter',
  'adulate',
  'vaunt',
  'extol',
  'glorify',
  'honor',
  'clap',
  'emblazon',
  'laud',
  'panegyrize',
  'express approval of',
  'express admiration for',
  'pay tribute to',
  'speak highly of',
  'praise to the skies',
  'rave about',
  'go into raptures about/over',
  'heap praise on',
  'wax lyrical about',
  'say nice things about',
  'pat on the back',
  'throw bouquets at',
  'cry someone/something up',
  'criticize',
];