export const definitions = [
  '"you\'re my ideal of how a man should be"',
  '"their intent is to guide and inspire psychologists toward the very highest ethical ideals of the profession"',
];
export const synonyms = [
  'perfection',
  'paragon',
  'epitome',
  'ne plus ultra',
  'beau idéal',
  'nonpareil',
  'crème de la crème',
  'the last word',
  'the ultimate',
  'a dream',
  'a nonesuch',
  'model',
  'pattern',
  'exemplar',
  'example',
  'paradigm',
  'archetype',
  'prototype',
  'criterion',
  'yardstick',
  'principle',
  'standard',
  'belief',
  'conviction',
  'persuasion',
  'morals',
  'morality',
  'ethics',
  'ideology',
  'creed',
  'integrity',
  'uprightness',
  'high-mindedness',
  'righteousness',
  'virtue',
  'probity',
  'rectitude',
  'honor',
  'decency',
  'conscience',
  'scruples',
  'rule of living',
  'moral value',
  'code of behavior',
  'code of honor',
  'sense of honor',
  'sense of duty',
];