export const definitions = [
  '"he had a feeling for phrase and idiom"',
  '"they were both working in a neo-impressionist idiom"',
];
export const synonyms = [
  'expression',
  'turn of phrase',
  'set phrase',
  'phrase',
  'locution',
  'idiomatic expression',
  'fixed expression',
  'language',
  'speech',
  'talk',
  '-speak',
  'usage',
  'phraseology',
  'phrasing',
  'vocabulary',
  'parlance',
  'tongue',
  'vernacular',
  'jargon',
  'patter',
  'argot',
  'patois',
  'cant',
  'locution',
  'mode of expression',
  'style of speech',
  'way/manner of speaking',
  'choice of words',
  'façon de parler',
  'vernacular',
  'patois',
  'regionalisms',
  'localisms',
  'provincialisms',
  'acrolect',
  'basilect',
  'sociolect',
  'idiolect',
  'regional language',
  'local language',
  'local tongue',
  'local speech',
  'local parlance',
  'variety of language',
  'nonstandard language',
];