export const definitions = [
  '"four men were idling outside the shop"',
  '"we idled the afternoon away"',
  '"Cal idled past MetroHealth at a stately pace"',
  '"he will close the newspaper, idling 2,200 workers"',
  '"the car is noisily idling in the street"',
];
export const synonyms = [
  'do nothing',
  'vegetate',
  'sit back',
  'take it easy',
  'rest on one\'s oars',
  'mark time',
  'twiddle one\'s thumbs',
  'languish',
  'go to seed',
  'degenerate',
  'molder',
  'stagnate',
  'fritter',
  'while',
  'laze',
  'loiter',
  'pass',
  'spend',
  'use',
  'employ',
  'use up',
  'occupy',
  'take up',
  'fill up',
  'fill in',
  'fill',
  'beguile',
  'expend',
  'devote',
  'waste',
  'dissipate',
  'kill',
  'be inactive',
  'kick one\'s heels',
  'kill time',
  'laze (around)',
  'lounge (around)',
  'loll (around)',
  'loaf (around)',
  'slouch (around)',
  'saunter',
  'stroll',
  'dawdle',
  'drift',
  'putter',
  'amble',
  'loiter',
  'maunder',
  'wander',
  'straggle',
  'go/walk slowly',
  'saunter',
  'stroll',
  'dawdle',
  'drift',
  'putter',
  'amble',
  'loiter',
  'maunder',
  'wander',
  'straggle',
  'go/walk slowly',
  'tick over',
  'run slowly in neutral',
  'tick over',
  'run slowly in neutral',
];