export const definitions = [
    '"her work juxtaposed images from serious and popular art"',
    '"Voyager 2 sent back images of the planet Neptune"',
    '"he had an image of Uncle Walter throwing his crutches away"',
    '"he\'s the image of his father"',
    '"we are made in the image of God"',
    '"she strives to project an image of youth"',
    '"he uses the image of a hole to describe emotional emptiness"',
    '"artworks that imaged women\'s bodies"',
    '"every point on the Ea\'s \'s surface was imaged by the satellite"',
    '"the hard disk drive should be imaged using a specialized bitstream backup product"',
    '"it is possible for us to image a society in which no one committed crime"',
]
export const synonyms = [
    'likeness',
    'resemblance',
    'depiction',
    'portrayal',
    'representation',
    'statue',
    'statuette',
    'sculpture',
    'bust',
    'effigy',
    'figure',
    'figurine',
    'doll',
    'carving',
    'painting',
    'picture',
    'portrait',
    'drawing',
    'sketch',
    'artist\'s impression',
    'picture',
    'facsimile',
    'photograph',
    'snapshot',
    'photo',
    'reproduction',
    'optical representation',
    'reflection',
    'mirror image',
    'likeness',
    'echo',
    'conception',
    'impression',
    'idea',
    'concept',
    'perception',
    'notion',
    'conceptualization',
    'vision',
    'fancy',
    'thought',
    'mental picture',
    'mental representation',
    'double',
    'replica',
    'lookalike',
    'clone',
    'copy',
    'reproduction',
    'twin',
    'duplicate',
    'facsimile',
    'counterpart',
    'mirror image',
    'similitude',
    'living image',
    'exact likeness',
    'Doppelgänger',
    'semblance',
    'guise',
    'appearance',
    'form',
    'shape',
    'aspect',
    'character',
    'mien',
    'outward form',
    'idol',
    'icon',
    'fetish',
    'golden calf',
    'totem',
    'talisman',
    'false god',
    'persona',
    'profile',
    'face',
    'identity',
    'front',
    'facade',
    'mask',
    'guise',
    'role',
    'part',
    'portrayal',
    'depiction',
    'public perception',
    'public conception',
    'public impression',
    'simile',
    'metaphor',
    'metonymy',
    'figure of speech',
    'trope',
    'turn of phrase',
    'conceit',
    'word picture',
    'figurative expression',
    'rhetorical device',
    'word painting',
    'envisage',
    'envision',
    'imagine',
    'picture',
    'dream up',
    'conceive of',
    'see in one\'s mind\'s eye',
]