export const definitions = [
  '"there was the sound of a third impact"',
  '"bullets that expand and cause devastating injury on impact"',
  '"our regional measures have had a significant impact on unemployment"',
  '"the shell impacted twenty yards away"',
  '"an asteroid impacted the earth some 60 million years ago"',
  '"the animals\' feet do not impact and damage the soil as cows\' hooves do"',
  '"high interest rates have impacted on retail spending"',
  '"the move is not expected to impact the company\'s employees"',
];
export const synonyms = [
  'collision',
  'crash',
  'smash',
  'clash',
  'bump',
  'bang',
  'knock',
  'jolt',
  'thump',
  'whack',
  'thwack',
  'slam',
  'smack',
  'contact',
  'effect',
  'influence',
  'impression',
  'footprint',
  'results',
  'aftermath',
  'consequences',
  'repercussions',
  'ramifications',
  'reverberations',
  'hit',
  'strike',
  'ram',
  'crash into',
  'smash into',
  'collide with',
  'be in collision with',
  'smack into',
  'slam into',
  'bang into',
  'cannon into',
  'plow into',
  'meet head-on',
  'dash against',
  'affect',
  'influence',
  'act',
  'work',
  'strike',
  'hit',
  'touch',
  'change',
  'alter',
  'modify',
  'transform',
  'shape',
  'control',
  'govern',
  'determine',
  'decide',
  'sway',
  'bias',
  'have an effect',
  'have an influence',
  'exert influence',
  'make an impression',
];