export const definitions = [
    '"teachers had a duty to impart strong morals to their students"',
    '"its main use has been to impart a high surface gloss to finished articles"',
]
export const synonyms = [
    'communicate',
    'pass on',
    'convey',
    'transmit',
    'relay',
    'relate',
    'recount',
    'set forth',
    'present',
    'tell',
    'report',
    'announce',
    'proclaim',
    'spread',
    'disseminate',
    'circulate',
    'promulgate',
    'broadcast',
    'disclose',
    'reveal',
    'divulge',
    'discover',
    'unbosom',
    'make known',
    'make public',
    'go public with',
    'bring into the open',
    'keep to oneself',
    'give',
    'bestow',
    'confer',
    'grant',
    'lend',
    'accord',
    'afford',
    'provide',
    'supply',
    'offer',
    'yield',
    'contribute',
    'remove',
]