export const definitions = [
  '"Japan\'s reluctance to import more cars"',
  '"new beliefs were often imported by sailors"',
  '"having thus seen, what is imported in a Man\'s trusting his Heart"',
  '"they passed a resolution importing that they relied on His Maje\'s \'s gracious promise"',
  '"cheap imports from eastern Europe"',
  '"this surplus pushes up the yen, which ought to boost imports"',
  '"the import of live cattle from Canada"',
  '"the import of her message is clear"',
  '"pronouncements of world-shaking import"',
];
export const synonyms = [
  'bring in',
  'buy in',
  'buy from abroad',
  'bring from abroad',
  'ship in',
  'source from abroad',
  'export',
  'imported commodity',
  'foreign commodity',
  'nondomestic commodity',
  'export',
  'importation',
  'importing',
  'introduction',
  'bringing in',
  'bringing from abroad',
  'buying from abroad',
  'sourcing from abroad',
  'shipping in',
  'export',
  'meaning',
  'sense',
  'essence',
  'gist',
  'drift',
  'purport',
  'message',
  'thrust',
  'substance',
  'implication',
  'signification',
  'point',
  'burden',
  'tenor',
  'spirit',
  'pith',
  'core',
  'nub',
  'sum and substance',
  'importance',
  'significance',
  'consequence',
  'moment',
  'momentousness',
  'magnitude',
  'substance',
  'weight',
  'weightiness',
  'note',
  'noteworthiness',
  'gravity',
  'seriousness',
  'insignificance',
];