export const definitions = [
    '"a charity for the relief of indigent artists"',
]
export const synonyms = [
    'poor',
    'impecunious',
    'destitute',
    'penniless',
    'impoverished',
    'poverty-stricken',
    'down and out',
    'pauperized',
    'insolvent',
    'ruined',
    'needy',
    'hard up',
    'hard-pressed',
    'deprived',
    'disadvantaged',
    'distressed',
    'badly off',
    'beggarly',
    'beggared',
    'penurious',
    'without a penny to one\'s name',
    'without two farthings/pennies to rub together',
    'in need',
    'in want',
    'on the breadline',
    'in reduced/straitened circumstances',
    'rich',
    'pauper',
    'bankrupt',
    'insolvent',
    'beggar',
    'mendicant',
    'vagrant',
    'tramp',
    'drifter',
    'derelict',
    'vagabond',
    'knight of the road',
    'bird of passage',
    'rolling stone',
    'job-seeker',
    'hobo',
    'bagman',
    'knockabout',
    'overlander',
    'sundowner',
    'whaler',
    'the homeless',
    'poor person',
    'homeless person',
    'person of no fixed address/abode',
    'unemployed person',
    'streety',
    'the poor',
    'the destitute',
    'the needy',
    'the unemployed',
]