export const definitions = [
  '"the pickets induced many workers to stay away"',
  '"none of these measures induced a change of policy"',
  '"the current in the primary winding is induced by the rotating magnet"',
  '"she was 11 days overdue when labor was induced"',
  '"Carol was induced just four days before her baby\'s due date"',
  '"from the experimental evidence, one infers or induces the hypothesis"',
];
export const synonyms = [
  'persuade',
  'convince',
  'get',
  'make',
  'prompt',
  'move',
  'inspire',
  'instigate',
  'influence',
  'press',
  'urge',
  'incite',
  'encourage',
  'impel',
  'actuate',
  'motivate',
  'talk into',
  'procure',
  'prevail upon',
  'exert influence on',
  'coax into',
  'wheedle into',
  'cajole into',
  'prod into',
  'dissuade',
  'bring about',
  'bring on',
  'cause',
  'produce',
  'effect',
  'create',
  'give rise to',
  'generate',
  'originate',
  'instigate',
  'engender',
  'occasion',
  'develop',
  'whip up',
  'stir up',
  'kindle',
  'arouse',
  'rouse',
  'foster',
  'promote',
  'encourage',
  'beget',
  'enkindle',
  'effectuate',
  'be the cause of',
  'set in motion',
  'lead to',
  'result in',
  'have as a consequence',
  'have as a result',
  'trigger off',
  'spark off',
  'prevent',
];