export const definitions = [
    '"a day that will live in infamy"',
    '"one of history\'s greatest infamies"',
]
export const synonyms = [
    'notoriety',
    'disrepute',
    'disreputableness',
    'ill repute',
    'disgrace',
    'discredit',
    'shame',
    'dishonor',
    'ignominy',
    'scandal',
    'censure',
    'blame',
    'disapprobation',
    'condemnation',
    'contempt',
    'humiliation',
    'loss of face',
    'disesteem',
    'wickedness',
    'evil',
    'baseness',
    'sordidness',
    'vileness',
    'iniquity',
    'iniquitousness',
    'depravity',
    'degeneracy',
    'turpitude',
    'immorality',
    'unscrupulousness',
    'corruption',
    'dissolution',
    'sin',
    'wrong',
    'offense',
    'violation',
    'abuse',
    'indignity',
    'ill fame',
    'loss of reputation',
    'honor',
    'anonymity',
    'virtue',
]