export const definitions = [
    '"those who were old or infirm"',
    '"elderly and infirm people"',
    '"care for the infirm"',
    '"he was infirm of purpose"',
]
export const synonyms = [
    'frail',
    'weak',
    'feeble',
    'enfeebled',
    'weakly',
    'debilitated',
    'decrepit',
    'bedridden',
    'ill',
    'unwell',
    'sick',
    'sickly',
    'poorly',
    'indisposed',
    'failing',
    'ailing',
    'doddering',
    'doddery',
    'tottering',
    'wobbly',
    'unsteady',
    'unstable',
    'in poor/declining health',
    'strong',
    'healthy',
]