export const definitions = [
    '"her work is infused with an anger born of pain and oppression"',
    '"he did his best to infuse good humor into his voice"',
    '"infuse the dried flowers in boiling water"',
    '"allow the mixture to infuse for 15 minutes"',
    '"saline was infused into the aorta"',
]
export const synonyms = [
    'fill',
    'pervade',
    'permeate',
    'suffuse',
    'charge',
    'saturate',
    'imbue',
    'inspire',
    'inundate',
    'instil',
    'breathe',
    'inject',
    'impart',
    'inculcate',
    'introduce',
    'implant',
    'add',
    'steep',
    'brew',
    'stew',
    'soak',
    'immerse',
    'marinate',
    'souse',
    'mast',
]