export const definitions = [
    '"lead will poison anyone if enough is ingested"',
    '"they ingest oxygen from the air"',
    '"he spent his days ingesting the contents of the library"',
]
export const synonyms = [
    'eat',
    'consume',
    'take',
    'taste',
    'swallow',
    'devour',
    'ingurgitate',
    'bib',
    'munch (on)',
    'partake of',
    'feast on',
    'gulp (down)',
    'gobble (down)',
    'wolf (down)',
    'scoff (down)',
    'tuck in/into',
    'breakfast (on)',
    'lunch (on)',
    'dine (on)',
    'have breakfast',
    'have lunch',
    'have dinner',
    'have tea',
    'have supper',
    'absorb',
    'assimilate',
    'digest',
    'take in',
    'be absorbed in',
    'be immersed in',
    'be rapt in',
    'be lost in',
    'be fascinated by',
    'pay close attention to',
]