export const definitions = [
    '"she insisted on carrying her own bag"',
    '"I\'ll call him and cancel it, if you insist"',
    '"he insisted on answers to his allegations"',
    '"the heavy studded boots she insisted on wearing"',
    '"the chairman insisted that all was not doom and gloom"',
    '"\"I really am all right now,\" Isabel insisted"',
]
export const synonyms = [
    'stand one\'s ground',
    'hold on',
    'hold out',
    'not take no for an answer',
    'persevere',
    'persist',
    'demand',
    'command',
    'require',
    'dictate',
    'importune',
    'entreat',
    'urge',
    'exhort',
    'stand firm',
    'be firm',
    'make a stand',
    'stand up for oneself',
    'be resolute',
    'be determined',
    'show determination',
    'be emphatic',
    'brook no refusal',
    'not give up',
    'keep on at someone',
    'give up',
    'call for',
    'ask for',
    'request',
    'push for',
    'hold out for',
    'claim',
    'requisition',
    'stipulate',
    'exact',
    'impose',
    'expect',
    'look for',
    'press for',
    'clamor for',
    'bay for',
    'insist on',
    'lay claim to',
    'make a condition of',
    'maintain',
    'assert',
    'hold',
    'contend',
    'argue',
    'protest',
    'claim',
    'aver',
    'avow',
    'vow',
    'swear',
    'state',
    'declare',
    'announce',
    'pronounce',
    'proclaim',
    'propound',
    'emphasize',
    'stress',
    'repeat',
    'reiterate',
    'avouch',
    'asseverate',
    'represent',
    'be emphatic',
]