export const definitions = [
    '"you\'re insulting the woman I love"',
    '"he hurled insults at us"',
    '"he saw the book as a deliberate insult to the Church"',
    '"the present offer is an absolute insult"',
    '"the movement of the bone causes a severe tissue insult"',
]
export const synonyms = [
    'offend',
    'affront',
    'abuse',
    'call someone names',
    'slight',
    'disparage',
    'discredit',
    'libel',
    'slander',
    'malign',
    'defame',
    'denigrate',
    'impugn',
    'slur',
    'revile',
    'calumniate',
    'hurt',
    'mortify',
    'humiliate',
    'wound',
    'snub',
    'rebuff',
    'spurn',
    'shun',
    'ignore',
    'turn one\'s back on',
    'asperse',
    'derogate',
    'miscall',
    'abusive',
    'rude',
    'vulgar',
    'offensive',
    'wounding',
    'mortifying',
    'humiliating',
    'disparaging',
    'belittling',
    'derogatory',
    'depreciating',
    'deprecatory',
    'disrespectful',
    'denigratory',
    'uncomplimentary',
    'pejorative',
    'vituperative',
    'disdainful',
    'derisive',
    'scornful',
    'contemptuous',
    'defamatory',
    'slanderous',
    'libelous',
    'scurrilous',
    'blasphemous',
    'discrediting',
    'contumelious',
    'give/cause offense to',
    'be rude to',
    'cast aspersions on',
    'hurt someone\'s feelings',
    'treat disrespectfully',
    'cut dead',
    'give someone the cold-shoulder',
    'compliment',
    'flatter',
    'complimentary',
    'polite',
    'jibe',
    'affront',
    'slight',
    'snub',
    'barb',
    'slur',
    'injury',
    'libel',
    'slander',
    'defamation',
    'abuse',
    'disparagement',
    'depreciation',
    'impugnment',
    'revilement',
    'humiliation',
    'indignity',
    'insolence',
    'rudeness',
    'aspersions',
    'contumely',
    'abusive remark',
    'backhanded compliment',
    'compliment',
]