export const definitions = [
    '"the table should be insured for $2,500"',
    '"the company had insured itself against a fall of the dollar"',
    '"businesses can insure against exchange rate fluctuations"',
    '"subsidiaries set up to insure the risks of a group of companies"',
    '"by appeasing Celia they might insure themselves against further misfortune"',
    '"such changes could insure against further violence and unrest"',
]
export const synonyms = [
    'sponsor',
    'support',
    'back',
    'indemnify',
    'subsidize',
    'finance',
    'fund',
    'sanction',
    'approve',
    'confirm',
    'ratify',
    'validate',
    'authenticate',
    'certify',
    'seal',
    'guarantee',
    'warrant',
    'accredit',
    'provide security for',
    'take the risk for',
    'contribute to',
    'pay for',
    'provide capital for',
    'agree to',
    'protect',
    'indemnify',
    'cover',
    'underwrite',
    'assure',
    'guarantee',
    'warrant',
]