export const definitions = [
    '"the family were interned for the duration of the war as enemy aliens"',
]
export const synonyms = [
    'trainee',
    'apprentice',
    'probationer',
    'student',
    'novice',
    'learner',
    'beginner',
    'person doing work experience',
    'imprison',
    'incarcerate',
    'impound',
    'jail',
    'detain',
    'hold',
    'lock up',
    'confine',
    'immure',
    'put in jail',
    'put behind bars',
    'take into custody',
    'hold in custody',
    'hold captive',
    'keep under lock and key',
    'detain at Her Majesty\'s pleasure',
    'release',
]