export const definitions = [
    '"it was all part of a grander French plan to invade Ireland"',
    '"they would invade at dawn"',
    '"demonstrators invaded the Presidential Palace"',
    '"sometimes the worms invade the central nervous system"',
    '"he felt his privacy was being invaded"',
]
export const synonyms = [
    'occupy',
    'conquer',
    'capture',
    'seize',
    'take (over)',
    'annex',
    'win',
    'gain',
    'secure',
    'overrun',
    'overwhelm',
    'storm',
    'attack',
    'assail',
    'assault',
    'raid',
    'plunder',
    'maraud',
    'march into',
    'descend on',
    'swoop on',
    'swarm over',
    'surge over',
    'make inroads on',
    'withdraw from',
    'permeate',
    'pervade',
    'fill',
    'imbue',
    'perfuse',
    'assail',
    'attack',
    'take over',
    'spread through/over',
    'diffuse through',
    'be disseminated through',
    'flow through',
    'violate',
    'interrupt',
    'disturb',
    'disrupt',
    'intrude on',
    'encroach on',
    'infringe on',
    'trespass on',
    'obtrude on',
    'burst in on',
    'entrench on',
    'respect',
]