export const definitions = [
  '"the company is to invest $12 million in its new manufacturing site"',
  '"getting workers to invest in private pension funds"',
  '"politicians who have invested so much time in the Constitution would be crestfallen"',
  '"I invested in an expensive moisturizer and tried to drink more water"',
  '"the passage of time has invested the words with an unintended humor"',
  '"he was invested as Head of State on October 1,1936"',
  '"all executive powers were invested in the Secretary of State"',
  '"he stands before you invested in the full canonicals of his calling"',
  '"Fort Pulaski was invested and captured"',
];
export const synonyms = [
  'fund',
  'back',
  'finance',
  'underwrite',
  'subsidize',
  'support',
  'buy into',
  'put money into',
  'sink money into',
  'lay out money on',
  'plow money into',
  'provide capital for',
  'spend money on',
  'pay for',
  'buy shares in',
  'buy/take a stake in',
  'spend',
  'expend',
  'lay out',
  'put in',
  'plow in',
  'use up',
  'devote',
  'venture',
  'speculate',
  'risk',
  'gamble',
  'contribute',
  'donate',
  'give',
  'purchase',
  'acquire',
  'obtain',
  'get',
  'pick up',
  'snap up',
  'take',
  'secure',
  'procure',
  'come by',
  'make a/the purchase of',
  'pay for',
  'shop for',
  'invest in',
  'put money into',
  'sell',
  'imbue',
  'infuse',
  'perfuse',
  'charge',
  'steep',
  'saturate',
  'suffuse',
  'pervade',
  'fill',
  'endow',
  'instate',
  'install',
  'induct',
  'swear in',
  'ordain',
  'anoint',
  'crown',
  'enthrone',
  'admit to office',
  'vest in',
  'endow in',
  'confer on',
  'bestow on',
  'grant to',
  'entrust to',
  'give to',
  'consign to',
  'put in someone\'s hands',
  'dress',
  'attire',
  'outfit',
  'array',
  'rig (out)',
  'turn out',
  'fit out',
  'costume',
  'robe',
  'garb',
  'drape',
  'accoutre',
  'bedizen',
  'caparison',
  'apparel',
  'habit',
  'trick out/up',
  'deck out',
  'put clothes on',
  'trap out',
  'undress',
  'besiege',
  'lay siege to',
  'beleaguer',
  'beset',
  'surround',
  'enclose',
];