export const definitions = [
  '"the antiquated defense of insanity is rarely invoked today"',
  '"she invoked his help against this attack"',
  '"how could she explain how the accident happened without invoking his wrath?"',
];
export const synonyms = [
  'cite',
  'adduce',
  'instance',
  'turn to',
  'use',
  'refer to',
  'resort to',
  'have recourse to',
  'call into use',
  'put into effect/use',
  'waive',
  'call on',
  'supplicate',
  'entreat',
  'solicit',
  'beseech',
  'beg',
  'implore',
  'importune',
  'petition',
  'call for',
  'request',
  'impetrate',
  'pray to',
  'appeal to',
  'plead with',
  'obtest',
  'obsecrate',
  'summon',
  'call (up)',
  'bring',
  'conjure (up)',
  'bring forth',
  'bring on',
  'elicit',
  'induce',
  'cause',
  'kindle',
  'bring out',
];