export const definitions = [
    '"serve liver as it\'s a good source of iron"',
    '"how are your iron levels ? "',
    '"her father had a will of iron"',
    '"the iron grip of the president on every aspect of foreign policy"',
    '"a caulking iron"',
    '"a four-iron"',
]
export const synonyms = [
    'ferric',
    'ferrous',
    'made of iron',
    'strength',
    'toughness',
    'resilience',
    'fortitude',
    'firmness',
    'robustness',
    'hardiness',
    'steel',
    'uncompromising',
    'unrelenting',
    'unyielding',
    'unbending',
    'resolute',
    'resolved',
    'determined',
    'firm',
    'rigid',
    'steadfast',
    'unwavering',
    'stern',
    'strict',
    'unvacillating',
    'weakness',
    'weak',
    'flexible',
    'tool',
    'implement',
    'utensil',
    'device',
    'apparatus',
    'appliance',
    'contrivance',
    'contraption',
    'mechanism',
    'manacles',
    'shackles',
    'fetters',
    'chains',
    'restraints',
    'handcuffs',
    'trammels',
    'flat iron',
    'steam iron',
    'electric iron',
    'smoothing iron',
    'press',
]