export const definitions = [
  '"the issue of global warming"',
  '"money is not an issue"',
  '"a nice guy with a great sense of humor and not too many issues"',
  '"a small number of users are experiencing connectivity issues"',
  '"the issue of promissory notes by the bank"',
  '"a share issue has been launched"',
  '"the December issue of the magazine"',
  '"the chance of carrying such a scheme to a successful issue was small"',
  '"the point of issue"',
  '"an issue of blood"',
  '"he died without male issue"',
  '"licenses were issued indiscriminately to any company"',
  '"everyone was issued with a gas mask"',
  '"the minister issued a statement"',
  '"Christmas stamps to be issued in November"',
  '"exotic smells issued from a nearby building"',
  '"the struggles of history issue from the divided heart of humanity"',
];
export const synonyms = [
  'matter',
  'affair',
  'business',
  'subject',
  'topic',
  'question',
  'point',
  'item',
  'thing',
  'case',
  'concern',
  'theme',
  'proceeding',
  'situation',
  'occasion',
  'circumstance',
  'problem',
  'bone of contention',
  'controversy',
  'argument',
  'matter in question',
  'point at issue',
  'issuing',
  'issuance',
  'publication',
  'publishing',
  'circulation',
  'distribution',
  'supplying',
  'supply',
  'delivery',
  'appearance',
  'sending out',
  'issuing',
  'issuance',
  'publication',
  'publishing',
  'circulation',
  'distribution',
  'supplying',
  'supply',
  'delivery',
  'appearance',
  'sending out',
  'edition',
  'number',
  'installment',
  'copy',
  'printing',
  'imprint',
  'impression',
  'version',
  'publication',
  'result',
  'outcome',
  'consequence',
  'end result',
  'upshot',
  'effect',
  'aftereffect',
  'aftermath',
  'conclusion',
  'end',
  'denouement',
  'net result',
  'discharge',
  'emission',
  'release',
  'outflow',
  'outflowing',
  'outpouring',
  'outrush',
  'rush',
  'flood',
  'deluge',
  'spurt',
  'jet',
  'cascade',
  'stream',
  'torrent',
  'gush',
  'flow',
  'flux',
  'welling',
  'leakage',
  'escape',
  'drain',
  'drainage',
  'excretion',
  'secretion',
  'ejection',
  'disgorgement',
  'debouchment',
  'emanation',
  'exudation',
  'exuding',
  'venting',
  'effluence',
  'effluent',
  'effusion',
  'efflux',
  'outflux',
  'offspring',
  'descendants',
  'heirs',
  'successors',
  'children',
  'progeny',
  'scions',
  'family',
  'youngsters',
  'babies',
  'seed',
  'fruit',
  'sons or daughters',
  'fruit of one\'s loins',
  'supply',
  'provide',
  'furnish',
  'arm',
  'equip',
  'fit out',
  'rig out',
  'accoutre',
  'outfit',
  'fit up',
  'provision',
  'stock',
  'purvey',
  'accommodate',
  'present',
  'invest',
  'endow',
  'favor',
  'kit out',
  'withdraw',
  'send out',
  'put out',
  'release',
  'deliver',
  'publish',
  'announce',
  'proclaim',
  'broadcast',
  'promulgate',
  'communicate',
  'impart',
  'purvey',
  'circulate',
  'distribute',
  'spread',
  'disseminate',
  'utter',
  'bruit about/abroad',
  'withdraw',
  'emanate',
  'emerge',
  'proceed',
  'exude',
  'discharge',
  'flow (out/forth)',
  'pour (out/forth)',
  'gush (out/forth)',
  'come (out/forth)',
  'seep (out/forth)',
  'ooze (out/forth)',
  'spread out',
  'be uttered',
  'be emitted',
  'be transmitted',
  'result',
  'follow',
  'ensue',
  'develop',
  'stem',
  'spring',
  'arise',
  'start',
  'derive',
  'evolve',
  'proceed',
  'emerge',
  'emanate',
  'flow',
  'attend',
  'accompany',
  'be got',
  'be had',
  'be taken',
  'be caused by',
  'be the result of',
  'be brought on/about by',
  'be produced by',
  'originate in',
  'have its origin in',
  'be consequent on',
  'supervene on',
  'bring about',
];