export const definitions = [
  '"I have itemized the morning\'s tasks"',
  '"an itemized bill"',
];
export const synonyms = [
  'analyze',
  'break down',
  'split up',
  'dissect',
  'take apart',
  'deconstruct',
  'list',
  'catalog',
  'inventory',
  'record',
  'set out',
  'set forth',
  'spell out',
  'document',
  'register',
  'tabulate',
  'detail',
  'particularize',
  'specify',
  'identify',
  'cite',
  'name',
  'mention',
  'give',
  'enumerate',
  'number',
];