export const definitions = [
  '"he jabbered away to his friends"',
  '"stop your jabber"',
];
export const synonyms = [
  'prattle',
  'babble',
  'chatter',
  'twitter',
  'prate',
  'gabble',
  'go on',
  'run on',
  'yap',
  'jibber-jabber',
  'patter',
  'blather',
  'maunder',
  'ramble',
  'drivel',
  'blab',
  'twaddle',
  'clack',
  'rattle on/away',
  'talk rapidly',
  'talk incoherently',
  'talk unintelligibly',
  'twattle',
  'prattle',
  'babble',
  'chatter',
  'chattering',
  'twitter',
  'twittering',
  'prating',
  'gabble',
  'jibber-jabber',
  'patter',
  'blather',
  'rambling',
  'twaddle',
  'drivel',
  'clack',
  'rapid talk',
  'unintelligible talk',
  'twattle',
];