export const definitions = [
    '"a race car driver, jacked up on amphetamines"',
    '"we\'re jacked about going to the semifinals"',
    '"a dude so jacked you have to wonder if he\'s freebasing creatine"',
    '"his MO in the studio remains the same—jack other peo\'s \'s tracks and present them in a new context"',
    '"they jacked him for his car"',
]
export const synonyms = [
    'strong',
    'brawny',
    'muscly',
    'sinewy',
    'well built',
    'burly',
    'strapping',
    'sturdy',
    'rugged',
    'powerful',
    'broad-shouldered',
    'athletic',
    'well knit',
    'muscle-bound',
    'Herculean',
    'manly',
    'stalwart',
    'thewy',
    'mesomorphic',
    'powerfully built',
    'well muscled',
]