export const definitions = [
  '"a bell jangled loudly"',
  '"Ryan stood on the terrace jangling his keys"',
  '"a thirty-eight point game that jangled the nerves"',
  '"the jangle of a telephone"',
];
export const synonyms = [
  'clank',
  'clink',
  'jingle',
  'tinkle',
  'ding',
  'ping',
  'clang',
  'clash',
  'clatter',
  'rattle',
  'vibrate',
  'ring',
  'chime',
  'tintinnabulate',
  'irritate',
  'disturb',
  'assault',
  'fray',
  'rasp',
  'shred',
  'test',
  'rattle',
  'grate on',
  'jar on',
  'put/set on edge',
  'rub raw',
  'stretch tight',
  'wreak havoc on',
  'clank',
  'clanking',
  'clink',
  'clinking',
  'chink',
  'chinking',
  'jangling',
  'jingle',
  'jingling',
  'clash',
  'clashing',
  'clang',
  'clanging',
  'rattle',
  'rattling',
  'clangor',
  'cacophony',
  'din',
  'racket',
  'noise',
  'discord',
  'dissonance',
  'discordance',
  'caterwauling',
  'raucousness',
  'stridency',
  'stridor',
  'tintinnabulation',
];