export const definitions = [
    '"there was no mistaking that jaunty walk"',
]
export const synonyms = [
    'cheerful',
    'cheery',
    'happy',
    'merry',
    'jolly',
    'joyful',
    'gleeful',
    'glad',
    'lively',
    'vivacious',
    'perky',
    'bright',
    'sunny',
    'buoyant',
    'bubbly',
    'bouncy',
    'breezy',
    'frisky',
    'exuberant',
    'ebullient',
    'effervescent',
    'sparkling',
    'sparkly',
    'sprightly',
    'spry',
    'carefree',
    'unworried',
    'untroubled',
    'blithe',
    'airy',
    'lighthearted',
    'nonchalant',
    'insouciant',
    'happy-go-lucky',
    'free and easy',
    'easygoing',
    'blasé',
    'devil-may-care',
    'casual',
    'relaxed',
    'gay',
    'blithesome',
    'perk',
    'wick',
    'full of life',
    'full of the joys of spring',
    'in good spirits',
    'without a care in the world',
    'as merry/lively as a grig',
    'depressed',
    'serious',
    'sedate',
]