export const definitions = [
  '"some of the younger men jeered at him"',
  '"the performers were jeered and heckled"',
];
export const synonyms = [
  'taunt',
  'mock',
  'ridicule',
  'deride',
  'tease',
  'insult',
  'abuse',
  'scorn',
  'heckle',
  'interrupt',
  'hector',
  'scoff at',
  'laugh at',
  'sneer at',
  'jibe (at)',
  'shout disapproval (at)',
  'shout at/down',
  'catcall (at)',
  'boo (at)',
  'hoot at',
  'whistle at',
  'hiss (at)',
  'blow raspberries (at)',
  'flout at',
  'cheer',
  'applaud',
];