export const definitions = [
  '"the food was great, especially the jerked chicken and ribs"',
  '"authentic Jamaican jerked pork"',
  '"the van jerked forward"',
  '"she jerked her chin up"',
  '"the thud jerked her back to reality"',
  '"If they didn\'t use pimento to jerk the chicken it\'s not the original Jamaican jerk chicken"',
  '"they became excellent marksmen, poaching the wild cattle and jerking the beef"',
];
export const synonyms = [
  'yank',
  'tug',
  'pull',
  'wrench',
  'wrest',
  'heave',
  'haul',
  'drag',
  'tweak',
  'twitch',
  'pluck',
  'snatch',
  'seize',
  'rip',
  'tear',
  'whisk',
  'jolt',
  'lurch',
  'bump',
  'jog',
  'bang',
  'rattle',
  'bounce',
  'shake',
  'jounce',
  'ease',
  'glide',
  'yank',
  'tug',
  'pull',
  'wrench',
  'wrest',
  'heave',
  'haul',
  'drag',
  'tweak',
  'twitch',
  'pluck',
  'snatch',
  'seize',
  'rip',
  'tear',
  'whisk',
  'ease',
];