export const definitions = [
    '"he stood up and jigged in the cockpit"',
    '"we were jigging about in our seats"',
    '"the floor space was jigged and tooled to produce six fuselages a month"',
    '"a man jigged for squid"',
]
export const synonyms = [
    'skip',
    'hop',
    'prance',
    'caper',
    'bounce',
    'curvet',
    'rollick',
    'capriole',
    'jounce',
    'bob up and down',
    'leap up and down',
    'jump up and down',
    'spring up and down',
    'skip',
    'hop',
    'prance',
    'caper',
    'bounce',
    'curvet',
    'rollick',
    'capriole',
    'jounce',
    'bob up and down',
    'leap up and down',
    'jump up and down',
    'spring up and down',
]