export const definitions = [
  '"a bout of the jitters"',
  '"picture jitter"',
  '"an anxious student who jittered at any provocation"',
];
export const synonyms = [
  'nervousness',
  'nerves',
  'edginess',
  'uneasiness',
  'anxiety',
  'anxiousness',
  'tension',
  'agitation',
  'fretfulness',
  'restlessness',
  'fidgeting',
  'trembling',
  'shaking',
  'jumpiness',
  'stage fright',
  'buck fever',
  'worriment',
  'fit of nerves',
  'Joe Blakes',
  'calmness',
  'serenity',
];