export const definitions = [
    '"the steering wheel juddered in his hand"',
    '"the plane juddered to a halt"',
    '"the car gave a judder"',
]
export const synonyms = [
    'quiver',
    'shake',
    'tremble',
    'quaver',
    'waver',
    'shiver',
    'shudder',
    'jiggle',
    'wobble',
    'rock',
    'undulate',
    'move',
    'heave',
    'convulse',
    'jerk',
    'jolt',
    'jar',
    'oscillate',
    'vacillate',
    'swing',
    'sway',
    'wave',
    'agitate',
    'waggle',
    'wag',
    'wigwag',
    'move to and fro',
    'swing back and forth',
    'swing backwards and forwards',
    'quiver',
    'quivering',
    'shake',
    'shaking',
    'quaver',
    'quavering',
    'quake',
    'quaking',
    'tremble',
    'trembling',
    'tremor',
    'shiver',
    'shivering',
    'shudder',
    'shuddering',
    'oscillation',
    'vacillation',
    'shaking movement',
]