export const definitions = [
    '"she gave us a big jug of water"',
    '"three months in the jug"',
    '"the hotel could jug him for trespassing"',
]
export const synonyms = [
    'pitcher',
    'ewer',
    'crock',
    'jar',
    'urn',
    'carafe',
    'flask',
    'flagon',
    'decanter',
    'vessel',
    'receptacle',
    'container',
    'toby jug',
    'creamer',
    'amphora',
    'jorum',
    'graybeard',
    'pitcher',
    'ewer',
    'crock',
    'jar',
    'urn',
    'carafe',
    'flask',
    'flagon',
    'decanter',
    'vessel',
    'receptacle',
    'container',
    'toby jug',
    'creamer',
    'amphora',
    'jorum',
    'graybeard',
    'jail',
    'lockup',
    'guardhouse',
    'detention center',
    'penitentiary',
    'jailhouse',
    'boot camp',
    'stockade',
    'house of correction',
    'pound',
    'roundhouse',
    'borstal',
    'bridewell',
    'tollbooth',
    'bastille',
    'reformatory',
    'penal institution',
    'place of detention',
    'place of confinement',
    'young offender institution',
    'correctional facility',
    'youth custody centre',
    'approved school',
    'mammary gland',
    'mamma',
    'bosom(s)',
    'bust',
    'chest',
    'dugs',
    'paps',
    'embonpoint',
    'braise',
    'casserole',
    'fricassee',
    'simmer',
    'boil',
    'seethe',
    'smoor',
    'accuse',
    'cite',
    'summons',
    'sue',
    'try',
    'charge',
    'indict',
    'arraign',
    'impeach',
    'incarcerate',
    'jail',
    'lock up',
    'put away',
    'intern',
    'confine',
    'detain',
    'hold',
    'immure',
    'take to court',
    'bring/institute legal proceedings against',
    'bring an action against',
    'take legal action against',
    'bring to trial',
    'put on trial',
    'put in the dock',
    'bring a charge against',
    'bring a criminal charge against',
    'prefer charges against',
    'bring a suit against',
    'implead',
    'put in prison',
    'send to prison',
    'take into custody',
    'put under lock and key',
    'hold prisoner',
    'hold captive',
    'put into detention',
    'put in chains',
    'put in irons',
    'clap in irons',
    'detain at Her Majesty\'s pleasure',
    'defend',
    'let off',
    'pardon',
    'free',
    'release',
]