export const definitions = [
    '"junior tennis"',
    '"junior pupils"',
    '"his junior year in college"',
    '"John F. Kennedy Junior"',
    '"part of my function is to supervise those junior to me"',
    '"Virginia\'s junior senator"',
    '\'s \'s five years her junior"',
    '"high-school juniors and seniors"',
    '"indoor tennis for juniors"',
    '"he said: \"there\'s Junior,\" referring to his son"',
    '"an office junior"',
]
export const synonyms = [
    'younger',
    'youngest',
    'senior',
    'older',
    'minor',
    'the Younger',
    'II',
    'Senior',
    'low-ranking',
    'lower-ranking',
    'subordinate',
    'sub-',
    'lesser',
    'lower',
    'minor',
    'secondary',
    'inferior',
    'beneath',
    'under',
    'higher-ranking',
    'senior',
    'subordinate',
    'inferior',
    'deputy',
    'assistant',
    'adjutant',
    'aide',
    'minion',
    'lackey',
    'flunkey',
    'menial',
    'retainer',
    'vassal',
    'subject',
    'serf',
    'hireling',
    'servant',
    'henchman',
    'myrmidon',
    'factotum',
    'stooge',
    'follower',
    'camp follower',
    'hanger-on',
    'disciple',
    'scullion',
    'servitor',
    'right-hand man/woman',
    'girl/man Friday',
    'boss',
    'leader',
]