export const definitions = [
    '"I\'m your friend, not your keeper"',
    '"this disc is a keeper and one that belongs on every serious DVD collector\'s shelf"',
    '"if\'s \'s a good communicator and a great listener,\'s \'s a keeper"',
    '"hazelnuts are good keepers"',
]
export const synonyms = [
    'guardian',
    'protector',
    'defender',
    'guard',
    'bodyguard',
    'escort',
    'attendant',
    'chaperone',
    'nursemaid',
    'nurse',
    'minder',
    'carer',
    'curator',
    'conservator',
    'custodian',
    'guardian',
    'administrator',
    'overseer',
    'steward',
    'caretaker',
    'superintendent',
    'governor',
    'warden',
    'attendant',
]