export const definitions = [
    '"d\'ye ken anyone who can boast of that ? "',
    '"that\'s him—d\'ye ken him ? "',
]
export const synonyms = [
    'be friends with',
    'understand',
    'be acquainted with',
    'have met',
    'be familiar with',
    'be friendly with',
    'be on good terms with',
    'be close to',
    'be intimate with',
    'socialize with',
    'associate with',
    'have dealings with',
    'have insight into',
    'be in sympathy with',
    'empathize with',
    'identify',
    'place',
    'know',
    'pick out',
    'put a name to',
    'remember',
    'recall',
    'recollect',
    'know again',
    'call to mind',
    'know by sight',
    'agnize',
    'forget',
]