export const definitions = [
    '"a love of art was kindled in me"',
    '"she hesitated, suspicion kindling within her"',
    '"the young man kindled at once"',
    '"a day or two before she kindles, the mother will pull out some of her fur to make a soft lining"',
]
export const synonyms = [
    'light',
    'ignite',
    'set fire to',
    'put a match to',
    'start',
    'touch off',
    'spark',
    'set alight',
    'set light to',
    'set on fire',
    'set burning',
    'get going',
    'douse',
    'extinguish',
    'put out',
    'rouse',
    'arouse',
    'wake',
    'waken',
    'awaken',
    'quicken',
    'stimulate',
    'inspire',
    'stir up',
    'call forth',
    'bring out',
    'excite',
    'evoke',
    'pique',
    'whet',
    'stir',
    'provoke',
    'spur',
    'fire',
    'inflame',
    'trigger',
    'prompt',
    'induce',
    'encourage',
    'actuate',
    'activate',
    'touch off',
    'set off',
    'incite',
    'promote',
    'engender',
    'generate',
    'enkindle',
    'call/bring into being',
    'draw forth',
    'spark off',
    'set going',
    'rouse',
    'arouse',
    'wake',
    'waken',
    'awaken',
    'quicken',
    'stimulate',
    'inspire',
    'stir up',
    'call forth',
    'bring out',
    'excite',
    'evoke',
    'pique',
    'whet',
    'stir',
    'provoke',
    'spur',
    'fire',
    'inflame',
    'trigger',
    'prompt',
    'induce',
    'encourage',
    'actuate',
    'activate',
    'touch off',
    'set off',
    'incite',
    'promote',
    'engender',
    'generate',
    'enkindle',
    'call/bring into being',
    'draw forth',
    'spark off',
    'set going',
]