export const definitions = [
    '"what chance did I stand against kismet?"',
]
export const synonyms = [
    'fate',
    'destiny',
    'fortune',
    'providence',
    'karma',
    'predestination',
    'predetermination',
    'luck',
    'chance',
    'the stars',
    'God\'s will',
    'what is written in the stars',
    'one\'s doom',
    '\'s \'s portion',
    '\'s \'s lot',
    '\'s \'s lot in life',
    'preordination',
    'what is to come',
    'the writing on the wall',
    'one\'s dole',
    'predestiny',
]