export const definitions = [
  '"the knees finally healed and I returned to tennis and kiting"',
  '"he was caught check kiting"',
  '"while I kited, she would always watch out for me"',
  '"he kited into England on Concorde"',
];
export const synonyms = [
  'run',
  'race',
  'leap',
  'sprint',
  'dash',
  'rush',
  'speed',
  'streak',
  'shoot',
  'whiz',
  'whoosh',
  'buzz',
  'zoom',
  'flash',
  'blast',
  'charge',
  'stampede',
  'chase',
  'career',
  'bustle',
  'hare',
  'fly',
  'wing',
  'dive',
  'jump',
  'skip',
  'scurry',
  'scud',
  'scutter',
  'scramble',
  'hurry',
  'hasten',
  'skite',
];