export const definitions = [
  '"the lava lamp is an example of sixties kitsch"',
  '"the front room is stuffed with kitsch knickknacks, little glass and gilt ornaments"',
  '"she offers kitsch interpretations of classic British dress, including a range of tartan mini-kilts"',
];
export const synonyms = [
  'poor-quality',
  'second-rate',
  'third-rate',
  'substandard',
  'low-grade',
  'inferior',
  'common',
  'vulgar',
  'shoddy',
  'trashy',
  'tawdry',
  'tinny',
  'brassy',
  'worthless',
  'meretricious',
  'cheap and nasty',
  'cheapjack',
  'gimcrack',
  'Brummagem',
  'pinchbeck',
  'trumpery',
  'high-class',
];