export const definitions = [
  '"most people know that CFCs can damage the ozone layer"',
  '"I know what I\'m doing"',
  '"I would write to him if I knew his address"',
  '"I know of one local who shot himself"',
  '"I just knew it was something I wanted to do"',
  '"I knew it!"',
  '"he knew and respected Laura"',
  '"Isabel couldn\'t hear the words clearly but she knew the voice"',
  '"a little restaurant she knew near Times Square"',
  '"a man who had known better times"',
  '"he is also known as an amateur painter"',
  '"the doctor was universally known as \"Hubert.\""',
  '"you are convinced you know your own baby from any other in the world"',
];
export const synonyms = [
  'realize',
  'notice',
  'perceive',
  'see',
  'sense',
  'recognize',
  'understand',
  'appreciate',
  'be aware',
  'be conscious',
  'have knowledge',
  'be informed',
  'have information',
  'have knowledge of',
  'be aware of',
  'be cognizant of',
  'be informed of',
  'be apprised of',
  'be friends with',
  'understand',
  'ken',
  'be acquainted with',
  'have met',
  'be familiar with',
  'be friendly with',
  'be on good terms with',
  'be close to',
  'be intimate with',
  'socialize with',
  'associate with',
  'have dealings with',
  'have insight into',
  'be in sympathy with',
  'empathize with',
  'grasp',
  'understand',
  'comprehend',
  'apprehend',
  'be familiar with',
  'be conversant with',
  'be acquainted with',
  'have knowledge of',
  'be versed in',
  'be knowledgeable about',
  'have mastered',
  'have a grasp of',
  'have learned',
  'have memorized',
  'have learned by heart',
  'experience',
  'go through',
  'undergo',
  'live through',
  'meet',
  'meet with',
  'encounter',
  'taste',
  'have experience of',
  'distinguish',
  'tell apart',
  'differentiate',
  'tell',
  'discriminate',
  'recognize',
  'pick out',
  'identify',
  'make out',
  'discern',
  'see',
  'tell which is which',
];