export const definitions = [
    '"a kosher kitchen"',
    '"she consulted lawyers to make sure everything was kosher"',
]
export const synonyms = [
    'allowable',
    'allowed',
    'permissible',
    'permitted',
    'acceptable',
    'passable',
    'tolerable',
    'satisfactory',
    'justifiable',
    'defensible',
    'supportable',
    'well founded',
    'tenable',
    'sound',
    'sensible',
    'reasonable',
    'legitimate',
    'lawful',
    'legal',
    'licit',
    'above board',
    'valid',
    'recognized',
    'sanctioned',
    'within the law',
    'inadmissible',
    'authentic',
    'real',
    'actual',
    'original',
    'bona fide',
    'true',
    'veritable',
    'unfeigned',
    'unadulterated',
    'unalloyed',
    'sterling',
    'attested',
    'undisputed',
    'rightful',
    'legitimate',
    'lawful',
    'legal',
    'valid',
    'sound',
    'echt',
    'simon-pure',
    'bogus',
]