export const definitions = [
    '"she emerges as something of a kvetch, constantly nagging Rick"',
    '"\"They don\'t make \'em like they used to\" has become an all - purpose kvetch"',
    '"Jane\'s kvetching about her crummy existence"',
]
export const synonyms = [
    'shrew',
    'curmudgeon',
    'discontent',
    'complainer',
    'grumbler',
    'moaner',
    'fault-finder',
    'carper',
    'misery',
    'mope',
    'dog in the manger',
    'damper',
    'dampener',
    'spoilsport',
    'pessimist',
    'crank',
    'jade',
    'melancholiac',
    'prophet of doom',
    'complaint',
    'grumble',
    'moan',
    'groan',
    'grievance',
    'objection',
    'protest',
    'whine',
    'cavil',
    'quibble',
    'niggle',
    'grumble',
    'complain',
    'moan',
    'groan',
    'protest',
    'whine',
    'bleat',
    'carp',
    'cavil',
    'make a fuss',
    'oppose',
    'lament',
    'bewail',
    'twine',
    'crib',
    'natter',
    'lodge a complaint',
    'make a complaint',
    'object to',
    'speak out against',
    'rail at',
    'grieve over',
    'sorrow about',
    'sorrow for',
    'sigh over',
    'mither',
    'plain over',
]