export const definitions = [
    '"persons whose blood pressure is more labile will carry an enhanced risk of heart attack"',
    '"we may be the most labile culture in all history"',
    '"mood seemed generally appropriate, but the patient was often labile"',
    '"the breakage of labile bonds"',
    '"a heat-labile protein"',
]
export const synonyms = [
    'unpredictable',
    'inconsistent',
    'changeable',
    'variable',
    'inconstant',
    'uncertain',
    'irregular',
    'unstable',
    'turbulent',
    'unsteady',
    'unsettled',
    'unreliable',
    'undependable',
    'changing',
    'ever-changing',
    'volatile',
    'varying',
    'shifting',
    'fluctuating',
    'fluid',
    'mutable',
    'protean',
    'fitful',
    'wavering',
    'peaky',
    'mercurial',
    'capricious',
    'whimsical',
    'fickle',
    'flighty',
    'giddy',
    'impulsive',
    'wayward',
    'temperamental',
    'highly strung',
    'excitable',
    'moody',
    'fluctuant',
    'changeful',
    'full of ups and downs',
    'predictable',
    'consistent',
    'evaporative',
    'vaporous',
    'explosive',
    'eruptive',
    'inflammable',
    'unstable',
    'vaporescent',
]