export const definitions = [
    '"they struggled with each other\'s clothing, tearing at the lacing"',
    '"the elaborate lacings of his shirt"',
    '"coffee to which he added a liberal lacing of brandy"',
    '"he put the shoes on and laced them up"',
    '"Rosina laced her up tight to show off her neat waist"',
    '"they laced her into a sky-blue dress, which was so tight she could hardly breathe"',
    '"the shoes laced at the front"',
    '"he laced his fingers together and sat back"',
    '"he laced the twine through the eyelets and pulled it tight"',
    '"he gave us coffee laced with brandy"',
    '"he was left seriously ill after eating a meal allegedly laced with poison"',
    '"the script is laced with expletives"',
    '"her brown hair was laced with gray"',
    '"he laced a double down the first-base line"',
]
export const synonyms = [
    'fasten',
    'do up',
    'tie up',
    'secure',
    'bind',
    'knot',
    'truss',
    'undo',
    'entwine',
    'intertwine',
    'twine',
    'entangle',
    'interweave',
    'interlink',
    'link',
    'crisscross',
    'braid',
    'plait',
    'flavor',
    'mix (in)',
    'blend',
    'fortify',
    'strengthen',
    'stiffen',
    'season',
    'imbue',
    'infuse',
    'enrich',
    'enliven',
    'doctor',
    'adulterate',
    'contaminate',
    'drug',
    'spice (up)',
    'liven up',
]