export const definitions = [
  '"he had lacqueyed and flattered Walpole"',
];
export const synonyms = [
  'servant',
  'flunkey',
  'footman',
  'manservant',
  'valet',
  'steward',
  'butler',
  'equerry',
  'retainer',
  'vassal',
  'page',
  'attendant',
  'houseboy',
  'domestic',
  'drudge',
  'factotum',
  'scullion',
  'liveried servant',
  'toady',
  'flunkey',
  'sycophant',
  'flatterer',
  'minion',
  'doormat',
  'spaniel',
  'stooge',
  'hanger-on',
  'lickspittle',
  'parasite',
  'tool',
  'puppet',
  'instrument',
  'pawn',
  'subordinate',
  'underling',
  'creature',
  'cat\'s paw',
];