export const definitions = [
    '"the journal has filled a lacuna in Middle Eastern studies"',
]
export const synonyms = [
    'gap',
    'space',
    'absence',
    'lack',
    'deficiency',
    'blank',
    'continuity',
    'hollow',
    'indentation',
    'dent',
    'dint',
    'cavity',
    'concavity',
    'dip',
    'pit',
    'hole',
    'pothole',
    'sink',
    'sinkhole',
    'excavation',
    'trough',
    'crater',
    'valley',
    'basin',
    'bowl',
    'fossa',
    'protuberance',
]