export const definitions = [
    '"I spoke to the lady at the travel agency"',
    '"a lady doctor"',
    '"I\'m sorry, lady, but you have the wrong number"',
    '"lords and ladies and royalty were once entertained at the house"',
    '"his wife was a real lady, with such nice manners"',
    '"Lady Caroline Lamb"',
    '"welcoming the vice president and his lady"',
    '"the young man bought a rose for his lady"',
]
export const synonyms = [
    'woman',
    'female',
    'girl',
    'lass',
    'lassie',
    'Frau',
    'Signora',
    'Señora',
    'gentlewoman',
    'maid',
    'damsel',
    'adult female',
    'noblewoman',
    'gentlewoman',
    'duchess',
    'countess',
    'peeress',
    'viscountess',
    'baroness',
    'dame',
    'grand dame',
    'wife',
    'spouse',
    'bride',
    'memsahib',
    'partner',
    'lover',
    'significant other',
    'girl',
    'woman',
    'love',
    'beloved',
    'darling',
    'dearest',
    'sweetheart',
    'cohabitee',
    'fiancée',
    'inamorata',
    'querida',
    'lady friend',
    'lady love',
    'young lady',
    'betrothed',
    'leman',
    'loved one',
    'live-in lover',
    'common-law wife',
]