export const definitions = [
    '"she lapped all of her rivals in the 3,000 meters"',
    '"he lapped two tenths of a second faster than anyone else"',
    '"he was lapped in blankets"',
    '"I was accustomed to being lapped in luxury"',
    '"the water lapped over the edges"',
    '"the honing and lapping of ring gauges"',
    '"the cat was lapping up a saucer of milk"',
    '"she\'s lapping up the attention"',
    '"the waves lapped the shore"',
    '"the sound of the river lapping against the banks"',
]
export const synonyms = [
    'overtake',
    'overhaul',
    'outstrip',
    'outdistance',
    'leave behind',
    'pass',
    'catch up with',
    'go past',
    'get/pull ahead of',
    'wrap',
    'swathe',
    'cover',
    'envelop',
    'enfold',
    'encase',
    'wind',
    'swaddle',
    'twist',
    'surround',
    'drink',
    'sip',
    'sup',
    'swallow',
    'slurp',
    'gulp',
    'swill',
    'suck',
    'lick up',
    'relish',
    'savor',
    'enjoy',
    'revel in',
    'delight in',
    'luxuriate in',
    'bask in',
    'wallow in',
    'glory in',
    'indulge in',
    'splash',
    'wash',
    'swish',
    'slap',
    'slosh',
    'break',
    'purl',
    'beat',
    'strike',
    'dash',
    'surge',
    'rush',
    'ripple',
    'roll',
    'flow',
    'plash',
]