export const definitions = [
  '"the latter half of 1989"',
  '"heart disease dogged his latter years"',
  '"the project had low cash flows in its latter years"',
  '"if we are trying to choose between green and yellow bananas, we often go for the latter option"',
];
export const synonyms = [
  'later',
  'hindmost',
  'closing',
  'end',
  'concluding',
  'final',
  'latest',
  'modern',
  'most recent',
  'last-mentioned',
  'second',
  'last',
  'later',
  'second-mentioned',
  'second of the two',
  'former',
  'prior',
];