export const definitions = [
    '"a lauded author"',
    '"her much-lauded rendering of Lady Macbeth"',
    '"the obituary lauded him as a great statesman and soldier"',
]
export const synonyms = [
    'praise',
    'extol',
    'hail',
    'applaud',
    'acclaim',
    'commend',
    'admire',
    'make much of',
    'sing the praises of',
    'lionize',
    'eulogize',
    'cheer',
    'celebrate',
    'welcome',
    'salute',
    'glorify',
    'exalt',
    'honor',
    'adore',
    'revere',
    'venerate',
    'idolize',
    'magnify',
    'panegyrize',
    'approve of',
    'speak highly of',
    'pay tribute/homage to',
    'sing paeans to',
    'rhapsodize over/about',
    'cry someone/something up',
    'condemn',
    'criticize',
]