export const definitions = [
  '"the bust depicts the president wearing Roman laurels, armor, and a cloak"',
  '"Mansell became only the seventh Briton to wear the champion\'s laurels"',
  '"she has rightly won laurels for this brilliantly perceptive first novel"',
  '"she will be laureled alongside politicians, historians, and other actors"',
];
export const synonyms = [
  'prize',
  'trophy',
  'award',
  'crown',
  'wreath',
  'laurels',
  'bays',
  'honor',
  'glory',
  'fame',
  'victory',
  'triumph',
  'success',
  'accolade',
  'laurel wreath',
  'honors',
  'awards',
  'trophies',
  'prizes',
  'rewards',
  'tributes',
  'praise',
  'plaudits',
  'accolades',
  'decorations',
  'titles',
  'kudos',
  'acclaim',
  'acclamation',
  'commendation',
  'credit',
  'glory',
  'honor',
  'distinction',
  'fame',
  'renown',
  'prestige',
  'recognition',
  'laudation',
];