export const definitions = [
  '"a lavish banquet"',
  '"he was lavish with his hospitality"',
  '"lavish praise"',
  '"the media couldn\'t lavish enough praise on the film"',
  '"she lavished our son with kisses"',
];
export const synonyms = [
  'sumptuous',
  'luxurious',
  'luxuriant',
  'lush',
  'gorgeous',
  'costly',
  'opulent',
  'grand',
  'elaborate',
  'splendid',
  'rich',
  'regal',
  'ornate',
  'expensive',
  'pretentious',
  'showy',
  'fancy',
  'meager',
  'generous',
  'liberal',
  'bountiful',
  'openhanded',
  'unstinting',
  'unsparing',
  'ungrudging',
  'free',
  'munificent',
  'handsome',
  'extravagant',
  'prodigal',
  'fulsome',
  'frugal',
  'abundant',
  'copious',
  'ample',
  'superabundant',
  'plentiful',
  'profuse',
  'liberal',
  'prolific',
  'generous',
  'plenteous',
  'scant',
  'spend',
  'expend',
  'heap',
  'shower',
  'pour',
  'deluge',
  'give freely',
  'give generously',
  'give unstintingly',
  'bestow freely',
  'economize',
  'begrudge',
];