export const definitions = [
    '"it is an offense to carry a weapon in public without lawful authority"',
]
export const synonyms = [
    'legitimate',
    'legal',
    'licit',
    'just',
    'permissible',
    'permitted',
    'allowable',
    'allowed',
    'rightful',
    'proper',
    'constitutional',
    'legalized',
    'sanctioned',
    'authorized',
    'warranted',
    'justified',
    'justifiable',
    'approved',
    'recognized',
    'admissible',
    'above board',
    'law-abiding',
    'righteous',
    'honorable',
    'good',
    'decent',
    'solid',
    'virtuous',
    'moral',
    'ethical',
    'orderly',
    'well behaved',
    'peacekeeping',
    'peaceful',
    'civilized',
    'dutiful',
    'duteous',
    'obedient',
    'compliant',
    'complying',
    'disciplined',
    'within the law',
    'going by the rules',
    'illegal',
    'prohibited',
    'lawless',
    'criminal',
]