export const definitions = [
    '"the League of Nations"',
    '"the leading goalscorer in the league"',
    '"the league championship"',
    '"the year we won the league"',
    '"the two men were not in the same league"',
    '"Jack\'s in a league of his own"',
    '"Oscar had leagued with other construction firms"',
]
export const synonyms = [
    'alliance',
    'confederation',
    'confederacy',
    'federation',
    'union',
    'association',
    'coalition',
    'combine',
    'consortium',
    'affiliation',
    'guild',
    'corporation',
    'conglomerate',
    'cooperative',
    'partnership',
    'fellowship',
    'syndicate',
    'compact',
    'band',
    'group',
    'circle',
    'ring',
    'bloc',
    'faction',
    'axis',
    'congress',
    'entente',
    'brotherhood',
    'society',
    'fraternity',
    'coterie',
    'lodge',
    'consociation',
    'sodality',
    'championship',
    'competition',
    'contest',
    'group',
    'band',
    'association',
    'class',
    'group',
    'category',
    'level',
    'ability group',
    'level of ability',
    'ally',
    'join forces',
    'unite',
    'affiliate',
    'combine',
    'amalgamate',
    'confederate',
    'collaborate',
    'join together',
    'form an association',
    'band together',
    'form a federation',
    'team up',
    'join up',
]