export const definitions = [
  '"his lean, muscular body"',
  '"lean bacon"',
  '"he made leaner government a campaign theme"',
  '"the lean winter months"',
  '"keep a small reserve to tide you over the lean years"',
  '"lean air-to-fuel ratios"',
  '"the man who eats no fat and the wife who eats no lean"',
];
export const synonyms = [
  'slim',
  'thin',
  'slender',
  'rangy',
  'spare',
  'wiry',
  'slight',
  'lissom',
  'svelte',
  'willowy',
  'sylphlike',
  'skinny',
  'scrawny',
  'scraggly',
  'lanky',
  'lank',
  'bony',
  'gaunt',
  'emaciated',
  'rawboned',
  'gangling',
  'spindly',
  'skeletal',
  'size-zero',
  'angular',
  'pinched',
  'skin and bones',
  'fat',
  'nonfatty',
  'unfatty',
  'fatty',
  'meager',
  'scanty',
  'sparse',
  'poor',
  'scant',
  'mean',
  'inadequate',
  'insufficient',
  'paltry',
  'limited',
  'restricted',
  'modest',
  'deficient',
  'insubstantial',
  'slight',
  'unproductive',
  'unfruitful',
  'unprofitable',
  'unremunerative',
  'arid',
  'barren',
  'hard',
  'bad',
  'difficult',
  'tough',
  'impoverished',
  'poverty-stricken',
  'moneyless',
  'abundant',
  'plentiful',
  'productive',
  'prosperous',
];