export const definitions = [
    '"the legend of King Arthur"',
    '"according to legend he banished all the snakes from Ireland"',
    '"the mosaics illustrate the Legends of the Saints"',
    '"the man was a living legend"',
    '"a Wall Street legend"',
    '"a picture of a tiger with the legend, \"Go ahead, make my day.\""',
    '"see legend under Fig. 1"',
    '"his speed and ferocity in attack were legend"',
]
export const synonyms = [
    'myth',
    'saga',
    'epic',
    'folk tale',
    'tale',
    'story',
    'fairy tale',
    'narrative',
    'fable',
    'romance',
    'folklore',
    'lore',
    'mythology',
    'fantasy',
    'oral history',
    'tradition',
    'old wives\' tales',
    'mythos',
    'folk story',
    'traditional story',
    'folk tradition',
    'mythus',
    'celebrity',
    'star',
    'superstar',
    'icon',
    'great',
    'genius',
    'phenomenon',
    'luminary',
    'giant',
    'big name',
    'famous person',
    'caption',
    'inscription',
    'dedication',
    'motto',
    'slogan',
    'device',
    'heading',
    'head',
    'title',
    'wording',
    'subtitle',
    'subheading',
    'rubric',
    'colophon',
    'caption',
    'inscription',
    'label',
    'heading',
    'subheading',
    'head',
    'motto',
    'slogan',
    'device',
    'wording',
    'rubric',
    'credit',
    'explanation',
    'key',
    'code',
    'cipher',
    'guide',
    'glossary',
    'table of symbols',
]