export const definitions = [
    '"it can reach over two feet in length"',
    '"the length of the airport terminal"',
    '"the length of the waiting list"',
    '"fifty lengths of the pool"',
    '"the mare won the race last year by seven lengths"',
    '"the length of her skirt"',
    '"the muscles running the length of my spine"',
    '"he awkwardly lowered his length into the small car"',
    '"the length of the syllable is isomorphic with the length of the syllabic vowel"',
    '"delivery must be within a reasonable length of time"',
    '"a stout length of wood"',
    '"they go to great lengths to avoid the press"',
    '"knee-length"',
    '"full-length"',
    '"feature-length"',
    '"medium-length"',
]
export const synonyms = [
    'extent',
    'distance',
    'span',
    'reach',
    'area',
    'expanse',
    'stretch',
    'range',
    'scope',
    'extent lengthwise',
    'distance lengthwise',
    'linear measure',
    'period',
    'duration',
    'stretch',
    'term',
    'span',
    'period',
    'duration',
    'stretch',
    'term',
    'span',
    'piece',
    'swatch',
    'portion',
    'section',
    'measure',
    'segment',
    'roll',
    'do absolutely anything',
    'go to any extreme',
    'go to any limits',
    'observe no limits',
]