export const definitions = [
]
export const synonyms = [
    'wound',
    'injury',
    'bruise',
    'abrasion',
    'contusion',
    'scratch',
    'scrape',
    'cut',
    'gash',
    'laceration',
    'tear',
    'puncture',
    'ulcer',
    'ulceration',
    'sore',
    'abscess',
    'carbuncle',
    'canker',
    'mark',
    'trauma',
    'running sore',
]