export const definitions = [
    '"avoiding loss of time"',
    '"funding cuts will lead to job losses"',
    '"insurance can protect you against financial loss"',
    '"we have incurred huge losses"',
    '"loss-making industries"',
    '"I feel a terrible sense of loss"',
    '"he will be a great loss to many people"',
]
export const synonyms = [
    'mislaying',
    'misplacement',
    'dropping',
    'forgetting',
    'overlooking',
    'deprivation',
    'disappearance',
    'losing',
    'privation',
    'forfeiture',
    'waste',
    'squandering',
    'dissipation',
    'diminution',
    'erosion',
    'reduction',
    'impoverishment',
    'depletion',
    'recovery',
    'finding',
    'injury',
    'hurt',
    'pain',
    'suffering',
    'distress',
    'anguish',
    'trauma',
    'torment',
    'grief',
    'damage',
    'impairment',
    'destruction',
    'ruin',
    'defacement',
    'defilement',
    'mischief',
    'benefit',
]