export const definitions = [
    '"the front garden is on a level with this floor"',
    '"storms caused river levels to rise"',
    '"a high level of unemployment"',
    '"debt rose to unprecedented levels"',
    '"at six he could play chess at an advanced level"',
    '"a fairly junior level of management"',
    '"I\'ve now reached level 106 on Candy Crush Saga"',
    '"you can easily take a character to level 20 in less than 15 hours and finish the campaign"',
    '"flooded levels"',
    '"contractors started leveling the ground for the new power station"',
    '"bulldozers are now waiting to level their home"',
    '"Woods sliced the ball into the net to level the score"',
    '"he leveled a long-barreled pistol at us"',
    '"accusations of corruption had been leveled against him"',
]
export const synonyms = [
    'height',
    'highness',
    'altitude',
    'elevation',
    'distance upward',
    'floor',
    'story',
    'tier',
    'deck',
    'quantity',
    'amount',
    'extent',
    'measure',
    'degree',
    'volume',
    'size',
    'magnitude',
    'intensity',
    'pitch',
    'strength',
    'proportion',
    'rank',
    'standing',
    'status',
    'position',
    'echelon',
    'station',
    'degree',
    'grade',
    'gradation',
    'stage',
    'standard',
    'rung',
    'point',
    'mark',
    'step',
    'class',
    'stratum',
    'group',
    'grouping',
    'set',
    'classification',
    'level of achievement',
    'degree of competence',
    'level off',
    'flatten',
    'smooth',
    'plane',
    'regularize',
    'polish',
    'face',
    'make level',
    'level out',
    'make even',
    'even off',
    'even out',
    'make flat',
    'smooth out',
    'make uniform',
    'make regular',
    'raze',
    'demolish',
    'flatten',
    'gut',
    'topple',
    'destroy',
    'wipe out',
    'blow up',
    'bomb',
    'tear down',
    'knock down',
    'pull down',
    'bring down',
    'bulldoze',
    'fell',
    'dismantle',
    'break up',
    'wreck',
    'pulverize',
    'obliterate',
    'raze to the ground',
    'lay waste',
    'blow to bits',
    'raise',
    'build',
    'equal',
    'even',
    'equalize',
    'make equal',
    'even up',
    'make level',
    'aim',
    'point',
    'direct',
    'train',
    'sight',
    'focus',
    'turn',
    'beam',
    'take aim',
    'zero in on',
    'draw a bead on',
]