export const definitions = [
  '"a new tax could be levied on industry to pay for cleaning up contaminated land"',
  '"there will be powers to levy the owner"',
  '"there were no goods to levy upon"',
  '"he sought to levy one man from each parish for service"',
  '"they then proceeded without further ceremony to levy war upon the king"',
];
export const synonyms = [
  'impose',
  'charge',
  'exact',
  'demand',
  'raise',
  'collect',
  'gather',
  'tax',
  'mulct',
  'impose',
  'charge',
  'exact',
  'demand',
  'raise',
  'collect',
  'gather',
  'tax',
  'mulct',
  'conscript',
  'call up',
  'enlist',
  'mobilize',
  'rally',
  'muster',
  'marshal',
  'press',
  'recruit',
  'raise',
  'assemble',
  'round up',
  'draft',
  'demobilize',
  'disband',
];