export const definitions = [
    '"as an attempt to introduce a note of levity, the words were a disastrous flop"',
]
export const synonyms = [
    'light-heartedness',
    'carefreeness',
    'high spirits',
    'vivacity',
    'liveliness',
    'conviviality',
    'cheerfulness',
    'cheeriness',
    'humor',
    'gaiety',
    'fun',
    'jocularity',
    'hilarity',
    'frivolity',
    'frivolousness',
    'amusement',
    'mirth',
    'laughter',
    'merriment',
    'glee',
    'comedy',
    'funniness',
    'wit',
    'wittiness',
    'jollity',
    'joviality',
    'joking',
    'drollery',
    'good cheer',
    'sportiveness',
    'nonsense',
    'irreverence',
    'facetiousness',
    'flippancy',
    'blitheness',
    'triviality',
    'silliness',
    'foolishness',
    'childishness',
    'giddiness',
    'skittishness',
    'light-mindedness',
    'seriousness',
    'gravity',
]