export const definitions = [
  '"they likened the reigning emperor to a god"',
];
export const synonyms = [
  'compare',
  'equate',
  'analogize',
  'parallel',
  'correlate',
  'match',
  'link',
  'associate',
  'show the resemblance/similarity between',
  'draw an analogy between',
  'make an analogy of/between',
  'draw a parallel between',
  'make connections between',
  'bracket together',
  'think of together',
  'regard as similar',
  'set beside',
  'mention in the same breath',
  'set side by side',
  'contrast',
];