export const definitions = [
  '"they were like brothers"',
  '"she looked nothing like Audrey Hepburn"',
  '"there were other suits like mine in the shop"',
  '"he was screaming like a banshee"',
  '"you must run like the wind"',
  '"students were angry at being treated like children"',
  '"just like you to put a damper on people\'s enjoyment"',
  '"what is it like to be a tuna fisherman?"',
  '"what\'s she like ? "',
  '"I apologize for coming over unannounced like this"',
  '"why are you talking about me like that?"',
  '"the cautionary vision of works like Animal Farm and 1984"',
  '"people who change countries like they change clothes"',
  '"I felt like I\'d been kicked by a camel"',
  '"the quotations could be arranged to put like with like"',
  '"I know him—him and his like"',
  '"did you ever hear the like?"',
  '"a church interior the like of which he had never seen before"',
  '"I responded in like manner"',
  '"the grouping of children of like ability together"',
  '"\"Who painted the dog\'s picture ? It\'s very like.\""',
  '"I was, like, so hyped up I couldn\'t go to sleep"',
  '"so she comes into the room and she\'s like \"Where is everybody ?\""',
  '"like as a ship with dreadful storm long tossed"',
  '"people who don\'t like reading books"',
  '"I like to be the center of attention"',
  '"I like all Angela Carter\'s stories"',
  '"more than 15,000 Facebook users had liked his page by Monday morning"',
  '"would you like a cup of coffee?"',
  '"I\'d like to rent a car"',
  '"I\'d like you to stay"',
  '"we would like for you to work for us"',
  '"we would like to apologize for the late running of this service"',
  '"I don\'t like leaving her on her own too long"',
  '"how do you like your coffee?"',
  '"how would you like it if it happened to you?"',
  '"a wide variety of likes, dislikes, tastes, and income levels"',
  '"pages that rank well are likely to receive high numbers of likes because they are highly visible in the search engines"',
  '"bell-like"',
  '"grasslike"',
];
export const synonyms = [
  'similar to',
  'the same as',
  'identical to',
  'unlike',
  'as',
  'in the same way as',
  'in the manner of',
  'in the same manner as',
  'in the same way that',
  'in a similar way to',
  'after the fashion of',
  'along/on the lines of',
  'tantamount to',
  'unlike',
  'characteristic of',
  'typical of',
  'in character with',
  'unlike',
  'characteristic of',
  'typical of',
  'in character with',
  'unlike',
  'such as',
  'for example',
  'for instance',
  'in particular',
  'as',
  'namely',
  'viz.',
  'except for',
  'equal',
  'match',
  'equivalent',
  'counterpart',
  'opposite number',
  'fellow',
  'twin',
  'mate',
  'parallel',
  'peer',
  'compeer',
  'inferior',
  'superior',
  'similar',
  'comparable',
  'corresponding',
  'correspondent',
  'resembling',
  'alike',
  'approximating',
  'analogous',
  'parallel',
  'equivalent',
  'cognate',
  'related',
  'of a kind',
  'akin',
  'kindred',
  'interchangeable',
  'indistinguishable',
  'identical',
  'same',
  'matching',
  'much the same',
  'more or less the same',
  'not unlike',
  'different',
  'dissimilar',
  'have a soft spot for',
  'admire',
  'respect',
  'esteem',
  'fancy',
  'enjoy',
  'take to',
  'appreciate',
  'love',
  'adore',
  'relish',
  'savor',
  'be fond of',
  'be attached to',
  'have a fondness for',
  'have a liking for',
  'have regard for',
  'think well of',
  'look on with favor',
  'hold in esteem',
  'be attracted to',
  'find attractive',
  'be keen on',
  'be taken with',
  'have a taste for',
  'have a preference for',
  'have a weakness for',
  'be partial to',
  'delight in',
  'find/take pleasure in',
  'find agreeable',
  'derive pleasure from',
  'be pleased by',
  'have a penchant for',
  'have a passion for',
  'derive satisfaction from',
  'find enjoyable',
  'lap up',
  'revel in',
  'dislike',
  'hate',
  'enjoy',
  'take to',
  'appreciate',
  'love',
  'adore',
  'relish',
  'savor',
  'have a taste for',
  'have a preference for',
  'have a liking for',
  'have a weakness for',
  'be partial to',
  'delight in',
  'find/take pleasure in',
  'be keen on',
  'find agreeable',
  'derive pleasure from',
  'be pleased by',
  'have a penchant for',
  'have a passion for',
  'derive satisfaction from',
  'find enjoyable',
  'lap up',
  'revel in',
  'dislike',
  'hate',
  'regard',
  'think about',
  'consider',
  'feel about',
];