export const definitions = [
    '"the fate of the Contras is now in limbo"',
    '"children left in an emotional limbo"',
    '"the children limboed under the bar"',
]
export const synonyms = [
    'oblivion',
    'void',
    'nonexistence',
    'neither heaven nor hell',
    'unfinished',
    'incomplete',
    'suspended',
    'deferred',
    'postponed',
    'put off',
    'pending',
    'on ice',
    'unresolved',
    'undetermined',
    'up in the air',
    'betwixt and between',
    'ongoing',
    'outstanding',
    'abandoned',
    'forgotten',
    'neglected',
    'in abeyance',
    'unattended to',
    'in a state of suspension',
    'awaiting action',
    'in cold storage',
    'in a state of uncertainty',
    'in no man\'s land',
    'hanging fire',
    'left out',
    'in hand',
    'under way',
    'continuing',
    'unfinished',
    'incomplete',
    'suspended',
    'deferred',
    'postponed',
    'put off',
    'pending',
    'on ice',
    'unresolved',
    'undetermined',
    'up in the air',
    'betwixt and between',
    'ongoing',
    'outstanding',
    'abandoned',
    'forgotten',
    'neglected',
    'in abeyance',
    'unattended to',
    'in a state of suspension',
    'awaiting action',
    'in cold storage',
    'in a state of uncertainty',
    'in no man\'s land',
    'hanging fire',
    'left out',
    'in hand',
    'under way',
    'continuing',
]