export const definitions = [
    '"she lingered in the yard, enjoying the warm sunshine"',
    '"she let her eyes linger on him suggestively"',
    '"she lingered over her meal"',
    '"the tradition seems to linger on"',
    '"we are thankful that she didn\'t linger on and suffer"',
]
export const synonyms = [
    'stay',
    'remain',
    'stay put',
    'wait',
    'loiter',
    'dawdle',
    'dally',
    'take one\'s time',
    'straggle',
    'dither',
    'pause',
    'procrastinate',
    'stall',
    'delay',
    'tarry',
    'wait around',
    'lag behind',
    'putter around',
    'leave',
    'persist',
    'continue',
    'remain',
    'stay',
    'endure',
    'carry on',
    'last',
    'hold',
    'survive',
    'abide',
    'be protracted',
    'keep on/up',
    'vanish',
    'disappear',
]