export const definitions = [
    '"plans of a link-up between the two tour operators have been announced"',
    '"a live satellite linkup"',
]
export const synonyms = [
    'join forces',
    'amalgamate',
    'consolidate',
    'integrate',
    'unite',
    'unify',
    'combine',
    'incorporate',
    'affiliate',
    'coalesce',
    'meld',
    'agglutinate',
    'link (up)',
    'ally',
    'league',
    'federate',
    'join',
    'conflate',
    'pool',
    'knit',
    'yoke',
    'join (together)',
    'team up',
    'band (together)',
    'bring together',
    'separate',
    'split',
    'amalgamation',
    'combination',
    'merging',
    'union',
    'fusion',
    'coalition',
    'affiliation',
    'coupling',
    'unification',
    'incorporation',
    'coalescence',
    'consolidation',
    'confederation',
    'hookup',
    'alliance',
    'association',
    'connection',
    'split',
    'breakup',
]