export const definitions = [
    '"evidently he was not listening"',
    '"if I\'ve had a stressful day I love to chill out and listen to music"',
    '"I told her over and over again, but she wouldn\'t listen"',
    '"they listened for sounds from the baby\'s room"',
    '"listen, I\'ve got an idea"',
    '"radio plays are definitely worth a listen"',
]
export const synonyms = [
    'hear',
    'attend',
    'prick up one\'s ears',
    'hark',
    'hearken',
    'pay attention',
    'be attentive',
    'concentrate on',
    'concentrate on hearing',
    'give ear to',
    'lend an ear to',
    'hang on someone\'s words',
    'keep \'s \'s ears open',
    'heed',
    'take notice',
    'take note',
    'mind',
    'observe',
    'watch',
    'follow',
    'notice',
    'mark',
    'take into consideration',
    'hang on',
    'accept',
    'believe',
    'obey',
    'pay attention',
    'take heed',
    'give heed',
    'bear in mind',
    'give a thought to',
    'take into account',
    'take to heart',
    'do as one is told by',
    'ignore',
    'be deaf to',
    'hear',
    'attend',
    'prick up one\'s ears',
    'hark',
    'hearken',
    'pay attention',
    'be attentive',
    'concentrate on',
    'concentrate on hearing',
    'give ear to',
    'lend an ear to',
    'hang on someone\'s words',
    'keep \'s \'s ears open',
]