export const definitions = [
    '"she joined a lively team of reporters"',
    '"Barcelona\'s many lively bars"',
    '"a lively discussion"',
    '"her lively mind"',
]
export const synonyms = [
    'energetic',
    'active',
    'animated',
    'vigorous',
    'dynamic',
    'outgoing',
    'spirited',
    'high-spirited',
    'vivacious',
    'enthusiastic',
    'vibrant',
    'buoyant',
    'exuberant',
    'effervescent',
    'cheerful',
    'bouncy',
    'bubbly',
    'perky',
    'sparkling',
    'sprightly',
    'spry',
    'youthful',
    'zesty',
    'zestful',
    'frisky',
    'skittish',
    'fun',
    'fun-loving',
    'full of life',
    'listless',
    'lifeless',
    'apathetic',
    'busy',
    'crowded',
    'bustling',
    'hectic',
    'swarming',
    'teeming',
    'astir',
    'buzzing',
    'thronging',
    'vibrant',
    'boisterous',
    'jolly',
    'festive',
    'quiet',
    'dead',
    'heated',
    'vigorous',
    'stimulating',
    'animated',
    'spirited',
    'enthusiastic',
    'forceful',
    'exciting',
    'stirring',
    'interesting',
    'eventful',
    'memorable',
    'lifeless',
    'dull',
]