export const definitions = [
  '"she saw Mary loitering near the cloakrooms"',
  '"they loitered along in the sunshine, stopping at the least excuse"',
];
export const synonyms = [
  'linger',
  'putter',
  'wait',
  'skulk',
  'loaf',
  'lounge',
  'idle',
  'laze',
  'tarry',
  'waste time',
  'kill time',
  'while away time',
  'dawdle',
  'dally',
  'stroll',
  'saunter',
  'loll',
  'take one\'s time',
  'drag \'s \'s feet',
  'delay',
  'go slowly',
  'go/move at a snail\'s pace',
];