export const definitions = [
    '"lordly titles"',
    '"they were putting on lordly airs"',
]
export const synonyms = [
    'noble',
    'aristocratic',
    'princely',
    'kingly',
    'regal',
    'royal',
    'imperial',
    'courtly',
    'stately',
    'magnificent',
    'majestic',
    'grand',
    'august',
    'lofty',
    'exalted',
    'dignified',
    'imposing',
    'impressive',
    'lowly',
]