export const definitions = [
    '"the child was lured into a car but managed to escape"',
]
export const synonyms = [
    'tempt',
    'entice',
    'attract',
    'induce',
    'coax',
    'persuade',
    'inveigle',
    'allure',
    'seduce',
    'cajole',
    'beguile',
    'bewitch',
    'ensnare',
    'captivate',
    'enrapture',
    'decoy',
    'draw',
    'lead (on)',
    'win over',
    'whet someone\'s appetite',
    'deter',
    'put off',
]