export const definitions = [
    '"the luster of the Milky Way"',
    '"she couldn\'t eat and her hair lost its luster"',
    '"a celebrity player to add luster to the lineup"',
    '"luster jugs"',
    '"luster yarn"',
    '"a chandelier dripping with glass lusters"',
]
export const synonyms = [
    'sheen',
    'gloss',
    'glossiness',
    'shine',
    'brightness',
    'radiance',
    'burnish',
    'polish',
    'patina',
    'glow',
    'gleam',
    'glimmer',
    'shimmer',
    'brilliance',
    'sparkle',
    'dazzle',
    'flash',
    'glitter',
    'glint',
    'luminousness',
    'luminosity',
    'luminescence',
    'light',
    'effulgence',
    'refulgence',
    'lambency',
    'coruscation',
    'dullness',
    'darkness',
    'honor',
    'glory',
    'illustriousness',
    'credit',
    'merit',
    'prestige',
    'éclat',
    'distinction',
    'eminence',
    'preeminence',
    'notability',
    'consequence',
    'renown',
    'fame',
    'dishonor',
    'glaze',
    'lacquer',
    'shellac',
    'varnish',
    'enamel',
    'patina',
    'coat',
    'coating',
    'covering',
    'finish',
]