export const definitions = [
  '"he lived a life of luxury"',
  '"luxuries like raspberry vinegar and state-of-the-art CD players"',
  '"he considers bananas a luxury"',
  '"a luxury yacht"',
  '"luxury goods"',
];
export const synonyms = [
  'opulence',
  'luxuriousness',
  'sumptuousness',
  'richness',
  'costliness',
  'grandeur',
  'grandness',
  'splendor',
  'magnificence',
  'lavishness',
  'milk and honey',
  'comfort',
  'security',
  'affluence',
  'wealth',
  'prosperity',
  'prosperousness',
  'plenty',
  'lap of luxury',
  'bed of roses',
  'austerity',
  'poverty',
  'indulgence',
  'extravagance',
  'self-indulgence',
  'treat',
  'extra',
  'nonessential',
  'frill',
  'refinement',
  'necessity',
  'smart',
  'stylish',
  'upmarket',
  'fancy',
  'high-class',
  'fashionable',
  'chic',
  'luxurious',
  'deluxe',
  'exclusive',
  'select',
  'sumptuous',
  'opulent',
  'lavish',
  'grand',
  'rich',
  'elegant',
  'ornate',
  'ostentatious',
  'showy',
  'high-toned',
  'upscale',
  'swell',
  'sprauncy',
];