export const definitions = [
    '"the jagged edges gashed their fingers"',
    '"soothing her jagged nerves"',
    '"she jagged herself in the mouth"',
]
export const synonyms = [
    'spiky',
    'spiked',
    'barbed',
    'snaggy',
    'nicked',
    'pointed',
    'ragged',
    'craggy',
    'rough',
    'uneven',
    'irregular',
    'broken',
    'serrated',
    'sawtooth',
    'toothed',
    'notched',
    'indented',
    'denticulate',
    'saw-edged',
    'smooth',
]