export const definitions = [
    '"she came downstairs, her face still white under her heavy makeup"',
    '"stage makeup"',
    '"chief makeup artist"',
    '"studying the makeup of ocean sediments"',
    '"a nastiness that had long been in his makeup"',
    '"page makeup"',
    '"Tony has a makeup exam"',
]
export const synonyms = [
    'cosmetics',
    'greasepaint',
    'foundation',
    'pancake',
    'powder',
    'blusher',
    'rouge',
    'concealer',
    'mascara',
    'eyeliner',
    'eyeshadow',
    'eyebrow pencil',
    'kohl',
    'lipstick',
    'lip gloss',
    'maquillage',
    'panstick',
    'loose powder',
    'pressed powder',
    'eye makeup',
    'lip pencil',
    'nail varnish/polish',
    'composition',
    'constitution',
    'configuration',
    'form',
    'arrangement',
    'format',
    'structure',
    'construction',
    'formation',
    'assembly',
    'organization',
    'fabric',
    'framework',
    'character',
    'nature',
    'temperament',
    'temper',
    'personality',
    'disposition',
    'constitution',
    'mentality',
    'persona',
    'psyche',
    'psychology',
    'make',
    'stamp',
    'mold',
    'humor',
    'grain',
    'cast/turn of mind',
    'design',
    'style',
    'presentation',
    'appearance',
    'look',
    'form',
    'shape',
    'size',
    'arrangement',
    'plan',
    'scheme',
    'composition',
    'configuration',
    'structure',
    'setup',
]