export const definitions = [
    '"the making of videos"',
    '"glassmaking"',
    '"a film with all the makings of a cinematic success"',
    '"he reached for his tobacco tin and makings"',
    '"my grandmother made a dress for me"',
    '"the body is made from four pieces of maple"',
    '"baseball bats are made of ash"',
    '"buffalo\'s milk can be made into cheese"',
    '"she made her will"',
    '"she was making lunch for Lucy and Francis"',
    '"I\'ll make us both a cup of tea"',
    '"after breakfast you\'d have until 8: 25 to make your bed"',
    '"the drips had made a pool on the floor"',
    '"decorative features make brickwork more interesting"',
    '"the best way to disarm your critics is to make them laugh"',
    '"anyone can make a mistake"',
    '"Unger made a speech of forty minutes"',
    '"we made a deal"',
    '"make him an offer he can\'t refuse"',
    '"I tend to make heavy demands on people"',
    '"a marriage made in heaven"',
    '"he was made a colonel in the Mexican army"',
    '"the sale price and extended warranty make it an excellent value"',
    '"the work which really made Wordsworth\'s reputation"',
    '"she bought me a brandy and made me drink it"',
    '"they made an unusual duo"',
    '"this fern makes a good houseplant"',
    '"How many are there? I make it sixteen"',
    '"let\'s make it 7: 30"',
    '"he\'d made a lot of money out of hardware"',
    '"we\'ve got a lot to do if you\'re going to make the shuttle"',
    '"they didn\'t always make it on time"',
    '"he waited confidently for his band to make it"',
    '"these dogs seldom make the news"',
    '"they made it to the semifinals"',
    '"he wasn\'t going to make captain"',
    '"he struggled to his feet and made toward the car"',
    '"she made as if to leave the room"',
    '"he had been trying to make Cynthia for two years now"',
    '"his alleged quest to make it with the world\'s most attractive women"',
]
export const synonyms = [
    'manufacture',
    'manufacturing',
    'mass production',
    'building',
    'construction',
    'assembly',
    'production',
    'producing',
    'creation',
    'creating',
    'modeling',
    'fabrication',
    'invention',
    'forming',
    'formation',
    'molding',
    'forging',
    'composition',
    'putting together',
    'destruction',
    'qualities',
    'characteristics',
    'ingredients',
    'potential',
    'promise',
    'capacity',
    'capability',
    'essentials',
    'essence',
    'beginnings',
    'rudiments',
    'basics',
    'materials',
    'stuff',
    'construct',
    'build',
    'assemble',
    'put together',
    'manufacture',
    'produce',
    'fabricate',
    'create',
    'form',
    'fashion',
    'model',
    'mold',
    'shape',
    'forge',
    'bring into existence',
    'destroy',
    'formulate',
    'draw up',
    'write',
    'frame',
    'draft',
    'form',
    'enact',
    'pass',
    'lay down',
    'establish',
    'institute',
    'found',
    'originate',
    'repeal',
    'formulate',
    'frame',
    'draw up',
    'devise',
    'make out',
    'prepare',
    'compile',
    'compose',
    'put together',
    'draft',
    'write',
    'pen',
    'produce',
    'form',
    'enact',
    'pass',
    'lay down',
    'establish',
    'institute',
    'found',
    'originate',
    'repeal',
    'prepare',
    'put together',
    'concoct',
    'cook',
    'dish up',
    'throw together',
    'whip up',
    'brew',
    'mast',
    'get ready',
    'cause',
    'create',
    'give rise to',
    'produce',
    'bring about',
    'generate',
    'engender',
    'occasion',
    'effect',
    'set up',
    'establish',
    'institute',
    'found',
    'develop',
    'originate',
    'frame',
    'beget',
    'cause',
    'create',
    'give rise to',
    'produce',
    'bring about',
    'generate',
    'engender',
    'occasion',
    'effect',
    'set up',
    'establish',
    'institute',
    'found',
    'develop',
    'originate',
    'frame',
    'beget',
    'perform',
    'execute',
    'give',
    'do',
    'accomplish',
    'achieve',
    'bring off',
    'carry out',
    'practice',
    'commit',
    'act',
    'prosecute',
    'perpetrate',
    'blunder',
    'err',
    'nod',
    'miscalculate',
    'utter',
    'deliver',
    'give voice to',
    'enunciate',
    'recite',
    'pronounce',
    'engage in',
    'be responsible for',
    'be guilty of',
    'be to blame for',
    'trip up',
    'put a foot wrong',
    'utter',
    'give',
    'deliver',
    'give voice to',
    'enunciate',
    'recite',
    'pronounce',
    'appoint',
    'designate',
    'name',
    'nominate',
    'select',
    'elect',
    'install',
    'place',
    'post',
    'induct',
    'institute',
    'invest',
    'ordain',
    'assign',
    'detail',
    'draft',
    'engage',
    'hire',
    'employ',
    'recruit',
    'retain',
    'enroll',
    'enlist',
    'sign up',
    'vote in',
    'cast as',
    'be',
    'act as',
    'constitute',
    'represent',
    'embody',
    'form',
    'serve as',
    'function as',
    'perform the function of',
    'do duty for',
    'play the part of',
    'force',
    'compel',
    'coerce',
    'press',
    'drive',
    'pressure',
    'pressurize',
    'oblige',
    'require',
    'dragoon',
    'bludgeon',
    'strong-arm',
    'impel',
    'constrain',
    'urge',
    'will',
    'steamroller',
    'browbeat',
    'intimidate',
    'bully',
    'hector',
    'blackmail',
    'have someone do something',
    'prevail on',
    'use strong-arm tactics on',
    'be',
    'act as',
    'constitute',
    'represent',
    'embody',
    'form',
    'serve as',
    'function as',
    'perform the function of',
    'do duty for',
    'play the part of',
    'be',
    'act as',
    'constitute',
    'represent',
    'embody',
    'form',
    'serve as',
    'function as',
    'perform the function of',
    'do duty for',
    'play the part of',
    'compute',
    'calculate',
    'work out',
    'estimate',
    'determine',
    'gauge',
    'reckon',
    'put a figure on',
    'forecast',
    'predict',
    'count up',
    'give a figure to',
    'reach',
    'come to',
    'conclude',
    'establish',
    'seal',
    'settle on',
    'determine on',
    'acquire',
    'obtain',
    'gain',
    'get',
    'realize',
    'secure',
    'win',
    'earn',
    'gross',
    'fetch',
    'bring in',
    'take (in)',
    'pocket',
    'net',
    'clear',
    'take home',
    'lose',
    'catch',
    'get',
    'reach',
    'get to',
    'arrive/be in time for',
    'arrive at',
    'miss',
    'succeed',
    'prosper',
    'get ahead',
    'make good',
    'be successful',
    'distinguish oneself',
    'be a success',
    'get into',
    'enter',
    'achieve',
    'attain',
    'gain a place in',
    'gain access to',
    'succeed',
    'prosper',
    'get ahead',
    'make good',
    'be successful',
    'distinguish oneself',
    'be a success',
    'make a beeline for',
    'take to',
    'go toward',
    'head for/toward',
    'aim for',
    'make one\'s way toward',
    'move toward',
    'direct one\'s steps toward',
    'steer a course toward',
    'be bound for',
    'set out for',
    'feign',
    'pretend',
    'affect',
    'feint',
    'make out',
    'give the impression',
    'make a show/pretense of',
]