export const definitions = [
    '"manual dexterity"',
    '"manual hauling of boats along the towpath"',
    '"a manual typewriter"',
    '"a manual laborer"',
    '"a computer manual"',
    '"a training manual"',
    '"a pocket-sized manual of the artist\'s aphorisms"',
]
export const synonyms = [
    'laboring',
    'physical',
    'blue-collar',
    'done with one\'s hands',
    'hand-operated',
    'hand',
    'nonautomatic',
    'automatic',
    'mechanical',
    'hand-operated',
    'hand',
    'nonautomatic',
    'automatic',
    'mechanical',
    'handbook',
    'instructions',
    'guide',
    'companion',
    'reference book',
    'ABC',
    'guidebook',
    'vade mecum',
    'enchiridion',
    'set of instructions',
    'instruction book',
]