export const definitions = [
    '"farmers going to market"',
    '"the labor market"',
    '"the sale of cruisers in the American market continues to plummet"',
    '"there is a market for ornamental daggers"',
    '"the bottom\'s fallen out of the market"',
    '"future development cannot simply be left to the market"',
    '"a market economy"',
    '"the sale of the company\'s shares on world markets"',
    '"the product was marketed under the name \"aspirin.\""',
    '"sheep farmers are still unable to market their lambs"',
    '"some people liked to do their marketing very early in the morning"',
]
export const synonyms = [
    'shopping center',
    'marketplace',
    'mart',
    'flea market',
    'fair',
    'bazaar',
    'piazza',
    'plaza',
    'souk',
    'agora',
    'emporium',
    'retail outlet',
    'demand',
    'call',
    'want',
    'desire',
    'need',
    'requirement',
    'trade',
    'trading',
    'business',
    'commerce',
    'dealing',
    'buying and selling',
    'sell',
    'retail',
    'vend',
    'merchandise',
    'trade',
    'peddle',
    'hawk',
    'advertise',
    'promote',
    'offer for sale',
    'put up for sale',
    'sell',
    'vend',
    'put up for sale',
    'put on the market',
    'make available',
    'put under the hammer',
    'ask for bids for',
]