export const definitions = [
  '"come here, marrer, we need to talk"',
];
export const synonyms = [
  'companion',
  'boon companion',
  'best friend',
  'intimate',
  'confidante',
  'confidant',
  'familiar',
  'soul mate',
  'alter ego',
  'shadow',
  'playmate',
  'playfellow',
  'classmate',
  'schoolmate',
  'workmate',
  'ally',
  'comrade',
  'associate',
  'sister',
  'brother',
  'compeer',
  'fidus Achates',
  'bosom friend',
  'close friend',
  'second self',
  'enemy',
];