export const definitions = [
    '"saints, martyrs, and witnesses to the faith"',
    '"she wanted to play the martyr"',
    '"I\'m a martyr to migraines!"',
    '"she was martyred for her faith"',
    '"there was no need to martyr themselves again"',
]
export const synonyms = [
    'get',
    'suffer from',
    'be a constant sufferer from',
    'have chronic …',
    'be seriously affected by',
    'be afflicted with',
    'be troubled by',
    'kill',
    'martyrize',
    'burn',
    'stone',
    'immolate',
    'crucify',
    'put to death',
    'make a martyr of',
    'burn at the stake',
    'throw to the lions',
    'put on the rack',
]