export const definitions = [
  '"mashed banana"',
  '"he came home really mashed"',
  '"mash the beans to a paste"',
  '"he almost had his head mashed by a slamming door"',
  '"the worst thing you can do is mash the brake pedal"',
  '"the barley is dried out over peat fires and mashed with water which flows through peat ground"',
  '"I\'ve just mashed a pot of tea"',
  '"we\'d let the pot mash for ten minutes"',
];
export const synonyms = [
  'crush',
  'squeeze',
  'squash',
  'compress',
  'pulp',
  'reduce',
  'clamp',
  'pack down',
  'tamp',
  'condense',
  'compact',
  'trample',
  'stamp',
  'tread',
  'grind',
  'mill',
  'pound',
  'pulverize',
  'macerate',
  'pulp',
  'crush',
  'puree',
  'cream',
  'smash',
  'squash',
  'pound',
  'beat',
  'macerate',
  'liquidize',
  'liquefy',
  'whip',
  'grind',
  'mince',
  'soften',
  'mangle',
  'chew',
  'infuse',
  'stew',
  'mast',
  'be in preparation',
];