export const definitions = [
    '"adding a treatment masque to your cleansing routine works wonders"',
    '"this exfoliating mask helps clear your pores and leaves your skin feeling soft and healthy"',
    '"his face was a mask of rage"',
    '"she let her mask of moderate respectability slip"',
]
export const synonyms = [
    'masked ball',
    'fancy-dress party',
    'disguise',
    'veil',
    'false face',
    'domino',
    'stocking mask',
    'fancy dress',
    'visor',
    'vizard',
    'matte',
    'photomask',
    'shadow mask',
    'masking',
    'masking tape',
    'face mask',
    'face covering',
    'face shield',
    'surgical mask',
    'medical mask',
    'gas mask',
    'oxygen mask',
    'ski mask',
    'visor',
    'protective mask',
    'fencing mask',
    'iron mask',
    'dust mask',
    'safety goggles',
    'welding goggles',
    'welding mask',
    'eye mask',
    'pretense',
    'semblance',
    'veil',
    'screen',
    'front',
    'facade',
    'veneer',
    'blind',
    'false colors',
    'disguise',
    'guise',
    'concealment',
    'cover',
    'cover-up',
    'cloak',
    'camouflage',
    'false front',
]