export const definitions = [
    '"a single-masted fishing boat"',
]
export const synonyms = [
    'spar',
    'boom',
    'yard',
    'gaff',
    'foremast',
    'mainmast',
    'topmast',
    'mizzenmast',
    'mizzen',
    'royal mast',
    'stick',
    'flagpole',
    'flagstaff',
    'pole',
    'post',
    'rod',
    'support',
    'upright',
    'aerial',
    'transmitter',
    'pylon',
]