export const definitions = [
    '"ovulation occurs only if mating has taken place"',
    '"successful males may mate with many females"',
    '"a male is mated to several females"',
    '"a four-cylinder engine mated to a five-speed gearbox"',
]
export const synonyms = [
    'copulation',
    'copulating',
    'coupling',
    'sexual intercourse',
    'intercourse',
    'sex',
    'procreation',
    'pairing',
    'breeding',
    'union',
    'coitus',
    'coition',
    'copulation',
    'copulating',
    'coupling',
    'sexual intercourse',
    'intercourse',
    'sex',
    'procreation',
    'pairing',
    'breeding',
    'union',
    'coitus',
    'coition',
    'breed',
    'couple',
    'copulate',
    'sexually active',
    'couple',
    'pair',
    'join',
    'bring together',
]