export const definitions = [
    '"she was now a mature woman"',
    '"owls are sexually mature at one year"',
    '"mature trees"',
    '"a young man mature beyond his years"',
    '"on mature reflection he decided they should not go"',
    '"Miss Walker was a mature lady when she married"',
    '"Van Gogh\'s mature work"',
    '"a rather nice mature Camembert"',
    '"a mature, sophisticated economy"',
    '"children mature at different ages"',
    '"the trees take at least thirty years to mature"',
    '"she matured into a woman"',
    '"men mature as they grow older"',
    '"leave the cheese to mature"',
    '"the Scotch is matured for a minimum of three years"',
    '"when the policy matures it pays off the loan"',
]
export const synonyms = [
    'adult',
    'grown-up',
    'grown',
    'full-grown',
    'fully fledged',
    'nubile',
    'fully grown',
    'of age',
    'fully developed',
    'in one\'s prime',
    'in full bloom',
    'immature',
    'growing',
    'adolescent',
    'sensible',
    'responsible',
    'adult',
    'levelheaded',
    'reliable',
    'dependable',
    'discriminating',
    'shrewd',
    'practical',
    'wise',
    'sagacious',
    'experienced',
    'sophisticated',
    'immature',
    'childish',
    'careful',
    'thorough',
    'deep',
    'considered',
    'methodical',
    'impulsive',
    'unthinking',
    'elderly',
    'aged',
    'older',
    'senior',
    'long in the tooth',
    'gray',
    'grizzled',
    'hoary',
    'ancient',
    'decrepit',
    'doddering',
    'doddery',
    'ripe',
    'senescent',
    'senile',
    'superannuated',
    'venerable',
    'septuagenarian',
    'octogenarian',
    'nonagenarian',
    'centenarian',
    'wise',
    'sensible',
    'experienced',
    'worldly-wise',
    'knowledgeable',
    'familiar',
    'practiced',
    'skilled',
    'skillful',
    'adept',
    'expert',
    'veteran',
    'advanced in years',
    'up in years',
    'getting on',
    'in one\'s dotage',
    'gray-haired',
    'gray-bearded',
    'past one\'s prime',
    'not as young as one was',
    'not long for this world',
    'longevous',
    'well versed',
    'young',
    'ingenuous',
    'inexperienced',
    'ripe',
    'ripened',
    'mellow',
    'ready',
    'seasoned',
    'full-flavored',
    'fresh',
    'unripe',
    'come of age',
    'develop',
    'grow',
    'evolve',
    'bloom',
    'blossom',
    'flourish',
    'thrive',
    'be fully grown',
    'be full-grown',
    'be fully developed',
    'develop fully',
    'become adult',
    'reach adulthood',
    'reach maturity',
    'come to fruition',
    'grow up',
    'bloom',
    'blossom',
    'become more sensible/responsible/adult',
    'ripen',
    'mellow',
    'age',
    'grow ripe',
    'become ripe',
    'become mellow',
]