export const definitions = [
  '"the society does its best on limited mazuma"',
];
export const synonyms = [
  'cash',
  'hard cash',
  'ready money',
  'funds',
  'capital',
  'finances',
  'banknotes',
  'notes',
  'paper money',
  'coins',
  'change',
  'coin',
  'coinage',
  'silver',
  'copper',
  'currency',
  'legal tender',
  'sterling',
  'bills',
  'roll',
  'specie',
  'pelf',
  'the means',
  'the wherewithal',
  '(filthy) lucre',
  'l.s.d.',
];