export const definitions = [
  '"they were forced to supplement their meager earnings"',
  '"a meager diet of bread and beans"',
  '"a tall, meager man"',
];
export const synonyms = [
  'inadequate',
  'scanty',
  'scant',
  'paltry',
  'limited',
  'restricted',
  'modest',
  'insufficient',
  'sparse',
  'spare',
  'deficient',
  'negligible',
  'insubstantial',
  'skimpy',
  'short',
  'little',
  'lean',
  'small',
  'slight',
  'slender',
  'poor',
  'miserable',
  'pitiful',
  'puny',
  'miserly',
  'beggarly',
  'exiguous',
  'abundant',
  'thin',
  'lean',
  'skinny',
  'spare',
  'scrawny',
  'scraggly',
  'gangling',
  'gangly',
  'spindly',
  'stringy',
  'lanky',
  'reedy',
  'bony',
  'rawboned',
  'gaunt',
  'underweight',
  'emaciated',
  'skeletal',
  'starved',
  'underfed',
  'undernourished',
  'attenuated',
  'wraithlike',
  'cadaverous',
  'wasted',
  'anorexic',
  'thin as a rake',
  'fat',
];