export const definitions = [
  '"a medial ligament"',
  '"a medial consonant"',
];
export const synonyms = [
  'halfway',
  'in-between',
  'middle',
  'mid',
  'midway',
  'median',
  'intermediary',
  'intervening',
  'interposed',
  'transitional',
  'in the middle',
  'at the halfway point',
  'equidistant between two points/stages',
  'intermedial',
  'mean',
  'median',
  'middle',
  'middle',
  'center',
  'halfway',
  'midway',
  'mid',
  'median',
  'mean',
  'middling',
  'intermediate',
  'mesial',
  'intermedial',
  'side',
  'extreme',
];