export const definitions = [
    '"the median duration of this treatment was four months"',
    '"the median part of the sternum"',
    '"acreages ranged from one to fifty-two with a median of twenty-four"',
    '"the Median empire"',
    'Loading',
]
export const synonyms = [
    'mean',
    'medial',
    'middle',
    'halfway',
    'in-between',
    'middle',
    'mid',
    'midway',
    'intermediary',
    'intervening',
    'interposed',
    'transitional',
    'medial',
    'in the middle',
    'at the halfway point',
    'equidistant between two points/stages',
    'intermedial',
    'mean',
    'mode',
    'midpoint',
    'center',
    'norm',
    'standard',
    'rule',
    'par',
    'the general run',
    'center',
    'mean',
    'mid point',
    'dead center',
    'focal point',
    'focus',
    'hub',
    'nucleus',
    'midst',
    'eye',
    'heart',
    'core',
    'kernel',
    'bosom',
    'interior',
    'depths',
    'thick',
    'bullseye',
    'halfway point',
    'outside',
    'circumference',
]