export const definitions = [
  '"I used to call her Miss Mouse because she was so meek and mild"',
  '"the meek compliance of our politicians"',
];
export const synonyms = [
  'patient',
  'long-suffering',
  'forbearing',
  'resigned',
  'gentle',
  'quiet',
  'shy',
  'retiring',
  'reverent',
  'peaceful',
  'peaceable',
  'docile',
  'lamblike',
  'mild',
  'demure',
  'modest',
  'humble',
  'lowly',
  'diffident',
  'unassuming',
  'self-effacing',
  'unpretentious',
  'unambitious',
  'unobtrusive',
  'submissive',
  'yielding',
  'unresisting',
  'obedient',
  'compliant',
  'tame',
  'biddable',
  'tractable',
  'acquiescent',
  'deferential',
  'weak',
  'timid',
  'frightened',
  'spineless',
  'spiritless',
  'unprotesting',
  'like a lamb to the slaughter',
  'impatient',
  'assertive',
  'overbearing',
];