export const definitions = [
    '"in 1924 she published a short memoir of her husband"',
    '"a revealing passage from Khrushchev\'s memoirs"',
    '"an important memoir on Carboniferous crustacea"',
    '"Memoirs of the Horticultural Society"',
]
export const synonyms = [
    'account',
    'history',
    'record',
    'chronicle',
    'commentary',
    'narrative',
    'story',
    'report',
    'portrayal',
    'depiction',
    'sketch',
    'portrait',
    'life',
    'profile',
    'biography',
    'autobiography',
    'memories',
    'recollections',
    'reminiscences',
    'experiences',
    'journal',
    'diary',
    'log',
    'weblog',
    'blog',
    'vlog',
    'moblog',
    'historical account',
    'annal(s)',
    'life story',
    'personal recollections',
]