export const definitions = [
  '"mental faculties"',
  '"mental phenomena"',
  '"a quick mental calculation"',
  '"I started my mental journey"',
  '"mental health"',
  '"a mental illness"',
  '"last week was just mental!"',
  '"she said honeymooning without her new husband was mental"',
  '"it\'s going to be a mental night"',
  '"I think he was a little worried that I might be mental"',
];
export const synonyms = [
  'intellectual',
  'cerebral',
  'brain',
  'rational',
  'psychological',
  'cognitive',
  'abstract',
  'conceptual',
  'theoretical',
  'phrenic',
  'mindly',
  'physical',
  'psychiatric',
  'psychogenic',
  'mad',
  'insane',
  'certifiable',
  'deranged',
  'demented',
  'out of one\'s mind',
  'not in \'s \'s right mind',
  'crazy',
  'crazed',
  'lunatic',
  'non compos mentis',
  'unbalanced',
  'unhinged',
  'unstable',
  'disturbed',
  'distracted',
  'manic',
  'frenzied',
  'raving',
  'distraught',
  'frantic',
  'hysterical',
  'delirious',
  'psychotic',
  'psychopathic',
  'sectionable',
  'out of one\'s tree',
  'meshuga',
  'squirrelly',
  'wacko',
  'mentally ill',
  'of unsound mind',
  'sick in the head',
  'not together',
  'stark mad',
  'mad as a hatter',
  'mad as a March hare',
  'foaming at the mouth',
  'sane',
];