export const definitions = [
    '"those who work honestly at their métier"',
    '"she decided that her real métier was grand opera"',
    '"subtlety is not his métier"',
]
export const synonyms = [
    'occupation',
    'job',
    'day job',
    'work',
    'profession',
    'specialism',
    'business',
    'employment',
    'employ',
    'career',
    'calling',
    'vocation',
    'mission',
    'trade',
    'craft',
    'walk of life',
    'field',
    'province',
    'area',
    'specialty',
    'line (of work)',
    'forte',
    'strong point',
    'strength',
    'long suit',
    'strong suit',
    'speciality',
    'talent',
    'skill',
    'gift',
    'bent',
]