export const definitions = [
    '"a meadow ready for cutting"',
    '"143 acres of meadow and pasture"',
    '"a pleasant campsite in a meadow, complete with sparkling stream"',
]
export const synonyms = [
    'field',
    'pasture',
    'paddock',
    'pastureland',
    'grassland',
    'lea',
    'mead',
    'water meadow',
    'bawn',
    'field',
    'pasture',
    'paddock',
    'pastureland',
    'grassland',
    'lea',
    'mead',
    'water meadow',
    'bawn',
]