export const definitions = [
  '"she stood alone in the middle of the street"',
  '"we were married in the middle of December"',
  '"he had a towel around his middle"',
  '"the early and middle part of life"',
  '"middle and eastern Europe"',
  '"the woman was in her middle forties"',
  '"there is a dearth of talent at the middle level"',
  '"Middle High German"',
];
export const synonyms = [
  'center',
  'mean',
  'median',
  'mid point',
  'dead center',
  'focal point',
  'focus',
  'hub',
  'nucleus',
  'midst',
  'eye',
  'heart',
  'core',
  'kernel',
  'bosom',
  'interior',
  'depths',
  'thick',
  'bullseye',
  'halfway point',
  'outside',
  'circumference',
  'midriff',
  'waist',
  'waistline',
  'belly',
  'gut',
  'stomach',
  'paunch',
  'pot belly',
  'beer belly',
  'central',
  'mid',
  'mean',
  'medium',
  'medial',
  'median',
  'midway',
  'halfway',
  'equidistant',
  'mesial',
  'intermediate',
  'intermediary',
  'inner',
  'inside',
  'intermedial',
];