export const definitions = [
    '"three mighty industrial countries"',
    '"mighty beasts"',
    '"a mighty heave"',
    '"a mighty blow against racism"',
    '"she gave a mighty hiccup"',
    '"it seems mighty early to be talking about Christmas"',
    '"my ears got cold mighty fast"',
]
export const synonyms = [
    'fearsome',
    'ferocious',
    'big',
    'tough',
    'robust',
    'manful',
    'potent',
    'sturdy',
    'muscular',
    'strapping',
    'Herculean',
    'vigorous',
    'energetic',
    'stout',
    'dominant',
    'influential',
    'strong',
    'powerful',
    'important',
    'leading',
    'authoritative',
    'controlling',
    'predominant',
    'prestigious',
    'puny',
    'tiny',
    'insignificant',
    'powerful',
    'forceful',
    'violent',
    'ferocious',
    'fierce',
    'brutal',
    'vicious',
    'vigorous',
    'hefty',
    'thunderous',
    'savage',
    'destructive',
    'damaging',
    'painful',
    'lethal',
    'deadly',
    'feeble',
    'huge',
    'enormous',
    'massive',
    'gigantic',
    'big',
    'large',
    'great',
    'giant',
    'colossal',
    'mammoth',
    'vast',
    'immense',
    'tremendous',
    'stupendous',
    'monumental',
    'prodigious',
    'mountainous',
    'monstrous',
    'titanic',
    'towering',
    'elephantine',
    'king-sized',
    'king-size',
    'gargantuan',
    'Brobdingnagian',
    'substantial',
    'tiny',
    'extremely',
    'exceedingly',
    'enormously',
    'vastly',
    'immensely',
    'tremendously',
    'hugely',
    'markedly',
    'remarkably',
    'abundantly',
    'deadly',
    'awfully',
    'dreadfully',
    'mightily',
    'very',
    'most',
    'so',
    'to a great extent',
    'very much',
]