export const definitions = [
  '"he checked his appearance in the mirror"',
  '"the stage is supposed to be the mirror of life"',
  '"the company now has a mirror site in Taiwan"',
  '"the clear water mirrored the sky"',
  '"his own views mirrored those of his followers"',
  '"gradations of educational attainment mirror differences in social background"',
  '"those predictions mirror the preliminary data from the Tourist Board"',
  '"device owners can mirror their screen to their TV"',
  '"wireless technology lets you mirror your phone\'s screen on a compatible TV"',
  '"his site was mirrored at several colleges around the United States"',
  '"another three identical drives would mirror data from primary sources"',
];
export const synonyms = [
  'looking glass',
  'reflector',
  'glass',
  'reflecting surface',
  'reflection',
  'twin',
  'double',
  'image',
  'replica',
  'copy',
  'clone',
  'match',
  'parallel',
  'exact likeness',
  'throw back',
  'give back',
  'return',
  'send back',
  'cast back',
  'bounce back',
  'shine back',
  'absorb',
  'reflect',
  'repeat',
  'match',
  'reproduce',
  'imitate',
  'simulate',
  'reiterate',
  'follow',
  'copy',
  'mimic',
  'echo',
  'parallel',
  'impersonate',
  'correspond to',
];