export const definitions = [
    '"a laser-guided bomb had missed its target"',
    '"he was given two free throws, but missed both times"',
    '"a piece of shrapnel missed him by inches"',
    '"Mandy missed the catch, and flung the ball back crossly"',
    '"Callison tried for a catch and missed"',
    '"the villa is impossible to miss—it\'s right by the road"',
    '"I\'ll say it again in case you missed it"',
    '"teachers were supposed to report those students who missed class that day"',
    '"we\'ll miss the train if he doesn\'t hurry"',
    '"\"Potter\'s been here this morning ?\" \"You\'ve just missed him.\""',
    '"don\'t miss the chance to visit the breathtaking Dolomites"',
    '"I drive in at 5 a.m. to miss the traffic"',
    '"how many periods have you missed?"',
    '"I think I\'m pregnant—this is the second time I\'ve missed"',
    '"he\'s rich—he won\'t miss the money"',
    '"she slipped away when she thought she wouldn\'t be missed"',
    '"she misses all her old friends"',
    '"I still miss France and I wish I could go back"',
    '"the motor began missing and investigation found a cracked cylinder head"',
    '"Elster\'s stunning catch in the third inning made up for his dreadful miss in the first"',
    '"audiences will decide whether Bra\'s \'s latest flick is a hit or a miss"',
    '"Miss Hazel Armstrong"',
    '"Miss World"',
    '"where will you be staying in England, miss?"',
    '"please, Miss, can I be excused?"',
    '"there was none of the country bumpkin about this young miss"',
    '"she had a miss, that time, lost the baby"',
]
export const synonyms = [
    'fail to hit',
    'be wide of',
    'go wide of',
    'fall short of',
    'hit',
    'drop',
    'fumble',
    'fluff',
    'bungle',
    'mishandle',
    'misfield',
    'mishit',
    'fail to catch',
    'catch',
    'mishear',
    'misunderstand',
    'overlook',
    'pass over',
    'forget',
    'fail to hear',
    'fail to take in',
    'fail to see/notice',
    'see',
    'notice',
    'cut',
    'skip',
    'omit',
    'fail to attend',
    'be too late for',
    'absent oneself from',
    'be absent from',
    'play truant from',
    'take French leave from',
    'attend',
    'be too late for',
    'fail to catch/get',
    'catch',
    'notice the absence of',
    'find missing',
    'forfeit',
    'pass up',
    'overlook',
    'disregard',
    'fail to take advantage of',
    'fail to seize/grasp/take',
    'let slip',
    'let go/pass',
    'lose out on',
    'avoid',
    'beat',
    'evade',
    'escape',
    'dodge',
    'sidestep',
    'elude',
    'get around',
    'circumvent',
    'steer clear of',
    'bypass',
    'skirt',
    'cheat',
    'duck',
    'give a wide berth to',
    'find a way around',
    'get caught up in',
    'leave out',
    'exclude',
    'except',
    'pass over',
    'skip',
    'fail to include',
    'miss off',
    'fail to mention',
    'notice the absence of',
    'find missing',
    'need',
    'pine for',
    'yearn for',
    'ache for',
    'long for',
    'long to see',
    'regret the absence/loss of',
    'feel the loss of',
    'feel nostalgic for',
    'need',
    'pine for',
    'yearn for',
    'ache for',
    'long for',
    'long to see',
    'regret the absence/loss of',
    'feel the loss of',
    'feel nostalgic for',
    'failure',
    'omission',
    'slip',
    'blunder',
    'error',
    'mistake',
    'fiasco',
    'hit',
    'young lady',
    'girl',
    'lass',
    'lassie',
    'colleen',
    'maid',
    'maiden',
    'damsel',
    'nymph',
    'wench',
    'young woman',
    'slip of a girl',
]