export const definitions = [
  '"she may be prepared to modify her views"',
  '"the theory has been modified to fit subsequent experimental evidence"',
  '"a modified version of the aircraft"',
  '"the target noun is modified by a \"direction\" word"',
];
export const synonyms = [
  'alter',
  'change',
  'adjust',
  'adapt',
  'amend',
  'improve',
  'revise',
  'recast',
  'reform',
  'reshape',
  'refashion',
  'redesign',
  'restyle',
  'revamp',
  'rework',
  'remake',
  'remodel',
  'remold',
  'redo',
  'reconstruct',
  'reorganize',
  'refine',
  'reorient',
  'reorientate',
  'vary',
  'transform',
  'convert',
  'customize',
  'tailor',
  'permute',
  'permutate',
  'moderate',
  'temper',
  'soften',
  'tone down',
  'blunt',
  'dull',
  'qualify',
  'restrict',
  'limit',
  'lessen',
  'reduce',
  'decrease',
  'diminish',
  'lower',
  'abate',
  'mitigate',
  'make alterations to',
  'make adjustments to',
];