export const definitions = [
  '"he was charged with molesting and taking obscene photographs of a ten-year-old boy"',
  '"he had been arrested for being drunk and molesting passers-by"',
];
export const synonyms = [
  'abuse',
  'assault',
  'rape',
  'violate',
  'attack',
  'hurt',
  'harm',
  'injure',
  'ravish',
  'sexually abuse',
  'sexually assault',
  'interfere with',
  'harass',
  'harry',
  'pester',
  'beset',
  'persecute',
  'torment',
  'plague',
];