export const definitions = [
    '"she was silent for a moment before replying"',
    '"a few moments later he returned to the office"',
    '"she would always remember the moment they met"',
    '"I was waiting for the right moment"',
    '"one of the great moments in aviation history"',
    '"the issues were of little moment to the electorate"',
]
export const synonyms = [
    'bit',
    'minute',
    'second',
    'instant',
    'split second',
    'little while',
    'short time',
    'point',
    'time',
    'hour',
    'juncture',
    'stage',
    'point in time',
    'point',
    'time',
    'hour',
    'juncture',
    'stage',
    'point in time',
    'importance',
    'import',
    'significance',
    'consequence',
    'substance',
    'note',
    'mark',
    'prominence',
    'value',
    'weight',
    'concern',
    'interest',
    'gravity',
    'seriousness',
]