export const definitions = [
  '"where have you been, you little monkey!"',
  '"don\'t monkey with that lock!"',
];
export const synonyms = [
  'simian',
  'primate',
  'ape',
  'rascal',
  'imp',
  'wretch',
  'mischief-maker',
  'devil',
  'rogue',
  'scapegrace',
  'rapscallion',
  'fool around',
  'play around',
  'fiddle-faddle',
  'clown around',
  'play with',
  'fool with',
  'tamper with',
  'fiddle with',
  'interfere with',
  'meddle with',
  'tinker with',
  'touch/handle without permission',
  'trifle with',
  'imitate',
  'copy',
  'impersonate',
  'take off',
  'do',
  'ape',
  'caricature',
  'mock',
  'make fun of',
  'parody',
  'satirize',
  'lampoon',
  'burlesque',
  'travesty',
  'do an impression of',
  'do an impersonation of',
];