export const definitions = [
  '"no use moping—things could be worse"',
  '"moping around at home won\'t get you anywhere"',
  '"they\'re just a bunch of mopes"',
  '"they switched to treating him like a child just bravely out of its mopes"',
];
export const synonyms = [
  'brood',
  'sulk',
  'pine',
  'eat one\'s heart out',
  'fret',
  'grieve',
  'despair',
  'repine',
  'be miserable',
  'be gloomy',
  'be sad',
  'be despondent',
  'languish',
  'moon',
  'droop',
  'idle',
  'loaf',
  'fiddle',
  'drift',
  'stooge',
  'melancholic',
  'depressive',
  'pessimist',
  'killjoy',
  'moaner',
  'melancholiac',
  'prophet of doom',
];