export const definitions = [
    '"in midwinter the track beneath this bridge became a muddy morass"',
    '"she would become lost in a morass of lies and explanations"',
]
export const synonyms = [
    'quagmire',
    'swamp',
    'bog',
    'marsh',
    'mire',
    'quag',
    'marshland',
    'fen',
    'slough',
    'quicksand',
    'moss',
    'bayou',
    'moor',
    'peat bog',
    'carr',
    'corcass',
    'pocosin',
    'marish',
    'confusion',
    'chaos',
    'muddle',
    'tangle',
    'entanglement',
    'imbroglio',
    'mix-up',
    'jumble',
    'clutter',
    'mire',
    'quagmire',
    'comess',
]