export const definitions = [
    '"his mother was a painter"',
    '"a mother of three"',
    '"she returned to Bristol to nurse her aging mother"',
    '"a mother penguin"',
    '"she will always be remembered as the mother of modern ecology"',
    '"they are often referred to as the founding mothers of the Museum of Modern Art"',
    '"the mother church"',
    '"she didn\'t know how to mother my brother and he was very sensitive"',
    '"he found a beautiful wife that mothered his children"',
    '"she felt mothered by her older sister"',
    '"she\'s mothered two foals that have gone on to be impressive dressage competitors"',
]
export const synonyms = [
    'birth mother',
    'stepmother',
    'surrogate mother',
    'materfamilias',
    'matriarch',
    'female parent',
    'biological mother',
    'foster mother',
    'adoptive mother',
    'Mata',
    'progenitress',
    'progenitrix',
    'dam',
    'originator',
    'initiator',
    'founder',
    'inventor',
    'creator',
    'maker',
    'author',
    'prime mover',
    'instigator',
    'architect',
    'engineer',
    'designer',
    'deviser',
    'planner',
    'contriver',
    'mastermind',
    'begetter',
    'founding mother',
    'bring up',
    'take care of',
    'look after',
    'rear',
    'support',
    'raise',
    'foster',
    'parent',
    'tend',
    'feed',
    'nourish',
    'provender',
    'care for',
    'provide for',
    'attend to',
    'neglect',
    'look after',
    'take care of',
    'nurture',
    'nurse',
    'protect',
    'cherish',
    'tend',
    'raise',
    'rear',
    'pamper',
    'coddle',
    'cosset',
    'baby',
    'overprotect',
    'overparent',
    'indulge',
    'spoil',
    'care for',
    'fuss over',
    'neglect',
    'have',
    'deliver',
    'bear',
    'produce',
    'bring forth',
    'birth',
    'give birth to',
    'be brought to bed of',
]