export const definitions = [
    '"the laws of planetary motion"',
    '"a cushioned shoe that doesn\'t restrict motion"',
    '"she made a motion with her free hand"',
    '"the earliest engines had the Gresley conjugated motion for the middle cylinder"',
    '"the head of our commission made a motion that we rewrite the constitution"',
    '"often the defendant contributes to the length of proceedings by filing many procedural motions"',
    '"he motioned Dennis to a plush chair"',
    '"he motioned the young officer to sit down"',
    '"he motioned for a time out"',
    '"a resolution, motioned by Adam Tyler, proposed that members without a CCL could still belong to the association"',
    '"Councillor Byrne motioned that the committee call on the area manager to install street lighting"',
]
export const synonyms = [
    'movement',
    'moving',
    'locomotion',
    'shifting',
    'stirring',
    'to and fro',
    'toing and froing',
    'progress',
    'passage',
    'passing',
    'transit',
    'course',
    'flow',
    'going',
    'travel',
    'traveling',
    'motility',
    'mobility',
    'rise and fall',
    'coming and going',
    'gesture',
    'gesticulation',
    'movement',
    'signal',
    'sign',
    'indication',
    'wave',
    'nod',
    'body language',
    'kinesics',
    'proposal',
    'proposition',
    'submission',
    'recommendation',
    'suggestion',
    'gesture',
    'gesticulate',
    'signal',
    'sign',
    'direct',
    'indicate',
    'wave',
    'beckon',
    'nod',
]