export const definitions = [
  '"a motley crew of discontents and zealots"',
  '"a motley of interacting interest groups"',
  '"life-size mannequins in full motley"',
];
export const synonyms = [
  'miscellaneous',
  'disparate',
  'diverse',
  'assorted',
  'sundry',
  'varied',
  'mixed',
  'diversified',
  'heterogeneous',
  'homogeneous',
  'uniform',
  'mixture',
  'assortment',
  'collection',
  'selection',
  'assemblage',
  'medley',
  'miscellany',
  'melange',
  'mix',
  'variety',
  'mixed bag',
  'patchwork',
  'pastiche',
  'blend',
  'smorgasbord',
  'ragbag',
  'hotchpotch',
  'hodgepodge',
  'mishmash',
  'jumble',
  'farrago',
  'gallimaufry',
  'omnium gatherum',
  'olio',
  'olla podrida',
  'salmagundi',
  'pasticcio',
  'macédoine',
  'motley collection',
];