export const definitions = [
  '"the school motto, \"Serve and obey\""',
  '"he soon adopted the motto \"work hard and play hard.\""',
];
export const synonyms = [
  'maxim',
  'saying',
  'proverb',
  'aphorism',
  'adage',
  'saw',
  'axiom',
  'formula',
  'expression',
  'phrase',
  'rule',
  'dictum',
  'precept',
  'epigram',
  'gnome',
  'slogan',
  'catchphrase',
  'watchword',
  'byword',
  'cry',
  'battle cry',
  'truism',
  'cliché',
  'platitude',
  'apothegm',
];