export const definitions = [
    '"a mousy smell"',
    '"his mousy sister had become a dynamic journalist"',
]
export const synonyms = [
    'brownish',
    'colourless',
    'neutral',
    'drab',
    'dull',
    'lacklustre',
    'lightish brown',
    'brownish-grey',
    'dun-coloured',
    'timid',
    'quiet',
    'meek',
    'fearful',
    'timorous',
    'shy',
    'self-effacing',
    'diffident',
    'ineffectual',
    'unassertive',
    'unconfident',
    'unforthcoming',
    'reticent',
    'shrinking',
    'hesitant',
    'withdrawn',
    'introverted',
    'introvert',
    'unobtrusive',
    'bold',
    'brazen',
    'ferocious',
]