export const definitions = [
  '"I fear he may have muddled the message"',
  '"Paul was hopelessly muddled by the rates of exchange"',
  '"he was muddling about in the kitchen"',
  '"muddle the kiwi slices with the sugar"',
  '"the finances were in a muddle"',
  '"a muddle of French, English, Ojibwa, and a dash of Gaelic"',
  '"a bureaucratic muddle"',
];
export const synonyms = [
  'jumbled',
  'chaotic',
  'topsy-turvy',
  'disorganized',
  'disordered',
  'disorderly',
  'out of place',
  'out of order',
  'mixed up',
  'upside-down',
  'at sixes and sevens',
  'untidy',
  'messy',
  'scrambled',
  'tangled',
  'confuse',
  'mix up',
  'jumble',
  'disarrange',
  'disorganize',
  'disorder',
  'disturb',
  'scramble',
  'mess up',
  'in a jumble',
  'in a muddle',
  'in a mess',
  'in disorder',
  'in disarray',
  'jumble up',
  'throw into disorder',
  'get into a tangle',
  'orderly',
  'be in (good) order',
  'confused',
  'bewildered',
  'bemused',
  'perplexed',
  'disorientated',
  'disoriented',
  'at sea',
  'befuddled',
  'dazed',
  'incoherent',
  'muddle-headed',
  'woolly',
  'jumbled',
  'disjointed',
  'bewilder',
  'confuse',
  'bemuse',
  'perplex',
  'puzzle',
  'baffle',
  'nonplus',
  'mystify',
  'confound',
  'disorientate',
  'disorient',
  'befuddle',
  'daze',
  'addle',
  'in a state of confusion',
  'in a muddle',
  'clear',
  'lucid',
  'enlighten',
  'mix',
  'blend',
  'agitate',
  'beat',
  'whip',
  'whisk',
  'fold in',
  'untidiness',
  'disorder',
  'disarray',
  'clutter',
  'heap',
  'shambles',
  'litter',
  'tangle',
  'jumble',
  'mishmash',
  'chaos',
  'confusion',
  'disorganization',
  'turmoil',
  'bungle',
  'mix-up',
  'misunderstanding',
  'mistake',
];