export const definitions = [
    '"the stabbing murder of an off-Broadway producer"',
    '"he was put on trial for attempted murder"',
    '"my first job at the steel mill was murder"',
    '"somebody tried to murder Joe"',
    '"my father will murder me if I\'m home late"',
    '"the only thing he had murdered was the English language"',
]
export const synonyms = [
    'killing',
    'homicide',
    'assassination',
    'liquidation',
    'extermination',
    'execution',
    'slaughter',
    'butchery',
    'massacre',
    'manslaughter',
    'patricide',
    'matricide',
    'parricide',
    'fratricide',
    'filicide',
    'infanticide',
    'uxoricide',
    'regicide',
    'slaying',
    'sororicide',
    'hell',
    'misery',
    'torture',
    'agony',
    'hell on earth',
    'a nightmare',
    'an ordeal',
    'a trial',
    'a frustrating/unpleasant/difficult experience',
    'kill',
    'assassinate',
    'execute',
    'liquidate',
    'eliminate',
    'neutralize',
    'dispatch',
    'butcher',
    'slaughter',
    'massacre',
    'wipe out',
    'mow down',
    'slay',
    'put/do to death',
    'cut to pieces',
    'beat',
    'conquer',
    'get the better of',
    'best',
    'worst',
    'vanquish',
    'rout',
    'trounce',
    'overcome',
    'overpower',
    'overthrow',
    'overwhelm',
    'crush',
    'quash',
    'bring someone to their knees',
    'quell',
    'subjugate',
    'subdue',
    'repulse',
    'win against',
    'win a victory over',
    'triumph over',
    'prevail over',
    'lose to',
    'spoil',
    'ruin',
    'mar',
    'mutilate',
    'mangle',
    'mess up',
    'make a mess of',
    'wreck',
    'cut about',
]