export const definitions = [
    '"the calf muscle"',
    '"the sheet of muscle between the abdomen and chest"',
    '"showing off our muscles to prove how strong we were"',
    '"he had muscle but no brains"',
    '"an ex-marine of enormous proportions who\'d been brought along as muscle"',
    '"he had enough muscle and resources to hold his position on the council"',
    '"they were muscling baggage into the hold of the plane"',
    '"he was eventually muscled out of business"',
]
export const synonyms = [
    'thew',
    'strength',
    'power',
    'muscularity',
    'brawn',
    'brawniness',
    'burliness',
    'huskiness',
    'thew',
    'influence',
    'power',
    'strength',
    'might',
    'force',
    'forcefulness',
    'weight',
    'potency',
]