export const definitions = [
  '"his musings were interrupted by the sound of the telephone"',
  '"the sad musing gaze"',
  '"he was musing on the problems he faced"',
  '"\"I think I\'ve seen him somewhere before,\" mused Rachel"',
  '"he sat on the edge of the bank, legs dangling, eyes musing on the water"',
];
export const synonyms = [
  'meditation',
  'thinking',
  'contemplation',
  'deliberation',
  'pondering',
  'reflection',
  'rumination',
  'cogitation',
  'introspection',
  'daydreaming',
  'dreaming',
  'reverie',
  'abstraction',
  'preoccupation',
  'brooding',
  'woolgathering',
  'cerebration',
  'brown study',
  'ponder',
  'consider',
  'contemplate',
  'deliberate',
  'chew over',
  'weigh up',
  'evaluate',
  'examine',
  'study',
  'review',
  'think',
  'daydream',
  'cerebrate',
  'think over/about',
  'mull over',
  'reflect on',
  'turn over in one\'s mind',
  'meditate on',
  'ruminate over/on',
  'brood on',
  'give some thought to',
  'cogitate on',
  'debate with oneself',
  'be lost in contemplation/thought',
  'be in a brown study',
  'be in a reverie',
  'pore on',
];