export const definitions = [
    '"Irene, the talkative one, was now mute"',
    '"she gazed at him in mute appeal"',
    '"the great church was mute and dark"',
    '"mute e is generally dropped before suffixes beginning with a vowel"',
    '"an undertaker\'s mute"',
    '"her footsteps were muted by the thick carpet"',
    '"when muted and blown hard the trombone produces a very nasal and metallic sound"',
    '"his professional contentment was muted by personal sadness"',
    '"it seems the changes merely muted the symptoms rather than tackling the root problem"',
    '"this mode will mute the ringtone and message notification sounds"',
    '"remember to mute other gadgets such as phones, watches, and computers that could distract by their alerts"',
    '"it\'s simple to mute notifications you don\'t want to see"',
    '"you can mute posts depending on what you feel is best for your mental health"',
]
export const synonyms = [
    'silent',
    'speechless',
    'dumb',
    'unspeaking',
    'wordless',
    'voiceless',
    'tongue-tied',
    'tight-lipped',
    'close-mouthed',
    'taciturn',
    'uncommunicative',
    'at a loss for words',
    'mumchance',
    'voluble',
    'talkative',
    'wordless',
    'silent',
    'dumb',
    'tacit',
    'unspoken',
    'inarticulate',
    'unvoiced',
    'unsaid',
    'unexpressed',
    'unuttered',
    'spoken',
    'quiet',
    'silent',
    'noiseless',
    'soundless',
    'hushed',
    'noisy',
    'dumb',
    'aphasic',
    'unable to speak',
    'aphonic',
    'deaden',
    'muffle',
    'mask',
    'dull',
    'dampen',
    'soften',
    'silence',
    'stifle',
    'smother',
    'suppress',
    'lower',
    'reduce',
    'diminish',
    'decrease',
    'quieten',
    'quiet',
    'damp down',
    'amplify',
    'restrain',
    'soften',
    'subdue',
    'tone down',
    'moderate',
    'temper',
    'soft-pedal',
    'make less intense',
    'intensify',
]