export const definitions = [
    '"her footsteps were muted by the thick carpet"',
    '"when muted and blown hard the trombone produces a very nasal and metallic sound"',
    '"his professional contentment was muted by personal sadness"',
    '"it seems the changes merely muted the symptoms rather than tackling the root problem"',
    '"this mode will mute the ringtone and message notification sounds"',
    '"remember to mute other gadgets such as phones, watches, and computers that could distract by their alerts"',
    '"it\'s simple to mute notifications you don\'t want to see"',
    '"you can mute posts depending on what you feel is best for your mental health"',
]
export const synonyms = [
    'deaden',
    'muffle',
    'mask',
    'dull',
    'dampen',
    'soften',
    'silence',
    'stifle',
    'smother',
    'suppress',
    'lower',
    'reduce',
    'diminish',
    'decrease',
    'quieten',
    'quiet',
    'damp down',
    'amplify',
    'restrain',
    'soften',
    'subdue',
    'tone down',
    'moderate',
    'temper',
    'soft-pedal',
    'make less intense',
    'intensify',
]