export const definitions = [
    '"he muttered something under his breath"',
    '"\"I knew she was a troublemaker,\" Rebecca muttered"',
    '"she muttered in annoyance as the keys slid from her fingers"',
    '"when he disappeared, people began to mutter"',
    '"a little mutter of disgust"',
]
export const synonyms = [
    'murmur',
    'mumble',
    'whisper',
    'talk under one\'s breath',
    'speak in an undertone',
    'speak sotto voce',
    'speak in hushed tones',
    'talk to oneself',
    'speak out',
    'grumble',
    'moan',
    'complain',
    'grouse',
    'carp',
    'whine',
    'bleat',
    'twine',
    'mither',
    'complaint',
    'grumble',
    'moan',
    'murmur',
    'grouse',
    'objection',
    'protest',
    'protestation',
    'outcry',
    'demur',
    'argument',
    'remonstrance',
    'remonstration',
    'exception',
    'grievance',
    'cavil',
    'quibble',
    'word',
    'sound',
]