export const definitions = [
    '"she patted the horse\'s velvety muzzle"',
    '"the law says that pit bull terriers have to wear a muzzle"',
    '"his close-shaven muzzle"',
    '"Devlin jammed the muzzle of the gun into the man\'s neck"',
    '"the dog should have been muzzled"',
    '"the politicians want to muzzle us and control what we write"',
]
export const synonyms = [
    'snout',
    'nose',
    'mouth',
    'jaws',
    'maw',
    'gag',
    'restraint',
    'gag',
    'silence',
    'censor',
    'suppress',
    'stifle',
    'inhibit',
    'restrain',
    'check',
    'curb',
    'fetter',
    'deplatform',
    'no-platform',
]