export const definitions = [
  '"networks connecting a myriad of computers"',
  '"myriads of insects danced around the light above my head"',
  '"the army was organized on a decimal system, up to divisions of 10,000 or myriads"',
  '"the myriad lights of the city"',
  '"the myriad political scene"',
];
export const synonyms = [
  'multitude',
  'scores',
  'quantities',
  'mass',
  'crowd',
  'throng',
  'host',
  'droves',
  'horde',
  'army',
  'legion',
  'sea',
  'swarm',
  'a large/great number/quantity',
  'a lot',
  'innumerable',
  'countless',
  'infinite',
  'numberless',
  'unlimited',
  'untold',
  'limitless',
  'unnumbered',
  'immeasurable',
  'multitudinous',
  'numerous',
  'manifold',
  'multiple',
  'legion',
  'several',
  'many',
  'various',
  'sundry',
  'diverse',
  'multifarious',
  'divers',
  'innumerous',
  'unnumberable',
  'various',
  'sundry',
  'manifold',
  'multiple',
  'varied',
  'varying',
  'miscellaneous',
  'assorted',
  'mixed',
  'diversified',
  'divergent',
  'variegated',
  'heterogeneous',
  'different',
  'differing',
  'distinct',
  'unlike',
  'dissimilar',
  'distinctive',
  'contrasting',
  'conflicting',
  'divers',
  'legion',
  'contrastive',
  'many and various',
  'similar',
  'uniform',
];