export const definitions = [
    '"the Arthurian mythos"',
    '"the rhetoric and mythos of science create the comforting image of linear progression toward truth"',
]
export const synonyms = [
    'folk tale',
    'story',
    'legend',
    'tale',
    'fable',
    'saga',
    'allegory',
    'parable',
    'tradition',
    'lore',
    'folklore',
    'folk story',
    'mythus',
    'storyline',
    'story',
    'scenario',
    'action',
    'thread',
    'diegesis',
    'chain of events',
]