export const definitions = [
    '"Olympic drug tests nabbed another athlete yesterday"',
    '"Dan nabbed the seat next to mine"',
]
export const synonyms = [
    'seize',
    'grab',
    'snatch',
    'lay (one\'s) hands on',
    'get one\'s hands on',
    'grasp',
    'grip',
    'clutch',
    'clench',
    'pluck',
    'hold',
    'receive',
    'acquire',
    'get',
    'intercept',
    'seize/grab/take hold of',
    'fasten on',
    'hang onto',
    'come into possession of',
    'drop',
    'purloin',
    'thieve',
    'take',
    'loot',
    'pilfer',
    'run off with',
    'appropriate',
    'abstract',
    'carry off',
    'shoplift',
    'embezzle',
    'misappropriate',
    'crib',
    'hook',
    'peculate',
    'defalcate',
    'take for oneself',
    'help oneself to',
    'abscond with',
    'have one\'s fingers / hand in the till',
    'clifty',
]