export const definitions = [
  '"he made his way down the narrow road"',
  '"his ability to get good results within narrow constraints of money and manpower"',
  '"companies fail through their narrow view of what contributes to profit"',
  '"a narrow definition of family can neglect the experiences of many people"',
  '"the home team just hung on for a narrow victory"',
  '"the road narrowed and crossed an old bridge"',
  '"the embankment was built to narrow the river"',
  '"she narrowed her eyes at him suspiciously"',
  '"Jake\'s eyes had narrowed to pinpoints"',
  '"their trade surplus narrowed to $70 million in January"',
  '"New England had narrowed Denver\'s lead from 13 points to 4"',
  '"a basaltic fang rising from the narrows of the Upper Missouri"',
];
export const synonyms = [
  'small',
  'tapered',
  'tapering',
  'narrowing',
  'strait',
  'slender',
  'slim',
  'lean',
  'slight',
  'spare',
  'attenuated',
  'thin',
  'attenuate',
  'confined',
  'cramped',
  'tight',
  'close',
  'restricted',
  'limited',
  'constricted',
  'confining',
  'pinched',
  'squeezed',
  'meager',
  'scant',
  'scanty',
  'incommodious',
  'exiguous',
  'narrow-gauged',
  'incapacious',
  'wide',
  'broad',
  'spacious',
  'limited',
  'restricted',
  'circumscribed',
  'straitened',
  'small',
  'inadequate',
  'insufficient',
  'deficient',
  'lacking',
  'wanting',
  'select',
  'exclusive',
  'wide',
  'broad',
  'narrow-minded',
  'intolerant',
  'illiberal',
  'reactionary',
  'conservative',
  'ultra-conservative',
  'conventional',
  'parochial',
  'provincial',
  'insular',
  'small-town',
  'localist',
  'small-minded',
  'petty',
  'close-minded',
  'short-sighted',
  'myopic',
  'blinkered',
  'inward-looking',
  'hidebound',
  'dyed-in-the-wool',
  'diehard',
  'limited',
  'restricted',
  'inflexible',
  'dogmatic',
  'rigid',
  'entrenched',
  'prejudiced',
  'bigoted',
  'biased',
  'partisan',
  'sectarian',
  'discriminatory',
  'prudish',
  'priggish',
  'strait-laced',
  'stuffy',
  'puritanical',
  'moralistic',
  'prim',
  'starchy',
  'prissy',
  'shockable',
  'racist',
  'racialist',
  'chauvinistic',
  'chauvinist',
  'sexist',
  'nationalistic',
  'parish-pump',
  'blimpish',
  'borné',
  'claustral',
  'petty-minded',
  'broad-minded',
  'tolerant',
  'strict',
  'literal',
  'exact',
  'precise',
  'close',
  'faithful',
  'true',
  'marginal',
  'lucky',
  'taper',
  'diminish',
  'decrease',
  'reduce',
  'contract',
  'shrink',
  'constrict',
  'straiten',
  'get/become/make narrower',
  'get/become/make smaller',
  'constrict',
  'contract',
  'brace',
  'draw in',
  'compress',
  'screw up',
  'pucker',
  'purse',
  'squinch',
  'become narrow/narrower',
  'become tight/tighter',
  'become pinched',
  'constringe',
  'relax',
  'reduce',
  'curtail',
  'cut',
  'cut down',
  'cut back',
  'prune',
  'lessen',
  'lower',
  'decrease',
  'shrink',
  'contract',
  'constrict',
  'restrict',
  'limit',
  'curb',
  'check',
  'blunt',
  'weaken',
  'erode',
  'undermine',
  'sap',
  'pare down',
  'make weaker',
  'increase',
  'strait(s)',
  'sound',
  'neck',
  'channel',
  'waterway',
  'passage',
  'sea passage',
];