export const definitions = [
    '"the world\'s leading industrialized nations"',
    '"he addressed the nation"',
    '"a massive earthquake struck the island nation"',
    '"collaboration between the two nations"',
]
export const synonyms = [
    'country',
    'state',
    'land',
    'nation state',
    'kingdom',
    'empire',
    'republic',
    'confederation',
    'federation',
    'commonwealth',
    'power',
    'superpower',
    'polity',
    'domain',
    'fatherland',
    'motherland',
    'people',
    'race',
    'civilization',
    'tribe',
    'society',
    'community',
    'population',
    'body politic',
    'populace',
    'public',
    'realm',
    'res publica',
    'sovereign state',
    'ethnic group',
    'ethnic minority',
    'tribe',
    'clan',
    'race',
    'ethnos',
]