export const definitions = [
  '"a native of Montreal"',
  '"an eighteen-year-old Brooklyn native"',
  '"New York in the summer was too hot even for the natives"',
  '"the marigold is a native of southern Europe"',
  '"he\'s a native New Yorker"',
  '"her native country"',
  '"a ceremonial native dance from Fiji"',
  '"these plants are native to North America"',
  '"America\'s native black bear"',
  '"some last vestige of native wit prompted Guy to say nothing"',
  '"a jealousy and rage native to him"',
];
export const synonyms = [
  'inhabitant',
  'resident',
  'local',
  'citizen',
  'national',
  'dweller',
  'aborigine',
  'autochthon',
  'indigene',
  'foreigner',
  'outsider',
  'alien',
  'mother',
  'vernacular',
  'indigenous',
  'original',
  'earliest',
  'first',
  'aboriginal',
  'initial',
  'ancient',
  'primeval',
  'primordial',
  'autochthonous',
  'autochthonic',
  'immigrant',
  'domestic',
  'homegrown',
  'homemade',
  'home',
  'local',
  'indigenous',
  'endemic',
  'imported',
  'innate',
  'inherent',
  'inborn',
  'intrinsic',
  'instinctive',
  'instinctual',
  'intuitive',
  'natural',
  'natural-born',
  'deep-seated',
  'deep-rooted',
  'hereditary',
  'inherited',
  'natal',
  'congenital',
  'bred in the bone',
  'inbred',
  'ingrained',
  'built-in',
  'connate',
  'connatural',
  'in the blood',
  'in the family',
  'acquired',
  'learned',
];