export const definitions = [
    '"a wave of nausea engulfed him"',
    '"intended to induce a feeling of nostalgia, it only induces in me a feeling of nausea"',
]
export const synonyms = [
    'sickness',
    'biliousness',
    'queasiness',
    'vomiting',
    'retching',
    'gagging',
    'seasickness',
    'carsickness',
    'airsickness',
    'motion sickness',
    'morning sickness',
    'altitude sickness',
    'qualms',
    'travel-sickness',
    'disgust',
    'revulsion',
    'repugnance',
    'repulsion',
    'distaste',
    'aversion',
    'loathing',
    'abhorrence',
    'detestation',
    'odium',
    'disrelish',
]