export const definitions = [
  '"David was nearly asleep"',
  '"a rise of nearly 25 percent"',
  '"in the absence of anyone more nearly related, I had been designated next of kin"',
];
export const synonyms = [
  'just about',
  'about',
  'more or less',
  'practically',
  'virtually',
  'all but',
  'as good as',
  'next to',
  'close to',
  'near',
  'to all intents and purposes',
  'approaching',
  'nearing',
  'roughly',
  'approximately',
  'not quite',
  'well-nigh',
  'nigh on',
  'not far from',
  'not far off',
  'bordering on',
  'verging on',
];