export const definitions = [
  '"a big house in the near distance"',
  '"I was fifteen miles from the nearest town"',
  '"the conflict is unlikely to be resolved in the near future"',
  '"walking in these shoes is the nearest thing to floating on air"',
  '"his state of near despair"',
  '"a near disaster"',
  '"the loss of a child or other near relative"',
  '"the near right-hand end window of the trailer"',
];
export const synonyms = [
  'close',
  'nearby',
  'at hand',
  'within reach',
  'accessible',
  'handy',
  'convenient',
  'local',
  'neighboring',
  'adjacent',
  'next-door',
  'adjoining',
  'bordering',
  'abutting',
  'contiguous',
  'proximate',
  'not far off/away',
  'close/near at hand',
  'a stone\'s throw away',
  'within range',
  'far',
  'imminent',
  'forthcoming',
  'in the offing',
  'at hand',
  'approaching',
  'impending',
  'upcoming',
  'coming',
  'looming',
  'close/near at hand',
  '(just) around the corner',
  'distant',
  'remote',
  'narrow',
  'close',
  'by a hair\'s breadth',
  'close',
  'related',
  'connected',
  'closely related',
  'distant',
  'miserly',
  'close-fisted',
  'penny-pinching',
  'cheeseparing',
  'ungenerous',
  'penurious',
  'illiberal',
  'close',
  'grasping',
  'Scroogelike',
  'stinting',
  'sparing',
  'frugal',
  'mean',
];