export const definitions = [
    '"the books had been stacked up in neat piles"',
    '"her daughter was always neat and clean"',
    '"Alan noted down the orders in his neat, precise script"',
    '"Howard\'s neat, precise tackling"',
    '"this neat division does not take into account a host of associated factors"',
    '"he drank neat Scotch"',
    '"it was really neat seeing the city"',
]
export const synonyms = [
    'tidy',
    'orderly',
    'well ordered',
    'well kept',
    'immaculate',
    'spick and span',
    'uncluttered',
    'straight',
    'trim',
    'spruce',
    'tricksy',
    'neat and tidy',
    'as neat as a new pin',
    'in (good) order',
    'shipshape (and Bristol fashion)',
    'in apple-pie order',
    'disorderly',
    'untidy',
    'smart',
    'spruce',
    'dapper',
    'trim',
    'well groomed',
    'besuited',
    'organized',
    'tidy',
    'methodical',
    'fastidious',
    'trig',
    'well turned out',
    'well organized',
    'as if one had just stepped out of a bandbox',
    'shabby',
    'well formed',
    'regular',
    'precise',
    'crisp',
    'clean-cut',
    'elegant',
    'well proportioned',
    'simple',
    'unadorned',
    'unornamented',
    'skillful',
    'deft',
    'dexterous',
    'adroit',
    'adept',
    'expert',
    'practiced',
    'accurate',
    'precise',
    'nimble',
    'agile',
    'graceful',
    'stylish',
    'clever',
    'ingenious',
    'inventive',
    'resourceful',
    'good',
    'apt',
    'efficient',
    'slick',
    'clumsy',
    'undiluted',
    'straight',
    'unmixed',
    'unadulterated',
    'pure',
    'uncut',
    'unblended',
    'excellent',
    'superb',
    'outstanding',
    'magnificent',
    'exceptional',
    'marvelous',
    'wonderful',
    'sublime',
    'perfect',
    'eminent',
    'preeminent',
    'matchless',
    'peerless',
    'supreme',
    'first-rate',
    'first-class',
    'superior',
    'superlative',
    'splendid',
    'admirable',
    'worthy',
    'sterling',
    'fine',
    'very good',
    'of high quality',
    'of the highest quality',
    'of the highest standard',
    'applaudable',
    'poor',
    'inferior',
]