export const definitions = [
    '"she is wearing a silk scarf around her neck"',
    '"the neck muscles"',
    '"her dress had three buttons at the neck undone"',
    '"a polo neck"',
    '"neck of lamb made an excellent stew"',
    '"he\'ll be stuck with a loan around his neck"',
    '"he seized the neck of the whiskey bottle"',
    '"the neck of the womb, usually called the cervix"',
    '"the colt won the 122nd running of the Midsummer Derby by a neck"',
    '"we started necking on the sofa"',
    '"after necking some beers, we left the bar"',
    '"the nylon filament necks down to a fraction of its original diameter"',
]
export const synonyms = [
    'nape',
    'scruff',
    'cervix',
    'scrag',
    'halse',
    'strait(s)',
    'sound',
    'arm',
    'narrows',
    'passage',
    'waterway',
    'sea passage',
    'stretch of water',
    'kiss',
    'caress',
    'pet',
    'spoon',
    'swallow',
    'quaff',
    'swill',
    'guzzle',
    'sup',
    'imbibe',
    'sip',
    'consume',
    'take',
    'drain',
    'toss off',
    'ingurgitate',
    'gulp down',
    'partake of',
]