export const definitions = [
  '"alcohol negates the effects of the drug"',
  '"negating the political nature of education"',
];
export const synonyms = [
  'invalidate',
  'nullify',
  'neutralize',
  'undo',
  'reverse',
  'annul',
  'void',
  'revoke',
  'rescind',
  'abrogate',
  'repeal',
  'retract',
  'countermand',
  'overrule',
  'overturn',
  'avoid',
  'render null and void',
  'render invalid',
  'make ineffective',
  'cancel (out)',
  'confirm',
  'support',
  'validate',
  'deny',
  'dispute',
  'contradict',
  'refute',
  'rebut',
  'discredit',
  'disclaim',
  'reject',
  'repudiate',
  'gainsay',
  'controvert',
  'call into question',
  'confirm',
  'ratify',
];