export const definitions = [
    '"it is a neuter word in Greek"',
    '"soft, languid, sexually neuter types"',
    '"the conquering hero is a neuter"',
    '"a neutered tomcat"',
    '"disarmament negotiations that will neuter their military power"',
]
export const synonyms = [
    'asexual',
    'sexless',
    'unsexed',
    'epicene',
    'castrate',
    'geld',
    'cut',
    'emasculate',
    'spay',
    'sterilize',
    'fix',
    'desex',
    'alter',
    'caponize',
    'ovariectomize',
    'eunuchize',
    'oophorectomize',
]