export const definitions = [
    '"he is now a partner at a leading law firm and feels he has found his niche"',
    '"he is carving out a niche for himself as one of the most talented and reliable character actors around"',
    '"he believes he has found a niche in the market"',
    '"smaller cooperatives must find and develop a niche for their speciality product"',
    '"the niche left vacant by the disappearance of wolves"',
    '"each niche held a shepherdess in Dresden china"',
    '"her bed was tucked into a niche in the wall"',
    '"these elements were niched within the shadowy reaches"',
]
export const synonyms = [
    'calling',
    'vocation',
    'métier',
    'place',
    'function',
    'job',
    'slot',
    'opportunity',
    'ideal position',
    'recess',
    'alcove',
    'nook',
    'cranny',
    'slot',
    'slit',
    'hollow',
    'bay',
    'cavity',
    'cubbyhole',
    'pigeonhole',
    'opening',
    'aperture',
    'mihrab',
]