export const definitions = [
    '"nimrods take to the field after everything from prairie dogs to grizzly bears"',
    '"these days you can\'t even make dinner without some nimrod on the internet having their two cents"',
    '"some nimrod pulled the fire alarm"',
]
export const synonyms = [
    'idiot',
    'halfwit',
    'nincompoop',
    'blockhead',
    'buffoon',
    'dunce',
    'dolt',
    'ignoramus',
    'cretin',
    'imbecile',
    'dullard',
    'moron',
    'simpleton',
    'clod',
    'tomfool',
    'noddy',
    'loggerhead',
    'spoony',
    'mooncalf',
    'clodpole',
]