export const definitions = [
    '"I was force-fed vegetables as a nipper"',
    '"using a pair of nippers you can chip away at the tiles"',
    '"mosquitoes must be some of the most voracious nippers ever created"',
]
export const synonyms = [
    'child',
    'youngster',
    'baby',
    'toddler',
    'infant',
    'minor',
    'juvenile',
    'adolescent',
    'teenager',
    'youth',
    'stripling',
    'offspring',
    'bairn',
    'wean',
    'pickney',
    'ankle-biter',
    'babe',
    'little one',
    'young one',
    'boy/girl',
    'young person',
    'son/daughter',
    'pincer',
    'chela',
]