export const definitions = [
]
export const synonyms = [
    'difficulty',
    'issue',
    'trouble',
    'worry',
    'complication',
    'mess',
    'muddle',
    'mix-up',
    'snag',
    'hitch',
    'drawback',
    'stumbling block',
    'obstacle',
    'hurdle',
    'hiccup',
    'setback',
    'catch',
    'catch-22',
    'quandary',
    'the rub',
    'predicament',
    'plight',
    'Gordian knot',
    'misfortune',
    'mishap',
    'misadventure',
    'difficult situation',
    'vexed question',
    'can of worms',
    'hornets\' nest',
]