export const definitions = [
    '"people were nudging each other and pointing at me"',
    '"the canoe nudged a bank of reeds"',
    '"we have to nudge the politicians in the right direction"',
    '"both men were nudging fifty"',
]
export const synonyms = [
    'poke',
    'elbow',
    'dig',
    'prod',
    'jog',
    'jab',
    'butt',
    'touch',
    'run into',
    'bump (against)',
    'push (against)',
    'prompt',
    'encourage',
    'coax',
    'stimulate',
    'prod',
    'jog',
    'approach',
    'near',
    'come/get close to',
    'be verging on',
    'border on',
]