export const definitions = [
    '"doctors are obliged by law to keep patients alive while there is a chance of recovery"',
    '"oblige me by not being sorry for yourself"',
    '"tell me what you want to know and I\'ll see if I can oblige"',
    '"if you can give me a few minutes of your time I\'ll be much obliged"',
    '"my father had obliged me to the improvement of my stock"',
]
export const synonyms = [
    'require',
    'compel',
    'bind',
    'make',
    'constrain',
    'obligate',
    'force',
    'impel',
    'coerce',
    'pressure',
    'pressurize',
    'put under an obligation',
    'leave someone no option',
    'do someone a favor',
    'accommodate',
    'indulge',
    'gratify',
    'help',
    'assist',
    'serve',
    'humor',
    'do someone a kindness',
    'do someone a service',
    'gratify the wishes of',
    'meet the wants/needs of',
    'put oneself out for',
    'be kind enough to',
    'thankful',
    'grateful',
    'appreciative',
    'beholden',
    'indebted',
    'obligated',
    'thank you',
    'thanks',
    'in someone\'s debt',
    'under an obligation',
    'many thanks',
    'thanks a lot',
    'thanks very much',
    'thank you kindly',
]