export const definitions = [
    '"he was obsessed with the theme of death"',
    '"he became completely obsessed about germs"',
    '"her husband, who is obsessing about the wrong she has done him"',
]
export const synonyms = [
    'preoccupy',
    'possess',
    'haunt',
    'consume',
    'plague',
    'torment',
    'hound',
    'bedevil',
    'take over',
    'engross',
    'eat up',
    'grip',
    'dominate',
    'rule',
    'control',
    'beset',
    'monopolize',
    'be uppermost in someone\'s mind',
    'prey on some\'s \'s mind',
    'prey on',
    'take control of',
    'become an obsession with',
    'have a hold on',
    'have a grip on',
    'be fixated',
    'be preoccupied',
    'be infatuated',
    'be possessed',
    'be haunted',
    'be consumed',
    'be plagued',
    'be tormented',
    'be bedeviled',
    'be eaten up',
    'be gripped',
    'be in the grip of',
    'be dominated',
    'be beset',
]