export const definitions = [
    '"an opportunity to obtain advanced degrees"',
    '"the price of silver fell to that obtaining elsewhere in the ancient world"',
]
export const synonyms = [
    'get',
    'acquire',
    'come by',
    'secure',
    'procure',
    'pick up',
    'gain',
    'derive',
    'earn',
    'achieve',
    'attain',
    'win',
    'draw',
    'reap',
    'buy',
    'purchase',
    'come into possession of',
    'be given',
    'lose',
    'relinquish',
    'prevail',
    'apply',
    'exist',
    'stand',
    'hold',
    'be the case',
    'be in force',
    'be in use',
    'be established',
    'be customary',
    'be effective',
    'be prevalent',
]