export const definitions = [
  '"the accident occurred at about 3:30 p.m."',
  '"radon occurs naturally in rocks such as granite"',
  '"it occurred to him that he hadn\'t eaten"',
];
export const synonyms = [
  'happen',
  'take place',
  'come about',
  'transpire',
  'materialize',
  'chance',
  'arise',
  'crop up',
  'turn out',
  'fall',
  'come',
  'fall out',
  'pass off',
  'come to pass',
  'befall',
  'betide',
  'hap',
  'eventuate',
  'exist',
  'appear',
  'prevail',
  'turn up',
  'obtain',
  'be found',
  'be present',
  'be met with',
  'present itself',
  'show itself',
  'manifest itself',
  'cross one\'s mind',
  'come to mind',
  'enter one\'s head / mind',
  'spring to mind',
  'come to one',
  'strike one',
  'hit one',
  'dawn on one',
  'suggest itself',
  'present itself',
  'come into one\'s consciousness',
];