export const definitions = [
  '"she was regarded as a bit of an oddity"',
  '"realizing the oddity of the remark, he retracted it"',
];
export const synonyms = [
  'eccentric',
  'crank',
  'misfit',
  'maverick',
  'nonconformist',
  'original',
  'rare bird',
  'rara avis',
  'peculiarity',
  'idiosyncrasy',
  'eccentricity',
  'quirk',
  'irregularity',
  'twist',
  'kink',
  'crotchet',
  'mannerism',
  'fish out of water',
  'square peg in a round hole',
  'round peg in a square hole',
  'conformist',
  'strangeness',
  'peculiarity',
  'oddness',
  'curiousness',
  'weirdness',
  'bizarreness',
  'abnormality',
  'unusualness',
  'eccentricity',
  'queerness',
  'freakishness',
  'unnaturalness',
  'incongruity',
  'incongruousness',
  'outlandishness',
  'extraordinariness',
  'unconventionality',
  'singularity',
  'individuality',
  'anomalousness',
];