export const definitions = [
    '"the complete oeuvre of Mozart"',
    '"an early oeuvre"',
]
export const synonyms = [
    'compositions',
    'works',
    'opus',
    'books',
    'volumes',
    'publications',
    'titles',
    'tomes',
    'papers',
    'articles',
    'essays',
    'work',
    'work of art',
    'achievement',
    'production',
    'opus',
    'invention',
    'handiwork',
    'masterpiece',
    'masterwork',
    'magnum opus',
    'chef-d\'œuvre',
    'pièce de résistance',
    'tour de force',
    'opuscule',
]