export const definitions = [
  '"an office job"',
  '"computers first appeared in offices in the late 1970s"',
  '"a company that has four U.S. and four European offices"',
  '"a ticket office"',
  '"a Post Office"',
  '"a patient walks in to a doctor\'s office"',
  '"the office of attorney general"',
  '"a year ago, when the President took office"',
  '"he was ejected from office in 1988"',
  '"the Foreign Office"',
  '"rescued through the good offices of the Italian Ambassador, he was returned safely to England"',
  '"the offices of a nurse"',
  '"the noon office"',
];
export const synonyms = [
  'workplace',
  'workroom',
  'studio',
  'headquarters',
  'base',
  'center',
  'place of business',
  'place of work',
  'branch',
  'division',
  'section',
  'bureau',
  'department',
  'agency',
  'post',
  'position',
  'appointment',
  'job',
  'day job',
  'occupation',
  'role',
  'place',
  'situation',
  'station',
  'function',
  'capacity',
  'assistance',
  'help',
  'aid',
  'services',
  'intervention',
  'intercession',
  'mediation',
  'intermediation',
  'agency',
  'support',
  'backing',
  'patronage',
  'aegis',
  'auspices',
  'advocacy',
  'chore',
  'duty',
  'job',
  'task',
  'obligation',
  'assignment',
  'service',
  'responsibility',
  'charge',
  'commission',
  'work',
  'employment',
];