export const definitions = [
  '"an offset against taxable profits"',
  '"these wheels have an offset of four inches"',
  '"offset adjustment circuits"',
  '"a present of tulip bulbs, offsets, and seeds for his garden"',
  '"allow for any bend you need including offsets for connecting the downpipe"',
  '"they produced banknotes by offset"',
  '"offset printing"',
  '"the deficit has been more than offset by capital inflows"',
  '"several places where the ridge was offset at right angles to its length"',
];
export const synonyms = [
  'counterbalance',
  'balance',
  'cancel',
  'counteract',
  'counterpoise',
  'countervail',
  'equalize',
  'neutralize',
  'nullify',
  'make up for',
  'make good',
  'redeem',
  'indemnify',
  'redress',
  'balance out',
  'cancel out',
  'even out/up',
  'compensate for',
  'atone for',
  'make amends for',
  'make restitution for',
  'equilibrize',
];