export const definitions = [
    '"the old man lay propped up on cushions"',
    '"the old quarter of the town"',
    '"he gave his old clothes away"',
    '"I wish she\'d shut up—it\'s getting old"',
    '"valuation under the old rating system was inexact"',
    '"I was going to try to get my old job back"',
    '"we greet each other like old friends"',
    '"I get sick of the same old routine"',
    '"he was fourteen years old"',
    '"a seven-month-old baby"',
    '"how old are you?"',
    '"a nineteen-year-old"',
    '"it gets the old adrenaline going"',
    '"\"Good old Mom,\" she said"',
]
export const synonyms = [
    'elderly',
    'mature',
    'aged',
    'older',
    'senior',
    'long in the tooth',
    'gray',
    'grizzled',
    'hoary',
    'ancient',
    'decrepit',
    'doddering',
    'doddery',
    'ripe',
    'senescent',
    'senile',
    'superannuated',
    'venerable',
    'septuagenarian',
    'octogenarian',
    'nonagenarian',
    'centenarian',
    'advanced in years',
    'up in years',
    'getting on',
    'in one\'s dotage',
    'gray-haired',
    'gray-bearded',
    'past one\'s prime',
    'not as young as one was',
    'not long for this world',
    'longevous',
    'young',
    'historic',
    'antiquated',
    'dilapidated',
    'broken-down',
    'run down',
    'tumbledown',
    'ramshackle',
    'decaying',
    'crumbling',
    'disintegrating',
    'new',
    'modern',
    'worn',
    'worn out',
    'shabby',
    'threadbare',
    'holey',
    'torn',
    'frayed',
    'patched',
    'tattered',
    'moth-eaten',
    'ragged',
    'yellowed',
    'old-fashioned',
    'out of date',
    'outmoded',
    'castoff',
    'hand-me-down',
    'démodé',
    'antique',
    'veteran',
    'vintage',
    'new',
    'fashionable',
    'modern',
    'bygone',
    'past',
    'former',
    'olden',
    'of old',
    'remote',
    'previous',
    'early',
    'earlier',
    'earliest',
    'medieval',
    'ancient',
    'classical',
    'primeval',
    'primordial',
    'prehistoric',
    'antediluvian',
    'forgotten',
    'immemorial',
    'modern',
    'recent',
    'former',
    'previous',
    'ex-',
    'one-time',
    'sometime',
    'erstwhile',
    'once',
    'then',
    'lapsed',
    'quondam',
    'new',
    'hackneyed',
    'hack',
    'banal',
    'trite',
    'overused',
    'overworked',
    'cut and dried',
    'tired',
    'worn out',
    'timeworn',
    'stale',
    'stereotyped',
    'clichéd',
    'platitudinous',
    'unoriginal',
    'derivative',
    'unimaginative',
    'commonplace',
    'common',
    'pedestrian',
    'prosaic',
    'run-of-the-mill',
    'stock',
    'conventional',
    'out of date',
    'outdated',
    'old-fashioned',
    'outmoded',
    'archaic',
    'obsolete',
    'defunct',
    'extinct',
    'antiquated',
    'antediluvian',
    'superannuated',
    'hoary',
    'passé',
    'time-honored',
    'old-time',
    'long-established',
    'age-old',
    'long-standing',
    'long-lived',
    'enduring',
    'lasting',
    'familiar',
    'customary',
    'established',
    'ritual',
    'ritualistic',
    'habitual',
    'set',
    'fixed',
    'routine',
    'usual',
    'wonted',
    'historic',
    'folk',
    'old-world',
    'ancestral',
    'fresh',
    'innovative',
    'new',
]