export const definitions = [
  '"we were friendly to each other, but there was no bonding"',
  '"family bonding can be accomplished by planning a fishing trip"',
  '"the bonding of metals to non-metals"',
  '"the interactions are stabilized by hydrogen bonding"',
  '"scientific principles such as chemical bonding or the workings of jet propulsion"',
  '"the bonding of the brickwork would have to be altered during construction to allow a window to be inserted"',
  '"they want the introduction of bonding to guarantee that consignments will be properly handled"',
  '"a bonding agent"',
  '"it\'s bonding to sing together"',
  '"these can be bonding times for the whole family"',
  '"press the material to bond the layers together"',
  '"this material will bond well to stainless steel rods"',
  '"the failure to properly bond with their children"',
  '"the team has bonded together well"',
  '"neutral molecules bond to the central atom"',
  '"assets may have to be sold or bonded to provide cash for the payment of this tax"',
];
export const synonyms = [
  'join',
  'connect',
  'fasten',
  'fix',
  'affix',
  'attach',
  'secure',
  'bind',
  'stick',
  'glue',
  'gum',
  'paste',
  'cement',
  'fuse',
  'weld',
  'solder',
];