export const definitions = [
]
export const synonyms = [
    'sorcery',
    'witchcraft',
    'wizardry',
    'necromancy',
    'enchantment',
    'spellworking',
    'incantation',
    'occultism',
    'black magic',
    'devilry',
    'divination',
    'malediction',
    'voodoo',
    'hoodoo',
    'sympathetic magic',
    'white magic',
    'witching',
    'witchery',
    'charm',
    'hex',
    'spell',
    'jinx',
    'mojo',
    'makutu',
    'sortilege',
    'thaumaturgy',
    'theurgy',
    'the supernatural',
    'the occult',
    'the black arts',
]