export const definitions = [
  '"some hogs are just mean and ornery"',
  '"his ornery determination drove him to get back on the court following two injuries"',
];
export const synonyms = [
  'tedious',
  'dull',
  'monotonous',
  'repetitious',
  'repetitive',
  'unrelieved',
  'unvaried',
  'unimaginative',
  'uneventful',
  'characterless',
  'featureless',
  'colorless',
  'lifeless',
  'soulless',
  'passionless',
  'spiritless',
  'insipid',
  'uninteresting',
  'unexciting',
  'uninspiring',
  'unstimulating',
  'unoriginal',
  'derivative',
  'jejune',
  'nondescript',
  'sterile',
  'flat',
  'bland',
  '(plain) vanilla',
  'arid',
  'dry',
  'dry as dust',
  'stale',
  'wishy-washy',
  'gray',
  'anemic',
  'tired',
  'banal',
  'lame',
  'plodding',
  'ponderous',
  'pedestrian',
  'lackluster',
  'stodgy',
  'dreary',
  'mechanical',
  'stiff',
  'leaden',
  'wooden',
  'mind-numbing',
  'wearisome',
  'tiring',
  'tiresome',
  'irksome',
  'trying',
  'frustrating',
  'humdrum',
  'prosaic',
  'mundane',
  'commonplace',
  'workaday',
  'quotidian',
  'unremarkable',
  'routine',
  'run-of-the-mill',
  'normal',
  'usual',
  'ordinary',
  'conventional',
  'suburban',
  'garden variety',
  'lacking variety',
  'lacking variation',
  'lacking excitement',
  'lacking interest',
  'unspirited',
  'soul-destroying',
  'interesting',
];