export const definitions = [
  '"the star said he was ‘very touched’ to receive his medal"',
  '"you have to be a little touched to do my job"',
  '"he leaned back so that only two legs of his chair touched the floor"',
  '"the dog had one paw outstretched, not quite touching the ground"',
  '"he touched a strand of her hair"',
  '"she lowered her head to touch his fingers with her lips"',
  '"for a moment their fingers touched"',
  '"we touched wheels and nearly came off the road"',
  '"I didn\'t play her records or touch any of her stuff"',
  '"I\'ve got friends who\'ll pull strings—nobody will dare touch me"',
  '"the beer by his right hand was hardly touched"',
  '"in three years I haven\'t touched a cent of the money"',
  '"he was good only for the jobs that nobody else would touch"',
  '"a tenth of state companies have been touched by privatization"',
  '"the voice was touched by hysteria"',
  '"a wry smile touched his lips"',
  '"she was touched by her friend\'s loyalty"',
  '"sales touched twenty grand last year"',
  '"there\'s no one who can touch him at lightweight judo"',
];
export const synonyms = [
  'mad',
  'insane',
  'unbalanced',
  'unhinged',
  'deranged',
  'demented',
  'crazed',
  'out of one\'s mind',
  'off \'s \'s head',
  'eccentric',
  'distracted',
  'simple',
  'non compos mentis',
  'mad as a hatter',
  'mad as a March hare',
  'sane',
  'well adjusted',
  'meet',
  'join',
  'connect',
  'adjoin',
  'abut',
  'neighbor',
  'be in contact (with)',
  'come into contact (with)',
  'come together (with)',
  'converge (with)',
  'be contiguous (with)',
  'border (on)',
  'be (up) against',
  'link up (with)',
  'tap',
  'pat',
  'nudge',
  'prod',
  'poke',
  'feel',
  'stroke',
  'rub',
  'brush',
  'graze',
  'fondle',
  'caress',
  'pet',
  'tickle',
  'finger',
  'thumb',
  'handle',
  'press lightly',
  'rub (up) against',
  'brush (up) against',
  'toy with',
  'play about with',
  'fiddle with',
  'put one\'s hand on',
  'lay a hand on',
  'lay a finger on',
  'handle',
  'hold',
  'pick up',
  'move',
  'disturb',
  'harm',
  'use',
  'employ',
  'make use of',
  'access',
  'get (at)',
  'take advantage of',
  'meddle with',
  'play (about/around) with',
  'toy with',
  'fiddle with',
  'interfere with',
  'tamper with',
  'lay a hand on',
  'lay a finger on',
  'put to use',
  'have access to',
  'avail oneself of',
  'taste',
  'consume',
  'eat',
  'drink',
  'take',
  'partake of',
  'refrain from',
  'handle',
  'be associated with',
  'concern oneself with',
  'involve oneself in/with',
  'get involved with/in',
  'have something to do with',
  'have dealings with',
  'deal with',
  'be a party to',
  'affect',
  'concern',
  'involve',
  'have an effect on',
  'have a bearing on',
  'be relevant to',
  'be pertinent to',
  'affected',
  'softened',
  'moved',
  'stirred',
  'swayed',
  'aroused',
  'impressed',
  'influenced',
  'warmed',
  'impassioned',
  'upset',
  'disturbed',
  'distressed',
  'affect',
  'move',
  'stir',
  'arouse',
  'impress',
  'influence',
  'impassion',
  'disturb',
  'melt',
  'soften',
  'make/leave an impression on',
  'have an impact on',
  'have an effect on',
  'make sad',
  'arouse sympathy',
  'unmoved',
  'unimpressed',
  'reach',
  'attain',
  'come to',
  'make',
  'get up to',
  'get down to',
  'arrive at',
  'rise to',
  'soar to',
  'sink to',
  'plummet to',
  'dive to',
  'equal',
  'match',
  'parallel',
  'rival',
  'approach',
  'better',
  'beat',
  'compare with',
  'be on a par with',
  'be a match for',
  'be in the same class as',
  'be in the same league as',
  'be on an equal footing with',
  'come near',
  'get near',
  'come up to',
  'come/get close to',
  'measure up to/against',
];