export const definitions = [
    '"they would go on family outings to the movies"',
    '"her daily outing to the stores"',
    '"her first screen outing in three years"',
    '"LGBT organizations strongly condemn the outing of a transgender person before they are ready to tell their own story"',
    '"the author was famously outed as a spy"',
    '"his true identity is outed in front of the others"',
    '"they had outed Asquith quite easily"',
    '"out the lamp when you\'re ready"',
    '"the truth will out"',
]
export const synonyms = [
    'trip',
    'excursion',
    'jaunt',
    'expedition',
    'day trip',
    'tour',
    'airing',
    'drive',
    'ride',
    'run',
    'turn',
    'cruise',
    'sally',
    'pleasure trip',
    'day out',
    'mystery tour',
    'excursion',
    'jaunt',
    'visit',
    'tour',
    'journey',
    'expedition',
    'voyage',
    'transfer',
    'drive',
    'run',
    'pilgrimage',
    'holiday',
    'peregrination',
    'day out',
    'minibreak',
    'exposure',
    'unmasking',
    'uncovering',
    'revelation',
    'exposé',
    'uncover',
    'reveal',
    'show',
    'display',
    'exhibit',
    'disclose',
    'manifest',
    'unveil',
    'unmask',
    'discover',
    'bring to light',
    'unearth',
    'let out',
    'divulge',
    'denounce',
    'condemn',
    'detect',
    'find out',
    'catch out',
    'smoke out',
    'betray',
    'give away',
    'bring into the open',
    'make known',
    'make obvious',
    'throw out',
    'bar',
    'ban',
    'debar',
    'drum out',
    'turn out',
    'oust',
    'remove',
    'get rid of',
    'reject',
    'dismiss',
    'blackball',
    'blacklist',
    'cashier',
    'thrust out',
    'push out',
    'admit',
    'welcome',
]