export const definitions = [
    '"a fast-food outlet"',
    '"the indoor markets in Moscow were an outlet for surplus collective-farm produce"',
    '"an outlet store"',
    '"witnesses told local media outlets that the woman fell"',
    '"the outlet reported iPad production could start as early as this year"',
    '"writing became the main outlet for his energies"',
]
export const synonyms = [
    'vent',
    'way out',
    'exit',
    'egress',
    'outfall',
    'opening',
    'channel',
    'trench',
    'culvert',
    'cut',
    'conduit',
    'ditch',
    'mouth',
    'valve',
    'safety valve',
    'blowoff',
    'blowhole',
    'orifice',
    'pore',
    'duct',
    'vent hole',
    'store',
    'reseller',
    'cash and carry',
    'boutique',
    'salon',
    'parlor',
    'establishment',
    'emporium',
    'department store',
    'supermarket',
    'hypermarket',
    'superstore',
    'warehouse club',
    'warehouse',
    'factory outlet',
    'chain store',
    'mall',
    'shopping mall',
    'shopping center',
    'megastore',
    'bargain basement',
    'concession',
    'market',
    'mart',
    'stall',
    'stand',
    'booth',
    'counter',
    'trading post',
    'lockup',
    'minimart',
    'convenience store',
    'mini-mall',
    'retail store',
    'retail outlet',
    'retail center',
    'multiple (shop/store)',
    'market',
    'marketplace',
    'shop',
    'store',
    'retail outlet',
    'selling place',
    'release',
    'safety valve',
    'vent',
    'avenue',
    'channel',
    'means of expression',
    'means of release',
    'release mechanism',
    'way of harnessing',
]