export const definitions = [
    '"bands of outlaws held up trains"',
    '"the outlaw Ned Kelly"',
    '"Maryland outlawed cheap small-caliber pistols"',
    '"he lost the estate in 1626, having been outlawed for nonpayment of debts"',
]
export const synonyms = [
    'fugitive',
    'outcast',
    'exile',
    'pariah',
    'bandit',
    'desperado',
    'brigand',
    'robber',
    'criminal',
    'black hat',
    'wanted criminal',
    'ban',
    'bar',
    'prohibit',
    'forbid',
    'veto',
    'embargo',
    'boycott',
    'disallow',
    'proscribe',
    'interdict',
    'banish',
    'exile',
    'cast out',
    'exclude',
    'expel',
    'shut out',
    'repudiate',
    'condemn',
    'make illegal',
    'put a price on someone\'s head',
    'permit',
    'allow',
]