export const definitions = [
  '"their one chance was to outrun their pursuers"',
  '"it\'s harder than anyone imagines to outrun destiny"',
  '"his courage outran his prudence"',
];
export const synonyms = [
  'outstrip',
  'outdistance',
  'outpace',
  'leave behind',
  'gain on',
  'overtake',
  'pass',
  'shake off',
  'throw off',
  'lose',
  'run faster than',
  'get (further) ahead of',
  'draw away from',
  'put distance between oneself and one\'s pursuer(s)',
  'widen the gap between oneself and \'s \'s pursuer(s)',
  'evade',
  'elude',
  'dodge',
  'avoid',
  'give someone the slip',
  'shake off',
  'throw off',
  'duck',
  'get rid of',
  'leave behind',
  'outdistance',
  'outstrip',
  'outpace',
  'bilk',
  'escape from',
  'throw off the scent',
  'get ahead of',
];