export const definitions = [
    '"a characteristic arrangement of paired fins"',
    '"she wore a cardigan paired with a matching skirt"',
    '"they bought a rooster to pair with the hen"',
    '"an absent member on one side is to be paired with an absentee on the other"',
    '"you\'ll now be able to pair your watch directly with a set of Bluetooth headphones"',
]
export const synonyms = [
    'corresponding',
    'equivalent',
    'parallel',
    'analogous',
    'coordinating',
    'complementing',
    'complementary',
    'harmonizing',
    'blending',
    'toning',
    'harmonious',
    'twin',
    'coupled',
    'double',
    'duplicate',
    'identical',
    'like',
    'alike',
    'comparable',
    'similar',
    'correlative',
    'congruent',
    'tallying',
    'agreeing',
    'concordant',
    'consonant',
    'the same',
    '(all) of a piece',
    'like (two) peas in a pod',
    'different',
    'clashing',
    'match',
    'put together',
    'couple',
    'twin',
    'partner',
    'marry up',
]