export const definitions = [
    '"he obtained pardon for his sins"',
    '"he offered a full pardon to five convicted men"',
    '"I know Catherine will pardon me"',
    '"he was pardoned for his treason"',
    '"one can be pardoned the suspicion that some of his errors were deliberate"',
    '"\"Pardon?\" I said, cupping a hand to my ear"',
]
export const synonyms = [
    'forgiveness',
    'absolution',
    'remission',
    'clemency',
    'mercy',
    'lenience',
    'leniency',
    'condonation',
    'indulgence',
    'reprieve',
    'amnesty',
    'exoneration',
    'exculpation',
    'release',
    'acquittal',
    'discharge',
    'oblivion',
    'free pardon',
    'general pardon',
    'forgive',
    'absolve',
    'have mercy on',
    'excuse',
    'condone',
    'overlook',
    'remit',
    'be merciful to',
    'deal leniently with',
    'blame',
    'exonerate',
    'acquit',
    'amnesty',
    'exculpate',
    'let off',
    'reprieve',
    'release',
    'free',
    'spare',
    'grant a pardon to',
    'punish',
    'what',
    'eh',
    'I beg your pardon',
    'sorry',
    'excuse me',
    'what did you say',
    'beg pardon',
    'say again',
    'pardon me',
]