export const definitions = [
    '"the parents of the bride"',
    '"his adoptive parents"',
    '"God\'s hand had written in the hearts of our first parents all the rules of good"',
    '"stems will root down, creating a new crown near the parent"',
    '"policy considerations were determined largely by the parent institution"',
    '"all children are special to those who parent them"',
    '"we are losing our intuitive ability to parent"',
]
export const synonyms = [
    'mother',
    'father',
    'surrogate mother',
    'stepparent',
    'stepmother',
    'stepfather',
    'guardian',
    'single parent',
    'co-parent',
    'begetter',
    'procreator',
    'progenitor',
    'genitor',
    'pater',
    'birth/biological parent',
    'adoptive mother/father',
    'foster-parent',
    'foster-mother',
    'foster-father',
    'lone parent',
    'progenitress',
    'progenitrix',
    'ancestor',
    'forefather',
    'forebear',
    'begetter',
    'primogenitor',
    'procreator',
    'stirps',
    'source',
    'origin',
    'genesis',
    'originator',
    'root',
    'fountain',
    'cause',
    'author',
    'architect',
    'precursor',
    'forerunner',
    'predecessor',
    'antecedent',
    'forebear',
    'ancestor',
    'wellspring',
    'radix',
    'bring up',
    'look after',
    'take care of',
    'rear',
    'raise',
    'nurture',
    'be the parent of',
]