export const definitions = [
    '"the movie is a parody of the horror genre"',
    '"his provocative use of parody"',
    '"he seems like a parody of an educated Englishman"',
    '"his specialty was parodying schoolgirl fiction"',
    '"he parodied his friend\'s voice"',
]
export const synonyms = [
    'satire',
    'burlesque',
    'lampoon',
    'pastiche',
    'caricature',
    'takeoff',
    'skit',
    'imitation',
    'mockery',
    'pasquinade',
    'pasticcio',
    'distortion',
    'travesty',
    'caricature',
    'mockery',
    'misrepresentation',
    'perversion',
    'corruption',
    'debasement',
    'poor imitation',
    'apology for',
    'satirize',
    'ridicule',
    'make fun of',
    'lampoon',
    'mock',
    'caricature',
    'imitate',
    'ape',
    'monkey',
    'satirize',
    'burlesque',
    'lampoon',
    'caricature',
    'mimic',
    'imitate',
    'ape',
    'copy',
    'do',
    'make fun of',
    'travesty',
    'take off',
    'do an impression of',
]