export const definitions = [
    '"he took out a patent for an improved steam hammer"',
    '"designs in a wide range of textures featuring super-chic patent, soft suede, or sophisticated nappa"',
    '"he wore black trousers and black patent shoes"',
    '"she was smiling with patent insincerity"',
    '"the patient is usually left with a patent vessel"',
    '"there are a few recorded cases of patent infection in man"',
    '"patent milk powder"',
    '"an invention is not your own until it is patented"',
]
export const synonyms = [
    'copyright',
    'license',
    'right',
    'permit',
    'privilege',
    'charter',
    'franchise',
    'legal protection',
    'performing right',
    'registered trademark',
    'obvious',
    'clear',
    'plain',
    'evident',
    'apparent',
    'manifest',
    'self-evident',
    'distinct',
    'definite',
    'transparent',
    'overt',
    'discernible',
    'visible',
    'conspicuous',
    'blatant',
    'downright',
    'barefaced',
    'flagrant',
    'palpable',
    'glaring',
    'undisguised',
    'unconcealed',
    'unmistakable',
    'unequivocal',
    'unquestionable',
    'undeniable',
    'glaringly obvious',
    'unobtrusive',
    'inconspicuous',
    'proprietary',
    'patented',
    'licensed',
    'protected',
    'branded',
    'brand-name',
    'designer-label',
    'own-brand',
    'own-label',
]