export const definitions = [
    '"we were ordered to investigate on a night patrol"',
    '"a police patrol stopped the man and searched him"',
    '"the policemen were on patrol when they were ordered to investigate the incident"',
    '"a submarine patrol"',
    '"break the Cubs into sixes and Scouts into patrols"',
    '"the garrison had to patrol the streets to maintain order"',
    '"pairs of men were patrolling on each side of the thoroughfare"',
]
export const synonyms = [
    'vigil',
    'guard',
    'watch',
    'monitoring',
    'policing',
    'beat',
    'patrolling',
    'round',
    'reconnoiter',
    'surveillance',
    'survey',
    'examination',
    'beat-pounding',
    'sentry duty',
    'group',
    'crew',
    'gang',
    'team',
    'squad',
    'sentinel',
    'sentry',
    'garrison',
    'defender',
    'detail',
    'scout',
    'task force',
    'escort',
    'convoy',
    'patrolman/patrolwoman',
    'scouting party',
    'guard',
    'police',
    'picket',
    'cover',
    'monitor',
    'defend',
    'safeguard',
    'cruise',
    'pound',
    'prowl',
    'rove',
    'roam',
    'keep guard (on)',
    'keep watch (on)',
    'walk the beat (of)',
    'pound the beat (of)',
    'make the rounds (of)',
    'walk along/around',
    'range (over)',
    'perform sentry duty (on)',
    'stand guard (over)',
    'keep a vigil (on)',
    'keep a lookout (over)',
]