export const definitions = [
  '"a celebrated patron of the arts"',
  '"Charles became a patron of Rubens and van Dyck"',
  '"we surveyed the plushness of the hotel and its sleek, well-dressed patrons"',
];
export const synonyms = [
  'sponsor',
  'backer',
  'financier',
  'subsidizer',
  'underwriter',
  'guarantor',
  'contributor',
  'subscriber',
  'donor',
  'philanthropist',
  'promoter',
  'friend',
  'helper',
  'supporter',
  'upholder',
  'advocate',
  'champion',
  'protector',
  'benefactor/benefactress',
  'Maecenas',
  'customer',
  'client',
  'frequenter',
  'shopper',
  'buyer',
  'purchaser',
  'consumer',
  'diner',
  'user',
  'visitor',
  'guest',
  'clientele',
  'member of the audience/crowd',
];