export const definitions = [
    '"he paid the locals to pick his coffee beans"',
    '"I\'ll pay for your ticket"',
    '"he paid $1,000 to have it built in 1977"',
    '"you will have paid out more in premiums that you received from claims"',
    '"a museum paid him a four-figure sum for it"',
    '"I always prefer to pay all my bills on time"',
    '"bonuses were paid to savers whose policies completed their full term"',
    '"jobs that pay $5 or $6 an hour"',
    '"crime doesn\'t pay"',
    '"it pays to choose varieties carefully"',
    '"they paid for his impatience"',
    '"the destroyer responsible for these atrocities would have to pay with his life"',
    '"\"I\'ll pay you for that,\" he snarled"',
    '"no one paid them any attention"',
    '"she has been prevailed upon to pay us a visit"',
    '"an open groove between the planks had to be payed by running in hot pitch from a special ladle"',
]
export const synonyms = [
    'reward',
    'reimburse',
    'recompense',
    'remunerate',
    'tip',
    'indemnify',
    'finance',
    'endow',
    'support',
    'back',
    'stake',
    'fund',
    'capitalize',
    'subsidize',
    'sponsor',
    'give payment to',
    'settle up with',
    'defray the cost of',
    'settle up for',
    'donate/leave money for',
    'provide finance/capital for',
    'furnish credit for',
    'treat someone to',
    'spend',
    'expend',
    'pay out',
    'lay out',
    'disburse',
    'hand over',
    'remit',
    'render',
    'part with',
    'discharge',
    'settle',
    'pay off',
    'meet',
    'clear',
    'square',
    'defray',
    'honor',
    'satisfy',
    'make good',
    'liquidate',
    'pay in full',
    'yield',
    'pay out',
    'return',
    'produce',
    'bring in',
    'benefit',
    'repay',
    'serve',
    'be profitable',
    'make money',
    'make a profit',
    'be remunerative',
    'make a return',
    'provide a living',
    'be advantageous to',
    'be of advantage to',
    'be of benefit to',
    'be beneficial to',
    'be profitable to',
    'be worthwhile to',
    'suffer',
    'atone',
    'take one\'s medicine',
    'suffer the consequences',
    'be punished',
    'pay a penalty',
    'make atonement',
    'pay the price',
    'get one\'s deserts',
    'bestow',
    'present',
    'grant',
    'give',
    'hand out',
    'extend',
    'offer',
    'proffer',
    'render',
    'afford',
]