export const definitions = [
    '"a peaked cap"',
    '"you do look a little peaked"',
    '"its popularity peaked in the 1940s"',
    '"the rate of increase peaked at 34 percent last autumn"',
    '"she sat all day, peaking and pining, at the fire-side"',
]
export const synonyms = [
    'careworn',
    'tired',
    'drained',
    'drawn',
    'raddled',
    'unwell',
    'unhealthy',
    'sickly',
    'spent',
    'sapped',
    'washed out',
    'rundown',
    'exhausted',
    'gaunt',
    'grim',
    'pinched',
    'peaky',
    'hollow-eyed',
    'pale',
    'wan',
    'gray',
    'ashen',
    'pallid',
    'pasty-faced',
    'sallow',
    'thin',
    'emaciated',
    'wasted',
    'cadaverous',
    'ghastly',
    'ghostlike',
    'deathlike',
    'hollow-cheeked',
    'fresh',
    'healthy',
    'climax',
    'culminate',
    'come to a head',
    'reach its highest point',
    'reach the high point',
    'reach a climax',
    'come to a climax',
    'reach the zenith',
]