export const definitions = [
    '"peasants left the farms to work in industry"',
    '"peasant farmers"',
    '"\"That is a civilized drink, you peasant\""',
]
export const synonyms = [
    'rustic',
    'countryman',
    'countrywoman',
    'farmhand',
    'swain',
    'villein',
    'serf',
    'paysan',
    'muzhik',
    'kulak',
    'campesino',
    'paisano',
    'contadino',
    'fellah',
    'ryot',
    'carl',
    'cottier',
    'kern',
    'hind',
    'agricultural worker',
    'small farmer',
    'son of the soil',
    'lout',
    'boor',
    'oaf',
    'clown',
    'churl',
    'yokel',
    'bumpkin',
    'village idiot',
    'provincial',
    'barbarian',
    'bucolic',
    'country bumpkin',
    'culchie',
    'bosthoon',
    'bogman',
]