export const definitions = [
  '"two geese were pecking at some grain"',
  '"vultures pecked out the calf\'s eyes"',
  '"robins are the worst culprits, pecking holes in every cherry"',
  '"she pecked him on the cheek"',
  '"don\'t peck at your food, eat a whole mouthful"',
  '"defects for a critic to peck at"',
  '"his son Paul was pecking out letters with two fingers on his typewriter"',
  '"part of a wall was pecked down and carted away"',
  '"her father\'s horse had pecked slightly on landing"',
];
export const synonyms = [
  'bite',
  'nip',
  'strike',
  'hit',
  'tap',
  'rap',
  'jab',
  'poke',
  'prick',
  'kiss',
  'plant a kiss',
  'give someone a peck',
  'nibble',
  'pick at',
  'pick over',
  'play with',
  'eat like a bird',
  'take very small bites from',
  'eat listlessly',
  'toy with',
  'show no appetite for',
  'eat sparingly of',
];