export const definitions = [
  '"he peddled art and printing materials around the country"',
  '"he was arrested after trying to peddle guns"',
  '"he criticized his fellow candidate for peddling risky ideas"',
];
export const synonyms = [
  'sell',
  'hawk',
  'tout',
  'vend',
  'carry',
  'stock',
  'offer',
  'market',
  'merchandise',
  'trade',
  'trade in',
  'sell from door to door',
  'offer for sale',
  'deal in',
  'traffic in',
  'advocate',
  'suggest',
  'urge',
  'recommend',
  'champion',
  'preach',
  'present',
  'put forward',
  'advance',
  'offer',
  'introduce',
  'spread',
  'proclaim',
  'propound',
  'promote',
];