export const definitions = [
  '"the door was ajar and she couldn\'t resist peeping in "',
  '"the sun began to peep out"',
  '"a wad of money that was peeping out of his pocket"',
  '"Don peeped on his whistle"',
];
export const synonyms = [
  'spy',
  'peek',
  'glance',
  'peer',
  'keek',
  'look quickly',
  'cast a brief look',
  'take a secret look',
  'take a sly/stealthy look',
  'sneak a look',
  'have a peek',
  'show',
  'make an appearance',
  'emerge',
  'issue',
  'peek',
  'surface',
  'loom',
  'come to light',
  'pop up',
  'appear (slowly/partly)',
  'come into view/sight',
  'put in an appearance',
  'present oneself/itself',
  'become visible',
  'peer out',
  'show one\'s / its face',
  'spring up',
  'cheep',
  'chirp',
  'chirrup',
  'tweet',
  'twitter',
  'chirr',
  'squeak',
];