export const definitions = [
  '"fish food pellets"',
  '"he had also been struck by a number of shotgun pellets"',
  '"owl pellets"',
  '"the business made its name pelleting sugar beet seed"',
  '"pelleted forms of fertilizer"',
  '"the last drops of rain were pelleting the windshield"',
];
export const synonyms = [
  'prill',
  'little ball',
  'little piece',
  'bullet',
  'shot',
  'lead shot',
  'buckshot',
  'excrement',
  'excreta',
  'dropping',
  'feces',
  'dung',
  'stool',
  'dirt',
  'mess',
  'motion',
];