export const definitions = [
]
export const synonyms = [
    'clerk',
    'secretary',
    'copyist',
    'transcriber',
    'amanuensis',
    'recorder',
    'scrivener',
    'writer',
    'record keeper',
    'mallam',
    'writer',
    'wordsmith',
    'novelist',
    'dramatist',
    'playwright',
    'screenwriter',
    'scriptwriter',
    'poet',
    'essayist',
    'biographer',
    'journalist',
    'columnist',
    'reporter',
    'correspondent',
    'librettist',
    'lyricist',
    'songwriter',
    'littérateur',
    'man/woman of letters',
]