export const definitions = [
    '"the porter was the last person to see her"',
    '"she is a person of astonishing energy"',
    '"the entrance fee is $10.00 per person"',
    '"she\'s not a cat person"',
    '"his previous roles in the person of a fallible cop"',
    '"I have publicity photographs on my person at all times"',
    '"chairperson"',
    '"salesperson"',
    '"sportsperson"',
]
export const synonyms = [
    'human being',
    'individual',
    'human',
    'being',
    'soul',
    'mortal',
    'creature',
    'fellow',
    'figure',
    'personage',
    'wight',
    'man/woman',
    'living soul',
    'individual',
    'creature',
    'fellow',
    'man',
    'woman',
    'wight',
    'ego',
    'I',
    'oneself',
    'persona',
    'identity',
    'character',
    'personality',
    'psyche',
    'soul',
    'spirit',
    'mind',
    'intellect',
    'inner man/woman/person',
    'inner self',
    'one\'s innermost feelings',
    '\'s \'s heart of hearts',
    'other',
    'body',
    'self',
    'backside',
]