export const definitions = [
]
export const synonyms = [
    'kind',
    'sort',
    'type',
    'order',
    'class',
    'classification',
    'category',
    'variety',
    'genre',
    'brand',
    'style',
    'species',
    'genus',
    'family',
    'generation',
    'breed',
    'strain',
    'denomination',
    'group',
    'order',
    'class',
    'subclass',
    'genus',
    'species',
    'stock',
    'strain',
    'line',
    'taxon',
    'taxonomic group',
]