export const definitions = [
    '"she hit him in panic"',
    '"he ran to the library in a blind panic"',
    '"he caused an economic panic by his sudden resignation"',
    '"panic selling"',
    '"a workload of constant panics and rush jobs"',
    '"the crowd panicked and stampeded for the exit"',
    '"talk of love panicked her"',
]
export const synonyms = [
    'alarm',
    'anxiety',
    'nervousness',
    'fear',
    'fright',
    'trepidation',
    'dread',
    'terror',
    'horror',
    'agitation',
    'hysteria',
    'consternation',
    'perturbation',
    'dismay',
    'disquiet',
    'apprehension',
    'apprehensiveness',
    'calm',
    'calmness',
    'overreact',
    'take fright',
    'fall apart',
    'frighten',
    'alarm',
    'scare',
    'unnerve',
    'agitate',
    'horrify',
    'terrify',
    'be alarmed',
    'be scared',
    'be nervous',
    'be afraid',
    'become panic-stricken',
    'be filled with fear',
    'be terrified',
    'be agitated',
    'be hysterical',
    'lose one\'s nerve',
    'be perturbed',
    'get overwrought',
    'get worked up',
    'go/fall to pieces',
    'lose control',
    'fill with panic',
    'relax',
]