export const definitions = [
    '"travel by bus from your local pickup point to your hotel"',
    '"curbside pickup"',
    '"most people met through casual pickups"',
    '"signs of a pickup in demand"',
    '"this microphone helps reduce the pickup of background noise"',
    '"six players had started a full-court pickup basketball game"',
]
export const synonyms = [
    'pickup truck',
    'monster truck',
    'utility vehicle/truck',
    'bakkie',
    'improvement',
    'recovery',
    'revival',
    'upturn',
    'upswing',
    'rally',
    'comeback',
    'resurgence',
    'renewal',
    'reinvigoration',
    'advancement',
    'betterment',
    'a turn for the better',
    'slump',
    'downturn',
]