export const definitions = [
  '"forty pickets were arrested"',
  '"the workers walked out, mounting mass pickets at the factory gates"',
  '"a picket of soldiers fired a volley over the coffin"',
  '"a cedar-picket stockade"',
  '"strikers picketed the newspaper\'s main building"',
  '"18, 000 people turned up to picket"',
];
export const synonyms = [
  'striker',
  'demonstrator',
  'protester',
  'objector',
  'picketer',
  'strike picket',
  'flying picket',
  'demonstration',
  'picket line',
  'blockade',
  'boycott',
  'picketing',
  'secondary picketing',
  'watchman',
  'guard',
  'watch',
  'sentry',
  'sentinel',
  'night watchman',
  'scout',
  'vedette',
  'stake',
  'peg',
  'post',
  'paling',
  'upright',
  'stanchion',
  'pier',
  'piling',
  'palisade',
  'blockade',
  'isolate',
  'surround',
  'demonstrate at',
  'form a picket at',
  'man the picket line at',
  'launch a demonstration at',
  'protest at',
  'form a protest group at',
  'cordon off',
];