export const definitions = [
    '"the work has piled up"',
    '"the laundry was piling up"',
    '"we\'re piling up debt at an incredible rate"',
    '"a massive pileup of data"',
]
export const synonyms = [
    'crash',
    'car crash',
    'collision',
    'accident',
    'bump',
    'smash',
    'wreck',
    'multiple crash',
    'multiple collision',
    'car accident',
    'road accident',
    'traffic accident',
    'car smash',
    'RTA (road traffic accident)',
    'accumulation',
    'logjam',
    'pile',
    'heap',
    'mountain',
    'excess',
    'arrears',
]