export const definitions = [
  '"a pillar of smoke"',
  '"he was a pillar of his local community"',
];
export const synonyms = [
  'column',
  'post',
  'pole',
  'support',
  'upright',
  'vertical',
  'baluster',
  'pier',
  'pile',
  'piling',
  'pilaster',
  'stanchion',
  'standard',
  'prop',
  'buttress',
  'rod',
  'shaft',
  'leg',
  'mast',
  'tower',
  'pylon',
  'obelisk',
  'monolith',
  'newel',
  'caryatid',
  'telamon',
  'herm',
  'stalwart',
  'mainstay',
  'strength',
  'bastion',
  'rock',
  'leading light',
  'worthy',
  'backbone',
  'support',
  'upholder',
  'champion',
  'torchbearer',
  'flagbearer',
  'tower of strength',
];