export const definitions = [
    '"a pine potpourri"',
    '"she thinks I am pining away from love"',
    '"I was pining for my boyfriend"',
]
export const synonyms = [
    'languish',
    'decline',
    'weaken',
    'dwindle',
    'wilt',
    'wither',
    'fade',
    'flag',
    'sicken',
    'droop',
    'brood',
    'mope',
    'moon',
    'peak',
    'yearn',
    'long',
    'ache',
    'sigh',
    'hunger',
    'thirst',
    'itch',
    'miss',
    'mourn',
    'lament',
    'bemoan',
    'rue',
    'cry out for',
    'go into a decline',
    'lose strength',
    'waste away',
    'carry a torch',
    'grieve over',
    'cry/weep over',
    'fret about',
    'shed tears for',
    'regret the loss/absence of',
    'hanker for/after',
    'eat one\'s heart out over',
]