export const definitions = [
    '"the pivot of community life was the chapel"',
    '"the sail pivots around the axis of the mast"',
    '"he swung around, pivoting on his heel"',
    '"your escape pivots on my disappearing with you"',
    '"the teams performed exceptionally by quickly pivoting to meet the increased demand from our customers"',
    '"she sold off her equipment and pivoted back to her original model of running classes"',
    '"practice creativity in pivoting your business from its current platforms to new ways of service deliveries"',
    '"Mike had a passion for cooking and pivoted his career into food service"',
]
export const synonyms = [
    'fulcrum',
    'axis',
    'axle',
    'swivel',
    'pin',
    'hub',
    'spindle',
    'hinge',
    'pintle',
    'kingpin',
    'gudgeon',
    'trunnion',
    'central shaft',
    'center',
    'focal point',
    'focus',
    'hub',
    'heart',
    'nucleus',
    'raison d\'être',
    'crux',
    'keystone',
    'cornerstone',
    'linchpin',
    'kingpin',
    'central point',
    'rotate',
    'turn',
    'revolve',
    'spin',
    'swivel',
    'twirl',
    'whirl',
    'wheel',
    'oscillate',
    'depend',
    'hinge',
    'turn',
    'center',
    'hang',
    'rely',
    'rest',
    'be contingent',
    'revolve around',
]