export const definitions = [
];
export const synonyms = [
  'indictment',
  'accusation',
  'denunciation',
  'prosecution',
  'trial',
  'charge',
  'summons',
  'citation',
  'impeachment',
  'bill of indictment',
  'inculpation',
  'acquittal',
  'grumble',
  'complaint',
  'moan',
  'groan',
  'whine',
  'grievance',
  'objection',
  'protest',
  'protestation',
  'cavil',
  'quibble',
];