export const definitions = [
    '"the horizontal plane"',
    '"the planets orbit the sun in roughly the same plane"',
    '"the plane of his forehead"',
    '"everything is connected on the spiritual plane"',
    '"a bird planed down toward the water below"',
    '"a plane crash"',
    '"I had planed into the large air terminal at Los Angeles"',
    '"plane the edges of the wood to a smooth finish"',
    '"high areas can be planed down"',
    '"let us exert our abilities to plane the way for his passage"',
]
export const synonyms = [
    'horizontal',
    'flat surface',
    'level surface',
    'the flat',
    'level',
    'stage',
    'degree',
    'standard',
    'stratum',
    'position',
    'rung',
    'echelon',
    'footing',
    'soar',
    'glide',
    'float',
    'drift',
    'wheel',
    'skim',
    'glide',
    'aircraft',
    'craft',
    'flying machine',
    'aeroplane',
    'airplane',
    'ship',
]