export const definitions = [
    '"he arranged a fishing trip to please his son"',
    '"it pleased him to be seen with someone in the news"',
    '"she was quiet and eager to please"',
    '"this is the first time in ages that I can just please myself"',
    '"feel free to wander around as you please"',
    '"instead of attending the meeting, it pleased him to go off hunting"',
    '"please address letters to the Editor"',
    '"what type of fish is this, please?"',
    '"please, please come home!"',
    '"\"May I call you at home?\" \"Please do.\""',
    '"\"Would you like a drink?\" \"Yes, please.\""',
    '"Rita, please—people are looking"',
    '"You cleaned out the barn in only two hours? Oh, please!"',
]
export const synonyms = [
    'nice',
    'agreeable',
    'pleasant',
    'pleasurable',
    'satisfying',
    'gratifying',
    'welcome',
    'good',
    'acceptable',
    'to one\'s liking',
    'enjoyable',
    'entertaining',
    'amusing',
    'delightful',
    'fine',
    'friendly',
    'amiable',
    'pleasant',
    'agreeable',
    'affable',
    'nice',
    'genial',
    'likable',
    'good-humored',
    'charming',
    'engaging',
    'winning',
    'delightful',
    'delight',
    'charm',
    'amuse',
    'divert',
    'entertain',
    'gladden',
    'cheer up',
    'satisfy',
    'gratify',
    'humor',
    'oblige',
    'content',
    'suit',
    'make happy',
    'give pleasure to',
    'make someone pleased/glad/content',
    'make someone feel good',
    'be agreeable to',
    'displease',
    'annoy',
    'like',
    'want',
    'wish',
    'desire',
    'choose',
    'will',
    'prefer',
    'opt',
    'see/think fit',
    'be inclined',
    'if you please',
    'kindly',
    'pray',
    'prithee',
    'if you wouldn\'t mind',
    'if you would be so good',
    'have the goodness to',
]