export const definitions = [
  '"our daughters whooped as they plunged into the sea"',
  '"a car swerved to avoid a bus and plunged into a ravine"',
  '"overconfident researchers who plunge ahead"',
  '"their fourth-quarter operating profit plunged 25%"',
  '"the ship plunged through the 20-foot seas"',
  '"he plunged his hands into his pockets"',
  '"cover the cucumbers with boiling water and then plunge them into iced water"',
  '"for a moment the scene was illuminated, then it was plunged back into darkness"',
  '"pot up and plunge spring-flowering bulbs"',
  '"we went straight from the sauna to take a cold plunge"',
  '"the bank declared a 76% plunge in its profits"',
];
export const synonyms = [
  'jump',
  'dive',
  'hurl oneself',
  'throw oneself',
  'fling oneself',
  'launch oneself',
  'catapult oneself',
  'cast oneself',
  'pitch oneself',
  'crash',
  'plummet',
  'pitch',
  'drop',
  'fall',
  'tumble',
  'nosedive',
  'crash-dive',
  'descend',
  'fall headlong',
  'take a nosedive',
  'begin',
  'start',
  'commence',
  'undertake',
  'set about',
  'enter on',
  'go into',
  'take up',
  'launch into',
  'turn one\'s hand to',
  'institute',
  'initiate',
  'tackle',
  'venture into',
  'plunge into',
  'engage in',
  'settle down to',
  'plummet',
  'go down',
  'tumble',
  'sink',
  'slump',
  'fall off a cliff',
  'fall steeply/sharply',
  'drop rapidly',
  'lurch',
  'pitch',
  'roll',
  'reel',
  'keel',
  'list',
  'wallow',
  'labor',
  'flounder',
  'pitchpole',
  'toss around',
  'make heavy weather',
  'thrust',
  'stick',
  'ram',
  'drive',
  'jab',
  'stab',
  'push',
  'shove',
  'force',
  'sink',
  'immerse',
  'submerge',
  'sink',
  'dip',
  'dunk',
  'douse',
  'duck',
  'throw',
  'cast',
  'pitch',
  'jump',
  'dive',
  'nosedive',
  'fall',
  'pitch',
  'drop',
  'plummet',
  'descent',
  'tumble',
  'plump',
  'fall',
  'drop',
  'tumble',
  'slump',
];