export const definitions = [
    '"a minus and a plus make another minus"',
    '"knowing the language is a decided plus"',
]
export const synonyms = [
    'advantage',
    'asset',
    'pro',
    'benefit',
    'fringe benefit',
    'bonus',
    'extra',
    'perk',
    'dividend',
    'attraction',
    'beauty',
    'perquisite',
    'good point',
    'plus point',
    'added advantage',
    'additional benefit',
    'added extra',
    'attractive feature',
    'disadvantage',
    'drawback',
    'minus',
]