export const definitions = [
    '"the children were playing outside"',
    '"I want to play Monopoly"',
    '"the boys were playing cops and robbers"',
    '"I play softball and tennis"',
    '"the Red Sox will play two games on Wednesday"',
    '"the team will play France on Wednesday"',
    '"he needs financial backing, but the bank won\'t play"',
    '"he played shortstop"',
    '"was he in an offside position when his teammate played the ball?"',
    '"the manager will want to play the right-handed Curtis"',
    '"he played his queen"',
    '"he didn\'t play the ponies"',
    '"she played Ophelia"',
    '"he was proud to be playing opposite a famous actor"',
    '"the show was one of the best we ever played"',
    '"the skipper played the innocent, but smuggled goods were found on his vessel"',
    '"we heard someone playing a harmonica"',
    '"a pianist who will play for us"',
    '"he taught himself to play the violin"',
    '"they played a violin sonata"',
    '"someone is playing a record—I can hear the drum"',
    '"somewhere within, a harp was playing"',
    '"the bagpipes played them out of the dining room"',
    '"a smile played about her lips"',
    '"a fountain played in the courtyard"',
    '"no fisherman ever played a bonita more carefully or with greater wile"',
]
export const synonyms = [
    'relax',
    'rest',
    'play games',
    'frolic',
    'frisk',
    'gambol',
    'romp',
    'cavort',
    'caper',
    'sport',
    'amuse oneself',
    'entertain oneself',
    'enjoy oneself',
    'have fun',
    'have a good time',
    'be at leisure',
    'occupy oneself',
    'divert oneself',
    'disport oneself',
    'do',
    'take part in',
    'participate in',
    'engage in',
    'be involved in',
    'join in',
    'compete in',
    'do',
    'take part in',
    'participate in',
    'engage in',
    'be involved in',
    'join in',
    'compete in',
    'do',
    'take part in',
    'participate in',
    'engage in',
    'be involved in',
    'join in',
    'compete in',
    'oppose',
    'take on',
    'challenge',
    'rival',
    'compete against',
    'contend against',
    'vie with',
    'cooperate',
    'collaborate',
    'play along',
    'play the game',
    'help',
    'lend a hand',
    'assist',
    'be of assistance',
    'contribute',
    'reciprocate',
    'respond',
    'go along with the plan',
    'show willing',
    'be willing',
    'act',
    'enact',
    'represent',
    'perform',
    'portray',
    'depict',
    'impersonate',
    'execute',
    'render',
    'interpret',
    'personate',
    'act the part of',
    'play the part of',
    'take the role of',
    'appear as',
    'pretend to be',
    'put on',
    'present',
    'produce',
    'give',
    'perform in',
    'act in',
    'play in',
    'take part in',
    'participate in',
    'be involved in',
    'be engaged in',
    'blow',
    'sound',
    'strum',
    'perform on',
    'make music on',
    'dance',
    'flit',
    'dart',
    'ripple',
    'lick',
    'touch',
    'move lightly',
]