export const definitions = [
    '"the muse is a poetic convention"',
    '"a poetic drama"',
    '"the orchestral playing was colorful and poetic"',
]
export const synonyms = [
    'verse',
    'metrical',
    'rhythmical',
    'poetical',
    'lyrical',
    'lyric',
    'elegiac',
    'rhapsodic',
    'Parnassian',
    'in verse',
    'formal',
    'written',
    'dramatic',
    'dignified',
    'solemn',
    'elaborate',
    'ornate',
    'flowery',
    'purple',
    'informal',
    'colloquial',
    'vernacular',
    'expressive',
    'figurative',
    'symbolic',
    'flowery',
    'moving',
    'aesthetic',
    'artistic',
    'tasteful',
    'graceful',
    'elegant',
    'elevated',
    'fine',
    'beautiful',
    'sensitive',
    'imaginative',
    'creative',
]