export const definitions = [
    '"he killed himself with poison"',
    '"strong chemical poisons"',
    '"meanwhile he is spreading his poison over the internet"',
    '"someone had tried to poison me"',
    '"swans are being poisoned by lead from anglers\' lines"',
    '"he claimed the guards had poisoned his food"',
    '"hunters would use the sap of monkshood to poison their spears"',
    '"he was once shot at with poisoned arrows"',
    '"the bombings poisoned the political atmosphere and deepened the social divide"',
]
export const synonyms = [
    'toxin',
    'venom',
    'bane',
    'toxicant',
    'malice',
    'maliciousness',
    'ill will',
    'hate',
    'malevolence',
    'malignity',
    'malignancy',
    'balefulness',
    'embitterment',
    'spite',
    'spitefulness',
    'venom',
    'acrimony',
    'rancor',
    'blight',
    'bane',
    'contagion',
    'cancer',
    'canker',
    'corruption',
    'pollution',
    'embitteredness',
    'acrimoniousness',
    'bad influence',
    'murder',
    'administer poison to',
    'give poison to',
    'contaminate',
    'adulterate',
    'spike',
    'lace',
    'doctor',
    'pollute',
    'taint',
    'foul',
    'befoul',
    'dirty',
    'blight',
    'spoil',
    'put poison in',
    'tamper with',
    'prejudice',
    'bias',
    'jaundice',
    'color',
    'embitter',
    'sour',
    'envenom',
    'warp',
    'corrupt',
    'subvert',
]