export const definitions = [
  '"a portly little man with a bowler hat"',
  '"he was a man of portly presence"',
];
export const synonyms = [
  'stout',
  'plump',
  'fat',
  'overweight',
  'heavy',
  'corpulent',
  'fleshy',
  'paunchy',
  'pot-bellied',
  'beer-bellied',
  'ample',
  'well upholstered',
  'broad in the beam',
  'rotund',
  'roly-poly',
  'round',
  'rounded',
  'stocky',
  'bulky',
  'Falstaffian',
  'pursy',
  'abdominous',
  'of ample build',
  'well padded',
  'slim',
  'thin',
];