export const definitions = [
    '"thrones were potent symbols of authority"',
    '"a potent drug"',
    '"a potent argument"',
    '"a cross potent"',
]
export const synonyms = [
    'powerful',
    'strong',
    'vigorous',
    'mighty',
    'formidable',
    'influential',
    'commanding',
    'dominant',
    'forceful',
    'dynamic',
    'redoubtable',
    'overpowering',
    'overwhelming',
    'puissant',
    'convincing',
    'cogent',
    'compelling',
    'persuasive',
    'effective',
    'effectual',
    'eloquent',
    'impressive',
    'telling',
    'sound',
    'well founded',
    'valid',
    'weighty',
    'authoritative',
    'irresistible',
    'efficacious',
    'intoxicating',
    'heady',
    'hard',
    'stiff',
    'spiritous',
    'weak',
    'impotent',
]