export const definitions = [
  '"her eyes were puffy and full of tears"',
  '"small puffy clouds"',
  '"a puffy blue ski jacket"',
  '"his breath was puffy and fast"',
];
export const synonyms = [
  'swollen',
  'puffed up',
  'distended',
  'enlarged',
  'full',
  'inflated',
  'dilated',
  'bloated',
  'engorged',
  'bulging',
  'baggy',
  'tumid',
  'turgescent',
  'tumescent',
  'tumefied',
  'edematous',
  'ventricose',
];