export const definitions = [
    '"the outcome of the game presaged the coming year"',
    '"lands he could measure, terms and tides presage"',
    '"the fever was a somber presage of his final illness"',
    '"he had a strong presage that he had only a very short time to live"',
]
export const synonyms = [
    'portend',
    'augur',
    'foreshadow',
    'foretell',
    'prophesy',
    'herald',
    'indicate',
    'signal',
    'bode',
    'announce',
    'promise',
    'threaten',
    'point to',
    'mean',
    'signify',
    'spell',
    'denote',
    'add up to',
    'betoken',
    'foretoken',
    'forebode',
    'harbinger',
    'be an omen of',
    'be a sign of',
    'be the harbinger of',
    'be a warning of',
    'give a warning of',
    'warn of',
    'be an indication of',
    'be a presage of',
    'amount to',
    'omen',
    'sign',
    'indication',
    'portent',
    'warning',
    'forewarning',
    'harbinger',
    'foreshadowing',
    'augury',
    'signal',
    'promise',
    'threat',
    'forecast',
    'prediction',
    'prognostication',
    'prophecy',
    'hint',
    'foretoken',
    'auspice',
    'ill omen',
    'straw in the wind',
    'writing on the wall',
    'premonition',
    'foreboding',
    'intuition',
    'feeling',
    'hunch',
    'suspicion',
    'inkling',
    'idea',
    'sixth sense',
    'misgiving',
    'worry',
    'anxiety',
    'apprehension',
    'apprehensiveness',
    'fear',
    'dread',
    'sneaking suspicion',
    'feeling in one\'s bones',
    'funny feeling',
    'vague feeling',
]