export const definitions = [
  '"the kestrel pounced on its prey"',
  '"he was easy prey for the two con men"',
  '"small birds that prey on insect pests"',
  '"this is a mean type of theft by ruthless people preying on the elderly"',
  '"the problem had begun to prey on my mind"',
];
export const synonyms = [
  'quarry',
  'game',
  'kill',
  'predator',
  'hunter',
  'victim',
  'target',
  'dupe',
  'fool',
  'innocent',
  'gull',
  'hunt',
  'catch',
  'seize',
  'eat',
  'devour',
  'feed on',
  'live on',
  'live off',
  'exploit',
  'victimize',
  'molest',
  'pick on',
  'intimidate',
  'harass',
  'hound',
  'take advantage of',
  'trick',
  'swindle',
  'cheat',
  'hoodwink',
  'fleece',
  'attack',
  'terrorize',
  'blackmail',
  'bleed',
  'oppress',
  'weigh on',
  'burden',
  'trouble',
  'worry',
  'beset',
  'disturb',
  'depress',
  'distress',
  'haunt',
  'nag',
  'torment',
  'plague',
  'obsess',
  'take over',
  'weigh heavily on',
  'lie heavy on',
  'be a burden on/to',
  'hang over',
  'gnaw at',
  'take control of',
];