export const definitions = [
  '"a very prim and proper lady"',
  '"Larry primmed up his mouth"',
];
export const synonyms = [
  'demure',
  'proper',
  'formal',
  'stuffy',
  'strait-laced',
  'prudish',
  'prissy',
  'priggish',
  'puritanical',
  'niminy-piminy',
  'Victorian',
  'old-maid',
  'old-maidish',
  'schoolmarmish',
  'po-faced',
  'square-toed',
  'prim and proper',
  'mimsy',
  'schoolmistressy',
  'governessy',
  'Grundyish',
  'uninhibited',
  'informal',
];