export const definitions = [
    '"he was the prince of a small kingdom that was now part of Pakistan"',
    '"arctic char is a prince among fishes"',
]
export const synonyms = [
    'ruler',
    'sovereign',
    'lord',
    'overlord',
    'dynast',
    'leader',
    'monarch',
    'crowned head',
    'king',
    'emperor',
    'tsar',
    'grand duke',
    'elector',
    'potentate',
    'suzerain',
    'crown prince',
    'princeling',
    'mogul',
    'baron',
    'liege (lord)',
    'emir',
    'sheikh',
    'sultan',
    'maharaja',
    'raja',
    'atheling',
    'royal duke',
    'prince regent',
]