export const definitions = [
  '"the boat is propelled by using a very long paddle"',
  '"a rocket-propelled grenade launcher"',
  '"fear propelled her out of her stillness"',
];
export const synonyms = [
  'move',
  'get moving',
  'drive',
  'throw',
  'thrust',
  'toss',
  'fling',
  'hurl',
  'lob',
  'let fly',
  'launch',
  'pitch',
  'project',
  'send',
  'shoot',
  'push/move forwards',
  'set in motion',
  'spur',
  'drive',
  'prompt',
  'precipitate',
  'catapult',
  'motivate',
  'force',
  'impel',
];