export const definitions = [
    '"he proposed a new nine-point peace plan"',
    '"I proposed that we should retain a 51 percent stake in the company"',
    '"we propose to be away for six months"',
    '"Thomson was proposed as chairman"',
    '"the government put its slim majority to the test by proposing a vote of confidence"',
    '"I have already proposed to Sarah"',
]
export const synonyms = [
    'put forward',
    'suggest',
    'advance',
    'offer',
    'present',
    'move',
    'submit',
    'prefer',
    'file',
    'lodge',
    'initiate',
    'bring',
    'bring forward',
    'come up with',
    'tender',
    'bid',
    'project',
    'recommend',
    'advocate',
    'propound',
    'proffer',
    'posit',
    'table',
    'withdraw',
    'nominate',
    'put forward',
    'put up',
    'name',
    'suggest',
    'submit',
    'present',
    'recommend',
    'withdraw',
    'suggest',
    'recommend',
    'advocate',
    'move',
    'submit',
    'table',
    'ask someone to marry you',
    'make an offer of marriage',
    'offer marriage',
    'ask for someone\'s hand in marriage',
]