export const definitions = [
  '"public concern"',
  '"public affairs"',
  '"a public library"',
  '"his public career was destroyed by tenacious reporters"',
  '"a public figure"',
  '"he wanted a public apology in the Wall Street Journal"',
  '"we should talk somewhere less public"',
  '"public benefits"',
  '"public examination results"',
  '"the library is open to the public"',
  '"the public has made an informed choice"',
  '"the reading public"',
  '"some famous last words to give my public"',
];
export const synonyms = [
  'popular',
  'general',
  'common',
  'communal',
  'collective',
  'shared',
  'joint',
  'universal',
  'widespread',
  'communal',
  'available',
  'free',
  'unrestricted',
  'community',
  'open (to the public)',
  'not private',
  'not exclusive',
  'accessible to all',
  'private',
  'restricted',
  'prominent',
  'well known',
  'leading',
  'important',
  'eminent',
  'preeminent',
  'recognized',
  'distinguished',
  'notable',
  'noteworthy',
  'noted',
  'outstanding',
  'foremost',
  'of mark',
  'illustrious',
  'celebrated',
  'famous',
  'renowned',
  'acclaimed',
  'famed',
  'honored',
  'esteemed',
  'respected',
  'well thought of',
  'influential',
  'prestigious',
  'in the public eye',
  'obscure',
  'unknown',
  'known',
  'overt',
  'plain',
  'obvious',
  'in circulation',
  'published',
  'publicized',
  'exposed',
  'widely known',
  'secret',
  'state',
  'national',
  'federal',
  'government',
  'constitutional',
  'democratic',
  'civic',
  'civil',
  'official',
  'social',
  'municipal',
  'community',
  'local',
  'communal',
  'nationalized',
  'state-owned',
  'urban',
  'metropolitan',
  'private',
  'people',
  'citizens',
  'subjects',
  'electors',
  'electorate',
  'voters',
  'taxpayers',
  'residents',
  'inhabitants',
  'citizenry',
  'population',
  'populace',
  'community',
  'society',
  'country',
  'nation',
  'world',
  'everyone',
  'ratepayers',
  'general public',
  'backing',
  'patronage',
  'audience',
  'circle',
  'coterie',
  'retinue',
  'train',
  'supporters',
  'backers',
  'admirers',
  'fans',
  'adherents',
  'devotees',
  'advocates',
  'patrons',
  'body of support',
  'audience',
  'spectators',
  'concertgoers',
  'followers',
  'following',
  'fans',
  'devotees',
  'aficionados',
  'admirers',
  'patrons',
  'clientele',
  'market',
  'consumers',
  'buyers',
  'customers',
  'readers',
  'theatergoers',
];