export const definitions = [
    '"he pulled them down onto the couch"',
    '"I pulled the door shut behind me"',
    '"the little boy pulled at her skirt"',
    '"the carriage was pulled by four horses"',
    '"the engine warmed up quickly and pulled well"',
    '"he pulled at the oars and the boat moved swiftly through the water"',
    '"she looked at the waves and pulled hard with her oars"',
    '"he pulled himself into the saddle"',
    '"she pulled a handkerchief out of her pocket"',
    '"he pulled on his boots"',
    '"I pulled up some onions"',
    '"the bus was about to pull away"',
    '"the boy pulled ahead and disappeared around the corner"',
    '"she tried to pull away from him"',
    '"tourist attractions that pull in millions of foreign visitors"',
    '"the magazine pulled its trick of producing the right issue at the right time"',
    '"it\'s not every day a young woman pulls a gun on a burglar"',
    '"he pulled a calf muscle in the first half of the game and had to be replaced"',
    '"the gig was pulled at the first sign of difficulty"',
    '"four of the leading eight runners were pulled"',
    '"he pulled the ball every time he hit a grounder"',
    '"he may be their best ever lineman—he can run and pull with the best"',
    '"give the hair a quick pull and it comes out by the roots"',
    '"the Cowboy Collection offers hand-forged iron drawer pulls"',
    '"he unscrewed the cap from the flask and took another pull"',
    '"he took a pull on his cheroot"',
    '"he was taken out of the game with a hamstring pull"',
    '"the pull of the water tore her away"',
    '"the pull of her hometown was a strong one"',
    '"one of the pulls of urban life is the opportunity of finding work"',
    '"they were hamstrung without the political pull of the mayor\'s office"',
]
export const synonyms = [
    'tug',
    'haul',
    'drag',
    'draw',
    'trail',
    'tow',
    'heave',
    'lug',
    'jerk',
    'lever',
    'prise',
    'wrench',
    'wrest',
    'twist',
    'pry',
    'strain at',
    'push',
    'crawl',
    'inch',
    'edge',
    'slither',
    'slide',
    'squirm',
    'wriggle',
    'writhe',
    'worm',
    'move on all fours',
    'move on hands and knees',
    'pull oneself',
    'worm one\'s way',
    'insinuate oneself',
    'pull out',
    'draw out',
    'take out',
    'extract',
    'remove',
    'root out',
    'attract',
    'draw',
    'pull in',
    'bring in',
    'lure',
    'charm',
    'engage',
    'enchant',
    'captivate',
    'bewitch',
    'seduce',
    'entice',
    'tempt',
    'beckon',
    'interest',
    'fascinate',
    'catch the eye of',
    'repel',
    'commit',
    'carry out',
    'perform',
    'execute',
    'do',
    'effect',
    'bring about',
    'accomplish',
    'inflict',
    'wreak',
    'effectuate',
    'be guilty of',
    'be to blame for',
    'be responsible for',
    'take out',
    'draw',
    'draw out',
    'bring out',
    'get out',
    'withdraw',
    'produce',
    'fish out',
    'strain',
    'sprain',
    'turn',
    'wrench',
    'rick',
    'stretch',
    'tear',
    'dislocate',
    'damage',
    'put out of joint',
    'run off',
    'preprint',
    'reprint',
    'proof',
    'copy',
    'reproduce',
    'list',
    'dump',
    'set in print',
    'send to press',
    'tug',
    'haul',
    'jerk',
    'heave',
    'handle',
    'grip',
    'switch',
    'joystick',
    'key',
    'knob',
    'gulp',
    'draft',
    'drink',
    'swallow',
    'mouthful',
    'sip',
    'sup',
    'puff',
    'tug',
    'towing',
    'haul',
    'drawing',
    'drag',
    'trailing',
    'trawl',
    'attraction',
    'lure',
    'allurement',
    'enticement',
    'draw',
    'magnetism',
    'influence',
    'enchantment',
    'magnet',
    'temptation',
    'invitation',
    'fascination',
    'appeal',
    'drawing power',
    'influence',
    'sway',
    'strength',
    'power',
    'authority',
    'say',
    'prestige',
    'standing',
    'weight',
    'leverage',
    'muscle',
    'teeth',
    'page proof',
    'galley proof',
    'galley',
    'slip',
    'revise',
    'trial print',
]