export const definitions = [
  '"one of their bestselling items is a clear plastic raincoat purfled with ribbon"',
];
export const synonyms = [
  'ruffle',
  'flounce',
  'ruff',
  'furbelow',
  'jabot',
  'peplum',
  'flute',
  'ruche',
  'ruching',
  'gather',
  'tuck',
  'fringe',
  'decoration',
  'trimming',
  'ornamentation',
  'adornment',
  'embellishment',
  'border',
  'edging',
  'piping',
  'purfling',
  'rickrack',
  'hem',
  'fringe',
  'frill',
];