export const definitions = [
    '"the purity of our drinking water"',
    '"white is meant to represent purity and innocence"',
]
export const synonyms = [
    'cleanness',
    'clearness',
    'clarity',
    'freshness',
    'wholesomeness',
    'naturalness',
    'healthiness',
    'healthfulness',
    'salubrity',
    'sterility',
    'salubriousness',
    'freedom from adulteration/contamination',
    'lack of pollution',
    'untaintedness',
    'impurity',
    'pollution',
    'virtue',
    'virtuousness',
    'morality',
    'goodness',
    'righteousness',
    'rectitude',
    'saintliness',
    'piety',
    'honor',
    'honesty',
    'integrity',
    'uprightness',
    'decency',
    'worthiness',
    'ethicality',
    'blamelessness',
    'guiltlessness',
    'innocence',
    'chastity',
    'sinlessness',
    'spotlessness',
    'irreproachableness',
    'immaculateness',
    'impeccability',
    'lack of corruption',
    'nobility of soul/spirit',
    'stainlessness',
    'immorality',
]