export const definitions = [
    '"stir in the tomato puree"',
    '"puree the potatoes through the sieve"',
]
export const synonyms = [
    'mash',
    'mush',
    'cream',
    'pap',
    'slop',
    'paste',
    'slush',
    'mulch',
    'swill',
    'slurry',
    'semiliquid',
    'semifluid',
    'mess',
    'baby food',
    'triturate',
    'pomace',
    'pressé',
    'mash',
    'cream',
    'crush',
    'press',
    'smash',
    'liquidize',
    'liquefy',
    'sieve',
    'shred',
    'squash',
    'pound',
    'beat',
    'macerate',
    'mill',
    'grind',
    'mince',
    'soften',
    'mangle',
    'triturate',
    'levigate',
    'bray',
    'comminute',
    'powderize',
]