export const definitions = [
    '"the officer pursued the van"',
    '"a heavily indebted businessman was being pursued by creditors"',
    '"Sophie was being pursued by a number of men"',
    '"should people pursue their own happiness at the expense of others?"',
    '"mercy lasts as long as sin pursues man"',
    '"the road pursued a straight course over the scrubland"',
    '"Andrew was determined to pursue a computer career"',
    '"the council decided not to pursue an appeal"',
    '"we shall not pursue the matter any further"',
]
export const synonyms = [
    'go after',
    'run after',
    'follow',
    'chase',
    'hunt',
    'stalk',
    'track',
    'trail',
    'trace',
    'shadow',
    'dog',
    'hound',
    'course',
    'give chase to',
    'avoid',
    'flee',
    'woo',
    'court',
    'pay court to',
    'chase',
    'run after',
    'romance',
    'pay suit to',
    'chase after',
    'make love to',
    'set one\'s cap at',
    'seek the hand of',
    'pay addresses to',
    'seek',
    'strive for',
    'push toward',
    'work toward',
    'try for',
    'search for',
    'quest (after)',
    'be intent on',
    'aim at/for',
    'have as a goal',
    'have as an objective',
    'aspire to',
    'eschew',
    'trouble',
    'bother',
    'burden',
    'distress',
    'beset',
    'harass',
    'worry',
    'oppress',
    'annoy',
    'vex',
    'irritate',
    'exasperate',
    'strain',
    'stress',
    'tax',
    'torment',
    'plague',
    'blight',
    'bedevil',
    'rack',
    'smite',
    'curse',
    'harrow',
    'grip',
    'visit',
    'take',
    'discommode',
    'ail',
    'cause trouble to',
    'cause suffering to',
    'comfort',
    'practice',
    'follow',
    'prosecute',
    'conduct',
    'ply',
    'go in for',
    'take up',
    'engage in',
    'be engaged in',
    'be occupied in',
    'participate in',
    'take part in',
    'work at',
    'apply oneself to',
    'shun',
    'conduct',
    'undertake',
    'follow',
    'carry on',
    'continue',
    'prosecute',
    'investigate',
    'research',
    'look into',
    'examine',
    'study',
    'review',
    'check',
    'scrutinize',
    'analyze',
    'probe',
    'devote oneself to',
    'go on with',
    'proceed with',
    'go ahead with',
    'keep/carry on with',
    'continue with',
    'take further',
    'persist in',
    'stick with/at',
    'inquire into',
    'delve into',
    'dig into',
    'give up',
]