export const definitions = [
    '"shops purveying cooked food"',
    '"we didn\'t want to purvey gloom and doom"',
]
export const synonyms = [
    'sell',
    'supply',
    'provide',
    'furnish',
    'cater',
    'retail',
    'trade',
    'carry',
    'handle',
    'stock',
    'offer',
    'auction',
    'peddle',
    'hawk',
    'tout',
    'pass on',
    'transmit',
    'broadcast',
    'disseminate',
    'spread',
    'circulate',
    'communicate',
    'publicize',
    'publish',
    'deal in',
    'have for sale',
    'put on the market',
    'traffic in',
    'put around',
    'make known',
    'make available',
]