export const definitions = [
    '"military regimes generally have no qualms about controlling the press"',
]
export const synonyms = [
    'misgiving',
    'doubt',
    'reservation',
    'second thought',
    'worry',
    'concern',
    'anxiety',
    'hesitation',
    'hesitance',
    'hesitancy',
    'demur',
    'reluctance',
    'disinclination',
    'apprehension',
    'trepidation',
    'disquiet',
    'disquietude',
    'unease',
    'uneasiness',
    'scruple',
    'compunction',
    'remorse',
    'pang of conscience',
    'twinge of conscience/remorse',
    'confidence',
]