export const definitions = [
  '"in the morning he was still pale and queasy"',
  '"the queasy swell of the boat"',
];
export const synonyms = [
  'nauseous',
  'nauseated',
  'bilious',
  'sick',
  'seasick',
  'carsick',
  'trainsick',
  'airsick',
  'ill',
  'unwell',
  'poorly',
  'bad',
  'out of sorts',
  'dizzy',
  'peaky',
  'liverish',
  'green around the gills',
  'off',
  'off colour',
  'sick to one\'s stomach',
  'travel-sick',
  'suffering from motion sickness',
  'suffering from altitude sickness',
  'peakish',
];