export const definitions = [
  '"he only pursued her to quench an aching need"',
  '"firemen hauled on hoses in a desperate bid to quench the flames"',
  '"fury rose in him, but he quenched it"',
];
export const synonyms = [
  'fulfill',
  'gratify',
  'meet',
  'fill',
  'serve',
  'supply',
  'indulge',
  'cater to',
  'appease',
  'assuage',
  'slake',
  'satiate',
  'sate',
  'take the edge off',
  'satisfice',
  'provide for',
  'pander to',
  'frustrate',
  'satisfy',
  'slake',
  'sate',
  'satiate',
  'gratify',
  'relieve',
  'assuage',
  'take the edge off',
  'appease',
  'meet',
  'fulfill',
  'indulge',
  'lessen',
  'deaden',
  'decrease',
  'lower',
  'reduce',
  'diminish',
  'curb',
  'check',
  'still',
  'damp',
  'suppress',
  'extinguish',
  'smother',
  'stifle',
  'overcome',
  'extinguish',
  'put out',
  'smother',
  'douse',
  'snuff out',
  'dampen down',
];