export const definitions = [
    '"he quoted a passage from the Psalms"',
    '"\"The stream mysterious glides beneath,\" Melinda quoted"',
    '"when we told her this she said, and I quote, \"Phooey!\""',
    '"the prime minister was quoted as saying that he would resist all attempts to \"sabotage\" his government"',
    '"he quoted Shakespeare, Goethe, and other poets"',
    '"they won\'t be here at all in three years time—you can quote me on that"',
    '"heavy teaching loads are often quoted as a bad influence on research"',
    '"the agent quoted him a fare of $180"',
    '"an organization that is quoted on the Stock Exchange"',
    '"a quote from Wordsworth"',
    '"use double quotes around precise phrases you wish to search for"',
    '"quotes from different insurance companies"',
    '"quotes for North Sea Brent were rising"',
]
export const synonyms = [
    'recite',
    'repeat',
    'reproduce',
    'restate',
    'retell',
    'echo',
    'iterate',
    'parrot',
    'take',
    'extract',
    'excerpt',
    'derive',
    'misquote',
    'ingeminate',
    'say again',
    'cite',
    'mention',
    'give',
    'name',
    'instance',
    'specify',
    'identify',
    'relate',
    'recount',
    'enumerate',
    'list',
    'itemize',
    'spell out',
    'adduce',
    'exemplify',
    'put forward',
    'point out',
    'call attention to',
    'present',
    'offer',
    'advance',
    'propose',
    'refer to',
    'make reference to',
    'allude to',
    'estimate',
    'state',
    'set',
    'tender',
    'bid',
    'offer',
    'price something at',
    'estimate',
    'price',
    'tender',
    'bid',
    'cost',
    'charge',
    'rate',
    'figure',
    'estimated price',
]