export const definitions = [
    '"a squash racket"',
    '"the kids were making a racket"',
    '"a protection racket"',
    '"I\'m in the insurance racket"',
    '"trains racketed by"',
]
export const synonyms = [
    'noise',
    'din',
    'hubbub',
    'clamor',
    'row',
    'uproar',
    'hullabaloo',
    'tumult',
    'commotion',
    'rumpus',
    'fracas',
    'pandemonium',
    'clangor',
    'brouhaha',
    'disturbance',
    'crash',
    'clatter',
    'clash',
    'babble',
    'shouting',
    'yelling',
    'babel',
    'bangarang',
    'fraud',
    'swindle',
    'criminal activity',
    'illegal scheme/enterprise',
    'fraudulent scheme',
    'bit of sharp practice',
]