export const definitions = [
    '"it was beginning to rain"',
    '"the low sky raining over tower\'d Camelot"',
    '"bombs rained down"',
    '"it was just raining glass"',
    '"she rained blows onto him"',
]
export const synonyms = [
    'beat down',
    'lash down',
    'come down',
    'rain cats and dogs',
    'fall',
    'shower',
    'drizzle',
    'spit',
    'pour (down)',
    'pelt down',
    'tip down',
    'teem down',
    'sheet down',
    'come down in torrents/sheets',
    'fall',
    'drop',
    'shower',
    'pour',
    'pour/rain down',
    'bombard someone with',
    'pepper someone with',
    'pelt someone with',
]