export const definitions = [
    '"they ate on a raised platform at one end of the hall"',
    '"the building features raised lettering"',
    '"raised doughnuts"',
    '"a neighbor heard raised voices from the women\'s apartment"',
    '" as we age we are more likely to have raised blood pressure"',
    '"she raised both arms above her head"',
    '"his flag was raised over the city"',
    '"Melody managed to raise him to his feet"',
    '"a fence was being raised around the property"',
    '"the galloping horse raised a cloud of dust"',
    '"divers have located and hope to raise the submarine"',
    '"a strain of yeast that would create enough gas to raise the thick bread dough"',
    '"the gig mills raised the nap on the cloth prior to shearing"',
    '"the bank raised interest rates"',
    '"the aim was to raise awareness of the plight of the homeless"',
    '"the king raised him to the title of Count Torre Bella"',
    '"3 raised to the 7th power is 2,187"',
    '"I\'ll raise you another hundred dollars"',
    '"with support for partner\'s bid suit you raise him to game in it"',
    '"North raises to three no trumps"',
    '"the alarm was raised when he failed to return home"',
    '"doubts have been raised about the future of the reprocessing plant"',
    '"I have raised an invoice for the tape"',
    '"she was attempting to raise $20,000"',
    '"he was born and raised in San Francisco"',
    '"they raised pigs and kept a pony"',
    '"God raised Jesus from the dead"',
    '"the piece raises the ghosts of a number of twentieth-century ideas"',
    '"in late April Henry decided to raise the siege"',
    '"the rabbit was only 250 yards from where he first raised it"',
    '"they raised the low coast by evening"',
    '"I raised him on the open line"',
    '"monoclonal antibodies raised against human lymphocytes"',
]
export const synonyms = [
    'embossed',
    'relief',
    'relievo',
    'cameo',
    'ribbed',
    'die-stamped',
    'thermographed',
    'engraved',
    'lift',
    'elevate',
    'uplift',
    'upraise',
    'hoist',
    'take up',
    'upheave',
    'upthrust',
    'lift up',
    'raise aloft',
    'haul up',
    'heave up',
    'lever up',
    'hitch up',
    'uprear',
    'set up',
    'put up',
    'stand (up)',
    'upend',
    'pitch',
    'set upright',
    'place vertical',
    'stand on end',
    'knock over',
    'lay down',
    'build',
    'construct',
    'erect',
    'assemble',
    'put up',
    'demolish',
    'raze',
    'leaven',
    'ferment',
    'dilate',
    'inflate',
    'cause to rise',
    'make rise',
    'puff up',
    'increase',
    'put up',
    'push up',
    'up',
    'mark up',
    'step up',
    'lift',
    'augment',
    'escalate',
    'inflate',
    'swell',
    'add to',
    'heighten',
    'amplify',
    'magnify',
    'intensify',
    'boost',
    'turn up',
    'louden',
    'make higher',
    'make louder',
    'lower',
    'reduce',
    'promote',
    'advance',
    'upgrade',
    'elevate',
    'prefer',
    'ennoble',
    'aggrandize',
    'exalt',
    'give a higher rank to',
    'give advancement to',
    'demote',
    'bring up',
    'introduce',
    'advance',
    'broach',
    'mention',
    'touch on',
    'suggest',
    'moot',
    'put forward',
    'bring forward',
    'pose',
    'present',
    'propose',
    'submit',
    'air',
    'ventilate',
    'table',
    'give rise to',
    'occasion',
    'cause',
    'bring about',
    'produce',
    'engender',
    'elicit',
    'create',
    'prompt',
    'awaken',
    'arouse',
    'excite',
    'activate',
    'evoke',
    'induce',
    'kindle',
    'incite',
    'stir up',
    'trigger',
    'provoke',
    'instigate',
    'foment',
    'whip up',
    'beget',
    'enkindle',
    'call up',
    'call forth',
    'invoke',
    'allude to',
    'bring into being',
    'draw forth',
    'set going',
    'set afoot',
    'result in',
    'lead to',
    'summon up',
    'spark off',
    'cause to appear',
    'summon (up)',
    'conjure up',
    'withdraw',
    'allay',
    'end',
    'lay',
    'keep quiet about',
    'get',
    'obtain',
    'acquire',
    'accumulate',
    'amass',
    'collect',
    'fetch',
    'realize',
    'yield',
    'net',
    'make',
    'recruit',
    'enlist',
    'sign up',
    'conscript',
    'call up',
    'muster',
    'mobilize',
    'levy',
    'rally',
    'press',
    'assemble',
    'draft',
    'impose',
    'exact',
    'demand',
    'charge',
    'scrape together',
    'call to arms',
    'get/gather together',
    'call together',
    'distribute',
    'spend',
    'stand down',
    'demobilize',
    'bring up',
    'rear',
    'nurture',
    'look after',
    'take care of',
    'mother',
    'parent',
    'tend',
    'protect',
    'cherish',
    'educate',
    'train',
    'foster',
    'care for',
    'provide for',
    'breed',
    'rear',
    'nurture',
    'keep',
    'tend',
    'grow',
    'farm',
    'cultivate',
    'produce',
    'propagate',
    'bring on',
    'plant',
    'end',
    'stop',
    'put an end to',
    'terminate',
    'abandon',
    'lift',
    'bring to an end',
    'start',
    'impose',
    'contact',
    'get hold of',
    'reach',
    'phone',
    'radio',
    'call',
    'get on to',
    'get in touch with',
    'communicate with',
]