export const definitions = [
    '"rancid meat"',
    '"without preservatives, fat goes rancid"',
]
export const synonyms = [
    'sour',
    'stale',
    'turned',
    'rank',
    'putrid',
    'foul',
    'rotten',
    'bad',
    'off',
    'old',
    'tainted',
    'gamy',
    'high',
    'fetid',
    'stinking',
    'malodorous',
    'foul-smelling',
    'evil-smelling',
    'unpleasant',
    'noxious',
    'revolting',
    'nasty',
    'sickening',
    'offensive',
    'noisome',
    'mephitic',
    'miasmic',
    'miasmal',
    'olid',
    'fresh',
]