export const definitions = [
  '"clumps of rank grass"',
  '"breathing rank air"',
  '"the tea at work is nice but the coffee\'s pretty rank"',
  '"rank stupidity"',
  '"a rank outsider"',
  '"rank amateurs"',
];
export const synonyms = [
  'abundant',
  'lush',
  'luxuriant',
  'dense',
  'profuse',
  'flourishing',
  'exuberant',
  'vigorous',
  'productive',
  'spreading',
  'overgrown',
  'sparse',
  'offensive',
  'unpleasant',
  'nasty',
  'disagreeable',
  'revolting',
  'sickening',
  'obnoxious',
  'noxious',
  'foul-smelling',
  'evil-smelling',
  'fetid',
  'smelly',
  'stinking',
  'reeking',
  'reeky',
  'high',
  'off',
  'rancid',
  'putrid',
  'malodorous',
  'fusty',
  'musty',
  'stale',
  'noisome',
  'mephitic',
  'miasmic',
  'miasmal',
  'olid',
  'ill-smelling',
  'pleasant',
  'downright',
  'utter',
  'outright',
  'out-and-out',
  'absolute',
  'complete',
  'sheer',
  'stark',
  'thorough',
  'thoroughgoing',
  'categorical',
  'unequivocal',
  'undeniable',
  'unqualified',
  'unrestricted',
  'unmitigated',
  'unconditional',
  'positive',
  'simple',
  'wholesale',
  'all-out',
  'perfect',
  'consummate',
  'patent',
  'pure',
  'total',
  'entire',
  'flat',
  'direct',
  'dead',
  'final',
  'conclusive',
  'arrant',
  'unmodified',
  'right-down',
];