export const definitions = [
];
export const synonyms = [
  'criminal',
  'lawbreaker',
  'offender',
  'villain',
  'black hat',
  'delinquent',
  'malefactor',
  'culprit',
  'wrongdoer',
  'transgressor',
  'sinner',
  'juvenile delinquent',
  'felon',
  'thief',
  'robber',
  'burglar',
  'housebreaker',
  'shoplifter',
  'mugger',
  'fraudster',
  'confidence trickster',
  'swindler',
  'racketeer',
  'gunman',
  'gangster',
  'outlaw',
  'bandit',
  'terrorist',
  'yakuza',
  'holdupper',
  'tea leaf',
  'malfeasant',
  'infractor',
  'miscreant',
  'trespasser',
  'trusty',
  'transport',
  'peculator',
  'defalcator',
  'young offender',
  'armed robber',
  'misfeasor',
  'law-abiding citizen',
];