export const definitions = [
  '"the rarity of the condition"',
  '"to take the morning off was a rarity"',
];
export const synonyms = [
  'infrequency',
  'rareness',
  'unusualness',
  'uncommonness',
  'singularity',
  'uniqueness',
  'scarcity',
  'scarceness',
  'sparseness',
  'collector\'s item',
  'rare bird',
  'marvel',
  'wonder',
  'nonpareil',
  'one of a kind',
  'find',
  'conversation piece',
  'curiosity',
  'oddity',
  'anomaly',
  'freak',
  'outlier',
  'edge case',
  'rara avis',
  'rare person/thing',
];