export const definitions = [
    '"he reached over and turned off his bedside light"',
    '"she reached forward and yanked the curtains back"',
    '"Carl reached for the phone"',
    '"reach me those glasses"',
    '"I had to stand on tiptoe and even then I could hardly reach"',
    '"\"Goodbye,\" she said as they reached the door"',
    '"the show is due to reach our screens early next year"',
    '"unemployment reached a peak in 1933"',
    '"in its native habitat it will reach to about 6 m in height"',
    '"the intergovernmental conference reached agreement on the draft treaty"',
    '"their fresh sound and message reach people who may never set foot in a church"',
    '"I\'ve been trying to reach you all morning"',
    '"television reached those parts of the electorate that other news sources could not"',
    '"\"Brighteyes\" was followed round the Goldstone by \"Patriot\", while \"Patriot\" white-sail reached"',
    '"she made a reach for him"',
    '"a giant, over six feet seven with a reach of over 81 inches"',
    '"the diameter and the reach of the spark plug varies from engine to engine"',
    '"the upper reaches of the Nile"',
    '"he could sail a clear reach for Key Canaka"',
]
export const synonyms = [
    'hold out',
    'extend',
    'outstretch',
    'stick out',
    'outreach',
    'stretch out',
    'thrust out',
    'grab',
    'seize',
    'lay (one\'s) hands on',
    'get one\'s hands on',
    'reach for',
    'snatch at',
    'make a grab for',
    'catch at',
    'claw at',
    'grab/seize/take hold of',
    'pass',
    'hand',
    'give',
    'let someone have',
    'get to',
    'come to',
    'gain',
    'arrive at',
    'get as far as',
    'make it to',
    'end up at',
    'land up at',
    'set foot on',
    'attain',
    'get to',
    'fall to',
    'run to',
    'amount to',
    'rise to',
    'climb to',
    'sink to',
    'drop to',
    'achieve',
    'attain',
    'gain',
    'accomplish',
    'work out',
    'draw up',
    'put together',
    'strike',
    'negotiate',
    'thrash out',
    'hammer out',
    'influence',
    'sway',
    'get through to',
    'get to',
    'carry weight with',
    'make an impression on',
    'have an effect on',
    'have an impact on',
    'register with',
    'contact',
    'get through to',
    'get',
    'speak to',
    'talk to',
    'get in touch with',
    'communicate with',
    'make contact with',
    'grasp',
    'range',
    'capabilities',
    'capacity',
    'jurisdiction',
    'authority',
    'sway',
    'control',
    'command',
    'influence',
    'scope',
    'range',
    'compass',
    'ambit',
    'orbit',
    'latitude',
    'sphere',
    'area',
    'field',
    'territory',
]