export const definitions = [
  '"so what really happened?"',
  '"they\'re not really my aunt and uncle"',
  '"really, there are only three options"',
  '"I really want to go"',
  '"I\'m sorry, Ruth, I really am"',
  '"you really ought to tell her"',
  '"do you really expect me to believe that?"',
  '"I think she\'s really great"',
  '"a really cold day"',
  '"he writes really well"',
  '"\"I\'ve been working hard.\" \"Really ?\""',
  '"really, Marjorie, you do jump to conclusions!"',
  '"\"It\'s a nightmare finding somewhere to live in this town.\" \"Yeah, really.\""',
];
export const synonyms = [
  'in fact',
  'in actual fact',
  'actually',
  'in reality',
  'as a matter of fact',
  'in truth',
  'if truth be told',
  'to tell the truth',
  'in sooth',
  'in point of fact',
  'in actuality',
  'genuinely',
  'truly',
  'honestly',
  'undoubtedly',
  'indubitably',
  'certainly',
  'surely',
  'assuredly',
  'unquestionably',
  'undeniably',
  'indeed',
  'verily',
  'without a doubt',
  'genuinely',
  'honestly',
  'truly',
  'truthfully',
  'wholeheartedly',
  'with all one\'s heart',
  'from the bottom of \'s \'s heart',
  'earnestly',
  'fervently',
  'seriously',
  'with all sincerity',
  'without pretense',
  'without feigning',
  'in good faith',
  'insincerely',
  'genuinely',
  'truly',
  'honestly',
  'undoubtedly',
  'indubitably',
  'certainly',
  'surely',
  'assuredly',
  'unquestionably',
  'undeniably',
  'indeed',
  'verily',
  'very',
  'extremely',
  'thoroughly',
  'decidedly',
  'awfully',
  'terribly',
  'frightfully',
  'dreadfully',
  'fearfully',
  'exceptionally',
  'exceedingly',
  'immensely',
  'uncommonly',
  'remarkably',
  'eminently',
  'extraordinarily',
  'most',
  'positively',
  'downright',
  'heartily',
  'unco',
  'quite',
  'très',
  'exceeding',
  'sore',
  'without a doubt',
  'well I never',
  'go on',
  'you don\'t say',
  'go to',
  'is that so',
  'is that a fact',
  'well I never did',
];