export const definitions = [
    '"the peers of the realm"',
    '"the defense of the realm"',
    '"the realm of applied chemistry"',
    '"this zoogeographical realm includes Africa south of the Atlas Mountains"',
]
export const synonyms = [
    'kingdom',
    'monarchy',
    'empire',
    'principality',
    'palatinate',
    'duchy',
    'country',
    'land',
    'domain',
    'dominion',
    'nation',
    'province',
    'sovereign state',
    'domain',
    'sphere',
    'area',
    'field',
    'department',
    'arena',
    'world',
    'region',
    'province',
    'territory',
    'zone',
    'orbit',
]