export const definitions = [
  '"the scheme eases the move to the council tax by giving rebates in the first year"',
  '"you will be entitled to a 20 percent rebate off each standard fare"',
  '"the government rebates part of your own and your employer\'s National Insurance contributions into the plan"',
  '"a rebate joint"',
  '"you can use it for rebating"',
  '"rebated blocks are glued in each corner"',
  '"the oak boarding was rebated in"',
];
export const synonyms = [
  'refund',
  'repayment',
  'discount',
  'deduction',
  'reduction',
  'decrease',
  'allowance',
  'concession',
  'partial refund',
  'refund',
  'repayment',
  'discount',
  'deduction',
  'reduction',
  'decrease',
  'allowance',
  'concession',
  'partial refund',
];