export const definitions = [
  '"I can still vaguely recall being taken to the hospital"',
  '"Annie recalled the event that led to the rift in their friendship"',
  '"he recalled how he felt at the time"',
  '"\"He was awfully fond of teasing people,\" she recalled"',
  '"the film\'s analysis of contemporary concerns recalls The Big Chill"',
  '"the smell of a black-currant bush has ever since recalled to me that evening"',
  '"students can recall templates or stored formats"',
  '"the Panamanian ambassador was recalled from Peru"',
  '"the Fulham defender has been recalled to the Welsh squad for the World Cup"',
  '"her action recalled him to the present"',
  '"he sent another note to Lord Grey recalling his earlier communication"',
  '"a recall of Parliament"',
  '"he has amazing recall"',
  '"people\'s understanding and subsequent recall of stories or events"',
];
export const synonyms = [
  'remember',
  'recollect',
  'think of',
  'mind',
  'call to mind',
  'think back on/to',
  'look back on',
  'cast one\'s mind back to',
  'reminisce about',
  'hark back to',
  'forget',
  'call up',
  'evoke',
  'echo',
  'bring to mind',
  'call to mind',
  'put one in mind of',
  'summon up',
  'conjure up',
  'allude to',
  'call back',
  'bring back',
  'summon back',
  'order back',
  'dissolve',
  'prorogue',
  'revoke',
  'rescind',
  'cancel',
  'retract',
  'countermand',
  'take back',
  'withdraw',
  'repeal',
  'veto',
  'overrule',
  'override',
  'abrogate',
  'annul',
  'invalidate',
  'nullify',
  'void',
  'negate',
  'declare null and void',
  'disannul',
  'ratify',
  'confirm',
  'summons',
  'revocation',
  'rescinding',
  'cancellation',
  'canceling',
  'retraction',
  'retracting',
  'countermanding',
  'withdrawal',
  'abrogation',
  'repeal',
  'vetoing',
  'veto',
  'annulment',
  'invalidation',
  'nullification',
  'rescission',
  'summoning back',
  'ordering back',
  'calling back',
  'recollection',
  'memory',
  'remembrance',
  'anamnesis',
];