export const definitions = [
    '"the flood waters had receded"',
    '"his footsteps receded down the corridor"',
    '"the prospects of an early end to the war receded"',
    '"his dark hair was receding a little"',
    '"Fred was receding a bit"',
    '"his chin receded sharply from his lower lip"',
]
export const synonyms = [
    'retreat',
    'go back',
    'move away',
    'withdraw',
    'ebb',
    'subside',
    'go down',
    'abate',
    'fall back',
    'sink',
    'retrocede',
    'move back',
    'move further off',
    'advance',
    'approach',
    'diminish',
    'lessen',
    'decrease',
    'dwindle',
    'fade',
    'abate',
    'subside',
    'ebb',
    'wane',
    'fall off',
    'shrink',
    'de-escalate',
    'grow less',
    'taper off',
    'peter out',
    'grow',
    'intensify',
    'beg off',
    'pull out of',
    'back out of',
    'bow out of',
    'scratch from',
    'get cold feet',
    'recede from',
]