export const definitions = [
    '"rains have helped recoup water levels"',
    '"sleep was what she needed to recoup her strength"',
    '"oil companies are keen to recoup their investment"',
    '"the company turned to the real estate industry to recoup them"',
    '"federal law allows them to recoup part of the damages"',
]
export const synonyms = [
    'regain',
    'recover',
    'retrieve',
    'repossess',
    'redeem',
    'make good',
    'recuperate',
    'get back',
    'win back',
    'reimburse',
    'refund',
    'pay back',
    'recompense',
    'compensate',
    'remunerate',
    'indemnify',
    'pay off',
    'square accounts with',
    'settle up with',
]