export const definitions = [
    '"a confidential memo which has been redacted from 25 pages to just one paragraph"',
]
export const synonyms = [
    'correct',
    'rectify',
    'repair',
    'fix',
    'improve',
    'enhance',
    'polish',
    'refine',
    'clarify',
    'edit',
    'alter',
    'rewrite',
    'revise',
    'copyedit',
    'subedit',
    'amend',
    'change',
    'modify',
    'redraft',
    'recast',
    'rephrase',
    'reword',
    'rework',
    'rescript',
    'expurgate',
    'censor',
    'bowdlerize',
]