export const definitions = [
  '"the reports of the commission are often referred to in the media"',
  '"New York, referred to as the Big Apple"',
  '"I refer my colleague to the reply that I gave some moments ago"',
  '"the term \"rhetoric\" almost invariably refers to persuasion"',
  '"disagreement arose and the issue was referred back to the Executive Committee"',
  '"she was referred to a clinical psychologist for counseling"',
  '"I always refer to a dictionary when I come across a new word"',
  '"the God to whom he habitually referred his highest inspirations"',
  '"you went wrong when you referred all legislation to a part of virtue"',
];
export const synonyms = [
  'mention',
  'touch on',
  'cite',
  'name',
  'go into',
  'note',
  'point out',
  'call attention to',
  'bring up',
  'raise',
  'broach',
  'introduce',
  'moot',
  'make mention of',
  'make reference to',
  'allude to',
  'speak of/about',
  'talk of/about',
  'write about',
  'comment on',
  'deal with',
  'treat (of)',
  'advert to',
  'pass',
  'hand on',
  'send on',
  'transfer',
  'remit',
  'direct',
  'leave',
  'commit',
  'entrust',
  'assign',
  'hand over',
  'concern',
  'have to do with',
  'bear on',
  'affect',
  'involve',
  'cover',
  'touch',
  'touch on',
  'regard',
  'denote',
  'describe',
  'indicate',
  'mean',
  'depict',
  'symbolize',
  'signify',
  'designate',
  'stand for',
  'represent',
  'apply to',
  'be relevant to',
  'have relevance to',
  'relate to',
  'belong to',
  'be about',
  'be connected with',
  'have reference to',
  'pertain to',
  'appertain to',
  'be pertinent to',
  'have a bearing on',
  'consult',
  'turn to',
  'call on',
  'call in',
  'ask',
  'look at',
  'look up (in)',
  'seek information from',
  'search in',
  'have recourse to',
  'seek advice from',
  'take counsel from',
];