export const definitions = [
    '"he was forced to take refuge in the French embassy"',
    '"I sought refuge in drink"',
    '"the family came to be seen as a refuge from a harsh world"',
]
export const synonyms = [
    'haven',
    'safe haven',
    'shelter',
    'sanctuary',
    'retreat',
    'asylum',
    'oasis',
    'sanctum',
    'place of safety',
    'place of security',
    'port in a storm',
    'shelter',
    'protection',
    'safety',
    'security',
    'asylum',
    'sanctuary',
    'preservation',
    'safe keeping',
    'haven',
    'safe haven',
    'sanctum',
    'safe house',
    'harbor',
    'ark',
    'retreat',
    'bolthole',
    'foxhole',
    'hiding place',
    'hideaway',
    'hideout',
    'fastness',
    'place of shelter',
    'place of safety',
    'port in a storm',
    'querencia',
]