export const definitions = [
    '"I refused to answer"',
    '"he was severely beaten when he refused"',
    '"she refused a cigarette"',
    '"the old lady was refused admission to four hospitals"',
    '"the car refused to start"',
    '"he\'s so conceited he\'d never believe anyone would refuse him"',
    '"her horse refused a high hedge"',
    '"again the horse refused, his nostrils flaring with fear"',
    '"heaps of refuse"',
    '"refuse collection"',
]
export const synonyms = [
    'decline',
    'turn down',
    'reject',
    'spurn',
    'scorn',
    'rebuff',
    'disdain',
    'repudiate',
    'dismiss',
    'repulse',
    'shake one\'s head',
    'withhold',
    'disapprove',
    'deny',
    'discountenance',
    'say no to',
    'send one\'s regrets',
    'balk at',
    'demur at',
    'protest at',
    'jib at',
    'draw the line at',
    'not grant',
    'accept',
    'grant',
    'waste',
    'debris',
    'litter',
    'garbage',
    'detritus',
    'dross',
    'landfill',
    'scrap',
    'rubble',
    'slag',
    'spoilage',
    'sullage',
    'sewage',
    'slop',
    'dregs',
    'lees',
    'leavings',
    'leftovers',
    'sweepings',
    'rubbish',
    'trash',
    'draff',
    'raffle',
    'discarded matter',
    'mullock',
    'debitage',
    'raff',
]