export const definitions = [
    '"one of the region\'s major employers"',
    '"the equatorial regions"',
    '"a major wine - producing region"',
    '"an unexpected clenching sensation in the region of her heart"',
    '"his work takes needlework into the region of folk art"',
]
export const synonyms = [
    'area',
    'sector',
    'section',
    'belt',
    'territory',
    'tract',
    'stretch',
    'expanse',
    'district',
    'quarter',
    'precinct',
    'locality',
    'neighborhood',
    'province',
    'land',
    'district',
    'province',
    'territory',
    'division',
    'area',
    'section',
    'sector',
    'zone',
    'belt',
    'tract',
    'stretch',
    'expanse',
    'terrain',
    'part',
    'quarter',
    'locality',
    'locale',
    'domain',
    'realm',
    'province',
    'field',
    'area',
    'territory',
    'arena',
    'department',
    'discipline',
    'speciality',
    'specialty',
    'area of interest',
    'area of study',
]