export const definitions = [
    '"he contented himself with occasional articles in journals, rehashing his own work"',
    '"is it really necessary to rehash that trauma all over again?"',
    '"the spring show was a rehash of the summer show from the previous year"',
]
export const synonyms = [
    'reword',
    'rephrase',
    'rewrite',
    'rescript',
    'restate',
    'interpret',
    'gloss',
    'put/express in other words',
    'put/express in one\'s own words',
    'express differently',
    'adapt',
    'turn',
    'rework',
    'recast',
    'reshape',
    'refashion',
    'remodel',
    'remold',
    'rewording',
    'rephrasing',
    'rewriting',
    'rewrite',
    'restatement',
    'restating',
    'rendition',
    'rendering',
    'version',
    'interpretation',
    'gloss',
    'paraphrasis',
]