export const definitions = [
    '"she was going to refuse his request, but relented"',
    '"by evening the rain relented"',
]
export const synonyms = [
    'change one\'s mind',
    'backpedal',
    'back down',
    'give way',
    'give in',
    'capitulate',
    'yield',
    'accede',
    'come around',
    'acquiesce',
    'soften',
    'melt',
    'weaken',
    'unbend',
    'do a U-turn',
    'become merciful',
    'become lenient',
    'have/show pity',
    'have/show mercy',
    'give quarter',
    'agree to something',
    'allow something',
    'concede something',
    'admit something',
    'do an about-turn',
    'harden',
    'ease off',
    'slacken',
    'let up',
    'ease',
    'relax',
    'abate',
    'drop',
    'fall off',
    'lessen',
    'decrease',
    'diminish',
    'moderate',
    'subside',
    'weaken',
    'tail off',
    'ease up',
    'die down',
    'strengthen',
    'worsen',
]