export const definitions = [
  '"\"Tom\'s looking peaked,\" she remarked"',
  '"he remarked that he had some work to finish"',
  '"the judges remarked on the high standard of the entries"',
  '"he remarked the man\'s inflamed eyelids"',
  '"I decided to ignore his rude remarks"',
  '"the landscape was not worthy of remark"',
];
export const synonyms = [
  'comment',
  'say',
  'observe',
  'mention',
  'reflect',
  'state',
  'declare',
  'announce',
  'pronounce',
  'assert',
  'interpose',
  'interject',
  'come out with',
  'opine',
  'speak of',
  'touch on',
  'comment on',
  'refer to',
  'pass comment on',
  'say something about',
  'note',
  'notice',
  'observe',
  'mark',
  'perceive',
  'discern',
  'take note of',
  'comment',
  'statement',
  'utterance',
  'observation',
  'declaration',
  'pronouncement',
  'reflection',
  'thought',
  'opinion',
  'words',
  'attention',
  'notice',
  'mention',
  'consideration',
  'heed',
  'acknowledgment',
  'recognition',
];