export const definitions = [
  '"I had a seventeen-year-old son remanded to a drug-addiction program"',
  '"the Supreme Court summarily vacated the opinion and remanded the matter back to the California Court of Appeal"',
  '"the prosecutor applied for a remand to allow forensic evidence to be investigated"',
  '"a remand home"',
];
export const synonyms = [
  'imprison',
  'jail',
  'incarcerate',
  'detain',
  'intern',
  'impound',
  'immure',
  'shut up',
  'shut in',
  'confine',
  'cage',
  'pen',
  'send to prison',
  'put behind bars',
  'put under lock and key',
  'put in chains',
  'put/throw into irons',
  'clap in irons',
  'hold captive',
  'coop up',
  'fence in',
  'pen in',
  'wall in',
  'mew (up)',
  'custody',
  'imprisonment',
  'confinement',
  'incarceration',
  'internment',
  'captivity',
  'restraint',
  'arrest',
  'house arrest',
  'committal',
  'quarantine',
  'duress',
  'durance',
  'detainment',
];