export const definitions = [
    '"herbal remedies for aches and pains"',
    '"shopping became a remedy for personal problems"',
    '"the doctrine took away their only remedy against merchants who refused to honor their contracts"',
    '"by the time a problem becomes patently obvious, it may be almost too late to remedy it"',
]
export const synonyms = [
    'treatment',
    'cure',
    'medicine',
    'medication',
    'medicament',
    'drug',
    'restorative',
    'antidote',
    'prophylactic',
    'nostrum',
    'panacea',
    'cure-all',
    'therapy',
    'physic',
    'specific',
    'solution',
    'answer',
    'cure',
    'antidote',
    'corrective',
    'curative',
    'nostrum',
    'panacea',
    'cure-all',
    'heal-all',
    'palliative',
    'balm',
    'countermeasure',
    'magic formula',
    'comeback',
    '(means of) redress',
    '(means of) reparation',
    'right',
    'rectify',
    'retrieve',
    'solve',
    'fix',
    'sort out',
    'resolve',
    'correct',
    'repair',
    'mend',
    'redress',
    'make good',
    'improve',
    'amend',
    'ameliorate',
    'better',
    'put right',
    'set right',
    'set to rights',
    'put to rights',
    'put in order',
    'straighten out',
    'deal with',
    'make better',
]