export const definitions = [
    '"it would be very remiss of me not to pass on that information"',
    '"they have been remiss in their duties"',
]
export const synonyms = [
    'negligent',
    'neglectful',
    'irresponsible',
    'careless',
    'thoughtless',
    'heedless',
    'unthinking',
    'unmindful',
    'lax',
    'slack',
    'slipshod',
    'lackadaisical',
    'forgetful',
    'inattentive',
    'unheeding',
    'lazy',
    'dilatory',
    'indolent',
    'derelict',
    'delinquent',
    'barratrous',
    'disregardful',
    'oscitant',
    'careful',
    'diligent',
    'painstaking',
]