export const definitions = [
  '"the excess of the sentence over 12 months was remitted"',
  '"God\'s act of remitting the sins of guilty men"',
  '"the income they remitted to their families"',
  '"the request for an investigation was remitted to a special committee"',
  '"it remits an offender to another court after convicting him"',
  '"the movers refused Mr. Tierney\'s request to remit the motion"',
  '"thus his indiscretion remitted him to the nature of an ordinary person"',
  '"phobias may remit spontaneously without any treatment"',
  '"the committee was becoming caught up in issues that did not fall within its remit"',
  '"a remit on the question failed"',
];
export const synonyms = [
  'cancel',
  'set aside',
  'revoke',
  'repeal',
  'rescind',
  'abrogate',
  'suspend',
  'pardon',
  'forgive',
  'excuse',
  'overlook',
  'pass over',
  'send',
  'dispatch',
  'forward',
  'transmit',
  'convey',
  'pay',
  'hand over',
  'make payment of',
  'pass (on)',
  'refer',
  'send on',
  'transfer',
  'hand on',
  'direct',
  'assign',
  'commit',
  'entrust',
  'postpone',
  'defer',
  'put off',
  'put back',
  'shelve',
  'delay',
  'stand over',
  'suspend',
  'prorogue',
  'reschedule',
  'put over',
  'table',
  'continue',
  'respite',
  'hold over/off',
  'keep in abeyance',
  'lay on the table',
  'diminish',
  'lessen',
  'decrease',
  'abate',
  'moderate',
  'dwindle',
  'wane',
  'ebb',
  'subside',
  'ease (up)',
  'sphere',
  'orbit',
  'scope',
  'ambit',
  'province',
  'territory',
  'realm',
  'department',
  'turf',
  'brief',
  'instructions',
  'orders',
  'area of responsibility',
  'area of activity',
];