export const definitions = [
    '"I\'d chosen a spot that looked as remote from any road as possible"',
    '"a remote Oregon valley"',
    '"a golden age in the remote past"',
    '"the theory seems rather intellectual and remote from everyday experience"',
    '"a remote cousin"',
    '"companies will understand that remote working can be helpful for employees"',
    '"she said teachers deserved more credit for the success of remote learning"',
    '"these jobs are largely virtual and may be open to remote workers from any location"',
    '"a second feature allows pagers to be alerted from remote alarm sensors"',
    '"chances of a genuine and lasting peace become even more remote"',
    '"Maria seemed remote and patronizing"',
    '"universal remotes which let you operate all your audio/video components from one handset"',
]
export const synonyms = [
    'faraway',
    'distant',
    'far',
    'far off',
    'isolated',
    'out of the way',
    'outlying',
    'secluded',
    'lonely',
    'off the map',
    'godforsaken',
    'obscure',
    'inaccessible',
    'cutoff',
    'unreachable',
    'far-flung',
    'lonesome',
    'lone',
    'unapproachable',
    'far removed',
    'dim and distant',
    'off the beaten track',
    'in the depths of …',
    'hard to find',
    'in the back of beyond',
    'in the hinterlands',
    'in the middle of nowhere',
    'in the backwoods',
    'in the backveld',
    'in the platteland',
    'in the backblocks',
    'in the booay',
    'close',
    'near',
    'central',
    'irrelevant to',
    'unrelated to',
    'unconnected to',
    'unconcerned with',
    'not pertinent to',
    'inapposite to',
    'immaterial to',
    'unassociated with',
    'inappropriate to',
    'foreign to',
    'alien to',
    'extrinsic to',
    'relevant',
    'unlikely',
    'improbable',
    'implausible',
    'doubtful',
    'dubious',
    'far-fetched',
    'faint',
    'slight',
    'slim',
    'small',
    'slender',
    'minimal',
    'marginal',
    'negligible',
    'insignificant',
    'inconsiderable',
    'likely',
    'strong',
    'aloof',
    'distant',
    'detached',
    'impersonal',
    'withdrawn',
    'reserved',
    'uncommunicative',
    'unforthcoming',
    'unapproachable',
    'unresponsive',
    'indifferent',
    'unconcerned',
    'preoccupied',
    'abstracted',
    'unfriendly',
    'unsociable',
    'standoffish',
    'cool',
    'chilly',
    'cold',
    'haughty',
    'introspective',
    'introvert',
    'introverted',
    'friendly',
    'approachable',
]