export const definitions = [
    '"money serves as a reward for services rendered"',
    '"Mrs. Evans would render assistance to those she thought were in real need"',
    '"he would render income tax returns at the end of the year"',
    '"the jury\'s finding amounted to the clearest verdict yet rendered upon the scandal"',
    '"he will render up his immortal soul"',
    '"the rains rendered his escape impossible"',
    '"the eyes and the cheeks are exceptionally well rendered"',
    '"a soprano solo reverently rendered by Linda Howie"',
    '"the phrase was rendered into English"',
    '"he is forced to render images by intermixing pixels of a few basic colors"',
    '"the fat was being cut up and rendered for lard"',
    '"animal carcasses were rendered to provide a protein supplement"',
    '"external walls will be rendered and tiled"',
]
export const synonyms = [
    'give',
    'provide',
    'supply',
    'furnish',
    'contribute',
    'offer',
    'extend',
    'proffer',
    'show',
    'display',
    'exhibit',
    'evince',
    'manifest',
    'make available',
    'send in',
    'present',
    'tender',
    'submit',
    'deliver',
    'return',
    'hand down',
    'bring in',
    'give',
    'announce',
    'pronounce',
    'proclaim',
    'give back',
    'return',
    'restore',
    'pay back',
    'repay',
    'hand over',
    'give up',
    'surrender',
    'relinquish',
    'deliver',
    'turn over',
    'yield',
    'cede',
    'make',
    'leave',
    'cause to be/become',
    'paint',
    'draw',
    'depict',
    'portray',
    'represent',
    'reproduce',
    'execute',
    'limn',
    'act',
    'perform',
    'play',
    'interpret',
    'perform',
    'play',
    'sing',
    'execute',
    'interpret',
    'translate',
    'put',
    'express',
    'transcribe',
    'convert',
    'rephrase',
    'reword',
    'transliterate',
    'construe',
    'melt down',
    'clarify',
    'purify',
]