export const definitions = [
  '"authors of great renown"',
];
export const synonyms = [
  'fame',
  'distinction',
  'eminence',
  'preeminence',
  'prominence',
  'repute',
  'reputation',
  'prestige',
  'acclaim',
  'celebrity',
  'note',
  'notability',
  'mark',
  'consequence',
  'standing',
  'stature',
  'account',
  'glory',
  'illustriousness',
  'obscurity',
  'anonymity',
];