export const definitions = [
    '"the legislation was repealed five months later"',
    '"the House voted in favor of repeal"',
]
export const synonyms = [
    'revoke',
    'rescind',
    'cancel',
    'reverse',
    'abrogate',
    'annul',
    'nullify',
    'void',
    'invalidate',
    'quash',
    'abolish',
    'set aside',
    'countermand',
    'retract',
    'withdraw',
    'overrule',
    'override',
    'vacate',
    'avoid',
    'recall',
    'declare null and void',
    'make void',
    'render invalid',
    'disannul',
    'introduce',
    'enact',
    'ratify',
    'revocation',
    'rescinding',
    'cancellation',
    'reversal',
    'annulment',
    'nullification',
    'voiding',
    'invalidation',
    'quashing',
    'abolition',
    'abrogation',
    'countermanding',
    'retraction',
    'withdrawal',
    'overruling',
    'overriding',
    'recall',
    'rescission',
    'setting aside',
    'rescindment',
    'disannulment',
    'introduction',
    'enactment',
    'ratification',
]