export const definitions = [
    '"\"Are you hurt?\" he repeated"',
    '"Billy repeated his question"',
    '"the landlady repeated that she was being very lenient with him"',
    '"he repeated the words after me"',
    '"she repeated what I\'d said"',
    '"she was fretful and kept repeating herself"',
    '"force was not—repeat, not—to be used"',
    '"earlier experiments were to be repeated on a far larger scale"',
    '"the thirteen episodes from the first two series were constantly repeated"',
    '"Mark had to repeat first and second grades"',
    '"I don\'t intend to let history repeat itself"',
    '"the first team in nineteen years to repeat as NBA champions"',
    '"a watch repeater that repeats hours and quarters"',
    '"it sat rather uncomfortably on my stomach and repeated on me for hours"',
    '"the final will be a repeat of last year"',
    '"she goes home alone to TV dinners and repeats of \"I Love Lucy\""',
    '"a repeat prescription"',
    '"rugs with simple repeat patterns"',
]
export const synonyms = [
    'restate',
    'reiterate',
    'iterate',
    'rehearse',
    'recapitulate',
    'reprise',
    'ingeminate',
    'say again',
    'go through again',
    'go over again',
    'run through again',
    'restate',
    'reiterate',
    'iterate',
    'rehearse',
    'recapitulate',
    'reprise',
    'ingeminate',
    'recite',
    'quote',
    'reproduce',
    'echo',
    'parrot',
    'regurgitate',
    'say again',
    'go through again',
    'go over again',
    'run through again',
    'go on',
    'talk constantly',
    'talk endlessly',
    'talk repeatedly',
    'keep talking',
    'go on talking',
    'go on and on',
    'dwell on the subject',
    'refer to repeatedly',
    'repeat oneself',
    'ramble on',
    'rant on',
    'redo',
    'replicate',
    'duplicate',
    'do again',
    'perform again',
    'rebroadcast',
    'rerun',
    'reshow',
    'replay',
    'reoccur',
    'recur',
    'reappear',
    'occur again',
    'happen again',
    'repetition',
    'duplication',
    'replication',
    'rerun',
    'duplicate',
    'replica',
    'copy',
    'echo',
    'ditto',
    'rerun',
    'replay',
    'rebroadcast',
    'reshowing',
]