export const definitions = [
    '"he could stop the tape and replay it whenever he wished"',
    '"she replayed in her mind every detail of the night before"',
    '"clouds can be studied in speeded-up replay"',
    '"the umpire studied TV replays"',
    '"a replay of last summer\'s civil disturbance"',
    '"Wilson equalized to earn a replay"',
]
export const synonyms = [
    'rebroadcast',
    'rerun',
    'reshow',
    'repeat',
    'repetition',
    'curtain call',
    'repeat performance',
    'extra performance',
    'additional performance',
    'rerun',
    'rebroadcast',
    'reshowing',
    'contest',
    'competition',
    'game',
    'tournament',
    'tie',
    'event',
    'fixture',
    'trial',
    'test',
    'test match',
    'meet',
    'bout',
    'fight',
    'duel',
    'quarterfinal',
    'semifinal',
    'final',
    'Cup Final',
    'friendly',
    'derby',
    'playoff',
    'rematch',
    'clash',
    'split',
    'tourney',
    'cup tie',
    'local derby',
    'playdown',
]