export const definitions = [
    '"in repose her face looked relaxed"',
    '"he had lost none of his grace or his repose"',
    '"many of the qualities of the great Piero della Francescas—the sense of grand stasis, of timeless repose—seem strongly reincarnated in this work"',
    '"the diamond now reposes in the Louvre"',
    '"how sweetly he would repose in the four-poster bed"',
    '"I\'ll go to him, and repose our distresses on his friendly bosom"',
    '"he halted to repose his wayworn soldiers"',
    '"we have never betrayed the trust that you have reposed in us"',
]
export const synonyms = [
    'rest',
    'relaxation',
    'inactivity',
    'restfulness',
    'stillness',
    'idleness',
    'sleep',
    'slumber',
    'work',
    'activity',
    'peace',
    'peacefulness',
    'quiet',
    'quietness',
    'quietude',
    'calm',
    'calmness',
    'tranquillity',
    'stillness',
    'leisure',
    'ease',
    'respite',
    'time off',
    'breathing space',
    'composure',
    'serenity',
    'tranquility',
    'equanimity',
    'poise',
    'self-possession',
    'aplomb',
    'self-assurance',
    'dignity',
    'peace and quiet',
    'peace of mind',
    'stress',
    'strain',
    'agitation',
    'lie',
    'rest',
    'be placed',
    'be set',
    'be situated',
    'be positioned',
    'be supported',
    'lie',
    'recline',
    'rest',
    'relax',
    'sleep',
    'slumber',
    'couch',
    'lie down',
    'stretch out',
    'take one\'s ease',
    'put',
    'place',
    'lay',
    'lodge',
    'set',
    'consign',
    'invest',
    'entrust',
]