export const definitions = [
  '"a reprise of his earlier performance"',
  '"he reprises his role as the vigilante architect"',
];
export const synonyms = [
  'reiteration',
  'repeating',
  'restatement',
  'retelling',
  'iteration',
  'recapitulation',
  'recital',
  'rehearsal',
  'iterance',
  'repeat',
  'restate',
  'reiterate',
  'copy',
  'imitate',
  'parrot',
  'parody',
  'mimic',
  'reproduce',
  'iterate',
  'recite',
  'quote',
  'rehearse',
  'recapitulate',
  'regurgitate',
  'ingeminate',
  'say again',
];