export const definitions = [
  '"a seaside resort"',
  '"a health resort"',
  '"places of public resort"',
  '"territorial questions must not be settled by resort to violence"',
  '"her only resort is surgery"',
  '"the duke was prepared to resort to force if negotiation failed"',
  '"local housing authorities must consider the needs of all people residing in or resorting to their district"',
];
export const synonyms = [
  'center',
  'spot',
  'retreat',
  'haunt',
  'spa',
  'watering place',
  'tourist center',
  'holiday destination',
  'holiday centre',
  'utilizing',
  'recourse to',
  'turning to',
  'the use of',
  'application to',
  'appealing to',
  'looking to',
  'expedient',
  'measure',
  'step',
  'recourse',
  'alternative',
  'option',
  'choice',
  'possibility',
  'hope',
  'remedy',
  'possible course of action',
  'source of help',
  'source of assistance',
  'someone/something to turn to',
  'fall back on',
  'turn to',
  'make use of',
  'use',
  'utilize',
  'employ',
  'call on',
  'adopt',
  'exercise',
  'have recourse to',
  'look to',
  'avail oneself of',
  'bring into play/service',
  'press into service',
  'stoop to',
  'descend to',
  'sink to',
];