export const definitions = [
    '"the representative reported a decline in milk and meat production"',
    '"police reported that the flood waters were abating"',
    '"the teacher should report on the child\'s progress"',
    '"the public disliked the way that the media reported on the scandal"',
    '"the Egyptian news agency reported that a coup attempt had taken place"',
    '"the paper reported a secret program by the country to build nuclear warheads"',
    '"these hoaxers are reported to be hacking into airline frequencies to impersonate air traffic controllers"',
    '"undisclosed illegalities are reported to the company\'s directors"',
    '"eight horses have been reported missing in the last month"',
    '"the Chairman shall report the Bill to the House"',
    '"Stewart is to report to a probation office on Monday"',
    '"he was given only a few days to say goodbye to his family and report for duty"',
    '"he reports to the chairman of the committee"',
    '"the chairman\'s annual report"',
    '"according to press reports, the plan faced considerable opposition"',
    '"reports were circulating that the chairman was about to resign"',
    '"report has it that the beetles have now virtually disappeared"',
    '"all our horses are very gentle and are accustomed to hearing the report of a .22"',
    '"all of his reports are twenty-somethings with no concept of proper attire for work"',
    '"whatsoever things are lovely and of good report"',
]
export const synonyms = [
    'announce',
    'describe',
    'tell of',
    'detail',
    'delineate',
    'outline',
    'communicate',
    'pass on',
    'relay',
    'divulge',
    'disclose',
    'reveal',
    'publish',
    'circulate',
    'set out',
    'set forth',
    'put out',
    'post',
    'broadcast',
    'blazon',
    'herald',
    'proclaim',
    'declare',
    'publicize',
    'promulgate',
    'document',
    'record',
    'chronicle',
    'adumbrate',
    'give an account of',
    'make public',
    'investigate',
    'look into',
    'survey',
    'research',
    'study',
    'cover',
    'describe',
    'write up',
    'inquire into',
    'write about',
    'write an account of',
    'broadcast details of',
    'give details of',
    'commentate on',
    'supposed',
    'so-called',
    'claimed',
    'professed',
    'purported',
    'ostensible',
    'apparent',
    'putative',
    'unproven',
    'rumored',
    'reputed',
    'presumed',
    'assumed',
    'reported',
    'declared',
    'stated',
    'avowed',
    'described',
    'accuse',
    'make a complaint against',
    'make a charge against',
    'inform on',
    'tattle on',
    'delate on',
    'announce',
    'describe',
    'tell of',
    'detail',
    'delineate',
    'outline',
    'communicate',
    'pass on',
    'relay',
    'divulge',
    'disclose',
    'reveal',
    'publish',
    'circulate',
    'set out',
    'set forth',
    'put out',
    'post',
    'broadcast',
    'blazon',
    'herald',
    'proclaim',
    'declare',
    'publicize',
    'promulgate',
    'document',
    'record',
    'chronicle',
    'adumbrate',
    'give an account of',
    'make public',
    'arrive',
    'appear',
    'turn up',
    'clock in',
    'sign in',
    'come',
    'punch in',
    'present oneself',
    'make oneself known',
    'announce oneself',
    'be present',
    'clock on',
    'punch the (time) clock',
    'account',
    'review',
    'record',
    'description',
    'exposition',
    'statement',
    'delineation',
    'transactions',
    'proceedings',
    'transcripts',
    'minutes',
    'compte rendu',
    'procès-verbal',
    'story',
    'account',
    'description',
    'article',
    'piece',
    'item',
    'column',
    'feature',
    'write-up',
    'exposé',
    'bulletin',
    'communiqué',
    'dispatch',
    'communication',
    'assessment',
    'evaluation',
    'appraisal',
    'marks',
    'report card',
    'grades',
    'news',
    'information',
    'word',
    'intelligence',
    'intimation',
    'tidings',
    'advices',
    'rumor',
    'whisper',
    'bruit',
    'piece of gossip',
    'piece of hearsay',
    'on dit',
    'rumor',
    'whisper',
    'bruit',
    'piece of gossip',
    'piece of hearsay',
    'on dit',
    'bang',
    'blast',
    'crack',
    'pop',
    'shot',
    'gunshot',
    'explosion',
    'detonation',
    'boom',
    'crash',
    'noise',
    'sound',
    'echo',
    'reverberation',
    'reputation',
    'repute',
    'regard',
    'character',
    'name',
    'standing',
    'stature',
]