export const definitions = [
    '"he retired from the navy in 1966"',
    '"the Home Office retired him"',
    '"he retired from football several years ago"',
    '"Stewart retired hurt"',
    '"he was forced to retire to the bench"',
    '"the pitcher retired twelve batters in a row"',
    '"she retired into the bathroom with her toothbrush"',
    '"everyone retired early that night"',
    '"the judge finished his summing up and the jury retired"',
    '"lack of numbers compelled the cavalry to retire"',
    '"the general retired all his troops"',
    '"the debt is to be retired from state gaming-tax receipts"',
]
export const synonyms = [
    'give up work',
    'stop working',
    'stop work',
    'reach retirement age',
    'pension off',
    'force to retire',
    'force to give up work',
    'go off',
    'withdraw',
    'go out',
    'exit',
    'depart',
    'decamp',
    'adjourn',
    'repair',
    'go away',
    'make an exit',
    'take oneself off',
    'leave for',
    'shut oneself away in',
    'absent oneself',
    'betake oneself',
    'call it a day',
    'go to sleep',
    'go to bed',
    'go to one\'s room',
    'retreat',
    'withdraw',
    'pull back',
    'fall back',
    'pull out',
    'disengage',
    'back off',
    'give way',
    'give ground',
    'flee',
    'take flight',
    'turn tail',
    'beat a (hasty) retreat',
    'advance',
]