export const definitions = [
  '"Brenda was forced to reveal Robbie\'s whereabouts"',
  '"he revealed that he and his children had received death threats"',
  '"the clouds were breaking up to reveal a clear blue sky"',
  '"the truth revealed at the Incarnation"',
  '"the big reveal at the end of the movie answers all questions"',
  '"the gate can be easily fitted to the face or reveal of a window or door aperture"',
  '"the deep reveals of small square windows"',
];
export const synonyms = [
  'divulge',
  'disclose',
  'tell',
  'let out',
  'let fall',
  'give away',
  'babble',
  'give out',
  'release',
  'leak',
  'betray',
  'open up',
  'unveil',
  'broadcast',
  'air',
  'publicize',
  'publish',
  'circulate',
  'disseminate',
  'pass on',
  'report',
  'declare',
  'post',
  'communicate',
  'impart',
  'unfold',
  'vouchsafe',
  'confess',
  'admit',
  'discover',
  'let slip',
  'let drop',
  'give the game/show away',
  'blurt (out)',
  'bring out into the open',
  'go public on/with',
  'make known',
  'make public',
  'bring to public notice/attention',
  'lay bare',
  'hide',
  'conceal',
  'show',
  'display',
  'exhibit',
  'disclose',
  'uncover',
  'bare',
  'uncloak',
  'unclothe',
  'unclose',
  'expose to view',
  'allow to be seen',
  'put on display',
  'put on show',
  'put on view',
  'hide',
];