export const definitions = [
    '"Ruth listened to the rhythm of his breathing"',
    '"guitar melodies with deep African rhythms"',
    '"they\'ve got no rhythm"',
    '"the twice daily rhythms of the tides"',
]
export const synonyms = [
    'pattern',
    'flow',
    'tempo',
    'regular features',
    'recurrent nature',
    'beat',
    'cadence',
    'tempo',
    'time',
    'pace',
    'pulse',
    'throb',
    'lilt',
    'swing',
    'periodicity',
    'pattern',
    'flow',
    'tempo',
    'regular features',
    'recurrent nature',
    'meter',
    'measure',
    'pattern',
    'stress',
    'accent',
    'pulse',
    'time',
    'flow',
    'cadence',
    'pattern',
    'flow',
    'tempo',
    'regular features',
    'recurrent nature',
]