export const definitions = [
  '"he who knows not how to riddle"',
  '"riddle me this then"',
  '"his car was riddled by sniper fire"',
  '"the existing law is riddled with loopholes"',
  '"for final potting, the soil mixture is not riddled"',
  '"she heard Mr. Evans riddling the fire"',
];
export const synonyms = [
  'perforate',
  'hole',
  'pierce',
  'penetrate',
  'puncture',
  'honeycomb',
  'pepper',
  'prick',
  'gore',
  'transfix',
  'make/put/punch holes in',
  'bore through',
  'permeate',
  'suffuse',
  'fill',
  'pervade',
  'imbue',
  'inform',
  'charge',
  'saturate',
  'overrun',
  'take over',
  'overspread',
  'infiltrate',
  'run through',
  'invade',
  'beset',
  'pester',
  'plague',
  'spread through',
  'filter through',
  'be diffused through',
  'sieve',
  'sift',
  'strain',
  'screen',
  'filter',
  'purify',
  'refine',
  'winnow',
  'bolt',
  'griddle',
];