export const definitions = [
    '"the ridged sand of the beach"',
    '"a field ploughed in narrow stretches that are ridged up slightly"',
    '"the table\'s steel surface was ridged with a network of channels"',
    '"the crust of the earth ridged"',
]
export const synonyms = [
    'wrinkled',
    'wrinkly',
    'crinkled',
    'crumpled',
    'rumpled',
    'creased',
    'crimped',
    'corrugated',
    'fluted',
    'gathered',
    'puckered',
    'furrowed',
    'grooved',
    'rippled',
    'wavy',
    'kinked',
    'kinky',
]