export const definitions = [
    '"he riffled through the pages"',
    '"she opened a book with her thumbnail and riffled the pages"',
    '"she riffled through her leather handbag"',
    '"there was a slight breeze that riffled her hair"',
    '"just a riffle through the books"',
    '"the loudest sound was the constant riffle of paper as people looked at the agendas"',
    '"the river\'s sweeping riffles and deep pools provide a superb habitat for salmon"',
]
export const synonyms = [
    'flick through',
    'run through',
    'scan',
    'look through',
    'peruse',
    'thumb (through)',
    'leaf through',
    'skim through',
    'riffle through',
    'browse through',
    'dip into',
    'glance at/through',
    'read quickly',
    'have a quick look at',
    'run one\'s eye over',
    'give something a/the once-over',
    'pore over',
    'disarrange',
    'tousle',
    'dishevel',
    'rumple',
    'tumble',
    'disorder',
    'mess up',
    'make a mess of',
    'tangle',
    'ripple',
    'roughen',
    'run one\'s fingers through',
    'make untidy',
    'make ripples in',
    'smooth',
    'flick',
    'flip',
    'thumb',
    'skim',
    'browse',
    'glance',
    'look',
    'read',
    'scan',
    'peruse',
    'dip into',
    'run one\'s eye over',
    'have a look at',
]