export const definitions = [
    '"his risqué humor"',
]
export const synonyms = [
    'bawdy',
    'indecent',
    'ribald',
    'rude',
    'racy',
    'broad',
    'earthy',
    'Rabelaisian',
    'spicy',
    'suggestive',
    'titillating',
    'improper',
    'naughty',
    'indelicate',
    'indecorous',
    'off color',
    'locker-room',
    'vulgar',
    'dirty',
    'filthy',
    'smutty',
    'crude',
    'offensive',
    'salacious',
    'coarse',
    'obscene',
    'lewd',
    'pornographic',
    'X-rated',
]