export const definitions = [
  '"a rococo carved gilt mirror"',
  '"the rococo style"',
  '"his labyrinthine sentences and rococo usages"',
  '"rococo is alive and living in our hearts"',
];
export const synonyms = [
  'ornate',
  'fancy',
  'curlicued',
  'overelaborate',
  'extravagant',
  'baroque',
  'fussy',
  'busy',
  'ostentatious',
  'showy',
  'wedding-cake',
  'gingerbread',
  'flowery',
  'florid',
  'flamboyant',
  'high-flown',
  'high-sounding',
  'magniloquent',
  'grandiloquent',
  'orotund',
  'rhetorical',
  'oratorical',
  'bombastic',
  'overwrought',
  'overblown',
  'overripe',
  'overdone',
  'convoluted',
  'turgid',
  'inflated',
  'tumid',
  'pleonastic',
  'euphuistic',
  'aureate',
  'Ossianic',
  'fustian',
  'hyperventilated',
  'very elaborate',
  'plain',
  'simple',
];