export const definitions = [
  '"the wheel continued to rotate"',
  '"the small directional side rockets rotated the craft"',
  '"the job of chairing the meeting rotates"',
  '"these crops were sometimes rotated with grass"',
];
export const synonyms = [
  'revolve',
  'go around',
  'turn',
  'turn around',
  'spin',
  'gyrate',
  'wheel',
  'whirl',
  'twirl',
  'swivel',
  'circle',
  'pirouette',
  'pivot',
  'reel',
  'move around',
  'alternate',
  'take turns',
  'trade places',
  'change',
  'switch',
  'interchange',
  'exchange',
  'swap',
  'take it in turns',
  'work/act in sequence',
  'pass from one to another in rotation',
  'move around',
];