export const definitions = [
    '"rotten eggs"',
    '"the supporting beams were rotten"',
    '"he believed that the whole art business was rotten"',
    '"she was a rotten cook"',
    '"he\'s had rotten luck this year"',
    '\'s \'s rotten for you having to cope on your own"',
    '"she tried to tell me she felt rotten"',
    '"your mother said that I spoiled you rotten"',
]
export const synonyms = [
    'decaying',
    'decayed',
    'rotting',
    'bad',
    'off',
    'decomposed',
    'decomposing',
    'putrid',
    'putrescent',
    'spoiled',
    'spoilt',
    'tainted',
    'perished',
    'moldy',
    'moldering',
    'mildewy',
    'sour',
    'rancid',
    'rank',
    'festering',
    'fetid',
    'stinking',
    'smelly',
    'addled',
    'maggoty',
    'worm-eaten',
    'wormy',
    'flyblown',
    'disintegrating',
    'crumbling',
    'corroding',
    'carious',
    'black',
    'unfit for human consumption',
    'falling to pieces',
    'caried',
    'fresh',
    'sound',
    'corrupt',
    'unprincipled',
    'dishonest',
    'dishonorable',
    'unscrupulous',
    'untrustworthy',
    'immoral',
    'villainous',
    'bad',
    'wicked',
    'evil',
    'sinful',
    'iniquitous',
    'vicious',
    'base',
    'amoral',
    'debauched',
    'degenerate',
    'dissolute',
    'dissipated',
    'depraved',
    'perverted',
    'wanton',
    'venal',
    'nasty',
    'unkind',
    'unpleasant',
    'foul',
    'obnoxious',
    'vile',
    'contemptible',
    'despicable',
    'wretched',
    'shabby',
    'spiteful',
    'mean',
    'malicious',
    'poisonous',
    'mean-spirited',
    'cruel',
    'hateful',
    'hurtful',
    'unfair',
    'uncharitable',
    'below the belt',
    'unacceptable',
    'unwarranted',
    'uncalled for',
    'honorable',
    'decent',
    'incorruptible',
    'nice',
    'pleasant',
    'kind',
    'bad',
    'poor',
    'dreadful',
    'awful',
    'terrible',
    'frightful',
    'atrocious',
    'hopeless',
    'inadequate',
    'inferior',
    'unsatisfactory',
    'laughable',
    'substandard',
    'wretched',
    'horrible',
    'unspeakable',
    'good',
    'accomplished',
    'unpleasant',
    'disagreeable',
    'miserable',
    'awful',
    'dreadful',
    'terrible',
    'frightful',
    'bad',
    'vile',
    'grim',
    'horrid',
    'horrible',
    'ghastly',
    'disappointing',
    'regrettable',
    'unfortunate',
    'unlucky',
    'delightful',
    'good',
    'nice',
    'ill',
    'unwell',
    'poorly',
    'bad',
    'out of sorts',
    'indisposed',
    'sick',
    'queasy',
    'nauseous',
    'nauseated',
    'peaky',
    'liverish',
    'green around the gills',
    'run down',
    'washed out',
    'faint',
    'dizzy',
    'giddy',
    'lightheaded',
    'off',
    'off colour',
    'queer',
    'seedy',
    'peaked',
    'not oneself',
    'peakish',
    'well',
    'okay',
    'a great deal',
    'really',
    'very much',
    'a lot',
]