export const definitions = [
    '"art for a purpose, not for its own sake, was his rubric"',
    '"such ideas fall naturally under the rubric of postmodernism"',
]
export const synonyms = [
    'title',
    'caption',
    'legend',
    'subtitle',
    'subheading',
    'wording',
    'inscription',
    'name',
    'headline',
    'banner headline',
    'ritual',
    'worship',
    'service',
    'ceremony',
    'rite',
    'observance',
    'celebration',
    'ordinance',
    'office',
    'sacrament',
    'solemnity',
    'ceremonial',
    'formulation',
    'form',
    'custom',
    'practice',
    'tradition',
]