export const definitions = [
  '"she had been rude to her boss"',
  '"he is a rude and arrogant bully"',
  '"it\'s rude to talk about people right in front of them"',
  '"Graham giggled at every rude joke"',
  '"the war came as a very rude awakening"',
  '"Isabel had always been in rude health"',
  '"a rude coffin"',
  '"the new religion was first promulgated by rude men"',
];
export const synonyms = [
  'ill-mannered',
  'bad-mannered',
  'impolite',
  'discourteous',
  'impertinent',
  'insolent',
  'impudent',
  'cheeky',
  'audacious',
  'presumptuous',
  'uncivil',
  'disrespectful',
  'unmannerly',
  'ill-bred',
  'churlish',
  'crass',
  'curt',
  'brusque',
  'blunt',
  'ungracious',
  'graceless',
  'brash',
  'unpleasant',
  'disagreeable',
  'offhand',
  'short',
  'sharp',
  'offensive',
  'insulting',
  'derogatory',
  'disparaging',
  'abusive',
  'tactless',
  'undiplomatic',
  'uncomplimentary',
  'uncharitable',
  'ungentlemanly',
  'unladylike',
  'malapert',
  'contumelious',
  'underbred',
  'mannerless',
  'unchivalrous',
  'ungallant',
  'polite',
  'civil',
  'chivalrous',
  'vulgar',
  'coarse',
  'smutty',
  'dirty',
  'filthy',
  'crude',
  'lewd',
  'obscene',
  'offensive',
  'indelicate',
  'improper',
  'indecorous',
  'salacious',
  'off color',
  'tasteless',
  'risqué',
  'naughty',
  'ribald',
  'bawdy',
  'racy',
  'broad',
  'spicy',
  'colorful',
  'suggestive',
  'in bad taste',
  'clean',
  'abrupt',
  'sudden',
  'sharp',
  'startling',
  'unpleasant',
  'disagreeable',
  'nasty',
  'harsh',
  'primitive',
  'crude',
  'rudimentary',
  'rough',
  'rough-hewn',
  'rough and ready',
  'simple',
  'basic',
  'makeshift',
  'sophisticated',
  'classy',
  'ignorant',
  'unenlightened',
  'uneducated',
  'unschooled',
  'untutored',
  'illiterate',
  'unlettered',
  'unlearned',
  'unscholarly',
  'unread',
  'uninformed',
  'backward',
  'simple',
  'primitive',
  'uncivilized',
  'unsophisticated',
  'unrefined',
  'uncouth',
  'unpolished',
  'uncultured',
  'philistine',
  'barbarian',
  'barbaric',
  'barbarous',
  'savage',
  'crude',
  'coarse',
  'rough',
  'vulgar',
  'gross',
  'nescient',
  'enlightened',
];