export const definitions = [
    '"a ruined castle"',
    '"his ruined career"',
    '"the nation\'s ruined economy"',
    '"the castle was ruined when dynamite was used to demolish one of the corner towers"',
    '"a noisy freeway has ruined village life"',
    '"they were ruined by the highest interest rates this century"',
    '"carriages go ruining over the brink from time to time"',
]
export const synonyms = [
    'derelict',
    'in ruins',
    'dilapidated',
    'ruinous',
    'tumbledown',
    'ramshackle',
    'broken-down',
    'decrepit',
    'crumbling',
    'decaying',
    'disintegrating',
    'neglected',
    'blasted',
    'gone to rack and ruin',
    'in disrepair',
    'falling to pieces',
    'falling apart',
    'uncared-for',
    'intact',
    'well maintained',
    'destroyed',
    'in ruins',
    'over',
    'finished',
    'at an end',
    'in pieces',
    'in ashes',
    'falling down about one\'s ears',
    'flourishing',
    'derelict',
    'in ruins',
    'dilapidated',
    'ruinous',
    'tumbledown',
    'ramshackle',
    'broken-down',
    'decrepit',
    'crumbling',
    'decaying',
    'disintegrating',
    'neglected',
    'blasted',
    'destroy',
    'devastate',
    'ravage',
    'raze',
    'demolish',
    'blast',
    'wreck',
    'wipe out',
    'flatten',
    'level',
    'crush',
    'waste',
    'gone to rack and ruin',
    'in disrepair',
    'falling to pieces',
    'falling apart',
    'uncared-for',
    'lay waste',
    'leave in ruins',
    'wreak havoc on',
    'leave desolate',
    'intact',
    'rebuild',
    'repair',
    'well maintained',
    'destroyed',
    'in ruins',
    'over',
    'finished',
    'at an end',
    'wreck',
    'destroy',
    'devastate',
    'damage',
    'spoil',
    'mar',
    'injure',
    'blast',
    'blight',
    'smash',
    'shatter',
    'dash',
    'torpedo',
    'scotch',
    'make a mess of',
    'mess up',
    'sabotage',
    'poison',
    'bring to naught',
    'in pieces',
    'in ashes',
    'falling down about one\'s ears',
    'wreak havoc on',
    'reduce to nothing',
    'flourishing',
    'restore',
    'save',
    'bankrupt',
    'impoverish',
    'bring someone to their knees',
    'wipe out',
    'break',
    'cripple',
    'pauperize',
    'beggar',
    'make bankrupt',
    'cause to go bankrupt',
    'make insolvent',
    'reduce to penury/destitution',
    'bring to ruin',
]