export const definitions = [
    '"our food is about to run out"',
    '"we\'ve run out of gasoline"',
    '"her contract runs out at the end of the year"',
    '"slowly, he let the cables run out"',
    '"a row of buildings ran out to Cityline Avenue"',
    '"slight runout in your drill can make the holes oversized"',
    '"I skied the trail\'s long runout to the bottom and found the familiar yellow bus waiting"',
]
export const synonyms = [
    'dry up',
    'give out',
    'fail',
    'exhaust',
    'be used up',
    'be exhausted',
    'be finished',
    'peter out',
    'be plentiful',
    'use up',
    'consume',
    'eat up',
    'have none left',
    'have no more of',
    'be out of',
    'exhaust one\'s supply of',
    'sell out of',
    'expire',
    'come to an end',
    'end',
    'terminate',
    'finish',
    'lapse',
    'be no longer valid',
]