export const definitions = [
  '"sacred rites"',
  '"the site at Eleusis is sacred to Demeter"',
  '"sacred music"',
  '"a sacred Hindu text"',
  '"an animal sacred to Mexican culture"',
  '"a profit-oriented public to whom nothing is sacred"',
];
export const synonyms = [
  'holy',
  'hallowed',
  'blessed',
  'blest',
  'consecrated',
  'sanctified',
  'dedicated',
  'venerated',
  'revered',
  'cursed',
  'unconsecrated',
  'religious',
  'spiritual',
  'devotional',
  'church',
  'churchly',
  'ecclesiastical',
  'secular',
  'profane',
  'holy',
  'consecrated',
  'sanctified',
  'blessed',
  'blest',
  'revered',
  'reverenced',
  'venerated',
  'honored',
  'sacrosanct',
  'worshipped',
  'divine',
  'inviolable',
  'cursed',
  'sacrosanct',
  'inviolable',
  'inviolate',
  'unimpeachable',
  'invulnerable',
  'untouchable',
  'inalienable',
  'protected',
  'defended',
  'secure',
  'safe',
  'unthreatened',
];