export const definitions = [
    '"one week on safari"',
]
export const synonyms = [
    'journeys',
    'expeditions',
    'trips',
    'tours',
    'excursions',
    'voyages',
    'treks',
    'safaris',
    'odysseys',
    'pilgrimages',
    'jaunts',
    'journeying',
    'traveling',
    'touring',
    'sightseeing',
    'voyaging',
    'cruising',
    'sailing',
    'backpacking',
    'globetrotting',
    'jet-setting',
    'exploration',
    'trekking',
    'wandering',
    'roving',
    'roaming',
    'peregrinations',
]