export const definitions = [
  '"he raises his arms in a triumphant salute"',
  '"he stood to attention but did not return the salute"',
  '"he acknowledged the salute of the policeman on duty"',
  '"a twenty-one-gun salute"',
  '"don\'t you usually salute a superior officer ? "',
  '"he clicked his heels and saluted"',
  '"he saluted her with a smile"',
  '"we salute a truly great photographer"',
  '"they saluted him king when he entered into Jerusalem"',
];
export const synonyms = [
  'greeting',
  'salutation',
  'address',
  'hail',
  'welcome',
  'tribute',
  'wave',
  'homage',
  'obeisance',
  'acknowledgment',
  'gesture of respect',
  'greet',
  'address',
  'hail',
  'welcome',
  'acknowledge',
  'toast',
  'accost',
  'pay one\'s respects to',
  'make obeisance to',
  'wave to',
  'honor',
  'recognize',
  'celebrate',
  'acknowledge',
  'take one\'s hat off to',
  'pay tribute to',
  'pay homage to',
];