export const definitions = [
  '"investigations involved analyzing samples of handwriting"',
  '"a urine sample"',
  '"bone marrow cells were sampled"',
  '"a survey of two hundred randomly sampled households"',
  '"sample the pleasures of Saint Maarten"',
];
export const synonyms = [
  'representative',
  'illustrative',
  'selected',
  'specimen',
  'test',
  'trial',
  'typifying',
  'typical',
  'specimen',
  'example',
  'bit',
  'snippet',
  'illustration',
  'demonstration',
  'exemplification',
  'instance',
  'selection',
  'model',
  'prototype',
  'pattern',
  'dummy',
  'swatch',
  'pilot',
  'trailer',
  'trial',
  'indication',
  'foretaste',
  'taste',
  'taster',
  'tester',
  'smear',
  'scantling',
  'representative piece',
  'test piece',
  'cross section',
  'variety',
  'sampling',
  'test',
  'try out',
  'try',
  'taste',
  'sip',
  'nibble',
  'test',
  'experience',
  'inspect',
  'examine',
  'check out',
  'appraise',
  'evaluate',
  'put to the test',
  'dip into',
  'experiment with',
];