export const definitions = [
    '"fresh pineapple is useful in savory as well as in sweet dishes"',
    '"she carried in a pie from the kitchen, steaming and savory"',
    '"everyone knew it was a front for less savory operations"',
    '"refreshments include cakes and savories"',
]
export const synonyms = [
    'salty',
    'spicy',
    'piquant',
    'tangy',
    'sweet',
    'acceptable',
    'pleasant',
    'palatable',
    'wholesome',
    'respectable',
    'honorable',
    'proper',
    'seemly',
    'creditable',
    'unpleasant',
    'unacceptable',
    'dishonorable',
    'canapé',
    'hors d\'oeuvre',
    'appetizer',
    'tidbit',
    'amuse-gueule',
]