export const definitions = [
    '"this is stated in the sayings of the Prophet"',
    '"\"Thank you,\" he said"',
    '"he said the fund stood at $100,000"',
    '"our parents wouldn\'t believe a word we said"',
    '"he said to come early"',
    '"the law says such behavior is an offense"',
    '"I don\'t want to say too much"',
    '"the movie\'s title says it all"',
    '"the clock says ten past two"',
    '"they were said to be training freedom fighters"',
    '"it is said that she lived to be over a hundred"',
    '"all I can say for him is that he\'s a better writer than some"',
    '"we say the Pledge of Allegiance each morning"',
    '"let\'s say we pay five thousand dollars in the first year"',
    '"the form might include, say, a dozen questions"',
]
export const synonyms = [
    'proverb',
    'maxim',
    'aphorism',
    'axiom',
    'adage',
    'saw',
    'tag',
    'motto',
    'precept',
    'epigram',
    'epigraph',
    'dictum',
    'gnome',
    'pearl of wisdom',
    'expression',
    'phrase',
    'formula',
    'slogan',
    'catchphrase',
    'platitude',
    'cliché',
    'commonplace',
    'truism',
    'apothegm',
    'speak',
    'utter',
    'voice',
    'pronounce',
    'give voice to',
    'vocalize',
    'declare',
    'state',
    'announce',
    'remark',
    'observe',
    'mention',
    'comment',
    'note',
    'add',
    'reply',
    'respond',
    'answer',
    'rejoin',
    'whisper',
    'mutter',
    'mumble',
    'mouth',
    'claim',
    'maintain',
    'assert',
    'hold',
    'insist',
    'contend',
    'aver',
    'affirm',
    'avow',
    'allege',
    'profess',
    'opine',
    'asseverate',
    'express',
    'phrase',
    'articulate',
    'communicate',
    'get across',
    'put across',
    'convey',
    'verbalize',
    'render',
    'tell',
    'reveal',
    'divulge',
    'impart',
    'disclose',
    'imply',
    'suggest',
    'signify',
    'denote',
    'mean',
    'adduce',
    'propose',
    'advance',
    'bring forward',
    'offer',
    'plead',
    'give utterance to',
    'put into words',
    'make known',
    'indicate',
    'show',
    'read',
    'apparently',
    'seemingly',
    'by all accounts',
    'be reported',
    'be thought',
    'be believed',
    'be alleged',
    'be rumored',
    'be reputed',
    'be put around',
    'be described',
    'be asserted',
    'it seems that',
    'it appears that',
    '(so) they say',
    '(so) the story goes',
    'rumor has it',
    'the rumor is',
    'recite',
    'repeat',
    'utter',
    'deliver',
    'perform',
    'declaim',
    'orate',
    'suppose',
    'assume',
    'imagine',
    'presume',
    'hypothesize',
    'postulate',
    'posit',
    'take as a hypothesis',
]