export const definitions = [
    '"a schema of scientific reasoning"',
]
export const synonyms = [
    'plot',
    'outline',
    'storyline',
    'framework',
    'structure',
    'scheme',
    'plan',
    'layout',
    'screenplay',
    'script',
    'synopsis',
    'summary',
    'precis',
    'diegesis',
    'arrangement',
    'system',
    'organization',
    'configuration',
    'pattern',
    'format',
    'layout',
    'disposition',
]