export const definitions = [
    '"a clever marketing scheme"',
    '"police uncovered a scheme to steal paintings worth more than $250,000"',
    '"a classical rhyme scheme"',
    '"the whole scheme is plunged into darkness, bar the light in Victor\'s house"',
    '"he schemed to bring about the collapse of the government"',
]
export const synonyms = [
    'plan',
    'project',
    'plan of action',
    'program',
    'strategy',
    'stratagem',
    'game plan',
    'enterprise',
    'venture',
    'measure',
    'move',
    'course of action',
    'system',
    'procedure',
    'design',
    'formula',
    'recipe',
    'device',
    'tactic',
    'contrivance',
    'proposal',
    'proposition',
    'suggestion',
    'idea',
    'blueprint',
    'shift',
    'line of action',
    'plot',
    'intrigue',
    'conspiracy',
    'ruse',
    'ploy',
    'stratagem',
    'maneuver',
    'subterfuge',
    'machinations',
    'secret plan',
    'arrangement',
    'system',
    'organization',
    'configuration',
    'pattern',
    'format',
    'layout',
    'disposition',
    'schema',
    'plot',
    'conspire',
    'intrigue',
    'connive',
    'maneuver',
    'plan',
    'machinate',
    'cabal',
    'hatch a plot',
    'take part in a conspiracy',
    'lay plans',
    'complot',
]