export const definitions = [
  '"Ryder\'s children did not go to school at all"',
  '"school supplies"',
  '"the cost of building a new school"',
  '"the principal was addressing the whole school"',
  '"school started at 7 a.m"',
  '"a dancing school"',
  '"Harvard is certainly not a loafer\'s school"',
  '"the School of Dental Medicine"',
  '"the Frankfurt school of critical theory"',
  '"filmmakers are tired of the skin-deep school of cinema"',
  '"he was schooled in Boston"',
  '"he schooled her in horsemanship"',
  '"it\'s important to school yourself to be good at exams"',
  '"a school of dolphins"',
  '"gray snapper schooled in shallow lagoons"',
];
export const synonyms = [
  'academy',
  'college',
  'alma mater',
  'educational institution',
  'center of learning',
  'phrontistery',
  'department',
  'faculty',
  'division',
  'group',
  'set',
  'circle',
  'clique',
  'faction',
  'sect',
  'followers',
  'following',
  'disciples',
  'apostles',
  'pupils',
  'students',
  'admirers',
  'devotees',
  'votaries',
  'proponents',
  'adherents',
  'imitators',
  'copiers',
  'emulators',
  'epigones',
  'school of thought',
  'persuasion',
  'creed',
  'credo',
  'doctrine',
  'belief',
  'faith',
  'outlook',
  'opinion',
  'point of view',
  'denomination',
  'approach',
  'method',
  'style',
  'way of thinking',
  'educate',
  'teach',
  'instruct',
  'train',
  'teach',
  'tutor',
  'coach',
  'instruct',
  'upskill',
  'drill',
  'discipline',
  'direct',
  'guide',
  'prepare',
  'groom',
  'mold',
  'shape',
  'form',
  'prime',
  'verse',
  'indoctrinate',
  'inculcate',
];