export const definitions = [
  '"a room with a red carpet and screens with elaborate decoration"',
  '"his jeep was discreetly parked behind a screen of trees"',
  '"the article is using science as a screen for unexamined prejudice"',
  '"the chancel screen retains two sections of the original oak arcading"',
  '"a screen door"',
  '"a television screen"',
  '"the world\'s largest movie screen"',
  '"\'s \'s a star of the stage as well as the screen"',
  '"he is interviewed on screen"',
  '"pressing the F1 key at any time will display a help screen"',
  '"HMS Prince Leopold and HMS Prince Charles sailed for Shetland with a screen of four destroyers"',
  '"the material retained on each sieve screen is weighed in turn"',
  '"her hair swung across to screen her face"',
  '"a high hedge screened all of the front from passersby"',
  '"an area had been screened off as a waiting room"',
  '"in my country a man of my rank would be screened completely from any risk of attack"',
  '"ensure that your microphone leads are properly screened from hum pickup"',
  '"the show is to be screened by HBO later this year"',
  '"outpatients were screened for cervical cancer"',
  '"all prospective presidential candidates would have to be screened by the committee"',
  '"only one percent of rainforest plants have been screened for medical use"',
  '"anti-spam software can screen out large amounts of unwanted email"',
  '"granulated asphalt—manufactured to 40 mm down or screened to 28 mm & 14 mm down"',
];
export const synonyms = [
  'partition',
  '(room) divider',
  'separator',
  'curtain',
  'arras',
  'blind',
  'awning',
  'shade',
  'shutter',
  'canopy',
  'windbreak',
  'dividing wall',
  'buffer',
  'protection',
  'shield',
  'shelter',
  'guard',
  'safeguard',
  'mesh',
  'net',
  'netting',
  'display',
  'monitor',
  'cathode-ray tube',
  'CRT',
  'visual display unit',
  'VDU',
  'sieve',
  'riddle',
  'sifter',
  'strainer',
  'colander',
  'filter',
  'winnow',
  'griddle',
  'conceal',
  'hide',
  'mask',
  'shield',
  'shelter',
  'shade',
  'protect',
  'guard',
  'safeguard',
  'veil',
  'cloak',
  'camouflage',
  'disguise',
  'partition off',
  'divide off',
  'separate off',
  'curtain off',
  'show',
  'present',
  'air',
  'broadcast',
  'transmit',
  'televise',
  'put out',
  'telecast',
  'relay',
  'put on the air',
  'vet',
  'check',
  'check up on',
  'check out',
  'evaluate',
  'assess',
  'scrutinize',
  'test',
  'examine',
  'investigate',
  'scan',
  'sieve',
  'riddle',
  'sift',
  'strain',
  'filter',
  'sort',
  'winnow',
  'bolt',
  'griddle',
];