export const definitions = [
  '"they could hear him screaming in pain"',
  '"I ran to the house screaming for help"',
  '"\"Get out!\" he screamed"',
  '"he screamed abuse into the phone"',
  '"his supporters scream that he is being done an injustice"',
  '"the creative side of me is screaming out for attention"',
  '"sirens were screaming from all over the city"',
  '"a shell screamed overhead"',
  '"they were awakened by screams for help"',
  '"the screams of the seagulls"',
  '"the scream of a falling bomb"',
  '"the movie\'s a scream"',
];
export const synonyms = [
  'shriek',
  'screech',
  'yell',
  'howl',
  'shout',
  'bellow',
  'bawl',
  'cry out',
  'call out',
  'yawp',
  'yelp',
  'squeal',
  'wail',
  'squawk',
  'squall',
  'caterwaul',
  'whoop',
  'whisper',
  'shriek',
  'screech',
  'yell',
  'howl',
  'shout',
  'bellow',
  'bawl',
  'cry',
  'yawp',
  'yelp',
  'squeal',
  'wail',
  'squawk',
  'squall',
  'caterwaul',
  'whoop',
  'whisper',
  'laugh',
  'hoot',
  'comedy',
  'wit',
  'comedian',
  'comic',
  'entertainer',
  'joker',
  'clown',
  'buffoon',
  'bore',
];