export const definitions = [
    '"I have scrimped and saved to give you a good education"',
]
export const synonyms = [
    'economize',
    'skimp',
    'save',
    'tighten one\'s belt',
    'cut back',
    'budget',
    'retrench',
    'pinch pennies',
    'be (more) economical',
    'make economies',
    'scrimp and scrape',
    'be thrifty',
    'be frugal',
    'make cutbacks',
    'husband one\'s resources',
    'cut costs',
    'cut expenditure',
    'draw in one\'s horns',
    'watch \'s \'s pennies',
    'look after the pence',
    'rake and scrape',
    'spend',
]