export const definitions = [
    '"pedestrians scurried for cover"',
    '"I was in such a scurry"',
]
export const synonyms = [
    'scamper',
    'scuttle',
    'bustle',
    'skip',
    'trot',
    'hurry',
    'hasten',
    'make haste',
    'rush',
    'race',
    'dash',
    'run',
    'sprint',
    'scutter',
    'amble',
    'stroll',
    'rush',
    'race',
    'dash',
    'run',
    'sprint',
    'scamper',
    'scampering',
    'scuttle',
    'scuttling',
    'scramble',
    'scrambling',
    'bustle',
    'bustling',
    'trot',
    'hurry',
    'scutter',
    'scuttering',
    'stroll',
]