export const definitions = [
    '"the rainy season"',
    '"the season for gathering pine needles"',
    '"basketball season is over"',
    '"the pies are made with fruit that is in season"',
    '"lobster season"',
    '"to everything there is a season"',
    '"this most beautiful soul; who walked with me for a season in this world"',
    '"the first two seasons of the show"',
    '"the bitch can come into season at irregular intervals"',
    '"season the soup to taste with salt and pepper"',
    '"his conversation is seasoned liberally with exclamation points and punch lines"',
    '"I collect and season most of my wood"',
]
export const synonyms = [
    'period',
    'time',
    'spell',
    'term',
    'phase',
    'stage',
    'active period',
    'time of year',
    'available',
    'obtainable',
    'on offer',
    'on the market',
    'growing',
    'common',
    'plentiful',
    'abundant',
    'readily available/obtainable',
    'to be had',
    'out of season',
    'flavor',
    'spice',
    'add flavoring to',
    'add salt/pepper to',
    'add spices/herbs to',
    'enliven',
    'leaven',
    'enrich',
    'animate',
    'augment',
    'add spice to',
    'liven up',
    'mature',
    'age',
    'mellow',
    'condition',
    'acclimatize',
    'temper',
    'prepare',
    'prime',
    'ripen',
]