export const definitions = [
    '"operations in the southern sector of the North Sea"',
    '"the industrial and commercial sector"',
    '"the business sector of the city"',
]
export const synonyms = [
    'district',
    'quarter',
    'part',
    'section',
    'zone',
    'precinct',
    'borough',
    'locality',
    'neighborhood',
    'side',
    'province',
    'territory',
    'division',
    'region',
    'area',
    'belt',
    'tract',
    'locale',
    'part',
    'branch',
    'arm',
    'division',
    'subdivision',
    'area',
    'department',
    'category',
    'field',
    'sphere',
    'layer',
    'stratum',
    'corner',
]