export const definitions = [
    '"a lawyer had seduced a female client"',
    '"they should not be seduced into thinking that their success ruled out the possibility of a relapse"',
    '"the melody seduces the ear with warm string tones"',
]
export const synonyms = [
    'corrupt',
    'deprave',
    'ravish',
    'deflower',
    'dishonor',
    'ruin',
    'persuade someone to have sex',
    'take away someone\'s innocence',
    'lead astray',
    'attract',
    'allure',
    'lure',
    'tempt',
    'entice',
    'beguile',
    'cajole',
    'wheedle',
    'ensnare',
    'charm',
    'captivate',
    'enchant',
    'hypnotize',
    'mesmerize',
    'tantalize',
    'titillate',
    'bewitch',
    'ravish',
    'inveigle',
    'trap',
    'maneuver',
    'deceive',
    'dupe',
    'lead astray',
]