export const definitions = [
  '"the brew foamed and seethed"',
  '"others were cut into joints and seethed in cauldrons made of the animal\'s own skins"',
  '"inwardly he was seething at the slight to his authority"',
  '"the entire cellar was seething with spiders"',
  '"the village seethed with life"',
  '"we cascaded down the stairs and seethed across the station"',
];
export const synonyms = [
  'boil',
  'bubble',
  'simmer',
  'foam',
  'froth',
  'rise',
  'ferment',
  'fizz',
  'effervesce',
  'teem',
  'swarm',
  'swirl',
  'convulse',
  'churn',
  'whirl',
  'surge',
  'boil',
  'simmer',
  'chafe',
  'rage',
  'rant',
  'rave',
  'rant and rave',
  'storm',
  'fume',
  'smolder',
  'spit',
  'breathe fire',
  'burn',
  'be angry',
  'be furious',
  'be enraged',
  'be incensed',
  'be infuriated',
  'be beside oneself',
  'have lost one\'s temper',
  'have/throw a fit',
  'be boiling over',
  'be in a rage',
];