export const definitions = [
    '"spectacular views of mountain scenery"',
]
export const synonyms = [
    'landscape',
    'countryside',
    'country',
    'terrain',
    'topography',
    'setting',
    'surroundings',
    'environment',
    'view',
    'vista',
    'panorama',
    'prospect',
    'outlook',
    'cityscape',
    'townscape',
    'riverscape',
    'seascape',
    'waterscape',
    'snowscape',
    'roofscape',
    'set',
    'flats',
    'backdrop',
    'drop curtain',
    'setting',
    'background',
    'decor',
    'coulisse',
    'mise en scène',
    'stage set',
    'backcloth',
]