export const definitions = [
  '"senior citizens"',
  '"Henry James senior"',
  '"he is a senior Finance Ministry official"',
  '"the people senior to me in my department"',
  '"she was only two years his senior"',
  '"the price is $7 for adults and $3.50 for seniors"',
  '"among the pupils was a senior, a boy of about seventeen"',
  '"at fourteen you move up to the seniors"',
];
export const synonyms = [
  'older',
  'elder',
  'more grown up',
  'junior',
  'younger',
  'major',
  'I',
  'the Elder',
  '(the First)',
  'higher-ranking',
  'highest-ranking',
  'high-ranking',
  'superior',
  'top',
  'chief',
  'high-status',
  'ranking',
  'more/most important',
  'junior',
  'subordinate',
  'pensioner',
  'elder',
  'Methuselah',
  'patriarch',
  'retiree',
  'golden ager',
  'senex',
  'retirer',
  'pensionary',
  'retired person',
  'old-age pensioner',
  'OAP',
  'old person',
  'elderly person',
  'superannuitant',
];