export const definitions = [
    '"the explosion was the latest in a series of accidents"',
    '"he gave a series of lectures on modern art"',
    '"the first four books in the Toybox Science series"',
    '"a series of travel books"',
    '"a playoff series against Portland"',
    '"early models of the 600D series incorporated a centrifugal oil filter"',
    '"a series III SWB Land Rover"',
    '"a series of five stamps issued today to mark the 14th World Orchid Conference"',
    '"a new drama series"',
    '"a series circuit"',
    '"the series connection of the two coils"',
    '"the Pliocene series"',
    '"the metals of the lanthanide series"',
    '"the voiced plosive series [b], [d], [g]"',
]
export const synonyms = [
    'sequence',
    'succession',
    'string',
    'chain',
    'concatenation',
    'train',
    'run',
    'chapter',
    'round',
    'progression',
    'procession',
    'spate',
    'wave',
    'stream',
    'rash',
    'outbreak',
    'set',
    'course',
    'cycle',
    'row',
    'line',
    'bank',
    'battery',
    'arrangement',
    'order',
    'program',
    'production',
    'serial',
    'situation comedy',
    'soap opera',
    'set of programs',
]