export const definitions = [
    '"Malcolm has served the church very faithfully"',
    '"a telecommunications company that serves southern New England"',
    '"a military engineer who served with the army"',
    '"he is serving a ten-year jail sentence"',
    '"they serve wine instead of beer"',
    '"serve white wines chilled"',
    '"Peter served them generous portions of soup"',
    '"I\'ll serve you with coffee and cake"',
    '"the recipe serves four people"',
    '"she turned to serve the impatient customer"',
    '"I remember the trick you served me"',
    '"he said his lawyer would serve a writ to the multinational corporation within a week"',
    '"a warrant was served on Jack Sherman"',
    '"they were just about to serve him with a writ"',
    '"when they served her a writ, she lit the fire with it"',
    '"this book will serve a useful purpose"',
    '"the union came into existence to serve the interests of musicians"',
    '"sweat serves to cool down the body"',
    '"the island\'s one pub serves as a cafe by day"',
    '"the strategy served him well"',
    '"he tossed the ball up to serve"',
    '"serve the ball onto the front wall"',
    '"before long Lodge was the only man in his section able to serve the guns"',
]
export const synonyms = [
    'obey',
    'help',
    'assist',
    'aid',
    'do something for',
    'benefit',
    'succor',
    'work on',
    'sit on',
    'work for',
    'be in the service of',
    'perform duties for',
    'be employed by',
    'have a job with',
    'be obedient to',
    'carry out the wishes of',
    'be of service to',
    'be of use to',
    'give help to',
    'give assistance to',
    'lend a hand to',
    'give a helping hand to',
    'do a good turn to',
    'make a contribution to',
    'do one\'s bit for',
    'minister to',
    'be a member of',
    'be on',
    'have/hold a place on',
    'perform duties on',
    'carry out duties on',
    'oblige',
    'accommodate',
    'entertain',
    'receive',
    'handle',
    'see to',
    'look after',
    'provide for',
    'meet the needs/wants of',
    'deal with',
    'care for',
    'carry out',
    'perform',
    'do',
    'fulfill',
    'complete',
    'discharge',
    'spend',
    'go through',
    'give out',
    'distribute',
    'set out',
    'present',
    'provide',
    'supply',
    'dish up/out',
    'plate up',
    'spoon out',
    'ladle out',
    'make available',
    'wait',
    'act as waiter/waitress',
    'distribute food/refreshments',
    'see to',
    'assist',
    'help',
    'look after',
    'take care of',
    'attend to',
    'give one\'s attention to',
    'attend to the requirements of',
    'deal with',
    'deliver to',
    'present with',
    'give to',
    'hand over to',
    'cause to accept',
    'suffice',
    'do',
    'answer',
    'suit',
    'be adequate',
    'be good enough',
    'be all right',
    'fit/fill the bill',
    'be useful',
    'serve a purpose',
    'meet requirements',
    'act as',
    'do duty as',
    'function as',
    'fulfill the function of',
    'do the work of',
    'act as a substitute for',
    'treat',
    'handle',
    'deal with',
    'act toward',
    'behave toward',
    'conduct oneself toward',
]