export const definitions = [
    '"every effort was made to settle the dispute"',
    '"he sued for libel and then settled out of court"',
    '"the matter was settled out of court"',
    '"exactly what goes into the legislation has not been settled"',
    '"they had not yet settled on a date for the wedding"',
    '"it was too cold for champagne so they settled for a cup of tea"',
    '"his bill was settled by charge card"',
    '"I settled up with your brother for my board and lodging"',
    '"he offered to settle $150 a year on her"',
    '"one day I will settle down and raise a family"',
    '"in 1863 the family settled in London"',
    '"European immigrants settled much of Australia"',
    '"he had settled into his new job"',
    '"she settled in happily with a foster family"',
    '"Catherine settled down to her studies"',
    '"after a few months the controversy settled down"',
    '"try to settle your puppy down before going to bed"',
    '"he told me to hold my tongue or he would find a way to settle me"',
    '"he settled into an armchair"',
    '"she allowed him to settle her in the taxi"',
    '"she settled her bag on her shoulder"',
    '"dust from the mill had settled on the roof"',
    '"sediment settles near the bottom of the tank"',
    '"he pours a glass and leaves it on the bar to settle"',
    '"they listened to the soft ticking and creaking as the house settled"',
    '"the craft was settling nose-down in the water"',
    '"she read to her brother, who sat on the settle opposite her"',
]
export const synonyms = [
    'resolve',
    'sort out',
    'solve',
    'clear up',
    'fix',
    'work out',
    'iron out',
    'rectify',
    'remedy',
    'reconcile',
    'compose',
    'reach an agreement about',
    'find a solution to',
    'find an answer to',
    'bring to an end',
    'smooth over',
    'straighten out',
    'deal with',
    'put right',
    'set right',
    'put to rights',
    'prolong',
    'set',
    'fix',
    'name',
    'determine',
    'establish',
    'arrange',
    'appoint',
    'designate',
    'assign',
    'confirm',
    'choose',
    'select',
    'pick',
    'decide on',
    'come to a decision about',
    'agree on',
    'arrive at',
    'accept',
    'agree to',
    'accede to',
    'acquiesce in',
    'assent to',
    'compromise on',
    'pay',
    'discharge',
    'square',
    'clear',
    'defray',
    'liquidate',
    'satisfy',
    'pay in full',
    'settle up',
    'take up residence',
    'put down roots',
    'make one\'s home',
    'set up home',
    'establish oneself',
    'go to live',
    'move to',
    'emigrate to',
    'set up housekeeping in',
    'become domiciled in',
    'move away from',
    'colonize',
    'occupy',
    'people',
    'inhabit',
    'populate',
    'establish a colony in',
    'get down to',
    'set about',
    'attack',
    'apply oneself to',
    'turn one\'s attention to',
    'address oneself to',
    'set to work on',
    'begin to tackle',
    'concentrate on',
    'focus on',
    'devote oneself to',
    'relax',
    'calm',
    'soothe',
    'compose',
    'pacify',
    'lull',
    'subdue',
    'quell',
    'sedate',
    'tranquillize',
    'quieten',
    'quiet',
    'calm down',
    'be quiet',
    'be still',
    'quieten down',
    'quiet down',
    'agitate',
    'disturb',
    'sit down',
    'flump',
    'land',
    'come to rest',
    'come down',
    'alight',
    'light',
    'descend',
    'perch',
    'seat oneself',
    'install oneself',
    'plant oneself',
    'ensconce oneself',
    'plump oneself',
    'stand up',
    'take off',
    'tuck in',
    'bed down',
    'make comfortable',
    'sink',
    'subside',
    'fall',
    'gravitate',
    'precipitate out',
    'rise',
]