export const definitions = [
    '"I need to buy a hat for the shivoo next weekend"',
]
export const synonyms = [
    'gathering',
    'function',
    'get-together',
    'celebration',
    'reunion',
    'festivity',
    'jamboree',
    'reception',
    'at-home',
    'soirée',
    'social',
    'dance',
    'ball',
    'ceilidh',
    'frolic',
    'carousal',
    'carouse',
    'fete',
    'hoedown',
    'shower',
    'bake',
    'cookout',
    'levee',
    'keg party',
    'corroboree',
    'bashment',
    'luau',
    'simcha',
    'squash',
    'squeeze',
    'ding-dong',
    'social gathering',
    'social occasion',
    'social event',
    'social function',
    'tertulia',
]