export const definitions = [
    '"the workforce has shrunk to less than a thousand"',
    '"the sun had shrunk and dried the wood"',
    '"she wore a sweater which had shrunk slightly"',
    '"the metal is unsuitable for shrinking onto wooden staves"',
    '"she shrank away from him, covering her face"',
    '"he shrank back against the wall"',
    '"I don\'t shrink from my responsibilities"',
    '"you should see a shrink"',
]
export const synonyms = [
    'contract',
    'diminish',
    'lessen',
    'reduce',
    'decrease',
    'dwindle',
    'narrow',
    'shorten',
    'slim',
    'decline',
    'fall off',
    'drop off',
    'condense',
    'deflate',
    'shrivel',
    'wither',
    'truncate',
    'abbreviate',
    'concentrate',
    'abridge',
    'compress',
    'squeeze',
    'get smaller',
    'become/grow smaller',
    'make smaller',
    'slim down',
    'pare down',
    'expand',
    'increase',
    'draw back',
    'recoil',
    'pull back',
    'back away',
    'retreat',
    'withdraw',
    'flinch',
    'blench',
    'start',
    'wince',
    'cringe',
    'cower',
    'quail',
    'jump back',
    'spring back',
    'jerk back',
    'start back',
    'shy away',
    'recoil',
    'hang back',
    'demur',
    'flinch',
    'fight shy of',
    'shy away',
    'have scruples about',
    'scruple about',
    'have misgivings about',
    'have qualms about',
    'be loath to',
    'be reluctant to',
    'be unwilling to',
    'be disinclined to',
    'be indisposed to',
    'be sorry to',
    'be averse to',
    'be slow to',
    'be chary of',
    'not be in favor of',
    'be against',
    'be opposed to',
    'be hesitant to',
    'be diffident about',
    'be bashful about',
    'be shy about',
    'be coy about',
    'be ashamed to',
    'be afraid to',
    'hesitate to',
    'hate to',
    'not like to',
    'not have the heart to',
    'drag one\'s feet / heels over',
    'waver about',
    'vacillate about',
    'think twice about',
    'balk at',
    'quail at',
    'mind doing something',
    'disrelish something',
    'confront',
    'be eager to',
]