export const definitions = [
    '"a shrill laugh"',
    '"a concession to their shrill demands"',
    '"a piercing whistle shrilled through the night air"',
    '"\"For God\'s sake!\" shrilled Jan"',
    '"the shrill of a smoke detector filled the air"',
]
export const synonyms = [
    'high-pitched',
    'piercing',
    'high',
    'sharp',
    'ear-piercing',
    'ear-splitting',
    'penetrating',
    'shattering',
    'strident',
    'loud',
    'strong',
    'intrusive',
    'screeching',
    'shrieking',
    'screechy',
    'air-rending',
    'squawky',
    'low',
    'soft',
    'dulcet',
    'screech',
    'scream',
    'shriek',
    'squawk',
    'howl',
    'cry',
    'wail',
    'squall',
    'yawp',
    'yelp',
    'screech',
    'scream',
    'shriek',
    'squawk',
    'howl',
    'cry',
    'wail',
    'squall',
    'yawp',
    'yelp',
]