export const definitions = [
    '"none of her chaplains knew English or French enough to shrive the king"',
]
export const synonyms = [
    'pardon',
    'absolution',
    'exoneration',
    'remission',
    'dispensation',
    'indulgence',
    'understanding',
    'tolerance',
    'purgation',
    'clemency',
    'mercy',
    'pity',
    'lenience',
    'leniency',
    'quarter',
    'reprieve',
    'discharge',
    'amnesty',
    'delivery',
    'acquittal',
    'clearing',
    'pardoning',
    'condoning',
    'condonation',
    'vindication',
    'exculpation',
    'shrift',
    'shriving',
    'mercilessness',
    'punishment',
]