export const definitions = [
  '"he was buried in a linen shroud"',
  '"the trigger shroud prevents snagging on clothing"',
  '"a shroud of mist"',
  '"they operate behind a shroud of secrecy"',
  '"the body was washed and shrouded"',
  '"mountains shrouded by cloud"',
  '"the mystery that shrouds the origins of the universe"',
];
export const synonyms = [
  'winding sheet',
  'cerements',
  'chrisom',
  'grave clothes',
  'burial clothes',
  'covering',
  'cover',
  'pall',
  'cloak',
  'mask',
  'mantle',
  'blanket',
  'sheet',
  'layer',
  'overlay',
  'envelope',
  'cloud',
  'veil',
  'screen',
  'curtain',
  'canopy',
  'cover',
  'envelop',
  'veil',
  'cloak',
  'curtain',
  'swathe',
  'wrap',
  'blanket',
  'screen',
  'cloud',
  'mantle',
  'conceal',
  'hide',
  'disguise',
  'mask',
  'obscure',
  'surround',
  'overlay',
  'clothe',
  'enshroud',
];