export const definitions = [
  '"a silken ribbon"',
  '"silken hair"',
];
export const synonyms = [
  'thin',
  'light',
  'lightweight',
  'fine',
  'ultra-fine',
  'diaphanous',
  'sheer',
  'delicate',
  'insubstantial',
  'floaty',
  'filmy',
  'gossamer',
  'gossamer-thin',
  'gossamery',
  'gauzy',
  'gauze-like',
  'cobwebby',
  'feathery',
  'translucent',
  'transparent',
  'see-through',
  'transpicuous',
  'chiffony',
  'gossamer-like',
  'translucid',
  'thick',
  'smooth',
  'soft',
  'sleek',
  'lustrous',
  'fine',
  'glossy',
  'satiny',
  'velvety',
];