export const definitions = [
  '"a gravel cleaner that removes detritus without siphoning off water"',
  '"he\'s been siphoning money off the firm"',
];
export const synonyms = [
  'tube',
  'conduit',
  'hose',
  'main',
  'duct',
  'line',
  'channel',
  'canal',
  'conveyor',
  'pipeline',
  'drain',
  'tubing',
  'piping',
  'cylinder',
  'fistula',
  'convey',
  'channel',
  'run',
  'feed',
  'lead',
  'bring',
  'extract',
  'withdraw',
  'remove',
  'milk',
  'bleed',
  'tap',
  'void',
  'filter',
  'pour out',
  'tip',
  'discharge',
  'transfer',
  'draw off',
  'pump off',
  'siphon off',
  'pour off',
];