export const definitions = [
    '"I had nine brothers and sisters"',
    '"textile unions are showing solidarity with their brothers and sisters in the developing world"',
    '"uncloseted lesbian sisters"',
    '"brothers and sisters, holla if you feel this"',
    '"the sisters announced that there would be a special rosary every morning"',
    '"Sister Elizabeth, the headmistress of the Convent High School"',
    '"the ward sister needs to be consulted"',
    '"Sister nodded, glancing at the reports"',
    '"a sister ship"',
    '"Eastern\'s sister airline, Continental"',
]
export const synonyms = [
    'female sibling',
    'skin and blister',
    'comrade',
    'friend',
    'partner',
    'associate',
    'colleague',
    'nun',
    'novice',
    'abbess',
    'prioress',
    'Mother Superior',
    'Reverend Mother',
    'religious',
    'conventual',
    'contemplative',
    'canoness',
    'vestal',
    'anchoress',
    'bride of Christ',
    'ancress',
    'vowess',
]