export const definitions = [
    '"the bacon began to sizzle in the pan"',
    '"we sizzled in blazing sunshine this week"',
    '"they simply sizzle as their affair develops"',
    '"the sizzle of hot dogs"',
    '"a dance routine with lots of sizzle"',
]
export const synonyms = [
    'crackle',
    'frizzle',
    'sputter',
    'hiss',
    'spit',
    'fry',
    'red-hot',
    'blazing',
    'flaming',
    'fiery',
    'burning',
    'scorching',
    'blistering',
    'searing',
    'sweltering',
    'torrid',
    'tropical',
    'parching',
    'withering',
    'broiling',
    'extremely hot',
    'unbearably hot',
    'baking (hot)',
    'like an oven',
    'like a furnace',
    'like a blowtorch',
    'freezing',
    'passionate',
    'torrid',
    'amorous',
    'ardent',
    'sexy',
    'lustful',
    'erotic',
]