export const definitions = [
    '"the woods were still and silent"',
    '"she fell silent for a moment"',
    '"a silent prayer"',
    '"a silent \"h\""',
    '"she appeared in a number of silent films"',
    '"the poems are silent on the question of marriage"',
    '"I\'m the strong, silent type"',
]
export const synonyms = [
    'still',
    'hushed',
    'inaudible',
    'noiseless',
    'soundless',
    'peaceful',
    'tranquil',
    'completely quiet',
    'so quiet you could hear a pin drop',
    'audible',
    'noisy',
    'speechless',
    'quiet',
    'unspeaking',
    'wordless',
    'voiceless',
    'dumb',
    'mute',
    'taciturn',
    'reticent',
    'uncommunicative',
    'unforthcoming',
    'tight-lipped',
    'close-mouthed',
    'untalkative',
    'tongue-tied',
    'saying nothing',
    'at a loss for words',
    'struck dumb',
    'loquacious',
    'unspoken',
    'wordless',
    'unsaid',
    'unstated',
    'undeclared',
    'unexpressed',
    'unmentioned',
    'unvoiced',
    'tacit',
    'implicit',
    'understood',
    'implied',
    'unpronounced',
    'taken for granted',
    'spoken',
]