export const definitions = [
  '"a sliver of cheese"',
  '"there was a sliver of light under his door"',
  '"sliver the blanched almonds, chop the pistachios, and set them aside"',
  '"I slivered four garlic cloves and browned them in the oil"',
  '"the fibers are combed or carded, then slivered and spun into yarn"',
];
export const synonyms = [
  'splinter',
  'shard',
  'shiver',
  'chip',
  'flake',
  'shred',
  'scrap',
  'slither',
  'shaving',
  'paring',
  'slice',
  'wafer',
  'piece',
  'fragment',
  'bit',
  'rove',
  'skelf',
];