export const definitions = [
    '"Elkhorn Slough"',
    '"the economic slough of the interwar years"',
    '"a snake sloughs off its old skin"',
    '"exfoliate once a week to slough off any dry skin"',
    '"he is concerned to slough off the country\'s bad environmental image"',
    '"the drugs can cause blistering and slough"',
]
export const synonyms = [
    'discard',
    'throw away',
    'throw out',
    'get rid of',
    'shed',
    'jettison',
    'scrap',
    'repudiate',
    'abandon',
    'relinquish',
    'drop',
    'reject',
    'shrug off',
    'forsake',
    'dispose of',
    'toss out',
    'cast aside/off',
    'dispense with',
    'have done with',
    'throw on the scrapheap',
    'keep',
    'acquire',
    'throw away',
    'throw out',
    'get rid of',
    'reject',
    'jettison',
    'scrap',
    'repudiate',
    'abandon',
    'relinquish',
    'drop',
    'shed',
    'shrug off',
    'forsake',
    'dispose of',
    'toss out',
    'dispense with',
    'cast aside/off',
    'have done with',
    'slough off',
    'throw on the scrapheap',
    'keep',
    'acquire',
]