export const definitions = [
    '"she had a sly personality"',
    '"he gave a sly grin"',
    '"a sly sip of water"',
]
export const synonyms = [
    'cunning',
    'crafty',
    'clever',
    'wily',
    'artful',
    'guileful',
    'tricky',
    'conniving',
    'scheming',
    'devious',
    'designing',
    'deceitful',
    'duplicitous',
    'dishonest',
    'disingenuous',
    'underhand',
    'sneaky',
    'untrustworthy',
    'manipulative',
    'calculating',
    'Machiavellian',
    'subtle',
    'carny',
    'honest',
    'artless',
    'roguish',
    'mischievous',
    'impish',
    'puckish',
    'playful',
    'teasing',
    'naughty',
    'wicked',
    'waggish',
    'arch',
    'knowing',
    'surreptitious',
    'furtive',
    'stealthy',
    'covert',
    'secret',
]