export const definitions = [
    '"sneaky, underhanded tactics"',
    '"I developed a sneaky fondness for the old lady"',
]
export const synonyms = [
    'sly',
    'crafty',
    'cunning',
    'wily',
    'clever',
    'artful',
    'scheming',
    'devious',
    'guileful',
    'tricky',
    'conniving',
    'designing',
    'deceitful',
    'duplicitous',
    'dishonest',
    'disingenuous',
    'underhand',
    'untrustworthy',
    'unscrupulous',
    'double-dealing',
    'furtive',
    'secretive',
    'secret',
    'stealthy',
    'surreptitious',
    'sneaking',
    'skulking',
    'slinking',
    'clandestine',
    'hidden',
    'covert',
    'cloaked',
    'conspiratorial',
    'under the table',
    'black',
    'subtle',
    'carny',
    'honest',
    'open',
]