export const definitions = [
  '"snide remarks about my mother"',
  '"a snide divorce lawyer"',
  '"snide Rolex watches"',
  '"he\'s not a snide, he\'s better than most"',
];
export const synonyms = [
  'disparaging',
  'derogatory',
  'deprecating',
  'deprecatory',
  'denigratory',
  'insulting',
  'vituperative',
  'disapproving',
  'contemptuous',
  'mocking',
  'taunting',
  'ridiculing',
  'sneering',
  'jeering',
  'scoffing',
  'scornful',
  'derisive',
  'sarcastic',
  'caustic',
  'biting',
  'bitchy',
  'shrewish',
  'spiteful',
  'hurtful',
  'nasty',
  'mean',
  'mordacious',
  'complimentary',
  'sympathetic',
  'underhand',
  'underhanded',
  'deceitful',
  'dishonest',
  'dishonorable',
  'disreputable',
  'unethical',
  'unprincipled',
  'immoral',
  'unscrupulous',
  'fraudulent',
  'cheating',
  'dubious',
  'dirty',
  'unfair',
  'treacherous',
  'duplicitous',
  'double-dealing',
  'Janus-faced',
  'below the belt',
  'two-timing',
  'two-faced',
  'unsporting',
  'unsportsmanlike',
  'crafty',
  'cunning',
  'calculating',
  'artful',
  'conniving',
  'scheming',
  'designing',
  'sly',
  'wily',
  'guileful',
  'tricky',
  'sneaky',
  'sneaking',
  'furtive',
  'secret',
  'secretive',
  'clandestine',
  'surreptitious',
  'covert',
  'veiled',
  'shrouded',
  'cloak-and-dagger',
  'hugger-mugger',
  'hole-and-corner',
  'hidden',
  'back-alley',
  'backstairs',
  'under the table',
  'conspiratorial',
  'snidey',
  'above board',
];