export const definitions = [
    '"his clothes were sodden"',
    '"a whiskey-sodden criminal"',
    '"the rains have soddened the earth"',
]
export const synonyms = [
    'soaking',
    'soaked',
    'soaked through',
    'wet through',
    'saturated',
    'drenched',
    'streaming',
    'waterlogged',
    'soggy',
    'boggy',
    'swampy',
    'miry',
    'fenny',
    'oozy',
    'marshy',
    'heavy',
    'squelchy',
    'soft',
    'quaggy',
    'soaking wet',
    'sopping (wet)',
    'dripping (wet)',
    'wringing (wet)',
    'dry',
    'arid',
    'sprinkle',
    'moisten',
    'dampen',
    'wet',
    'spray',
    'splash',
    'soak',
    'douse',
    'souse',
    'drench',
    'saturate',
    'flood',
    'waterlog',
    'hose (down)',
    'water down',
    'dry out',
    'parch',
]