export const definitions = [
  '"she was dark, petite, and soignée"',
];
export const synonyms = [
  'stylish',
  'smart',
  'elegant',
  'chic',
  'crisp',
  'dapper',
  'spruce',
  'trim',
  'debonair',
  'well dressed',
  'well groomed',
  'tasteful',
  'understated',
  'attractive',
  'flattering',
  'fancy',
  'fashionable',
  'high-fashion',
  'modish',
  'voguish',
  'modern',
  'up to date',
  'up to the minute',
  'ultramodern',
  'contemporary',
  'designer',
  'à la mode',
  'trig',
  'well turned out',
  'smartly dressed',
  'in vogue',
  'as if one had just stepped out of a bandbox',
  'dowdy',
  'unfashionable',
];