export const definitions = [
    '"remove the fitting using a blowtorch to melt the solder"',
    '"the Roman silversmith did indeed use several different solders"',
    '"the wires to this clip are soldered to the circuit board"',
    '"the soldered terminal joints"',
]
export const synonyms = [
    'attach',
    'join',
    'fasten',
    'fix',
    'affix',
    'couple',
    'link',
    'bridge',
    'secure',
    'tie',
    'tie up',
    'bind',
    'fetter',
    'strap',
    'rope',
    'tether',
    'truss',
    'lash',
    'hitch',
    'moor',
    'anchor',
    'yoke',
    'chain',
    'stick',
    'tape',
    'adhere',
    'glue',
    'bond',
    'cement',
    'fuse',
    'weld',
    'pin',
    'peg',
    'screw',
    'bolt',
    'rivet',
    'batten',
    'pinion',
    'clamp',
    'clip',
    'hook (up)',
    'add',
    'append',
    'annex',
    'subjoin',
    'concatenate',
    'make fast',
    'disconnect',
]