export const definitions = [
  '"he understood the sorrow and discontent underlying his brother\'s sigh"',
  '"it was a great sorrow to her when they separated"',
  '"a woman had cried all night, sorrowing over the death of her husband"',
];
export const synonyms = [
  'sadness',
  'unhappiness',
  'dejection',
  'regret',
  'depression',
  'misery',
  'cheerlessness',
  'downheartedness',
  'despondency',
  'despair',
  'desolation',
  'wretchedness',
  'glumness',
  'gloom',
  'gloominess',
  'dolefulness',
  'melancholy',
  'low spirits',
  'mournfulness',
  'woe',
  'broken-heartedness',
  'heartache',
  'grief',
  'dolorous',
  'disconsolateness',
  'disconsolation',
  'dismalness',
  'heaviness of heart',
  'joy',
  'trouble',
  'difficulty',
  'problem',
  'adversity',
  'misery',
  'woe',
  'affliction',
  'trial',
  'tribulation',
  'misfortune',
  'misadventure',
  'mishap',
  'setback',
  'reverse',
  'blow',
  'failure',
  'accident',
  'disaster',
  'tragedy',
  'catastrophe',
  'calamity',
  'reverse of fortune',
  'stroke of bad luck',
  'despair',
  'suffer',
  'ache',
  'agonize',
  'anguish',
  'pine',
  'weep',
  'shed tears',
  'grieve',
  'mourn',
  'lament',
  'wail',
  'be sad',
  'feel sad',
  'be miserable',
  'be despondent',
  'be wretched',
  'be dejected',
  'be heavy of heart',
  'rejoice',
];