export const definitions = [
  '"the few reckless vagabonds with whom he sotted in the alehouse"',
];
export const synonyms = [
  'intoxicated',
  'inebriated',
  'drunken',
  'befuddled',
  'incapable',
  'tipsy',
  'under the influence',
  'maudlin',
  'blind drunk',
  '(as) drunk as a skunk',
  'sottish',
  'tippling',
  'toping',
  'sotted',
  'besotted',
  'foxed',
  'screwed',
  'crapulent',
  'crapulous',
  'inebriate',
  'bibulous',
  'the worse for drink',
  'dead drunk',
  'rolling drunk',
  'roaring drunk',
  '(as) drunk as a lord',
  'gin-soaked',
  'ebrious',
  'ebriose',
  'ebriate',
  'sober',
];