export const definitions = [
  '"mackerel is a good source of fish oil"',
  '"the source of the Nile"',
  '"military sources announced a reduction in strategic nuclear weapons"',
  '"each type of coffee is sourced from one country"',
  '"she was called upon to source a supply of carpet"',
];
export const synonyms = [
  'origin',
  'birthplace',
  'spring',
  'wellspring',
  'fount',
  'history',
  'pedigree',
  'provenance',
  'derivation',
  'root',
  'etymology',
  'beginning',
  'genesis',
  'start',
  'rise',
  'cause',
  'author',
  'originator',
  'initiator',
  'creator',
  'inventor',
  'architect',
  'father',
  'mother',
  'provenience',
  'fountainhead',
  'begetter',
  'radix',
  'place of origin',
  'starting point',
  'spring',
  'origin',
  'head',
  'well head',
  'headspring',
  'headwater(s)',
  'eye',
  'wellspring',
  'reference',
  'authority',
  'informant',
  'documentation',
  'reference',
  'authority',
  'informant',
  'documentation',
];