export const definitions = [
    '"he was born deaf and without the power of speech"',
    '"she wouldn\'t accept his correction of her speech"',
    '"the headmistress made a speech about how much they would miss her"',
    '"Antony\'s speech over Caesar\'s body"',
]
export const synonyms = [
    'speaking',
    'talking',
    'articulation',
    'verbal communication',
    'verbal expression',
    'diction',
    'elocution',
    'articulation',
    'enunciation',
    'pronunciation',
    'utterance',
    'words',
    'phraseology',
    'talk',
    'orthoepy',
    'manner of speaking',
    'talk',
    'address',
    'lecture',
    'discourse',
    'oration',
    'disquisition',
    'peroration',
    'declamation',
    'deliverance',
    'presentation',
    'valedictory',
    'sermon',
    'homily',
    'harangue',
    'diatribe',
    'tirade',
    'rant',
    'monologue',
    'soliloquy',
    'recitation',
    'effusion',
    'outpouring',
    'salutatory',
    'allocution',
    'predication',
    'philippic',
    'words',
    'role',
    'part',
    'script',
    'dialogue',
]