export const definitions = [
    '"the firm has spent $100,000 on hardware and software"',
    '"the college spent $140 on each of its students"',
    '"she spent a lot of time traveling"',
    '"she couldn\'t buy any more because she had already spent her money"',
    '"the initial surge of interest had spent itself"',
    '"the average spend at the cafe is about $10 a head"',
]
export const synonyms = [
    'pay out',
    'lay out',
    'expend',
    'disburse',
    'squander',
    'go through',
    'run through',
    'waste',
    'lavish',
    'spring',
    'fritter away',
    'save',
    'keep',
    'hoard',
    'pass',
    'occupy',
    'fill',
    'take up',
    'use up',
    'put in',
    'devote',
    'employ',
    'waste',
    'while away',
    'use up',
    'consume',
    'exhaust',
    'deplete',
    'drain',
]