export const definitions = [
  '"they had to thank the goalie for some inspired saves"',
  '"she was an inspired gardener"',
  '"inspired air must be humidified"',
  '"his passion for romantic literature inspired him to begin writing"',
  '"their past record does not inspire confidence"',
  '"he inspired his students with a vision of freedom"',
  '"the movie was successful enough to inspire a sequel"',
  '"they can expand their lungs and inspire enough gas to satisfy oxygen requirements"',
];
export const synonyms = [
  'outstanding',
  'wonderful',
  'marvelous',
  'excellent',
  'magnificent',
  'fine',
  'exceptional',
  'formidable',
  'first-class',
  'first-rate',
  'virtuoso',
  'supreme',
  'superlative',
  'dazzling',
  'coruscating',
  'exciting',
  'thrilling',
  'enthralling',
  'memorable',
  'gifted',
  'talented',
  'creative',
  'imaginative',
  'inventive',
  'innovative',
  'innovatory',
  'innovational',
  'ingenious',
  'original',
  'resourceful',
  'enterprising',
  'mediocre',
  'poor',
  'stimulate',
  'motivate',
  'cause',
  'incline',
  'persuade',
  'encourage',
  'influence',
  'rouse',
  'move',
  'stir',
  'goad',
  'energize',
  'galvanize',
  'incite',
  'impel',
  'animate',
  'inspirit',
  'incentivize',
  'fillip',
  'spur (on)',
  'fire the imagination of',
  'fire with enthusiasm',
  'arouse',
  'awaken',
  'prompt',
  'cause',
  'induce',
  'ignite',
  'trigger',
  'kindle',
  'produce',
  'generate',
  'bring out',
  'bring about',
  'give rise to',
  'sow the seeds of',
  'enkindle',
  'extinguish',
  'give rise to',
  'bring about',
  'cause',
  'prompt',
  'produce',
  'spawn',
  'engender',
  'beget',
  'lead to',
  'result in',
  'be the cause of',
  'be the inspiration for',
  'draw in',
  'suck in',
  'gasp',
  'gulp',
  'drink in',
  'inbreathe',
  'breathe in',
  'sniff in',
  'exhale',
  'expire',
];