export const definitions = [
    '"I was spoony over Miss Talmadge to the point of idolatry"',
    '"priests are bound to be mild and spoony"',
    '"what the deuce can she find in that spoony of a Pitt Crawley?"',
]
export const synonyms = [
    'lustful',
    'sexual',
    'erotic',
    'amatory',
    'ardent',
    'passionate',
    'impassioned',
    'romantic',
    'affectionate',
    'fond',
    'loving',
    'tender',
    'doting',
    'enamored',
    'lovesick',
    'sportive',
    'in love',
    'unloving',
    'cold',
    'idiot',
    'halfwit',
    'nincompoop',
    'blockhead',
    'buffoon',
    'dunce',
    'dolt',
    'ignoramus',
    'cretin',
    'imbecile',
    'dullard',
    'moron',
    'simpleton',
    'clod',
    'tomfool',
    'noddy',
    'loggerhead',
    'mooncalf',
    'clodpole',
]