export const definitions = [
  '"a spiral pattern"',
  '"a wrought-iron spiral staircase"',
  '"a spiral notebook"',
  '"he spotted a spiral of smoke"',
  '"an inflationary spiral"',
  '"a downward spiral of sex and drink"',
  '"a wisp of smoke spiraled up from the trees"',
  '"spiral the bandage around the injured limb"',
  '"inflation continued to spiral"',
  '"he expects the figures to spiral down further"',
];
export const synonyms = [
  'coiled',
  'helical',
  'corkscrew',
  'curling',
  'winding',
  'twisting',
  'whorled',
  'scrolled',
  'cochlear',
  'cochleate',
  'voluted',
  'helicoid',
  'helicoidal',
  'helix-shaped',
  'coil',
  'helix',
  'curl',
  'corkscrew',
  'twist',
  'gyre',
  'whorl',
  'scroll',
  'curlicue',
  'convolution',
  'volute',
  'volution',
  'growth',
  'rise',
  'enlargement',
  'expansion',
  'extension',
  'multiplication',
  'elevation',
  'swelling',
  'inflation',
  'increment',
  'addition',
  'augmentation',
  'magnification',
  'intensification',
  'strengthening',
  'amplification',
  'stepping up',
  'step up',
  'heightening',
  'climb',
  'escalation',
  'surge',
  'upsurge',
  'upswing',
  'improvement',
  'boost',
  'amelioration',
  'enhancement',
  'upgrade',
  'upturn',
  'worsening',
  'exacerbation',
  'aggravation',
  'development',
  'advance',
  'boom',
  'spurt',
  'snowballing',
  'mushrooming',
  'decrease',
  'reduction',
  'coil',
  'wind',
  'twirl',
  'swirl',
  'twist',
  'wreathe',
  'snake',
  'gyrate',
  'coil',
  'wind',
  'twirl',
  'swirl',
  'twist',
  'wreathe',
  'snake',
  'gyrate',
  'soar',
  'shoot up',
  'rocket',
  'escalate',
  'climb',
  'mount',
  'increase rapidly',
  'rise rapidly',
  'leap up',
  'fall',
  'deteriorate',
  'decline',
  'degenerate',
  'worsen',
  'get worse',
  'improve',
];