export const definitions = [
  '"I sprang out of bed"',
  '"they sprang to her defense"',
  '"the drawer sprang open"',
  '"the engine sprang into life"',
  '"the president sought to spring the hostages"',
  '"madness and creativity could spring from the same source"',
  '"tears sprang from his eyes"',
  '"a terrible storm sprang up"',
  '"we decided to spring a surprise on them"',
  '"he\'s never offered to spring for dinner"',
  '"he might spring a few pennies more"',
];
export const synonyms = [
  'leap',
  'jump',
  'bound',
  'vault',
  'hop',
  'materialize',
  'appear suddenly',
  'appear unexpectedly',
  'fly back',
  'recoil',
  'kick back',
  'resile',
  'come from',
  'originate from',
  'have its origins in',
  'derive from',
  'arise from',
  'stem from',
  'emanate from',
  'proceed from',
  'start from',
  'issue from',
  'evolve from',
  'announce suddenly/unexpectedly',
  'present suddenly/unexpectedly',
  'introduce suddenly/unexpectedly',
  'reveal suddenly/unexpectedly',
  'pay out',
  'lay out',
  'expend',
  'disburse',
  'squander',
  'go through',
  'run through',
  'waste',
  'lavish',
  'fritter away',
  'save',
  'keep',
  'hoard',
];