export const definitions = [
    '"an assassination squad"',
    '"the demolition squad from No. 6 Troop were blowing up the guns"',
    '"eleven first-string players on the Nebraska squad"',
    '"the vice squad"',
    '"the 39-year-old actress and her squad snapped some pics together after the show"',
]
export const synonyms = [
    'group',
    'gang',
    'band',
    'body',
    'crew',
    'team',
    'mob',
    'crowd',
    'outfit',
    'force',
    'detachment',
    'detail',
    'platoon',
    'battery',
    'troop',
    'patrol',
    'squadron',
    'cadre',
    'commando',
    'unit',
    'formation',
    'group',
    'set',
    'ring',
    'company',
    'body',
    'coterie',
    'clique',
    'camp',
    'league',
    'faction',
    'crowd',
    'band',
    'crew',
]