export const definitions = [
    '"the geese flew upriver, squawking"',
    '"\"What are you doing?\" she squawked"',
    '"he is well known for squawking about price-fixing at local gas pumps"',
    '"her plan provoked a loud squawk from her friends"',
]
export const synonyms = [
    'screech',
    'squeal',
    'shriek',
    'scream',
    'croak',
    'crow',
    'caw',
    'cluck',
    'clack',
    'cackle',
    'hoot',
    'cry',
    'call',
    'complain',
    'protest',
    'object',
    'put up a fight',
    'kick',
    'grouse',
    'grouch',
    'grumble',
    'whine',
    'wail',
    'moan',
    'carp',
    'squeal',
    'twine',
    'express disapproval',
    'raise objections',
    'make/take a stand',
    'take exception',
    'mither',
    'screech',
    'squeal',
    'shriek',
    'scream',
    'croak',
    'crow',
    'caw',
    'cluck',
    'clack',
    'cackle',
    'hoot',
    'cry',
    'call',
    'complaint',
    'protest',
    'objection',
    'fuss',
    'grouse',
    'grouch',
    'grumble',
    'whine',
    'wail',
    'moan',
    'carp',
    'squeal',
]