export const definitions = [
    '"we heard a splash and a squeal"',
    '"the girls squealed with delight"',
    '"\"Don\'t you dare!\" she squealed"',
    '"the bookies only squealed because we beat them"',
    '"she feared they would victimize her for squealing on their pals"',
]
export const synonyms = [
    'screech',
    'scream',
    'shriek',
    'squawk',
    'howl',
    'cry',
    'wail',
    'squall',
    'yawp',
    'yelp',
    'shrill',
    'screech',
    'scream',
    'shriek',
    'squawk',
    'howl',
    'cry',
    'wail',
    'squall',
    'yawp',
    'yelp',
    'shrill',
    'squawk',
    'screech',
    'shriek',
    'scream',
    'howl',
    'yowl',
    'wail',
    'yell',
    'cry out',
    'call out',
    'shout',
    'bawl',
    'yawp',
    'yap',
    'bark',
    'woof',
    'bay',
    'complain',
    'protest',
    'object',
    'put up a fight',
    'kick',
    'grouse',
    'grouch',
    'grumble',
    'whine',
    'wail',
    'moan',
    'carp',
    'squawk',
    'twine',
    'express disapproval',
    'raise objections',
    'make/take a stand',
    'take exception',
    'mither',
    'report',
    'give away',
    'sell out',
    'inform (on/against)',
    'act as an informer',
    'tell tales (on)',
    'sneak (on)',
    'be disloyal (to)',
    'stab in the back',
]