export const definitions = [
    '"a staunch supporter of the antinuclear lobby"',
    '"a staunch Catholic"',
    '"these staunch walls could withstand attack by cannon"',
    '"colleagues may have saved her life by stanching the flow"',
    '"the company did nothing to stanch the tide of rumors"',
]
export const synonyms = [
    'stalwart',
    'loyal',
    'faithful',
    'trusty',
    'committed',
    'devoted',
    'dedicated',
    'dependable',
    'reliable',
    'steady',
    'constant',
    'hard-working',
    'vigorous',
    'stable',
    'firm',
    'steadfast',
    'redoubtable',
    'resolute',
    'unswerving',
    'unwavering',
    'unhesitating',
    'unfaltering',
    'disloyal',
    'unfaithful',
    'unreliable',
    'robust',
    'strong',
    'well built',
    'well made',
    'solid',
    'substantial',
    'stout',
    'sound',
    'serviceable',
    'stable',
    'tough',
    'resilient',
    'durable',
    'long-lasting',
    'hardwearing',
    'imperishable',
    'indestructible',
    'resistant',
    'strongly made',
    'built to last',
    'weak',
    'ramshackle',
]