export const definitions = [
    '"he stared at her in amazement"',
    '"he looked away, pretending to stare out of the window"',
    '"she tried hard not to stare"',
    '"Robin sat staring into space, her mind numb"',
    '"her gray eyes stared back at him"',
    '"the obituaries stared out at us"',
]
export const synonyms = [
    'gaze',
    'gape',
    'goggle',
    'gawk',
    'glare',
    'ogle',
    'leer',
    'peer',
    'study',
    'survey',
    'observe',
    'eyeball',
    'outstare',
    'look fixedly',
    'look vacantly',
    'watch closely',
    'gaze',
    'gape',
    'goggle',
    'gawk',
    'glare',
    'ogle',
    'leer',
    'peer',
    'study',
    'survey',
    'observe',
    'eyeball',
    'outstare',
    'look fixedly',
    'look vacantly',
    'watch closely',
]