export const definitions = [
    '"she left her animals to starve"',
    '"seven million starved to death"',
    '"for a while she had considered starving herself"',
    '"I don\'t know about you, but I\'m starving"',
    '"the Royalists were starved out after eleven days"',
    '"German U-boats hoping to starve Britain into submission"',
    '"the arts are being starved of funds"',
    '"pull down that window for we are perfectly starving here"',
]
export const synonyms = [
    'ravenous',
    'empty',
    'hollow',
    'starving',
    'starved',
    'famished',
    'half-starved',
    'malnourished',
    'undernourished',
    'underfed',
    'sharp-set',
    'esurient',
    'faint from hunger',
    'dying from hunger',
    'deprived of food',
    'full',
    'well fed',
]