export const definitions = [
    '"the state of the company\'s finances"',
    '"we\'re worried about her state of mind"',
    '"water in a liquid state"',
    '"don\'t get into a state"',
    '"look at the state of you—what a mess!"',
    '"Germany, Italy, and other European states"',
    '"the German state of Bavaria"',
    '"services provided by the state"',
    '"King Fahd appointed a council to advise him on affairs of state"',
    '"state-owned companies"',
    '"he was buried in state"',
    '"an oblong plate, dry point, first state of eight"',
    '"there are four states of the first edition"',
    '"the report stated that more than 51 percent of voters failed to participate"',
    '"\"Money hasn\'t changed me,\" she stated firmly"',
    '"people will be invited to state their views"',
    '"judges must give both sides an equal opportunity to state their case"',
]
export const synonyms = [
    'condition',
    'shape',
    'situation',
    'circumstances',
    'state of affairs',
    'position',
    'predicament',
    'plight',
    'mood',
    'humor',
    'temper',
    'disposition',
    'spirits',
    'morale',
    'frame of mind',
    'attitude',
    'state of mind',
    'emotional state',
    'fluster',
    'flutter',
    'frenzy',
    'fever',
    'fret',
    'panic',
    'state of agitation',
    'state of anxiety',
    'nervous state',
    'distressed state',
    'untidiness',
    'mess',
    'chaos',
    'disorder',
    'disarray',
    'disorganization',
    'confusion',
    'clutter',
    'muddle',
    'heap',
    'shambles',
    'tangle',
    'mishmash',
    'turmoil',
    'untidy state',
    'country',
    'nation',
    'land',
    'nation state',
    'kingdom',
    'empire',
    'republic',
    'confederation',
    'federation',
    'body politic',
    'commonwealth',
    'power',
    'world power',
    'superpower',
    'polity',
    'domain',
    'territory',
    'fatherland',
    'motherland',
    'realm',
    'res publica',
    'sovereign state',
    'province',
    'region',
    'territory',
    'canton',
    'department',
    'county',
    'area',
    'district',
    'sector',
    'zone',
    'shire',
    'federal state',
    'government',
    'parliament',
    'the administration',
    'the Establishment',
    'the regime',
    'the authorities',
    'the council',
    'ceremonial',
    'official',
    'formal',
    'governmental',
    'national',
    'public',
    'unofficial',
    'private',
    'informal',
    'express',
    'voice',
    'utter',
    'say',
    'tell',
    'declare',
    'affirm',
    'assert',
    'aver',
    'announce',
    'communicate',
    'reveal',
    'disclose',
    'divulge',
    'give out',
    'give voice to',
    'pronounce',
    'articulate',
    'enunciate',
    'proclaim',
    'present',
    'expound',
    'preach',
    'promulgate',
    'publish',
    'broadcast',
    'set out',
    'set down',
    'frame',
    'formulate',
    'spell out',
    'asseverate',
    'set',
    'fixed',
    'settled',
    'agreed',
    'declared',
    'determined',
    'approved',
    'authorized',
    'accredited',
    'ruled',
    'ordained',
    'designated',
    'claimed',
    'official',
    'supposed',
    'professed',
    'alleged',
    'make known',
    'be specific about',
    'laid down',
    'undefined',
    'irregular',
    'tacit',
    'actual',
]