export const definitions = [
    '"an improvement in the status of women"',
    '"those who enjoy wealth and status"',
    '"the duchy had been elevated to the status of a principality"',
    '"an update on the status of the bill"',
    '"when I updated my status on Facebook yesterday I said I was \'seeking a sense of purpose\'"',
    '"I noticed that there were some interesting status updates from some of my local friends"',
]
export const synonyms = [
    'standing',
    'rank',
    'ranking',
    'position',
    'station',
    'level',
    'footing',
    'place',
    'repute',
    'reputation',
    'estimation',
    'stature',
    'condition',
    'degree',
    'report',
    'social position',
    'prestige',
    'kudos',
    'cachet',
    'standing',
    'stature',
    'prestigiousness',
    'reputation',
    'repute',
    'regard',
    'fame',
    'note',
    'renown',
    'honor',
    'esteem',
    'estimation',
    'image',
    'account',
    'rank',
    'character',
    'celebrity',
    'importance',
    'prominence',
    'consequence',
    'class',
    'distinction',
    'laurels',
    'influence',
    'weight',
    'authority',
    'supremacy',
    'eminence',
    'superiority',
    'mana',
    'izzat',
    '(good) name',
]