export const definitions = [
    '"stowage room hasn\'t been stinted"',
    '"to avoid having to stint yourself, budget in advance"',
    '"he doesn\'t stint on wining and dining"',
    '"his varied career included a stint as a magician"',
    '"a collector with an eye for quality and the means to indulge it without stint"',
]
export const synonyms = [
    'limit',
    'restrict',
    'pinch pennies',
    'skimp on',
    'scrimp on',
    'be economical with',
    'economize on',
    'be sparing with',
    'hold back on',
    'be frugal with',
    'be mean with',
    'be parsimonious with',
    'spoil the ship for a ha\'porth of tar',
    'spell',
    'stretch',
    'period',
    'time',
    'turn',
    'run',
    'session',
    'term',
    'shift',
    'tour of duty',
    'watch',
]