export const definitions = [
    '"a stolid bourgeois gent"',
]
export const synonyms = [
    'impassive',
    'phlegmatic',
    'unemotional',
    'calm',
    'placid',
    'unexcitable',
    'apathetic',
    'uninterested',
    'unimaginative',
    'indifferent',
    'dull',
    'bovine',
    'lumpish',
    'wooden',
    'slow',
    'lethargic',
    'torpid',
    'stupid',
    'emotional',
    'lively',
    'imaginative',
]