export const definitions = [
    '"the houses are built of stone"',
    '"high stone walls"',
    '"Isabel stood as if turned to stone"',
    '"the elevator dropped like a stone"',
    '"her face became as hard as stone"',
    '"a memorial stone"',
    '"boundary stones"',
    '"a gold ring with a small dark red stone"',
    '"I weighed 10 stone"',
    '"stone stretch trousers"',
    '"three vehicles were stoned and torched"',
    '"halve, stone, and peel the avocados"',
    '"the honey-stoned, eighteenth-century city"',
]
export const synonyms = [
    'rock',
    'pebble',
    'boulder',
    'cobbles',
    'gravel',
    'scree',
    'concretion',
    'boondie',
    'gravestone',
    'headstone',
    'tombstone',
    'tablet',
    'monument',
    'monolith',
    'obelisk',
    'gem',
    'gemstone',
    'jewel',
    'precious stone',
    'brilliant',
    'bijou',
    'semiprecious stone',
    'kernel',
    'seed',
    'pip',
    'pit',
    'endocarp',
    'fawn',
    'buff',
    'sand',
    'sandy',
    'oatmeal',
    'wheaten',
    'biscuit',
    'coffee',
    'coffee-colored',
    'café au lait',
    'camel',
    'kasha',
    'ecru',
    'taupe',
    'mushroom',
    'putty',
    'greige',
    'neutral',
    'natural',
    'brownish yellow',
    'pale brown',
    'stone-colored',
    'naturelle',
]