export const definitions = [
    '"the Strait of Gibraltar"',
    '"the economy is in dire straits"',
    '"a crippling disease could leave anyone in serious financial straits"',
    '"the road was so strait that a handful of men might have defended it"',
    '"my captivity was strait as ever"',
]
export const synonyms = [
    'channel',
    'sound',
    'narrows',
    'inlet',
    'neck',
    'stretch of water',
    'arm of the sea',
    'sea passage',
    'kyle',
    'difficulty',
    'trouble',
    'crisis',
    'a bad/difficult situation',
    'a sorry condition',
    'a mess',
    'a predicament',
    'a plight',
    'a tight corner',
    'cramped',
    'constricted',
    'restricted',
    'limited',
    'confining',
    'small',
    'narrow',
    'compact',
    'tight',
    'pinched',
    'squeezed',
    'poky',
    'uncomfortable',
    'inadequate',
    'meager',
    'incommodious',
    'exiguous',
    'incapacious',
    'open',
    'roomy',
]