export const definitions = [
    '"a stratum of flint"',
    '"thin strata of air"',
    '"members of other social strata"',
    '"allocation of sample units to strata"',
]
export const synonyms = [
    'layer',
    'vein',
    'seam',
    'lode',
    'bed',
    'stratification',
    'thickness',
    'sheet',
    'lamina',
    'level',
    'class',
    'echelon',
    'rank',
    'grade',
    'station',
    'gradation',
    'group',
    'set',
    'bracket',
    'caste',
    'estate',
    'sphere',
]