export const definitions = [
  '"two of the firm\'s trucks are stranded in France"',
  '"they were stranded by the blizzard"',
  '"the ships were stranded in shallow water"',
  '"a heron glided to rest on a pebbly strand"',
  '"a strand of cotton"',
  '"strands of grass"',
  '"certain strands of postmodern thought"',
];
export const synonyms = [
  'seashore',
  'shore',
  'beach',
  'sands',
  'foreshore',
  'shoreline',
  'coast',
  'seaside',
  'seaboard',
  'waterfront',
  'front',
  'waterside',
  'littoral',
  'plage',
  'water\'s edge',
  'thread',
  'filament',
  'fiber',
  'length',
  'piece',
  'string',
  'ply',
  'fibril',
  'rope',
  'necklace',
  'rosary',
  'chaplet',
  'element',
  'component',
  'factor',
  'ingredient',
  'aspect',
  'feature',
  'theme',
  'strain',
  'trope',
];