export const definitions = [
    '"a streak of oil"',
    '"she could see white streaks in his beard"',
    '"there\'s a streak of insanity in the family"',
    '"Lucy had a ruthless streak"',
    '"the theater is on a winning streak"',
    '"the team closed the season with an 11-game losing streak"',
    '"a streak for charity"',
    '"tears streaking her face, Cynthia looked up"',
    '"his beard was streaked withgray"',
    '"hair that was streaked blond"',
    '"swabs were streaked directly on blood agar plates"',
    '"the cat leaped free and streaked across the street"',
    '"the singer admitted to streaking in his home town in the seventies"',
]
export const synonyms = [
    'band',
    'line',
    'strip',
    'stripe',
    'vein',
    'slash',
    'bar',
    'ray',
    'finger',
    'pencil',
    'stroke',
    'trace',
    'touch',
    'fleck',
    'dash',
    'stria',
    'striation',
    'lane',
    'mark',
    'smear',
    'smudge',
    'stain',
    'blotch',
    'element',
    'vein',
    'trace',
    'touch',
    'dash',
    'strain',
    'trait',
    'characteristic',
    'period',
    'spell',
    'stretch',
    'run',
    'time',
    'series',
    'stripe',
    'band',
    'bar',
    'fleck',
    'striate',
    'freak',
    'mark',
    'daub',
    'smear',
    'smudge',
    'stain',
    'race',
    'dash',
    'rush',
    'run',
    'sprint',
    'bolt',
    'dart',
    'gallop',
    'career',
    'charge',
    'shoot',
    'hurtle',
    'hare',
    'bound',
    'fly',
    'speed',
    'zoom',
    'plunge',
    'dive',
    'whisk',
    'scurry',
    'scuttle',
    'scamper',
    'scramble',
    'fleet',
    'post',
    'hie',
    'haste',
    'go hell for leather',
]