export const definitions = [
    '"he strode across the road"',
    '"striding confidently toward the future"',
    '"a woman striding the cobbled streets"',
    '"by giving a little leap she could stride across like a grown-up"',
    '"new wealth enabled Britain to stride the world once more"',
    '"he crossed the room in a couple of strides"',
    '"the horse shortened its stride"',
    '"he followed her with an easy stride"',
    '"great strides have been made toward equality"',
    '"after months of ineffective campaigning, he seems to have hit his stride"',
    '"a stride pianist"',
]
export const synonyms = [
    'march',
    'stalk',
    'pace',
    'tread',
    'step',
    'walk',
    'step',
    'pace',
    'footstep',
    'long step',
    'large step',
    'gain ground',
    'progress',
    'advance',
    'proceed',
    'move',
    'get on',
    'get ahead',
    'come on',
    'come along',
    'shape up',
    'take shape',
    'make progress',
    'make headway',
    'move forward in leaps and bounds',
]