export const definitions = [
    '"a pair of blue shorts with pink stripes"',
    '"he was wearing his old uniform without its sergeant\'s stripes"',
    '"entrepreneurs of all stripes are joining in the offensive"',
    '"her body was striped with bands of sunlight"',
]
export const synonyms = [
    'line',
    'band',
    'strip',
    'belt',
    'bar',
    'swathe',
    'streak',
    'striation',
    'vein',
    'thread',
    'chevron',
    'flash',
    'blaze',
    'marking',
    'stria',
    'stroke',
    'blow',
    'hit',
    'strike',
    'welt',
    'bang',
    'thwack',
    'thump',
    'emblem',
    'insignia',
    'badge',
    'marking',
    'patch',
    'streak',
    'bar',
    'chevron',
    'bright patch',
    'sort',
    'variety',
    'kind',
    'style',
    'type',
    'category',
    'order',
    'breed',
    'species',
    'class',
    'designation',
    'specification',
    'genre',
    'genus',
    'brand',
    'make',
    'character',
    'ilk',
    'kidney',
    'grain',
    'stamp',
    'mold',
]