export const definitions = [
    '"I was stupid enough to think she was perfect"',
    '"that is such a stupid question"',
    '"apprehension was numbing her brain and making her stupid"',
    '"she told him to stop messing with his stupid painting"',
    '"you\'re not a coward, stupid!"',
]
export const synonyms = [
    'unintelligent',
    'ignorant',
    'dense',
    'brainless',
    'mindless',
    'foolish',
    'dull-witted',
    'dull',
    'slow-witted',
    'witless',
    'slow',
    'simpleminded',
    'empty-headed',
    'vacuous',
    'vapid',
    'halfwitted',
    'idiotic',
    'moronic',
    'imbecilic',
    'imbecile',
    'obtuse',
    'doltish',
    'gullible',
    'naive',
    'silly',
    'scatterbrained',
    'crackbrained',
    'nonsensical',
    'senseless',
    'irresponsible',
    'unthinking',
    'ill-advised',
    'ill-considered',
    'inept',
    'damfool',
    'unwise',
    'injudicious',
    'indiscreet',
    'short-sighted',
    'inane',
    'absurd',
    'ludicrous',
    'ridiculous',
    'laughable',
    'risible',
    'fatuous',
    'asinine',
    'pointless',
    'meaningless',
    'futile',
    'fruitless',
    'mad',
    'insane',
    'lunatic',
    'dunce-like',
    'intelligent',
    'clever',
    'astute',
    'sensible',
    'prudent',
    'fool',
    'nincompoop',
    'dunce',
    'dullard',
    'ignoramus',
]