export const definitions = [
    '"the wounded had little chance of succor"',
    '"prisoners of war were liberated and succored"',
]
export const synonyms = [
    'aid',
    'help',
    'a helping hand',
    'assistance',
    'ministration',
    'comfort',
    'ease',
    'relief',
    'support',
    'guidance',
    'backing',
    'easement',
    'supplementaries',
    'auxiliaries',
    'reserves',
    'support',
    'backup',
    'help',
    'succors',
    'additional troops',
    'fresh troops',
    'additional police',
    'help',
    'aid',
    'assist',
    'comfort',
    'support',
    'sustain',
    'protect',
    'take care of',
    'look after',
    'serve',
    'wait on',
    'bring aid to',
    'give help to',
    'give/render assistance to',
    'lend a (helping) hand to',
    'be of service to',
    'minister to',
    'care for',
    'bring comfort to',
    'bring relief to',
    'be supportive of',
    'attend to',
]