export const definitions = [
  '"energy-restoring, sugary drinks"',
  '"a sugary texture"',
  '"sugary romance"',
];
export const synonyms = [
  'sweet',
  'sugared',
  'sickly',
  'sickly sweet',
  'oversweet',
  'sour',
  'tart',
  'sentimental',
  'oversentimental',
  'mawkish',
  'cloying',
  'sickly',
  'sickly sweet',
  'gushing',
  'saccharine',
  'syrupy',
  'slushy',
  'oversweet',
  'spare',
  'stark',
];