export const definitions = [
    '"the task is ideally suited to a computer"',
    '"a dark-suited man"',
    '"sober-suited lawyers"',
    '"the apartment has two bedrooms—if it suits, you can have one of them"',
    '"he lied whenever it suited him"',
    '"\"I\'m not going to help you.\" \"Suit yourself.\""',
    '"they took care to suit their answers to the questions put to them"',
    '"the dress didn\'t suit her"',
    '"I suited up and entered the water"',
]
export const synonyms = [
    'suitable',
    'relevant',
    'pertinent',
    'apt',
    'appropriate',
    'apposite',
    'apropos',
    '-worthy',
    'fitting',
    'befitting',
    'proper',
    'due',
    'seemly',
    'decorous',
    'decent',
    'right',
    'correct',
    'comme il faut',
    'meet',
    'good enough',
    'unfit',
    'inappropriate',
    'befit',
    'match',
    'complement',
    'go with',
    'tailor',
    'fashion',
    'accommodate',
    'adjust',
    'adapt',
    'modify',
    'fit',
    'gear',
    'equip',
    'design',
    'be cut out for',
    'be convenient for',
    'be acceptable to',
    'be suitable for',
    'meet the requirements of',
    'satisfy the demands of',
    'be in line with the wishes of',
    'make appropriate to/for',
    'make fitting to/for',
    'become',
    'flatter',
    'set off',
    'enhance',
    'ornament',
    'grace',
    'look attractive on',
    'enhance the appearance of',
    'look right on',
    'look good on',
    'show to advantage',
]