export const definitions = [
    '"the sultry late summer weather had brought swarms of insects"',
    '"the air was warm, slightly humid but not sultry"',
    '"she delivered a sultry look to the camera"',
    '"the star shared a sultry snap of herself leaning on a balcony"',
    '"they have a sultry on-air conversation"',
]
export const synonyms = [
    'humid',
    'close',
    'airless',
    'stuffy',
    'stifling',
    'suffocating',
    'oppressive',
    'muggy',
    'sticky',
    'sweltering',
    'tropical',
    'torrid',
    'steamy',
    'heavy',
    'hot',
    'warm',
    'boiling',
    'roasting',
    'claggy',
    'cool',
    'cold',
    'refreshing',
    'passionate',
    'attractive',
    'sensual',
    'sexy',
    'voluptuous',
    'luscious',
    'erotic',
    'seductive',
    'provocative',
    'alluring',
    'tempting',
]