export const definitions = [
    '"she climbed back up the path toward the summit"',
    '"the dramas are considered to form one of the summits of world literature"',
    '"a summit conference"',
    '"in 2013, 658 climbers summited Everest"',
    '"they started climbing at 3:45 a.m. and summited at 8:45 p.m."',
]
export const synonyms = [
    'top',
    'peak',
    'mountaintop',
    'crest',
    'crown',
    'apex',
    'vertex',
    'apogee',
    'tip',
    'cap',
    'ridge',
    'brink',
    'brow',
    'needle',
    'crag',
    'tor',
    'mountain top',
    'hilltop',
    'aiguille',
    'serac',
    'bottom',
    'base',
    'acme',
    'peak',
    'height',
    'pinnacle',
    'zenith',
    'culmination',
    'climax',
    'high point',
    'high spot',
    'optimum',
    'highlight',
    'crowning glory',
    'best',
    'finest',
    'nonpareil',
    'ne plus ultra',
    'crowning point',
    'nadir',
    'meeting',
    'negotiation',
    'conference',
    'talk(s)',
    'discussion',
    'conclave',
    'consultation',
    'deliberation',
    'dialogue',
    'parley',
    'colloquy',
    'confabulation',
]