export const definitions = [
    '"the Pope summoned Anselm to Rome"',
    '"she summoned medical assistance"',
    '"he summoned a meeting of head delegates"',
    '"she managed to summon up a smile"',
    '"names that summon up images of far-off places"',
]
export const synonyms = [
    'send for',
    'call for',
    'ask for',
    'ask',
    'invite',
    'bid',
    'request the presence of',
    'demand the presence of',
    'convene',
    'assemble',
    'order',
    'call',
    'muster',
    'rally',
    'levy',
    'round up',
    'announce',
    'declare',
    'convoke',
    'muster',
    'gather',
    'collect',
    'rally',
    'mobilize',
    'screw up',
    'call into action',
    'evoke',
    'recall',
    'revive',
    'invoke',
    'raise',
    'arouse',
    'kindle',
    'awaken',
    'excite',
    'stir up',
    'provoke',
    'call to mind',
    'bring to mind',
    'call up/forth',
    'conjure up',
    'spark (off)',
]