export const definitions = [
    '"a superb performance"',
    '"a superb Egyptian statue of Osiris"',
]
export const synonyms = [
    'excellent',
    'superlative',
    'first-rate',
    'first-class',
    'superior',
    'supreme',
    'outstanding',
    'remarkable',
    'dazzling',
    'marvelous',
    'magnificent',
    'wonderful',
    'splendid',
    'admirable',
    'noteworthy',
    'impressive',
    'fine',
    'exquisite',
    'exceptional',
    'glorious',
    'sublime',
    'perfect',
    'of the first order',
    'of the first water',
    'poor',
    'inferior',
    'magnificent',
    'majestic',
    'splendid',
    'grand',
    'impressive',
    'imposing',
    'awe-inspiring',
    'breathtaking',
    'gorgeous',
    'choice',
    'resplendent',
    'stately',
    'sumptuous',
    'opulent',
    'lavish',
    'luxurious',
    'deluxe',
    'poor',
    'inferior',
]