export const definitions = [
    '"they remained supine in the face of terrible wrongdoing"',
]
export const synonyms = [
    'prone',
    'recumbent',
    'prostrate',
    'spreadeagled',
    'lying',
    'sprawling',
    'horizontal',
    'flat on one\'s back',
    'stretched out',
    'flat as a pancake',
    'erect',
    'vertical',
    'weak',
    'spineless',
    'yielding',
    'enervated',
    'effete',
    'docile',
    'acquiescent',
    'pliant',
    'submissive',
    'servile',
    'inactive',
    'passive',
    'inert',
    'spiritless',
    'apathetic',
    'indifferent',
    'strong',
    'assertive',
]