export const definitions = [
    '"there is a thin line between success and failure"',
    '"the region has had some success in attracting light industry"',
    '"her success owed more to hard work than luck"',
    '"the success of his play"',
    '"overall the fair was a great success"',
    '"I must make a success of my business"',
    '"the good or ill success of their maritime enterprises"',
]
export const synonyms = [
    'successfulness',
    'victory',
    'triumph',
    'favorable outcome',
    'favorable result',
    'successful outcome',
    'positive result',
    'failure',
    'prosperity',
    'prosperousness',
    'successfulness',
    'affluence',
    'wealth',
    'riches',
    'fortune',
    'opulence',
    'luxury',
    'comfort',
    'milk and honey',
    'life of ease',
    'the good life',
    'failure',
    'poverty',
    'triumph',
    'bestseller',
    'sellout',
    'coup',
    'master stroke',
    'star',
    'superstar',
    'celebrity',
    'big name',
    'household name',
    'somebody',
    'VIP',
    'personality',
    'dignitary',
    'luminary',
    'leading light',
    'box-office success',
    'important person',
    'public figure',
    'failure',
    'flop',
    'disaster',
    'nobody',
    'result',
    'end result',
    'consequence',
    'upshot',
    'effect',
    'aftereffect',
    'aftermath',
    'conclusion',
    'sequel',
    'follow-up',
    'issue',
    'product',
    'end product',
    'end',
    'development',
    'offshoot',
    'outgrowth',
    'wake',
    'denouement',
    'sequelae',
    'net result',
]