export const definitions = [
    '"sutures are removed on the 5th to 7th day after the operation"',
    '"the small incision was sutured"',
]
export const synonyms = [
    'join',
    'stitching',
    'joint',
    'junction',
    'closure',
    'line',
    'join',
    'joint',
    'intersection',
    'link',
    'bond',
    'weld',
    'seam',
    'coupling',
    'connection',
    'union',
    'juncture',
    'brace',
    'bracket',
    'hinge',
    'commissure',
    'synapse',
]