export const definitions = [
  '"directors with swanky company cars"',
];
export const synonyms = [
  'luxurious',
  'luxury',
  'deluxe',
  'plush',
  'sumptuous',
  'palatial',
  'lavish',
  'gorgeous',
  'opulent',
  'splendid',
  'magnificent',
  'lush',
  'glamorous',
  'glittering',
  'rich',
  'costly',
  'expensive',
  'upmarket',
  'fancy',
  'stylish',
  'grandiose',
  'Lucullan',
  'lavishly appointed',
  'palatian',
  'plain',
  'austere',
  'bragging',
  'crowing',
  'swaggering',
  'braggart',
  'overweening',
  'overbearing',
  'bumptious',
  'puffed up',
  'vaunting',
  'blowhard',
  'ostentatious',
  'full of oneself',
  'cocky',
  'conceited',
  'proud',
  'arrogant',
  'vain',
  'egotistical',
  'vainglorious',
  'modest',
  'unassuming',
];