export const definitions = [
    '"the symbol r in Figure 5 represents a gene which is ineffective"',
    '"the chemical symbol for helium is He"',
    '"the Red Cross symbol"',
    '"the Star of David, the Jewish symbol"',
    '"the limousine was another symbol of his wealth and authority"',
]
export const synonyms = [
    'sign',
    'character',
    'mark',
    'letter',
    'hieroglyph',
    'ideogram',
    'logo',
    'emblem',
    'badge',
    'stamp',
    'trademark',
    'crest',
    'insignia',
    'coat of arms',
    'seal',
    'figure',
    'device',
    'rune',
    'logotype',
    'logogram',
    'monogram',
    'hallmark',
    'tag',
    'flag',
    'motto',
    'token',
    'motif',
    'colophon',
    'ideogram',
    'emblem',
    'token',
    'sign',
    'representation',
    'figure',
    'image',
    'type',
    'metaphor',
    'allegory',
    'represent',
    'stand for',
    'exemplify',
    'denote',
    'signify',
    'mean',
    'communicate',
    'indicate',
    'convey',
    'express',
    'imply',
    'suggest',
    'embody',
    'epitomize',
    'encapsulate',
    'personify',
    'typify',
    'betoken',
    'be a symbol of',
    'be a sign of',
    'allude to',
]