export const definitions = [
    '"the state railroad system"',
    '"fluid is pushed through a system of pipes or channels"',
    '"the digestive system"',
    '"you need to get the cholesterol out of your system"',
    '"the Devonian system"',
    '"the system of bright stars known as the Gould Belt"',
    '"a multiparty system of government"',
    '"the public school system"',
    '"the metric system"',
    '"there was no system at all in the company"',
    '"don\'t try bucking the system"',
]
export const synonyms = [
    'structure',
    'organization',
    'order',
    'arrangement',
    'complex',
    'apparatus',
    'network',
    'administration',
    'institution',
    'method',
    'methodology',
    'technique',
    'process',
    'procedure',
    'approach',
    'practice',
    'line',
    'attack',
    'means',
    'way',
    'manner',
    'mode',
    'framework',
    'modus operandi',
    'scheme',
    'plan',
    'policy',
    'program',
    'regimen',
    'formula',
    'routine',
    'tactic',
    'tack',
    'line of action',
    'line of attack',
    'set of principles',
    'set of procedures',
    'set of guidelines',
    'law',
    'laws',
    'rules',
    'regulations',
    'constitution',
    'charter',
    'canon',
    'jurisprudence',
    'body of law',
    'orderliness',
    'systematization',
    'planning',
    'logic',
    'routine',
    'methodicalness',
    'the establishment',
    'the powers that be',
    'bureaucracy',
    'officialdom',
    'the authorities',
    'the ruling class',
    'the regime',
    'the status quo',
    'the prevailing political/social order',
    'the regimen',
]