export const definitions = [
  '"the minority attempted to control the Council by a delaying tactic"',
  '"these are possible tax-saving tactics to discuss with your accountant"',
  '"basic infantry tactics were taught by guest instructors"',
];
export const synonyms = [
  'strategy',
  'scheme',
  'stratagem',
  'plan',
  'maneuver',
  'method',
  'program',
  'expedient',
  'gambit',
  'move',
  'approach',
  'tack',
  'path',
  'road',
  'device',
  'trick',
  'ploy',
  'dodge',
  'ruse',
  'game',
  'machination',
  'contrivance',
  'stunt',
  'means',
  'wiles',
  'artifice',
  'subterfuge',
  'shift',
  'set of tactics',
  'course/line of action',
  'plans',
  'game plans',
  'moves',
  'maneuvers',
  'logistics',
  'strategy',
  'policy',
  'campaign',
  'generalship',
  'military science',
  'organization',
  'planning',
  'arrangement',
  'administration',
  'direction',
  'masterminding',
  'orchestration',
  'handling',
  'running',
  'battle plans',
];