export const definitions = [
    '"the bears were tagged and released"',
    '"we have to tag the sheep before sale or when moving them from one farm to another"',
    '"he left because he didn\'t want to be tagged as a soap star"',
    '"storefronts are shuttered with metal roll-down barricades tagged with graffiti"',
    '"I will be tagged in every photo I post"',
    '"pieces of DNA tagged with radioactive particles"',
    '"she meant to tag her question on at the end of her remarks"',
    '"that\'ll teach you not to tag along where you\'re not wanted"',
    '"catching their fastest runner in a rundown and tagging him out"',
    '"the short center fielder could field the ball and tag second base for a force out"',
    '"when the ball was hit, he went back to the bag to tag up"',
]
export const synonyms = [
    'label',
    'mark',
    'ticket',
    'earmark',
    'identify',
    'docket',
    'flag',
    'indicate',
    'attach tags to',
    'put a label on',
    'designate',
    'describe',
    'identify',
    'classify',
    'label',
    'class',
    'categorize',
    'characterize',
    'mark',
    'stamp',
    'brand',
    'pigeonhole',
    'stereotype',
    'typecast',
    'compartmentalize',
    'typify',
    'name',
    'call',
    'nickname',
    'title',
    'entitle',
    'dub',
    'term',
    'style',
    'christen',
    'baptize',
    'add',
    'tack',
    'join',
    'attach',
    'append',
    'affix',
    'annex',
    'follow',
    'trail',
    'come after',
    'go after',
    'shadow',
    'dog',
    'go with',
    'accompany',
    'attend',
    'escort',
    'tread on the heels of',
]