export const definitions = [
    '"he possesses more talent than any other player"',
    '"she displayed a talent for garden design"',
    '"I signed all the talent in Rome"',
    '"Simon is a talent to watch"',
    '"most Saturday nights I have this urge to go on the hunt for new talent"',
    '"a mighty steed bought from a Thessalian merchant for thirteen talents"',
]
export const synonyms = [
    'flair',
    'aptitude',
    'facility',
    'gift',
    'knack',
    'technique',
    'touch',
    'bent',
    'ability',
    'expertise',
    'capacity',
    'power',
    'faculty',
    'strength',
    'strong point',
    'forte',
    'genius',
    'brilliance',
    'dexterity',
    'adroitness',
    'skill',
    'cleverness',
    'virtuosity',
    'artistry',
    'inability',
    'clumsiness',
]