export const definitions = [
    '"the tail tapers to a rounded tip"',
    '"David asked my dressmaker to taper his trousers"',
    '"the impact of the dollar\'s depreciation started to taper off"',
    '"he lit the tapers in the silver candelabra"',
    '"the current industry standard taper of 5 degrees"',
    '"with the taper in training, athletes can feel less hungry"',
]
export const synonyms = [
    'narrow',
    'attenuate',
    'thin (out)',
    'become narrow',
    'become narrower',
    'become thin',
    'become thinner',
    'come to a point',
    'thicken',
    'swell',
    'decrease',
    'lessen',
    'dwindle',
    'diminish',
    'reduce',
    'subside',
    'decline',
    'die off',
    'fade',
    'wane',
    'ebb',
    'abate',
    'wind down',
    'fall off',
    'drop off',
    'let up',
    'weaken',
    'wilt',
    'slump',
    'plummet',
    'fall off a cliff',
    'die away',
    'die down',
    'peter out',
    'slacken (off)',
    'trail off/away',
    'thin out',
    'increase',
    'candle',
    'spill',
    'wick',
    'night light',
    'dip',
    'glim',
    'rushlight',
    'wax light',
]