export const definitions = [
  '"damask curtains were held by silk cords with gold tassels"',
  '"the pollen forms on the tassel"',
  '"the banner was tasseled with silk and golden cords"',
];
export const synonyms = [
  'comb',
  'plume',
  'tuft',
  'topknot',
  'mane',
  'aigrette',
  'panache',
  'caruncle',
  'trim',
  'hem',
  'edge',
  'border',
  'rim',
  'bind',
  'braid',
  'decorate',
  'adorn',
  'ornament',
  'embellish',
  'finish',
  'purfle',
  'befringe',
  'befrill',
];