export const definitions = [
  '"he never tattled or told tales"',
  '"I would tattle on her whenever I had hard evidence"',
];
export const synonyms = [
  'inform',
  'report',
  'talk',
  'tell all',
  'spill the beans',
  'accuse',
  'gossip',
  'tittle-tattle',
  'chatter',
  'chat',
  'chitchat',
  'prattle',
  'prate',
  'babble',
  'blabber',
  'jabber',
  'gabble',
  'rattle on',
  'spread rumors',
  'spread gossip',
  'circulate rumors',
  'spread stories',
  'gossip',
  'rumor',
  'tittle-tattle',
  'hearsay',
  'prattle',
  'scandal',
  'small talk',
  'chitchat',
];