export const definitions = [
    '"a military tattoo takes place with clockwork precision"',
    '"a visit to Edinburgh during the Festival includes a visit to the Tattoo"',
    '"a crash involving two Russian jet fighters at the International Air Tattoo"',
    '"she tapped her fingers in a nervous tattoo"',
    '"his cheek was tattooed with a winged fist"',
    '"he has a heart tattooed on his left hand"',
    '"they were muscle-bound men covered in scars and tattoos"',
]
export const synonyms = [
    'festival',
    'fiesta',
    'fete',
    'gala',
    'jamboree',
    'holiday',
    'celebration',
    'party',
    'parade',
    'procession',
    'march',
    'pitter-patter',
    'tapping',
    'pattering',
    'drumming',
    'drumbeat',
    'clatter',
    'beat',
    'beating',
    'pounding',
    'throb',
    'pulsation',
    'rat-a-tat',
    'pit-a-pat',
    'clack',
    'click-clack',
    'thrum',
    'thrumming',
    'clacketing',
    'tap',
    'beat',
    'rap',
    'knock',
    'strike',
    'thud',
    'thump',
    'hit',
    'thrum',
]