export const definitions = [
    '"pupils will play truant rather than face the taunts of classmates about their ragged clothes"',
    '"students began taunting her about her weight"',
    '"you once taunted me taunted me with cowardice because I dared not face the world and conquer it"',
]
export const synonyms = [
    'jeer',
    'gibe',
    'sneer',
    'insult',
    'barb',
    'catcall',
    'brickbat',
    'scoff',
    'teasing',
    'taunting',
    'provocation',
    'goading',
    'ridiculing',
    'derision',
    'mockery',
    'sarcasm',
    'slap in the face',
    'poke fun at',
    'make fun of',
    'get at',
    'insult',
    'tease',
    'chaff',
    'torment',
    'provoke',
    'goad',
    'ridicule',
    'deride',
    'mock',
    'heckle',
    'ride',
    'make sport of',
    'jeer at',
    'gibe at',
    'sneer at',
    'scoff at',
]