export const definitions = [
    '"the fabric stays taut without adhesive"',
    '"my voice was taut with anger"',
    '"a taut text of only a hundred and twenty pages"',
    '"his language was salty and he ran a taut ship"',
]
export const synonyms = [
    'tight',
    'stretched',
    'rigid',
    'stressed',
    'tightly stretched',
    'not slack',
    'not loose',
    'slack',
    'loose',
    'flexed',
    'tensed',
    'tightened',
    'hard',
    'solid',
    'firm',
    'rigid',
    'stiff',
    'unyielding',
    'fraught',
    'strained',
    'stressed',
    'tense',
    'drawn',
    'drained',
    'sapped',
    'fatigued',
    'tired',
    'relaxed',
    'concise',
    'controlled',
    'crisp',
    'pithy',
    'sharp',
    'succinct',
    'compact',
    'terse',
    'verbose',
    'orderly',
    'in order',
    'tight',
    'trim',
    'neat',
    'well ordered',
    'tidy',
    'spruce',
    'smart',
    'in good order',
    'in good condition',
    'well regulated',
    'well disciplined',
    'shipshape (and Bristol fashion)',
]