export const definitions = [
  '"I tore up the letter"',
  '"he tore up the floorboards"',
  '"he tore off his belt"',
  '"Joe tore the sack from her hand"',
  '"she was always tearing her clothes"',
  '"the blast tore a hole in the wall"',
  '"the material wouldn\'t tear"',
  '"he tore a ligament playing squash"',
  '"she tore along the footpath on her bike"',
  '"he was torn between his duty and his better instincts"',
  '"I\'m torn and I\'m confused"',
  '"there was a tear in her dress"',
  '"one of my drinking buddies came for the weekend and we went on a tear"',
  '"he went on a tear, winning three out of every four hands"',
];
export const synonyms = [
  'rip up',
  'pull apart',
  'shred',
  'rip in two',
  'pull to pieces',
  'snatch',
  'grab',
  'seize',
  'rip',
  'wrench',
  'wrest',
  'pull',
  'pluck',
  'rip',
  'snag',
  'ladder',
  'lacerate',
  'gash',
  'slash',
  'scratch',
  'claw',
  'mangle',
  'mutilate',
  'hack',
  'pierce',
  'stab',
  'injure',
  'wound',
  'cut (open)',
  'cut to pieces',
  'cut to ribbons',
  'sprint',
  'race',
  'run',
  'dart',
  'rush',
  'dash',
  'hasten',
  'hurry',
  'scurry',
  'scuttle',
  'scamper',
  'hare',
  'bolt',
  'bound',
  'fly',
  'gallop',
  'career',
  'charge',
  'pound',
  'shoot',
  'hurtle',
  'speed',
  'streak',
  'flash',
  'whiz',
  'zoom',
  'sweep',
  'post',
  'hie',
  'go like lightning',
  'go hell for leather',
  'go like the wind',
  'stroll',
  'amble',
  'torment',
  'torture',
  'rack',
  'harrow',
  'wring',
  'lacerate',
  'rend',
  'rip',
  'hole',
  'split',
  'rent',
  'cut',
  'slash',
  'slit',
  'ladder',
  'run',
  'snag',
];