export const definitions = [
    '"he rushed out in a very bad temper"',
    '"I know my temper gets the better of me at times"',
    '"Drew had walked out in a temper"',
    '"I only said it in a fit of temper"',
    '"the blade rapidly heats up and the metal loses its temper"',
    '"the way a smith would temper a sword"',
    '"tempered steel pins"',
    '"the display is a single sheet of glass, tempered for strength"',
    '"for a shiny sheen to the chocolate coating, I recommend tempering the chocolate first"',
    '"their idealism is tempered with realism"',
]
export const synonyms = [
    'temperament',
    'disposition',
    'nature',
    'character',
    'personality',
    'makeup',
    'constitution',
    'mind',
    'spirit',
    'stamp',
    'mettle',
    'mold',
    'mood',
    'frame of mind',
    'attitude',
    'humor',
    'grain',
    'cast of mind',
    'habit of mind',
    'anger',
    'fury',
    'rage',
    'annoyance',
    'vexation',
    'crossness',
    'irascibility',
    'irritation',
    'irritability',
    'ill humor',
    'ill temper',
    'dyspepsia',
    'spleen',
    'pique',
    'petulance',
    'peevishness',
    'pettishness',
    'testiness',
    'tetchiness',
    'snappishness',
    'crabbiness',
    'resentment',
    'surliness',
    'churlishness',
    'air rage',
    'ire',
    'choler',
    'good humor',
    'rage',
    'fury',
    'tantrum',
    'passion',
    'paroxysm',
    'bad mood',
    'mood',
    'pet',
    'sulk',
    'miff',
    'fit of rage',
    'fit of bad/ill temper',
    'bad temper',
    'fit of pique',
    'mard',
    'paddywhack',
    'harden',
    'strengthen',
    'toughen',
    'fortify',
    'anneal',
    'moderate',
    'modify',
    'modulate',
    'tone down',
    'mitigate',
    'palliate',
    'alleviate',
    'allay',
    'assuage',
    'lessen',
    'reduce',
    'weaken',
    'lighten',
    'soften',
    'cushion',
    'qualify',
]