export const definitions = [
    '"council-house tenants"',
    '"a frequent tenant of the gossip columns"',
    '"the house was tenanted by his cousin"',
]
export const synonyms = [
    'occupant',
    'resident',
    'inhabitant',
    'leaseholder',
    'lessee',
    'renter',
    'holder',
    'addressee',
    'lodger',
    'boarder',
    'occupier',
    'roomer',
    'dweller',
    'sitting tenant',
    'feodary',
    'owner',
    'freeholder',
    'live in',
    'inhabit',
    'people',
    'populate',
    'settle',
    'be the tenant of',
    'lodge in',
    'be established/ensconced in',
    'establish/ensconce oneself in',
    'take up residence in',
    'make one\'s home in ',
    'settle in',
    'move into',
    'stay in',
    'reside in',
    'dwell in',
]