export const definitions = [
    '"the tenets of a democratic society"',
]
export const synonyms = [
    'principle',
    'belief',
    'doctrine',
    'precept',
    'creed',
    'credo',
    'dogma',
    'canon',
    'rule',
    'theory',
    'thesis',
    'conviction',
    'persuasion',
    'idea',
    'view',
    'opinion',
    'position',
    'hypothesis',
    'postulation',
    'presumption',
    'ideology',
    'teaching(s)',
    'article of faith',
    'component of a theory',
    'code of belief',
]