export const definitions = [
  '"his central thesis is that psychological life is not part of the material world"',
  '"a doctoral thesis"',
];
export const synonyms = [
  'theory',
  'contention',
  'argument',
  'proposal',
  'proposition',
  'premise',
  'assumption',
  'presumption',
  'hypothesis',
  'postulation',
  'surmise',
  'supposition',
  'belief',
  'idea',
  'notion',
  'opinion',
  'view',
  'theme',
  'subject',
  'topic',
  'text',
  'matter',
  'theorem',
  'line of argument',
  'dissertation',
  'essay',
  'paper',
  'treatise',
  'disquisition',
  'composition',
  'monograph',
  'study',
  'theme',
  'piece of writing',
];