export const definitions = [
    '"he had a loose thread on his shirt"',
    '"the thread that bound them had snapped"',
    '"she put her needle and thread away"',
    '"the river was a thread of silver below them"',
    '"a common thread running through the scandals was the failure to conduct audits"',
    '"his fine threads and fashionable specs"',
    '"I can\'t even thread a needle"',
    '"she threaded up the machine with the right cotton"',
    '"he threaded the rope through a pulley"',
    '"Connie sat threading beads"',
    '"thread the buttons onto a length of cotton"',
    '"she threaded her way through the tables"',
    '"his hair had become ill-kempt and threaded withgray"',
    '"I had my eyebrows threaded today"',
    '"we\'re laser - cutting holes to be threaded for screws"',
]
export const synonyms = [
    'yarn',
    'cotton',
    'filament',
    'fiber',
    'strand',
    'string',
    'twine',
    'line',
    'ply',
    'streak',
    'strand',
    'stripe',
    'line',
    'striation',
    'strip',
    'seam',
    'vein',
    'belt',
    'bar',
    'swathe',
    'train of thought',
    'drift',
    'direction',
    'sense',
    'theme',
    'subject matter',
    'motif',
    'tenor',
    'strain',
    'thrust',
    'subject',
    'gist',
    'burden',
    'action',
    'plot',
    'storyline',
    'scenario',
    'outfit',
    'clothes',
    'costume',
    'ensemble',
    'suit',
    'clothing',
    'dress',
    'attire',
    'garments',
    'garb',
    'turnout',
    'rig',
    'uniform',
    'livery',
    'array',
    'regalia',
    'robes',
    'finery',
    'apparel',
    'raiment',
    'habiliments',
    'vestments',
    'vesture',
    'habit',
    'pass',
    'string',
    'weave',
    'work',
    'ease',
    'inch',
    'move',
    'push',
    'poke',
    'thrust',
    'string',
    'file',
    'make one\'s way',
    'progress',
    'pass',
    'weave (one\'s way) ',
    'inch (\'s \'s way) ',
    'wind (\'s \'s way) ',
    'work (\'s \'s way) ',
    'push (\'s \'s way) ',
    'squeeze (\'s \'s way) ',
    'shoulder (\'s \'s way) ',
    'elbow (\'s \'s way) ',
]