export const definitions = [
    '"I threw a brick through the window"',
    '"the pilot and one passenger were thrown clear and survived"',
    '"the door was thrown open and a uniformed guard entered the room"',
    '"the stewards had thrown a cordon across the fairway"',
    '"she threw her head back and laughed"',
    '"a chandelier threw its bright light over the walls"',
    '"Cheryl drew back her fist and threw another punch"',
    '"she threw a withering glance at him"',
    '"I can throw my voice—I could make a fortune as a medium"',
    '"at the trolley portal the operator had to manually throw the switch using a switch iron"',
    '"he reached out and put the dice in the shaker and threw them"',
    '"he threw all her emotions into turmoil"',
    '"the bond market was thrown into confusion"',
    '"these guys should be thrown in jail"',
    '"she frowned, thrown by this apparent change of tack"',
    '"in the final Arnaud was too strong, and threw Hughes twice"',
    '"their horse threw its jockey before the race had started"',
    '"further on a potter was throwing pots"',
    '"occasionally a small child will throw a tantrum when denied something"',
    '"he threw a huge farewell party for them"',
    '"the man who throws a race is a crook for life"',
    '"sometimes a completely black calf is thrown"',
]
export const synonyms = [
    'hurl',
    'toss',
    'fling',
    'pitch',
    'cast',
    'lob',
    'launch',
    'flip',
    'catapult',
    'shy',
    'dash',
    'aim',
    'direct',
    'project',
    'propel',
    'send',
    'bowl',
    'catch',
    'hold',
    'thrust',
    'fling',
    'propel',
    'shoot',
    'slam',
    'smack',
    'bang',
    'crash',
    'thump',
    'push',
    'force',
    'move quickly/suddenly',
    'push suddenly/violently',
    'project',
    'cast',
    'send',
    'emit',
    'radiate',
    'give off',
    'deliver',
    'give',
    'land',
    'pull',
    'direct',
    'cast',
    'send',
    'dart',
    'shoot',
    'give',
    'bestow on',
    'operate',
    'switch on',
    'engage',
    'move',
    'click on',
    'disconcert',
    'unnerve',
    'fluster',
    'ruffle',
    'flurry',
    'agitate',
    'harass',
    'upset',
    'disturb',
    'discomfit',
    'put off',
    'put someone off their stroke',
    'discompose',
    'discountenance',
    'perturb',
    'unsettle',
    'bother',
    'affect',
    'worry',
    'disquiet',
    'trouble',
    'confuse',
    'throw off balance',
    'make nervous',
    'cause someone to lose their composure',
    'fell',
    'unbalance',
    'bring down',
    'floor',
    'prostrate',
    'throw to the ground',
    'hurl to the ground',
    'unseat',
    'dislodge',
    'upset',
    'bring down',
    'shape',
    'form',
    'mold',
    'fashion',
    'give',
    'host',
    'hold',
    'have',
    'provide',
    'put on',
    'lay on',
    'arrange',
    'organize',
]