export const definitions = [
  '"she thrust her hands into her pockets"',
  '"Howard was thrust into the limelight"',
  '"he thrust at his opponent with his sword"',
  '"she thrust through the bramble canes"',
  '"he tried to thrust his way past her"',
  '"beside the boathouse a jetty thrust out into the water"',
  '"he felt that fame had been thrust upon him"',
  '"he drove the blade upward with one powerful thrust"',
  '"executives led a new thrust in business development"',
  '"anti-Americanism became the main thrust of their policy"',
  '"the engine was a Russian-built Nene of higher thrust than the original models"',
];
export const synonyms = [
  'shove',
  'push',
  'propel',
  'impel',
  'send',
  'press',
  'drive',
  'plunge',
  'stick',
  'force',
  'shoot',
  'ram',
  'barge',
  'bump',
  'knock',
  'strike',
  'hit',
  'jolt',
  'butt',
  'prod',
  'poke',
  'nudge',
  'elbow',
  'shoulder',
  'bulldoze',
  'sweep',
  'jostle',
  'bundle',
  'hustle',
  'hurry',
  'rush',
  'manhandle',
  'impose',
  'foist',
  'unload',
  'inflict',
  'obtrude',
  'urge',
  'saddle someone with',
  'land someone with',
  'burden someone with',
  'lumber someone with',
  'stick out',
  'jut',
  'protrude',
  'extend',
  'stand out',
  'overhang',
  'obtrude',
  'cantilever',
  'jut out',
  'hang over',
  'bulge out',
  'poke out',
  'lap over',
  'ride over',
  'thrust out',
  'be imminent',
  'protuberate',
  'shove',
  'push',
  'ram',
  'prod',
  'poke',
  'stab',
  'jab',
  'lunge',
  'drive',
  'barge',
  'bump',
  'bang',
  'jolt',
  'butt',
  'knock',
  'nudge',
  'advance',
  'push',
  'drive',
  'charge',
  'attack',
  'assault',
  'onslaught',
  'onrush',
  'offensive',
  'sortie',
  'foray',
  'raid',
  'sally',
  'invasion',
  'incursion',
  'blitz',
  'campaign',
  'onset',
  'barb',
  'insult',
  'criticism',
  'censure',
  'vitriol',
  'barbed remark',
  'verbal attack/assault',
  'hostile remark',
  'gist',
  'substance',
  'drift',
  'implication',
  'intention',
  'burden',
  'meaning',
  'significance',
  'signification',
  'sense',
  'essence',
  'thesis',
  'import',
  'purport',
  'tenor',
  'message',
  'spirit',
  'force',
  'propulsion',
  'drive',
  'actuation',
  'impetus',
  'impulse',
  'impulsion',
  'momentum',
  'push',
  'pressure',
  'power',
  'motive force',
  'propulsive force',
  'driving force',
];