export const definitions = [
  '"when you are out with your puppy always have a tidbit in your pocket"',
  '"they were hoping for tidbits about the family"',
];
export const synonyms = [
  'delicacy',
  'dainty',
  'fancy',
  'confection',
  'luxury',
  'treat',
  'snack',
  'nibble',
  'savory',
  'appetizer',
  'namkeen',
  'sweetmeat',
  'tasty morsel',
  'bonne bouche',
  'piece of gossip',
  'bit of scandal',
  'juicy bit of gossip',
  'juicy bit of news',
  'scrap of information',
  'morsel of information',
  'item of information',
];