export const definitions = [
    '"we were all a little bit tiddly"',
    '"a tiddly little pool"',
]
export const synonyms = [
    'intoxicated',
    'inebriated',
    'drunken',
    'befuddled',
    'incapable',
    'tipsy',
    'under the influence',
    'maudlin',
    'blind drunk',
    '(as) drunk as a skunk',
    'sottish',
    'tippling',
    'toping',
    'sotted',
    'besotted',
    'foxed',
    'screwed',
    'crapulent',
    'crapulous',
    'inebriate',
    'bibulous',
    'the worse for drink',
    'dead drunk',
    'rolling drunk',
    'roaring drunk',
    '(as) drunk as a lord',
    'gin-soaked',
    'ebrious',
    'ebriose',
    'ebriate',
    'sober',
    'little',
    'small-scale',
    'compact',
    'bijou',
    'portable',
    'tiny',
    'miniature',
    'mini',
    'minute',
    'microscopic',
    'microscale',
    'nanoscopic',
    'minuscule',
    'toy',
    'baby',
    'poky',
    'cramped',
    'boxy',
    'wee',
    'big',
    'large',
]