export const definitions = [
    '"inflammation is a reaction of living tissue to infection or injury"',
    '"scar tissue"',
    '"DNA prepared from tissue samples"',
    '"the organs and tissues of the body"',
    '"a slim package wrapped in blue tissue"',
    '"a box of tissues"',
    '"Rosheen wiped her fingers on a sheet of tissue"',
    '"the blue and silver tissue sari"',
    '"such scandalous stories are a tissue of lies"',
]
export const synonyms = [
    'matter',
    'material',
    'substance',
    'stuff',
    'flesh',
    'the body',
    'tissue paper',
    'wrapping paper',
    'facial tissue',
    'toilet tissue',
    'toilet paper',
    'wipe',
    'paper towel',
    'Kleenex',
    'paper handkerchief',
    'disposable handkerchief',
    'kitchen towel',
    'gauze',
    'gossamer',
    'chiffon',
    'netting',
    'mesh',
    'lattice',
    'web',
    'webbing',
    'screen',
    'mat',
    'fabric',
    'material',
    'textile',
    'fiber',
    'web',
    'network',
    'nexus',
    'maze',
    'tangle',
    'knot',
    'complex',
    'mass',
    'conglomeration',
    'set',
    'series',
    'chain',
]