export const definitions = [
    '"the rules have not been altered one jot or tittle since"',
]
export const synonyms = [
    'bit',
    'scrap',
    'shred',
    'speck',
    'iota',
    'particle',
    'ounce',
    'whit',
    'jot',
    'atom',
    'crumb',
    'morsel',
    'fragment',
    'grain',
    'drop',
    'hint',
    'touch',
    'trace',
    'suggestion',
    'whisper',
    'suspicion',
    'scintilla',
    'spot',
    'mite',
    'modicum',
    'tiny amount',
    'jot or tittle',
    'stim',
]