export const definitions = [
  '"a flat-topped hat"',
  '"snow-topped hills"',
  '"high-topped leather boots"',
  '"losses are expected to top $100 million this year"',
  '"her debut album topped the charts for five weeks"',
  '"he topped her by several inches"',
  '"he was baffled as to how he could top his past work"',
  '"Hopper topped a great night of boxing"',
  '"baked potatoes topped with melted cheese"',
  '"a white dress topped by a dark cardigan"',
  '"I use the sharp edge of an old butcher\'s knife for topping and the back of the blade for cleaning the roots"',
  '"they topped a rise and began a slow descent"',
  '"he topped his drive on the fifth hole"',
  '"sliced and topped shots"',
];
export const synonyms = [
  'exceed',
  'surpass',
  'transcend',
  'better',
  'best',
  'beat',
  'defeat',
  'excel',
  'outstrip',
  'outdo',
  'outshine',
  'eclipse',
  'surmount',
  'cap',
  'trump',
  'trounce',
  'go beyond',
  'improve on',
  'go one better than',
  'lead',
  'head',
  'be first in',
  'be at the top of',
  'cover',
  'cap',
  'crown',
  'coat',
  'overspread',
  'finish',
  'garnish',
  'crest',
  'climb',
  'scale',
  'ascend',
  'mount',
  'conquer',
  'reach the top of',
];