export const definitions = [
  '"we sat around in a torpid state"',
  '"the animal need not lie around in a torpid state, vulnerable to attack"',
];
export const synonyms = [
  'lethargic',
  'sluggish',
  'inert',
  'inactive',
  'slow',
  'slow-moving',
  'lifeless',
  'dull',
  'listless',
  'languid',
  'lazy',
  'idle',
  'indolent',
  'shiftless',
  'slothful',
  'heavy',
  'stagnant',
  'somnolent',
  'sleepy',
  'tired',
  'fatigued',
  'languorous',
  'apathetic',
  'passive',
  'supine',
  'comatose',
  'narcotic',
  'energetic',
  'active',
  'lively',
];