export const definitions = [
  '"he scored a total of thirty-three points"',
  '"in total, 200 people were interviewed"',
  '"they were left with debts totaling $6,260"',
  '"the scores were totaled"',
  '"he almost totaled the car"',
];
export const synonyms = [
  'sum',
  'sum total',
  'grand total',
  'aggregate',
  'whole',
  'entirety',
  'totality',
  'summation',
  'result',
  'add up to',
  'come to',
  'run to',
  'make',
  'equal',
  'number',
  'amount to',
  'mount up to',
  'correspond to',
  'work out as',
  'tot up to',
  'add',
  'sum',
  'count',
  'reckon',
  'tot',
  'compute',
  'work out',
  'take stock of',
  'wreck',
  'crash',
  'smash',
  'destroy',
  'demolish',
  'write off',
  'damage beyond repair',
];