export const definitions = [
    '"a hunched figure was tottering down the path"',
    '"the building began to totter and then the roof gave way"',
    '"the industry has tottered from crisis to crisis"',
    '"his property empire was tottering on the brink of bankruptcy"',
    '"Coney Street in York was a totter\'s paradise on Tuesday morning"',
]
export const synonyms = [
    'teeter',
    'stagger',
    'wobble',
    'stumble',
    'dodder',
    'shuffle',
    'shamble',
    'falter',
    'reel',
    'toddle',
    'hobble',
    'sway',
    'roll',
    'lurch',
    'walk unsteadily',
    'shake',
    'sway',
    'tremble',
    'quiver',
    'teeter',
    'shudder',
    'judder',
    'rock',
    'quake',
    'reel',
    'lurch',
    'vibrate',
    'oscillate',
    'falter',
    'be unstable',
    'be unsteady',
    'be shaky',
    'be insecure',
    'be precarious',
    'be on the point of collapse',
    'teeter',
    'sway',
    'rocking',
    'swaying',
    'shaking',
    'unsteady movement',
]