export const definitions = [
    '"large tracts of natural forest"',
    '"the vast tracts of time required to account for the deposition of the strata"',
    '"the digestive tract"',
]
export const synonyms = [
    'area',
    'region',
    'expanse',
    'span',
    'sweep',
    'stretch',
    'extent',
    'belt',
    'swathe',
    'zone',
    'plot',
    'patch',
    'parcel',
    'portion',
    'section',
    'sector',
    'quarter',
    'territory',
    'estate',
    'acreage',
    'allotment',
    'treatise',
    'essay',
    'article',
    'paper',
    'monograph',
    'disquisition',
    'dissertation',
    'thesis',
    'exposition',
    'study',
    'lecture',
    'homily',
    'sermon',
    'work',
    'pamphlet',
    'booklet',
    'leaflet',
    'brochure',
    'piece of writing',
]