export const definitions = [
  '"he was a letter-of-the-law man, a common trait among coaches"',
  '"breeders were installing some trait that allowed the crop to thrive"',
];
export const synonyms = [
  'characteristic',
  'attribute',
  'feature',
  'quality',
  'property',
  'distinction',
  'idiosyncrasy',
  'peculiarity',
  'quirk',
  'foible',
  'singularity',
  'oddity',
  'eccentricity',
  'abnormality',
  'mark',
  'trademark',
  'hallmark',
  'earmark',
  'mannerism',
  'way',
  'trick',
  'habit',
  'custom',
  'tendency',
  'lineament',
  'essential quality',
];