export const definitions = [
  '"she put him into a light trance"',
  '"the kind of trance he went into whenever illness was discussed"',
  '"in the Hades Warehouse there\'s the finest in trance and techno"',
  '"\'s \'s been tranced and may need waking"',
];
export const synonyms = [
  'daze',
  'stupor',
  'haze',
  'dream',
  'daydream',
  'reverie',
  'suspended animation',
  'hypnotic state',
  'half-conscious state',
  'brown study',
  'dwam',
  'daze',
  'stupor',
  'haze',
  'dream',
  'daydream',
  'reverie',
  'suspended animation',
  'hypnotic state',
  'half-conscious state',
  'brown study',
  'dwam',
];