export const definitions = [
    '"the vessel had been traveling from Libya to Ireland"',
    '"we traveled thousands of miles"',
    '"he traveled the world with the army"',
    '"the exhibition will travel to London, New York City, Cape Town, and Tokyo"',
    '"he usually travels well"',
    '"accordion music travels well"',
    '"he traveled for a shoe company through Mississippi"',
    '"light travels faster than sound"',
    '"my job involves a lot of travel"',
    '"the pass allows you unlimited travel on public transport"',
    '"perhaps you\'ll write a book about your travels"',
    '"a travel iron"',
    '"two proximity switches detect when the valve has reached the end of its travel"',
]
export const synonyms = [
    'journey',
    'tour',
    'voyage',
    'globetrot',
    'backpack',
    'roam',
    'rove',
    'range',
    'cruise',
    'hike',
    'trek',
    'tramp',
    'ride',
    'roll',
    'cross',
    'traverse',
    'cover',
    'circumnavigate',
    'go around',
    'move',
    'go',
    'proceed',
    'peregrinate',
    'take a trip',
    'go on a trip',
    'go on an expedition',
    'go on an excursion',
    'go sightseeing',
    'wend one\'s way',
    'make \'s \'s way over',
    'move around',
    'move',
    'proceed',
    'progress',
    'advance',
    'carry',
    'be transmitted',
    'speed',
    'race',
    'hurry',
    'hurtle',
    'hasten',
    'whiz',
    'go fast',
    'go rapidly',
    'drive fast',
    'go at breakneck speed',
    'hotfoot it',
    'whip (along)',
    'go like (greased) lightning',
    'journeys',
    'expeditions',
    'trips',
    'tours',
    'excursions',
    'voyages',
    'treks',
    'safaris',
    'odysseys',
    'pilgrimages',
    'jaunts',
    'journeying',
    'traveling',
    'touring',
    'sightseeing',
    'voyaging',
    'cruising',
    'sailing',
    'backpacking',
    'globetrotting',
    'jet-setting',
    'exploration',
    'trekking',
    'wandering',
    'roving',
    'roaming',
    'peregrinations',
    'portable',
    'mobile',
    'transportable',
    'movable',
    'transferable',
    'conveyable',
    'lightweight',
    'compact',
    'handy',
    'convenient',
    'manageable',
    'easily carried',
    'easy to carry',
    'portative',
    'full-sized',
]