export const definitions = [
  '"we needn\'t trouble the headmaster over such trifles"',
  '"the thousand yen he\'d paid seemed the merest trifle"',
  '"syllabubs, trifles, and other dishes"',
  '"bowls of trifle followed"',
  '"he is not a man to be trifled with"',
  '"men who trifle with women\'s affections"',
  '"we will not trifle—life is too short"',
  '"he had trifled away two months at a task which should have taken a week"',
];
export const synonyms = [
  'triviality',
  'bagatelle',
  'inessential',
  'nothing',
  'technicality',
  'trivia',
  'minutiae',
  'bauble',
  'trinket',
  'knickknack',
  'gimcrack',
  'gewgaw',
  'toy',
  'unimportant thing/matter',
  'trivial thing/matter',
  'thing/matter of no consequence',
  'thing/matter of no importance',
  'pittance',
  'very small amount',
  'next to nothing',
  'hardly anything',
  'small fortune',
  'play ducks and drakes with',
  'play with',
  'treat in a cavalier fashion',
  'treat lightly',
  'treat frivolously',
  'treat casually',
  'dally with',
  'amuse oneself with',
  'toy with',
  'flirt with',
  'play fast and loose with',
  'sport with',
  'wanton with',
  'palter with',
];