export const definitions = [
    '"he put his hand on her hair and stroked it"',
    '"she strokes blue eyeshadow on her eyelids"',
    '"production executives were expert at stroking stars and brokering talent"',
    '"he stroked Penn\'s rowing eight to victory"',
    '"Miller calmly stroked three-pointers throughout the tournament"',
    '"the senior stroked a two-run single"',
]
export const synonyms = [
    'caress',
    'fondle',
    'pat',
    'pet',
    'touch',
    'brush',
    'rub',
    'massage',
    'knead',
    'soothe',
    'manipulate',
    'finger',
    'handle',
    'feel',
    'maul',
    'tickle',
    'pat',
    'press',
    'touch',
    'blot',
    'mop',
    'swab',
    'smudge',
    'spread',
    'daub',
    'bedaub',
    'apply',
    'wipe',
    'stipple',
]