export const definitions = [
  '"a turgid and fast-moving river"',
  '"some turgid verses on the death of Prince Albert"',
];
export const synonyms = [
  'swollen',
  'congested',
  'in spate',
  'in flood',
  'bombastic',
  'pompous',
  'overblown',
  'overripe',
  'inflated',
  'high-flown',
  'affected',
  'pretentious',
  'grandiose',
  'florid',
  'flowery',
  'ornate',
  'magniloquent',
  'grandiloquent',
  'rhetorical',
  'oratorical',
  'orotund',
  'stodgy',
  'ponderous',
  'labored',
  'strained',
  'stilted',
  'tumid',
  'euphuistic',
  'fustian',
  'sesquipedalian',
  'Ossianic',
  'simple',
  'plain',
];