export const definitions = [
    '"she twirled in delight to show off her new dress"',
    '"she twirled her fork in the pasta"',
    '"Kate did a twirl in front of the mirror"',
    '"on the lid was a name written in old-fashioned twirls"',
]
export const synonyms = [
    'pirouette',
    'whirl',
    'turn (around)',
    'wheel',
    'gyrate',
    'pivot',
    'swivel',
    'twist',
    'revolve',
    'rotate',
    'birl',
    'spin (around)',
    'wind',
    'twist',
    'coil',
    'curl',
    'wrap',
    'pirouette',
    'spin',
    'whirl',
    'turn',
    'twist',
    'rotation',
    'revolution',
    'gyration',
    'birl',
]