export const definitions = [
    '"the knot was difficult to undo"',
    '"there wasn\'t any way Evelyn could undo the damage"',
    '"you can frequently undo the error if you notice it in time"',
    '"Iago\'s hatred of women undoes him"',
]
export const synonyms = [
    'unfasten',
    'unbutton',
    'unhook',
    'untie',
    'unlace',
    'unbind',
    'unfetter',
    'unshackle',
    'unbridle',
    'unlock',
    'unbolt',
    'uncouple',
    'unhitch',
    'unlink',
    'unclick',
    'loosen',
    'loose',
    'disentangle',
    'extricate',
    'release',
    'detach',
    'free',
    'liberate',
    'open',
    'unseal',
    'unwrap',
    'let out',
    'disconnect',
    'disjoin',
    'disengage',
    'disunite',
    'separate',
    'unmanacle',
    'disentwine',
    'set free',
    'fasten',
    'do up',
    'revoke',
    'overrule',
    'overturn',
    'repeal',
    'rescind',
    'reverse',
    'retract',
    'take back',
    'disallow',
    'veto',
    'countermand',
    'cancel',
    'annul',
    'nullify',
    'invalidate',
    'negate',
    'abrogate',
    'disestablish',
    'set aside',
    'do away with',
    'wipe out',
    'avoid',
    'vacate',
    'recall',
    'rule against',
    'render null and void',
    'render invalid',
    'make ineffective',
    'bring to an end',
    'disannul',
    'ratify',
    'ruin',
    'undermine',
    'put an end to',
    'subvert',
    'overturn',
    'topple',
    'scupper',
    'scotch',
    'sabotage',
    'spoil',
    'mess up',
    'make a mess of',
    'quash',
    'squelch',
    'crush',
    'harm',
    'cripple',
    'impair',
    'mar',
    'destroy',
    'devastate',
    'play havoc with',
    'wreck',
    'smash',
    'shatter',
    'annihilate',
    'eradicate',
    'obliterate',
    'defeat',
    'neutralize',
    'thwart',
    'upset',
    'foil',
    'frustrate',
    'hamper',
    'hinder',
    'obstruct',
    'bring to naught',
    'put at risk',
    'cancel out',
    'render ineffective',
    'further',
    'enhance',
    'help',
]