export const definitions = [
    '"the floors are cracked and uneven"',
    '"the uneven distribution of resources"',
    '"Fran struggled briefly but soon gave up the uneven contest"',
]
export const synonyms = [
    'bumpy',
    'rough',
    'lumpy',
    'stony',
    'rocky',
    'potholed',
    'holey',
    'rutted',
    'rutty',
    'pitted',
    'jagged',
    'craggy',
    'dented',
    'indented',
    'knobby',
    'cragged',
    'even',
    'flat',
    'smooth',
    'irregular',
    'unequal',
    'differing',
    'dissimilar',
    'unlike',
    'unalike',
    'unbalanced',
    'lopsided',
    'awry',
    'askew',
    'crooked',
    'asymmetrical',
    'unsymmetrical',
    'disproportionate',
    'inconsistent',
    'variable',
    'varying',
    'changeable',
    'fluctuating',
    'intermittent',
    'wavering',
    'erratic',
    'patchy',
    'bitty',
    'unidentical',
    'not matching',
    'even',
    'regular',
    'consistent',
    'one-sided',
    'unequal',
    'unfair',
    'unjust',
    'inequitable',
    'ill-matched',
    'unbalanced',
    'lopsided',
    'biased',
    'prejudiced',
    'skewed',
    'equal',
    'fair',
]