export const definitions = [
    '"he was opposed to closer political or economic union with Europe"',
    '"a currency union between the two countries"',
    '"they live in perfect union"',
    '"their union had not been blessed with children"',
    '"members of the Students\' Union"',
    '"the National Farmers\' Union"',
    '"California is the fastest growing state in the Union when it comes to urban encroachment"',
]
export const synonyms = [
    'unification',
    'uniting',
    'joining',
    'merging',
    'merger',
    'fusion',
    'fusing',
    'amalgamating',
    'amalgamation',
    'junction',
    'coalition',
    'combining',
    'combination',
    'consolidation',
    'conjunction',
    'confederation',
    'federation',
    'integration',
    'synthesis',
    'blend',
    'blending',
    'mixture',
    'mingling',
    'commingling',
    'separation',
    'parting',
    'unity',
    'accord',
    'unison',
    'unanimity',
    'harmony',
    'concord',
    'agreement',
    'concurrence',
    'undividedness',
    'marriage',
    'wedding',
    'partnership',
    'pairing',
    'alliance',
    'match',
    'compact',
    'affiliation',
    'civil partnership',
    'coupling',
    'intercourse',
    'mating',
    'coition',
    'coitus',
    'copulation',
    'divorce',
    'annulment',
    'association',
    'alliance',
    'league',
    'guild',
    'coalition',
    'consortium',
    'combine',
    'syndicate',
    'confederation',
    'federation',
    'confederacy',
    'partnership',
    'fraternity',
    'brotherhood',
    'sorority',
    'society',
    'club',
    'group',
    'organization',
    'trade union',
    'join',
    'joint',
    'intersection',
    'link',
    'bond',
    'weld',
    'seam',
    'coupling',
    'connection',
    'juncture',
    'brace',
    'bracket',
    'hinge',
    'commissure',
    'suture',
    'synapse',
]