export const definitions = [
    '"the ship was ready to be unmoored"',
    '"the loss of his wife has unmoored him"',
    '"one of the things that unmoored me was slowly losing control of my self-image"',
]
export const synonyms = [
    'undo',
    'unknot',
    'unbind',
    'unfasten',
    'unwrap',
    'unlace',
    'untether',
    'unfetter',
    'unhitch',
    'unclick',
    'loose',
    'detach',
    'free',
    'release',
    'cast off',
    'set free',
    'let go',
    'set adrift',
    'tie up',
]