export const definitions = [
  '"she was feeling nervous, unsure of herself"',
  '"she was unsure how to reply"',
  '"the date is unsure"',
];
export const synonyms = [
  'unconfident',
  'unassertive',
  'insecure',
  'hesitant',
  'diffident',
  'timid',
  'timorous',
  'anxious',
  'apprehensive',
  'fearful',
  'undecided',
  'irresolute',
  'dithering',
  'equivocating',
  'ambivalent',
  'vague',
  'dubious',
  'doubtful',
  'skeptical',
  'distrustful',
  'suspicious',
  'mistrustful',
  'uncertain',
  'unconvinced',
  'not confident',
  'lacking confidence',
  'lacking self-confidence',
  'not self-assured',
  'lacking assurance',
  'in two minds',
  'in a dilemma',
  'in a quandary',
  'confident',
  'assertive',
  'decided',
  'happy',
  'convinced',
  'undecided',
  'indeterminate',
  'uncertain',
  'unknown',
  'not fixed',
  'not settled',
  'fixed',
];