export const definitions = [
    '"any unused equipment will be welcomed back"',
    '"unused to spicy food, she took a long mouthful of water"',
]
export const synonyms = [
    'unutilized',
    'unemployed',
    'unexploited',
    'nonfunctioning',
    'left over',
    'remaining',
    'uneaten',
    'unconsumed',
    'untouched',
    'unneeded',
    'to spare',
    'superfluous',
    'surplus',
    'extra',
    'pristine',
    'immaculate',
    'unspoiled',
    'spotless',
    'flawless',
    'clean',
    'fresh',
    'blank',
    'new',
    'virgin',
    'pure',
    'unopened',
    'unmarked',
    'unblemished',
    'untarnished',
    'unsullied',
    'undefiled',
    'unworn',
    'not made use of',
    'not in service',
    'not required',
    'still available',
    'surplus to requirements',
    'as new',
    'used',
    'in use',
    'unaccustomed',
    'new',
    'fresh',
    'strange',
    'not used',
    'a stranger',
    'unfamiliar with',
    'unconversant with',
    'unacquainted with',
    'unpracticed in',
    'inexperienced in',
    'unversed in',
    'used',
    'accustomed',
]