export const definitions = [
    '"these suggestions are totally untrue"',
    '"a malicious and untrue story"',
    '"a despotic sheik can be untrue to his vast seraglio"',
]
export const synonyms = [
    'false',
    'untruthful',
    'fabricated',
    'made up',
    'invented',
    'concocted',
    'trumped up',
    'erroneous',
    'wrong',
    'incorrect',
    'inaccurate',
    'inexact',
    'flawed',
    'specious',
    'fallacious',
    'unsound',
    'unfounded',
    'misguided',
    'distorted',
    'out',
    'misleading',
    'fictitious',
    'fabulous',
    'mythical',
    'mythological',
    'in error',
    'economical with the truth',
    'true',
    'correct',
    'unfaithful',
    'disloyal',
    'faithless',
    'false',
    'false-hearted',
    'treacherous',
    'traitorous',
    'perfidious',
    'deceitful',
    'deceiving',
    'untrustworthy',
    'duplicitous',
    'double-dealing',
    'two-faced',
    'Janus-faced',
    'insincere',
    'unreliable',
    'undependable',
    'inconstant',
    'adulterous',
    'true',
    'faithful',
]