export const definitions = [
    '"the court upheld his claim for damages"',
    '"many furniture makers uphold the tradition of fine design"',
]
export const synonyms = [
    'confirm',
    'endorse',
    'sustain',
    'validate',
    'ratify',
    'verify',
    'vindicate',
    'justify',
    'approve',
    'support',
    'back',
    'back up',
    'stand by',
    'champion',
    'defend',
    'stick up for',
    'give one\'s support to',
    'be supportive of',
    'give one\'s backing to',
    'come to the defense of',
    'overturn',
    'oppose',
    'maintain',
    'sustain',
    'continue',
    'preserve',
    'protect',
    'keep',
    'hold to',
    'keep going',
    'strengthen',
    'nurture',
    'keep alive',
    'abandon',
]