export const definitions = [
    '"the refreshing smell of essential oils like lavender and peppermint can instantly uplift your mood"',
    '"what better way to uplift the spirits than to plan your next holiday?"',
    '"Mona says the orchestra has uplifted her quality of life"',
    '"audiences will be uplifted by this incredible tale of fighting for your dreams"',
    '"dust is uplifted by wind"',
    '"the mountains were uplifted during the Jurassic period"',
    '"the whole club has seen an uplift in confidence"',
    '"there\'s been an uplift in revenue"',
    '"their love will prove an enormous uplift"',
    '"to get our whole group back together should be a big emotional uplift for the team"',
    '"this uplift happened as recently as 45,000 years ago"',
    '"an uplift bra"',
]
export const synonyms = [
    'boost',
    'raise',
    'elevate',
    'edify',
    'inspire',
    'lift',
    'cheer up',
    'enliven',
    'lighten',
    'gladden',
    'encourage',
    'stimulate',
    'arouse',
    'revive',
    'restore',
    'raised',
    'elevated',
    'hoisted',
    'upraised',
    'upthrust',
    'reared',
    'erect',
    'proud',
    'upheaved',
    'buoy up',
    'give a lift to',
    'perk up',
    'brighten up',
    'ginger up',
    'hitched up',
    'held high',
    'upreared',
    'lowered',
]