export const definitions = [
  '"an uppity sister-in-law"',
];
export const synonyms = [
  'haughty',
  'conceited',
  'hubristic',
  'self-important',
  'opinionated',
  'egotistic',
  'full of oneself',
  'superior',
  'overbearing',
  'pompous',
  'high-handed',
  'swaggering',
  'boastful',
  'bumptious',
  'blustering',
  'patronizing',
  'condescending',
  'disdainful',
  'contemptuous',
  'imperious',
  'proud',
  'vain',
  'immodest',
  'lofty',
  'lordly',
  'snobbish',
  'snobby',
  'overweening',
  'supercilious',
  'smug',
  'pretentious',
  'affected',
  'scornful',
  'mocking',
  'sneering',
  'scoffing',
  'humble',
  'modest',
];