export const definitions = [
  '"the upshot of the meeting was that he was on the next plane to New York"',
];
export const synonyms = [
  'result',
  'consequence',
  'outcome',
  'outturn',
  'sequel',
  'effect',
  'reaction',
  'repercussion',
  'reverberations',
  'ramification',
  'end',
  'end result',
  'conclusion',
  'termination',
  'culmination',
  'denouement',
  'corollary',
  'concomitant',
  'aftermath',
  'fruit(s)',
  'product',
  'produce',
  'byproduct',
  'sequelae',
  'issue',
  'success',
  'cause',
  'origin',
];