export const definitions = [
    '"he was surrounded by a dozen street urchins in rags"',
]
export const synonyms = [
    'imp',
    'monkey',
    'Puck',
    'rascal',
    'rogue',
    'minx',
    'mischief-maker',
    'prankster',
    'ragamuffin',
    'guttersnipe',
    'waif',
    'stray',
    'tearaway',
    'jackanapes',
    'rip',
    'gamin',
    'gamine',
    'mudlark',
    'scapegrace',
    'street Arab',
    'wastrel',
    'mischievous child',
    'tatterdemalion',
]