export const definitions = [
    '"the president resigned and the post was left vacant"',
    '"a vacant stare"',
]
export const synonyms = [
    'empty',
    'unoccupied',
    'unfilled',
    'free',
    'available',
    'unused',
    'unengaged',
    'uninhabited',
    'untenanted',
    'tenantless',
    'to let',
    'for sale',
    'on the market',
    'abandoned',
    'deserted',
    'not in use',
    'full',
    'occupied',
    'open',
    'blank',
    'expressionless',
    'deadpan',
    'inscrutable',
    'inexpressive',
    'poker-faced',
    'emotionless',
    'impassive',
    'absent',
    'absentminded',
    'uninterested',
    'vacuous',
    'empty',
    'glassy',
    'stony',
    'wooden',
    'motionless',
    'lifeless',
    'inanimate',
    'empty-headed',
    'unintelligent',
    'brainless',
    'dense',
    'dull-witted',
    'thick',
    'inane',
    'stupid',
    'without thought',
    'expressive',
    'meaningful',
    'thinking',
    'intelligent',
]