export const definitions = [
  '"the political vacuum left by the death of the Emperor"',
  '"the room needs to be vacuumed"',
];
export const synonyms = [
  'emptiness',
  'void',
  'nothingness',
  'vacuity',
  'vacancy',
  'voidness',
  'nihility',
  'empty space',
  'gap',
  'space',
  'absence',
  'lack',
  'deficiency',
  'blank',
  'lacuna',
  'continuity',
  'vacuum cleaner',
  'Hoover',
  'vacuum-clean',
  'hoover',
];