export const definitions = [
  '"I verily believed myself to be a free woman"',
];
export const synonyms = [
  'definitely',
  'certainly',
  'unquestionably',
  'undoubtedly',
  'positively',
  'beyond doubt',
  'unmistakably',
  'indubitably',
  'undeniably',
  'surely',
  'assuredly',
  'in truth',
  'truly',
  'really',
  'in reality',
  'actually',
  'in fact',
  'forsooth',
  'in sooth',
  'without (a) doubt',
  'beyond any doubt',
  'beyond question',
  'beyond the shadow of a doubt',
  'possibly',
];