export const definitions = [
    '"the proposed investment was economically viable"',
    '"most clones can produce thousands of viable seeds"',
    '"the largest and most viable population of this endangered vetch"',
    '"little of the frozen semen has been viable when thawed"',
    '"what if the fetus were viable?"',
]
export const synonyms = [
    'workable',
    'feasible',
    'practicable',
    'practical',
    'applicable',
    'usable',
    'manageable',
    'operable',
    'operational',
    'possible',
    'within reach',
    'likely',
    'achievable',
    'attainable',
    'realizable',
    'reasonable',
    'sensible',
    'realistic',
    'logical',
    'useful',
    'serviceable',
    'suitable',
    'expedient',
    'effective',
    'valid',
    'tenable',
    'sound',
    'well advised',
    'well thought out',
    'well grounded',
    'judicious',
    'levelheaded',
    'wise',
    'within the bounds/realms of possibility',
    'within reason',
    'accomplishable',
    'of use',
    'impracticable',
]