export const definitions = [
    '"he was a powerful, virile man"',
    '"a strong, virile performance of the Mass"',
]
export const synonyms = [
    'manly',
    'masculine',
    'male',
    'gallant',
    'chivalrous',
    'swashbuckling',
    'valiant',
    'valorous',
    'courageous',
    'brave',
    'intrepid',
    'fearless',
    'stouthearted',
    'lionhearted',
    'bold',
    'heroic',
    'daring',
    'strong',
    'tough',
    'vigorous',
    'robust',
    'well made',
    'well built',
    'muscular',
    'muscly',
    'brawny',
    'rugged',
    'strapping',
    'sturdy',
    'hefty',
    'husky',
    'burly',
    'solid',
    'substantial',
    'red-blooded',
    'fertile',
    'fecund',
    'all-male',
    'powerfully built',
    'sexually potent',
    'unmanly',
    'effeminate',
    'weak',
]