export const definitions = [
    '"paragons of virtue"',
    '"patience is a virtue"',
    '"Mike was extolling the virtues of the car"',
    '"there\'s no virtue in suffering in silence"',
]
export const synonyms = [
    'goodness',
    'virtuousness',
    'righteousness',
    'morality',
    'uprightness',
    'integrity',
    'dignity',
    'rectitude',
    'honesty',
    'honorableness',
    'honor',
    'incorruptibility',
    'probity',
    'propriety',
    'decency',
    'respectability',
    'nobility',
    'nobleness',
    'worthiness',
    'worth',
    'good',
    'trustworthiness',
    'meritoriousness',
    'irreproachableness',
    'blamelessness',
    'purity',
    'pureness',
    'merit',
    'principles',
    'ethics',
    'ethicalness',
    'upstandingness',
    'honorability',
    'nobility of soul/spirit',
    'lack of corruption',
    'high principles',
    'vice',
    'iniquity',
    'good quality',
    'strong point',
    'strong suit',
    'long suit',
    'asset',
    'forte',
    'attribute',
    'advantage',
    'benefit',
    'strength',
    'talent',
    'good point',
    'failing',
    'merit',
    'advantage',
    'benefit',
    'usefulness',
    'efficacy',
    'efficaciousness',
    'power',
    'potency',
    'force',
    'strength',
    'disadvantage',
    'virginity',
    'honor',
    'maidenhood',
    'maidenhead',
    'chastity',
    'chasteness',
    'purity',
    'pureness',
    'sinlessness',
    'spotlessness',
    'wholesomeness',
    'innocence',
    'decency',
    'virtuousness',
    'respectability',
    'dignity',
    'modesty',
    'celibacy',
    'abstinence',
    'self-restraint',
    'self-denial',
    'immaculateness',
    'continence',
    'lack of sin',
    'promiscuity',
]