export const definitions = [
    '"larks were warbling in the trees"',
    '"he warbled in an implausible soprano"',
    '"through the wall came a faint warble"',
    '"the warble of the phone"',
]
export const synonyms = [
    'trill',
    'sing',
    'chirp',
    'chirrup',
    'chirr',
    'cheep',
    'twitter',
    'tweet',
    'whistle',
    'chatter',
    'squeak',
    'pipe',
    'peep',
    'trill',
    'sing',
    'chirp',
    'chirrup',
    'chirr',
    'cheep',
    'twitter',
    'tweet',
    'whistle',
    'chatter',
    'squeak',
    'pipe',
    'peep',
    'trill',
    'trilling',
    'song',
    'birdsong',
    'cry',
    'warbling',
    'chirp',
    'chirping',
    'chirrup',
    'chirruping',
    'chirr',
    'chirring',
    'cheep',
    'cheeping',
    'twitter',
    'twittering',
    'tweet',
    'tweeting',
    'whistle',
    'whistling',
    'chatter',
    'chattering',
    'squeak',
    'squeaking',
    'pipe',
    'piping',
    'peep',
    'peeping',
    'call',
    'calling',
]