export const definitions = [
    '"wasted fuel"',
    '"a wasted opportunity"',
    '"I\'m sorry you\'ve had a wasted journey"',
    '"her wasted arm"',
    '"he looked kind of wasted"',
    '"we can\'t afford to waste electricity"',
    '"I don\'t use the car, so why should I waste precious money on it ? "',
    '"her small talk was wasted on this guest"',
    '"we\'re wasted in this job"',
    '"she was visibly wasting away"',
    '"these symptoms wasted the patients very much"',
    '"he seized their cattle and wasted their country"',
    '"I saw them waste the guy I worked for"',
    '"the years were wasting"',
]
export const synonyms = [
    'squandered',
    'misspent',
    'misdirected',
    'misused',
    'dissipated',
    'pointless',
    'useless',
    'unnecessary',
    'needless',
    'missed',
    'lost',
    'past',
    'forfeited',
    'neglected',
    'bungled',
    'gone',
    'frittered away',
    'not needed',
    'gone by the board',
    'futile',
    'vain',
    'in vain',
    'idle',
    'pointless',
    'useless',
    'worthless',
    'needless',
    'hollow',
    'ineffectual',
    'ineffective',
    'inefficacious',
    'unproductive',
    'unrewarding',
    'profitless',
    'unsuccessful',
    'unavailing',
    'barren',
    'abortive',
    'bootless',
    'to no avail',
    'to no effect',
    'for naught',
    'fruitful',
    'productive',
    'emaciated',
    'atrophied',
    'withered',
    'shriveled',
    'weak',
    'weakened',
    'frail',
    'shrunken',
    'skeletal',
    'rickety',
    'scrawny',
    'cadaverous',
    'wilted',
    'faded',
    'flagging',
    'deteriorating',
    'degenerative',
    'gaunt',
    'haggard',
    'wizened',
    'undernourished',
    'starved',
    'half-starved',
    'drunk',
    'drunken',
    'inebriated',
    'intoxicated',
    'befuddled',
    'incapable',
    'tipsy',
    'under the influence',
    'maudlin',
    'blind drunk',
    '(as) drunk as a skunk',
    'sottish',
    'tippling',
    'toping',
    'sotted',
    'besotted',
    'foxed',
    'screwed',
    'crapulent',
    'crapulous',
    'inebriate',
    'bibulous',
    'the worse for drink',
    'dead drunk',
    'rolling drunk',
    'roaring drunk',
    '(as) drunk as a lord',
    'gin-soaked',
    'ebrious',
    'ebriose',
    'ebriate',
    'sober',
    'squander',
    'misspend',
    'misuse',
    'throw away',
    'lavish',
    'dissipate',
    'go through',
    'run through',
    'exhaust',
    'drain',
    'deplete',
    'burn up',
    'use up',
    'consume',
    'fritter away',
    'spend recklessly',
    'be wasteful with',
    'spend like water',
    'throw around like confetti',
    'conserve',
    'wither',
    'atrophy',
    'shrink',
    'decay',
    'decline',
    'wilt',
    'fade',
    'flag',
    'deteriorate',
    'degenerate',
    'rot',
    'molder',
    'languish',
    'grow weak',
    'become emaciated',
    'shrivel up',
    'be abandoned',
    'be neglected',
    'be forgotten',
    'be disregarded',
    'flourish',
    'thrive',
    'destroy',
    'devastate',
    'ravage',
    'raze',
    'demolish',
    'blast',
    'wreck',
    'wipe out',
    'flatten',
    'level',
    'crush',
    'lay waste',
    'leave in ruins',
    'wreak havoc on',
    'leave desolate',
    'rebuild',
    'repair',
    'murder',
    'kill',
    'do away with',
    'assassinate',
    'liquidate',
    'eliminate',
    'terminate',
    'dispatch',
    'finish off',
    'execute',
    'slaughter',
    'butcher',
    'massacre',
    'wipe out',
    'destroy',
    'annihilate',
    'eradicate',
    'exterminate',
    'extirpate',
    'decimate',
    'mow down',
    'shoot down',
    'cut down',
    'slay',
    'do to death',
    'put to death',
    'cut to pieces',
]