export const definitions = [
    '"a reddish afterburn from waxing"',
    '"a sale on pedicures and eyebrow waxings"',
    '"painful waxing procedures"',
    '"the latest waxing by the band"',
    '"I washed and waxed the floor"',
    '"she waxed her legs when necessary"',
    '"he waxed a series of tracks that emphasized his lead guitar work"',
    '"his anger waxed"',
    '"they waxed lyrical about the old days"',
]
export const synonyms = [
    'enlarge',
    'approach full moon',
    'get bigger',
    'increase in size',
    'wane',
    'increase',
    'grow',
    'develop',
    'rise',
    'expand',
    'swell',
    'enlarge',
    'magnify',
    'extend',
    'escalate',
    'deepen',
    'intensify',
    'widen',
    'broaden',
    'spread',
    'mushroom',
    'snowball',
    'decrease',
    'wane',
    'become',
    'grow',
    'get',
    'turn',
    'enthuse',
    'rave',
    'gush',
    'come to be',
    'become enthusiastic',
    'get carried away',
]