export const definitions = [
    '"they\'re celebrating 25 years of wedded bliss"',
    '"it was the perfect start to their wedded life"',
    '"he was to wed the king\'s daughter"',
    '"they wed a week after meeting"',
    '"they were wed in London"',
    '"will you wed your daughter to him?"',
    '"in this album he weds an excellent programme with a distinctive vocal style"',
    '"the government was wedded to budgetary orthodoxy"',
    '"foreign policy has remained wedded to outdated assumptions"',
]
export const synonyms = [
    'married',
    'matrimonial',
    'marital',
    'conjugal',
    'connubial',
    'nuptial',
    'marriage',
    'wedding',
    'spousal',
    'hymeneal',
    'epithalamic',
    'marry',
    'espouse',
    'get/be married',
    'be wed',
    'become husband and wife',
    'become man and wife',
    'plight/pledge one\'s troth',
    'become espoused',
    'get/be married to',
    'be wed to',
    'take as one\'s wife / husband',
    'lead to the altar',
    'wive',
    'divorce',
    'separate',
    'jilt',
    'married',
    'wedded',
    'engaged',
    'affianced',
    'pledged',
    'promised',
    'involved',
    'united',
    'bound',
    'contracted',
    'betrothed',
    'espoused',
    'plighted',
    'joined in marriage',
    'joined in matrimony',
    'united in wedlock',
    'promised in marriage',
    'going out',
    'spoken for',
    'unattached',
    'single',
    'unite',
    'unify',
    'join',
    'link',
    'connect',
    'combine',
    'amalgamate',
    'fuse',
    'integrate',
    'weld',
    'bond',
    'stick together',
    'glue',
    'cement',
    'coalesce',
    'merge',
    'bring together',
    'knit together',
    'stick to',
    'dedicated to',
    'devoted to',
    'attached to',
    'fixated on',
    'obsessive about',
    'fanatical about',
    'single-minded about',
    'addicted to',
    'hell-bent on',
    'refuse to give up',
]