export const definitions = [
    '"a wedge of cheese"',
    '"the door was wedged open"',
    '"I wedged the bags into the back seat"',
]
export const synonyms = [
    'chock',
    'door stop',
    'tapered block',
    'triangle',
    'segment',
    'slice',
    'section',
    'chunk',
    'lump',
    'slab',
    'hunk',
    'block',
    'tapered piece',
    'squeeze',
    'cram',
    'jam',
    'crush',
    'pack',
    'thrust',
    'ram',
    'force',
    'push',
    'stow',
]