export const definitions = [
  '"he was at least 175 pounds in weight"',
  '"as he came upstairs the boards creaked under his weight"',
  '"weights and measures"',
  '"be careful when lifting a heavy weight"',
  '"a recommendation by the committee will carry great weight"',
  '"individuals differ in the weight they attach to various aspects of a job"',
  '"a mug half filled with coffee weighted down a stack of papers"',
  '"the jugs were covered with muslin veils weighted with colored beads"',
  '"speaking, reading, and writing should be weighted equally in the assessment"',
  '"the balance of power is weighted in favor of the government"',
];
export const synonyms = [
  'heaviness',
  'mass',
  'load',
  'burden',
  'pressure',
  'force',
  'poundage',
  'tonnage',
  'influence',
  'force',
  'leverage',
  'sway',
  'muscle',
  'teeth',
  'importance',
  'significance',
  'consequence',
  'value',
  'substance',
  'power',
  'authority',
  'prestige',
  'highlight',
  'point up',
  'spotlight',
  'foreground',
  'play up',
  'make a point of',
  'stress',
  'dwell on',
  'belabor',
  'accent',
  'accentuate',
  'underline',
  'intensify',
  'strengthen',
  'heighten',
  'deepen',
  'italicize',
  'underscore',
  'prioritize',
  'bring/call/draw attention to',
  'focus attention on',
  'put/lay stress on',
  'give an emphasis to',
  'give prominence to',
  'bring to the fore',
  'harp on',
  'insist on',
  'understate',
  'play down',
];