export const definitions = [
    '"the illness often leaves her wheezing"',
    '"he could barely wheeze out his pleas for a handout"',
    '"\"Don\'t worry son,\" he wheezed"',
    '"she wheezed up the hill toward them"',
    '"the engine coughed, wheezed, and shrieked into life"',
    '"I talk with a wheeze"',
    '"the old wheeze about the diner complaining about the fly in his soup"',
    '"a new wheeze to help farmers"',
]
export const synonyms = [
    'gasp',
    'whistle',
    'hiss',
    'rasp',
    'croak',
    'pant',
    'cough',
    'breathe audibly/noisily',
    'gasp',
    'whistle',
    'hiss',
    'rasp',
    'croak',
    'pant',
    'cough',
    'constricted breathing',
    'scheme',
    'plan',
    'idea',
    'tactic',
    'move',
    'stratagem',
    'ploy',
    'gambit',
    'device',
    'maneuver',
    'contrivance',
    'expedient',
    'trick',
    'dodge',
    'subterfuge',
    'game',
    'wile',
    'ruse',
    'joke',
    'prank',
    'stunt',
    'shift',
]