export const definitions = [
  '"we chatted for a while"',
  '"she retired a little while ago"',
  '"can I keep it a while?"',
  '"he starts to draw, talking the while"',
  '"beseeching him, the while his hand she wrung"',
  '"a diversion to while away the long afternoons"',
];
export const synonyms = [
  'time',
  'spell',
  'stretch',
  'stint',
  'span',
  'season',
  'interval',
  'period',
  'duration',
  'run',
  'phase',
  'stage',
  'term',
  'period of time',
  'length of time',
  'pass',
  'spend',
  'occupy',
  'use up',
  'kill',
  'beguile',
];