export const definitions = [
    '"a train whooshed by"',
    '"there was a loud whooshing noise"',
    '"there was a big whoosh of air"',
    '"the starlings gather, then suddenly—whoosh!—flocks rise and swirl"',
]
export const synonyms = [
    'hurry up',
    'hasten',
    'make haste',
    'speed',
    'speed up',
    'lose no time',
    'push on',
    'run',
    'dash',
    'rush',
    'hurtle',
    'dart',
    'race',
    'fly',
    'flash',
    'shoot',
    'streak',
    'bolt',
    'bound',
    'blast',
    'charge',
    'chase',
    'career',
    'scurry',
    'scramble',
    'scamper',
    'scuttle',
    'sprint',
    'gallop',
    'scutter',
    'post',
    'hie',
    'fleet',
    'be quick',
    'move quickly',
    'go fast',
    'press on',
    'go hell for leather',
    'go like lightning',
    'dawdle',
    'move slowly',
    'rustle',
    'murmur',
    'sigh',
    'moan',
    'sough',
    'whir',
    'swish',
    'susurration',
    'howl',
    'roar',
]