export const definitions = [
    '"Whoops! I nearly dropped it"',
    '"all at once they were whooping with laughter"',
    '"I\'m still looking forward to whooping your ass, buddy"',
    '"I should listen to him because he whooped my butt"',
    '"everyone\'s mother was allowed to whoop you if you got into trouble"',
    '"we just got whooped by the Jaguars"',
    '"she whooped him in the election"',
]
export const synonyms = [
    'shout',
    'cry',
    'call',
    'yell',
    'roar',
    'scream',
    'shriek',
    'screech',
    'hoot',
    'hoop',
    'cheer',
    'hurrah',
    'huzzah',
    'shout',
    'cry',
    'call',
    'yell',
    'roar',
    'scream',
    'shriek',
    'screech',
    'hoot',
    'hoop',
    'cheer',
    'hurrah',
    'huzzah',
]