export const definitions = [
  '"a wide road"',
  '"it measures 15 cm long by 12 cm wide"',
  '"how wide do you think this house is?"',
  '"wide eyes"',
  '"tax revenues have undershot Treasury projections by a wide margin"',
  '"a wide range of opinion"',
  '"the business is slowly gaining wider acceptance"',
  '"an industry-wide trend"',
  '"Bodie\'s shot was inches wide"',
  '"the ball was wide of the plate"',
  '"forced a wide throw to first"',
  '"he played in a wide left position"',
];
export const synonyms = [
  'broad',
  'extensive',
  'spacious',
  'open',
  'vast',
  'outspread',
  'baggy',
  'loose',
  'capacious',
  'roomy',
  'ample',
  'full',
  'generous',
  'commodious',
  'voluminous',
  'slack',
  'sloppy',
  'shapeless',
  'sacklike',
  'ill-fitting',
  'ballooning',
  'billowing',
  'floppy',
  'spread out',
  'generously cut',
  'oversize',
  'narrow',
  'tight',
  'gaping',
  'agape',
  'wide open',
  'yawning',
  'fully open',
  'closed',
  'comprehensive',
  'ample',
  'broad',
  'extensive',
  'large',
  'large-scale',
  'vast',
  'immense',
  'wide-ranging',
  'expansive',
  'sweeping',
  'encyclopedic',
  'exhaustive',
  'general',
  'all-inclusive',
  'all-embracing',
  'universal',
  'catholic',
  'compendious',
  'cross-disciplinary',
  'interdisciplinary',
  'multidisciplinary',
  'far-ranging',
  'restricted',
  'limited',
  'off target',
  'off the mark',
  'inaccurate',
  'off course',
  'astray',
  'nowhere near',
  'out',
  'wide of the mark/target',
  'on target',
  'accurate',
];