export const definitions = [
    '"his wily opponents"',
]
export const synonyms = [
    'shrewd',
    'clever',
    'sharp',
    'sharp-witted',
    'astute',
    'canny',
    'smart',
    'crafty',
    'cunning',
    'artful',
    'sly',
    'scheming',
    'calculating',
    'guileful',
    'disingenuous',
    'devious',
    'Machiavellian',
    'deceitful',
    'deceptive',
    'Janus-faced',
    'dishonest',
    'cheating',
    'double-dealing',
    'subtle',
    'vulpine',
    'carny',
    'naive',
    'guileless',
]