export const definitions = [
  '"a Nobel Prize winner"',
  '"he equalized and hit a last-minute winner"',
  '"dummy has the spade ace and two diamond winners at the finish"',
  '"the changes failed to make the soap opera a winner"',
];
export const synonyms = [
  'victor',
  'champion',
  'conqueror',
  'vanquisher',
  'hero',
  'medalist',
  'gold medalist',
  'prizewinner',
  'conquistador',
  'defeater',
  'conquering hero',
  'cup winner',
  'prizeman',
  'victor ludorum',
  'loser',
  'success',
  'sellout',
  'triumph',
  'sensation',
  'bestseller',
  'tour de force',
  'box-office success',
  'failure',
  'flop',
];