export const definitions = [
    '"listen to his words of wisdom"',
    '"some questioned the wisdom of building the dam so close to an active volcano"',
    '"the traditional farming wisdom of India"',
]
export const synonyms = [
    'sagacity',
    'sageness',
    'intelligence',
    'understanding',
    'insight',
    'perception',
    'perceptiveness',
    'percipience',
    'penetration',
    'perspicuity',
    'acuity',
    'discernment',
    'sense',
    'common sense',
    'shrewdness',
    'astuteness',
    'acumen',
    'smartness',
    'judiciousness',
    'judgment',
    'foresight',
    'clear-sightedness',
    'prudence',
    'circumspection',
    'logic',
    'rationale',
    'rationality',
    'soundness',
    'saneness',
    'advisability',
    'sapience',
    'good sense',
    'arguteness',
    'stupidity',
    'folly',
    'sagacity',
    'sageness',
    'intelligence',
    'understanding',
    'insight',
    'perception',
    'perceptiveness',
    'percipience',
    'penetration',
    'perspicuity',
    'acuity',
    'discernment',
    'sense',
    'common sense',
    'shrewdness',
    'astuteness',
    'acumen',
    'smartness',
    'judiciousness',
    'judgment',
    'foresight',
    'clear-sightedness',
    'prudence',
    'circumspection',
    'logic',
    'rationale',
    'rationality',
    'soundness',
    'saneness',
    'advisability',
    'sapience',
    'good sense',
    'arguteness',
    'stupidity',
    'folly',
    'knowledge',
    'learning',
    'erudition',
    'scholarship',
    'philosophy',
    'lore',
]