export const definitions = [
    '"the grass had withered to an unappealing brown"',
    '"the flesh had withered away"',
    '"programs would wither away if they did not command local support"',
    '"a business that can wither the hardiest ego"',
    '"she withered me with a look"',
]
export const synonyms = [
    'wilt',
    'droop',
    'fade',
    'dry up',
    'die',
    'perish',
    'become limp',
    'shrivel (up)',
    'become marcescent',
    'thrive',
    'flourish',
    'atrophy',
    'decay',
    'waste (away)',
    'become shrunken',
    'shrivel (up)',
    'strengthen',
    'diminish',
    'dwindle',
    'shrink',
    'lessen',
    'fade',
    'wane',
    'weaken',
    'languish',
    'evaporate',
    'disappear',
    'ebb (away)',
    'melt away',
    'grow',
]