export const definitions = [
  '"a financial wizard"',
  '"how absolutely wizard!"',
  '"I\'ve just had a wizard idea"',
];
export const synonyms = [
  'sorcerer',
  'warlock',
  'magus',
  'necromancer',
  'occultist',
  'enchanter',
  'mage',
  'thaumaturge',
  'thaumaturgist',
  'male witch',
  '(black) magician',
  'pishogue',
  'genius',
  'expert',
  'master',
  'adept',
  'virtuoso',
  'maestro',
  'past master',
  'marvel',
  'prodigy',
  'star',
  'wunderkind',
  'proficient',
  'beginner',
  'amateur',
  'duffer',
  'excellent',
  'wonderful',
  'marvelous',
  'magnificent',
  'superb',
  'splendid',
  'glorious',
  'sublime',
  'lovely',
  'delightful',
  'first-class',
  'first-rate',
  'outstanding',
  'consummate',
  'perfect',
  'goodly',
  'dreadful',
  'awful',
  'horrible',
];