export const definitions = [
    '"a red woolly hat"',
    '"woolly gray-green foliage"',
    '"the woolly aphid"',
    '"woolly wisps of cloud"',
    '"woolly thinking"',
    '"an opaque and woolly recording"',
]
export const synonyms = [
    'woolen',
    'wool',
    'fleecy',
    'made of wool',
    'fleecy',
    'shaggy',
    'hairy',
    'fluffy',
    'flocculent',
    'wool-bearing',
    'laniferous',
    'lanigerous',
    'downy',
    'floccose',
    'lanate',
    'vague',
    'ill-defined',
    'hazy',
    'unclear',
    'unfocused',
    'fuzzy',
    'blurry',
    'foggy',
    'nebulous',
    'imprecise',
    'inexact',
    'indefinite',
    'confused',
    'muddled',
    'muddle-headed',
    'disorganized',
    'clear',
    'woolen',
    'knitted garment',
]