// cached
definitions: [
    '"he decided that they must cache their weapons"',
    '"the operating system tries to cache every disk operation"',
    '"the device comes complete with 4MB of RAM to cache the hard drive"',
    '"a cached host adapter"',
]
synonyms: [
    'store',
    'stow',
    'pack',
    'load',
    'garner',
    'hide',
    'conceal',
    'secrete',
    'hoard',
    'put aside',
    'set aside',
    'put by',
    'lay by',
    'lay aside',
    'save',
    'stockpile',
    'reserve',
    'deposit',
    'keep',
    'keep in reserve',
    'put by for a rainy day',
]

// caches
definitions: [
    '"an arms cache"',
    '"a cache of gold coins"',
    '"there was a good supply of meat in the caches"',
    '"typical cache sizes range from 64K to 256K"',
    '"he decided that they must cache their weapons"',
    '"the operating system tries to cache every disk operation"',
    '"the device comes complete with 4MB of RAM to cache the hard drive"',
    '"a cached host adapter"',
]
synonyms: [
    'hoard',
    'store',
    'stockpile',
    'stock',
    'supply',
    'collection',
    'accumulation',
    'reserve',
    'fund',
    'arsenal',
    'treasure',
    'nest egg',
    'hidden treasure',
    'amassment',
    'hiding place',
    'hole',
    'hideout',
    'storage place',
    'secret place',
    'memory bank',
    'store',
    'disk',
    'RAM',
    'ROM',
    'store',
    'stow',
    'pack',
    'load',
    'garner',
    'hide',
    'conceal',
    'secrete',
    'hoard',
    'put aside',
    'set aside',
    'put by',
    'lay by',
    'lay aside',
    'save',
    'stockpile',
    'reserve',
    'deposit',
    'keep',
    'keep in reserve',
    'put by for a rainy day',
]

// caking
definitions: [
    '"a pair of boots caked with mud"',
    '"the blood under his nose was beginning to cake"',
]
synonyms: [
    'cover',
    'coat',
    'encrust',
    'plaster',
    'smother',
    'spread thickly',
    'clot',
    'congeal',
    'coagulate',
    'thicken',
    'solidify',
    'harden',
    'set',
    'dry',
    'inspissate',
    'liquefy',
]

// camera
definitions: [
    '"she faced the cameras"',
    '"a photographer\'s camera flashed"',
    '"a video camera"',
    '"the Radcliffe Camera"',
]
synonyms: [
    'recorder',
    'records a thousand words'
]

// camped
definitions: [
    '"parks in which you can camp or stay in a chalet"',
    '"we camped out for the night in a mission schoolroom"',
    '"the press will be camping on your doorstep once they get onto this story"',
    '"he camped it up a bit for the cameras"',
    '"they wore funny masks and camped around a lot and acted silly"',
    '"it\'s precisely the kind of role that a lesser actor would have camped up and exaggerated"',
]
synonyms: [
    'encamp',
    'bivouac',
    'pitch tents',
    'set up camp',
    'pitch camp',
    'outspan',
    'posture',
    'overact',
    'go overboard',
    'show off',
    'behave theatrically',
    'behave affectedly',
    'overdo it',
    'ham it up',
]

// campus
definitions: [
    '"for the first year I had a room on campus"',
]
synonyms: [

]

// canals
definitions: [
    '"the ear canal"',
]
synonyms: [
    'channel',
    'watercourse',
    'waterway',
    'ship canal',
    'inland waterway',
    'duct',
    'tube',
    'passage',
    'vessel',
]

// cancel
definitions: [
    '"he was forced to cancel his visit"',
    '"his visa had been canceled"',
    '"I intend to cancel your debt to me"',
    '"the shipping costs canceled out any savings"',
    '"the electric fields may cancel each other out"',
    '"“‘Divide by 9” cancels out “multiply by 9”"',
    '"fans on social media are torn over whether to support or cancel him"',
    '"a stamp franked and with an adhesive cancel"',
    '"a cancel title page"',
]
synonyms: [
    'call off',
    'abandon',
    'scrap',
    'drop',
    'postpone',
    'mothball',
    'annul',
    'invalidate',
    'nullify',
    'void',
    'revoke',
    'rescind',
    'retract',
    'countermand',
    'set aside',
    'take back',
    'withdraw',
    'recall',
    'repeal',
    'overrule',
    'override',
    'abrogate',
    'quash',
    'extinguish',
    'remit',
    'retire',
    'vacate',
    'discharge',
    'negate',
    'declare null and void',
    'render null and void',
    'disannul',
    'neutralize',
    'counterbalance',
    'counteract',
    'countervail',
    'negate',
    'nullify',
    'wipe out',
    'offset',
    'make up for',
    'negative',
    'balance (out)',
    'compensate for',
    'counterweigh',
]

// cancer
definitions: [
    '"race to cure ______"',
    '"addition by substraction, if can trade the ______ of the team'
]
synonyms: [
    'terminal',
    'capricorn',
    'killer',
]

// candle
definitions: [
    '"the egg was candled—it was fertile"',
]
synonyms: [
    'taper',
    'sconce',
    'paschal candle',
    'wax light',
    'glim',
    'rushlight',
    'bougie',
    'tallow candle',
    'wax candle',
    'Christmas candle',
    'votary candle',
    'rush candle',
    'cierge',
]

// cannot
definitions: [
    '"we just cannot afford it"',
    '"the possibility cannot be excluded"',
    '"she cannot walk unaided"',
]
synonyms: [
    'impeded',
    'undoable'
]

// career
definitions: [
    '"he seemed destined for a career as an engineer like his father"',
    '"the end of a distinguished career in the navy"',
    '"the court has had a checkered career"',
    '"a career diplomat"',
    '"the car careered across the road and went through a hedge"',
]
synonyms: [
    'profession',
    'occupation',
    'vocation',
    'calling',
    'employment',
    'job',
    'day job',
    'line',
    'walk of life',
    'position',
    'post',
    'sphere',
    'métier',
    'line of work',
    'existence',
    'life',
    'progress',
    'course',
    'progression',
    'passage',
    'path',
    'professional',
    'permanent',
    'full-time',
    'committed',
    'rush',
    'hurtle',
    'streak',
    'shoot',
    'race',
    'bolt',
    'dash',
    'speed',
    'run',
    'gallop',
    'stampede',
    'cannon',
    'careen',
    'whiz',
    'buzz',
    'zoom',
    'flash',
    'blast',
    'charge',
    'hare',
    'fly',
    'wing',
    'pelt',
    'scurry',
    'scud',
    'go like the wind',
]

// carers
definitions: [
    '"elderly people and their carers need long-term support"',
]
synonyms: [
    'attendant',
    'aide',
    'helper',
    'assistant',
    'personal assistant',
    'valet',
    'equerry',
    'squire',
    'lady in waiting',
    'chaperone',
    'duenna',
    'protector',
    'protectress',
    'minder',
]

// castle
definitions: [
    '"storm the castle gates"',
    '"the crumbling stonework of a ruined castle"',
    '"preference is to castle on the queenside"',
]
synonyms: [
    'fortress',
    'fort',
    'stronghold',
    'fortification',
    'keep',
    'citadel',
    'fastness',
    'tower',
    'peel',
    'palace',
    'chateau',
    'donjon',
    'alcazar',
    'mansion',
    'stately home',
    'hall',
    'manor',
    'big house',
    'country house',
    'palace',
    'edifice',
    'residence',
    'abode',
    'seat',
    'château',
    'palazzo',
    'manor house',
    'impressive building/structure',
    'manoir',
]

// catted
definitions: [
    '"I kept her off the wind and sailing free until I had the anchor catted"',
]
synonyms: [
]

// cattle
definitions: [
]
synonyms: [
    'cows',
    'bovines',
    'oxen',
    'bulls',
    'stock',
    'livestock',
    'neat',
    'kine',
]

// cloned
definitions: [
    '"of the hundreds of new plants cloned the best ones are selected"',
    '"we have cloned DNA sequences added to the ends of the linear plasmid"',
]
synonyms: [
    'copy',
    'reproduce',
    'duplicate',
    'recreate',
    'repeat',
    'make a copy of',
    'make a replica of',
    'perform again',
    'copy',
    'duplicate',
    'replicate',
    'photocopy',
    'xerox',
    'photostat',
    'mimeograph',
    'mimeo',
    'print',
    'transcribe',
    'forge',
    'counterfeit',
    'produce a copy of',
    'make a facsimile of',
    'make a Xerox of',
]

// clones
definitions: [
    '"successful women don\'t want to be male clones"',
    '"an IBM PC clone"',
    '"of the hundreds of new plants cloned the best ones are selected"',
    '"we have cloned DNA sequences added to the ends of the linear plasmid"',
]
synonyms: [
    'double',
    'replica',
    'lookalike',
    'copy',
    'reproduction',
    'twin',
    'duplicate',
    'facsimile',
    'counterpart',
    'mirror image',
    'similitude',
    'living image',
    'exact likeness',
    'Doppelgänger',
    'copy',
    'reproduce',
    'duplicate',
    'recreate',
    'repeat',
    'make a copy of',
    'make a replica of',
    'perform again',
    'copy',
    'duplicate',
    'replicate',
    'photocopy',
    'xerox',
    'photostat',
    'mimeograph',
    'mimeo',
    'print',
    'transcribe',
    'forge',
    'counterfeit',
    'produce a copy of',
    'make a facsimile of',
    'make a Xerox of',
]

// closed
definitions: [
    '"rooms with closed doors lined the hallway"',
    '"he sat with his eyes closed"',
    '"the perception of the Soviet Union as a closed society had changed"',
    '"a closed squash tournament"',
    '"the UN Security Council met in closed session"',
    '"you\'re facing the situation with a closed mind"',
    '"he put the “Closed” sign up on the door"',
    '"a closed factory"',
    '"she jumped into the train just as the doors were closing"',
    '"they had to close the window because of the insects"',
    '"Stephen closed his ears to the sound"',
    '"glass doors close off the living room from the hall"',
    '"Loretta closed her mouth"',
    '"Ron closed the book"',
    '"my fist closed around the weapon"',
    '"this will cause a relay to operate and close the circuit"',
    '"the members were thanked for attending and the meeting was closed"',
    '"the concert closed with “Silent Night”"',
    '"we close with a point about truth"',
    '"he closed a deal with a metal dealer"',
    '"the factory is to close with the loss of 150 jobs"',
    '"the country has been closed to outsiders for almost 50 years"',
    '"I went to the bank to close an account held by my daughter"',
    '"a statement is used to close a data file"',
    '"they plotted a large group of aircraft about 130 miles away and closing fast"',
]
synonyms: [
    'watertight',
    'waterproof',
    'water-resistant',
    'water-repellent',
    'airtight',
    'tight',
    'sealed',
    'impenetrable',
    'impregnable',
    'inviolable',
    'resistant',
    'damp-proof',
    'hermetically sealed',
    'imperviable',
    'permeable',
    'select',
    'chic',
    'high-class',
    'elite',
    'fashionable',
    'stylish',
    'elegant',
    'choice',
    'special',
    'premier',
    'expensive',
    'restrictive',
    'restricted',
    'limited',
    'private',
    'cliquish',
    'cliquey',
    'clannish',
    'snobbish',
    'upmarket',
    'high-toned',
    'upscale',
    'discriminative',
    'grade A',
    'open',
    'unaffected by',
    'untouched by',
    'immune to',
    'invulnerable to',
    'insusceptible to',
    'not susceptible to',
    'proof against',
    'unreceptive to',
    'closed to',
    'resistant to',
    'indifferent to',
    'heedless of',
    'unresponsive to',
    'oblivious to',
    'unmoved by',
    'deaf to',
    'receptive to',
    'susceptible to',
    'shut',
    'slam',
    'fasten',
    'secure',
    'lock',
    'bolt',
    'bar',
    'latch',
    'padlock',
    'draw to',
    'pull to',
    'push to',
    'put up the shutter',
    'open',
    'unlock',
    'stop up',
    'plug',
    'cork',
    'stopper',
    'fill (up)',
    'pack',
    'stuff',
    'choke',
    'obstruct',
    'occlude',
    'stopple',
    'block (up/off)',
    'seal (up/off)',
    'shut up/off',
    'bung (up)',
    'make airtight',
    'make watertight',
    'clog (up)',
    'open',
    'unblock',
    'join',
    'connect',
    'unite',
    'come together',
    'come into contact',
    'form a circle',
    'end',
    'conclude',
    'finish',
    'terminate',
    'wind up',
    'break off',
    'halt',
    'discontinue',
    'dissolve',
    'adjourn',
    'suspend',
    'prorogue',
    'recess',
    'bring/come to an end',
    'call a halt to',
    'open',
    'begin',
    'end',
    'conclude',
    'finish',
    'terminate',
    'wind up',
    'break off',
    'halt',
    'discontinue',
    'dissolve',
    'adjourn',
    'suspend',
    'prorogue',
    'recess',
    'bring/come to an end',
    'call a halt to',
    'open',
    'begin',
    'clinch',
    'settle',
    'secure',
    'seal',
    'set the seal on',
    'confirm',
    'guarantee',
    'establish',
    'transact',
    'pull off',
    'complete',
    'conclude',
    'fix',
    'agree',
    'finalize',
    'bring off/about',
    'shake hands on',
    'shut down',
    'close down',
    'fail',
    'collapse',
    'crash',
    'go under',
    'cease activity',
    'cease production',
    'cease operating',
    'come to a halt',
    'cease trading',
    'go out of business',
    'go bankrupt',
    'become insolvent',
    'go into receivership',
    'go into liquidation',
    'be liquidated',
    'be wound up',
    'be closed (down)',
    'be shut (down)',
    'open',
    'catch up',
    'creep up',
    'near',
    'approach',
    'narrow',
    'lessen',
    'dwindle',
    'diminish',
    'reduce',
    'shrink',
    'contract',
    'constrict',
    'straiten',
    'gain on someone',
    'draw nearer/near',
    'get nearer/near',
    'come nearer/near',
    'draw closer/close',
    'get closer/close',
    'come closer/close',
    'grow/become/make smaller',
    'get/become/make narrower',
    'widen',
]

// closer
definitions: [
    '"the perfect closer to the album"',
    '"the last episode was still a great closer"',
    '"this role will best suit closers who are hungry to make commissions"',
    '"he could develop into a big-league closer"',
    '"one of the game\'s highest - paid closers"',
    '"the hotel is close to the sea"',
    '"her birthday and her wedding date were close together"',
    '"the months of living in close proximity to her were taking their toll"',
    '"cloth with a closer weave"',
    '"this work occupies over 1,300 pages of close print"',
    '"animals in close confinement"',
    '"on a good day the climate in LA is close to perfection"',
    '"she was close to tears"',
    '"the race will be a close contest"',
    '"she finished a close second"',
    '"the family history of cancer in close relatives"',
    '"they had always been very close, with no secrets at all"',
    '"the college has close links with many other institutions"',
    '"pay close attention to what your body is telling you about yourself"',
    '"we need to keep a close eye on this project"',
    '"his whereabouts are a close secret"',
    '"you\'re very close about your work, aren\'t you?"',
    '"a close, hazy day"',
    '"it was very close in the dressing room"',
    '"they stood close to the door"',
    '"he was holding her close"',
]
synonyms: [
    'near',
    'adjacent',
    'in the neighborhood of',
    'neighboring',
    'hard by',
    'adjoining',
    'abutting',
    'alongside',
    'close by',
    'nearby',
    'at hand',
    'contiguous',
    'proximate',
    'accessible',
    'handy',
    'convenient',
    'walkable',
    'nigh',
    'in close proximity',
    'close/near at hand',
    'not far from',
    'in the vicinity of',
    'within reach of',
    'within close range of',
    'on the doorstep',
    'within sight',
    'within earshot',
    'a stone\'s throw away',
    'at close quarters',
    'far',
    'distant',
    'remote',
    'dense',
    'compact',
    'tight',
    'close-packed',
    'packed',
    'solid',
    'condensed',
    'compressed',
    'concentrated',
    'crowded',
    'cramped',
    'crammed',
    'congested',
    'crushed',
    'squeezed',
    'jammed',
    'tightly packed',
    'sparse',
    'near',
    'within an ace of',
    'in danger of',
    'on the verge of',
    'on the brink of',
    'on the point of',
    'even',
    'well matched',
    'neck and neck',
    'side by side',
    'hard-fought',
    'nip and tuck',
    'evenly matched',
    'nose to nose',
    'with nothing to choose between them',
    'sharply contested',
    'one-sided',
    'immediate',
    'direct',
    'near',
    'distant',
    'intimate',
    'dear',
    'bosom',
    'close-knit',
    'inseparable',
    'attached',
    'loving',
    'devoted',
    'faithful',
    'constant',
    'special',
    'good',
    'best',
    'fast',
    'firm',
    'valued',
    'treasured',
    'cherished',
    'casual',
    'strong',
    'marked',
    'distinct',
    'pronounced',
    'slight',
    'careful',
    'detailed',
    'thorough',
    'minute',
    'painstaking',
    'meticulous',
    'assiduous',
    'diligent',
    'rigorous',
    'scrupulous',
    'conscientious',
    'attentive',
    'focused',
    'intent',
    'concentrated',
    'searching',
    'methodical',
    'vigilant',
    'watchful',
    'keen',
    'alert',
    'casual',
    'strict',
    'tight',
    'carefully guarded',
    'closely guarded',
    'reticent',
    'quiet',
    'uncommunicative',
    'unforthcoming',
    'private',
    'secretive',
    'tight-lipped',
    'close-mouthed',
    'close-lipped',
    'guarded',
    'evasive',
    'humid',
    'muggy',
    'stuffy',
    'airless',
    'fuggy',
    'heavy',
    'sticky',
    'steamy',
    'clammy',
    'sultry',
    'oppressive',
    'stifling',
    'suffocating',
    'unventilated',
    'like a Turkish bath',
    'like a sauna',
    'claggy',
    'fresh',
]

// clothe
definitions: [
    '"Francesca was clothed in white"',
    '"luxuriant tropical forests clothed the islands"',
    '"they already had eight children to feed and clothe"',
    '"you have been clothed with power from on high"',
]
synonyms: [
    'dress',
    'attire',
    'outfit',
    'array',
    'rig (out)',
    'turn out',
    'fit out',
    'costume',
    'robe',
    'garb',
    'drape',
    'accoutre',
    'bedizen',
    'caparison',
    'apparel',
    'habit',
    'invest',
    'cover',
    'overlay',
    'overspread',
    'cloak',
    'blanket',
    'carpet',
    'envelop',
    'swathe',
    'swaddle',
    'shroud',
    'wrap',
    'surround',
    'enshroud',
    'trick out/up',
    'deck out',
    'put clothes on',
    'trap out',
    'undress',
    'uncover',
    'provide',
    'furnish',
    'endow',
    'serve',
    'confer',
    'equip',
    'rig out',
    'outfit',
    'fit',
    'arm',
    'endue',
    'kit out',
]

// cloudy
definitions: [
    '"next morning was cloudy"',
    '"the pond water is slightly cloudy"',
    '"cloudy reds and blues and greens"',
    '"she stared at him, her eyes cloudy"',
    '"the issue becomes more cloudy"',
]
synonyms: [
    'overcast',
    'clouded',
    'overclouded',
    'dark',
    'darkened',
    'gray',
    'black',
    'leaden',
    'dull',
    'murky',
    'somber',
    'dismal',
    'dreary',
    'cheerless',
    'heavy',
    'gloomy',
    'dim',
    'louring',
    'sunless',
    'starless',
    'hazy',
    'misty',
    'foggy',
    'threatening',
    'menacing',
    'clouded over',
    'promising rain',
    'claggy',
    'bright',
    'murky',
    'muddy',
    'milky',
    'dirty',
    'clouded',
    'dull',
    'opaque',
    'nontransparent',
    'emulsified',
    'opalescent',
    'turbid',
    'riled',
    'roily',
    'roiled',
    'clear',
    'tearful',
    'teary',
    'weepy',
    'weeping',
    'lachrymose',
    'moist',
    'misty',
    'watery',
    'rheumy',
    'blurred',
    'blurry',
    'unfocused',
    'dry',
    'vague',
    'blurred',
    'fuzzy',
    'indistinct',
    'imprecise',
    'foggy',
    'hazy',
    'confused',
    'muddled',
    'indefinite',
    'nebulous',
    'obscure',
    'unformed',
    'lacking definition',
    'clear',
    'focused',
]

// coated
definitions: [
    '"plastic-coated wire"',
    '"a winter coat"',
    '"his coat pocket"',
    '"a laboratory coat"',
    '"she wore a pale linen coat and skirt"',
    '"a dog\'s coat may become tangled and matted"',
    '"the protein coat of the virus"',
    '"a protective coat of varnish"',
    '"coat each part with a thin oil"',
    '"his boots were coated with mud"',
    '"a film of dust coated the floor"',
    '"coat each part with a thin oil"',
    '"his boots were coated with mud"',
    '"a film of dust coated the floor"',
]
synonyms: [
    'overcoat',
    'tunic',
    'fur',
    'hair',
    'wool',
    'fleece',
    'hide',
    'pelt',
    'skin',
    'fell',
    'layer',
    'covering',
    'overlay',
    'coating',
    'skin',
    'skim',
    'plating',
    'film',
    'wash',
    'glaze',
    'varnish',
    'veneer',
    'lamination',
    'sheet',
    'finish',
    'dusting',
    'blanket',
    'mantle',
    'daub',
    'smear',
    'topping',
    'crust',
    'patina',
    'luster',
    'deposit',
    'scale',
    'facing',
    'cladding',
    'paint',
    'stain',
    'varnish',
    'layer',
    'film',
    'overlay',
    'cover',
    'overlay',
    'paint',
    'glaze',
    'varnish',
    'wash',
    'surface',
    'veneer',
    'inlay',
    'laminate',
    'plate',
    'blanket',
    'mantle',
    'daub',
    'smear',
    'bedaub',
    'cake',
    'plaster',
    'overspread',
    'encrust',
    'face',
    'besmear',
    'cover',
    'clad',
    'veneer',
    'skin',
    'overlay',
    'surface',
    'dress',
    'pave',
    'laminate',
    'inlay',
    'plate',
    'line',
    'put a facing on',
    'cover',
    'overlay',
    'paint',
    'glaze',
    'varnish',
    'wash',
    'surface',
    'veneer',
    'inlay',
    'laminate',
    'plate',
    'blanket',
    'mantle',
    'daub',
    'smear',
    'bedaub',
    'cake',
    'plaster',
    'overspread',
    'encrust',
    'face',
    'besmear',
    'cover',
    'clad',
    'veneer',
    'skin',
    'overlay',
    'surface',
    'dress',
    'pave',
    'laminate',
    'inlay',
    'plate',
    'line',
    'put a facing on',
]



// crewed
// crewed
// definitions: [
//     '"normally the boat is crewed by five people"',
//     '"I\'ve never crewed for a world - famous yachtsman before"'
// ]
// synonyms: [
// ]





// danged
definitions: [
    '"just get the dang car started!"',
    '"every danged day, it seems like there\'s bad news"',
    '"this is the dangedest thing I have ever seen"',
    '"some of the stuff was just dang strange"',
    '"I\'ll be danged!"',
    '"dang me, I wish I was as strong as I used to be"',
    '"dang it, Phil, stop snoring!"',
]
synonyms: [
]

// danger
definitions: [
    '"his life was in danger"',
    '"infertile soils where drought is a danger"',
    '"there was no danger of the champagne running out"',
    '"one of the trains involved passed a signal at danger"',
]
synonyms: [
    'peril',
    'hazard',
    'risk',
    'jeopardy',
    'endangerment',
    'imperilment',
    'insecurity',
    'perilousness',
    'riskiness',
    'precariousness',
    'uncertainty',
    'instability',
    'safety',
    'menace',
    'hazard',
    'threat',
    'risk',
    'peril',
    'source of apprehension',
    'source of dread',
    'source of fright',
    'source of fear',
    'source of terror',
    'possibility',
    'chance',
    'risk',
    'probability',
    'likelihood',
    'fear',
    'prospect',
]



// darkly
definitions: [
    '"“You can\'t trust him,” said Jacob darkly"',
    '"I wondered darkly if I was wasting my time"',
    '"a figure silhouetted darkly against the trees"',
]
synonyms: [
]

// dashed
definitions: [
    '"it\'s a dashed shame"',
    '"she was dashed rude"',
    '"I dashed into the garden"',
    '"I must dash, I\'m late"',
    '"the ship was dashed upon the rocks"',
    '"a gust of rain dashed against the bricks"',
    '"the budget dashed hopes of an increase in funding"',
    '"I won\'t tell Stuart—I think he\'d be dashed"',
]
synonyms: [
    'damned',
    'damn',
    'damnable',
    'wretched',
    'accursed',
    'rotten',
    'horrible',
    'annoying',
    'irritating',
    'infuriating',
    'exasperating',
    'rush',
    'race',
    'run',
    'sprint',
    'bolt',
    'dart',
    'gallop',
    'career',
    'charge',
    'shoot',
    'hurtle',
    'hare',
    'bound',
    'fly',
    'speed',
    'streak',
    'zoom',
    'plunge',
    'dive',
    'whisk',
    'scurry',
    'scuttle',
    'scamper',
    'scramble',
    'fleet',
    'post',
    'hie',
    'haste',
    'dawdle',
    'hurl',
    'smash',
    'crash',
    'slam',
    'throw',
    'toss',
    'fling',
    'pitch',
    'cast',
    'lob',
    'launch',
    'flip',
    'catapult',
    'shy',
    'aim',
    'direct',
    'project',
    'propel',
    'send',
    'bowl',
    'crash',
    'smash',
    'batter',
    'strike',
    'beat',
    'pound',
    'pummel',
    'lash',
    'be hurled',
    'slam into',
    'shatter',
    'destroy',
    'wreck',
    'ruin',
    'crush',
    'devastate',
    'demolish',
    'blast',
    'blight',
    'wipe out',
    'overturn',
    'torpedo',
    'scotch',
    'spoil',
    'frustrate',
    'thwart',
    'balk',
    'check',
    'burst someone\'s bubble',
    'bring to naught',
    'wreak havoc with',
    'raise',
    'depress',
    'dispirit',
    'dishearten',
    'grieve',
    'desolate',
    'discourage',
    'upset',
    'get down',
    'bring down',
    'cast down',
    'break someone\'s heart',
    'deject',
    'dampen someone\'s spirits',
    'cast a gloom on',
    'bring tears to someone\'s eyes',
    'make someone\'s heart bleed',
    'cheer up',
]



// defuel
definitions: [
]
synonyms: [
]

// degels
definitions: [
]
synonyms: [
]


// deltas
definitions: [
    '"delta hepatitis"',
    '"Delta Cephei"',
    '"there\'s a delta between perception and reality"',
    '"as long as the price delta is not too great, consumers can be sold on specs and future-proofing"',
    '"this approach saves disk space by storing only data deltas"',
    '"updates will be delivered as delta updates instead of complete application downloads"',
    '"the Nile delta"',
    '"a huge delta system developed"',
]
synonyms: [
]

// denial
definitions: [
    '"she shook her head in denial"',
    '"official denials"',
    '"his denial that he was having an affair"',
    '"the denial of insurance to people with certain medical conditions"',
    '"you\'re living in denial"',
]
synonyms: [
    'contradiction',
    'refutation',
    'rebuttal',
    'repudiation',
    'disclaimer',
    'retraction',
    'abjuration',
    'negation',
    'dissent',
    'disaffirmation',
    'confutation',
    'counterstatement',
    'retractation',
    'confirmation',
    'contradiction',
    'refutation',
    'rebuttal',
    'repudiation',
    'disclaimer',
    'retraction',
    'abjuration',
    'negation',
    'dissent',
    'disaffirmation',
    'confutation',
    'counterstatement',
    'retractation',
    'confirmation',
    'refusal',
    'withholding',
    'withdrawal',
    'rejection',
    'dismissal',
    'rebuff',
    'repulse',
    'declination',
    'veto',
    'turndown',
    'acceptance',
]
// denies
definitions: [
    '"they deny any responsibility for the tragedy"',
    '"an anti-environmentalist campaign group that denies climate change"',
    '"the inquiry was denied access to intelligence sources"',
    '"there was no way that I was going to deny myself ice cream"',
    '"the servants are ordered to deny him"',
]
synonyms: [
    'contradict',
    'repudiate',
    'gainsay',
    'challenge',
    'contest',
    'oppose',
    'retract',
    'take back',
    'backpedal',
    'disprove',
    'debunk',
    'explode',
    'discredit',
    'refute',
    'rebut',
    'invalidate',
    'negate',
    'nullify',
    'quash',
    'disaffirm',
    'controvert',
    'confute',
    'negative',
    'declare untrue',
    'dissent from',
    'disagree with',
    'confirm',
    'refuse',
    'turn down',
    'reject',
    'rebuff',
    'repulse',
    'decline',
    'veto',
    'dismiss',
    'accept',
]

// denned
definitions: [
    '"the cubs denned in the late autumn"',
]
synonyms: [

]

// denote
definitions: [
    '"this mark denotes purity and quality"',
    '"the level of output per firm, denoted by X"',
]
synonyms: [
    'designate',
    'indicate',
    'signify',
    'signal',
    'symbolize',
    'represent',
    'stand for',
    'mean',
    'typify',
    'characterize',
    'distinguish',
    'mark',
    'identify',
    'bespeak',
    'betoken',
    'suggest',
    'point to',
    'show',
    'reveal',
    'demonstrate',
    'intimate',
    'imply',
    'connote',
    'convey',
    'give away',
    'betray',
    'be a sign of',
    'be a mark of',
    'be evidence of',
    'smack of',
    'conjure up',
    'bring to mind',
    'represent',
    'stand for',
    'exemplify',
    'signify',
    'mean',
    'communicate',
    'indicate',
    'convey',
    'express',
    'imply',
    'suggest',
    'embody',
    'epitomize',
    'encapsulate',
    'personify',
    'typify',
    'betoken',
    'symbol',
    'be a symbol of',
    'be a sign of',
    'allude to',
]

// dental
definitions: [
    '"dental health"',
    '"dental councils"',
]
synonyms: [
]
// depend
definitions: [
    '"differences in earnings depended on a wide variety of factors"',
    '"the kind of person you could depend on"',
    '"a town that had depended heavily upon the wool industry"',
    '"his tongue depended from open jaws"',
]
synonyms: [
    'turn on',
    'hang on',
    'be contingent on',
    'be conditional on',
    'be dependent on',
    'pivot on',
    'hinge on',
    'rest on',
    'be based on',
    'rely on',
    'be subject to',
    'be controlled by',
    'be determined by',
    'be influenced by',
    'be decided by',
    'be resultant from',
    'relate to',
    'believe in',
    'bank on',
    'count on',
    'swear by',
    'have faith in',
    'put/place one\'s trust in ',
    'have (every) confidence in',
    'pin one\'s hopes / faith on',
    'rely on',
    'depend on',
    'be sure of',
    'be convinced by',
    'confide in',
    'distrust',
    'mistrust',
    'doubt',
    'lean on',
    'count on',
    'bank on',
    'trust',
    'believe in',
    'swear by',
    'rely on',
    'place reliance on',
    'cling to',
    'be supported by',
    'be sustained by',
    'be unable to manage without',
    'trust in',
    'put one\'s trust in ',
    'put one\'s faith in ',
    'have faith in',
    'have (every) confidence in',
    'be sure of',
    'pin one\'s hope on',
    'droop',
    'sag',
    'swing',
    'sway',
    'wave',
    'trail',
    'stream',
    'hang (down)',
]


// desert
definitions: [
    '"we feel our public representatives have deserted us"',
    '"good weather came after the summer hordes had deserted the beaches"',
    '"her luck deserted her"',
    '"his life in the regiment had been such a hell that he decided to desert"',
    '"a cultural desert"',
    '"overgrazing has created desert conditions"',
    '"desert wastes"',
]
synonyms: [
    'abandoned',
    'forsaken',
    'betrayed',
    'jilted',
    'shunned',
    'neglected',
    'stranded',
    'marooned',
    'relinquished',
    'renounced',
    'forlorn',
    'bereft',
    'abandon',
    'leave',
    'give up',
    'cast off',
    'turn one\'s back on',
    'throw over',
    'betray',
    'jilt',
    'neglect',
    'shun',
    'leave behind',
    'strand',
    'maroon',
    'relinquish',
    'renounce',
    'forsake',
    'repudiate',
    'forswear',
    'wash one\'s hands of',
    'abjure',
    'disavow',
    'apostatize',
    'recant',
    'cast off/aside',
    'thrown over',
    'break (up) with',
    'leave high and dry',
    'leave in the lurch',
    'leave stranded',
    'renege on',
    'have no more truck with',
    'have done with',
    'disprofess',
    'stand by',
    'empty',
    'uninhabited',
    'unoccupied',
    'unpeopled',
    'abandoned',
    'evacuated',
    'vacant',
    'vacated',
    'untenanted',
    'tenantless',
    'unfrequented',
    'neglected',
    'secluded',
    'isolated',
    'desolate',
    'lonely',
    'solitary',
    'godforsaken',
    'forlorn',
    'crowded',
    'populous',
    'abscond',
    'defect',
    'run away',
    'make off',
    'decamp',
    'flee',
    'fly',
    'bolt',
    'turn tail',
    'depart',
    'quit',
    'escape',
    'go absent without leave',
    'take French leave',
    'stay',
    'wasteland',
    'waste',
    'wilderness',
    'wilds',
    'dust bowl',
    'barren land',
    'wasteland',
    'uninteresting place/period',
    'unproductive place/period',
    'arid',
    'dry',
    'moistureless',
    'parched',
    'scorched',
    'burnt',
    'hot',
    'burning',
    'torrid',
    'barren',
    'bare',
    'stark',
    'infertile',
    'nonfertile',
    'unproductive',
    'unfruitful',
    'dehydrated',
    'sterile',
    'dried up',
    'uncultivatable',
    'fertile',
    'uninhabited',
    'empty',
    'solitary',
    'lonely',
    'desolate',
    'bleak',
    'dismal',
    'waste',
    'wild',
    'uncultivated',
    'untended',
    'untilled',
]


// dialed






// dollar
definitions: [
]
synonyms: [
]



// dorses
definitions: [
    '"he took a dose of cough medicine"',
    '"a dose of radiation exceeding safety limits"',
    '"I wanted to give you a dose of the hell you put me through"',
    '"he dosed himself with vitamins"',
    '"the champagne was dosed with sugar"',
]
synonyms: [
    'amount',
    'quantity',
    'measure',
    'portion',
    'dosage',
    'drench',
    'draft',
    'overdose',
    'lethal dose',
    'treat',
    'medicate',
    'soothe',
    'cure',
    'heal',
    'tend',
    'take care of',
    'nurse',
    'attend to',
    'minister to',
    'administer to',
    'care for',
]

// dosage
definitions: [
    '"a dosage of 450 milligrams a day"',
    '"there are recommendations about dosage for elderly patients"',
]
synonyms: [
    'amount',
    'number',
    'total',
    'aggregate',
    'sum',
    'quota',
    'group',
    'size',
    'mass',
    'weight',
    'volume',
    'bulk',
    'load',
    'consignment',
    'expanse',
    'extent',
    'length',
    'area',
    'quantum',
    'proportion',
    'portion',
    'part',
    'dose',
]

// douane
definitions: [
]
synonyms: [
]

// double
definitions: [
    '"the double doors"',
    '"she sipped a double brandy"',
    '"a double bed"',
    '"the double life of a freelance secret agent"',
    '"“otter” is spelled with a double t"',
    '"large double blooms"',
    '"the jail now houses almost double the number of prisoners it was designed for"',
    '"I\'ll pay double what I paid last time"',
    '"you have to be careful, and this counts double for older people"',
    '"she thought she was seeing double"',
    '"join the two sleeping bags together to make a double"',
    '"“Two whiskies, and make it doubles please”"',
    '"you must finish the game on a double"',
    '"you could pass yourself off as his double"',
    '"she had seen her husband\'s double"',
    '"the semifinals of the doubles"',
    '"he paid double and had a room all to himself"',
    '"profits doubled in one year"',
    '"Clare doubled her income overnight"',
    '"thy fifty yet doth double five and twenty"',
    '"I doubled across the deck to join the others"',
    '"Strawberry doubled with two outs"',
    '"it may be right for East to double"',
    '"the muslin is doubled and then laid in a sieve over the bowl"',
    '"he had one arm around her and the other fist doubled"',
    '"we struck out seaward to double the headland of the cape"',
    '"a laser printer doubles as a photocopier"',
]
synonyms: [
    'dual',
    'duplex',
    'twin',
    'binary',
    'duplicate',
    'matched',
    'matching',
    'paired',
    'complementary',
    'coupled',
    'twofold',
    'binate',
    'in pairs',
    'single',
    'doubled',
    'twofold',
    'twice the usual size',
    'ambiguous',
    'equivocal',
    'dual',
    'two-edged',
    'ambivalent',
    'arguable',
    'debatable',
    'Delphic',
    'cryptic',
    'enigmatic',
    'gnomic',
    'paradoxical',
    'misleading',
    'double-edged',
    'deceitful',
    'double-dealing',
    'two-faced',
    'Janus-faced',
    'hypocritical',
    'backstabbing',
    'false',
    'duplicitous',
    'insincere',
    'deceiving',
    'dissembling',
    'dishonest',
    'disloyal',
    'treacherous',
    'perfidious',
    'faithless',
    'lying',
    'untruthful',
    'mendacious',
    'open to debate',
    'open to argument',
    'unambiguous',
    'simple',
    'honest',
    'twice',
    'doubly',
    'twice over',
    'twice the amount',
    'lookalike',
    'twin',
    'clone',
    'duplicate',
    'replica',
    'copy',
    'facsimile',
    'imitation',
    'picture',
    'image',
    'mirror image',
    'counterpart',
    'match',
    'mate',
    'fellow',
    'perfect likeness',
    'exact likeness',
    'living image',
    'Doppelgänger',
    'stand-in',
    'body double',
    'understudy',
    'substitute',
    'lookalike',
    'twin',
    'clone',
    'duplicate',
    'replica',
    'copy',
    'facsimile',
    'imitation',
    'picture',
    'image',
    'mirror image',
    'counterpart',
    'match',
    'mate',
    'fellow',
    'perfect likeness',
    'exact likeness',
    'living image',
    'Doppelgänger',
    'enlarge',
    'magnify',
    'repeat',
    'multiply by two',
    'increase twofold',
    'sprint',
    'race',
    'dart',
    'rush',
    'dash',
    'hasten',
    'hurry',
    'scurry',
    'scuttle',
    'scamper',
    'hare',
    'bolt',
    'bound',
    'fly',
    'gallop',
    'career',
    'charge',
    'pound',
    'shoot',
    'hurtle',
    'speed',
    'streak',
    'whiz',
    'zoom',
    'sweep',
    'flash',
    'jog',
    'lope',
    'trot',
    'jogtrot',
    'dogtrot',
    'post',
    'hie',
    'go like lightning',
    'go hell for leather',
    'go like the wind',
    'dawdle',
    'crease',
    'fold (back/up/down/over/under)',
    'turn back/up/down/over/under',
    'tuck back/up/down/under',
    'bend back/over',
    'function',
    'do',
    '(also) serve',
    'have/serve a dual purpose',
    'have a dual role',
]

// drafts
definitions: [
    '"the first draft of the party\'s manifesto"',
    '"a draft document"',
    '"25 million men were subject to the draft"',
    '"draft cards"',
    '"heavy curtains at the windows cut out drafts"',
    '"she downed the remaining beer in one draft"',
    '"he took deep drafts of oxygen into his lungs"',
    '"the shallow draft enabled her to get close to shore"',
    '"I drafted a letter of resignation"',
    '"he was drafted to help with the task force on best safety practices"',
    '"he was drafted in 1938"',
    '"he was drafted by Winnipeg and traded the following spring"',
]
synonyms: [
    'conscript',
    'call up',
    'enlist',
    'mobilize',
    'rally',
    'muster',
    'marshal',
    'press',
    'recruit',
    'raise',
    'assemble',
    'round up',
    'demobilize',
    'disband',
]

// dragon
definitions: [
    '"the geography teacher was a real dragon"',
]
synonyms: [

]

// dramas
definitions: [
    '"a gritty urban drama about growing up in Harlem"',
    '"Renaissance drama"',
    '"a hostage drama"',
    '"an afternoon of high drama at Fenway Park"',
]
synonyms: [
    'play',
    'show',
    'piece',
    'spectacle',
    'dramatization',
    'screenplay',
    'theatrical work',
    'catastrophe',
    'calamity',
    'cataclysm',
    'emergency',
    'disaster',
    'predicament',
    'plight',
    'mess',
    'dilemma',
    'quandary',
    'setback',
    'reverse',
    'reversal',
    'upheaval',
    'trouble',
    'hardship',
    'adversity',
    'extremity',
    'distress',
    'difficulty',
    'dire straits',
    'hard times',
]

// dreamt
definitions: [
    '"I dreamed about her last night"',
    '"maybe you dreamed it"',
    '"eventually I dozed off and dreamed that I was flying among the clouds"',
    '"she had dreamed of a trip to Italy"',
    '"this is not at all how she dreamed her baby\'s birthday was going to be"',
    '"I wouldn\'t dream of foisting myself on you"',
    '"I never dreamed anyone would take offense"',
]
synonyms: [
    'have a dream',
    'have dreams',
    'have a nightmare',
    'have nightmares',
    'set one\'s heart on',
    'set one\'s sights on',
    'fantasize about',
    'daydream about',
    'wish for',
    'hope for',
    'long for',
    'yearn for',
    'hunger for',
    'hanker after',
    'aspire to',
    'desire to',
    'wish to',
    'aim for',
    'seek to',
    'have as one\'s goal/aim',
    'thirst for/after',
    'think',
    'consider',
    'contemplate',
    'conceive',
    'visualize',
    'entertain the thought of',
]

// driers
definitions: [
    '"putting their sweaters in the big dryer"',
]
synonyms: [

]

// driver]
definitions: [
    '"a taxi driver"',
    '"student drivers"',
    '"mule drivers"',
    '"the hope of achieving such monopolies becomes the main driver of investment"',
]
synonyms: [
    'motorist',
    'chauffeur',
    'pilot',
    'operator',
    'engineer',
    'passenger',
]

// droved
definitions: [
    '"a drove of cattle"',
    '"tourists have stayed away in droves this summer"',
    '"he got into his car and drove off"',
    '"they drove back into town"',
    '"a car drives up, and a man gets out"',
    '"a stream of black cars drove by"',
    '"I watched her car drive away"',
    '"I drove the truck back to New York"',
    '"there are endless shots of Julie driving her car along winding roads"',
    '"Sue drives an old Chevy"',
    '"I take it you can drive?"',
    '"Shelley drove him to the supermarket"',
    '"the wind will drive you onshore"',
    '"the snow drove against him"',
    '"nails are driven through the boards"',
    '"an engineer suggested driving a tunnel through the hills"',
    '"they drove a flock of sheep through the center of the city"',
    '"the French infantry were driven back"',
    '"turbines driven by steam"',
    '"the interface can be used to drive a printer"',
    '"he was driven by ambition"',
    '"some people are driven to murder their tormentors"',
    '"the thought drove him to despair"',
    '"my laziness drives my wife crazy"',
    '"you\'re driving yourself too hard"',
    '"the consumer has been driving the economy for a number of years"',
    '"we need to allow market forces to drive growth in the telecommunications sector"',
    '"I\'m driving the ball really well and my irons are good"',
]
synonyms: [
    'herd',
    'flock',
    'pack',
    'fold',
    'crowd',
    'swarm',
    'horde',
    'multitude',
    'mob',
    'throng',
    'host',
    'mass',
    'army',
    'collection',
    'gathering',
    'assembly',
    'company',
    'rabble',
    'herd',
    'crush',
    'press',
    'stream',
    'sea',
    'operate',
    'pilot',
    'steer',
    'handle',
    'manage',
    'guide',
    'direct',
    'navigate',
    'motor',
    'travel by car',
    'go by car',
    'walk',
    'maintain',
    'keep',
    'own',
    'possess',
    'have',
    'chauffeur',
    'run',
    'take',
    'bring',
    'ferry',
    'transport',
    'convey',
    'carry',
    'give someone a lift',
    'power',
    'propel',
    'move',
    'push',
    'hammer',
    'screw',
    'ram',
    'bang',
    'pound',
    'sink',
    'plunge',
    'thrust',
    'stab',
    'propel',
    'knock',
    'send',
    'drill',
    'pierce',
    'perforate',
    'puncture',
    'punch',
    'cut',
    'tunnel',
    'burrow',
    'mine',
    'dig (out)',
    'sink',
    'make',
    'create',
    'put',
    'gouge (out)',
    'impel',
    'urge',
    'press',
    'move',
    'herd',
    'roundup',
    'shepherd',
    'get going',
    'force',
    'compel',
    'constrain',
    'impel',
    'press',
    'prompt',
    'precipitate',
    'catapult',
    'oblige',
    'coerce',
    'make',
    'pressure',
    'goad',
    'spur',
    'prod',
    'work',
    'exert',
    'push',
    'tax',
    'overwork',
    'overtax',
    'overburden',
]

// drunks
definitions: [
    '"we staggered up the path like a couple of drunks"',
    '"he used to go on these blind drunks"',
]
synonyms: [
    'drunkard',
    'inebriate',
    'drinker',
    'imbiber',
    'tippler',
    'sot',
    'alcoholic',
    'dipsomaniac',
    'alcohol abuser',
    'toper',
    'tosspot',
    'heavy drinker',
    'hard drinker',
    'serious drinker',
    'problem drinker',
    'chronic alcoholic',
    'alcohol addict',
    'person with a drink problem',
    'teetotaler',
]

// drying
definitions: [
    '"allow 24 hours for the paint to dry"',
    '"come in out of the rain and dry off"',
    '"they had washed and dried their hair"',
    '"she dried her eyes and blew her nose"',
    '"I use several methods to dry the flowers and foliage I use in my arrangements"',
    '"the natural sugars in the fruit will be concentrated when it is dried"',
    '"a colleague of mine once dried in the middle of a scene"',
]
synonyms: [
    'parch',
    'scorch',
    'sear',
    'bake',
    'dehydrate',
    'desiccate',
    'dehumidify',
    'towel',
    'towel-dry',
    'rub',
    'mop up',
    'soak up',
    'absorb',
    'clean up',
    'drain',
    'make dry',
    'dry out/up',
    'dry off',
    'blot up',
    'sop up',
    'moisten',
    'wipe',
    'rub',
    'dab',
    'wipe tears from',
    'dry up',
    'dehydrate',
    'desiccate',
    'wither',
    'shrivel',
    'wilt',
    'wizen',
    'mummify',
    'preserve',
    'cure',
    'smoke',
    'remove the moisture from',
    'moisten',
]

// during
definitions: [
    '"the restaurant is open during the day"',
    '"the period during which he grew to adulthood"',
    '"the stabbing took place during an argument at a party"',
]
synonyms: [
    'throughout',
    'through',
    'in',
    'in the course of',
    'throughout the time of',
    'for the time of',
    'in the time of',
]
