export const definitions = [
    '"issues worthy of further consideration"',
    '"generous donations to worthy causes"',
    '"no composer was considered worthy of the name until he had written an opera"',
    '"schools governed by local worthies"',
    '"newsworthy"',
    '"roadworthy"',
]
export const synonyms = [
    'virtuous',
    'good',
    'moral',
    'ethical',
    'principled',
    'high-principled',
    'high-minded',
    'right-thinking',
    'noble',
    'upright',
    'upstanding',
    'righteous',
    'solid',
    'decent',
    'law-abiding',
    'honest',
    'honorable',
    'respectable',
    'respected',
    'venerable',
    'reputable',
    'trustworthy',
    'trusty',
    'trusted',
    'reliable',
    'dependable',
    'conscientious',
    'irreproachable',
    'blameless',
    'unimpeachable',
    'exemplary',
    'admirable',
    'praiseworthy',
    'laudable',
    'commendable',
    'estimable',
    'deserving',
    'meritorious',
    'creditable',
    'sterling',
    'of good report',
    'applaudable',
    'disreputable',
    'unworthy',
    'deserve',
    'merit',
    'warrant',
    'rate',
    'justify',
    'earn',
    'be deserving of',
    'be entitled to',
    'have a right to',
    'have a claim to/on',
    'be qualified for',
    'qualify for',
    'be unworthy of',
    'be undeserving of',
    'dignitary',
    'notable',
    'notability',
    'celebrity',
    'personage',
    'luminary',
    'official',
    'grandee',
    'panjandrum',
    'leading light',
    'name',
    'big name',
    'somebody',
    'someone',
    'famous person',
    'important person',
    'person of note',
    'public figure',
    'pillar of society',
    'nobody',
]