export const definitions = [
  '"with a wrench Tony wriggled free"',
  '"it will be a real wrench to leave after eight years"',
  '"you will need a wrench to tighten it in position"',
  '"Casey grabbed the gun and wrenched it upward from my hand"',
  '"she wrenched herself free of his grip"',
  '"the betrayal wrenched at her heart"',
  '"she slipped and wrenched her ankle"',
  '"to wrench our Bible to make it fit a misconception of facts"',
];
export const synonyms = [
  'tug',
  'pull',
  'jerk',
  'jolt',
  'wrest',
  'heave',
  'twist',
  'pain',
  'ache',
  'pang',
  'trauma',
  'painful parting',
  'distressing separation',
  'traumatic event',
  'spanner',
  'monkey wrench',
  'adjustable spanner',
  'tug',
  'pull',
  'jerk',
  'wrest',
  'heave',
  'twist',
  'tear',
  'rip',
  'pluck',
  'grab',
  'seize',
  'snatch',
  'force',
  'prise',
  'peel',
  'pry',
  'take by force',
  'remove by force',
  'sprain',
  'twist',
  'turn',
  'strain',
  'rick',
  'crick',
  'pull',
  'dislocate',
  'damage',
  'injure',
  'hurt',
  'put out of joint',
];