export const definitions = [
    '"can the poor wretch\'s corpse tell us anything ? "',
    '"ungrateful wretches"',
]
export const synonyms = [
    'unfortunate',
    'poor creature',
    'poor soul',
    'poor thing',
    'miserable creature',
    'sad case',
    'poor unfortunate',
    'scoundrel',
    'villain',
    'ruffian',
    'rogue',
    'rascal',
    'reprobate',
    'criminal',
    'delinquent',
    'good-for-nothing',
    'cad',
    'blackguard',
    'miscreant',
    'knave',
    'dastard',
    'varlet',
    'wastrel',
    'rapscallion',
    'whoreson',
]