export const definitions = [
  '"she yearned for a glimpse of him"',
  '"they yearned to go home"',
  '"some people yearn for a return to monarchy"',
  '"no fellow spirit yearned toward her"',
];
export const synonyms = [
  'long',
  'pine',
  'crave',
  'desire',
  'want',
  'wish',
  'covet',
  'lust',
  'pant',
  'hunger',
  'thirst',
  'ache',
  'itch',
  'fancy',
  'want badly',
  'have/feel a longing',
  'be aching',
  'be itching',
  'hanker after',
  'dream of',
  'have one\'s heart set on',
  'be bent on',
  'eat one\'s heart out over',
  'be athirst for',
  'be desirous',
  'suspire for',
];