export const definitions = [
    '"curly yellow hair"',
    '"he put Camp Visoko on yellow alert"',
    '"he\'d better get back there quick and prove he\'s not yellow"',
    '"he based his judgment on headlines and yellow journalism"',
    '"the craft detonated in a blaze of red and yellow"',
    '"a wide range of colours from rich vibrant reds, yellows, blues, and greens to more unexpected pastel shades"',
    '"everyone dresses in yellow"',
    '"the cream paint was beginning to yellow"',
]
export const synonyms = [
    'yellowish',
    'yellowy',
    'lemon',
    'lemony',
    'amber',
    'gold',
    'golden',
    'blond',
    'fair',
    'flaxen',
    'light brown',
    'cowardly',
    'lily-livered',
    'faint-hearted',
    'chicken-hearted',
    'pigeon-hearted',
    'craven',
    'spiritless',
    'spineless',
    'timid',
    'timorous',
    'fearful',
    'trembling',
    'quaking',
    'shrinking',
    'cowering',
    'pusillanimous',
    'weak',
    'feeble',
    'soft',
    'poltroon',
    'recreant',
    'poor-spirited',
    'afraid of one\'s own shadow',
    'brave',
    'courageous',
    'overdramatized',
    'dramatic',
    'melodramatic',
    'exaggerated',
    'overripe',
    'sensationalist',
    'sensationalistic',
    'graphic',
    'explicit',
    'unrestrained',
    'lurid',
    'trashy',
    'cheap',
    'tasteless',
    'kitschy',
    'pulp',
    'garish',
    'full-frontal',
    'dull',
    'understated',
]