export const definitions = [
    '"answering with assured and ardent yeses"',
]
export const synonyms = [
    'approval',
    'seal of approval',
    'approbation',
    'endorsement',
    'welcome',
    'encouragement',
    'permission',
    'liberty',
    'authorization',
    'consent',
    'leave',
    'authority',
    'sanction',
    'ratification',
    'license',
    'dispensation',
    'nod',
    'assent',
    'acquiescence',
    'agreement',
    'blessing',
    'imprimatur',
    'rubber stamp',
    'clearance',
    'acceptance',
    'permit',
    'rejection',
    'thumbs down',
]