export const definitions = [
    '"under Justinian, the Byzantine Empire reached its zenith of influence"',
    '"the sun was well past the zenith"',
    '"the missile reached its zenith and fell"',
]
export const synonyms = [
    'high point',
    'height',
    'top',
    'acme',
    'peak',
    'pinnacle',
    'apex',
    'apogee',
    'vertex',
    'tip',
    'crown',
    'crest',
    'summit',
    'climax',
    'culmination',
    'maximum',
    'optimum',
    'prime',
    'meridian',
    'flower',
    'highest point',
    'crowning point',
    'nadir',
    'bottom',
]