export const definitions = [
    '"I zipped up my sweater"',
    '"he zipped himself up"',
    '"swallows zipped back and forth across the lake"',
    '"he zipped a pass out to his receiver"',
]
export const synonyms = [
    'speed',
    'hurry',
    'race',
    'run',
    'sprint',
    'dash',
    'bolt',
    'dart',
    'rush',
    'hasten',
    'hurtle',
    'career',
    'streak',
    'shoot',
    'whiz',
    'zoom',
    'whirl',
    'whoosh',
    'buzz',
    'swoop',
    'flash',
    'blast',
    'charge',
    'stampede',
    'gallop',
    'sweep',
    'hare',
    'fly',
    'wing',
    'scurry',
    'scud',
    'scutter',
    'scramble',
    'fleet',
    'post',
    'hie',
    'drive',
    'go like lightning',
    'go hell for leather',
    'spank along',
    'bowl along',
    'rattle along',
    'dawdle',
]