export const definitions = ['"they heard the sound as an augury of death"'];
export const synonyms = [
  "omen",
  "sign",
  "indication",
  "presage",
  "warning",
  "forewarning",
  "harbinger",
  "signal",
  "promise",
  "threat",
  "menace",
  "forecast",
  "prediction",
  "prognostication",
  "prophecy",
  "hint",
  "auspice",
  "premonition",
  "presentiment",
  "feeling",
  "foreboding",
  "misgiving",
  "foretoken",
  "ill omen",
  "straw in the wind",
  "writing on the wall",
  "vague feeling",
  "funny feeling",
  "feeling in one's bones",
  "fortune telling",
  "divining",
  "prophecy",
  "prediction",
  "soothsaying",
  "clairvoyance",
  "second sight",
  "magic",
  "sorcery",
  "witchcraft",
  "vaticination",
  "sortilege",
  "witchery",
  "foretelling the future",
  "forecasting the future",
  "spellworking",
  "auspication",
];
