export const definitions = [
  '"she was in august company"',
  '"the sultry haze of late August"',
  '"an August cold snap"',
];
export const synonyms = [
  "distinguished",
  "respected",
  "eminent",
  "venerable",
  "hallowed",
  "illustrious",
  "prestigious",
  "renowned",
  "celebrated",
  "honored",
  "acclaimed",
  "esteemed",
  "exalted",
  "well thought of",
  "great",
  "important",
  "lofty",
  "high-ranking",
  "noble",
  "regal",
  "royal",
  "aristocratic",
  "imposing",
  "impressive",
  "awe-inspiring",
  "magnificent",
  "majestic",
  "imperial",
  "stately",
  "lordly",
  "kingly",
  "grand",
  "dignified",
  "solemn",
  "proud",
  "highly regarded",
  "of distinction",
  "of repute",
  "of high standing",
];
