export const definitions = [
  '"a cast of crazy and kooky characters"',
  '"I like kooky foreign films"',
];
export const synonyms = [
  "unusual",
  "irregular",
  "unorthodox",
  "unfamiliar",
  "uncommon",
  "unwonted",
  "rare",
  "out of the ordinary",
  "atypical",
  "singular",
  "distinctive",
  "individual",
  "individualistic",
  "free-spirited",
  "alternative",
  "different",
  "new",
  "fresh",
  "novel",
  "newfangled",
  "innovative",
  "groundbreaking",
  "experimental",
  "pioneering",
  "original",
  "unprecedented",
  "eccentric",
  "idiosyncratic",
  "maverick",
  "quirky",
  "odd",
  "strange",
  "bizarre",
  "weird",
  "outlandish",
  "freakish",
  "funny",
  "quaint",
  "queer",
  "curious",
  "abnormal",
  "anomalous",
  "aberrant",
  "extraordinary",
  "offbeat",
  "off-center",
  "radical",
  "esoteric",
  "nonconformist",
  "bohemian",
  "outré",
  "avant-garde",
  "left-field",
  "uncustomary",
  "unheard of",
  "conventional",
  "orthodox",
  "ordinary",
];
