export const definitions = [
  '"customers equate their name with quality"',
  '"that sum equates to half a million pounds today"',
  '"the level of prices will move to equate supply and demand"',
];
export const synonyms = [
  "identify",
  "compare",
  "bracket",
  "class",
  "associate",
  "connect",
  "pair",
  "link",
  "relate",
  "ally",
  "regard as the same as",
  "regard as identical to",
  "liken to",
  "think of together",
  "set side by side",
  "correspond",
  "amount",
  "equal",
  "be equivalent",
  "be the same as",
  "equalize",
  "balance",
  "square",
  "tally",
  "match",
  "even out/up/off",
  "level up/off",
  "make equal",
  "make even",
  "make level",
  "make equivalent",
  "make identical",
  "make the same",
  "make uniform",
];
