export const definitions = [
  '"my fiancé and I were childhood sweethearts"',
];
export const synonyms = [
  'sweetheart',
  'love',
  'lady love',
  'darling',
  'dearest',
  'lover',
  'girlfriend',
  'boyfriend',
  'young lady',
  'young man',
  'lady friend',
  'beau',
  'admirer',
  'worshipper',
  'inamorata',
  'inamorato',
  'fiancée',
  'betrothed',
  'partner',
  'significant other',
  'the apple of one\'s eye',
  'querida',
  'swain',
  'gallant',
  'paramour',
  'leman',
  'doxy',
  'loved one',
  'true love',
  'dear one',
  'woman friend',
  'man friend',
  'the love of one\'s life',
  'the object of \'s \'s affections',
];