export const definitions = [
  '"Web patrons are a notoriously fickle lot, bouncing from one site to another on a whim"',
  '"the weather is forever fickle"',
];
export const synonyms = [
  'capricious',
  'changeable',
  'variable',
  'volatile',
  'mercurial',
  'vacillating',
  'fitful',
  'irregular',
  'inconstant',
  'disloyal',
  'undependable',
  'unstable',
  'unsteady',
  'unfaithful',
  'faithless',
  'irresolute',
  'flighty',
  'giddy',
  'skittish',
  'erratic',
  'impulsive',
  'unpredictable',
  'random',
  'labile',
  'mutable',
  'constant',
  'stable',
];