export const definitions = [
  '"the audience had begun to fidget on their chairs"',
  '"she fidgets me with her never-ending spit and polish"',
  '"he disturbed other people with convulsive fidgets"',
  '"a marketing person full of nervous energy and fidgets"',
];
export const synonyms = [
  "wriggle",
  "squirm",
  "twitch",
  "jiggle",
  "writhe",
  "twist",
  "shuffle",
  "play",
  "fuss",
  "toy",
  "twiddle",
  "fool around",
  "trifle",
  "move restlessly",
  "be jittery",
  "be anxious",
  "be agitated",
  "sit still",
  "be at ease",
  "bundle of nerves",
  "restless person",
  "restlessness",
  "nervousness",
  "fidgetiness",
  "unease",
  "uneasiness",
];
