export const definitions = [
  '"a wheat field"',
  '"a field of corn"',
  '"a football field"',
  '"he is fast in the field and on the bases"',
  '"an ice field"',
  '"an oil field"',
  '"a field of battle"',
  '"many a bloody field was to be fought"',
  '"we talked to professionals in various fields"',
  '"the stars drift through this telescope\'s field of view"',
  '"he destroyed the rest of the field with a devastating injection of speed"',
  '"fifty white stars on a blue field"',
  '"the variation in the strength of the field"',
  '"he fielded the ball cleanly, but threw it down the right-field line"',
  '"a high school that traditionally fielded mediocre teams"',
  '"a radical political party that is beginning to field candidates in local elections"',
  '"no one had the power to field an army of any consequence"',
  '"she has fielded five calls from salespeople"',
];
export const synonyms = [
  'meadow',
  'pasture',
  'paddock',
  'green',
  'pen',
  'grassland',
  'pastureland',
  'sward',
  'park',
  'corral',
  'glebe',
  'lea',
  'mead',
  'greensward',
  'bawn',
  'ground',
  'playing field',
  'arena',
  'stadium',
  'pitch',
  'sports field',
  'recreation ground',
  'area',
  'sphere',
  'discipline',
  'province',
  'department',
  'domain',
  'sector',
  'line',
  'branch',
  'subject',
  'speciality',
  'specialty',
  'specialization',
  'specialism',
  'métier',
  'forte',
  'area of activity',
  'scope',
  'range',
  'sweep',
  'reach',
  'extent',
  'purview',
  'limits',
  'confines',
  'parameters',
  'bounds',
  'horizons',
  'competitors',
  'entrants',
  'competition',
  'runners',
  'applicants',
  'candidates',
  'possibles',
  'possibilities',
  'hopefuls',
  'catch',
  'stop',
  'retrieve',
  'return',
  'throw back',
  'send out',
  'play',
  'put up',
  'put in the team',
  'deploy',
  'position',
  'post',
  'station',
  'range',
  'dispose',
  'handle',
  'answer',
  'parry',
  'deflect',
  'evade',
  'sidestep',
  'avoid',
  'dodge',
  'fend off',
  'deal with',
  'cope with',
  'reply to',
  'respond to',
  'react to',
  'turn aside',
  'answer evasively',
];