export const definitions = [
  '"official census figures"',
  '"a figure of 30,000 deaths annually from snakebite"',
  '"the figure 7"',
  '"their market price runs into five figures"',
  '"a six-figure salary"',
  '"a figure of two thousand dollars"',
  '"she has no head for figures"',
  '"she had always been so proud of her figure"',
  '"a backpacked figure appeared in the distance"',
  '"starkly painted figures"',
  '"Williams became something of a cult figure"',
  '"a red ground with white and blue geometric figures"',
  '"figure 1 shows an ignition circuit"',
  '"the issue of nuclear policy figured prominently in the talks"',
  '"he figured largely in opposition to the bill"',
  '"the four characters who figure in Ridley\'s play"',
  '"for years, teachers had figured him for a dullard"',
  '"I figure that wearing a suit makes you look like a bank clerk"',
  '"well, she supposed that figured"',
  '"my accountant figured my tax wrong"',
  '"varieties of this Cape genus are figured from drawings made there"',
  '"the 11th-century silken dalmatic is figured with double-headed griffins"',
  '"a clock with a figured mahogany case"',
];
export const synonyms = [
  "statistic",
  "number",
  "integer",
  "quantity",
  "amount",
  "level",
  "total",
  "sum",
  "data",
  "information",
  "particulars",
  "digit",
  "numeral",
  "character",
  "cipher",
  "numerical symbol",
  "price",
  "cost",
  "amount",
  "quantity",
  "value",
  "valuation",
  "quotation",
  "quote",
  "rate",
  "total",
  "sum",
  "aggregate",
  "arithmetic",
  "mathematics",
  "sums",
  "calculations",
  "reckoning",
  "computation",
  "numbers",
  "statistics",
  "counting",
  "physique",
  "build",
  "frame",
  "body",
  "proportions",
  "torso",
  "shape",
  "form",
  "stature",
  "silhouette",
  "outline",
  "shape",
  "form",
  "profile",
  "shadow",
  "effigy",
  "likeness",
  "human representation",
  "image of a person",
  "person",
  "personage",
  "individual",
  "man",
  "woman",
  "character",
  "personality",
  "presence",
  "representative",
  "embodiment",
  "personification",
  "epitome",
  "symbol",
  "representation",
  "exemplification",
  "exemplar",
  "shape",
  "pattern",
  "design",
  "motif",
  "device",
  "depiction",
  "diagram",
  "illustration",
  "drawing",
  "picture",
  "plate",
  "graphic",
  "sketch",
  "chart",
  "plan",
  "map",
  "feature",
  "appear",
  "participate",
  "play a part",
  "star",
  "be featured/mentioned",
  "be referred to",
  "play a role",
  "be conspicuous",
  "have prominence",
  "have a place",
  "suppose",
  "think",
  "believe",
  "fancy",
  "consider",
  "expect",
  "take it",
  "suspect",
  "sense",
  "assume",
  "conclude",
  "presume",
  "trust",
  "deduce",
  "infer",
  "gather",
  "glean",
  "divine",
  "guess",
  "have a sneaking suspicion",
  "dare say",
  "take it as read",
  "be of the opinion",
  "make sense",
  "follow",
  "add up",
  "stand up",
  "hold up",
  "go without saying",
  "be understandable",
  "seem reasonable",
  "stand to reason",
  "be to be expected",
  "be logical",
  "ring true",
  "be convincing",
  "be likely/probable",
  "calculate",
  "work out",
  "total",
  "sum",
  "reckon",
  "compute",
  "enumerate",
  "determine",
  "evaluate",
  "quantify",
  "assess",
  "count",
  "add up",
  "put a figure on",
  "tally",
  "totalize",
  "gauge",
  "cast",
  "tot up",
];
