export const definitions = [
  '"a file of correspondence"',
  '"do you want to save this file?"',
  '"a file name"',
  '"the contract, when signed, is filed"',
  '"he still had the moment filed away in his memory"',
  '"criminal charges were filed against the firm"',
  '"the company had filed for bankruptcy"',
  '"it is possible to make the necessary notch with a file"',
  '"when I have nothing else to do, I file my nails"',
  '"the engine numbers were filed away"',
];
export const synonyms = [
  "folder",
  "portfolio",
  "binder",
  "box",
  "document case",
  "filing cabinet",
  "document",
  "text",
  "program",
  "batch of data",
  "categorize",
  "classify",
  "organize",
  "order",
  "arrange",
  "catalog",
  "tabulate",
  "index",
  "pigeonhole",
  "record",
  "enter",
  "store",
  "log",
  "archive",
  "put in place",
  "put in order",
  "put on record",
  "apply",
  "put in",
  "register",
  "sign up",
  "ask",
  "bring",
  "press",
  "lodge",
  "place",
  "lay",
  "prefer",
  "put forward",
  "present",
  "submit",
  "smooth",
  "buff",
  "rub",
  "rub down",
  "polish",
  "burnish",
  "furbish",
  "shape",
  "refine",
  "scrape",
  "abrade",
  "rasp",
  "sandpaper",
];
