export const definitions = [
  '"I filled the bottle with water"',
  '"the office was filled with reporters"',
  '"Elinor\'s eyes filled with tears"',
  '"road engineers planned to fill the hole with concrete"',
  '"he said the scheme would fill a gap in the market"',
  '"a pungent smell of garlic filled the air"',
  '"smoke filled the room"',
  '"the next few days were filled with meetings"',
  '"I had to find something to do to fill my time this summer"',
  '"his presence filled us with foreboding"',
  '"the board contacted him to say they had already filled the position"',
  '"he had filled the post in an acting capacity for some time"',
  '"she fills the role of the "good" child"',
  '"community land trusts are a way to fill the pressing need for housing"',
  '"she needed to fill a prescription"',
];
export const synonyms = [
  "fill up",
  "charge",
  "pack",
  "top up",
  "crowd",
  "throng",
  "jam",
  "overcrowd",
  "congest",
  "overfill",
  "stock",
  "load",
  "supply",
  "furnish",
  "provide",
  "replenish",
  "restock",
  "refill",
  "stop (up)",
  "plug",
  "seal",
  "caulk",
  "close",
  "choke",
  "obstruct",
  "occlude",
  "make/become full",
  "fill to the brim",
  "fill to overflowing",
  "load (up)",
  "pack (into)",
  "occupy all of",
  "press into",
  "squeeze into",
  "cram (into)",
  "block up",
  "bung up",
  "clog (up)",
  "dam up",
  "empty",
  "unblock",
  "open",
  "pervade",
  "permeate",
  "suffuse",
  "imbue",
  "penetrate",
  "infuse",
  "perfuse",
  "run through",
  "saturate",
  "impregnate",
  "spread throughout/through",
  "be diffused through",
  "diffuse through",
  "pass through",
  "extend throughout",
  "be disseminated through",
  "flow through",
  "occupy",
  "hold",
  "take up",
  "have",
  "be in",
  "carry out",
  "complete",
  "fulfill",
  "execute",
  "perform",
  "implement",
  "discharge",
  "bring about",
  "effectuate",
];
