export const definitions = [
  '"his first wife"',
  '"the first of five daughters"',
  '"her first day at school"',
  '"I didn\'t take the first bus"',
  '"the first house I came to"',
  '"many valuable drugs have been recognized first as poisons"',
  '"Do you mind if I take a shower first?"',
  '"she first picked up a guitar out of sheer boredom"',
  '"first, it is wrong that the victims should have no remedy"',
  "\"she longed to go abroad, but not at this man's expense—she'd die first!\"",
  '"we traveled by air, a first for both of us"',
  '"he stuck the car in first and revved"',
  '"he made it all the way home from first"',
  '"collectors of modern firsts"',
  '"the doctor\'s first duty is to respect this right"',
  '"I always put myself first"',
  '"football must come first"',
  '"he is the first to admit he was not the best of patients"',
  '"his first problem is where to live"',
  '"the first violins"',
  '"he took a first in Classics"',
  '"factory firsts, seconds, and discontinued styles"',
  '"it plunged nose first into the river"',
];
export const synonyms = [
  "earliest",
  "initial",
  "opening",
  "introductory",
  "original",
  "fundamental",
  "basic",
  "rudimentary",
  "primary",
  "beginning",
  "elemental",
  "underlying",
  "basal",
  "foundation",
  "key",
  "cardinal",
  "central",
  "chief",
  "vital",
  "essential",
  "last",
  "closing",
  "developed",
  "initial",
  "introductory",
  "initiatory",
  "launching",
  "opening",
  "maiden",
  "dedicatory",
  "final",
  "closing",
  "first and foremost",
  "firstly",
  "in the first place",
  "without further ado",
  "now",
  "before anything else",
  "last",
  "sooner",
  "rather",
  "in preference",
  "more willingly",
  "novelty",
  "new experience",
  "first experience",
  "first occurrence",
  "unusual event",
  "foremost",
  "principal",
  "highest",
  "greatest",
  "paramount",
  "top",
  "topmost",
  "utmost",
  "uppermost",
  "prime",
  "chief",
  "leading",
  "main",
  "major",
  "preeminent",
  "overriding",
  "outstanding",
  "supreme",
  "premier",
  "predominant",
  "prevailing",
  "vital",
  "key",
  "essential",
  "crucial",
  "central",
  "core",
  "focal",
  "pivotal",
  "dominant",
  "ruling",
  "head",
  "best",
  "superlative",
  "winning",
  "champion",
  "most important",
  "of greatest importance",
  "of prime importance",
  "winner's",
  "last",
];
