export const definitions = [
  '"the blouse has a fitted bodice"',
  '"navy blue fitted sheets"',
  '"a fitted kitchen"',
  '"a pistol fitted with a match-grade barrel"',
  '"physicists may not be fitted for involvement in industrial processes"',
  '"those jeans still fit me"',
  '"the shoes fit better after being stretched"',
  '"she was about to be fitted for her costume"',
  '"Angela says we can all fit in her car"',
  '"they fitted smoke alarms to their home"',
  '"most tools can be fitted with a new handle"',
  '"it took a while to figure out how the confounded things fit together"',
  '"many physicists tried to fit together the various pieces of the puzzle"',
  '"an MS fits the student for a professional career"',
];
export const synonyms = [
  'shaped',
  'contoured',
  'contour',
  'fitting tightly/well',
  'suited',
  'right',
  'suitable',
  'ideal',
  'equipped',
  'fit',
  'appropriate',
  'well suited',
  'unsuited',
  'be the right/correct size (for)',
  'be big/small enough (for)',
  'be the right shape (for)',
  'be too big/small (for)',
  'lay',
  'position',
  'place',
  'fix',
  'insert',
  'arrange',
  'adjust',
  'shape',
  'put in place/position',
  'equip',
  'provide',
  'supply',
  'fit out',
  'rig out',
  'furnish',
  'outfit',
  'endow',
  'join',
  'connect',
  'put together',
  'attach',
  'unite',
  'link',
  'splice',
  'fuse',
  'weld',
  'piece together',
  'qualify',
  'prepare',
  'make ready',
  'prime',
  'condition',
  'train',
  'coach',
  'groom',
  'tailor',
  'make suitable',
];