export const definitions = [
  '"17,000 men had been mustered on Haldon Hill"',
  '"the cavalrymen mustered beside the other regiments"',
  '"reporters mustered outside her house"',
  '"the city council was unable to muster enough votes to pass the measure"',
  '"he replied with as much dignity as he could muster"',
  '"I finally mustered up the courage to call them"',
  '"mustering his strength, he made it across the finish line"',
  '"he attended the musters, which were called to train all able-bodied men"',
  '"a meeting was held to fix the times and places of muster"',
  '"the sound was like the cry of a muster of peacocks"',
];
export const synonyms = [
  "assemble",
  "marshal",
  "mobilize",
  "rally",
  "round up",
  "raise",
  "summon",
  "gather",
  "mass",
  "collect",
  "convene",
  "call up",
  "recruit",
  "conscript",
  "draft",
  "convoke",
  "levy",
  "bring together",
  "call together",
  "gather together",
  "call to arms",
  "disperse",
  "gather",
  "assemble",
  "collect",
  "mass",
  "amass",
  "draw up",
  "line up",
  "align",
  "array",
  "organize",
  "group",
  "arrange",
  "deploy",
  "position",
  "order",
  "dispose",
  "rank",
  "mobilize",
  "rally",
  "round up",
  "triage",
  "gather together",
  "call together",
  "set/put in order",
  "set/put into position",
  "disperse",
  "scatter",
  "congregate",
  "assemble",
  "meet",
  "convene",
  "mass",
  "rally",
  "foregather",
  "gather together",
  "come together",
  "collect together",
  "cluster together",
  "flock together",
  "summon",
  "screw up",
  "call up",
  "rally",
  "summon up",
  "gather together",
  "roll call",
  "assembly",
  "rally",
  "meeting",
  "roundup",
  "convocation",
  "mobilization",
  "gathering",
  "assemblage",
  "congregation",
  "convention",
  "parade",
  "review",
];
