export const definitions = [
  '"a mutiny by those manning the weapons could trigger a global war"',
  '"mutiny at sea"',
  '"thousands of the soldiers mutinied over the non-payment of wages"',
];
export const synonyms = [
  "insurrection",
  "rebellion",
  "revolt",
  "riot",
  "revolution",
  "uprising",
  "rising",
  "coup",
  "coup d'état",
  "putsch",
  "protest",
  "strike",
  "insurgence",
  "insurgency",
  "subversion",
  "sedition",
  "anarchy",
  "disorder",
  "insubordination",
  "disobedience",
  "resistance",
  "defiance",
  "rebel",
  "revolt",
  "riot",
  "protest",
  "strike",
  "rise up",
  "take part in an insurrection/uprising",
  "resist/oppose authority",
  "disobey/defy authority",
  "refuse to obey orders",
  "be insubordinate",
  "go on strike",
];
