export const definitions = [
  '"a partnership based on mutual respect and understanding"',
  '"my father hated him from the start and the feeling was mutual"',
  '"they were mutual beneficiaries of the settlement"',
  '"we were introduced by a mutual friend"',
  '"the world\'s oldest mutual insurance company"',
];
export const synonyms = [
  "reciprocal",
  "reciprocated",
  "requited",
  "returned",
  "give-and-take",
  "interchangeable",
  "interactive",
  "complementary",
  "correlative",
  "common",
  "joint",
  "shared",
  "reciprocal",
  "reciprocated",
  "requited",
  "returned",
  "give-and-take",
  "interchangeable",
  "interactive",
  "complementary",
  "correlative",
  "common",
  "joint",
  "shared",
];
