export const definitions = [
  '"how long must I bide here to wait for the answer?"',
];
export const synonyms = [
  "stay behind",
  "stay put",
  "wait",
  "linger",
  "stick",
  "continue",
  "hold on",
  "hang on",
  "lodge",
  "rest",
  "delay",
  "pause",
  "stop",
  "tarry",
  "visit",
  "put up",
  "stop off",
  "stop over",
  "room",
  "board",
  "take up residence",
  "settle",
  "holiday",
  "vacation",
  "sojourn",
  "abide",
  "remain (behind)",
  "wait around",
  "be left",
  "spend some time",
  "break one's journey",
  "have rooms",
  "be housed",
  "be accommodated",
  "be quartered",
  "be billeted",
  "take a room",
  "leave",
];
