export const definitions = [
  '"an apparently benevolent elderly gentleman bilked me of twenty dollars"',
  '"some businesses bilk thousands of dollars from unsuspecting elderly consumers"',
  '"I ducked into the pantry, bilking Edward for the third time this week"',
];
export const synonyms = [
  "swindle",
  "defraud",
  "deceive",
  "trick",
  "dupe",
  "hoodwink",
  "double-cross",
  "gull",
  "shortchange",
  "exploit",
  "take advantage of",
  "victimize",
  "cozen",
  "chicane",
  "sell",
  "illude",
  "mulct",
  "evade",
  "avoid",
  "dodge",
  "flee",
  "lose",
  "duck",
  "shake off",
  "circumvent",
  "get away from",
  "escape (from)",
  "run (away) from",
  "give the slip to",
  "slip away from",
  "throw off the scent",
  "be caught by",
];
