export const definitions = [
  '"some see the whole weekend as a chance to binge"',
  '"some dieters say they cannot help binging on chocolate"',
  '"secret binging and vomiting"',
  '"I\'ve binged seasons one through seven in the past week"',
  '"every so often he might binge a Netflix show"',
  '"I binged on all six episodes in two days"',
  '"I have to get back to binging on the four seasons I’ve missed"',
];
export const synonyms = [
  "binge-drink",
  "overindulge",
  "bar-hop",
  "revel",
  "celebrate",
  "feast",
  "roister",
  "frolic",
  "romp",
  "wassail",
  "drink and make merry",
  "go on a drinking bout",
  "go on a binge",
  "drink heavily/freely",
  "go on a pub crawl",
  "go on a spree",
  "have a party",
  "enjoy oneself",
  "have a good time",
  "eat, drink, and be merry",
];
