export const definitions = [
  '"a landscape of farmland bisected by long straight roads"',
];
export const synonyms = [
  'divide',
  'disunite',
  'separate',
  'sever',
  'partition',
  'cleave',
  'rend',
  'sunder',
  'rive',
  'dichotomize',
  'factionalize',
  'tear asunder',
  'unite',
  'unify',
  'halve',
  'cleave',
  'cross',
  'intersect',
  'cut in half',
  'divide/cut/split in two',
  'split down the middle',
  'separate into two',
];