export const definitions = [
  '"he bit off a piece of cheese"',
  '"Rosa bit into a cupcake"',
  '"babies learn to bite and chew about halfway through their first year"',
  '"he was chased and bitten by a dog"',
  '"she had bitten, scratched, and kicked her assailant"',
  '"the couple admit the dog bites if she feels threatened"',
  '"she was bitten by an adder"',
  '"I marvel at how easily and eagerly a chub will bite"',
  '"a hundred or so retailers should bite"',
  '"the brake pads don\'t bite until they\'re warmed up"',
  '"once on the wet grass, my boots failed to bite"',
  '"the handcuffs bit into his wrists"',
  '"chemicals have bitten deep into the stone"',
  '"the cuts in art education were starting to bite"',
  '"Cheryl\'s betrayal had bitten deep"',
  '"it bites that your mom won\'t let you go"',
];
export const synonyms = [
  'chew',
  'munch',
  'crunch',
  'champ',
  'masticate',
  'eat',
  'sink one\'s teeth into',
  'tear at',
  'nibble at',
  'gnaw at',
  'puncture',
  'prick',
  'pierce',
  'sting',
  'wound',
  'accept',
  'go for it',
  'agree',
  'respond',
  'rise to the bait',
  'be lured',
  'be enticed',
  'be tempted',
  'be allured',
  'take the bait',
  'grip',
  'hold',
  'get a purchase',
  'corrode',
  'eat into',
  'eat away at',
  'wear away',
  'burn (into)',
  'etch',
  'erode',
  'dissolve',
  'destroy',
  'consume',
  'take effect',
  'work',
  'function',
  'act',
  'take hold',
  'succeed',
  'work out',
  'have an effect',
  'be effective',
  'be efficacious',
  'have results',
  'be successful',
  'go as planned',
  'have the desired effect/result',
];
