export const definitions = [];
export const synonyms = [
  "grounds",
  "ground",
  "fields",
  "property",
  "acres",
  "acreage",
  "estate",
  "lands",
  "real property",
  "real estate",
  "landholding",
  "holding",
  "countryside",
  "green belt",
  "demesne",
  "open space",
  "open area",
  "unbuilt land",
  "rural area",
  "green area",
];
