export const definitions = [
  '"sleeping sickness and related diseases"',
  '"income-related benefits"',
  '"the study examines social change within the city and relates it to wider developments in the country as a whole"',
  '"high unemployment is related to high crime rates"',
  '"he was related to my mother"',
  '"people who are related"',
  '"the new legislation related to corporate activities"',
  '"kids related to him because he was so anti-establishment"',
  '"various versions of the chilling story have been related by the locals"',
];
export const synonyms = [
  'connected',
  'interconnected',
  'associated',
  'linked',
  'coupled',
  'correlated',
  'allied',
  'affiliated',
  'accompanying',
  'concomitant',
  'corresponding',
  'analogous',
  'kindred',
  'parallel',
  'comparable',
  'equivalent',
  'homologous',
  'incidental',
  'kin',
  'akin',
  'agnate',
  'consanguineous',
  'cognate',
  'of the same family',
  'of the same blood',
  'with a common ancestor/forebear',
  'unconnected',
  'separate',
  'unrelated',
  'connect (with)',
  'associate (with)',
  'link (with)',
  'correlate (with)',
  'ally (with)',
  'couple (with)',
  'bracket (with)',
  'bring together',
  'find/establish a connection between',
  'find/establish a relationship between',
  'find/establish a link between',
  'find/establish an association between',
  'find/establish a correspondence between',
  'kin',
  'akin',
  'kindred',
  'connected',
  'agnate',
  'consanguineous',
  'cognate',
  'of the same family',
  'of the same blood',
  'with a common ancestor/forebear',
  'unrelated',
  'concern',
  'have to do with',
  'bear on',
  'affect',
  'involve',
  'cover',
  'touch',
  'regard',
  'apply to',
  'be relevant to',
  'have relevance to',
  'refer to',
  'have reference to',
  'belong to',
  'pertain to',
  'be pertinent to',
  'have a bearing on',
  'appertain to',
  'understand',
  'have a rapport with',
  'get on (well) with',
  'respond to',
  'sympathize with',
  'feel sympathy with',
  'feel for',
  'identify with',
  'empathize with',
  'connect with',
  'speak the same language as',
  'be in tune with',
  'be on the same wavelength as',
  'tell',
  'recount',
  'narrate',
  'describe',
  'portray',
  'depict',
  'paint',
  'unfold',
  'set forth',
  'present',
  'report',
  'chronicle',
  'outline',
  'delineate',
  'retail',
  'recite',
  'repeat',
  'rehearse',
  'relay',
  'convey',
  'communicate',
  'impart',
  'spin',
  'detail',
  'enumerate',
  'list',
  'specify',
  'itemize',
  'cite',
  'particularize',
  'catalog',
  'give an account of',
];