export const definitions = [
  '"she had rebuked him for drinking too much"',
  '"the judge publicly rebuked the jury"',
  '"he hadn\'t meant it as a rebuke, but Neil flinched"',
];
export const synonyms = [
  "reprimand",
  "reproach",
  "scold",
  "admonish",
  "reprove",
  "chastise",
  "chide",
  "upbraid",
  "berate",
  "pull up",
  "castigate",
  "lambaste",
  "read someone the Riot Act",
  "give someone a piece of one's mind",
  "criticize",
  "censure",
  "call down",
  "rate",
  "trim",
  "reprehend",
  "objurgate",
  "remonstrate with",
  "take to task",
  "haul over the coals",
  "give someone a rating",
  "praise",
  "compliment",
  "commend",
  "reprimand",
  "reproach",
  "reproof",
  "scolding",
  "admonishment",
  "admonition",
  "remonstration",
  "lecture",
  "upbraiding",
  "castigation",
  "lambasting",
  "criticism",
  "censure",
  "rating",
  "reproval",
  "praise",
  "compliment",
  "commendation",
];
