export const definitions = [
  '"his recent visit to Britain"',
  '"a recent edition of the newspaper"',
];
export const synonyms = [
  "new",
  "late",
  "current",
  "fresh",
  "modern",
  "contemporary",
  "present-day",
  "up to date",
  "up to the minute",
  "latter-day",
  "latter",
  "neoteric",
  "immediate",
  "the latest",
  "not long past",
  "occurring/appearing recently",
  "just gone",
  "old",
  "former",
];
