export const definitions = [
  '"we provided our own entertainment by singing and reciting poetry"',
  '"she recited the dates and names of kings and queens"',
];
export const synonyms = [
  'declaim',
  'quote',
  'speak',
  'deliver',
  'render',
  'intone',
  'chant',
  'spout',
  'parrot',
  'daven',
  'cantillate',
  'intonate',
  'perform',
  'repeat from memory',
  'say aloud',
  'read aloud',
  'say parrot-fashion',
  'bespout',
  'give a recitation',
  'say a poem',
  'enumerate',
  'list',
  'detail',
  'itemize',
  'reel off',
  'rattle off',
  'recount',
  'relate',
  'describe',
  'narrate',
  'run through',
  'recapitulate',
  'repeat',
  'rehearse',
  'specify',
  'particularize',
  'spell out',
  'give an account of',
];