export const definitions = [
  '"you should keep a written record"',
  '"identification was made through dental records"',
  '"a record of meter readings"',
  '"the safety record at the airport"',
  '"the team preserved its unbeaten home record"',
  '"he held the world record for over a decade"',
  '"record profits"',
  '"he managed to beat the record"',
  '"I\'m listening to records in my room"',
  '"my favorite record"',
  '"a record company"',
  '"they were asked to keep a diary and record everything they ate or drank"',
  '"the coroner recorded a verdict of accidental death"',
  '"the temperature was the lowest recorded since 1926"',
  '"they recorded their first win of the season"',
  '"they were recording a guitar recital"',
  '"they go into the studio next week to record their debut album"',
];
export const synonyms = [
  "account(s)",
  "document(s)",
  "documentation",
  "data",
  "file(s)",
  "dossier(s)",
  "information",
  "evidence",
  "report(s)",
  "archive(s)",
  "chronicle(s)",
  "note(s)",
  "minutes",
  "transactions",
  "proceedings",
  "transcript(s)",
  "certificate(s)",
  "deed(s)",
  "instrument(s)",
  "diary",
  "journal",
  "memoir",
  "register",
  "log",
  "logbook",
  "yearbook",
  "almanac",
  "inventory",
  "list",
  "catalog",
  "case history",
  "case study",
  "casebook",
  "procès-verbal",
  "act(s)",
  "muniment(s)",
  "annal(s)",
  "track record",
  "history",
  "past",
  "life history",
  "background",
  "reputation",
  "curriculum vitae",
  "previous conduct/performance",
  "previous achievements/accomplishments",
  "career to date",
  "criminal record",
  "previous",
  "police record",
  "list of offenses",
  "list of previous convictions",
  "history of crime",
  "crime sheet",
  "personal best",
  "best performance",
  "highest achievement",
  "star performance",
  "best time",
  "fastest time",
  "furthest distance",
  "world record",
  "album",
  "vinyl",
  "tape",
  "cassette",
  "disk",
  "compact disk",
  "CD",
  "recording",
  "release",
  "gramophone record",
  "LP",
  "long-player",
  "single",
  "forty-five",
  "twelve-inch (single)",
  "seventy-eight",
  "78",
  "phonograph record",
  "EP (extended-play)",
  "black disc",
  "write down",
  "set down",
  "put down",
  "take down",
  "note",
  "document",
  "post",
  "enter",
  "minute",
  "register",
  "chronicle",
  "file",
  "chart",
  "docket",
  "log",
  "inscribe",
  "transcribe",
  "list",
  "catalog",
  "diarize",
  "put in writing",
  "make a note of",
  "jot down",
  "put down on paper",
  "commit to paper",
  "put on record",
  "put on file",
  "make an inventory of",
  "state",
  "declare",
  "announce",
  "communicate",
  "mention",
  "say",
  "reveal",
  "divulge",
  "disclose",
  "register",
  "admit",
  "make (it) known",
  "put it on record",
  "indicate",
  "register",
  "read",
  "show",
  "display",
  "achieve",
  "accomplish",
  "gain",
  "earn",
  "chalk up",
  "turn in",
  "notch up",
  "tape",
  "tape-record",
  "videotape",
  "video",
  "audiotape",
  "make",
  "produce",
  "cut",
  "make a record/recording of",
  "video-record",
  "telerecord",
  "put on disk/tape",
];
