export const definitions = [];
export const synonyms = [
  "minister",
  "priest",
  "parson",
  "minister of religion",
  "clergyman",
  "clergywoman",
  "cleric",
  "churchman",
  "churchwoman",
  "ecclesiastic",
  "pastor",
  "father",
  "curate",
  "chaplain",
  "curé",
  "presbyter",
  "preacher",
  "evangelist",
  "divine",
  "dominie",
  "man/woman of the cloth",
  "man/woman of god",
  "lay preacher",
  "kirkman",
  "head",
  "chief",
  "director",
  "leader",
  "governor",
  "principal",
  "master",
  "chancellor",
  "vice chancellor",
  "dean",
  "warden",
  "provost",
  "captain",
  "figurehead",
];
