export const definitions = [
  '"when the sun\'s rays hit the Earth a lot of the heat is reflected back into space"',
  '"his eyes gleamed in the reflected light"',
  '"he could see himself reflected in Keith\'s mirrored glasses"',
  '"schools should reflect cultural differences"',
  '"stocks are priced at a level that reflects a company\'s prospects"',
  '"he reflected with sadness on the unhappiness of his marriage"',
  '"Charles reflected that maybe there was hope for the family after all"',
  '"the clergy were strictly charged not to reflect on the Catholic religion in their discourses"',
  '"the incident reflects badly on the operating practices of the airlines"',
  '"I want every decision I make to reflect well on me"',
  '"that is quite a serious accusation, which reflects on all 120 members of Parliament"',
  '"the main contract is progressing well, which reflects great credit on those involved"',
];
export const synonyms = [
  "throw back",
  "give back",
  "return",
  "mirror",
  "send back",
  "cast back",
  "bounce back",
  "shine back",
  "absorb",
  "throw back",
  "give back",
  "return",
  "mirror",
  "send back",
  "cast back",
  "bounce back",
  "shine back",
  "absorb",
  "indicate",
  "show",
  "display",
  "demonstrate",
  "register",
  "reveal",
  "betray",
  "evince",
  "disclose",
  "exhibit",
  "manifest",
  "express",
  "bespeak",
  "communicate",
  "bear out",
  "attest",
  "prove",
  "evidence",
  "be evidence of",
  "result from",
  "think about",
  "consider",
  "review",
  "contemplate",
  "study",
  "dwell on",
  "chew over",
  "weigh up",
  "revolve",
  "cerebrate",
  "give thought to",
  "give consideration to",
  "mull over",
  "cogitate about/on",
  "meditate on",
  "muse on",
  "deliberate about/on",
  "ruminate about/on/over",
  "brood on/over",
  "agonize over",
  "worry about",
  "puzzle over",
  "speculate about",
  "turn over in one's mind",
  "be in a brown study",
  "pore on",
];
