export const definitions = [
  '"an opportunity to reform and restructure an antiquated schooling model"',
  '"the state has a duty to reform criminals"',
  '"it was only when his drunken behavior led to blows that he started to reform"',
  '"the reform of the divorce laws"',
  '"economic reforms"',
  '"a Reform rabbi"',
];
export const synonyms = [
  "improve",
  "better",
  "ameliorate",
  "refine",
  "mend",
  "rectify",
  "correct",
  "rehabilitate",
  "alter",
  "change",
  "adjust",
  "adapt",
  "amend",
  "revise",
  "recast",
  "reshape",
  "refashion",
  "redesign",
  "restyle",
  "revamp",
  "renovate",
  "rework",
  "redo",
  "remake",
  "rebuild",
  "reconstruct",
  "remodel",
  "make over",
  "remold",
  "reorganize",
  "revolutionize",
  "reorient",
  "reorientate",
  "vary",
  "transform",
  "convert",
  "customize",
  "tailor",
  "permute",
  "permutate",
  "make better",
  "make alterations to",
  "make adjustments to",
  "preserve",
  "maintain",
  "mend one's ways",
  "turn over a new leaf",
  "improve",
  "go straight",
  "change for the better",
  "change completely",
  "make a fresh start",
  "become a new person",
  "reconstruct oneself",
  "get back on the straight and narrow",
  "worsen",
  "improvement",
  "betterment",
  "amelioration",
  "refinement",
  "rectification",
  "correction",
  "rehabilitation",
  "alteration",
  "change",
  "adjustment",
  "adaptation",
  "amendment",
  "revision",
  "recasting",
  "reshaping",
  "refashioning",
  "redesigning",
  "restyling",
  "revamp",
  "revamping",
  "renovation",
  "reworking",
  "redoing",
  "remake",
  "rebuilding",
  "reconstruction",
  "remodeling",
  "makeover",
  "remolding",
  "reorganizing",
  "reorganization",
  "reorienting",
  "reorientation",
  "transformation",
  "conversion",
  "customizing",
  "tailoring",
];
