export const definitions = [
  '"these claims have not been convincingly refuted"',
  '"his voice challenging his audience to rise and refute him"',
  '"a spokesman totally refuted the allegation of bias"',
];
export const synonyms = [
  "disprove",
  "rebut",
  "confute",
  "give the lie to",
  "demolish",
  "explode",
  "debunk",
  "discredit",
  "invalidate",
  "controvert",
  "negative",
  "prove wrong/false",
  "show/prove to be wrong/false",
  "drive a coach and horses through",
  "confirm",
  "deny",
  "reject",
  "repudiate",
  "rebut",
  "contradict",
  "gainsay",
  "declare to be untrue",
  "accept",
];
