export const definitions = [
  '"she regarded Omaha as her base"',
  '"he was highly regarded by senators of both parties"',
  '"Professor Ryker regarded him with a faint smile"',
  '"if these things regarded only myself, I could stand it with composure"',
  '"he talked very wisely, but I regarded him not"',
  '"the court must have regard to the principle of welfare"',
  '"she rescued him without regard for herself"',
  '"she had a particular regard for Eliot"',
  '"he shifted uneasily before their clear regard"',
  '"give her my regards"',
  '"Warm regards, Helen"',
];
export const synonyms = [
  "consider",
  "look on",
  "view",
  "see",
  "hold",
  "think",
  "think of",
  "contemplate",
  "count",
  "judge",
  "deem",
  "estimate",
  "evaluate",
  "interpret",
  "appraise",
  "assess",
  "make of",
  "find",
  "account",
  "reckon",
  "treat",
  "adjudge",
  "value",
  "rate",
  "gauge",
  "sum up",
  "weigh up",
  "put down as",
  "take for",
  "size up",
  "contemplate",
  "eye",
  "watch",
  "observe",
  "view",
  "survey",
  "scan",
  "examine",
  "inspect",
  "study",
  "scrutinize",
  "behold",
  "look at",
  "gaze at",
  "stare at",
  "concern",
  "have to do with",
  "bear on",
  "affect",
  "involve",
  "cover",
  "touch",
  "apply to",
  "be relevant to",
  "have relevance to",
  "refer to",
  "have reference to",
  "belong to",
  "pertain to",
  "be pertinent to",
  "have a bearing on",
  "appertain to",
  "heed",
  "mind",
  "take into consideration",
  "pay heed to",
  "pay attention to",
  "attend to",
  "listen to",
  "take notice of",
  "take into account",
  "consideration",
  "care",
  "concern",
  "sympathy",
  "thought",
  "mind",
  "notice",
  "heed",
  "attention",
  "interest",
  "esteem",
  "respect",
  "acclaim",
  "admiration",
  "approval",
  "approbation",
  "popularity",
  "appreciation",
  "estimation",
  "favor",
  "deference",
  "reverence",
  "veneration",
  "liking",
  "affection",
  "love",
  "high opinion",
  "look",
  "gaze",
  "stare",
  "observation",
  "contemplation",
  "examination",
  "inspection",
  "study",
  "scrutiny",
  "fixed look",
  "intent look",
  "best wishes",
  "greetings",
  "felicitations",
  "salutations",
  "respects",
  "compliments",
  "best",
  "love",
  "remembrances",
  "devoirs",
  "good wishes",
  "kind/kindest regards",
];
