export const definitions = [
  '"she received her prize from the manager"',
  '"most businesses will receive a tax cut"',
  '"he failed to find a magistrate to receive his oath"',
  '"a man convicted of receiving stolen property"',
  '"the event received wide press coverage"',
  '"she received only cuts and bruises"',
  '"he received an eight-year prison sentence"',
  '"her first poem was not well received"',
  '"the landward slopes receive the full force of the wind"',
  '"the rulings have received widespread acceptance"',
  '"representatives of the club will be received by the Mayor"',
  '"she was not allowed to receive visitors"',
  '"hundreds of converts were received into the Church"',
  '"the impression she received was one of unhurried leisure"',
  '"Turkish television began to be received in Tashkent"',
  '"the basin that receives your blood"',
  '"three lines are reserved for special vehicles, and the remaining lines receive the general rolling stock"',
  '"he received Communion and left"',
];
export const synonyms = [
  'collect',
  'accept',
  'get',
  'obtain',
  'gain',
  'acquire',
  'secure',
  'come by',
  'pick up',
  'take',
  'derive',
  'win',
  'earn',
  'gross',
  'net',
  'accrue',
  'inherit',
  'come into',
  'be given',
  'be presented with',
  'be awarded',
  'have conferred on one',
  'be provided with',
  'be paid',
  'give',
  'present',
  'accept',
  'hear',
  'discover',
  'learn',
  'gather',
  'get wind of',
  'be sent',
  'be in receipt of',
  'accept delivery of',
  'take into one\'s possession',
  'be told',
  'be informed of',
  'be notified of',
  'be made aware of',
  'find out (about)',
  'send',
  'experience',
  'sustain',
  'undergo',
  'meet with',
  'encounter',
  'go through',
  'come in for',
  'suffer',
  'bear',
  'endure',
  'be subjected to',
  'hear',
  'take',
  'meet',
  'greet',
  'listen to',
  'respond to',
  'react to',
  'get',
  'obtain',
  'acquire',
  'procure',
  'come by',
  'be given',
  'be sent',
  'take receipt of',
  'send',
  'give',
  'hear',
  'take',
  'meet',
  'greet',
  'listen to',
  'respond to',
  'react to',
  'greet',
  'welcome',
  'admit',
  'say hello to',
  'show in',
  'usher in',
  'let in',
  'entertain',
  'be at home to',
  'accommodate',
  'lodge',
  'take in',
  'put up',
  'house',
  'billet',
  'quarter',
  'harbor',
  'shelter',
  'keep',
  'feed',
  'cater for',
  'provide shelter for',
  'give a bed to',
  'give someone a roof over their head',
  'make room for',
  'give accommodation to',
  'cook for',
];