export const definitions = [
  '"she immediately regretted her words"',
  '"I regretted that he did not see you"',
  '"any inconvenience to readers is regretted"',
  '"we regret that no tickets may be exchanged"',
  '"my home, when shall I cease to regret you!"',
  '"she expressed her regret at Virginia\'s death"',
  '"he had to decline, to his regret"',
  '"she had few regrets in leaving the house"',
  '"please give your grandmother my regrets"',
];
export const synonyms = [
  "rue",
  "mourn",
  "lament",
  "deplore",
  "be sorry about",
  "feel contrite about",
  "feel apologetic about",
  "feel remorse about/for",
  "be remorseful about",
  "repent (of)",
  "feel repentant about",
  "be regretful at/about",
  "have a conscience about",
  "blame oneself for",
  "grieve for/over",
  "feel grief at",
  "weep over",
  "sigh over",
  "fret about",
  "pine over",
  "feel sad about",
  "feel sorrow at",
  "sorrow for",
  "be upset/disappointed about",
  "applaud",
  "welcome",
  "sadness",
  "sorrow",
  "disappointment",
  "dismay",
  "unhappiness",
  "dejection",
  "lamentation",
  "grief",
  "mourning",
  "mournfulness",
  "happiness",
  "gladness",
  "apology",
  "apologies",
  "refusal",
  "nonacceptance",
  "expression of regret",
];
