export const definitions = [
  '"union negotiators rejected a 1.5 percent pay increase"',
  '"an application to hold a pop concert at the club was rejected"',
  '"she didn\'t want him to feel he had been rejected after his sister was born"',
  '"his body could begin to reject the implanted heart"',
  '"some of the team\'s rejects have gone on to prove themselves in championships"',
];
export const synonyms = [
  "turn down",
  "refuse",
  "decline",
  "dismiss",
  "spurn",
  "negative",
  "say no to",
  "accept",
  "turn down",
  "refuse",
  "decline",
  "dismiss",
  "spurn",
  "negative",
  "say no to",
  "accept",
  "rebuff",
  "spurn",
  "repudiate",
  "cut off",
  "cast off",
  "cast aside",
  "discard",
  "jettison",
  "abandon",
  "desert",
  "turn one's back on",
  "wash 's 's hands of",
  "cast out",
  "shut out",
  "exclude",
  "shun",
  "cold-shoulder",
  "ostracize",
  "blackball",
  "blacklist",
  "avoid",
  "ignore",
  "snub",
  "disfellowship",
  "cut",
  "excommunicate",
  "forsake",
  "have nothing (more) to do with",
  "give someone the cold shoulder",
  "give a wide berth to",
  "cut dead",
  "keep at arm's length",
  "leave out in the cold",
  "send to Coventry",
  "welcome",
  "failure",
  "loser",
  "incompetent",
  "flotsam",
];
