export const definitions = [
  '"Ian\'s smile was replaced by a frown"',
  '"the light bulb needs replacing"',
  '"the government dismissed 3,000 of its customs inspectors, replacing them with new recruits"',
  '"he drained his glass and replaced it on the bar"',
];
export const synonyms = [
  "substitute",
  "exchange",
  "change",
  "give in place of",
  "give as a replacement for",
  "give in return/exchange for",
  "swap for",
  "take the place of",
  "succeed",
  "supersede",
  "come after",
  "supplant",
  "oust",
  "act for",
  "cover for",
  "relieve",
  "understudy",
  "step into the breach",
  "hold the fort",
  "be a replacement for",
  "take over from",
  "follow after",
  "stand in for",
  "substitute for",
  "act as stand-in for",
  "deputize for",
  "stand in lieu of",
  "fill in for",
  "act as locum for",
  "put back",
  "return",
  "restore",
  "return to its place",
  "remove",
];
