export const definitions = [
  '"a cloister is all that remains of the monastery"',
  '"her husband remained at the beach condo"',
  '"he had remained alert the whole time"',
  '"several years remain in the transition period"',
];
export const synonyms = [
  'endure',
  'last',
  'abide',
  'go on',
  'carry on',
  'persist',
  'hang in the air',
  'stand',
  'hold out',
  'prevail',
  'survive',
  'live on',
  'residual',
  'surviving',
  'left',
  'left over',
  'unused',
  'extra',
  'surplus',
  'spare',
  'superfluous',
  'excess',
  'in addition',
  'lasting',
  'enduring',
  'continuing',
  'persisting',
  'lingering',
  'abiding',
  'long-lived',
  'extant',
  'living',
  'lifelong',
  'long-term',
  'perennial',
  'continue to exist',
  'stay around',
  'be extant',
  'in excess',
  '(still) existing',
  'in existence',
  'short-lived',
  'cease to exist',
  'stay',
  'stay behind',
  'stay put',
  'wait',
  'linger',
  'hold on',
  'hang on',
  'rest',
  'stop',
  'sojourn',
  'bide',
  'tarry',
  'wait around',
  'be left',
  'go',
  'depart',
  'leave',
  'stay',
  'keep',
  'continue to be',
  'persist in being',
  'carry on being',
  'go on being',
  'unsettled',
  'outstanding',
  'unresolved',
  'unfinished',
  'incomplete',
  'undone',
  'unpaid',
  'be left',
  'be left over',
  'be still available',
  'be unused',
  'have not yet passed',
  'have not yet expired',
  'to be done',
  'not done',
  'unattended to',
];