export const definitions = [
  '"she resented the fact that I had children"',
  '"he forgot to put the time of the party on the invitations and had to resend them"',
];
export const synonyms = [
  "begrudge",
  "grudge",
  "dislike",
  "take exception to",
  "envy",
  "take something ill",
  "feel aggrieved at/about",
  "feel bitter about",
  "be annoyed at/about",
  "be angry at/about",
  "be resentful of",
  "be displeased at/about",
  "object to",
  "be offended by",
  "take amiss",
  "take offense at",
  "take umbrage at",
  "feel envious of",
  "feel jealous of",
  "bear/harbor a grudge about",
  "like",
  "welcome",
  "be pleased by",
];
