export const definitions = [
  '"a day later normal service was resumed"',
  '"hostilities had ceased and normal life had resumed"',
  '"he sipped at the glass of water on the lectern and then resumed"',
  '""As for Joe," the major resumed, "I can\'t promise anything.""',
  '"the judge resumed his seat"',
  '"I gave him a quick résumé of events"',
];
export const synonyms = [
  "restart",
  "recommence",
  "start again",
  "reopen",
  "renew",
  "reinstitute",
  "reoccupy",
  "begin again",
  "take up again",
  "return to",
  "continue with",
  "carry on with",
  "proceed with",
  "go on with",
  "push on with",
  "pick up where one left off",
  "come back to",
  "occupy again",
  "suspend",
  "abandon",
  "leave",
  "CV",
  "life history",
  "biography",
  "details",
  "curriculum vitae",
  "vita",
  "bio",
  "summary",
  "precis",
  "synopsis",
  "abstract",
  "outline",
  "summarization",
  "summation",
  "abridgment",
  "digest",
  "condensation",
  "abbreviation",
  "survey",
  "overview",
  "rundown",
  "run-through",
  "review",
  "sketch",
  "tour d'horizon",
  "wrap-up",
  "headnote",
  "brief",
  "conspectus",
  "summa",
  "epitome",
  "compendium",
];
