export const definitions = [
  '"built in 1830, the house retains many of its original features"',
  '"the rights of defendants must be retained"',
  '"I retained a few French words and phrases"',
  '"limestone is known to retain water"',
  '"the successful design of a cartridge belt requires that the cartridges in it be properly located and retained in that position"',
  '"he has been retained as a freelance"',
];
export const synonyms = [
  "keep",
  "keep back",
  "maintain",
  "continue",
  "preserve",
  "reserve",
  "conserve",
  "perpetuate",
  "cherish",
  "keep possession of",
  "keep hold of",
  "hold onto",
  "hold fast to",
  "hang onto",
  "cling to",
  "cleave to",
  "give up",
  "lose",
  "abolish",
  "discontinue",
  "alter",
  "maintain",
  "keep",
  "continue",
  "preserve",
  "reserve",
  "conserve",
  "perpetuate",
  "cherish",
  "abolish",
  "discontinue",
  "alter",
  "remember",
  "memorize",
  "learn",
  "recall",
  "recollect",
  "think of",
  "con",
  "keep in one's mind",
  "keep in 's 's memory",
  "learn by heart",
  "get by heart",
  "commit to memory",
  "get down pat",
  "learn by rote",
  "impress on the memory",
  "become word-perfect in",
  "call to mind",
  "succeed in remembering",
  "get off pat",
  "forget",
  "employ",
  "commission",
  "contract",
  "pay",
  "hire",
  "engage",
  "appoint",
  "recruit",
  "sign on",
  "sign up",
  "take on",
  "keep on the payroll",
  "have in employment",
  "put on the payroll",
  "secure the services of",
  "take into one's employ",
  "dismiss",
];
