export const definitions = [
  '""No need to be rude," retorted Isabel"',
  '"he retorted that this was nonsense"',
  '"I resisted the urge to retort"',
  '"it was now his time to retort the humiliation"',
  '"he was resolute to retort the charge of treason on his foes"',
  '"the answer they make to us may very easily be retorted"',
  '"she opened her mouth to make a suitably cutting retort"',
  '"gas was made by baking coal in airtight retorts"',
  '"a laboratory full of bubbling retorts and crackling electrical equipment"',
  '"the raw shale is retorted at four crude oil works"',
];
export const synonyms = [
  "answer",
  "reply",
  "respond",
  "acknowledge",
  "return",
  "counter",
  "rejoin",
  "riposte",
  "retaliate",
  "snap back",
  "come back",
  "say in response",
  "hurl back",
  "fling back",
  "round on someone",
  "answer",
  "reply",
  "response",
  "acknowledgment",
  "return",
  "counter",
  "rejoinder",
  "riposte",
  "sally",
  "retaliation",
];
