export const definitions = [
  '"Cézanne\'s still lifes were revered by his contemporaries"',
];
export const synonyms = [
  'respect',
  'admire',
  'esteem',
  'appreciate',
  'cherish',
  'value',
  'prize',
  'treasure',
  'look up to',
  'worship',
  'venerate',
  'reverence',
  'adulate',
  'idolize',
  'lionize',
  'hero-worship',
  'honor',
  'love',
  'think highly of',
  'have a high opinion of',
  'hold in high regard',
  'hold in (high) esteem',
  'think much of',
  'approve of',
  'set (great) store by',
  'pay homage to',
  'hold in awe',
  'put on a pedestal',
  'despise',
];