export const definitions = [
  '"the book was published in 1960 and revised in 1968"',
  '"the agency revised its procedures in as a result of the fire"',
  '"he had cause to revise his opinion a moment after expressing it"',
  '"students frantically revising for exams"',
  '"revise your lecture notes on the topic"',
  '"I handed in the revises this morning"',
];
export const synonyms = [
  "reconsider",
  "review",
  "re-examine",
  "reassess",
  "re-evaluate",
  "reappraise",
  "rethink",
  "think over",
  "change",
  "alter",
  "modify",
  "disconfirm",
  "take another look at",
  "take a fresh look at",
  "look at in a different light",
  "have another think about",
  "retain",
  "confirm",
  "go over",
  "reread",
  "run through",
  "study",
  "memorize",
  "cram",
  "page proof",
  "galley proof",
  "galley",
  "pull",
  "slip",
  "trial print",
];
