export const definitions = [
  '"both men collapsed, but were revived"',
  '"she was beginning to revive from her faint"',
  '"the cool, refreshing water revived us all"',
  '"many pagan traditions continue or are being revived"',
  '"the paper made panicky attempts to revive falling sales"',
];
export const synonyms = [
  "resuscitate",
  "bring around",
  "bring to life",
  "bring back",
  "rescue",
  "save",
  "defibrillate",
  "come around",
  "come to life",
  "come to one's senses",
  "recover",
  "awake",
  "wake up",
  "bring someone (back) to their senses",
  "bring back to consciousness",
  "bring back from the edge of death",
  "give artificial respiration to",
  "give the kiss of life to",
  "give cardiac massage to",
  "regain consciousness",
  "recover consciousness",
  "reinvigorate",
  "revitalize",
  "refresh",
  "energize",
  "reanimate",
  "resuscitate",
  "brace",
  "fortify",
  "strengthen",
  "revivify",
  "rejuvenate",
  "regenerate",
  "renew",
  "breathe new life into",
  "enliven",
  "stimulate",
  "freshen",
  "torpefy",
  "reintroduce",
  "re-establish",
  "restore",
  "resurrect",
  "relaunch",
  "bring back",
  "reinstall",
  "reinstitute",
  "regenerate",
  "revitalize",
  "resuscitate",
  "breathe new life into",
  "reinvigorate",
  "renew",
  "awaken",
  "wake up",
  "rejuvenate",
  "stimulate",
  "renovate",
  "give a new lease of life to",
  "abolish",
];
