export const definitions = [
  '"a comprehensive review of defense policy"',
  '"all areas of the company will come under review"',
  '"a review of her sentence"',
  '"his case comes up for review in January"',
  '"the CEO\'s end - of - year review"',
  '"a review of recent developments in multicultural education"',
  '"she released her debut solo album to rave reviews"',
  '"the New Left Review"',
  '"he conducted a final review of his troops and spoke of his pride in having served in the US army"',
  '"the company\'s safety procedures are being reviewed"',
  '"the Attorney General asked the court to review the sentence"',
  '"in the next chapter we review a number of recent empirical studies"',
  '"I reviewed his first novel"',
  '"the Queen reviewed her brightly arrayed troops"',
  '"all slides were then reviewed by one pathologist"',
];
export const synonyms = [
  "analysis",
  "evaluation",
  "assessment",
  "appraisal",
  "examination",
  "investigation",
  "scrutiny",
  "inquiry",
  "exploration",
  "probe",
  "inspection",
  "study",
  "audit",
  "anatomization",
  "reconsideration",
  "re-examination",
  "reassessment",
  "re-evaluation",
  "reappraisal",
  "moderation",
  "rethink",
  "change",
  "alteration",
  "modification",
  "revision",
  "another look",
  "a fresh look",
  "survey",
  "report",
  "study",
  "account",
  "record",
  "description",
  "exposition",
  "statement",
  "delineation",
  "overview",
  "rundown",
  "breakdown",
  "compte rendu",
  "procès-verbal",
  "summing-up",
  "overall picture",
  "criticism",
  "critique",
  "write-up",
  "notice",
  "assessment",
  "evaluation",
  "judgment",
  "rating",
  "commentary",
  "piece",
  "article",
  "column",
  "journal",
  "periodical",
  "magazine",
  "organ",
  "publication",
  "proceedings",
  "annual",
  "quarterly",
  "monthly",
  "inspection",
  "parade",
  "display",
  "demonstration",
  "field day",
  "tattoo",
  "array",
  "muster",
  "procession",
  "march-past",
  "survey",
  "study",
  "research",
  "consider",
  "analyze",
  "audit",
  "examine",
  "scrutinize",
  "explore",
  "look into",
  "probe",
  "investigate",
  "inspect",
  "assess",
  "appraise",
  "sum up",
  "anatomize",
  "take stock of",
  "inquire into",
  "make inquiries into",
  "conduct investigations into",
  "size up",
  "discuss",
  "evaluate",
  "assess",
  "appraise",
  "judge",
  "weigh up",
  "rate",
  "write up",
  "critique",
  "criticize",
  "comment on",
  "inspect",
  "view",
  "scrutinize",
  "parade",
  "muster",
  "march past",
  "reconsider",
  "re-examine",
  "reassess",
  "re-evaluate",
  "reappraise",
  "moderate",
  "rethink",
  "think over",
  "change",
  "alter",
  "modify",
  "revise",
  "take another look at",
  "take a fresh look at",
  "look at in a different light",
  "have another think about",
  "stick by",
];
