export const definitions = ['"the men appealed and the sentence was revoked"'];
export const synonyms = [
  "cancel",
  "repeal",
  "rescind",
  "reverse",
  "abrogate",
  "annul",
  "nullify",
  "void",
  "invalidate",
  "quash",
  "abolish",
  "set aside",
  "countermand",
  "retract",
  "withdraw",
  "overrule",
  "override",
  "vacate",
  "avoid",
  "recall",
  "declare null and void",
  "make void",
  "render invalid",
  "disannul",
  "introduce",
  "enact",
  "ratify",
];
