export const definitions = [
  '"the insurgents revolted and had to be suppressed"',
  '"voters may revolt when they realize the cost of the measures"',
  '"he was revolted by the stench that greeted him"',
  '"\'tis just the main assumption reason most revolts at"',
  '"a revolt against oppressive rule"',
  '"the peasants rose in revolt"',
  '"a revolt over tax increases"',
];
export const synonyms = [
  'rebel',
  'rise',
  'take up arms',
  'riot',
  'mutiny',
  'rise up',
  'take to the streets',
  'take part in an uprising',
  'show resistance',
  'resist/oppose authority',
  'disobey/defy authority',
  'refuse to obey orders',
  'be insubordinate',
  'revolting',
  'disgusting',
  'abhorrent',
  'repellent',
  'repugnant',
  'offensive',
  'objectionable',
  'vile',
  'foul',
  'nasty',
  'loathsome',
  'sickening',
  'nauseating',
  'stomach-churning',
  'stomach-turning',
  'hateful',
  'detestable',
  'execrable',
  'abominable',
  'monstrous',
  'appalling',
  'reprehensible',
  'deplorable',
  'insufferable',
  'intolerable',
  'despicable',
  'contemptible',
  'beyond the pale',
  'unspeakable',
  'noxious',
  'horrendous',
  'heinous',
  'atrocious',
  'awful',
  'terrible',
  'dreadful',
  'frightful',
  'obnoxious',
  'unsavory',
  'unpleasant',
  'disagreeable',
  'distasteful',
  'dislikeable',
  'off-putting',
  'uninviting',
  'displeasing',
  'ugly',
  'hideous',
  'grotesque',
  'gruesome',
  'unsightly',
  'reptilian',
  'vomitous',
  'noisome',
  'disgustful',
  'scurvy',
  'loathly',
  'rebarbative',
  'as ugly as sin',
  'delightful',
  'pleasant',
  'attractive',
  'rebellion',
  'revolution',
  'insurrection',
  'mutiny',
  'uprising',
  'riot',
  'rioting',
  'rising',
  'insurgence',
  'insurgency',
  'coup',
  'overthrow',
  'regime change',
  'subversion',
  'sedition',
  'anarchy',
  'disorder',
  'protest',
  'strike',
  'coup d\'état',
  'jacquerie',
  'putsch',
  'seizure of power',
  'act of resistance',
  'act of defiance',
];