export const definitions = [
  '"the report attempted to educate the public and allay fears"',
  '"some stale figs partly allayed our hunger"',
];
export const synonyms = [
  "reduce",
  "diminish",
  "decrease",
  "lessen",
  "assuage",
  "alleviate",
  "ease",
  "relieve",
  "soothe",
  "soften",
  "take the edge off",
  "dull",
  "cushion",
  "mollify",
  "moderate",
  "calm",
  "lull",
  "temper",
  "mitigate",
  "palliate",
  "blunt",
  "deaden",
  "abate",
  "tone down",
  "dispel",
  "banish",
  "dismiss",
  "dissipate",
  "drive away",
  "quell",
  "check",
  "eliminate",
  "drive off",
  "chase away",
  "put to rest",
  "lenify",
  "increase",
  "intensify",
  "alleviate",
  "assuage",
  "palliate",
  "relieve",
  "ameliorate",
  "ease",
  "help",
  "soften",
  "lessen",
  "mitigate",
  "attenuate",
  "salve",
  "aggravate",
];
