export const definitions = [
  '"allied territories"',
  '"the allied fleet"',
  '"the liberation of Paris by Allied troops"',
  '"skilled craftsmanship allied to advanced technology"',
  '"members of the medical and allied professions"',
  '"he allied his racing experience with his father\'s business acumen"',
  '"he allied himself with the forces of change"',
];
export const synonyms = [
  "federated",
  "confederated",
  "federal",
  "associated",
  "in league",
  "cooperating",
  "unified",
  "united",
  "amalgamated",
  "integrated",
  "in alliance",
  "in partnership",
  "independent",
  "hostile",
  "associated",
  "related",
  "connected",
  "interconnected",
  "linked",
  "coupled",
  "similar",
  "like",
  "kindred",
  "comparable",
  "parallel",
  "equivalent",
  "corresponding",
  "cognate",
  "analogous",
  "homologous",
  "unrelated",
  "dissimilar",
  "combine",
  "marry",
  "couple",
  "merge",
  "amalgamate",
  "join",
  "pool",
  "fuse",
  "weld",
  "knit",
  "split",
  "unite",
  "join",
  "join forces",
  "combine",
  "collaborate",
  "side",
  "league",
  "affiliate",
  "confederate",
  "make common cause",
  "join up",
  "band together",
  "go into partnership",
  "team up",
  "align oneself",
  "go into league",
  "form an alliance",
  "throw in one's lot",
  "split",
];
