export const definitions = [
  '"debate continued among NATO allies"',
  '"he was forced to dismiss his closest political ally"',
  '"Claudia is an activist and an ally, deeply involved with Black Lives Matter and LGBTQ+ rights"',
  '"they were caught between the German army of occupation and the advancing Allies"',
  '"he allied his racing experience with his father\'s business acumen"',
  '"he allied himself with the forces of change"',
];
export const synonyms = [
  "associate",
  "colleague",
  "friend",
  "confederate",
  "partner",
  "supporter",
  "accomplice",
  "helper",
  "accessory",
  "abetter",
  "enemy",
  "opponent",
  "supporter",
  "advocate",
  "champion",
  "defender",
  "protector",
  "campaigner",
  "activist",
  "reformer",
  "demonstrator",
  "friend",
  "partner",
  "comrade",
  "opponent",
  "combine",
  "marry",
  "couple",
  "merge",
  "amalgamate",
  "join",
  "pool",
  "fuse",
  "weld",
  "knit",
  "split",
  "unite",
  "join",
  "join forces",
  "combine",
  "collaborate",
  "side",
  "league",
  "affiliate",
  "confederate",
  "make common cause",
  "join up",
  "band together",
  "go into partnership",
  "team up",
  "align oneself",
  "go into league",
  "form an alliance",
  "throw in one's lot",
  "split",
];
