export const definitions = [
  '"people for whom gold holds no allure"',
  '"will sponsors really be allured by such opportunities?"',
];
export const synonyms = [
  'attraction',
  'lure',
  'draw',
  'pull',
  'appeal',
  'glamour',
  'allurement',
  'enticement',
  'temptation',
  'bewitchment',
  'enchantment',
  'charm',
  'seduction',
  'persuasion',
  'fascination',
  'magnetism',
  'repulsion',
  'attract',
  'lure',
  'entice',
  'tempt',
  'captivate',
  'draw',
  'beguile',
  'bewitch',
  'enchant',
  'charm',
  'seduce',
  'persuade',
  'lead on',
  'tantalize',
  'intrigue',
  'fascinate',
  'enticing',
  'tempting',
  'attractive',
  'appealing',
  'fetching',
  'inviting',
  'glamorous',
  'captivating',
  'seductive',
  'enchanting',
  'beguiling',
  'charming',
  'fascinating',
  'intriguing',
  'tantalizing',
  'magnetic',
  'irresistible',
  'appeal to',
  'whet the appetite of',
  'make someone\'s mouth water',
  'win over',
  'repel',
];