export const definitions = [
  '"he ______ knocked Georgina over"',
  '"the place was ______ empty"',
  '"Rachel laughed, ______ apologetically"',
  '"it will eat ______ anything"',
  '"the storm was ______ upon them"',
];
export const synonyms = [
  "nearly",
  "just about",
  "about",
  "more or less",
  "practically",
  "virtually",
  "all but",
  "as good as",
  "next to",
  "close to",
  "near",
  "to all intents and purposes",
  "approaching",
  "nearing",
  "roughly",
  "approximately",
  "not quite",
  "well-nigh",
  "nigh on",
  "not far from",
  "not far off",
  "bordering on",
  "verging on",
];
