export const definitions = [
  '"the sun ______ rises in the east"',
  '"she had ______ been an obstinate sort"',
  '"she will ______ be missed"',
  '"she is ______ making derogatory remarks"',
  '"if the marriage doesn\'t work out, we can ______ get divorced"',
];
export const synonyms = [
  'every time',
  'all the time',
  'consistently',
  'invariably',
  'without fail',
  'without exception',
  'regularly',
  'repeatedly',
  'habitually',
  'unfailingly',
  'infallibly',
  'inevitably',
  'each time',
  'at all times',
  'on every occasion',
  'on all occasions',
  'permanently',
  'for good',
  'perpetually',
  'ever',
  '(for) evermore',
  'eternally',
  'in perpetuity',
  'everlastingly',
  'endlessly',
  'forevermore',
  'for aye',
  'for good and all',
  'for ever and ever',
  'for all (future) time',
  'until the end of time',
  'for eternity',
  'continually',
  'continuously',
  'constantly',
  'forever',
  'repeatedly',
  'perpetually',
  'incessantly',
  'ceaselessly',
  'unceasingly',
  'endlessly',
  'interminably',
  'eternally',
  'permanently',
  'the entire time',
  'as a last resort',
  'in any event',
  'in any case',
  'come what may',
  'whatever the circumstances',
  'no matter what',
];

export const antonyms = [
  'never',
  'seldom',
  'sometimes',
];
