export const definitions = [
  '""Never mind," she said kindly"',
  '"will you kindly sign the enclosed copy of this letter"',
  '"he was a quiet, kindly man"',
];
export const synonyms = [
  "benevolently",
  "good-naturedly",
  "warmly",
  "affectionately",
  "tenderly",
  "lovingly",
  "compassionately",
  "considerately",
  "thoughtfully",
  "helpfully",
  "obligingly",
  "generously",
  "selflessly",
  "unselfishly",
  "graciously",
  "indulgently",
  "sympathetically",
  "leniently",
  "charitably",
  "unkindly",
  "harshly",
  "please",
  "if you please",
  "pray",
  "prithee",
  "if you would be so good",
  "if you wouldn't mind",
  "have the goodness to",
  "s'il vous plaît",
  "benevolent",
  "kind",
  "kindhearted",
  "warmhearted",
  "generous",
  "good-natured",
  "humane",
  "gentle",
  "warm",
  "mild",
  "compassionate",
  "caring",
  "tenderhearted",
  "softhearted",
  "tender",
  "loving",
  "motherly",
  "fatherly",
  "benign",
  "mellow",
  "well meaning",
  "genial",
  "indulgent",
  "understanding",
  "sympathetic",
  "lenient",
  "tolerant",
  "charitable",
  "magnanimous",
  "easygoing",
  "patient",
  "helpful",
  "thoughtful",
  "considerate",
  "good",
  "good-hearted",
  "nice",
  "friendly",
  "neighborly",
  "pleasant",
  "amiable",
  "agreeable",
  "affable",
  "amicable",
  "benignant",
  "loving and giving",
  "unkind",
  "cruel",
];
