export const definitions = [
  '"kinky underwear"',
  '"long and kinky hair"',
];
export const synonyms = [
  'abnormal',
  'unusual',
  'weird',
  'bizarre',
  'peculiar',
  'strange',
  'odd',
  'funny',
  'perverted',
  'deviant',
  'unnatural',
  'warped',
  'twisted',
  'depraved',
  'degenerate',
  'perverse',
  'unhealthy',
  'aberrant',
  'sadistic',
  'masochistic',
  'corrupt',
  'immoral',
  'deviative',
  'provocative',
  'sexy',
  'erotic',
  'seductive',
  'suggestive',
  'inviting',
  'tempting',
  'tantalizing',
  'alluring',
  'titillating',
  'indecent',
  'sexually arousing',
  'sexually exciting',
  'curly',
  'crimped',
  'curled',
  'curling',
  'frizzy',
  'frizzed',
  'wavy',
  'ringletted',
  'twisted',
  'bent',
  'coiled',
  'crinkled',
  'ringletty',
  'straight',
];