export const definitions = [
  '"the first draft of the party\'s manifesto"',
  '"a draft document"',
  '"25 million men were subject to the draft"',
  '"draft cards"',
  '"heavy curtains at the windows cut out drafts"',
  '"she downed the remaining beer in one draft"',
  '"he took deep drafts of oxygen into his lungs"',
  '"the shallow draft enabled her to get close to shore"',
  '"I drafted a letter of resignation"',
  '"he was drafted to help with the task force on best safety practices"',
  '"he was drafted in 1938"',
  '"he was drafted by Winnipeg and traded the following spring"',
];
export const synonyms = [
  'conscript',
  'call up',
  'enlist',
  'mobilize',
  'rally',
  'muster',
  'marshal',
  'press',
  'recruit',
  'raise',
  'assemble',
  'round up',
  'demobilize',
  'disband',
];