export const definitions = [
  '"Two gritty urban ______ about growing up in Harlem coming this fall"',
  '"Teen ______ dominating Netflix development"',
  '"She felt exhausted from navigating multiple ______ at home, at work and in her own mind"',
];
export const synonyms = [
  "plays",
  "shows",
  "pieces",
  "spectacles",
  "dramatizations",
  "screenplays",
  "theatrical works",
  "catastrophes",
  "calamities",
  "cataclysms",
  "emergencies",
  "disasters",
  "predicaments",
  "plights",
  "messes",
  "dilemmas",
  "quandaries",
  "setbacks",
  "reversals",
  "upheavals",
  "troubles",
  "hardships",
  "adversity",
  "extremities",
  "distresses",
  "difficulties",
  "dire straits",
  "hard times",
];
