export const definitions = [
  '"Jane was dreading the party"',
  '"I dread to think what Russell will say"',
  '"the thought of returning to New Jersey filled her with dread"',
  '"I used to have a dread of Sunday afternoons"',
  '"Lyon combed his fingers through Curtis\' dreads"',
];
export const synonyms = [
  "fear",
  "be afraid of",
  "worry about",
  "be anxious about",
  "have forebodings about",
  "feel apprehensive about",
  "be terrified by",
  "cower at",
  "tremble/shudder at",
  "cringe from",
  "shrink from",
  "quail from",
  "flinch from",
  "look forward to",
  "revere",
  "reverence",
  "venerate",
  "respect",
  "stand in awe of",
  "regard with awe",
  "be intimidated by",
  "fear",
  "fearfulness",
  "apprehension",
  "trepidation",
  "anxiety",
  "worry",
  "concern",
  "foreboding",
  "disquiet",
  "disquietude",
  "unease",
  "uneasiness",
  "angst",
  "fright",
  "panic",
  "alarm",
  "terror",
  "horror",
  "trembling",
  "shuddering",
  "flinching",
  "confidence",
];
