export const definitions = [
  '"I ______ about being with my crush last night"',
  '"Living a fantasy someone else ______ up"',
];
export const synonyms = [
  "have a dream",
  "have dreams",
  "have a nightmare",
  "have nightmares",
  "set one's heart on",
  "set one's sights on",
  "fantasize about",
  "daydream about",
  "wish for",
  "hope for",
  "long for",
  "yearn for",
  "hunger for",
  "hanker after",
  "aspire to",
  "desire to",
  "wish to",
  "aim for",
  "seek to",
  "have as one's goal / aim",
  "thirst for/after",
  "think",
  "consider",
  "contemplate",
  "conceive",
  "visualize",
  "entertain the thought of",
];
