export const definitions = [
  '"don\'t talk such drivel!"',
  '"he was driveling on about the glory days"',
  '"the nurse leaves you to drivel, and never wipes your nose"',
];
export const synonyms = [
  "nonsense",
  "twaddle",
  "claptrap",
  "balderdash",
  "gibberish",
  "mumbo jumbo",
  "rubbish",
  "sense",
  "babble",
  "ramble",
  "gibber",
  "burble",
  "blather",
  "blether",
  "prate",
  "prattle",
  "gabble",
  "chatter",
  "twitter",
  "maunder",
  "talk nonsense",
  "talk rubbish",
  "salivate",
  "dribble",
  "slaver",
  "slobber",
  "slabber",
  "water at the mouth",
];
