export const definitions = [];
export const synonyms = [
  "entitlement",
  "prerogative",
  "privilege",
  "advantage",
  "due",
  "birthright",
  "liberty",
  "authority",
  "authorization",
  "power",
  "license",
  "permission",
  "dispensation",
  "leave",
  "consent",
  "warrant",
  "charter",
  "franchise",
  "sanction",
  "exemption",
  "immunity",
  "indemnity",
  "carte blanche",
];
