export const definitions = [
  '"in the far distance a machine droned"',
  '"he reached for another beer while Jim droned on"',
  '"traffic droned up and down the street"',
  '"he nodded off to the drone of the car engine"',
  '"only twenty minutes of the hour-long drone had passed"',
  '"the drone rose by a third to A"',
  '"the University takes all the profit and redistributes it to drones like him"',
  '"pilots use remote controls to guide a stealth reconnaissance drone"',
  '"a photographer used a drone to take some unconventional photos of the countryside"',
  '"a drone was sent to explore the depths"',
];
export const synonyms = [
  "hum",
  "buzz",
  "whir",
  "vibrate",
  "murmur",
  "rumble",
  "purr",
  "hiss",
  "whisper",
  "sigh",
  "intone",
  "pontificate",
  "speak boringly",
  "speak monotonously",
  "go on and on",
  "talk interminably",
  "hum",
  "buzz",
  "whir",
  "whirring",
  "vibration",
  "murmur",
  "murmuring",
  "purr",
  "purring",
  "hiss",
  "hissing",
  "whisper",
  "whispering",
  "sigh",
  "flatness",
  "tonelessness",
  "lack of inflection",
  "hum",
  "singing",
  "note",
  "hanger-on",
  "parasite",
  "leech",
  "passenger",
  "idler",
  "loafer",
  "layabout",
  "lounger",
  "good-for-nothing",
  "do-nothing",
  "sluggard",
  "laggard",
];
