export const definitions = [
  '"the baby begins to drool, then to cough"',
  '"he was drooling over your photo on the inside cover"',
];
export const synonyms = [
  "salivate",
  "dribble",
  "slaver",
  "slobber",
  "drivel",
  "slabber",
  "water at the mouth",
  "desire",
  "crave",
  "covet",
  "want",
  "be consumed with desire for",
  "find sexually attractive",
  "find sexy",
  "wish for",
  "long for",
  "yearn for",
  "hunger for",
  "thirst for",
  "ache for",
  "burn for",
  "pant for",
];
