export const definitions = [
  '"a droopy mustache"',
  '"the girls looked rather droopy"',
  '"a period of droopy sales"',
];
export const synonyms = [
  "drooping",
  "hanging",
  "dangling",
  "falling",
  "dropping",
  "draped",
  "bending",
  "bent",
  "bowed",
  "bowing",
  "stooping",
  "sagging",
  "sinking",
  "slumping",
  "flopping",
  "wilting",
  "hanging down",
  "becoming limp",
  "becoming flaccid",
  "upright",
  "apathetic",
  "passive",
  "unenthusiastic",
  "lifeless",
  "listless",
  "weak",
  "feeble",
  "spineless",
  "limp",
  "languid",
  "bloodless",
  "insipid",
  "characterless",
  "submissive",
  "meek",
  "irresolute",
  "indecisive",
  "lackluster",
  "flat",
  "colorless",
  "passionless",
  "uninspiring",
  "uninspired",
  "wooden",
  "dry",
  "desiccated",
  "anemic",
  "vapid",
  "dull",
  "boring",
  "lacking in vitality",
  "unimpassioned",
  "spirited",
  "lively",
];
