export const definitions = [
  '"the wine had made her drowsy"',
  '"the drowsy heat of the meadows"',
  '"a drowsy suburb"',
];
export const synonyms = [
  "sleepy",
  "dozy",
  "dozing",
  "heavy",
  "heavy-eyed",
  "yawning",
  "nodding",
  "groggy",
  "somnolent",
  "tired",
  "weary",
  "fatigued",
  "exhausted",
  "lethargic",
  "sluggish",
  "torpid",
  "lifeless",
  "listless",
  "languid",
  "languorous",
  "comatose",
  "dazed",
  "drugged",
  "slumberous",
  "half asleep",
  "ready for bed",
  "hardly able to keep one's eyes open",
  "wakeful",
  "alert",
  "soporific",
  "sleep-inducing",
  "sleepy",
  "somniferous",
  "narcotic",
  "sedative",
  "calmative",
  "tranquillizing",
  "lulling",
  "soothing",
  "dreamy",
  "somnific",
  "invigorating",
];
