export const definitions = [
  '"he was beginning to drowse in his chair"',
  '"any birds which the heat has not utterly drowsed"',
  '"let not your prudence drowse"',
  '"she awoke from a light drowse"',
];
export const synonyms = [
  'doze',
  'nap',
  'catnap',
  'rest',
  'slumber',
  'sleep (lightly)',
  'take a nap',
  'take a siesta',
  'be awake',
  'asleep',
  'sleeping',
  'slumbering',
  'resting',
  'reposing',
  'drowsing',
  'comatose',
  'supine',
  'inactive',
  'passive',
  'inert',
  'latent',
  'fallow',
  'quiescent',
  'inoperative',
  'stagnant',
  'sluggish',
  'lethargic',
  'torpid',
  'motionless',
  'immobile',
  'estivating',
  'awake',
  'active',
  'doze',
  'nap',
  'catnap',
  'siesta',
  'rest',
  'slumber',
  'light sleep',
  'lie-down',
  'wakefulness',
];