export const definitions = [
  '"I felt like a household drudge"',
  '"her husband was drudging in the smoke of London"',
];
export const synonyms = [
  "menial",
  "slave",
  "galley slave",
  "toiler",
  "lackey",
  "servant",
  "laborer",
  "hack",
  "worker",
  "houseboy",
  "factotum",
  "peon",
  "charwoman",
  "charlady",
  "char",
  "scullion",
  "servitor",
  "menial worker",
  "maid/man of all work",
  "hewer of wood and drawer of water",
  "labor",
  "work one's fingers to the bone",
  "work like a Trojan",
  "keep one's nose to the grindstone",
  "grind away",
  "travail",
  "moil",
  "work hard",
  "work like a dog",
  "work day and night",
  "exert oneself",
  "keep at it",
  "slave away",
  "grub away",
  "plow away",
  "plod away",
  "rest",
  "relax",
  "laze",
];
