export const definitions = [
  '"we staggered up the path like a couple of ______"',
  '"the crowd became unruly as it a bunch of ______"',
];
export const synonyms = [
  "drunkard",
  "inebriate",
  "drinker",
  "imbiber",
  "tippler",
  "sot",
  "alcoholic",
  "dipsomaniac",
  "alcohol abuser",
  "toper",
  "tosspot",
  "heavy drinker",
  "hard drinker",
  "serious drinker",
  "problem drinker",
  "chronic alcoholic",
  "alcohol addict",
  "person with a drink problem",
  "teetotaler",
];
