export const definitions = [
  '"allow 24 hours for the paint to dry"',
  '"come in out of the rain and dry off"',
  '"they had washed and dried their hair"',
  '"she dried her eyes and blew her nose"',
  '"I use several methods to dry the flowers and foliage I use in my arrangements"',
  '"the natural sugars in the fruit will be concentrated when it is dried"',
  '"a colleague of mine once dried in the middle of a scene"',
];
export const synonyms = [
  "parch",
  "scorch",
  "sear",
  "bake",
  "dehydrate",
  "desiccate",
  "dehumidify",
  "towel",
  "towel-dry",
  "rub",
  "mop up",
  "soak up",
  "absorb",
  "clean up",
  "drain",
  "make dry",
  "dry out/up",
  "dry off",
  "blot up",
  "sop up",
  "moisten",
  "wipe",
  "rub",
  "dab",
  "wipe tears from",
  "dry up",
  "dehydrate",
  "desiccate",
  "wither",
  "shrivel",
  "wilt",
  "wizen",
  "mummify",
  "preserve",
  "cure",
  "smoke",
  "remove the moisture from",
  "moisten",
];
