export const definitions = [
  '"there was a brief hiatus in the war with France"',
];
export const synonyms = [
  "pause",
  "break",
  "interval",
  "interruption",
  "suspension",
  "intermission",
  "interlude",
  "gap",
  "lacuna",
  "lull",
  "rest",
  "respite",
  "breathing space",
  "time out",
  "recess",
  "surcease",
  "opening",
  "aperture",
  "cavity",
  "hole",
  "gap",
  "cleft",
  "breach",
  "fissure",
  "foramen",
];
