export const definitions = [
  '"three armed men hijacked a white van"',
  '"the UN convoys have been tamely allowing gunmen to hijack relief supplies"',
  '"the organization had been hijacked by extremists"',
  '"an unsuccessful hijack attempt"',
];
export const synonyms = [
  'commandeer',
  'seize',
  'take over',
  'skyjack',
  'appropriate',
  'expropriate',
  'confiscate',
  'take possession of',
  'seizure',
  'seizing',
  'taking',
  'appropriation',
  'appropriating',
  'commandeering',
  'expropriation',
  'expropriating',
  'confiscation',
  'confiscating',
  'requisition',
  'requisitioning',
  'hijacking',
  'wresting',
  'usurping',
  'preempting',
  'arrogation',
  'claiming',
  'taking over',
  'taking away',
];