export const definitions = [
  '"medical ethics also enter into the question"',
  '"a code of ethics"',
  '"many scientists question the ethics of cruel experiments"',
  '"neither metaphysics nor ethics is the home of religion"',
  '"the puritan ethic was being replaced by the hedonist ethic"',
];
export const synonyms = [
  'morals',
  'morality',
  'principles',
  'ideals',
  'creed',
  'credo',
  'ethos',
  'virtues',
  'moral code',
  'moral stand',
  'moral principles',
  'moral values',
  'rights and wrongs',
  'rules of conduct',
  'standards (of behavior)',
  'dictates of conscience',
  'fairness',
  'justness',
  'fair play',
  'fair-mindedness',
  'equity',
  'equitableness',
  'even-handedness',
  'egalitarianism',
  'impartiality',
  'objectivity',
  'neutrality',
  'disinterestedness',
  'open-mindedness',
  'nonpartisanship',
  'honor',
  'uprightness',
  'decency',
  'integrity',
  'probity',
  'honesty',
  'righteousness',
  'morals',
  'morality',
  'virtue',
  'principle',
  'right-mindedness',
  'propriety',
  'scrupulousness',
  'trustworthiness',
  'incorruptibility',
  'impartialness',
  'lack of bias',
  'lack of prejudice',
  'injustice',
  'doctrine',
  'belief',
  'creed',
  'credo',
  'attitude',
  'rule',
  'golden rule',
  'guideline',
  'formula',
  'standard',
  'criterion',
  'tenet',
  'truism',
  'code',
  'maxim',
  'motto',
  'axiom',
  'aphorism',
  'notion',
  'dictum',
  'dogma',
  'canon',
  'law',
];