export const definitions = [
  '"the alcohol content is clearly stated on the label"',
  '"price labels"',
  '"a garment with the label "Laura Ashley""',
  '"independent labels"',
  '"she plans to launch her own designer clothes label"',
  '"my reluctance to stick a label on myself politically"',
  '"the italic part-of-speech label follows the pronunciation"',
  '"radioactive labels"',
  '"she labeled the parcels neatly, writing the addresses in capital letters"',
  '"the critics labeled him a loser"',
  '"children were labeled as bullies"',
];
export const synonyms = [
  "tag",
  "ticket",
  "tab",
  "sticker",
  "marker",
  "docket",
  "chit",
  "flag",
  "stamp",
  "document",
  "documentation",
  "chitty",
  "brand",
  "brand name",
  "trade name",
  "trademark",
  "proprietary name",
  "line",
  "make",
  "logo",
  "designation",
  "denomination",
  "description",
  "characterization",
  "identification",
  "tag",
  "name",
  "epithet",
  "nickname",
  "title",
  "sobriquet",
  "pet name",
  "byname",
  "appellation",
  "cognomen",
  "tag",
  "tab",
  "ticket",
  "stamp",
  "mark",
  "docket",
  "flag",
  "attach labels to",
  "put labels on",
  "put stickers on",
  "categorize",
  "classify",
  "class",
  "characterize",
  "describe",
  "designate",
  "identify",
  "mark",
  "stamp",
  "pronounce",
  "brand",
  "condemn",
  "pigeonhole",
  "stereotype",
  "typecast",
  "compartmentalize",
  "typify",
  "call",
  "name",
  "term",
  "dub",
  "nickname",
];
