export const definitions = [
  '"the price of repairs includes labor and parts"',
  '"manual labor"',
  '"nonunion casual labor"',
  '"the labor movement"',
  '"Secretary of Labor"',
  '"the Labour leader"',
  '"his wife is in labor"',
  '"they labored from dawn to dusk"',
  '"she was patiently laboring over her sketchbooks"',
  '"he was eking out an existence by laboring"',
  '"the land belonged to him who labored it"',
  '"Coley labored against confident opponents"',
  '"they labored up a steep, tortuous track"',
  '"the wheels churned, the engine laboring"',
  '"the seas ran high, and the ship labored hard"',
  '"she labored very well and comfortably because she was relaxed"',
];
export const synonyms = [
  "task",
  "job",
  "chore",
  "undertaking",
  "mission",
  "commission",
  "assignment",
  "workers",
  "employees",
  "workmen",
  "workforce",
  "staff",
  "hands",
  "laborers",
  "labor force",
  "hired hands",
  "proletariat",
  "manpower",
  "human resources",
  "personnel",
  "liveware",
  "working people",
  "blue-collar workers",
  "wage-earners",
  "management",
  "childbirth",
  "birth",
  "birthing",
  "delivery",
  "nativity",
  "contractions",
  "labor pains",
  "parturition",
  "confinement",
  "accouchement",
  "lying-in",
  "childbed",
  "travail",
  "labor pangs",
  "labor throes",
  "toil",
  "grind away",
  "struggle",
  "strive",
  "overwork",
  "work one's fingers to the bone",
  "keep 's 's nose to the grindstone",
  "drudge",
  "travail",
  "moil",
  "work (hard)",
  "slave (away)",
  "grub away",
  "plod away",
  "sweat away",
  "exert oneself",
  "work like a Trojan/dog/slave",
  "rest",
  "relax",
  "laze",
  "strive",
  "struggle",
  "endeavor",
  "work",
  "make every effort",
  "do one's best",
  "do 's 's utmost",
  "fight",
  "push",
  "try hard",
  "do all one can",
  "give (it/something) one's all",
  "go all out",
  "be at pains",
  "put oneself out",
  "apply oneself",
  "exert oneself",
  "lurch",
  "plunge",
  "roll",
  "reel",
  "sway",
  "rock",
  "flounder",
  "keel",
  "list",
  "wallow",
  "pitchpole",
  "toss (around)",
];
