export const definitions = [
  '"a lapsed insurance policy"',
  '"a lapsed Catholic"',
  '"my membership to the gym has lapsed"',
  '"if your diet has lapsed it\'s time you revived it"',
  '"many Christians in Britain have lapsed"',
  '"the country has lapsed into chaos"',
  '"the girls lapsed into French"',
];
export const synonyms = [
  "expired",
  "void",
  "invalid",
  "run out",
  "out of date",
  "terminated",
  "discontinued",
  "unrenewed",
  "current",
  "valid",
  "non-practicing",
  "backsliding",
  "recidivist",
  "apostate",
  "quondam",
  "lacking faith",
  "practicing",
  "devout",
  "expired",
  "void",
  "invalid",
  "run out",
  "out of date",
  "terminated",
  "discontinued",
  "expire",
  "terminate",
  "unrenewed",
  "become void",
  "become invalid",
  "become obsolete",
  "current",
  "valid",
  "end",
  "cease",
  "come to an end",
  "stop",
  "terminate",
  "vanish",
  "disappear",
  "pass",
  "fade",
  "fall away",
  "dwindle",
  "wilt",
  "wither",
  "die",
  "non-practicing",
  "backsliding",
  "recidivist",
  "apostate",
  "quondam",
  "lacking faith",
  "practicing",
  "devout",
  "deteriorate",
  "decline",
  "fall",
  "fall off",
  "drop",
  "worsen",
  "degenerate",
  "decay",
  "rot",
  "backslide",
  "regress",
  "retrogress",
  "sink",
  "wane",
  "slump",
  "fail",
  "get worse",
  "improve",
  "strengthen",
  "revert",
  "relapse",
  "fall back",
  "drift",
  "slide",
  "slip",
  "sink",
  "subside",
];
