export const definitions = [
  '"they lashed him repeatedly about the head"',
  '"waves lashed the coast"',
  '"the rain lashed against the car"',
  '"I could feel the wind lashing at me"',
  '"the cat was lashing its tail back and forth"',
  '"the cat\'s tail lashed furiously from side to side"',
  '"the hatch was securely lashed down"',
  '"he lashed the flag to the mast"',
  '"he was sentenced to fifty lashes for his crime"',
  '"she felt the lash of my tongue"',
  '"he brought the lash down upon the prisoner\'s back"',
  '"they were living under the threat of the lash"',
  '"she fluttered her long dark lashes"',
];
export const synonyms = [
  "whip",
  "flog",
  "beat",
  "thrash",
  "horsewhip",
  "scourge",
  "birch",
  "switch",
  "flay",
  "belt",
  "strap",
  "cane",
  "leather",
  "strike",
  "hit",
  "clout",
  "batter",
  "welt",
  "hammer",
  "pummel",
  "belabor",
  "smite",
  "stripe",
  "flagellate",
  "pound",
  "batter",
  "buffet",
  "strike",
  "hit",
  "knock",
  "beat against",
  "dash against",
  "crash against",
  "smack against",
  "swish",
  "flick",
  "twitch",
  "switch",
  "whip",
  "wave",
  "wag",
  "fasten",
  "bind",
  "tie",
  "tie up",
  "tether",
  "hitch",
  "attach",
  "knot",
  "rope",
  "strap",
  "leash",
  "truss",
  "fetter",
  "secure",
  "chain",
  "pinion",
  "join",
  "connect",
  "couple",
  "make fast",
  "stroke",
  "blow",
  "hit",
  "strike",
  "welt",
  "bang",
  "thwack",
  "thump",
  "stripe",
  "whip",
  "scourge",
  "cat",
  "thong",
  "switch",
  "birch",
  "cane",
  "stick",
  "riding crop",
  "hunting crop",
  "whip",
  "horsewhip",
  "bullwhip",
  "switch",
  "scourge",
  "flagellum",
  "cat",
  "thong",
  "flail",
  "strap",
  "birch",
  "cane",
  "knout",
];
