export const definitions = [
  '"the latest news"',
  '"have you heard the latest?"',
  '"his late arrival"',
  '"she was half an hour late for her lunch appointment"',
  '"they won the game with a late goal"',
  '"the late 1960s"',
  '"late Gothic style"',
  '"I\'m sorry the call is so late"',
  '"it\'s too late for lunch"',
  '"the last late chrysanthemums"',
  '"her late husband\'s grave"',
  '"the late William Jennings Bryan"',
  '"a late colleague of mine"',
  '"she arrived late"',
  '"it happened late in 1984"',
  '"now I\'m old enough to stay up late"',
  '"Captain Falconer, late of the British army"',
];
export const synonyms = [
  "newest",
  "brand new",
  "fresh",
  "present-day",
  "up to date",
  "up to the minute",
  "state-of-the-art",
  "current",
  "modern",
  "contemporary",
  "modernistic",
  "fashionable",
  "in fashion",
  "voguish",
  "in",
  "à la mode",
  "most recent",
  "just out",
  "just released",
  "in vogue",
  "bang up to date",
  "old",
  "unfashionable",
  "behind time",
  "behind schedule",
  "behind",
  "behindhand",
  "unpunctual",
  "tardy",
  "overdue",
  "delayed",
  "belated",
  "slow",
  "dilatory",
  "not on time",
  "running late",
  "long-overdue",
  "long-delayed",
  "punctual",
  "early",
  "fast",
  "dead",
  "deceased",
  "departed",
  "lamented",
  "lost",
  "expired",
  "gone",
  "extinct",
  "perished",
  "passed on/away",
  "alive",
  "existing",
  "previous",
  "preceding",
  "former",
  "past",
  "prior",
  "earlier",
  "as was",
  "sometime",
  "one-time",
  "ex-",
  "erstwhile",
  "old",
  "defunct",
  "precedent",
  "foregoing",
  "ci-devant",
  "quondam",
  "whilom",
  "no longer extant",
  "current",
  "behind schedule",
  "behind time",
  "behindhand",
  "belatedly",
  "tardily",
  "dilatorily",
  "slowly",
  "recently",
  "after hours",
  "overtime",
  "unpunctually",
  "at the last minute",
  "at the tail end",
  "after office hours",
  "past the usual finishing/stopping/closing time",
  "early",
  "betimes",
  "late at night",
  "till the early hours of the morning",
];
