export const definitions = [
  '"changing the layout of the ground floor"',
  '"the layout is uncluttered and the illustrations are helpful"',
  '"doing layout for newspapers and magazines"',
  '"a model railroad layout"',
];
export const synonyms = [
  'structure',
  'arrangement',
  'construction',
  'framework',
  'format',
  'design',
  'organization',
  'system',
  'planning',
  'order',
  'orderliness',
  'symmetry',
  'proportion',
  'content',
  'arrangement',
  'geography',
  'design',
  'organization',
  'makeup',
  'shape',
  'plan',
  'map',
  'design',
  'arrangement',
  'presentation',
  'style',
  'format',
  'structure',
  'organization',
  'composition',
  'formation',
  'configuration',
  'setup',
  'pattern',
  'outline',
  'plan',
  'sketch',
];