export const definitions = [
  '"I don\'t want him meddling in our affairs"',
  '"you have no right to come in here and meddle with my things"',
];
export const synonyms = [
  "interfere",
  "butt in",
  "intrude",
  "intervene",
  "interlope",
  "pry",
  "poke",
  "nose",
  "busybody",
  "interpose",
  "obtrude",
  "thrust",
  "intermeddle",
  "fiddle",
  "tamper",
  "tinker",
  "monkey",
  "finger",
  "touch/handle without permission",
  "mind one's own business",
  "leave alone",
];
