export const definitions = [
  '"interest from members of the public"',
  '"a member of the lily family"',
  '"the EU\'s member countries"',
  '"a member of the drama club"',
  '"he travelled with fellow Church members"',
  '"a Member of Parliament"',
  '"members of Congress"',
  '"the main member that joins the front and rear axles"',
];
export const synonyms = [
  "constituent",
  "element",
  "component",
  "part",
  "portion",
  "piece",
  "unit",
  "factor",
  "feature",
  "attribute",
  "subscriber",
  "associate",
  "representative",
  "attender",
  "insider",
  "fellow",
  "comrade",
  "adherent",
  "life member",
  "supporter",
  "follower",
  "upholder",
  "advocate",
  "disciple",
  "sectary",
  "founder member",
  "card-carrying member",
  "Member of Parliament",
  "MP",
  "Member",
  "councilor",
  "Member of Congress",
  "congressman",
  "congresswoman",
  "senator",
  "limb",
  "organ",
  "arm",
  "leg",
  "appendage",
  "extremity",
  "projection",
  "protuberance",
  "process",
  "penis",
  "part of the body",
  "phallus",
  "(male) member",
  "sex",
  "erection",
  "lunch box",
  "intromittent organ",
  "membrum virile",
  "nerve",
  "person",
  "propagator",
  "verge",
  "pizzle",
  "loom",
  "needle",
  "pintle",
  "(male) organ",
  "virile member",
  "tarse",
  "pillicock",
  "runnion",
];
