export const definitions = [
  '"I\'ve a great memory for faces"',
  '"the brain regions responsible for memory"',
  '"my grandmother is losing her memory"',
  '"he searched his memory frantically for an answer"',
  '"one of my earliest memories is of sitting on his knee"',
  '"the mind can bury all memory of traumatic abuse"',
  '"clubs devoted to the memory of Sherlock Holmes"',
  '"the worst slump in recent memory"',
  '"the module provides 16Mb of memory"',
];
export const synonyms = [
  "recall",
  "retention",
  "mind",
  "ability to remember",
  "powers of recall",
  "powers of retention",
  "forgetfulness",
  "recollection",
  "remembrance",
  "reminiscence",
  "evocation",
  "reminder",
  "souvenir",
  "echo",
  "impression",
  "commemoration",
  "remembrance",
  "honor",
  "tribute",
  "recognition",
  "observance",
  "respect",
  "memory bank",
  "store",
  "cache",
  "disk",
  "RAM",
  "ROM",
];
