export const definitions = [
  '"workmen were mending faulty cabling"',
  '"a patch was used to mend the garment"',
  '"foot injuries can take months to mend"',
  '"quarrels could be mended by talking"',
];
export const synonyms = [
  "repair",
  "fix",
  "restore",
  "sew (up)",
  "stitch",
  "darn",
  "patch",
  "cobble",
  "botch",
  "rehabilitate",
  "renew",
  "renovate",
  "redevelop",
  "overhaul",
  "recondition",
  "rebuild",
  "refurbish",
  "cure",
  "heal",
  "fettle",
  "ranter",
  "clout",
  "tinker",
  "beet",
  "put back together",
  "piece together",
  "patch up",
  "vamp (up)",
  "make whole",
  "make well",
  "spetch",
  "break",
  "tear",
  "recover",
  "pull through",
  "recuperate",
  "convalesce",
  "improve",
  "heal",
  "knit",
  "get better",
  "get well",
  "be on the road to recovery",
  "be well",
  "be cured",
  "be all right",
  "draw together",
  "worsen",
  "make up",
  "sort out",
  "rectify",
  "remedy",
  "right",
  "redress",
  "resolve",
  "square",
  "settle",
  "correct",
  "amend",
  "emend",
  "retrieve",
  "improve",
  "better",
  "make good",
  "ameliorate",
  "reform",
  "put/set right",
  "set straight",
  "straighten out",
  "put in order",
  "put to rights",
  "make better",
  "make worse",
];
