export const definitions = ['"menial factory jobs"'];
export const synonyms = [
  "unskilled",
  "lowly",
  "humble",
  "low-grade",
  "low-status",
  "routine",
  "humdrum",
  "boring",
  "dull",
  "degrading",
  "mean",
  "inferior",
  "unworthy",
  "blue-collar",
  "noble",
  "elevated",
  "skilled",
  "servant",
  "domestic",
  "drudge",
  "galley slave",
  "laborer",
  "minion",
  "junior",
  "slave",
  "underling",
  "subordinate",
  "inferior",
  "hireling",
  "vassal",
  "serf",
  "lackey",
  "flunkey",
  "factotum",
  "stooge",
  "hewers of wood and drawers of water",
  "scullion",
  "servitor",
  "domestic servant",
  "maid of all work",
  "master",
];
