export const definitions = [
  '"composers of outstanding merit"',
  '"the relative merits of both approaches have to be considered"',
  '"if you expect to pass, why not go for a merit or a distinction?"',
  '"a plaintiff who has a good arguable case on the merits"',
  '"the results have been encouraging enough to merit further investigation"',
];
export const synonyms = [
  "excellence",
  "goodness",
  "standard",
  "quality",
  "level",
  "grade",
  "caliber",
  "worth",
  "good",
  "credit",
  "eminence",
  "worthiness",
  "value",
  "virtue",
  "distinction",
  "account",
  "deservingness",
  "meritoriousness",
  "high quality",
  "inferiority",
  "strong point",
  "advantage",
  "benefit",
  "value",
  "profit",
  "asset",
  "plus",
  "advisability",
  "good point",
  "advantageousness",
  "fault",
  "disadvantage",
  "deserve",
  "earn",
  "warrant",
  "rate",
  "justify",
  "be deserving of",
  "be worthy of",
  "be worth",
  "be entitled to",
  "have a right to",
  "have a claim to/on",
  "be qualified for",
];
