export const definitions = [
  '"a method for software maintenance"',
  '"labor-intensive production methods"',
  '"historical study is the rigorous combination of knowledge and method"',
  '"Paula was at least hip to the Method"',
  '"reliance on Method technique"',
];
export const synonyms = [
  "procedure",
  "technique",
  "system",
  "practice",
  "routine",
  "modus operandi",
  "formula",
  "process",
  "means",
  "medium",
  "mechanism",
  "tack",
  "approach",
  "way",
  "line",
  "course of action",
  "route",
  "road",
  "strategy",
  "tactic",
  "plan",
  "recipe",
  "rule",
  "method of working",
  "order",
  "orderliness",
  "organization",
  "arrangement",
  "structure",
  "form",
  "system",
  "logic",
  "planning",
  "plan",
  "design",
  "purpose",
  "pattern",
  "routine",
  "discipline",
  "chaos",
  "disorder",
];
