export const definitions = ['"Diana passed the test with aplomb"'];
export const synonyms = [
  "poise",
  "self-assurance",
  "assurance",
  "self-possession",
  "self-confidence",
  "calmness",
  "composure",
  "collectedness",
  "presence of mind",
  "level-headedness",
  "sangfroid",
  "equilibrium",
  "equanimity",
  "nerve",
  "nonchalance",
  "savoir faire",
  "savoir vivre",
  "gaucheness",
];
