export const definitions = [
  '"an escrow account"',
  '"the board holds funds in escrow"',
  '"those funds are escrowed for the purpose of improving municipal services"',
];
export const synonyms = [
  "care",
  "guardianship",
  "charge",
  "keeping",
  "safe keeping",
  "wardship",
  "ward",
  "responsibility",
  "protection",
  "guidance",
  "tutelage",
  "custodianship",
  "trusteeship",
  "trust",
  "keep",
  "possession",
  "hands",
  "supervision",
  "superintendence",
  "surveillance",
  "control",
  "aegis",
  "auspices",
];
