export const definitions = ['"conflict is the essence of drama"'];
export const synonyms = [
  "quintessence",
  "soul",
  "spirit",
  "ethos",
  "nature",
  "life",
  "lifeblood",
  "core",
  "heart",
  "center",
  "crux",
  "nub",
  "nucleus",
  "kernel",
  "marrow",
  "meat",
  "pith",
  "gist",
  "substance",
  "principle",
  "reality",
  "actuality",
  "quiddity",
  "esse",
  "central part",
  "fundamental quality",
  "basic quality",
  "essential part",
  "intrinsic nature",
  "sum and substance",
  "extract",
  "concentrate",
  "concentration",
  "quintessence",
  "distillate",
  "elixir",
  "abstraction",
  "decoction",
  "juice",
  "tincture",
  "solution",
  "suspension",
  "dilution",
  "scent",
  "perfume",
];
