export const definitions = [
  '"bake until the top is crisp and bubbly"',
  '"a bright and bubbly personality"',
  '"I\'ll get us a little bottle of bubbly"',
];
export const synonyms = [
  'sparkling',
  'fizzy',
  'carbonated',
  'aerated',
  'effervescent',
  'gassy',
  'frothy',
  'foamy',
  'bubbling',
  'sudsy',
  'pétillant',
  'spumante',
  'frizzante',
  'Perl-',
  '(vin) mousseux',
  'Schaum-',
  'still',
  'flat',
  'vivacious',
  'animated',
  'ebullient',
  'lively',
  'spirited',
  'high-spirited',
  'scintillating',
  'vibrant',
  'zestful',
  'energetic',
  'dynamic',
  'bubbling',
  'effervescent',
  'sparkling',
  'bouncy',
  'buoyant',
  'carefree',
  'happy-go-lucky',
  'excited',
  'elated',
  'merry',
  'happy',
  'cheerful',
  'cheery',
  'perky',
  'sunny',
  'airy',
  'breezy',
  'bright',
  'enthusiastic',
  'full of life',
  'bright and breezy',
  'dull',
  'listless',
  'champagne',
  'mousseux',
  'spumante',
  'cava',
  'sparkling wine',
  'perlé',
];