export const definitions = [
  '"keep within the household budget"',
  '"a budget deficit"',
  '"they have a limited budget"',
  '"the university is budgeting for a deficit"',
  '"corporate planning and budgeting"',
  '"the council proposes to budget $100,000 to provide grants"',
  '"a budget guitar"',
  ,
];
export const synonyms = [
  "forecast",
  "accounts",
  "statement",
  "spreadsheet",
  "financial plan",
  "financial estimate",
  "financial blueprint",
  "prediction of revenue and expenditure",
  "allowance",
  "allocation",
  "allotment",
  "quota",
  "share",
  "ration",
  "helping",
  "lot",
  "slice",
  "grant",
  "award",
  "funds",
  "means",
  "resources",
  "wherewithal",
  "capital",
  "allocate",
  "allot",
  "assign",
  "allow",
  "earmark",
  "devote",
  "designate",
  "appropriate",
  "set aside",
  "award",
  "grant",
  "allocation",
  "allotment",
  "issuing",
  "issuance",
  "awarding",
  "grant",
  "granting",
  "administration",
  "earmarking",
  "designation",
  "budgeting",
  "apportionment",
  "distribution",
  "dispensation",
  "setting aside",
  "sharing out",
  "handing out",
  "dealing out",
  "doling out",
  "giving out",
  "dishing out",
  "parceling out",
  "rationing out",
  "dividing out",
  "dividing up",
  "measuring out",
  "meting out",
  "cheap",
  "inexpensive",
  "economy",
  "economic",
  "economical",
  "low-cost",
  "low-price",
  "low-budget",
  "reasonable",
  "cut-price",
  "cut-rate",
  "discount",
  "discounted",
  "bargain",
  "bargain-basement",
  "reasonably priced",
  "expensive",
];
