export const definitions = [
  '"a cold buffet lunch"',
  '"the rough seas buffeted the coast"',
  '"the wind was buffeting at their bodies"',
  '"he was buffeted from side to side"',
  '"they were buffeted by a major recession"',
  '"the daily buffets of urban civilization"',
  '"fifteen degrees of flap induce marked buffet"',
];
export const synonyms = [
  'self-service',
  'smorgasbord',
  'cold table',
  'cold meal',
  'cafe',
  'cafeteria',
  'snack bar',
  'canteen',
  'salad bar',
  'restaurant',
  'refreshment stall/counter',
  'sideboard',
  'cabinet',
  'counter',
  'china cupboard',
  'batter',
  'pound',
  'lash',
  'strike',
  'hit',
  'bang',
  'beat/knock/dash against',
  'push against',
  'afflict',
  'trouble',
  'harm',
  'distress',
  'burden',
  'bother',
  'beset',
  'harass',
  'worry',
  'oppress',
  'strain',
  'stress',
  'tax',
  'torment',
  'blight',
  'bedevil',
  'harrow',
  'cause trouble to',
  'cause suffering to',
  'shock',
  'jolt',
  'jar',
  'upset',
  'setback',
  'crisis',
  'catastrophe',
  'blow',
  'misfortune',
  'trouble',
  'problem',
  'difficulty',
  'hardship',
  'adversity',
  'distress',
  'disaster',
  'misadventure',
  'affliction',
  'sorrow',
  'misery',
  'tribulation',
  'woe',
  'pain',
  'tragedy',
  'calamity',
  'vicissitude',
  'trial',
  'cross',
  'burden',
];