export const definitions = [
  '"their offices, homes, and telephones were bugged"',
  '"she fears that her conversations were bugged"',
  '"a persistent reporter was bugging me"',
  ,
];
export const synonyms = [
  'eavesdrop',
  'spy',
  'overhear',
  'tap',
  'wiretap',
  'monitor',
  'record',
  'tap',
  'overhear',
  'wiretap',
  'monitor',
  'listen in on',
  'eavesdrop on',
  'spy on',
  'phone-tap',
  'annoy',
  'irritate',
  'vex',
  'anger',
  'exasperate',
  'irk',
  'gall',
  'pique',
  'put out',
  'displease',
  'antagonize',
  'get on someone\'s nerves',
  'ruffle',
  'ruffle someone\'s feathers',
  'make someone\'s hackles rise',
  'enrage',
  'infuriate',
  'madden',
  'make someone\'s blood boil',
  'goad',
  'provoke',
  'exacerbate',
  'hump',
  'rasp',
  'make angry',
  'make cross',
  'get/put someone\'s back up',
  'rub up the wrong way',
  'raise someone\'s hackles',
  'drive to distraction',
  'please',
  'gratify',
];
