export const definitions = [
  '"the ironworks were built in 1736"',
  '"the county council plans to build a bypass"',
  '"you can build database applications without writing any code"',
  '"we built up confidence in our abilities"',
  '"the air of excited anticipation builds"',
  '"they need to build a strong relationship with journal users"',
  '"people scrimp and save to build a better life for their children"',
  '"she was of medium height and slim build"',
  '"he has the ideal build for a sprinter"',
  '"the car\'s high specification and impressive build quality"',
  '"a beta build of the program"',
  ,
];
export const synonyms = [
  "construct",
  "erect",
  "put up",
  "assemble",
  "set up",
  "raise",
  "make",
  "fabricate",
  "form",
  "manufacture",
  "create",
  "fashion",
  "model",
  "mold",
  "shape",
  "forge",
  "demolish",
  "boost",
  "strengthen",
  "increase",
  "improve",
  "invigorate",
  "augment",
  "raise",
  "intensify",
  "enhance",
  "escalate",
  "multiply",
  "swell",
  "establish",
  "found",
  "set up",
  "originate",
  "institute",
  "start",
  "begin",
  "inaugurate",
  "initiate",
  "constitute",
  "secure",
  "form",
  "create",
  "organize",
  "develop",
  "expand",
  "enlarge",
  "put in place",
  "bring into being",
  "physique",
  "frame",
  "body",
  "figure",
  "form",
  "structure",
  "shape",
  "makeup",
  "formation",
  "stature",
  "proportions",
  "pattern",
  "form",
  "shape",
  "format",
  "structure",
  "configuration",
  "construction",
  "frame",
  "model",
  "design",
  "arrangement",
  "organization",
  "formation",
  "figure",
  "cast",
  "kind",
  "brand",
  "make",
  "line",
  "type",
  "cut",
  "style",
  "archetype",
  "paradigm",
  "prototype",
];
