export const definitions = [
  '"the veins in his neck bulged"',
  '"a briefcase bulging with documents"',
];
export const synonyms = [
  'swell',
  'stick out',
  'balloon',
  'fill out',
  'bag',
  'belly',
  'project',
  'protrude',
  'stand out',
  'expand',
  'inflate',
  'distend',
  'dilate',
  'enlarge',
  'bloat',
  'intumesce',
  'tumefy',
  'swell out',
  'puff up/out',
  'balloon up/out',
  'jut (out)',
  'be prominent',
  'contract',
];