export const definitions = [
  '"territorial questions bulked large in diplomatic relations"',
  '"traders were bulking up their flour with chalk"',
  ,
];
export const synonyms = [
  "dominate",
  "preponderate",
  "count",
  "matter",
  "signify",
  "carry weight",
  "be important",
  "loom large",
  "be prominent",
  "be significant",
  "be influential",
  "be of consequence",
  "be of account",
  "be relevant",
  "mean a lot",
  "be insignificant",
  "expand",
  "fill out",
  "add to",
  "augment",
  "increase",
  "make bigger",
  "make larger",
  "pad out",
  "eke out",
];
