export const definitions = [
  '"the party was a real bummer"',
  '"You lost your wallet? Bummer!"',
];
export const synonyms = [
  "disaster",
  "calamity",
  "catastrophe",
  "cataclysm",
  "devastation",
  "misfortune",
  "misadventure",
  "mishap",
  "reverse",
  "vicissitude",
  "setback",
  "trial",
  "tribulation",
  "affliction",
  "blight",
  "injury",
  "adversity",
  "shock",
  "blow",
  "pain",
  "sorrow",
  "misery",
  "distress",
  "agony",
  "unhappiness",
  "sadness",
  "disappointment",
  "sad event",
  "serious accident",
  "fortune",
  "joy",
];
