export const definitions = [
  '"she started the car with a jerk and hit the bumper of the car in front"',
  '"a bumper crop"',
];
export const synonyms = [
  "abundant",
  "rich",
  "heavy",
  "healthy",
  "bountiful",
  "goodly",
  "large",
  "big",
  "huge",
  "immense",
  "massive",
  "exceptional",
  "unusual",
  "good",
  "excellent",
  "fine",
  "magnificent",
  "lovely",
  "vintage",
  "superabundant",
  "prolific",
  "profuse",
  "copious",
  "profitable",
  "bounteous",
  "plenteous",
  "poor",
  "meager",
  "disastrous",
];
