export const definitions = [
  '"a stream burbled through the woods"',
  '"he burbled on about annuities"',
  '"he was burbling inanities"',
  '"the air no longer flows smoothly over the wing but burbles and slows down, decreasing lift"',
  '"the steady burble of running water"',
  '"an hour of boring burble"',
];
export const synonyms = [
  "gurgle",
  "bubble",
  "murmur",
  "purr",
  "purl",
  "tinkle",
  "whir",
  "drone",
  "rumble",
  "buzz",
  "hum",
  "plash",
  "prattle",
  "blather",
  "blether",
  "blither",
  "gabble",
  "prate",
  "drivel",
  "ramble",
  "maunder",
  "go on",
  "run on",
  "chatter",
  "yap",
  "gossip",
  "talk nineteen to the dozen",
  "twaddle",
  "clack",
  "babble (on)",
  "rattle on/away",
  "talk at length",
  "talk incessantly",
  "talk a lot",
  "slabber on",
  "twattle",
  "claver",
  "babble",
  "purl",
  "gurgle",
  "plash",
  "saga",
  "yarn",
  "recitation",
  "burbling",
  "maundering",
  "shaggy-dog story",
  "lengthy story/explanation",
];
