export const definitions = [
  '"buried treasure"',
  '"for many, music is a gateway to unlocking buried emotions"',
  '"what buried secrets could possibly prompt this severe a self-punishment?"',
  '"he buried the box in the back garden"',
  '"he was buried in Arlington National Cemetery"',
  '"she buried her sixty-year-old husband"',
  '"the countryside has been buried under layers of concrete"',
  '"the warehouse was buried in the faceless sprawl of the city"',
  '"she buried her face in her hands"',
  '"with his hands buried in the pockets of his overcoat"',
  '"they had buried their feelings of embarrassment and fear"',
  '"losses that would bury multiple businesses"',
  '"he buried himself in work"',
];
export const synonyms = [
  'inter',
  'entomb',
  'sepulcher',
  'inhume',
  'lay to rest',
  'consign to the grave',
  'earth up',
  'ensepulcher',
  'inearth',
  'exhume',
  'hide',
  'conceal',
  'cover',
  'secrete',
  'enfold',
  'submerge',
  'sink',
  'embed',
  'engulf',
  'immerse',
  'enclose',
  'tuck',
  'cup',
  'enshroud',
  'put out of sight',
  'reveal',
  'take out of',
  'hide',
  'cover up',
  'disguise',
  'dissemble',
  'mask',
  'veil',
  'draw a veil over',
  'gloss over',
  'suppress',
  'repress',
  'bottle up',
  'keep secret',
  'keep quiet about',
  'keep dark',
  'hush up',
  'sweep under the carpet',
  'show',
  'disclose',
  'confess',
  'absorb',
  'engross',
  'occupy',
  'engage',
  'busy',
  'employ',
  'distract',
  'preoccupy',
  'immerse',
  'interest',
  'involve',
];