export const definitions = [
  '"he had been too busy to enjoy himself"',
  '"there was enough work to keep two people busy"',
  '"the team members are busy raising money"',
  '"he was busy with preparations"',
  '"they papered the bedroom with a busy pattern of satyrs and dryads"',
];
export const synonyms = [
  "hard-pressed",
  "time-poor",
  "on the job",
  "lively",
  "industrious",
  "bustling",
  "energetic",
  "tireless",
  "have one's hands full",
  "occupied (in)",
  "engaged in",
  "involved in",
  "employed in",
  "working at",
  "laboring at",
  "toiling at",
  "slaving at",
  "hard at work (on)",
  "wrapped up (in/with)",
  "rushed off one's feet(with) ",
  "at work (on)",
  "absorbed in",
  "engrossed in",
  "immersed in",
  "preoccupied with",
  "active (in)",
  "idle",
  "hard-pressed",
  "time-poor",
  "on the job",
  "lively",
  "industrious",
  "bustling",
  "energetic",
  "tireless",
  "have one's hands full",
  "occupied (in)",
  "engaged in",
  "involved in",
  "employed in",
  "working at",
  "laboring at",
  "toiling at",
  "slaving at",
  "hard at work (on)",
  "wrapped up (in/with)",
  "rushed off one's feet(with) ",
  "at work (on)",
  "absorbed in",
  "engrossed in",
  "immersed in",
  "preoccupied with",
  "active (in)",
  "idle",
  "strenuous",
  "hectic",
  "energetic",
  "active",
  "lively",
  "exacting",
  "tiring",
  "full",
  "eventful",
  "crowded",
  "bustling",
  "swarming",
  "teeming",
  "astir",
  "buzzing",
  "thronged",
  "thronging",
  "vibrant",
  "quiet",
  "overornate",
  "overelaborate",
  "over-embellished",
  "overdecorated",
  "overblown",
  "overripe",
  "overwrought",
  "exaggerated",
  "overdone",
  "florid",
  "fussy",
  "cluttered",
  "contrived",
  "overworked",
  "over-detailed",
  "strained",
  "labored",
  "baroque",
  "rococo",
  "excessively ornate",
  "quiet",
  "restrained",
  "unavailable",
  "engaged",
  "occupied",
  "working",
  "at work",
  "on duty",
  "in harness",
  "otherwise engaged",
  "in a meeting",
  "on active service",
  "have a prior/previous engagement",
  "free",
];
