export const definitions = [
  '"I caught a bus"',
  '"together they get on the bus"',
  '"a bus service"',
  '"managerial staff was bused in and out of the factory"',
  '"I\'d never bused so many dishes in one night"',
  '"Chad buses tables on weekends"',
  '"he bussed her on the cheek"',
];
export const synonyms = [
  "minibus",
  "van",
  "motor coach",
  "omnibus",
  "charabanc",
  "greyhound",
  "air kiss",
  "French kiss",
  "soul kiss",
  "X",
  "osculation",
  "air-kiss",
  "osculate",
  "plant a kiss on",
  "brush one's lips against",
  "blow a kiss to",
];
