export const definitions = [
  '"people clutching clipboards bustled about"',
  '"she bustled us into the kitchen"',
  '"the small harbor bustled with boats"',
  '"all the noise and the traffic and the bustle"',
];
export const synonyms = [
  "rush",
  "dash",
  "scurry",
  "scuttle",
  "scamper",
  "scramble",
  "flutter",
  "fuss",
  "hurry",
  "hasten",
  "make haste",
  "race",
  "run",
  "sprint",
  "tear",
  "shoot",
  "charge",
  "chase",
  "career",
  "scutter",
  "amble",
  "hustle",
  "bundle",
  "sweep",
  "push",
  "hurry",
  "rush",
  "whisk",
  "whip",
  "activity",
  "animation",
  "commotion",
  "flurry",
  "tumult",
  "hubbub",
  "busyness",
  "action",
  "liveliness",
  "movement",
  "life",
  "stir",
  "excitement",
  "agitation",
  "fuss",
  "whirl",
  "hurry-scurry",
  "pother",
  "hustle and bustle",
  "inactivity",
];
