export const definitions = [
  '"a blouse with five ______s in front"',
  '"______ thread"',
  '"chocolate ______s"',
  '"I ______ed my shirt and knotted my tie"',
  '"he ______ed up his jacket"',
  '"he ______ed himself into the raincoat"',
  '"a dress that ______ed down the front"',
];
export const synonyms = [
  'fastener',
  'stud',
  'link',
  'toggle',
  'hook',
  'catch',
  'clasp',
  'knob',
  'switch',
  'disk',
  'lever',
  'handle',
  'key',
  'control',
  'controller',
  'on/off switch',
  'push switch',
  'pin',
  'brooch',
  'breastpin',
  'hold one\'s tongue',
  'say no more',
  'dry up',
  'quieten',
  'quiet',
  'be quiet',
  'keep/stay quiet',
  'be/keep/stay silent',
  'keep one\'s lips sealed',
  'stop talking',
  'fall silent',
  'quieten down',
  'quiet down',
  'speak up',
];
