export const definitions = [
  '"she butted him in the chest"',
  '"he butts his head against a wall"',
  '"the church butted up against the row of houses"',
  '"a garden that butted up to the neighbor\'s"',
  '"the floorboards will be butted up against each other to make tight seams"',
  ,
];
export const synonyms = [
  "ram",
  "headbutt",
  "bunt",
  "bump",
  "buffet",
  "push",
  "thrust",
  "shove",
  "prod",
  "knock",
  "tup",
  "ram",
  "headbutt",
  "bunt",
  "bump",
  "buffet",
  "push",
  "thrust",
  "shove",
  "prod",
  "knock",
  "tup",
  "adjoin",
  "abut",
  "neighbor",
  "join",
  "conjoin",
  "touch",
  "meet",
  "butt up to",
  "be next to",
  "be adjacent to",
  "border (on)",
  "verge on",
  "bound on",
  "be contiguous with",
  "be connected to",
  "communicate with",
  "link up with",
  "extend as far as",
  "extend to",
  "connect with/to",
  "be separate from",
];
