export const definitions = [
  '"after just one drink, I was buzzed"',
  '"mosquitoes were buzzing all around us"',
  '"this amp is loud enough to make my ears buzz for a couple of hours on full blast"',
  '"he buzzed the stewardesses every five minutes"',
  '"the electric bell began to buzz for closing time"',
  '"he buzzed me on the car phone"',
  '"she buzzed along the highway back into town"',
  '"helicopter gunships were sent to buzz the villages"',
  '"the club is buzzing with excitement"',
  '"twenty-four hours later Mark was still buzzing"',
];
export const synonyms = [
  "hum",
  "drone",
  "bumble",
  "whir",
  "fizz",
  "fuzz",
  "hiss",
  "sing",
  "murmur",
  "whisper",
  "bombinate",
  "susurrate",
  "sibilate",
  "bombilate",
  "purr",
  "sound",
  "reverberate",
  "ring",
  "beep",
  "bleep",
  "warble",
  "phone",
  "call",
  "get",
  "reach",
  "dial",
  "ring up",
  "ring",
  "get someone on the phone",
  "get on the phone to",
  "make/place a call to",
  "give someone a ring",
  "bustle",
  "scurry",
  "scuttle",
  "scramble",
  "scamper",
  "flutter",
  "fuss",
  "hurry",
  "hasten",
  "make haste",
  "rush",
  "race",
  "dash",
  "run",
  "sprint",
  "tear",
  "shoot",
  "charge",
  "chase",
  "career",
  "scutter",
  "bustle",
  "hum",
  "throb",
  "vibrate",
  "pulse",
  "whirl",
  "have an air of",
  "be active",
  "be lively",
  "be busy",
  "be bustling",
];
