export const definitions = [
  '"the entire sales force ______ed the conference"',
  '"she was unable to ______ the wedding"',
  '"all children are required to ______ school"',
  '"he muttered that he had business to ______ to"',
  '"the severely wounded had two medics to ______ to their wounds"',
  '"each of the beds in the intensive care unit is ______ed by a nurse"',
  '"Alice hadn\'t ______ed to a word of his sermon"',
  '"Her Royal Highness was ______ed by two capable women"',
  '"people feared that the switch to a peacetime economy would be ______ed by a severe slump"',
];
export const synonyms = [
  "visit",
  "go to",
  "frequent",
  "haunt",
  "patronize",
  "be present at",
  "be at",
  "be there at",
  "sit in on",
  "take part in",
  "appear at",
  "put in an appearance at",
  "make an appearance at",
  "present oneself at",
  "turn up at",
  "pay a visit to",
  "miss",
  "see to",
  "address",
  "manage",
  "organize",
  "orchestrate",
  "sort out",
  "handle",
  "take care of",
  "take up",
  "undertake",
  "tackle",
  "deal with",
  "cope with",
  "make arrangements for",
  "take charge of",
  "take responsibility for",
  "take in hand",
  "take forward",
  "give one's attention to",
  "apply oneself to",
  "neglect",
  "look after",
  "take care of",
  "keep an eye on",
  "see to",
  "tend",
  "treat",
  "nurse",
  "help",
  "aid",
  "assist",
  "succor",
  "nurture",
  "mind",
  "care for",
  "minister to",
  "administer to",
  "listen",
  "lend an ear",
  "take into consideration",
  "heed",
  "respect",
  "follow",
  "observe",
  "notice",
  "mark",
  "hearken",
  "regard",
  "pay attention",
  "pay heed",
  "be attentive",
  "concentrate on",
  "take note of",
  "bear in mind",
  "give thought to",
  "be heedful of",
  "give ear",
  "disregard",
  "ignore",
  "escort",
  "accompany",
  "guard",
  "chaperone",
  "squire",
  "convoy",
  "guide",
  "lead",
  "conduct",
  "usher",
  "shepherd",
  "follow",
  "shadow",
  "assist",
  "help",
  "serve",
  "wait on",
  "be accompanied by",
  "be associated with",
  "be connected with",
  "be linked with",
  "go hand in hand with",
  "occur with",
  "co-occur with",
  "coexist with",
  "be produced by",
  "be brought about by",
  "originate from",
  "originate in",
  "stem from",
  "result from",
  "be a result of",
  "arise from",
  "follow on from",
  "be a consequence of",
];
