export const definitions = [
  '"his status is attested by his recent promotion"',
  '"his numerous drawings of ships attest to his fascination with them"',
  '"I can attest to his tremendous energy"',
  '"the deceased\'s attorney attested that he had been about to institute divorce proceedings"',
  '"the witnesses must attest and sign the will in the testa\'s \'s presence"',
];
export const synonyms = [
  'indicate',
  'show',
  'reveal',
  'display',
  'exhibit',
  'manifest',
  'denote',
  'evince',
  'signify',
  'verify',
  'confirm',
  'prove',
  'substantiate',
  'endorse',
  'back up',
  'support',
  'bear out',
  'give credence to',
  'be evidence of',
  'testify to',
  'attest to',
  'disprove',
  'declare',
  'maintain',
  'contend',
  'argue',
  'state',
  'claim',
  'propound',
  'submit',
  'posit',
  'postulate',
  'adduce',
  'move',
  'advocate',
  'venture',
  'volunteer',
  'aver',
  'proclaim',
  'announce',
  'pronounce',
  'affirm',
  'protest',
  'profess',
  'swear',
  'insist',
  'avow',
  'opine',
  'asseverate',
  'certify',
  'corroborate',
  'confirm',
  'verify',
  'substantiate',
  'document',
  'authenticate',
  'evidence',
  'demonstrate',
  'evince',
  'display',
  'exhibit',
  'show',
  'manifest',
  'prove',
  'endorse',
  'back up',
  'support',
  'guarantee',
  'affirm',
  'aver',
  'swear to',
  'bear witness to',
  'bear out',
  'give credence to',
  'asseverate',
  'give proof of',
  'provide evidence of',
  'testify to',
  'vouch for',
  'depose to',
  'disprove',
];