export const definitions = [
  '"this exercise helps to flatten a flabby stomach"',
  '"the quartet playing was uncommitted and flabby"',
];
export const synonyms = [
  "soft",
  "loose",
  "flaccid",
  "yielding",
  "slack",
  "lax",
  "drooping",
  "droopy",
  "sagging",
  "saggy",
  "pendulous",
  "limp",
  "unfirm",
  "out of tone",
  "firm",
  "taut",
  "fat",
  "fleshy",
  "overweight",
  "plump",
  "chubby",
  "portly",
  "rotund",
  "meaty",
  "broad in the beam",
  "obese",
  "corpulent",
  "bloated",
  "gross",
  "of ample proportions",
  "thin",
  "lean",
];
