export const definitions = [
  '"a public relations flack"',
  '"a crass ambulance-chaser who flacks himself in TV ads"',
  '"the local news media shamelessly flack for the organizing committee"',
];
export const synonyms = [
  "publicize",
  "bill",
  "post",
  "announce",
  "broadcast",
  "proclaim",
  "trumpet",
  "call attention to",
  "promulgate",
  "promote",
  "market",
  "merchandise",
  "peddle",
  "display",
  "tout",
  "build up",
  "trail",
  "trailer",
  "make public",
  "make known",
  "give publicity to",
  "shout from the rooftops",
  "give notice of",
  "beat/bang the drum for",
];
