export const definitions = [
  '"the yoghurt comes in eight fruit flavors"',
  '"adding sun-dried tomatoes gives the sauce extra flavor"',
  '"no other cracker adds so much flavor to the cheese"',
  '"we use vanilla and almond flavors"',
  '"the extracts give a flavor of the content and tone of the conversation"',
  '"whitewashed walls and red pantiles gave the resort a Mediterranean flavor"',
  '"various flavors of firewall are evolving"',
  '"chunks of chicken flavored with herbs"',
  '"they use a wide range of spices to flavor their foods"',
  '"the faint exasperation that had flavored her tone"',
];
export const synonyms = [
  "taste",
  "savor",
  "tang",
  "relish",
  "palate",
  "flavoring",
  "seasoning",
  "tastiness",
  "tanginess",
  "interest",
  "bite",
  "piquancy",
  "pungency",
  "smack",
  "spice",
  "spiciness",
  "sharpness",
  "zest",
  "raciness",
  "edge",
  "sapor",
  "blandness",
  "season",
  "enrich",
  "enliven",
  "add flavor to",
  "add flavoring to",
  "spice (up)",
  "add seasoning/herbs/spices to",
  "add piquancy to",
  "ginger up",
  "liven up",
];
