export const definitions = [
  '"she flinched at the acidity in his voice"',
  '"he had faced death without flinching"',
  '"I rarely flinch from a fight when I\'m sure of myself"',
  '"\"Don\'t call me that,\" he said with a flinch"',
];
export const synonyms = [
  'wince',
  'start',
  'recoil',
  'shrink',
  'pull back',
  'back away',
  'draw back',
  'withdraw',
  'blench',
  'cringe',
  'squirm',
  'quiver',
  'shudder',
  'shiver',
  'tremble',
  'quake',
  'shake',
  'quail',
  'cower',
  'waver',
  'falter',
  'hesitate',
  'blanch',
  'shy (away)',
  'shy away',
  'get cold feet',
  'stand firm',
  'shrink',
  'recoil',
  'turn away',
  'swerve',
  'hang back',
  'demur',
  'dodge',
  'evade',
  'avoid',
  'duck',
  'fight shy of',
  'shy away',
  'balk at',
  'jib at',
  'quail at',
  'jerk',
  'twitch',
  'wince',
  'spasm',
  'convulsion',
  'jump',
];