export const definitions = [
  '"it amused him to flirt with her"',
  '"a painter who had flirted briefly with Cubism"',
  '"the need of some individuals to flirt with death"',
  '"a moorhen stepped out of the reeds, flirting its white tail"',
  '"the lark was flirting around the site"',
  '"Jim was an outrageous flirt"',
];
export const synonyms = [
  "tease",
  "lead on",
  "court",
  "woo",
  "trifle with",
  "toy with",
  "philander with",
  "dally with",
  "make romantic advances to",
  "set one's cap at",
  "play with",
  "consider",
  "dabble in",
  "toy with",
  "trifle with",
  "amuse oneself with",
  "entertain the idea/possibility of",
  "give thought to",
  "putter around with",
  "tinker with",
  "dip into",
  "scratch the surface of",
  "court",
  "risk",
  "make light of",
  "dice with",
  "not be afraid of",
  "treat frivolously",
  "tease",
  "coquette",
  "heartbreaker",
  "trifler",
  "philanderer",
  "seductress",
  "siren",
  "femme fatale",
  "Mata Hari",
  "Delilah",
  "enchantress",
  "sorceress",
  "Circe",
  "gallant",
  "Lorelei",
  "fizgig",
];
