export const definitions = [
  '"elegant floaty dresses"',
  '"she plopped down on a pool floatie"',
  '"the one-year-old girl was in the pool wearing floaties"',
];
export const synonyms = [
  "ultra-fine",
  "fine",
  "diaphanous",
  "gauzy",
  "gauze-like",
  "gossamer-thin",
  "gossamery",
  "delicate",
  "filmy",
  "cobwebby",
  "feathery",
  "silky",
  "silken",
  "wispy",
  "thin",
  "light",
  "lightweight",
  "insubstantial",
  "papery",
  "flimsy",
  "frail",
  "translucent",
  "transparent",
  "see-through",
  "sheer",
  "transpicuous",
  "gossamer-like",
  "chiffony",
  "translucid",
  "heavy",
  "opaque",
];
