export const definitions = [
  '"I stopped to buy Bridget some flowers"',
  '"the roses were just coming into flower"',
  '"the flower of college track athletes"',
  '"a young policeman in the flower of his life gunned down"',
  '"all right then, flower?"',
  '"these daisies can flower as late as October"',
  '"it is there that the theory of deconstruction has flowered most extravagantly"',
];
export const synonyms = [
  "bloom",
  "blossom",
  "floweret",
  "floret",
  "best",
  "finest",
  "top",
  "pick",
  "choice",
  "choicest",
  "prime",
  "cream",
  "prize",
  "treasure",
  "pearl",
  "gem",
  "jewel",
  "the jewel in the crown",
  "first class",
  "elite",
  "elect",
  "the crème de la crème",
  "dregs",
  "bloom",
  "appear",
  "open",
  "come into bloom",
  "wither",
];
