export const definitions = [];
export const synonyms = [
  "lackey",
  "steward",
  "butler",
  "footman",
  "valet",
  "retainer",
  "attendant",
  "factotum",
  "houseboy",
  "page",
  "liveried manservant",
  "liveried servant",
  "minion",
  "lackey",
  "hireling",
  "subordinate",
  "underling",
  "servant",
  "retainer",
  "vassal",
  "puppet",
  "spaniel",
  "pawn",
  "tool",
  "creature",
  "instrument",
  "cat's paw",
];
