export const definitions = [
  '"they graveled the road"',
  '"this was a bad strike, and it graveled him to involve himself in it"',
  '"the wisest doctor is graveled by the inquisitiveness of a child"',
];
export const synonyms = [
  "shingle",
  "grit",
  "pebbles",
  "stones",
  "annoy",
  "vex",
  "anger",
  "exasperate",
  "bother",
  "irk",
  "gall",
  "pique",
  "put out",
  "displease",
  "antagonize",
  "get on someone's nerves",
  "ruffle",
  "ruffle someone's feathers",
  "make some's 's hackles rise",
  "enrage",
  "infuriate",
  "madden",
  "incense",
  "make someone's blood boil",
  "goad",
  "provoke",
  "exacerbate",
  "hump",
  "rasp",
  "make angry",
  "make cross",
  "get/put someone's back up",
  "rub up the wrong way",
  "try someone's patience",
  "raise some's 's hackles",
  "drive to distraction",
  "pacify",
  "perplex",
  "confuse",
  "bewilder",
  "bemuse",
  "baffle",
  "mystify",
  "confound",
  "nonplus",
  "throw",
  "wilder",
  "maze",
  "pose",
  "obfuscate",
  "set someone thinking",
];
