export const definitions = [
  '"greedy thieves who plundered a defense contractor"',
];
export const synonyms = [
  "avaricious",
  "acquisitive",
  "covetous",
  "rapacious",
  "grasping",
  "venal",
  "materialistic",
  "mercenary",
  "predatory",
  "usurious",
  "possessive",
  "grabbing",
  "hoarding",
  "Scroogelike",
  "pleonectic",
  "eager",
  "avid",
  "hungry",
  "craving",
  "longing",
  "yearning",
  "hankering",
  "thirsty",
  "pining",
  "enthusiastic",
  "impatient",
  "anxious",
  "cupidinous",
  "Mammonish",
  "Mammonistic",
  "desirous of",
  "generous",
  "altruistic",
  "indifferent",
  "gluttonous",
  "ravenous",
  "ravening",
  "voracious",
  "gourmandizing",
  "gourmand",
  "intemperate",
  "self-indulgent",
  "insatiable",
  "insatiate",
  "wolfish",
  "esurient",
  "edacious",
  "gannet-like",
  "have eyes bigger than one's stomach",
  "temperate",
  "ascetic",
];
