export const definitions = [
  '"she was overcome with grief"',
  '"time heals griefs and quarrels"',
  '"we were too tired to cause any grief"',
];
export const synonyms = [
  'sorrow',
  'misery',
  'sadness',
  'anguish',
  'pain',
  'distress',
  'agony',
  'torment',
  'affliction',
  'suffering',
  'heartache',
  'heartbreak',
  'broken-heartedness',
  'woe',
  'desolation',
  'despondency',
  'dejection',
  'despair',
  'angst',
  'mortification',
  'mourning',
  'mournfulness',
  'bereavement',
  'lamentation',
  'lament',
  'remorse',
  'regret',
  'pining',
  'dolour',
  'dole',
  'heaviness of heart',
  'joy',
  'trouble',
  'annoyance',
  'bother',
  'irritation',
  'vexation',
  'harassment',
  'nuisance',
];