export const definitions = [
  '"her eyes felt gritty"',
  '"a stone floor that was gritty and unswept"',
  '"a gritty pioneer woman"',
  '"a gritty look at urban life"',
];
export const synonyms = [
  "sandy",
  "grainy",
  "granular",
  "gravelly",
  "pebbly",
  "stony",
  "powdery",
  "dusty",
  "courageous",
  "brave",
  "plucky",
  "mettlesome",
  "stouthearted",
  "lionhearted",
  "valiant",
  "bold",
  "spirited",
  "intrepid",
  "game",
  "hardy",
  "tough",
  "steely",
  "determined",
  "resolute",
  "purposeful",
  "dogged",
  "tenacious",
  "enduring",
  "unfaltering",
  "unswerving",
  "unyielding",
  "unflinching",
  "perseverant",
  "realistic",
  "true to life",
  "unembellished",
  "unvarnished",
  "naked",
  "bare",
  "brutal",
  "harsh",
  "frank",
  "candid",
  "honest",
  "forthright",
  "straightforward",
  "direct",
  "blunt",
  "outspoken",
  "unrealistic",
  "idealized",
];
