export const definitions = [
  '"he would watch Nick grow to manhood"',
  '"the stupidity of grown men hitting a ball with a stick"',
  '"seaweed grows in the ocean"',
  '"more and more land was needed to grow crops for export"',
  '"she grew her hair long"',
  '"turnover grew to more than $100,000 within three years"',
  '"entrepreneurs who are struggling to grow their businesses"',
  '"sharing our experiences we grew braver"',
  '"she grew to like the friendly, quiet people at the farm"',
];
export const synonyms = [
  'fill out',
  'fatten',
  'heighten',
  'lengthen',
  'enlarge',
  'extend',
  'expand',
  'stretch',
  'spread',
  'widen',
  'swell',
  'increase',
  'multiply',
  'snowball',
  'mushroom',
  'balloon',
  'augment',
  'build up',
  'pile up',
  'get bigger',
  'get taller',
  'get larger',
  'increase in size',
  'increase in weight',
  'mount up',
  'shrink',
  'sprout',
  'shoot up',
  'develop',
  'bud',
  'germinate',
  'bloom',
  'emerge',
  'arise',
  'spread',
  'flourish',
  'thrive',
  'run riot',
  'pullulate',
  'vegetate',
  'burgeon',
  'spring up',
  'burst forth',
  'fail',
  'cultivate',
  'produce',
  'propagate',
  'raise',
  'rear',
  'bring on',
  'nurture',
  'tend',
  'farm',
  'plant',
  'sow',
  'fill out',
  'fatten',
  'heighten',
  'lengthen',
  'enlarge',
  'extend',
  'expand',
  'stretch',
  'spread',
  'widen',
  'swell',
  'increase',
  'multiply',
  'snowball',
  'mushroom',
  'balloon',
  'augment',
  'build up',
  'pile up',
  'get bigger',
  'get taller',
  'get larger',
  'increase in size',
  'increase in weight',
  'mount up',
  'shrink',
  'expand',
  'improve',
  'advance',
  'develop',
  'progress',
  'flourish',
  'thrive',
  'burgeon',
  'prosper',
  'succeed',
  'boom',
  'make progress',
  'make headway',
  'be successful',
  'get on well',
  'decline',
  'fail',
  'become',
  'get',
  'turn',
  'come to be',
  'get to be',
  'start to feel',
];