export const definitions = [
  '"she held a grudge against her former boss"',
  '"he grudged the work and time that the meeting involved"',
  '"I don\'t grudge him his moment of triumph"',
];
export const synonyms = [
  "grievance",
  "resentment",
  "bitterness",
  "rancor",
  "pique",
  "umbrage",
  "displeasure",
  "dissatisfaction",
  "disgruntlement",
  "hard feelings",
  "ill will",
  "venom",
  "hate",
  "hatred",
  "dislike",
  "aversion",
  "animosity",
  "antipathy",
  "antagonism",
  "enmity",
  "animus",
  "bad feelings",
  "ill feelings",
  "begrudge",
  "resent",
  "mind",
  "take exception to",
  "regret",
  "feel aggrieved/bitter about",
  "be annoyed about",
  "be angry about",
  "be displeased about",
  "be resentful of",
  "object to",
  "give unwillingly",
  "give reluctantly",
  "give resentfully",
  "give stintingly",
  "envy",
  "begrudge",
  "resent",
  "mind",
  "be jealous of",
  "be envious of",
  "be resentful of",
];
