export const definitions = [
  '"he has a marvelous talent for making the most of downtown locations as well as suburban emptiness and industrial park grunge"',
  '"the album incorporated blues, goth, and of course grunge"',
  '"she\'s a fan of grunge icons Nirvana"',
  '"a mixture of grunge and Parisian chic"',
  '"she rocked more of a grunge look with very short hair"',
];
export const synonyms = [
  "grime",
  "dust",
  "soot",
  "smut",
  "muck",
  "mud",
  "filth",
  "mire",
  "sludge",
  "slime",
  "ooze",
  "dross",
  "scum",
  "pollution",
  "waste",
  "smudges",
  "stains",
];
