export const definitions = [
  '"he was dragging a large object"',
  '"small objects such as shells"',
  '"disease became the object of investigation"',
  '"the Institute was opened with the object of promoting scientific study"',
  '"in Gaelic the word order is verb, subject, object"',
  '"the interface treats most items, including cells, graphs, and buttons, as objects"',
  '"residents object to the volume of traffic"',
  '"the boy\'s father objected that the police had arrested him unlawfully"',
  '"Bryant objects this very circumstance to the authenticity of the Iliad"',
];
export const synonyms = [
  "thing",
  "article",
  "item",
  "piece",
  "device",
  "gadget",
  "entity",
  "body",
  "notion",
  "abstract idea",
  "target",
  "butt",
  "focus",
  "recipient",
  "victim",
  "purpose",
  "objective",
  "aim",
  "goal",
  "target",
  "end",
  "plan",
  "ambition",
  "design",
  "intent",
  "intention",
  "idea",
  "point",
  "end in view",
  "object of the exercise",
  "oppose",
  "take exception (to)",
  "take issue (with)",
  "have a problem (with)",
  "condemn",
  "demur",
  "mind",
  "beg to differ",
  "protest (against)",
  "lodge a protest (against)",
  "raise/express objections (to)",
  "express disapproval (of)",
  "express disagreement (with)",
  "be in opposition (to)",
  "take a stand against",
  "argue (against)",
  "remonstrate (against)",
  "make a fuss (about)",
  "quarrel with",
  "disapprove (of)",
  "draw the line (at)",
  "complain (about)",
  "moan (about)",
  "grumble (about)",
  "grouse (about)",
  "cavil (at)",
  "quibble (about)",
  "approve",
  "accept",
  "acquiesce",
];
