export const definitions = [
  '"he wondered if the doctor was being deliberately obtuse"',
  '"blame lies at the feet of obtuse senior leaders"',
  '"some of the lyrics are a bit obtuse"',
  '"an obtuse angle of 150°"',
  '"it had strange obtuse teeth"',
];
export const synonyms = [
  "stupid",
  "dull",
  "slow-witted",
  "slow",
  "dull-witted",
  "unintelligent",
  "witless",
  "half-baked",
  "halfwitted",
  "doltish",
  "lumpish",
  "blockish",
  "imperceptive",
  "uncomprehending",
  "bovine",
  "stolid",
  "crass",
  "insensitive",
  "thick-skinned",
  "hebete",
  "clever",
  "astute",
  "shrewd",
  "bright",
  "rounded",
  "flat",
  "thick",
  "stubby",
  "stubbed",
  "unpointed",
  "pointed",
];
