export const definitions = [
  '"a coat trimmed with gold braid"',
  '"she wove her hair into a chic braid and coiled it into a bun"',
  '"a flexible copper braid"',
  '"braids of garlic"',
  '"when I was a kid, I loved braiding my hair"',
  '"their garments were braided with silk"',
];
export const synonyms = [
  'cord',
  'cording',
  'braiding',
  'bullion',
  'thread',
  'twine',
  'yarn',
  'tape',
  'binding',
  'rickrack',
  'ribbon',
  'cordon',
  'torsade',
  'galloon',
  'soutache',
  'scrambled egg',
  'plait',
  'pigtail',
  'twist',
  'cornrows',
  'dreadlocks',
  'plait',
  'entwine',
  'intertwine',
  'interweave',
  'interlace',
  'crisscross',
  'weave',
  'knit',
  'lace',
  'twist',
  'twine',
  'wind',
  'interthread',
  'trim',
  'edge',
  'border',
  'pipe',
  'hem',
  'fringe',
  'frill',
  'decorate',
  'adorn',
  'ornament',
  'embellish',
  'embroider',
  'befrill',
];