export const definitions = [
  '"a brave soldier"',
  '"he put up a brave fight before losing"',
  '"it was a time to remember the brave"',
  '"his medals made a brave show"',
];
export const synonyms = [
  "courageous",
  "plucky",
  "fearless",
  "valiant",
  "valorous",
  "intrepid",
  "heroic",
  "lionhearted",
  "manful",
  "macho",
  "bold",
  "daring",
  "daredevil",
  "adventurous",
  "audacious",
  "undaunted",
  "unflinching",
  "unshrinking",
  "unafraid",
  "dauntless",
  "indomitable",
  "doughty",
  "mettlesome",
  "venturesome",
  "stouthearted",
  "stout",
  "spirited",
  "gallant",
  "stalwart",
  "resolute",
  "determined",
  "rock-ribbed",
  "death-or-glory",
  "venturous",
  "cowardly",
  "fearful",
];
