export const definitions = [
  '"he went about his illegal business with a brazen assurance"',
  '"a brazen hussy"',
  '"brazen fire irons"',
  '"the music\'s brazen chords"',
  '"there was nothing to do but brazen it out"',
];
export const synonyms = [
  'bold',
  'shameless',
  'as bold as brass',
  'brazen-faced',
  'forward',
  'presumptuous',
  'brash',
  'immodest',
  'unashamed',
  'unabashed',
  'unembarrassed',
  'unblushing',
  'defiant',
  'impudent',
  'insolent',
  'impertinent',
  'cheeky',
  'pert',
  'barefaced',
  'blatant',
  'flagrant',
  'undisguised',
  'timid',
  'shy',
  'brass',
  'metallic',
  'made of brass',
  'stand one\'s ground',
  'put on a bold front',
  'put a bold face on it',
  'be defiant',
  'be unrepentant',
  'be impenitent',
  'be unashamed',
  'be unabashed',
];