export const definitions = [
  '"tantalizing cooking smells wafted on the evening breeze"',
  '"traveling through London was a breeze"',
  '"I breezed in as if nothing were wrong"',
  '"the computer has the power to breeze through huge documents"',
  '"he breezed to victory"',
];
export const synonyms = [
  "gust",
  "light air",
  "zephyr",
  "cat's paw",
  "gentle wind",
  "breath of wind",
  "puff of air",
  "current of air",
  "flurry of air",
  "child's play",
  "nothing",
  "five-finger exercise",
  "gift",
  "walkover",
  "sinecure",
  "snip",
  "easy task",
  "easy job",
  "saunter",
  "stroll",
  "sail",
  "cruise",
  "glide",
  "drift",
  "float",
  "walk casually",
];
