export const definitions = [
  '"it was a bright, breezy day"',
  '"the text is written in a breezy matter-of-fact manner"',
];
export const synonyms = [
  "windy",
  "fresh",
  "brisk",
  "airy",
  "blowy",
  "blustery",
  "gusty",
  "boisterous",
  "blusterous",
  "windless",
  "still",
  "jaunty",
  "cheerful",
  "cheery",
  "brisk",
  "airy",
  "carefree",
  "free and easy",
  "easy",
  "easygoing",
  "casual",
  "relaxed",
  "informal",
  "lighthearted",
  "lively",
  "spirited",
  "buoyant",
  "sparkling",
  "animated",
  "vivacious",
  "frisky",
  "sprightly",
  "sunny",
  "nonchalant",
  "insouciant",
  "easy-breezy",
  "blithe",
  "blithesome",
  "gay",
  "full of the joys of spring",
  "without a care in the world",
  "serious",
  "lifeless",
];
