export const definitions = [
  '"within five years the company will brew as much beer in China as in Australia"',
  '"the brewing industry"',
  '"I\'ve just brewed some coffee"',
  '"he did a crossword while the tea brewed"',
  '"he insisted on sitting us down and then went to brew up"',
  '"there was more trouble brewing as the airline pilots went on strike"',
  '"a storm was brewing"',
];
export const synonyms = [
  "ferment",
  "make",
  "prepare",
  "infuse",
  "make",
  "mast",
  "stew",
  "be in preparation",
  "develop",
  "loom",
  "impend",
  "gather force",
  "be close",
  "be ominously close",
  "be on the way",
  "be on the horizon",
  "be in the offing",
  "be in the wings",
  "be imminent",
  "be threatening",
  "be impending",
  "be just around the corner",
];
