export const definitions = [
  '"a bridge across the river"',
  '"a railroad bridge"',
  '"a committee that was formed to create a bridge between rival parties"',
  '"Talbot stepped across the two gunwales and made his way up to the bridge"',
  '"he pushed his spectacles further up the bridge of his nose"',
  '"these sunglasses have a special nose bridge for comfort"',
  '"ebony bridges and fingerboards"',
  '"a covered walkway that bridged the gardens"',
  '"earlier attempts to bridge the channel had failed"',
  '"bridging the gap between avant garde art and popular culture"',
  '"she plays bridge once a month with a group of friends"',
  '"Fitzgerald has a passion for bridge"',
  '"a bridge club"',
];
export const synonyms = [
  'viaduct',
  'aqueduct',
  'overpass',
  'flyover',
  'way over',
  'link',
  'connection',
  'bond',
  'tie',
  'means of uniting',
  'span',
  'cross',
  'cross over',
  'go over',
  'pass over',
  'traverse',
  'extend across',
  'reach across',
  'arch over',
  'join',
  'link',
  'connect',
  'unite',
  'straddle',
  'overcome',
  'reconcile',
  'divide',
  'separate',
];
