export const definitions = [
  '"grooms came at once to take the bridles"',
  '"five horses, saddled and bridled, were tied by the reins to branches of trees"',
  '"the fact that he was their servant bridled his tongue"',
  '"ranchers have bridled at excessive federal control"',
];
export const synonyms = [
  "rope",
  "cord",
  "line",
  "guy",
  "wire",
  "chain",
  "hawser",
  "stay",
  "topping lift",
  "choker",
  "piece of cordage",
  "harness",
  "yoke",
  "saddle",
  "couple",
  "hitch up",
  "curb",
  "restrain",
  "hold back",
  "bite back",
  "control",
  "check",
  "keep a tight rein on",
  "govern",
  "master",
  "repress",
  "suppress",
  "subdue",
  "stifle",
  "keep control of",
  "keep in check",
  "rein in/back",
  "bristle",
  "be/become indignant",
  "take offense",
  "take umbrage",
  "be affronted",
  "be offended",
  "get angry",
  "draw oneself up",
  "feel one's hackles rise",
];
