export const definitions = [
  '"he broached the subject he had been avoiding all evening"',
  '"boxed wines will remain in good condition for up to four months once broached"',
  '"the salmon broach, then fall to slap the water"',
  '"we had broached badly, side on to the wind and sea"',
  '"the ship would have broached to if the captain had not sprung to the wheel"',
  '"the helmsman was forced to use the engines in conjunction with the wheel to prevent a broach"',
];
export const synonyms = [
  'bring up',
  'raise',
  'introduce',
  'talk about',
  'mention',
  'touch on',
  'open',
  'enter on',
  'air',
  'ventilate',
  'put forward',
  'propound',
  'propose',
  'suggest',
  'submit',
  'embark on',
  'pierce',
  'puncture',
  'tap',
  'open',
  'uncork',
  'start',
  'begin',
  'pierce',
  'puncture',
  'tap',
  'open',
  'uncork',
  'start',
  'begin',
];