export const definitions = [
  '"he had a broken arm"',
  '"he grew up poor in a broken family"',
  '"unable to survive in this broken household, Michael moved around foster homes"',
  '"he went to his grave a broken man"',
  '"a broken white line across the road"',
  '"a young man talking in broken Italian"',
  '"broken ground"',
  '"the branch broke with a loud snap"',
  '"windows in the street were broken by the blast"',
  '"the slate fell from my hand and broke in two on the hard floor"',
  '"break the chocolate into pieces"',
  '"she had broken her leg in two places"',
  '"what if his leg had broken?"',
  '"the bite had scarcely broken the skin"',
  '"the machine has broken and they can\'t fix it until next week"',
  '"I think I\'ve broken the mechanism in my watch"',
  '"she realized her water had broken"',
  '"she had to break a ten"',
  '"I was acting as referee and telling them to break"',
  '"ciphers are easily broken by the new wonder machines"',
  '"this broke the pattern of generations remaining in the place where they were born"',
  '"his concentration was broken by a sound"',
  '"it was some time before he broke the silence"',
  '"we will break our journey in Venice"',
  '"at mid-morning they broke for coffee"',
  '"she put out an arm to break her fall"',
  '"a multimeter able to measure current without having to break the circuit under test"',
  '"try to break the habit of adding salt at the table"',
  '"the movie broke box-office records"',
  '"the district attorney says she will prosecute retailers who break the law"',
  '"the legally binding contract can only be broken by mutual consent"',
  "\"if I don't go, I'll be breaking my promise\"",
  '"diets started without preparation are broken all the time"',
  '"the idea was to better the prisoners, not to break them"',
  '"her self-control finally broke"',
  '"the management are out to break the union"',
  '"the company has attempted to break the strike using non-union labor"',
  '"the weather broke and thunder rumbled through a leaden sky"',
  '"when all were aboard, the storm broke"',
  '"dawn was just breaking"',
  '"on the seventh of September the clouds broke for the first time"',
  '"the Caribbean sea breaking gently on the shore"',
  '"her voice broke as she relived the experience"',
  '"after his voice broke, he left the choir"',
  '"since the news broke I\'ve received thousands of wonderful letters"',
  '"he was trying to break the terrible news gently to his father"',
  '"the flight broke to the right and formed a defensive circle"',
  '"the ball broke to Craig but his shot rebounded from the post"',
];
export const synonyms = [
  "smashed",
  "shattered",
  "burst",
  "fragmented",
  "splintered",
  "shivered",
  "crushed",
  "snapped",
  "rent",
  "torn",
  "ruptured",
  "separated",
  "severed",
  "destroyed",
  "wrecked",
  "demolished",
  "disintegrated",
  "cracked",
  "split",
  "chipped",
  "fractured",
  "damaged",
  "injured",
  "maimed",
  "in bits",
  "in pieces",
  "whole",
  "unbroken",
  "failed",
  "ended",
  "defeated",
  "beaten",
  "vanquished",
  "overpowered",
  "overwhelmed",
  "subdued",
  "demoralized",
  "dispirited",
  "discouraged",
  "dejected",
  "crushed",
  "humbled",
  "dishonored",
  "ruined",
  "crippled",
  "interrupted",
  "disturbed",
  "fitful",
  "disrupted",
  "disconnected",
  "discontinuous",
  "fragmentary",
  "intermittent",
  "unsettled",
  "sporadic",
  "spasmodic",
  "erratic",
  "troubled",
  "incomplete",
  "uninterrupted",
  "halting",
  "hesitating",
  "disjointed",
  "faltering",
  "stumbling",
  "stammering",
  "stuttering",
  "imperfect",
  "perfect",
  "uneven",
  "rough",
  "irregular",
  "bumpy",
  "jagged",
  "ragged",
  "craggy",
  "rutted",
  "pitted",
  "rutty",
  "flat",
  "smooth",
  "shatter",
  "smash",
  "crack",
  "snap",
  "fracture",
  "fragment",
  "splinter",
  "disintegrate",
  "fall to pieces",
  "split",
  "burst",
  "blow out",
  "tear",
  "rend",
  "sever",
  "rupture",
  "separate",
  "divide",
  "shiver",
  "smash to smithereens",
  "fall to bits",
  "repair",
  "mend",
  "fracture",
  "crack",
  "smash",
  "pierce",
  "puncture",
  "penetrate",
  "perforate",
  "cut",
  "graze",
  "make a flesh wound in",
  "break down",
  "go wrong",
  "give out",
  "malfunction",
  "crash",
  "stop working",
  "cease to work/function",
  "develop a fault",
  "be damaged",
  "be unusable",
  "decipher",
  "decode",
  "decrypt",
  "unravel",
  "solve",
  "work out",
  "interrupt",
  "disturb",
  "interfere with",
  "stop",
  "pause",
  "recess",
  "take/have a break",
  "have a rest",
  "suspend proceedings",
  "resume",
  "cushion",
  "take the edge off",
  "diminish",
  "moderate",
  "mitigate",
  "lessen/reduce/soften the impact of",
  "give up",
  "relinquish",
  "drop",
  "get out of",
  "exceed",
  "surpass",
  "beat",
  "better",
  "cap",
  "top",
  "trump",
  "outdo",
  "outstrip",
  "eclipse",
  "go beyond",
  "put in the shade",
  "contravene",
  "violate",
  "disobey",
  "infringe",
  "breach",
  "defy",
  "flout",
  "fly in the face of",
  "ignore",
  "disregard",
  "infract",
  "fail to comply with",
  "fail to observe",
  "commit a breach of",
  "transgress against",
  "keep",
  "abide by",
  "give way",
  "collapse",
  "crack",
  "give in",
  "cave in",
  "yield",
  "crumple",
  "go to pieces",
  "be overcome",
  "destroy",
  "crush",
  "smash",
  "quash",
  "defeat",
  "vanquish",
  "overcome",
  "overpower",
  "overwhelm",
  "cripple",
  "bring someone to their knees",
  "weaken",
  "enfeeble",
  "sap",
  "suppress",
  "subdue",
  "cow",
  "dispirit",
  "impair",
  "undermine",
  "demoralize",
  "incapacitate",
  "extinguish",
  "change",
  "alter",
  "shift",
  "metamorphose",
  "undergo a change",
  "dawn",
  "begin",
  "start",
  "emerge",
  "appear",
  "come into being",
  "come forth",
  "crash",
  "dash",
  "beat",
  "pound",
  "lash",
  "batter",
  "falter",
  "quaver",
  "quiver",
  "tremble",
  "shake",
  "erupt",
  "break out",
  "burst out",
  "reveal",
  "disclose",
  "divulge",
  "let out",
  "announce",
  "tell",
  "impart",
  "release",
  "proclaim",
  "make public",
  "make known",
];
