export const definitions = [
  '"the centralized lenders operate through brokers"',
  '"fighting continued despite attempts to broker a ceasefire"',
];
export const synonyms = [
  "dealer",
  "broker-dealer",
  "agent",
  "negotiator",
  "trafficker",
  "middleman",
  "intermediary",
  "mediator",
  "factor",
  "trustee",
  "liaison",
  "representative",
  "go-between",
  "stockbroker",
  "interdealer broker",
  "scrivener",
  "insurance broker",
  "arrange",
  "organize",
  "orchestrate",
  "work out",
  "thrash out",
  "hammer out",
  "settle",
  "clinch",
  "contract",
  "pull off",
  "negotiate",
  "mediate",
  "arbitrate",
  "bring off/about",
  "act as go-between",
];
