export const definitions = [
  '"he enameled the back of the case in the rococo style"',
];
export const synonyms = [
  'lacquer',
  'lac',
  'shellac',
  'japan',
  'glaze',
  'polish',
  'oil',
  'resin',
  'wax',
  'varnish',
  'lacquer',
  'veneer',
  'coat',
  'stain',
  'wax',
  'shellac',
  'glaze',
  'gloss',
  'polish',
  'burnish',
  'put a finish on',
  'give a shine to',
  'smooth off',
];