export const definitions = [
  '"it is not difficult to see why Edward is enamored of her"',
  '"she was truly enamored of New York"',
];
export const synonyms = [
  "in love with",
  "infatuated with",
  "besotted with",
  "smitten with",
  "love-struck by",
  "captivated by",
  "charmed by",
  "enchanted by",
  "fascinated by",
  "bewitched by",
  "beguiled by",
  "enthralled by",
  "entranced by",
  "enraptured by",
  "keen on",
  "taken with",
  "head over heels for",
  "under the spell of",
  "consumed with desire for",
  "ensorcelled by",
  "indifferent to",
  "in love with",
  "infatuated with",
  "besotted with",
  "smitten with",
  "love-struck by",
  "captivated by",
  "charmed by",
  "enchanted by",
  "fascinated by",
  "bewitched by",
  "beguiled by",
  "enthralled by",
  "entranced by",
  "enraptured by",
  "keen on",
  "taken with",
  "head over heels for",
  "under the spell of",
  "consumed with desire for",
  "ensorcelled by",
  "indifferent to",
];
