export const definitions = [
  '"the ending of the Cold War"',
  '"a nerve ending"',
  '"the student has to choose the right plural endings"',
  '"when the war ended, policy changed"',
  '"the chapter ends with a case study"',
  '"she wanted to end the relationship"',
  '"the boundary where agnosticism ends and atheism begins"',
  '"he ended by thanking the public for their support"',
  '"one in three marriages is now likely to end in divorce"',
  '"I ended up in Connecticut"',
  '"you could end up with a higher income"',
];
export const synonyms = [
  "end",
  "finish",
  "close",
  "closing",
  "conclusion",
  "resolution",
  "summing-up",
  "denouement",
  "finale",
  "cessation",
  "stopping",
  "termination",
  "discontinuation",
  "final scene",
  "last act",
  "breaking off",
  "beginning",
  "conjugation",
  "declension",
  "form",
  "case",
  "finish",
  "conclude",
  "terminate",
  "come to an end",
  "close",
  "stop",
  "cease",
  "culminate",
  "climax",
  "build up to",
  "lead up to",
  "come to a head",
  "break off",
  "call off",
  "put an end to",
  "halt",
  "drop",
  "discontinue",
  "dissolve",
  "cancel",
  "annul",
  "sunder",
  "destroy",
  "extinguish",
  "do away with",
  "wipe out",
  "take",
  "draw to a close",
  "reach a finale",
  "bring to an end",
  "call a halt to",
  "snuff out",
  "begin",
  "start",
  "finish up",
  "land up",
  "arrive",
  "turn up",
  "come",
  "go",
  "appear",
  "find oneself",
];
