export const definitions = [
  '"changes in the levels of vitamins can affect energy and well-being"',
  '"an alternative is to devote your energies to voluntary work"',
  '"nuclear energy"',
  '"a collision in which no energy is transferred"',
  '"gamma rays at different energies"',
];
export const synonyms = [
  "vitality",
  "vigor",
  "life",
  "liveliness",
  "animation",
  "vivacity",
  "spirit",
  "spiritedness",
  "fire",
  "passion",
  "ardor",
  "zeal",
  "verve",
  "enthusiasm",
  "zest",
  "vibrancy",
  "spark",
  "sparkle",
  "effervescence",
  "exuberance",
  "buoyancy",
  "perkiness",
  "sprightliness",
  "strength",
  "stamina",
  "forcefulness",
  "power",
  "might",
  "potency",
  "dynamism",
  "drive",
  "push",
  "power",
];
