export const definitions = [
  '"he plowed on, trying to outline his plans and engage Sutton\'s attention"',
  '"they attempted to engage Anthony in conversation"',
  '"organizations engage in a variety of activities"',
  '"some are actively engaged in crime"',
  '"the teams needed to engage with local communities"',
  '"he was engaged as a trainee copywriter"',
  '"he engaged to pay them $10,000 against a bond"',
  '"he had engaged a small sailboat"',
  '"the clutch will not engage"',
  '"he engaged the gears and pulled out into the road"',
  '"tank and infantry units engaged the enemy"',
  '"he was determined that his writing and thinking should be engagé"',
];
export const synonyms = [
  "capture",
  "catch",
  "arrest",
  "grab",
  "seize",
  "draw",
  "attract",
  "gain",
  "win",
  "captivate",
  "hold",
  "grip",
  "engross",
  "absorb",
  "occupy",
  "lose",
  "go in for",
  "enter into",
  "undertake",
  "set about",
  "launch into",
  "participate in",
  "take part in",
  "join in",
  "become involved in",
  "partake in/of",
  "occupy oneself with",
  "throw oneself into",
  "share in",
  "play a part in",
  "play a role in",
  "be a participant in",
  "be associated with",
  "have a hand in",
  "be a party to",
  "embark on",
  "employ",
  "hire",
  "recruit",
  "take on",
  "enroll",
  "appoint",
  "commission",
  "enlist",
  "retain",
  "take into employment",
  "secure the services of",
  "put on the payroll",
  "have in employment",
  "have on the payroll",
  "dismiss",
  "contract",
  "promise",
  "agree",
  "pledge",
  "vow",
  "covenant",
  "undertake",
  "commit oneself",
  "bind oneself",
  "enter into an agreement",
  "reach an agreement",
  "negotiate a deal",
  "hire",
  "lease",
  "rent",
  "book",
  "reserve",
  "bespeak",
  "pay for the use of",
  "interlock",
  "interconnect",
  "mesh",
  "intermesh",
  "join",
  "unite",
  "connect",
  "yoke",
  "mate",
  "couple",
  "fit together",
  "join together",
  "disengage",
  "attack",
  "take on",
  "encounter",
  "meet",
  "do battle with",
  "fight with",
  "enter into combat with",
  "wage war on",
  "wage war against",
  "take up arms against",
  "mount an attack on",
  "set upon",
  "clash with",
  "skirmish with",
  "grapple with",
  "wrest with",
  "devout",
  "devoted",
  "loyal",
  "dedicated",
  "faithful",
  "staunch",
  "firm",
  "steadfast",
  "resolute",
  "unwavering",
  "sincere",
  "wholehearted",
  "keen",
  "earnest",
  "enthusiastic",
  "zealous",
  "passionate",
  "ardent",
  "fervent",
  "motivated",
  "driven",
  "active",
  "sworn",
  "pledged",
  "dutiful",
  "hard-working",
  "diligent",
  "studious",
  "assiduous",
  "apathetic",
];
