export const definitions = [
  '"the roar of a car engine"',
  '"engine failure"',
  '"exports used to be the engine of growth"',
  '"a siege engine"',
];
export const synonyms = [
  'motor',
  'mechanism',
  'machine',
  'drive',
  'power source',
  'cause',
  'agent',
  'instrument',
  'driver',
  'originator',
  'initiator',
  'generator',
  'device',
  'contraption',
  'gadget',
  'apparatus',
  'machine',
  'appliance',
  'mechanism',
  'implement',
  'instrument',
  'tool',
  'utensil',
  'aid',
  'invention',
  'contrivance',
  'machinery',
  'means',
];