export const definitions = [
  '"hundreds of thousands of recruits had been enlisted"',
  '"he enlisted in the army"',
  '"the company enlisted the help of independent consultants"',
];
export const synonyms = [
  'join',
  'recruit',
  'call up',
  'enroll',
  'sign up',
  'mobilize',
  'raise',
  'muster',
  'rally',
  'hire',
  'employ',
  'take on',
  'engage',
  'conscript',
  'draft',
  'induct',
  'press',
  'press-gang',
  'levy',
  'list',
  'join up',
  'enroll in',
  'sign up for',
  'volunteer for',
  'take the King\'s shilling',
  'leave',
  'discharge',
  'obtain',
  'engage',
  'win',
  'get',
  'procure',
  'secure',
  'spurn',
];