export const definitions = [
  '"there\'s too much work and not enough people to do it"',
  '"he did just enough studying to pass his exams"',
  '"there will be time enough to tell you when we meet"',
  '"we\'ve got enough problems without that"',
  '"you need to get enough of the right things to eat"',
  '"they ordered more than enough for five people"',
  '"he used to give us a small allowance, just enough to live on"',
  '"I\'ve had enough of this behavior"',
  '"that\'s enough, pack it in "',
  '"Enough! After six years of your arguing, I\'ve had it!"',
  '"at the time, he wasn\'t old enough to vote"',
  '"a house that\'s big enough for your family"',
  '"I can get there easily enough"',
  '"he seems nice enough"',
  '"curiously enough, this is not a new phenomenon"',
];
export const synonyms = [
  'sufficient',
  'adequate',
  'ample',
  'abundant',
  'as much … as necessary',
  'the necessary',
  'insufficient',
  'sufficient',
  'full measure',
  'plenty (of)',
  'a sufficient amount (of)',
  'an adequate amount (of)',
  'as much as necessary',
  'a sufficiency',
  'an adequacy',
  'an ample supply',
  'a satisfactory amount',
  'a passable amount',
  'a tolerable amount',
  'an acceptable amount',
  'an abundance',
  'an amplitude',
  'insufficient',
  'sufficiently',
  'adequately',
  'amply',
  'satisfactorily',
  'passably',
  'tolerably',
  'reasonably',
  'fairly',
  'insufficiently',
];