export const definitions = [
  '"her exposure to museums enriched her life in France"',
  '"cereal enriched with extra oat bran"',
  '"they announced they would resume building the centrifuges that can enrich uranium to weapons-grade strength"',
  '"one may enrich the echinus of a Doric capital with the egg and dart motif"',
  '"top party members had enriched themselves"',
];
export const synonyms = [
  'enhance',
  'improve',
  'add to',
  'augment',
  'supplement',
  'complement',
  'boost',
  'upgrade',
  'reinforce',
  'raise',
  'lift',
  'refine',
  'polish',
  'heighten',
  'deepen',
  'elevate',
  'aggrandize',
  'intensify',
  'exalt',
  'fertilize',
  'compost',
  'dung',
  'manure',
  'mulch',
  'dress',
  'make richer',
  'make more nutritious',
  'vitaminize',
  'add fertilizer to',
  'make more fertile',
  'spoil',
  'devalue',
  'impoverish',
];