export const definitions = [
  '"the client must ensure that accurate records be kept"',
  '"she would ensure him a place in society"',
  '"only by researching stocks thoroughly can a client ensure against being misled"',
];
export const synonyms = [
  "make sure",
  "make certain",
  "secure",
  "guarantee",
  "warrant",
  "certify",
  "set the seal on",
  "clinch",
  "confirm",
  "check",
  "verify",
  "corroborate",
  "establish",
  "see to it",
  "safeguard",
  "protect",
  "guard",
  "shield",
  "shelter",
  "fortify",
  "assure",
  "secure",
  "look after",
  "take care of",
  "make invulnerable",
  "make safe",
  "watch over",
];
