export const definitions = [
  '"Church and empire were fused in a single entity"',
  '"entity and nonentity"',
];
export const synonyms = [
  "organization",
  "institution",
  "establishment",
  "body",
  "operation",
  "structure",
  "system",
  "unit",
  "whole",
  "existence",
  "being",
  "life",
  "living",
  "animation",
  "vital force",
  "substance",
  "essence",
  "reality",
  "actuality",
  "quintessence",
  "quiddity",
  "esse",
  "animateness",
  "essential nature",
  "nonentity",
  "nonexistence",
];
