export const definitions = [
  '"she was entrapped by family expectations"',
  '"he argued that his client had been entrapped by an undercover police officer"',
];
export const synonyms = [
  'trap',
  'snare',
  'ensnare',
  'entangle',
  'enmesh',
  'catch',
  'capture',
  'net',
  'bag',
  'hook',
  'land',
  'release',
  'entice',
  'lure',
  'tempt',
  'inveigle',
  'bait',
  'decoy',
  'trap',
  'lead on',
  'seduce',
  'trick',
  'deceive',
  'dupe',
  'gull',
  'hoodwink',
  'delude',
  'lay a trap for',
];