export const definitions = [
  '"Stasia wiggled her toes"',
  '"my tooth was wiggling around"',
  '"they\'re trying to wiggle out of their agreement"',
  '"a slight wiggle of the hips"',
  '"a wiggle on a chart"',
];
export const synonyms = [
  "jiggle",
  "wriggle",
  "twitch",
  "flutter",
  "shimmy",
  "joggle",
  "wag",
  "wobble",
  "shake",
  "twist",
  "squirm",
  "writhe",
  "wave",
  "quiver",
  "jerk",
  "bobble",
];
