export const definitions = [
  '"the earliest winged insects"',
  '"those eyeglasses with the winged frames were very popular"',
  '"a bird came winging around the corner"',
  '"the prize will be winging its way to you soon"',
  '"just jot down the title on a postcard and wing it to us"',
  '"the convent was at some distance, but fear would wing her steps"',
  '"one bird was winged for every bird killed"',
  '"a little boning up puts you ahead of the job seekers who try to wing it"',
];
export const synonyms = [
  "fly",
  "glide",
  "soar",
  "take wing",
  "hurtle",
  "speed",
  "shoot",
  "whiz",
  "zoom",
  "streak",
  "sweep",
  "fly",
  "race",
  "sail",
  "wound",
  "graze",
  "hit",
  "clip",
  "improvise",
  "extemporize",
  "ad lib",
  "play it by ear",
];
