export const definitions = [
  '"a combine cuts, threshes, and winnows the grain in one operation"',
  '"women winnow the chaff from piles of unhusked rice"',
  '"guidelines that would help winnow out those not fit to be soldiers"',
  '"the contenders had been winnowed to five"',
  '"amidst this welter of confusing signals, it\'s difficult to winnow out the truth"',
  '"the autumn wind winnowing its way through the grass"',
  '"the emperors of the sky winnowing the air"',
];
export const synonyms = [
  "separate",
  "divide",
  "sort out",
  "remove",
  "get rid of",
  "isolate",
  "sort out",
  "find",
  "identify",
  "separate the wheat from the chaff",
  "separate out",
  "sift out",
  "filter out",
  "ferret out",
];
