export const definitions = [
  '"the groan and clank of a winch"',
  '"I could hear the chain clanking"',
  '"Cassie bounced on the bed, clanking the springs"',
];
export const synonyms = [
  "jangling",
  "clanging",
  "rattling",
  "clinking",
  "jingling",
  "clunking",
  "clattering",
  "clang",
  "jangle",
  "rattle",
  "clangor",
  "clink",
  "jingle",
  "clunk",
  "clatter",
  "jangle",
  "rattle",
  "clink",
  "clang",
  "jingle",
  "clunk",
  "clatter",
];
