export const definitions = [
  '"the large axe his father used to cleave wood for the fire"',
  '"the egg cleaves to form a mulberry-shaped cluster of cells"',
  '"they watched a coot cleave the smooth water"',
  '"an unstoppable warrior clove through their ranks"',
  '"Stan was off, cleaving a path through the traffic"',
  '"Rose\'s mouth was dry, her tongue cleaving to the roof of her mouth"',
  '"part of why we cleave to sports is that excellence is so measurable"',
  '"it was his choice to cleave to the Brownings"',
];
export const synonyms = [
  "split",
  "divide",
  "sever",
  "splinter",
  "cut (up)",
  "hew",
  "hack",
  "halve",
  "bisect",
  "quarter",
  "rend",
  "sunder",
  "rive",
  "split open",
  "crack open",
  "lay open",
  "chop up",
  "slice up",
  "plow",
  "drive",
  "bulldoze",
  "cut",
  "carve",
  "make",
  "stick to",
  "stick fast to",
  "be stuck to",
  "adhere to",
  "cohere to",
  "be attached to",
  "bond to",
  "hold to",
  "stand by",
  "adhere to",
  "cling to",
  "abide by",
  "be loyal to",
  "be faithful to",
  "remain true to",
  "hold to",
  "stand by",
  "adhere to",
  "cling to",
  "abide by",
  "be loyal to",
  "be faithful to",
  "remain true to",
];
