export const definitions = [
  '"the climax of her speech"',
  '"a thrilling climax to the game"',
  '"a mixed hardwood climax forest"',
  '"the day climaxed with a gala concert"',
  '"the sentencing climaxed a seven-month trial"',
];
export const synonyms = [
  "peak",
  "pinnacle",
  "height",
  "high point",
  "summit",
  "top",
  "acme",
  "zenith",
  "apex",
  "apogee",
  "apotheosis",
  "culmination",
  "crown",
  "crest",
  "crescendo",
  "finale",
  "denouement",
  "highlight",
  "high spot",
  "high water mark",
  "highest point",
  "crowning point",
  "best part",
  "nadir",
  "anticlimax",
  "orgasm",
  "ejaculation",
  "sexual climax",
  "culminate",
  "peak",
  "result",
  "end",
  "come to a head",
  "come to a climax",
  "reach a pinnacle",
  "come to a crescendo",
  "ejaculate",
  "die",
  "have an orgasm",
  "reach/achieve orgasm",
];
