export const definitions = [
  '"the current economic crisis"',
  '"he goes to pieces in a crisis"',
  '"a family in crisis"',
  '"when the crisis came, she does not appear to have hesitated"',
  '"a crisis point of history"',
];
export const synonyms = [
  "catastrophe",
  "calamity",
  "cataclysm",
  "emergency",
  "disaster",
  "predicament",
  "plight",
  "mess",
  "dilemma",
  "quandary",
  "setback",
  "reverse",
  "reversal",
  "upheaval",
  "drama",
  "trouble",
  "hardship",
  "adversity",
  "extremity",
  "distress",
  "difficulty",
  "dire straits",
  "hard times",
  "critical point",
  "turning point",
  "crossroads",
  "critical period",
  "crux",
  "climax",
  "climacteric",
  "culmination",
  "height",
  "head",
  "moment of truth",
  "zero hour",
  "Rubicon",
  "decisive point",
  "point of no return",
];
