export const definitions = [
  '"rooms with ______ doors lined the hallway"',
  '"he sat with his eyes ______"',
  '"the perception of the Soviet Union as a ______ society had changed"',
  '"a ______ squash tournament"',
  '"the UN Security Council met in ______ session"',
  '"you\'re facing the situation with a ______ mind"',
  'he put the "______" sign up in the window',
  '"Detroit has several ______ down factories"',
  '"Stephen ______ his ears to the sound"',
  '"Loretta ______ her mouth, but not to listen"',
  '"Ron ______ the book"',
  '"my fist ______ around the weapon"',
  '"spoke with a spy via a ______ circuit radio"',
  '"the members were thanked for attending and the meeting was ______"',
  '"the concert ______ with "Silent Night""',
  '"he ______ a deal with a metal dealer"',
  '"the soda shop doors ______ permanently"',
  '"______ out the register"',
  '"The experiment required a ______ circuit of wires and batteries"',
  '"salesman ______ a deal quickly"',
];
export const synonyms = [
  "watertight",
  "waterproof",
  "water-resistant",
  "water-repellent",
  "airtight",
  "tight",
  "sealed",
  "impenetrable",
  "impregnable",
  "inviolable",
  "resistant",
  "damp-proof",
  "hermetically sealed",
  "imperviable",
  "permeable",
  "select",
  "chic",
  "high-class",
  "elite",
  "fashionable",
  "stylish",
  "elegant",
  "choice",
  "special",
  "premier",
  "expensive",
  "restrictive",
  "restricted",
  "limited",
  "private",
  "cliquish",
  "cliquey",
  "clannish",
  "snobbish",
  "upmarket",
  "high-toned",
  "upscale",
  "discriminative",
  "grade A",
  "open",
  "unaffected by",
  "untouched by",
  "immune to",
  "invulnerable to",
  "insusceptible to",
  "not susceptible to",
  "proof against",
  "unreceptive to",
  "resistant to",
  "indifferent to",
  "heedless of",
  "unresponsive to",
  "oblivious to",
  "unmoved by",
  "deaf to",
  "receptive to",
  "susceptible to",
  "shut",
  "slam",
  "fasten",
  "secure",
  "lock",
  "bolt",
  "bar",
  "latch",
  "padlock",
  "draw to",
  "pull to",
  "push to",
  "put up the shutter",
  "open",
  "unlock",
  "stop up",
  "plug",
  "cork",
  "stopper",
  "fill (up)",
  "pack",
  "stuff",
  "choke",
  "obstruct",
  "occlude",
  "stopple",
  "block (up/off)",
  "seal (up/off)",
  "shut up/off",
  "bung (up)",
  "make airtight",
  "make watertight",
  "clog (up)",
  "open",
  "unblock",
  "join",
  "connect",
  "unite",
  "come together",
  "come into contact",
  "form a circle",
  "end",
  "conclude",
  "finish",
  "terminate",
  "wind up",
  "break off",
  "halt",
  "discontinue",
  "dissolve",
  "adjourn",
  "suspend",
  "prorogue",
  "recess",
  "bring/come to an end",
  "call a halt to",
  "open",
  "begin",
  "end",
  "conclude",
  "finish",
  "terminate",
  "wind up",
  "break off",
  "halt",
  "discontinue",
  "dissolve",
  "adjourn",
  "suspend",
  "prorogue",
  "recess",
  "bring/come to an end",
  "call a halt to",
  "open",
  "begin",
  "clinch",
  "settle",
  "secure",
  "seal",
  "set the seal on",
  "confirm",
  "guarantee",
  "establish",
  "transact",
  "pull off",
  "complete",
  "conclude",
  "fix",
  "agree",
  "finalize",
  "bring off/about",
  "shake hands on",
  "shut down",
  "close down",
  "fail",
  "collapse",
  "crash",
  "go under",
  "cease activity",
  "cease production",
  "cease operating",
  "come to a halt",
  "cease trading",
  "go out of business",
  "go bankrupt",
  "become insolvent",
  "go into receivership",
  "go into liquidation",
  "be liquidated",
  "be wound up",
  "be shut (down)",
  "open",
  "catch up",
  "creep up",
  "near",
  "approach",
  "narrow",
  "lessen",
  "dwindle",
  "diminish",
  "reduce",
  "shrink",
  "contract",
  "constrict",
  "straiten",
  "gain on someone",
  "draw nearer/near",
  "get nearer/near",
  "come nearer/near",
  "draw closer/close",
  "get closer/close",
  "come closer/close",
  "grow/become/make smaller",
  "get/become/make narrower",
  "widen",
];
