export const definitions = [
  '"he has a closet full of designer suits"',
  '"his brother\'s decision to come out of the closet"',
  '"she tries to have a relationship with another woman while remaining in the closet"',
  '"a closet alcoholic"',
  '"he was closeted with the king"',
  '"he returned home and closeted himself in his room"',
];
export const synonyms = [
  'cupboard',
  'wardrobe',
  'cabinet',
  'locker',
  'cubicle',
  'storage room',
  'lavatory',
  'bathroom',
  'facilities',
  'urinal',
  'privy',
  'latrine',
  'outhouse',
  'WC',
  'water closet',
  'cloakroom',
  'the Ladies',
  'the Gents',
  'powder room',
  'earth closet',
  'restroom',
  'washroom',
  'men\'s room',
  'ladies\' room',
  'comfort station',
  'comfort room',
  'pissoir',
  'head',
  'jakes',
  'garderobe',
  'public convenience',
  'necessary house',
  'secret',
  'covert',
  'unrevealed',
  'undisclosed',
  'private',
  'hidden',
  'concealed',
  'surreptitious',
  'clandestine',
  'underground',
  'furtive',
  'out',
  'open',
  'shut away',
  'sequester',
  'seclude',
  'cloister',
  'insulate',
  'confine',
  'isolate',
];