export const definitions = [
  '"he stripped off his clothes"',
  '"baby clothes"',
  '"a clothes shop"',
  '"Rosie got into bed and pulled the clothes up to her nose"',
  '"Francesca was clothed in white"',
  '"luxuriant tropical forests clothed the islands"',
  '"they already had eight children to feed and clothe"',
  '"you have been clothed with power from on high"',
];
export const synonyms = [
  "clothing",
  "garments",
  "attire",
  "garb",
  "dress",
  "wear",
  "wardrobe",
  "outfit",
  "costume",
  "turnout",
  "finery",
  "apparel",
  "raiment",
  "habiliments",
  "habit",
  "vestments",
  "articles of clothing/dress",
  "dress",
  "attire",
  "outfit",
  "array",
  "rig (out)",
  "turn out",
  "fit out",
  "costume",
  "robe",
  "garb",
  "drape",
  "accoutre",
  "bedizen",
  "caparison",
  "apparel",
  "habit",
  "invest",
  "cover",
  "overlay",
  "overspread",
  "cloak",
  "blanket",
  "carpet",
  "envelop",
  "swathe",
  "swaddle",
  "shroud",
  "wrap",
  "surround",
  "enshroud",
  "trick out/up",
  "deck out",
  "put clothes on",
  "trap out",
  "undress",
  "uncover",
  "provide",
  "furnish",
  "endow",
  "serve",
  "confer",
  "equip",
  "rig out",
  "outfit",
  "fit",
  "arm",
  "endue",
  "kit out",
];
