export const definitions = [
  '"next morning was ______"',
  '"the pond water is slightly ______"',
  '"______ reds and blues and greens"',
  '"she stared at him, her eyes ______"',
  '"the issue becomes more ______"',
];
export const synonyms = [
  "overcast",
  "clouded",
  "overclouded",
  "dark",
  "darkened",
  "gray",
  "black",
  "leaden",
  "dull",
  "murky",
  "somber",
  "dismal",
  "dreary",
  "cheerless",
  "heavy",
  "gloomy",
  "dim",
  "louring",
  "sunless",
  "starless",
  "hazy",
  "misty",
  "foggy",
  "threatening",
  "menacing",
  "clouded over",
  "promising rain",
  "claggy",
  "bright",
  "murky",
  "muddy",
  "milky",
  "dirty",
  "clouded",
  "dull",
  "opaque",
  "nontransparent",
  "emulsified",
  "opalescent",
  "turbid",
  "riled",
  "roily",
  "roiled",
  "clear",
  "tearful",
  "teary",
  "weepy",
  "weeping",
  "lachrymose",
  "moist",
  "misty",
  "watery",
  "rheumy",
  "blurred",
  "blurry",
  "unfocused",
  "dry",
  "vague",
  "blurred",
  "fuzzy",
  "indistinct",
  "imprecise",
  "foggy",
  "hazy",
  "confused",
  "muddled",
  "indefinite",
  "nebulous",
  "obscure",
  "unformed",
  "lacking definition",
  "clear",
  "focused",
];
