export const definitions = [
  '"the sun had disappeared behind a cloud"',
  '"the full moon, hidden by veils of cloud"',
  '"a cloud of dust"',
  '"clouds of orange butterflies"',
  '"a black cloud hung over their lives"',
  '"the only cloud to appear on the horizon was Leopold\'s unexpected illness"',
  "\"a cloud passed over Jess's 's face\"",
  '"once you are logged in to your cloud storage space, you can upload files to it and share them with others"',
  '"$13 per month gets you 25GB of storage in the cloud"',
  '"the blue skies clouded over abruptly"',
  '"the western sky was still clouded"',
  '"blood pumped out, clouding the water"',
  '"her eyes clouded with tears"',
  '"don\'t allow your personal feelings to cloud your judgment"',
  '"the general election was clouded by violence"',
  '"his expression clouded over"',
  '"suspicion clouded her face"',
];
export const synonyms = [
  "mass",
  "billow",
  "pall",
  "shroud",
  "mantle",
  "blanket",
  "layer",
  "sheet",
  "curtain",
  "canopy",
  "swarm",
  "flock",
  "flight",
  "hive",
  "covey",
  "drove",
  "herd",
  "mass",
  "multitude",
  "host",
  "horde",
  "throng",
  "crowd",
  "threat",
  "menace",
  "shadow",
  "specter",
  "blight",
  "gloom",
  "darkness",
  "chill",
  "pall",
  "trouble",
  "problem",
  "worry",
  "lour",
  "blacken",
  "darken",
  "dim",
  "become cloudy",
  "cloud over",
  "become overcast",
  "become gloomy",
  "grow dim",
  "clear",
  "dirty",
  "darken",
  "blacken",
  "roil",
  "rile",
  "make cloudy",
  "make murky",
  "clear",
  "confuse",
  "muddle",
  "obscure",
  "fog",
  "befog",
  "muddy",
  "blur",
  "make unclear",
  "clarify",
  "ruin",
  "wreck",
  "destroy",
  "upset",
  "undo",
  "mess up",
  "make a mess of",
  "dash",
  "sabotage",
  "scupper",
  "scotch",
  "torpedo",
  "blast",
  "vitiate",
  "cast a shadow over",
  "darken",
  "take the shine off",
  "put a damper on",
  "take the edge off",
  "cook someone's goose",
  "bring to naught",
  "cast a pall over",
  "take the enjoyment/pleasure out of",
  "upset someone's apple cart",
  "further",
  "help",
  "enhance",
];
