export const definitions = [
  '"he stood clutching a microphone"',
  '"Mrs. Longhill clutched at the idea"',
  '"doctors could clutch up and lose control as easily as anyone"',
  '"she made a clutch at his body"',
  '"she escaped the clutches of her temperamental family"',
  '"she let the clutch in and the car surged forward"',
  '"they both are hard-nosed players who seem to thrive in clutch situations"',
  '"a clutch quarterback"',
  '"clutch free-throw shooting"',
  '"they lay fewer than ten eggs in a clutch"',
  '"the number of chicks in a clutch varies according to the availability of food and the danger of predators"',
  '"a clutch of young girls on roller skates"',
];
export const synonyms = [
  'grip',
  'grasp',
  'clasp',
  'clench',
  'hold',
  'grab',
  'seize',
  'lay (one\'s) hands on',
  'get one\'s hands on',
  'cling to',
  'hang onto',
  'reach for',
  'snatch at',
  'make a grab for',
  'catch at',
  'claw at',
  'grab/seize/take hold of',
  'power',
  'control',
  'domination',
  'command',
  'mastery',
  'rule',
  'tyranny',
  'hands',
  'hold',
  'grip',
  'grasp',
  'claws',
  'jaws',
  'custody',
  'possession',
  'keeping',
  'evil embrace',
  'group',
  'batch',
  'nestful',
  'group',
  'collection',
  'set',
  'quantity',
  'raft',
  'handful',
  'fistful',
  'armful',
];