export const definitions = [
  '"God sent an angel to talk to Gideon"',
  '"the Angel of Death"',
  '"Ella, ever the angel of mercy, organized the children into baking cookies"',
  '"there was an angel watching over me"',
  '"I know I\'m no angel"',
  '"their parents think they are angels"',
  '"you sang like an angel"',
  '"be an angel and let us come in"',
  '"I miss you too, angel"',
  '"the longer it takes you to get your product into the marketplace, the longer it will be until the angels get their money back"',
  '"every year we raise the money for the next season and we are always looking for an angel"',
  '"we rendezvous at angels nine"',
];
export const synonyms = [
  "spirit",
  "messenger of God",
  "divine/heavenly messenger",
  "divine being",
  "devil",
  "seraph",
  "saint",
  "gem",
  "treasure",
  "nonpareil",
  "darling",
  "dear",
  "paragon of virtue",
  "paragon",
  "gem",
  "nonpareil",
  "find",
  "prize",
  "treasure",
  "saint",
  "paragon",
  "marvel",
  "find",
  "godsend",
  "darling",
  "dear",
  "nonesuch",
  "someone/something worth their weight in gold",
  "beloved",
  "dear",
  "dearest",
  "darling",
  "sweetheart",
  "sweet",
  "honey",
  "lover",
  "boyfriend",
  "girlfriend",
  "significant other",
  "betrothed",
  "paramour",
  "inamorata",
  "inamorato",
  "querida",
  "loved one",
  "love of one's life",
  "dear one",
  "sweet one",
  "backer",
  "sponsor",
  "supporter",
  "benefactor",
  "subsidizer",
  "promoter",
  "patron",
  "guarantor",
  "underwriter",
  "Maecenas",
];
