export const definitions = [
  '"the author\'s animus toward her"',
  '"the reformist animus came from within the Party"',
];
export const synonyms = [
  "hostility",
  "animosity",
  "antagonism",
  "friction",
  "antipathy",
  "opposition",
  "dissension",
  "rivalry",
  "feud",
  "conflict",
  "discord",
  "contention",
  "acrimony",
  "bitterness",
  "rancor",
  "resentment",
  "aversion",
  "dislike",
  "ill feeling",
  "ill will",
  "bad blood",
  "hatred",
  "hate",
  "loathing",
  "detestation",
  "abhorrence",
  "odium",
  "malice",
  "spite",
  "spitefulness",
  "venom",
  "malevolence",
  "malignity",
  "grudges",
  "grievances",
  "bad feeling",
  "friendship",
  "goodwill",
];
