export const definitions = [
  '"he knocked and entered without waiting for an ______"',
  '"write your ______ on a postcard"',
  '"the ______ is 280°"',
  '"the ______ to poverty and unemployment is a properly funded range of services"',
  '"the press called her Britain\'s ______ to Marilyn Monroe"',
  '""Of course I can," she ______ed"',
  '"she ______ed that she would take nothing but the ring"',
  '"she tried to ______ his questions truthfully"',
  '"Steve was about to ______, but Hazel spoke first"',
  '"I didn\'t ______ him"',
  '"______ the questions below for a chance to win a vacation"',
  '"David ______ed the door"',
  '"she called Edward\'s house, hoping he would ______"',
  '"he said he would return to Spain to ______ all charges"',
  '"entrepreneurship is necessary to ______ the needs of national and international markets"',
  '"nothing short of that would ______"',
];
export const synonyms = [
  "reply",
  "response",
  "rejoinder",
  "return",
  "reaction",
  "acknowledgment",
  "retort",
  "riposte",
  "question",
  "query",
  "solution",
  "explanation",
  "resolution",
  "key",
  "solution",
  "remedy",
  "way out",
  "way of solving the problem",
  "counterpart",
  "parallel",
  "alternative",
  "match",
  "complement",
  "analog",
  "double",
  "twin",
  "opposite number",
  "equal",
  "peer",
  "rival",
  "coequal",
  "reply",
  "respond",
  "rejoin",
  "retort",
  "come back",
  "acknowledge",
  "write back",
  "riposte",
  "speak/say in response",
  "make a rejoinder",
  "fling back",
  "hurl back",
  "rebut",
  "refute",
  "defend oneself against",
  "satisfy",
  "meet",
  "fulfill",
  "fill",
  "serve",
  "suit",
  "measure up to",
  "match up to",
  "fit/fill the bill",
];
