export const definitions = ['"the antics of our political parties"'];
export const synonyms = [
  "capers",
  "pranks",
  "larks",
  "escapades",
  "high jinks",
  "skylarking",
  "stunts",
  "tricks",
  "horseplay",
  "romps",
  "frolics",
  "silliness",
  "tomfoolery",
  "foolery",
  "clowning",
  "buffoonery",
  "harlequinades",
  "amusing behavior",
  "foolish behavior",
];
